lib: nrf_modem: increase minimum NRF_MODEM_LIB_SHMEM_TX_SIZE
nrfconnect/sdk-nrf pull request #10038
Opened 2023-01-24 09:52 UTC by eivindj-nordic

With modem firmware 1.3.4 the minimum NRF_MODEM_LIB_SHMEM_TX_SIZE is increased.

Signed-off-by: Eivind Jølsgard <eivind.jolsgard@nordicsemi.no>

2023-01-24 09:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10038/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10038/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10038/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-24 09:58 UTC, lemrey requested changes

2023-01-24 09:58 UTC, lemrey commented on doc/nrf/releases/release-notes-changelog.rst
> +    * The minimal value for ``CONFIG_NRF_MODEM_LIB_SHMEM_TX_SIZE`` has been updated to meet the requirements for modem firmware 1.3.4.
You mean `RX` ?

2023-01-24 10:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10038
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-24 11:15 UTC, eivindj-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +    * The minimal value for ``CONFIG_NRF_MODEM_LIB_SHMEM_TX_SIZE`` has been updated to meet the requirements for modem firmware 1.3.4.
Thanks, updated.

2023-01-24 11:25 UTC, lemrey approved these changes

2023-01-24 12:13 UTC, divipillai approved these changes

2023-01-24 12:13 UTC, divipillai commented on doc/nrf/releases/release-notes-changelog.rst
> +    * The minimal value for ``CONFIG_NRF_MODEM_LIB_SHMEM_RX_SIZE`` has been updated to meet the requirements for modem firmware 1.3.4.
```suggestion
* :ref:`nrf_modem_lib_readme` library:

  * Updated:

    * The minimal value of :kconfig:option:`CONFIG_NRF_MODEM_LIB_SHMEM_RX_SIZE` to meet the requirements of modem firmware 1.3.4.
```

2023-01-24 13:11 UTC, divipillai approved these changes

2023-02-02 14:07 UTC, MirkoCovizzi approved these changes

2023-02-02 14:19 UTC, merged