drivers: wifi: twt tx fix
nrfconnect/sdk-nrf pull request #10094
Opened 2023-01-30 03:50 UTC by ajayparida

[SHEL-1179] Fix for twt tx issue.

Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>

2023-01-30 03:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10094/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10094/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10094/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-30 08:39 UTC, krish2718 requested changes
Can you please add the fix details to the commit log? It is not clear as to what we are trying to fix.
Also, please avoid unnecessary whitespace changes?

2023-01-30 08:39 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
> -
unnecessary whitespace

2023-01-30 08:39 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_twt.c
> +		/*for (ac = WIFI_NRF_FMAC_AC_VO; ac >= 0; --ac) {*/
Remove commented code

2023-01-30 09:50 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
> +	int tx_cmd_cnt;
This can be a separate commit

2023-01-31 12:32 UTC, sachinthegreen requested changes

2023-02-01 05:55 UTC, ajayparida commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +			}
yes, it is aligned as per the statement

2023-02-01 11:48 UTC, closed without merging