net: lwm2m_client_utils: Firmaware utils update
nrfconnect/sdk-nrf pull request #10104
Opened 2023-01-30 13:49 UTC by jheiskan81

Added support for server read client supported protocol's for Firmware update Pull-mode.

Client enable by default COAP & HTTPS.
COAPS and HTPPS are only enabled when Modem have configured LWM2M_CLIENT_UTILS_DOWNLOADER_SEC_TAG.

Workaround for Standard Object 5 for update resource instance if there is less space than 4.

Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>

2023-01-30 13:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10104/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10104/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10104/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-30 15:38 UTC, rlubos reviewed
Looks good but please fix the compliance.

2023-01-31 07:44 UTC, VeijoPesonen requested changes
Just one minor naming thing.

2023-01-31 07:44 UTC, VeijoPesonen commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
> +		lwm2m_firware_object_pull_protol_int(instance_id);
```suggestion
		lwm2m_firmware_object_pull_protocol_int(instance_id);
```

2023-01-31 07:58 UTC, jheiskan81 commented
@VeijoPesonen and @rlubos Thanks for comment I fix issues.

2023-01-31 08:06 UTC, VeijoPesonen approved these changes

2023-01-31 10:03 UTC, rlubos approved these changes

2023-01-31 10:48 UTC, jheiskan81 commented
I will verify that COAPS and HTPPS works currently I fail to connect by error 111. Need to investigate that my certificate is correct

2023-01-31 11:21 UTC, jheiskan81 commented
I verified PULL operation with HTTPS and certificate sec tag type need to be CA. I put original back. PULL operation was tested with Coiote server certificate  ISRG Root X1.

2023-01-31 13:21 UTC, jheiskan81 commented
Tested COAPS also. COAPS with AVSystem need's to add AVSystem Self-signed CA and Device Own certificate. Now functionality is OK when client sec_tags are configured like Server request.

2023-01-31 13:54 UTC, SeppoTakalo approved these changes

2023-01-31 14:16 UTC, jheiskan81 commented
Fixed Typo from commit message title

2023-01-31 15:16 UTC, merged