Twt tx
nrfconnect/sdk-nrf pull request #10122
Opened 2023-02-01 13:10 UTC by ajayparida

Changes for twt tx issue. 
After TWT block event it is possible that firmware still sending tx_done events. Host will no more send pkts as RPU is in sleep state.It will just clear the descriptor if it is not done yet. 
On un-block event host will try to send pkts from pending pkts if the desciptor and pkts are available. Host will no more maintanis "last_tx_done_desc" variable depending upon which tx was being attempted.

2023-02-02 08:58 UTC, sachinthegreen requested changes

2023-02-02 08:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_twt.c
> +		for (ac = 1; ac <= WIFI_NRF_FMAC_AC_MAX; ++ac) {
Use macro instead of 1 here.

2023-02-02 08:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
> + * @twt_sleep_status: current RPU sleep status.
Use capital letter for first word of a sentence. In this case Current instead of current.

2023-02-02 08:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +				/* Spare Token Case*/
Space before */

2023-02-02 08:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +					/*Adjust the counters*/
Spaces after /* and before */

2023-02-02 08:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
> +	bool twt_sleep_status;
Use enum instead of bool to enhance code readability. E.g. enum twt_state where values can be TWT_STATE_ASLEEP, TWT_STATE_AWAKE.

2023-02-14 09:58 UTC, krish2718 requested changes
The grouping of changes to commits is wrong, please recheck.

2023-02-14 11:04 UTC, ajayparida commented
> The grouping of changes to commits is wrong, please recheck.
I have segregated the commits to different parts. Please check.

2023-02-14 12:23 UTC, sachinthegreen approved these changes

2023-02-15 06:12 UTC, krish2718 approved these changes

2023-02-15 07:45 UTC, merged

2025-02-20 00:23 UTC, Yedfree approved these changes