bluetooth: controller: Fix unexpected low TX power with FEM connected
nrfconnect/sdk-nrf pull request #10143
Opened 2023-02-02 15:33 UTC by rugeGerritsen

Solved by setting the default radio output power when enabling Bluetooth. That is, after the FEM is initialized.

Previously the initial default radio output power would be selected as if there was no FEM connected. For example 6 dBm.
Then, when packets are to be transmitted, we would recalculate how much power we would need on the outputting device. That is, 6 dBm minus the FEM gain.

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

2023-02-03 07:23 UTC, jciupis commented
I'd suggest to rephrase the commit message to better reflect the issue being fixed.

```
Previously the initial default output power would be selected as if there was no FEM connected.
For example, suppose that the application requested 20dBm power at the antenna. Even though
such power could be achievable using the configured front-end module, that power would first
be converted to the maximum output power supported by the SoC, which usually is much lower.
Then, when the device transmitted frames, this decreased power would be treated as the requested
power and divided between the radio and the external PA.

This commit fixes that by setting the default radio output power when enabling Bluetooth,
when the FEM driver is already initialized. This way the controller takes FEM into account in its
initial output power calculation.
```

2023-02-03 07:25 UTC, jciupis reviewed
We probably need to mention the issue in known issues and the fix in release notes changelog.

2023-02-03 08:12 UTC, jciupis approved these changes

2023-02-03 08:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10143
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-03 09:49 UTC, weeTike commented on doc/nrf/known_issues.rst
> +DRGN-18568: Lower radio output power when :kconfig:option:`BT_CTLR_TX_PWR_ANTENNA` and :kconfig:option:`MPSL_FEM` is used.
This also applies to CONFIG_BT_CTLR_TX_PWR so maybe this statement should be generalized a bit. Something like "when setting a default TX power and :kconfig:option:`MPSL_FEM` is used.". Or both kconfigs could be mentioned.

2023-02-06 13:58 UTC, weeTike approved these changes

2023-02-06 16:58 UTC, annakielar requested changes

2023-02-06 19:18 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +DRGN-18568: Lower radio output power when setting default radio output power when :kconfig:option:`MPSL_FEM` is used.
Thanks. Corrected it

2023-02-06 19:18 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +  For this configuration the output power is lower than expected when :kconfig:option:`BT_CTLR_TX_PWR_ANTENNA` or :kconfig:option:`CONFIG_BT_CTLR_TX_PWR` is used.
Updated as suggested

2023-02-07 08:07 UTC, annakielar approved these changes

2023-02-07 11:02 UTC, ryanjh approved these changes

2023-02-07 13:03 UTC, merged