doc: updated documentation for the lwM2M carrier library
nrfconnect/sdk-nrf pull request #10141
Opened 2023-02-02 14:26 UTC by nordic-hani

Added some fixes and clarifications to the LwM2M carrier library usage.

Signed-off-by: Vermeer <havard.vermeer@nordicsemi.no>

2023-02-02 15:05 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/index.rst
> +   It is *mandatory* to include the LwM2M carrier library in any Verizon certified product.
Shouldn't we also mention that it is optional to include the library in any AT&T and T-Mobile certified product?

2023-02-02 15:35 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10141
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-03 08:19 UTC, umapraseeda requested changes

2023-02-03 08:19 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/index.rst
> +For more information, see the list of `applicable carriers <Mobile network operator certifications_>`_, and the ref:`lwm2m_certification` subpage.
```suggestion
For more information, see the list of `applicable carriers <Mobile network operator certifications_>`_, and the :ref:`lwm2m_certification` subpage.
```

2023-02-03 08:19 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/index.rst
> +In addition to this stand-alone sample, the following applications and samples include an overlay file to easily integrate the LwM2M carrier library.
```suggestion
In addition to this stand-alone sample, the following applications and samples include an overlay file to easily integrate the LwM2M carrier library:
```

2023-02-03 08:19 UTC, umapraseeda commented on samples/nrf9160/lwm2m_carrier/sample_description.rst
> +   #. Finally, as described in ref:`lwm2m_carrier_shell` we must set ``auto_startup`` (or else the sample will wait indefinetly for us to configure all the settings).
:ref:\`lwm2m_carrier_shell\`

2023-02-16 14:00 UTC, umapraseeda approved these changes

2023-02-16 15:04 UTC, divipillai approved these changes

2023-02-17 07:37 UTC, peknis requested changes

2023-02-17 07:37 UTC, peknis commented on samples/nrf9160/lwm2m_carrier/sample_description.rst
> +   #. Finally, as described in ref:`lwm2m_carrier_shell`, we must set ``auto_startup`` (or else the sample will wait indefinitely for you to configure all the settings).
```suggestion
   #. Finally, as described in ref:`lwm2m_carrier_shell`, set ``auto_startup`` (or else the sample will wait indefinitely for you to configure all the settings).
```

2023-02-17 08:00 UTC, peknis approved these changes

2023-02-17 08:43 UTC, merged