manifest: pull Matter Wi-Fi connection recovery mechanism
nrfconnect/sdk-nrf pull request #10151
Opened 2023-02-03 14:18 UTC by markaj-nordic

This change adds an implementation of Wi-Fi connection recovery which retries to scan networks in case the requested SSID is not present at the moment.

Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>

2023-02-03 14:19 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/6105af8af0c381de167882a19adec7772d3b998b (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/203 | [nrfconnect/sdk-connectedhomeip#203/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/203/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-02-03 14:31 UTC, LuDuda approved these changes

2023-02-03 14:31 UTC, LuDuda commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Wi-Fi connection retries mechanism
```suggestion
  * Wi-Fi connection retries mechanism.
```

2023-02-03 14:32 UTC, wiba-nordic requested changes

2023-02-03 14:32 UTC, wiba-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Wi-Fi connection retries mechanism
```suggestion
  * Mechanism to retry a failed Wi-Fi connection.
```
I _think_ that's a correct statement.

2023-02-03 14:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10151
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-03 17:25 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10151/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10151/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10151/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-04 16:34 UTC, LuDuda approved these changes

2023-02-06 05:53 UTC, wiba-nordic approved these changes

2023-02-06 06:48 UTC, kkasperczyk-no approved these changes

2023-02-06 07:51 UTC, merged