samples: bluetooth: Remove 3w Bluetoth coex example
nrfconnect/sdk-nrf pull request #10164
Opened 2023-02-06 13:12 UTC by jostn

The Bluetooth 3w COEX implementation is being removed

Signed-off-by: Johan Stridkvist <johan.stridkvist@nordicsemi.no>

2023-02-06 14:12 UTC, rugeGerritsen requested changes
Please update the commit message to 
```
Bluetooth: Remove 3w Bluetooth coex

The Bluetooth 3w COEX implementation is being removed.
```
This commit removes more than just the sample

2023-02-07 13:24 UTC, rugeGerritsen approved these changes

2023-02-16 09:38 UTC, shantha-14 commented
removed 2.3.0 milestone as approvals were missing and CI was failing

2023-02-17 07:54 UTC, martintv approved these changes

2023-02-17 08:01 UTC, wiba-nordic approved these changes
Looks good.

2023-02-17 09:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10164/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10164/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10164/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-06 12:04 UTC, merged