Add wifi provisioning BLE service
nrfconnect/sdk-nrf pull request #10178
Opened 2023-02-07 09:24 UTC by wentong-li

Extract common part from wifi provisioning sample, and form it as a BLE service.

DNM until #10108 get merged.

2023-02-14 09:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10178/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10178/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10178/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-14 11:39 UTC, alwa-nordic approved these changes

2023-02-15 03:46 UTC, wentong-li commented
Hi @richabp . The doc is reorganized as follows:

`readme.rst`: previously it is a navigation page containing two subpages. Now it holds the contents of `sample_description.rst` and no longer has subpage. **Now it is for the sample.**
`sample_description.rst`: removed
`implementaion_details.rst`: it is moved to doc/nrf/libraries/bluetooth_services/services, and renamed as `wifi_prov.rst`. **It is for the service.**

Hope my explanation can help.

2023-02-15 09:44 UTC, kittydepa requested changes

2023-02-15 09:44 UTC, kittydepa commented on doc/nrf/libraries/bluetooth_services/services/wifi_prov.rst
> +This module implements of an Bluetooth GATT service for Wi-Fi provisioning.
```suggestion
This module implements a Bluetooth® GATT service for Wi-Fi® provisioning.
```

2023-02-15 09:44 UTC, kittydepa commented on doc/nrf/libraries/bluetooth_services/services/wifi_prov.rst
> +* GATT service inerface: Defines GATT service and provide an interface for configurator to exchange messages.
```suggestion
* GATT service inerface: Defines GATT service and provides an interface for the configurator to exchange messages.
```

2023-02-15 10:39 UTC, richabp requested changes
Please add an entry for the updated Provisioning sample in the change log.

2023-02-15 10:39 UTC, richabp commented on doc/nrf/libraries/bluetooth_services/services/wifi_prov.rst
> +It uses the :ref:`lib_wifi_credentials` to handle the configurations in flash.
```suggestion
It uses the :ref:`lib_wifi_credentials` library to handle the configurations in flash.
```

2023-02-15 10:39 UTC, richabp commented on doc/nrf/libraries/bluetooth_services/services/wifi_prov.rst
> +It uses the :ref:`lib_wifi_credentials` to handle the configurations in flash.
```suggestion
It uses the :ref:`lib_wifi_credentials` library to handle the configurations in flash.
```

2023-02-15 10:51 UTC, kittydepa reviewed
Added one article, within Richa's suggested edit.

2023-02-16 01:58 UTC, wentong-li commented on samples/wifi/provisioning/README.rst
> +Kconfig options
I will add a section called "configuration" to list all kconfig options we provide, and explain their functions

2023-02-16 06:51 UTC, bama-nordic approved these changes
LGTM

2023-02-16 09:21 UTC, kittydepa requested changes
Two small changes, to remove trademark symbols since they have already been used in the first instance.

2023-02-16 09:21 UTC, kittydepa commented on samples/wifi/provisioning/README.rst
> +With this sample, you can provision a Wi-Fi® device that lacks input or output capability using the :ref:`wifi_prov_readme` library.
```suggestion
With this sample, you can provision a Wi-Fi device that lacks input or output capability using the :ref:`wifi_prov_readme` library.
```

2023-02-16 09:21 UTC, kittydepa commented on samples/wifi/provisioning/README.rst
> +* Transport layer: Based on Bluetooth® Low Energy and exchanges information between the device and the nRF Wi-Fi Provisioner app.
```suggestion
* Transport layer: Based on Bluetooth Low Energy and exchanges information between the device and the nRF Wi-Fi Provisioner app.
```

2023-02-16 09:34 UTC, kittydepa approved these changes

2023-02-16 09:35 UTC, richabp approved these changes

2023-02-16 09:35 UTC, merged