Bluetooth: Mesh: Time mod srv/cli coex check
nrfconnect/sdk-nrf pull request #10181
Opened 2023-02-07 11:13 UTC by Andrewpini

Add check in time client model to prevent that a single element contains both a Time Server and a Time Client. Both these models share a common time status message. If a element contains both these models it will cause undefined behaviour when handling incoming time status messages.

Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

2023-02-07 11:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10181/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10181/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10181/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-07 11:17 UTC, ludvigsj commented
Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.

2023-02-07 11:19 UTC, PavelVPV approved these changes

2023-02-07 11:23 UTC, Andrewpini commented
> Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.

Interesting. I can take a look at it

2023-02-07 11:28 UTC, alxelax approved these changes

2023-02-07 11:30 UTC, ludvigsj requested changes
See comment above

2023-02-07 11:37 UTC, PavelVPV commented
> Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.

The idea is good, but this will brake some our tests that use imposter models with the same message id on the same element.

2023-02-07 11:42 UTC, Andrewpini commented
> > Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.
> 
> The idea is good, but this will brake some our tests that use imposter models with the same message id on the same element.

This is a fair point. The scope of such approach is much wider than the fix applied here. Would it not be better to just identify the models that have the simmilar issue and fix it in the same way then? If we want to go with the generic solution I don't want to do it now, but rather create a task in the backlog.

2023-02-07 11:49 UTC, ludvigsj commented
> > > Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.
> > 
> > 
> > The idea is good, but this will brake some our tests that use imposter models with the same message id on the same element.
> 
> This is a fair point. The scope of such approach is much wider than the fix applied here. Would it not be better to just identify the models that have the simmilar issue and fix it in the same way then? If we want to go with the generic solution I don't want to do it now, but rather create a task in the backlog. Cause I think finding fixes for the tests that exploits this could be time consuming.

Sure, it can be it's own backlog item. But keep in mind that users can implement models themselves, including extensions to spec models. We will have no way of avoiding collisions between them other than by fixing this at the access layer, so any other "solution" would be only a half-solution in my opinion.

2023-02-07 11:49 UTC, PavelVPV commented
> > > Isn't it better to have a generic functionality in the access layer itself which checks that you don't register the same opcode twice on an element? This (time srv + time cli) is not the only combination affected by this, for instance I can think of sensor client and LC server which also share a status message.
> > 
> > 
> > The idea is good, but this will brake some our tests that use imposter models with the same message id on the same element.
> 
> This is a fair point. The scope of such approach is much wider than the fix applied here. Would it not be better to just identify the models that have the simmilar issue and fix it in the same way then? If we want to go with the generic solution I don't want to do it now, but rather create a task in the backlog.

I'm fine with fixing this later. This check could also be converted to a Kconfig option (debug option) which you enable once to ensure that composition data is correct. Not sure how practical it is, but for me sounds similar to, for example, toggling off the assert macro.

2023-02-07 11:51 UTC, PavelVPV commented
> Sure, it can be it's own backlog item. But keep in mind that users can implement models themselves, including extensions to spec models. We will have no way of avoiding collisions between them other than by fixing this at the access layer, so any other "solution" would be only a half-solution in my opinion.

Composition data is a static thing. So you will probably notice that model doesn't work immediately when testing. Finding root cause will take some time though.

2023-02-07 13:39 UTC, Andrewpini commented
Kconfig option sounds like a good approach. I'll create a task for it, and close this PR.

2023-02-15 12:55 UTC, ludvigsj approved these changes

2023-02-15 13:02 UTC, merged