doc: app_event_manager: Improve event flags documentation
nrfconnect/sdk-nrf pull request #10222
Opened 2023-02-09 16:03 UTC by zycz

Add flags description and modify documentation example,
 so that logging is enabled by default.

Jira: NCSDK-19607

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2023-02-09 16:05 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10222/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10222/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10222/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-10 10:00 UTC, MarekPieta requested changes

2023-02-10 11:17 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +   For example, you can provide a function that logs using event manager macro a string version of the event data (used for logging).
```suggestion
   For example, you can provide a function that logs a string version of the event data (used for logging) by using the event manager macro.
```

2023-02-10 11:17 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +   To not set any flag, use :c:macro:`APP_EVENT_FLAGS_CREATE` without any argument.
```suggestion
   To not set any flag, use the :c:macro:`APP_EVENT_FLAGS_CREATE` macro without any argument.
```

2023-02-10 11:17 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +   To enable logging from the application start use :c:enum:`APP_EVENT_TYPE_FLAGS_INIT_LOG_ENABLE` as shown in the below example.
```suggestion
   To enable logging from the application start, use the :c:enum:`APP_EVENT_TYPE_FLAGS_INIT_LOG_ENABLE` enum as shown in the following example.
```

2023-02-10 11:17 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +For subscribing to an event type, the Application Event Manager provides four types of subscriptions, differing in priority.
```suggestion
The Application Event Manager provides four types of events subscriptions, differing in priority.
```

2023-02-10 11:17 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +For subscribing to an event type, the Application Event Manager provides four types of subscriptions, differing in priority.
please double-check if the meaning remains unchanged

2023-02-10 11:32 UTC, MarekPieta requested changes

2023-02-10 11:32 UTC, MarekPieta commented on doc/nrf/libraries/others/app_event_manager.rst
> +   For example, you can provide a function that logs using event manager macro a string version of the event data (used for logging).
`For example, you can provide a function that logs a string version of the event data using :c:macro:`APP_EVENT_MANAGER_LOG` macro`

2023-02-10 11:32 UTC, MarekPieta commented on include/app_event_manager.h
> + *Flag description:
` *Flag description:` -> This seems actually not needed

2023-02-10 11:32 UTC, MarekPieta commented on include/app_event_manager.h
> +	 *  APP_EVENT_TYPE_FLAGS_HAS_DYNDATA indicates that event type has dyndata data field.
`has dyndata field` / `has variable data size`

2023-02-10 11:32 UTC, MarekPieta commented on include/app_event_manager.h
> +	 * APP_EVENT_TYPE_FLAGS_INIT_LOG_ENABLE enables event logging from the application start.
In generated doc, this sentence is placed right below the enum value definition, so I think there is no need to duplicate the option name

2023-02-10 11:32 UTC, MarekPieta commented on include/app_event_manager.h
> +	/** APP_EVENT_TYPE_FLAGS_SYSTEM_START marks beginning of system flags.*/
`.. of flags controlled internally by Application Event Manager`?

2023-02-10 13:26 UTC, annwoj approved these changes

2023-02-10 13:26 UTC, annwoj commented on doc/nrf/libraries/others/app_event_manager.rst
> +   For example, you can provide a function that logs a string version of the event data (used for logging) by using :c:macro:APP_EVENT_MANAGER_LOG macro.
```suggestion
   For example, you can provide a function that logs a string version of the event data (used for logging) by using the :c:macro:APP_EVENT_MANAGER_LOG macro.
```

2023-02-10 15:29 UTC, MarekPieta approved these changes

2023-02-10 15:29 UTC, MarekPieta commented on doc/nrf/libraries/others/app_event_manager.rst
> +   For example, you can provide a function that logs a string version of the event data (used for logging) by using the :c:macro:APP_EVENT_MANAGER_LOG macro.
is `(used for logging)` part still needed?

2023-02-13 08:53 UTC, merged