samples: bluetooth: Fix building HIDS Mouse with security disabled.
nrfconnect/sdk-nrf pull request #10251
Opened 2023-02-13 12:03 UTC by grochu

The example was not building when the Kconfig option: CONFIG_BT_HIDS_SECURITY_ENABLED is disabled.

2023-02-13 12:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10251/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10251/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10251/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-27 10:49 UTC, KAGA164 approved these changes
LGTM. Please add also test case with security disabled in the sample.yaml file

2023-02-27 11:15 UTC, maje-emb approved these changes

2023-02-27 11:46 UTC, annakielar requested changes

2023-02-27 11:46 UTC, annakielar commented on doc/nrf/known_issues.rst
> +  Build fails when the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` is disabled.
```suggestion
  Build fails when the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` Kconfig option is disabled.
```

2023-02-27 11:46 UTC, annakielar commented on doc/nrf/known_issues.rst
> +  **Workaround:** Build the sample with default configuration: enable the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` option.
```suggestion
  **Workaround:** Build the sample with its default configuration, that is, enable the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` Kconfig option.
```

2023-02-27 11:46 UTC, annakielar commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed building the sample with the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` option disabled.
```suggestion
  * Fixed building the sample with the :kconfig:option:`BT_HIDS_SECURITY_ENABLED` Kconfig option disabled.
```

2023-02-27 11:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10251
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-27 12:25 UTC, annakielar approved these changes

2023-02-27 13:47 UTC, merged