manifest: Update sdk-nrf-802154 and nrfxlib revisions
nrfconnect/sdk-nrf pull request #10275
Opened 2023-02-14 14:07 UTC by ahasztag

This PR updates sdk-nrf-802154 and nrfxlib revisions to bring in
the latest changes in the nrf_802154 component.

Signed-off-by: Artur Hadasz <artur.hadasz@nordicsemi.no>

2023-02-14 14:08 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrf-802154 | [nrfconnect/sdk-nrf-802154@v2.2.0](https://github.com/nrfconnect/sdk-nrf-802154/releases/tag/v2.2.0) | https://github.com/nrfconnect/sdk-nrf-802154/commit/2079d8bd247176af6d9324da242fb97d48bfa617 (main) | [nrfconnect/sdk-nrf-802154@v2.2.0..2079d8bd](https://github.com/nrfconnect/sdk-nrf-802154/compare/v2.2.0..2079d8bd247176af6d9324da242fb97d48bfa617) |
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/f8eeb71cc37c6622e7b26a16a68d031ab1364159 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/912 | [nrfconnect/sdk-nrfxlib#912/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/912/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-02-14 14:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10275/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10275/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10275/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-14 15:20 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10275
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-15 06:44 UTC, ankuns requested changes

2023-02-15 06:44 UTC, ankuns commented on west.yml
> +      revision: 7f5cb04aa26937d61995d91c0439b70f35e14186
bad sha, see my comment https://github.com/nrfconnect/sdk-nrfxlib/pull/912#pullrequestreview-1298887651

2023-02-15 07:33 UTC, ahasztag commented on west.yml
> +      revision: 7f5cb04aa26937d61995d91c0439b70f35e14186
Fixed

2023-02-15 07:38 UTC, ankuns approved these changes

2023-02-15 11:29 UTC, merged