Nrf7 x 26
nrfconnect/sdk-nrf pull request #10313
Opened 2023-02-16 10:09 UTC by vivinordic

Set maximum payload length to 4000 bytes for legacy frames. 
Set maximum payload length to 2300 bytes for DSSS frames. 

Update sample_description.rst file to reflect this change in documentation.

2023-02-16 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=10313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=10313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=10313) it.</sub>

2023-02-16 10:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10313/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10313/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10313/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-16 10:59 UTC, srkanordic commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +			(ctx->conf_params.tx_pkt_rate == 5) ||
Set payload length to 4000 for all legacy rates.

2023-02-16 11:14 UTC, sachinthegreen requested changes

2023-02-16 11:14 UTC, sachinthegreen commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +			(ctx->conf_params.tx_pkt_rate == 5) ||
Alignment seems to be missing here.

2023-02-16 11:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10313
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-16 12:14 UTC, srkanordic approved these changes

2023-02-17 06:28 UTC, sachinthegreen approved these changes

2023-02-17 06:35 UTC, baduNordic approved these changes

2023-02-17 07:30 UTC, bama-nordic approved these changes

2023-02-17 09:43 UTC, richabp reviewed
Is changelog entry required for this?

2023-02-17 10:37 UTC, merged