doc: fast_pair: Update the documentation
nrfconnect/sdk-nrf pull request #10312
Opened 2023-02-16 10:03 UTC by alstrzebonski

Updates the Fast Pair documentation to reflect the current progress.

Jira: NCSDK-19617

2023-02-16 10:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10312/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10312/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-02-16 10:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10312
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-16 10:43 UTC, mkapala-nordic approved these changes

2023-02-16 11:31 UTC, divipillai approved these changes

2023-02-16 11:43 UTC, MarekPieta approved these changes

2023-02-16 11:43 UTC, MarekPieta commented on doc/nrf/external_comp/bt_fast_pair.rst
> +   The implementation passes Fast Pair Validator tests.
I think you should mention that you used beta version of the Validator (non-beta would not work)

2023-02-16 11:44 UTC, MarekPieta requested changes
Please inform about the beta version of Fast Pair Validator

2023-02-17 08:54 UTC, alstrzebonski commented
One slight change - please rereview.

2023-02-17 08:58 UTC, MarekPieta approved these changes

2023-02-17 09:13 UTC, divipillai approved these changes

2023-02-17 09:13 UTC, divipillai commented on doc/nrf/external_comp/bt_fast_pair.rst
> +   The implementation passes Fast Pair Validator (Beta version) tests.
```suggestion
   The implementation passes Fast Pair Validator (beta version) tests.
```

2023-02-17 09:52 UTC, merged