doc improvment: wi-fi: minor sample and feature improvements
nrfconnect/sdk-nrf pull request #10348
Opened 2023-02-17 14:30 UTC by kittydepa

doc improvment: for Wi-Fi samples and features page

Signed-off-by: Katherine Depa <katherine.depa@nordicsemi.no>

2023-02-17 14:36 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10348/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10348/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-02-17 15:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10348
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-20 07:22 UTC, muraliThokala approved these changes

2023-02-20 10:40 UTC, bama-nordic requested changes

2023-02-20 10:40 UTC, bama-nordic commented on samples/wifi/radio_test/sample_description.rst
> +         * To run a continuous Orthogonal frequency-division multiplexing (OFDM) TX traffic sequence use the following configuration:
I think "with" is the correct word here. "use" gives a wrong meaning - the tests have to be run "with" the below parameters. This comment is relevant for all such changed

2023-02-20 11:16 UTC, richabp requested changes

2023-02-20 12:48 UTC, richabp approved these changes

2023-02-20 14:19 UTC, bama-nordic approved these changes

2023-02-21 06:53 UTC, sachinthegreen approved these changes

2023-02-21 08:55 UTC, D-Triveni approved these changes

2023-02-21 12:29 UTC, merged