samples: wifi: Update command output and help
nrfconnect/sdk-nrf pull request #10346
Opened 2023-02-17 14:03 UTC by ajayparida

[SHEL-1208] Update help text to provide information for ps_mode and reg_domain commands in wifi shell

2023-02-17 14:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10346/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10346/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-02-17 14:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10346
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-21 06:56 UTC, sachinthegreen requested changes

2023-02-21 06:56 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +   * - reg_domian
reg_domain*

2023-02-21 06:56 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +     - Configure Wi-Fi power save mode legacy/wmm
Can't we list the values for legacy and wmm? Also wmm should be WMM.
e.g.
- | Configure Wi-Fi power save mode
  | 0 - Legacy
  | 1 - WMM

2023-02-21 06:56 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +     - | Set or Get Wi-Fi regulatory domain
get*

2023-02-21 08:50 UTC, richabp requested changes

2023-02-21 08:50 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | 1 - WMM
```suggestion
   * - ps_mode
     - | Configure Wi-Fi power save mode
       | 0 - Legacy
       | 1 - WMM
```

2023-02-21 08:50 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | own risk.
```suggestion
       | (Note that this may cause regulatory compliance issues.)
```

2023-02-21 09:37 UTC, kittydepa approved these changes

2023-02-21 12:50 UTC, sachinthegreen approved these changes

2023-02-21 12:53 UTC, merged