samples: mmss: Increase at monitor heap size
nrfconnect/sdk-nrf pull request #10351
Opened 2023-02-17 22:53 UTC by glarsennordic

Before this commit, MMSS randomly becomes inoperable due to the at monitor heap being overrun. This commit increases the heap size to the minimum power of two that prevents the issue from happening

2023-02-17 22:56 UTC, plskeggs approved these changes

2023-02-17 22:57 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10351/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10351/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10351/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-17 22:57 UTC, jayteemo approved these changes

2023-02-17 22:57 UTC, jayteemo commented on samples/nrf9160/nrf_cloud_mqtt_multi_service/prj.conf
> +# AT monitor heap size needs to be tuned for each application orsample.
```suggestion
# AT monitor heap size should be tuned for each application.
```

2023-02-18 00:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10351
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-20 08:40 UTC, peknis requested changes

2023-02-20 08:40 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Increased at monitor heap to prevent occasional overruns
```suggestion
    * Increased AT monitor heap to prevent occasional overruns
```

2023-02-21 01:16 UTC, glarsennordic commented
It is looking as though this might not actually solve the issue that underlies whatever is going wrong with the at_monitor heap.

However, in case I am wrong about that, I have gone ahead and applied your changes anyways @peknis that way we can merge quickly as we figure out what is going on

I am adding DNM, though, so that the PR is not accidentally merged before we know for sure what the issue is

2023-02-21 07:50 UTC, peknis approved these changes

2023-02-22 02:28 UTC, glarsennordic commented
Closing, obsoleted by https://github.com/nrfconnect/sdk-nrf/pull/10399

2023-02-22 02:28 UTC, closed without merging