applications: nrf_desktop: Miscellaneous documentation improvements
nrfconnect/sdk-nrf pull request #10350
Opened 2023-02-17 16:00 UTC by MarekPieta

Change introduces documentation improvements for the NCS 2.3 release.

Jira: NCSDK-19128

2023-02-17 16:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10350/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10350/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-02-17 16:35 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10350
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-20 09:27 UTC, divipillai reviewed
Some minor suggestions.

2023-02-20 09:27 UTC, divipillai commented on applications/nrf_desktop/README.rst
> +The :ref:`CONFIG_DESKTOP_SETTINGS_LOADER <config_desktop_app_options>` and :ref:`CONFIG_DESKTOP_POWER_MANAGER <config_desktop_app_options>` are implied to enable respectively :ref:`nrf_desktop_settin
```suggestion
The :ref:`CONFIG_DESKTOP_SETTINGS_LOADER <config_desktop_app_options>` and :ref:`CONFIG_DESKTOP_POWER_MANAGER <config_desktop_app_options>` are implied to enable the :ref:`nrf_desktop_settings_loader` and :ref:`nrf_desktop_power_manager` modules, respectively.
```

2023-02-20 09:27 UTC, divipillai commented on applications/nrf_desktop/README.rst
> +#. By default nRF Desktop device enables Bluetooth connectivity support.
```suggestion
#. By default, the nRF Desktop device enables Bluetooth connectivity support.
```

2023-02-20 09:27 UTC, divipillai commented on doc/nrf/getting_started/modifying.rst
> +For example :file:`child_image/mcuboot/prj_release.conf` can be used to define ``release`` build type for ``mcuboot`` child image.
```suggestion
For example, :file:`child_image/mcuboot/prj_release.conf` can be used to define ``release`` build type for ``mcuboot`` child image.
```

2023-02-20 09:55 UTC, MarekPieta commented
Hi @divipillai
I applied review comments and added a small note related to menuconfig configuration and Kconfig defaults (I think it could help to avoid confusion). Please rereview

2023-02-20 10:15 UTC, divipillai commented on applications/nrf_desktop/README.rst
> +   See the section ``Stuck symbols in menuconfig and guiconfig`` on the :ref:`kconfig_tips_and_tricks` in the Zephyr documentation for details.
```suggestion
   Changing configuration in menuconfig does not automatically adjust user-configurable values to the new defaults. So, you must update those values manually.
   For more information, see the Stuck symbols in menuconfig and guiconfig section on the :ref:`kconfig_tips_and_tricks` in the Zephyr documentation.
```

2023-02-20 10:15 UTC, divipillai commented on applications/nrf_desktop/README.rst
> +   The default Kconfig option values are automatically updated if configuration change is applied directly in the configuration files.
```suggestion
   The default Kconfig option values are automatically updated if configuration changes are applied directly in the configuration files.
```

2023-02-20 12:27 UTC, divipillai approved these changes

2023-02-20 13:21 UTC, mkapala-nordic requested changes
Beside one typo - lgtm

2023-02-20 13:21 UTC, mkapala-nordic commented on applications/nrf_desktop/README.rst
> +Zerphyr support for a board
Zephyr

2023-02-20 13:41 UTC, mkapala-nordic approved these changes

2023-02-20 17:32 UTC, b-gent approved these changes

2023-02-21 11:18 UTC, merged