docs: at_host heap overrun known issue
nrfconnect/sdk-nrf pull request #10399
Opened 2023-02-22 02:27 UTC by glarsennordic

Add an item to known_issues.rst describing the at_host heap overrun that has, thus far, only been observed with MMSS

2023-02-22 02:30 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10399/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10399/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-02-22 03:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10399
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-22 09:45 UTC, peknis requested changes

2023-02-22 09:45 UTC, peknis commented on doc/nrf/known_issues.rst
> +NCSDK-19858: :ref:`at_monitor_readme` library / :ref:`nrf_cloud_mqtt_multi_service` sample heap overrun.
```suggestion
NCSDK-19858: :ref:`at_monitor_readme` library and :ref:`nrf_cloud_mqtt_multi_service` sample heap overrun.
```

2023-02-22 09:45 UTC, peknis commented on doc/nrf/known_issues.rst
> +
Is there a workaround?

2023-02-22 18:03 UTC, glarsennordic commented on doc/nrf/known_issues.rst
> +
Not that I have yet found

2023-02-23 07:13 UTC, peknis approved these changes

2023-02-23 07:16 UTC, greg-fer approved these changes

2023-02-23 07:19 UTC, greg-fer commented
@plskeggs , @jayteemo , @glarsennordic , to reduce the number of PRs we're dealing with before the release, this has been merged just before RC-2. If you have any edits or concerns about phrasing, please add a comment in the general known issues PR that will stay open almost til the release tag: https://github.com/nrfconnect/sdk-nrf/pull/10362

2023-02-23 07:27 UTC, merged