net: lib: lwm2m_client_utils: Add support for connection pre-evaluation
nrfconnect/sdk-nrf pull request #10520
Opened 2023-03-07 11:54 UTC by juhaylinen

Connection pre-evaluation estimates the LTE radio signal state and energy efficiency in a cell that the modem would use for data transmission. Application can use the information to decide when to start the data transmission.
If estimated energy usage is too high the application pauses the lwm2m client and waits for better signal state.
User can set evaluation period in milliseconds and maximum time in seconds to pause the transmission.

2023-03-07 11:58 UTC, juhaylinen commented
This PR needs to wait for Zephyr upmerge to pass CI tests.

2023-03-07 12:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10520
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-08 15:14 UTC, rlubos commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	bool "Enable connection pre-evaluation"
Please add `[EXPERIMENTAL]` suffix to the option description.

2023-03-08 15:14 UTC, rlubos commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +config LWM2M_CLIENT_UTILS_CONNEVAL
I wonder if this option/API should include `LTE` keyword, like `LTE_CONNEVAL`. With other networking technologies on the table now, current name might be too generic.

2023-03-15 10:58 UTC, juhaylinen commented
Refactored the code as discussed offline with @SeppoTakalo 

- Removed own work queue implementation and use delayed work instead.
- Use asynchronous AT command for connection pre-evaluation when evaluation is done multiple times. LTE link controller API may block too long for system work queue.

2023-03-16 12:25 UTC, VeijoPesonen requested changes
Nothing major, generally looks good to me.

2023-03-16 12:25 UTC, VeijoPesonen commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_conneval.c
> +static uint64_t poll_period;
```suggestion
static uint64_t poll_period; /* [ms] */
```

2023-03-20 08:01 UTC, VeijoPesonen approved these changes
Looks good to me

2023-03-21 07:55 UTC, VeijoPesonen approved these changes

2023-03-28 06:46 UTC, divipillai approved these changes

2023-04-13 08:36 UTC, SeppoTakalo approved these changes

2023-04-14 06:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10520/8/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10520/8/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10520/8/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-19 10:38 UTC, rlubos approved these changes

2023-04-19 10:39 UTC, merged