driver: wifi: Utility command to get rpu power save state
nrfconnect/sdk-nrf pull request #10569
Opened 2023-03-10 09:35 UTC by ajayparida

[SHEL-1351] Utility command to get the current rpu power save state.

2023-03-14 14:06 UTC, sachinthegreen requested changes

2023-03-14 14:06 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +	SHELL_CMD_ARG(rpu_state,
Call the command `sleep_state` instead of `rpu_state`

2023-03-14 14:06 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +		      "rpu_state = %s\n", rpu_ps_state ? "AWAKE" : "SLEEP");
The print can be more user friendly, as in: `"Sleep state = %s\n", rpu_ps_state ? "AWAKE" : "SLEEP"`

2023-03-23 12:50 UTC, sachinthegreen requested changes

2023-03-23 12:50 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/os_if/inc/osal_structs.h
> +
Move this to a FW shared header file (rpu_if.h?) rather than a osal header file.

2023-03-24 11:42 UTC, sachinthegreen approved these changes

2023-03-30 07:17 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +enum wifi_nrf_rpu_ps_state wifi_nrf_fmac_get_rpu_ps_state(void *dev_ctx)
The naming is misleading, this is not a `current` PS state of RPU, this is just host's perspective, RPU could still be dozing or checking beacon. So, we should name it appropriately.

2023-03-30 09:59 UTC, krish2718 requested changes
I would drop host_ref and instead rename this to `host_rpu_ps_ctrl` (including the variable `rpu_ps_state`) this is not a status that we get from RPU, this is the control of RPU sleep by host driver based on inactivity.

2023-03-30 09:59 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/hw_if/hal/inc/fw/rpu_if.h
> +enum wifi_nrf_host_ref_rpu_ps_state {
Why is this in `rpu_if.h` this is just local to host and we already have `enum RPU_PS_STATE` (this should be prefixed with WIFI_NRF).

2023-04-04 12:24 UTC, rado17 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +			      "Programming tx_rate failed\n");
Incorrect log message.

2023-04-04 12:46 UTC, rado17 requested changes

2023-04-04 12:46 UTC, rado17 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +			      "programming to get ps state failed\n");
I think just " Failed to get PS state." would be better.

2023-04-11 08:01 UTC, krish2718 approved these changes

2023-04-12 21:07 UTC, merged