wifi: Tx cleanup
nrfconnect/sdk-nrf pull request #10635
Opened 2023-03-19 21:10 UTC by krish2718

Return value and type cleanup.

2023-03-19 21:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10635/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10635/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10635/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-21 14:02 UTC, sachinthegreen requested changes

2023-03-21 14:02 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
>  	return WIFI_NRF_STATUS_FAIL;
This should also change to WIFI_NRF_FMAC_TX_STATUS_FAIL ?

2023-03-21 14:02 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +	enum wifi_nrf_fmac_tx_status status = WIFI_NRF_STATUS_FAIL;
WIFI_NRF_FMAC_TX_STATUS_FAIL ?

2023-03-21 15:12 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +	enum wifi_nrf_status status;
No point, as we override the status anyway.

2023-03-24 09:49 UTC, sachinthegreen approved these changes

2023-03-24 10:09 UTC, ajayparida approved these changes

2023-03-24 11:58 UTC, rado17 approved these changes

2023-03-24 14:53 UTC, merged