samples: bluetooth: peripheral_hids_mouse: Include SMP when security is enabled
nrfconnect/sdk-nrf pull request #10639
Opened 2023-03-20 12:48 UTC by maje-emb

Refactor the sample so that BT_SMP is included when BT_HIDS_SECURITY_ENABLED is enabled.
When BT_HIDS_SECURITY_ENABLED=n, some systems disconnect from HID devices because they do not support security.

2023-03-20 12:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10639/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10639/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10639/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-20 13:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10639
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-22 07:52 UTC, KAGA164 reviewed
Maybe it would be good to add changelog entry also?

2023-03-22 07:52 UTC, KAGA164 commented on samples/bluetooth/peripheral_hids_mouse/src/main.c
> +#if defined(CONFIG_BT_HIDS_SECURITY_ENABLED)
You can you here IS_ENABLED() macro and then there won't be need to have conditional compilation in 121 line

2023-03-22 07:52 UTC, KAGA164 commented on samples/bluetooth/peripheral_hids_mouse/src/main.c
> +#if defined(CONFIG_BT_HIDS_SECURITY_ENABLED)
`IS ENABLED()`?

2023-03-22 13:57 UTC, maje-emb commented
> Maybe it would be good to add changelog entry also?

Added changelog entry.

2023-03-22 14:08 UTC, peknis requested changes

2023-03-22 14:08 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * :kconfig:option:`CONFIG_BT_SMP` is included when `CONFIG_BT_HIDS_SECURITY_ENABLED` is enabled.
```suggestion
  * The :kconfig:option:`CONFIG_BT_SMP` Kconfig option is included when ``CONFIG_BT_HIDS_SECURITY_ENABLED`` is enabled.
```
Is that latter also a Kconfig option? At least it is not introduced in the Kconfig documentation or in the sample doc. Sounds a bit weird as something called ... _ENABLED is enabled. Should we rather say that it is selected in the Kconfig file or something like that?

2023-03-23 05:51 UTC, peknis approved these changes

2023-03-23 07:01 UTC, KAGA164 approved these changes

2023-03-23 13:27 UTC, merged