lib: dk_buttons_and_leds: fix for nRF9160DK IO expander
nrfconnect/sdk-nrf pull request #10646
Opened 2023-03-21 12:38 UTC by eivindj-nordic

The driver for the PCAL6408A IO expander on the nRF9160DK does not support disabling the interrupts while they are being processed. Move disabling of the interrupts to the buttons_scan_fn function. Also, the IO expander driver only supports edge driven interrupts, so this is added to the configuration.

2023-03-21 12:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10646/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10646/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10646/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-23 09:29 UTC, divipillai approved these changes

2023-03-24 14:05 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| find-my | https://github.com/nrfconnect/sdk-find-my/commit/92054fe0ba2155e1ad9be2bd2d7c89296399873d (main) | https://github.com/nrfconnect/sdk-find-my/pull/133 | [nrfconnect/sdk-find-my#133/files](https://github.com/nrfconnect/sdk-find-my/pull/133/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-03-24 15:34 UTC, kapi-no requested changes
@eivindj-nordic, you seem to pull in the manifest change for Find My by accident. Please remove it

2023-03-27 07:13 UTC, eivindj-nordic commented
> @eivindj-nordic, you seem to pull in the manifest change for Find My by accident. Please remove the following commit:

Yes, it is only temporary to see if that fixes the issues with failures on the `test-sdk-find-my` plan. I will remove it/wait for it to get merged before merging this one.

2023-03-29 13:45 UTC, kapi-no commented
@miha-nordic, @rawoNCS, please take a look why the Find My CI is failing

2023-04-11 13:34 UTC, eivindj-nordic commented
> Looks like environmental issue with access to artifactory.

@miha-nordic Do you know what is the status on this issue? If I understand you correctly it should not be related to this PR in this case(?). I see that this test is using the buttons, which this PR is changing the handling of. Could it be related? If so, how is the buttons used in CI for this? Is there any way I can reproduce locally?

2023-04-11 13:35 UTC, eivindj-nordic commented
> @eivindj-nordic, you seem to pull in the manifest change for Find My by accident. Please remove the following commit:
> 
> [e75963b](https://github.com/nrfconnect/sdk-nrf/commit/e75963b52486f653e6da536951e0c3fafcb76a71)

@kapi-no The manifest change commit is removed.

2023-04-11 13:49 UTC, miha-nordic commented
> > Looks like environmental issue with access to artifactory.
> 
> @miha-nordic Do you know what is the status on this issue? If I understand you correctly it should not be related to this PR in this case(?). I see that this test is using the buttons, which this PR is changing the handling of. Could it be related? If so, how is the buttons used in CI for this? Is there any way I can reproduce locally?

Access to artifactory is not a problem anymore. Issue that occurs here could be related to button handling. Case that is not working is pressing button for 3s and log should be printed on console. You can reproduce it bu flashing device with Find-my qualification sample and manually hold button. in CI we use nrf52840 to send button press signals.

2023-04-13 09:03 UTC, jhn-nordic approved these changes

2023-04-13 13:03 UTC, kapi-no approved these changes
Approving as this PR does not change Find My component anymore

2023-04-14 06:26 UTC, MirkoCovizzi commented on lib/dk_buttons_and_leds/dk_buttons_and_leds.c
> +
Nit: let's keep the pattern of 'err' and 'if (err)' with no empty line in between

2023-04-18 11:26 UTC, MirkoCovizzi approved these changes

2023-04-18 14:22 UTC, merged