lib: nrf_modem: split normal and bootloader initialization functions.
nrfconnect/sdk-nrf pull request #10671
Opened 2023-03-23 09:25 UTC by eivindj-nordic

Split the normal mode and bootloader initialization functions. This saves flash when only one of the modes are used.
Use a macro for nrf_modem_lib_init() for now to allow it to be called both with and without the mode parameter.

2023-03-23 09:34 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10671/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10671/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10671/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-23 11:44 UTC, SeppoTakalo requested changes

2023-03-23 14:15 UTC, eivindj-nordic commented on include/modem/nrf_modem_lib.h
> +int nrf_modem_lib_normal_init(void);
I see your point. We already have `nrf_modem_init()` and `nrf_modem_bootloader_init()` in `nrf_modem.h`, so I think I'll stick to it as is. It also keeps the verb at the end :)

2023-03-23 14:17 UTC, eivindj-nordic commented on include/modem/nrf_modem_lib.h
> + *       nrf_modem_lib_bootloader_init(void) to initialize in bootloader mode.
Thanks, I'll clean this up. I used `void` to distinguish that it is without the `mode` parameter as it has been earlier, but that is probably ok anyways.

2023-03-23 16:30 UTC, lemrey reviewed
I think this is more complicated than it should be. I suggest to remove the macro and the two new functions, and instead just change the signature of `nrf_modem_lib_init`. It's not a big change, we are not removing any functionality, just moving it to a different function, so we don't have to deprecate anything.

If we went ahead with this, users will get a warning when they compile their app; they will fix their app by calling `nrf_modem_lib_normal_init`, and then get a new warning in a few releases when we deprecate that in favor of `nrf_modem_lib_init` again? Unless we stick with `nrf_modem_lib_normal_init` which I think is a much worse name.

2023-03-23 21:49 UTC, glarsennordic approved these changes
LGTM

2023-03-24 11:00 UTC, eivindj-nordic commented
> I think this is more complicated than it should be. I suggest to remove the macro and the two new functions, and instead just change the signature of nrf_modem_lib_init. It's not a big change, we are not removing any functionality, just moving it to a different function, so we don't have to deprecate anything.

Ok, I have rewritten it to remove the former way of initializing instead of deprecating it.

2023-03-24 11:54 UTC, SeppoTakalo approved these changes

2023-03-24 12:18 UTC, simensrostad approved these changes
LGTM

2023-03-24 13:55 UTC, trantanen approved these changes

2023-03-27 05:26 UTC, MarkusLassila approved these changes

2023-03-27 06:05 UTC, tokangas approved these changes

2023-03-27 08:53 UTC, lemrey reviewed
looks good, some comments on doxygen

2023-03-27 08:53 UTC, lemrey commented on include/mgmt/fmfu_mgmt.h
>   * The modem library must be initialized in DFU mode before calling this
nit: `... initialized in bootloader mode ..`

2023-03-27 08:53 UTC, lemrey commented on include/modem/nrf_modem_lib.h
> + * when a firmware update is scheduled.
Some repetitions here:
`this function initializes the modem ... and turns on the modem`, those are the same thing.

2023-03-27 08:53 UTC, lemrey commented on include/modem/nrf_modem_lib.h
> + * @brief Initialize the Modem library in normal operating mode and turn on the modem.
I would remove the "normal operating mode" wording and simplify a bit, based on the doc in `nrf_modem.h`.
`Initialize the Modem library and turn on the modem`

2023-03-27 08:53 UTC, lemrey commented on include/modem/nrf_modem_lib.h
> + * when a firmware update is scheduled.
I think the first part can be omitted, and we could start with `The operation can take a few ...`

2023-03-27 08:53 UTC, lemrey commented on include/modem/nrf_modem_lib.h
> + * won't be available.
First part is a bit redundant, I would start directly with `When the modem is initialized in bootloader ..` and omit the first part.

2023-03-27 15:39 UTC, lemrey approved these changes

2023-03-28 00:42 UTC, plskeggs approved these changes

2023-03-28 08:08 UTC, gregersrygg approved these changes

2023-04-03 12:09 UTC, divipillai approved these changes

2023-04-19 14:14 UTC, merged