doc: add signed_by_b0_*_image.bin to output files
nrfconnect/sdk-nrf pull request #10674
Opened 2023-03-23 10:05 UTC by greg-fer

Added entries to for MCUboot output file list:
signed_by_b0_s0_image.bin and signed_by_b0_s1_image.bin. NCSDK-19379.

----

Related to https://devzone.nordicsemi.com/f/nordic-q-a/95700/signed_by_b0_s1_image-bin-vs-signed_by_mcuboot_and_b0_s1_image_update-bin

2023-03-23 10:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10674
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-23 10:42 UTC, annwoj approved these changes

2023-03-23 13:40 UTC, gregersrygg requested changes
The original question from the customer is not being answered here. What is the difference between these files and those that are also signed by mcuboot? I don't think CMakeLists.txt and the cmake files are relevant, but it could be mentioned that these files are only intermediate images when also using MCUboot. These images can be used when using NSIB without mcuboot (but then it doesn't belong in this mcuboot table).

2023-03-23 14:20 UTC, greg-fer commented
@gregersrygg , I've updated the phrasing and moved the files to other output files. Please check again.

2023-03-23 14:49 UTC, gregersrygg commented on doc/nrf/app_dev/build_and_config_system/index.rst
> +| :file:`signed_by_mcuboot_and_b0_s0_image_update.bin`             | MCUboot update for s0. Created using the :file:`signed_by_b0_s0_image.bin` (see :ref:`app_build_output_files_other`).
```suggestion
| :file:`signed_by_mcuboot_and_b0_s0_image_update.bin`             | MCUboot update image for s0 signed by both MCUboot and NSIB. The MCUboot signature is used by MCUboot to verify the integrity of the image before swapping and the NSIB signature is used by NSIB before booting the image.                                                                                                                                                        |
```

2023-03-23 14:49 UTC, gregersrygg commented on doc/nrf/app_dev/build_and_config_system/index.rst
> +| :file:`signed_by_mcuboot_and_b0_s1_image_update.bin`             | MCUboot update for s1. Created using the :file:`signed_by_b0_s1_image.bin` (see :ref:`app_build_output_files_other`).
```suggestion
| :file:`signed_by_mcuboot_and_b0_s1_image_update.bin`             | MCUboot update image for s1 signed by both MCUboot and NSIB. The MCUboot signature is used by MCUboot to verify the integrity of the image before swapping and the NSIB signature is used by NSIB before booting the image                  |
```

2023-03-23 14:49 UTC, gregersrygg commented on doc/nrf/app_dev/build_and_config_system/index.rst
> +|                                   | Can be used to generate the :file:`signed_by_mcuboot_and_b0_s1_image_update.bin` when using NSIB with MCUboot.                    |
```suggestion
| :file:`signed_by_b0_s0_image.bin` | Intermediate file only signed by NSIB.                                                 |                                                                                                                                                                                             |
|                                   |                    |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| :file:`signed_by_b0_s1_image.bin` | Intermediate file only signed by NSIB.                                                 |
|                                   |                    |
```

I struggle to see the usefulness of describing these files here except that they're just intermediate files. Is it even possible to use NSIB without MCUboot? Would you have the application as S0/S1 then? Or would you need some other bootloader? This sounds very edge-case to me, but please correct me if there is an actual use-case for this.
The way I understood the question from the customer was why we had the two set of files and the difference between them. There was also some confusion in the case w.r.t. swapping of S0/S1 and how the mcuboot signature was being used. So I think it's more important to explain why the image needs to be signed by both NSIB and MCUboot.

2023-03-24 09:28 UTC, greg-fer commented
@gregersrygg , @aHaugl , please have another look. Thanks!

2023-03-24 10:47 UTC, gregersrygg approved these changes
Thanks :)

2023-03-27 07:29 UTC, aHaugl approved these changes

2023-03-27 08:03 UTC, merged