samples: aws_iot: Option to use UUID as device id
nrfconnect/sdk-nrf pull request #10685
Opened 2023-03-24 10:07 UTC by dilner

2023-03-24 10:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10685/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10685/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10685/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-24 10:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10685
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-24 14:00 UTC, jorgenmk requested changes

2023-03-27 13:44 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +#if IS_ENABLED(CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID)
```suggestion
#if defined(CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID)
```

2023-03-27 13:44 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +#if IS_ENABLED(CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID)
In general we use `#if defined` for preprocessor statements. I think we should continue to stick to that.

2023-03-27 13:44 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +#if IS_ENABLED(CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID)
```suggestion
#if defined(CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID)
```

2023-03-27 13:44 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +	static struct aws_iot_config config;
```suggestion
	static struct aws_iot_config config = {
	    .client_id = device_id,
	    .client_id_len = strlen(device_id)
	};
```

2023-03-27 13:44 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +	static struct aws_iot_config config;
The values can be set directly, I would also move the declaration up next to `static char device_id[HW_ID_LEN];
And, we should use `strlen` to get the length of the string contained in `device_id` buffer. HW_ID gives the whole buffer which will usually be larger and include the null character. Including the null character is not necessary. We only want the string.

2023-03-30 11:48 UTC, jorgenmk commented on samples/nrf9160/aws_iot/prj.conf
> +CONFIG_AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID=n
This line should be removed

2023-03-30 11:53 UTC, jorgenmk commented on samples/nrf9160/aws_iot/src/main.c
> +	LOG_INF("Using UUID as device id: %s", device_id);
This will not be a UUID by default, as it's selected by option `HW_ID_LIBRARY_SOURCE`. Suggest changing to just `Device id: %s`

2023-03-31 06:06 UTC, jorgenmk approved these changes

2023-03-31 07:01 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +		LOG_ERR("Failed to retrieve device ID, error: %d", err);
No need of continuing if this function fails, the `device_id` will be wrong.

2023-03-31 07:03 UTC, simensrostad commented on samples/nrf9160/aws_iot/src/main.c
> +	static char device_id[HW_ID_LEN];
I've suggested zeroing out the `device_id`, this is good practise in general. Previously when the `static` keyword was used this happened automatically.

2023-03-31 07:05 UTC, simensrostad commented on samples/nrf9160/aws_iot/README.rst
> +.. _CONFIG_AWS_IOT_SAMPLE_AWS_IOT_SAMPLE_APP_VERSION:
Mismatch between the Kconfig definition and docs.

2023-04-12 07:35 UTC, simensrostad approved these changes
LGTM

2023-04-12 09:07 UTC, simensrostad commented on samples/nrf9160/aws_iot/Kconfig
> +config AWS_IOT_SAMPLE_DEVICE_ID_USE_HW_ID
Good idea, yes

2023-04-12 11:56 UTC, divipillai approved these changes

2023-04-18 11:35 UTC, merged