wifi: A few RX improvements
nrfconnect/sdk-nrf pull request #10712
Opened 2023-03-27 16:57 UTC by krish2718

2023-03-29 06:45 UTC, sachinthegreen requested changes

2023-03-29 06:45 UTC, sachinthegreen commented on drivers/wifi/nrf700x/Kconfig.nrf700x
> +config NRF700X_BH_WORKQ_PRIORITY
Change WORKQ to WQ to maintain naming consistency with NRF700X_IRQ_WQ_PRIORITY

2023-03-29 06:45 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_work.c
> +K_THREAD_STACK_DEFINE(wq_stack_area, 1024);
Rename wq_stack_area to bh_wq_stack_area since we are now differentiating workqueues as IRQ and BH workqueues.

2023-03-29 06:45 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_work.c
> +K_THREAD_STACK_DEFINE(irq_stack_area, 1024);
Rename irq_stack_area to irq_wq_stack_area.

2023-03-29 18:21 UTC, krish2718 commented
@krga2022  this change impacts the scan results number, so, can you please run some tests in crowded channel and see if this is causing any degradation, we can tweak `CONFIG_NET_MGMT_EVENT_QUEUE_SIZE` and `CONFIG_NRF700X_WORKQ_MAX_ITEMS` accordingly.

2023-04-12 14:13 UTC, krga2022 approved these changes

2023-04-13 11:30 UTC, merged