Radiotestcw pr
nrfconnect/sdk-nrf pull request #10713
Opened 2023-03-28 06:32 UTC by karun2796

drivers: wifi: Update RPU patch to rev#106

    [SHEL-1157]:Add option to include random back-off in Wi-Fi Radio Test.
    [SHEL-1418]:Wifi channel allocation avoided for connected scan.

2023-03-28 06:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10713/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10713/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10713/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-28 07:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10713
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-28 08:54 UTC, krish2718 requested changes
The commits order is wrong, header file change should go first

2023-03-28 11:36 UTC, udaynordic approved these changes

2023-03-28 11:58 UTC, karun2796 commented
> The commits order is wrong, header file change should go first

Its taken care.

2023-03-29 06:34 UTC, krish2718 approved these changes

2023-03-29 06:50 UTC, sachinthegreen requested changes

2023-03-29 06:50 UTC, sachinthegreen commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +	if ((val < 0) || (val > 200000)) {
We can remove the `(val < 0)` check since it is a unsigned long variable.

2023-03-29 06:50 UTC, sachinthegreen commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +		(val == 3) ||
Indentation seems to be off.

2023-03-29 06:50 UTC, sachinthegreen commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +		      "<val> - Cw values to be configured (0, 3, 7, 15, 31, 63, 127, 255, 511, 1023)",
Cw can be replaced by Channel width?
Also values should be value.

2023-03-29 06:53 UTC, sachinthegreen commented
This would also need corresponding documentation change.

2023-03-29 08:53 UTC, richabp approved these changes

2023-03-29 09:38 UTC, merged