drivers: wifi: Clean boot logs
nrfconnect/sdk-nrf pull request #10729
Opened 2023-03-29 12:59 UTC by sachinthegreen

1. Clean up Wi-Fi driver boot log messages by removing non-essential informational messages 
2. Display firmware version on successful boot of Sheliak

This addresses the following jira issues:
[SHEL-1347]

2023-03-29 13:00 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hostap | https://github.com/nrfconnect/sdk-hostap/commit/6d949b2b1f95d53bc91f798ace564587e0408bd1 (main) | https://github.com/nrfconnect/sdk-hostap/pull/77 | [nrfconnect/sdk-hostap#77/files](https://github.com/nrfconnect/sdk-hostap/pull/77/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-03-29 13:04 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10729/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10729/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |

**test-sdk-wifi:** added because there was no .github/test-spec.yml in 'hostap'
**test-sdk-wifi-EK-shell:** added because there was no .github/test-spec.yml in 'hostap'
**test-sdk-wifi-radio:** added because there was no .github/test-spec.yml in 'hostap'
**test-sdk-wifi-scan:** added because there was no .github/test-spec.yml in 'hostap'
**test-sdk-wifi-sta:** added because there was no .github/test-spec.yml in 'hostap'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10729/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-29 13:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10729
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-03-29 16:24 UTC, krish2718 requested changes
IMHO, we should convert those prints to _dbg rather than removing them.

2023-03-29 16:24 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c
> +
This is handy, so, should be converted to `_dbg`

2023-03-30 08:06 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +	LOG_INF("Firmware (Version %d:%d:%d:%d / %d:%d:%d:%d) booted succesfully\n",
@udaynordic : WDYT?

2023-03-31 10:34 UTC, krish2718 approved these changes

2023-04-03 10:58 UTC, udaynordic commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +	LOG_INF("Firmware (Version %d:%d:%d:%d / %d:%d:%d:%d) booted succesfully\n",
I would prefer to have this as info than debug.

2023-04-03 11:07 UTC, udaynordic approved these changes

2023-04-03 11:08 UTC, rado17 approved these changes

2023-04-19 03:42 UTC, bama-nordic submitted a review, later dismissed
Should the firmware version be displayed everytime we boot or only when we explictly query? Need to finalize this.

2023-05-08 12:37 UTC, sachinthegreen commented
> Should the firmware version be displayed everytime we boot or only when we explictly query? Need to finalize this.

Discussed with @bama-nordic and @udaynordic and it was agreed to display the version everytime we boot.

2023-05-09 06:44 UTC, merged