cmake: Prevent cleanup of RAM when coredump RAM backend is used
nrfconnect/sdk-nrf pull request #10745
Opened 2023-03-30 13:50 UTC by maxd-nordic

This patch prevents deletion of coredumps by MCUBoot. It should fix the broken asset_tracker+memfault configuration on the Thingy:91.

2023-03-30 13:59 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10745/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10745/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10745/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-03-30 14:03 UTC, sigvartmh approved these changes

2023-03-31 07:08 UTC, simensrostad commented
@maxd-nordic @sigvartmh 
Are there other implications that we need to be aware of when disabling `CONFIG_MCUBOOT_NRF_CLEANUP_NONSECURE_RAM`?

If so, we should probably have a disclaimer somewhere.

2023-03-31 08:20 UTC, simensrostad approved these changes

2023-03-31 10:13 UTC, gregersrygg requested changes
Discussed this separately with @maxd-nordic and @sigvartmh, and we think it might be possible to remove the default `CONFIG_MCUBOOT_USE_ALL_AVAILABLE_RAM=y` for thingy:91 that was introduced in #9780. That would result in `CONFIG_MCUBOOT_NRF_CLEANUP_NONSECURE_RAM` to be turned off and this PR would be redundant. The question is if `sram_secure` is large enough alone for the different apps/samples or if the secure RAM size needs to be increased.

2023-04-11 13:28 UTC, closed without merging