Issue20877 caf new ztest
nrfconnect/sdk-nrf pull request #10779
Opened 2023-04-05 15:28 UTC by zycz

2023-04-05 15:30 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10779/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10779/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10779/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-06 15:07 UTC, rakons requested changes

2023-04-06 15:07 UTC, rakons commented on tests/subsys/caf/sensor_manager/src/main.c
> +	APP_EVENT_SUBMIT(event_sensor3);
Make sure that test initialization is finished. For that:
- add event: test_initialization_done and send it here.
- In event processing - when test_initialization_done is received - set the semaphore.
- Here - wait for this semaphore (remember to check the waiting result).

This way we would be sure that no timing issue jumps in and when the test execution is started, all the configuration events are already processed.

2023-04-07 12:35 UTC, MarekPieta reviewed
Seems ok (you even made unit tests independent on each other :) ).
Please just apply @rakons suggestion to ensure that `test_before` takes effect before test is started

2023-04-07 15:01 UTC, rakons approved these changes

2023-04-07 15:14 UTC, MarekPieta approved these changes
Looks good. Thanks for clarification during the offline discussion

2023-04-11 11:47 UTC, gopiotr approved these changes
LGTM. I tested it locally on hardware and it works properly. Thank you a lot for your effort.

2023-04-12 21:02 UTC, merged