drivers: wifi: Display firmware version
nrfconnect/sdk-nrf pull request #10789
Opened 2023-04-06 13:15 UTC by rado17

Add command in wifi_util shell to display firmware version.

2023-04-06 13:23 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10789/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10789/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10789/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-06 13:41 UTC, sachinthegreen requested changes

2023-04-06 13:41 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +		 "UMAC : %d.%d.%d.%d\nLMAC : %d.%d.%d.%d\n",
`UMAC version` and `LMAC version`

2023-04-10 07:11 UTC, rado17 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +		 "UMAC : %d.%d.%d.%d\nLMAC : %d.%d.%d.%d\n",
Done

2023-04-10 07:11 UTC, rado17 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +	if (status == WIFI_NRF_STATUS_SUCCESS) {
Done

2023-04-10 10:29 UTC, sachinthegreen approved these changes

2023-04-11 07:58 UTC, krish2718 approved these changes

2023-04-19 09:31 UTC, rlubos commented
@rado17 Please fix the compliance issue:
> drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c:510  Statements should start on a tabstop

2023-04-24 07:37 UTC, merged