drivers: wifi: TX coalesce logic tuning
nrfconnect/sdk-nrf pull request #10791
Opened 2023-04-06 13:42 UTC by ajayparida

[SHEL-1217] TX coalesce logic to accommodate more number of frames based on current subframe lengths. Existing Current logic uses fixed number of frames without taking frame lengths into consideration. More number of frames will get aggregated for lower lengths of pkts.

2023-04-06 13:48 UTC, sachinthegreen requested changes

2023-04-06 13:48 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/hw_if/hal/inc/hal_structs.h
> +	unsigned long last_buf_addr;
Call this as `addr_last_buf` to maintain consistency with other variable names above

2023-04-06 13:48 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +	/* Align the memory*/
Space before `*/`

2023-04-06 13:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10791/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10791/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10791/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-06 18:12 UTC, krish2718 requested changes
This also needs further changes, it is failing here `<err> wifi_nrf: wifi_nrf_hal_rpu_pktram_buf_map_init: RPU PKTRAM buffer overflowed`.

2023-04-10 10:22 UTC, krish2718 requested changes

2023-04-10 10:22 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +			  hal_dev_ctx->hpriv->cfg_params.rx_buf_pool[pool_idx].buf_sz));
This is not easy to understand, randomly doing `MAX_NUM_OF_RX_QUEUES - 2` and then `pool_idx +1`, can we please refactor to make it easier to understand.

2023-04-10 11:23 UTC, ajayparida commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +
Needed, as part of coalescing

2023-04-10 12:49 UTC, sachinthegreen approved these changes

2023-04-10 19:31 UTC, krish2718 requested changes

2023-04-10 19:31 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +					   config->num_tx_pkts);
the prototype says `frame_id`, but we are passing `config->num_tx_pkts` ?

2023-04-10 19:31 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +
Still isn't clear:

* If you want to store the previous address then why isn't `bounce_buf_addr` derivation not under `frame_id == 0`?
* First `bounce_buf_addr` still uses `max_tx_frm_sz` which is wrong, it should be based on `addr_last_buf`
* Head room is added only after succesful map for `hal_dev_ctx->addr_last_buf` , but if map fails the TX desc is abandoned, so, no need for this.
* A better name for `addr_last_buf` would be `bounce_buf_curr_addr`

This looks unnecessarily complex and can be simplified, IMHO we could move the offset in PKTRAM calculation to FMAC from HAL, and then keep only mem_write + dmap_map in HAL?

2023-04-10 19:31 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +	buf_len = (buf_len + 4) & 0xfffffffc;
if Aligning length enough or do we need to align the buffer address as well?

2023-04-11 06:56 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
> +					   config->num_tx_pkts);
`num_tx_pkts` is a misnomer, its incremented for each packets, so, its an index.

2023-04-11 06:59 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
> +	buf_len = (buf_len + 4) & 0xfffffffc;
`spim_addr_check` checks both address and length, so, maybe in your tests only length needs alignment, but what about in general or for QSPI? We need to meet the alignment requirements without depending on tests as we cannot excite all scenarios.

2023-04-12 21:09 UTC, merged