Bluetooth: Mesh: Fix in scheduler message validity test
nrfconnect/sdk-nrf pull request #10834
Opened 2023-04-13 16:27 UTC by akredalen

Fixed bug where ctx was passed as NULL to scheduler client api without any defined publish parameters, triggering a segmentation fault in model_ackd_timeout_get.

2023-04-13 16:30 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10834/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10834/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10834/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-14 07:36 UTC, alxelax requested changes
Please check with Valgrind. If you need assistance running it, please let me know.

2023-04-14 08:02 UTC, balaji-nordic approved these changes
The fix works. The test runs and passes when optimizations are disabled (it is failing in main when optimizations are disabled).

2023-04-14 14:03 UTC, alxelax approved these changes

2023-04-17 08:14 UTC, ludvigsj approved these changes

2023-04-17 08:17 UTC, merged