quarantine_windows: Add EBC tests
nrfconnect/sdk-nrf pull request #10880
Opened 2023-04-18 08:06 UTC by rawoNCS

Add EBC tests to quarantine.
Rename file from quarantine_windows to quarantine_windows_mac as it is common for both platforms.

Signed-off-by: Rafal Wozniakowski <rafal.wozniakowski@nordicsemi.no>

2023-04-18 08:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10880/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10880/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10880/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-18 10:07 UTC, gopiotr requested changes
Since last Zephyr upmerge there is possiblity to use in quarantine regexes and "platforms under quarantine". So, in this PR you can also change the way for excluding tests which are dedicated for native_posix and QEMU. For example like this (without listing all testscenarios):
``` yaml
- platforms:
    - native_posix
    - qemu_cortex_m3
    - qemu_x86
  comment: "Cannot build samples for Native POSIX and QEMU on Windows OS"
```
More information about this you can find here:
https://docs.zephyrproject.org/latest/develop/test/twister.html#quarantine

2023-04-18 10:52 UTC, gopiotr approved these changes

2023-04-19 07:11 UTC, miha-nordic approved these changes

2023-04-19 07:27 UTC, merged