Bluetooth: Mesh: Add sensor server to light_ctrl sample
nrfconnect/sdk-nrf pull request #10892
Opened 2023-04-18 15:17 UTC by omkar3141

Adds a demonstration of usage of the sensor server model to report additional data about the device (in this case (dummy) energy use) to the light_ctrl sample.

2023-04-18 16:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10892
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-04-20 13:34 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10892/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10892/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10892/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-21 13:06 UTC, mia-ko requested changes

2023-04-25 14:51 UTC, akredalen requested changes
Looks good to me :) Just a few nitpicks.

2023-04-25 14:51 UTC, akredalen commented on samples/bluetooth/mesh/light_ctrl/README.rst
> +* Bind the model to **Application Key 1**, make sure to bind the same application key to the peer Sensor Client.
```suggestion
* Bind the model to **Application Key 1**. Make sure to bind the same application key to the peer Sensor Client.
```

2023-04-25 17:48 UTC, Balaklaka reviewed
Should we extend the sensor_client sample to support this functionality?

2023-04-25 17:48 UTC, Balaklaka commented on samples/bluetooth/mesh/light_ctrl/README.rst
> +
Should it say something about Publish/Subscriptions before it is able to receive sensor settings and it is configured? Same for sensor server.

2023-04-26 15:03 UTC, akredalen approved these changes

2023-04-27 07:46 UTC, mia-ko approved these changes

2023-04-28 07:23 UTC, merged