doc: update edge Impulse user guide
nrfconnect/sdk-nrf pull request #10936
Opened 2023-04-25 09:28 UTC by divipillai

update the Edge Impulse user guide to match
with integration template

NCSDK-19384

2023-04-25 10:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10936
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-11 13:47 UTC, MarekPieta commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
You actually describe an applications that is part of the NCS

2023-05-11 13:49 UTC, divipillai commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
Agree, I will move to Applications and samples section.

2023-05-11 14:14 UTC, MarekPieta commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
Thanks

2023-05-12 07:22 UTC, annwoj commented on doc/nrf/external_comp/edge_impulse.rst
> +   * An `Edge Impulse studio account <Edge Impulse studio signup_>`_ and an Edge Impulse project.
```suggestion
   * Creation of an `Edge Impulse studio account <Edge Impulse studio signup_>`_ and an Edge Impulse project.
```

2023-05-12 07:22 UTC, annwoj commented on doc/nrf/external_comp/edge_impulse.rst
> +Complete the following steps to generate this archive and add it to the build system:
```suggestion
Complete the following steps to generate the archive and add it to the build system:
```

2023-05-12 07:22 UTC, annwoj commented on doc/nrf/external_comp/edge_impulse.rst
> +* :ref:`nrf_machine_learning_app` - demonstrates the complete out of the box reference design.
```suggestion
* :ref:`nrf_machine_learning_app` - demonstrates a complete out of the box reference design.
```

2023-05-12 07:22 UTC, annwoj commented on doc/nrf/external_comp/edge_impulse.rst
> +The following samples demonstrate the Edge Impulse integration in |NCS|:
```suggestion
The following samples demonstrate the Edge Impulse integration in the |NCS|:
```

2023-05-12 07:22 UTC, annwoj commented on doc/nrf/external_comp/edge_impulse.rst
> +The following application uses the Edge Impulse integration in |NCS|:
```suggestion
The following application uses the Edge Impulse integration in the |NCS|:
```

2023-05-15 08:23 UTC, emob-nordic requested changes

2023-05-15 08:39 UTC, divipillai commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
@emob-nordic : As per the comment here: I plan to move the sentence to https://github.com/nrfconnect/sdk-nrf/pull/10936#discussion_r1191197145, applications and samples. Hope this works for you.

2023-05-15 09:17 UTC, emob-nordic commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
Oh. I didn't notice that. That works for me.

2023-05-15 09:18 UTC, emob-nordic commented on doc/nrf/external_comp/edge_impulse.rst
> +nRF Machine learning application can also be used to collect data from devices (For example, it supports Thingy:53 with an out-of-the-box accelerometer).
Let me know once, moved so i could rereview.

2023-05-15 09:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10936/5/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10936/5/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-05-15 10:18 UTC, MarekPieta approved these changes

2023-05-16 12:02 UTC, annwoj approved these changes

2023-05-17 07:43 UTC, emob-nordic approved these changes

2023-05-18 11:57 UTC, merged