tests: crypto: Switch to new ztest API
nrfconnect/sdk-nrf pull request #10931
Opened 2023-04-24 14:36 UTC by stephen-nordic

Switching crypto tests to new ztest API

2023-04-24 14:42 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10931/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10931/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf_crypto | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10931/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-25 09:32 UTC, Mangl10 approved these changes

2023-04-25 09:52 UTC, torsteingrindvik approved these changes

2023-04-26 07:36 UTC, nordicjm requested changes
Can you squash the license changes into a single commit?

2023-04-26 09:32 UTC, merged