doc: update Matter known issues
nrfconnect/sdk-nrf pull request #10948
Opened 2023-04-26 08:30 UTC by LuDuda

Added a known issue KRKNWK-16783 that affects Matter reliability.

2023-04-26 08:34 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10948/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10948/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-04-26 09:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10948
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-04-26 12:14 UTC, greg-fer requested changes

2023-04-26 12:14 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +Workaround: Manually cherry-pick and apply commit from the sdk-connectedhomeip repository (commit hash: ``23f08242f92973a7a3308b4d62a82c59cf6cf6b3``).
```suggestion
KRKNWK-16783: Accessory may become unresponsive after several hours
   A Matter accessory may stop sending Report Data messages due to an internal bug in the Matter stack v1.0.0.0 and thus become unresponsive for Matter controllers.

   **Workaround:** Manually cherry-pick and apply commit from the `dedicated Matter fork`_ (commit hash: ``23f08242f92973a7a3308b4d62a82c59cf6cf6b3``).
```

2023-04-27 12:22 UTC, greg-fer approved these changes

2023-04-27 12:24 UTC, kkasperczyk-no approved these changes

2023-04-27 12:28 UTC, merged