bluetooth: fast_pair: Set Oberon as default crypto backend
nrfconnect/sdk-nrf pull request #10949
Opened 2023-04-26 08:46 UTC by joerchan

Set Oberon as default crypto backend.
The Mbed TLS APIs are considered as legacy crypto APIs in NCS. The memory usage of the Mbed TLS backend is significantly larger than Oberon or Tinycrypt.

2023-04-26 08:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10949/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10949/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10949/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-04-26 09:08 UTC, MarekPieta requested changes

2023-04-26 10:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10949
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-04-26 11:25 UTC, melwee01 commented on doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
> +  The Mbed TLS backend is using Mbed TLS crypto APIs which is considered a legacy API.
```suggestion
  The Mbed TLS backend uses the Mbed TLS crypto APIs, which are now considered legacy APIs.
```

Progressive tense to present (is using -> uses), subject verb agreement (APIs vs API, is -> are).

2023-04-26 11:25 UTC, melwee01 commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Salt size in the Fast Pair not discoverable advertising from 1 byte to 2 bytes to align with the Fast Pair specification update.
```suggestion
    * Salt size in the Fast Pair not discoverable advertising from 1 byte to 2 bytes, to align with the Fast Pair specification update.
```

2023-04-26 13:20 UTC, kapi-no approved these changes

2023-04-26 14:13 UTC, kapi-no commented
@annwoj or @divipillai, please take a look as you typically review documentation for Fast Pair modules

2023-04-26 14:26 UTC, MarekPieta approved these changes

2023-04-26 15:14 UTC, MarekPieta approved these changes

2023-04-26 15:14 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/Kconfig.fast_pair
> +	select ENTROPY_GENERATOR
Please add the same to `BT_FAST_PAIR_GATT_SERVICE`. It also uses the `sys_csrand_get` API

2023-04-26 15:23 UTC, MarekPieta approved these changes

2023-04-27 07:23 UTC, melwee01 approved these changes

2023-04-27 07:43 UTC, annwoj approved these changes
lgtm

2023-04-27 08:05 UTC, merged