doc: BT service library docs clean up
nrfconnect/sdk-nrf pull request #10975
Opened 2023-04-28 05:56 UTC by peknis

Mostly rewording and formatting fixes
to the BT service library docs (excluding Mesh).
Also some link fixes.

Ref: NCSDK-21324

2023-04-28 06:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-10975
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-04-28 07:27 UTC, wiba-nordic requested changes

2023-04-28 07:27 UTC, wiba-nordic commented on doc/nrf/libraries/bluetooth_services/services/dfu_smp.rst
>  The response to a command is sent as notification.
```suggestion
The response to a command is sent as a notification.
```

2023-04-28 07:27 UTC, wiba-nordic commented on doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
> +   In case of the :ref:`nRF53 Series <ug_nrf53>` devices, this part of the configuration cannot be automatically updated for the network core and you must manually align it.
```suggestion
   When using :ref:`nRF53 Series <ug_nrf53>` devices, this part of the configuration cannot be automatically updated for the network core and you must manually align it.
```

2023-04-28 07:27 UTC, wiba-nordic commented on doc/nrf/libraries/bluetooth_services/services/throughput.rst
> +   * Write ``0`` bytes to the characteristic to reset the metrics.
I don't think this is a correct change, and should instead be:
```suggestion
   * Write zero bytes to the characteristic to reset the metrics.
```

2023-04-28 08:21 UTC, kapi-no commented
@alstrzebonski, can you take a quick look at the Fast Pair part?

2023-05-04 10:38 UTC, alstrzebonski reviewed
Fast Pair part approved.

2023-05-04 14:16 UTC, KAGA164 commented on doc/nrf/libraries/bluetooth_services/services/throughput.rst
> +   * Write zero bytes to the characteristic to reset the metrics.
Hmm  it looks like in real it is one byte which values is not relevant, need to be written.
Maybe it is not related to this PR but it is worth to fix here

2023-05-05 06:32 UTC, KAGA164 approved these changes

2023-05-05 06:34 UTC, peknis commented
> Fast Pair part approved.

@alstrzebonski, please click the green button.

2023-05-05 07:28 UTC, merged