samples: common: dtm: radio_test: Extract common FEM functions
nrfconnect/sdk-nrf pull request #10984
Opened 2023-04-28 12:35 UTC by dchat-nordic

Extarct FEM functionality common to dtm and radio_test to a separate directory.

2023-05-17 06:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10984/13/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10984/13/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10984/13/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-17 08:38 UTC, b-gent commented
@wbober  can you confirm that adding a 'Common samples' section is fine (regarding the discussion about sample folder structure that we had). Thanks.

2023-05-17 09:35 UTC, peknis commented
> @wbober can you confirm that adding a 'Common samples' section is fine (regarding the discussion about sample folder structure that we had). Thanks.

Actually, I believe this should be a library, not a sample, after all. But in a new section "Common libraries".

2023-05-18 14:21 UTC, wbober commented
@carlescufi Could you please advise on if this should go to `subsys` or `lib`?

2023-05-19 08:28 UTC, peknis requested changes

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +FEM Abstraction Layer
Not so sure about the capitalization. Maybe this is fine with  lower case.

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +The library is a wrapper for the MPSL FEM.
```suggestion
This library is a wrapper for the MPSL FEM.
```

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +The library is designed to simplify low level usage of a FEM hardware.
```suggestion
The library simplifies low level usage of FEM hardware.
```

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +The library requires the usage of a FEM and MPSL functionality.
This does not sound like a proper requirement, as the lib is meant to be used with FEM and MPSL, which is stated already before. If there are no other requirements, you might as well leave this section out.

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +The library is enabled by the :kconfig:option:`CONFIG_FEM_AL_LIB`.
```suggestion
To enable this library, use the Kconfig option ``CONFIG_FEM_AL_LIB``.
```
As this option is not available in the Kconfig reference, you should not use the :kconfig:option: tag.

2023-05-19 08:28 UTC, peknis commented on doc/nrf/libraries/fem_al/index.rst
> +.. _fem_al_lib:
If you want to add this lib doc to the Other libraries section, place it in doc/nrf/libraries/other and rename this file to fem_al.rst, for example

2023-05-19 10:43 UTC, peknis requested changes

2023-05-19 10:43 UTC, peknis commented on samples/peripheral/radio_test/README.rst
>  This sample uses the following |NCS| library:
```suggestion
This sample uses the following |NCS| libraries:
```

2023-05-19 12:01 UTC, peknis approved these changes

2023-05-22 11:08 UTC, maje-emb approved these changes

2023-05-23 11:35 UTC, carlescufi commented
> @carlescufi Could you please advise on if this should go to `subsys` or `lib`?

Personally in this case I think this belongs in `lib`, @dchat-nordic. The distinction is not always clear, but this seems "passive" (i.e. no startup or threading).

2023-05-23 11:35 UTC, carlescufi requested changes
Please move to `lib`

2023-05-23 13:06 UTC, wbober commented
LGTM

2023-05-23 14:53 UTC, carlescufi approved these changes

2023-05-23 14:53 UTC, merged