TF-M: Print memory usage of TF-M executable
nrfconnect/sdk-nrf pull request #10991
Opened 2023-05-01 13:41 UTC by joerchan

2023-05-01 13:42 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10991/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10991/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-10991/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-02 10:19 UTC, frkv approved these changes
LGTM

2023-05-02 11:54 UTC, SebastianBoe commented on modules/tfm/tfm/boards/CMakeLists.txt
> +)
Strange.

Why isn't this working:

ncs/modules/tee/tf-m/trusted-firmware-m/toolchain_GNUARM.cmake
61:    set(MEMORY_USAGE_FLAG LINKER:--print-memory-usage)

?

2023-05-02 11:56 UTC, SebastianBoe requested changes
We should find out why upstream's attempt at doing the same thing is not working.

2023-05-02 12:53 UTC, joerchan commented
> We should find out why upstream's attempt at doing the same thing is not working.

I didn't know about that one, CONFIG_TFM_MEMORY_USAGE_QUIET is enabled, so that should make sense IMO.
I will try to change this config value instead of adding it like this.

Thanks.

2023-05-02 14:54 UTC, joerchan commented
Close in favour of: https://github.com/zephyrproject-rtos/zephyr/pull/57487

2023-05-02 14:54 UTC, closed without merging