tfm_(psa|regression)_test: Add tags to each test
nrfconnect/sdk-nrf pull request #11011
Opened 2023-05-03 10:43 UTC by Mangl10

2023-05-03 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11011) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11011) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=11011) it.</sub>

2023-05-03 10:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11011/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11011/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11011/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-03 10:53 UTC, torsteingrindvik commented on tests/tfm/tfm_psa_test/testcase.yaml
> +    tag: lvl1
I think it's `tags` not `tag`

2023-05-03 11:05 UTC, Mangl10 commented on tests/tfm/tfm_psa_test/testcase.yaml
> +    tag: lvl1
Yes, missed that.

2023-05-03 15:14 UTC, torsteingrindvik approved these changes

2023-05-03 18:09 UTC, joerchan requested changes
If this is a generic tag in global scope taking lvl1/2 for this seems not very future proof. I suggges tfm_lvl1/2

2023-05-04 08:08 UTC, closed without merging

2023-05-04 08:09 UTC, gmarull commented
please user forks, branches in upstream repo are not allowed.