doc: Issue with update_ad on CryptoCell
nrfconnect/sdk-nrf pull request #11053
Opened 2023-05-05 09:35 UTC by vili-nordic

Calling psa_aead_update_ad multiple times on AES GCM does result in invalid tags.

2023-05-05 09:43 UTC, Vge0rge approved these changes

2023-05-05 09:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11053/2/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11053/2/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-05-05 09:54 UTC, SebastianBoe approved these changes

2023-05-05 10:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11053
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-09 06:35 UTC, mia-ko requested changes

2023-05-09 06:35 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +NCSDK-20688: For ChaChaPoly, incorrect tag will be produced if plaintext is empty.
```suggestion
NCSDK-20688: For ChaCha-Poly, incorrect tag will be produced if plaintext is empty
```

2023-05-09 06:35 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +  For encryption, empty plaintext will result in incorrect tag. For decryption, correct tags will not be accepted.
```suggestion
  For encryption, empty plaintext will result in incorrect tag.
  For decryption, correct tags will not be accepted.
```

2023-05-09 06:35 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +NCSDK-20688: For AES GCM, calling psa_aead_update_ad multiple times will result in an incorrect tag on CryptoCell.
```suggestion
NCSDK-20688: For AES GCM, calling ``psa_aead_update_ad`` multiple times will result in an incorrect tag on CryptoCell
```
Or is psa_aead_update_ad a function or something we can link to using e.g. :c:func:...?

2023-05-09 06:35 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +  It is only supported to feed the additional data for AES GCM once using the CrypoCell backend.
```suggestion
  It is only supported to feed the additional data for AES GCM once using the CryptoCell backend.
```

2023-05-10 06:27 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +NCSDK-20688: For AES GCM, calling psa_aead_update_ad multiple times will result in an incorrect tag on CryptoCell.
Oki, I see rendering is not correct using :c:func:, so we will have to use `` instead.

2023-05-10 06:29 UTC, mia-ko requested changes

2023-05-10 06:29 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +NCSDK-20688: For AES GCM, calling c:func:`psa_aead_update_ad` multiple times will result in an incorrect tag on CryptoCell
```suggestion
NCSDK-20688: For AES GCM, calling :c:func:`psa_aead_update_ad` multiple times will result in an incorrect tag on CryptoCell
```

2023-05-10 06:29 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +NCSDK-20688: For AES GCM, calling c:func:`psa_aead_update_ad` multiple times will result in an incorrect tag on CryptoCell
```suggestion
NCSDK-20688: For AES GCM, calling :c:func:`psa_aead_update_ad` multiple times will result in an incorrect tag on CryptoCell
```

2023-05-10 12:45 UTC, mia-ko approved these changes

2023-05-10 13:03 UTC, merged