Extended ps
nrfconnect/sdk-nrf pull request #11079
Opened 2023-05-08 08:44 UTC by ajayparida

Listen interval parameters from user/app

2023-05-08 08:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11079/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11079/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11079/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-08 08:57 UTC, sachinthegreen requested changes

2023-05-08 08:57 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +						       sizeof(*set_ps_wake_interval_cmd));
Indentation

2023-05-08 08:57 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +	if (!dev || !params) {
Add an error message

2023-05-08 08:57 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +		LOG_ERR("%s: wifi_nrf_fmac_ failed\n", __func__);
wifi_nrf_fmac_ should be wifi_nrf_fmac_set_ps_wake_interval

2023-05-08 08:57 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +				      bool ps_wakeup_mode)
Indentation

2023-05-08 10:57 UTC, krish2718 requested changes
* PS is an acronym, so, should be all caps.
* the commit log says `set as received from f/w` but should be ` set as received from Zephyr` ?

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +		}
Using an intermediate variable a single invocation should suffice.

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + *
```suggestion
 * @details This function is used to configure PS wakeup mode, either DTIM Interval or Lister interval based . Default is DTIM interval based mode.
 *
```

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * @brief Configure WLAN ps wakeup mode to DTIM or listen interval.
```suggestion
 * @brief Configure WLAN PS wakeup mode to DTIM interval or listen interval.
```

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw/host_rpu_umac_if.h
> +/* As per hardware design for power efficiency
I don't think this is has to be with hardware design, but I might be wrong, can we elaborate on this? The comment should explain why 3, it now just explains that it is 3.

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * @brief Configure WLAN ps to dtim or listen interval.
wrong description

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * @param[in] ps_wake_interval Enable listen interval based ps(default dtim based)
Description looks wrong, we now have a separate mode, so, this should just be interval, no?

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +		if (status != WIFI_NRF_STATUS_SUCCESS) {
All status checks can be moved out of switch, we can just dump `%s: Configuring %d failed, __func__, params->type`, makes code cleaner

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> -int wifi_nrf_set_ps_wake_interval(const struct device *dev,
This is a fixup commit, as this function changes in previous commit, so, either fix or squash/fixup these two commits.

2023-05-08 10:57 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> - *
unnecessary whitespace

2023-05-09 07:41 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/4c765eaad4953cf08c7bf2b1fc3cbff7383d05ff | https://github.com/nrfconnect/sdk-zephyr/pull/1162 | [nrfconnect/sdk-zephyr#1162/files](https://github.com/nrfconnect/sdk-zephyr/pull/1162/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-05-09 08:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11079
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-12 12:13 UTC, sachinthegreen approved these changes

2023-05-15 11:19 UTC, krish2718 approved these changes

2023-05-16 11:05 UTC, rlubos commented on west.yml
> +      revision: pull/1162/head
Let's do the final manifest update here (`dfd1fad51fa591b44ed44159e54a97625d317a99`).

Just need to wait for https://github.com/nrfconnect/sdk-nrf/pull/11109 as it'll trigger conflict.

2023-05-16 11:22 UTC, rlubos commented
https://github.com/nrfconnect/sdk-nrf/pull/11109 was just merged, please rebase/update manfiest

2023-05-16 11:52 UTC, rlubos commented
The sdk-zephyr SHA should still be updated to `dfd1fad51fa591b44ed44159e54a97625d317a99`, otherwise it won't pick up the latest merged changes (from https://github.com/nrfconnect/sdk-zephyr/pull/1162)

2023-05-16 12:13 UTC, krish2718 commented
> The sdk-zephyr SHA should still be updated to `dfd1fad51fa591b44ed44159e54a97625d317a99`, otherwise it won't pick up the latest merged changes (from [nrfconnect/sdk-zephyr#1162](https://github.com/nrfconnect/sdk-zephyr/pull/1162))

I have pushed now, consolidated all `manifest-zephyr` PRs to this one.

2023-05-16 12:18 UTC, rlubos approved these changes

2023-05-17 07:15 UTC, rlubos commented
Merging, as it was agreed with @nordic-hani to merge this post RC1 tag.

2023-05-17 07:15 UTC, merged