doc: add busy topic with RST elements
nrfconnect/sdk-nrf pull request #11089
Opened 2023-05-08 13:38 UTC by b-gent

Updating the cheatsheet to create a busy topic.

2023-05-08 13:39 UTC, b-gent commented
I went through a lot of topics and this I found so far.

Two elements that cannot be inserted here and need to be checked in other topics is ``.. glossary::`` and ``.. toctree ::`` .

2023-05-08 15:26 UTC, greg-fer approved these changes

2023-05-09 05:23 UTC, peknis approved these changes

2023-05-09 08:09 UTC, umapraseeda commented
Don't we have to add numbered heading?

2023-05-09 08:29 UTC, umapraseeda commented on doc/nrf/templates/cheat_sheet.rst
>  * :c:func:`bt_hids_init`
How about the rest? 
* Structure: ``:c:struct:``
* Type: ``:c:type:``
* Enum (the list): ``:c:enum:``
* Enumerator (an item): ``:c:enumerator:``
* Structure member: ``:c:member:``

2023-05-09 08:34 UTC, umapraseeda commented on doc/nrf/templates/cheat_sheet.rst
> +
We have .. important::, .. warning::

2023-05-09 14:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11089
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-10 08:09 UTC, peknis requested changes

2023-05-10 11:41 UTC, b-gent commented
> One more missing element: .. toggle:: (example: https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11089/nrf/software_maturity.html#nrf5340-audio)

toggle added

2023-05-10 12:38 UTC, gmarull approved these changes

2023-05-10 12:38 UTC, merged