manifest: Update the Matter SDK version to 1.1.0.1 TAG
nrfconnect/sdk-nrf pull request #11084
Opened 2023-05-08 10:53 UTC by ArekBalysNordic

Update the Matter SDK version to 1.1.0.1 TAG to prepare the sdk_connectedhomeip version for NCS 2.4.0 release.

2023-05-08 10:53 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/0809166d47b61feb205acecb100cf5be7558b9e1 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/277 | [nrfconnect/sdk-connectedhomeip#277/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/277/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-05-08 11:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11084
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-11 09:44 UTC, greg-fer requested changes

2023-05-11 09:44 UTC, greg-fer commented on doc/nrf/protocols/matter/overview/dev_model.rst
> +|                 | - Overall enhancements and bugfixes for Matter Specification, Certification Test Plan, and Matter SDK            |                     |
```suggestion
|                 | - Enhancements and bug fixes for Matter Specification, Certification Test Plan, and the Matter SDK.            |                     |
```

2023-05-11 09:44 UTC, greg-fer commented on doc/nrf/protocols/matter/overview/dev_model.rst
> +|                 | - Overall enhancements and bugfixes for Matter Specification, Certification Test Plan, and Matter SDK            |                     |
```suggestion
|                 | - Enhancements and bug fixes for Matter Specification, Certification Test Plan, and the Matter SDK.            |                     |
```

2023-05-11 09:44 UTC, greg-fer commented on doc/nrf/protocols/matter/overview/dev_model.rst
> +| 1.1.0           | - Improved ICD support: more :ref:`ug_matter_configuring_optional_persistent_subscriptions`, improved monitoring | Unreleased          |
```suggestion
| 1.1.0           | - Improved ICD support: more :ref:`ug_matter_configuring_optional_persistent_subscriptions`, improved monitoring. | Unreleased          |
```
Can you expand ICD acronym to <name (ICD)>? "improved monitoring" of what?

2023-05-11 09:44 UTC, greg-fer commented on doc/nrf/protocols/matter/index.rst
> +| v2.3.99 (latest)         | :ref:`1.1.0 <ug_matter_overview_dev_model_support>` | 1.1.0.1                |
Looks good!

2023-05-11 12:01 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added device finish and device color attributes to the Basic Information cluster and added the proper entries in factory data set.
```suggestion
* Updated the Basic Information cluster with device finish and device color attributes and added the related entries in factory data set.
```

2023-05-11 12:09 UTC, greg-fer approved these changes

2023-05-11 12:38 UTC, LuDuda approved these changes

2023-05-11 12:38 UTC, LuDuda commented on doc/nrf/protocols/matter/overview/dev_model.rst
> +|                 | - Enhancements and bug fixes for Matter Specification, Certification Test Plan, and the Matter SDK.                            |                     |                     |
```suggestion
|                 | - Enhancements and bug fixes for Matter Specification, Certification Test Plan, and the Matter SDK.                            |                     |
```

2023-05-12 06:09 UTC, kkasperczyk-no reviewed
As far as I remember there are some differences regarding usage of generate.py script to generate source files. Could you make sure that guide in `adding_clusters.rst` is up to date and if not align it?

2023-05-12 06:12 UTC, kkasperczyk-no commented
> As far as I remember there are some differences regarding usage of `generate.py` script to generate source files. Could you make sure that guide in `adding_clusters.rst` is up to date and if not align it?

If you want to benefit from green CI we can also leave it as is and do a follow-up :laughing: But please in the end make sure the guide instructions are correct.

2023-05-12 06:16 UTC, kkasperczyk-no approved these changes

2023-05-12 07:06 UTC, merged