samples: bluetooth: nrf_dm: Added support for Thingy53
nrfconnect/sdk-nrf pull request #11116
Opened 2023-05-09 18:35 UTC by hlord2000

Adds overlay and configuration for Thingy53.

2023-05-09 18:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11116) before we can accept your contribution.<br/><hr/>**hlord2000** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=11116) it.</sub>

2023-05-09 18:35 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2023-05-11 10:17 UTC, greg-fer commented
Adding @peknis for related doc update monitoring. Can you coordinate with @KAGA164 and @grochu ?

2023-06-05 18:49 UTC, hlord2000 commented
Updating after 2.4.0 release. I have signed the CLA but it hasn't updated here.

2023-08-25 07:34 UTC, peknis requested changes

2023-08-25 07:34 UTC, peknis commented on samples/bluetooth/nrf_dm/child_image/hci_rpmsg/boards/thingy53_nrf5340_cpunet.overlay
> +	 * Note: Pay attention to select the same GPIO pins
```suggestion
	 * Note: Make sure to select the same GPIO pins
```

2023-08-25 07:34 UTC, peknis commented on samples/bluetooth/nrf_dm/child_image/hci_rpmsg/boards/thingy53_nrf5340_cpunet.overlay
> +	/* The selected pins will be used by Distance Measurement module for debug purposes.
```suggestion
	/* The selected pins will be used by the Distance Measurement module for debug purposes.
```

2023-08-25 07:34 UTC, peknis commented on samples/bluetooth/nrf_dm/boards/thingy53_nrf5340_cpuapp.overlay
> +  * Note: Pay attention to assign the same GPIO pins as those provide in network core DTS overlay.
```suggestion
  * Note: Make sure to assign the same GPIO pins as those provide in network core DTS overlay.
```

2023-08-25 07:34 UTC, peknis commented on samples/bluetooth/nrf_dm/boards/thingy53_nrf5340_cpuapp.overlay
> +  * Distance Measurement module for debug purposes.
```suggestion
  * the Distance Measurement module for debug purposes.
```

2023-10-19 16:29 UTC, closed without merging