bootloader: cmake: keys: Change from source dir to app config dir
nrfconnect/sdk-nrf pull request #11135
Opened 2023-05-11 10:34 UTC by nordicjm

Changes the base directory for signing keys to be based on the application configuration directory instead of the source directory.

2023-05-11 10:41 UTC, tejlmand requested changes
a big reason for this is to advocate better security practices, especially for applications where board configurations are divided into dedicated configuration folders, then we should highlight that in the commit messages.

something like:
>  bootloader: cmake: keys: Change from source dir to app config dir
>
> Changes the base directory for signing keys to be based on the
> application configuration directory instead of the source directory.
>
> For simple samples where APPLICATION_CONFIG_DIR is identical to APPLICATION_SOURCE_DIR, this change has no impact,
> but for applications where each board is having a dedication configuration folder, such as the nrf_desktop,
> then this change introduces a much better security practice because it now indicates that each board should have a unique private key.
> The current approach of sharing the private key across boards is not considered a good security practice.

2023-05-11 10:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11135/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11135/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11135/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-11 10:57 UTC, frkv commented
There is a chapter in documentation explaining how to [add a custom signing key](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/app_dev/bootloaders_and_dfu/bootloader_adding.html#adding-a-custom-signature-key-file) that should be updated as a result of this change.

This talks about relative paths of private keys like this "The relative path to the file from the application directory."

2023-05-11 13:58 UTC, MarekPieta approved these changes

2023-05-12 09:01 UTC, greg-fer approved these changes

2023-05-12 09:03 UTC, merged