Pmic npmx sample ldo
nrfconnect/sdk-nrf pull request #11165
Opened 2023-05-12 14:43 UTC by wilu-nordic

2023-05-12 14:47 UTC, mkleszcz-no approved these changes

2023-05-12 14:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11165/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11165/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11165/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-15 14:37 UTC, annakielar requested changes

2023-05-16 10:03 UTC, annakielar commented on samples/pmic/npmx/ldo/src/main.c
> +		/* Wait some time to stabilize and measure the output voltage. */
```suggestion
		/* Wait some time until the output voltage is stabilized, and measure it. */
```

2023-05-16 14:05 UTC, annakielar approved these changes

2023-05-17 15:24 UTC, closed without merging