doc: Added External flash memory and Modem trace flash backend
nrfconnect/sdk-nrf pull request #11167
Opened 2023-05-12 17:12 UTC by divipillai

Added following documentation:
External flash memory
Modem trace flash backend

2023-05-12 18:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11167
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-15 08:18 UTC, eivindj-nordic reviewed
Looks good!

2023-05-15 09:18 UTC, wiba-nordic requested changes

2023-05-15 09:18 UTC, wiba-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +See `nRF9160 DK board controller <nRF9160 DK board control section in the nRF9160 DK User Guide_>`_ and `External memory <External memory section in the nRF9160 DK User Guide_>`_ sections in the nRF9
```suggestion

See `nRF9160 DK board controller <nRF9160 DK board control section in the nRF9160 DK User Guide_>`_ and `External memory <External memory section in the nRF9160 DK User Guide_>`_ sections in the nRF9160 DK user guides for more details.
```

2023-05-15 09:18 UTC, wiba-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +To use the external flash memory on the nRF9160 DK v0.14.0 or later versions, you must program the board controller firmware v2.0.1 or higher by completing the following steps:
Should this bit use `includes/external_flash_nrf91.txt`?

2023-05-15 09:18 UTC, wiba-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +The application also needs configuration and devicetree options to use the external flash.
```suggestion
To use external flash, the application also needs to enable configuration and devicetree options.
```
Not quite happy with this version either, but it at least can't be read as devicetree options using external flash.

2023-05-15 09:18 UTC, wiba-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +If your application was built using |NCS|, you must define partitions using :ref:`partition_manager`.
```suggestion
If your application was built using the |NCS|, you must define partitions using :ref:`partition_manager`.
```

2023-05-15 09:18 UTC, wiba-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +The files which has ``external_flash`` as their region will have support for storing partitions in the external flash.
```suggestion
The files which have ``external_flash`` as their region will have support for storing partitions in the external flash.
```

2023-05-15 11:37 UTC, divipillai commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +   The new board controller firmware has been updated to enable routing by default (new DK versions?).
Isn't this sentence covered in the above points. Is it okay to remove this sentence.
Or, do we need add any other details (as a note) that the user needs to be made aware of?

cc: @gregersrygg.

2023-05-15 11:37 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +  The maximum available space is 0x800000 (8 MB).
Rephrased a bit. Please check.

2023-05-15 11:49 UTC, wiba-nordic approved these changes

2023-05-15 15:47 UTC, eivindj-nordic commented on doc/nrf/working_with_nrf/nrf91/nrf9160.rst
> +   The new board controller firmware has been updated to enable routing by default (new DK versions?).
Yes, I think the above should cover it.

2023-05-15 15:55 UTC, eivindj-nordic approved these changes

2023-05-18 11:59 UTC, merged