doc improvement: various doc fixes for 2.4 release
nrfconnect/sdk-nrf pull request #11208
Opened 2023-05-16 13:16 UTC by mia-ko

Various doc fixes before the 2.4 release

2023-05-22 11:42 UTC, mia-ko commented
Removed the changelog improvements from this PR like you suggested @umapraseeda.

2023-05-23 06:38 UTC, ludvigsj requested changes

2023-05-23 06:38 UTC, ludvigsj commented on samples/bluetooth/mesh/light_dimmer/README.rst
> +  * :file:`include/kernel.h``
Mismatched backtick counts. (Several in this file).

2023-05-23 06:58 UTC, ludvigsj approved these changes

2023-05-23 06:58 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11208/4/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11208/4/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-05-23 07:31 UTC, wiba-nordic approved these changes

2023-05-23 09:49 UTC, SebastianBoe approved these changes

2023-05-23 09:49 UTC, SebastianBoe approved these changes

2023-05-23 09:59 UTC, joerchan approved these changes

2023-05-23 14:48 UTC, merged