Bluetooth: mesh: fix in Light Dimmer sample docs
nrfconnect/sdk-nrf pull request #11286
Opened 2023-05-23 08:56 UTC by akredalen

Added a couple of missing models in the configuration list for Mesh Light Dimmer device.

2023-05-23 08:59 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11286/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11286/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-05-23 09:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11286
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-23 10:04 UTC, ludvigsj commented
I just discovered that the readme for this sample probably should mention somehow that the Thingy53 only has one button so that the scene selector is not functional when running on Thingy53. Could you fix that as well as part of this PR? Or should I create a separate one?

2023-05-23 11:16 UTC, mia-ko requested changes

2023-05-23 11:16 UTC, mia-ko commented on samples/bluetooth/mesh/light_dimmer/README.rst
> +* Configure the publication for all models to any same group.
```suggestion
* Configure the publication for all models to the same group.
  This can be any group.
```

2023-05-23 11:19 UTC, mia-ko requested changes

2023-05-23 11:48 UTC, ludvigsj approved these changes

2023-05-23 20:54 UTC, mia-ko approved these changes

2023-05-24 07:51 UTC, m-alperen-sener approved these changes

2023-05-24 07:59 UTC, merged