Bluetooth: Mesh: Fix Sensor Server sample
nrfconnect/sdk-nrf pull request #11296
Opened 2023-05-23 13:29 UTC by PavelVPV

2023-05-23 13:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11296/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11296/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11296/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-05-23 21:38 UTC, mia-ko requested changes

2023-05-24 07:28 UTC, m-alperen-sener approved these changes

2023-05-24 10:14 UTC, PavelVPV commented on samples/bluetooth/mesh/sensor_server/README.rst
>  * Bind the model to **Application Key 1**.
Added `on each element` like in light sample. Kept `model` without `s` like in light sample.

2023-05-24 10:15 UTC, mia-ko approved these changes

2023-05-24 12:07 UTC, merged