doc: Added working with PMICs section
nrfconnect/sdk-nrf pull request #11311
Opened 2023-05-24 09:56 UTC by aasinclair

Added Working with PMICs section to top level
Added nPM1300 features to new section

2023-05-25 16:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11311
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-26 10:37 UTC, peknis requested changes

2023-06-26 10:37 UTC, peknis commented on doc/nrf/working_with_pmic/npm1300/features.rst
> +It has two dual-mode buck regulators, two dual purpose LDO/load switches, 3 LED drivers and 5 GPIOs.
```suggestion
It has two dual-mode buck regulators, two dual purpose LDO/load switches, three LED drivers and five GPIOs.
```

2023-06-26 10:37 UTC, peknis commented on doc/nrf/working_with_pmic/npm1300/features.rst
> +nPM1300 is the perfect companion for nRF52, nRF53 series SoCs, and the nRF91 series SiP.
```suggestion
nPM1300 is the perfect companion for nRF52 and nRF53 Series SoCs, and the nRF91 series SiP.
```

2023-06-26 10:37 UTC, peknis commented on doc/nrf/working_with_pmic/npm1300/features.rst
> +It is ideal for compact and advanced IoT products such as advanced wearables and portable medical applications.
```suggestion
It is ideal for compact and advanced IoT products such as wearables and portable medical applications.
```

2023-06-26 10:37 UTC, peknis commented on doc/nrf/working_with_pmic/npm1300/gs.rst
> +If this is your first time developing with a Nordic DK, you should follow the appropriate getting started tutorial first:
```suggestion
If this is your first time developing with a Nordic DK, read the appropriate getting started tutorial first:
```

2023-06-26 10:37 UTC, peknis commented on doc/nrf/working_with_pmic/npm1300/gs.rst
> +Follow the detailed instructions in the :ref:`npm1300_fuel_gauge` sample to build the sample and flash it to the DK.
```suggestion
Follow the detailed instructions in the :ref:`npm1300_fuel_gauge` sample documentation to build the sample and flash it to the DK.
```

2023-06-26 11:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11311/14/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11311/14/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-06-26 14:33 UTC, WalkingTalkingPotato approved these changes

2023-06-26 14:33 UTC, WalkingTalkingPotato commented on doc/nrf/working_with_pmic/npm1300/gs.rst
> +* The EK `User Guide <nPM1300 EK User Guide_>`_ for detailed information related to the nPM1300 EK.
Page not available yet.

2023-06-27 04:59 UTC, peknis requested changes

2023-06-27 04:59 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* A new section "Working with PMICs", containing :ref:`ug_npm1300_features` and :ref:`ug_npm1300_gs`.
```suggestion
* A new section :ref:`ug_pmic`, containing :ref:`ug_npm1300_features` and :ref:`ug_npm1300_gs`.
```

2023-06-27 07:27 UTC, aasinclair commented on doc/nrf/links.txt
> +.. _`nPM1300 EK product page`: https://www.nordicsemi.com/Products/Development-hardware/nPM1300-EK
Linked pages will go live today

2023-06-27 09:14 UTC, peknis approved these changes

2023-06-27 10:36 UTC, b-gent approved these changes

2023-06-27 10:47 UTC, merged