Twt shell cmd doc update
nrfconnect/sdk-nrf pull request #11365
Opened 2023-05-29 12:17 UTC by ajayparida

2023-05-29 12:20 UTC, krish2718 commented on doc/nrf/working_with_nrf/nrf70/developing/powersave.rst
> +       | TWT interval - 52400 µs
should be `524000`

2023-05-29 12:20 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11365/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11365/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-05-29 12:31 UTC, sachinthegreen requested changes

2023-05-29 12:31 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +       | disable - Configure the Wi-Fi interface as station mode
Match description to the one from the shell

2023-05-29 12:31 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +       | enable - Configure the Wi-Fi interface as access point mode
Enable Access Point mode, with the following parameters: 
<List parameters from the shell>

2023-05-29 12:31 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +       | Currently access point mode is not supported
This should be a note, i.e. Note : Access point mode is presently unsupported.

2023-05-29 12:59 UTC, sachinthegreen approved these changes

2023-05-29 13:22 UTC, krish2718 approved these changes

2023-05-29 13:48 UTC, richabp requested changes

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | (Note: Access point mode is presently not supported.)
```suggestion
       | (Note that the Access Point mode is presently not supported.)
```

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | enable - Enable Access Point mode with below parameters
```suggestion
       | enable - Enable Access Point mode, with the following parameters:
```

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +     - | Connect to Wi-Fi AP with below parameters:
```suggestion
     - | Connect to the Wi-Fi AP with the following parameters:
```

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | <twt_interval: 1µs-2^31µs>
```suggestion
       | <implicit: 0/1> <announce: 0/1> <twt_wake_interval: 1 µs to 262144 µs>
       | <twt_interval: 1 µs to 2^31 µs>
```

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | <dialog_token: 1-255> <flow_id: 0-7>
```suggestion
       | <dialog_token: 1 - 255> <flow_id: 0 - 7>
```

2023-05-29 13:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | <dialog_token: 1-255> <flow_id: 0-7> <responder: 0/1> <trigger: 0/1>
```suggestion
       | <dialog_token: 1 - 255> <flow_id: 0 - 7> <responder: 0/1> <trigger: 0/1>
```

2023-05-29 14:01 UTC, krish2718 commented
@richabp  the help is taken from the source code, so, if you have comments then it needs to be fixed in upstream and then cherry-picked, so, for now this has to exactly match the help command and we can fix the help (and update everywhere) later.

2023-05-29 14:05 UTC, richabp commented
> @richabp the help is taken from the source code, so, if you have comments then it needs to be fixed in upstream and then cherry-picked, so, for now this has to exactly match the help command and we can fix the help (and update everywhere) later.
> 
> FYI its here https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/wifi/wifi_shell.c#L1059

Get it, thanks for clarifying.

2023-05-29 14:28 UTC, richabp approved these changes

2023-05-29 14:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11365
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-05-30 11:55 UTC, kittydepa approved these changes

2023-07-10 14:19 UTC, carlescufi commented
@ajayparida do you want to rebase this?

2023-07-12 07:39 UTC, merged