Add WFA quicktrack control application
nrfconnect/sdk-nrf pull request #11393
Opened 2023-06-01 12:01 UTC by krish2718

This application is useful to our customers going for their products certification using our qualified solutions.

2023-06-01 12:02 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| wfa-qt-control-app | N/A | https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc/commit/33e38ff2f27299f671685e1da58e96301573f6bf (main) | N/A |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-06-01 12:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11393/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11393/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11393/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-01 12:47 UTC, sachinthegreen approved these changes

2023-06-05 07:28 UTC, rlubos reviewed
What about the sample documentation? @richabp

2023-06-05 07:36 UTC, krish2718 commented
> What about the sample documentation? @richabp

Missed that, pushing now, thanks.

2023-06-07 09:59 UTC, kittydepa requested changes

2023-06-07 09:59 UTC, kittydepa commented on samples/wifi/wfa_qt_app/README.rst
> +Wi-Fi: WFA Quicktrack control app
```suggestion
Wi-Fi: WFA QuickTrack control application
```

2023-06-07 09:59 UTC, kittydepa commented on samples/wifi/wfa_qt_app/sample.yaml
> +  description: WFA Quicktrack control application
```suggestion
  description: WFA QuickTrack control application
```

2023-06-07 09:59 UTC, kittydepa commented on samples/wifi/wfa_qt_app/README.rst
> +This sample demonstrates how to use the WFA Quicktrack (WFA QT) library needed for Wi-Fi Alliance Quicktrack certification.
```suggestion
This sample demonstrates how to use the WFA QuickTrack (WFA QT) library needed for Wi-Fi Alliance® QuickTrack certification.
```

2023-06-07 09:59 UTC, kittydepa commented on samples/wifi/wfa_qt_app/README.rst
> +This sample acts as a control application for the WFA QT library, to be used for Wi-Fi Alliance Quicktrack certification. See `Wi-Fi Alliance Certification for nRF70 Series <Wi-Fi Alliance Certificat
```suggestion
This sample acts as a control application for the WFA QT library, to be used for Wi-Fi Alliance QuickTrack certification.
See `Wi-Fi Alliance Certification for nRF70 Series <Wi-Fi Alliance Certification for nRF70 Series_>`_
```

2023-06-08 06:34 UTC, kittydepa approved these changes

2023-06-08 09:00 UTC, merged