Bluetooth: Mesh: Make Sensor Observer fit nrf52832
nrfconnect/sdk-nrf pull request #11451
Opened 2023-06-06 14:28 UTC by ludvigsj

This lowers the RAM requirements for the Sensor Observer sample so that it fits on the nRF52832. This is done by:

  * Reverting stack sizes and ADV buffer counts to default (tested and works fine).
  * Disabling the `FLASH_SHELL` module, which allocates 8k of buffers for a flash testing command the sample doesn't need.

New RAM usage after these changes: 61182 B (93.36% of nRF52832).

2023-06-06 14:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11451/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11451/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11451/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-06 14:37 UTC, PavelVPV reviewed
Have you checked the sample with our system test?

2023-06-06 14:47 UTC, ludvigsj commented
> Have you checked the sample with our system test?

I have not. That test runs on the nRF52840 only, on CI. Should I manually run it on nRF52832 now, just to check?

2023-06-06 14:50 UTC, PavelVPV commented
> > Have you checked the sample with our system test?
> 
> I have not. That test runs on the nRF52840 only, on CI. Should I manually run it on nRF52832 now, just to check?

It would make sense I think if it doesn't take much time. Does it pass on 52840 and 5340 after this change?

2023-06-07 09:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11451
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-07 09:15 UTC, ludvigsj commented
> > > Have you checked the sample with our system test?
> > 
> > 
> > I have not. That test runs on the nRF52840 only, on CI. Should I manually run it on nRF52832 now, just to check?
> 
> It would make sense I think if it doesn't take much time. Does it pass on 52840 and 5340 after this change?

Passes on 52840. Is not marked as supported for nrf53.

2023-06-07 09:33 UTC, PavelVPV commented
> > > > Have you checked the sample with our system test?
> > > 
> > > 
> > > I have not. That test runs on the nRF52840 only, on CI. Should I manually run it on nRF52832 now, just to check?
> > 
> > 
> > It would make sense I think if it doesn't take much time. Does it pass on 52840 and 5340 after this change?
> 
> Passes on 52840. Is not marked as supported for nrf53.

But where is the build?

2023-06-07 10:10 UTC, ludvigsj commented
> > > > > Have you checked the sample with our system test?
> > > > 
> > > > 
> > > > I have not. That test runs on the nRF52840 only, on CI. Should I manually run it on nRF52832 now, just to check?
> > > 
> > > 
> > > It would make sense I think if it doesn't take much time. Does it pass on 52840 and 5340 after this change?
> > 
> > 
> > Passes on 52840. Is not marked as supported for nrf53.
> 
> But where is the build?

The test was run on the desk (which was easier than creating a test repo branch just to run a single test, I think), if that's what you mean. The sample is built by twister as well, compile only test.

2023-06-07 10:16 UTC, PavelVPV approved these changes

2023-06-07 10:21 UTC, m-alperen-sener approved these changes
looks good.

2023-06-07 10:23 UTC, ludvigsj commented
DNM until @mia-ko has had a look at my changelog entry

2023-06-07 11:13 UTC, mia-ko requested changes

2023-06-07 11:13 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed an issue where the sample would not fit in RAM on the nrf52dk_nrf52832 board.
```suggestion
  * Fixed an issue with the sample not fitting into RAM size on the nrf52dk_nrf52832 board.
```

2023-06-07 11:28 UTC, mia-ko approved these changes

2023-06-07 14:44 UTC, merged