applications: asset_tracker_v2: fix location_module build command
nrfconnect/sdk-nrf pull request #11469
Opened 2023-06-08 11:53 UTC by maxd-nordic

This patch fixes a build command in the docs that referred to a non-existent shield name.

2023-06-08 11:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11469/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11469/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-06-08 11:57 UTC, balaji-nordic requested changes

2023-06-08 11:57 UTC, balaji-nordic commented on applications/asset_tracker_v2/doc/location_module.rst
> -   west build -p -b nrf9160dk_nrf9160ns -- -DSHIELD=nrf7002ek_nrf7002 -DDTC_OVERLAY_FILE=nrf9160dk_with_nrf7002ek.overlay -DOVERLAY_CONFIG=overlay-nrf7002ek-wifi-scan-only.conf
Line 74 also needs update. There are also many other references to nrf7002ek_nrf7002 across NCS. Just do a search and replace across the tree :)

2023-06-08 12:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11469
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-09 08:50 UTC, divipillai approved these changes
Reviewed the .rst files, and occurrences of the nrf7002ek_nrf7002 shield are removed from NCS docs. LGTM.

2023-06-09 09:08 UTC, trantanen approved these changes

2023-06-09 09:09 UTC, rado17 approved these changes

2023-06-09 10:43 UTC, balaji-nordic approved these changes

2023-06-09 11:41 UTC, trantanen commented
> LGTM, But @carlescufi has raised an issue with the naming, so, we might go back to the `nrf7002ek_nrf7002` can we please hold off on this till we conclude the naming?

Whatever you decide, please make one final change so that all relevant parties agrees on the naming. It's not just about simple search and replace within nrf repository but also CI builds need to be changed in different repositories.
We've now seen `nrf7002_ek` -> `nrf7002ek_nrf7002` -> `nrf7002ek` so it's starting not to be fun anymore.

@krish2718 @carlescufi

2023-06-09 11:46 UTC, krish2718 commented
> > LGTM, But @carlescufi has raised an issue with the naming, so, we might go back to the `nrf7002ek_nrf7002` can we please hold off on this till we conclude the naming?
> 
> Whatever you decide, please make one final change so that all relevant parties agrees on the naming. It's not just about simple search and replace within nrf repository but also CI builds need to be changed in different repositories. We've now seen `nrf7002_ek` -> `nrf7002ek_nrf7002` -> `nrf7002ek` so it's starting not to be fun anymore.
> 
> @krish2718 @carlescufi

Sure, I understand, its not fun for us as well :), we will now get all concerned parties so that we can freeze the naming and of course will take care of making necessary changes in NCS and CTF.

2023-06-09 11:55 UTC, trantanen commented
> Sure, I understand, its not fun for us as well :), we will now get all concerned parties so that we can freeze the naming and of course will take care of making necessary changes in NCS and CTF.

There are builds / tests that are maintained by individual teams and they see in the morning that some builds/tests failed and see in the log that the shield name was invalid. Then they start changing their scripts so when these things are renamed, you cannot handle everything by yourself.

2023-06-12 07:15 UTC, SeppoTakalo approved these changes

2023-06-12 20:45 UTC, plskeggs approved these changes

2023-06-12 20:48 UTC, glarsennordic approved these changes

2023-06-13 07:20 UTC, sachinthegreen approved these changes

2023-06-15 11:59 UTC, krish2718 commented
The board and shield naming is now concluded and no other changes prorposed, so, this PR is good to go, thanks.

2023-06-19 14:43 UTC, merged