Scan handle unprogrammed dev
nrfconnect/sdk-nrf pull request #11481
Opened 2023-06-09 15:43 UTC by krish2718

2023-06-09 15:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11481/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11481/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11481/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-13 07:03 UTC, sachinthegreen requested changes

2023-06-13 07:03 UTC, sachinthegreen commented on samples/wifi/scan/src/main.c
> +		/* Set a local MAC address with Nordic OUI*/
Space between `OUI` and `*/`

2023-06-13 11:06 UTC, krish2718 commented on samples/wifi/scan/Kconfig
> +config WIFI_MAC_ADDRESS
That is a separate feature, the intention for this PR is to demonstrate a custom MAC assignment (if_down, assign MAC, if_up). Anyways, as that is in same area, I can add that feature as well to this PR.

2023-06-14 09:49 UTC, rado17 approved these changes

2023-06-15 08:03 UTC, merged