doc: sml: support for companion chips
nrfconnect/sdk-nrf pull request #11496
Opened 2023-06-12 14:10 UTC by gautesl

Added functionality to include companion chip dependencies as footnotes in the SML tables.

Since the generation of the tables and the data used in the tables are done separately, the doc preview of this PR will not reflect the changes. Instead, these are screenshots of a local build:
![image](https://github.com/nrfconnect/sdk-nrf/assets/23337250/afa0679a-c944-4ae0-bb9e-89534230f8ba)

![image](https://github.com/nrfconnect/sdk-nrf/assets/23337250/38c2a59a-eefe-4699-a82b-0910e538fd46)

2023-06-12 14:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11496
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-19 09:48 UTC, krish2718 commented on doc/_scripts/software_maturity/software_maturity_scanner.py
> +  is marked as indipendent of the companion chips for the given SoC. Otherwise
```suggestion
  is marked as independent of the companion chips for the given SoC. Otherwise
```

2023-06-19 09:54 UTC, krish2718 commented on doc/_extensions/software_maturity_table.py
> +                    if self.minimum_version(version, "0.2.0") and experimental[soc]:
As we are auto-detecting the format of `boards_and_shields` as `list` or `dict` this is already backwards compatible, why do we need this version check here? The version of the script is anyway bumped to `0.2.0`, so, won't this always be true?

2023-06-19 10:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11496/8/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11496/8/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-06-20 10:46 UTC, krish2718 approved these changes

2023-06-20 10:46 UTC, krish2718 commented on doc/_scripts/software_maturity/software_maturity_scanner.py
> +                # Dependencies are added together, or cleared if at least on instance has no dependencies
```suggestion
                # Dependencies are added together, or cleared if at least one instance has no dependencies
```

2023-06-20 13:19 UTC, carlescufi requested changes
Please add the Nordic 5-clause license to all .py files

2023-06-20 13:30 UTC, carlescufi approved these changes

2023-06-20 14:18 UTC, merged