manifest: Update zephyr
nrfconnect/sdk-nrf pull request #11495
Opened 2023-06-12 13:32 UTC by nordicjm

Updates zephyr repo to include a python path fix.

2023-06-12 13:33 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | [nrfconnect/sdk-zephyr@v3.3.99-ncs1](https://github.com/nrfconnect/sdk-zephyr/releases/tag/v3.3.99-ncs1) | https://github.com/nrfconnect/sdk-zephyr/pull/1204 | [nrfconnect/sdk-zephyr#1204/files](https://github.com/nrfconnect/sdk-zephyr/pull/1204/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-06-13 07:33 UTC, tejlmand requested changes
this seems to be a duplicate of #11494, except that this PR references the https://github.com/nrfconnect/sdk-zephyr/pull/1204 (which itself is a duplicate of https://github.com/nrfconnect/sdk-zephyr/pull/1203)

2023-06-14 06:35 UTC, nordicjm commented
> this seems to be a duplicate of #11494, except that this PR references the [nrfconnect/sdk-zephyr#1204](https://github.com/nrfconnect/sdk-zephyr/pull/1204) (which itself is a duplicate of [nrfconnect/sdk-zephyr#1203](https://github.com/nrfconnect/sdk-zephyr/pull/1203))

#11494: nordicjm wants to merge 1 commit into nrfconnect:main from nordicjm:pyfix1
#11495: nordicjm wants to merge 1 commit into nrfconnect:v2.4-branch from nordicjm:pyfix2

They are subtly different :)

2023-06-14 10:59 UTC, tejlmand approved these changes

2023-06-15 09:43 UTC, merged