samples: Merge Azure IoT Hub and Azure FOTA samples
nrfconnect/sdk-nrf pull request #11501
Opened 2023-06-13 09:16 UTC by jtguggedal

The azure_fota sample is removed and the FOTA functionality is
now shown in the azure_iot_hub sample instead.
This is done because there was a significant overlap in the
sample content and most applications will most likely want to
implement both IoT Hub communication and FOTA together.

2023-08-10 07:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11501/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11501/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11501/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-10 07:47 UTC, peknis requested changes

2023-08-10 07:47 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  FOTA using Azure IoT Hub is now demonstrated in :ref:`azure_iot_hub`.
```suggestion
  FOTA using Azure IoT Hub is now demonstrated in the :ref:`azure_iot_hub` sample.
```

2023-08-10 07:47 UTC, peknis commented on samples/net/azure_iot_hub/README.rst
> +#. In `Azure IoT Explorer`_ or Azure Portal, confirm that the device twin contains the updated application version in the ``reported.firmware.fwVersion`` field.
```suggestion
#. Confirm that the device twin contains the updated application version in the ``reported.firmware.fwVersion`` field in `Azure IoT Explorer`_ or `Azure Portal`_.
```

2023-08-10 08:12 UTC, peknis commented
Looks like the Azure FOTA sample doc has been linked to from a few other docs as well (my search for :ref: `azure_fota_sample` resulted in six hits). Please fix those as well.

2023-08-16 10:08 UTC, simensrostad approved these changes

2023-10-04 06:30 UTC, peknis requested changes

2023-10-04 06:30 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added FOTA support using :ref:`azure_fota`.
```suggestion
  * Added FOTA support using the :ref:`lib_azure_fota` library.
```

2023-10-04 06:30 UTC, peknis commented on samples/net/azure_iot_hub/README.rst
> +If you want to test FOTA, ensure that also the required credentials for the file server are provisioned and that the :kconfig:option:`CONFIG_AZURE_FOTA_SEC_TAG` Kconfig option is set accordingly.
```suggestion
If you want to test FOTA, ensure that also the required credentials for the file server are provisioned and the :kconfig:option:`CONFIG_AZURE_FOTA_SEC_TAG` Kconfig option is set accordingly.
```

2023-10-04 08:25 UTC, coderbyheart requested changes

2023-10-04 08:25 UTC, coderbyheart commented on samples/net/azure_iot_hub/README.rst
> +	            "host": "my-fota-server.comt",
```suggestion
	            "host": "example.com",
```

Use generic example domain.

2023-10-04 08:25 UTC, coderbyheart commented on samples/net/azure_iot_hub/README.rst
> +	        },
**question:** can't we use a fully qualified URL by now? AFAIR the download client is now able to use that?

2023-10-04 08:25 UTC, coderbyheart commented on samples/net/azure_iot_hub/README.rst
> +When the sample runs, the device boots, and the sample displays the following output in the terminal over UART on an nRF7002 DK:
*question:* Why is `nRF7002` relevant?

2023-10-04 08:25 UTC, coderbyheart commented on samples/net/azure_iot_hub/README.rst
> +	<inf> azure_fota: Attempting to download firmware (version 'v0.0.2-dev') from my-fota-server.com/firmware/app_update.bin
```suggestion
	<inf> azure_fota: Attempting to download firmware (version 'v0.0.2-dev') from example.com/firmware/app_update.bin
```

2023-10-04 08:25 UTC, coderbyheart commented on samples/net/azure_iot_hub/README.rst
> +	<inf> download_client: Connecting to my-fota-server.com
```suggestion
	<inf> download_client: Connecting to example.com
```

2023-10-04 09:37 UTC, peknis requested changes

2023-10-04 14:30 UTC, KajaKoren commented on samples/net/azure_iot_hub/README.rst
> +* :kconfig:option:`CONFIG_AZURE_FOTA_SEC_TAG` - Sets the security tag for TLS credentials when using HTTPS as the transport layer. See :ref:`certificates` for more details.
yes, it seems to reference the old README file of the Azure Fota sample.. I can move the certification text to this sample instead.

2023-10-04 14:36 UTC, KajaKoren commented on samples/net/azure_iot_hub/README.rst
> +* :kconfig:option:`CONFIG_AZURE_FOTA_SEC_TAG` - Sets the security tag for TLS credentials when using HTTPS as the transport layer. See :ref:`certificates` for more details.
or refer to the `prereq_connect_to_azure_iot_hub` instead, is being referred to in the credential reference anyway.

2023-10-09 12:47 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-2.3.0.rst
> +* azure_fota_sample sample:
```suggestion
* nRF9160: Azure FOTA sample:
```

2023-10-09 13:53 UTC, KajaKoren commented on doc/nrf/releases_and_maturity/releases/release-notes-2.3.0.rst
> +* azure_fota_sample sample:
Fixed

2023-10-10 06:10 UTC, peknis approved these changes

2023-10-11 07:14 UTC, coderbyheart approved these changes

2023-10-12 08:47 UTC, KajaKoren commented
A change added due to this change in azure-fota sample: [samples: cellular: azure_fota: use default C library](https://github.com/nrfconnect/sdk-nrf/commit/28c2e5f82b9103c82bc66f470d85183d0f5b4eee)

2023-10-12 09:25 UTC, KajaKoren approved these changes

2023-10-12 11:02 UTC, merged