drivers: wifi: Enable TCP/IP checksum offload by default
nrfconnect/sdk-nrf pull request #11516
Opened 2023-06-13 15:29 UTC by krish2718

This is now fully supported and working, so, making this default to reduce load on host processor.

Fixes SHEL-1683.

2023-06-13 15:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11516/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11516/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11516/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-14 06:35 UTC, srinivas1201 approved these changes

2023-06-14 07:46 UTC, rado17 approved these changes

2023-06-14 08:41 UTC, sachinthegreen approved these changes

2023-06-14 08:42 UTC, sachinthegreen requested changes
Can we add a Changelog entry for this?

2023-06-14 08:49 UTC, krish2718 commented
@krga2022 need your approval on this after running full test plan as this impacts all.

2023-06-14 09:12 UTC, krish2718 commented on doc/nrf/releases/release-notes-changelog.rst
> +* TCP/IP checksum offload is now enabled by default for the nRF70 series.
Shouldn't the alignment of second list match `A` in `Added`?

2023-06-14 09:15 UTC, kittydepa commented on doc/nrf/releases/release-notes-changelog.rst
> +* TCP/IP checksum offload is now enabled by default for the nRF70 series.
No, it should be nested as it is here: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases/release-notes-2.4.0.html#enhanced-shockburst-esb

There will be more added to this nested list by the next release as well.

2023-06-14 09:17 UTC, krish2718 commented on doc/nrf/releases/release-notes-changelog.rst
> +* TCP/IP checksum offload is now enabled by default for the nRF70 series.
Even there it looks aligned to `A`

```
* Added:

  * TCP/IP checksum offload is now enabled by default for the nRF70 series.
```

2023-06-14 09:18 UTC, krish2718 commented on doc/nrf/releases/release-notes-changelog.rst
> +* TCP/IP checksum offload is now enabled by default for the nRF70 series.
![image](https://github.com/nrfconnect/sdk-nrf/assets/100136718/f089c02b-489e-4d8c-bd33-bce8111d48fb)

2023-06-14 09:20 UTC, sachinthegreen approved these changes

2023-06-14 09:47 UTC, kittydepa approved these changes

2023-06-14 09:56 UTC, kittydepa commented on doc/nrf/releases/release-notes-changelog.rst
> +  * TCP/IP checksum offload is now enabled by default for the nRF70 series.
```suggestion
  * TCP/IP checksum offload is now enabled by default for the nRF70 Series.
```

2023-06-14 10:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11516
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-11 11:08 UTC, krish2718 commented
@krga2022 need your review on this, the UMAC changes are now merged, so, CI should pass.

2023-07-20 06:40 UTC, krga2022 approved these changes

2023-07-20 07:12 UTC, merged