drivers: wifi: Use signal field from RX events
nrfconnect/sdk-nrf pull request #11510
Opened 2023-06-13 13:03 UTC by ajayparida

For RSSI queries RPU only if no data is active.
If data is active maintains average signal strength and then provides it to WPA supplicant.

2023-06-13 13:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11510/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11510/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11510/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-13 14:20 UTC, sachinthegreen requested changes

2023-06-13 14:20 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +			LOG_ERR("%s: Failed to sen get station info command\n", __func__);
send*

2023-06-14 08:39 UTC, rado17 approved these changes

2023-06-14 09:18 UTC, sachinthegreen requested changes

2023-06-14 09:21 UTC, krish2718 requested changes

2023-06-14 09:21 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig.nrf700x
> +	int "RSSI stale timeout in milliseconds"
This can be elaborate than just converting the Kconfig to english.

2023-06-14 09:21 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +	vif_ctx_zep->rssi = (signal / MBM_TO_DBM); /* mBm to dBm */
```suggestion
	vif_ctx_zep->rssi = (signal / MBM_TO_DBM);
```

2023-06-14 09:21 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig.nrf700x
> +	default 100
Should the default be higher, say `1000` for ping case? Only when the STA is highly mobile this needs to be lower (and this should be explained in help).

2023-06-26 11:55 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	rssi_record_timestamp_ms = wifi_nrf_osal_time_elapsed_us(fmac_dev_ctx->fpriv->opriv,
```suggestion
	last_rssi_record_timestamp_ms = wifi_nrf_osal_time_elapsed_us(fmac_dev_ctx->fpriv->opriv,
```

2023-06-26 11:56 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +		LOG_ERR("%s: Failed to send get interface info command\n", __func__);
This looks unrelated and unnecessary.

2023-06-26 11:56 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
> +void wifi_nrf_process_rssi(void *vif_ctx,
```suggestion
void wifi_nrf_process_rssi_from_rx(void *vif_ctx,
```

2023-06-26 11:57 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig.nrf700x
> +	  If data is active(e.g. ping), driver stores the RSSI value from
```suggestion
	  If data is active (e.g. ping), driver stores the RSSI value from
```

2023-06-26 11:57 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig.nrf700x
> +	  as stored RSSI value at driver will be updated regularily.
```suggestion
	  as stored RSSI value at driver will be updated regularly.
```

2023-06-26 12:49 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	last_rssi_record_timestamp_ms = wifi_nrf_osal_time_elapsed_us(fmac_dev_ctx->fpriv->opriv,
Here and others `rssi_record_timestamp_ms` timestamp and ms doesn't make sense, is either a timestamp of a elapsed_ms?

2023-06-26 13:14 UTC, krish2718 approved these changes

2023-06-29 08:25 UTC, sachinthegreen approved these changes

2023-06-29 10:35 UTC, merged