Bluetooth: Mesh: Remove storage timers from models
nrfconnect/sdk-nrf pull request #11517
Opened 2023-06-13 15:57 UTC by PavelVPV

Each model instance allocates k_work structure that is used to postpone state storing. Mesh now provides new API that can be used to schedule storing model's data and a callback that is called upon timeout and where a model store its data.

This commit removes such dedicated timers from models and uses new mesh API with mesh settings thread to save some RAM for applications.

To control timeout use CONFIG_BT_MESH_STORE_TIMEOUT instead of CONFIG_BT_MESH_MODEL_SRV_STORE_TIMEOUT.

2023-06-14 08:21 UTC, Balaklaka reviewed
The BT_MESH_MODEL_SRV_STORE_TIMEOUT should be removed from the models *.rst files (doc).

2023-06-14 08:21 UTC, Balaklaka commented on subsys/bluetooth/mesh/light_hue_srv.c
>  	.settings_set = hue_srv_settings_set,
Should not this (together with the function) be within the CONFIG_BT_SETTINGS?

2023-06-14 08:21 UTC, Balaklaka commented on subsys/bluetooth/mesh/lightness_srv.c
>  #if IS_ENABLED(CONFIG_EMDS)
Could we put CONFIG_BT_SETTINGS and IS_ENABLED(CONFIG_EMDS) into one #if.

2023-06-14 09:23 UTC, alxelax commented
Hi @PavelVPV, it doesn't seem the changes are built. Please take a look at Jenkins log.

2023-06-14 12:49 UTC, alxelax requested changes
In general, it seems Ok to me. Need to fix CI

2023-06-14 12:50 UTC, ludvigsj requested changes

2023-06-14 12:50 UTC, ludvigsj commented on subsys/bluetooth/mesh/lightness_srv.c
> +	.pending_store = lightness_srv_pending_store,
Should be aligned with respect to `bt_mesh` prefix or not in these functions. I see the convention across files is a bit anarchy at the moment, but in a single file they should be aligned at least.

2023-06-15 06:13 UTC, Andrewpini approved these changes
LGTM 👍

2023-06-15 06:19 UTC, Andrewpini commented
And now I see that you also added xyl 👍 That was going to be my additional comment

2023-06-15 07:31 UTC, ludvigsj approved these changes

2023-06-16 07:43 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +    To control timeout for storing models states, use the :kconfig:option:`BT_MESH_STORE_TIMEOUT` Kconfig option instead.
```suggestion
  * The :kconfig:option:`BT_MESH_MODEL_SRV_STORE_TIMEOUT` Kconfig option, that is controlling timeout for storing of model states, is replaced by the :kconfig:option:`BT_MESH_STORE_TIMEOUT` Kconfig option.
```

2023-06-16 07:43 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +* Updated:
Move the entry under Libraries:

E.g.
Bluetooth libraries and services
--------------------------------

* :ref:`bt_mesh` library:

  * Updated:

    * The :kconfig:option:`BT_MESH_MODEL_SRV_STORE_TIMEOUT` Kconfig option, that is controlling timeout for storing of model states, is replaced by the :kconfig:option:`BT_MESH_STORE_TIMEOUT` Kconfig option.

2023-06-16 09:08 UTC, mia-ko approved these changes

2023-06-19 10:11 UTC, merged