Modem trace shell send uart
nrfconnect/sdk-nrf pull request #11582
Opened 2023-06-20 14:20 UTC by gregersrygg

Add shell command to send stored modem traces over UART when the device tree chosen node "nordic,modem-trace-uart" is specified.

This PR extends #11095 with a command to send stored modem traces to UART. This is useful when testing storage of modem traces and can be used for testing.

The chosen node name `nordic,modem-trace-uart` is the same as used in #10891. So that PR should get merged first.

2023-06-20 15:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11582
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-27 12:09 UTC, balaji-nordic requested changes

2023-06-27 12:09 UTC, balaji-nordic commented on samples/nrf9160/modem_trace_flash/src/dump_uart.h
> +static void print_traces(void);
```suggestion
void print_traces(void);
```

2023-06-27 12:09 UTC, balaji-nordic commented on samples/nrf9160/modem_trace_flash/src/dump_uart.c
> +static void print_traces(void)
```suggestion
void print_traces(void)
```

2023-06-27 12:09 UTC, balaji-nordic commented on samples/nrf9160/modem_trace_flash/src/main.c
> +
Spurious new line?

2023-06-27 12:09 UTC, balaji-nordic commented on samples/nrf9160/modem_trace_flash/src/main.c
> +		print_traces();
Please use a different name for this function. Now it looks like it calls itself.

2023-06-27 12:18 UTC, gregersrygg commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +To register an account and obtain the project key, refer to the :ref:`using_memfault` section of the :ref:`ug_memfault` guide.
@divipillai ?

2023-06-27 12:19 UTC, gregersrygg commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +This will free up the stored traces as they are sent.
As they are sent

2023-06-27 12:56 UTC, gregersrygg commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Moved modem_trace shell command from modem_shell sample into nrf_modem_lib to be used in any app with :kconfig:option:`CONFIG_SHELL` and :kconfig:option:`CONFIG_NRF_MODEM_LIB_TRACE` enabled.
Ah, the joy of PR dependencies 😞 This change is from #11095. You should only look at the last commit when reviewing this PR.

2023-06-27 13:01 UTC, gregersrygg commented on lib/nrf_modem_lib/shell/modem_trace_memfault.h
> +#define SHELL_MODEM_TRACE_MEMFAULT_H
This change belongs to #11095.

2023-06-27 13:01 UTC, gregersrygg commented on lib/nrf_modem_lib/shell/modem_trace_memfault.h
> +#endif /* SHELL_MODEM_TRACE_MEMFAULT_H */
This change belongs to #11095.

2023-06-27 13:02 UTC, gregersrygg commented on lib/nrf_modem_lib/shell/modem_trace_shell.c
> +	}
This change belongs to #11095.

2023-06-27 13:27 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +To register an account and obtain the project key, refer to the :ref:`using_memfault` section of the :ref:`ug_memfault` guide.
In PR https://github.com/nrfconnect/sdk-nrf/pull/11095/files, the docs were updates as : 

```suggestion
To send data to Memfault, you must have a `Memfault account <Memfault registration page_>`_, a project key, and :ref:`configure Memfault <ug_memfault_config>` in your application.
Refer to the :ref:`ug_memfault` guide for more information.
```

Please note the details about  remote debugging is mentioned in the Memfault user guide. May be we could change this as -

To send stored modem traces to Memfault, you must........

2023-06-27 13:27 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +This will free up the stored traces as they are sent.
Should be "after they are sent". I overlooked it. Thanks for pointing this out.

2023-06-29 11:25 UTC, balaji-nordic commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +A trace backend that can store modem traces is required to upload modem traces to the cloud.
okay. Fine by me. :)

2023-06-29 11:31 UTC, balaji-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Moved modem_trace shell command from modem_shell sample into nrf_modem_lib to be used in any app with :kconfig:option:`CONFIG_SHELL` and :kconfig:option:`CONFIG_NRF_MODEM_LIB_TRACE` enabled.
ah ok

2023-06-29 11:32 UTC, balaji-nordic commented on lib/nrf_modem_lib/shell/Kconfig
> +
ah okay. this is fine then

2023-06-29 11:34 UTC, balaji-nordic commented on lib/nrf_modem_lib/shell/modem_trace_shell.c
> +	}
okay. commented in that PR. Will resolve this.

2023-06-29 14:00 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +A trace backend that can store modem traces is required to upload modem traces to the cloud.
Addressed in PR https://github.com/nrfconnect/sdk-nrf/pull/11095

2023-06-29 14:00 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +To register an account and obtain the project key, refer to the :ref:`using_memfault` section of the :ref:`ug_memfault` guide.
Addressed in PR https://github.com/nrfconnect/sdk-nrf/pull/11095

2023-06-29 14:00 UTC, divipillai commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +This will free up the stored traces as they are sent.
Addressed in PR https://github.com/nrfconnect/sdk-nrf/pull/11095

2023-09-13 00:27 UTC, closed without merging