samples: bluetooth: mesh: dfu: Add DFU srv shell cmds for cancelling dfu
nrfconnect/sdk-nrf pull request #11612
Opened 2023-06-23 15:08 UTC by PavelVPV

It is possible that DFU Client and DFU Server states get desynchronized and cancelling DFU procedure from DFU Client using mesh dfd-cancel message is not possible. When running dfu target sample, it may get stuck in phase 2 and won't let to start a new DFU procedure.

This commit enables DFU server shell commands in the target sample to let a user cancel the ongoing DFU procedure.

2023-06-23 15:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11612/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11612/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11612/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-06-23 16:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11612
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-06-26 07:59 UTC, ludvigsj commented on samples/bluetooth/mesh/dfu/target/prj.conf
> +CONFIG_BT_MESH_SHELL_PROV=n
Check if we want to disable `CONFIG_FLASH_SHELL` as well, if both `CONFIG_FLASH` and `CONFIG_SHELL` is enabled implicitly after your change. It consumes 8k of RAM and we don't need it.

2023-06-26 09:56 UTC, mia-ko requested changes

2023-06-26 09:56 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Enabled Firmware Update Server shell commands to let a user cancel DFU on the target node.
```suggestion
  * Enabled Firmware Update Server shell commands allowing users to cancel DFU on the Target node.
```

2023-06-26 09:56 UTC, mia-ko commented on samples/bluetooth/mesh/dfu/target/README.rst
> +This sample enables the Firmware Update Server model shell commands using the :kconfig:`CONFIG_BT_MESH_SHELL_DFU_SRV` option.
```suggestion
This sample enables the Firmware Update Server model shell commands using the :kconfig:option:`CONFIG_BT_MESH_SHELL_DFU_SRV` Kconfig option.
```

2023-06-26 09:56 UTC, mia-ko commented on samples/bluetooth/mesh/dfu/target/README.rst
> +This allows to cancel the ongoing DFU transfer using `mesh models dfu srv rx-cancel` shell command if it gets stalled.
```suggestion
This allows cancelling of an ongoing DFU transfer using the ``mesh models dfu srv rx-cancel`` shell command, if the ongoing DFU transfer gets stalled.

```

2023-06-26 10:40 UTC, ludvigsj requested changes

2023-06-26 10:40 UTC, ludvigsj commented on samples/bluetooth/mesh/dfu/target/README.rst
> +This allows canelling of an ongoing DFU transfer using the ``mesh models dfu srv rx-cancel`` shell command, if the ongoing DFU transfer gets stalled.
```suggestion
This allows cancelling of an ongoing DFU transfer using the ``mesh models dfu srv rx-cancel`` shell command, if the ongoing DFU transfer gets stalled.
```

2023-06-26 10:56 UTC, mia-ko approved these changes

2023-06-26 10:57 UTC, ludvigsj approved these changes

2023-06-27 07:21 UTC, alxelax commented
Hm... What should a customer do if desynchronization happens in deployed devices in "the field"?
These changes are Ok but they seem mostly like developer hook to solve the problem in the workplace rather than the final product solution.
I guess, we need to provide an approach to how to do this from the mobile phone(or other customer front-end solution).
Probable custom command?

2023-06-27 07:26 UTC, alxelax approved these changes

2023-06-27 07:51 UTC, ludvigsj commented
> > Hm... What should a customer do if desynchronization happens in deployed devices in "the field"? These changes are Ok but they seem mostly like developer hook to solve the problem in the workplace rather than the final product solution. I guess, we need to provide an approach to how to do this from the mobile phone(or other customer front-end solution). Probably custom command?
> 
> It is possible to cancel DFU on any device by sending Firmware Update Cancel message. This is possible to do from the distributor sample as well, I missed that. So perhaps this change is not needed at all.

No, this is not possible. The distributor needs to be in a very specific state for it to allow you to send this message, it doesn't just allow you to send the message randomly to a given device with the current shell interface. Basically, it has to be in the middle of a transfer to that address for it to allow you to send the cancel message. Of course, if you end up out of sync, then you'll never be able to get back into this state, because the transfer will never start again because the target will return "busy" all the time until you cancel (which you can't do because you lost your state).

2023-06-27 07:53 UTC, PavelVPV commented
I will close the PR. Perhaps, when I created the issue, we didn't have DFU client shell commands, but now it is possible to call `mesh models dfu cli cancel <addr>` to cancel DFU on a specific target node. I think this may lead to wrong understanding of mesh DFU if this command will exist in the sample. I'll look if we need to additionally mention the canceling command on the dfu client side or in the dfu procedure guide.

2023-06-27 07:53 UTC, closed without merging

2023-06-27 07:58 UTC, PavelVPV commented
> > > Hm... What should a customer do if desynchronization happens in deployed devices in "the field"? These changes are Ok but they seem mostly like developer hook to solve the problem in the workplace rather than the final product solution. I guess, we need to provide an approach to how to do this from the mobile phone(or other customer front-end solution). Probably custom command?
> > 
> > 
> > It is possible to cancel DFU on any device by sending Firmware Update Cancel message. This is possible to do from the distributor sample as well, I missed that. So perhaps this change is not needed at all.
> 
> No, this is not possible. The distributor needs to be in a very specific state for it to allow you to send this message, it doesn't just allow you to send the message randomly to a given device with the current shell interface. Basically, it has to be in the middle of a transfer to that address for it to allow you to send the cancel message. Of course, if you end up out of sync, then you'll never be able to get back into this state, because the transfer will never start again because the target will return "busy" all the time until you cancel (which you can't do because you lost your state).

This is the shell command implementation which allows to call `bt_mesh_dfu_cli_cancel` for a specific device:
https://github.com/zephyrproject-rtos/zephyr/blob/a7498c39e2d34d33a463fc861f1f39f0a626b8da/subsys/bluetooth/mesh/shell/dfu.c#L788-L814

When `ctx` is provided (like in `cmd_dfu_tx_cancel`), `bt_mesh_dfu_cli_cancel` function will send the Firmware Update Cancel message to a specific device bypassing all states:
https://github.com/zephyrproject-rtos/zephyr/blob/a7498c39e2d34d33a463fc861f1f39f0a626b8da/subsys/bluetooth/mesh/dfu_cli.c#L1065-L1083

Firmware Update Server model will drop all states once it receives the message (unless it is already in idle state):
https://github.com/zephyrproject-rtos/zephyr/blob/a7498c39e2d34d33a463fc861f1f39f0a626b8da/subsys/bluetooth/mesh/dfu_srv.c#L374-L387

2023-06-27 08:57 UTC, ludvigsj commented
> I will close the PR. Perhaps, when I created the issue, we didn't have DFU client shell commands, but now it is possible to call `mesh models dfu cli cancel <addr>` to cancel DFU on a specific target node. I think this may lead to wrong understanding of mesh DFU if this command will exist in the sample. I'll look if we need to additionally mention the canceling command on the dfu client side or in the dfu procedure guide.

I _think_ that when this issue was created, the way the shell worked was that if you enabled DFD server, the DFD server took ownership of the DFU client, and the DFU client commands would become unavailable from the shell. If that is no longer the case, then I agree, we don't need this PR.

2023-06-27 09:09 UTC, PavelVPV commented
> > I will close the PR. Perhaps, when I created the issue, we didn't have DFU client shell commands, but now it is possible to call `mesh models dfu cli cancel <addr>` to cancel DFU on a specific target node. I think this may lead to wrong understanding of mesh DFU if this command will exist in the sample. I'll look if we need to additionally mention the canceling command on the dfu client side or in the dfu procedure guide.
> 
> I _think_ that when this issue was created, the way the shell worked was that if you enabled DFD server, the DFD server took ownership of the DFU client, and the DFU client commands would become unavailable from the shell. If that is no longer the case, then I agree, we don't need this PR.

Yes, now the commands are untied from the model instance. A user can choose any dfu client instance instantiated on a device.