drivers: wifi: FMAC API documentation update
nrfconnect/sdk-nrf pull request #11668
Opened 2023-07-03 07:17 UTC by VivekUppunda

This change is to update the doxygen documentation for FMAC API.

2023-07-03 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11668) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=11668) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=11668) it.</sub>

2023-07-03 07:19 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11668/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11668/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-EK-shell | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11668/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-03 07:24 UTC, krish2718 approved these changes

2023-07-04 12:50 UTC, sachinthegreen requested changes

2023-07-05 06:52 UTC, VivekUppunda commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + * @param data_config  Pointer to configuration of data queues.
completer

2023-07-05 06:53 UTC, VivekUppunda commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + * @param callbk_fns   Pointer to callback functions for addressing events
completed

2023-07-05 06:53 UTC, VivekUppunda commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *                     packet received from lower layer, scan result etc
completed

2023-07-05 06:53 UTC, VivekUppunda commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *	    - Initializes the RX Buffer Pool
completed

2023-07-05 07:21 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *	    - Get interface statistics using interface index.
```suggestion
 *	    - Get interface statistics using interface index \p if_idx.
```

2023-07-05 07:22 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *	     - the RPU firmware to Enable/Disable WLAN Power management.
```suggestion
 *	     - The RPU firmware to enable/disable WLAN power management.
```

2023-07-05 07:23 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + * This function is used to get PHY configuration from RPU firmware.
```suggestion
 * This function is used to get PHY configuration from the RPU firmware.
```

2023-07-05 07:25 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *	    - To configure parameters related to interface.
```suggestion
 *	    - To configure interface specific parameters on an interface identified by \p if_idx..
```

2023-07-05 07:25 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *	    - Configure parameters related to TWT setup.
```suggestion
 *	    - Configure TWT setup specific parameters.
```

2023-07-05 07:26 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
>   * @param if_idx Index of the interface on which the TWT parameters be set.
```suggestion
 * @param if_idx Index of the interface on which the TWT parameters are to be set.
```

2023-07-05 07:28 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *              - BAL layer device initialization
```suggestion
 *              - HAL layer device initialization
 *              - BAL layer device initialization
```

2023-07-05 07:28 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
> + *              - FW initialization and phy calibration data is sent to PHY
```suggestion
 *              - FW initialization and PHY calibration data is sent to PHY
```

2023-07-05 08:08 UTC, sachinthegreen approved these changes

2023-07-05 09:44 UTC, VivekUppunda commented
the CI run is failing for the check for test-sdk-wifi-EK-shell. CI failure reason is attached. As per discussion in NCS-CI chat - this is to be expected. 

[Yesterday 2:42 PM] Gadde, KranthiWi-Fi test-sdk-wifi-EK-shell/master CI Issue
Hi NCS CI .. If you find any Wi-Fi CI failing only because of test-sdk-wifi-EK-shell, then please ignore this . Recently we have merged this under a single Jenkinsplan now and is named as test-sdk-wifi,.. and we have removed this job totally .Tests will trigger on DK and EK using a single Jenkins plan ... If any of your PRs are failing only with this reason, request to please post in PR merge group mentioning this reason as status is correlated with given SHA.

please merge this PR .

Thanks and regards
Vivek
![PR-CI-Run-failure](https://github.com/nrfconnect/sdk-nrf/assets/134574280/ff67408d-8bd8-4ea1-8ab9-ca00631f7a03)

2023-07-06 10:34 UTC, merged