Bluetooth: Mesh: config options to use tfm and oberon
nrfconnect/sdk-nrf pull request #11778
Opened 2023-07-11 13:25 UTC by alxelax

PR adds configurtion options to use tf-m and Oberon as a default crypto engine for non-secure platforms
in mesh samples.

2023-07-11 13:28 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11778/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11778/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11778/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-11 14:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11778
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-11 14:18 UTC, joerchan requested changes

2023-07-11 14:18 UTC, joerchan commented on subsys/bluetooth/mesh/Kconfig
> +if BT_MESH_USES_TFM_PSA
config BT_MESH_USES_TFM_PSA
     bool
     select PSA_WANT_dep1
     select PSA_WANT_dep2

2023-07-11 14:18 UTC, joerchan commented on subsys/bluetooth/mesh/Kconfig
> +	default y
Please remove this, it's default y already.
We will make crypto_driver selection automatic based on PSA_WANT symbols, so the protocol shouldn't have to worry about this.

2023-07-11 21:26 UTC, joerchan approved these changes

2023-07-12 06:24 UTC, Andrewpini approved these changes

2023-07-12 06:41 UTC, alxelax commented
> Seems like thingy53_nrf5340_cpuapp_ns light_ctrl sample ran out of flash by quite a great deal according to CI. Do you know why?

Not yet. I try to figure out.

2023-07-12 07:59 UTC, PavelVPV approved these changes

2023-07-12 08:28 UTC, joerchan commented
> Seems like thingy53_nrf5340_cpuapp_ns light_ctrl sample ran out of flash by quite a great deal according to CI. Do you know why?

Thingy53 uses static partition layout and it's size is set to match TFM MINIMAL profile type.
So either this needs to set a new static partition file to support the crypto config of BT-Mesh, or the thingy53 NS should not be supported in these samples.

2023-07-12 09:36 UTC, PavelVPV commented
I guess changelog is required now

2023-07-12 09:42 UTC, alxelax commented
> I guess changelog is required now

What do you mean? just label or anything else?

2023-07-12 10:16 UTC, PavelVPV commented
> > I guess changelog is required now
> 
> What do you mean? just label or anything else?

https://github.com/nrfconnect/sdk-nrf/blob/2cfd6275046ba090460b19356563198084902cad/doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst?plain=1#L230-L235

2023-07-13 11:54 UTC, greg-fer requested changes
Some time ago we reworked how we talk about _ns build targets, also to make it clear that _non-secure_ is actually more secure than _secure_ :) This is the reason for edits, which now also point to the section that explains the difference.

2023-07-13 11:54 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support of Trusted Firmware-M(TF-M) PSA as crypot backend for mesh security toolbox for ``_ns`` platforms.
```suggestion
* Added support for Trusted Firmware-M (TF-M) PSA as the crypto backend for mesh security toolbox for the platforms with :ref:`CMSE enabled <app_boards_spe_nspe_cpuapp_ns>`.
```

2023-07-13 11:54 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Removed support of non-secure configuration for :ref:`zephyr:thingy53_nrf5340`.
```suggestion
  * Removed support for the configuration with :ref:`CMSE enabled <app_boards_spe_nspe_cpuapp_ns>` for :ref:`zephyr:thingy53_nrf5340`.
```
And similarly for other entries.

2023-07-13 14:39 UTC, PavelVPV approved these changes

2023-07-14 07:05 UTC, greg-fer approved these changes

2023-07-14 11:27 UTC, merged