Bluetooth: mesh: remove relative paths in samples
nrfconnect/sdk-nrf pull request #11796
Opened 2023-07-13 12:05 UTC by akredalen

Fixed an issue where samples copied via the VS Code extension did not compile due to relative paths in CMakeLists, referencing files outside the applications folder.

2023-07-13 12:09 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11796/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11796/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11796/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-13 13:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11796
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-13 14:12 UTC, Balaklaka approved these changes

2023-07-13 14:14 UTC, Balaklaka commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed an issue where samples copied via the VS Code extension did not compile due to relative paths in CMakeLists, referencing files outside the applications folder.
This should be pulled in with 2 spaces, as it does not have anything to to with sensor_client.

2023-07-13 14:42 UTC, PavelVPV reviewed
@greg-fer since @mia-ko is OOO, could you please look at the change in the release notes?

2023-07-13 14:42 UTC, PavelVPV approved these changes

2023-07-14 10:28 UTC, greg-fer requested changes

2023-07-14 10:28 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Fixed an issue where some samples copied via the VS Code extension did not compile due to relative paths in CMakeLists, referencing files outside the applications folder.
```suggestion
* Fixed an issue where some samples copied using the `nRF Connect for Visual Studio Code`_ extension would not compile due to relative paths in :file:`CMakeLists.txt`, which were referencing files outside of the applications folder.
```

2023-07-14 11:17 UTC, greg-fer approved these changes

2023-07-14 12:49 UTC, omkar3141 commented
@akredalen Did you get confirmation from someone in the vscode team that this solution works for the extension?

2023-07-14 13:07 UTC, akredalen commented
Needed rebase. Awaiting merge request until we get feedback from vscode team.

2023-07-18 09:22 UTC, merged