doc: nrf5340_audio: splic docs in multiple pages
nrfconnect/sdk-nrf pull request #11798
Opened 2023-07-13 13:07 UTC by greg-fer

Split the application documentation into multiple pages. OCT-2610.

2023-07-14 11:37 UTC, greg-fer commented
@gmarull , in this PR, I'd like to use `options-from-kconfig` in a doc subdirectory rather than in a README directly next to the .kconfig file.

Is there an option to define the `rel-path` for `options-from-kconfig`, so that the extension goes one dir level up to retrieve the Kconfig data?

2023-07-19 11:57 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11798
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-20 09:15 UTC, erikrobstad requested changes

2023-07-20 09:15 UTC, erikrobstad commented on applications/nrf5340_audio/doc/feature_support.rst
> +.. include:: /releases_and_maturity/software_maturity.rst
We don't need it to have the ".. toggle::" now

2023-07-20 09:15 UTC, erikrobstad commented on applications/nrf5340_audio/README.rst
> -Given the requirements for the Coordinated Set Identification Service (CSIS), make sure to change the Set Identity Resolving Key (SIRK) value when adapting the application.
Looks like this part has been removed now?

2023-07-21 08:18 UTC, alexsven commented
I see that none of the default values shows up for the different Kconfigs, I know they didn't do that before this PR either but is there a way to parse that and show it in the doc?

2023-07-21 08:23 UTC, alexsven approved these changes
Looks better now, not as overwhelming when first opening up the documentation

2023-07-21 08:35 UTC, rick1082 approved these changes

2023-07-21 08:55 UTC, erikrobstad approved these changes

2023-07-21 10:54 UTC, greg-fer commented
> I see that none of the default values shows up for the different Kconfigs, I know they didn't do that before this PR either but is there a way to parse that and show it in the doc?

I'll ask the people who coordinate this part of the docs.

2023-07-21 10:57 UTC, merged

2023-08-11 10:21 UTC, gmarull commented
> > I see that none of the default values shows up for the different Kconfigs, I know they didn't do that before this PR either but is there a way to parse that and show it in the doc?
> 
> I'll ask the people who coordinate this part of the docs.

are these sample level Kconfigs? If so, this is not supported.