Partition Manager: Support for Disk Access
nrfconnect/sdk-nrf pull request #11802
Opened 2023-07-13 14:38 UTC by de-nordic

2023-07-13 14:39 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/eb28632680089351c7bd4365cf3742bf7eff70d3 | https://github.com/nrfconnect/sdk-zephyr/pull/1243 | [nrfconnect/sdk-zephyr#1243/files](https://github.com/nrfconnect/sdk-zephyr/pull/1243/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-07-13 15:04 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11802/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11802/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11802/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-13 15:59 UTC, nordicjm commented
Could you post a configuration (and what sample you used) to test this? Tried with smp_svr and it builds but I get error 2 whilst trying to mount, tried other samples and it fell over with define/build failures when compiling (forcing PM to be enabled with `-DPM_SINGLE_IMAGE=y`)

2023-07-14 05:30 UTC, de-nordic commented
> Could you post a configuration (and what sample you used) to test this? Tried with smp_svr and it builds but I get error 2 whilst trying to mount, tried other samples and it fell over with define/build failures when compiling (forcing PM to be enabled with `-DPM_SINGLE_IMAGE=y`)

I have added temporary commit o top that provides dynamic configuration for partition manager for single SD named disk of minimal allowed size of 64kiB.
To test the setup, on nrf52840dk, you can just build the FAT sample from Zephyr with:
```
west build -d fat_test/ -b nrf52840dk_nrf52840 zephyr/samples/subsys/fs/fat_fs/  -DCONFIG_BOOTLOADER_MCUBOOT -DCONFIG_FLASH_MAP_CUSTOM=y
west flash -d fat_test
```

The additions, to partition, in dynamic configuration:
```
  affiliation: disk
  extra_params: {
    disk_name: "SD",
    disk_cache_size: 4096,
    disk_sector_size: 512,
    disk_read_only: 0
  }
```
is equivalent of 
```
  affiliation:
  - disk
  extra_params:
    disk_cache_size: 0x1000
    disk_name: SD
    disk_read_only: 0x0
    disk_sector_size: 0x200
```
in static.

2023-07-14 09:34 UTC, nordicjm approved these changes

2023-07-14 11:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11802
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-14 11:44 UTC, tmon-nordic approved these changes
Looks fine, but I think tech writers will want to revise the documentation part.

2023-07-18 13:29 UTC, greg-fer commented on scripts/partition_manager/partition_manager.rst
> +      :caption: Example of disk partition
```suggestion
The following code snippet shows an example of the disk partition configuration using the ``extra_params`` dictionary:

   .. code-block:: yaml
      :caption: Example of disk partition
```

2023-07-21 12:39 UTC, greg-fer approved these changes
Consider adding a changelog entry for the new arguments.

2023-07-24 14:19 UTC, FrancescoSer requested changes

2023-07-24 14:19 UTC, FrancescoSer commented on scripts/partition_manager/partition_manager.rst
> +   Currently, this feature is only used by the flash disk driver in Zephyr to generate disk objects for use with the Disk Access API, with the following extra parameters: ``disk_sector_size``, ``disk
```suggestion
   Currently, this feature is only used by the flash disk driver in Zephyr to generate disk objects for use with the Disk Access API, with the following extra parameters: ``disk_sector_size``, ``disk_cache_size``, ``disk_name``, and ``disk_read_only``.
```

2023-07-24 14:45 UTC, de-nordic commented on scripts/partition_manager/partition_manager.rst
> +          size: 65536
`extra_params` is addition to normal partition. Everything is at proper levels.

2023-07-25 14:49 UTC, carlescufi commented
@de-nordic your commit be428e2d8ad3270b4aabc6b8a69c9e8ee6aa74f4 does not seem to be part of `main` in `sdk-zephyr`?

2023-07-25 14:57 UTC, de-nordic commented
> @de-nordic your commit be428e2d8ad3270b4aabc6b8a69c9e8ee6aa74f4 does not seem to be part of `main` in `sdk-zephyr`?

Sorry, already fixed that. I have looked at incorrect git log, the commit is not needed at all.

2023-07-26 08:26 UTC, FrancescoSer approved these changes

2023-08-02 08:00 UTC, merged