applications: serial_lte_modem: add DTLS CID support
nrfconnect/sdk-nrf pull request #11836
Opened 2023-07-19 13:42 UTC by tomi-font

Additional minor changes include:
- Set a shorter connect/send timeout to #XUDPCLI.
- Improve the error logging and return codes around util_resolve_host().
- Fix a corner case in #XUDPSEND that could enter data mode even though there was no valid socket in use.
- Improve #XSSOCKETOPT error logging.

2023-07-19 13:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11836/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11836/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11836/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-20 06:52 UTC, SeppoTakalo commented on applications/serial_lte_modem/src/slm_at_udp_proxy.c
> +				goto cli_exit;
Why do we fail instead of just print out the status?

It is up to server configuration to accept the use of CID or not.

2023-07-20 07:23 UTC, SeppoTakalo commented on applications/serial_lte_modem/src/slm_at_udp_proxy.c
> +				goto cli_exit;
oh... I did not know that there is this weird distinction about socket commands and UDP client commands...

2023-07-20 07:23 UTC, SeppoTakalo approved these changes

2023-07-20 10:21 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/16721d9c09b2e37fc805fa992a7537211bd0836b | https://github.com/nrfconnect/sdk-nrfxlib/commit/360db807ed62d182c7d932802bb2f032e55cc318 (main) | [nrfconnect/sdk-nrfxlib@16721d9c..360db807](https://github.com/nrfconnect/sdk-nrfxlib/compare/16721d9c09b2e37fc805fa992a7537211bd0836b..360db807ed62d182c7d932802bb2f032e55cc318) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-07-20 11:28 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11836
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-20 11:37 UTC, wiba-nordic requested changes

2023-07-20 11:37 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
> +  It represents the error value according to the standard POSIX *errno* (or *EAI*).
What is EAI? A quick google didn't help me.

2023-07-21 06:08 UTC, wiba-nordic approved these changes
Looks good now.

2023-07-21 06:50 UTC, VTPeltoketo approved these changes

2023-07-21 06:50 UTC, VTPeltoketo commented on applications/serial_lte_modem/src/slm_at_commands.c
> +	int ret = UNKNOWN_AT_COMMAND_RET;
The PR looks good, just for curious: why this change?

2023-07-21 08:30 UTC, merged