application: serial_lte_modem: Read device local time
nrfconnect/sdk-nrf pull request #11857
Opened 2023-07-24 03:58 UTC by junqingzou

Add `#XCCLK` command to get device local time. As Zephyr does not support local time conversion, get UTC by `AT%CCLK?` then use time zone and daylight_saving info to calculate local time.

2023-07-24 04:01 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11857/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11857/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11857/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-24 05:40 UTC, wiba-nordic requested changes

2023-07-24 05:40 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +The ``<time>`` value returns a string indicating local time in the format "yy/MM/dd,hh:mm:ss+zz", where the characters, from left to right, indicate year, month, day, hour, minutes, seconds.
```suggestion
The ``<time>`` value returns a string indicating local time in the format "yy/MM/dd,hh:mm:ss+zz".
From left to right, the characters indicate the year, month, day, hour, minutes, and seconds.
```
The list leaves "zz" undefined.

2023-07-24 05:40 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +The ``<time_zone>`` value returns an integer indicating the difference, expressed in quarters of an hour, between the local time and GMT (value range from -48 to +48 and 99 for "not set").
```suggestion
The ``<time_zone>`` value returns an integer indicating the difference between the local time and GMT.
The difference is expressed in quarters of an hour, so the value ranges from ``-48`` to ``+48``, with the value ``99`` used to indicate the difference has not been set.
```

2023-07-24 05:40 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +The ``<daylight_saving_time>`` value returns an integer indicating below:
```suggestion
The ``<daylight_saving_time>`` value returns an integer indicating one of the following:
```

2023-07-24 05:40 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +* ``2`` - +2 hours adjustment of daylight-saving time.
```suggestion
* ``0`` - No adjustment for daylight saving time.
* ``1`` - +1 hour adjustment for daylight saving time.
* ``2`` - +2 hours adjustment for daylight saving time.
```
Grammatically daylight-saving time would be correct, but the convention is to write it without the dash.

2023-07-24 06:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11857
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-31 07:52 UTC, VTPeltoketo commented
Clear and straightforward addition. Firstly I just wondered why the user cannot use AT+CCLK and make the transform by him/herself. But then I noticed, that our CCLK is not standard one because the time zone is missing. Do you know why?
Moreover, the daylight mode is not supported in CCLK according to the standard 3GPP TS 27.007 V18.3.0 (2023-06)

Summa summarum: Do we need this feature in SLM or can we dig the local time from existing AT-commands?  

Current AT command using modem version 1.3.5:
AT+CCLK?
+CCLK: "23/07/31,07:31:47"

2023-07-31 08:19 UTC, junqingzou commented
> Clear and straightforward addition. Firstly I just wondered why the user cannot use AT+CCLK and make the transform by him/herself. But then I noticed, that our CCLK is not standard one because the time zone is missing. Do you know why? Moreover, the daylight mode is not supported in CCLK according to the standard 3GPP TS 27.007 V18.3.0 (2023-06)
> 
> Summa summarum: Do we need this feature in SLM or can we dig the local time from existing AT-commands?
> 
> Current AT command using modem version 1.3.5: AT+CCLK? +CCLK: "23/07/31,07:31:47"

It should, unless that network does not give the info to UE right after attach.
at+cclk?
+CCLK: "23/07/31,08:16:01+36"
OK

What's missing is daylight_saving_time (DST), which is added in Nordic proprietary %CCLK.

Zephyr does not support local date time as it has no time zone info.

2023-07-31 09:01 UTC, VTPeltoketo commented
ok, but when the %CCLK has all the needed information, do we need #XCCLK because the local time calculation is so simple?

2023-07-31 09:06 UTC, junqingzou commented
> ok, but when the %CCLK has all the needed information, do we need #XCCLK because the local time calculation is so simple?
If MCU is not Zephyr-based, we calculate for MCU with Zephyr API.
Originaly prepared as reference code for SoC-based application, i.e. how to calculate local datetime based on modem info.

2023-07-31 09:53 UTC, ChanduBoyapati commented
Hi Guys,
As per customer requirement, they need local time instead of UTC time. In India, we don't have day light saving mode and this command looks fine as per customer requirement. Our competitors have local time option in their modem. So, better we have this option in SLM and if required we will keep as internal command.

2023-07-31 10:11 UTC, VTPeltoketo commented
Just to clarify the need to myself: The UTC-local time conversion is very simple, just two lines of mathematics.

Is the root reason functions timeutil_timegm() and gmtime_r() which we can easily use inside SLM, but maybe not by the customer?

2023-08-01 01:21 UTC, junqingzou commented
> timeutil_timegm

API timeutil_timegm() is Zephyr time represemtation API,

2023-08-01 01:31 UTC, junqingzou commented
> 

API timeutil_timegm() is Zephyr time represemtation API, gmtime_r() is standard libc API. They are not the root reason, however, as any SoC app nRF91 could call them. For external MCU, there could be couterpart APIs to do the conversion to and from standard C time_t structure.

Since mode already has +CCLK and %CCLK, let's drop the idea of another #XCCLK to avoid confusion.

@ChanduBoyapati please ask your customer to do the calculation on MCU side following similar logic. The nrf_modem_at_scanf() could be replaced by sscanf() using the %CCLK? response as input.

2023-08-01 01:31 UTC, closed without merging

2023-08-01 04:26 UTC, VTPeltoketo commented
Ok, thank you