Bluetooth: Mesh: Fix dim to dark behavior
nrfconnect/sdk-nrf pull request #11903
Opened 2023-07-28 10:18 UTC by PavelVPV

According to E22980, section 6.1.2.2.2 of MshMDLd1.1, Delta Set and Move
Set can never dim the lightness value to zero.

2023-07-28 10:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11903/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11903/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11903/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-28 13:21 UTC, akredalen approved these changes
Looks good. Just some small doc requests.

2023-08-01 06:35 UTC, mia-ko requested changes

2023-08-01 06:35 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed an issue where the sample could return an invalid Light Lightness Status message if the transition time was evaluated to zero.
Looks good, just consider moving this bullet point before the one that starts with Removed. The order of changes is:
- Added
- Updated
- Fixed
- Removed

2023-08-01 06:35 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The Light Lightness Actual and Generic Power Level states of the :ref:`bt_mesh_lightness_srv_readme` and :ref:`bt_mesh_plvl_srv_readme` models can not dim to off as a result of binding with Gen
```suggestion
    * The Light Lightness Actual and Generic Power Level states of the :ref:`bt_mesh_lightness_srv_readme` and :ref:`bt_mesh_plvl_srv_readme` models cannot dim to off.
      This is due to binding with Generic Level state when receiving Generic Delta Set and Generic Move Set messages.
```

2023-08-01 12:39 UTC, ludvigsj approved these changes

2023-08-17 12:35 UTC, mia-ko approved these changes

2023-08-18 07:31 UTC, merged