net: lib: nrf_cloud: add missing AIR_QUAL handler to shadow encoder
nrfconnect/sdk-nrf pull request #11914
Opened 2023-07-31 19:06 UTC by glarsennordic

Prior to this commit, nrf_cloud_encode_service_info_ui erroneously ignores the air_quality member of nrf_cloud_svc_info_ui. This commit adds the missing handler, so that AIR_QUALITY is correctly enabled when updating shadow.

IRIS-6724

2023-07-31 19:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11914/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11914/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11914/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-07-31 19:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11914
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-07-31 23:22 UTC, jayteemo approved these changes

2023-08-02 04:59 UTC, wiba-nordic requested changes

2023-08-02 04:59 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Fixed bug preventing `AIR_QUAL` from being enabled in shadow UI service info.
```suggestion

  * Fixed:

    * A build issue that occurred when MQTT and P-GPS are enabled and A-GPS is disabled.
    * A bug preventing `AIR_QUAL` from being enabled in shadow UI service info.
```
"Fixed" can be used as its own bullet on the same level as "updated" in the changelog.

2023-08-07 07:48 UTC, wiba-nordic approved these changes

2023-08-08 07:00 UTC, peknis requested changes

2023-08-08 07:00 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * A bug preventing `AIR_QUAL` from being enabled in shadow UI service info.
```suggestion
    * A bug preventing ``AIR_QUAL`` from being enabled in shadow UI service info.
```

2023-08-08 17:24 UTC, plskeggs approved these changes

2023-08-09 05:38 UTC, peknis approved these changes

2023-08-11 07:04 UTC, merged