cmake: Set kernel version to NCS version
nrfconnect/sdk-nrf pull request #11956
Opened 2023-08-04 08:57 UTC by nordicjm

Sets the zephyr kernel version to the version of NCS so that the
    boot banner displays the correct NCS details instead of sdk-zephyr
    details

and

    manifest: Update sdk-zephyr revision
    
    Adds the boot banner override features which displays the NCS
    version

2023-08-04 08:57 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/c9d01d05ce83a8cec0fd60bf8e2ba27c1534d08f (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1265 | [nrfconnect/sdk-zephyr#1265/files](https://github.com/nrfconnect/sdk-zephyr/pull/1265/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-08-04 09:00 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11956/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11956/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11956/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-04 09:25 UTC, krish2718 approved these changes

2023-08-04 09:43 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11956
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-18 12:50 UTC, wiba-nordic requested changes

2023-08-18 12:56 UTC, nordicjm commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
>  |no_changes_yet_note|
Fixed

2023-08-21 12:09 UTC, tejlmand requested changes
temp blocking.

2023-09-07 11:05 UTC, tejlmand approved these changes
lgtm

2023-09-20 07:04 UTC, merged