samples: matter: define sample persistance subscription configuration
nrfconnect/sdk-nrf pull request #11954
Opened 2023-08-04 07:32 UTC by doublemis1

Definition of new configuration of light bulb matter sample and light switch matter sample needed to execute load memory tests.

2023-08-04 07:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11954/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11954/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11954/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-04 08:25 UTC, jnsgsr requested changes

2023-08-04 08:25 UTC, jnsgsr commented on samples/matter/light_bulb/sample.yaml
> +  sample.matter.light_bulb.persistence_subscription:
You have to select integration platforms, if you don't want it to run in integration builds you have to use quarantine configuration file. Maybe enable one of them for 7002 and another for 52840. I think the tag is redundant for now but it is a good idea to comment configurations if they are specific in testing context.

2023-08-04 08:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11954
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-07 08:38 UTC, kkasperczyk-no approved these changes

2023-08-11 14:39 UTC, jnsgsr commented on samples/matter/light_switch/sample.yaml
> +    tags: load
the tag will not be used, it is redundant

2023-08-11 14:39 UTC, jnsgsr commented on samples/matter/light_bulb/sample.yaml
> +    tags: load
Redundant

2023-08-11 14:39 UTC, jnsgsr commented on samples/matter/light_bulb/sample.yaml
> +  sample.matter.light_bulb.nrf7002_ek:
Should not be here I guess

2023-08-16 08:52 UTC, jnsgsr approved these changes

2023-08-16 10:16 UTC, merged