net: lib: nrf_cloud: filter local APs from Wi-Fi location req
nrfconnect/sdk-nrf pull request #11988
Opened 2023-08-08 23:25 UTC by jayteemo

Do not include access points with local MAC addresses in nRF Cloud location requests. The cloud will discard them.

Consolidate location request message generation into one function, nrf_cloud_obj_location_request_payload_add(), and remove nrf_cloud_location_req_json_encode().

IRIS-6733

2023-08-09 00:05 UTC, plskeggs approved these changes
LGTM

2023-08-09 00:18 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11988/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11988/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11988/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-09 00:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11988
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-09 06:10 UTC, peknis requested changes

2023-08-09 06:10 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * A new internal codec function, :c:func:`nrf_cloud_obj_location_request_payload_add`, which excludes local Wi-Fi access point MAC addresses from the location request.
```suggestion
    * A new internal codec function :c:func:`nrf_cloud_obj_location_request_payload_add`, which excludes local Wi-Fi access point MAC addresses from the location request.
```

2023-08-09 06:10 UTC, peknis commented on subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
> +/** @brief Build a WiFi positioning request in the provided cJSON object using the provided
```suggestion
/** @brief Build a Wi-Fi positioning request in the provided cJSON object using the provided
```

2023-08-09 06:10 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * :ref:`lib_nrf_cloud_coap` library for accessing nRF Cloud services using CoAP.
This item is needed here. I believe there is a separate changelog entry for this new library. Anyway, this library is not added to the nRF Cloud library.

2023-08-09 17:30 UTC, glarsennordic approved these changes

2023-08-09 17:30 UTC, glarsennordic commented on subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
> +			LOG_WRN("At least %d (non-local) APs required for Wi-Fi request",
``At least %d APs (with non-local MAC) required for Wi-Fi request``

2023-08-10 05:38 UTC, peknis approved these changes

2023-08-10 06:55 UTC, merged