manifest: Update Matter SDK to pull changes related to factory data
nrfconnect/sdk-nrf pull request #11980
Opened 2023-08-08 08:45 UTC by ArekBalysNordic

This PR enables factory data generation and usage by default in all NCS samples.

2023-08-08 08:45 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/834a21bf2b0f22b9e9af7adb6167041b3dbdebf8 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/314 | [nrfconnect/sdk-connectedhomeip#314/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/314/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-08-08 08:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11980/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11980/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11980/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-08 09:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11980
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-08 11:18 UTC, doublemis1 requested changes

2023-08-08 11:18 UTC, doublemis1 commented on samples/matter/lock/sample.yaml
> +  sample.matter.lock.no_dfu_no_fd:
no_dfu.no_fd
```suggestion
  sample.matter.lock.no_dfu.no_fd:
```

2023-08-08 11:18 UTC, doublemis1 commented on samples/matter/lock/sample.yaml
> +    extra_args: CONF_FILE=prj_no_dfu.conf CONFIG_CHIP_FACTORY_DATA=n CONFIG_CHIP_FACTORY_DATA_BUILD=n
```suggestion
    extra_args: CONF_FILE=prj_no_dfu.conf CONFIG_CHIP_FACTORY_DATA=n
      CONFIG_CHIP_FACTORY_DATA_BUILD=n
```

2023-08-08 12:35 UTC, doublemis1 commented
Please remove factory_data configuration file and remove from sample.yaml for applications/matter_weather_station

2023-08-09 07:10 UTC, greg-fer requested changes

2023-08-09 07:10 UTC, greg-fer commented on applications/matter_weather_station/configuration/thingy53_nrf5340_cpuapp/prj.conf
> +# Disable factory data that is enabled by default in Matter stack configuration
```suggestion
# Disable factory data that is enabled by default in the Matter stack configuration
```

2023-08-09 07:10 UTC, greg-fer commented on applications/matter_weather_station/configuration/thingy53_nrf5340_cpuapp/prj_release.conf
> +# Disable factory data that is enabled by default in Matter stack configuration
```suggestion
# Disable factory data that is enabled by default in the Matter stack configuration
```

2023-08-09 07:10 UTC, greg-fer commented on applications/matter_weather_station/sample.yaml
>    # Excluded in quarantine.yaml to limit resources usage in integration builds
```suggestion
  # Excluded in quarantine.yaml to limit resource usage in integration builds
```

2023-08-09 07:10 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Enabled build with factory data enabled for all samples.
Move this to line 380, as it applies to all samples.

2023-08-09 07:10 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Set factory data feature to be enabled by default.
```suggestion
* Set the factory data feature to be enabled by default in the Matter stack configuration.
```

2023-08-09 12:13 UTC, greg-fer approved these changes

2023-08-10 07:44 UTC, kkasperczyk-no reviewed
Should we consider adding it to the Matter bridge as well?

2023-08-10 14:14 UTC, doublemis1 commented on applications/matter_weather_station/sample.yaml
> +  applications.matter_weather_station.release.no_fd:
remove configuration release without factory data

2023-08-10 14:16 UTC, doublemis1 commented on applications/matter_weather_station/sample.yaml
> +  applications.matter_weather_station.debug.no_fd:
Can you add comment that this configuration need to be used for testing Thingy e.g. DFU between different Thingy apps?

2023-08-16 11:33 UTC, doublemis1 commented
should we add instruction how to disable factory data?
update factory data section?

2023-08-17 07:32 UTC, ArekBalysNordic commented
I've added the factory data description to the samples' docs. @greg-fer could you please look at the recent changes and verify whether everything is ok?

2023-08-18 08:14 UTC, greg-fer submitted a review, later dismissed

2023-08-18 08:14 UTC, greg-fer commented on samples/matter/lock/README.rst
> +To learn more about factory data, read the :doc:`matter:nrfconnect_factory_data_configuration` page in the Matter documentation.
```suggestion
In this sample, the factory data support is enabled by default for all build types except for the ``no_dfu`` build type.
This means that a new factory data set will be automatically generated when building for the target board.

To disable factory data support, set the following Kconfig options to ``n``:

   * :kconfig:option:`CONFIG_CHIP_FACTORY_DATA`
   * :kconfig:option:`CONFIG_CHIP_FACTORY_DATA_BUILD`

To learn more about factory data, read the :doc:`matter:nrfconnect_factory_data_configuration` page in the Matter documentation.
```
I think the example should not be needed. How to build is explained in other places, and the Kconfigs can be set to ``n`` in different places.

2023-08-18 08:14 UTC, greg-fer commented on samples/matter/lock/README.rst
> +   * ``factory_data.txt`` - a text file that contains QR Code Payload and Manual pairing code
```suggestion
When the factory data support is enabled, the onboarding information will be stored in the build directory in the following files:

   * The :file:`factory_data.png` file includes the generated QR code.
   * The :file:`factory_data.txt` file includes the QR Code Payload and the manual pairing code.
```

2023-08-18 14:04 UTC, jnsgsr commented on applications/matter_weather_station/sample.yaml
> +  # This configuration is used for testing DFU over BLE between different NCS
I suggest to only remove word "testing" as it is not solely for testing, that is for a usage scenario case to support.

2023-08-22 11:46 UTC, doublemis1 approved these changes

2023-08-22 12:06 UTC, jnsgsr requested changes

2023-08-22 12:06 UTC, jnsgsr commented on applications/matter_weather_station/sample.yaml
In NCS integration builds we need to build WS in debug configuration with factory data enabled, previously it was "factory_data" now it will be "debug". You need to remove "debug" in the quarantine configuration file https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine_integration.yaml#L38

2023-08-22 12:06 UTC, jnsgsr commented on samples/matter/lock/sample.yaml
> -  sample.matter.lock.factory_data:
You need to remove the entries in the quarantine configuration file here https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine_integration.yaml#L6 and here https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine_integration.yaml#L22

2023-08-24 12:27 UTC, jnsgsr approved these changes

2023-08-24 12:33 UTC, merged