Bluetooth: Mesh: support unknown range in ctl
nrfconnect/sdk-nrf pull request #11982
Opened 2023-08-08 11:07 UTC by alxelax

Commit adds support of unknown temperature range
for CTL model.

2023-08-08 11:09 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11982/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11982/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-11982/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-08 12:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-11982
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-10 12:30 UTC, ludvigsj commented on subsys/bluetooth/mesh/light_temp_srv.c
> +	if (range->min < BT_MESH_LIGHT_TEMP_MIN && range->min != BT_MESH_LIGHT_TEMP_UNKNOWN) {
I can't seem to get this to make sense ... wouldn't `range->min < TEMP_MIN` mean that `range->min != TEMP_UNKNOWN` is always true?

2023-08-10 14:15 UTC, ludvigsj approved these changes

2023-08-10 14:17 UTC, akredalen requested changes

2023-08-10 14:17 UTC, akredalen commented on subsys/bluetooth/mesh/light_ctl_internal.h
> +static inline uint16_t get_range_max(uin16_t max)
```suggestion
static inline uint16_t get_range_max(uint16_t max)
```

2023-08-10 14:17 UTC, akredalen commented on subsys/bluetooth/mesh/light_ctl_internal.h
> +static inline uint16_t get_range_min(uin16_t min)
```suggestion
static inline uint16_t get_range_min(uint16_t min)
```

2023-08-10 14:19 UTC, alxelax commented on subsys/bluetooth/mesh/light_ctl_internal.h
> +static inline uint16_t get_range_max(uin16_t max)
Ooops. :(  fixed

2023-08-10 14:21 UTC, akredalen approved these changes

2023-08-11 07:13 UTC, merged