samples: wifi: Add build support for nrf7001 DK board
nrfconnect/sdk-nrf pull request #12029
Opened 2023-08-14 09:19 UTC by D-Triveni

Add change to build scan, sta and radio_test samples for nrf7001 dk board.

Fixes SHEL-1627.

2023-08-14 09:22 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12029/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12029/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12029/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-24 13:24 UTC, sachinthegreen approved these changes

2023-08-24 13:27 UTC, krish2718 requested changes
Not adding 7001 to tests was intentional to minimize unnecessary twister tests, see https://github.com/nrfconnect/sdk-nrf/pull/10964#discussion_r1187179501

2023-08-25 04:40 UTC, D-Triveni commented on samples/wifi/sta/Kconfig
> +	depends on (BOARD_NRF7002DK_NRF5340_CPUAPP || BOARD_NRF7002DK_NRF7001_NRF5340_CPUAPP)
Will address and raise a new PR for this change.

2023-08-25 04:40 UTC, D-Triveni commented
> Not adding 7001 to tests was intentional to minimize unnecessary twister tests, see [#10964 (comment)](https://github.com/nrfconnect/sdk-nrf/pull/10964#discussion_r1187179501)

So, closing this PR.

2023-08-25 04:40 UTC, closed without merging

2023-08-25 07:07 UTC, krish2718 commented on samples/wifi/sta/Kconfig
> +	depends on (BOARD_NRF7002DK_NRF5340_CPUAPP || BOARD_NRF7002DK_NRF7001_NRF5340_CPUAPP)
You can just push to this PR, it will have a context.