[DRAFT] [DNM] Update rest device message sample
nrfconnect/sdk-nrf pull request #12026
Opened 2023-08-11 23:26 UTC by tony-le-24

Note: This PR based off another PR #11927 and should not be move out of draft before the other PR merged.

I updated the nrf_cloud_rest_device_message sample to use the Common Application Framework instead of DK library. Added DTS overlay for nrf9160dk_nrf9160_ns platform to have the LEDs compatible with CAF LED module.

@pdunaj Please ignore this PR, since it's a copy from my other PR. Seems like I cannot remove you as a reviewer.

2023-08-12 00:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12026
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-14 18:24 UTC, jayteemo approved these changes

2023-08-14 18:24 UTC, jayteemo commented on samples/cellular/nrf_cloud_rest_device_message/src/main.c
>  	return err;
```suggestion
	return 0;
```

2023-08-14 18:24 UTC, jayteemo commented on samples/cellular/nrf_cloud_rest_device_message/src/main.c
> +	if (event->key_id == (uint16_t)(BTN_NUM - 1)) {
you could move `LOG_DBG("Button %d pressed", BTN_NUM);` before the key_id check, so there is a log message for any button press?

2023-08-14 18:24 UTC, jayteemo commented on samples/cellular/nrf_cloud_rest_device_message/src/main.c
> +		LOG_ERR("Application Event Manager could not be initialized");
```suggestion
		LOG_ERR("Application Event Manager could not be initialized, error: %d", err);
```

2023-08-14 18:24 UTC, jayteemo commented on samples/cellular/nrf_cloud_rest_device_message/src/main.c
> +		LOG_ERR("Invalid led ID: %d", led_idx);
```suggestion
		LOG_ERR("Invalid LED ID: %d", led_idx);
```

2023-08-16 19:49 UTC, plskeggs approved these changes

2023-08-16 19:49 UTC, plskeggs commented on samples/cellular/nrf_cloud_rest_device_message/boards/nrf9160dk_nrf9160_ns.overlay
> +/* Copyright (c) 2023 Nordic Semiconductor ASA
We need to add support for the 9161 to all our samples. I've created a ticket for it: https://nordicsemi.atlassian.net/browse/IRIS-6848.

When that happens, there will need to be an overlay for that as well here, I assume.

2023-08-21 18:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12026/6/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12026/6/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12026/6/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-21 19:26 UTC, glarsennordic approved these changes

2023-08-21 19:26 UTC, glarsennordic commented on samples/cellular/nrf_cloud_rest_device_message/boards/nrf9160dk_nrf9160_ns.overlay
> +		label = "LED 1";
Zephyr has dropped support for the label property, so let's kill that from these device tree bindings

2023-08-21 19:29 UTC, tony-le-24 commented on samples/cellular/nrf_cloud_rest_device_message/boards/nrf9160dk_nrf9160_ns.overlay
> +	leds1 {
Probably yes. Nice catch :D

2023-08-22 05:25 UTC, peknis requested changes

2023-08-22 05:25 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Header files for buttons and LEDs definition required by :ref:`lib_caf` library.
```suggestion
    * Header files for buttons and LEDs definition required by the :ref:`lib_caf` library.
```

2023-08-22 05:25 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The sample to use :ref:`lib_caf` library instead of :ref:`dk_buttons_and_leds_readme` library.
```suggestion
    * The sample to use the :ref:`lib_caf` library instead of the :ref:`dk_buttons_and_leds_readme` library.
```

2023-08-22 05:25 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Displaying an error message when the sample fails to send alert to nRF Cloud.
```suggestion
    * Displaying an error message when the sample fails to send an alert to nRF Cloud.
```

2023-08-22 05:25 UTC, peknis commented on samples/cellular/nrf_cloud_rest_device_message/include/buttons_def.h
> + * information about pins forming keyboard matrix.
```suggestion
 * information about pins forming the keyboard matrix.
```

2023-08-22 05:25 UTC, peknis commented on samples/cellular/nrf_cloud_rest_device_message/include/buttons_def.h
> +/* This structure enforces the header file is included only once in the build.
```suggestion
/* This structure enforces the header file to be included only once in the build.
```

2023-08-22 05:25 UTC, peknis commented on samples/cellular/nrf_cloud_rest_device_message/include/leds_def.h
> +/* This configuration file is included only once from main module and holds
```suggestion
/* This configuration file is included only once from the main module and holds
```

2023-08-22 05:25 UTC, peknis commented on samples/cellular/nrf_cloud_rest_device_message/include/leds_def.h
> +/* This structure enforces the header file is included only once in the build.
```suggestion
/* This structure enforces the header file to be included only once in the build.
```

2023-08-23 05:11 UTC, peknis approved these changes

2023-08-24 07:26 UTC, merged