Applications: nrf5340_audio: Added audio ablk
nrfconnect/sdk-nrf pull request #12036
Opened 2023-08-15 08:51 UTC by koffes

to be squashed

2023-08-15 08:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12036/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12036/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12036/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-15 09:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12036
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-15 13:28 UTC, alexsven requested changes

2023-08-15 13:28 UTC, alexsven commented on include/audio_defines.h
> +#include <zephyr/kernel.h>
This is probably not needed, should most likely be types.h or something similar

2023-08-15 13:28 UTC, alexsven commented on include/audio_defines.h
> +	enum ablk_interleaved interleaved;
Should this be a bool?

2023-08-15 13:28 UTC, alexsven commented on include/audio_defines.h
> +	uint32_t frame_len_us;
Should we add number_of_frames? If we know how many frames are in the block, we can calculate the bitrate by using data_size and frame_len_us

2023-08-17 10:04 UTC, asbjornsabo requested changes
This looks generally good.
It seems quite tied to the LE Audio / ISO specs though - we may want to discuss how tied we want to be.
And we (now or later) need to have a discussion on our audio timing.
Also lots of comments on naming.

2023-08-17 10:48 UTC, koffes commented on include/audio_defines.h
> +	uint32_t sample_rate_hz;
I see no reason why we should limit this here. This structure is only to convey information.

2023-08-17 10:49 UTC, koffes commented on include/audio_defines.h
> +	uint32_t data_len_us;
It cannot if it is encoded.

2023-08-17 11:06 UTC, koffes commented on include/audio_defines.h
> +	uint32_t data_len_us;
We don't have the number of samples

2023-08-17 11:07 UTC, koffes commented on include/audio_defines.h
> +	uint8_t carrier_size;
bps = bits per second.

2023-08-17 11:11 UTC, koffes commented on include/audio_defines.h
> +	 */
Graham to comment, but I really don't see that we will ever need interleaved. I have removed it.

2023-08-17 11:14 UTC, koffes commented on include/audio_defines.h
> +	bool bad;
I can rename, but from the host this is called `bad_frame`

2023-08-17 11:17 UTC, koffes commented on include/audio_defines.h
> +	bool bad;
Renamed to `bad_data`

2023-08-21 08:16 UTC, asbjornsabo commented on include/audio_defines.h
>  #define _AUDIO_DEFINES_H_
As far as I can see, the only real thing that was in this file before was a single enum with the left and right audio channels (lines 17 - 25 after the commit).

I can agree that renaming the file may be outside the scope of this PR, but it should be done.

2023-08-21 08:20 UTC, asbjornsabo commented on include/audio_defines.h
> +	uint32_t sample_rate_hz;
As long as we are limiting it somewhere else ...
But I guess that typically the sampling frequency values defined in the LE Audio host will be used.

2023-08-21 08:23 UTC, asbjornsabo commented on include/audio_defines.h
> +	uint8_t carrier_size;
True.

But what about the "carrier_size", which the comment mainly was about?

2023-08-21 08:27 UTC, asbjornsabo commented on include/audio_defines.h
> +	uint32_t data_len_us;
It is (implicitly) there, in the audio_data.
There is now the possibility that the metadata will say one thing about how much data this is (in seconds), while the data will say something else (in seconds).

2023-08-21 10:01 UTC, asbjornsabo commented on include/audio_defines.h
> +	 * used channels. Metadata is not included in this figure.
Agreed to remove this added comment again.

2023-08-21 10:01 UTC, asbjornsabo commented on include/audio_defines.h
> +	uint32_t data_len_us;
Fixed by adjusting comment in audio_data

2023-08-21 12:11 UTC, koffes commented on include/audio_defines.h
> +	uint8_t carrier_size;
Changed after our discussion.

2023-08-21 12:21 UTC, asbjornsabo approved these changes
LGTM

2023-08-21 12:29 UTC, alexsven approved these changes

2023-08-21 14:11 UTC, merged