partition_manager.py: Fix a bug where 'align' spec was deleted.
nrfconnect/sdk-nrf pull request #12031
Opened 2023-08-14 13:23 UTC by oyvindronningstad

This happened in a case where two placement specs were identical. When disambiguating one of them, the alignment spec was not preserved.

Jira: NCSIDB-1032

2023-08-14 13:25 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12031/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12031/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12031/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-14 14:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12031
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-15 07:40 UTC, osaether approved these changes
LGTM :-)

2023-08-15 09:26 UTC, SebastianBoe approved these changes

2023-08-16 15:23 UTC, FrancescoSer requested changes

2023-08-16 15:23 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed a bug where 'align' spec was deleted.
```suggestion
  * Fixed a bug where the ``align`` spec was deleted.
```

2023-08-16 15:23 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    This would happen in cases where two 'placement' specs were identical.
```suggestion
    This would happen in cases where two ``placement`` specs were identical.
```

2023-08-16 15:23 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    When disambiguating one of them, the 'align' spec was not preserved.
```suggestion
    When disambiguating one of them, the ``align`` spec was not preserved.
```

2023-08-17 12:44 UTC, FrancescoSer approved these changes

2023-08-24 08:26 UTC, tejlmand approved these changes

2023-10-12 13:28 UTC, oyvindronningstad commented
Failing CI jobs have rebuilt successfully.

2023-10-17 12:11 UTC, rakons approved these changes

2023-10-17 12:12 UTC, merged