applications: nrf5340_audio: Added capabilities doc for the controller
nrfconnect/sdk-nrf pull request #12060
Opened 2023-08-17 10:50 UTC by erikrobstad

Based on CIS/BIS BAP tables.

2023-08-17 10:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12060/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12060/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12060/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-17 11:09 UTC, erikrobstad commented
Hmmm, compliance fails with "No binary files allowed.". I checked now and it does not look like there are other PDF files in the nrf folder.
Is this a blocker for using .pdf @greg-fer ?

2023-08-17 11:40 UTC, greg-fer requested changes
PDFs can't go into the main repo. I'll upload it to the FTP.

2023-08-17 13:12 UTC, koffes commented
@greg-fer: Should we then link to it? Can we have it as a markdown?

2023-08-18 07:22 UTC, greg-fer approved these changes

2023-08-18 10:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12060
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-18 10:56 UTC, alexsven requested changes

2023-08-18 10:56 UTC, alexsven commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +These are configurations like sample frequency, bitrate and number of retransmissions.
```suggestion
The relevant configurations are bitrate and number of retransmissions.
```
Sample frequency does not affect this, the packet on air can be 120 bytes regardless if it is sampled in 48kHz or 8kHz

2023-08-21 09:48 UTC, alexsven approved these changes

2023-08-21 10:28 UTC, FrancescoSer requested changes

2023-08-21 10:28 UTC, FrancescoSer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +are dependent on which configurations you use.
```suggestion
The number of Connected Isochronous Streams (CIS) you can use in a Connected Isochronous Group (CIG) and the number of Broadcast Isochronous Streams (BIS) you can use in a Broadcast Isochronous Group (BIG) are dependent on which configurations you use.
```

2023-08-21 10:28 UTC, FrancescoSer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +For the matrix of supported CIS in a CIG and BIS in a BIG, see the `Capabilities for the LE Audio Controller Subsystem for nRF5340`_ document, which is based on the Basic Audio Profile (BAP) tables.
```suggestion
See the `Capabilities for the LE Audio Controller Subsystem for nRF5340`_ document for a matrix table listing the supported CIS in a CIG and the supported BIS in a BIG.
The document is based on the Basic Audio Profile (BAP) tables.
```

2023-08-21 10:28 UTC, FrancescoSer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +   The LE Audio controller for nRF5340 associated with this version of the |NCS| comes with the QDID #181316.
```suggestion
   The LE Audio controller for nRF5340 associated with this version of the |NCS| comes with the QDID ``#181316``.
```

2023-08-21 10:34 UTC, erikrobstad commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +are dependent on which configurations you use.
Done

2023-08-21 10:35 UTC, erikrobstad commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +   The LE Audio controller for nRF5340 associated with this version of the |NCS| comes with the QDID #181316.
Done

2023-08-21 10:39 UTC, erikrobstad commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
> +For the matrix of supported CIS in a CIG and BIS in a BIG, see the `Capabilities for the LE Audio Controller Subsystem for nRF5340`_ document, which is based on the Basic Audio Profile (BAP) tables.
Done, with some modifications

2023-08-21 12:11 UTC, FrancescoSer approved these changes

2023-08-21 13:34 UTC, koffes approved these changes

2023-08-21 14:10 UTC, merged