doc: nrf70: Add traffic information
nrfconnect/sdk-nrf pull request #12100
Opened 2023-08-22 08:37 UTC by krish2718

Extend the usage profiles to include recommended network buffer configuration and expected throughput.

2023-08-22 09:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12100
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-13 15:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12100/6/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12100/6/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-09-15 11:12 UTC, richabp requested changes

2023-09-15 13:19 UTC, krga2022 commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/constrained.rst
> +Note: Throughputs measured, as shown in the table above, are based on tests conducted using nRF7002DK. These results represent the best throughput, averaged over three iterations, and were obtained u
Done

2023-09-15 13:23 UTC, krga2022 approved these changes

2023-09-15 13:26 UTC, bama-nordic approved these changes

2023-09-15 13:43 UTC, richabp approved these changes

2023-09-19 06:37 UTC, merged