mpsl: Do calibration from k_timer
nrfconnect/sdk-nrf pull request #12147
Opened 2023-08-28 09:53 UTC by hermabe

MPSL no longer does calibration itself and requires users to call `mpsl_calibration_timer_handle`.

2023-08-28 09:54 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/d31f8cd416669883354cdffdf20c8e028f05fbcf | https://github.com/nrfconnect/sdk-nrfxlib/pull/1068 | [nrfconnect/sdk-nrfxlib#1068/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1068/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-08-28 09:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12147/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12147/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12147/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-28 10:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12147
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-28 11:14 UTC, rugeGerritsen approved these changes

2023-08-28 11:44 UTC, vegu-nordic approved these changes

2023-08-28 11:52 UTC, rugeGerritsen requested changes
Please se the related comment in sdk-nrf-next

2023-08-28 13:20 UTC, hermabe commented
Updated to not use `k_timer`.

FYI: @e-rk

2023-08-28 13:21 UTC, rugeGerritsen approved these changes

2023-08-28 13:40 UTC, e-rk approved these changes

2023-08-29 07:44 UTC, hermabe commented
Rebased on main and updated manifest to point at nrfxlib main.

2023-08-29 12:03 UTC, merged