doc: update files to main for NCS 2.4.2
nrfconnect/sdk-nrf pull request #12161
Opened 2023-08-29 11:15 UTC by peknis

Updating known issues and adding release notes to the main branch.

2023-08-29 11:30 UTC, mariuszpos commented on doc/nrf/releases_and_maturity/known_issues.rst
> +.. rst-class:: v2-4-2 v2-4-1 v2-4-0 v2-3-0 v2-2-0 v2-1-4 v2-1-3 v2-1-2 v2-1-1 v2-1-0 v2-0-2 v2-0-1 v2-0-0 v1-9-2 v1-9-1 v1-9-0
Please remove v2-4-2 tag due to fix: https://github.com/nrfconnect/sdk-nrf/pull/12095

2023-08-29 12:07 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12161
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-31 06:47 UTC, mariuszpos approved these changes

2023-08-31 09:09 UTC, umapraseeda commented
Shouldn't NCSDK-13947 have 2.4.2 tag?

2023-08-31 09:21 UTC, umapraseeda requested changes
Update missing for shortcuts.txt

2023-08-31 09:23 UTC, umapraseeda commented
> Update missing for shortcuts.txt

Also for dm_adding_code.rst.

2023-08-31 10:20 UTC, peknis commented
> NCSDK-13947

No, this was fixed in 2.4.2.

2023-08-31 10:34 UTC, umapraseeda approved these changes

2023-08-31 11:54 UTC, b-gent approved these changes

2023-08-31 12:12 UTC, nordic-hani approved these changes

2023-08-31 12:37 UTC, rlubos approved these changes

2023-08-31 14:11 UTC, merged