samples: lwm2m_client: Server initiated bootstrap fix
nrfconnect/sdk-nrf pull request #12179
Opened 2023-08-30 12:04 UTC by jheiskan81

Disconnect event can't trig state changes because at bootsrap generate that disconnect event.

2023-08-30 12:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12179/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12179/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12179/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-08-30 14:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12179
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-08-31 05:12 UTC, peknis requested changes

2023-08-31 05:12 UTC, peknis commented on doc/nrf/releases/release-notes-2.4.2.rst
> +
```suggestion
Samples
=======

Cellular samples
----------------

:ref:`lwm2m_client` sample:

* Added missing ``lwm2m_rd_client_start()`` call error handling.

```
Move this before nrfxlib heading.

2023-08-31 06:18 UTC, jheiskan81 commented on doc/nrf/releases/release-notes-2.4.2.rst
> +
Thanks @peknis I have update docs

2023-08-31 06:18 UTC, peknis approved these changes

2023-08-31 07:15 UTC, merged