samples: openthread: Remove nrf52833 support for CLI and CoAP
nrfconnect/sdk-nrf pull request #12195
Opened 2023-08-31 09:17 UTC by maciejbaczmanski

Support for `nrf52833dk_nrf52833` target in openthread CLI and CoAP samples has been withdrawn. Updated project files accordingly.

2023-08-31 10:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12195
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-21 07:18 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12195/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12195/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12195/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-21 07:21 UTC, canisLupus1313 approved these changes

2023-09-21 07:26 UTC, wiba-nordic requested changes

2023-09-21 07:26 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  :ref:`coap_client_sample` and :ref:`coap_server_sample`.
```suggestion
* Removed support for the ``nrf52833dk_nrf52833`` build target in :ref:`ot_cli_sample`, :ref:`coap_client_sample` and :ref:`coap_server_sample`.
```

2023-09-21 07:29 UTC, pjasinski990 approved these changes
lgtm

2023-09-21 07:33 UTC, maciejbaczmanski commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  :ref:`coap_client_sample` and :ref:`coap_server_sample`.
done

2023-09-21 07:39 UTC, wiba-nordic approved these changes
Looks good to me.

2023-09-21 11:35 UTC, rlubos approved these changes

2023-09-21 11:35 UTC, merged