doc: wifi: Add Optimizing scan operation page to Developing ug
nrfconnect/sdk-nrf pull request #12233
Opened 2023-09-04 15:10 UTC by richabp

Add a new page on Optimizing scan operation to the Developing with nRF70 Series user guide.

SHEL-1757

2023-09-04 15:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12233
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-05 13:57 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12233/3/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12233/3/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-09-05 14:19 UTC, krish2718 reviewed
Should the signoff also include original authors?

2023-09-06 07:09 UTC, peknis commented
Should some of this belong to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/test_and_optimize/optimizing/memory.html?

2023-09-06 07:34 UTC, richabp commented
> Should the signoff also include original authors?

I think its a documentation page hence not required.
@sachinthegreen: Can you confirm?

2023-09-06 09:56 UTC, sachinthegreen commented
> > Should the signoff also include original authors?
> 
> I think its a documentation page hence not required. @sachinthegreen: Can you confirm?

I am not aware of the protocol here but seems ok to me that the signoff of original authors also should be included. In this case it would be @udaynordic , @sachinthegreen and @krish2718

2023-09-06 10:06 UTC, sachinthegreen requested changes

2023-09-06 10:06 UTC, sachinthegreen commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/scan_operation.rst
> +       | :c:enumerator:`bands`
Shouldn't these be clickable links (in this case pointing to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/connectivity/networking/api/wifi.html#c.wifi_scan_params.bands)

2023-09-06 10:18 UTC, richabp commented
> Should some of this belong to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/test_and_optimize/optimizing/memory.html or https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/test_and_optimize/optimizing/power.html?
> 
> We could maybe use some of the power optimization stuff as includes in the Power optimization section.

@sachinthegreen: Can you please advise?

2023-09-06 11:26 UTC, sachinthegreen commented
> > Should some of this belong to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/test_and_optimize/optimizing/memory.html or https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/test_and_optimize/optimizing/power.html?
> > We could maybe use some of the power optimization stuff as includes in the Power optimization section.
> 
> @sachinthegreen: Can you please advise?

I don't have a opinion on this. Maybe @ioannisg can advise.

2023-09-06 11:33 UTC, sachinthegreen requested changes

2023-09-06 11:33 UTC, sachinthegreen commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/scan_operation.rst
> +You can find the scan API reference in :ref:`zephyr:wifi_mgmt` in the Zephyr documentation.
This should be pointing to https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12233/zephyr/connectivity/networking/api/wifi.html#c.wifi_mgmt_ops.scan

2023-09-06 11:36 UTC, krish2718 commented
> > > Should the signoff also include original authors?
> > 
> > 
> > I think its a documentation page hence not required. @sachinthegreen: Can you confirm?
> 
> I am not aware of the protocol here but seems ok to me that the signoff of original authors also should be included. In this case it would be @udaynordic , @sachinthegreen and @krish2718

FYI, this would be adding below lines to the commit.

```
Signed-off-by: Sachin D Kulkarni <sachin.kulkarni@nordicsemi.no>
Signed-off-by: Uday Kannemadugu <Uday.Kannemadugu@nordicsemi.no>
Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
```
This acts as both legal ownership and also to track original authors.

2023-09-08 08:05 UTC, kittydepa requested changes
Small suggested changes

2023-09-08 08:43 UTC, kittydepa approved these changes

2023-09-08 13:02 UTC, sachinthegreen approved these changes

2023-09-08 14:56 UTC, ioannisg commented
I have a feeling that the diagrams will be easier to read if the X-axis text is written in the opposite direction, that is as the Y-axis text.

2023-09-11 08:05 UTC, richabp commented
> I have a feeling that the diagrams will be easier to read if the X-axis text is written in the opposite direction, that is as the Y-axis text. At least, for me it seems harder to read the bar labels as they are written now.

This is as per our style guide: https://nordicsemi.atlassian.net/wiki/spaces/TECHDOC/pages/120293046/Figure+guide. I have changed the direction of the text on the Y-axis.

@mirjaku : Can you provide guidance here?

2023-09-12 11:00 UTC, ioannisg commented
> @richabp @ioannisg The guideline to write vertical diagram texts from top to bottom has been in effect and implemented consistently in our diagrams for the better part of a decade, so for the sake of stylistic consistency I would not make an exception for this one diagram.

There needs to be an exception to this rule, IMHO, at least for this particular type of bar-graphs with lots of long texts in the x-axis, otherwise such graphs are very hard to read.

2023-09-12 11:42 UTC, merged