wifi: Add twt traffic gen support
nrfconnect/sdk-nrf pull request #12235
Opened 2023-09-04 18:42 UTC by chiranjeevi2776

Add generic traffic generation module and use that in the TWT sample to exchange data after TWT flow is established. This gives us fine grained control that will be used in upcoming enhancements where the traffic will be synchronized to TWT service periods.

2023-09-04 18:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12235/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12235/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12235/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-04 19:43 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12235
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-04 20:29 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/c7094146b5b47fd4da05ed773e0128e2e6a634e1 (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1295 | [nrfconnect/sdk-zephyr#1295/files](https://github.com/nrfconnect/sdk-zephyr/pull/1295/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-09-05 09:38 UTC, kittydepa requested changes

2023-09-05 09:38 UTC, kittydepa commented on samples/wifi/twt/README.rst
> +server running on a PC connected to the same access point (typically via Ethernet).
```suggestion
server running on a PC connected to the same access point (typically through Ethernet).
```
Please also combine this part with the link above (so the same sentence is all on the same line).

2023-09-05 09:38 UTC, kittydepa commented on samples/wifi/twt/README.rst
> +When traffic generator module is used with this sample, the traffic generator server must be running on a PC connected to the same access point (typically via Ethernet).
```suggestion

When the traffic generator module is used with this sample, the traffic generator server must be running on a PC connected to the same access point (typically through Ethernet).
```

2023-09-05 09:38 UTC, kittydepa commented on samples/wifi/twt/README.rst
> +The server source is available in the :file:`scripts/traffic_gen_server` file. This is a `python3` based server, so, you need to have `python3` installed on your PC.
```suggestion
The server source is available in the :file:`scripts/traffic_gen_server` file.
This is a `python3` based server, so, you need to have `python3` installed on your PC.
```

2023-09-05 10:40 UTC, krish2718 requested changes
Manifest update was removed in latest push. Please fix

2023-09-05 13:29 UTC, krish2718 approved these changes

2023-09-07 07:34 UTC, kittydepa commented on samples/wifi/twt/README.rst
> +server running on a PC connected to the same access point (typically through Ethernet).
Please move this to previous line (so the entire sentence is on one line).

2023-09-07 11:58 UTC, richabp requested changes

2023-09-07 11:58 UTC, richabp commented on samples/wifi/twt/README.rst
> +The server can be started by running the following command:
```suggestion
To start the server, run the following command:
```

2023-09-07 11:58 UTC, richabp commented on samples/wifi/twt/README.rst
> +This is a `python3` based server, so, you need to have `python3` installed on your PC.
```suggestion
This is a `python3` based server, so you must make sure that `python3` is installed on your PC.
```

2023-09-07 11:58 UTC, richabp commented on samples/wifi/twt/README.rst
> +Please use the ``-h`` option to see the help message for how to use the server.
```suggestion
Use the ``-h`` option to display the help message for how to use the server.
```

2023-09-12 13:45 UTC, richabp commented on samples/wifi/twt/Kconfig
> +	int "Overall Connection timeout i.e., time to be waited for a station to connect and get an IP address"
```suggestion
	int "Overall Connection timeout (time to be waited for a station to connect and get an IP address)"
```

2023-09-12 13:45 UTC, richabp commented on samples/wifi/twt/README.rst
> +This is a `python3` based server, so, you must make sure that `python3` is installed on your PC.
```suggestion
This is a `python3` based server, so you must make sure that `python3` is installed on your PC.
```

2023-09-12 13:45 UTC, richabp commented on samples/wifi/twt/README.rst
> +When the traffic generator module is used with this sample, the traffic generator server must be running on a PC connected to the same access point (typically through Ethernet).
Seems to be repetitive from line 25, so can remove it.
```suggestion
When the traffic generator module is used with this sample, the traffic generator server must be running on a PC connected to the same access point.
```

2023-09-12 13:45 UTC, richabp commented on samples/wifi/twt/modules/traffic_gen/Kconfig
> +config TRAFFIC_GEN_DURATION
Can we write all Kconfig Help in a similar way to make it consistent with other Kconfigs?

2023-09-14 08:14 UTC, richabp approved these changes

2023-09-15 10:32 UTC, D-Triveni approved these changes

2023-09-15 11:03 UTC, kittydepa approved these changes

2023-09-20 07:11 UTC, merged