doc: Add known issue for Advertising Providers
nrfconnect/sdk-nrf pull request #12264
Opened 2023-09-07 08:40 UTC by alstrzebonski

Adds known issue related to improper configuration of CONFIG_BT_ADV_PROV_FAST_PAIR_ADV_BUF_SIZE.
Links to commit with fix for the issue.

Jira: NCSDK-23315

2023-09-07 10:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12264
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-07 10:51 UTC, divipillai commented on doc/nrf/releases_and_maturity/known_issues.rst
> +NCSDK-23315: The :ref:`bt_le_adv_prov_readme` has improper range and default value of the :kconfig:option:`CONFIG_BT_ADV_PROV_FAST_PAIR_ADV_BUF_SIZE` Kconfig option.
```suggestion
NCSDK-23315: The :ref:`bt_le_adv_prov_readme` has incorrect range and default value for the :kconfig:option:`CONFIG_BT_ADV_PROV_FAST_PAIR_ADV_BUF_SIZE` Kconfig option.
```

2023-09-07 10:51 UTC, divipillai commented on doc/nrf/releases_and_maturity/known_issues.rst
> +
We need to have a new section "Bluetooth libraries and services" and this KI could be moved to that section as this library don't belong to "other libraries".

2023-09-07 10:51 UTC, divipillai commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  As a consequence of it, the :ref:`peripheral_fast_pair` sample reboots on assert when it has five Account Keys and starts advertising in the Fast Pair not discoverable advertising mode.
```suggestion
  Hence, the :ref:`peripheral_fast_pair` sample reboots on assert when it has five Account Keys and starts advertising in the Fast Pair not discoverable advertising mode.
```

2023-09-07 12:03 UTC, MarekPieta requested changes

2023-09-07 15:42 UTC, alstrzebonski commented
Addressed review comments.

2023-09-08 05:45 UTC, MarekPieta approved these changes

2023-09-08 13:09 UTC, mkapala-nordic approved these changes

2023-09-11 07:59 UTC, divipillai commented on doc/nrf/releases_and_maturity/known_issues.rst
> +NCSDK-23315: The :ref:`bt_le_adv_prov_readme` has incorrect range and default value for the :kconfig:option:`CONFIG_BT_ADV_PROV_FAST_PAIR_ADV_BUF_SIZE` Kconfig option.
```suggestion
NCSDK-23315: The :ref:`bt_le_adv_prov_readme` has an incorrect range and default value for the :kconfig:option:`CONFIG_BT_ADV_PROV_FAST_PAIR_ADV_BUF_SIZE` Kconfig option.
```

2023-09-11 07:59 UTC, divipillai commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  The buffer size has not been aligned to new Fast Pair not discoverable advertising data size after size of salt included in the data was increased from 1 byte to 2 bytes.
```suggestion
  The buffer size has not been aligned to the new Fast Pair not discoverable advertising data size after size of the salt included in the data was increased from 1 byte to 2 bytes.
```

2023-09-11 08:25 UTC, divipillai approved these changes
nits

2023-09-11 13:25 UTC, alstrzebonski commented
Addressed review comments.

2023-09-12 07:16 UTC, merged