Oct 2655 bt stream module
nrfconnect/sdk-nrf pull request #12290
Opened 2023-09-11 08:18 UTC by alexsven

2023-09-11 12:11 UTC, alexsven reviewed
Initial comments based on reviewing the two last commits only, since I didn't get to review those PRs last week

2023-09-11 12:11 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h
> +int broadcast_source_enable(void);
Remove. It seems this got messed up in a rebase in https://github.com/alexsven/sdk-nrf/pull/25/files#diff-f960e1ec977a994f52a902c0645a161e09aae73315c58ac9604efa66a04ca6f4R51-R56

2023-09-11 12:11 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
>  }
There should be a unicast_server_disable

2023-09-11 12:11 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.h
> + * @param [in] adv_buf_vacant	Number of vacant elements in @p adv_buf.
Formatting not correct

2023-09-11 12:11 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/Kconfig
>  choice BT_BAP_UNICAST_BAP_CONFIGURATION
All of the stuff below here should be moved to bt_stream/unicast/Kconfig

2023-09-11 12:11 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
>  	default 1
Code below related to unicast should be moved to bt_stream/unicast/Kconfig.default

2023-09-11 12:50 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
> +int broadcast_sink_enable(le_audio_receive_cb recv_cb)
The only thing this function does now is call initialize, so I suggest we just move the code from initialize here.

2023-09-12 06:55 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
> +};
I will remove in my testing branch

2023-09-12 06:55 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
> +#include <zephyr/bluetooth/audio/tmap.h>
I will remove in my testing branch

2023-09-12 06:58 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
> +	BT_BYTES_LIST_LE16(AVAILABLE_SOURCE_CONTEXT),
I will do this change in my test branch

2023-09-22 11:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12290
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-25 08:39 UTC, greg-fer commented
Discussed this with @erikrobstad , and when the PR is open and not in draft anymore, I'll work on the following updates:
- Review of the API docs in header files.
- Update to https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/nrf5340_audio/doc/firmware_architecture.html with new information about BT modules.

2023-10-02 14:16 UTC, greg-fer commented
@alexsven , my PR is merged. Please remember to pull edits. Thanks.

2023-10-02 14:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12290/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12290/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12290/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-05 08:09 UTC, greg-fer approved these changes

2023-10-06 10:39 UTC, erikrobstad commented
**Remember that the commit message must be changed before merging it to NCS main**

2023-10-06 10:40 UTC, erikrobstad requested changes
Commit message must be changed

2023-10-06 10:49 UTC, erikrobstad reviewed
Never mind

2023-10-10 09:49 UTC, koffes requested changes

2023-10-10 09:50 UTC, koffes approved these changes

2023-10-10 10:08 UTC, erikrobstad approved these changes

2023-10-10 10:13 UTC, Frodevan approved these changes

2023-10-10 12:32 UTC, merged