drivers: wifi: Bug fix of memory leak in interface up-down
nrfconnect/sdk-nrf pull request #12299
Opened 2023-09-11 12:22 UTC by kapbh

Memory allocated for a virtual interface in wifi_nrf_fmac_add_vif, is never freed in the corresponding wifi_nrf_fmac_del_vif. It results in the driver leaking 40 bytes of memory every time the networking interface is cycled.
Free the memory of vif_ctx in out: tag of wifi_nrf_fmac_del_vif.

2023-09-11 13:05 UTC, sachinthegreen requested changes

2023-09-11 13:05 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/default/fmac_api.c
> +	if (vif_ctx) {
Please add a blank line above this.

2023-09-12 04:11 UTC, sachinthegreen approved these changes

2023-09-12 04:12 UTC, VivekUppunda approved these changes

2023-09-12 07:15 UTC, merged