bluetooth: controller: Fix command complete
nrfconnect/sdk-nrf pull request #12327
Opened 2023-09-14 10:08 UTC by Tschet1

When HCI commands for legacy and extended commands are being used, a Command Disallowed error should be produced. In this case, the command complete event was missing the other (command specific) parameters in the event.

Added them.

2023-09-14 10:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12327/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12327/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12327/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-15 11:36 UTC, minkrg commented on subsys/bluetooth/controller/hci_internal.c
> +			generate_status_disallowed_command_complete_event(cmd_in, opcode);
I might be missing something, but the opcodes in `command_generates_command_complete_event ` are less than the ones in the newly added function `generate_status_disallowed_command_complete_event `
Shouldn't they be the same?

2023-09-19 11:00 UTC, de-nordic commented
@rugeGerritsen @minkrg Please review.

2023-09-19 11:14 UTC, rugeGerritsen requested changes
Discussed offline. Will see if we can combine with something in `is_host_using_legacy_and_extended_commands()` to reduce code size

2023-09-28 11:44 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_internal.c
> +	static enum type_of_adv_cmd type_of_adv_cmd_used_since_reset;
You could consider explicitly initializing `type_of_adv_cmd_used_since_reset` to `ADV_COMMAND_TYPE_NONE`

2023-09-28 11:44 UTC, rugeGerritsen approved these changes

2023-09-29 05:37 UTC, minkrg approved these changes

2023-09-29 06:48 UTC, merged