doc: improve ps ug
nrfconnect/sdk-nrf pull request #12386
Opened 2023-09-21 06:50 UTC by kittydepa

[SHEL-1740](https://nordicsemi.atlassian.net/browse/SHEL-1740)
Improve [Powersave Wi-Fi UG](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.html) for style and readability, as requested.

2023-09-21 06:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12386/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12386/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-09-21 08:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12386
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-21 09:53 UTC, krish2718 approved these changes
Thanks @kittydepa , looks much better.

2023-09-22 09:51 UTC, sachinthegreen approved these changes

2023-09-25 14:16 UTC, richabp requested changes
Some minor issues.

2023-09-25 14:16 UTC, richabp commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst
> +The two key parameters of TWT are TWT Wake Duration, and TWT Wake Interval.
```suggestion
The two key parameters of TWT are TWT Wake Duration and TWT Wake Interval.
```

2023-09-25 14:16 UTC, richabp commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst
> +#. Tear down the TWT session with the following Wi-Fi shell commands:
```suggestion
#. Tear down the TWT session using the following Wi-Fi shell commands:
```

2023-09-26 07:44 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst
> +  You, or the application, can set the device to the Permanent Active mode using the ``NET_REQUEST_WIFI_PS`` network management API.
Thanks for catching!
I will try to put this as a note afterwards, since now the list has been reordered and it may look out of place otherwise.

2023-09-26 11:21 UTC, richabp approved these changes

2023-09-28 07:55 UTC, udaynordic approved these changes

2023-09-28 08:10 UTC, merged