Fix qt api issues
nrfconnect/sdk-nrf pull request #12382
Opened 2023-09-20 14:30 UTC by D-Triveni

Dependent on https://github.com/nrfconnect/sdk-nrf/pull/12341

2023-09-20 14:30 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hostap | https://github.com/nrfconnect/sdk-hostap/commit/ba3e82925b075ddaac0dad37b9809a9294815ee5 | https://github.com/nrfconnect/sdk-hostap/commit/bfdce6b7196ff185ecbbd747a9fde6b484c22226 (main) | [nrfconnect/sdk-hostap@ba3e8292..bfdce6b7](https://github.com/nrfconnect/sdk-hostap/compare/ba3e82925b075ddaac0dad37b9809a9294815ee5..bfdce6b7196ff185ecbbd747a9fde6b484c22226) |
| wfa-qt-control-app | https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc/commit/238a291701169cc1be56ee8ad7538436fe1c6470 | https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc/pull/14 | [nrfconnect/sdk-wi-fiquicktrack-controlappc#14/files](https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc/pull/14/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-09-20 14:40 UTC, krish2718 commented on samples/wifi/wfa_qt_app/prj.conf
> +CONFIG_WPA_SUPP_EAPOL=y
Add a comment that this is needed for PMKSA caching tests

2023-09-20 14:40 UTC, krish2718 commented on samples/wifi/wfa_qt_app/prj.conf
> +CONFIG_NRF_WIFI_LOW_POWER=n
Even this needs a comment as to why we are disabling LPM?

2023-09-20 15:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12382
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-21 09:34 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12382/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12382/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12382/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-21 18:37 UTC, krish2718 approved these changes

2023-09-22 04:06 UTC, bama-nordic approved these changes

2023-09-25 07:24 UTC, richabp requested changes
One minor comment.

2023-09-25 07:24 UTC, richabp commented on samples/wifi/wfa_qt_app/README.rst
> +To build for the nRF7002 DK with the netusb support, use the ``nrf7002dk_nrf5340_cpuapp`` build target with netusb overlay configuration.
```suggestion
To build for the nRF7002 DK with the netusb support, use the ``nrf7002dk_nrf5340_cpuapp`` build target with the configuration overlay :file:`overlay-netusb.conf`.
```

2023-09-26 07:07 UTC, richabp approved these changes

2023-09-26 09:24 UTC, merged