samples: cellular: modem_shell: Improve "link edrx" command
nrfconnect/sdk-nrf pull request #12411
Opened 2023-09-22 10:55 UTC by tokangas

Previously, the "link edrx" command required the system (LTE-M/NB-IoT) to be selected, although eDRX was always enabled for both systems.

The command syntax has now been changed so, that the system parameters are no longer used. Instead, it's possible to give eDRX and PTW values for both LTE-M and NB-IoT at the same time.

2023-09-22 10:57 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12411/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12411/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12411/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-25 06:18 UTC, moksanen approved these changes
CI tests ok.

2023-09-25 07:17 UTC, trantanen approved these changes

2023-09-25 09:40 UTC, peknis requested changes

2023-09-25 09:40 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +      Parameters ``--ltem``, ``--nbiot``, ``--edrx_value`` and ``--ptw`` are removed, use parameters ``--ltem_edrx``, ``--ltem_ptw``, ``--nbiot_edrx`` and ``--nbiot_ptw`` to give eDRX and PTW values
```suggestion
      Parameters ``--ltem``, ``--nbiot``, ``--edrx_value,`` and ``--ptw`` are removed.
      Instead, use ``--ltem_edrx``, ``--ltem_ptw``, ``--nbiot_edrx``, and ``--nbiot_ptw`` to give eDRX and PTW values for LTE-M and NB-IoT.
```

2023-09-25 09:47 UTC, peknis approved these changes

2023-09-26 05:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12411
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-26 10:00 UTC, merged