net: lib: download_client: Allow use of DTLS CID
nrfconnect/sdk-nrf pull request #12412
Opened 2023-09-22 11:07 UTC by SeppoTakalo

* When connecting to DTLS service, enable Connection-ID.
    This helps the X509 certificate modes, where timeouts might happen during the certificate transfer.

2023-09-22 11:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12412/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12412/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12412/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-22 11:25 UTC, juhaylinen approved these changes

2023-09-22 12:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12412
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-22 12:31 UTC, rlubos commented
@SeppoTakalo Please don't remove `doc-requried` label, all doc changes should get a tech writer approval.

2023-09-25 10:59 UTC, umapraseeda commented on doc/nrf/libraries/networking/download_client.rst
> +When modem firmware v1.3.5 or newer is used, you can enable the support for DTLS Connection Identifier feature in the download client library by enabling :kconfig:option:`CONFIG_DOWNLOAD_CLIENT_CID`
```suggestion
When modem firmware v1.3.5 or newer is used, you can enable the support for DTLS Connection Identifier feature in the download client library by enabling the :kconfig:option:`CONFIG_DOWNLOAD_CLIENT_CID` Kconfig option.
```

2023-09-25 10:59 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Option :kconfig:option`CONFIG_DOWNLOAD_CLIENT_CID` that allows use of Connection Identifier on DTLS connection.
```suggestion
  * Added:
  
    * Kconfig option :kconfig:option:`CONFIG_DOWNLOAD_CLIENT_CID` that allows use of Connection Identifier on DTLS connection.
```

2023-09-25 11:17 UTC, umapraseeda approved these changes

2023-09-25 11:44 UTC, jheiskan81 approved these changes

2023-09-25 13:21 UTC, SeppoTakalo commented
Why is the documentation build broken?
I cannot spot the failure.

2023-09-25 13:30 UTC, rlubos commented
> Why is the documentation build broken? I cannot spot the failure.

It's currently broken on main, fixes in https://github.com/nrfconnect/sdk-nrf/pull/12379

2023-09-26 07:41 UTC, peknis requested changes

2023-09-26 07:41 UTC, peknis commented on doc/nrf/libraries/networking/download_client.rst
> +When modem firmware v1.3.5 or newer is used, you can enable the support for DTLS Connection Identifier feature in the download client library by enabling the :kconfig:option:`CONFIG_DOWNLOAD_CLIENT_C
```suggestion
When you have modem firmware v1.3.5 or newer, you can use the :kconfig:option:`CONFIG_DOWNLOAD_CLIENT_CID` Kconfig option to enable the DTLS Connection Identifier feature in this library.
```

2023-09-26 09:12 UTC, peknis approved these changes

2023-09-26 13:11 UTC, merged