bluetooth: Fix assert when handling illegal response data cmd
nrfconnect/sdk-nrf pull request #12421
Opened 2023-09-25 10:43 UTC by olivier-le-sage

Fixes an assert that could happen if the LE set periodic advertising response data was issued more than once without fetching the command complete event.

2023-09-25 10:55 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12421/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12421/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12421/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-25 12:18 UTC, olivier-le-sage commented
test https://projecttools.nordicsemi.no/bitbucket/projects/NCS-TEST/repos/test-fw-nrfconnect-ble/pull-requests/4912/overview

2023-09-27 08:37 UTC, seko-nordic commented on subsys/bluetooth/controller/hci_internal.c
>  	}
may be we should put that entire `if (opcode == SDC_HCI_OPCODE_CMD_LE_SET_PERIODIC_ADV_RESPONSE_DATA` under corresponding KConfig ifdef. Currently it eats few cycles for every event we generate, even for an application that has nothing to do with PAwR.

2023-09-27 08:37 UTC, seko-nordic approved these changes

2023-09-28 07:51 UTC, rugeGerritsen requested changes
I would be happy if you could add some ifdefs. That saves power

2023-11-21 11:42 UTC, rugeGerritsen approved these changes

2023-11-21 13:23 UTC, merged