drivers: wifi: Remove bss ie and len setting in auth info
nrfconnect/sdk-nrf pull request #12446
Opened 2023-09-27 12:27 UTC by ajayparida

Zephyr case firmware is not expecting the bss ie field. As bss ie field is valid only for cfg80211 offload case. The value ibss ie length for Zephyr case set to 0.

2023-09-27 12:28 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12446/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12446/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12446/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-27 14:06 UTC, sachinthegreen approved these changes

2023-09-28 07:35 UTC, rado17 approved these changes

2023-09-28 08:13 UTC, sachinthegreen requested changes

2023-09-28 08:13 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +		}
Why not use a `len` variable and set it to min of `NRF_WIFI_MAX_IE_LEN` and `params->ie_len` ?

2023-09-28 09:58 UTC, sachinthegreen approved these changes

2023-09-28 11:38 UTC, merged