samples: wifi: qt: Add SLIP configuration
nrfconnect/sdk-nrf pull request #12444
Opened 2023-09-27 09:29 UTC by D-Triveni

Add changes to use SLIP as control interface using the UART as transport.

2023-09-27 09:35 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12444/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12444/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12444/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-09-27 10:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12444
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-09-27 12:51 UTC, richabp requested changes
Since we are updating this Sample, its good to fix some minor issues as well:

Line 15: The sample supports the following development **kit:**
Line 32-34: Currently, the nRF7002 DK + QSPI configuration is supported.

2023-09-27 12:51 UTC, richabp commented on samples/wifi/wfa_qt_app/README.rst
> +To build for the nRF7002 DK with the SLIP support, use the ``nrf7002dk_nrf5340_cpuapp`` build target with the configuration overlay :file:`overlay-slip.conf` and dtc overlay :file:`nrf7002_uart_pipe.
Mention the expanded form of SLIP as well.
```suggestion
To build for the nRF7002 DK with the SLIP support, use the ``nrf7002dk_nrf5340_cpuapp`` build target with the configuration overlay :file:`overlay-slip.conf` and DTC overlay :file:`nrf7002_uart_pipe.overlay`.
```

2023-09-27 13:11 UTC, D-Triveni commented
> Since we are updating this Sample, its good to fix some minor issues as well:
> 
> Line 15: The sample supports the following development **kit:** Line 32-34: Currently, the nRF7002 DK + QSPI configuration is supported.

Addressed.

2023-09-28 08:01 UTC, richabp reviewed
Do we need a Changelog entry since we are adding SLIP support?

Ok, so we don't need a Changelog entry as it's already in the Changelog as a new sample.

2023-09-28 08:45 UTC, D-Triveni commented
> Do we need a Changelog entry since we are adding SLIP support?

It's needed.

2023-09-29 06:40 UTC, richabp approved these changes

2023-10-02 10:09 UTC, richabp reviewed
Do we have a WFA QuickTrack (WFA QT) library as mentioned in this sample?

2023-10-04 04:46 UTC, D-Triveni commented
> Do we have a WFA QuickTrack (WFA QT) library as mentioned in this sample?

Yes, we do.

2023-10-08 18:55 UTC, krish2718 approved these changes

2023-10-09 06:31 UTC, bama-nordic approved these changes

2023-10-09 08:42 UTC, merged