Develop/ncsdk 23472 dim to dark
nrfconnect/sdk-nrf pull request #12506
Opened 2023-10-03 13:04 UTC by ludvigsj

Fixes issues with Move Set and Delta Set handlers not
handling dimming starting from 0 correctly.

 * Clamp targets to 0 when dimming down from 0, instead of clamping to
   RANGE_MIN, to avoid a message requesting a dim down causing the light
   to actually turn on.
 * Take the gap between 0 and RANGE_MIN into account when computing the
   transition time for a move set before this is sent to the application
   callback, to avoid a slow transition for dims starting at 0
 * Update the samples and tester to correctly transition the
   lightness state when dimming up from zero when a RANGE_MIN is set.
 * Update the documentation for the callback to mention this
   requirement.
 * Small bug fixes
    * Range converted to actual in delta set to match with the delta and
      target_actual
    * Do not compute transition in move set if target == current

2023-10-03 13:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12506/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12506/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12506/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-03 14:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12506
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-03 16:12 UTC, PavelVPV commented on subsys/bluetooth/mesh/lightness_srv.c
> +	if (srv->delta_start == 0 && delta_set->delta < 0) {
Shouldn't it be `<=`? If `delta_start` and `delta` are both zero, this will set lightness to range min.

2023-10-04 06:07 UTC, ludvigsj commented on tests/bluetooth/tester/src/model_handler.c
> +	}
Something like `bt_mesh_lightness_get_start_value(current, target)`?

2023-10-04 06:24 UTC, PavelVPV commented on tests/bluetooth/tester/src/model_handler.c
> +	}
+ server pointer to get range min.

2023-10-04 07:38 UTC, PavelVPV approved these changes

2023-10-04 10:47 UTC, ludvigsj commented
There is an ongoing discussion for specs about the expected behavior here, will leave this PR DNM until discussion about specs is done

2023-10-04 10:48 UTC, mia-ko requested changes

2023-10-04 10:48 UTC, mia-ko commented on include/bluetooth/mesh/lightness_srv.h
> +	 * time specified by the transition.
```suggestion
	 * When performing a non-instantaneous state change, the applicaton must call
	 * @ref bt_mesh_lightness_start_value. The change must move instantaneously
	 * to the start value returned by this function, and then gradually change from
	 * that value over time specified by the transition.
```

2023-10-04 10:48 UTC, mia-ko commented on include/bluetooth/mesh/lightness_srv.h
> + * should immediately jump to this starting value and then start gradually changing.
```suggestion
 * should immediately jump to this starting value and then gradually start changing.
```

2023-10-04 10:48 UTC, mia-ko commented on subsys/bluetooth/mesh/lightness_srv.c
> +		 * a dim down to cause the light to turn on.
```suggestion
		/* Do not clamp to range when dimming down from zero to avoid
		 * the light to turn on when dimmed down.
```

2023-10-04 10:48 UTC, mia-ko commented on subsys/bluetooth/mesh/lightness_srv.c
> +		 * back to zero in binding with Generic Level state.
```suggestion
		/* Clamp the value to the lightness range to prevent that it moves
		 * back to zero in binding with Generic Level state.
```

2023-10-10 11:47 UTC, mia-ko approved these changes

2023-10-10 13:32 UTC, PavelVPV approved these changes

2023-10-10 14:53 UTC, merged