lib: modem_slm: String null-terminator protection
nrfconnect/sdk-nrf pull request #12512
Opened 2023-10-04 00:10 UTC by junqingzou

The strstr() function requires the source string to be null- terminated. It's risky to use to search in data buffer of UART reception as it could be partial of full AT response, meaning not null-terminated.

Solution is to use strnstr() to search with length limit.

2023-10-04 00:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12512/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12512/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12512/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-04 07:30 UTC, SeppoTakalo requested changes

2023-10-04 08:15 UTC, junqingzou commented on lib/modem_slm/modem_slm.c
> + * __FBSDID("$FreeBSD: src/lib/libc/string/strnstr.c,v 1.5 2009/02/03 17:58:20 danger Exp $");
How to?

2023-10-04 09:25 UTC, SeppoTakalo commented
You only call this callback from one location
```c
	case UART_RX_RDY:
		LOG_DBG("RX_RDY %d", evt->data.rx.len);
		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
```

Why don't you put the nul terminator here?

```c
	case UART_RX_RDY:
		LOG_DBG("RX_RDY %d", evt->data.rx.len);
                evt->data.rx.buf[evt->data.rx.offset + evt->data.rx.len] = 0;
		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
```

Verify if that code works, before using it. I did not test it. Just a suggestion.

2023-10-04 09:34 UTC, junqingzou commented
> You only call this callback from one location
> 
> ```c
> 	case UART_RX_RDY:
> 		LOG_DBG("RX_RDY %d", evt->data.rx.len);
> 		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
> ```
> 
> Why don't you put the nul terminator here?
> 
> ```c
> 	case UART_RX_RDY:
> 		LOG_DBG("RX_RDY %d", evt->data.rx.len);
>                 evt->data.rx.buf[evt->data.rx.offset + evt->data.rx.len] = 0;
> 		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
> ```
> 
> Verify if that code works, before using it. I did not test it. Just a suggestion.

No we cannot assume that there is always one extra byte in the buffer to add null-terminator.
For large response, on every CONFIG_MODEM_SLM_DMA_MAXLEN there will be one RX_RDY and the buffer is already full.

2023-10-04 09:44 UTC, junqingzou commented on lib/modem_slm/modem_slm.c
> + * __FBSDID("$FreeBSD: src/lib/libc/string/strnstr.c,v 1.5 2009/02/03 17:58:20 danger Exp $");
If there is extra room Zephyr Serial already set it to be 0x00.
See https://github.com/nrfconnect/sdk-zephyr/blob/main/drivers/serial/uart_nrfx_uarte.c#L1212

2023-10-04 09:46 UTC, SeppoTakalo commented
> No we cannot assume that there is always one extra byte in the buffer to add null-terminator. For large response, on every CONFIG_MODEM_SLM_DMA_MAXLEN there will be one RX_RDY and the buffer is already full.

Then make a room:
```c
	case UART_RX_BUF_REQUEST:
		LOG_DBG("RX_BUF_REQ");
		pos = 0;
		err = uart_rx_buf_rsp(uart_dev, next_buf, sizeof(uart_rx_buf[0]) - 1);
		if (err) {
			LOG_WRN("UART RX buf rsp: %d", err);
		}
```

2023-10-04 10:08 UTC, junqingzou commented
> > No we cannot assume that there is always one extra byte in the buffer to add null-terminator. For large response, on every CONFIG_MODEM_SLM_DMA_MAXLEN there will be one RX_RDY and the buffer is already full.
> 
> Then make a room:
> 
> ```c
> 	case UART_RX_BUF_REQUEST:
> 		LOG_DBG("RX_BUF_REQ");
> 		pos = 0;
> 		err = uart_rx_buf_rsp(uart_dev, next_buf, sizeof(uart_rx_buf[0]) - 1);
> 		if (err) {
> 			LOG_WRN("UART RX buf rsp: %d", err);
> 		}
> ```

This will mismatch DMA buffer size with SLM UART.
For example, SLM sends 256 bytes in one DMA and modem_slm will receive 255 + 1 in two DMA events.

2023-10-04 10:25 UTC, junqingzou commented
Well, I'm not in favor of altering RX buffer so let me close this PR for a new one.
I'll forward the original bug report from customer as info, too.

2023-10-04 10:25 UTC, closed without merging

2023-10-05 06:34 UTC, MarkusLassila commented
> > You only call this callback from one location
> > ```c
> > 	case UART_RX_RDY:
> > 		LOG_DBG("RX_RDY %d", evt->data.rx.len);
> > 		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why don't you put the nul terminator here?
> > ```c
> > 	case UART_RX_RDY:
> > 		LOG_DBG("RX_RDY %d", evt->data.rx.len);
> >                 evt->data.rx.buf[evt->data.rx.offset + evt->data.rx.len] = 0;
> > 		uart_rx_handler(&(evt->data.rx.buf[pos]), evt->data.rx.len);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Verify if that code works, before using it. I did not test it. Just a suggestion.
> 
> No we cannot assume that there is always one extra byte in the buffer to add null-terminator. For large response, on every CONFIG_MODEM_SLM_DMA_MAXLEN there will be one RX_RDY and the buffer is already full.

In principle, the response could contain multiple or partial responses or even something with 0 (like data in datamode), so I would not recommend adding 0 in it. If 0 was to be added, it should likely be added in uart_rx_handler to the ring buffer.

Generally, I don't think that this current implementation can handle the responses very well and there are situations where it will fail. If this needs to work in future as well, we should consider refactoring the UART implementation.