Support for Save & Load Modem DTLS session
nrfconnect/sdk-nrf pull request #12532
Opened 2023-10-05 05:24 UTC by jheiskan81

### LwM2M client utils

- Added support for pause DTLS CID by TLS_DTLS_CONN_SAVE socket option at Rx-OFF-IDLE state and load CID socket back by TLS_DTLS_CONN_LOAD operation at Registration or De-registration state.
- New Feature can be enabled by kconfig CONFIG_LWM2M_CLIENT_UTILS_DTLS_CON_MANAGEMENT.

### LwM2M client sample

- integrated new feature with Connection Identifier overlay

2023-10-05 05:28 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12532/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12532/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12532/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-05 06:00 UTC, peknis requested changes

2023-10-05 06:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12532
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-05 06:48 UTC, peknis requested changes

2023-10-05 06:48 UTC, peknis commented on include/net/lwm2m_client_utils.h
> + * he function saves the DTLS CID connection at LWM2M_RD_CLIENT_EVENT_QUEUE_MODE_RX_OFF state and
```suggestion
 * It saves the DTLS CID connection at LWM2M_RD_CLIENT_EVENT_QUEUE_MODE_RX_OFF state and
```

2023-10-05 06:48 UTC, peknis commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	bool "Enable DTLS Connection save and load"
```suggestion
	bool "Enable DTLS connection save and load"
```

2023-10-05 06:48 UTC, peknis commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	  Enable DTLS connection Identifier save at idle and load exit from idle
```suggestion
	  Enable DTLS connection identifier save at idle and load exit from idle.
```

2023-10-05 06:48 UTC, peknis commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	  This requires modem firmware 1.3.5 or newer.
```suggestion
	  This requires modem firmware v1.3.5 or newer.
```

2023-10-05 06:58 UTC, jheiskan81 commented
@peknis Thanks for review.  I have fixed your change requests.

2023-10-05 07:04 UTC, peknis approved these changes

2023-10-05 07:15 UTC, juhaylinen approved these changes

2023-10-05 09:10 UTC, rlubos approved these changes

2023-10-05 09:42 UTC, simensrostad approved these changes

2023-10-05 10:00 UTC, SeppoTakalo commented on samples/cellular/lwm2m_client/src/main.c
> +	if (IS_ENABLED(CONFIG_LWM2M_CLIENT_UTILS_DTLS_CON_MANAGEMENT)) {
Move this `IS_ENABLED()` into the function itself.

The main application is becoming too messy, so rather have all checks in the utility library.

2023-10-05 10:01 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_sec_con_management.c
> +	if ((client_event == LWM2M_RD_CLIENT_EVENT_REG_UPDATE ||
Check here, if we need to do anything.

Also, why is this called `lwm2m_security_`

2023-10-05 12:05 UTC, jheiskan81 commented
@SeppoTakalo Please review my changes

2023-10-05 12:35 UTC, SeppoTakalo reviewed
Looks otherwise fine, but this does not need extra Kconfigs.

The `lwm2m_utils_connection_manage()` pretty much selects conpile time, if there is anything to do.
Application don't need any iffdeff.

2023-10-05 12:35 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	  This requires modem firmware v1.3.5 or newer.
```suggestion
config LWM2M_CLIENT_UTILS_DTLS_CON_SAVE
	bool "Enable DTLS connection save and load"
	depends on LWM2M_RD_CLIENT_STOP_POLLING_AT_IDLE
	help
	  Enable DTLS connection identifier save at idle and load exit from idle.
	  This requires modem firmware v1.3.5 or newer.
```

2023-10-05 12:35 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/CMakeLists.txt
> +zephyr_library_sources_ifdef(CONFIG_LWM2M_CLIENT_UTILS_CONNECTION_MANAGEMENT lwm2m/lwm2m_utils_con_management.c)
```suggestion
zephyr_library_sources(lwm2m/lwm2m_utils_con_management.c)
```

2023-10-05 12:35 UTC, SeppoTakalo commented on samples/cellular/lwm2m_client/src/main.c
> +	}
```suggestion
	lwm2m_utils_connection_manage(client, &client_event);
```

2023-10-05 12:35 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	select LWM2M_CLIENT_UTILS_CONNECTION_MANAGEMENT
```suggestion
```

2023-10-05 12:35 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +	select LWM2M_CLIENT_UTILS_CONNECTION_MANAGEMENT
```suggestion
```

2023-10-05 12:35 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/Kconfig
> +
```suggestion
```

2023-10-05 12:36 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_utils_con_management.c
> +#ifdef CONFIG_LWM2M_CLIENT_UTILS_DTLS_CON_MANAGEMENT
```suggestion
```

2023-10-05 12:36 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_utils_con_management.c
> +#endif
```suggestion
```

2023-10-06 03:40 UTC, SeppoTakalo approved these changes

2023-10-09 06:36 UTC, peknis approved these changes

2023-10-10 06:25 UTC, merged