Usability fixes and improvements when using BUILD_STRATEGY_USE_HEX_FILE
nrfconnect/sdk-nrf pull request #12543
Opened 2023-10-05 12:11 UTC by oyvindronningstad

- Fix an issue where the provision hex file was missing a public key digest when using MCUBOOT_BUILD_STRATEGY_USE_HEX_FILE
- Add BUILD_STRATEGY options for the provision hex file
- Allow the BOOT_SIGNATURE_KEY_FILE path to be specified relative to the current sample directory

2023-10-05 12:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12543/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12543/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12543/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-05 13:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12543
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-06 10:01 UTC, sigvartmh approved these changes

2023-10-06 13:25 UTC, oyvindronningstad commented
cc @hieuv

2023-10-06 13:48 UTC, FrancescoSer requested changes

2023-10-06 13:48 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Allow the path in :kconfig:option:`CONFIG_BOOT_SIGNATURE_KEY_FILE` to be relative to the current sample directory.
```suggestion
  * The path set with :kconfig:option:`CONFIG_BOOT_SIGNATURE_KEY_FILE` can now be relative to the current sample directory.
```

2023-10-06 13:48 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    Fix generation of the provision page, and also add the option to provide the provision page as a hex file or, be skipped (:kconfig:option:`CONFIG_PROVISION_BUILD_STRATEGY_USE_HEX_FILE` and :kconf
```suggestion
  * Added:

    * the :kconfig:option:`CONFIG_PROVISION_BUILD_STRATEGY_USE_HEX_FILE` Kconfig option to provide the provision page as a HEX file.
    * the :kconfig:option:`CONFIG_PROVISION_BUILD_STRATEGY_SKIP_BUILD` kconfig option to skip the building of the provision page. 
 
  * Fixed:

    * The generation of the provision page.
    * The regeneration of the provision page when both :ref:`bootloader` and :ref:`mcuboot_ncs` are present, and MCUboot is provided as a HEX file (using :kconfig:option:`CONFIG_MCUBOOT_BUILD_STRATEGY_USE_HEX_FILE`).
```

This is a guess, let me know if the descriptions of the options mentioned are correct.

2023-10-17 13:33 UTC, nordicjm requested changes

2023-10-17 13:33 UTC, nordicjm commented on modules/mcuboot/CMakeLists.txt
> +    set(mcuboot_key_file ${mcuboot_CONF_DIR}/${CONFIG_BOOT_SIGNATURE_KEY_FILE})
This does not work and I do not like this change

2023-10-17 13:33 UTC, nordicjm commented on subsys/bootloader/cmake/provision_hex.cmake
> +endif()
-1 on breaking sysbuild support, we need to stop making changing to child/parent images

2023-10-19 13:23 UTC, FrancescoSer approved these changes

2024-03-19 00:27 UTC, closed without merging

2024-03-27 11:37 UTC, CodingGhost commented
can this be reopened? being able to specify the hex file and signature file relative to the working directory is very Important for us. Currently we have to use very awkward workarounds for that.

2024-03-27 11:41 UTC, nordicjm commented
> @nordicjm @oyvindronningstad can this be reopened? being able to specify the hex file and signature file relative to the working directory is very Important for us. Currently we have to use very awkward workarounds for that.

This will not work with sysbuild and it's possible that the whole feature will be dropped in it's entirety

2024-03-27 11:44 UTC, CodingGhost commented
@nordicjm and is there any other possibility to specify the file relatively?
I think my use case for this is pretty common. multiple developers trying to build the project on their own PCs, for every build one has to change the path of the hex file manually... This is bad.

2024-04-19 11:54 UTC, CodingGhost commented
any update on this? How do people solve this issue or work around it?