net: lwm2m_client_utils: Advanced FOTA push fix
nrfconnect/sdk-nrf pull request #12620
Opened 2023-10-10 19:02 UTC by jheiskan81

Fixed interoperability issue with AVSystem Coiote server for do Firmware update with Push-mode.
Server cancel at idle state was not accepted and cause failure to FOTA process.

2023-10-10 19:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12620/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12620/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12620/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-11 05:59 UTC, jheiskan81 commented
@SeppoTakalo , @juhaylinen  and @peknis Please review

2023-10-11 06:09 UTC, peknis requested changes

2023-10-11 06:09 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +      Fix interoperability issue with AVSystem's Coiote Device Management server with firmware update by push-mode.
```suggestion
    * The advanced LwM2M FOTA object to accept zero length of a firmware package for reset state and result resources.
      This fixes an interoperability issue with AVSystem's Coiote Device Management server related to firmware update by push-mode.
```

2023-10-11 06:27 UTC, juhaylinen approved these changes

2023-10-11 06:36 UTC, peknis approved these changes

2023-10-11 06:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12620
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-11 09:17 UTC, jheiskan81 commented
@SeppoTakalo Please review

2023-10-11 09:39 UTC, SeppoTakalo approved these changes

2023-10-11 09:45 UTC, rlubos approved these changes

2023-10-11 09:45 UTC, merged