doc: working_with_pmic: Added developing with npm1300
nrfconnect/sdk-nrf pull request #12646
Opened 2023-10-11 12:03 UTC by aasinclair

Added developing with npm1300 page.
Includes information on how to use PowerUP overlays.

2023-10-11 12:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12646
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-13 08:30 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12646/2/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12646/2/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-10-16 09:53 UTC, peknis requested changes

2023-10-16 09:53 UTC, peknis commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +This exported overlay file can be used to quickly configure the nPM1300 in your application.
```suggestion
You can use this exported overlay file to quickly configure the nPM1300 in your application.
```

2023-10-16 09:53 UTC, peknis commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +`app.overlay`
```suggestion
:file:`app.overlay`.
```

2023-10-16 13:26 UTC, annakielar requested changes

2023-10-16 13:26 UTC, annakielar commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +The |NCS| provides support for development with the `nPM1300 Power Management IC (PMIC) <nPM1300 product website_>`_, using the `nPM1300 EK (PCA10152) <nPM1300 EK product page_>`_.
```suggestion
The |NCS| provides support for development with the `nPM1300 <nPM1300 product website_>`_ Power Management IC (PMIC), using the `nPM1300 EK <nPM1300 EK product page_>`_ (PCA10152).
```

2023-10-16 13:26 UTC, annakielar commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +#######################
```suggestion
Developing with nPM1300 EK
##########################
```

2023-10-16 13:26 UTC, annakielar commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +If you are not familiar with the |NCS| and its development environment, see :ref:`installation` and :ref:`configuration_and_build` documentation.
```suggestion
If you are not familiar with the |NCS| and its development environment, see the :ref:`installation` and :ref:`configuration_and_build` documentation.
```

2023-10-16 13:26 UTC, annakielar commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +nPM PowerUP supports exporting a full configuration of the nPM1300 in devicetree overlay format.
```suggestion
nPM PowerUP application supports exporting a full configuration of the nPM1300 in devicetree overlay format.
```
Am I right?

2023-10-17 10:34 UTC, annakielar approved these changes

2023-11-01 07:17 UTC, peknis requested changes

2023-11-01 07:17 UTC, peknis commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +nPM PowerUP application supports exporting a full configuration of the nPM1300 in devicetree overlay format.
```suggestion
The nPM PowerUP application supports exporting a full configuration of the nPM1300 in devicetree overlay format.
```

2023-11-01 07:17 UTC, peknis commented on doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
> +If there is no overlay file for you project, include the file directly in your application folder with the name
```suggestion
If there is no overlay file for your project, include the file directly in your application folder with the name
```

2023-11-01 09:16 UTC, peknis approved these changes

2023-11-01 10:06 UTC, merged