migration_guide: add entries for SLM
nrfconnect/sdk-nrf pull request #12714
Opened 2023-10-16 11:54 UTC by tomi-font

Also, make small fixes to the release notes.

2023-10-16 11:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12714/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12714/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-10-16 12:06 UTC, wiba-nordic approved these changes

2023-10-16 12:06 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
> +  * The ``#XAGPS`` and ``#XPGPS``AT commands have been replaced by ``#XGPS``.
```suggestion
  * The ``#XAGPS`` and ``#XPGPS`` AT commands have been replaced by ``#XGPS``.
```

2023-10-16 12:36 UTC, peknis requested changes

2023-10-16 12:36 UTC, peknis commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
> +  * If you are using the LwM2M carrier library, make sure to take into account the addition of the auto-connect feature that is enabled by default.
```suggestion
  * If you are using the :ref:`liblwm2m_carrier_readme` library, make sure to take into account the addition of the auto-connect feature that is enabled by default.
```

2023-10-16 12:41 UTC, peknis approved these changes

2023-10-17 04:12 UTC, MarkusLassila approved these changes
Looks good. My changes are coming today or tomorrow.

2023-10-17 04:48 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
> +  * The :kconfig:option:`CONFIG_SLM_AGPS` Kconfig option has been replaced by :kconfig:option:`CONFIG_NRF_CLOUD_AGNSS` and is now enabled by default.
```suggestion
* For the Serial LTE Modem (SLM) application:

  * The :kconfig:option:`CONFIG_SLM_AGPS` Kconfig option has been replaced by :kconfig:option:`CONFIG_NRF_CLOUD_AGNSS` and is now enabled by default.
```
Breaks doc build by trying to apply term definition formatting.

2023-10-17 07:25 UTC, merged