samples: wifi: scan: Fix pin conflicts with Wi-Fi on nRF9160
nrfconnect/sdk-nrf pull request #12737
Opened 2023-10-17 13:01 UTC by krish2718

UART1 shares few pins with Wi-Fi GPIOs causing boot failure, this is already fixed in shell and location samples, but missed in scan sample.

2023-10-17 13:05 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12737/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12737/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12737/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-17 13:16 UTC, bama-nordic approved these changes

2023-10-18 08:12 UTC, krga2022 approved these changes

2023-10-18 08:34 UTC, rado17 approved these changes

2023-10-18 08:42 UTC, sachinthegreen requested changes

2023-10-18 08:42 UTC, sachinthegreen commented on samples/wifi/scan/boards/nrf9160dk_nrf9160_ns.overlay
> + * Copyright (c) 2022 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2023 Nordic Semiconductor ASA
```

2023-10-18 09:43 UTC, sachinthegreen approved these changes

2023-10-18 10:32 UTC, merged