applications: nrf5340_audio: Check if local json file exists.
nrfconnect/sdk-nrf pull request #12803
Opened 2023-10-19 13:52 UTC by MariusVaardal

If there is a json file specified by the
AUDIO_KIT_IDS environmental variable, use this as
an alternative to the json file in the buildprog folder when building.

2023-10-19 13:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12803/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12803/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12803/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-24 07:50 UTC, koffes requested changes

2023-10-24 07:50 UTC, koffes commented on applications/nrf5340_audio/tools/buildprog/buildprog.py
> +USER_CONFIG = BUILDPROG_FOLDER / "nrf5340_audio_dk_devices.json" if os.getenv("AUDIO_KIT_IDS") is None else Path(os.getenv("AUDIO_KIT_IDS"))
Suggest this is made more readable by:
```suggestion
 if os.getenv("AUDIO_KIT_IDS") is None:
    USER_CONFIG = BUILDPROG_FOLDER / "nrf5340_audio_dk_devices.json" 
 else: 
     USER_CONFIG = Path(os.getenv("AUDIO_KIT_IDS"))
```

2023-10-24 07:50 UTC, koffes commented on applications/nrf5340_audio/tools/buildprog/buildprog.py
> +USER_CONFIG = BUILDPROG_FOLDER / "nrf5340_audio_dk_devices.json" if os.getenv("AUDIO_KIT_IDS") is None else Path(os.getenv("AUDIO_KIT_IDS"))
Also, mind the naming. It is a tad strange that "AUDIO_KIT_IDS are set to "USER_CONFIG".
I think your name is better.  Suggest that both AUDIO_KIT_IDS and USER_CONFIG is renamed to something like AUDIO_KIT_SNRS or AUDIO_KIT_SERIAL_NUMBERS_JSON

2023-11-02 12:35 UTC, koffes approved these changes

2023-11-02 12:55 UTC, andvib approved these changes

2023-11-06 08:50 UTC, merged