manifest: update nrfxlib
nrfconnect/sdk-nrf pull request #12833
Opened 2023-10-23 14:06 UTC by knutel-nordic

Update nrfxlib for hci vs command

2023-10-23 14:07 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/bbb718adf44a915c1f42bbc6393b2708cb93cf88 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1099 | [nrfconnect/sdk-nrfxlib#1099/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1099/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-10-24 04:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12833/4/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12833/4/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12833/4/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-24 05:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12833
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-31 08:02 UTC, rugeGerritsen requested changes
Please also update the entry of the dragoon project in this file

2023-10-31 12:02 UTC, rugeGerritsen approved these changes

2023-11-02 06:31 UTC, KyraLengfeld approved these changes

2023-11-02 07:42 UTC, rugeGerritsen approved these changes

2023-11-02 09:52 UTC, merged