net: fota_download: Only retry on ECONNRESET
nrfconnect/sdk-nrf pull request #12874
Opened 2023-10-26 14:06 UTC by SeppoTakalo

Only the ECONNRESET is documented in Download Client as a possibility to rettry.

* Fix up the documentation regarding other error codes.
* Fix the FOTA download so that we don't assume retry.
* Add testcases for download client errors.

2023-10-26 14:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12874/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12874/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12874/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-26 14:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12874
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-30 07:32 UTC, jheiskan81 approved these changes

2023-10-31 08:52 UTC, umapraseeda commented on include/net/download_client.h
> +	 * If download is stopped, and it was sterted using @ref download_client_start
```suggestion
	 * If download is stopped, and it was started using @ref download_client_start
```

2023-10-31 08:52 UTC, umapraseeda commented on subsys/net/lib/download_client/src/download_client.c
> +		 * in the download client API
```suggestion
		/* Make sure that ECONNRESET is not returned as it has a special meaning
		 * in the download client API
```

2023-10-31 08:59 UTC, peknis requested changes

2023-10-31 11:02 UTC, umapraseeda approved these changes

2023-11-10 08:37 UTC, merged