net: lib: lwm2m_client_utils: Update RAI
nrfconnect/sdk-nrf pull request #12885
Opened 2023-10-27 07:03 UTC by juhaylinen

Sending of dummy packet after setting socket option SO_RAI_LAST is not needed anymore. Modem lib handles this.
Add dummy parameter to socket commands.

2023-10-27 07:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12885/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12885/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12885/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-27 07:17 UTC, SeppoTakalo requested changes

2023-10-27 07:17 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c
> +			int dummy;
```suggestion
			int dummy = 1;
```

Even when we don't use the value, initialize it, so at least we don't get warnings of using uninitialized variables, if static analyzers see this.

2023-10-27 07:17 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c
> +			int dummy;
```suggestion
			int dummy = 1;
```

2023-10-27 07:21 UTC, SeppoTakalo approved these changes

2023-10-30 07:32 UTC, jheiskan81 commented on samples/cellular/lwm2m_client/prj.conf
> +CONFIG_NRF_MODEM_LIB_TRACE=y
Why this is enabled?

2023-10-30 07:34 UTC, juhaylinen commented on samples/cellular/lwm2m_client/prj.conf
> +CONFIG_NRF_MODEM_LIB_TRACE=y
Oops, I'll revert this change.

2023-10-30 07:57 UTC, jheiskan81 approved these changes

2023-11-01 12:23 UTC, merged