samples: cellular: mss: Wait for connection before printing connected.
nrfconnect/sdk-nrf pull request #12901
Opened 2023-10-28 00:12 UTC by glarsennordic

MSS does not wait for connection success before printing "Connected to nRF Cloud".

This commit fixes this by making the connect_cloud function correctly block until connection either succeeds or fails.

IRIS-7090

2023-10-28 00:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12901/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12901/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12901/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-28 00:15 UTC, glarsennordic commented
I still need to test CoAP, but I don't think the results will be different, so this should be ready for review

2023-10-28 00:18 UTC, plskeggs approved these changes
Needs a change log, otherwise fine.

2023-10-28 00:19 UTC, glarsennordic commented
Ah, right, changelog. I've spent too long on Zephyr PRs

2023-10-28 00:25 UTC, glarsennordic commented
DNM until I test CoAP

2023-10-28 01:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12901
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-30 07:04 UTC, peknis requested changes

2023-10-30 07:04 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Sample now waits for connection success before printing ``Connected to nRF Cloud!``.
```suggestion
    * The sample now waits for a successful connection before printing ``Connected to nRF Cloud!``.
```

2023-10-31 21:04 UTC, tony-le-24 approved these changes

2023-10-31 21:19 UTC, jayteemo approved these changes

2023-11-01 23:56 UTC, glarsennordic commented
Tests succeed with CoAP

2023-11-02 06:42 UTC, peknis approved these changes

2023-11-03 11:59 UTC, merged