doc: glossary: Add GNSS scheduled downloads into glossary
nrfconnect/sdk-nrf pull request #12902
Opened 2023-10-30 08:02 UTC by tokangas

Added GNSS scheduled downloads into glossary.

Updated nrfxlib revision to pull GNSS interface documentation updates.

2023-10-30 08:03 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/c230f914828d2ecf44a9f28922b40804216f0408 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1103 | [nrfconnect/sdk-nrfxlib#1103/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1103/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-10-30 08:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12902/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12902/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12902/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-30 08:11 UTC, peknis requested changes

2023-10-30 08:11 UTC, peknis commented on doc/nrf/documentation/glossary.rst
> +      Scheduled downloads are only performed in periodic navigation mode.
```suggestion
      A mechanism to maintain GNSS data availability in periodic navigation mode.
      
      If GNSS only runs long enough to calculate the first usable fix, it is probably never able to download for example almanacs or ionospheric correction data from the satellite broadcast.
      To ensure GNSS data availability and to improve accuracy in periodic navigation mode, GNSS performs scheduled downloads.
      When GNSS determines it needs to download ephemerides or almanacs from the broadcast, the fix interval and fix retry parameters are temporarily ignored and GNSS runs continuously for a longer period of time.
      GNSS performs scheduled downloads until it has downloaded the data it needs.
      After the downloads, normal operation is resumed.
      When `A-GNSS`_ is used, scheduled downloads are not necessary and you can disable them using the :ref:`nrfxlib:nrf_modem_gnss_api`.
      Scheduled downloads are only performed in periodic navigation mode.
```

2023-10-30 08:19 UTC, peknis approved these changes

2023-10-30 08:31 UTC, trantanen approved these changes

2023-10-30 09:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-12902
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-10-30 10:53 UTC, tokangas commented
I'll create a separate PR to add scheduled downloads into glossary. That needs to be merged first to make sure there's no doc build break.

2023-10-31 08:36 UTC, hiltunent approved these changes

2023-10-31 09:45 UTC, merged