applications: nrf5340_audio: Bad_frame flag for wrong sizes
nrfconnect/sdk-nrf pull request #12910
Opened 2023-10-30 13:50 UTC by alexsven

- Set bad_frame flag if frame_size is not matching desired_size

2023-10-30 13:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12910/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12910/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12910/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-10-30 14:05 UTC, koffes approved these changes

2023-10-30 14:35 UTC, erikrobstad requested changes

2023-10-30 14:35 UTC, erikrobstad commented on applications/nrf5340_audio/src/audio/le_audio_rx.c
>  		data_size_mismatch = true;
data_size_mismatch is not used now?

2023-10-31 08:20 UTC, alexsven commented on applications/nrf5340_audio/src/audio/le_audio_rx.c
>  		data_size_mismatch = true;
Right you are, removed

2023-10-31 09:45 UTC, erikrobstad requested changes
data_size_mismatch is still there.
You probably forgot to commit?

2023-10-31 09:57 UTC, alexsven commented
> data_size_mismatch is still there. You probably forgot to commit?

Correct, again! 'Removed' 2.0 ;)

2023-10-31 10:30 UTC, erikrobstad approved these changes

2023-10-31 12:02 UTC, merged