applications: nrf5340_audio: Audio datapath sync improvements
nrfconnect/sdk-nrf pull request #12943
Opened 2023-11-02 09:48 UTC by erikrobstad

- Changes to counter resets, so that the sync mechanisms are run less often.
- Change how the sync error/offset is calculated.

2023-11-02 09:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12943/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12943/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12943/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-02 10:03 UTC, erikrobstad commented
We should not merge this until SDC support is in main, and we have rebased and tested these changes using SDC

2023-11-02 12:55 UTC, koffes requested changes

2023-12-07 10:04 UTC, alexsven commented
I guess this can be closed now?

2023-12-19 13:17 UTC, erikrobstad commented
Closing this pull request. Some of these changes are already in NCS.
We will open a new PR if the rest of the changes are needed.

2023-12-19 13:17 UTC, closed without merging