Applications: nrf5340_audio: Experimental addition of SDC in buildprog
nrfconnect/sdk-nrf pull request #12996
Opened 2023-11-07 15:38 UTC by koffes

To be squashed

2023-11-10 04:06 UTC, rick1082 approved these changes
Confirmed this works, I'm using following command for testing:
$ python buildprog.py -c both -b debug -d both -p --pristine --ctlr="SDC" -f -s

But probably we could add a comment in "-h" for mentioning this feature?

2023-11-13 11:08 UTC, alexsven approved these changes

2023-11-13 11:08 UTC, alexsven commented on applications/nrf5340_audio/tools/buildprog/buildprog.py
> +        help="MCUBOOT with external, internal flash. Only for controller: "+Controller.acs_nrf53,
Nitpick: Could need some spaces around `+`

2023-11-13 11:08 UTC, alexsven commented on applications/nrf5340_audio/tools/buildprog/buildprog.py
> +              "Experimental app - controller combination"+Style.RESET_ALL)
```suggestion
              "Experimental app - controller combination" + Style.RESET_ALL)
```

2023-11-13 11:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12996/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12996/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-12996/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-14 09:25 UTC, erikrobstad requested changes
If there are no build folders from "previous SDC builds" present, this command does not work:
python buildprog.py -c net -b debug -d both -p --ctlr SDC --pristine
In other words, it is not possible to do '-c net'.
This should be improved, or possibly just e.g. throw a warning.
![image](https://github.com/nrfconnect/sdk-nrf/assets/89020256/9d660cd0-c07b-4f45-bbd7-3a4df3430aaa)

2023-11-14 14:24 UTC, erikrobstad approved these changes

2023-11-14 14:32 UTC, merged