samples: cellular: mss Fix NRF_MODEM_LIB configuration
nrfconnect/sdk-nrf pull request #13001
Opened 2023-11-08 01:16 UTC by glarsennordic

A recent commit changed the default values for
CONFIG_NRF_MODEM_LIB_NET_IF_AUTO_START
CONFIG_NRF_MODEM_LIB_NET_IF_AUTO_CONNECT
CONFIG_NRF_MODEM_LIB_NET_IF_AUTO_DOWN

but did not update this sample. This commit rectifies that.

2023-11-08 01:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13001/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13001/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13001/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-08 01:19 UTC, plskeggs approved these changes

2023-11-08 01:21 UTC, jayteemo reviewed
https://github.com/nrfconnect/sdk-nrf/pull/12991 should have added a change log entry since it changed a public library's default behavior.

feel free to add one if you'd like.

2023-11-08 01:21 UTC, jayteemo approved these changes

2023-11-08 01:49 UTC, jayteemo approved these changes

2023-11-08 02:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13001
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-08 06:30 UTC, peknis approved these changes

2023-11-08 08:04 UTC, lemrey requested changes
We did agree that samples in NCS shall manage network interfaces and connectivity all in the same way, by manually calling the API functions. I would be fine with keeping `_AUTO_DOWN=y`  though, that is different from the other two.

2023-11-10 08:24 UTC, lemrey approved these changes
Thank you for your patience and for updating the changelog.

2023-11-10 08:34 UTC, merged