twister: quarantine: Add quarantine for tests from sdk-zephyr
nrfconnect/sdk-nrf pull request #13050
Opened 2023-11-10 12:59 UTC by PerMac

Adds a quarantine required for a new workflow, where tests from sdk-zephyr are executed within nrf context (using manifest from nrf)

2023-11-10 13:29 UTC, katgiadla approved these changes

2023-11-10 14:06 UTC, gopiotr approved these changes

2023-11-10 14:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/buran/job/users/job/jag1/job/sdk-nrf/job/PR-13050/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/buran/job/users/job/jag1/job/sdk-nrf/job/PR-13050/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/buran/job/users/job/jag1/job/sdk-nrf/job/PR-13050/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-10 19:00 UTC, jangalda-nsc requested changes
There are still 4 tests failing https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/buran%2Fusers%2Fjag1%2Fsdk-nrf/detail/PR-13050/4/tests

2023-11-13 09:20 UTC, PerMac commented
These all failures are on nrf52833dk. The idea is that we will bring back nrf52840dk to the scope and remove nrf52833dk, hence no need for those.

2023-11-13 15:23 UTC, jangalda-nsc approved these changes

2023-11-13 15:26 UTC, merged