crypto: User Matter version of SPAKE2+
nrfconnect/sdk-nrf pull request #13061
Opened 2023-11-13 09:13 UTC by vili-nordic

Set's the define in Oberon could so Matter compatible of SPAKE2+ is used.

2023-11-13 09:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13061/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13061/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13061/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-13 09:16 UTC, SebastianBoe approved these changes

2023-11-13 09:19 UTC, joerchan requested changes
I suggest we set the define in the config header instead. This avoids changing the external source code.

2023-11-13 09:48 UTC, LuDuda approved these changes

2023-11-27 14:32 UTC, joerchan approved these changes

2023-11-30 08:05 UTC, merged