docs: update KRKNWK-17718 workaround's known issue in Matter
nrfconnect/sdk-nrf pull request #13072
Opened 2023-11-13 15:53 UTC by doublemis1

Update workaround's known issue with the infomation about fixing the software diagnostic's feature-map.

2023-11-13 15:55 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13072/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13072/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-11-13 16:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13072
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-14 08:24 UTC, kkasperczyk-no approved these changes

2023-11-14 08:37 UTC, wiba-nordic requested changes

2023-11-14 08:37 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +.. rst-class:: v2-4-2 v2-4-1 v2-4-0 v2-3-0
Is this an intended change? This line affects issue KRKNWK-17699, not KRKNWK-17718.

2023-11-14 08:37 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  and manually cherry-pick and apply the commit with the fix to ``sdk-connectedhomeip`` (commit hash: ``70dd449ff943159365466ad5125f42a5bdcbfc0b``)
```suggestion
  **Workaround:** Set the default value of the Software Diagnostic cluster feature map to 0 using the ZAP Tool and regenerate files, and manually cherry-pick and apply the commit with the fix to ``sdk-connectedhomeip`` (commit hash: ``70dd449ff943159365466ad5125f42a5bdcbfc0b``).
```

2023-11-14 14:34 UTC, doublemis1 commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  and manually cherry-pick and apply the commit with the fix to ``sdk-connectedhomeip`` (commit hash: ``70dd449ff943159365466ad5125f42a5bdcbfc0b``)
Done

2023-11-15 06:07 UTC, wiba-nordic approved these changes

2023-11-15 07:10 UTC, merged