applications: Added support for groups in the Matter bridge
nrfconnect/sdk-nrf pull request #13084
Opened 2023-11-15 08:13 UTC by kkasperczyk-no

Added declaration of groups cluster and handling attributes read operations for the OnOff Light device.

2023-11-15 08:14 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/599f334e6f865deb7ed452dbc7d63648f822094e (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/351 | [nrfconnect/sdk-connectedhomeip#351/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/351/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-11-15 08:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13084/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13084/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13084/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-15 08:31 UTC, wiba-nordic requested changes

2023-11-15 08:31 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for the groupcast communication to the On/Off Light device implementation.
```suggestion
* Added support for groupcast communication to the On/Off Light device implementation.
```

2023-11-15 08:31 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for the groupcast communication to the On/Off Light device implementation.
```suggestion
* Added support for groupcast communication to the On/Off Light device implementation.
```
Could also be "groupcast commands".

2023-11-15 10:04 UTC, kkasperczyk-no commented
@wiba-nordic added one more change in the known issues section.

2023-11-15 10:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13084
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-15 10:50 UTC, wiba-nordic requested changes

2023-11-15 10:50 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-17360: The groupcast communication does not work for multiple endpoints being part of a group on a single Matter node
```suggestion
KRKNWK-17360: Groupcast communication does not work for multiple endpoints thare are part of a group on a single Matter node
```

2023-11-15 10:50 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  The logic in a Matter core implementation handles commands status in a wrong way for those targeted to a group.
```suggestion
  The Matter core implementation handles commands status in a wrong way for those targeted to a group.
```

2023-11-15 10:50 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  It results in application crash after receiving a group command.
```suggestion
  This issue is only visible when adding multiple endpoints that exist on the same Matter node to the same group, and results in an application crash after receiving a group command.
```

2023-11-15 10:50 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  In case of adding multiple Matter nodes with a single endpoint each to the group, the communication works correctly.
```suggestion
  When adding multiple Matter nodes with a single endpoint each to the same group, the communication works correctly.
```

2023-11-15 10:50 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Manually cherry-pick and apply commit from the main branch (commit hash: ``TODO: fill after merging sdk-connectedhomeip PR``).
```suggestion
  **Workaround:** Manually cherry-pick and apply the commit with the fix to ``sdk-connectedhomeip`` (commit hash: ``TODO: fill after merging sdk-connectedhomeip PR``).
```

2023-11-15 12:39 UTC, wiba-nordic approved these changes

2023-11-16 07:03 UTC, LuDuda approved these changes

2023-11-16 07:13 UTC, merged