doc: Rearranged items on the ncs intro page
nrfconnect/sdk-nrf pull request #13090
Opened 2023-11-15 13:15 UTC by annwoj

Added missing protocols.
Rearranged the order.

2023-11-15 13:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13090
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-16 14:26 UTC, greg-fer requested changes
I'm not convinced we should be touching this page. The network protocols are listed in full here: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/introduction.html

As mentioned in #11845, the Welcome page will be dropped once we switch 100% to TechDocs, so I don't see the point of updating it.

2023-11-17 10:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13090/6/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13090/6/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-11-17 14:43 UTC, greg-fer requested changes
This is great, but we need to keep the old page tag. The proposed edit should fix the doc build.

2023-11-17 14:43 UTC, greg-fer commented on doc/nrf/index.rst
>  .. _index:
```suggestion
.. _index:
.. _ncs_introduction:
```

2023-11-20 08:04 UTC, greg-fer approved these changes

2023-11-20 08:25 UTC, DeidreCasey approved these changes

2023-11-20 12:29 UTC, merged