bt: bas_client: Fix CONTAINER_OF invocation
nrfconnect/sdk-nrf pull request #13124
Opened 2023-11-17 09:40 UTC by trond-snekvik

The bas_client used the k_delayed_work struct instead of the k_work struct to resolve the bt_bas_client with CONTAINER_OF. As k_work is the first member in k_delayed_work, this isn't an active bug, but zephyrproject-rtos/zephyr#61962 adds a static assert for this, which starts failing in the upmerge.

2023-11-17 09:41 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13124/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13124/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13124/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-21 10:11 UTC, nordicjm reviewed
Part of https://github.com/nrfconnect/sdk-nrf/pull/12619

2023-11-24 09:21 UTC, joerchan approved these changes

2023-11-24 09:22 UTC, nordicjm requested changes
-1 to prevent merge, fix is OK but is already part of upmerge and would rather not have to fix a rebase

2023-11-24 09:30 UTC, joerchan commented
> -1 to prevent merge, fix is OK but is already part of upmerge and would rather not have to fix a rebase

Might as well close it then.

2023-11-24 10:05 UTC, closed without merging