doc: build files: move the list to new page
nrfconnect/sdk-nrf pull request #13154
Opened 2023-11-20 12:50 UTC by greg-fer

Moved the reference list of output build files to a new page in the Configuration and building section. Edited other pages for links.

Removed Building FOTA images section and edited info in tables and cross-links.

Added link to MCUboot build output files in Adding MCUboot as an upgradable bootloader.

NCSDK-22324 and NCSIDB-964.

2023-11-20 13:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13154
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-20 13:58 UTC, peknis requested changes

2023-11-20 13:58 UTC, peknis commented on doc/nrf/config_and_build/output_build_files.rst
> +A symbol table is created which maps addresses to symbol names, which is used by debuggers.
```suggestion
A symbol table that maps addresses to symbol names is created.
This table is used by debuggers.
```

2023-11-20 13:58 UTC, peknis commented on doc/nrf/config_and_build/output_build_files.rst
> +When an ELF file is converted into another format, such as HEX or binary, the symbol table is lost.
```suggestion
When an ELF file is converted to another format, such as HEX or binary, the symbol table is lost.
```

2023-11-20 13:58 UTC, peknis commented on doc/nrf/config_and_build/output_build_files.rst
> +The table includes files for single-core and multi-core programming scenarios for both |VSC| and command line building methods.
```suggestion
The table includes files for single-core and multi-core programming scenarios for both |VSC| and command-line building methods.
```

2023-11-20 13:58 UTC, peknis commented on doc/nrf/config_and_build/output_build_files.rst
> +  You can read more about this scenario in :ref:`ug_multi_image`.
```suggestion
  For more details about this scenario, see :ref:`ug_multi_image`.
```

2023-11-20 13:58 UTC, peknis commented on doc/nrf/config_and_build/output_build_files.rst
> +    MCUboot's :doc:`direct-xip mode <mcuboot:design>` and the related :kconfig:option:`CONFIG_BOOT_BUILD_DIRECT_XIP_VARIANT` Kconfig option are currently supported only on the single-core devices suc
```suggestion
.. note::
   MCUboot's :doc:`direct-xip mode <mcuboot:design>` and the related :kconfig:option:`CONFIG_BOOT_BUILD_DIRECT_XIP_VARIANT` Kconfig option are currently supported only on single-core devices, such as nRF52 Series devices.
   For more details, see the :ref:`ug_nrf52_developing_ble_fota_mcuboot_direct_xip_mode` section of the :ref:`ug_nrf52_developing` page.
```

2023-11-21 08:16 UTC, hellesvik-nordic approved these changes

2023-11-21 12:50 UTC, peknis approved these changes

2023-11-21 13:24 UTC, merged

2023-11-21 17:42 UTC, MarekPieta reviewed
Post merge review. Looks good :)