SoftDevice Controller: Update Kconfig entries managing event lengths
nrfconnect/sdk-nrf pull request #13172
Opened 2023-11-21 14:36 UTC by rugeGerritsen

* BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT can now be set to 0
* New: BT_CTLR_MIN_VAL_OF_MAX_ACL_TX_PAYLOAD_DEFAULT. To allow packing events tighter

2023-11-21 14:37 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13172/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13172/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13172/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-21 15:07 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13172
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-22 08:47 UTC, Tschet1 approved these changes

2023-11-22 08:49 UTC, Tschet1 commented on subsys/bluetooth/controller/hci_driver.c
> +				CONFIG_config BT_CTLR_MIN_VAL_OF_MAX_ACL_TX_PAYLOAD_DEFAULT
is this correct?

2023-11-22 08:52 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
> +				CONFIG_config BT_CTLR_MIN_VAL_OF_MAX_ACL_TX_PAYLOAD_DEFAULT
It is not. This needs to be fixed

2023-11-22 09:07 UTC, Tschet1 requested changes
.

2023-11-22 11:22 UTC, jostn approved these changes

2023-11-22 13:09 UTC, Tschet1 approved these changes

2023-11-23 10:54 UTC, merged