wifi: Fix MTU checks
nrfconnect/sdk-nrf pull request #13179
Opened 2023-11-21 20:11 UTC by krish2718

2023-11-21 20:12 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/d7813e2e5f22064f942112b3cd0d9c756b01deb4 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1129 | [nrfconnect/sdk-nrfxlib#1129/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1129/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-11-21 20:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13179/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13179/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13179/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-21 20:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13179
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-11-22 09:15 UTC, rlubos approved these changes

2023-11-22 12:00 UTC, sachinthegreen requested changes

2023-11-22 12:01 UTC, krish2718 commented on drivers/wifi/nrf700x/src/fmac_main.c
> +	(NRF_WIFI_IFACE_MTU + TX_BUF_HEADROOM)
Yes, thanks, will fix.

2023-11-23 08:11 UTC, sachinthegreen approved these changes

2023-11-23 14:29 UTC, merged