samples: mesh: distributor: Add note about securing LE connection
nrfconnect/sdk-nrf pull request #13191
Opened 2023-11-22 13:08 UTC by PavelVPV

Add note about securing LE connection in the distributor sample when accessing SMP characteristics.

2023-11-22 13:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13191/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13191/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-11-22 13:48 UTC, ludvigsj requested changes

2023-11-22 13:48 UTC, ludvigsj commented on samples/bluetooth/mesh/dfu/distributor/README.rst
> +   See `Zephyr Bluetooth LE Security`_ or more details about securing the Bluetooth LE connection.
```suggestion
   See `Zephyr Bluetooth LE Security`_ for more details about securing the Bluetooth LE connection.
```

2023-11-22 13:49 UTC, ludvigsj requested changes

2023-11-22 13:49 UTC, ludvigsj commented on samples/bluetooth/mesh/dfu/distributor/README.rst
> +   This will enforce a remote device to initiate pairing request before accessing SMP characteristics.
```suggestion
   This will enforce a remote device to initiate a pairing request before accessing SMP characteristics.
```

2023-11-22 13:51 UTC, ludvigsj approved these changes

2023-11-22 14:22 UTC, divipillai commented
The doc build error is because homekit no longer exists in main, which is breaking the software maturity level table in the 2.5 branch. Gerad is informed about this issue.

2023-11-23 16:11 UTC, divipillai commented
> The doc build error is because Homekit no longer exists in main, which is breaking the software maturity level table in the 2.5 branch. Gerard is informed about this issue.

@cvinayak : Here also, the issue is because homekit no longer exists in main. The document issue is not PR-specific, and changes related to PR work as expected in the main The document issue can be bypassed.

2023-11-23 16:19 UTC, merged