doc: match nRF Cloud frontend changes
nrfconnect/sdk-nrf pull request #13198
Opened 2023-11-23 07:05 UTC by wiba-nordic

The workflow in the nRF Cloud frontend is changing. This aligns the documentation for the nRF9160 DK and the Thingy:91 to match the new flow.

2023-11-23 07:28 UTC, peknis approved these changes

2023-11-27 11:14 UTC, greg-fer reviewed
I'll be more than happy to review once the doc build issues are resolved and NordicBuilder posts an update.

2023-11-27 11:19 UTC, greg-fer requested changes

2023-11-27 11:19 UTC, greg-fer commented on doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160_gs.rst
>     If you have not yet installed the |NCS| and selected the preferred development environment, the application will point you to the related resources.
I would remove the indent on this entire paragraph.

2023-11-30 09:06 UTC, greg-fer approved these changes

2023-11-30 09:25 UTC, merged