drivers: wifi: Add an assert for enforcing proper TX buffer sizes
nrfconnect/sdk-nrf pull request #13217
Opened 2023-11-23 16:43 UTC by krish2718

The TX buffers should accomodate MTU size and headroom needed, so, add a build assert to avoid dropping packets at runtime.

Fixes SHEL-2175.

(backport of 0e67ad4f9dc3574f8d0ed6e419718238c717e869).

2023-11-23 16:44 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13217/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13217/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13217/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-24 06:07 UTC, VivekUppunda approved these changes

2023-11-24 07:22 UTC, rado17 approved these changes

2023-11-24 12:42 UTC, sachinthegreen requested changes
I guess this also needs the updates from https://github.com/nrfconnect/sdk-nrf/pull/13223 ?

2023-11-27 10:59 UTC, krish2718 commented
> I guess this also needs the updates from #13223 ?

Yes, I was waiting for it to be merged, its now updated.

2023-11-27 12:42 UTC, sachinthegreen approved these changes

2023-11-29 09:08 UTC, divipillai commented
Please rebase the PR to fix the doc build failure. The issue related to homekit is now fixed.

2023-11-29 12:11 UTC, merged