nrf_security: Remove unused vendor max ECC bits
nrfconnect/sdk-nrf pull request #13226
Opened 2023-11-24 11:46 UTC by Vge0rge

This code is not useful anymore for two reasons.
First of all the CONFIG_PSA_CRYPTO_DRIVER_*
symbols are now removed and so this will never
be executed.

The vendor max ECC bits are not configured
but the Oberon PSA core in the file:

core/include/psa/crypto_sizes.h

Depending on the PSA_WANT_* enabled curves.

2023-11-24 11:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13226/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13226/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13226/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-11-24 11:49 UTC, SebastianBoe approved these changes

2023-11-27 09:07 UTC, vili-nordic approved these changes

2023-11-28 17:27 UTC, joerchan requested changes
Remove it from the template as well:

```
/* Max curve bits for PSA APIs */
#cmakedefine PSA_VENDOR_ECC_MAX_CURVE_BITS                      @PSA_VENDOR_ECC_MAX_CURVE_BITS@
```

2023-11-29 16:23 UTC, Vge0rge commented
@joerchan  done :)

2023-11-30 11:43 UTC, joerchan approved these changes

2023-11-30 13:07 UTC, merged