applications: nrf5340_audio: Reimplement function for calculating err_us
nrfconnect/sdk-nrf pull request #13242
Opened 2023-11-27 12:09 UTC by alexsven

- Fix bug where modulo operations where done on negative numbers
- Create helper function to fix both uses in one place

2023-11-27 12:20 UTC, koffes requested changes

2023-11-27 12:20 UTC, koffes commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +static int32_t err_us_calculate(uint32_t sdu_ref_us, uint32_t frame_start_ts)
```suggestion
static int32_t err_calculate_us(uint32_t sdu_ref_us, uint32_t frame_start_ts)
```
Nitpick. Discuss

2023-11-27 12:20 UTC, koffes commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +	int32_t total_err = (sdu_ref_us - frame_start_ts);
Must be int64_t

2023-11-27 12:20 UTC, koffes commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +	bool err_neg = false;
Move to top of function.

2023-11-27 12:20 UTC, koffes commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +
Add comment: How we later take errors over 1000 us into account.

2023-11-27 12:37 UTC, koffes approved these changes

2023-11-27 13:01 UTC, gWacey approved these changes

2023-11-27 16:28 UTC, merged

2023-11-28 03:58 UTC, rick1082 commented
> We need to figure out why we get more negative values for ctrl_blk.previous_sdu_ref_us - frame_start_ts using SDC

Pardon me a dumb question:
Would this because of the different definition between PCFT and SDC regarding with the sdu_ref?