applications: nrf_desktop: NVM instead of flash in doc
nrfconnect/sdk-nrf pull request #13275
Opened 2023-11-29 11:54 UTC by MarekPieta

Change switches to using non-volatile memory term instead of flash in the documentation. Other non-volatile memory may be used aswell.

Jira: NCSDK-24793

2023-11-29 12:00 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13275/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13275/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-11-29 13:01 UTC, kapi-no approved these changes

2023-11-29 13:34 UTC, mkapala-nordic approved these changes

2023-11-29 14:28 UTC, peknis requested changes

2023-11-29 14:28 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Documentation describing :ref:`nrf_desktop_memory_layout` configuration to simplify gettings started for new users.
```suggestion
  * The documentation describing the :ref:`nrf_desktop_memory_layout` configuration to simplify the process of getting started with the application.
```

2023-11-29 14:28 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Changed the flash memory term to the non-volatile memory term to generalize the documentation.
```suggestion

* Changed the term flash memory to non-volatile memory to generalize the documentation.
```

2023-11-29 14:28 UTC, peknis commented on applications/nrf_desktop/README.rst
> +  For details on using an external non-volatile memory for the secondary image slot, see the :ref:`nrf_desktop_pm_external_flash` section.
```suggestion
  For details on using external non-volatile memory for the secondary image slot, see the :ref:`nrf_desktop_pm_external_flash` section.
```

2023-11-29 14:28 UTC, peknis commented on applications/nrf_desktop/README.rst
> +    The swap operation significantly increases boot time after a successful image transfer, but an external non-volatile memory can be used as the secondary image slot.
```suggestion
    The swap operation significantly increases boot time after a successful image transfer, but external non-volatile memory can be used as the secondary image slot.
```

2023-11-29 14:32 UTC, annwoj commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Changed the flash memory term to the non-volatile memory term to generalize the documentation.
Would suggest: 
```suggestion
  * Changed the term *flash memory* to *non-volatile memory* for generalization purposes.
```

2023-11-29 15:25 UTC, mkapala-nordic approved these changes

2023-11-29 15:44 UTC, MarekPieta commented
Updated reference in `release-notes-1.4.0.rst` to fix doc build failure

2023-11-30 06:23 UTC, peknis approved these changes

2023-11-30 07:06 UTC, annwoj approved these changes

2023-11-30 07:55 UTC, kapi-no approved these changes

2023-11-30 08:04 UTC, merged