Do Not Review: Do Not Merge: Prototype for single file PSA/Legacy Mbed TLS configs
nrfconnect/sdk-nrf pull request #13339
Opened 2023-12-05 14:16 UTC by frkv

-Adds PSA Crypto Client awareness (for TF-M)
-Adds single config file prototype
-Involves changes to TF-M, Matter, Openthread and Mbed TLS
-Involves changes to MCUboot

This is a work in progress!

2023-12-05 14:17 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/frkv/sdk-connectedhomeip/commit/3c7f9a68c05916c799429bf726fdf6e0c9439a06 | psa-combined-config/head | [frkv/sdk-connectedhomeip@3c7f9a68..psa-combined-config/head](https://github.com/frkv/sdk-connectedhomeip/compare/3c7f9a68c05916c799429bf726fdf6e0c9439a06..psa-combined-config/head) |
| mbedtls | v3.3.0-ncs2 | psa-combined-config/head | [frkv/sdk-mbedtls@v3.3.0-ncs2..psa-combined-config/head](https://github.com/frkv/sdk-mbedtls/compare/v3.3.0-ncs2..psa-combined-config/head) |
| mcuboot | https://github.com/frkv/sdk-mcuboot/commit/adab597a0eb0eb9c030a7b797748a49ca89988c2 (main) | psa-combined-config/head | [frkv/sdk-mcuboot@adab597a..psa-combined-config/head](https://github.com/frkv/sdk-mcuboot/compare/adab597a0eb0eb9c030a7b797748a49ca89988c2..psa-combined-config/head) |
| trusted-firmware-m | https://github.com/frkv/sdk-trusted-firmware-m/commit/4c908f47646ac082848771d3e066bd709e251dfc | psa-combined-config/head | [frkv/sdk-trusted-firmware-m@4c908f47..psa-combined-config/head](https://github.com/frkv/sdk-trusted-firmware-m/compare/4c908f47646ac082848771d3e066bd709e251dfc..psa-combined-config/head) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-12-05 14:46 UTC, nordicjm requested changes

2023-12-05 14:46 UTC, nordicjm commented on modules/mcuboot/CMakeLists.txt
> +  endif()
this is a problem as sysbuild currently has no access to devicetree info

2023-12-05 14:46 UTC, nordicjm commented on subsys/nrf_security/src/CMakeLists.txt
> +if(CONFIG_MCUBOOT)
Not really liking this, what if someone clones mcuboot and calls it funboot?

2023-12-28 07:46 UTC, rado17 approved these changes

2024-02-27 12:07 UTC, de-nordic commented
@frkv Do you want to remove the Stale label?

2024-05-26 00:29 UTC, closed without merging