applications: nrf_desktop/machine_learning: Align CONFIG_RESET_ON_FATAL_ERROR in MCUboot configs
nrfconnect/sdk-nrf pull request #13378
Opened 2023-12-08 14:00 UTC by mkapala-nordic

Jira: NCSDK-22426

2023-12-08 14:01 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13378/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13378/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13378/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-08 15:01 UTC, kapi-no reviewed
Please add changelog entries

2023-12-15 09:19 UTC, MarekPieta requested changes

2023-12-15 09:19 UTC, MarekPieta commented on applications/nrf_desktop/configuration/nrf52833dk_nrf52833/child_image/mcuboot/prj.conf
> +# Improve debugging experience by disabling reset on fatal error
btw. I would also consider aligning this for B0 bootloader and HCI rpmsg configurations (either under a separate tickets or we can expand scope and story points of this ticket)

2023-12-18 14:03 UTC, mkapala-nordic commented
Only rebased

2023-12-18 14:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13378
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-19 10:18 UTC, mkapala-nordic commented on applications/nrf_desktop/configuration/nrf52833dk_nrf52833/child_image/mcuboot/prj.conf
> +# Improve debugging experience by disabling reset on fatal error
Applied, please verify if i did not miss any conf file as there are a few of them :D

2023-12-19 12:31 UTC, MarekPieta approved these changes

2023-12-19 12:31 UTC, MarekPieta commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated the MCUboot and ``hci_rpmsg`` child image debug configurations to disable the :kconfig:option:`CONFIG_RESET_ON_FATAL_ERROR` Kconfig option.
`MCUboot and HCI RMPsg child images` -> to improve consistency
Also in other places

2023-12-19 12:31 UTC, MarekPieta commented on applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/child_image/mcuboot/prj_release.conf
>  # Use minimal C library instead of the Picolib
typo in commit message (both commits):
`explicitely` -> `explicitly`

2023-12-19 13:06 UTC, zycz approved these changes

2023-12-20 08:06 UTC, annwoj commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    Enabling this Kconfig option improves the reliability of the firmware.
```suggestion
  * The MCUboot, B0, and HCI RPMsg child images debug configurations to disable the :kconfig:option:`CONFIG_RESET_ON_FATAL_ERROR` Kconfig option.
    Disabling this Kconfig option improves the debugging experience.
  * The MCUboot, B0, and HCI RPMsg child images release configurations to explicitly enable the :kconfig:option:`CONFIG_RESET_ON_FATAL_ERROR` Kconfig option.
    Enabling this Kconfig option improves the reliability of the firmware.
```

2023-12-20 08:13 UTC, mkapala-nordic commented
Applied @annwoj suggestions

2023-12-20 08:14 UTC, mkapala-nordic commented
Rebased

2023-12-20 09:22 UTC, annwoj approved these changes

2024-01-02 08:40 UTC, mkapala-nordic commented
Rebased

2024-01-12 08:28 UTC, merged