samples: matter: Initial version of PSA Crypto in Matter
nrfconnect/sdk-nrf pull request #13416
Opened 2023-12-12 15:23 UTC by ArekBalysNordic

PSA Crypto API can be enabled in Matter samples by adding selecting `CONFIG_CHIP_CRYPTO_PSA` to y.

2023-12-12 15:23 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/3b8ba59f1f43d84754de4facfac23f46f8d7cc71 | https://github.com/nrfconnect/sdk-connectedhomeip/pull/311 | [nrfconnect/sdk-connectedhomeip#311/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/311/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-12-12 15:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13416/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13416/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13416/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-12 15:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13416
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-19 09:59 UTC, wiba-nordic requested changes

2023-12-19 09:59 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  It can be enabled by setting :kconfig:option:`CONFIG_CHIP_CRYPTO_PSA` to ``y``.
```suggestion
  It can be enabled by setting the :kconfig:option:`CONFIG_CHIP_CRYPTO_PSA` Kconfig option to ``y``.
```

2023-12-19 12:24 UTC, wiba-nordic approved these changes

2023-12-19 12:37 UTC, ArekBalysNordic commented
@wiba-nordic, sorry, one more small change was needed :/ The new PSA solution has been enabled only for Thread for now. I needed to add it to the release notes.

2023-12-19 12:48 UTC, wiba-nordic requested changes

2023-12-20 10:49 UTC, markaj-nordic approved these changes

2023-12-20 10:49 UTC, Damian-Nordic approved these changes

2023-12-21 08:58 UTC, merged