applications: nrf5340_audio: Fix netcore scheduler
nrfconnect/sdk-nrf pull request #13415
Opened 2023-12-12 14:43 UTC by pirun

Turn off sys clock related kconfig to prevent network core scheduler abnormal.

2023-12-12 14:44 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13415/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13415/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13415/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-12 15:00 UTC, rick1082 approved these changes

2023-12-15 07:20 UTC, erikrobstad requested changes
Thank you for the help on this.
Maybe it is better to do CONFIG_SOC_NRF53_RTC_PRETICK=n instead of using CONFIG_SYS_CLOCK_EXISTS?

2023-12-15 11:47 UTC, koffes commented
Thanks. Please coordinate this with @andvib.

2023-12-15 12:00 UTC, andvib requested changes
I agree with Erik - using CONFIG_SOC_NRF53_RTC_PRETICK=n disables only the functionality that caused the bug to appear.

Maybe we should add a comment to why this must be disabled as well? Mentioning that that the controller isn't affected by the anomaly this fixes, and that there's a resource collision between B0N and the controller

2023-12-15 12:07 UTC, erikrobstad commented
> I agree with Erik - using CONFIG_SOC_NRF53_RTC_PRETICK=n disables only the functionality that caused the bug to appear.
> 
> Maybe we should add a comment to why this must be disabled as well? Mentioning that that the controller isn't affected by the anomaly this fixes, and that there's a resource collision between B0N and the controller

Agreed

2023-12-15 12:20 UTC, closed without merging