lib: pdn: improve pdn_dynamic_params_get()
nrfconnect/sdk-nrf pull request #13426
Opened 2023-12-13 12:52 UTC by tomi-font

Make use of nrf_modem_at_scanf() and add a changelog entry.

2023-12-13 12:55 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13426/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13426/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13426/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-13 13:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13426
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-13 16:17 UTC, lemrey commented
Because this PR updates the changelog file, it must be reviewed by a tech writer before it can be merged.
I am adding back the `doc-required` label.

The `doc-required` label is added automatically when changes to certain files are detected (documentation changes), so in general it should not be removed. Instead you must add a tech writer to review and approve your PR.

The `changelog-entry-required` label is added automatically to all PRs. Some PRs don't require updates to the changelog, so that label can be removed, but if you remove it then you should provide an argument as to why the changelog does not need to be updated.

2023-12-14 06:35 UTC, MarkusLassila approved these changes

2023-12-14 07:09 UTC, tomi-font commented
> Because this PR updates the changelog file, it must be reviewed by a tech writer before it can be merged.
I am adding back the doc-required label.
>
> The doc-required label is added automatically when changes to certain files are detected (documentation changes), so in general it should not be removed. Instead you must add a tech writer to review and approve your PR.

True. I know how it works but somehow dismissed it as a `changelog-entry-required` label, thinking that there were no documentation changes. But the changelog itself is a document.
Thanks again for pointing this out.

2023-12-14 07:27 UTC, peknis requested changes

2023-12-14 07:27 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +   * Added a function to retrieve dynamic parameters of an active PDN connection, :c:func:`pdn_dynamic_params_get`.
```suggestion
   * Added the :c:func:`pdn_dynamic_params_get` function to retrieve dynamic parameters of an active PDN connection.
```

2023-12-14 07:36 UTC, peknis approved these changes

2023-12-14 18:24 UTC, lemrey approved these changes
No problem thanks for the patch

2023-12-15 08:19 UTC, SeppoTakalo approved these changes

2023-12-15 08:19 UTC, merged