lib: nrf_fuel_gauge: Update nRF Fuel Gauge
nrfconnect/sdk-nrf pull request #13420
Opened 2023-12-13 09:05 UTC by nordic-auko

Update nrfxlib nRF Fuel Gauge to v0.9.1,
and adjust sample and test accordingly.

2023-12-13 09:06 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a1cfe142b6060b8976201d959f6db5c8f6f989ca | https://github.com/nrfconnect/sdk-nrfxlib/pull/1141 | [nrfconnect/sdk-nrfxlib#1141/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1141/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-12-13 09:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13420/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13420/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13420/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-13 09:43 UTC, WalkingTalkingPotato approved these changes

2023-12-13 09:48 UTC, aasinclair commented on samples/pmic/native/npm1300_fuel_gauge/src/fuel_gauge.c
> +#define NPM1300_CHG_STATUS_CC_MASK BIT_MASK(3)
I'll add a JIRA to add this upstream.

2023-12-13 10:07 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13420
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-15 09:08 UTC, peknis requested changes

2023-12-15 09:08 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated :ref:`npm1300_fuel_gauge` to accommodate API changes in :ref:`nrfxlib:nrf_fuel_gauge`.
```suggestion
* :ref:`npm1300_fuel_gauge` sample:

  * Updated to accommodate API changes in the :ref:`nrfxlib:nrf_fuel_gauge`.
```

2023-12-15 09:12 UTC, peknis approved these changes

2023-12-15 10:00 UTC, merged