dfu: dfu_target: auto enable fmfu parition
nrfconnect/sdk-nrf pull request #13443
Opened 2023-12-14 14:18 UTC by gregersrygg

The full modem update could overwrite other partitions on ext. flash if CONFIG_DFU_TARGET_FULL_MODEM_USE_EXT_PARTITION was not enabled.

Change the default value to CONFIG_PM_EXTERNAL_FLASH_ENABLED. Which is enabled when the chosen node nordic,pm-ext-flash is set in device tree.

Also removed nordic,pm-ext-flash from samples that didn't use partitions in external flash and removed docs not needed anymore.

2023-12-14 14:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13443/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13443/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13443/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-14 14:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13443
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-15 09:27 UTC, peknis requested changes

2023-12-15 09:27 UTC, peknis commented on doc/nrf/libraries/dfu/dfu_target.rst
> +When ``nordic,pm-ext-flash`` is set, :ref:`partition_manager` will add the partition ``fmfu_storage`` to the external flash region.
```suggestion
External flash partitions require the chosen node ``nordic,pm-ext-flash`` to be set to the external flash device in devicetree, see :ref:`partition_manager` for details.
When ``nordic,pm-ext-flash`` is set, the :ref:`partition_manager` will add the partition ``fmfu_storage`` to the external flash region.
```

2023-12-15 09:27 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * :kconfig:option:`CONFIG_DFU_TARGET_FULL_MODEM_USE_EXT_PARTITION` is automatically enabled when ``nordic,pm-ext-flash`` is chosen in the devicetree; see :ref:`partition_manager` for details.
```suggestion
  * Updated:
  
    * The :kconfig:option:`CONFIG_DFU_TARGET_FULL_MODEM_USE_EXT_PARTITION` Kconfig option to be automatically enabled when ``nordic,pm-ext-flash`` is chosen in the devicetree.
      See :ref:`partition_manager` for details.
```

2023-12-15 10:14 UTC, peknis approved these changes

2023-12-15 11:29 UTC, SeppoTakalo approved these changes

2023-12-15 17:24 UTC, plskeggs approved these changes
you might fix the spelling error in the commit title

2023-12-18 09:05 UTC, merged