bluetooth: scan: Add connect_if_match flag update function.
nrfconnect/sdk-nrf pull request #13458
Opened 2023-12-15 14:23 UTC by maje-emb

Commit adds connet_if_match flag update function.

2023-12-15 14:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13458/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13458/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13458/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-15 14:51 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13458
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-19 06:52 UTC, peknis requested changes

2023-12-19 06:52 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The :c:func:`bt_scan_update_connect_if_match` function to update the autoconnect flag after a filter match.
```suggestion
  * Added the :c:func:`bt_scan_update_connect_if_match` function to update the autoconnect flag after a filter match.
```

2023-12-19 07:39 UTC, dchat-nordic approved these changes

2023-12-19 09:37 UTC, KAGA164 requested changes

2023-12-19 11:10 UTC, maje-emb commented on include/bluetooth/scan.h
> +#if CONFIG_BT_CENTRAL
This function is useless e.g when BT_OBSERVER is enabled. Therefore there is conditional compilation, as for CONFIG_BT_SCAN_FILTER_ENABLE in this file.

2023-12-19 12:32 UTC, KAGA164 commented on include/bluetooth/scan.h
> +#if CONFIG_BT_CENTRAL
Still it can be under conditional compilation in source file

2023-12-20 12:55 UTC, grochu approved these changes
Looks good - if it simplifies the implementation in some use cases why not add it, the cost is low.

2023-12-20 14:18 UTC, maje-emb commented on include/bluetooth/scan.h
> +#if CONFIG_BT_CENTRAL
Yes, this is not needed in the header file.

2023-12-21 07:56 UTC, peknis approved these changes

2023-12-21 07:56 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> + :ref:`nrf_bt_scan_readme` library:
```suggestion
 :ref:`nrf_bt_scan_readme`:
```
Not so sure about this. This library is called Scanning module. Feels a bit awkward to call it Scanning module library.

2024-01-02 08:48 UTC, merged