matter: pull deferred attribute persister fix
nrfconnect/sdk-nrf pull request #13465
Opened 2023-12-18 12:53 UTC by Damian-Nordic

Fix memory leak in DeferredAttributePersister class.

2023-12-18 12:54 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/c84b2c43069a14c047e27f652dedb944d64c0a9c | https://github.com/nrfconnect/sdk-connectedhomeip/pull/369 | [nrfconnect/sdk-connectedhomeip#369/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/369/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-12-18 12:55 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13465/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13465/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13465/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-18 13:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13465
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-18 13:55 UTC, wiba-nordic requested changes

2023-12-18 13:55 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-18221: Deferred attribute persister leaks heap memory buffer.
```suggestion
KRKNWK-18221: Memory leak in the deferred attribute persister
```

2023-12-18 13:55 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  This can eventually lead to running out of heap memory and the need for rebooting a device to restore its normal operations.
```suggestion
  This class leaks a 1-byte heap memory buffer for each deferred attribute write, which can eventually lead to running out of heap memory until the device is rebooted.
```

2023-12-22 08:39 UTC, wiba-nordic approved these changes

2024-01-02 09:17 UTC, markaj-nordic approved these changes

2024-01-02 10:42 UTC, kkasperczyk-no approved these changes

2024-01-02 10:56 UTC, merged