samples: openthread: disable `mx25r64` in OpenThread samples
nrfconnect/sdk-nrf pull request #13475
Opened 2023-12-19 14:44 UTC by maciejbaczmanski

`mx25r64` is used to enable QSPI in nrf samples. It is not used in OpenThread and should be disabled by default.

In the future, disabling `mx25r64` will be handled directly in boards `.dts` zephyr files, but until then, we should disable it in project overlays.

2023-12-19 14:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13475/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13475/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13475/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-19 14:55 UTC, edmont approved these changes

2023-12-19 15:37 UTC, canisLupus1313 commented on samples/openthread/coap_client/boards/nrf52840dk_nrf52840.overlay
> +};
The convention normally is different. node should be disabled by default and then enabled when needed.
```suggestion
&mx25r64 {
	status = "okay";
};
```

2023-12-19 15:37 UTC, canisLupus1313 requested changes
```
&mx25r64 {
	status = "disabled";
};

2023-12-20 08:01 UTC, maciejbaczmanski commented
As discussed with @canisLupus1313 , we will wait for `mx25r64` to be disabled by default in zephyr to keep the correct convention

2023-12-20 08:01 UTC, closed without merging