doc: install_ncs: fix slash formatting
nrfconnect/sdk-nrf pull request #13481
Opened 2023-12-20 08:44 UTC by greg-fer

Updated formatting in parsed-literal and code-blocks. Changed \ to / for Windows commands.

2023-12-20 09:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13481
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-20 10:16 UTC, peknis requested changes

2023-12-20 10:16 UTC, peknis commented on doc/nrf/installation/install_ncs.rst
> +         nrfutil toolchain-manager config --set toolchain-index=\*custom_toolchain_URL*
This does not do the trick yet. I believe this needs an empty space between the backslash and the asterisk, possibly the same combination after the second asterisk.

2023-12-21 06:45 UTC, peknis requested changes

2023-12-21 06:45 UTC, peknis commented on doc/nrf/installation/install_ncs.rst
> +         nrfutil toolchain-manager config --set toolchain-index=\*custom_toolchain_URL\*
Still missing an empty space after the backslash. The latter backslash is probably not needed.

2024-01-02 09:28 UTC, peknis approved these changes

2024-01-02 09:48 UTC, nordicjm requested changes

2024-01-02 09:48 UTC, nordicjm commented on doc/nrf/installation/install_ncs.rst
> +                        ncs/.venv/Scripts/activate.bat
Not valid for command prompt

2024-01-02 10:19 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13481/4/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13481/4/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-01-02 12:13 UTC, nordicjm approved these changes

2024-01-02 12:13 UTC, merged