manifest: sdk-zephyr: Pull Wi-Fi shell improvements
nrfconnect/sdk-nrf pull request #13504
Opened 2023-12-22 09:04 UTC by krish2718

Mainly in help and argument count fixes.

2023-12-22 09:04 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/426213023e08965311421143ca3abe2ec25b39a4 (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1429 | [nrfconnect/sdk-zephyr#1429/files](https://github.com/nrfconnect/sdk-zephyr/pull/1429/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-12-22 09:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13504/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13504/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13504/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-12-22 09:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13504
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-12-22 10:58 UTC, sachinthegreen approved these changes

2023-12-22 16:01 UTC, trantanen commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +      * ``CONFIG_WIFI_MGMT_SCAN_MAX_BSS_CNT``
Should migration to `CONFIG_NRF_WIFI_SCAN_MAX_BSS_CNT` be mentioned here?

2023-12-26 08:48 UTC, D-Triveni approved these changes

2023-12-28 07:22 UTC, rado17 approved these changes

2024-01-02 06:06 UTC, krga2022 approved these changes

2024-01-02 18:34 UTC, plskeggs approved these changes

2024-01-03 15:41 UTC, richabp requested changes

2024-01-03 15:41 UTC, richabp commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +  * A few Kconfig options related to scan operations have been removed in the current release. If your application uses scan operations, they need to be updated to remove the dependency on the follow
```suggestion
  * A few Kconfig options related to scan operations have been removed in the current release.
     If your application uses scan operations, they need to be updated to remove the dependency on the following options:
```

2024-01-03 18:54 UTC, glarsennordic approved these changes

2024-01-04 12:46 UTC, richabp approved these changes

2024-01-04 13:04 UTC, merged