Add Shell support for raw Tx Injection
nrfconnect/sdk-nrf pull request #13517
Opened 2024-01-02 07:38 UTC by D-Triveni

2024-01-02 07:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13517/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13517/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13517/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-03 13:36 UTC, D-Triveni commented on samples/wifi/shell/src/wifi_raw_tx_pkt_shell.c
> +		if (strcmp(argv[i], "-f") == 0 || strcmp(argv[i], "--rate-flags") == 0) {
No specific reason for using ``strcmp``. Updated to use ``getopt`` for consistency with the approach in ``net/l2/wifi/``

2024-01-04 11:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13517
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-04 16:06 UTC, krish2718 approved these changes

2024-01-05 06:26 UTC, bama-nordic approved these changes

2024-01-10 05:59 UTC, VivekUppunda approved these changes

2024-01-10 10:48 UTC, richabp requested changes
This needs a Changelog entry for the added support.

2024-01-10 10:48 UTC, richabp commented on samples/wifi/shell/README.rst
> +       | [-h, --help] : Print out the help for the send command.
```suggestion
     - | Configure the raw TX packet header with the following parameters:
       | [-f, --rate-flags]: Rate flag value.
       | [-d, --data-rate]: Data rate value.
       | [-q, --queue-number]: Queue number.
       | [-h, --help]: Print out the help for the configure command.
   * - send
     - | Send raw TX packets
       | parameters:
       | [-m, --mode]: Mode of transmission (either continuous or fixed).
       | [-n, --number-of-pkts]: Number of packets to be transmitted.
       | [-t, --inter-frame-delay]: Delay between frames or packets.
       | [-h, --help]: Print out the help for the send command.
```

2024-01-10 13:40 UTC, D-Triveni commented
> This needs a Changelog entry for the added support.

Added.

2024-01-11 14:15 UTC, rado17 approved these changes

2024-01-15 11:45 UTC, richabp requested changes

2024-01-15 11:45 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added `raw_tx` extension to the Wi-Fi command line.
```suggestion
    * Added ``raw_tx`` extension to the Wi-Fi command line.
```

2024-01-18 07:47 UTC, richabp approved these changes

2024-01-19 12:03 UTC, krga2022 approved these changes

2024-01-19 12:28 UTC, merged