doc: config_and_build: regroup pages
nrfconnect/sdk-nrf pull request #13548
Opened 2024-01-05 10:34 UTC by greg-fer

Created "Configuring application" section with "Configuring devicetree". Moved devicetree related information under the devicetree section. The landing page reuses contents of Changing hardware config section.

Created "Board support" section.
Split information on former board support page into several pages.

NCSDK-22324.

2024-01-05 11:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13548
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-08 09:08 UTC, greg-fer commented
@richabp , can you have a look at the shield table? I've added mentions of Wi-Fi boards there.

2024-01-09 14:12 UTC, richabp requested changes

2024-01-09 14:12 UTC, richabp commented on doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst
> +.. _nrf70_gs_shields_expansion_boards_nrf7002ek:
```suggestion
.. _nrf70_gs_shields_evaluation_kit_nrf7002ek:
```

2024-01-09 14:21 UTC, trond-snekvik approved these changes

2024-01-12 07:46 UTC, DeidreCasey requested changes

2024-01-12 08:24 UTC, richabp commented on doc/tags.yml
> +                                                "nrf9160", "thingy91", "nrf5340", "thingy53",
FYI, Uma has raised a PR for adding nrf9161: https://github.com/nrfconnect/sdk-nrf/pull/13591.

2024-01-12 08:27 UTC, DeidreCasey approved these changes

2024-01-12 10:28 UTC, richabp commented
> @richabp , can you have a look at the shield table? I've added mentions of Wi-Fi boards there.

Confirmed with Bansi, the entries are correct.

2024-01-12 10:52 UTC, richabp approved these changes

2024-01-15 07:13 UTC, merged