LwM2M: Ground fix object workaround and fixes
nrfconnect/sdk-nrf pull request #13559
Opened 2024-01-08 13:07 UTC by SeppoTakalo

Two changes in this PR:

### samples: lwm2m_client: Workaround ground fix problem
AVSystem server assumes incorrect object version for
Connection Monitoring object.

Breaks Ground Fix queries.
Force object version reporting by using different
Connection Monitor object version.

Reported as CDM-665

### net: lwm2m_client_utils: Forward ground fix data to Location obj

If LwM2M Location object is used and Ground Fix object receives
current location, forward that location to Location object as well.

2024-01-10 07:59 UTC, juhaylinen approved these changes

2024-01-10 10:59 UTC, peknis requested changes

2024-01-10 10:59 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added workaround for Ground Fix Location assistance queries in AVSystem Coiote by using fixed Connectivity Monitor object version. This is enabled in :file:`overlay-assist-cell.conf` configuratio
```suggestion
  * Added a workaround for Ground Fix Location assistance queries in AVSystem Coiote by using fixed Connectivity Monitor object version.
  This is enabled in the :file:`overlay-assist-cell.conf` configuration overlay.
```

2024-01-10 10:59 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * If device location is requested using Ground Fix location services, received coordinates will be copien in to the LwM2M Location object.
```suggestion
  * Updated the received coordinated to be copied to the LwM2M Location object, when device location is requested using Ground Fix location services.
```
Or is it rather fixed than updated?

2024-01-10 11:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13559
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-10 12:52 UTC, peknis approved these changes
Approved with minor nit.

2024-01-10 12:52 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Updated the Ground fix object to copy received coordinates to the LwM2M Location object.
```suggestion
  * Updated the Ground Fix object to copy received coordinates to the LwM2M Location object.
```

2024-01-11 13:14 UTC, SeppoTakalo commented
Added workaround for other overlays as well, as this seem to affect others as well. At least AGPS is affected.

2024-01-12 12:54 UTC, trantanen approved these changes

2024-01-16 10:46 UTC, dilner approved these changes

2024-01-16 14:56 UTC, merged