bluetooth: hids: Don't leak conn_ctx on error paths in writes
nrfconnect/sdk-nrf pull request #13553
Opened 2024-01-07 22:42 UTC by ndreys

A number of erros paths in various _write functions do early returns after acquiring conn_ctx without releasing the context first. Fix this by converting affected early returns in to error cleanup gotos and sharing the "happy path" cleanup sequence.

2024-01-07 22:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=13553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=13553) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=13553) it.</sub>

2024-01-07 22:43 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2024-01-08 06:21 UTC, jori-nordic requested changes

2024-01-08 06:21 UTC, jori-nordic commented on subsys/bluetooth/services/hids.c
> +		len = BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
`ret =`

2024-01-08 21:19 UTC, ndreys commented on subsys/bluetooth/services/hids.c
> +		len = BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
Updated. Thanks for catching that!

2024-01-09 08:32 UTC, jori-nordic approved these changes
thanks for the patch!

2024-01-09 08:38 UTC, alwa-nordic approved these changes

2024-01-10 12:37 UTC, KAGA164 approved these changes
Good catch. Thanks

2024-01-10 12:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13553/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13553/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13553/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-10 17:24 UTC, merged