Bluetooth: Mesh: Add new Sensor API support to light_ctrl
nrfconnect/sdk-nrf pull request #13576
Opened 2024-01-10 15:33 UTC by ludvigsj

This adds support for running the light_ctrl model when the new Sensor
API is enabled.

Some API signatures in the light_ctrl_cli have been changed to use the
new bt_mesh_sensor_value when the new API is enabled.

Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>

2024-01-10 16:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13576
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-12 13:03 UTC, PavelVPV approved these changes

2024-01-16 07:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13576/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13576/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13576/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-16 14:09 UTC, HaavardRei approved these changes

2024-01-17 08:31 UTC, mia-ko requested changes

2024-01-17 08:31 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * :ref:`bt_mesh_light_ctrl_readme` APIs are updated to match new Sensor APIs.
```suggestion
  * :ref:`bt_mesh_light_ctrl_readme` APIs to match new Sensor APIs.
```
Would we like a link to Sensor API?

2024-01-17 08:57 UTC, mia-ko approved these changes

2024-01-17 12:43 UTC, merged