Applications: nrf5340_audio: timestamp implementation
nrfconnect/sdk-nrf pull request #13589
Opened 2024-01-11 14:28 UTC by koffes

OCT-2809
integrate timestamps for L-R sync

2024-01-11 14:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13589/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13589/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13589/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-18 09:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13589
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-23 13:28 UTC, henrla commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +		ret = bt_iso_chan_get_tx_sync(iso_chan, &tx_info[i].iso_tx);
You could consider calling this inside the if on line 196.

2024-01-24 08:15 UTC, alexsven requested changes

2024-01-24 08:21 UTC, henrla commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +			LOG_ERR("Not all channels have the same ISO interval");
CISes/BISes in the same CIG/BIG must have the same SDU_interval and ISO_interval. I suspect that the application does not have streams from different CIGs/BIGs here. If this is the case, you are right, this check should not be necessary.

2024-01-24 08:37 UTC, henrla commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +		}
It is not necessary to do it again for synchronizing. So it should only be kept as is if it is necessary to have updated tx_info for some other reason.

2024-01-24 10:58 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +		}
We needed this before for checking the status, but this may not be required anymore. Let me refactor and run some tests.

2024-01-24 19:54 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +			LOG_ERR("Not all channels have the same ISO interval");
Discuss. This is a cheap check to validate that the user has not misconfigured the intervals. I have added a return.

2024-01-24 20:08 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
> +		}
Moved the code so it is only called once.

2024-01-25 07:37 UTC, alexsven approved these changes

2024-01-28 15:17 UTC, rick1082 commented on applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
I would suggest we need to add some doc for this static function, since it is an important function and also the mechanism is complex.

2024-01-29 12:49 UTC, rick1082 approved these changes

2024-01-29 13:32 UTC, alexsven approved these changes

2024-01-29 14:02 UTC, merged