Support to disable DFS channels in scan
nrfconnect/sdk-nrf pull request #13596
Opened 2024-01-12 10:11 UTC by ajayparida

Default scan operation includes DFS channels which are passive. A significant amount of time is taken for scan to complete.
To reduce overall scan duration user can disable scanning on DFS channels.

2024-01-12 10:11 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/d72297308cf359ddb1bdb061a0f846d36928fd62 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1159 | [nrfconnect/sdk-nrfxlib#1159/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1159/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-01-12 10:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13596/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13596/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13596/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-12 10:17 UTC, krish2718 requested changes

2024-01-12 10:17 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	bool "Disables dfs channels in scan operation"
```suggestion
	bool "Disables DFS channels in scan operation"
```

2024-01-12 10:17 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	  This option disables inclusion of dfs channels in scan operation.
```suggestion
	  This option disables inclusion of DFS channels in scan operation.
	  This is useful to reduce the scan time, as DFS channels are seldom used.
```

2024-01-12 10:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13596
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-12 13:53 UTC, ajayparida commented
> Please raise and link Linux PR.
Updated

2024-01-18 06:50 UTC, sachinthegreen approved these changes

2024-01-18 09:57 UTC, rado17 approved these changes

2024-01-19 10:20 UTC, rlubos commented
@ajayparida The manifest change doesn't seem right, as it updates SHA to an older commit, note that `https://github.com/nrfconnect/sdk-nrfxlib/commit/7d7b831e63444238febe9f2e88d8b5ea404fc3ff` is already the topmost commit in `sdk-nrfxlib`.

2024-01-19 10:26 UTC, rlubos approved these changes

2024-01-19 12:28 UTC, merged