manifest: crypto: nsib: Ensure nrf_cc310_bl is only used in bootloaders
nrfconnect/sdk-nrf pull request #13602
Opened 2024-01-12 13:49 UTC by vili-nordic

-NOTE: Manifest combined with code change for bisectability. This pulls
 in items dependent items from nrfxlib.
-This ensures that nrf_cc310_bl library is only used for bootloaders
 and is not linked into main application.

ref: NCSDK-25144

2024-01-12 13:49 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/d72297308cf359ddb1bdb061a0f846d36928fd62 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1160 | [nrfconnect/sdk-nrfxlib#1160/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1160/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-01-12 14:20 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13602
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-16 09:49 UTC, mswarowsky approved these changes

2024-01-16 11:19 UTC, SebastianBoe commented on subsys/bootloader/bl_crypto/CMakeLists.txt
> +if(CONFIG_IS_SECURE_BOOTLOADER OR CONFIG_ZTEST)
I see that we have

add_subdirectory_ifdef(CONFIG_IS_SECURE_BOOTLOADER bootloader)

in nrf/subsys/CMakeLists.txt, so CONFIG_IS_SECURE_BOOTLOADER is always true.

Unless this CMakeLists.txt is sourced from elsewhere? (Which would be bad practice).

Making this if statement always true.

Would you mind explaining this if-statement?

2024-01-16 12:42 UTC, SebastianBoe requested changes
Discussed offline, I think there is a simpler way to solve NCSDK-25144.

Will do some prototyping and report back.

2024-01-17 09:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13602/6/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13602/6/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13602/6/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-17 13:52 UTC, merged