applications: nrf5340_audio: Fix bonding test with SDC
nrfconnect/sdk-nrf pull request #13634
Opened 2024-01-16 21:26 UTC by gWacey

OCT-2846

For bonding testing, only the Bluetooth address must change after each re-flash of the tester device. This also requires the bonding information on the tester to be cleared. A new testing menu for the Bluetooth has been added with a config to select the additional testing code within bt_mgmt.c to perform the desired tester actions.

2024-01-16 21:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13634/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13634/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13634/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-16 21:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13634
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-17 09:18 UTC, koffes approved these changes

2024-01-18 09:58 UTC, alexsven requested changes

2024-01-18 09:58 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
> +static int static_addr_random(void)
It seems a bit strange that we have one function called `random_static_addr_cfg()` and another called `static_addr_random()`. I suggest the following: `random_static_addr_cfg` --> `ficr_static_addr_set` and `static_addr_random` --> `random_static_addr_set`

2024-01-18 09:58 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
>  		ret = settings_load();
```suggestion
		if (!IS_ENABLED(CONFIG_TESTING_BLE_ADDRESS_RANDOM)) {
		    ret = settings_load();
```
and then remove the code you added below. If we never load in the bonding information we don't need to clear it

2024-01-23 11:54 UTC, koffes approved these changes

2024-01-23 11:54 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
> +static int random_static_addr_set(void)
Suggest: Have a comment on this function as well, like the one you have besides the Kconfig.

2024-01-24 07:12 UTC, alexsven approved these changes

2024-01-24 20:09 UTC, koffes approved these changes

2024-01-25 08:05 UTC, alexsven approved these changes

2024-01-25 09:27 UTC, merged