samples: radio_test: Add support for nRF54
nrfconnect/sdk-nrf pull request #13665
Opened 2024-01-18 15:02 UTC by dchat-nordic

Add support for nRF54H20 and nRF54L15 in radio_test.

Jira: NCSDK-25455

2024-01-18 15:04 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13665/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13665/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13665/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-19 17:37 UTC, KAGA164 commented on samples/peripheral/radio_test/src/radio_test.c
> +		uint32_t temp;
Not sure what definitions will be in MDK for this repository but we could consider using register and bitmask definition instead of magic numbers

2024-01-26 10:39 UTC, grochu commented
@dchat-nordic aren't there any updates in documentation that need migration together with the code and build system files?

2024-01-26 10:45 UTC, dchat-nordic commented
> @dchat-nordic aren't there any updates in documentation that need migration together with the code and build system files?

Currently there are some docs missing i.e. nRF54 building/running template and the naming of the DK is still to be merged (for sample.yaml).

2024-01-26 14:21 UTC, maje-emb requested changes
Please note that the board name will change from `nrf54l15dk_nrf54l15_cpuapp` to `nrf54l15pdk_nrf54l15_cpuapp` so the overlay and conf files must be adapted.

2024-01-26 14:21 UTC, maje-emb commented on samples/peripheral/radio_test/src/radio_test.c
>  	switch (tx_power) {
-7 -6 -4 -3 -2 -1 3 4 5 6 7 8 dBm are missing.
Also in `SHELL_STATIC_SUBCMD_SET_CREATE`.

2024-04-03 13:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13665
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-05 14:25 UTC, grochu approved these changes

2024-04-09 11:26 UTC, KAGA164 approved these changes

2024-04-09 11:41 UTC, maje-emb approved these changes

2024-04-09 11:50 UTC, peknis requested changes

2024-04-09 11:50 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```suggestion
    
  * Added:
  
    * Support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```

2024-04-09 12:17 UTC, KAGA164 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
Done

2024-04-09 12:19 UTC, peknis approved these changes

2024-04-09 13:57 UTC, peknis requested changes

2024-04-09 13:57 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```suggestion
  * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```

2024-04-09 14:05 UTC, KAGA164 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
Done

2024-04-09 14:06 UTC, peknis approved these changes

2024-04-09 14:53 UTC, merged