manifest: sdk-nrfxlib: Replace RF parameter string with a structure definition
nrfconnect/sdk-nrf pull request #13720
Opened 2024-01-24 11:43 UTC by imapa

[SHEL-1493]: Replace the string with a structure definition for better readability.

2024-01-24 11:44 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/352ea3d4a6917df35392dde942e6a36a6c3f802a | https://github.com/nrfconnect/sdk-nrfxlib/pull/1172 | [nrfconnect/sdk-nrfxlib#1172/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1172/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-01-24 11:49 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13720/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13720/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13720/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-24 13:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13720
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-02 12:00 UTC, sachinthegreen requested changes

2024-02-02 12:00 UTC, sachinthegreen commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +	ctx->conf_params.rf_params[NRF_WIFI_TX_PWR_CEIL_BYTE_OFFSET +
(Generic comment) Can't we now just cast this to struct nrf_wifi_phy_rf_params and assign to the member elements of the structure ?

2024-02-05 08:00 UTC, rlubos commented on samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
> +			* So,multiply 4 to MAX_TX_PWR_RADIO_TEST and
Please fix this compliance issue (align `*`).

2024-02-05 11:32 UTC, krish2718 approved these changes

2024-02-05 11:34 UTC, sachinthegreen approved these changes

2024-02-05 11:50 UTC, merged