lwm2m: Use DTLS CID by default
nrfconnect/sdk-nrf pull request #13727
Opened 2024-01-24 14:01 UTC by SeppoTakalo

## samples: lwm2m-client: Use DTLS CID by default

As the currently supported modem FW(1.3.6) support DTLS CID,
and similarly most common LwM2M servers support it,
enable CID by default.

## net: lwm2m_client_utils: Deprecate LWM2M_CLIENT_UTILS_DTLS_CID

As the Zephyr LwM2M engine already supports CONFIG_LWM2M_DTLS_CID,
we should use that instead. Both set the same flag, so we don't
need a separate wrapper in nRF Connect SDK anymore.

2024-01-24 14:03 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13727/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13727/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13727/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-24 14:18 UTC, juhaylinen approved these changes

2024-01-25 06:36 UTC, peknis requested changes

2024-01-25 06:36 UTC, peknis commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +* For LwM2M applications, replace all use of :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_DTLS_CID` with :kconfi:option:`CONFIG_LWM2M_DTLS_CID`.
```suggestion
* For LwM2M applications, replace the :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_DTLS_CID` Kconfig option with :kconfi:option:`CONFIG_LWM2M_DTLS_CID`.
```

2024-01-25 06:36 UTC, peknis commented on samples/cellular/lwm2m_client/sample_description.rst
> +* Security: Enabled with PSK, DTLS Connection Identifier and DTLS session caching
```suggestion
* Security: Enabled with PSK, DTLS Connection Identifier, and DTLS session caching
```

2024-01-25 13:09 UTC, peknis requested changes

2024-01-25 13:09 UTC, peknis commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
> +* For LwM2M applications, replace the :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_DTLS_CID` Kconfig option with :kconfi:option:`CONFIG_LWM2M_DTLS_CID`.
```suggestion
* For LwM2M applications, replace the :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_DTLS_CID` Kconfig option with :kconfig:option:`CONFIG_LWM2M_DTLS_CID`.
```

2024-01-25 14:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13727
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-25 14:05 UTC, rlubos approved these changes

2024-01-25 14:11 UTC, merged