doc: Doc fixes
nrfconnect/sdk-nrf pull request #13759
Opened 2024-01-26 08:24 UTC by umapraseeda

Doc fixes to the sample documentation

2024-01-26 08:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13759
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-07 11:32 UTC, divipillai approved these changes

2024-02-07 11:55 UTC, peknis requested changes

2024-02-07 11:55 UTC, peknis commented on samples/net/http_server/README.rst
> +The HTTP Server sample demonstrates how to host an HTTP server on a Nordic Semiconductor device that is connected to the internet through LTE or Wi-Fi®.
```suggestion
The HTTP Server sample demonstrates how to host an HTTP server on a Nordic Semiconductor device that is connected to the Internet through LTE or Wi-Fi®.
```

2024-02-07 12:14 UTC, peknis approved these changes

2024-02-07 19:58 UTC, balaji-nordic approved these changes

2024-02-08 06:57 UTC, simensrostad approved these changes

2024-02-08 08:14 UTC, merged