applications: nrf5340_audio: Add direction to zbus from bt_stream
nrfconnect/sdk-nrf pull request #13787
Opened 2024-01-29 15:46 UTC by alexsven

- Send direction from bt_stream to main.
- Differentiate between timestamp used for pres and drift compensation
- Change log in main files to prefix main
- Add helper function for getting stream direction
- Turn on just-in-time for bidirectional gateways

- OCT-2875

2024-01-29 15:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13787/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13787/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13787/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-30 13:33 UTC, koffes requested changes

2024-01-30 13:33 UTC, koffes commented on applications/nrf5340_audio/src/audio/sw_codec_select.h
> +	bool started;
I may see later why this started is required. 
It is often better with a state machine instead of two variables.

2024-01-30 13:33 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
> +int le_audio_stream_dir_get(struct bt_bap_stream *stream)
```suggestion
int le_audio_stream_dir_get(struct bt_bap_stream const * const stream)
```

2024-01-30 13:33 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
> +		LOG_WRN("Failed to get ep_info");
WRN or ERR?

2024-01-30 13:33 UTC, koffes commented on applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
> + * retval	Negative value		Failed to get ep_info from host.
```suggestion
 * @retval	Negative value		Failed to get ep_info from host.
```

2024-02-01 11:34 UTC, rick1082 approved these changes

2024-02-02 12:01 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
> +		LOG_WRN("Failed to get ep_info");
Discussed, will keep as WRN

2024-02-05 09:29 UTC, koffes approved these changes

2024-02-05 14:35 UTC, merged