manifest: sdk-nrfxlib: Pull Osal header cleanup
nrfconnect/sdk-nrf pull request #13794
Opened 2024-01-30 11:47 UTC by ajayparida

OSAL hdr cleanup changes to use internal hdrs [CAL-3923].

2024-01-30 11:48 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a9a80f315618c78a68c3f7d917de0db182ac121d | https://github.com/nrfconnect/sdk-nrfxlib/pull/1190 | [nrfconnect/sdk-nrfxlib#1190/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1190/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-01-30 11:49 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13794/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13794/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13794/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-30 12:28 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13794
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-01-31 07:09 UTC, krish2718 approved these changes

2024-01-31 11:44 UTC, sachinthegreen approved these changes

2024-01-31 12:00 UTC, NordicBuilder commented
The changes to the 'requirements-fixed.txt' have been added to this PR.
All further changes to any of the requirements file will automatically be applied as long an :eyes: is present.


*Note: This comment is automatically posted and updated by the Comment GitHub Action.*

2024-01-31 15:52 UTC, rlubos requested changes
Something must've gone wrong during rebase, the SHA updated was squashed into https://github.com/nrfconnect/sdk-nrf/commit/ac88ccab76c9756cae83d1d04ba51803aee69445 instead of being a separate commit.

2024-02-01 08:09 UTC, rlubos approved these changes

2024-02-01 08:53 UTC, merged