net: lwm2m_client_utils: Match tau with lifetime
nrfconnect/sdk-nrf pull request #13816
Opened 2024-01-31 13:56 UTC by juhaylinen

Try to match periodic TAU with client lifetime.
Log TAU period and active time when PSM parameters are updated.

Update lwm2m_client sample's RPTAU config to match configured lifetime.

2024-01-31 13:59 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13816/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13816/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13816/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-01 11:14 UTC, SeppoTakalo approved these changes
Looks OK.

I would still change the debug level.

2024-02-01 11:14 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_lte_notification.c
> +		LOG_INF("Active time %d seconds", psm_cfg.active_time);
```suggestion
		LOG_DBG("Tau period %d seconds", psm_cfg.tau);
		LOG_DBG("Active time %d seconds", psm_cfg.active_time);
```

2024-02-01 11:14 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_utils_con_management.c
> +		LOG_INF("Requesting new periodic TAU");
```suggestion
		LOG_DBG("Requesting new periodic TAU");
```

2024-02-01 11:14 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_utils_con_management.c
> +		LOG_INF("Using default lifetime: %u", lifetime);
```suggestion
		LOG_WRN("Using default lifetime: %u", lifetime);
```

I assume that this should not happen usually.

2024-02-01 11:15 UTC, SeppoTakalo commented
Btw. This changes the behaviour of the client, so it deserves a changelog entry.

2024-02-05 09:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13816
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-05 10:40 UTC, peknis requested changes

2024-02-05 10:40 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The eDRX cycle to 5.12s for both LTE-M and Nb-IOT.
```suggestion
    * The eDRX cycle to 5.12 s for both LTE-M and NB-IoT.
```

2024-02-05 10:40 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The Release Assistance Indication (RAI) support to follow socket state changes from LwM2M engine, and modify RAI values based on the state.
```suggestion
    * The Release Assistance Indication (RAI) support to follow socket state changes from LwM2M engine and modify RAI values based on the state.
```

2024-02-05 13:25 UTC, SeppoTakalo commented
@juhaylinen Please check CI failures.

2024-02-06 13:01 UTC, juhaylinen commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * The eDRX cycle to 5.12 s for both LTE-M and NB-IOT.
Oops. Now fixed

2024-02-07 08:10 UTC, merged