net: lib: download_client: Only forward full buffers to app
nrfconnect/sdk-nrf pull request #13814
Opened 2024-01-31 13:06 UTC by SeppoTakalo

When receiving data from HTTP stream, we might end up in a situation where we have received just few bytes more than an HTTP header.
Forwarding too little data to the callback may cause problems on libraries that try to detect the download type from the first bytes.
Prevent this by always trying to fetch full buffer, until we forward that to the callback.

2024-01-31 13:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13814/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13814/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13814/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-01-31 15:50 UTC, rlubos approved these changes

2024-02-01 08:32 UTC, SeppoTakalo commented
Testing Download-client example with these changed.

min/max field is minimum and maximum amount of payload offered to
`download_client_callback_t`

HTTP tests run against `speedtest.ftp.otenet.gr`.
HTTPS tests run against `s3.eu-central-1.amazonaws.com` which seem to be very agressive on disconnecting too slow clients.

### When downloading full buffers
|Protocol | min/max | speed | notes |
|---------|---------|-------|-------|
|HTTPS Ranged-GET | 2048/2048 | 4542 B/s | |
|HTTP Ranged-GET | 2048/2048 | 4120 B/s | |
|HTTP GET| 2048/2048 | 2737 B/s | |
|HTTPS GET| 2048/2048 | 1355 B/s | Error ECONRESET happened once |


### Without this chage
|Protocol | min/max | speed | notes |
|---------|---------|-------|-------|
|HTTPS Ranged-GET | 2048/2048 | 1305 B/s | Error ECONRESET happened two times |
|HTTP Ranged-GET | 2048/2048 | 3751 B/s | |
|HTTPS GET| 0/2048 | 342 B/s | Error ECONRESET happened 19 times |
|HTTP GET | 458/2048 | 1076 B/s | |



#### Typical errors
```
*** Booting nRF Connect SDK zephyr-v3.5.0-3022-gb3c97b010983 ***
Download client sample started
Provisioning certificate
Certificate match
Connecting to network
IP Up
Network connected
Downloading https://nrfconnectsdk.s3.eu-central-1.amazonaws.com/sample-img-100kb.png
[   7% ] |===                                               | (8192/102923 bytes) (min 0 max 2048)Error -104 during download
[   9% ] |====                                              | (10240/102923 bytes) (min 0 max 2048)Error -104 during download
[  17% ] |========                                          | (18432/102923 bytes) (min 0 max 2048)Error -104 during download
[  19% ] |=========                                         | (20480/102923 bytes) (min 0 max 2048)Error -104 during download
[  29% ] |==============                                    | (30720/102923 bytes) (min 0 max 2048)Error -104 during download
[  33% ] |================                                  | (34816/102923 bytes) (min 0 max 2048)Error -104 during download
[  39% ] |===================                               | (40960/102923 bytes) (min 0 max 2048)Error -104 during download
[  55% ] |===========================                       | (57344/102923 bytes) (min 0 max 2048)Error -104 during download
[  59% ] |=============================                     | (61440/102923 bytes) (min 0 max 2048)Error -104 during download
[  67% ] |=================================                 | (69632/102923 bytes) (min 0 max 2048)Error -104 during download
[  69% ] |==================================                | (71680/102923 bytes) (min 0 max 2048)Error -104 during download
[  75% ] |=====================================             | (77824/102923 bytes) (min 0 max 2048)Error -104 during download
[  77% ] |======================================            | (79872/102923 bytes) (min 0 max 2048)Error -104 during download
[  79% ] |=======================================           | (81920/102923 bytes) (min 0 max 2048)Error -104 during download
[  81% ] |========================================          | (83968/102923 bytes) (min 0 max 2048)Error -104 during download
[  85% ] |==========================================        | (88064/102923 bytes) (min 0 max 2048)Error -104 during download
[  93% ] |==============================================    | (96256/102923 bytes) (min 0 max 2048)Error -104 during download
[  95% ] |===============================================   | (98304/102923 bytes) (min 0 max 2048)Error -104 during download
[  99% ] |================================================= | (102400/102923 bytes) (min 0 max 2048)Error -104 during download
[ 100% ] |==================================================| (102923/102923 bytes) (min 0 max 2048)
Download completed in 300503 ms @ 342 bytes per sec, total 102923 bytes
IP down
Disconnected from network
Bye

```

## Conclusion

This has high impact on unranged GET queries.
Sometimes the callback seem to get 0 length of data, which definitely might break FOTA Download or other libraries.

2024-02-01 09:02 UTC, stig-bjorlykke approved these changes
No difference observed in carrier lib downloading large FOTA delta from AVsystem.

2024-02-01 09:31 UTC, sigvartmh approved these changes

2024-02-01 11:04 UTC, SeppoTakalo commented
Added a changelog.

2024-02-01 11:35 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13814
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-01 11:39 UTC, peknis requested changes

2024-02-01 11:39 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * HTTP downloads forward data fragments to callback only when buffer is full.
```suggestion
    * HTTP downloads forward data fragments to a callback only when the buffer is full.
```

2024-02-01 14:07 UTC, peknis approved these changes

2024-02-05 14:38 UTC, merged