Rename secure storage -> encrypted storage
nrfconnect/sdk-nrf pull request #13833
Opened 2024-02-01 13:29 UTC by mswarowsky

2024-02-01 13:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13833/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13833/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13833/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-01 13:37 UTC, SebastianBoe approved these changes

2024-02-01 13:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13833
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-01 14:35 UTC, vili-nordic approved these changes

2024-02-01 15:02 UTC, frkv requested changes
To be discussed offline

2024-02-13 15:18 UTC, vili-nordic commented
Replaced by
https://github.com/nrfconnect/sdk-nrf/pull/13998

2024-02-13 15:18 UTC, closed without merging