doc: wifi: remove "experimental" comment from Radio sample
nrfconnect/sdk-nrf pull request #13831
Opened 2024-02-01 12:19 UTC by richabp

Remove the "Experimental" comment from compute_optimal_xo_val description.

SHEL-2429

2024-02-01 12:21 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13831/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13831/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-01 12:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13831
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-01 14:07 UTC, mjd90 requested changes

2024-02-01 14:07 UTC, mjd90 commented on samples/wifi/radio_test/radio_test_subcommands.rst
> +     - Compute optimal XO value.
I think we can improve this as well by adding the word 'trim'
```suggestion
     - Compute optimal XO trim value.
```

2024-02-02 06:29 UTC, bama-nordic approved these changes

2024-02-02 11:06 UTC, sachinthegreen approved these changes

2024-02-02 11:22 UTC, mjd90 approved these changes
LGTM

2024-02-02 11:31 UTC, merged