nrf: doc: Update TX injection documentation
nrfconnect/sdk-nrf pull request #13855
Opened 2024-02-03 02:32 UTC by VivekUppunda

This documentation update handles the change in TX injection mode command becoming a network shell command from a Wi-Fi shell command

2024-02-03 02:33 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13855/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13855/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-03 03:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13855
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-05 07:33 UTC, sachinthegreen commented
Adding @krga2022 so that STQA is aware of the feature updates.

2024-02-05 12:23 UTC, sachinthegreen requested changes

2024-02-05 14:43 UTC, sachinthegreen reviewed
I think an entry for `TX injection` would be needed in https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/software_maturity.html#wi-fi-feature-support

2024-02-06 08:37 UTC, kittydepa requested changes

2024-02-06 08:37 UTC, kittydepa commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +The ``net_eth_txinjection_mode`` functional API can be used to enable or disable TX injection mode in the nRF Wi-Fi driver as required by the application.
```suggestion
Use the``net_eth_txinjection_mode`` functional API to enable or disable TX injection mode.
```

2024-02-06 08:37 UTC, kittydepa commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +The ``NET_REQUEST_ETHERNET_SET_TXINJECTION_MODE`` network management API can also be used to enable or disable TX injection mode.
Lines 34 - 35 can be combined to:
```suggestion
You can also use the ``NET_REQUEST_ETHERNET_SET_TXINJECTION_MODE`` network management API to enable or disable TX injection mode, however it is recommended to use the functional API (``net_eth_txinjection_mode``).
```

2024-02-06 08:37 UTC, kittydepa commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +This channel will be used as the default transmit channel when the nRF70 Series device operates in a non-connected Station mode.
Suggestions here are fine, except keep the original ``operates``, as NCS docs lean towards an "active voice".

2024-02-06 08:37 UTC, kittydepa commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When the nRF70 Series device operates in Station mode connected to an AP on a given channel, the same channel will be used for raw 802.11 packet transmission.
Same comment as above, all suggestions fine but please keep ``operates``, unless this significantly changes the meaning and is required. Please ensure throughout. When possible "active voice" is preferred in NCS docs.

2024-02-06 09:47 UTC, VivekUppunda commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
The UMAC team has not enabled this feature for SoftAP as far as i am aware of

2024-02-06 11:30 UTC, sachinthegreen commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
@rajb9 / @karun2796 : Can you please look into this? As far as I understand `TX injection` is expected to work in all modes.

2024-02-06 11:48 UTC, karun2796 commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
The UMAC implementation does not restrict the Tx injection mode setting & sending Raw TX packet via any conditional checks (if_type). Thorough testing is still necessary to confirm correct operation.

2024-02-06 12:02 UTC, VivekUppunda commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
So what does that mean @karun2796 ? Are you stating that UMAC has necessary checks for working in SoftAP mode ? As i understand with discussions with you, UMAC has various checks for different modes of operation and how TX injection works in those modes. SoftAP checks and interface code checks are implemented today?

2024-02-06 12:06 UTC, ioannisg approved these changes
Looks good to me

2024-02-06 12:06 UTC, ioannisg commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When nRF70 Series Device is configured to Station Mode, TX injection mode can be enabled both when it is operating in a connected Station mode or in a non-connected Station mode (not connected to an
Slightly modifying above suggestion:

```suggestion
When the nRF70 Series device is configured in Station mode, TX injection mode can be enabled both when the device is either connected to an Access Point (AP) or not connected to one.```

2024-02-06 12:11 UTC, ioannisg commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
Reading through this discussion, some points
- if Raw packet TX mode can safely work together with SoftAP, we probably need to demonstrate this in the same, along with adding this in the docs. This guide is primarily meant to show and explain what the stack has been validated to do, so it should be aligned with the sample where we show raw tx support :)
- Raw packet TX and SoftAP is probably not the most popular combination, so, if it helps, it is perfectly OK if the ambiguity around whether this combination of modes is resolved at post-merge (of this PR)

2024-02-06 13:13 UTC, karun2796 commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +TX injection mode can be enabled when the nRF70 Series device primary mode of operation is set to Station mode or Monitor mode.
@VivekUppunda , yes previously we have some necessary checks and those checks got removed in last PR so i hope it should work fine with SoftAP too. But as i mentioned it need to be tested.

2024-02-07 00:54 UTC, VivekUppunda commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When the nRF70 series device operates in Monitor mode, the configured channel for Monitor mode will be used as the transmit channel for TX injection operation.
Keeping the sentence as is as per previous comments for active case usage

2024-02-07 08:58 UTC, sachinthegreen approved these changes

2024-02-08 11:29 UTC, richabp requested changes

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When the nRF70 Series device is configured in Station mode, TX injection mode can be enabled both when the device is either connected to an Access Point (AP) or not connected to one.
Please check that this suggestion still maintained the information you intended.
```suggestion
When the nRF70 Series device is configured in Station mode, TX injection mode can be enabled regardless of whether the device is connected to an Access Point (AP) or not.
```

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When the nRF70 Series device operates in Station mode and connected to an AP on a given channel, the connected channel will be used for raw 802.11 packet transmission.
```suggestion
This channel will be used as the transmit channel when the nRF70 Series device operates in Station mode, but is not connected to an AP.
When the nRF70 Series device operates in Station mode and is connected to an AP on a given channel, the connected channel will be used for raw 802.11 packet transmission.
```

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +When the nRF70 series device operates in Monitor mode, the configured channel for Monitor mode will be used as the transmit channel for TX injection operation.
```suggestion
When the nRF70 Series device operates in Monitor mode, the configured channel for Monitor mode will be used as the transmit channel for TX injection operation.
```

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +The following table provides the parameter details for ``net_eth_txinjection_mode`` API which is used to enable/disable TX injection mode for raw packet transmission.
```suggestion
The following table provides the parameter details for the ``net_eth_txinjection_mode`` API, which is used to enable or disable TX injection mode for raw packet transmission.
```

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +     - Boolean value to enable or disable TX injection mode.
```suggestion
     - Boolean value to enable or disable TX injection mode
```

2024-02-08 11:29 UTC, richabp commented on doc/nrf/protocols/wifi/raw_tx_operation.rst
> +The following table provides network management API to set channel of operation for raw packet transmission.
```suggestion
The following table provides the network management API used to set the channel of operation for raw packet transmission.
```

2024-02-09 01:15 UTC, VivekUppunda commented
> I think an entry for `TX injection` would be needed in https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/software_maturity.html#wi-fi-feature-support

As per discussion - adding BOARD_NRF7002DK_NRF5340_CPUAPP to software_maturity_features.yaml.
Thanks 
Vivek

2024-02-09 07:21 UTC, kittydepa approved these changes

2024-02-09 08:28 UTC, richabp approved these changes

2024-02-09 09:31 UTC, merged