Bluetooth: Controller: Define BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT and disable it for 802.15.4
nrfconnect/sdk-nrf pull request #13872
Opened 2024-02-05 15:23 UTC by rugeGerritsen

Define CONFIG_BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT to allow
users to enable and disable connection event extension in a simpler
way.

We do not want to enable connection event extension when
802.15.4 protocols are enabled as we would like to reserve as much time
as possible for those protocols.

Disabling the setting has no practical consequence when connected
to a single Bluetooth device, but it improves performance
significantly when connected to two or more Bluetooth devices.

Ref: DRGN-21305

2024-02-05 15:24 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13872/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13872/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13872/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-05 15:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13872
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-06 13:29 UTC, Tschet1 requested changes

2024-02-06 13:29 UTC, Tschet1 commented on subsys/bluetooth/controller/Kconfig
> +	  When BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT is set, more time may be used.
sdc_hci_cmd_vs_conn_event_extend may be called by the application, as well.
I think it is not only about the BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT, but the question is if connecion event extension is enabled.

2024-02-06 13:29 UTC, Tschet1 commented on subsys/bluetooth/controller/Kconfig
> +	  - There are no conflicts with other concurrent links.
```suggestion
	  - There are no conflicts with other roles of equal or higher priority.
```

2024-02-06 14:56 UTC, Tschet1 approved these changes

2024-02-07 12:21 UTC, henrla approved these changes

2024-02-07 12:57 UTC, merged