bluetooth: controller: add support for HCIVSBigReservedTimeSet
nrfconnect/sdk-nrf pull request #13881
Opened 2024-02-06 10:45 UTC by adamfc2000

Add support for a VS HCI command to adjust the reserved time in a BIG.

2024-02-06 10:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13881/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13881/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13881/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-06 11:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13881
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-16 09:13 UTC, sean-madigan requested changes

2024-02-16 09:13 UTC, sean-madigan commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Added support for HCIVSBigReservedTimeSet command and corresponding Kconfig option BT_CTLR_BIG_RESERVED_TIME_US.
Don't think this is the correct place for this

2024-02-16 09:13 UTC, sean-madigan commented on subsys/bluetooth/controller/Kconfig
> +		The default time reserved at the end of a BIG event for periodic advertising
Formatting seems to be off

2024-02-16 09:13 UTC, sean-madigan commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Added support for HCIVSBigReservedTimeSet command and corresponding Kconfig option BT_CTLR_BIG_RESERVED_TIME_US.
I think we'll have to merge it to internal repo changelog

2024-02-16 09:20 UTC, sean-madigan commented on subsys/bluetooth/controller/Kconfig
> +config BT_CTLR_BIG_RESERVED_TIME_US
```suggestion
config BT_CTLR_SDC_BIG_RESERVED_TIME_US
```

2024-02-19 14:48 UTC, sean-madigan commented on subsys/bluetooth/controller/Kconfig
> +	  The default time reserved at the end of a BIG event for periodic advertising
Maybe update wording to match Rubin's suggestions in bitbucket PR

2024-02-19 16:03 UTC, sean-madigan approved these changes

2024-02-21 09:21 UTC, sean-madigan commented on subsys/bluetooth/controller/Kconfig
> +	default 2500
Maybe it makes sense to default this to the periodic adv event length?

2024-02-22 14:44 UTC, rugeGerritsen approved these changes

2024-02-23 11:19 UTC, merged