Bluetooth: set configuration for HCI ISO data timestamps
nrfconnect/sdk-nrf pull request #13926
Opened 2024-02-08 13:48 UTC by Tschet1

If the host uses timestamps for HCI ISO data packets which are not based on the controller's clock, the controller needs to be configured accordingly.

Added a KConfig which exposes this possibility.

2024-02-08 13:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13926/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13926/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13926/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-08 13:53 UTC, rugeGerritsen requested changes

2024-02-08 13:53 UTC, rugeGerritsen commented on subsys/bluetooth/controller/Kconfig
> +	default 0
`default n` shall be omitted according to the Kconfig style guidelines: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/build/kconfig/tips.html#redundant-defaults

2024-02-08 14:33 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13926
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-08 14:35 UTC, rugeGerritsen requested changes

2024-02-08 14:35 UTC, rugeGerritsen commented on subsys/bluetooth/controller/Kconfig
> +	bool
Should probably have a prompt: 
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/build/kconfig/tips.html#what-to-turn-into-kconfig-options

2024-02-09 09:21 UTC, ivaniushkov approved these changes

2024-02-09 11:48 UTC, merged