doc: updated 54h documentation
nrfconnect/sdk-nrf pull request #13937
Opened 2024-02-09 10:20 UTC by FrancescoSer

Updated 54h documentation.

2024-02-12 15:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13937
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-12 17:49 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13937/13/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13937/13/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-16 14:20 UTC, FrancescoSer commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_matter_thread.rst
> +* nrfjprog from the nRF CLI tools.
CLI tools need link

2024-02-16 14:28 UTC, greg-fer approved these changes
Step in the right direction. I'll have a closer look at PRs where :orphan: tags are being gradually removed.

2024-02-19 09:51 UTC, wiba-nordic requested changes

2024-02-19 09:51 UTC, wiba-nordic commented on doc/nrf/glossary.rst
> +      Subsets of domains.
```suggestion
      Subsets of :term:`domains <Domain>`.
```

2024-02-19 13:51 UTC, FrancescoSer commented on doc/nrf/glossary.rst
> +      A peripheral that can communicate with multiple slaves using individual chip select signals for each of the slave devices attached to a bus.
I wondered about the same @hubertmis Is slave really the correct term here?

2024-02-19 14:09 UTC, FrancescoSer commented on doc/nrf/glossary.rst
> +      A peripheral that can communicate with multiple slaves using individual chip select signals for each of the slave devices attached to a bus.
Ok, thank you!

2024-02-20 06:40 UTC, wiba-nordic approved these changes

2024-02-20 06:44 UTC, wiba-nordic commented on doc/nrf/glossary.rst
> +      A :term:`VPR core` that implements system startup and power management functionalities that in the past would have been implemented in hardware.
```suggestion
      A :term:`VPR core<VPR Core (pronounced “Viper”)>` that implements system startup and power management functionalities that in the past would have been implemented in hardware.
```
My mistake on this one, got the link wrong.

2024-02-21 10:46 UTC, wiba-nordic approved these changes

2024-02-21 10:51 UTC, merged

2024-02-27 13:52 UTC, gmarull commented
@FrancescoSer please, do not blindly merge content from -next to the upstream repo. For example, all `@soc1` references do not exist here.

2024-02-27 14:10 UTC, FrancescoSer commented
@gmarull, please check with with @shanthanordic that docs would go in as-is and would undergo revisions towards their final form before the the next devtag. If you want additional details, feel free to contact me on teams.

2024-02-27 14:16 UTC, gmarull commented
> @gmarull, this was not a blind merge. As agreed with @shanthanordic weeks ago, docs would go in as-is and would undergo revisions towards their final form before the the next devtag. As you can notice, the pages are currently all orphaned. Moreover, they have already diverged from their version on nrf-next. If you want additional details, feel free to contact me on teams.

Just noting as this has caused failures to other PRs, so we should not copy content as is.

2024-02-27 14:36 UTC, FrancescoSer commented
@gmarull The content was reviewed. Could you please be more specific? If you are referring to the sample board rows, there was no entry previously present for anything related to 54H in there.

2024-02-27 14:48 UTC, gmarull commented
> If you are referring to the sample board rows, 

yes, upstream boards have names aligned with what's printed on the board

2024-02-27 15:53 UTC, FrancescoSer commented
Until the upstream meeting on Friday, SOC1 was expected to be supported in version 2.6. Anyway, I'm glad this issue was identified.