scripts: upgrade cmake version to 3.21.0
nrfconnect/sdk-nrf pull request #13952
Opened 2024-02-12 08:53 UTC by Mirlenko

Currently used 3.20.6 cmake version does not allow for applying cmake policies necessary for armclang compiler

2024-02-12 08:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13952/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13952/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13952/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-12 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=13952) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=13952) before we can accept your contribution.<br/><hr/>**Mirlenko, Aleksandr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=13952) it.</sub>

2024-02-12 09:58 UTC, thst-nordic requested changes

2024-02-12 09:58 UTC, thst-nordic commented on scripts/tools-versions-linux.yml
> -  version: 3.20.6
can you change `tools-versions-darwin.yml` also? 
https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/tools-versions-darwin.yml#L6

2024-02-12 10:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13952
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-13 07:53 UTC, thst-nordic approved these changes

2024-02-13 07:55 UTC, thst-nordic commented
LGTM

2024-02-13 08:33 UTC, jangalda-nsc approved these changes

2024-02-13 10:03 UTC, merged