caf: modules: ble_adv: Power down on disconnection with reason 0x15
nrfconnect/sdk-nrf pull request #13987
Opened 2024-02-13 11:31 UTC by MarekPieta

Force power down if bonded peer disconnects with reason 0x15 (Remote Device Terminated due to Power Off).

PR also adds broadcasting reason to ble_peer_event and integrates the new feature to nRF Desktop application.

Jira: NCSDK-24458

2024-02-13 11:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13987/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13987/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-13987/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-13 12:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-13987
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-13 16:01 UTC, zycz approved these changes

2024-02-14 10:34 UTC, mkapala-nordic approved these changes

2024-02-14 10:48 UTC, peknis requested changes

2024-02-14 10:48 UTC, peknis commented on doc/nrf/libraries/caf/ble_adv.rst
> +The :kconfig:option:`CONFIG_CAF_BLE_ADV_POWER_DOWN_ON_DISCONNECTION_REASON_0X15` Kconfig option can be used to force power down when a bonded peer disconnects with reason ``0x15`` (Remote Device Term
```suggestion
You can use the :kconfig:option:`CONFIG_CAF_BLE_ADV_POWER_DOWN_ON_DISCONNECTION_REASON_0X15` Kconfig option to force power down when a bonded peer disconnects with reason ``0x15`` (Remote Device Terminated due to Power Off).
```

2024-02-14 10:48 UTC, peknis commented on doc/nrf/libraries/caf/ble_adv.rst
> +The feature can be used to prevent waking up bonded peer until activity on peripheral's end is detected.
```suggestion
You can use this feature to prevent waking up bonded peer until activity on the peripheral is detected.
```

2024-02-14 10:48 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* :c:struct:`ble_peer_event`:
We do not usually refer to the structures on this level of the changelog. Is this related to a specific CAF module?

2024-02-14 10:48 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added :kconfig:option:`CONFIG_CAF_BLE_ADV_POWER_DOWN_ON_DISCONNECTION_REASON_0X15` Kconfig option.
```suggestion
  * Added the :kconfig:option:`CONFIG_CAF_BLE_ADV_POWER_DOWN_ON_DISCONNECTION_REASON_0X15` Kconfig option.
```

2024-02-14 10:48 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    The option can be used to force system power down when a bonded peer disconnects with reason ``0x15`` (Remote Device Terminated due to Power Off).
```suggestion
    You can use this option to force system power down when a bonded peer disconnects with reason ``0x15`` (Remote Device Terminated due to Power Off).
```

2024-02-14 11:42 UTC, divipillai commented on subsys/caf/modules/Kconfig.ble_adv
> +	  stops Bluetooth LE advertising and submits force_power_down event.
```suggestion
	  stops Bluetooth LE advertising and submits a force_power_down event.
```

2024-02-14 11:42 UTC, divipillai commented on doc/nrf/libraries/caf/ble_adv.rst
> +The module instantly stops Bluetooth LE advertising and submits :c:struct:`force_power_down_event` on :c:struct:`ble_peer_event` with :c:member:`ble_peer_event.reason` of ``0x15`` and :c:member:`ble_
```suggestion
The module instantly stops Bluetooth LE advertising and performs the following:

 *  Force power down using :c:struct:`force_power_down_event` on Bluetooth LE peer event (:c:struct:`ble_peer_event`) with reason ``0x15`` (:c:member:`ble_peer_event.reason`).
 * Disconnects (:c:enum:`PEER_STATE_DISCONNECTED`)  the Bluetooth stack from the remote peer (:c:member:`ble_peer_event.state`).
 
```
Hope my understanding is correct. Wanted this sentence to be a bit more descriptive (what the system does after the Bluetooth LE advertising stops).

2024-02-19 14:30 UTC, divipillai approved these changes

2024-02-20 06:30 UTC, peknis approved these changes

2024-02-20 08:13 UTC, mkapala-nordic approved these changes

2024-02-20 10:03 UTC, merged