doc: add known issue for ISO HCI command.
nrfconnect/sdk-nrf pull request #14020
Opened 2024-02-15 09:01 UTC by henrla

Document known issue for LE Read ISO TX Sync.

2024-02-15 09:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14020/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14020/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-15 09:23 UTC, wiba-nordic requested changes

2024-02-15 09:23 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +.. rst-class:: v2.6.0
```suggestion
.. rst-class:: v2-6-0
```

2024-02-15 09:23 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +DRGN-21293: Le Read ISO TX Sync is implemented according to the raised errata ES-23138.
```suggestion
DRGN-21293: The LE Read ISO TX Sync command is implemented according to the raised errata ES-23138. 
```

2024-02-15 09:23 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  Note that there is no difference between the CIG or BIG reference anchor point and the SDU synchronization reference when the CIG or BIG is configured with an ISO_Interval that equals the SDU_Inter
```suggestion
  Note that when the CIG or BIG is configured with an ``ISO_Interval`` that equals the ``SDU_Interval``, there is no difference between the CIG or BIG reference anchor point and the SDU synchronization reference .
```
Alternatively, these could be just ISO interval and SDU interval, and not be parameters at all.

2024-02-15 09:23 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  If several SDUs are transmitted per ISO_Interval, meaning that the ISO_Interval is larger than the SDU_Interval, our implementation of LE Read ISO TX Sync returns a unique SDU synchronization refer
```suggestion
  If several SDUs are transmitted during each ``ISO_Interval``, meaning that the ``ISO_Interval`` is larger than the ``SDU_Interval``, our implementation of the LE Read ISO TX Sync command returns a unique SDU synchronization reference for each SDU.
```

2024-02-15 09:23 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  In ES-23138, the return parameter TX_Time_Stamp is modified to be the SDU synchronization reference of the SDU previously scheduled for transmission, and not the CIG or BIG reference anchor point.
```suggestion
  In ES-23138, the return parameter ``TX_Time_Stamp`` is used as the SDU synchronization reference of the SDU previously scheduled for transmission.
  This differs from the Bluetooth Core Specification v5.4, which uses the CIG or BIG reference anchor point as the SDU synchronization reference.
```

2024-02-15 09:31 UTC, wiba-nordic approved these changes

2024-02-15 10:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14020
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-15 12:30 UTC, Tschet1 approved these changes

2024-02-26 09:28 UTC, peknis commented
Added this known issue to https://github.com/nrfconnect/sdk-nrf/pull/14185. Please close this PR.

2024-02-26 09:34 UTC, closed without merging