applications: nrf5340_audio: Extended codec cfg max metadata size
nrfconnect/sdk-nrf pull request #14022
Opened 2024-02-15 09:42 UTC by rick1082

Enlarge codec cfg max metadata size to prevent compatibility issue. 
OCT-NONE
Signed-off-by: Jui-Chou Chung <jui-chou.chung@nordicsemi.no>

2024-02-15 09:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14022/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14022/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14022/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-16 09:12 UTC, alexsven commented
We should increase this for all applications, so may want to set it in the Kconfig for bt_stream (have to be created)

2024-02-16 09:22 UTC, alexsven requested changes
We should increase this for all applications, so may want to set it in the Kconfig for bt_stream (have to be created)

2024-02-16 09:59 UTC, rick1082 commented
> We should increase this for all applications, so may want to set it in the Kconfig for bt_stream (have to be created)
This part is dedicated for broadcast sink.
The needed of metadata size would be different between BIS and CIS I think.
Since there's no handshaking between broadcast sink and source, so the broadcast source has to expose all the information from different level to metadata at once. So we have to set BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE bigger for broadcast sink, otherwise we cannot decode it properly.

For CIS, setting BT_AUDIO_CODEC_CFG_MAX_METADATA_SIZE to a higher number will also need to change CONFIG_BT_ATT_PREPARE_COUNT, which is the buffer for long write.

2024-02-16 10:37 UTC, alexsven approved these changes

2024-02-16 11:20 UTC, merged