doc: nrf: Update Monitor mode documentation
nrfconnect/sdk-nrf pull request #14038
Opened 2024-02-16 01:50 UTC by VivekUppunda

Update Monitor mode documentation for filter settings and minor corrections in documentation.

2024-02-16 01:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14038/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14038/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-16 02:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14038
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-16 06:26 UTC, krish2718 approved these changes

2024-02-16 06:26 UTC, krish2718 commented on doc/nrf/protocols/wifi/sniffer_rx_operation.rst
> +The type of IEEE 802.11 receive packets that the application receives can be configured using the filter ``NET_REQUEST_WIFI_PACKET_FILTER`` net management command.
```suggestion
The type of IEEE 802.11 packets that the application receives can be configured using the filter ``NET_REQUEST_WIFI_PACKET_FILTER`` Wi-Fi management command.
```

2024-02-16 08:38 UTC, richabp requested changes

2024-02-16 08:38 UTC, richabp commented on doc/nrf/protocols/wifi/sniffer_rx_operation.rst
> +The nRF70 Series Wi-Fi driver has to be configured to operate in Monitor mode or Promiscuous mode for setting packet filter settings.
```suggestion
The nRF70 Series Wi-Fi driver must be configured to operate in Monitor mode or Promiscuous mode for setting packet filter settings.
```

2024-02-16 08:38 UTC, richabp commented on doc/nrf/protocols/wifi/sniffer_rx_operation.rst
> +The application can choose to receive 802.11 management packets, 802.11 control packets, 802.11 data packets or a combination of the three types of 802.11 packets.
```suggestion
The application can choose to receive 802.11 management packets, 802.11 control packets, 802.11 data packets, or a combination of the three types of 802.11 packets.
```

2024-02-16 09:03 UTC, ioannisg approved these changes
looks good to me

2024-02-16 12:01 UTC, sachinthegreen approved these changes

2024-02-19 08:17 UTC, kittydepa approved these changes

2024-02-19 08:19 UTC, richabp approved these changes

2024-02-19 16:21 UTC, merged