bluetooth: controller: Kconfig: claim ISO production support
nrfconnect/sdk-nrf pull request #14030
Opened 2024-02-15 13:57 UTC by yuxCai

Isochronous channels has production support now.

Rename BT_LL_SOFTDEVICE_EXPERIMENTAL_ISO to BT_LL_SOFTDEVICE_ISO, and remove experimental wordings.

2024-02-15 14:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14030
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-19 07:07 UTC, rugeGerritsen requested changes
This kconfig entry can simply be removed as it is not used for anything else than printing that the feature is experimental

2024-02-20 11:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14030/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14030/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14030/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-20 12:00 UTC, rugeGerritsen approved these changes

2024-02-20 12:21 UTC, ivaniushkov approved these changes

2024-02-20 12:43 UTC, yuxCai commented
Rebased to the latest main to pass the compliance check

2024-02-20 17:02 UTC, merged