Add support for 4096-bit RSA keys with TF-M
nrfconnect/sdk-nrf pull request #14043
Opened 2024-02-16 09:18 UTC by vili-nordic

2024-02-16 09:19 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14043/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14043/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-fw-update | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14043/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-16 10:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14043
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-16 11:22 UTC, mswarowsky approved these changes
One small nit, but rest lgtm

2024-02-16 11:22 UTC, mswarowsky commented on samples/crypto/rsa/src/key.h
> + * Copyright (c) 2021 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2024 Nordic Semiconductor ASA
```

2024-02-16 13:49 UTC, frkv commented on samples/crypto/rsa/README.rst
> +   #. A RSA key pair is imported into the PSA crypto keystore.
It is unfortunate that we have to rely on a pre-generated key, but I think it should be mentioned that this key is not usable in any end-products. Maybe this text should be given in italics

```suggestion
   #. A RSA key pair is imported into the PSA crypto keystore.
   #. *Note that this is a test key and it should never be used in a product!*
```

2024-02-16 14:01 UTC, SebastianBoe reviewed
The title might mislead a customer into thinking using 4096 bit keys was not supported with TF-M previously.

The customer could have 4096 bit keys in his TF-M application by doing

CONFIG_TFM_CRYPTO_PARTITION_STACK_SIZE=0x4000

maybe:

Increase the default TF-M crypto partition stack size when 4096 bit RSA keys are enabled

2024-02-16 15:16 UTC, SebastianBoe approved these changes

2024-02-20 08:41 UTC, mia-ko requested changes

2024-02-20 08:41 UTC, mia-ko commented on samples/crypto/rsa/README.rst
> +   #. A RSA key pair is imported into the PSA crypto keystore.
```suggestion
   #. An RSA key pair is imported into the PSA crypto keystore.
```

2024-02-20 08:41 UTC, mia-ko commented on samples/crypto/rsa/README.rst
> +   *Note that the keys used in the sample are for demonstration purposes only and never be used in a product.*
```suggestion
   #. The public key is imported into the PSA crypto keystore.

      .. note::
         The keys used in the sample are for demonstration purposes only and must never be used in a product.
         ```

2024-02-20 09:25 UTC, mia-ko commented on samples/crypto/rsa/README.rst
> +         ```
These sneaked in, you probably want to remove them :)

2024-02-20 09:49 UTC, mia-ko reviewed
Do these changes require a changelog update?

2024-02-20 10:03 UTC, vili-nordic commented
I don't think updating the default stack-size for tf-m require changelog entry. The sample is showing something slightly different now (but probably a more "common" case), but I'm not sure how relevant that is for a changelog.

2024-02-20 13:21 UTC, merged