doc: lwm2m_client: Update documentation
nrfconnect/sdk-nrf pull request #14052
Opened 2024-02-16 12:13 UTC by juhaylinen

Add link to Zephyr LwM2M sample which is demonstrates basic LwM2M functionality.
Update some configuration values.

2024-02-16 12:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14052/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14052/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-16 13:02 UTC, SeppoTakalo approved these changes

2024-02-16 13:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14052
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-19 07:19 UTC, peknis requested changes

2024-02-19 07:19 UTC, peknis commented on samples/cellular/lwm2m_client/README.rst
> +This sample uses the :ref:`lib_lwm2m_client_utils` library and the :ref:`lib_lwm2m_location_assistance` library.
```suggestion
This sample uses the :ref:`lib_lwm2m_client_utils` and :ref:`lib_lwm2m_location_assistance` libraries.
```

2024-02-19 07:19 UTC, peknis commented on samples/cellular/lwm2m_client/README.rst
> +The sample has implementation for many cellular specific features such as location services, firmware update and power saving optimizations. For network agnostic and basic LwM2M client sample see: :z
```suggestion
The sample has implementation for many cellular-specific features, such as location services, firmware update, and power saving optimizations. For a network-agnostic and basic LwM2M client sample, see :zephyr:code-sample:`lwm2m-client`.
```

2024-02-19 08:55 UTC, peknis approved these changes

2024-02-19 10:18 UTC, peknis approved these changes
One more minor nit before you ask for merge.

2024-02-19 10:18 UTC, peknis commented on samples/cellular/lwm2m_client/README.rst
> +The sample has implementation for many cellular-specific features, such as location services, firmware update, and power saving optimizations. For a network-agnostic and basic LwM2M client sample, se
```suggestion
The sample has implementation for many cellular-specific features, such as location services, firmware update, and power saving optimizations.
For a network-agnostic and basic LwM2M client sample, see :zephyr:code-sample:`lwm2m-client`.
```

2024-02-19 12:07 UTC, merged