manifest: Update zephyr revision
nrfconnect/sdk-nrf pull request #14061
Opened 2024-02-16 15:34 UTC by anangl

Pull in a couple of fixes in drivers and implementation of workaround for nRF5340 anomaly 168.

2024-02-16 15:34 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/962eb7320fdb76ffe265d8bab7330ad472cb6f28 | https://github.com/nrfconnect/sdk-zephyr/pull/1508 | [nrfconnect/sdk-zephyr#1508/files](https://github.com/nrfconnect/sdk-zephyr/pull/1508/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-16 15:35 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14061/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14061/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14061/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-16 16:00 UTC, gmarull approved these changes

2024-02-16 16:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14061
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-19 08:06 UTC, SeppoTakalo approved these changes

2024-02-19 13:18 UTC, jfischer-no requested changes
Manifest is updated in #14006

2024-02-20 10:45 UTC, jfischer-no commented
#14006 is merged.

2024-02-20 10:45 UTC, closed without merging