doc: nrf_security: Add disclaimer about thread safety
nrfconnect/sdk-nrf pull request #14088
Opened 2024-02-20 11:03 UTC by SebastianBoe

Add disclaimer about thread safety.

2024-02-20 11:32 UTC, vili-nordic approved these changes

2024-02-21 07:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14088/2/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14088/2/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-21 07:38 UTC, frkv approved these changes
LGTM

2024-02-21 07:53 UTC, mia-ko requested changes

2024-02-21 07:53 UTC, mia-ko commented on doc/nrf/libraries/nrf_security/doc/configuration.rst
> +The PSA Crypto APIs are only thread safe when provided by TF-M.
```suggestion
.. caution::
   The PSA Crypto APIs are only thread safe when provided by TF-M.
```

2024-02-21 08:18 UTC, mia-ko approved these changes

2024-02-21 08:19 UTC, mia-ko commented on doc/nrf/libraries/nrf_security/doc/configuration.rst
> +   The PSA Crypto APIs are only thread safe when provided by TF-M.
Although, the more I think about it, it should probably be thread-safe instead.

2024-02-21 08:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14088
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-21 08:48 UTC, merged