Applications: nrf5340_audio: Ctlr poll in separate work q
nrfconnect/sdk-nrf pull request #14106
Opened 2024-02-21 08:57 UTC by koffes

OCT-2917
Now performing hci_sync call in separate work q
to avoid blocking system work q

2024-02-21 09:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14106
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-21 13:04 UTC, alexsven requested changes

2024-02-21 13:04 UTC, alexsven commented on applications/nrf5340_audio/src/audio/Kconfig
> +
This should be in src/bluetooth/bt_management/Kconfig

2024-02-21 13:04 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_management/controller_config/bt_mgmt_ctlr_cfg.c
> +#define CTLR_POLL_WORK_STACK_SIZE 1024
Does it need to be this size? Seems a bit big given that it's doing very little

2024-02-21 13:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14106/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14106/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14106/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-21 13:37 UTC, alexsven approved these changes

2024-02-22 03:44 UTC, rick1082 approved these changes

2024-02-22 11:58 UTC, merged