Update failure stats for raw tx failure
nrfconnect/sdk-nrf pull request #14150
Opened 2024-02-22 23:56 UTC by VivekUppunda

This set of changes pulls in raw tx failure count updation when tx done from firmware indicates failure

2024-02-22 23:57 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a03f55e86da15b5bfc0550d5e5025f72c1654963 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1224 | [nrfconnect/sdk-nrfxlib#1224/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1224/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-22 23:58 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14150/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14150/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14150/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-23 00:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14150
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-23 02:47 UTC, rado17 approved these changes

2024-02-23 04:04 UTC, kapbh approved these changes

2024-02-23 07:00 UTC, krish2718 approved these changes

2024-02-23 07:58 UTC, sachinthegreen requested changes
- Please add a Jira reference in the commit log
- Please update the documentation of `TX injection` on how to use this

2024-02-23 08:05 UTC, VivekUppunda commented on drivers/wifi/nrf700x/src/net_if.c
> +	def_dev_ctx = wifi_dev_priv(rpu_ctx_zep->rpu_ctx);
No...def_dev_ctx will not be NULL at this stage. It is a private porttion for fmac_dev_ctx. This is populated at the start of driver.

2024-02-23 08:20 UTC, VivekUppunda commented
> * Please add a Jira reference in the commit log
> * Please update the documentation of `TX injection` on how to use this

I have updated the JIRA reference in the commit log. I will provide the documentation changes separately as it might take time in review. Please kindly ack

2024-02-23 08:23 UTC, sachinthegreen approved these changes

2024-02-23 09:27 UTC, merged