doc: update documentation with sync. printk limitations in Matter.
nrfconnect/sdk-nrf pull request #14171
Opened 2024-02-23 14:16 UTC by markaj-nordic

* update known issues for Matter
* update changelog with the patch that disabled CONFIG_PRINTK_SYNC in Matter fork

2024-02-23 14:20 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14171/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14171/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-23 14:21 UTC, LuDuda approved these changes

2024-02-23 14:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14171
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-23 15:14 UTC, wiba-nordic requested changes

2024-02-23 15:14 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-18316: When the :kconfig:option:`CONFIG_PRINTK_SYNC` option is enabled in Matter over Thread application, the IEEE 802.15.4 radio driver may calculate invalid IEEE 802.15.4 radio frame timesta
```suggestion
KRKNWK-18316: When the :kconfig:option:`CONFIG_PRINTK_SYNC` Kconfig option is enabled in a Matter over Thread application, the IEEE 802.15.4 radio driver may calculate invalid IEEE 802.15.4 radio frame timestamps
```

2024-02-23 15:14 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  This is caused because the implementation of synchronous ``printk`` in Zephyr uses ``spinlock`` synchronization primitive which can block Real Time Clock interrupts that are needed by radio driver
```suggestion
  This is caused by the implementation of synchronous ``printk`` in Zephyr using ``spinlock`` synchronization primitive, which can block Real Time Clock interrupts that are needed by the radio driver to calculate precise timestamps.
```

2024-02-23 15:14 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** If enabled, disable :kconfig:option:`CONFIG_PRINTK_SYNC` in your application.
```suggestion
  **Workaround:** If it is enabled, disable the :kconfig:option:`CONFIG_PRINTK_SYNC` Kconfig option in your application.
```

2024-02-26 05:49 UTC, wiba-nordic approved these changes

2024-02-26 08:47 UTC, merged