Bluetooth: Mesh: Fix sysbuild configuration for mesh samples
nrfconnect/sdk-nrf pull request #14181
Opened 2024-02-26 07:32 UTC by PavelVPV

This PR enables the extended advertising API support and the necessary amount of advertising sets in the Bluetooth controller on the network core required by the Bluetooth Mesh when a sample is build with
`--sysbuild` option.

This PR also describes which options must be enabled on the network core for the bluetooth controller to work with mesh.

2024-02-26 07:33 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14181/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14181/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14181/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-26 08:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14181
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-26 11:49 UTC, PavelVPV commented
> LGTM. Shouldn't we remove `child image` support?

From what I understand it should stays while we support child image.

2024-02-26 11:51 UTC, alxelax approved these changes

2024-02-27 13:24 UTC, mia-ko requested changes

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/protocols/bt/bt_mesh/configuring.rst
> +When the Bluetooth controller is located on a separate image (like in :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`), the following configuration must be applied to the Bluetooth
```suggestion
When the Bluetooth LE Controller is located on a separate image (like on the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards), the following configuration must be applied to the Bluetooth LE Controller configuration:
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards.
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards.
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards.
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards.
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` and :ref:`zephyr:thingy53_nrf5340` boards.
```

2024-02-27 13:24 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Building with :ref:`zephyr:sysbuild` for :ref:`zephyr:nrf5340dk_nrf5340`.
```suggestion
    * Building with :ref:`zephyr:sysbuild` for the :ref:`zephyr:nrf5340dk_nrf5340` boards.
```

2024-02-27 13:45 UTC, mia-ko approved these changes

2024-02-28 09:20 UTC, jfischer-no commented
@PavelVPV Please rebase

2024-02-28 09:22 UTC, ludvigsj approved these changes

2024-02-28 09:28 UTC, PavelVPV commented
> @PavelVPV Please rebase

Done

2024-02-29 07:18 UTC, merged