applications: serial_lte_modem: improve AT Carrier documentation
nrfconnect/sdk-nrf pull request #14186
Opened 2024-02-26 09:46 UTC by kacperradoszewski

Added more descriptive documentation of custom AT commands in the LwM2M Carrier library integration.

2024-02-26 09:49 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14186/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14186/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14186/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-26 10:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14186
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-26 10:25 UTC, SeppoTakalo approved these changes

2024-02-26 11:12 UTC, MarkusLassila approved these changes

2024-02-26 11:12 UTC, MarkusLassila commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  * ``2`` - :kconfig:option:`CONFIG_LWM2M_CARRIER_ATT`.
Will conflict with https://github.com/nrfconnect/sdk-nrf/pull/14125

2024-02-26 14:15 UTC, wiba-nordic requested changes

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<uncertainty_v>`` is the vertical uncertainty speed in meters per second. Must be a non-negative float type value in double quotes.
```suggestion
  Set or update the latest velocity information that will be mapped into the Velocity resource (ID: 4) and Speed resource (ID: 6) of the Location object (ID: 6).

  * ``<heading>`` is the horizontal direction of movement in degrees clockwise from North.
    Must be an integer value between ``0`` and ``359``.
  * ``<speed_h>`` is the horizontal non-negative speed in meters per second.
    Must be a float type value in double quotes.
  * ``<speed_v>`` is the vertical speed in meters per second.
    A positive value indicates upward motion, while a negative value indicates downward motion.
    Must be a float type value in double quotes.
  * ``<uncertainty_h>`` is the horizontal uncertainty speed in meters per second.
    Must be a non-negative float type value in double quotes.
  * ``<uncertainty_v>`` is the vertical uncertainty speed in meters per second.
    Must be a non-negative float type value in double quotes.
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  Put the value in ``<voltage>`` into the Power Source Voltage resource (ID:7) instance corresponding to one of the Available Power Sources resource (ID:6) instances of the Device object (ID:3).
```suggestion
  Put the value in ``<voltage>`` into the Power Source Voltage resource (ID: 7) instance corresponding to one of the Available Power Sources resource (ID: 6) instances of the Device object (ID: 3).
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<voltage>`` must be an integer value specified in millivolts (mV).
```suggestion
  ``<voltage>`` must be an integer value specified in millivolts.
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  Set flag to automatically apply the enabled settings to the LwM2M carrier library configuration and connect to the device management network.
```suggestion
  Set a flag to automatically apply the enabled settings to the LwM2M carrier library configuration and connect to the device management network.
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<interval>`` must be an integer value specified in seconds. Two special values may also be used: ``-1`` to always use Confirmable notifications, or ``0`` to use the default interval of 86400 seco
```suggestion
  ``<interval>`` must be an integer value specified in seconds.
  Two special values may also be used: ``-1`` to always use Confirmable notifications, or ``0`` to use the default interval of 86400 seconds.
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  Configure the value in ``<manufacturer>`` to be put into the Manufacturer resource (ID:0) of the Device object (ID:3).
```suggestion
  Configure the value in ``<manufacturer>`` to be put into the Manufacturer resource (ID: 0) of the Device object (ID: 3).
```

2024-02-26 14:15 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<pdn_type>`` must be an integer value. It accepts the following values:
```suggestion
  ``<pdn_type>`` must be an integer value.
  It accepts the following values:
```

2024-02-27 09:53 UTC, kacperradoszewski commented
Thanks @wiba-nordic, I believe I have applied all the suggestions.

2024-02-27 10:48 UTC, wiba-nordic reviewed
A couple of spacing errors that will break the documentation build. 

I also suggest adding the following in the Updated part of the SLM section in the changelog:
```
  * The documentation for the ``#XCARRIER`` command by adding more detailed information.
```

2024-02-27 10:48 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  The URI path of the resource instance is indicated as ``/10250/0/0``.
```suggestion
    The URI path of the resource instance is indicated as ``/19/<obj_inst_id>/0/<res_inst_id>``.
  * If ``<obj_inst_id>`` and ``<res_inst_id>`` are not present, the data is set in the Uplink Data resource (ID: 0) of the App Data Container object (ID: 10250).
    The URI path of the resource instance is indicated as ``/10250/0/0``.
  * If ``<data>`` is not present, SLM enters ``slm_data_mode`` and the data is set in the Uplink Data resource (ID: 0) of the App Data Container object (ID: 10250).
    The URI path of the resource instance is indicated as ``/10250/0/0``.
```

2024-02-27 10:57 UTC, wiba-nordic approved these changes

2024-02-27 10:58 UTC, kacperradoszewski commented
> A couple of spacing errors that will break the documentation build.
> 
> I also suggest adding the following in the Updated part of the SLM section in the changelog:
> 
> ```
>   * The documentation for the ``#XCARRIER`` command by adding more detailed information.
> ```

Added a slightly modified entry in the changelog to include the other command too:
`The documentation for the ``#XCARRIER`` and ``#XCARRIERCFG`` commands by adding more detailed information.`

2024-02-27 12:42 UTC, merged