boards: arm: thingy91x: pin fixups
nrfconnect/sdk-nrf pull request #14188
Opened 2024-02-26 11:26 UTC by maxd-nordic

This patch sets the power-switch input pin correctly in the npm13 configuration for Thingy91x.

2024-02-26 11:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14188/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14188/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14188/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-27 09:12 UTC, jhn-nordic approved these changes

2024-02-27 12:17 UTC, coderbyheart requested changes

2024-02-27 12:17 UTC, coderbyheart commented on applications/asset_tracker_v2/sysbuild/mcuboot/boards/thingy91x_nrf9151.conf
> +# MCUBoot settings
```suggestion
#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# MCUBoot settings
```

2024-02-27 12:17 UTC, coderbyheart commented on sysbuild/CMakeLists.txt
> +    set(board_secure thingy91x_nrf9151)
```suggestion
  elseif(BOARD STREQUAL "thingy91x_nrf9151_ns")
    set(board_secure thingy91x_nrf9151)
```

2024-02-27 13:20 UTC, coderbyheart approved these changes

2024-02-28 07:34 UTC, merged