Applications: nrf5340_audio: Updated controller
nrfconnect/sdk-nrf pull request #14203
Opened 2024-02-26 17:08 UTC by koffes

OCT-2840
LE Audio controller subsystem updated to 17933

2024-02-26 17:09 UTC, koffes commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Updated to be based on ...
Changes to be added.

2024-02-26 17:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14203
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-26 19:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14203/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14203/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14203/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-27 05:56 UTC, rick1082 approved these changes

2024-02-27 07:10 UTC, alexsven approved these changes

2024-02-27 09:01 UTC, greg-fer requested changes
Would be good to add transition steps in the migration guide and a link to them, but there are three different PRs now addressing the same topic, so it is complicated to do this...

2024-02-27 09:01 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +The following changes have been introduced in the v17933 of the controller:
```suggestion
.. note::
     This controller is now :ref:`deprecated <api_deprecation>`. Before it is removed, make sure to transition to using :ref:`softdevice_controller`.

The following changes have been introduced in the v17933 of the controller:
```

2024-02-27 14:21 UTC, greg-fer requested changes
Please apply the blank lines after the note line and after the header.

2024-02-27 14:21 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Optimize CIS setup time.
```suggestion
.. note::
     This controller is now :ref:`deprecated <api_deprecation>`. Before it is removed, make sure to transition to using :ref:`softdevice_controller`.
 
The following changes have been introduced in the v17933 of the controller:

Changes
=======

* Improved the robustness for the CIS bidirectional four stream scenario (two sinks and two sources).
* Improved the stability for switching between the BIS and the CIS scenarios at runtime.
* Corrected the timestamps for BIS.
* Fixed the wrong Link Layer ID (LLID) from ISO empty packets.
* Corrected the disconnection reason for CIS.
* Modified handling of the missing support for pre-transmission offset (PTO). The sink will now accept ``PTO=0`` or ``PTO=1`` values and will not fail in either case.
* Optimized the CIS setup time.
* Bugfixes and stability improvements.
```

2024-02-27 14:52 UTC, greg-fer requested changes

2024-02-27 14:52 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Improved the robustness for the CIS bidirectional four stream scenario (two sinks and two sources).
```suggestion
The following changes have been introduced in the v17933 of the controller:

Changes
=======

* Improved the robustness for the CIS bidirectional four stream scenario (two sinks and two sources).
```

2024-02-27 14:55 UTC, greg-fer approved these changes

2024-02-27 17:25 UTC, merged