Bluetooth: Mesh: Allow multiple model appkey bindings
nrfconnect/sdk-nrf pull request #14238
Opened 2024-02-27 16:16 UTC by omkar3141

NLC profile requirements mandate the minimum value of "3" for BT_MESH_APP_KEY_COUNT setting. However, these multiple appkeys cannot be used with single model because corresponding BT_MESH_MODEL_KEY_COUNT config setting is still set to "1".

This is quite limiting from use-case perspetive. As multiple appkeys are supported on a node, there is no reason why it should not support multiple appkey bindings per model out-of-the-box.

2024-02-27 16:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14238/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14238/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14238/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-27 16:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14238
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-27 20:52 UTC, PavelVPV approved these changes

2024-02-28 07:38 UTC, Andrewpini approved these changes

2024-02-28 08:20 UTC, ludvigsj requested changes
This is not a formal requirement in any NLC profile. If we need a more sensible default for this option in general, that should be done in Zephyr, but it does not belong inside this NLC option since it's not a NLC-specific requirement.

2024-02-28 08:35 UTC, omkar3141 commented
This is a downstream update, driven by feedback from field. By adding option in Zephyr we expand the scope for this default setting where nobody is asking for this. 

I would strongly recommend to have this, the alternative would be to add this option manually in every single sample and set it to "3".

2024-02-28 08:44 UTC, ludvigsj commented
> This is a downstream update, driven by feedback from field. By adding option in Zephyr we expand the scope for this default setting where nobody is asking for this.
> 
> I would strongly recommend to have this, the alternative would be to add this option manually in every single sample and set it to "3".

I like the alternative of updating the samples much better. The sample at least has a well defined use-case. This is also where we would have made the change for any other sample which is not implementing any NLC profiles.

2024-02-28 09:10 UTC, PavelVPV commented on samples/bluetooth/mesh/light_ctrl/prj.conf
> +CONFIG_BT_MESH_MODEL_KEY_COUNT=3
Add a note why it is increased?

2024-02-28 09:12 UTC, ludvigsj commented
`sensor_client` also needs this change, it also sets up 3 app keys

2024-02-28 09:27 UTC, omkar3141 commented on samples/bluetooth/mesh/light_ctrl/prj.conf
> +CONFIG_BT_MESH_MODEL_KEY_COUNT=3
Done.

2024-02-28 09:32 UTC, ludvigsj approved these changes

2024-02-28 09:32 UTC, ludvigsj commented on samples/bluetooth/mesh/light_ctrl/prj.conf
> +# 3 appkeys.Therefore, allow upto 3 appkey bindings per model instance.
```suggestion
# Enabling BT_MESH_NLC_PERF_CONF enables support for 3 application keys by default.
# Therefore, allow up to 3 application key bindings per model instance.
```

2024-02-28 09:32 UTC, ludvigsj requested changes
Pressed wrong button, see comment above (and `sensor_client`)

2024-02-28 12:12 UTC, omkar3141 commented
> Pressed wrong button, see comment above (and `sensor_client`)

Ok, I don't think sensor client would need any additional explanation since `BT_MESH_APP_KEY_COUNT` is added without any explanation anyway. Also, if anyone sees commit message, they would get the reason.

2024-02-28 12:15 UTC, PavelVPV approved these changes

2024-02-28 12:16 UTC, ludvigsj approved these changes

2024-02-28 13:42 UTC, merged