manifest: zephyr: update zephyr remove weak nrf_802154_clock_hfclk_ready
nrfconnect/sdk-nrf pull request #14244
Opened 2024-02-28 07:16 UTC by ankuns

This commit updates Zephyr with removed __WEAK-tagged version of nrf_802154_clock_hfclk_ready.

2024-02-28 07:17 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/f3f276dd2ecad981a2abf1d87c3d3d0b2e9d5373 | https://github.com/nrfconnect/sdk-zephyr/pull/1545 | [nrfconnect/sdk-zephyr#1545/files](https://github.com/nrfconnect/sdk-zephyr/pull/1545/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-28 07:20 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14244/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14244/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14244/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-28 07:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14244
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-28 19:59 UTC, LuDuda approved these changes

2024-02-29 09:50 UTC, jfischer-no requested changes
Please do not update sdk-zephyr revision here.

2024-02-29 10:03 UTC, closed without merging