doc: wifi: Update memory footprint tables for 2.6 release
nrfconnect/sdk-nrf pull request #14267
Opened 2024-02-28 20:05 UTC by richabp

Updated Wi-Fi memory footprint tables for 2.6 release.

Created new "Memory requirements for Wi-Fi applications in SoftAP mode" page for SoftAP mode.

NCSDK-26300

2024-02-28 20:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14267/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14267/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-02-28 20:13 UTC, krish2718 approved these changes

2024-02-28 20:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14267
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-29 06:16 UTC, kittydepa approved these changes

2024-02-29 09:13 UTC, ioannisg requested changes
Thanks for the PR @richabp 
I left some editorial comments in the review.

In addition to that, I had a look at the numbers and I see several inconsistencies.
Above all, we need to revisit the list of samples for each platform and operation mode. Scan and SoftAP seem to be correct. STA mode, however should not include any samples for nRF91 Series of ICs. Samples should be listed for nRF52840 DK and nRF7002 DK

2024-02-29 09:13 UTC, ioannisg commented on doc/nrf/protocols/wifi/sap_mode/mem_requirements_sap.rst
> +Code and RAM memory footprint requirements differ depending on the selected platform and the application example.
```suggestion
Code and RAM memory footprint requirements differ depending on the selected platform, networking application layer, and application example.
```

2024-02-29 09:13 UTC, ioannisg commented on doc/nrf/protocols/wifi/sap_mode/mem_requirements_sap.rst
> +Code and RAM memory footprint requirements differ depending on the selected platform and the application example.
Essentially, these examples differ with respect to the selected application layer...

2024-02-29 09:13 UTC, ioannisg commented on doc/nrf/protocols/wifi/sap_mode/index.rst
> +The following subpages describe the memory requirements of the SoftAP sample and how an nRF70 Series device operates in :term:`Software-enabled Access Point (SoftAP or SAP)` mode.
I'd say let's make this text more generics, as we are likely going to add more examples with SoftAP mode.

2024-02-29 09:13 UTC, ioannisg commented on doc/nrf/protocols/wifi/sap_mode/index.rst
> +The following subpages describe the memory requirements of the SoftAP sample and how an nRF70 Series device operates in :term:`Software-enabled Access Point (SoftAP or SAP)` mode.
```suggestion
The following subpages describe how an nRF70 Series device operates in :term:`Software-enabled Access Point (SoftAP or SAP)` mode, along with  the memory requirements of Wi-Fi® applications that use the SoftAP mode.
```

2024-02-29 12:07 UTC, richabp commented
> Thanks for the PR @richabp I left some editorial comments in the review.
> 
> In addition to that, I had a look at the numbers and I see several inconsistencies. Above all, we need to revisit the list of samples for each platform and operation mode. Scan and SoftAP seem to be correct. STA mode, however should not include any samples for nRF91 Series of ICs. Samples should be listed for nRF52840 DK and nRF7002 DK

As discussed, the team will check and update about the inconsistencies in the numbers. Then, another PR could be open after this gets merged.

2024-02-29 12:37 UTC, ioannisg commented
The sample selection looks good now (MQTT sample still missing though)

2024-02-29 12:43 UTC, richabp commented
> The sample selection looks good now (MQTT sample still missing though)

Will address thin in a doc improvement PR once this is merged.

2024-02-29 12:44 UTC, ioannisg approved these changes
+1 to get this in, since the sample selection is correct.
Footprint numbers are still wrong, but I assume they can be fixed before v2.6.0

2024-02-29 12:47 UTC, richabp commented
> +1 to get this in, since the sample selection is correct. Footprint numbers are still wrong, but I assume they can be fixed before v2.6.0

@krga2022 @visinor FYI.

2024-02-29 13:57 UTC, merged