applications: nrf5340_audio: Update controller to version 18929
nrfconnect/sdk-nrf pull request #14275
Opened 2024-02-29 09:25 UTC by alexsven

- OCT-2928
- Le Audio controller subsystem updated to 18929

2024-02-29 09:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14275/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14275/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14275/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-02-29 09:28 UTC, rick1082 approved these changes

2024-02-29 09:38 UTC, koffes requested changes
I need to look over the checklist.

2024-02-29 09:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14275
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-02-29 11:27 UTC, Frodevan approved these changes

2024-02-29 13:01 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
> +* Fixed bug where right headset would disconnect in bidirectional mode.
```suggestion
* Fixed a bug where the right headset would disconnect when in bidirectional mode.
```

2024-02-29 13:04 UTC, greg-fer approved these changes

2024-03-01 09:05 UTC, SeppoTakalo approved these changes

2024-03-01 09:12 UTC, jfischer-no approved these changes

2024-03-01 09:12 UTC, merged