matter: fix usage of Link Time Optimization in Matter applications
nrfconnect/sdk-nrf pull request #14295
Opened 2024-02-29 21:40 UTC by LuDuda

This commit fixes the usage of LTO for Matter applications.

This PR depends on #14258 which must be merged first.

2024-02-29 21:40 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/efdae04affa42dc81d51f6473fc0e148115e90b3 | https://github.com/nrfconnect/sdk-connectedhomeip/pull/398 | [nrfconnect/sdk-connectedhomeip#398/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/398/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-02-29 21:41 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14295/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14295/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14295/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-01 08:16 UTC, wiba-nordic requested changes

2024-03-01 08:16 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/memory_optimization.rst
> +To enable LTO, set the :kconfig:option:`CONFIG_LTO` and :kconfig:option:`CONFIG_ISR_TABLES_LOCAL_DECLARATION`Kconfig options to ``y``.
```suggestion
To enable LTO, set the :kconfig:option:`CONFIG_LTO` and :kconfig:option:`CONFIG_ISR_TABLES_LOCAL_DECLARATION` Kconfig options to ``y``.
```

2024-03-01 08:16 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    :kconfig:option:`CONFIG_LTO` and :kconfig:option:`CONFIG_ISR_TABLES_LOCAL_DECLARATION` Kconfig options to ``y``.
```suggestion
  * Experimental support for building Matter samples and applications with Link Time Optimization (LTO).
    To enable it, set the :kconfig:option:`CONFIG_LTO` and :kconfig:option:`CONFIG_ISR_TABLES_LOCAL_DECLARATION` Kconfig options to ``y``.
```

2024-03-01 08:24 UTC, wiba-nordic approved these changes
Docs look good.

2024-03-01 08:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14295
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-01 09:24 UTC, ArekBalysNordic approved these changes

2024-03-01 09:24 UTC, Damian-Nordic approved these changes

2024-03-01 13:05 UTC, SeppoTakalo approved these changes

2024-03-05 13:54 UTC, merged