doc: Trusted Storage maturity
nrfconnect/sdk-nrf pull request #14305
Opened 2024-03-01 11:14 UTC by SebastianBoe

Trusted Storage maturity documentation.

2024-03-01 11:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14305/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14305/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-03-01 11:56 UTC, mia-ko requested changes

2024-03-01 11:56 UTC, mia-ko commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +* Trusted Storage
```suggestion
* Trusted storage
```

2024-03-01 11:56 UTC, mia-ko commented on doc/_scripts/software_maturity/software_maturity_features.yaml
> +    Trusted Storage implements Secure Storage without using TF-M: TRUSTED_STORAGE
```suggestion
    Trusted storage implements the PSA Certified Secure Storage APIs without using TF-M: TRUSTED_STORAGE
```

2024-03-01 11:56 UTC, mia-ko commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +Trusted Storage
```suggestion
Trusted storage
```

2024-03-01 13:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14305
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-01 14:09 UTC, mia-ko commented on doc/_scripts/software_maturity/software_maturity_features.yaml
> +    Trusted Storage implements Secure Storage without using TF-M: TRUSTED_STORAGE
I don't see the change reflected in the file.

2024-03-04 09:09 UTC, mia-ko approved these changes

2024-03-04 09:29 UTC, mia-ko commented on doc/_scripts/software_maturity/software_maturity_features.yaml
> +    TRUSTED_STORAGE
Btw, shouldn't this be in line 138?

2024-03-04 10:39 UTC, SeppoTakalo approved these changes

2024-03-04 11:23 UTC, merged