doc: fix broken links, minor fixes, and toc update
nrfconnect/sdk-nrf pull request #14322
Opened 2024-03-01 16:27 UTC by divipillai

* Fixed broken links and toc update.
* Fixed a minor update to the nRF desktop application.
* Arranged Applications in alphabetical order.

2024-03-01 16:28 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | [nrfconnect/sdk-nrfxlib@v2.6.0-rc1](https://github.com/nrfconnect/sdk-nrfxlib/releases/tag/v2.6.0-rc1) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1237 | [nrfconnect/sdk-nrfxlib#1237/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1237/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-03-04 07:21 UTC, tomi-font approved these changes
Approving SLM changes.

2024-03-04 07:21 UTC, wiba-nordic approved these changes

2024-03-04 07:32 UTC, MarkusLassila approved these changes

2024-03-04 07:37 UTC, peknis requested changes

2024-03-04 07:37 UTC, peknis commented on doc/nrf/applications.rst
> +   ../../applications/serial_lte_modem/README
Serial modem before Thingies.

2024-03-04 07:37 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Cherry-pick changes from PR #332 in sdk-homekit repo.
```suggestion
  **Workaround:** Cherry-pick changes from PR #332 in the sdk-homekit repository.
```

2024-03-04 07:37 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Cherry-pick changes from PR #329 in sdk-homekit repo.
```suggestion
  **Workaround:** Cherry-pick changes from PR #329 in the sdk-homekit repository.
```

2024-03-04 07:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14322/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14322/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-rs | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14322/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-04 10:19 UTC, greg-fer approved these changes

2024-03-04 10:38 UTC, peknis approved these changes

2024-03-04 10:38 UTC, SeppoTakalo approved these changes

2024-03-04 12:53 UTC, divipillai commented
@carlescufi , @gmarull : Some of the links on this table are broken.  
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/repository_revisions.html#ncs-repository-revisions. The table is pulled from a script. The behavior is seen in the previous releases also. For example, qcbor -
[751d36583a9ce1a640900c57e13c9b6b8f3a2ba2](https://github.com/laurencelundblade/QCBOR.git/commit/751d36583a9ce1a640900c57e13c9b6b8f3a2ba2), dragoon etc.

Could you confirm how this can be fixed.

2024-03-04 13:07 UTC, MarekPieta approved these changes
nRF Desktop changes look good. Thanks for the fixes

2024-03-04 17:11 UTC, jayteemo approved these changes

2024-03-04 18:43 UTC, plskeggs approved these changes

2024-03-05 10:45 UTC, divipillai commented
Also, added files to fix broken links in the Matter repo ( provided by @wiba-nordic).

2024-03-05 11:54 UTC, juhaylinen approved these changes

2024-03-05 14:03 UTC, jfischer-no commented
@divipillai Do not update the revision yet, wait until https://github.com/nrfconnect/sdk-nrf/pull/14282 get merged.

2024-03-05 14:31 UTC, jfischer-no commented
> @divipillai Do not update the revision yet, wait until #14282 get merged.

@divipillai Please update.

2024-03-05 14:41 UTC, divipillai commented
> > @divipillai Do not update the revision yet, wait until #14282 get merged.
> 
> @divipillai Please update.

Updated.

2024-03-05 16:47 UTC, merged