doc: software_maturity: Added trusted storage table
nrfconnect/sdk-nrf pull request #14338
Opened 2024-03-04 11:34 UTC by SebastianBoe

Added trusted storage table to software maturity document.

2024-03-04 11:36 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14338/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14338/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-03-04 11:39 UTC, mia-ko requested changes

2024-03-04 11:39 UTC, mia-ko commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +* Trusted Storage
```suggestion
* Trusted storage
```

2024-03-04 11:39 UTC, mia-ko commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +Trusted Storage
```suggestion
Trusted storage
```

2024-03-05 10:20 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14338
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-05 10:28 UTC, mia-ko approved these changes

2024-03-05 10:37 UTC, melwee01 approved these changes

2024-03-05 11:32 UTC, merged