Bluetooth: Mesh: Add note about LBS service adv
nrfconnect/sdk-nrf pull request #14344
Opened 2024-03-04 14:04 UTC by PavelVPV

Add a note that LBS Service advs are stopped after someone connected to the advs.

2024-03-04 14:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14344/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14344/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-03-04 14:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14344
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-05 08:37 UTC, mia-ko requested changes

2024-03-05 08:37 UTC, mia-ko commented on samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst
> +   Reboot the device to restart the LBS Service UUID advertisements.
```suggestion
   Once connected, the device will not advertise with the LBS Service UUID until the device is rebooted.
   Reboot the device to restart the LBS Service UUID advertisements.
```

2024-03-05 09:46 UTC, ludvigsj approved these changes

2024-03-05 10:25 UTC, merged