manifest: update Zephyr revision
nrfconnect/sdk-nrf pull request #14367
Opened 2024-03-05 11:16 UTC by maciejbaczmanski

Pull bugfix for too low shell stack size for OpenThread

2024-03-05 11:17 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/3912101710c23bfa3b6a2c5ab6fdecb6043a7133 | https://github.com/nrfconnect/sdk-zephyr/pull/1560 | [nrfconnect/sdk-zephyr#1560/files](https://github.com/nrfconnect/sdk-zephyr/pull/1560/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-03-05 11:17 UTC, edmont approved these changes

2024-03-05 11:18 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14367/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14367/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14367/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-05 11:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14367
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-07 07:54 UTC, jfischer-no requested changes
Please do not update sdk-zephyr revision here.

2024-03-07 07:59 UTC, jfischer-no commented
sdk-zephyr revision updated in https://github.com/nrfconnect/sdk-nrf/pull/14395

2024-03-07 08:10 UTC, maciejbaczmanski commented
> Please do not update sdk-zephyr revision here.

oh sorry, didn't see that. so I guess we can close this PR

2024-03-07 08:11 UTC, closed without merging