manifest: Update RPU patch to rev #5d9627b143a
nrfconnect/sdk-nrf pull request #14370
Opened 2024-03-05 12:26 UTC by kspraveeen

SHEL-2548:Apply PA, DA and PGA bias based on package type information. 
SHEL-2550:Avoid antenna gain and edge backoff when regulatory domain is bypassed.
SHEL-2546:Added missing functions to the Patch list to disable DPD depending on Temperature measured.

2024-03-05 12:26 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/d622557b17c7c97d196f0baf27b322d87f2850b8 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1243 | [nrfconnect/sdk-nrfxlib#1243/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1243/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-03-05 12:28 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14370/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14370/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14370/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-05 13:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14370
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-06 11:45 UTC, srkanordic approved these changes

2024-03-06 12:25 UTC, udaynordic approved these changes

2024-03-07 10:42 UTC, jfischer-no requested changes
Please do not update manifest revision here.
Perhaps https://github.com/nrfconnect/sdk-nrf/pull/14419 will update nrfxlib revision.

2024-03-07 11:49 UTC, SeppoTakalo approved these changes

2024-03-07 13:41 UTC, jfischer-no commented
https://github.com/nrfconnect/sdk-nrf/pull/14370#pullrequestreview-1922095370

2024-03-07 13:41 UTC, closed without merging