doc: wifi: Update radio test documents to reflect new commands
nrfconnect/sdk-nrf pull request #14410
Opened 2024-03-06 12:36 UTC by imapa

[SHEL-2521]: The documentation for recently incorporated RF test commands has been updated within the radio test sample. Furthermore, the TX command sequences have been revised to demonstrate the utilization of these newly integrated commands.

2024-03-06 12:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14410/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14410/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-03-06 13:43 UTC, richabp requested changes
Does it require a Changelog entry?

2024-03-06 13:43 UTC, richabp commented on samples/wifi/radio_test/radio_test_subcommands.rst
> +     - 'val' is subtracted from the transmit power.
```suggestion
     - <val> is subtracted from the transmit power.
```

2024-03-06 13:43 UTC, richabp commented on samples/wifi/radio_test/radio_test_subcommands.rst
> +     - If the channel is an edge channel, the value of 'val' is subtracted from the transmit power.
```suggestion
     - If the channel is an edge channel, the value of <val> is subtracted from the transmit power.
```

2024-03-06 13:43 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         * To run a continuous Orthogonal frequency-division multiplexing (OFDM) TX traffic sequence with the following configuration:
```suggestion
         * To run a continuous OFDM TX traffic sequence with the following configuration:
```

2024-03-06 13:43 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +              ``set_edge_bo`` and ``set_ant_gain`` commands. These backoffs are applied only when ``bypass_reg_domain`` is ``0``
```suggestion
            Edge backoff and antenna gain are configured in the Kconfig file. 
           To overwrite these backoffs with user-specified backoffs, use the``set_edge_bo`` and ``set_ant_gain`` commands. 
           These backoffs are applied only when the ``bypass_reg_domain`` is set to ``0``.
```

2024-03-06 13:55 UTC, srkanordic commented on samples/wifi/radio_test/sample_description.rst
> +              wifi_radio_test tx_power 4
Increase the example tx_power. Otherwise, we see 4 - 2 -3 = -1dBm power. This will be lower than lower tx power limit.

2024-03-07 07:37 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +              ``set_edge_bo`` and ``set_ant_gain`` commands. These backoffs are applied only when ``bypass_reg_domain`` is ``0``
Seems some parts of the feedback is missed while incorporating.

2024-03-07 07:50 UTC, richabp requested changes

2024-03-07 07:50 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Added support for run time configuration of antenna gain and edge backoff parameters.
```suggestion
    * Added support for runtime configuration of antenna gain and edge backoff parameters.
```

2024-03-07 07:50 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Support for CSP package.
```suggestion
  * Support for the CSP package.
```

2024-03-07 07:50 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Application of edge backoff is modified. It used to be subtracted from regulatory power limit. Now, backoff is subtracted from data rate dependent power ceiling.
```suggestion
  * Modification to the application of edge backoff.
    Previously, it was subtracted from the regulatory power limit.
    Now, backoff is subtracted from the data rate-dependent power ceiling.
```

2024-03-07 08:00 UTC, bama-nordic approved these changes

2024-03-07 08:58 UTC, srkanordic approved these changes

2024-03-07 09:07 UTC, richabp approved these changes

2024-03-07 10:39 UTC, merged