manifest: sdk-hostap: Pull error logs for security
nrfconnect/sdk-nrf pull request #14423
Opened 2024-03-06 21:13 UTC by krish2718

These logs are crucial to debug and fix any configuration issues that affect Wi-Fi security handshakes.

2024-03-06 21:14 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hostap | https://github.com/nrfconnect/sdk-hostap/commit/dda5457ad2cfce99e333980c7764c8d480ae4010 (main) | https://github.com/nrfconnect/sdk-hostap/pull/160 | [nrfconnect/sdk-hostap#160/files](https://github.com/nrfconnect/sdk-hostap/pull/160/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-03-06 21:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14423/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14423/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |

**test-sdk-wifi:** added because there was no .github/test-spec.yml in 'hostap'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14423/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-06 21:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14423
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-07 10:40 UTC, sachinthegreen approved these changes

2024-03-07 12:03 UTC, SeppoTakalo requested changes
The proposed changes in just `[nrf noup]` commits that add more debug logs.

I don't understand how this justifies as a bugfix for RC.

If this is improvement, it should be first proposed upstream.

2024-03-26 16:54 UTC, krish2718 commented
Will revisit after submitting upstream.

2024-03-26 16:54 UTC, closed without merging