manifest: Bring in MCUmgr fix for MCUBOOT_BOOTLOADER_NO_DOWNGRADE
nrfconnect/sdk-nrf pull request #14437
Opened 2024-03-07 11:48 UTC by de-nordic

The commit updates Zephyr to brin in fix where
CONFIG_MCUBOOT_BOOTLOADER_NO_DOWNGRADE check in code has been missing the CONFIG_ prefix, making the selection of the Kconfig option ineffective.

2024-03-07 11:48 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/8d93a161567dcc525771f70692587e6a37947b71 | https://github.com/nrfconnect/sdk-zephyr/pull/1567 | [nrfconnect/sdk-zephyr#1567/files](https://github.com/nrfconnect/sdk-zephyr/pull/1567/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-03-07 11:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14437/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14437/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14437/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-07 11:57 UTC, nordicjm requested changes
*bring (commit message)

2024-03-22 12:39 UTC, nordicjm commented
Needs rebase

2024-04-25 10:43 UTC, de-nordic commented
https://github.com/nrfconnect/sdk-nrf/pull/15033 takes over.

2024-04-25 10:43 UTC, closed without merging