nrf_security: Fix crypto include path issue
nrfconnect/sdk-nrf pull request #14446
Opened 2024-03-07 14:59 UTC by SebastianBoe

Fix crypto include path issue.

See comment in code for details.

Fixes an issue I had when building for the non-secure image.

2024-03-07 15:01 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14446/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14446/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14446/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-07 18:15 UTC, Vge0rge approved these changes

2024-03-08 09:41 UTC, frkv requested changes
Please delay taking this in until I have run CI on a proposal for a bugfix

(will remove the change request-statement, depending on first run)

2024-03-11 09:48 UTC, mswarowsky approved these changes

2024-04-10 14:05 UTC, SebastianBoe commented
already applied by a different PR

2024-04-10 14:05 UTC, closed without merging