Bluetooth: Mesh: Fix parsing Kconfig with multiple equals signs
nrfconnect/sdk-nrf pull request #14452
Opened 2024-03-08 07:09 UTC by PavelVPV

This fixes in particular parsing such Kconfig option: CONFIG_MODEM_ANTENNA_AT_MAGPIO="AT%XMAGPIO=1,0,0,1,1,1574,1577"

2024-03-08 07:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14452/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14452/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14452/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-08 08:58 UTC, ludvigsj approved these changes

2024-03-08 08:58 UTC, ludvigsj commented on scripts/bluetooth/mesh/mesh_dfu_metadata.py
> +                    kconfig, value = line.split("=")[:2]
Then value will contain `"AT%XMAGPIO` which is probably not what we want. 
```suggestion
                    kconfig, value = line.split("=", 1)
```

2024-03-08 08:59 UTC, ludvigsj requested changes
Pressed wrong button ... se change request above

2024-03-08 09:51 UTC, ludvigsj approved these changes

2024-03-08 09:54 UTC, Andrewpini approved these changes

2024-03-08 12:32 UTC, omkar3141 approved these changes

2024-03-11 11:15 UTC, SeppoTakalo approved these changes

2024-03-11 11:26 UTC, merged