net: lib: nrf_cloud_coap: Extend proprietary PSM support
nrfconnect/sdk-nrf pull request #14556
Opened 2024-03-18 23:27 UTC by plskeggs

Select LTE proprietary PSM mode for the 9131 and 9151 SOCs in addition to the existing 9161 selection, when building for CoAP connectivity to nRF Cloud.

Jira: IRIS-8450

2024-03-18 23:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14556/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14556/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14556/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-19 00:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14556
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-19 00:53 UTC, jayteemo approved these changes

2024-03-19 00:53 UTC, jayteemo commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Updated to request proprietary PSM mode for SOC_NRF9151_LACA and SOC_NRF9131_LACA in addition to SOC_NRF9151_LACA || SOC_NRF9161_LACA.
```suggestion
  * Updated to request proprietary PSM mode for SOC_NRF9151_LACA and SOC_NRF9131_LACA in addition to SOC_NRF9161_LACA.
```

2024-03-19 23:16 UTC, glarsennordic approved these changes
Point of curiosity, why do we enable this specifically for CoAP?

2024-03-19 23:24 UTC, plskeggs commented
> Point of curiosity, why do we enable this specifically for CoAP?

Our CoAP service does not send unsolicited packets to the device, so it is safe to use proprietary PSM mode, which keeps the receiver off while in power saving mode.  Regular PSM keeps the receiver on, so unsolicited packets will be received.

2024-03-19 23:32 UTC, glarsennordic commented
Ahhh, thank you, that makes sense

2024-03-21 07:25 UTC, peknis requested changes

2024-03-21 07:25 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Updated to request proprietary PSM mode for SOC_NRF9151_LACA and SOC_NRF9131_LACA in addition to SOC_NRF9161_LACA.
```suggestion
  * Updated to request proprietary PSM mode for ``SOC_NRF9151_LACA`` and ``SOC_NRF9131_LACA`` in addition to ``SOC_NRF9161_LACA``.
```

2024-03-22 06:24 UTC, peknis approved these changes

2024-03-25 07:19 UTC, merged