sdfw_services: add sdfw_services framework
nrfconnect/sdk-nrf pull request #14576
Opened 2024-03-19 14:35 UTC by anhmolt

* Adds `sdfw_services` framework for invoking secure domain services on `nRF54h20`.
* Adds `ssf_client` sample showing how to use services from application and radio core.
* Small fixes for nRF RPC.

_Note:_ Framework does not work with already released SecDomFW binaries. Most likely because of incompatibilities/changes in ICMsg shared memory. Address of read and write indices at the start of shared memory seems to deviate and ICMsg binding fails as a result. Investigation is ongoing.

2024-03-19 14:37 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14576/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14576/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14576/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-19 15:04 UTC, katgiadla submitted a review, later dismissed
Please specify the responsible person for this test and sample (add github nicknames in the file `CODEOWNERS`)

2024-03-20 09:51 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14576
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-20 13:06 UTC, greg-fer requested changes
This looks like a doc domain of @FrancescoSer  and @annwoj , given the relation to nRF54.

Also, I think we need a mention about this in https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/security.html and an entry in the changelog.

It also looks like a candidate for one of the core firmware components discussed here: https://nordicsemi.atlassian.net/browse/NCSDK-10551 -- @carlescufi , @pdunaj , @grochu , @wbober , what do you think? The only existing core firmware component has been integrated as an application in https://github.com/nrfconnect/sdk-nrf/pull/12588 given that there were no other core firmware components at that point. Should this SDFW and IPC Radio be grouped together?

2024-03-21 11:34 UTC, FrancescoSer commented on samples/sdfw/ssf_client/README.rst
> +Available Secure Domain Services can be found in :file:`nrf/include/sdfw_services`.
Could we add a file where we describe in detail these 8 services listed there?

2024-03-22 07:23 UTC, osaether approved these changes
LGTM but content itself is not reviewed in this round.

2024-03-22 07:47 UTC, 9gcity approved these changes

2024-03-22 07:55 UTC, hakonfam approved these changes
Locations of files looks good to me. Content itself is not reviewed in this round.

2024-03-25 16:28 UTC, pdunaj commented
> This looks like a doc domain of @FrancescoSer and @annwoj , given the relation to nRF54.
> 
> Also, I think we need a mention about this in https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/security.html and an entry in the changelog.
> 
> It also looks like a candidate for one of the core firmware components discussed here: https://nordicsemi.atlassian.net/browse/NCSDK-10551 -- @carlescufi , @pdunaj , @grochu , @wbober , what do you think? The only existing core firmware component has been integrated as an application in #12588 given that there were no other core firmware components at that point. Should this SDFW and IPC Radio be grouped together?

As for core components, this is framework not a firmware image. This does not fit there.
Regarding other changes - this change is on a critical path. Unless something is very wrong, I highly recommend to merge it and fix whatever is needed on the go.
Assuming the above comment could you let it in @greg-fer ? If there are some remaining activities could these be placed under a jira ticket and fixed before June?

2024-03-25 16:38 UTC, pdunaj commented
@doki-nordic please have a look at the changes after this get's in.

2024-03-26 10:38 UTC, jonathannilsen approved these changes

2024-03-26 11:55 UTC, merged