applications: serial_lte_modem: UART config/doc improvements
nrfconnect/sdk-nrf pull request #14571
Opened 2024-03-19 12:57 UTC by tomi-font

2024-03-19 13:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14571/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14571/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14571/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-19 13:12 UTC, wiba-nordic requested changes

2024-03-19 13:12 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CMUX_AT_commands.rst
> +   With higher baud rates (921 600, 1 000 000) it can happen that bytes come in faster than the chip is able to handle, and after a sufficient amount of them at once buffer space runs out.
```suggestion
   With higher baud rates (921 600, 1 000 000), it is possible for bytes to come in faster than the chip is able to handle, which can cause the buffer space to run out if it goes on for too long.
```

2024-03-19 13:12 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CMUX_AT_commands.rst
> +   At a baud rate of 460 800, the maximum throughput is slightly below that of the nRF91 series modem.
```suggestion
   At a baud rate of 460 800, the maximum throughput is slightly below that of the nRF91 Series modem.
```

2024-03-19 13:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14571
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-19 13:30 UTC, MarkusLassila commented on applications/serial_lte_modem/doc/CMUX_AT_commands.rst
> +   At a baud rate of 460 800, the maximum throughput is slightly below that of the nRF91 series modem.
... modem with LTE-M1.

2024-03-19 13:37 UTC, MarkusLassila approved these changes
Looks good. I will run these over when I am setting CI up.

2024-03-20 07:23 UTC, wiba-nordic approved these changes

2024-03-20 08:49 UTC, MarkusLassila approved these changes

2024-03-20 13:55 UTC, SeppoTakalo approved these changes

2024-03-26 09:01 UTC, merged