applications: machine_learning: Allow running ML model with no anomaly
nrfconnect/sdk-nrf pull request #14596
Opened 2024-03-21 10:47 UTC by MarekPieta

Change updates ML runner application module to allow running ML model without anomaly support.

Jira: NCSDK-25938

2024-03-21 10:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14596/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14596/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14596/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-21 11:18 UTC, peknis requested changes

2024-03-21 11:18 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated ``ml_runner`` application module to allow running a machine learning model without anomaly support.
```suggestion
* Updated the ``ml_runner`` application module to allow running a machine learning model without anomaly support.
```

2024-03-21 11:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14596
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-21 13:38 UTC, mkapala-nordic approved these changes

2024-03-22 06:23 UTC, peknis approved these changes

2024-03-25 09:12 UTC, pdunaj approved these changes

2024-03-25 09:32 UTC, merged