drivers: wifi: Disable workaround for anomaly 159
nrfconnect/sdk-nrf pull request #14618
Opened 2024-03-22 12:53 UTC by krish2718

The proper workaround would be to use 64MHz CPU that will impact Wi-Fi performance, and as its never been seen so far, disable the workaround, and this can be revisited in the future.

Fixes SHEL-2636.

2024-03-22 12:54 UTC, anangl approved these changes

2024-03-22 12:55 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14618/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14618/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14618/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-22 15:46 UTC, anangl requested changes

2024-03-22 15:46 UTC, anangl commented on drivers/wifi/nrf700x/CMakeLists.txt
> +  -DNRF53_ERRATA_159_ENABLE_WORKAROUND=0
I think this should be disabled only if QSPI is used for communication with nRF700x, so as above, `zephyr_compile_definitions_ifdef(CONFIG_NRF700X_ON_QSPI` should be used here.

2024-03-22 16:02 UTC, anangl approved these changes

2024-03-22 18:47 UTC, krish2718 commented
@anangl I saw that you had already fixed the issue https://github.com/nrfconnect/sdk-nrf/commit/23639c79b86ecbab2be64a75ce33c7ad164fd2f0 , as you now use 192MHz, do we still need this fix?

2024-03-25 10:25 UTC, anangl commented
> @anangl I saw that you had already fixed the issue [23639c7](https://github.com/nrfconnect/sdk-nrf/commit/23639c79b86ecbab2be64a75ce33c7ad164fd2f0) , as you now use 192MHz, do we still need this fix?

Yes, we need it. 23639c79b86ecbab2be64a75ce33c7ad164fd2f0 fixes the PCLK192M (QSPI clock) divider. But if the HCLK128M (CPU clock) divider is not set properly, only a related error log message is issued and the requested QSPI operation fails. Unless the workaround is disabled.

2024-03-26 11:15 UTC, sachinthegreen approved these changes

2024-03-26 13:28 UTC, krish2718 commented
PR https://github.com/nrfconnect/sdk-nrf/pull/14529 cherry-picked this commit.

2024-03-26 13:28 UTC, closed without merging