doc: cracen: Document that DRIVER_CRACEN must be enabled sometimes
nrfconnect/sdk-nrf pull request #14612
Opened 2024-03-22 11:37 UTC by SebastianBoe

Document that on nRF54L Series devices CRACEN is the only source of entropy, so disabling CONFIG_PSA_CRYPTO_DRIVER_CRACEN is not possible when the Zephyr entropy driver has been enabled.

2024-03-22 11:42 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14612/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14612/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-03-22 12:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14612
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-03-22 14:23 UTC, vili-nordic approved these changes

2024-03-25 07:21 UTC, mia-ko requested changes

2024-03-25 07:21 UTC, mia-ko commented on doc/nrf/libraries/security/nrf_security/doc/drivers.rst
> +
```suggestion
.. note::
   On nRF54L Series devices, CRACEN is the only source of entropy.
   Therefore, it is not possible to disable the :kconfig:option:`CONFIG_PSA_CRYPTO_DRIVER_CRACEN` option when the Zephyr entropy driver is enabled.

```

2024-04-09 05:15 UTC, mia-ko approved these changes

2024-04-09 08:59 UTC, merged