scripts: cert_tool: Add argument to set common-name
nrfconnect/sdk-nrf pull request #14645
Opened 2024-03-26 16:10 UTC by simensrostad

Add argument to set common-name

2024-03-26 16:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14645/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14645/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14645/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-23 06:16 UTC, shanthanordic approved these changes

2024-04-23 07:40 UTC, gregersrygg requested changes
As discussed offline, we should probably have a separate command to create server certificates instead of re-using the root ca command. The attributes should be different for a server than a root ca.

2024-04-24 10:18 UTC, jangalda-nsc commented
@shanthanordic I have no experience with changed file. So, I do not think I'm the best reviewer.

2024-04-24 10:27 UTC, closed without merging