Add nRF54L15 support in BLE samples
nrfconnect/sdk-nrf pull request #14640
Opened 2024-03-26 13:31 UTC by maje-emb

Adds support for samples: 
- central_hids
- peripheral_hids_mouse
- peripheral_hids_keyboard
- central_and_peripheral_hr
- peripheral_lbs

2024-03-26 13:35 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14640/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14640/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-nfc | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14640/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-27 06:22 UTC, peknis requested changes

2024-03-27 06:22 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   If you want to pair the device with a computer running MacOS, set :kconfig:option:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_AUTHEN` to ``Y``.
```suggestion
   If you want to pair the device with a computer running MacOS, set the :kconfig:option:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_AUTHEN` Kconfig option to ``y``.
```

2024-03-27 08:59 UTC, maje-emb commented on samples/bluetooth/central_hids/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
> +/*
Good point.

2024-03-27 09:25 UTC, peknis approved these changes

2024-03-27 14:40 UTC, KAGA164 approved these changes

2024-04-05 11:04 UTC, grochu approved these changes

2024-04-09 06:01 UTC, merged