bluetooth: controller: deselect BT_CTLR_ECDH
nrfconnect/sdk-nrf pull request #14676
Opened 2024-03-30 11:25 UTC by olivier-le-sage

It's rarely, if ever, used by the app. It also uses considerable memory. Places that need it can still select it.

2024-03-30 11:36 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14676/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14676/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14676/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-03-30 12:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14676
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-02 06:49 UTC, rugeGerritsen requested changes
This is a change that will change behavior for many applications. It will stop using the oberon library for ECDH by default. 

Instead of applying this change we should rather make the host use that library. That will also improve the performance for nRF53 where the cryptocell is located in the application core.

2024-04-02 07:04 UTC, jori-nordic commented
I think @seko-nordic hinted about moving all crypto to libs in the host/app core. Do you still have plans for this Sergey?

2024-04-02 07:45 UTC, seko-nordic commented
> I think @seko-nordic hinted about moving all crypto to libs in the host/app core. Do you still have plans for this Sergey?

Ideally, host should use HW accelerated crypto. SW crypto back-end should be used only with variants where HW crypto is not available (ECDH on nRF52820 for example).
For ECDH, I think in the end we should remove from SDC fake BT_HCI_OP_LE_P256_PUBLIC_KEY, BT_HCI_OP_LE_GENERATE_DHKEY, BT_HCI_OP_LE_GENERATE_DHKEY_V2 commands and its dependencies. I'm not sure if we need to move any libs for that, I though there should be support in app core already?
Anyone wants to give it a try?

2024-06-16 00:30 UTC, closed without merging