samples: cellular: nrf_cloud_multi_service: Fix Wi-Fi scanning
nrfconnect/sdk-nrf pull request #14680
Opened 2024-04-02 00:44 UTC by plskeggs

We need to allocate enough IPv4 and IPv6 address structures so the nrf91_socket always gets a slot, regardless of order that it and nordic_wlan0 are placed in the net_if array.

Jira: IRIS-8626

2024-04-02 00:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14680/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14680/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14680/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-02 01:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14680
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-02 17:37 UTC, glarsennordic approved these changes

2024-04-02 17:52 UTC, jayteemo approved these changes

2024-04-03 20:14 UTC, plskeggs commented
@b-gent can you get someone to review the docs on this? Thanks.

2024-04-09 07:41 UTC, peknis requested changes

2024-04-09 07:41 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed issue when using Wi-Fi scanning with the nrf91xx that prevented network connectivity.
```suggestion
  * Fixed issue when using Wi-Fi scanning with the nRF91xx that prevented network connectivity.
```

2024-04-10 05:27 UTC, peknis requested changes

2024-04-11 05:33 UTC, peknis approved these changes

2024-04-12 06:42 UTC, merged