samples: matter: Improve Matter memory profiling.
nrfconnect/sdk-nrf pull request #14700
Opened 2024-04-03 09:39 UTC by ArekBalysNordic

Enabled NCS_SAMPLE_MATTER_SETTINGS_SHELL if CHIP_MEMORY_PROFILING is set.
Disabled SHELL_MINIMAL when the memory profiling is enabled.

2024-04-03 09:40 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/70be330c014ae2067be1f641b365c19c2a6e4680 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/418 | [nrfconnect/sdk-connectedhomeip#418/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/418/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-03 09:41 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14700/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14700/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14700/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-03 10:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14700
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-03 13:55 UTC, doublemis1 commented on samples/matter/common/src/Kconfig
> +	default y if CHIP_MEMORY_PROFILING
Can we enable this CHIP_MEMORY_PROFILING  CONFIG in the sample yamls?
in Light Bulb sample:
```
sample.matter.light_bulb.memory_profiling:
    build_only: true
    extra_args: CONFIG_CHIP_MEMORY_PROFILING=y
    platform_allow: nrf52840dk_nrf52840 nrf5340dk_nrf5340_cpuapp nrf7002dk_nrf5340_cpuapp
    integration_platforms:
      - nrf52840dk_nrf52840
      - nrf5340dk_nrf5340_cpuapp
      - nrf7002dk_nrf5340_cpuapp
```
and Bridge Simulated:
```
applications.matter_bridge.memory_profiling:
    build_only: true
    extra_args: CONFIG_BRIDGE_GENERIC_SWITCH_BRIDGED_DEVICE=n
      CONFIG_BRIDGE_ONOFF_LIGHT_SWITCH_BRIDGED_DEVICE=y
      CONFIG_CHIP_MEMORY_PROFILING=y
    integration_platforms:
      - nrf7002dk_nrf5340_cpuapp
    platform_allow: nrf7002dk_nrf5340_cpuapp
```
then we need to add them to the `quarantine_integration.yaml` in scripts folder

2024-04-03 13:56 UTC, doublemis1 requested changes
Please add configuration to sample yamls based on the comment

2024-04-03 14:10 UTC, LuDuda approved these changes

2024-04-04 08:01 UTC, ArekBalysNordic commented
> Please add configuration to sample yamls based on the comment

@doublemis1 Done, please verify, especially the `quarantine_integration.yaml` file.

2024-04-04 09:09 UTC, doublemis1 approved these changes
LGTM!

2024-04-04 10:19 UTC, merged