Introduce a config option for station mode
nrfconnect/sdk-nrf pull request #14718
Opened 2024-04-04 07:46 UTC by rado17

Introduce a config option for station mode which can be used to include station-only features during compile time.

2024-04-04 07:46 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hostap | https://github.com/nrfconnect/sdk-hostap/commit/51873bba9cf3e462939c67e3ee6638e96e1a80b4 (main) | https://github.com/nrfconnect/sdk-hostap/pull/164 | [nrfconnect/sdk-hostap#164/files](https://github.com/nrfconnect/sdk-hostap/pull/164/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-04 07:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14718/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14718/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |

**test-sdk-wifi:** added because there was no .github/test-spec.yml in 'hostap'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14718/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-04 08:26 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14718
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-04 09:39 UTC, sachinthegreen requested changes
Can we include the Jira reference in the commits please?

2024-05-28 13:32 UTC, rado17 commented on modules/hostap/Kconfig
> +	depends on !WPA_SUPP_AP
We can add a config option to (say `ENABLE_DHCP_CLIENT`), and define it only for STA mode at build time. WDYT?

2024-05-28 13:35 UTC, krish2718 commented on modules/hostap/Kconfig
> +	depends on !WPA_SUPP_AP
That again brings in the question, how do you do STA mode in WPA supp? Anyways, and in upstream we are talking abut concurrent STA + AP modes as well. So, yes, the solution should be per-iface DHCP Client/Static IP/DHCP server option.

2024-05-30 07:31 UTC, rado17 commented on modules/hostap/Kconfig
> +	depends on !WPA_SUPP_AP
Added checks specific to interface acting as STA.

2024-05-31 07:29 UTC, sachinthegreen approved these changes

2024-05-31 07:30 UTC, VivekUppunda approved these changes

2024-06-07 13:36 UTC, krish2718 commented
manifest is updated in https://github.com/nrfconnect/sdk-nrf/pull/15810

2024-06-07 13:36 UTC, closed without merging