Remove bt ll acs nrf53
nrfconnect/sdk-nrf pull request #14737
Opened 2024-04-05 12:14 UTC by koffes

Need to add doc before merging.

2024-04-05 12:16 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14737/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14737/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14737/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-05 13:30 UTC, koffes commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
@greg-fer, should we delete this file/folder?

2024-04-06 07:49 UTC, rick1082 approved these changes
This is a huge PR, thanks so much for the great work from everyone who contributed to Audio Controller Subsystem!

2024-04-08 06:57 UTC, greg-fer requested changes
Shouldn't this module be removed in 2.9.0 at the earliest? The controller was replaced in 2.6.0, and we have the following guideline, provided by @tejlmand and @carlescufi and matching Zephyr:

> The Deprecated status is assigned to API that has gone through all maturity levels, but is being phased out. The deprecated API will be removed in one of future releases, **no earlier than two releases after the deprecation is announced** and only when the code has transitioned to not using the deprecated API. 

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/software_maturity.html#api-deprecation

2024-04-08 06:58 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
Yes, but we need to provide redirects and ensure nothing breaks. I can take care of this after we confirm the module should be indeed removed at this point.

2024-04-08 08:14 UTC, alexsven commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
We have it confirmed that it can be removed now

2024-04-08 08:15 UTC, alexsven approved these changes

2024-04-08 08:30 UTC, greg-fer commented on doc/nrf/libraries/bin/bt_ll_acs_nrf53/CHANGELOG.rst
OK, let me work on redirects and doc removal later today.

2024-04-08 12:05 UTC, koffes commented
@Frodevan : We need a separate PR to the test system which removes the use of the CONFIG_BT_LL_ACS_NRF53 flag.

2024-04-08 14:16 UTC, greg-fer approved these changes
@koffes , added commit with doc changes.
Please keep the double entry in the changelog, as we need a mention of the library removal in both areas, but kindly apply my edit.

2024-04-08 14:16 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    This enables use of standard tools for building, configuring and DFU.
```suggestion
  * Removed the LE Audio controller for nRF5340 library.
    The only supported controller for LE Audio is :ref:`ug_ble_controller_softdevice`.
    This enables use of standard tools for building, configuring, and DFU.
```

2024-04-08 14:46 UTC, koffes commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    This enables use of standard tools for building, configuring and DFU.
Done

2024-04-09 11:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14737
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-12 10:05 UTC, merged