samples: Bluetooth: Mesh: add p2p dfu for Moonlight
nrfconnect/sdk-nrf pull request #14778
Opened 2024-04-09 12:09 UTC by alxelax

Commit adds support p2p dfu for Moonlight in CI and docs.

2024-04-09 12:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14778/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14778/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14778/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-09 12:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14778
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-09 14:30 UTC, PavelVPV commented
Release notes need to be updated.

2024-04-10 10:12 UTC, mia-ko requested changes

2024-04-10 11:34 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Support for DFU over Bluetooth Low Energy for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
* Added:
is missing...

2024-04-10 11:52 UTC, ludvigsj approved these changes

2024-04-11 08:04 UTC, PavelVPV approved these changes

2024-04-11 11:12 UTC, merged