manifest: openthread: Add new festureset option.
nrfconnect/sdk-nrf pull request #14813
Opened 2024-04-11 10:19 UTC by canisLupus1313

Commit adds new feature set option to nrfxlib and modifies RCP sample accordingly.

2024-04-11 10:20 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/39c4313f419d49a2f4d7fd14ad34da2b7ed8888e (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1292 | [nrfconnect/sdk-nrfxlib#1292/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1292/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-11 10:22 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14813/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14813/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14813/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-11 10:45 UTC, canisLupus1313 commented
> Please update docs:
> 
> * `configuring.rst`
> * `prebuilt_libs.rst`
> * Sample's `README.rst`

@edmont  Should be fine now.

2024-04-11 10:51 UTC, maciejbaczmanski approved these changes

2024-04-11 10:53 UTC, wiba-nordic commented
Will take a look when the doc build finishes.

2024-04-11 11:45 UTC, wiba-nordic commented
The doc build seems to be broken by the libraries table:
![obrazek](https://github.com/nrfconnect/sdk-nrf/assets/83582261/d03f0c85-3623-42c4-b04f-6a675708aa08)

2024-04-11 12:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14813
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-11 13:34 UTC, canisLupus1313 commented
@wiba-nordic The documentation has been built properly now.

2024-04-11 13:37 UTC, edmont approved these changes

2024-04-12 06:05 UTC, wiba-nordic requested changes

2024-04-12 06:05 UTC, wiba-nordic commented on samples/openthread/coprocessor/README.rst
Are Lines 93 - 95 still correct? I think they are, since they tell the user to check and configure, but just making sure.

There's also an extra `:` at the end of Line 163 you could remove while the file is open.

2024-04-12 06:30 UTC, canisLupus1313 commented on samples/openthread/coprocessor/README.rst
> Are Lines 93 - 95 still correct? I think they are, since they tell the user to check and configure, but just making sure.

Yes You still need to use `CONFIG_OPENTHREAD_COPROCESSOR_RCP`. This is separate issue in Kconfig. That we will address later.

2024-04-12 06:30 UTC, canisLupus1313 commented on doc/nrf/protocols/thread/prebuilt_libs.rst
fixed

2024-04-12 06:31 UTC, canisLupus1313 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added new Feature set option :kconfig:option:`CONFIG_OPENTHREAD_NORDIC_LIBRARY_RCP`
fixed

2024-04-12 06:31 UTC, canisLupus1313 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
>  * Initial experimental support for nRF54L15 for Thread CLI and Co-processor samples.
fixed

2024-04-12 06:31 UTC, canisLupus1313 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Moved coprocessor sample from MASTER featureset variant to RCP.
fixed

2024-04-12 06:35 UTC, canisLupus1313 commented on doc/nrf/protocols/thread/prebuilt_libs.rst
I have added description for   however this sentence:
>   This option is the default for the :ref:`ot_coprocessor_sample` sample.

Is not correct so I lef it out.

2024-04-12 06:40 UTC, wiba-nordic requested changes

2024-04-12 06:40 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Changed the default :ref:`feature set <thread_ug_feature_sets>` from Master to RCP.
```suggestion
* :ref:`ot_coprocessor_sample` sample:

  * Changed the default :ref:`feature set <thread_ug_feature_sets>` from Master to RCP.
```
That's going to break the doc build.

2024-04-12 06:52 UTC, wiba-nordic approved these changes

2024-04-16 13:04 UTC, merged