Applications: nrf5340_audio: Support for no channel alloc
nrfconnect/sdk-nrf pull request #14810
Opened 2024-04-11 10:02 UTC by koffes

If codec chan alloc returns -ENODATA channel allocation is set to 0. OCT-2982

2024-04-11 10:04 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14810/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14810/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14810/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-11 11:53 UTC, alexsven requested changes

2024-04-11 11:53 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
> +			chan_allocation = 0;
Add a comment that we are reverting to mono if no Channel_allocation is available

2024-04-11 11:53 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
> +		audio_codec_info[bis->index - 1].chan_allocation, bis->index);
Remove

2024-04-11 11:53 UTC, alexsven commented on applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
> +		codec_info->chan_allocation = 0;
Add a comment that we are reverting to mono if no Channel_allocation is available

2024-04-12 08:24 UTC, alexsven approved these changes

2024-04-12 08:53 UTC, andvib approved these changes

2024-04-12 12:42 UTC, merged