doc: move getting started to evaluation guides
nrfconnect/sdk-nrf pull request #14844
Opened 2024-04-12 10:05 UTC by greg-fer

Moved device getting started guides to evaluation guides above installation. NCSDK-22328.

2024-04-15 06:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14844
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-30 08:54 UTC, OisinFitz approved these changes

2024-04-30 10:35 UTC, FrancescoSer approved these changes

2024-04-30 11:43 UTC, divipillai approved these changes
As discussed offline with @greg-fer : Please note the whole section of "Building and debugging" of the nRF70 GSG will be moved to the developing with guide of the nRF70 Series, in a separate PR, as these require NCS installation and is part of the development process.

2024-05-02 07:20 UTC, annwoj approved these changes

2024-05-02 07:37 UTC, greg-fer commented
Image size warning will be handled in https://nordicsemi.atlassian.net/browse/NCSDK-27322

2024-05-02 07:50 UTC, umapraseeda requested changes
Don't we need the new redirects for the gsg added in the redirects.py file?

2024-05-02 07:58 UTC, greg-fer commented
> Don't we need the new redirects for the gsg added in the redirects.py file?

Updated.

2024-05-02 08:25 UTC, umapraseeda commented on doc/_utils/redirects.py
> +    ("device_guides/working_with_nrf/nrf53/nrf5340", "gsg_guides/nrf5340_gs"),
```suggestion
    ("device_guides/working_with_nrf/nrf53/nrf5340_gs", "gsg_guides/nrf5340_gs"),
```

2024-05-02 15:06 UTC, umapraseeda approved these changes

2024-05-02 15:06 UTC, umapraseeda commented
@gmarull, could we get this merged by ignoring the compliance error on image size? These are already existing images and were just moved around.

2024-05-03 11:45 UTC, merged