doc: Doc fixes for Zoomin
nrfconnect/sdk-nrf pull request #14859
Opened 2024-04-15 07:57 UTC by umapraseeda

Doc fixes for Zoomin

2024-05-08 10:04 UTC, b-gent requested changes

2024-05-08 10:04 UTC, b-gent commented on doc/nrf/dev_model_and_contributions/documentation/structure.rst
> +You can navigate these documentation sets by using the Toc tree on the left.
```suggestion
You can navigate these documentation sets by using the table of contents on the left.
```

2024-05-13 08:26 UTC, umapraseeda commented on doc/nrf/dev_model_and_contributions/documentation/structure.rst
> +You can navigate these documentation sets by using the Toc tree on the left.
Fixed

2024-05-13 09:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14859
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-13 09:39 UTC, richabp approved these changes

2024-05-13 10:34 UTC, b-gent approved these changes

2024-05-14 16:16 UTC, merged