applications: asset_tracker_v2: Add check for GNSS heading validity
nrfconnect/sdk-nrf pull request #14850
Opened 2024-04-12 12:24 UTC by tokangas

Only accurate enough GNSS heading is considered valid and sent to the nRF Cloud.

Added accuracy values for heading, altitude and speed into internal data structures. Aligned naming and order of the fields in the data structures.

2024-04-12 12:25 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14850/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14850/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14850/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-12 12:29 UTC, jtguggedal commented
Could add a release note for this

2024-04-12 12:34 UTC, tokangas commented
This originates from a question from a customer. Currently, the heading from GNSS is always sent to the cloud. Also, the heading accuracy value from GNSS is not used. When the device is not moving or is moving very slowly, GNSS can not determine the orientation of the device and the heading accuracy is usually set to +-180 deg, i.e. the heading is unknown. In such cases, the heading should not be used. This PR modifies the implementation so, that when heading is considered too inaccurate, the heading is not encoded into the data sent to the nRF Cloud. Another option would be to send both heading and heading accuracy values to the cloud. 

I did not do a similar modification for `json_common.c`, it could be added as well.

The PR also adds accuracy values for altitude and speed in the data structures. Those are not used at the moment, but we could have similar functionality at least for the speed.

2024-04-12 13:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14850
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-12 14:05 UTC, trantanen commented
I don't think I have any new comments that haven't been mentioned. You should add similar changes to `json_common.c` and update unit tests.

2024-04-16 07:05 UTC, peknis requested changes

2024-04-16 07:05 UTC, peknis commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + *  cloud if it's accurate enough.
```suggestion
 *  cloud if it is accurate enough.
```

2024-04-16 07:05 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * GNSS heading is only sent to the cloud when it's considered accurate enough.
```suggestion
  * GNSS heading is only sent to the cloud when it is considered accurate enough.
```

2024-04-16 07:13 UTC, tokangas commented
@jtguggedal @trantanen I've now done all requested changes.

2024-04-16 07:16 UTC, peknis approved these changes

2024-04-16 11:38 UTC, trantanen approved these changes

2024-04-16 11:56 UTC, merged