manifest: sdk-zephyr & sdk-mcuboot
nrfconnect/sdk-nrf pull request #14875
Opened 2024-04-16 07:19 UTC by nvlsianpu

Configuration for MCUboot and smp_svr which
allows to use nRF54L15pdk external flash as location for the secondary partition.

2024-04-16 07:20 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| mcuboot | https://github.com/nrfconnect/sdk-mcuboot/commit/86af2de75205ec5f2c846a2393934360de22fde4 (main) | https://github.com/nrfconnect/sdk-mcuboot/pull/307 | [nrfconnect/sdk-mcuboot#307/files](https://github.com/nrfconnect/sdk-mcuboot/pull/307/files) |
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/3ae75850e43503aecbe481bfec7a51872e2aa946 | https://github.com/nrfconnect/sdk-zephyr/pull/1636 | [nrfconnect/sdk-zephyr#1636/files](https://github.com/nrfconnect/sdk-zephyr/pull/1636/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-16 07:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14875
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-07 14:23 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14875/4/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14875/4/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14875/4/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-20 13:51 UTC, michalek-no approved these changes

2024-05-21 13:07 UTC, sigvartmh approved these changes

2024-05-21 14:00 UTC, gchwier requested changes
`${ZEPHYR_BASE}/scripts/twister -vv -T ${ZEPHYR_BASE}/samples/subsys/mgmt/mcumgr/smp_svr -s sample.mcumgr.smp_svr.bt.nrf54l15pdk.ext_flash.pure_dts -G`
does not work.
See comment on sdk-zephyr PR

2024-05-21 14:40 UTC, gchwier approved these changes

2024-05-31 15:08 UTC, closed without merging