ci: quarantine `sample.matter.light_bulb.memory_profiling` for MacOS
nrfconnect/sdk-nrf pull request #14888
Opened 2024-04-16 12:40 UTC by thst-nordic

This sample overflows FLASH region.  The Matter team will investigate 
﻿
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>

2024-04-16 13:01 UTC, doublemis1 requested changes
Ticket need to be updated

2024-04-18 11:05 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14888/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14888/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14888/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-18 15:10 UTC, LuDuda approved these changes

2024-04-22 06:30 UTC, shanthanordic approved these changes

2024-04-22 11:36 UTC, merged