samples: peripheral: 802154_phy_test: support nRF54L15
nrfconnect/sdk-nrf pull request #14884
Opened 2024-04-16 09:24 UTC by jciupis

Enable 802154_phy_test sample for nRF54L15.

2024-04-16 09:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14884/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14884/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14884/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-16 09:49 UTC, dawidprzybylo approved these changes

2024-04-16 10:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14884
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-16 11:47 UTC, ankuns commented
What about the table here? https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/peripheral/802154_phy_test/README.html#requirements

what about changelog entry?
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/releases/release-notes-changelog.html#peripheral-samples

2024-04-16 12:25 UTC, jciupis commented
> What about the table here? https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/peripheral/802154_phy_test/README.html#requirements

The contents of this table are generated automatically from the sample.yaml file. If you follow the documentation link posted above, the table already contains entry for nRF54L15 in this PR.

> what about changelog entry?
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/releases/release-notes-changelog.html#peripheral-samples

Added just now, to be checked if the generated documentation is correctly formatted.

2024-04-16 13:12 UTC, ankuns approved these changes

2024-04-17 10:21 UTC, FrancescoSer approved these changes
Approving but please implement the small suggestion

2024-04-17 10:21 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```suggestion
  * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```

2024-04-17 10:24 UTC, jciupis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
Thank you for the suggestion, done.

2024-04-17 10:33 UTC, annwoj requested changes

2024-04-17 10:33 UTC, annwoj commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added support for the :ref:`zephyr:nrf54l15pdk_nrf54l15` board.
```suggestion
  * Added support for the :ref:`nRF54L15 PDK <ug_nrf54l15_gs>` board.
```
Please update the link to redirect to our getting started page

2024-04-17 12:47 UTC, annwoj approved these changes

2024-04-18 05:50 UTC, merged