[nrf noup] manifest: update zephyr - HWFC for nrf54l15
nrfconnect/sdk-nrf pull request #14913
Opened 2024-04-17 12:13 UTC by nordic-piks

Define RTS and CTS pins and enable HWFC for uart connected to debugger.

2024-04-17 12:14 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/700870d10917960e4799926b864189d755d95f83 (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1646 | [nrfconnect/sdk-zephyr#1646/files](https://github.com/nrfconnect/sdk-zephyr/pull/1646/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-17 12:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14913/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14913/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14913/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-17 12:22 UTC, nordic-segl approved these changes

2024-04-17 12:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14913
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-17 15:18 UTC, gmarull requested changes
tuned commit merged in sdk-zephyr, not for hemv2, so needs revert.

2024-04-18 09:43 UTC, nordic-piks commented
> tuned commit merged in sdk-zephyr, not for hwmv2, so needs revert.

Please review:
https://github.com/nrfconnect/sdk-zephyr/pull/1650
This is commit history fix only.
There is no possible to use upstream cherry-pick, so there is noup.

2024-04-18 12:38 UTC, nordic-piks commented
> Please drop `[nrf noup]` from the commit title, we only use sauce tags in forks.

Done.

2024-04-18 12:41 UTC, nordic-segl approved these changes

2024-04-19 07:09 UTC, rlubos approved these changes

2024-04-19 08:00 UTC, gmarull approved these changes

2024-04-19 08:00 UTC, merged