matter: Increase default retry interval for Thread
nrfconnect/sdk-nrf pull request #14936
Opened 2024-04-18 13:36 UTC by Damian-Nordic

The current 800ms is not enough in real setups, where Thread routers must serve as intermediate hops for many parallel conversations. Bump this to 2s.

2024-04-18 13:37 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/aaf689381ccc012aee4cc8a41ce232f65f0baa9d (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/428 | [nrfconnect/sdk-connectedhomeip#428/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/428/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-18 13:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14936/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14936/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14936/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-18 14:04 UTC, LuDuda approved these changes

2024-04-19 05:20 UTC, kkasperczyk-no approved these changes
Would you mind adding release note entry?

2024-04-19 07:24 UTC, kkasperczyk-no approved these changes

2024-04-19 07:56 UTC, wiba-nordic requested changes

2024-04-19 07:56 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated default MRP retry intervals for Thread devices to 2s to reduce the number of spurious retransmissions in Thread networks.
```suggestion
* Updated default MRP retry intervals for Thread devices to two seconds to reduce the number of spurious retransmissions in Thread networks.
```

2024-04-19 08:07 UTC, wiba-nordic approved these changes

2024-04-19 10:37 UTC, merged