No pm dumb way
nrfconnect/sdk-nrf pull request #14940
Opened 2024-04-18 15:07 UTC by de-nordic

2024-04-18 15:08 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/22e2d8781ef57c215b49539ae1b16fcd42b331cf | https://github.com/nrfconnect/sdk-zephyr/pull/1652 | [nrfconnect/sdk-zephyr#1652/files](https://github.com/nrfconnect/sdk-zephyr/pull/1652/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-23 15:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14940
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-24 07:44 UTC, nvlsianpu requested changes
Can you clarify the PR description: Is this patch for building multiple images using sysbuild (like the app + mcuboot)?

2024-04-24 07:44 UTC, nvlsianpu commented on subsys/partition_manager/Kconfig
> +config PARTITION_MANAGER
misleading name: maybe `STATR_PROJECT_WITH_PARTITION_MANAGER`

2024-04-24 07:44 UTC, nvlsianpu commented on subsys/partition_manager/Kconfig
> +	bool "Partition manager"
"Partition Manager pre-selected [DO NOT EDIT]"

2024-04-24 07:44 UTC, nvlsianpu commented on subsys/partition_manager/Kconfig
> +config PARTITION_MANAGER
or `PRE_SELECT_PARTITION_MANAGER`

2024-04-25 11:01 UTC, michalek-no commented on subsys/partition_manager/Kconfig
> +	  When set to n it directs all partition references to DTS and
```suggestion
	  When set to 'n' it directs all partition references to DTS and
```

2024-04-25 13:11 UTC, nvlsianpu approved these changes

2024-04-29 08:42 UTC, greg-fer requested changes
@nvlsianpu , what about documentation update for this? I think doc updates are needed under both DFU and Partition Manager doc sections (@kittydepa and @FrancescoSer ).

2024-04-29 08:50 UTC, nordicjm reviewed
I don't see the purpose in this, you should just use `-DCONFIG_PARTITION_MANAGER_ENABLED=n` and that should disable partition manager, no additional symbol is needed

2024-04-29 08:52 UTC, greg-fer reviewed
@bencefr , @kylebonnici , FYI, this might impact the VSC extension IDE.

2024-04-29 08:52 UTC, nordicjm requested changes
and this breaks sysbuild support

2024-04-29 09:18 UTC, tejlmand requested changes
Looks very wrong to me.

Can you explain why `-DSB_CONFIG_PARTITION_MANAGER=n` is not enough to disable partition manager when using sysbuild ?

2024-04-29 14:16 UTC, nordicjm commented
> > Looks very wrong to me.
> > Can you explain why `-DSB_CONFIG_PARTITION_MANAGER=n` is not enough to disable partition manager when using sysbuild ?
> 
> This disables partition manager when sysbuild is not enabled. Goal is to be able to build anything, as single project, even if CONFIG_BOOTLOADER_MCUBOOT=y; currently if you want to build something for MCUboot the Partition Manager and Multi-imaga kicks in, because cmakes have been modified, for sdk-nrf, to always do so, without override.

Use sysbuild where this feature is natively supported, child/parent image is deprecated, when this upmerge has finished all support for it in applications/samples/tests will be removed and it will remain only to prevent breaking support for customer applications, and will be fully removed in a couple of releases time

2024-04-29 14:21 UTC, nvlsianpu commented
@de-nordic I think building stuff (MCUboot + app + ...) using sysbuild & -DSB_CONFIG_PARTITION_MANAGER=n is what we want as target state.

2024-05-03 12:34 UTC, de-nordic commented
> @de-nordic I think building stuff (MCUboot + app + ...) using sysbuild & -DSB_CONFIG_PARTITION_MANAGER=n is what we want as target state.

Ok, so this PR makes no sense.

What about user cases where users only want to build application? Customers were asking why they have to build MCUboot while rebuilding the application.

2024-05-03 13:15 UTC, nordicjm commented
> > @de-nordic I think building stuff (MCUboot + app + ...) using sysbuild & -DSB_CONFIG_PARTITION_MANAGER=n is what we want as target state.
> 
> Ok, so this PR makes no sense.
> 
> What about user cases where users only want to build application? Customers were asking why they have to build MCUboot while rebuilding the application.

Not supported, if you mean building application which is booted from mcuboot, as the mcuboot parts of the static PM file would be dropped (this is how it's always been in PM). If you just mean building the application without mcuboot and without mcuboot support, that's fine, just do not enable mcuboot in sysbuild

2024-05-16 15:33 UTC, de-nordic commented
Seems to be not needed in the end.

2024-05-16 15:33 UTC, closed without merging