doc: Added features of nRF54H20 doc
nrfconnect/sdk-nrf pull request #14948
Opened 2024-04-19 08:05 UTC by FrancescoSer

Added features of nRF54H20 doc.

2024-04-19 08:14 UTC, FrancescoSer commented
@annwoj @kittydepa @wiba-nordic Just an early draft of how a features of page could look like (reusing existing content). Feel free to propose suggestions (I'm thinking of splitting this in two and remove a pair of chapters).

2024-04-19 11:04 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +It achieves this by integrating two Arm Cortex-M33 processors clocked up to 320 MHz, 2 MB of MRAM as non-volatile memory, 1 MB of RAM, a 10 dBm TX power multiprotocol radio, and state-of-the-art secu
```suggestion
It achieves this by integrating two Arm® Cortex® -M33 processors clocked up to 320 MHz, 2 MB of MRAM as non-volatile memory, 1 MB of RAM, a 10 dBm TX power multiprotocol radio, and state-of-the-art security features, in an asymmetric multi-core system, in which the different CPUs are optimized for various types of workloads.
```

2024-04-19 11:05 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +Compared to earlier devices, external interfaces have also been improved to support significantly higher data rates (up to 40x for USB and up to 8x for external memory).
```suggestion
Compared to earlier devices, external interfaces have also been improved to support significantly higher data rates (up to 40 times greater for USB and up to 8 times greater for external memory).
```

2024-04-19 11:06 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +############################
Also to be consistent with other "Features" pages - if this suggestion is accepted, then please apply throughout the doc.

2024-04-19 11:07 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +nRF54H20’s excellent energy efficiency enables smaller batteries to be utilized, further reducing both the design size and cost.
```suggestion
The nRF54H20 SoC’s excellent energy efficiency enables smaller batteries to be utilized, further reducing both the design size and cost.
```

2024-04-19 11:08 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +Security is key
Maybe just me, but I think this title isn't so descriptive? Maybe something like:

```suggestion
Additional security features
```
or 
```suggestion
Improved security design
```

2024-04-19 11:08 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +nRF54H20 provides security functionality as services, implemented centrally in the Secure Domain.
```suggestion
nRF54H20 SoC provides security functionality as services, implemented centrally in the Secure Domain.
```

2024-04-19 11:11 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +In the nRF54H20 SoC, we are using two different types of CPUs: Arm Cortex-M33, and a RISC-V-compatible CPU designed by Nordic Semiconductor called VPR (pronounced “Viper”).
```suggestion
In the nRF54H20 SoC, there are two different types of CPUs: Arm Cortex-M33, and a RISC-V-compatible CPU designed by Nordic Semiconductor called VPR (pronounced “Viper”).
```

2024-04-19 11:11 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +One key feature of the nRF54H20 is that a lot of functionality is provided as services, implemented by Nordic-provided firmware.
```suggestion
One key feature of the nRF54H20 SoC is that a lot of functionality is provided as services, implemented by Nordic-provided firmware.
```

2024-04-19 11:12 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +This means that users access functionality through a software API rather than through a set of registers.
```suggestion
This means that you can access functionality through a software API rather than through a set of registers.
```

2024-04-19 11:12 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +It is also more flexible and updateable than with the purely hardware approach.
Perhaps we can elaborate on "purely hardware" approach?

2024-04-19 11:15 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +Based on this information, the Power Management Service automatically handles the details, deciding how registers will be retained, which parts of the device are put into what mode, and what clock si
```suggestion
Based on this information, the Power Management Service automatically handles the details such as: deciding how registers will be retained, which parts of the device are put into what mode, and what clock signals are running.
```

2024-04-19 11:18 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +Security model, assets, threats, protections
```suggestion
Security model: Assets, threats, and protections
```

2024-04-19 11:18 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +CPUs overview and features
Maybe this can be moved further up in the doc, perhaps even as the first subheading

2024-04-19 11:20 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +These services manage Secure Boot, cryptographic operations, key management, and firmware updates.
```suggestion
These services manage the following:

* Secure Boot
* Cryptographic operations
* Key management
* Firmware updates

```

2024-04-19 11:20 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +nRF54H20 also includes tamper sensors that can detect an attack in progress and take appropriate action.
```suggestion

The nRF54H20 SoC also includes tamper sensors that can detect an attack in progress and take appropriate action.
```

2024-04-19 11:21 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +The VPR implementation has been optimized for low-power, real-time use-cases.
```suggestion
The VPR implementation has been optimized for low-power, real-time use cases.
```

2024-04-19 11:23 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +* Handle peripherals in low-power states while the main processors are in sleep mode.
Confirm if correct, otherwise disregard
```suggestion
* Handle peripherals in low-power states while the main processors are in Sleep mode.
```

2024-04-19 11:26 UTC, kittydepa commented
Provided an initial review - I am thinking if something about a new/unique DFU+booting procedure should be mentioned somewhere - I am not sure where yet/and what to write, but I can draft something and consult with you @FrancescoSer 

And perhaps some links for further reading in the beginning of the doc (as done with other series, to PS, UGs, etc.)

2024-04-22 13:37 UTC, FrancescoSer commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_features.rst
> +It is also more flexible and updateable than with the purely hardware approach.
I'll drop this

2024-04-23 06:43 UTC, wiba-nordic requested changes

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +One of the key methods used to optimize the nRF54H20 SoC for very efficient processing is to include several CPUs and optimize them for different workloads.
```suggestion
One of the key methods used to optimize the nRF54H20 SoC for very efficient processing is to include several CPUs that are optimized for different workloads.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +In the nRF54H20 SoC, there are two different types of CPUs: Arm Cortex-M33, and a RISC-V-compatible CPU designed by Nordic Semiconductor called VPR (pronounced “Viper”).
```suggestion
In the nRF54H20 SoC, there are two different types of CPUs: Arm Cortex-M33 and :term:`VPR <VPR Core>` (pronounced "Viper").
VPR are RISC-V-compatible CPUs designed by Nordic Semiconductor.

```
Note empty line to create paragraph break.

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +However, we also apply optimizations to each instance of each processor, so that CPUs are tailored to their range of tasks.
```suggestion
Each instance of each processor is also optimized so that the CPUs are tailored to their range of tasks.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +There is no centralized scheduler that assigns threads to various cores.
```suggestion
Each CPU runs its own instance of the operating system, and there is no centralized scheduler that assigns threads to various cores.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +Power management service
Should this be a subheading of System services?

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +nRF54H20 is designed to protect against logical attacks and firmware-oriented attacks, as well as physical security at the PCB or package level (for example, against voltage glitching and EMI attacks
```suggestion
The SoC is designed to protect against logical attacks and firmware-oriented attacks, as well as physical security at the PCB or package level (for example, against voltage glitching and EMI attacks).
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* Device Firmware Updates (DFU) through the Software Internet of Things (SUIT) procedure
```suggestion
* Device Firmware Updates (DFU) through the Software Update for Internet of Things (SUIT) procedure
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +This API is translated internally to messages sent to the Secure Domain through a mailbox-based interface.
```suggestion
This API is translated internally to requests that are sent to the Secure Domain through a mailbox-based interface.
```
Is the API translated, or are API calls translated?

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +The security services handle these requests, utilizing hardware accelerators and other resources, and as security is centralized in the Secure Domain, keys can be kept inside this physical area and r
```suggestion
The security services handle these requests, utilizing hardware accelerators and other resources.
Since security is centralized in the Secure Domain, keys can be kept inside this physical area and remain well-protected against attacks or breaches utilizing firmware exploits.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +==========================
```suggestion
CPUs and related features
=========================
```
Makes it more like the other headings. Also agree with Kitty that this section could probably be higher.

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* Arm Cortex M33
```suggestion
* Arm Cortex-M33
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +Arm Cortex M33
```suggestion
Arm Cortex-M33
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* Local level-1 (L1) cache, split into separate caches for data and instructions, with 16 kB each[2].
```suggestion
* Local level 1 (L1) cache, split into separate caches for data and instructions, with 16 kB each.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* Local RAM, serving as Tightly Coupled Memory (TCM), accessible without any wait states or latency.
```suggestion
* Local RAM, serving as :term:`Tightly Coupled Memory (TCM)`, accessible without any wait states or latency.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* A Memory Vector DMA (MVDMA) controller, which allows high-throughput DMA transfers between local and global memory.
Glossary has Memory-to-Memory Vector DMA. Same or different? If same, should probably be a term.

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* Two watch-dog timers (WDT), controlled by the secure and non-secure firmware, respectively.
```suggestion
* Two :term:`watchdog timers (WDT) <Watchdog timer (WDT)>`, one controlled by the secure firmware and and the other by the non-secure firmware.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +  WDTs produce a local reset, affecting only the core and not the rest of the system.
```suggestion
  The WDTs produce a local reset, affecting only the core and not the rest of the system.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +* An Interprocessor Communication Transceiver (IPCT) for communication with peripherals in other domains.
```suggestion
* An :term:`Interprocessor Communication Transceiver (IPCT)` for communication with peripherals in other domains.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +There is also a global level 2 (L2) cache.
```suggestion
These caches are 2-way set associative.

There is also a global level 2 (L2) cache.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +The VPR implementation has been optimized for low-power, real-time use cases.
```suggestion
The implementation has been optimized for low-power, real-time use cases.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +There are two user-accessible instances of VPRs in the nRF54H20 SoC: the Peripheral Processor (PPR, pronounced “Pepper”) and the Fast Lightweight Processor (FLPR, pronounced “Flipper”).
```suggestion
There are two user-accessible instances of VPRs in the nRF54H20 SoC: the :term:`Peripheral Processor (PPR, pronounced “Pepper”)` and the :term:`Fast Lightweight Processor (FLPR, pronounced “Flipper”)`.

```
Empty line to create paragraph break.

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +Dynamic Voltage and Frequency Scaling (DVFS) is a power management technique that allows adjusting the operating voltage and operating frequency of a CPU, depending on the workload.
```suggestion
:term:`Dynamic Voltage and Frequency Scaling (DVFS)` is a power management technique that allows adjusting the operating voltage and operating frequency of a CPU, depending on the workload.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +This functionality was common in high-end processors but is now viable also for MCUs.
```suggestion
This functionality is common in high-end processors but is now also viable for MCUs.
```

2024-04-23 06:43 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +In the nRF54H20 SoC, the Application Core is DVFS-enabled.
```suggestion
In the nRF54H20 SoC, the :term:`Application Core` is DVFS-enabled.
```

2024-04-29 10:28 UTC, annwoj reviewed
Adding first few suggestions for now, will re-review

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +It achieves this by integrating two Arm® Cortex®-M33 processors clocked up to 320 MHz, 2 MB of MRAM as non-volatile memory, 1 MB of RAM, a 10 dBm TX power multiprotocol radio, and state-of-the-art se
The list looks good, though I'd simplify the first sentence (line 21) to say: 

It uses an asymmetric multi-core system that optimizes different cores for various tasks by integrating the following:

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +Compared to earlier devices, external interfaces have also been improved to support significantly higher data rates (up to 40 times greater for USB and up to 8 times greater for external memory).
Not sure if saying "earlier devices" will be a good solution in future perspective. Also, that's a general comment, but should this article be so comparison-focused? Wouldn't it be better to just say, e.g.: 

```suggestion
External interfaces can support high data rates (up to 40 times greater for USB and up to 8 times greater for external memory).
```

It'd keep it more technical and less marketing-focused.
And to have a proper comparison between devices, that brings an added value, probably a table would work much better.

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +This does not come at the expense of power consumption, as both active and sleep power consumption have been improved as well.
This suggestions follows the comment above
```suggestion
This does not come at the expense of power consumption due to significantly reduced active and sleep power consumption.
```

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +It also provides a single easy-to-use development environment without having to use multiple tools from different vendors.
How about - It also comes with a single easy-to-use development environment (...)?

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +This includes all Bluetooth 5.3 features and the preparation to support upcoming Bluetooth specification versions.
Maybe "readiness to support"?

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +It also simplifies the inclusion of tamper sensors and side-channel protection without significantly increasing the cost of the device.
How about turning it into bullet points?
```suggestion
Physically separated centralized security has several advantages:

* It separates the most important security operations from the rest of the system.
  Because of this separation, there is a clear isolation layer where you interact with the secure services via well-defined APIs.
* It simplifies the inclusion of tamper sensors and side-channel protection without significantly increasing the cost of the device.
```

2024-04-29 10:28 UTC, annwoj commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +This way, you can freely select the CPU that is best suited to the various workloads that make up an application.
Line 77 and 80 essentially talk about the same thing.
```suggestion
```

2024-04-29 10:39 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +Compared to earlier devices, external interfaces have also been improved to support significantly higher data rates (up to 40 times greater for USB and up to 8 times greater for external memory).
Now that you mention, I did feel that in several places the tone was more marketing that technical documentation.

2024-04-30 08:47 UTC, kittydepa commented
> Provided an initial review - I am thinking if something about a new/unique DFU+booting procedure should be mentioned somewhere - I am not sure where yet/and what to write, but I can draft something and consult with you @FrancescoSer
> 
> And perhaps some links for further reading in the beginning of the doc (as done with other series, to PS, UGs, etc.)

Just FYI, still working on constructing the Bootloader/DFU subheading + its contents, will ping you directly @FrancescoSer when ready.

2024-05-02 09:43 UTC, kittydepa commented on doc/nrf/device_guides/working_with_nrf/nrf54h/features_nrf54h20.rst
> +If the maximum clock speed is not required, both the clock speed and voltage can be reduced, improving power efficiency.
For the bootloader/DFU section:
```
Supported bootloader and Device Firmware Update (DFU) procedures
****************************************************************

The nRF54H20 DK introduces new booting and DFU procedures: the Secure Domain (SecDom) and the Software Updates for Internet of Things (SUIT) procedure.

SecDom bootloader
=================

The nRF54H20 DK features a secure bootloader beginning with an immutable boot ROM that establishes a root-of-trust.
It initially verifies the Secure Domain (SecDom) firmware's signature.
Once verified, the SecDom, acting as the boot master, takes over to configure global resources, ensuring secure and efficient startup.
This process highlights the device's strong focus on security and effective resource management, crucial for reliable operations in sensitive applications.

For more information about the bootloader and overall booting procedure for the nRF54H20 DK, see the :ref:`ug_nrf54h20_architecture_boot` page.

SUIT DFU procedure
==================

The nRF54H20 DK supports advanced Device Firmware Update (DFU) procedures facilitated through the SUIT procedure (Nordic Semiconductor's implementation of the procedure).
SUIT employs a flexible, script-based system that allows for the customization of the installation and invocation processes.
The use of hierarchical manifest systems supports multiple CPU cores and images, providing robust management of firmware dependencies and secure, efficient updates.

The :ref:`SUIT manifests <ug_nrf54h20_suit_manifest_overview>` control every step of the DFU process: from payload fetching and installation, to validation and invocation procedures.
This setup ensures that updates are applied securely and reliably across all components of the device.
The manifests include detailed command sequences that manage the execution of updates, catering to complex multi-core architectures typical of the nRF54H20 DK.

For more information on working with SUIT for the nRF54H20 DK, refer to the :ref:`ug_nrf54h20_suit_dfu` page and its listed user guides.
For more detailed information about the SUIT DFU procedure, see the :ref:`ug_nrf54h20_suit_intro` page.

```

2024-09-16 00:33 UTC, closed without merging