manifest: update sdk-zephyr, nrf53/nrf54
nrfconnect/sdk-nrf pull request #14967
Opened 2024-04-19 13:02 UTC by martintv

Pull inn update of RC accuracy nRF devices.

2024-04-19 13:03 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/c22c9c258ce776b88dac8a917ab13f46a4c7db85 | https://github.com/nrfconnect/sdk-zephyr/pull/1657 | [nrfconnect/sdk-zephyr#1657/files](https://github.com/nrfconnect/sdk-zephyr/pull/1657/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-19 13:05 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14967/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14967/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14967/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-19 13:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14967
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-22 14:06 UTC, hermabe approved these changes

2024-04-23 05:47 UTC, greg-fer requested changes

2024-04-23 05:47 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* The default for Kconfig option :kconfig:option:`CLOCK_CONTROL_NRF_ACCURACY_PPM` has chaned from 500 to 250.
There's a typo in `chaned`, so let's make an edit to the whole line -- please apply it also to line 67.
```suggestion
* Changed the default value for the Kconfig option :kconfig:option:`CLOCK_CONTROL_NRF_ACCURACY_PPM` from 500 to 250.
```

2024-04-23 07:19 UTC, greg-fer approved these changes

2024-04-25 07:39 UTC, merged