trusted_storage: Add Kconfig for custom storage backend
nrfconnect/sdk-nrf pull request #14973
Opened 2024-04-19 14:08 UTC by mswarowsky

Add Kconfig option CONFIG_TRUSTED_STORAGE_STORAGE_BACKEND_CUSTOM This allows to use the non-default Storage backend that uses Settings + NVS

2024-04-19 14:09 UTC, vili-nordic approved these changes

2024-04-19 14:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14973
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-22 06:20 UTC, mia-ko requested changes

2024-04-22 06:20 UTC, mia-ko commented on subsys/trusted_storage/Kconfig
> +	  Use a custom made backend to store data on non-volatile memory.
```suggestion
	  Use a custom-made backend to store data in the non-volatile memory.
```

2024-04-22 06:20 UTC, mia-ko commented on doc/nrf/libraries/security/trusted_storage.rst
> +Alternatively, you can use a custom storage backend by setting the Kconfig option :kconfig:option:`CONFIG_TRUSTED_STORAGE_STORAGE_BACKEND_CUSTOM`.
```suggestion
If this Kconfig option is set, the configuration defaults to the :kconfig:option:`CONFIG_TRUSTED_STORAGE_STORAGE_BACKEND_SETTINGS` option to use Zephyr's settings subsystem.
Alternatively, you can use a custom storage backend by setting the Kconfig option :kconfig:option:`CONFIG_TRUSTED_STORAGE_STORAGE_BACKEND_CUSTOM`.
```

2024-04-22 06:21 UTC, mia-ko reviewed
Also remember to update the changelog with this new Kconfig :)

2024-04-22 08:19 UTC, mswarowsky commented
> Also remember to update the changelog with this new Kconfig :)

Good point can you check if I added it at the right location ( Security libraries)

2024-04-22 11:30 UTC, mia-ko requested changes

2024-04-22 11:32 UTC, mia-ko commented
> > Also remember to update the changelog with this new Kconfig :)
> 
> Good point can you check if I added it at the right location ( Security libraries)

Right location, but it should have its own bullet point, the trusted storage library :) Added a small change suggestion.

2024-04-22 12:20 UTC, mia-ko approved these changes

2024-04-22 12:55 UTC, merged