NCSDK-26629: Enable SUIT unit tests
nrfconnect/sdk-nrf pull request #14982
Opened 2024-04-22 09:33 UTC by tomchy

2024-04-22 09:34 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| suit-processor | https://github.com/nrfconnect/suit-processor/commit/869d22a795c4219f8e5019d44e1fbfdeadc251ab | https://github.com/nrfconnect/suit-processor/commit/5603911b75f037dc3822fd95542c3435c0bf812d (ncs) | [nrfconnect/suit-processor@869d22a7..5603911b](https://github.com/nrfconnect/suit-processor/compare/869d22a795c4219f8e5019d44e1fbfdeadc251ab..5603911b75f037dc3822fd95542c3435c0bf812d) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-04-22 09:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14982/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14982/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-sdk-find-my | X | | |
| test-sdk-mcuboot | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-14982/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-22 10:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-14982
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-23 08:01 UTC, adsz-nordic approved these changes

2024-04-23 08:08 UTC, ahasztag approved these changes

2024-04-23 09:06 UTC, rlubos commented
@nordicjm PTAL at the testcase files.

2024-04-23 09:12 UTC, nordicjm requested changes
https://github.com/nrfconnect/sdk-nrf/blob/933a880aa58c943ad84eb6a9b6c98789228d90a0/tests/subsys/suit/unit/app_specific/cmake/test_template.cmake needs updating to use proper variables like `${ZEPHYR_ZCBOR_MODULE_DIR}` i.e. that variable is already defined by the build system, remove it, then use the proper module names for the suit location instead of basing it off ZEPHYR_BASE and same with ncs

2024-04-23 09:41 UTC, nordicjm approved these changes

2024-04-23 10:27 UTC, merged