Wpa psk support
nrfconnect/sdk-nrf pull request #15007
Opened 2024-04-23 06:46 UTC by kapbh

2024-04-23 06:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15007/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15007/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15007/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-23 06:55 UTC, sachinthegreen approved these changes

2024-04-23 08:51 UTC, VivekUppunda approved these changes

2024-04-23 08:52 UTC, sachinthegreen reviewed
This might need a `Changelog` entry.

2024-04-23 08:55 UTC, krish2718 approved these changes

2024-04-23 09:45 UTC, richabp reviewed
Add a Changelog entry, if required.

2024-04-24 08:55 UTC, richabp requested changes

2024-04-24 08:55 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added support for the ``WPA-PSK`` security mode to the wifi_mgmt_ext.
```suggestion
  * Added support for the ``WPA-PSK`` security mode to the ``wifi_mgmt_ext`` library.
```

2024-04-24 09:01 UTC, kapbh commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added support for the ``WPA-PSK`` security mode to the wifi_mgmt_ext.
Done

2024-04-24 09:33 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***sample.matter.template.debug[nrf5340dk_nrf5340_cpuapp]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf5340dk_nrf5340_cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.debug[nrf7002dk_nrf5340_cpuapp]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf7002dk_nrf5340_cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.release[nrf52840dk_nrf52840]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf52840dk_nrf52840) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.release[nrf5340dk_nrf5340_cpuapp]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf5340dk_nrf5340_cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.release[nrf7002dk_nrf5340_cpuapp]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf7002dk_nrf5340_cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.debug[nrf52840dk_nrf52840]***: ***RAM*** size  ***increased by 11200[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf52840dk_nrf52840) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15007/5)*

2024-04-24 11:37 UTC, rado17 approved these changes

2024-04-25 12:15 UTC, merged