net: lib: nrf_cloud_pgps: Fix NULL pointer injection
nrfconnect/sdk-nrf pull request #15071
Opened 2024-04-25 00:17 UTC by plskeggs

Improve error handling when valid predictions exist but none are actually for the current GPS time.

Also improve error handling for all error returns from nrf_cloud_pgps_find_prediction().

Jira: IRIS-8818

2024-04-25 00:19 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15071/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15071/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15071/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-25 06:49 UTC, tokangas approved these changes

2024-04-25 16:44 UTC, jayteemo approved these changes

2024-04-25 17:36 UTC, glarsennordic approved these changes

2024-04-26 06:01 UTC, wiba-nordic requested changes

2024-04-26 06:01 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed a NULL pointer issue when there are some valid predictions in flash but not the one required at the current time.
```suggestion
  * Fixed a NULL pointer issue that could occur when there are some valid predictions in flash but not the one required at the current time.
```

2024-04-30 06:26 UTC, peknis approved these changes

2024-04-30 06:38 UTC, wiba-nordic approved these changes

2024-05-07 07:39 UTC, merged