doc: known_issue: Matter add known issue to KRKNWK-18673 bug
nrfconnect/sdk-nrf pull request #15082
Opened 2024-04-25 08:17 UTC by doublemis1

Update Matter known issue with the issue found during testing.

2024-04-25 08:20 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15082/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15082/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-04-25 08:27 UTC, wiba-nordic requested changes

2024-04-25 08:27 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-18673: Bridged Light Bulb device type reports a failure when reading or writing specific onoff cluster attributes
```suggestion
KRKNWK-18673: Bridged Light Bulb device type reports a failure when reading or writing specific ``onoff`` cluster attributes
```
I think that might be how we format clusters?

2024-04-25 08:27 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  Bridge has defined properly zap clusters for bridged light bulb, however handling specific onoff cluster attributes has not been implemented.
```suggestion
  The Bridge has defined ZAP clusters properly for a bridged Light Bulb, but handling of specific ``onoff`` cluster attributes has not been implemented.
```

2024-04-25 08:38 UTC, wiba-nordic approved these changes

2024-04-25 09:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15082
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-26 05:54 UTC, kkasperczyk-no approved these changes

2024-04-27 14:41 UTC, LuDuda approved these changes

2024-05-07 11:51 UTC, merged