workflows: add CI token
nrfconnect/sdk-nrf pull request #15105
Opened 2024-04-26 10:48 UTC by eivindj-nordic

Add token for workflows using nordicbuilder/action-checkout-west-update.

2024-04-26 10:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15105/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15105/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-04-26 11:13 UTC, karhama commented
secret used here should not exist in this repository; it has intentionally been left empty.

2024-04-26 11:13 UTC, karhama approved these changes

2024-04-26 11:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15105
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-26 11:49 UTC, gmarull commented on .github/workflows/docbuild.yml
> +          west-token: ${{ secrets.WEST_UPDATE_TOKEN }}
why is this needed here?

2024-04-26 12:02 UTC, gmarull requested changes
docs do not run west update

2024-04-26 12:14 UTC, eivindj-nordic commented
> docs do not run west update

Where do you see that?

2024-04-30 10:24 UTC, carlescufi commented
> > docs do not run west update
> 
> Where do you see that? To me the checkout sources step looks ok here: https://github.com/nrfconnect/sdk-nrf/actions/runs/8847144566/job/24294387285?pr=15105

@gmarull ping

2024-05-14 08:10 UTC, eivindj-nordic commented
> > docs do not run west update
> 
> Where do you see that? To me the checkout sources step looks ok here: https://github.com/nrfconnect/sdk-nrf/actions/runs/8847144566/job/24294387285?pr=15105

@gmarull

2024-07-09 07:14 UTC, closed without merging