nrf_rpc: add documentation page for the UART transport
nrfconnect/sdk-nrf pull request #15121
Opened 2024-04-29 11:44 UTC by Damian-Nordic

Add a documentation page that describes the nRF RPC UART transport frame encoding and API.

2024-04-29 11:58 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15121/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15121/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15121/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-29 12:07 UTC, wiba-nordic requested changes
Is this not aimed at the `main` branch on purpose?

2024-04-29 12:07 UTC, wiba-nordic commented on doc/nrf/libraries/nrf_rpc/nrf_rpc_uart.rst
> +   The current frame format is transitional and will be extended with CRC and other fields to ensure the transport reliability.
```suggestion
   The current frame format is transitional and will be extended with CRC and other fields to ensure transport reliability.
```

2024-04-29 12:09 UTC, Damian-Nordic commented
> Is this not aimed at the `main` branch on purpose?

Yes, we're developing a proof of concept on branch but it will be merged to main at some point.

2024-04-29 12:28 UTC, wiba-nordic approved these changes

2024-04-29 12:50 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zrelease[nrf52810dmouse_nrf52810]***: ***ROM*** size  ***increased by 952[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf52810dmouse_nrf52810) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52810dmouse_nrf52810]***: ***ROM*** size  ***increased by 916[B]*** in comparison to the ***main*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52810dmouse_nrf52810) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15121/2)*

2024-04-29 16:22 UTC, canisLupus1313 commented
@Damian-Nordic Overall looks good, but would be nice to add that this version is experimental, and will change.

2024-04-29 16:38 UTC, Damian-Nordic commented
> @Damian-Nordic Overall looks good, but would be nice to add that this version is experimental, and will change.

You mean apart from this big note I added:
"The current frame format is transitional and will be extended with CRC and other fields to ensure transport reliability."? ;)

2024-04-30 06:10 UTC, bpienk approved these changes

2024-04-30 06:31 UTC, canisLupus1313 commented
> > @Damian-Nordic Overall looks good, but would be nice to add that this version is experimental, and will change.
> 
> You mean apart from this big note I added: "The current frame format is transitional and will be extended with CRC and other fields to ensure transport reliability."? ;)
> 
> Or maybe should I move it to the section beginning?

I think it would be more visible on top of the sesction.

2024-04-30 06:31 UTC, canisLupus1313 approved these changes

2024-04-30 06:42 UTC, wiba-nordic commented
> > > @Damian-Nordic Overall looks good, but would be nice to add that this version is experimental, and will change.
> > 
> > 
> > You mean apart from this big note I added: "The current frame format is transitional and will be extended with CRC and other fields to ensure transport reliability."? ;)
> > Or maybe should I move it to the section beginning?
> 
> I think it would be more visible on top of the sesction.

I'd say adding it after the first line in the section would be best for the meaning, since that puts it just before the description of the current implementation.

2024-04-30 09:28 UTC, merged