applications: nrf_desktop: Fix HID subscription errors in hid_forward
nrfconnect/sdk-nrf pull request #15141
Opened 2024-04-30 12:21 UTC by MarekPieta

Change aligns Kconfig option used to configure number of ATT PDUs. This is needed after `a05a47573a11ba8a78dadc5d3229659f24ddd32f` was added to `sdk-zephyr`.

Jira: NCSDK-27314

2024-04-30 12:25 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15141/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15141/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15141/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-04-30 12:27 UTC, peknis requested changes

2024-04-30 12:27 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    Update is needed to align with new approach that was introduced to ``sdk-zephyr`` by the following commit: ``a05a47573a11ba8a78dadc5d3229659f24ddd32f``.
```suggestion
  * Replaced the :kconfig:option:`CONFIG_BT_L2CAP_TX_BUF_COUNT` Kconfig option with :kconfig:option:`CONFIG_BT_ATT_TX_COUNT` in nRF Desktop dongle configurations.
    This update is needed to align with the new approach introduced in ``sdk-zephyr`` by commit ``a05a47573a11ba8a78dadc5d3229659f24ddd32f``.
```

2024-04-30 12:40 UTC, peknis approved these changes

2024-04-30 13:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15141
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-04-30 16:11 UTC, alstrzebonski approved these changes

2024-05-07 06:28 UTC, MarekPieta commented
Hi @nordicjm,
Can we merge this one? It's a small bugfix for nRF Desktop dongle configurations

2024-05-07 07:35 UTC, merged