scripts: tools-versions-*.yml: update zephyr-sdk==0.16.6.rc1
nrfconnect/sdk-nrf pull request #15145
Opened 2024-04-30 14:11 UTC by thst-nordic

Just testing the RC.  We will wait for 0.16.6 before merge

Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>

2024-04-30 14:16 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15145/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15145/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15145/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-03 06:39 UTC, shanthanordic approved these changes

2024-05-03 07:42 UTC, carlescufi requested changes
Don't use -rc1, the final release is out:
https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.16.6

2024-05-03 10:12 UTC, carlescufi approved these changes

2024-05-06 06:47 UTC, thst-nordic commented
some trouble with building windows toolchain. nrfutil team is looking at it today.

2024-05-07 18:39 UTC, NordicBuilder commented
This pr introduces changes to requirements files.
The compiled requirements-fixed.txt has changed.
To automatically add the changed file to this pr react with the :eyes: emote to this comment and re-run the check.
[Check Run](https://github.com/nrfconnect/sdk-nrf/actions/runs/8990576622)
<details>
  <summary>requirements-fixed.txt diff</summary>

  ``` diff
  diff --git a/scripts/requirements-fixed.txt b/scripts/requirements-fixed.txt
index 5cff9d9..efc0c42 100644
--- a/scripts/requirements-fixed.txt
+++ b/scripts/requirements-fixed.txt
@@ -11,6 +11,7 @@ arrow==1.2.1              # via gitlint-core
 astroid==2.15.6           # via pylint
 attrs==23.1.0             # via jsonschema, referencing
 bitarray==2.8.1           # via -r nrf/scripts/requirements-ci.txt
+bz==1.0                   # via -r zephyr/scripts/requirements-run-test.txt
 canopen==2.1.0            # via -r zephyr/scripts/requirements-base.txt
 capstone==4.0.2           # via pyocd
 cbor==1.0.0               # via -r zephyr/scripts/requirements-run-test.txt
@@ -41,7 +42,7 @@ gitpython==3.1.41         # via -r nrf/scripts/requirements-ci.txt
 graphviz==0.20.1          # via -r zephyr/scripts/requirements-extras.txt
 grpcio==1.58.0            # via grpcio-tools
 grpcio-tools==1.58.0      # via -r zephyr/scripts/requirements-extras.txt
-idna==3.4                 # via requests
+idna==3.7                 # via -r nrf/scripts/requirements-extra.txt, requests
 imagesize==1.4.1          # via -r nrf/scripts/requirements-build.txt
 imgtool==2.0.0            # via -r zephyr/scripts/requirements-extras.txt
 importlib-metadata==6.8.0  # via pyocd
@@ -50,7 +51,7 @@ iniconfig==2.0.0          # via pytest
 intelhex==2.3.0           # via -r bootloader/mcuboot/scripts/requirements.txt, -r nrf/scripts/requirements-build.txt, -r zephyr/scripts/requirements-base.txt, imgtool, lpc-checksum, nrf-regtool, pyocd
 intervaltree==3.1.0       # via pyocd
 isort==5.12.0             # via pylint
-jinja2==3.1.3             # via -r nrf/scripts/requirements-extra.txt, gcovr, junit2html
+jinja2==3.1.4             # via -r nrf/scripts/requirements-extra.txt, gcovr, junit2html
 jsonschema==4.19.1        # via -r nrf/scripts/requirements-ci.txt
 jsonschema-specifications==2023.7.1  # via jsonschema
 junit2html==30.1.3        # via -r zephyr/scripts/requirements-extras.txt
@@ -74,7 +75,7 @@ nrfcredstore==1.0.0       # via -r nrf/scripts/requirements-extra.txt
 numpy==1.26.4             # via svada
 packaging==23.1           # via -r zephyr/scripts/requirements-base.txt, pytest, python-can, setuptools-scm, west
 pathspec==0.11.2          # via yamllint
-pillow==10.2.0            # via -r nrf/scripts/requirements-extra.txt, -r zephyr/scripts/requirements-extras.txt
+pillow==10.3.0            # via -r nrf/scripts/requirements-extra.txt, -r zephyr/scripts/requirements-extras.txt
 platformdirs==3.10.0      # via pylint
 pluggy==1.3.0             # via pytest
 ply==3.11                 # via -r zephyr/scripts/requirements-build-test.txt
  ```
</details>


*Note: This comment is automatically posted and updated by the Comment GitHub Action.*

2024-05-08 07:41 UTC, jangalda-nsc approved these changes

2024-05-10 08:52 UTC, thst-nordic commented
There are problems with the 0.16.6 release that have been reverted for 0.16.7.  
https://github.com/zephyrproject-rtos/sdk-ng/issues/751
This 0.16.7 was tagged but not yet 'released' with binaries. 

I will update this PR to use 0.16.7 as soon as the artifacts are ready.

2024-05-10 11:04 UTC, thst-nordic commented
With the revert of the C11-threads feature there are only 2 commits in 0.16.7, and neither is urgent. 
Lets wait for next zephyr-ng release. 
https://github.com/zephyrproject-rtos/gcc/commit/b016c34c39aa42a550fef3bf59876b942ca4a11a
https://github.com/zephyrproject-rtos/gcc/commit/06c248d3b93b4c7baf330e0f13eb99f8925fedec

2024-08-08 12:29 UTC, thst-nordic commented
I updated this to 0.16.8, and am rebuilding.

2024-08-09 06:47 UTC, nordic-piks approved these changes

2024-08-12 10:49 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 20
### Inputs:
#### Sources:
sdk-nrf: PR head: [675a364e85b60b5807111d3fa52367bbbf7fe1f2](https://github.com/nrfconnect/sdk-nrf/pull/15145/commits/675a364e85b60b5807111d3fa52367bbbf7fe1f2)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [675a364e85b60b5807111d3fa52367bbbf7fe1f2](https://github.com/nrfconnect/sdk-nrf/pull/15145/commits/675a364e85b60b5807111d3fa52367bbbf7fe1f2)
> merge base: [d11dcb6ec251f0ece98fa05aa42aaeb401ba21ae](https://github.com/nrfconnect/sdk-nrf/commit/d11dcb6ec251f0ece98fa05aa42aaeb401ba21ae)
> target head (main): [2f0cd2af419c86d005d84682f14dc859de7300e1](https://github.com/nrfconnect/sdk-nrf/commit/2f0cd2af419c86d005d84682f14dc859de7300e1)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
scripts
│  ├── tools-versions-darwin.yml
│  ├── tools-versions-linux.yml
│  │ tools-versions-win10.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-23 08:44 UTC, thst-nordic commented
testing is complete. all twister and downstream passed (with exemption for known issue on wifi)

> ## CI Information
> _To view the history of this post, clich the 'edited' button above_ Build number: 33

2024-08-23 09:03 UTC, merged