samples: wifi: shell: Fix wifi connect command syntax
nrfconnect/sdk-nrf pull request #15164
Opened 2024-05-03 10:36 UTC by D-Triveni

Fix the `wifi connect` command syntax in the documentation to include options for SSID, PSK, and Key Management.

Fixes SHEL-2733

2024-05-03 10:37 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15164/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15164/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-05-03 11:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15164
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-03 22:17 UTC, VivekUppunda approved these changes

2024-05-03 22:18 UTC, VivekUppunda commented on samples/wifi/shell/README.rst
> +   ``<SSID>`` is the SSID of the network you want to connect to, ``<passphrase>`` is its passphrase, and the key management is the security type used by the network.
Agree. Kindly make this change before merge

2024-05-08 09:05 UTC, richabp requested changes

2024-05-08 09:05 UTC, richabp commented on samples/wifi/shell/README.rst
> +   ``<SSID>`` is the SSID of the network you want to connect to, ``<passphrase>`` is its passphrase, and the key management is the security type used by the network.
To be consistent, may be ``<key_management>`` ?

2024-05-08 13:06 UTC, sachinthegreen approved these changes

2024-05-17 05:24 UTC, D-Triveni commented
Fix was addressed in another PR https://github.com/nrfconnect/sdk-nrf/pull/15301, so closing this.

2024-05-17 05:24 UTC, closed without merging