applications: nrf5340_audio: Using low latency setting as default
nrfconnect/sdk-nrf pull request #15179
Opened 2024-05-06 10:05 UTC by rick1082

Using low latency configuration as default.
* Set transport latency to 5ms
* Set minimal presentation delay to 3ms
* Set prefer minimal presentation delay to 3ms OCT-2995
Signed-off-by: Jui-Chou Chung <jui-chou.chung@nordicsemi.no>

2024-05-06 10:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15179/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15179/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15179/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-06 10:09 UTC, rick1082 commented on applications/nrf5340_audio/src/bluetooth/Kconfig
> +	default 5
Yes, this can do some help. And the transport latency can be smaller than ISO interval.

2024-05-06 10:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15179
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-06 11:56 UTC, alexsven approved these changes

2024-05-06 14:17 UTC, rick1082 commented
> > This looks good, but we need to run the nightly latency tests before merging.
> 
> On the way, will share the result in here when I got it. But from my desk, the number will be CIS: 32ms BIS: 28ms The comparison will help us to tell the difference between audio analyzer and oscilloscope.

Now the test result shows
BIS: 30.79ms
CIS: 31.88ns

2024-05-13 12:28 UTC, koffes commented
We need to add to the changelog as well. We may also discuss adding to known issues.

2024-05-14 09:03 UTC, rick1082 commented
Updated the MTL from 5ms to 10ms, the test result:
CIS: 33.55ms
BIS: 30.81ms

2024-05-15 05:32 UTC, peknis requested changes

2024-05-15 05:32 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Using low latency configuration as default setting for the nRF5340 Audio application.
Suggesting that you organize the bullets under nRF5340 Audio as follows:

* Removed:

  * The LE Audio...

* Updated:

  * Low latency configuration to be used as default setting for the nRF5340 Audio application.

2024-05-15 06:34 UTC, peknis requested changes

2024-05-15 06:34 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The LE Audio controller for nRF5340 library is removed.
```suggestion
  * The LE Audio controller for nRF5340 library.
```
The first bullet already says it is removed.

2024-05-15 06:37 UTC, peknis approved these changes

2024-05-15 09:35 UTC, merged