FMDN upstream part 1: Crypto
nrfconnect/sdk-nrf pull request #15181
Opened 2024-05-06 10:06 UTC by kapi-no

Dependencies:

https://github.com/nrfconnect/sdk-nrf/pull/15156

2024-05-06 10:07 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/646a678c8d7b79a758236557161241caf678c9ab (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1317 | [nrfconnect/sdk-nrfxlib#1317/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1317/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-05-06 10:09 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15181/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15181/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15181/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-06 10:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15181
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-07 08:19 UTC, MarekPieta requested changes

2024-05-07 08:46 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
These are not optional for the FMDN extension. They are required. When we reviewed this part, we aimed to introduce similar options for other configurations. If we do not support the PN extension some APIs and ops are also not needed

2024-05-07 08:56 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +	if (datalen != SECP160R1_DATA_LEN) {
It's a limitation of this particular backend. See the mbedTLS implementation

2024-05-07 08:57 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +	if (datalen != SECP160R1_DATA_LEN) {
The SECP functions are very similar to existing FP crypto APIs that have similar usage (e.g. hashing function):

```
int fp_crypto_sha256(uint8_t *out, const uint8_t *in, size_t data_len);
```

2024-05-07 12:03 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
I mean that they are optional from `fp_crypto` backend's perspective (backend can declare if it implements given crypto operation or not). Still, looking at your response, my comment by itself may be misleading.
Maybe, apart from comment update, we could mark crypto operations required by FMDN under Kconfig helps?

2024-05-07 12:04 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
Keep in mind that FMDN is an user of `fp_crypto` library, so the `fp_crypto` library does not need to know about FMDN requirements (FMDN tailors `fp_crypto` to align it to FMDN needs)

2024-05-07 12:06 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +	if (datalen != SECP160R1_DATA_LEN) {
I meant that, if FMDN uses only a single input length here, we could simplify API. Still, I would not insist and we can keep it as is if you prefer more generic implementation.

2024-05-07 12:08 UTC, alstrzebonski approved these changes

2024-05-08 07:24 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
> Keep in mind that FMDN is an user of `fp_crypto` library, so the `fp_crypto` library does not need to know about FMDN requirements (FMDN tailors `fp_crypto` to align it to FMDN needs)

The same thing can be said about the PN extension and its dedicated crypto requirements and the `fp_crypto_additional_data_encode` function

2024-05-08 08:24 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +	 /* SECP160R1 key length corresponds to one coordinate. */
I think compliance generally does not complain about spaces after tabs (it seems not to have special handling for comments)

2024-05-08 08:33 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
I would say it's unlikely that these FMDN crypto operations would require other data length. For additional data encode chances that various data length are needed are higher I think (e.g. if a new operation is added). Still, we can keep the API as is here.

2024-05-08 08:34 UTC, MarekPieta commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +/* START: importing additional APIs from the Oberon runtime. */
@kapi-no, maybe we can open a tracking ticket and get back to it after this PR is merged?

2024-05-08 14:33 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
> +# Define Fast Pair operations that can be supported by each backend.
Discussed offline:

```suggestion
# A backend supporting a given crypto operation selects a related Kconfig option.
```

2024-05-08 14:34 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +/* START: importing additional APIs from the Oberon runtime. */
discussed offline, create a tracking ticket

2024-05-08 14:36 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +	if (datalen != SECP160R1_DATA_LEN) {
discussed offline, keep as is

2024-05-09 12:47 UTC, kapi-no commented on subsys/bluetooth/services/fast_pair/fp_crypto/fp_crypto_oberon.c
> +/* START: importing additional APIs from the Oberon runtime. */
Defined a tracking ticket in JIRA:

https://nordicsemi.atlassian.net/browse/NCSDK-27410

Please do not resolve this comment thread so it is easier to access it using a link defined in the JIRA ticket

2024-05-09 12:51 UTC, kapi-no commented
The last force push contains only the rebase diff

2024-05-10 08:25 UTC, MarekPieta approved these changes

2024-05-16 08:43 UTC, kapi-no commented
Dropping the dependency on nrfxlib as it was merged into the main NCS branch.

2024-05-16 10:26 UTC, merged