wifi: Add kconfig option to disable wmm mode
nrfconnect/sdk-nrf pull request #15198
Opened 2024-05-07 10:21 UTC by kapbh

[SHEL-2054] A wmm was by default set to 1. Adding a kconfig option for wmm. By default value of kconfig will be 1. If user needs to disable it, set it as 0.

2024-05-07 10:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15198/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15198/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15198/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-07 10:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15198
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-08 07:31 UTC, kapbh commented on drivers/wifi/nrf700x/Kconfig
> +	int "Disable wmm mode"
Done.

2024-05-08 11:33 UTC, rado17 approved these changes

2024-05-08 13:06 UTC, sachinthegreen requested changes

2024-05-08 13:06 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/fmac_main.c
>  static const unsigned char wmm = 1;
Why do we need this variable any longer? `CONFIG_NRF_WIFI_WMM_MODE` could just be used to set the value on line 700 ?

2024-05-14 09:01 UTC, krish2718 requested changes

2024-05-14 09:01 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +config NRF_WIFI_WMM_MODE
`NRF_WIFI_WMM` should suffice, it's not a mode.

2024-05-14 09:01 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +config NRF_WIFI_WMM_MODE
or maybe `NRF_WIFI_FEAT` as a generic prefix and for all Wi-Fi features?

2024-07-04 07:24 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	int "Disable WMM mode"
```suggestion
	bool "Disable WMM mode"
```

2024-07-16 10:29 UTC, sachinthegreen requested changes

2024-07-16 10:29 UTC, sachinthegreen commented on drivers/wifi/nrf700x/Kconfig
> +	default n
Default n is implicit ?

2024-07-16 14:49 UTC, krish2718 requested changes

2024-07-16 14:49 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	bool "Enable/Disable WMM mode"
may be define what is WMM somewhere, either in title of help ?

2024-07-16 14:49 UTC, krish2718 commented on drivers/wifi/nrf700x/src/fmac_main.c
> +#endif
```suggestion
	data_config.wmm = IS_ENABLED(CONFIG_NRF_WIFI_FEAT_WMM);
```

2024-07-16 14:49 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	help
Shouldn't this enabled by default?

2024-07-17 05:49 UTC, kapbh commented on drivers/wifi/nrf700x/src/fmac_main.c
> +#endif
Ok.

2024-07-17 10:26 UTC, krish2718 approved these changes

2024-07-17 11:32 UTC, merged