doc: snippets: move info from VSC extension docs
nrfconnect/sdk-nrf pull request #15226
Opened 2024-05-08 13:16 UTC by greg-fer

Moved info about snippets from VSC extension docs to where it should belong.

2024-05-08 13:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15226
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-10 04:44 UTC, wiba-nordic requested changes

2024-05-10 04:44 UTC, wiba-nordic commented on doc/nrf/device_guides/working_with_nrf/nrf70/developing/fw_patches_ext_flash.rst
> +This feature can be enabled using DTS or :ref:`app_build_snippets` feature or by using :ref:`partition_manager`.
```suggestion
This feature can be enabled using DTS or the :ref:`app_build_snippets` feature, or by using :ref:`partition_manager`.
```

2024-05-21 12:08 UTC, bencefr approved these changes
LGTM

2024-05-21 12:12 UTC, wiba-nordic approved these changes

2024-05-23 07:24 UTC, merged