modules: wfa-qt: use net_if_ipv4_set_netmask_by_addr
nrfconnect/sdk-nrf pull request #15246
Opened 2024-05-09 17:27 UTC by D-Triveni

Replace usage of the deprecated `net_if_ipv4_set_netmask` with the `net_if_ipv4_set_netmask_by_addr`.

2024-05-09 17:28 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15246/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15246/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15246/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-09 19:29 UTC, krish2718 requested changes

2024-05-09 19:29 UTC, krish2718 commented on modules/wfa-qt/src/utils.c
> +	const struct device *dev = DEVICE_DT_GET(DT_CHOSEN(zephyr_wifi));
Please do this in a separate commit.

2024-05-09 19:29 UTC, krish2718 commented on modules/wfa-qt/src/utils.c
> +	struct in_addr addr = { 0 };
we don't need the unnecessary initialisation as we overwrite with the parse.

2024-05-10 07:40 UTC, krish2718 approved these changes

2024-05-10 07:42 UTC, VivekUppunda approved these changes

2024-05-10 11:05 UTC, merged