Upstream multicore hello world
nrfconnect/sdk-nrf pull request #15289
Opened 2024-05-14 07:58 UTC by gmarull

2024-05-14 07:58 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/8e18208ae30e172d05b69bba5908095a561c0794 | https://github.com/nrfconnect/sdk-zephyr/pull/1711 | [nrfconnect/sdk-zephyr#1711/files](https://github.com/nrfconnect/sdk-zephyr/pull/1711/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-05-14 08:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15289
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-14 12:30 UTC, grochu approved these changes

2024-05-14 12:43 UTC, gmarull commented
> Hi @gmarull , can you tell who has agreed to that?

I guess the question is: why maintain a sample in NCS that has an upstream equivalent?

2024-05-15 12:28 UTC, pdunaj commented
> > Hi @gmarull , can you tell who has agreed to that?
> 
> I guess the question is: why maintain a sample in NCS that has an upstream equivalent?

Convenience - it's easier for us. I expect I don't have a problem with migrating that if you take the ownership for it. We have other stuff to do and I see @grochu is already ok.

@carlescufi, will you take ownership for this sample?

2024-05-15 12:28 UTC, pdunaj submitted a review, later dismissed
Let's confirm the ownership first.

2024-05-16 10:05 UTC, gmarull commented
> > > Hi @gmarull , can you tell who has agreed to that?
> > 
> > 
> > I guess the question is: why maintain a sample in NCS that has an upstream equivalent?
> 
> Convenience - it's easier for us. I expect I don't have a problem with migrating that if you take the ownership for it. We have other stuff to do and I see @grochu is already ok.
> 
> @carlescufi, will you take ownership for this sample?

I guess maintenance can be taken, it's actually easier to maintain upstream as it will get updated as needed so it'll never be broken.

2024-05-21 09:13 UTC, greg-fer requested changes
Requires a changelog entry about the sample removal.

2024-05-21 17:13 UTC, gmarull commented
> Requires a changelog entry about the sample removal.

done

2024-05-23 10:35 UTC, greg-fer requested changes
Just an edit to the changelog.

2024-05-23 10:35 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Multicore hello world sample removed in favor of :zephyr:code-sample:`sysbuild_hello_world`, which has equivalent functionality.
```suggestion
* Removed the "Multicore Hello World application" sample in favor of :zephyr:code-sample:`sysbuild_hello_world`, which has equivalent functionality.
  This also removes the Multicore samples category from the :ref:`samples` page.
```

2024-05-29 08:19 UTC, gmarull commented
@greg-fer @pdunaj ping

2024-05-29 10:52 UTC, FrancescoSer requested changes

2024-05-29 10:52 UTC, FrancescoSer commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
> +      west build -p -b nrf54h20dk_nrf54h20_cpuapp -T sample.sysbuild.hello_world.nrf54h20dk_cpuapp_cpurad .
Could you update the board target in the command here?

2024-05-29 10:52 UTC, FrancescoSer commented on doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
> +      west build -p -b nrf54h20dk_nrf54h20_cpuapp -T sample.sysbuild.hello_world.nrf54h20dk_cpuapp_cpuppr .
same here

2024-05-30 13:39 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug_4llpmconn[nrf52840dongle/nrf52840]***: ***RAM*** size  ***increased by 312[B]*** in comparison to the ***main[643c3f4f]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_4llpmconn&var-testcase=none&var-arch=arm&var-platform=nrf52840dongle/nrf52840) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15289/8)*

2024-06-03 08:08 UTC, gmarull commented
@greg-fer @FrancescoSer ping

2024-06-03 09:55 UTC, FrancescoSer approved these changes
Approving but please implement the small suggestion

2024-06-04 08:46 UTC, merged