nrf_wifi: Set bss params max_inactivity, skip_inactivity_poll and max_num_sta
nrfconnect/sdk-nrf pull request #15284
Opened 2024-05-14 06:57 UTC by ajayparida

Support for configuring BSS parameters max_inactivity, skip_inactivity_poll and max_num_sta

2024-05-14 07:03 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15284/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15284/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15284/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-14 07:04 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/8e18208ae30e172d05b69bba5908095a561c0794 | pull/head/1710 | [nrfconnect/sdk-zephyr@8e18208a..pull/head/1710](https://github.com/nrfconnect/sdk-zephyr/compare/8e18208ae30e172d05b69bba5908095a561c0794..pull/head/1710) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-05-14 07:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15284
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-21 13:34 UTC, krish2718 commented on modules/hostap/src/supp_events.c
> +					      wpa_s->current_ssid->ssid,
Do we need a NULL check for `wpa_s->current_ssid` ?

2024-05-21 13:34 UTC, krish2718 commented on modules/hostap/src/supp_events.c
> +		if (hapd) {
we can indent it down using early exits (Linux style).

2024-05-21 13:34 UTC, krish2718 commented on modules/hostap/src/supp_events.c
> +			}
If the failure is being ignored, this should be a warning and also please log the ret code for failure.

2024-05-21 13:34 UTC, krish2718 commented on modules/hostap/src/supp_api.c
> +			wpa_s->conf->max_num_sta = params->max_num_sta;
This can also be per-BSS, so, why not use the same command `set_network`?

2024-05-21 16:47 UTC, krish2718 commented on modules/hostap/src/supp_api.c
> +		wpa_printf(MSG_ERROR, "Failed to get current ssid");
```suggestion
		wpa_printf(MSG_ERROR, "AP is not operational");
```

2024-05-21 16:47 UTC, krish2718 commented on modules/hostap/src/supp_api.c
> +		if (params->max_num_sta > CONFIG_WIFI_MGMT_AP_MAX_NUM_STA) {
May be add a comment here `Build time precedence is higer`?

2024-05-21 16:47 UTC, krish2718 commented on modules/hostap/src/supp_api.c
> +
no need of a newline b//w assignment and error checking.

2024-05-23 12:34 UTC, sachinthegreen requested changes

2024-05-23 12:34 UTC, sachinthegreen commented on modules/hostap/src/supp_api.c
> +	/* Set the default maximum inactivity time for the bss to
```suggestion
	/* Set the default maximum inactivity time for the BSS to
```

2024-05-23 12:34 UTC, sachinthegreen commented on modules/hostap/src/supp_api.c
> +	/* Set bss parameter max_num_sta to default configured value */
```suggestion
	/* Set BSS parameter max_num_sta to default configured value */
```

2024-05-23 12:34 UTC, sachinthegreen commented on modules/hostap/src/supp_api.c
> +		/* Build time value is higher precedence than runtime configuration value.
```suggestion
		/* Build time value has higher precedence than runtime configuration value.
```

2024-05-29 08:22 UTC, krish2718 approved these changes

2024-05-29 15:23 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug_4llpmconn[nrf52840dongle/nrf52840]***: ***RAM*** size  ***increased by 312[B]*** in comparison to the ***main[2001e6db]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_4llpmconn&var-testcase=none&var-arch=arm&var-platform=nrf52840dongle/nrf52840) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15284/25)*

2024-05-31 09:36 UTC, rlubos commented
@ajayparida It seems the SHA is wrong (not from main), can you set it to the most recent commit (`ccd3d27de3ca1e754628192a29121e2382f59d57`), thanks.

2024-05-31 09:39 UTC, rlubos approved these changes

2024-05-31 14:37 UTC, merged