samples: matter: Enabled BLE extended announcement
nrfconnect/sdk-nrf pull request #15371
Opened 2024-05-17 13:05 UTC by kkasperczyk-no

Enabled by default BLE extended announcement in all Matter samples. Also, enabled pairing autostart in Window Covering and Light Switch samples (according to spec all devices shall use it besides door lock, or define custom commissioning flow).

2024-05-17 13:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15371/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15371/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15371/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-17 13:34 UTC, LuDuda approved these changes

2024-05-17 13:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15371
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-20 06:34 UTC, ArekBalysNordic approved these changes

2024-05-20 06:43 UTC, wiba-nordic reviewed
Shouldn't we also have a changelog entry for the samples with autopairing now enabled?

2024-05-20 06:43 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +* Setting :kconfig:option:`CONFIG_CHIP_BLE_EXT_ADVERTISING` to ``n`` to disable Extended Announcement (also called Extended Beaconing), which allows a device to advertise for a duration of more than
```suggestion
* :kconfig:option:`CONFIG_CHIP_BLE_EXT_ADVERTISING` -  Set to ``n`` to disable Extended Announcement (also called Extended Beaconing).
  When disabled, the device is not allowed to advertise for a duration of more than 15 minutes.
```

2024-05-20 06:43 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +* Setting :kconfig:option:`CONFIG_CHIP_BLE_ADVERTISING_DURATION` to the lower value.
```suggestion
* :kconfig:option:`CONFIG_CHIP_BLE_ADVERTISING_DURATION` - Set how long the device advertises (in minutes).
```

2024-05-20 07:13 UTC, kkasperczyk-no commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +To reduce the consumed energy you can consider:
I added to your suggestion "and reduce the consumed energy", because I think it's important to highlight what is the purpose of the configuration.

2024-05-20 08:28 UTC, wiba-nordic approved these changes

2024-05-20 09:14 UTC, markaj-nordic approved these changes
Should we update the documentation for Window Covering and Light Switch (BLE advertising start)?

2024-05-20 10:11 UTC, kkasperczyk-no commented
> Should we update the documentation for Window Covering and Light Switch (BLE advertising start)?

Fair point. @wiba-nordic please take a look once again. I updated readme files for these samples to mention that the advertising is automatically started and the duration is 1 hour. I also added entry in the release notes.

2024-05-20 10:21 UTC, wiba-nordic requested changes

2024-05-20 10:21 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Enabled Bluetooth® LE Extended Announcement feature to all samples and increased advertising timeout from 15 minutes to 1 hour.
```suggestion
* Enabled the Bluetooth® LE Extended Announcement feature for all samples, and increased advertising timeout from 15 minutes to 1 hour.
```

2024-05-20 10:21 UTC, wiba-nordic commented on samples/matter/light_switch/README.rst
>  Press **Button 1** to enable the Bluetooth LE advertising.
```suggestion
If the Bluetooth LE advertising times out, press **Button 1** to enable it again.
```

2024-05-20 12:25 UTC, wiba-nordic approved these changes

2024-05-21 08:06 UTC, merged