TF-M and Crypto samples: add 9161 support
nrfconnect/sdk-nrf pull request #15409
Opened 2024-05-21 10:46 UTC by juhaylinen

* Add 9161 support to t-fm samples and tests
* Add 9161 support to crypto tests and samples

2024-05-21 10:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15409/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15409/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15409/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-21 11:01 UTC, MarkusLassila approved these changes
LGTM!

2024-05-21 11:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15409
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-22 12:24 UTC, mswarowsky approved these changes

2024-05-29 11:22 UTC, mia-ko requested changes

2024-05-29 11:22 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for the :ref:`zephyr:nrf9151dk_nrf9151` and the :ref:`nRF9161 DK <ug_nrf9161>` boards for all TF-M samples.
```suggestion
* Added support for the :ref:`zephyr:nrf9151dk_nrf9151` and the :ref:`nRF9161 DK <ug_nrf9161>` boards for all TF-M samples (except for the :ref:`provisioning_image_net_core` sample).
```

2024-05-29 11:22 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for the :ref:`zephyr:nrf9151dk_nrf9151` and the :ref:`nRF9161 DK <ug_nrf9161>` boards for all TF-M samples.
Also, add a bullet point after line 533 (under the Cryptography samples section)

Support for the :ref:`nRF9161 DK <ug_nrf9161>` board for the :ref:`crypto_test` sample.

2024-05-30 11:10 UTC, mia-ko approved these changes

2024-05-31 07:18 UTC, merged