Enable ITS encryption by default on 54L
nrfconnect/sdk-nrf pull request #15418
Opened 2024-05-21 13:46 UTC by mswarowsky

2024-05-21 13:47 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| trusted-firmware-m | https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/dd0114796baf44d249764b2f3b9bc3be9c1d01d4 (main) | https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/149 | [nrfconnect/sdk-trusted-firmware-m#149/files](https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/149/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-05-21 13:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15418/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15418/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-find-my | X | | |
| test-sdk-mcuboot | X | | |
| test-sdk-sidewalk | X | | |

**test-fw-nrfconnect-tfm:** added because there was no .github/test-spec.yml in 'trusted-firmware-m'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15418/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-21 15:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15418
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-23 08:36 UTC, mia-ko requested changes
Rewriting when non TF-M is used...
because it should be hyphenated 'non-TF-M', but that just looks a bit odd :)
Let me know if what I used instead doesn't feel right either.

2024-05-23 08:36 UTC, mia-ko commented on samples/crypto/persistent_key_usage/README.rst
> +The ITS backend is either provided by TF-M or the :ref:`trusted_storage_readme` library for non TF-M builds.
```suggestion
The ITS backend is either provided by TF-M, or the :ref:`trusted_storage_readme` library when building applications without TF-M.
```

2024-05-23 08:36 UTC, mia-ko commented on samples/crypto/persistent_key_usage/README.rst
> +   For non-TF-M builds, and on nRF54L15 devices, the :ref:`hardware unique key (HUK) <lib_hw_unique_key>` is used to encrypt the key before storing it.`
```suggestion
   In environments without TF-M and on nRF54L15 devices, the :ref:`hardware unique key (HUK) <lib_hw_unique_key>` is used to encrypt the key before storing it.`
```

2024-05-23 08:36 UTC, mia-ko commented on samples/crypto/persistent_key_usage/README.rst
> +* Non TF-M builds use the :ref:`trusted_storage_readme` library
```suggestion
* Builds without TF-M use the :ref:`trusted_storage_readme` library
```

2024-05-23 08:59 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug[nrf52820dongle/nrf52820]***: ***ROM*** size  ***increased by 692[B]*** in comparison to the ***main[0ebb976e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52820dongle/nrf52820) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52kbd/nrf52832]***: ***ROM*** size  ***increased by 624[B]*** in comparison to the ***main[0ebb976e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52810dmouse/nrf52810]***: ***ROM*** size  ***increased by 664[B]*** in comparison to the ***main[0ebb976e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52810dmouse/nrf52810) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52833dk/nrf52820]***: ***ROM*** size  ***increased by 692[B]*** in comparison to the ***main[0ebb976e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52833dk/nrf52820) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52dmouse/nrf52832]***: ***ROM*** size  ***increased by 620[B]*** in comparison to the ***main[0ebb976e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52dmouse/nrf52832) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15418/11)*

2024-05-23 10:12 UTC, vili-nordic approved these changes

2024-05-23 11:08 UTC, mswarowsky commented on samples/crypto/persistent_key_usage/README.rst
> +   For non-TF-M builds, and on nRF54L15 devices, the :ref:`hardware unique key (HUK) <lib_hw_unique_key>` is used to encrypt the key before storing it.`
Discussed offline an changed

2024-05-23 12:36 UTC, mia-ko approved these changes

2024-05-24 10:47 UTC, Vge0rge approved these changes

2024-05-27 13:55 UTC, merged