wifi: hostap: Fix user disconnection request
nrfconnect/sdk-nrf pull request #15415
Opened 2024-05-21 13:00 UTC by kapbh

[SHEL-2326] When user tries to disconnect the shell, it's always printing "Disconnection request failed". Here setting status as 0 when disconnection is requested by user. (wifi disconnect command). If disconnection happens due to any other reason, it will take reason code.

2024-05-21 13:23 UTC, krish2718 requested changes
Actually, why can't we do this? Solves the problem of disconnect reason codes.

```
diff --git a/include/zephyr/net/wifi_mgmt.h b/include/zephyr/net/wifi_mgmt.h
index 70fd5978fba..f9d8ec81f9c 100644
--- a/include/zephyr/net/wifi_mgmt.h
+++ b/include/zephyr/net/wifi_mgmt.h
@@ -389,8 +389,10 @@ enum wifi_conn_status {
  * in the disconnect result event for detailed reason.
  */
 enum wifi_disconn_reason {
+       /** Success, overload status as reason */
+       WIFI_REASON_DISCONN_SUCCESS = 0,
        /** Unspecified reason */
-       WIFI_REASON_DISCONN_UNSPECIFIED = WIFI_STATUS_DISCONN_FIRST_STATUS,
+       WIFI_REASON_DISCONN_UNSPECIFIED,
        /** Disconnected due to user request */
        WIFI_REASON_DISCONN_USER_REQUEST,
        /** Disconnected due to AP leaving */
```

2024-05-21 13:29 UTC, rado17 approved these changes

2024-05-22 05:47 UTC, kapbh commented
> Actually, why can't we do this? Solves the problem of disconnect reason codes.
> 
> ```
> diff --git a/include/zephyr/net/wifi_mgmt.h b/include/zephyr/net/wifi_mgmt.h
> index 70fd5978fba..f9d8ec81f9c 100644
> --- a/include/zephyr/net/wifi_mgmt.h
> +++ b/include/zephyr/net/wifi_mgmt.h
> @@ -389,8 +389,10 @@ enum wifi_conn_status {
>   * in the disconnect result event for detailed reason.
>   */
>  enum wifi_disconn_reason {
> +       /** Success, overload status as reason */
> +       WIFI_REASON_DISCONN_SUCCESS = 0,
>         /** Unspecified reason */
> -       WIFI_REASON_DISCONN_UNSPECIFIED = WIFI_STATUS_DISCONN_FIRST_STATUS,
> +       WIFI_REASON_DISCONN_UNSPECIFIED,
>         /** Disconnected due to user request */
>         WIFI_REASON_DISCONN_USER_REQUEST,
>         /** Disconnected due to AP leaving */
> ```

Ok, we can add that and here we can do change like:

diff --git a/modules/hostap/src/supp_events.c b/modules/hostap/src/supp_events.c
index b9dbbb8e6..fbcd6c336 100644
--- a/modules/hostap/src/supp_events.c
+++ b/modules/hostap/src/supp_events.c
@@ -218,7 +218,7 @@ int send_wifi_mgmt_conn_event(void *ctx, int status_code)
 int send_wifi_mgmt_disc_event(void *ctx, int reason_code)
 {
        struct wpa_supplicant *wpa_s = ctx;
-       int status = wpas_to_wifi_mgmt_diconn_status(reason_code);
+       int status = (reason_code == 0) ? WIFI_REASON_DISCONN_SUCCESS : wpas_to_wifi_mgmt_diconn_status(reason_code);
        enum net_event_wifi_cmd event;
 
        if (!wpa_s || !wpa_s->current_ssid) {

2024-05-22 07:20 UTC, krish2718 commented
```
diff --git a/modules/hostap/src/supp_events.c b/modules/hostap/src/supp_events.c
index cae26bbc603..416c1a3fe07 100644
--- a/modules/hostap/src/supp_events.c
+++ b/modules/hostap/src/supp_events.c
@@ -70,6 +70,9 @@ static enum wifi_conn_status wpas_to_wifi_mgmt_conn_status(int status)
 static enum wifi_disconn_reason wpas_to_wifi_mgmt_diconn_status(int status)
 {
        switch (status) {
+       /* Overload status for success case */
+       case WLAN_STATUS_SUCCESS:
+               return WIFI_REASON_DISCONN_SUCCESS;
        case WLAN_REASON_DEAUTH_LEAVING:
                return WIFI_REASON_DISCONN_AP_LEAVING;
        case WLAN_REASON_DISASSOC_DUE_TO_INACTIVITY:
```
Isn't this enough?

2024-05-23 12:35 UTC, kapbh commented
> > Actually, why can't we do this? Solves the problem of disconnect reason codes.
> > ```
> > diff --git a/include/zephyr/net/wifi_mgmt.h b/include/zephyr/net/wifi_mgmt.h
> > index 70fd5978fba..f9d8ec81f9c 100644
> > --- a/include/zephyr/net/wifi_mgmt.h
> > +++ b/include/zephyr/net/wifi_mgmt.h
> > @@ -389,8 +389,10 @@ enum wifi_conn_status {
> >   * in the disconnect result event for detailed reason.
> >   */
> >  enum wifi_disconn_reason {
> > +       /** Success, overload status as reason */
> > +       WIFI_REASON_DISCONN_SUCCESS = 0,
> >         /** Unspecified reason */
> > -       WIFI_REASON_DISCONN_UNSPECIFIED = WIFI_STATUS_DISCONN_FIRST_STATUS,
> > +       WIFI_REASON_DISCONN_UNSPECIFIED,
> >         /** Disconnected due to user request */
> >         WIFI_REASON_DISCONN_USER_REQUEST,
> >         /** Disconnected due to AP leaving */
> > ```
> 
> While at it can you also change `WIFI_REASON_DISCONN...` to `WIFI_DISCONN_REASON...` ?

Ok. I will change all variable to `WIFI_DISCONN_REASON...`. Hope upstream will Okay with this.

2024-05-29 06:55 UTC, sachinthegreen approved these changes

2024-05-29 07:23 UTC, jukkar approved these changes

2024-05-29 08:02 UTC, krish2718 approved these changes

2024-05-29 08:13 UTC, merged