emds: add preliminary timings for rram
nrfconnect/sdk-nrf pull request #15448
Opened 2024-05-22 14:31 UTC by alxelax

Commit adds preliminary writing timings for flash driver based on rram.

2024-05-22 14:35 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15448/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15448/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15448/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-23 06:48 UTC, mia-ko requested changes
Do we need a changelog entry for this?

2024-05-23 06:48 UTC, mia-ko commented on subsys/emds/Kconfig
> +	  one 32 bytes block.
```suggestion
	  For RRAM-based flash drivers, data is written in blocks of 32 bytes over
	  buffered writing. This value is used to calculate the time to write
	  one 32-byte block.
```

2024-05-23 06:48 UTC, mia-ko commented on subsys/emds/Kconfig
> +	   The default erase block size is 4096 bytes.
```suggestion
	   For RRAM-based flash drivers, the time is defined by the erasing block size.
	   The default erasing block size is 4096 bytes.
```

2024-05-23 07:02 UTC, Andrewpini approved these changes

2024-05-23 07:29 UTC, alxelax commented
> Do we need a changelog entry for this?

No we don't. We didn't release anything related to nrf54l. Nothing to change.

2024-05-23 08:40 UTC, mia-ko approved these changes

2024-05-28 18:57 UTC, merged