doc: 54H gs guide updates
nrfconnect/sdk-nrf pull request #15445
Opened 2024-05-22 11:28 UTC by FrancescoSer

Updated 54H GS guide.

2024-05-22 11:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15445/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15445/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-05-22 22:32 UTC, FrancescoSer commented
This needs cherry-picked commit from https://github.com/nrfconnect/sdk-nrf/pull/15443

2024-05-23 12:10 UTC, annwoj approved these changes

2024-05-23 12:19 UTC, b-gent approved these changes

2024-05-23 12:22 UTC, wiba-nordic approved these changes

2024-05-23 12:25 UTC, greg-fer approved these changes

2024-05-23 12:36 UTC, wiba-nordic requested changes

2024-05-23 12:36 UTC, wiba-nordic commented on samples/multicore/hello_world/README.rst
> +
```suggestion
```
Duplicated include.

2024-05-23 12:36 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/migration/2.4.99-cs3_to_2.6.99-cs2/migration_guide_2.4.99-cs3_to_2.6.99-cs2_application.rst
> +========
```suggestion
--------
```
I think this should be on the same level as the General heading. Not sure if the same is true of the zcbor heading.

2024-05-23 12:58 UTC, merged