Samples: Bluetooth: Mesh: Update light docs to mention FILE_SUFFIX
nrfconnect/sdk-nrf pull request #15453
Opened 2024-05-23 08:38 UTC by ludvigsj

This updates the documentation for the light sample to correctly mention that FILE_SUFFIX now is used to enable the DFU configuration.

2024-05-23 08:40 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15453/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15453/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-05-23 09:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15453
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-23 09:20 UTC, mia-ko requested changes

2024-05-23 09:20 UTC, mia-ko commented on samples/bluetooth/mesh/light/README.rst
> +For more information about using file suffixes, see :ref:`zephyr:important-build-vars` in the Zephyr documentation.
Would this page fit better to reference to? https://docs.nordicsemi.com/bundle/ncs-latest/page/zephyr/develop/application/index.html#application-file-suffixes
Either replacing the existing or in addition.
Or like this:
```suggestion
For more information about using the :ref:`file suffixes <zephyr:application-file-suffixes>`, see :ref:`zephyr:important-build-vars` in the Zephyr documentation.
```

2024-05-28 12:27 UTC, ludvigsj commented
Closing this, superseded by #15543

2024-05-28 12:27 UTC, closed without merging