samples: event_manager_proxy: Adapt to nRF54h20 and sysbuild
nrfconnect/sdk-nrf pull request #15471
Opened 2024-05-23 13:26 UTC by KAGA164

Align the event_manager_proxy sample with sysbuild and nrf54h20 support.

2024-05-23 13:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15471/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15471/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15471/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-23 14:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15471
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-24 05:25 UTC, peknis requested changes

2024-05-24 05:25 UTC, peknis commented on samples/event_manager_proxy/README.rst
> +On nRF5340, by default, the Event Manager Proxy sample uses the OpenAMP backend provided by the IPC Service.
```suggestion
On the nRF5340 DK, this sample uses by default the OpenAMP backend provided by the IPC Service.
```

2024-05-24 05:25 UTC, peknis commented on samples/event_manager_proxy/README.rst
>  #. Program both the cores:
```suggestion
#. Program both cores:
```

2024-05-24 05:25 UTC, peknis commented on samples/event_manager_proxy/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
> + * Mbox for ppr target, one for each sides and one ipc instance
```suggestion
 * Mbox for PPR target, one for each side and one IPC instance
```

2024-05-24 07:48 UTC, KAGA164 commented on samples/event_manager_proxy/README.rst
> +On nRF5340, by default, the Event Manager Proxy sample uses the OpenAMP backend provided by the IPC Service.
Done

2024-05-24 07:49 UTC, peknis approved these changes

2024-05-24 11:22 UTC, dchat-nordic approved these changes

2024-05-28 12:06 UTC, KAGA164 commented on samples/event_manager_proxy/sample.yaml
> +  sample.event_manager_proxy.nrf54h20dk_cpuapp:
It is set globally at the beginning of this file

2024-05-28 15:58 UTC, maje-emb commented on samples/event_manager_proxy/sample.yaml
> +  sample.event_manager_proxy.nrf54h20dk_cpuapp:
I had in mind the field `tags: sysbuild`.
?

2024-06-05 11:37 UTC, grochu approved these changes

2024-06-05 11:46 UTC, merged