Locator Tag: support for remaining targets
nrfconnect/sdk-nrf pull request #15495
Opened 2024-05-24 11:40 UTC by kapi-no

2024-05-24 11:44 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15495/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15495/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15495/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-24 12:44 UTC, mkapala-nordic approved these changes

2024-05-27 11:40 UTC, MarekPieta requested changes

2024-05-27 11:40 UTC, MarekPieta commented on samples/bluetooth/fast_pair/locator_tag/Kconfig
> +	prompt "Application platform"
Should it actually have prompts? There is no need to assign it by the user (property determined by the used board - a supported board could update default here I think).

2024-05-27 11:40 UTC, MarekPieta commented on samples/bluetooth/fast_pair/locator_tag/boards/thingy53_nrf5340_cpuapp.overlay
> +#include "thingy53_nrf5340_cpuapp_common.overlay"
It should be `*.dtsi` file (DTS include). That would separate naming from board-specific overlays and clearly show the intention here.

2024-05-27 11:40 UTC, MarekPieta commented on samples/bluetooth/fast_pair/locator_tag/Kconfig
> +	prompt "Application platform"
Actually maybe we can even rely directly on board Kconfig here?

2024-05-27 12:47 UTC, kapi-no commented
Adding @divipillai due to one minor improvement in the sample Readme (got the "doc-required" label)

2024-05-27 12:50 UTC, divipillai approved these changes

2024-05-27 12:53 UTC, MarekPieta approved these changes

2024-05-27 14:17 UTC, kapi-no commented
Rebased my PR to pass CI. I haven't changed this PR file diff

2024-05-28 07:29 UTC, merged