Fix Event triggers docs and switch watchdog instance for nrf54l15
nrfconnect/sdk-nrf pull request #15525
Opened 2024-05-27 14:10 UTC by ArekBalysNordic

Some parts of the event triggers guide have not been aligned with the recent changes.

wdt30 is reserved for Secure purposes and we need to switch to the wdt31 instance for application purposes.

2024-05-27 14:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15525/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15525/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15525/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-27 14:11 UTC, SebastianBoe approved these changes

2024-05-28 05:27 UTC, kkasperczyk-no approved these changes

2024-05-28 05:52 UTC, wiba-nordic requested changes

2024-05-28 05:52 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/test_event_triggers.rst
> +Activation codes in range from ``0x0000000000000000`` to ``0xFFFFFFFF00000000`` are reserved for Matter stack purposes and should not be defined as custom event triggers.
```suggestion
   Activation codes in range from ``0x0000000000000000`` to ``0xFFFFFFFF00000000`` are reserved for Matter stack purposes and should not be defined as custom event triggers.
```

2024-05-28 05:52 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/test_event_triggers.rst
> +   Here's an example to handle the ``0xFFFFFFFF00010000`` activation code, where 1234 is the event trigger value field:
This doesn't seem to match up with how the terms are used on Line 202.

2024-05-28 07:43 UTC, wiba-nordic approved these changes

2024-05-28 08:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15525
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-28 12:45 UTC, merged