Bluetooth: Mesh: Add note on blocking API calls to CLI headers
nrfconnect/sdk-nrf pull request #15529
Opened 2024-05-27 21:08 UTC by akredalen

Added a note to mesh message APIs that blocking calls must be made from the main cooperative thread only, and not in button handler context or workqueues.

2024-05-27 21:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15529/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15529/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15529/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-27 21:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15529
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-28 08:09 UTC, ludvigsj requested changes
I'm not sure if I like adding this to every single API function. Would it be possible to find a more central location for this note?

2024-05-28 08:09 UTC, ludvigsj commented on include/bluetooth/mesh/gen_battery_cli.h
> + * button handlers or workqueues.
They probably _can_ be used in a workqueue, if you set it up to run in a thread with correct priority, I think. Suggest to change to
```suggestion
 * button handlers or the system workqueue.
```

2024-05-28 08:18 UTC, akredalen commented
> I'm not sure if I like adding this to every single API function. Would it be possible to find a more central location for this note?

I am not sure either. At least now it is very clear whenever using the API. I did consider finding a more centralized location for this note, but I worry it might end up being too hidden and thereby useless. Any suggestions?

2024-05-29 09:05 UTC, alxelax requested changes

2024-05-29 09:05 UTC, alxelax commented on include/bluetooth/mesh/gen_loc_cli.h
> + * @note Blocking calls must be made from the main cooperative thread only. Do not use in
> 
Blocking calls must be made from the threads, blocking of which doesn't disrupt functionality of Zephyr system services. Do not use blocking calls from interrupt handlers (for example button handlers) and kernel services (for example the system work queue handlers).

2024-05-29 10:22 UTC, akredalen commented
Any opinion about where to add this note, @alxelax? See Ludvig's comment.

2024-05-29 10:26 UTC, alxelax commented
> Any opinion about where to add this note, @alxelax? See Ludvig's comment.

In general, I agree with Ludvig, but I do not have any good suggestion for this. I leave it up to your decision.

2024-05-29 10:41 UTC, alxelax commented
Probably this page: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/bluetooth_services/mesh/model_types.html
as `Common rule of the model's blocking API` 
but again, if you think this is bad idea just ignore this comment

2024-05-29 10:52 UTC, akredalen commented
> Probably this page: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/bluetooth_services/mesh/model_types.html as `Common rule of the model's blocking API` but again, if you think this is bad idea just ignore this comment

Great! Thanks. I agree this is a logical place to add the note. It might not be the most obvious place for a user to check before using the API but I still think it is good enough for now. We could relocate later if we see the need to do so.

2024-05-29 12:29 UTC, alxelax approved these changes

2024-05-29 13:06 UTC, ludvigsj approved these changes

2024-05-30 07:12 UTC, Andrewpini approved these changes

2024-05-30 10:50 UTC, mia-ko approved these changes
LGTM
The placement looks ok as well, let's see if we need any changes if any feedback comes from the customers.
And I always ask this... do we need a changelog entry? :)

2024-05-31 07:13 UTC, merged