Samples: Bluetooth: Mesh: Use overlay for DFU in Light sample
nrfconnect/sdk-nrf pull request #15543
Opened 2024-05-28 12:25 UTC by ludvigsj

This makes the DFU-specific project configuration an extra configuration file overlay instead of using FILE_SUFFIX with a separate configuration file. It also updates the documentation to describe how to build the DFU-supported configuration.

2024-05-28 12:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15543/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15543/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15543/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-28 13:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15543
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-05-28 13:25 UTC, Andrewpini approved these changes

2024-05-29 05:50 UTC, HaavardRei approved these changes

2024-05-29 10:47 UTC, mia-ko requested changes

2024-05-29 10:47 UTC, mia-ko commented on samples/bluetooth/mesh/light/README.rst
> +For more information about selecting a sysbuild configuration file, see the section about the "Sysbuild Kconfig file" in the page :ref:`zephyr:sysbuild` in the Zephyr documentation.
```suggestion
For more information about selecting a sysbuild configuration file, see the section about the sysbuild Kconfig file on the :ref:`zephyr:sysbuild` page in the Zephyr documentation.
```
Or alternatively: see the Sysbuild Kconfig file section on the XX page...

2024-05-29 10:48 UTC, mia-ko reviewed
Btw, does this require a changelog entry?

2024-05-29 12:43 UTC, ludvigsj commented
> Btw, does this require a changelog entry?

I was thinking no, since this is a sample and won't affect existing users with existing applications? It's more of a consequence of the global switch to samples using sysbuild. But I can add one if you think it's needed?

2024-05-30 09:03 UTC, mia-ko commented
> > Btw, does this require a changelog entry?
> 
> I was thinking no, since this is a sample and won't affect existing users with existing applications? It's more of a consequence of the global switch to samples using sysbuild. But I can add one if you think it's needed?

I guess this global switch will be mentioned somewhere, so we don’t have to do it sample by sample, so we drop the changelog entry.

2024-05-30 09:04 UTC, mia-ko approved these changes

2024-05-31 07:12 UTC, merged