doc: working_with_nrf: restructuring of nRF52 Series
nrfconnect/sdk-nrf pull request #15598
Opened 2024-05-30 12:44 UTC by divipillai

Renamed Working with to Developing with.
Removed "Developing with" pages.
Created separate pages for the contents
in the developing with guide.

2024-05-30 13:35 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15598
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-05 08:05 UTC, kittydepa approved these changes
Approving but one question about the order of the docs, on the ``device_guides.rst`` page - were these grouped together in a specific way? If not, could that be addressed after RC1?

2024-06-05 08:34 UTC, greg-fer requested changes

2024-06-05 08:34 UTC, greg-fer commented on doc/nrf/device_guides/nrf52/testing.rst
> +##########################################
Do we really need this page? It is repeating a scenario from a sample Testing section, and somewhat repeating https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/gsg_guides/nrf52_gs.html#testing_the_sample .

2024-06-05 08:34 UTC, greg-fer commented on doc/nrf/device_guides/nrf52/testing.rst
> +To perform the test, :ref:`connect to the nRF52 Series DK <nrf52_gs_connecting>` and complete the following steps:
If this page is kept, it should rather point to https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/test_and_optimize.html and not the getting started guide.

2024-06-05 13:59 UTC, divipillai commented
> Approving but one question about the order of the docs, on the `device_guides.rst` page - were these grouped together in a specific way? If not, could that be addressed after RC1?

discussed offline and no changes are required.

2024-06-05 15:26 UTC, zycz approved these changes

2024-06-06 06:29 UTC, divipillai commented on doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
> +==============================
Please note the header level issue with the "FOTA update sample" section will be fixed in PR https://github.com/nrfconnect/sdk-nrf/pull/15708.

2024-06-06 06:33 UTC, greg-fer commented on doc/nrf/device_guides/nrf52/testing.rst
> +##########################################
I don't think it makes sense to keep this page here. There are other samples that have testing scenarios for 2+ development kits, yet here we specifically refer to Peripheral UART. This whole page should rather be a subsection of https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/samples/bluetooth/peripheral_uart/README.html#testing

This whole page was once moved from Infocenter, where it maybe had its purpose, but in the NCS it is redundant.
Re https://github.com/nrfconnect/sdk-nrf/commit/8796a90ba355899c6eafbaf3c68f2488049277b8#diff-5c5fa22b8c1b99fc19b85717fe5a405395e647a4a0f82a7326744c56e35cd4b2

2024-06-06 06:34 UTC, greg-fer approved these changes
I think the nrf52/testing.rst should be removed. Other edits look ok.

2024-06-06 07:53 UTC, divipillai commented
> I think the nrf52/testing.rst should be removed. Other edits look ok.

I will cover this in a separate PR. Move the testing section to the Peripheral UART sample.

2024-06-06 08:19 UTC, merged