suit: require SUIT_ENVELOPE_TARGET to access data
nrfconnect/sdk-nrf pull request #15622
Opened 2024-05-31 12:51 UTC by e-rk

When building the manifest, the CONFIG_SUIT_ENVELOPE_TARGET is now required to access the data of the application.
The build system no longer automatically includes all sysbuild image data into manifest build.

2024-05-31 12:52 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| suit-generator | https://github.com/nrfconnect/suit-generator/commit/72e873da8201d8f48e2821ee0ae1b076e081cc5d (ncs) | https://github.com/nrfconnect/suit-generator/pull/119 | [nrfconnect/suit-generator#119/files](https://github.com/nrfconnect/suit-generator/pull/119/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-05-31 12:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15622/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15622/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-dfu | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15622/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-05-31 13:28 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15622
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-03 15:27 UTC, ahasztag requested changes
I think I need a call to see if this won't break the recovery application build.

For the recovery application, `CONFIG_SUIT_LOCAL_ENVELOPE_GENERATE` is set to n, yet the `application` data is still required in the manifest. Won't this PR break it?

2024-06-04 06:44 UTC, ahasztag requested changes

2024-06-04 06:44 UTC, ahasztag commented on cmake/sysbuild/suit.cmake
> -      --core ${target},${SUIT_ROOT_DIRECTORY}${target}.bin,${BINARY_DIR}/zephyr/edt.pickle,${BINARY_DIR}/zephyr/.config
This seems dangerous, couldn't we leave this part and change it to:

`--core ${target},${SUIT_ROOT_DIRECTORY}${image}.bin,${BINARY_DIR}/zephyr/edt.pickle,${BINARY_DIR}/zephyr/.config`

to fix the problem that `${target}.bin` won't be available?

2024-06-05 09:36 UTC, ahasztag approved these changes

2024-06-05 09:56 UTC, tomchy approved these changes

2024-06-05 10:52 UTC, merged