doc: add Thread related known issue
nrfconnect/sdk-nrf pull request #15642
Opened 2024-06-03 09:35 UTC by edmont

Document Thread known issue:
High power consumption after parent loss.

2024-06-03 09:49 UTC, wiba-nordic requested changes

2024-06-03 09:49 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  After a parent loss, a SED would keep the radio on in between reattach attempts.
```suggestion
  After a parent loss, an SED would keep the radio on between reattach attempts.
```

2024-06-03 10:05 UTC, wiba-nordic approved these changes

2024-06-03 10:44 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15642
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-04 09:53 UTC, maciejbaczmanski approved these changes

2024-06-06 09:36 UTC, merged