Issue27583 dfu confchannel
nrfconnect/sdk-nrf pull request #15668
Opened 2024-06-03 16:45 UTC by zycz

2024-06-03 17:26 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15668
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-04 19:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15668/4/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15668/4/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15668/4/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-04 20:46 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 28159[B]*** in comparison to the ***main[2f920a38]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 24048[B]*** in comparison to the ***main[2f920a38]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 28191[B]*** in comparison to the ***main[2f920a38]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 35220[B]*** in comparison to the ***main[2f920a38]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15668/5)*

2024-06-05 08:22 UTC, MarekPieta requested changes

2024-06-05 08:22 UTC, MarekPieta commented on scripts/hid_configurator/modules/dfu.py
> +    from suit_generator.envelope import SuitEnvelope
Could we squash commits related to HID configurator? The second commit removes most of the changes applied by the first one

2024-06-05 08:22 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +#define FLASH_CLEAN_VAL_64	UINT64_MAX
Consider using `flash_area_erased_val`

2024-06-05 08:22 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +	if (store_size < (4 * sizeof(uint32_t))) {
Can we rely on: `flash_get_write_block_size`? That would make implementation more generic

2024-06-05 08:22 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +	if (store_size < (4 * sizeof(uint32_t))) {
Also I would make flash aligning as a separate commit.

2024-06-05 08:59 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +	if ((store_size > (4 * sizeof(uint32_t))) &&
can we put alignment value (`4 * sizeof(uint32_t)`) into the define or const?

2024-06-05 08:59 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +	BUILD_ASSERT((sizeof(sync_buffer) % (4 * sizeof(uint32_t))) == 0);
Previously there was alignment to the `sizeof(uint32_t)` for all NVM and now it has been changed to the 4 times original value.
Will it still be good for all old targets?

2024-06-05 12:44 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +			LOG_INF("DFU started");
```suggestion

		LOG_INF("DFU started");
```

2024-06-05 12:49 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +static int erased_val;
Function later used uses `uint8_t` as far as i can see (`uint8_t flash_area_erased_val(const struct flash_area *fap);`)

2024-06-05 12:52 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +			if (buf[j] != erased_val) {
Will it work? `erased_val` will be equal to `0xFF` as far as I understand as the used function returns the `uint8_t`.

2024-06-05 12:54 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +			if (buf[j] != erased_val) {
Example from mcumgr how they do it:
```
#define ERASED_VAL_32(x) (((x) << 24) | ((x) << 16) | ((x) << 8) | (x))

uint8_t erased_val;
uint32_t erased_val_32;

erased_val = flash_area_erased_val(fa);
erased_val_32 = ERASED_VAL_32(erased_val);
```

2024-06-05 12:54 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +			sync_buffer[store_offset + store_size + i] = erased_val & 0xFF;
If you would change the erased_val to uint8_t you would not need `& 0xFF`

2024-06-05 12:56 UTC, mkapala-nordic commented on applications/nrf_desktop/src/modules/dfu.c
> +static int flash_write_block;
this should be `uint32_t` -> `uint32_t flash_area_align(const struct flash_area *fa);`

2024-06-05 14:09 UTC, mkapala-nordic approved these changes

2024-06-05 14:23 UTC, MarekPieta requested changes

2024-06-05 14:23 UTC, MarekPieta commented on scripts/hid_configurator/modules/dfu.py
> +    print('The SUIT generator Python package is necassary to handle device with SUIT bootloader')
`SUIT bootloader` -> `SUIT`

2024-06-05 14:23 UTC, MarekPieta commented on scripts/hid_configurator/modules/dfu.py
> +    print('Please install the SUIT generator from ncs/modules/lib/suit-generator')
`The SUIT generator can be installed from ncs/modules/lib/suit-generator`

2024-06-05 14:23 UTC, MarekPieta commented on scripts/hid_configurator/modules/dfu.py
> +            print("Invalid sequence number type")
Can we print the invalid version? (would be helpful for debugging)

2024-06-05 14:23 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/Kconfig.config_channel
> +	select SOC_FLASH_NRF_MRAM_ONE_BYTE_WRITE_ACCESS if SOC_FLASH_NRF_MRAM
`SOC_FLASH_NRF_MRAM_ONE_BYTE_WRITE_ACCESS` no longer exists

2024-06-05 14:23 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +		LOG_ERR("suit_read_manifest_data failed (err: %d)", err);
Function no longer used, please update log

2024-06-05 14:23 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +		}
Can we use `memset` here?

2024-06-05 14:23 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +		erased_val_32 = ERASED_VAL_32(erased_val);
Since you introduced a macro, I think there is no need to cache this one

2024-06-05 14:23 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/dfu.c
> +		flash_write_block = flash_area_align(flash_area);
Also, could we perform the assignments and do the checks on boot? So that user would instantly be notified about invalid configuration

2024-06-05 15:39 UTC, MarekPieta approved these changes

2024-06-05 20:40 UTC, kapi-no commented
Debased. No file diff has changed

2024-06-05 21:31 UTC, kapi-no approved these changes

2024-06-05 22:02 UTC, kapi-no commented
Rebased. No file diff has changed

2024-06-06 05:44 UTC, kapi-no commented on applications/nrf_desktop/src/modules/dfu.c
> +			flash_write_block_size = flash_area_align(flash_area);
Bus fault due to the mem pointer access

2024-06-06 05:44 UTC, kapi-no requested changes

2024-06-06 05:44 UTC, kapi-no commented on applications/nrf_desktop/src/modules/dfu.c
> +			flash_write_block_size = flash_area_align(flash_area);
Bus fault due to the mem pointer access

2024-06-06 05:57 UTC, kapi-no approved these changes

2024-06-06 07:15 UTC, merged