net: lib: nrf_cloud: add support for mqtt shadow transform requests
nrfconnect/sdk-nrf pull request #15670
Opened 2024-06-03 17:36 UTC by jayteemo

Support shadow transform (JSONata) requests over MQTT.
IRIS-8721

2024-06-03 19:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15670/4/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15670/4/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-sdk-mcuboot | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15670/4/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-05 10:30 UTC, shanthanordic commented
No approvals yet and CI RED moving it out of NCS 2.7.0

2024-06-05 16:27 UTC, plskeggs approved these changes

2024-06-18 21:39 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/7cdba410507f1edd6af13aa723628f7f95a465d9 | https://github.com/nrfconnect/sdk-zephyr/commit/3611f46f85c0980c19b60bb842033cbaba35e023 (main) | [nrfconnect/sdk-zephyr@7cdba410..3611f46f](https://github.com/nrfconnect/sdk-zephyr/compare/7cdba410507f1edd6af13aa723628f7f95a465d9..3611f46f85c0980c19b60bb842033cbaba35e023) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-08-27 22:50 UTC, glarsennordic approved these changes

2024-08-27 22:50 UTC, glarsennordic commented on include/net/nrf_cloud_codec.h
> +};
I'm not sold on this needing to be its own struct, but I don't feel super strongly

2024-08-27 22:50 UTC, glarsennordic commented on include/net/nrf_cloud_codec.h
> +};
otherwise LGTM

2024-09-10 00:33 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 19
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-09-30 07:18 UTC, peknis requested changes

2024-09-30 07:18 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +      Functionality is enabled by the Kconfig option :kconfig:option:`CONFIG_NRF_CLOUD_MQTT_SHADOW_TRANSFORMS`.
```suggestion
      This functionality is enabled by the :kconfig:option:`CONFIG_NRF_CLOUD_MQTT_SHADOW_TRANSFORMS` Kconfig option.
```

2024-09-30 07:18 UTC, peknis commented on include/net/nrf_cloud.h
> + *        The application will receive response data in a
```suggestion
 *        The application will receive response data in an
```

2024-10-04 05:30 UTC, peknis approved these changes

2024-10-07 08:10 UTC, nordicjm approved these changes

2024-10-08 07:26 UTC, rlubos approved these changes

2024-10-08 07:27 UTC, merged