doc: wifi: add random mac address changelog entry
nrfconnect/sdk-nrf pull request #15711
Opened 2024-06-04 15:44 UTC by hlord2000

Adds entry explaining new random MAC Kconfig

2024-06-04 15:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15711/2/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15711/2/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-06-05 19:16 UTC, krish2718 approved these changes

2024-06-05 19:39 UTC, richabp requested changes

2024-06-05 19:39 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for random MAC address generation at boot using :kconfig:option:`CONFIG_WIFI_RANDOM_MAC_ADDRESS`.
```suggestion
* Added support for random MAC address generation at boot using the :kconfig:option:`CONFIG_WIFI_RANDOM_MAC_ADDRESS` Kconfig option.
```

2024-06-05 19:45 UTC, hlord2000 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added support for random MAC address generation at boot using :kconfig:option:`CONFIG_WIFI_RANDOM_MAC_ADDRESS`.
Changed :+1:

2024-06-05 20:22 UTC, richabp approved these changes

2024-06-06 06:29 UTC, kittydepa approved these changes

2024-06-06 07:28 UTC, merged