Bluetooth: Add hci_vs_sdc.h which expose wrappers VS HCI commands
nrfconnect/sdk-nrf pull request #15798
Opened 2024-06-06 12:32 UTC by rugeGerritsen

The SDC provides vendor specific Bluetooth functionality through vendor specific HCI commands.
The APIs added in this commit handles:
 - Building the VS HCI commands
 - Sending the VS HCI command to the controller. This works both when the controller is on the same core, or if the controller is separated from the host by another HCI layer.
 - Return parameters

This removes the need for boilerplate code in applications.

Some of the vendor specific APIs take in handles.
Those can be obtained from host types using the APIs defined in `zephyr/bluetooth/hci.h`.

The API documentation is referring to the HCI command documentation to avoid duplication.

2024-06-06 12:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15798/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15798/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15798/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-06 13:28 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug.usb_next[nrf52840gmouse/nrf52840]***: ***ROM*** size  ***increased by 1164[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=usb_next&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_mcuboot_smp.nrf52840gmouse[nrf52840gmouse/nrf52840]***: ***ROM*** size  ***increased by 1172[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_mcuboot_smp&var-testcase=nrf52840gmouse&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 37533[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 48330[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_fast_pair.gmouse[nrf52840gmouse/nrf52840]***: ***ROM*** size  ***increased by 996[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_fast_pair&var-testcase=gmouse&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf21540ek[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1052[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf21540ek&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_wwcb[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1012[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_wwcb&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebugwithshell[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1064[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebugwithshell&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease.nrf52kbd[nrf52kbd/nrf52832]***: ***ROM*** size  ***increased by 1112[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=nrf52kbd&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52840gmouse/nrf52840]***: ***ROM*** size  ***increased by 1012[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_keyboard[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1180[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_fast_pair.keyboard[nrf52kbd/nrf52832]***: ***ROM*** size  ***increased by 1100[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_fast_pair&var-testcase=keyboard&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1012[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52kbd/nrf52832]***: ***ROM*** size  ***increased by 1216[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_keyboard.usb_next[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 1336[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=usb_next&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_mcuboot_smp.nrf52840dk[nrf52840dk/nrf52840]***: ***ROM*** size  ***increased by 980[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_mcuboot_smp&var-testcase=nrf52840dk&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 38170[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testca [...]

2024-06-07 07:38 UTC, alwa-nordic requested changes

2024-06-07 07:38 UTC, alwa-nordic commented on subsys/bluetooth/hci_vs_sdc.c
> +	buf = bt_hci_cmd_create(opcode, 0);
`buf` is never used, so this just leaks a buffer

2024-06-07 10:36 UTC, alwa-nordic approved these changes

2024-06-10 10:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15798
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-10 11:00 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug[nrf54l15pdk/nrf54l15/cpuapp]***: ***ROM*** size  ***increased by 512[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf54l15pdk/nrf54l15/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_keyboard[nrf54l15pdk/nrf54l15/cpuapp]***: ***ROM*** size  ***increased by 512[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=none&var-arch=arm&var-platform=nrf54l15pdk/nrf54l15/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 38170[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 72710[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 37533[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 48394[B]*** in comparison to the ***main[0411564e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15798/9)*

2024-06-10 11:07 UTC, theob-pro approved these changes

2024-06-11 06:44 UTC, KAGA164 approved these changes
LGTM

2024-07-09 09:03 UTC, merged