doc: Bluetooth RPC Host related documentation updates
nrfconnect/sdk-nrf pull request #15793
Opened 2024-06-06 11:48 UTC by ppryga-nordic

There were updated documentation related to Bluetooth RPC host interface in following parts of SDK:

    nordic-bt-rpc snippet
    BLE RPC subsystem
    ipc_radio
    peripheral_uart

2024-06-06 11:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15793/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15793/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-06-06 12:15 UTC, dchat-nordic approved these changes

2024-06-06 12:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15793
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-10 05:29 UTC, peknis requested changes

2024-06-10 05:29 UTC, peknis commented on snippets/nordic-bt-rpc/README.rst
> +For example in the nRF54H20 SoC it is radio core.
```suggestion
For example in the nRF54H20 SoC, it is the radio core.
```

2024-06-10 05:29 UTC, peknis commented on snippets/nordic-bt-rpc/README.rst
> +   For the nRF54H20 SoC the snippet modifies the memory map to make room for settings storage for the radio core.
```suggestion
   On the nRF54H20 SoC, the snippet modifies the memory map to make room for settings storage for the radio core.
```

2024-06-10 05:48 UTC, ppryga-nordic commented on snippets/nordic-bt-rpc/README.rst
> +For example in the nRF54H20 SoC it is radio core.
Corrected

2024-06-10 05:48 UTC, ppryga-nordic commented on snippets/nordic-bt-rpc/README.rst
> +   For the nRF54H20 SoC the snippet modifies the memory map to make room for settings storage for the radio core.
Corrected

2024-06-10 06:10 UTC, peknis approved these changes

2024-06-10 07:16 UTC, merged