bl_storage: Change key invalidation to be more strict
nrfconnect/sdk-nrf pull request #15848
Opened 2024-06-10 10:07 UTC by oyvindronningstad

Also fix the bl_validation test to put the key at the end and add debug keys.

2024-06-10 10:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15848/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15848/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-mcuboot | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15848/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-10 12:57 UTC, nvlsianpu approved these changes

2024-06-11 10:28 UTC, pdunaj requested changes

2024-06-11 10:28 UTC, pdunaj commented on subsys/bootloader/bl_storage/bl_storage.c
> +	if (key_idx > num_public_keys_read()) {
shouldn't it be `>=`?

2024-06-11 11:18 UTC, oyvindronningstad commented on subsys/bootloader/bl_storage/bl_storage.c
> +	if (key_idx > num_public_keys_read()) {
You're right. Fixed.

2024-06-11 11:38 UTC, pdunaj requested changes

2024-06-11 11:38 UTC, pdunaj commented on subsys/bootloader/bl_storage/bl_storage.c
> +	if (num_public_keys_read() >= MAX_NUM_PUBLIC_KEYS) {
This was correct in the earlier version.
In this case it should be simply `>`. This is a number of keys that is checked here not an index (like in line 84).

2024-06-11 15:55 UTC, nvlsianpu commented
Verified that patch is working correctly.
Need to apply Pawel's remark.

2024-06-11 15:55 UTC, nvlsianpu approved these changes

2024-06-11 15:56 UTC, nvlsianpu requested changes
as above

2024-06-12 12:16 UTC, pdunaj approved these changes

2024-06-12 12:26 UTC, nvlsianpu approved these changes

2024-06-12 13:08 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug_keyboard.usb_next[nrf52840dk/nrf52840]***: ***RAM*** size  ***increased by 432[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=usb_next&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_mcuboot_smp.nrf52840gmouse[nrf52840gmouse/nrf52840]***: ***RAM*** size  ***increased by 336[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_mcuboot_smp&var-testcase=nrf52840gmouse&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 576[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 576[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52kbd/nrf52832]***: ***RAM*** size  ***increased by 432[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease.nrf52kbd[nrf52kbd/nrf52832]***: ***RAM*** size  ***increased by 432[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=nrf52kbd&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease_fast_pair.keyboard[nrf52kbd/nrf52832]***: ***RAM*** size  ***increased by 1016[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease_fast_pair&var-testcase=keyboard&var-arch=arm&var-platform=nrf52kbd/nrf52832) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_keyboard[nrf54l15pdk/nrf54l15/cpuapp]***: ***RAM*** size  ***increased by 432[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=none&var-arch=arm&var-platform=nrf54l15pdk/nrf54l15/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_mcuboot_smp.nrf52840dk[nrf52840dk/nrf52840]***: ***RAM*** size  ***increased by 336[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_mcuboot_smp&var-testcase=nrf52840dk&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_fast_pair.gmouse[nrf52840gmouse/nrf52840]***: ***RAM*** size  ***increased by 336[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_fast_pair&var-testcase=gmouse&var-arch=arm&var-platform=nrf52840gmouse/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_keyboard[nrf52840dk/nrf52840]***: ***RAM*** size  ***increased by 432[B]*** in comparison to the ***main[8c3b7017]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_keyboard&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-15848/4)*

2024-06-12 14:00 UTC, pdunaj requested changes

2024-06-12 14:00 UTC, pdunaj commented on subsys/bootloader/bl_storage/bl_storage.c
> +	NVIC_SystemReset();
I don't understand this change. Can you tell why it was needed?

I expect it should use a system oops or panic, which in release version should reboot. If it does not we have a problem in the entire system.
BTW - how are other fatal errors handled in NSIB?

2024-06-12 14:28 UTC, pdunaj commented
> nrf54h20[nrf54h20dk/nrf54h20/cpuapp

Hi @miha-nordic , this change modifies NSIB but log in memory consumption increase shows regression in builds that do not use it (based on SUIT and MCUBoot). Is it some false positive or an issue in check itself?

2024-06-13 08:53 UTC, pdunaj approved these changes

2024-06-13 10:37 UTC, pdunaj commented
@shanthanordic , this can go in

2024-06-13 11:20 UTC, merged