[nrf noup] scripts: update quarantine for zephyr samples.
nrfconnect/sdk-nrf pull request #15850
Opened 2024-06-10 11:36 UTC by nordic-babu

Tests were fixed in https://github.com/nrfconnect/sdk-zephyr/pull/1777 and https://github.com/nrfconnect/sdk-mcuboot/pull/316.

2024-06-10 11:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15850/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15850/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15850/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-10 11:43 UTC, nordic-piks approved these changes

2024-06-10 11:44 UTC, nordic-segl approved these changes

2024-06-11 16:02 UTC, nvlsianpu approved these changes

2024-06-11 20:37 UTC, anangl approved these changes

2024-06-12 07:24 UTC, PerMac commented
I think it shouldn't have [noup patch] in the name/commit, since it is pure nrf PR (not addressing any upstream), but maybe it is acceptable?

2024-06-12 07:28 UTC, anangl commented
> I think it shouldn't have [noup patch] in the name/commit, since it is pure nrf PR (not addressing any upstream), but maybe it is acceptable?

You're right. This tag should be removed. I overlooked this.

2024-06-12 07:28 UTC, anangl requested changes
Please remove the `[nrf noup]` tag from the commit title.

2024-06-12 07:42 UTC, PerMac commented
I added CI disabled label so the change won't require the CI to run

2024-06-13 08:30 UTC, anangl commented
> > Please remove the `[nrf noup]` tag from the commit title.
> 
> done

What's the point in having `[noup patch]` instead?

2024-06-13 08:33 UTC, nordic-babu commented
> > > Please remove the `[nrf noup]` tag from the commit title.
> > 
> > 
> > done
> 
> What's the point in having `[noup patch]` instead?

yes, sorry misunderstood your comments

2024-06-13 08:34 UTC, anangl approved these changes

2024-06-14 05:56 UTC, shanthanordic commented
@gchwier  FYI

2024-06-14 06:00 UTC, merged