Fix FEM SHIELDS for sysbuild
nrfconnect/sdk-nrf pull request #15862
Opened 2024-06-10 13:47 UTC by ankuns

When application was built with sysbuild the -DSHIELD=shield is passed to all sub-images involved in the build.
```
west build --sysbuild nrf5340dk/nrf5340/cpunet -- -DSHIELD=nrf21540ek
```
lead to boards/shields/nrf21540ek/nrf21540ek.overlay to be applied to image for cpuapp what is incorrect.

Moreover attempt to use single -DSHIELD on command required detection of the shield in sysbuild.cmake and applying appropriate pin forwarder overlay to the cpuapp. This required explicit handling of a shield within sysbuild.cmake and didn't scale for other FEM shields.

The samples radio_test an direct_test_mode are fixed.

2024-06-10 13:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15862/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15862/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15862/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-10 15:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15862
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-11 07:29 UTC, peknis requested changes

2024-06-11 07:29 UTC, peknis commented on doc/nrf/includes/sample_dtm_radio_test_fem.txt
> +   If you use the nRF21540 EK with SoCs of nRF52 family, append ``nrf21540ek`` shield to your build command instructing build system to append the appropriate devicetree overlay file.
```suggestion
   If you use the nRF21540 EK with SoCs of nRF52 Series, append the ``nrf21540ek`` shield to your build command instructing the build system to use the appropriate devicetree overlay file.
```

2024-06-11 07:29 UTC, peknis commented on doc/nrf/includes/sample_dtm_radio_test_fem.txt
> +   If you use the nRF21540 EK with nRF5340 SoC, append the ``nrf21540ek_fwd`` shield to your build command for the application core image and the ``nrf21540ek`` shield to the network core image.
```suggestion
   If you use the nRF21540 EK with nRF5340 SoC, append the ``nrf21540ek_fwd`` shield to your build command for the application core image and the ``nrf21540ek`` shield for the network core image.
```

2024-06-11 07:41 UTC, dchat-nordic requested changes
The PR adds 2 shield configurations, but it's shown as bugfix - it's not ok.
The way of CMake modification can break some build.
This PR needs work.

2024-06-11 07:41 UTC, dchat-nordic commented on samples/peripheral/radio_test/sample.yaml
> +    tags: ci_build sysbuild
This PR is a bugfix. The release is in the bugfix state. Adding more features like supported shields to samples is not good.

2024-06-11 07:41 UTC, dchat-nordic commented on doc/nrf/includes/sample_dtm_radio_test_fem.txt
>  For example, to build the sample from the command line for an nRF5340 DK with an attached nRF21540 EK, invoke the following command within the sample directory:
This line says 'following command' but there are 3 commands each for different case. Please clarify

2024-06-11 07:41 UTC, dchat-nordic commented on samples/bluetooth/direct_test_mode/README.rst
> +   west build samples/bluetooth/direct_test_mode -b nrf5340dk/nrf5340/cpunet --sysbuild -- -Ddirect_test_mode_SHIELD=nrf21540ek -DFILE_SUFFIX=usb
This doesn't add the shield for app core remote_shell

2024-06-11 07:41 UTC, dchat-nordic commented on samples/bluetooth/direct_test_mode/sysbuild.cmake
> -  string(REPLACE " " ";" shield_list "${SHIELD}")
This should stay, but be changed to add the overlay for example for remote_hci with FEM. This will break.

2024-06-11 08:09 UTC, ankuns commented
You are code owners, if your point of view is https://github.com/nrfconnect/sdk-nrf/pull/15862#discussion_r1634336699 I have no option than decline, because the main goal of this PR is to have these apps buildable with the new shields.

2024-06-11 08:09 UTC, closed without merging