doc improvement: Update samples and apps with Thingy:91 X
nrfconnect/sdk-nrf pull request #15879
Opened 2024-06-11 06:40 UTC by divipillai

* Update samples and apps with Thingy:91 X, for the samples and apps the support are added.
* Asset Tracker v2
* Connectivity bridge
* Serial LTE modem
* Memfault sample
* MQTT sample

2024-06-11 06:49 UTC, MarkusLassila commented on doc/nrf/links.txt
> +.. _	: https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme688/
Something missing?

2024-06-11 07:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15879
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-11 07:59 UTC, wiba-nordic requested changes

2024-06-11 07:59 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/slm_testing.rst
> +Complete the following steps to test the functionality provided by the i2c sensors on the Thingy:91 and Thingy:91 X using the two-wire interface (TWI):
```suggestion
Complete the following steps to test the functionality provided by the i2c sensors on the Thingy:91 or Thingy:91 X using the two-wire interface (TWI):
```

2024-06-11 07:59 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/slm_testing.rst
> +   As the devices connect to the sensors through i2c2, it shows that TWI2 is available:
```suggestion
   As the device connects to the sensors through i2c2, it shows that TWI2 is available:
```

2024-06-11 07:59 UTC, wiba-nordic commented on samples/debug/memfault/README.rst
> +The sample connects to an LTE network using an nRF91 Series DK or a Thingy:91, or a Thingy:91 X, or to Wi-Fi®  using the nRF7002 DK, and sends the collected data to Memfault's cloud using HTTPS.
```suggestion
The sample connects to an LTE network using an nRF91 Series DK, a Thingy:91, or a Thingy:91 X, or to Wi-Fi®  using the nRF7002 DK, and sends the collected data to Memfault's cloud using HTTPS.
```

2024-06-11 10:07 UTC, MarkusLassila approved these changes
SLM ok

2024-06-13 08:08 UTC, wiba-nordic approved these changes

2024-06-13 08:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15879/3/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15879/3/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-06-13 10:04 UTC, maxd-nordic approved these changes

2024-06-13 16:49 UTC, merged