Bluetooth: select `CONFIG_CTLR_CRYPTO_SUPPORT`
nrfconnect/sdk-nrf pull request #15886
Opened 2024-06-11 09:21 UTC by jori-nordic

This is a dependency of the Softdevice Controller.

Since a66baa1101ad82cb708e27e465c25180e81adaae, this symbol now gates:
- ENTROPY_GENERATOR
- `bluetooth/controller/crypto.c`, which provides `bt_rand()`

2024-06-11 09:25 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15886/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15886/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15886/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-11 10:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15886
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-11 12:03 UTC, ilhanates approved these changes

2024-06-12 07:51 UTC, cvinayak requested changes

2024-06-12 07:51 UTC, cvinayak commented on subsys/bluetooth/controller/Kconfig
> +	select BT_CTLR_CRYPTO_SUPPORT
This is not in sdk-zephyr yet

2024-08-27 00:29 UTC, closed without merging