applications: serial_lte_modem: data mode support for object /19
nrfconnect/sdk-nrf pull request #15909
Opened 2024-06-11 13:01 UTC by kacperradoszewski

The test specification of a certain carrier requires to test the upper limit of data set through the AT#XCARRIER="app_data_set". This cannot be set through a single command and so must be done via data mode. Change the format of the command to accept the target URI path as a string to be tokenized.

2024-06-11 13:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15909/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15909/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15909/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-11 13:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15909
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-11 14:52 UTC, shanthanordic commented
Why shoud this be part of NCS 2.7.0 after RC-1 Tag ? @nordic-hani

2024-06-12 01:13 UTC, junqingzou commented
Command-mode AT command has a buffer up to 4K so 768*2 is not an issue.
#define SLM_AT_MAX_CMD_LEN   4096
uint8_t slm_at_buf[SLM_AT_MAX_CMD_LEN + 1];

Pay attention to the receiving buffer and recommend using heap memory to receive the large data, instead of stack variable.

2024-06-12 04:50 UTC, wiba-nordic requested changes

2024-06-12 04:50 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<uri_path>`` is a string in double quotes indicating the target URI path. This command currently support two possible URI paths:
```suggestion
  ``<uri_path>`` is a string in double quotes indicating the target URI path.
  This command currently support two possible URI paths:
```

2024-06-12 04:50 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  * ``"/10250/0/0"``, in which case the data is set in the Uplink Data resource (ID: 0) of the App Data Container object (ID: 10250).
```suggestion
  * ``"/10250/0/0"`` - The data is set in the Uplink Data resource (ID: 0) of the App Data Container object (ID: 10250).
```

2024-06-12 04:50 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  * ``"/19/<obj_inst_id>/0/<res_inst_id>"``, the data is set in an instance of the Data resource (ID: 0) of the Binary App Data Container object (ID: 19).
```suggestion
  * ``"/19/<obj_inst_id>/0/<res_inst_id>"`` - The data is set in an instance of the Data resource (ID: 0) of the Binary App Data Container object (ID: 19).
```

2024-06-12 04:50 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
> +  ``<data>`` must be a hexadecimal string in double quotes, unless ``slm_data_mode`` is enabled. If ``<data>`` is not present, SLM enters ``slm_data_mode``
```suggestion
  ``<data>`` must be a hexadecimal string in double quotes, unless ``slm_data_mode`` is enabled.
  If ``<data>`` is not present, SLM enters ``slm_data_mode``.
```

2024-06-12 10:45 UTC, closed without merging