samples: matter: Fix diagnostic logs snippet
nrfconnect/sdk-nrf pull request #15903
Opened 2024-06-11 12:37 UTC by ArekBalysNordic

Several issues were found in the matter diagnostic logs snippet. Added an important note to the documentation about using snippets.

2024-06-11 12:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15903/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15903/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-15903/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-11 13:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-15903
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-12 05:25 UTC, wiba-nordic requested changes

2024-06-12 05:25 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +  You can enable diagnostic log support only by setting the snippet because it contains the crucial devicetree overlays.
```suggestion
  To enable diagnostic log support, you must use the :ref:`diagnostic logs snippet <ug_matter_diagnostic_logs_snippet>`, which contains required devicetree overlays.
```
This this line should replace Line 235.

With this change, the `important` can be changed to `note` and moved before Line 274 (between the list of Kconfig options and the use instructions).

2024-06-12 05:25 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +  To disable a specific functionality, use the snippet and set the chosen config to ``n``.
```suggestion
  If you want to use just some of the diagnostic logs functionality, use the snippet and set the Kconfig options for the other functionalities to ``n``.
```

2024-06-12 05:57 UTC, kkasperczyk-no approved these changes

2024-06-12 07:33 UTC, wiba-nordic approved these changes

2024-06-12 09:06 UTC, merged