Fast Pair: locator tag use case: upgrade to "Supported" maturity level
nrfconnect/sdk-nrf pull request #16014
Opened 2024-06-14 09:57 UTC by kapi-no

2024-06-14 10:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16014
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-14 10:58 UTC, miha-nordic requested changes

2024-06-14 10:58 UTC, miha-nordic commented on doc/nrf/releases_and_maturity/software_maturity.rst
Everything for nrf54L15 should be marked as supported.
Should nrf5340 support for Fast Pair features follows Locator tag maturity and should be experimental?

2024-06-14 12:07 UTC, kapi-no commented on doc/nrf/releases_and_maturity/software_maturity.rst
The locator tag uses only the following FP features: "Initial pairing" and "FMDN extension".

2024-06-14 12:23 UTC, kapi-no commented on doc/nrf/releases_and_maturity/software_maturity.rst
The use case level support for nRF5340 and nRF54L15 platforms is considered experimental as they ideally should support the "Security provisioning" feature and keep the provisioned data as part of the Secure Storage. Apart from that, nRF54L15 SoC is experimental so we shouldn't encourage customers to deploy experimental SoC into their products.

Individual features like "Initial pairing" and "FMDN extension" are not platform-specific so they are declared as supported for all platforms if they are deployed in products for at least one use case and SoC (e.g. Locator Tag, nRF52840 SoC). 

Platform-specific features (e.g. "Secure provisioning") can differ for various SoCs.

I am happy to change the approach, but I just wanted to describe the wider context so that we can make a more informed decision. I would love to hear input from others.

@alstrzebonski, @MarekPieta, @PaalKastnes

2024-06-14 13:59 UTC, alstrzebonski commented on doc/nrf/releases_and_maturity/software_maturity.rst
I agree with @kapi-no. I think there's no reason to claim that e.g. "Initial pairing" feature support is experimental on one platform and supported on another platform. The platform itself might be experimental, but the feature is not. That's why we have two tables.

2024-06-14 14:00 UTC, alstrzebonski approved these changes

2024-06-14 14:12 UTC, miha-nordic commented on doc/nrf/releases_and_maturity/software_maturity.rst
@kapi-no @alstrzebonski I understand but then it shouldn't be divided through platforms at all. If you leave it like that you give false impression that anything is production ready for nrf54L15 when it is still SOC1 not even checked on FP1 targets. So you have production ready support on experimental HW. That doesn't make sense in my opinion. If you remove this division into platforms then it will be fine for me.

2024-06-14 16:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16014/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16014/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16014/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-14 17:37 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug_nrf54h20[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 1408[B]*** in comparison to the ***main[4084eb1f]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf54h20&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-16014/1)*

2024-06-17 07:03 UTC, kapi-no commented on doc/nrf/releases_and_maturity/software_maturity.rst
@miha-nordic, documenting the software maturity level for every platform is the NCS documentation policy for this type of information. It is used for other protocols, libraries and NCS modules. The Fast Pair software maturity table follows this documentation policy. We don't want to be the outlier here.

2024-06-17 07:05 UTC, miha-nordic commented on doc/nrf/releases_and_maturity/software_maturity.rst
Then it can't be supported for the platforms that it is not production ready.

2024-06-17 10:03 UTC, miha-nordic commented
@kapi-no This section: Fast Pair feature needs to be change I don't approve it in this shape.

2024-06-17 10:12 UTC, miha-nordic requested changes
This section: Fast Pair feature needs to be change I don't approve it in this shape.

2024-06-17 10:18 UTC, kapi-no commented
@miha-nordic, please request specific changes that you think are mandatory. This way, we can progress with our discussion

2024-06-17 10:22 UTC, miha-nordic commented
> @miha-nordic, please request specific changes that you think are mandatory. This way, we can progress with our discussion

@kapi-no   As mention before:
- Initial pairing needs to be marked as experimental for nrf5340 and nrf54l15
- Find My Device Network extension needs to be marked as experimental for nrf5340 and nrf54l15

2024-06-17 11:21 UTC, MarekPieta approved these changes
I would suggest to apply my comment related to nRF54L to align with @miha-nordic request

2024-06-17 13:53 UTC, kapi-no commented
> > @miha-nordic, please request specific changes that you think are mandatory. This way, we can progress with our discussion
> 
> @kapi-no As mention before:
> 
> * Initial pairing needs to be marked as experimental for nrf5340 and nrf54l15
> * Find My Device Network extension needs to be marked as experimental for nrf5340 and nrf54l15

Done

2024-06-17 14:00 UTC, miha-nordic approved these changes

2024-06-17 14:06 UTC, MarekPieta approved these changes

2024-06-17 14:57 UTC, alstrzebonski approved these changes

2024-06-17 15:01 UTC, kapi-no commented
@divipillai or @annwoj, could you ACK this PR? This is technically a documentation update.

2024-06-17 15:26 UTC, merged