doc: Bluetooth: Mesh: Add note about cancel after successful dist
nrfconnect/sdk-nrf pull request #16026
Opened 2024-06-14 14:24 UTC by Balaklaka

Add a note about the need to cancel the Distribution Server after a successful firmware distribution.

2024-06-14 14:26 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16026/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16026/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-06-14 15:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16026
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-17 06:34 UTC, mia-ko requested changes

2024-06-17 06:34 UTC, mia-ko commented on doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst
> +   After a successful firmware distribution, the Firmware Distribution Server need to be set to idle state by issuing the ``mesh models dfd cancel`` shell command, before a new firmware distribution
```suggestion
   After a successful firmware distribution, the Firmware Distribution Server has to be set to idle state by issuing the ``mesh models dfd cancel`` shell command, before a new firmware distribution can be initiated.
```

2024-06-17 11:54 UTC, akredalen approved these changes

2024-06-17 12:06 UTC, ludvigsj approved these changes

2024-06-17 12:20 UTC, mia-ko approved these changes

2024-06-17 13:05 UTC, merged