applications: machine_learning: Update documentation
nrfconnect/sdk-nrf pull request #16051
Opened 2024-06-17 11:17 UTC by maje-emb

Added the nRF54H20 board description to the documentation.

Ref: NCSDK-27849

2024-06-18 06:17 UTC, peknis requested changes

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   If the device can not be found - the PDK might be connected to the other device.
```suggestion
   If the device cannot be found - the PDK might be connected to the other device.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   Terminate the connection with the other device, refresh the scanning and connect to the PDK.
```suggestion
   Terminate the connection with the other device, refresh the scanning, and connect to the PDK.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   If the device disconnects shortly after being connected - the PDK might have saved bonding data from previous connection.
```suggestion
   If the device disconnects shortly after being connected, the PDK might have saved bonding data from previous connection.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   The bonding data can be erased if you double-click the **Button 0** within 3 seconds after the application reboots.
```suggestion
   You can erase the bonding data by double-clicking the **Button 0** within three seconds after the application reboots.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +#. Find **Nordic Status Message Service** by its name or UUID (57a70001-9350-11ed-a1eb-0242ac120002).
```suggestion
#. Find **Nordic Status Message Service** by its name or UUID (``57a70001-9350-11ed-a1eb-0242ac120002``).
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +#. Press and hold **Button 0** for more than 5 seconds to switch to the data forwarding mode.
```suggestion
#. Press and hold **Button 0** for more than five seconds to switch to the data forwarding mode.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +#. You can test the data forwarding mode of the application with the `nRF Connect for Mobile`_.
```suggestion
#. Test the data forwarding mode of the application with the `nRF Connect for Mobile`_:
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +#. You can also test the data forwarding mode with use of additional DK.
```suggestion
#. Test the data forwarding mode with an additional DK:
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   a. Program the :ref:`central_uart` sample to a compatible development kit, for example the nRF52840 Development Kit.
```suggestion
   a. Program the :ref:`central_uart` sample to a compatible development kit, for example the nRF52840.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +      The **LED0**, **LED1**, and **LED2** on the nRF54H20 PDK start to blink rapidly.
```suggestion
      The **LED0**, **LED1**, and **LED2** on the nRF54H20 PDK start blinking rapidly.
```

2024-06-18 06:17 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   #. Connect to the Bluetooth® Central UART sample with a terminal emulator (for example, PuTTY).
```suggestion
   #. Connect to the Bluetooth Central UART sample with a terminal emulator (for example, PuTTY).
```

2024-06-18 06:31 UTC, peknis requested changes

2024-06-18 06:31 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   * dual-core - Simulated sensor (:ref:`sensor_sim`).
Link target pca63566 not found and the doc build fails. Where do you want to link to?

2024-06-18 06:49 UTC, maje-emb commented
I want to link to boards/shields/pca63566/doc/index.rst

2024-06-18 06:55 UTC, peknis commented
> pca63566

Unfortunately, that is not part of our doc set. Try linking with :doc:`pca63566`. If it does not work, then we need to drop the link.

2024-06-18 06:59 UTC, dchat-nordic commented on applications/machine_learning/app_desc.rst
> +1. Turn on your PDK.
Is it PDK or DK now?

2024-06-18 07:35 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +1. Turn on your PDK.
Good point, DK it is.

2024-06-18 07:40 UTC, maje-emb commented on applications/machine_learning/app_desc.rst
> +1. Turn on your PDK.
It should be DK.

2024-06-18 09:34 UTC, maje-emb commented on applications/machine_learning/app_desc.rst
> +* nRF54H20 DK:
Good idea.

2024-06-18 10:36 UTC, peknis requested changes

2024-06-18 10:36 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +   * Single-core - Accelerometer (``ADXL362``) connected to the DK with the :file:`nrf/boards/shields/pca63566/doc/index.rst` shield.
```suggestion
   * Single-core - Accelerometer (``ADXL362``) connected to the DK with the PCA63566 shield.
     See details in :file:`nrf/boards/shields/pca63566/doc/index.rst`.
```

2024-06-18 11:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16051
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-18 11:27 UTC, peknis approved these changes

2024-06-18 11:33 UTC, peknis requested changes

2024-06-18 11:33 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +         The machine learning result is represented by:
```suggestion
        The machine learning result is represented by:
```

2024-06-18 11:33 UTC, peknis commented on applications/machine_learning/app_desc.rst
> +         The machine learning result is represented by the number of blinks:
```suggestion
        Then the sequence is repeated.
        The machine learning result is represented by the number of blinks:
```

2024-06-18 12:37 UTC, peknis approved these changes

2024-06-19 12:21 UTC, dchat-nordic approved these changes

2024-06-19 13:02 UTC, merged