bl_crypto: cc310: Do not initialize cc310 from EXT_ABI
nrfconnect/sdk-nrf pull request #16076
Opened 2024-06-18 13:50 UTC by sigvartmh

Fix-up for 723194f47bfdc3572c3e5cb27eeab74df23522b9 to add handling for a case where you call this function when you are running from PSP and have modified MSP so that you would still initialize the cc310.

Ref. NCSDK-23962

2024-06-18 13:54 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16076/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16076/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-mcuboot | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16076/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-21 05:15 UTC, hakonfam approved these changes
So if invoked by EXT_ABI, then the PSP is selected, and if its invoked by B0 directly then MSP is selected? Should we add a comment describing this?

2024-06-21 08:06 UTC, sigvartmh commented
No. It checks if you are coming from outside of B0. So it's more if you call ext abi from an external context like app or MCUBoot.

Before you could skip this check by changing to PSP then call the function from PSP context

2024-06-21 08:08 UTC, sigvartmh commented
Not enough approvals so removing it from 2.7

2024-06-21 09:37 UTC, oyvindronningstad requested changes
CONTROL.SPSEL doesn't alone specify whether PSP is being used. If execution is in handler mode, MSP is always used, regardless of CONTROL.SPSEL.

2024-06-24 08:51 UTC, pdunaj commented
I wonder why it is done the way it is. Can't it be called from some place that we know it's B0? Since it is clearly done once it does not look like you have to reinitialize on every call, right?

2024-06-24 10:11 UTC, sigvartmh commented
> CONTROL.SPSEL doesn't alone specify whether PSP is being used. If execution is in handler mode, MSP is always used, regardless of CONTROL.SPSEL.

So it should check that MSP is larger regardless then and only check PSP if SPSEL is set.

2024-06-24 10:37 UTC, oyvindronningstad commented
You must check if you are in handler mode (i.e. executing an interrupt). I don't quite remember how you can do that.

2024-08-26 08:27 UTC, closed without merging