doc: manual override of SML tables
nrfconnect/sdk-nrf pull request #16135
Opened 2024-06-21 12:08 UTC by b-gent

Some further manual updates as a result
of broken script.

2024-06-21 12:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16135/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16135/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-06-21 12:15 UTC, greg-fer approved these changes

2024-06-21 12:16 UTC, divipillai approved these changes

2024-06-21 12:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16135
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-21 12:58 UTC, divipillai requested changes

2024-06-21 12:58 UTC, divipillai commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +   :insert-values: [("Bluetooth","nRF54H20","Experimental"), ("Matter","nRF54H20","Experimental"), ("Thread","nRF54H20","Experimental"), ("Wi-Fi","nRF54H20","Experimental"),("Bluetooth","nRF54L15","E
```suggestion
   :insert-values: [("Bluetooth","nRF54H20","Experimental"), ("Matter","nRF54H20","Experimental"), ("Thread","nRF54H20","Experimental"), ("Wi-Fi","nRF54H20","Experimental"),("Bluetooth","nRF54L15","Experimental"), ("Bluetooth Mesh","nRF54L15","Experimental"), ("Matter","nRF54L15","Experimental"), ("Sidewalk","nRF54L15","Experimental"), ("Thread","nRF54L15","Experimental"), ("Wi-Fi","nRF54L15","Experimental"), ("DECT_PHY","nRF9160","-"), ("DECT_PHY","nRF9161","Experimental"), ("DECT_PHY","nRF9151","Experimental")]
```
Is there any way to rename DECT_PHY to DECT NR+ PHY in the table?

2024-06-21 14:41 UTC, b-gent commented
Looks like the :insert-values: method does not really meet our requirements. I will be changing these tables to manual markdown tables in the next commit.

2024-06-25 02:13 UTC, VivekUppunda requested changes

2024-06-25 02:13 UTC, VivekUppunda commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +   | **Thread Coexistence**                        | -        | -        | -        | -        | -        | -           | Experimental     | -              | -              | -       | -
This is not visible in the Documentation Link generated for this PR. Will this be seen in the documentation for main build?

2024-06-25 02:13 UTC, VivekUppunda commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +   | **SoftAP Mode (for Wi-Fi provisioning)**      | -        | -        | -        | -        | -        | -           | Supported        | -              | -              | -       | -
This is change is also not visible in the PR documentation link

2024-06-25 07:46 UTC, VivekUppunda approved these changes

2024-06-26 11:11 UTC, divipillai approved these changes

2024-06-26 14:07 UTC, merged