sysbuild: Remove non-functional environmental key support
nrfconnect/sdk-nrf pull request #16154
Opened 2024-06-24 09:08 UTC by nordicjm

Removes using the environmental or command line parameters for specifying a key as the underlying functionality in child/parent has never worked so does not need reimplementation in sysbuild

2024-06-24 09:09 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16154/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16154/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-dfu | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16154/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-24 11:29 UTC, tejlmand requested changes
also needs an update:
https://github.com/nrfconnect/sdk-nrf/blob/7dcd587b67ac1289ff99270b203fc8500fb6a93f/sysbuild/Kconfig.secureboot#L69-L72

Please check for other references in addition.

2024-06-24 11:31 UTC, nordicjm commented
> also needs an update:
> 
> https://github.com/nrfconnect/sdk-nrf/blob/7dcd587b67ac1289ff99270b203fc8500fb6a93f/sysbuild/Kconfig.secureboot#L69-L72
> 
> Please check for other references in addition.

Part of https://github.com/nrfconnect/sdk-nrf/pull/16152

2024-06-24 12:09 UTC, tejlmand commented
> 
> Part of #16152

could you please keep such updates part of the PR which does the change.
Splitting this in different PRs really makes it hard to know what changes are caused by which.

2024-06-25 14:01 UTC, carlescufi approved these changes

2024-06-26 08:16 UTC, 57300 approved these changes

2024-06-26 14:10 UTC, tejlmand approved these changes

2024-06-26 20:01 UTC, merged