samples: event_manager_proxy: Add default configuration
nrfconnect/sdk-nrf pull request #16153
Opened 2024-06-24 09:07 UTC by KAGA164

This commit allows to build Event Manager Proxy
sample for all target in default configuration
without a need for passing additional parameters
to the build command.

2024-06-24 09:09 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16153/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16153/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-low-level | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16153/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-24 09:33 UTC, peknis requested changes

2024-06-24 09:33 UTC, peknis commented on samples/event_manager_proxy/README.rst
> +   Snippet for running PPR core is added automatically to build configuration
```suggestion
   A snippet for running the PPR core is added automatically to build configuration.
```

2024-06-24 11:33 UTC, grochu approved these changes
Looks good

2024-06-24 12:02 UTC, maje-emb approved these changes

2024-06-24 12:15 UTC, dchat-nordic approved these changes

2024-06-25 08:24 UTC, peknis approved these changes

2024-06-25 09:07 UTC, merged