Applications: nrf5340_audio: Doc and sample.yaml update
nrfconnect/sdk-nrf pull request #16166
Opened 2024-06-24 11:41 UTC by koffes

OCT-3067
Added more explicitly the use of flags in the doc. Cleaned up sample.yaml

2024-06-24 11:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16166/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16166/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16166/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-25 02:47 UTC, rick1082 requested changes

2024-06-25 02:47 UTC, rick1082 commented on applications/nrf5340_audio/doc/configuration.rst
> +An Auracaster/broadast source or unicast client is a gateway.
Aurcast/broadcast

2024-06-25 02:47 UTC, rick1082 commented on applications/nrf5340_audio/doc/configuration.rst
> +If you want to work with Auracasters/broadcast sources and sinks, set the ``CONFIG_TRANSPORT_BIS`` Kconfig option to ``y`` in the :file:`applications/nrf5340_audio/prj.conf` file.
Auracast or Auracast transmitter

2024-06-25 06:26 UTC, alexsven requested changes

2024-06-25 06:26 UTC, alexsven commented on applications/nrf5340_audio/doc/configuration.rst
> +By default, if you have not made any changes to :file:`.conf` files at :file:`applications/nrf5340_audio/`, the nRF5340 build script tries to build the CIS/unicast application in the CIS unidirection
```suggestion
By default, if you have not made any changes to :file:`.conf` files at :file:`applications/nrf5340_audio/`, the nRF5340 build script will build the CIS/unicast application in the CIS unidirectional mode as a headset. ( ``CONFIG_TRANSPORT_CIS=y`` and ``CONFIG_AUDIO_DEV=2``).
```

2024-06-25 06:26 UTC, alexsven commented on applications/nrf5340_audio/doc/configuration.rst
> +Headset build is identified with ``CONFIG_AUDIO_DEV=2`` and is the default config.
```suggestion
Gateway is selected by adding ``CONFIG_AUDIO_DEV=2`` to the prj.conf file.

Oppositely, a headset is a common term for headphones, headsets, speakers or earbuds, acting as unicast server or broadcast sink.
With reference to the gateway, the headset is often the smallest and most portable device, and is commonly the Bluetooth peripheral if applicable.
Headset build is identified with ``CONFIG_AUDIO_DEV=1`` and is the default config.
```

2024-06-25 06:26 UTC, alexsven commented on applications/nrf5340_audio/doc/configuration.rst
> +Headset build is identified with ``CONFIG_AUDIO_DEV=2`` and is the default config.
```
config AUDIO_DEV
	int "Select which device type to compile for. 1=HEADSET or 2=GATEWAY"
	range 1 2
	default 1
	help
	  Setting this variable to 1 selects that the project is compiled
	  as a HEADSET device.
	  Setting to 2 will compile as a GATEWAY.
```
This is from the Kconfig

2024-06-26 11:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16166
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-27 05:46 UTC, alexsven approved these changes

2024-06-27 07:37 UTC, rick1082 approved these changes

2024-06-27 07:44 UTC, eivindj-nordic approved these changes

2024-06-27 14:08 UTC, greg-fer approved these changes

2024-06-27 14:09 UTC, greg-fer commented
@koffes , please note I pushed with force, so make sure to pull my changes if you need to make further edits.

2024-07-31 13:03 UTC, merged