samples: mss: Minor tweaks
nrfconnect/sdk-nrf pull request #16179
Opened 2024-06-24 23:59 UTC by glarsennordic

Tweak PR covering two minor tickets: IRIS-7458 and IRIS-9197

2024-06-25 00:00 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16179/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16179/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16179/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-25 00:10 UTC, jayteemo approved these changes

2024-06-25 05:30 UTC, peknis requested changes

2024-06-25 05:30 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * CONFIG_TEST_COUNTER_MULTIPLIER to multiply the number of test counter messages sent, for testing purposes.
```suggestion
    * The :kconfig:option:`CONFIG_TEST_COUNTER_MULTIPLIER` Kconfig option to multiply the number of test counter messages sent, for testing purposes.
```

2024-06-25 19:19 UTC, plskeggs approved these changes

2024-06-25 21:52 UTC, glarsennordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * CONFIG_TEST_COUNTER_MULTIPLIER to multiply the number of test counter messages sent, for testing purposes.
Ahh, good catch

2024-06-25 22:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16179
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-26 05:28 UTC, peknis approved these changes

2024-06-26 23:48 UTC, glarsennordic commented
Added DNM: This breaks CoAP due to JWT requiring PicoLib, needs further investigation

2024-07-10 00:26 UTC, glarsennordic commented
One of these is blocked on an issue with hostap, so I will split into two PRs.

2024-07-10 00:26 UTC, closed without merging