manifest: zephyr: Turn on NRFS for NRF54H20 DK
nrfconnect/sdk-nrf pull request #16185
Opened 2024-06-25 09:50 UTC by zycz

Turn on NRFS globally so turning off
suspending MRAM for NRF54H20 DK will work.

Jira: NCSDK-27870

2024-06-25 09:50 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/58284ff0e1b85f24d1be928860e9e6eb0e86b4e5 (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1856 | [nrfconnect/sdk-zephyr#1856/files](https://github.com/nrfconnect/sdk-zephyr/pull/1856/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-06-25 09:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16185/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16185/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16185/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-25 10:10 UTC, tomchy requested changes
Please disable `NRFS` inside `flash_companion` image - it does not use radio core and should be optimized for memory (https://github.com/nrfconnect/sdk-nrf/blob/main/samples/suit/flash_companion/prj.conf).

2024-06-25 10:26 UTC, tomchy approved these changes

2024-06-25 10:59 UTC, pdunaj approved these changes

2024-06-25 11:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16185
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-06-25 14:12 UTC, e-rk approved these changes

2024-06-26 17:05 UTC, shanthanordic approved these changes

2024-06-26 20:00 UTC, merged