manifest: update suit-generator sha
nrfconnect/sdk-nrf pull request #16244
Opened 2024-06-28 05:56 UTC by robertstypa

WIP

Store only unique SUIT cid to role mappings to avoid a broken configuration.

Ref: NCSDK-27289

Signed-off-by: Robert Stypa <robert.stypa@nordicsemi.no>

2024-06-28 05:58 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16244/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16244/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16244/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-06-28 06:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16244
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-01 07:11 UTC, tomchy requested changes

2024-07-01 07:11 UTC, tomchy commented on west.yml
> +      path: pull/130/head
It is better to modify revision than path :slightly_smiling_face:

2024-07-01 13:58 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| suit-generator | [nrfconnect/suit-generator@v2.7.0-rc3](https://github.com/nrfconnect/suit-generator/releases/tag/v2.7.0-rc3) | https://github.com/nrfconnect/suit-generator/pull/130 | [nrfconnect/suit-generator#130/files](https://github.com/nrfconnect/suit-generator/pull/130/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-07-01 14:49 UTC, tomchy approved these changes

2024-07-03 05:42 UTC, kszromek-nordic approved these changes

2024-07-04 09:21 UTC, tejlmand approved these changes

2024-10-16 13:27 UTC, jnsgsr approved these changes

2024-12-14 00:34 UTC, closed without merging