services: hids: Fix possible out-of-bound access
nrfconnect/sdk-nrf pull request #16279
Opened 2024-07-01 12:16 UTC by KAGA164

Fixes coverity issue 122949

2024-07-01 12:21 UTC, alwa-nordic requested changes
I think you also have to fix the `if (len > sizeof(uint8_t)) {` so it is `!=` instead.

https://github.com/nrfconnect/sdk-nrf/blob/d4de8ecbc9599abcbdf4393f3350dadc280a7b84/subsys/bluetooth/services/hids.c#L711

2024-07-02 07:14 UTC, dchat-nordic requested changes
I agree with @alwa-nordic

2024-07-08 06:26 UTC, KAGA164 commented
> I think you also have to fix the `if (len > sizeof(uint8_t)) {` so it is `if (len != sizeof(uint8_t)) {` instead.
> 
> https://github.com/nrfconnect/sdk-nrf/blob/d4de8ecbc9599abcbdf4393f3350dadc280a7b84/subsys/bluetooth/services/hids.c#L711

@alwa-nordic @dchat-nordic  Done

2024-07-08 07:21 UTC, alwa-nordic approved these changes

2024-07-08 10:17 UTC, dchat-nordic approved these changes

2024-07-09 07:57 UTC, maje-emb approved these changes

2024-07-09 11:19 UTC, grochu approved these changes

2024-07-11 14:04 UTC, merged