samples: wifi: Coexistence samples readme update
nrfconnect/sdk-nrf pull request #16271
Opened 2024-07-01 08:19 UTC by muraliThokala

Update the README files for both the BLE and Thread coexistence samples, as well as the block diagram for the Thread coexistence sample, accordingly.

2024-07-01 08:22 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16271/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16271/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-07-01 08:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16271
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-01 09:27 UTC, peknis requested changes

2024-07-01 09:27 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +|              | sample            | device if Thread role on DUT is a server.                                           |
```suggestion
| nRF7002 DK   | Thread-only      | Case 1: Thread-only UDP throughput is run in server mode on the peer nRF7002 DK     |
| (peer)       | throughput using  | device if Thread role on DUT is a client.                                           |
|              | Thread coexistence| Case 2: Thread-only UDP throughput is run in client mode on the peer nRF7002 DK     |
|              | sample            | device if Thread role on DUT is a server.                                           |
```

2024-07-01 09:27 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +* Wi-Fi connection: Configure the following Wi-Fi credentials in the :file:`prj.conf` file: appropriately as per the credentials of the access point used for this testing:
```suggestion
* Wi-Fi connection: Configure the following Wi-Fi credentials in the :file:`prj.conf` appropriately as per the credentials of the access point used for this testing:
```

2024-07-01 10:28 UTC, peknis approved these changes

2024-07-02 07:57 UTC, krish2718 approved these changes

2024-07-02 07:58 UTC, bama-nordic approved these changes

2024-07-02 09:38 UTC, merged