samples: cellular: nrf_cloud_rest_device_message: update logging
nrfconnect/sdk-nrf pull request #16345
Opened 2024-07-05 18:36 UTC by tony-le-24

Updated the overlay_nrfcloud_logging.conf to remove the comments for dictionary-based logging which is not available for the REST protocol.

2024-07-05 18:38 UTC, jayteemo approved these changes

2024-07-05 18:40 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16345/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16345/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16345/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-08 05:40 UTC, peknis requested changes

2024-07-08 05:40 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* :ref:`nrf_cloud_rest_device_message_sample` sample:
```suggestion
* :ref:`nrf_cloud_rest_device_message` sample:
```
This failed the doc build.

2024-07-08 05:40 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Removed the dictionary-based comments in the :file:`overlay_nrfcloud_logging.conf`.
```suggestion
  * Removed the dictionary-based comments in the :file:`overlay_nrfcloud_logging.conf` file.
```

2024-07-08 17:06 UTC, glarsennordic approved these changes

2024-07-08 17:13 UTC, plskeggs approved these changes

2024-07-08 17:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16345
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-09 05:25 UTC, peknis approved these changes

2024-07-12 18:13 UTC, merged