Application: nrf5340_audio: Allow opening multiple files on SD card
nrfconnect/sdk-nrf pull request #16351
Opened 2024-07-08 10:17 UTC by andvib

Remove semaphores in sd_card module so multiple files can be opened and read from at the same time. The Zephyr FS supports multiple open files, and there are no relevant limitiations of the SD card module to not allow multiple files.

OCT-3031

2024-07-08 10:21 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16351/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16351/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16351/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-08 10:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16351
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-09 08:46 UTC, alexsven requested changes

2024-07-09 08:46 UTC, alexsven commented on applications/nrf5340_audio/src/modules/sd_card.c
>  	}
Remove
```suggestion
```

2024-07-09 13:38 UTC, gWacey requested changes
Just the one issue that Alexsven has picked up.

2024-07-09 16:27 UTC, gWacey approved these changes

2024-07-10 03:14 UTC, rick1082 approved these changes

2024-07-11 06:38 UTC, alexsven approved these changes

2024-07-11 07:02 UTC, merged