Option to select power save data retrieval mechanism  from AP
nrfconnect/sdk-nrf pull request #16477
Opened 2024-07-17 07:43 UTC by ajayparida

Option to select power save data retrieval mechanism.

2024-07-17 07:43 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/980bf2a1ae0178a23be58fc7270e647878de7400 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/1409 | [nrfconnect/sdk-nrfxlib#1409/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1409/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-07-17 07:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16477/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16477/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16477/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-17 08:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16477
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-17 08:38 UTC, sachinthegreen requested changes

2024-07-17 08:38 UTC, sachinthegreen commented on drivers/wifi/nrf700x/Kconfig
> +choice NRF_WIFI_PS_DATA_RETRIEVAL_MODE
```suggestion
choice NRF_WIFI_PS_DATA_RETRIEVAL_MECHANSIM
```

2024-07-17 09:16 UTC, krish2718 requested changes
@udaynordic please review the help, we need to convey the info necessary for the user to decide which mechanism is better in which scenario.

2024-07-17 09:16 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	bool "PS-Poll based mechanism to retrieve buffered data from AP"
```suggestion
	bool "PS-Poll frame based mechanism to retrieve buffered data from AP"
	help
	  When AP notifies about availability of buffered data, the STA stays in power save
	  and retrieves the frames one-by-one, this conserved more power but adds latency
	  to the traffic. Ideal for minimum number of frames.
```

2024-07-17 09:16 UTC, krish2718 commented on drivers/wifi/nrf700x/Kconfig
> +	bool "QoS null frame based mechanism to retrieve buffered data from AP"
```suggestion
	bool "QoS null frame based mechanism to retrieve buffered data from AP"
	help
	  When AP notifies about availability of buffered data, the STA comes out of
	  power save and then AP can deliver all buffered frames without any additional
	  overhead or latency, but STA enters power save after a delay costing more power
	  depending on the delay. Ideal for heavy buffered traffic.
	
```

2024-07-17 10:20 UTC, krish2718 approved these changes

2024-07-25 09:05 UTC, sachinthegreen approved these changes

2024-07-25 09:06 UTC, sachinthegreen approved these changes
I am assuming you will also update the corresponding changes in the `v2.5` branch.

2024-07-30 08:51 UTC, merged