doc: lwm2m_client_utils: Update documentation regarding objects
nrfconnect/sdk-nrf pull request #16475
Opened 2024-07-17 07:34 UTC by SeppoTakalo

* Remove outdated information of Nb-IoT and not supporting Bootstrap.
* Remove outdated information regarding read-callbacks. lwm2m_set_*() API should be used. Otherwise Notify operation does not work.
* Use LWM2M_OBJ_INIT() and LWM2M_APP_INIT() macros on sample.

2024-07-17 07:37 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16475/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16475/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-07-17 07:40 UTC, rlubos approved these changes

2024-07-17 08:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16475
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-29 09:44 UTC, wiba-nordic requested changes
A minor nit.

2024-07-29 09:44 UTC, wiba-nordic commented on doc/nrf/libraries/networking/lwm2m_client_utils.rst
> +For defining outputs, the process is very much similar but instead of updating the value, write callback is defined.
```suggestion
The process for defining outputs is similar, but instead of updating the value, a write callback is defined.
```

2024-07-29 09:50 UTC, wiba-nordic approved these changes

2024-07-29 12:52 UTC, merged