Bluetooth: Mesh: add metadata to lighting models
nrfconnect/sdk-nrf pull request #16485
Opened 2024-07-17 11:59 UTC by KyraLengfeld

This commit adds metadata to the lightning services in form of an optional parameter.

Note: Metadata is only supported if the Large Composition Data Server model is supported.

2024-07-17 12:01 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16485/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16485/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16485/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-17 14:01 UTC, omkar3141 requested changes
Suggestion for commit message and PR description:

> This commit adds metadata to the Light Lightness Server, Light HSL Server, Light CTL Temperature Server models in form of an optional parameter.

Otherwise looks fine.

2024-07-18 06:44 UTC, alxelax approved these changes

2024-07-19 08:36 UTC, omkar3141 approved these changes

2024-07-19 11:06 UTC, merged