Enable variable network buffer length settings
nrfconnect/sdk-nrf pull request #16505
Opened 2024-07-18 10:14 UTC by D-Triveni

This change is to optimize RAM usage.
Enable variable network buffer settings and also
resize `CONFIG_NET_PKT_BUF_TX_DATA_POOL_SIZE` and
`CONFIG_NET_PKT_BUF_RX_DATA_POOL_SIZE`for optimized throughput.

2024-07-18 10:16 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16505/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16505/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16505/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-23 07:53 UTC, krish2718 requested changes

2024-07-23 07:53 UTC, krish2718 commented on samples/wifi/shell/overlay-zperf.conf
> +CONFIG_HEAP_MEM_POOL_SIZE=180000
why is this change needed? No mention of it in the commit log?

P.S. Commit log should explain in just English rather than quoting code or configs

2024-07-29 07:11 UTC, krish2718 commented on samples/wifi/shell/overlay-zperf.conf
> +CONFIG_NET_PKT_BUF_TX_DATA_POOL_SIZE=55000
please add Jira reference to commit log.

2024-07-29 09:07 UTC, VivekUppunda approved these changes

2024-07-30 07:59 UTC, krish2718 approved these changes

2024-08-08 12:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16505
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-04 03:14 UTC, krga2022 approved these changes

2024-10-21 18:29 UTC, krish2718 commented
Migrated to upstream https://github.com/zephyrproject-rtos/zephyr/pull/78852

2024-10-21 18:29 UTC, closed without merging