tests: partition_manager: Add static_pm_file test
nrfconnect/sdk-nrf pull request #16515
Opened 2024-07-18 13:16 UTC by nordicjm

Adds a test that checks that PM_STATIC_YML_FILE functionality is working

2024-07-18 13:21 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16515/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16515/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem-nrf | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_nrf_provisioning | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_serial_lte_modem | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-low-level | X | | |
| test-sdk-dfu | X | | |
| test-sdk-find-my | X | | |
| test-sdk-mcuboot | X | | |
| test-sdk-pmic-samples | X | | |
| test-sdk-sidewalk | X | | |
| test-sdk-wifi | X | | |
| test_ble_commit | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16515/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-18 13:22 UTC, katgiadla approved these changes
Please add responsible person for these tests in `CODEOWNERS` file.

2024-07-18 13:23 UTC, katgiadla requested changes
Please add responsible person for these tests in CODEOWNERS file.

2024-07-18 13:41 UTC, katgiadla requested changes

2024-07-18 13:41 UTC, katgiadla commented on CODEOWNERS
> +/tests/subsys/partition_manager/region/   @hakonfam @sigvartmh
Duplicate with line 360. Please remove this line

2024-07-18 14:25 UTC, katgiadla approved these changes
LGTM

2024-07-19 13:53 UTC, sigvartmh approved these changes

2024-07-19 16:14 UTC, de-nordic approved these changes

2024-07-22 06:38 UTC, merged