wifi: Add Wi-Fi statistics reset command
nrfconnect/sdk-nrf pull request #16512
Opened 2024-07-18 12:06 UTC by kapbh

2024-07-18 12:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16512/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16512/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-low-level | X | | |
| test-sdk-find-my | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16512/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-18 12:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16512
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-19 08:08 UTC, sachinthegreen requested changes

2024-07-19 08:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +	struct rpu_host_stats host;
```suggestion
	struct rpu_host_stats host_stats;
```

2024-07-19 08:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +	rpu_ctx_zep = vif_ctx_zep->rpu_ctx_zep;
```suggestion

	rpu_ctx_zep = vif_ctx_zep->rpu_ctx_zep;
```

2024-07-19 08:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +		LOG_ERR("%s: nrf_wifi_fmac_stats_get failed", __func__);
```suggestion
		LOG_ERR("%s: nrf_wifi_fmac_stats_reset failed", __func__);
```

2024-07-22 12:36 UTC, sachinthegreen approved these changes

2024-07-24 12:11 UTC, krish2718 approved these changes

2024-07-24 12:28 UTC, merged