samples: npm1300_one_button: Fix irq allocation for nRF52840 DK.
nrfconnect/sdk-nrf pull request #16546
Opened 2024-07-22 11:02 UTC by aasinclair

Pin allocation for PMIC interrupt output on nRF52840 DK has been fixed.  It was previously allocated to a pin that is not available on a pin header.

2024-07-22 11:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16546
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-23 17:17 UTC, WalkingTalkingPotato requested changes
Needs line 20 to be changed in nrf52840dk_nrf52840.overlay:
`host-int-gpios = <&gpio1 12 0>;`

Then it works as documented (tested).

2024-07-25 08:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16546/7/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16546/7/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16546/7/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-30 06:48 UTC, shanthanordic approved these changes

2024-07-30 06:55 UTC, greg-fer approved these changes

2024-08-02 08:06 UTC, merged