snippets: Add snippets for nrf70 debug
nrfconnect/sdk-nrf pull request #16582
Opened 2024-07-23 12:44 UTC by D-Triveni

This commit adds the overlays for both the driver and supplicant to debug nrf70.

Fixes SHEL-1836.

2024-07-23 12:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16582/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16582/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16582/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-23 13:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16582
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-23 14:35 UTC, krish2718 requested changes

2024-07-23 14:35 UTC, krish2718 commented on snippets/nrf70-supplicant-debug/overlay-nrf70-supplicant-debug.conf
> +CONFIG_NRF_WIFI_RPU_RECOVERY=y
how is this related to WPA supplicant debug? This is a driver feature.

2024-07-23 14:35 UTC, krish2718 commented on snippets/nrf70-driver-debug/overlay-nrf70-driver-debug.conf
> +CONFIG_NRF_WIFI_RPU_RECOVERY=y
`recovery` is opposite of debugging :)

2024-07-23 14:35 UTC, krish2718 commented on snippets/nrf70-driver-debug/overlay-nrf70-driver-debug.conf
> +CONFIG_NRF_WIFI_LOG_LEVEL_DBG=y
These suffer from the same problem as WPA supplicant debugs, too verbose and memory consuming. But on the other hand, don't want to end up with too many snippet variants, may be, below?

1. WPA supplicant debug
2. Driver debug
3. Driver verbose debug (enable BUG debug as well)

2024-07-25 03:54 UTC, VivekUppunda approved these changes

2024-07-26 11:18 UTC, sachinthegreen approved these changes

2024-07-26 13:23 UTC, krish2718 requested changes
> `CONFIG_LOG_MODE_IMMEDIATE=y`

This is useful to avoid log buffer overflows, but can have impact on timing, may be add this to docs.

Also add it migration guide and changelog, as existing snippet is now removed.

2024-07-26 13:23 UTC, krish2718 commented on snippets/nrf70-supplicant-debug/overlay-nrf70-supplicant-debug.conf
> +# Copyright (c) 2024 Nordic Semiconductor
CONFIG_NRF700X_UTIL=y is not needed for WPA supplicant debug.

2024-07-26 13:23 UTC, krish2718 commented on snippets/nrf70-driver-verbose-debug/overlay-nrf70-driver-verbose-debug.conf
> +CONFIG_NRF_WIFI_LOG_LEVEL_DBG=y
we should bus level debug too, `WIFI_NRF700X_BUS_LOG_LEVEL`

2024-07-26 13:23 UTC, krish2718 commented on CODEOWNERS
> +/snippets/nrf70-supplicant-debug/         @krish2718 @sachinthegreen
```suggestion
/snippets/wpa-supplicant-debug/         @krish2718 @sachinthegreen
```
This is common code.

2024-07-29 10:05 UTC, D-Triveni commented
> > `CONFIG_LOG_MODE_IMMEDIATE=y`
> 
> This is useful to avoid log buffer overflows, but can have impact on timing, may be add this to docs.
> 
> Also add it migration guide and changelog, as existing snippet is now removed.

Updated.

2024-07-29 16:21 UTC, krish2718 commented on doc/nrf/protocols/wifi/debugging.rst
> +    west build -p -b nrf7002dk/nrf5340/cpuapp samples/wifi/shell -- -Dnrf_wifi_shell_SNIPPET="nrf70-driver-verbose-debug;wpa-supplicant-debug"
We should have sections to explain and demonstrate various debug snippets, combining them in to a single one won't work most of the times due to memory and defeats the purpose of splitting them up.

2024-07-29 16:21 UTC, krish2718 commented on snippets/wpa-supplicant-debug/overlay-wpa-supplicant-debug.conf
> -CONFIG_LOG_MODE_IMMEDIATE=y
My comment https://github.com/nrfconnect/sdk-nrf/pull/16582#pullrequestreview-2201818511 doesn't ask to remove, it should be enabled, else we loose many logs and won't help in debugging, but add a note in the docs.

2024-07-29 16:21 UTC, krish2718 commented on snippets/wpa-supplicant-debug/overlay-wpa-supplicant-debug.conf
>  CONFIG_SYS_HEAP_RUNTIME_STATS=y
these are driver stats, unrelated to WPA supplicant.

2024-07-30 09:27 UTC, krish2718 commented on doc/nrf/protocols/wifi/debugging.rst
> +To build with driver verbose, firmware interfacing and BUS interfacing debug logs enabled.
```suggestion
To build with driver verbose, firmware interface and BUS interface debug logs enabled.
```

2024-07-30 09:27 UTC, krish2718 commented on doc/nrf/protocols/wifi/debugging.rst
> +To build with driver verbose, firmware interfacing and BUS interfacing debug logs enabled.
```suggestion
To build with driver verbose, firmware interface and BUS interface debug logs enabled.
```

2024-07-30 09:27 UTC, krish2718 commented on doc/nrf/protocols/wifi/debugging.rst
> +To build with supplicant debug logs enabled.
```suggestion
To build with WPA supplicant debug logs enabled.
```

2024-07-30 09:27 UTC, krish2718 commented on doc/nrf/protocols/wifi/debugging.rst
> +To build with driver debug logs enabled.
may be add a sections for `driver` (normal and verbose) and `wpa_supplicant`?

2024-08-01 15:38 UTC, richabp requested changes

2024-08-01 15:38 UTC, richabp commented on doc/nrf/protocols/wifi/debugging.rst
> +      ninja -C build
Same as above.

2024-08-01 15:38 UTC, richabp commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +     * Use the ``wpa-supplicant-debug`` snippet to enable supplicant logs.
```suggestion
     * ``nrf70-driver-debug`` - To enable the nRF70 driver debug logs.
     * ``nrf70-driver-verbose-logs`` - To enable the nRF70 driver, firmware interface, and BUS interface debug logs.
     * ``wpa-supplicant-debug`` - To enable supplicant logs.
```

2024-08-01 15:38 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The :ref:`ug_nrf70_developing_debugging` with the new snippets added for nrf70 debug.
```suggestion
  * The :ref:`ug_nrf70_developing_debugging` page with the new snippets added for nRF70 debug logs.
```

2024-08-06 13:10 UTC, krish2718 approved these changes

2024-08-06 13:21 UTC, richabp requested changes

2024-08-06 13:21 UTC, richabp commented on doc/nrf/protocols/wifi/debugging.rst
> +With West
```suggestion
With west
^^^^^^^^^
```

2024-08-06 13:21 UTC, richabp commented on doc/nrf/protocols/wifi/debugging.rst
> +With West
```suggestion
With west
^^^^^^^^^
```

2024-08-06 13:21 UTC, richabp commented on doc/nrf/protocols/wifi/debugging.rst
> +With West
```suggestion
With west
^^^^^^^^^
```

2024-08-06 13:21 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The :ref:`ug_nrf70_developing_debugging` page with the new snippets added for nRF70 debug logs.
```suggestion
  * The :ref:`ug_nrf70_developing_debugging` page with the new snippets added for the nRF70 driver debug logs.
```

2024-08-07 14:21 UTC, richabp approved these changes

2024-08-08 09:00 UTC, merged