samples: npm1300_fuel_gauge: README: Added app note link.
nrfconnect/sdk-nrf pull request #16615
Opened 2024-07-25 09:56 UTC by aasinclair

Added link to fuel gauge application note in summary.

2024-07-25 12:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16615
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-29 09:21 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16615/3/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16615/3/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-07-29 15:33 UTC, WalkingTalkingPotato approved these changes

2024-08-09 08:12 UTC, peknis requested changes

2024-08-09 08:12 UTC, peknis commented on samples/pmic/native/npm1300_fuel_gauge/README.rst
> +For more information about fuel gauging with the nPM1300, see `Using the nPM1300 Fuel Gauge <Using the nPM1300 Fuel Gauge_>`_.
```suggestion
For more information about fuel gauging with the nPM1300, see `Using the nPM1300 Fuel Gauge`_.
```

2024-08-09 10:19 UTC, peknis approved these changes

2024-08-09 12:56 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 5
### Inputs:
#### Sources:
sdk-nrf: PR head: [792f0e96b2f016fde913dcc98fc3182c9a76c60f](https://github.com/nrfconnect/sdk-nrf/pull/16615/commits/792f0e96b2f016fde913dcc98fc3182c9a76c60f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [792f0e96b2f016fde913dcc98fc3182c9a76c60f](https://github.com/nrfconnect/sdk-nrf/pull/16615/commits/792f0e96b2f016fde913dcc98fc3182c9a76c60f)
> merge base: [4f7a150b2d8bc91831c56d709e1f64e811c60791](https://github.com/nrfconnect/sdk-nrf/commit/4f7a150b2d8bc91831c56d709e1f64e811c60791)
> target head (main): [eaa0f92f95326c616f9c6b62d8992eef8a1e4368](https://github.com/nrfconnect/sdk-nrf/commit/eaa0f92f95326c616f9c6b62d8992eef8a1e4368)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
doc
│  ├── nrf
│  │  │ links.txt
samples
│  ├── pmic
│  │  ├── native
│  │  │  ├── npm1300_fuel_gauge
│  │  │  │  │ README.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-12 11:00 UTC, merged