lib: lte_link_control: Remove deprecated (de)init functions
nrfconnect/sdk-nrf pull request #16629
Opened 2024-07-26 04:59 UTC by trantanen

Removing the following functions that have been deprecated by PR #13057:

- lte_lc_init()
- lte_lc_init_and_connect()
- lte_lc_init_and_connect_async()
- lte_lc_deinit()

2024-07-26 05:00 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16629/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16629/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-boot | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-sdk-mcuboot | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16629/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-26 05:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16629
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-26 07:42 UTC, eivindj-nordic approved these changes

2024-07-26 07:42 UTC, lemrey approved these changes
Thanks

2024-07-26 08:21 UTC, MirkoCovizzi approved these changes

2024-07-26 10:49 UTC, FrancescoSer requested changes

2024-07-26 10:49 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +      Use the :c:func:`lte_lc_connect_async` function instead.
```suggestion
    * The :c:func:`lte_lc_init` function.
      All instances of this function can be removed without any additional actions.
    * The :c:func:`lte_lc_deinit` function.
      Use the :c:func:`lte_lc_power_off` function instead.
    * The :c:func:`lte_lc_init_and_connect` function.
      Use the :c:func:`lte_lc_connect` function instead.
    * The :c:func:`lte_lc_init_and_connect_async` function.
      Use the :c:func:`lte_lc_connect_async` function instead.
```

2024-07-26 10:49 UTC, FrancescoSer commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +     * Replace the use of the :c:func:`lte_lc_init_and_connect_async` function with the :c:func:`lte_lc_connect_async` function.
```suggestion
   * For applications using :ref:`lte_lc_readme`:

     * Remove all instances of the :c:func:`lte_lc_init` function.
     * Replace the use of the :c:func:`lte_lc_deinit` function with the :c:func:`lte_lc_power_off` function.
     * Replace the use of the :c:func:`lte_lc_init_and_connect` function with the :c:func:`lte_lc_connect` function.
     * Replace the use of the :c:func:`lte_lc_init_and_connect_async` function with the :c:func:`lte_lc_connect_async` function.
```

2024-07-26 11:59 UTC, greg-fer approved these changes

2024-07-26 12:37 UTC, FrancescoSer approved these changes

2024-07-29 07:29 UTC, tokangas approved these changes

2024-07-29 07:44 UTC, merged