Samples: Bluetooth: Fix use of local obtained conn refs
nrfconnect/sdk-nrf pull request #16638
Opened 2024-07-26 13:41 UTC by rugeGerritsen

The returned reference is unused.

Found using the semantic patch file:
```
@@
local idexpression conn;
identifier e;
statement S1;
@@
* e = bt_conn_le_create(..., &conn);
... when != bt_conn_unref(conn)
    when != if (e == 0) { <+... bt_conn_unref(conn) ...+> } else S1
```

2024-07-26 13:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16638/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16638/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16638/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-26 16:07 UTC, alwa-nordic requested changes
This is a step in the right direction. It correctly disposes of the reference when we drop the pointer. But the code leaves the local optimum of "it's weird, but it works" and probably does not work anymore.

We must remove all other `bt_conn_unref(conn);` in these files at the same time, since I suspect those are all disposing of the same reference (the one from `bt_conn_le_create`).

2024-07-29 07:28 UTC, alwa-nordic approved these changes

2024-07-29 07:37 UTC, KAGA164 approved these changes

2024-07-29 11:04 UTC, merged