Bluetooth: Mesh: add changelog for added metadata to mesh models
nrfconnect/sdk-nrf pull request #16643
Opened 2024-07-29 08:49 UTC by KyraLengfeld

This commit adds the changelog for commit:
57daf41e953086d5d023b11599155e15c2d46b2e

2024-07-29 08:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16643/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16643/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-07-29 09:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16643
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-07-30 06:35 UTC, alxelax approved these changes

2024-07-30 06:51 UTC, mia-ko requested changes
Not sure if the location is ok, or if it fits better under Libraries for Bluetooth Mesh.

2024-07-30 06:51 UTC, mia-ko commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +   To use :kconfig:option:`CONFIG_BT_MESH_LARGE_COMP_DATA_SRV` needs to be enabled.
```suggestion
 * Added metadata as optional parameter for models Light Lightness Server, Light HSL Server, Light CTL Temperature Server, Sensor Server, and Time Server.
   To use the metadata, enable the :kconfig:option:`CONFIG_BT_MESH_LARGE_COMP_DATA_SRV` Kconfig option.
```

2024-07-30 10:59 UTC, mia-ko approved these changes

2024-07-30 11:42 UTC, merged