drivers: wifi: Add tx packets drop count calculation
nrfconnect/sdk-nrf pull request #16646
Opened 2024-07-29 09:44 UTC by kapbh

[SHEL-1063] Add calculation of drop packets in tx due to lack of buffer memory.

2024-07-29 09:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16646/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16646/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16646/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-30 11:19 UTC, sachinthegreen requested changes

2024-07-30 11:19 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +	struct rpu_host_stats *host_stats = NULL;
Where is this getting initialized before being used on line 317?

2024-07-30 11:19 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +	void *net_buff_check = NULL;
```suggestion
	void *nbuf = NULL;
```

2024-07-30 11:19 UTC, sachinthegreen commented on drivers/wifi/nrf700x/src/net_if.c
> +	}
Doesn't `net_buff_check` need to get used further (assuming it was allocated successfully above) ?

2024-08-06 07:21 UTC, krish2718 approved these changes

2024-08-06 11:54 UTC, sachinthegreen approved these changes

2024-08-06 11:59 UTC, merged