Cracen: Fix import/export/generate key implemenations
nrfconnect/sdk-nrf pull request #16671
Opened 2024-07-30 12:08 UTC by vili-nordic

Fixes some double read inconsitiencies and key validation in Cracen key management implementation.

2024-07-30 12:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16671/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16671/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-sdk-dfu | X | | |
| test-sdk-find-my | X | | |
| test-sdk-sidewalk | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16671/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-07-30 15:03 UTC, Vge0rge commented on subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
> +	uint8_t key_workbuf[PSA_KEY_EXPORT_RSA_KEY_PAIR_MAX_SIZE(PSA_MAX_RSA_KEY_BITS)];
Hm, why is this needed for the key generation?

2024-08-01 07:44 UTC, Vge0rge approved these changes

2024-08-08 14:04 UTC, tomi-font requested changes

2024-08-08 14:04 UTC, tomi-font commented on subsys/nrf_security/src/drivers/cracen/common/include/cracen/mem_helpers.h
> + * \brief Will copy memory, verifying that the buffer is non-zero.
```suggestion
 * \brief Will copy memory, verifying that the source buffer is non-zero.
```

2024-08-09 06:20 UTC, tomi-font approved these changes

2024-08-12 12:24 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 15
### Inputs:
#### Sources:
sdk-nrf: PR head: [6e462f4c71605f4fef636bcb7cbe84a80c941885](https://github.com/nrfconnect/sdk-nrf/pull/16671/commits/6e462f4c71605f4fef636bcb7cbe84a80c941885)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [6e462f4c71605f4fef636bcb7cbe84a80c941885](https://github.com/nrfconnect/sdk-nrf/pull/16671/commits/6e462f4c71605f4fef636bcb7cbe84a80c941885)
> merge base: [88b0fa1bcbc86d1acae0c1c4eca5284224c73fdb](https://github.com/nrfconnect/sdk-nrf/commit/88b0fa1bcbc86d1acae0c1c4eca5284224c73fdb)
> target head (main): [158854d0ee7de1a0e4532a8b10cc2b1ceb35f538](https://github.com/nrfconnect/sdk-nrf/commit/158854d0ee7de1a0e4532a8b10cc2b1ceb35f538)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
subsys
│  ├── nrf_security
│  │  ├── src
│  │  │  ├── drivers
│  │  │  │  ├── cracen
│  │  │  │  │  ├── common
│  │  │  │  │  │  ├── include
│  │  │  │  │  │  │  ├── cracen
│  │  │  │  │  │  │  │  │ mem_helpers.h
│  │  │  │  │  ├── cracenpsa
│  │  │  │  │  │  ├── src
│  │  │  │  │  │  │  ├── key_management.c
│  │  │  │  │  │  │  │ mem_helpers.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nrf_crypto
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-dfu

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-13 10:55 UTC, merged