mpsl: Stop calibration work on mpsl uninit
nrfconnect/sdk-nrf pull request #16731
Opened 2024-08-02 12:23 UTC by hermabe

The mpsl api shall not be used after mpsl is uninitialized.

MPSL requests the HFXO when doing LFRC calibration. However, when MPSL is uninitialized it does not handle the CLOCK DONE event and does not release the HFXO, leaving the HFXO running and consuming power.

---

There may be a nicer way to stop the work handler from running, but the zephyr plug api does not prevent the work item to resubmit itself, which is the case here.

2024-08-08 11:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16731/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16731/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test_ble_commit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16731/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2024-08-08 15:07 UTC, martintv approved these changes

2024-08-09 11:28 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 3
### Inputs:
#### Sources:
sdk-nrf: PR head: [544ca9a3a856b1b6d8e7990d9ad9917d99f3989d](https://github.com/nrfconnect/sdk-nrf/pull/16731/commits/544ca9a3a856b1b6d8e7990d9ad9917d99f3989d)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [544ca9a3a856b1b6d8e7990d9ad9917d99f3989d](https://github.com/nrfconnect/sdk-nrf/pull/16731/commits/544ca9a3a856b1b6d8e7990d9ad9917d99f3989d)
> merge base: [d11dcb6ec251f0ece98fa05aa42aaeb401ba21ae](https://github.com/nrfconnect/sdk-nrf/commit/d11dcb6ec251f0ece98fa05aa42aaeb401ba21ae)
> target head (main): [fcd3171040c5581b57d2de984fa38a53bd6ece21](https://github.com/nrfconnect/sdk-nrf/commit/fcd3171040c5581b57d2de984fa38a53bd6ece21)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
subsys
│  ├── mpsl
│  │  ├── init
│  │  │  │ mpsl_init.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test_ble_commit
   - :orange_circle: test-fw-nrfconnect-ble_samples
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-rs
   - :orange_circle: test-fw-nrfconnect-fem
   - :orange_circle: test-fw-nrfconnect-thread
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-tfm
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-09 12:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16731
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-12 05:40 UTC, wiba-nordic requested changes

2024-08-12 05:40 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed an issue where the HFXO would be left on after uninitializing MPSL when the RC oscillator was used as the Low Frequency clock source (DRGN-22809).
```suggestion
  * An issue where the HFXO would be left on after uninitializing MPSL when the RC oscillator was used as the Low Frequency clock source (DRGN-22809).
```

2024-08-12 09:38 UTC, wiba-nordic approved these changes

2024-08-12 10:42 UTC, merged