doc: Add changelog entry for BT APIs converting err to string
nrfconnect/sdk-nrf pull request #16745
Opened 2024-08-05 12:28 UTC by rugeGerritsen

The new APIs will simplify debugging issues.
The APIs are used in samples and audio app, see
https://github.com/nrfconnect/sdk-nrf/pull/16729
and
https://github.com/nrfconnect/sdk-nrf/pull/16733

2024-08-05 12:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16745/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-16745/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2024-08-05 12:38 UTC, alwa-nordic approved these changes

2024-08-05 13:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16745
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-06 06:15 UTC, wiba-nordic requested changes
The first two lines should be added to the Bluetooth samples section as well.

Maybe to the nRF5340 audio section as well. @alwa-nordic Do you think this is a notable enough change that it should be mentioned for the application section?

2024-08-06 06:15 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  The APIs return string representations of the error codes when :kconfig:option:`CONFIG_BT_HCI_ERR_TO_STR` and :kconfig:option:`CONFIG_BT_SECURITY_ERR_TO_STR` are enabled.
```suggestion
  Each API returns string representations of the error codes when the corresponding Kconfig option, :kconfig:option:`CONFIG_BT_HCI_ERR_TO_STR` or :kconfig:option:`CONFIG_BT_SECURITY_ERR_TO_STR` Kconfig, is enabled.
```

2024-08-06 06:15 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  The Bluetooth samples and :ref:`nrf53_audio_app` are updated to utilize these new APIs.
```suggestion
  The :ref:`ble_samples` and :ref:`nrf53_audio_app` are updated to utilize these new APIs.
```

2024-08-06 06:20 UTC, wiba-nordic commented
> Maybe to the nRF5340 audio section as well. @alwa-nordic Do you think this is a notable enough change that it should be mentioned for the application section?

Or I guess @alexsven who reviewed the related PR.

2024-08-07 06:40 UTC, wiba-nordic requested changes

2024-08-07 06:40 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The APIs :c:func:`bt_hci_err_to_str` and :c:func:`bt_security_err_to_str` are used to allow printing error codes as strings.
```suggestion
  * The APIs :c:func:`bt_hci_err_to_str` and :c:func:`bt_security_err_to_str` that are used to allow printing error codes as strings.
```

2024-08-07 06:43 UTC, wiba-nordic approved these changes

2024-08-07 06:56 UTC, alexsven approved these changes

2024-08-07 07:39 UTC, merged