boards: thingy91x: revert to nrfjprog
nrfconnect/sdk-nrf pull request #16824
Opened 2024-08-09 14:46 UTC by maxd-nordic

Since the combination of nrf53, sysbuild and nrfutil is not working properly, I suggest to revert to nrfjprog for the time being. The relevant ticket is NCSDK-28655.

2024-08-09 14:48 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [2a8a42c66235caa4bddf49f8dcb230d93285fdab](https://github.com/nrfconnect/sdk-nrf/pull/16824/commits/2a8a42c66235caa4bddf49f8dcb230d93285fdab)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [2a8a42c66235caa4bddf49f8dcb230d93285fdab](https://github.com/nrfconnect/sdk-nrf/pull/16824/commits/2a8a42c66235caa4bddf49f8dcb230d93285fdab)
> merge base: [6d766d8d07cc5198bbfc735d0253a3c6a23b288b](https://github.com/nrfconnect/sdk-nrf/commit/6d766d8d07cc5198bbfc735d0253a3c6a23b288b)
> target head (main): [6d766d8d07cc5198bbfc735d0253a3c6a23b288b](https://github.com/nrfconnect/sdk-nrf/commit/6d766d8d07cc5198bbfc735d0253a3c6a23b288b)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
boards
│  ├── nordic
│  │  ├── thingy91x
│  │  │  │ board.cmake
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-14 11:06 UTC, bjda approved these changes

2024-08-20 08:55 UTC, nordicjm requested changes

2024-08-20 08:55 UTC, nordicjm commented on boards/nordic/thingy91x/board.cmake
>    board_runner_args(nrfutil "--nrf-family=NRF53")
these arguments are wrong for nrfjprog

2024-08-20 08:56 UTC, nordicjm approved these changes
Is handled by python code apparently, not directly passed to application

2024-08-20 08:56 UTC, merged