doc: Update the bt_rpc doc with sysbuild
nrfconnect/sdk-nrf pull request #16867
Opened 2024-08-14 10:18 UTC by dchat-nordic

Update the bt_rpc doc with sysbuild options.
Promote the ipc_radio application.

Jira: NCSDK-28519

2024-08-14 10:23 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
sdk-nrf: PR head: [38d9c0f548e476d9e2857f87d36ae61af340e024](https://github.com/nrfconnect/sdk-nrf/pull/16867/commits/38d9c0f548e476d9e2857f87d36ae61af340e024)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [38d9c0f548e476d9e2857f87d36ae61af340e024](https://github.com/nrfconnect/sdk-nrf/pull/16867/commits/38d9c0f548e476d9e2857f87d36ae61af340e024)
> merge base: [030eccd89ae04eb09c849f7ca5cc42cbd6efec46](https://github.com/nrfconnect/sdk-nrf/commit/030eccd89ae04eb09c849f7ca5cc42cbd6efec46)
> target head (main): [1f825c47121b3aae172fdbb612f0e466898945c9](https://github.com/nrfconnect/sdk-nrf/commit/1f825c47121b3aae172fdbb612f0e466898945c9)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all downstreams_ | 
|| ci-force-downstream | _Force execution of downstream_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
doc
│  ├── nrf
│  │  ├── libraries
│  │  │  ├── bluetooth_services
│  │  │  │  │ rpc.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_commit
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-14 10:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16867
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-14 13:52 UTC, grochu requested changes
There are small TYPO and my other comments are suggestions for improvement.

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +  * :ref:`ipc_radio` application that includes the full configuaration for Bluetooth Low Energy stack, Bluetooth RPC Host, and common libraries that enable communication with the Bluetooth RPC Client
```suggestion
  * :ref:`ipc_radio` application that includes the full configuration of the Bluetooth Low Energy stack, Bluetooth RPC Host and common libraries that enable communication with the Bluetooth RPC Client.
```

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +To keep all the above configuration options in sync, create a snipptet with an overlay file that is shared between the application and network core.
```suggestion
To keep all the above configuration options in sync, you can create a snippet with an overlay file that is shared between the application and network core.
```
Also consider linking to sysbuild snippet documentation: https://docs.nordicsemi.com/bundle/ncs-latest/page/zephyr/build/snippets/index.html.

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +   west build -b *board_target* -Smy_snippet
```suggestion
   west build -b *board_target* -S my_snippet
```

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +   west build -b nrf5340dk/nrf5340/cpuapp -Snordic-bt-rpc -- -DSB_CONFIG_NETCORE_IPC_RADIO=y -DSB_CONFIG_NETCORE_IPC_RADIO_BT_RPC=y
```suggestion
   west build -b board_name -S nordic-bt-rpc -- -DSB_CONFIG_NETCORE_IPC_RADIO=y -DSB_CONFIG_NETCORE_IPC_RADIO_BT_RPC=y
```

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +   The samples which support the Bluetooth Low Energy RPC use the :makevar:`FILE_SUFFIX` along with :makevar:`SNIPPET` to adjust the network/radio core selection and configuration.
Suggestion:
```suggestion
   The samples which support the Bluetooth Low Energy RPC use the :makevar:`FILE_SUFFIX` along with :makevar:`SNIPPET` to adjust the selection and configuration of the network/radio core firmware.
```

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +The :ref:`ipc_radio` sample, is a configurable sample, which exposes the Bluetooth LE stack functionality that runs on an MCU with radio (for example, the nRF5340 network core) to another CPU using t
```suggestion
The :ref:`ipc_radio` sample, is a configurable application, that exposes the Bluetooth LE stack functionality running on an MCU with radio (for example, the nRF5340 network core) to another CPU through the :ref:`nrfxlib:nrf_rpc`.
```

2024-08-14 13:52 UTC, grochu commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +When using the :ref:`ipc_radio` as Bluetooth Low Energy over RPC reconfigure it by setting the ``SB_CONFIG_NETCORE_IPC_RADIO_BT_RPC=y`` Sysbuild Kconfig option to run the Bluetooth LE stack on the ne
```suggestion
When using the :ref:`ipc_radio` as Bluetooth Low Energy over RPC reconfigure it by setting the ``SB_CONFIG_NETCORE_IPC_RADIO_BT_RPC=y`` Sysbuild Kconfig option to run the whole Bluetooth LE stack on the network core.
```

2024-08-15 11:21 UTC, divipillai commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +When using the :ref:`ipc_radio` as Bluetooth Low Energy over RPC reconfigure it by setting the ``SB_CONFIG_NETCORE_IPC_RADIO_BT_RPC=y`` Sysbuild Kconfig option to run the Bluetooth LE stack on the ne
```suggestion
When using the :ref:`ipc_radio` as Bluetooth Low Energy over RPC, reconfigure it by setting the ``SB_CONFIG_NETCORE_IPC_RADIO_BT_RPC`` sysbuild Kconfig option to ``y`` to run the whole Bluetooth LE stack on the network core.
```

2024-08-15 11:21 UTC, divipillai commented on doc/nrf/libraries/bluetooth_services/rpc.rst
> +For more details, see :ref:`ipc_radio_config`.
```suggestion
For more details, see the :ref:`Configuration <ipc_radio_config>` section of the IPC radio firmware application guide.
```

2024-08-20 09:03 UTC, divipillai approved these changes

2024-08-20 10:11 UTC, maje-emb approved these changes

2024-08-21 11:47 UTC, grochu approved these changes
Looks good

2024-08-22 11:38 UTC, merged