Radio samples: nrf54h20 Clock Control driver support
nrfconnect/sdk-nrf pull request #16909
Opened 2024-08-19 10:01 UTC by KAGA164

This add support for Clock Control driver for nRF54h20 in radio samples that require manual control of HFXO clock.
Clock Control is in PR and needs go first: https://github.com/nrfconnect/sdk-zephyr/pull/1920

2024-08-19 12:51 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [1d3b6c9ccda8f6867f9846724055cf2c6889202c](https://github.com/nrfconnect/sdk-nrf/pull/16909/commits/1d3b6c9ccda8f6867f9846724055cf2c6889202c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [1d3b6c9ccda8f6867f9846724055cf2c6889202c](https://github.com/nrfconnect/sdk-nrf/pull/16909/commits/1d3b6c9ccda8f6867f9846724055cf2c6889202c)
> merge base: [56a03272a7444ec5f5d3f6d00a5316d58730b34f](https://github.com/nrfconnect/sdk-nrf/commit/56a03272a7444ec5f5d3f6d00a5316d58730b34f)
> target head (main): [29d06abd637a7712762fe32ed09f1fa15825678b](https://github.com/nrfconnect/sdk-nrf/commit/29d06abd637a7712762fe32ed09f1fa15825678b)> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/56a03272a7444ec5f5d3f6d00a5316d58730b34f..1d3b6c9ccda8f6867f9846724055cf2c6889202c)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
samples
│  ├── bluetooth
│  │  ├── direct_test_mode
│  │  │  ├── src
│  │  │  │  │ dtm.c
│  ├── esb
│  │  ├── esb_prx
│  │  │  ├── src
│  │  │  │  │ main.c
│  │  ├── esb_ptx
│  │  │  ├── src
│  │  │  │  │ main.c
│  ├── peripheral
│  │  ├── radio_test
│  │  │  ├── src
│  │  │  │  │ main.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples
   - :orange_circle: test-fw-nrfconnect-proprietary_esb

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-20 08:28 UTC, dchat-nordic approved these changes

2024-09-17 14:46 UTC, maje-emb requested changes
On the nRF54H20 `CONFIG_CLOCK_CONTROL_NRF2` is not enabled by default, the sample build fails due to assert: `BUILD_ASSERT(false, "No Clock Control driver");`

2024-09-18 10:33 UTC, doki-nordic commented
> On the nRF54H20 `CONFIG_CLOCK_CONTROL_NRF2` is not enabled by default, the sample build fails due to assert: `BUILD_ASSERT(false, "No Clock Control driver");`

@anangl will look at this issue. Probably it should be enabled by default.

2024-10-16 14:19 UTC, doki-nordic commented
Depends on: https://github.com/zephyrproject-rtos/zephyr/pull/79117

2024-10-24 05:27 UTC, doki-nordic approved these changes

2024-10-24 06:34 UTC, maje-emb approved these changes

2024-10-24 06:34 UTC, maje-emb commented on samples/bluetooth/direct_test_mode/src/dtm.c
> +#endif /* defined(NRF54L15_XXAA) */
NRF_CLOCK_TASK_PLLSTART task triggering applies to nRF54L15. 
Since CONFIG_CLOCK_CONTROL_NRF2 is for nRF54HX, it seems that this part is redundant.

2024-11-07 08:10 UTC, doki-nordic commented
> [!IMPORTANT]
> **This PR has problems with CI, so it was replaced by the https://github.com/nrfconnect/sdk-nrf/pull/18694.**

2024-11-07 08:10 UTC, closed without merging