net: lib: nrf_cloud: send obj data for all topics
nrfconnect/sdk-nrf pull request #16904
Opened 2024-08-16 22:52 UTC by jayteemo

Fixed an issue in nrf_cloud_send() that prevented data in the provided nrf_cloud_obj structure from being sent to the bulk and bin topics.
IRIS-9540

2024-08-16 22:53 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-16 23:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16904
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-19 18:10 UTC, plskeggs approved these changes

2024-08-20 21:47 UTC, glarsennordic approved these changes
I can't spot what actually changed, functionally -- this looks like a refactor to me with no functionality changes?

The refactor looks good, so I am approving, but can you point out the functionality difference? I apologize

2024-08-20 21:50 UTC, jayteemo commented
> but can you point out the functionality difference? I apologize

for the bulk and bin topics:
```
.data.ptr = msg->data.ptr,
.data.len = msg->data.len,
```

should use the `send_data`

2024-08-20 22:11 UTC, glarsennordic commented
Ahhh, thank you, I see it now

2024-08-21 07:21 UTC, wiba-nordic requested changes

2024-08-21 07:21 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Fixed an issue in :c:func:`nrf_cloud_send` that prevented data in the provided :c:struct:`nrf_cloud_obj` structure from being sent to the bulk and bin topics.
```suggestion
  * Fixed an issue in the :c:func:`nrf_cloud_send` function that prevented data in the provided :c:struct:`nrf_cloud_obj` structure from being sent to the bulk and bin topics.
```

2024-08-21 16:26 UTC, tony-le-24 approved these changes
LGTM

2024-08-22 06:03 UTC, wiba-nordic approved these changes

2024-08-22 06:30 UTC, merged