doc: liblwm2m_carrier: doc_improvements
nrfconnect/sdk-nrf pull request #16931
Opened 2024-08-20 13:18 UTC by nordic-hani

Improve the LwM2M carrier library API documentation.

- Move relevant header documentation from rst over to the header file.
- Remove redundant documentation.
- Tweaks to groups and overall structure.

2024-08-20 13:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16931
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-29 12:14 UTC, kacperradoszewski requested changes

2024-08-29 12:14 UTC, kacperradoszewski commented on lib/bin/lwm2m_carrier/include/lwm2m_carrier.h
> + * Read of the OMA LwM2M `Device` object `Current Time` resource (/3/0/13).
I think this would be better here and below
```suggestion
 * Read the OMA LwM2M `Device` object `Current Time` resource (/3/0/13).
```

2024-08-29 12:14 UTC, kacperradoszewski commented on lib/bin/lwm2m_carrier/include/lwm2m_carrier.h
> + * @param[in]  latitude    Latitude in degrees (/6/0/0). Must be between -90.0 and 90.0.
```suggestion
 * @param[in]  latitude    Latitude (/6/0/0) in degrees. Must be between -90.0 and 90.0.
```
and so on

2024-09-06 12:49 UTC, nordic-hani commented on lib/bin/lwm2m_carrier/include/lwm2m_carrier.h
>  #define LWM2M_CARRIER_ERROR_BOOTSTRAP		3
Made internal ticket NCSDK-29079

2024-09-06 20:09 UTC, kacperradoszewski approved these changes

2024-09-10 10:46 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
> +The following message sequence chart shows the state the LwM2M carrier library and the events given to the application up until the successful registration with an LwM2M device management server:
```suggestion
The following message sequence chart shows the state of the LwM2M carrier library and the events given to the application up until the successful registration with an LwM2M device management server:
```

2024-09-10 10:46 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
> +The following message sequence chart shows that FOTA fails at run time if an invalid if a downloaded fragment fails to be verified:
```suggestion
The following message sequence chart shows that FOTA fails at runtime if an invalid downloaded fragment fails to be verified:
```

2024-09-10 10:46 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
> +The following message sequence chart shows the c:func:`lwm2m_carrier_request()` API being used to deregister from the server:
```suggestion
The following message sequence chart shows the :c:func:`lwm2m_carrier_request()` API being used to deregister from the server:
```

2024-09-10 10:46 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
> +The following message sequence chart shows examples of the c:macro:`LWM2M_CARRIER_EVENT_DEFERRED` event being issued when connecting to a bootstrap server:
```suggestion
The following message sequence chart shows examples of the :c:macro:`LWM2M_CARRIER_EVENT_DEFERRED` event being issued when connecting to a bootstrap server:
```

2024-09-10 10:46 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
> +The following message sequence chart shows examples of the c:macro:`LWM2M_CARRIER_EVENT_DEFERRED` event being issued when connecting to a LwM2M server:
```suggestion
The following message sequence chart shows examples of the :c:macro:`LWM2M_CARRIER_EVENT_DEFERRED` event being issued when connecting to a LwM2M server:
```

2024-09-11 08:05 UTC, divipillai approved these changes

2024-09-13 10:22 UTC, rlubos approved these changes

2024-09-13 10:22 UTC, merged