tools: update requirements for nrf-regtool
nrfconnect/sdk-nrf pull request #16958
Opened 2024-08-21 14:43 UTC by PerMac

5.6.0 is required by
https://github.com/zephyrproject-rtos/zephyr/
blob/main/modules/hal_nordic/CMakeLists.txt#L15.

2024-08-21 14:45 UTC, NordicBuilder commented
This pr introduces changes to requirements files.
The compiled requirements-fixed.txt has changed.
To automatically add the changed file to this pr react with the :eyes: emote to this comment and re-run the check.
[Check Run](https://github.com/nrfconnect/sdk-nrf/actions/runs/10492056645)
<details>
  <summary>requirements-fixed.txt diff</summary>

  ``` diff
  diff --git a/scripts/requirements-fixed.txt b/scripts/requirements-fixed.txt
index 182fa50..d620f62 100644
--- a/scripts/requirements-fixed.txt
+++ b/scripts/requirements-fixed.txt
@@ -70,7 +70,7 @@ msgpack==1.0.5            # via python-can
 mypy==1.5.1               # via -r zephyr/scripts/requirements-build-test.txt
 mypy-extensions==1.0.0    # via mypy
 natsort==8.4.0            # via pyocd
-nrf-regtool==5.5.1        # via -r nrf/scripts/requirements-build.txt
+nrf-regtool==5.6.0        # via -r nrf/scripts/requirements-build.txt
 nrfcredstore==1.0.0       # via -r nrf/scripts/requirements-extra.txt
 numpy==1.26.4             # via svada
 packaging==24.0           # via -r zephyr/scripts/requirements-base.txt, pkg-about, pytest, python-can, setuptools-scm, west
  ```
</details>


*Note: This comment is automatically posted and updated by the Comment GitHub Action.*

2024-08-21 14:46 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [5d6700292587e2c3746e79be0e76a52a127b7278](https://github.com/nrfconnect/sdk-nrf/pull/16958/commits/5d6700292587e2c3746e79be0e76a52a127b7278)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [5d6700292587e2c3746e79be0e76a52a127b7278](https://github.com/nrfconnect/sdk-nrf/pull/16958/commits/5d6700292587e2c3746e79be0e76a52a127b7278)
> merge base: [72b43d22b0e8342cacbce17e198a3829d5612705](https://github.com/nrfconnect/sdk-nrf/commit/72b43d22b0e8342cacbce17e198a3829d5612705)
> target head (main): [72b43d22b0e8342cacbce17e198a3829d5612705](https://github.com/nrfconnect/sdk-nrf/commit/72b43d22b0e8342cacbce17e198a3829d5612705)> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/72b43d22b0e8342cacbce17e198a3829d5612705..5d6700292587e2c3746e79be0e76a52a127b7278)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
scripts
│  │ requirements-build.txt
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-21 15:43 UTC, gmarull requested changes
this requires bringing pinctrl clockpin changes

2024-08-21 18:57 UTC, shanthanordic commented
@57300  should approve this PR before merging.

2024-08-22 07:10 UTC, PerMac commented
> this requires bringing pinctrl clockpin changes

I assume those will come with the ongoing upmerge? Without newer regtool nrf54h20 prints no output. We can get it installed within our CI for now to unlock testing.

2024-08-22 07:13 UTC, gmarull commented
> > this requires bringing pinctrl clockpin changes
> 
> I assume those will come with the ongoing upmerge? Without newer regtool nrf54h20 prints no output. We can get it installed within our CI for now to unlock testing.

I guess this is upstream only, not downstream. They'll come with the next upmerge, if not, they can be easily cherry-picked in advance (it's strictly this single commit: 5e3188605ed94b3d2a01647187324415e31f4d07).

2024-08-23 09:22 UTC, 57300 requested changes
The required pinctrl changes are expected to go in with https://github.com/nrfconnect/sdk-zephyr/pull/1952

2024-09-13 09:25 UTC, closed without merging

2024-09-13 09:25 UTC, 57300 commented
Updated as part of #17197