doc:  Add release 2.4.4 to main
nrfconnect/sdk-nrf pull request #16960
Opened 2024-08-22 05:47 UTC by umapraseeda

Add release 2.4.4 to main

2024-08-22 05:52 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-22 06:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16960
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-22 08:04 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-2.4.4.rst
> +   git log --oneline manifest-rev ^v3.3.99-ncs2
Needs to be updated

2024-08-22 08:04 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-2.4.4.rst
> +The Zephyr fork in |NCS| (``sdk-zephyr``) contains all commits from the upstream Zephyr repository up to and including ``4bbd91a9083a588002d4397577863e0c54ba7038``.
SHA Needs to be updated

2024-08-22 08:05 UTC, umapraseeda commented on doc/nrf/releases_and_maturity/releases/release-notes-2.4.4.rst
> +
Needs to add the missing sentence.

2024-08-22 08:39 UTC, gmarull approved these changes

2024-08-22 09:12 UTC, richabp requested changes

2024-08-22 09:12 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-2.4.4.rst
> +* Added workarounds in sdk-zephyr for the Anomaly 168 and the Anomaly 165 that are affecting the nRF5340 SoC.
```suggestion
* Added workarounds in ``sdk-zephyr`` for the Anomaly 168 and the Anomaly 165 that are affecting the nRF5340 SoC.
```

2024-08-22 10:43 UTC, richabp approved these changes

2024-08-23 11:11 UTC, shanthanordic approved these changes

2024-08-23 11:17 UTC, merged