west.yml: Update zephyr to bring in zcbor 0.9.0
nrfconnect/sdk-nrf pull request #16974
Opened 2024-08-22 11:08 UTC by oyvindronningstad

Updated from 0.8.2

2024-08-22 11:09 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/8bd088c7c2936dbc94eddd5ede980d45a341e73d | https://github.com/nrfconnect/sdk-zephyr/pull/1966 | [nrfconnect/sdk-zephyr#1966/files](https://github.com/nrfconnect/sdk-zephyr/pull/1966/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-08-22 11:09 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-22 11:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16974
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-04 13:01 UTC, jonathannilsen approved these changes

2024-09-04 13:18 UTC, anhmolt approved these changes

2024-09-10 12:36 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug.uart[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 828[B]*** in comparison to the ***main[539fc039]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=uart&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 668[B]*** in comparison to the ***main[ef7c2048]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-16974/13)*

2024-09-11 08:26 UTC, tomchy approved these changes

2024-09-16 07:51 UTC, SeppoTakalo approved these changes

2024-09-16 09:52 UTC, e-rk approved these changes

2024-09-26 07:26 UTC, greg-fer requested changes

2024-09-26 07:26 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  Migration guide at https://github.com/NordicSemiconductor/zcbor/blob/0.9.0/MIGRATION_GUIDE.md
Links must be added through links.txt.

2024-09-26 07:26 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Allow --file-header to accept a path to a file with header contents
```suggestion
    * You can now decide at runtime whether the decoder should enforce canonical encoding.
    * Allow ``--file-header`` to accept a path to a file with header contents.
    * Many code generation bug fixes.
```

2024-09-26 07:26 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* fmfu_fdev: Regenerated generated code files using zcbor 0.9.0.
```suggestion
* :ref:`lib_fmfu_fdev`:

  * Regenerated the code files using zcbor v0.9.0.
```

2024-09-26 07:26 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* sdfw_services: Regenerated generated code files using zcbor 0.9.0.
Hey @FrancescoSer , do we have these libraries documented somewhere?

2024-09-26 07:26 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +----
```suggestion
Secure Domain Firmware (SDFW) libraries
---------------------------------------
```

2024-09-26 07:57 UTC, greg-fer commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +----
@oyvindronningstad , is this what you're referring to here?

2024-09-27 10:22 UTC, oyvindronningstad commented
@greg-fer Thanks for the review, all comments adressed.

2024-10-10 14:23 UTC, greg-fer approved these changes

2024-10-14 11:35 UTC, osaether approved these changes

2024-10-17 12:11 UTC, rlubos commented
@nrfconnect/ncs-co-build-system @nrfconnect/ncs-co-doc @nrfconnect/ncs-pluto Ping, please review

2024-10-17 13:03 UTC, nordicjm approved these changes

2024-10-18 13:31 UTC, tomchy approved these changes

2024-10-30 13:52 UTC, greg-fer approved these changes

2024-12-03 13:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-16974
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-03 14:55 UTC, umapraseeda approved these changes

2025-01-16 08:26 UTC, merged

2025-01-16 14:51 UTC, de-nordic approved these changes