cracen: Update platform key access checks for LCS
nrfconnect/sdk-nrf pull request #16997
Opened 2024-08-23 13:32 UTC by vili-nordic

Allows key access for local domains in some life cycle states.

2024-08-24 08:49 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [0679ac78025081a5754236ef7f329f32c86f9904](https://github.com/nrfconnect/sdk-nrf/pull/16997/commits/0679ac78025081a5754236ef7f329f32c86f9904)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [0679ac78025081a5754236ef7f329f32c86f9904](https://github.com/nrfconnect/sdk-nrf/pull/16997/commits/0679ac78025081a5754236ef7f329f32c86f9904)
> merge base: [5f15c74166ddfe5b9c298048adc807b875d7448e](https://github.com/nrfconnect/sdk-nrf/commit/5f15c74166ddfe5b9c298048adc807b875d7448e)
> target head (main): [01c2e80ae56be1411cd30baf2c4d03ba8e9cfef3](https://github.com/nrfconnect/sdk-nrf/commit/01c2e80ae56be1411cd30baf2c4d03ba8e9cfef3)> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/5f15c74166ddfe5b9c298048adc807b875d7448e..0679ac78025081a5754236ef7f329f32c86f9904)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
subsys
│  ├── nrf_security
│  │  ├── src
│  │  │  ├── drivers
│  │  │  │  ├── cracen
│  │  │  │  │  ├── cracenpsa
│  │  │  │  │  │  ├── src
│  │  │  │  │  │  │  ├── platform_keys
│  │  │  │  │  │  │  │  │ platform_keys.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nrf_crypto
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-dfu

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-27 10:37 UTC, Vge0rge approved these changes

2024-08-28 12:46 UTC, endre-nordic approved these changes

2024-08-29 10:41 UTC, hakonfam requested changes

2024-08-29 10:41 UTC, hakonfam commented on subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
> +		switch (lcs_get(domain_lcs)) {
If the domain is `SECURE` then this check should not be done. That way it will fail if the OEM keys are already installed.

2024-08-29 11:34 UTC, hakonfam requested changes

2024-08-29 11:34 UTC, hakonfam commented on subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
> +			return PSA_ERROR_NOT_PERMITTED;
```suggestion
		const int key_domain = PLATFORM_KEY_GET_DOMAIN(key_id);

		if (key_domain == 0) {
			/* OEM keys can be installed by any domain */
			return PSA_SUCCESS;
		}

		int status = nrf_domain_to_lcs_domain(key_domain, &domain_lcs);

		if (status != 0) {
			return PSA_ERROR_DOES_NOT_EXIST;

```

2024-08-29 11:34 UTC, hakonfam commented on subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
> +			return PSA_ERROR_NOT_PERMITTED;
This works when I'm testing. But please double check my logic

2024-08-30 12:18 UTC, hakonfam approved these changes

2024-09-03 10:33 UTC, merged