Add SPI/TWI stability test
nrfconnect/sdk-nrf pull request #17028
Opened 2024-08-27 08:06 UTC by nordic-segl

NRFX-6286: [Verification] Prepare POC for testing serial interface
Prepare test for serial interface (SPI/TWI) that can be used for stability testing in climate chamber.

2024-08-27 08:11 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [9e967c902080289918bb33751025692dab1eb5dc](https://github.com/nrfconnect/sdk-nrf/pull/17028/commits/9e967c902080289918bb33751025692dab1eb5dc)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [9e967c902080289918bb33751025692dab1eb5dc](https://github.com/nrfconnect/sdk-nrf/pull/17028/commits/9e967c902080289918bb33751025692dab1eb5dc)
> merge base: [b60eb4900e62bb7c771397adb152552849052b18](https://github.com/nrfconnect/sdk-nrf/commit/b60eb4900e62bb7c771397adb152552849052b18)
> target head (main): [59f75a70bd551c7b3317e1d4b9c086a398e0c8b4](https://github.com/nrfconnect/sdk-nrf/commit/59f75a70bd551c7b3317e1d4b9c086a398e0c8b4)> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/b60eb4900e62bb7c771397adb152552849052b18..9e967c902080289918bb33751025692dab1eb5dc)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (31)</summary>

```
CODEOWNERS
tests
│  ├── benchmarks
│  │  ├── i2c_endless
│  │  │  ├── CMakeLists.txt
│  │  │  ├── Kconfig
│  │  │  ├── README.txt
│  │  │  ├── boards
│  │  │  │  ├── nrf52840dk_nrf52840.conf
│  │  │  │  ├── nrf52840dk_nrf52840.overlay
│  │  │  │  ├── nrf5340dk_nrf5340_cpuapp.conf
│  │  │  │  ├── nrf5340dk_nrf5340_cpuapp.overlay
│  │  │  │  ├── nrf54h20dk_nrf54h20_cpuapp.conf
│  │  │  │  ├── nrf54h20dk_nrf54h20_cpuapp.overlay
│  │  │  │  ├── nrf54l15pdk_nrf54l15_cpuapp.conf
│  │  │  │  │ nrf54l15pdk_nrf54l15_cpuapp.overlay
│  │  │  ├── prj.conf
│  │  │  ├── src
│  │  │  │  │ main.c
│  │  │  │ testcase.yaml
│  │  ├── spi_endless
│  │  │  ├── CMakeLists.txt
│  │  │  ├── Kconfig
│  │  │  ├── README.txt
│  │  │  ├── boards
│  │  │  │  ├── 1mhz.overlay
│  │  │  │  ├── 250khz.overlay
│  │  │  │  ├── 2mhz.overlay
│  │  │  │  ├── 4mhz.overlay
│  │  │  │  ├── 500khz.overlay
│  │  │  │  ├── 8mhz.overlay
│  │  │  │  ├── nrf52840dk_nrf52840.overlay
│  │  │  │  ├── nrf54h20dk_nrf54h20_common.dtsi
│  │  │  │  ├── nrf54h20dk_nrf54h20_cpuapp.overlay
│  │  │  │  │ nrf54l15pdk_nrf54l15_cpuapp.overlay
│  │  │  ├── prj.conf
│  │  │  ├── src
│  │  │  │  │ main.c
│  │  │  │ testcase.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-27 08:19 UTC, katgiadla requested changes

2024-08-27 08:19 UTC, katgiadla commented on tests/benchmarks/i2c_endless/testcase.yaml
> +
Please add obligatory `intergation_platforms` section

2024-08-27 08:19 UTC, katgiadla commented on tests/benchmarks/spi_endless/testcase.yaml
> +
Please add obligatory `intergation_platforms` section too.

2024-08-27 08:32 UTC, nordic-segl commented on tests/benchmarks/spi_endless/testcase.yaml
> +
Done

2024-08-27 09:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17028
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-08-27 11:46 UTC, nordic-piks commented on tests/benchmarks/i2c_endless/src/main.c
> +static const struct device *spim_dev = DEVICE_DT_GET(DT_BUS(NODE_SENSOR));
spim_dev? in i2c test?

2024-08-27 11:50 UTC, nordic-piks commented on tests/benchmarks/i2c_endless/src/main.c
> +		ret = i2c_write(spim_dev, i2c_twim_buffer, DATA_FIELD_LEN,
spim_dev?

2024-08-27 11:59 UTC, nordic-segl commented on tests/benchmarks/i2c_endless/src/main.c
> +#define NODE_SENSOR DT_NODELABEL(sensor)
I can change to NODE_SLAVE :smile: if You are not afraid of inclusive language.
SPIS on other board is called here a sensor.

2024-08-27 12:11 UTC, nordic-segl commented on tests/benchmarks/i2c_endless/src/main.c
> +static const struct device *spim_dev = DEVICE_DT_GET(DT_BUS(NODE_SENSOR));
copy-paste error. Fixed

2024-08-27 12:12 UTC, nordic-segl commented on tests/benchmarks/i2c_endless/src/main.c
> +		ret = i2c_write(spim_dev, i2c_twim_buffer, DATA_FIELD_LEN,
copy-paste error. Fixed

2024-08-29 12:22 UTC, katgiadla approved these changes

2024-09-02 14:12 UTC, merged