samples: cellular: nrf_cloud_multi_service: Thingy91:X Wi-Fi
nrfconnect/sdk-nrf pull request #17066
Opened 2024-08-28 21:57 UTC by plskeggs

Merge overlay and config info from ATv2 and 7002EK shield to get MSS with Wi-Fi scanning to build and run.

2024-08-28 21:58 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests

<details><summary>Disable integration tests</summary>

- 
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-28 22:03 UTC, jayteemo approved these changes

2024-08-30 01:35 UTC, glarsennordic approved these changes

2024-09-05 02:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17066
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-05 06:42 UTC, wiba-nordic requested changes

2024-09-05 06:42 UTC, wiba-nordic commented on samples/cellular/nrf_cloud_multi_service/README.rst
> +For the Thingy:91 X, which contains both an nRF9151 and the nRF7002, the build command is simpler.
```suggestion
For the Thingy:91 X, which contains both an nRF9151 System-in-Package and the nRF7002 Companion IC, the build command is simpler.
```

2024-09-06 05:58 UTC, wiba-nordic approved these changes

2024-09-06 18:45 UTC, tony-le-24 approved these changes

2024-09-09 07:22 UTC, merged