manifest: Bring Zephyr with memconf for 54L
nrfconnect/sdk-nrf pull request #17075
Opened 2024-08-29 10:32 UTC by Vge0rge

Updated soc file in Zephyr to disable Cracen RAMs
on system off.

2024-08-29 10:33 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/a415e2d702d5192ffdf7ddf67fa73f8fab70a277 | https://github.com/nrfconnect/sdk-zephyr/pull/1983 | [nrfconnect/sdk-zephyr#1983/files](https://github.com/nrfconnect/sdk-zephyr/pull/1983/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-08-29 10:36 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [e40d60e953114223b94d1e78e8c4550bcc4cf3fd](https://github.com/nrfconnect/sdk-nrf/pull/17075/commits/e40d60e953114223b94d1e78e8c4550bcc4cf3fd)
zephyr: PR head: [dd4a1e820291c994a54366b92335119b8338e2ad](https://github.com/nrfconnect/sdk-zephyr/pull/1983/commits/dd4a1e820291c994a54366b92335119b8338e2ad)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [e40d60e953114223b94d1e78e8c4550bcc4cf3fd](https://github.com/nrfconnect/sdk-nrf/pull/17075/commits/e40d60e953114223b94d1e78e8c4550bcc4cf3fd)
> merge base: [32b91a8fe62d6c2c86d076344c03cbb79f5e91b2](https://github.com/nrfconnect/sdk-nrf/commit/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2)
> target head (main): [32b91a8fe62d6c2c86d076344c03cbb79f5e91b2](https://github.com/nrfconnect/sdk-nrf/commit/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2..e40d60e953114223b94d1e78e8c4550bcc4cf3fd)

zephyr:
> PR head: [dd4a1e820291c994a54366b92335119b8338e2ad](https://github.com/nrfconnect/sdk-zephyr/pull/1983/commits/dd4a1e820291c994a54366b92335119b8338e2ad)
> merge base: [a415e2d702d5192ffdf7ddf67fa73f8fab70a277](https://github.com/nrfconnect/sdk-zephyr/commit/a415e2d702d5192ffdf7ddf67fa73f8fab70a277)
> target head (main): [e7415e4e3943f5ccbbffc63be9c3e31fbb690766](https://github.com/nrfconnect/sdk-zephyr/commit/e7415e4e3943f5ccbbffc63be9c3e31fbb690766)
> [Diff](https://github.com/nrfconnect/sdk-zephyr/compare/a415e2d702d5192ffdf7ddf67fa73f8fab70a277..dd4a1e820291c994a54366b92335119b8338e2ad)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
west.yml
zephyr
│  ├── boards
│  │  ├── nordic
│  │  │  ├── thingy53
│  │  │  │  │ Kconfig.defconfig
│  ├── soc
│  │  ├── nordic
│  │  │  ├── nrf54l
│  │  │  │  │ soc.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-sdk-audio
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nfc
   - :orange_circle: test-fw-nrfconnect-nrf-iot_cloud
   - :orange_circle: test-fw-nrfconnect-rs
   - :orange_circle: test-fw-nrfconnect-fem
   - :orange_circle: test-fw-nrfconnect-thread
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - latest/ble/nrf/test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-dfu
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-29 11:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17075
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-03 08:29 UTC, tomi-font requested changes
The commit title is incorrect?

2024-09-04 08:53 UTC, Vge0rge commented
> The commit title is incorrect?

You are right, I updated it now.

2024-09-04 08:55 UTC, tomi-font approved these changes

2024-09-06 07:14 UTC, SeppoTakalo approved these changes

2024-12-03 20:20 UTC, closed without merging