bootloader: bl_validation: Switch to using LOG_* for output
nrfconnect/sdk-nrf pull request #17079
Opened 2024-08-29 11:55 UTC by nordicjm

Switches to use the logging subsystem for log output instead of using a custom function which does not work and outputs nothing irrespective of Kconfig settings

2024-08-29 12:20 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
sdk-nrf: PR head: [40b59f68e6fbd55fb23fa68e5c62ac955a5706e7](https://github.com/nrfconnect/sdk-nrf/pull/17079/commits/40b59f68e6fbd55fb23fa68e5c62ac955a5706e7)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [40b59f68e6fbd55fb23fa68e5c62ac955a5706e7](https://github.com/nrfconnect/sdk-nrf/pull/17079/commits/40b59f68e6fbd55fb23fa68e5c62ac955a5706e7)
> merge base: [32b91a8fe62d6c2c86d076344c03cbb79f5e91b2](https://github.com/nrfconnect/sdk-nrf/commit/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2)
> target head (main): [32b91a8fe62d6c2c86d076344c03cbb79f5e91b2](https://github.com/nrfconnect/sdk-nrf/commit/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2)> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/32b91a8fe62d6c2c86d076344c03cbb79f5e91b2..40b59f68e6fbd55fb23fa68e5c62ac955a5706e7)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
subsys
│  ├── bootloader
│  │  ├── Kconfig
│  │  ├── bl_validation
│  │  │  │ bl_validation.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-mcuboot

<details><summary>Disable integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-thread
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-pmic-samples
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-08-29 12:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17079
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-03 07:25 UTC, greg-fer commented
Bootloader is @annwoj 's domain, so removing myself from review and adding Anna.

2024-09-03 08:55 UTC, bjda approved these changes
thingy91x board change looks good

2024-09-03 10:28 UTC, MarkusLassila approved these changes
SLM

2024-09-03 10:31 UTC, nordicjm commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +If logs are wanted over RTT instead of UART then the following Kconfigs can be used to allow this: ``CONFIG_USE_SEGGER_RTT=y``, ``CONFIG_RTT_CONSOLE=y``, ``CONFIG_UART_CONSOLE=n`` and ``CONFIG_SERIAL
Have not applied this because not deprecated, dropped, deprecated means it's still there with a warning, but this gets rid of it entirely

2024-09-03 12:00 UTC, annwoj commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +If logs are wanted over RTT instead of UART then the following Kconfigs can be used to allow this: ``CONFIG_USE_SEGGER_RTT=y``, ``CONFIG_RTT_CONSOLE=y``, ``CONFIG_UART_CONSOLE=n`` and ``CONFIG_SERIAL
thanks for clarifying - updated my suggestion, please check

2024-09-04 06:45 UTC, nordicjm commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +If logs are wanted over RTT instead of UART then the following Kconfigs can be used to allow this: ``CONFIG_USE_SEGGER_RTT=y``, ``CONFIG_RTT_CONSOLE=y``, ``CONFIG_UART_CONSOLE=n`` and ``CONFIG_SERIAL
Fixed

2024-09-04 06:45 UTC, nordicjm commented on doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
> +Nordic Secure Immutable Bootloader (NSIB/b0/b0n)
Fixed

2024-09-04 07:01 UTC, kapi-no requested changes
Approving the nRF Desktop and the Fast Pair. Clean-up needed in the Apple Find My repository (this Kconfig was unnecessarily used in the MCUboot configurations)

2024-09-04 07:10 UTC, nordicjm commented
> Approving the nRF Desktop and the Fast Pair. Clean-up needed in the Apple Find My repository (this Kconfig was unnecessarily used in the MCUboot configurations)

Added

2024-09-04 07:10 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| find-my | https://github.com/nrfconnect/sdk-find-my/commit/ae051fe3f9ed9a905626461f5503ecbf6ba870fe (main) | https://github.com/nrfconnect/sdk-find-my/pull/219 | [nrfconnect/sdk-find-my#219/files](https://github.com/nrfconnect/sdk-find-my/pull/219/files) |
| mcuboot | [nrfconnect/sdk-mcuboot@v2.1.0-ncs1](https://github.com/nrfconnect/sdk-mcuboot/releases/tag/v2.1.0-ncs1) | https://github.com/nrfconnect/sdk-mcuboot/pull/332 | [nrfconnect/sdk-mcuboot#332/files](https://github.com/nrfconnect/sdk-mcuboot/pull/332/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-04 07:15 UTC, kapi-no approved these changes

2024-09-04 08:20 UTC, annwoj approved these changes

2024-09-05 18:57 UTC, de-nordic commented on subsys/bootloader/bl_validation/bl_validation.c
> +		LOG_INF("Hash: 0x%02x...%02x", key_data[0],
Shouldn't format string be hhx ?

2024-09-10 08:04 UTC, nordicjm commented on subsys/bootloader/bl_validation/bl_validation.c
> +		LOG_INF("Hash: 0x%02x...%02x", key_data[0],
02x is 2 character hex

2024-09-11 09:45 UTC, merged