lib: sms: Use AT+CMMS with concatenated SMS
nrfconnect/sdk-nrf pull request #17182
Opened 2024-09-04 13:49 UTC by trantanen

We have not used AT+CMMS before concatenated SMS parts and everything has worked fine.
Now we will send AT+CMMS=1 before each part except the last one. We'll send AT+CMMS=0 before the last part.

Jira: TNSW-62165

2024-09-04 13:51 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [23cbed79a948f667674bea96fdcd5a247d7f8725](https://github.com/nrfconnect/sdk-nrf/pull/17182/commits/23cbed79a948f667674bea96fdcd5a247d7f8725)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [23cbed79a948f667674bea96fdcd5a247d7f8725](https://github.com/nrfconnect/sdk-nrf/pull/17182/commits/23cbed79a948f667674bea96fdcd5a247d7f8725)
> merge base: [344bea8e167a3ad21907f0065684cd4f83297223](https://github.com/nrfconnect/sdk-nrf/commit/344bea8e167a3ad21907f0065684cd4f83297223)
> target head (main): [2d1690d77ed7354d6d7b4670ada62a472b5078cf](https://github.com/nrfconnect/sdk-nrf/commit/2d1690d77ed7354d6d7b4670ada62a472b5078cf)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/344bea8e167a3ad21907f0065684cd4f83297223..23cbed79a948f667674bea96fdcd5a247d7f8725)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
lib
│  ├── sms
│  │  │ sms_submit.c
tests
│  ├── lib
│  │  ├── sms
│  │  │  ├── src
│  │  │  │  │ sms_test.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - :orange_circle: test-fw-nrfconnect-nrf-iot_samples
   - :orange_circle: test-fw-nrfconnect-nrf-iot_lwm2m
   - :orange_circle: test-fw-nrfconnect-nrf-iot_mosh

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-04 14:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17182
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-05 01:25 UTC, junqingzou approved these changes

2024-09-05 10:26 UTC, tokangas approved these changes

2024-09-05 11:03 UTC, wiba-nordic requested changes

2024-09-05 11:03 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Added use of ``AT+CMMS`` for sending concatenated SMS message.
```suggestion
  * Added the use of the ``AT+CMMS`` AT command for sending concatenated SMS message.
```

2024-09-05 11:06 UTC, wiba-nordic approved these changes

2024-09-06 07:06 UTC, merged