samples: wifi: thread_coex: Readme update
nrfconnect/sdk-nrf pull request #17183
Opened 2024-09-04 13:57 UTC by muraliThokala

Minor edits to suit the latest documentation style.

2024-09-04 13:58 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-09-04 14:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17183
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-05 10:00 UTC, richabp requested changes

2024-09-05 10:25 UTC, muraliThokala commented on samples/wifi/thread_coex/README.rst
> +* Wi-Fi throughput test: Set the :kconfig:option:`CONFIG_NET_CONFIG_PEER_IPV4_ADDR` Kconfig option appropriately as per the Wi-Fi interface IP address of the test PC on which **iperf** is run.
1. Wi-Fi connection is done before running the Wi-Fi throughput test. So, these two are in this order in the doc. 
2. Configuring the credentials is part of the Wi-Fi connection and so mentioned immediately after the Wi-Fi connection, Alternative way of configuring the credentials (using menuconfig)  is mentioned as part of this.
So, connection, configuring credentials and running throughput are in the right sequence.

2024-09-05 10:27 UTC, richabp commented on samples/wifi/thread_coex/README.rst
> +* Wi-Fi throughput test: Set the :kconfig:option:`CONFIG_NET_CONFIG_PEER_IPV4_ADDR` Kconfig option appropriately as per the Wi-Fi interface IP address of the test PC on which **iperf** is run.
Ok, thanks!

2024-09-05 12:55 UTC, richabp approved these changes

2024-09-17 06:02 UTC, srkanordic approved these changes

2024-09-17 07:32 UTC, peknis commented
To improve the readability of the table under the test setup image, I'd have an empty line between the two cases. (line 58).

2024-09-17 07:33 UTC, peknis requested changes

2024-09-17 07:33 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +	   $ iperf -s -i 1 -u
```suggestion
.. code-block:: console

   $ iperf -s -i 1 -u
```

2024-09-17 07:33 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +When the sample runs Wi-Fi UDP throughput in client mode, a peer device (test PC) runs UDP throughput in server mode using the following command:
Does the user need to run that command or does it just happen?
If the user needs to run it, then rather:
"... runs UDP throughput in server mode.
Use the following command:"

2024-09-17 07:33 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +Tables given below provide the procedure to run Wi-Fi only, Bluetooth LE-only, and combined throughput for different Thread roles.
```suggestion
The following tables provide the procedure to run Wi-Fi only, Bluetooth LE-only, and combined throughput for different Thread roles.
```

2024-09-17 07:33 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +Program the nRF7002 DK by completing the following steps:
```suggestion
Complete the following steps to program the nRF7002 DK:
```

2024-09-17 07:33 UTC, peknis commented on samples/wifi/thread_coex/README.rst
> +	  In this example, ``1050779496`` is the device ID of the first nRF7002 DK and ``1050759502`` is the device ID of the second nRF7002 DK.
```suggestion
	  In this example, ``1050779496`` is the device ID of the first nRF7002 DK and ``1050759502`` is the device ID of the other one.
```

2024-09-18 05:45 UTC, peknis approved these changes

2024-09-18 07:54 UTC, richabp requested changes

2024-09-18 07:54 UTC, richabp commented on samples/wifi/thread_coex/README.rst
> +When the sample is executed, the Wi-Fi UDP throughput operates with the Device Under Test (DUT) in client mode. To run the UDP throughput in server mode on the peer device (test PC), use the followin
```suggestion
When the sample is executed, the Wi-Fi UDP throughput operates with the Device Under Test (DUT) in client mode.
To run the UDP throughput in server mode on the peer device (test PC), use the following command.
```

2024-09-18 09:36 UTC, richabp approved these changes

2024-09-18 09:53 UTC, merged