54 series extend samples
nrfconnect/sdk-nrf pull request #17212
Opened 2024-09-05 17:32 UTC by krish2718

2024-09-05 17:43 UTC, bama-nordic approved these changes

2024-09-05 18:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17212
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-06 06:31 UTC, sachinthegreen approved these changes

2024-09-06 07:59 UTC, katgiadla requested changes

2024-09-06 07:59 UTC, katgiadla commented on samples/wifi/scan/sample.yaml
> +  sample.nrf7002eb.nrf54l15pdk.shell:
New test scenarios should be designed only for `nrf54l15dk/nrf54l15/cpuapp`.

2024-09-06 07:59 UTC, katgiadla commented on samples/wifi/sta/sample.yaml
> +  sample.nrf7002eb.nrf54l15pdk.shell:
New test scenarios should be designed only for `nrf54l15dk/nrf54l15/cpuapp`.

Platform `nrf54l15pdk/nrf54l15/cpuapp` will be deprecated soon.

2024-09-06 10:43 UTC, katgiadla approved these changes

2024-09-06 20:20 UTC, mjd90 approved these changes
LGTM

2024-09-13 10:21 UTC, merged