samples: bluetooth: peripehral_uart: All to run complete sample on nRF54H20 radio core
nrfconnect/sdk-nrf pull request #17224
Opened 2024-09-07 15:11 UTC by ppryga-nordic

The PR brings three commits that:
- add new snippet `nrf54h-dk-buttons-leds-on-radio` that adds required DTS configuration to use the DK buttons and LEDs lib on the radio core
- add new snippet `nrf54h-settings-storage-on-radio` that modifies DTS regarding the memory map to add and enable settings storage for the radio core.
- adds entry in the sample documentation how to build it in required configuration to run complete sample on the radio core.

All changes are related with nRF54H20 SoC only.

2024-09-07 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=17224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=17224) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ppryga-nordic<br/>:x: Piotr Pryga<br/><hr/>**Piotr Pryga** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=17224) it.</sub>

2024-09-07 15:12 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [d32d231d24a3886428c2df078e8e0bcc83e1230f](https://github.com/nrfconnect/sdk-nrf/pull/17224/commits/d32d231d24a3886428c2df078e8e0bcc83e1230f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [d32d231d24a3886428c2df078e8e0bcc83e1230f](https://github.com/nrfconnect/sdk-nrf/pull/17224/commits/d32d231d24a3886428c2df078e8e0bcc83e1230f)
> merge base: [93170fa066ed12774866e358d57ec1dab1812fcd](https://github.com/nrfconnect/sdk-nrf/commit/93170fa066ed12774866e358d57ec1dab1812fcd)
> target head (main): [93170fa066ed12774866e358d57ec1dab1812fcd](https://github.com/nrfconnect/sdk-nrf/commit/93170fa066ed12774866e358d57ec1dab1812fcd)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/93170fa066ed12774866e358d57ec1dab1812fcd..d32d231d24a3886428c2df078e8e0bcc83e1230f)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (10)</summary>

```
samples
│  ├── bluetooth
│  │  ├── peripheral_uart
│  │  │  │ README.rst
snippets
│  ├── nrf54h-dk-buttons-leds-on-radio
│  │  ├── README.rst
│  │  ├── boards
│  │  │  ├── nrf54h20dk_nrf54h20_cpurad.conf
│  │  │  │ nrf54h20dk_nrf54h20_cpurad.overlay
│  │  │ snippet.yml
│  ├── nrf54h-settings-storage-on-radio
│  │  ├── README.rst
│  │  ├── boards
│  │  │  ├── nrf54h20dk_nrf54h20-mem-map-move.dtsi
│  │  │  ├── nrf54h20dk_nrf54h20_cpuapp.overlay
│  │  │  │ nrf54h20dk_nrf54h20_cpurad.overlay
│  │  │ snippet.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-07 16:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17224
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-09 06:46 UTC, nordicjm requested changes

2024-09-09 06:46 UTC, nordicjm commented on samples/bluetooth/peripheral_uart/README.rst
> +   west build -b nrf54h20dk/nrf54h20/cpurad -p -- -DSNIPPET="nrf54h-dk-buttons-leds-on-radio;nrf54h-settings-storage-on-radio"wes
"wes?

2024-09-09 08:01 UTC, tomchy approved these changes

2024-09-09 09:06 UTC, tejlmand requested changes
Are we going to create a snippet for any minor feature adjustment of Kconfig and devicetree overlays for the nRF54 ?

This looks like a mis-use of the snippet feature.

If we just want to allow a single sample to show the use of leds on the nRF54 radio core, like blinky or peripheral_uart, then it's much better to just have board specific conf and overlay files under `<sample>/board/<board_target>.[conf | overlay]`.

If we want a more generic solution, where app core is mainly ignored, and radio core can be used for anything, then a more "re-assign all nodes" to radio core is probably a better choice.

That would be re-assigning leds, buttons, memory, etc.
If a downstream user then needs to reassign only a portion, then they can already see how this is done and copy just the relevant parts (fir example leds) into their own project.
Such a highlevel, re-assign all solution could be done as a board variant.

Has such approach been considered ?

2024-09-09 14:18 UTC, FrancescoSer requested changes

2024-09-09 14:18 UTC, FrancescoSer commented on samples/bluetooth/peripheral_uart/README.rst
> +The sample can also be build in a configuration that allows to run it on nRf54H20 SoC radio core only.
```suggestion
The sample can also be build in a configuration that allows to run it on the nRF54H20 SoC radio core only.
```

2024-09-09 14:18 UTC, FrancescoSer commented on samples/bluetooth/peripheral_uart/README.rst
> +To build the sample in such configuration use the following command:
```suggestion
To build the sample with this configuration, use the following command:
```

2024-09-11 05:33 UTC, ppryga-nordic commented on samples/bluetooth/peripheral_uart/README.rst
> +   west build -b nrf54h20dk/nrf54h20/cpurad -p -- -DSNIPPET="nrf54h-dk-buttons-leds-on-radio;nrf54h-settings-storage-on-radio"wes
Thanks, that was leftover.

2024-09-11 05:34 UTC, ppryga-nordic commented on CODEOWNERS
> +/snippets/nrf54h-settings-storage-on-radio/ @ppryga-nordic
That commit was dropped

2024-09-11 05:45 UTC, ppryga-nordic commented
The PR was discussed internally and there was take a decision to drop use of SNIPPET. The right approach for generic solution would be to create a board variant. That can be done in future. As of now the configuration required for running the `peripehral_uart` sample was added as `peripehral_uart/board` overlays. 

For other readers or future reference, SNIPPETs are meant to provide a common set of changes to configuration of an application. These changes are meant to be generic for multiple boards/SOCs. Use of SNIPPETs for single board/SOC is a misuse.

@FrancescoSer I'm not 100% if it is better to give full command how to build the sample for the nRF54H20 radio core or state it in a bit different way. I think there should be an information the sample can be used in such configuration, because that is an exception.

2024-09-11 07:06 UTC, nordicjm approved these changes

2024-09-13 08:43 UTC, FrancescoSer approved these changes
Approved but please implement the following change

2024-09-13 08:43 UTC, FrancescoSer commented on samples/bluetooth/peripheral_uart/README.rst
> +The sample can also be build in a configuration that allows to run it on the nRF54H20 SoC radio core only.
```suggestion
The sample can also be built in a configuration that allows it to run on the nRF54H20 SoC radio core only. 
```

2024-09-13 08:45 UTC, ppryga-nordic commented on samples/bluetooth/peripheral_uart/README.rst
> +The sample can also be build in a configuration that allows to run it on the nRF54H20 SoC radio core only.
Done

2024-09-13 19:22 UTC, tejlmand approved these changes

2024-09-13 19:24 UTC, merged