CI: Optimize packaging in workflow
nrfconnect/sdk-nrf pull request #17275
Opened 2024-09-11 11:29 UTC by jaci-nordic

Add garbage collector and compress package before sending to Artifactory

2024-09-13 11:05 UTC, thst-nordic commented on .github/workflows/src-mirror.yml
> +          tar cvfz src.tar.gz -C ./workspace/ .
can we switch to 7z so it can be unzipped on all platforms?

2024-09-13 11:06 UTC, thst-nordic commented on .github/workflows/src-mirror.yml
> +          west-update-args: '--narrow -o=--depth=1 --group-filter=+babblesim,+sidewalk,+optional'
+optional is default so it can be dropped.

2024-09-18 11:23 UTC, thst-nordic requested changes

2024-09-18 11:23 UTC, thst-nordic commented on .github/workflows/src-mirror.yml
> +          west-update-args: '--narrow -o=--depth=1 --group-filter=+babblesim,+sidewalk,+optional'
I think we should remove `--narrow -o=--depth=1` 

users might need other refs and history.

2024-10-03 09:24 UTC, DatGizmo approved these changes

2024-10-04 07:10 UTC, merged