samples: bluetooth: fix peripheral hr coded
nrfconnect/sdk-nrf pull request #17283
Opened 2024-09-11 13:51 UTC by henrla

Pass default params to bt_le_ext_adv_start
instead of NULL. The NULL was deferenced and used
to set parameters for starting extended advertising in the sample.

2024-09-11 13:54 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [8ef5229261576a6197dc226958bab08add621486](https://github.com/nrfconnect/sdk-nrf/pull/17283/commits/8ef5229261576a6197dc226958bab08add621486)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [8ef5229261576a6197dc226958bab08add621486](https://github.com/nrfconnect/sdk-nrf/pull/17283/commits/8ef5229261576a6197dc226958bab08add621486)
> merge base: [79c0c3c3d2239926f46296ea21f73b03fcb1e54f](https://github.com/nrfconnect/sdk-nrf/commit/79c0c3c3d2239926f46296ea21f73b03fcb1e54f)
> target head (main): [25e225e2d0a20ad6fedc3baf902945c2493f4459](https://github.com/nrfconnect/sdk-nrf/commit/25e225e2d0a20ad6fedc3baf902945c2493f4459)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/79c0c3c3d2239926f46296ea21f73b03fcb1e54f..8ef5229261576a6197dc226958bab08add621486)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
samples
│  ├── bluetooth
│  │  ├── peripheral_hr_coded
│  │  │  ├── src
│  │  │  │  │ main.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-19 10:31 UTC, jostn approved these changes

2024-09-19 11:26 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17283
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-19 12:17 UTC, wiba-nordic requested changes

2024-09-19 12:17 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +   * Fixed an issue where HCI LE Set Extended Advertising Enable was called with a NULL pointer.
```suggestion
   * Fixed an issue where the HCI LE Set Extended Advertising Enable command was called with a NULL pointer.
```

2024-09-19 12:21 UTC, wiba-nordic approved these changes

2024-09-19 14:45 UTC, merged