lib: nrf_fuel_gauge: Update nrf fuel gauge
nrfconnect/sdk-nrf pull request #17292
Opened 2024-09-12 07:38 UTC by nordic-auko

Update nrfxlib nrf fuel gauge to v0.11.1,
and adjust sample and test accordingly.

2024-09-12 07:39 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a21499e8ac4bbf00e41879ade74dc95a26f7edb9 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1469 | [nrfconnect/sdk-nrfxlib#1469/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1469/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-12 07:42 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [10353739fbab9d1d60a9fa9a58b3206ee35691d7](https://github.com/nrfconnect/sdk-nrf/pull/17292/commits/10353739fbab9d1d60a9fa9a58b3206ee35691d7)
nrfxlib: PR head: [b90ef6e963dd344b2b2b1ad7424a10ce68e72f7c](https://github.com/nrfconnect/sdk-nrfxlib/pull/1469/commits/b90ef6e963dd344b2b2b1ad7424a10ce68e72f7c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [10353739fbab9d1d60a9fa9a58b3206ee35691d7](https://github.com/nrfconnect/sdk-nrf/pull/17292/commits/10353739fbab9d1d60a9fa9a58b3206ee35691d7)
> merge base: [6b9150387f77d7b71c460c72351b828b70f13a83](https://github.com/nrfconnect/sdk-nrf/commit/6b9150387f77d7b71c460c72351b828b70f13a83)
> target head (main): [25e225e2d0a20ad6fedc3baf902945c2493f4459](https://github.com/nrfconnect/sdk-nrf/commit/25e225e2d0a20ad6fedc3baf902945c2493f4459)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/6b9150387f77d7b71c460c72351b828b70f13a83..10353739fbab9d1d60a9fa9a58b3206ee35691d7)

nrfxlib:
> PR head: [b90ef6e963dd344b2b2b1ad7424a10ce68e72f7c](https://github.com/nrfconnect/sdk-nrfxlib/pull/1469/commits/b90ef6e963dd344b2b2b1ad7424a10ce68e72f7c)
> merge base: [a21499e8ac4bbf00e41879ade74dc95a26f7edb9](https://github.com/nrfconnect/sdk-nrfxlib/commit/a21499e8ac4bbf00e41879ade74dc95a26f7edb9)
> target head (main): [56a4bd3100123a8dd2049968d54cfc4014ca8eb8](https://github.com/nrfconnect/sdk-nrfxlib/commit/56a4bd3100123a8dd2049968d54cfc4014ca8eb8)
> [Diff](https://github.com/nrfconnect/sdk-nrfxlib/compare/a21499e8ac4bbf00e41879ade74dc95a26f7edb9..b90ef6e963dd344b2b2b1ad7424a10ce68e72f7c)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (20)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
nrfxlib
│  ├── nrf_fuel_gauge
│  │  ├── CHANGELOG.rst
│  │  ├── include
│  │  │  │ nrf_fuel_gauge.h
│  │  ├── lib
│  │  │  ├── cortex-m3
│  │  │  │  ├── soft-float
│  │  │  │  │  │ libnrf_fuel_gauge.a
│  │  │  ├── cortex-m33
│  │  │  │  ├── hard-float
│  │  │  │  │  │ libnrf_fuel_gauge.a
│  │  │  │  ├── soft-float
│  │  │  │  │  │ libnrf_fuel_gauge.a
│  │  │  ├── cortex-m4
│  │  │  │  ├── hard-float
│  │  │  │  │  │ libnrf_fuel_gauge.a
│  │  │  │  ├── soft-float
│  │  │  │  │  │ libnrf_fuel_gauge.a
│  ├── nrf_rpc
│  │  ├── CHANGELOG.rst
│  │  │ nrf_rpc_cbor.c
samples
│  ├── pmic
│  │  ├── native
│  │  │  ├── npm1300_fuel_gauge
│  │  │  │  ├── README.rst
│  │  │  │  ├── nrf52840dk_nrf52840.overlay
│  │  │  │  ├── nrf52dk_nrf52832.overlay
│  │  │  │  ├── nrf5340dk_nrf5340_cpuapp.overlay
│  │  │  │  ├── nrf9160dk_nrf9160.overlay
│  │  │  │  ├── src
│  │  │  │  │  ├── fuel_gauge.c
│  │  │  │  │  ├── fuel_gauge.h
│  │  │  │  │  │ main.c
tests
│  ├── lib
│  │  ├── nrf_fuel_gauge
│  │  │  ├── src
│  │  │  │  │ nrf_fuel_gauge_test.c
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-nrf-iot_cloud
   - :orange_circle: test-fw-nrfconnect-rpc
   - :orange_circle: test-sdk-dfu

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-12 14:45 UTC, WalkingTalkingPotato commented on samples/pmic/native/npm1300_fuel_gauge/README.rst
> +   * On the **P18** pin header, disconnect **VDDIO** jumper.
I think it's better to add "Remove all existing connections" at the start of this list, the same way as we have in One Button sample: https://github.com/nrfconnect/sdk-nrf/blob/main/samples/pmic/native/npm1300_one_button/README.rst?plain=1#L38

2024-09-13 12:41 UTC, nordic-auko commented on samples/pmic/native/npm1300_fuel_gauge/src/main.c
> +	vbus_connected = (val.val1 != 0) || (val.val2 != 0);
Yes, I agree. But the driver doesn't this currently. It reads the vbus status register, but does not expose it (https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/sensor/nordic/npm1300_charger/npm1300_charger.c#L301). I plan to set up an upstream PR to expose it.

2024-09-13 12:43 UTC, nordic-auko commented on samples/pmic/native/npm1300_fuel_gauge/README.rst
> +   * On the **P18** pin header, disconnect **VDDIO** jumper.
I'm fine with that

2024-09-17 11:34 UTC, WalkingTalkingPotato approved these changes

2024-09-20 09:57 UTC, peknis requested changes

2024-09-20 09:57 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* :ref:`npm1300_fuel_gauge` sample:
```suggestion

* :ref:`npm1300_fuel_gauge` sample:
```

2024-09-20 09:57 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Updated to accommodate API changes in nRF Fuel Gauge library v0.11.1.
```suggestion
  
  * Updated to accommodate API changes in nRF Fuel Gauge library v0.11.1.
```

2024-09-20 10:32 UTC, peknis approved these changes

2024-09-24 07:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17292
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-24 08:37 UTC, merged