samples: wifi: Fix duplicate twister names
nrfconnect/sdk-nrf pull request #17319
Opened 2024-09-13 14:47 UTC by krish2718

Fix duplicates name by using sample name prefix.

Note: For some reason CI didn't catch this in the original PR.

2024-09-13 15:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17319
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-14 12:49 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [6411fdcfa2e80ceff3e31406dc2738b4c74d1291](https://github.com/nrfconnect/sdk-nrf/pull/17319/commits/6411fdcfa2e80ceff3e31406dc2738b4c74d1291)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [6411fdcfa2e80ceff3e31406dc2738b4c74d1291](https://github.com/nrfconnect/sdk-nrf/pull/17319/commits/6411fdcfa2e80ceff3e31406dc2738b4c74d1291)
> merge base: [5e0c12fb6443f209fdcf28ca7b0b763b6bfff362](https://github.com/nrfconnect/sdk-nrf/commit/5e0c12fb6443f209fdcf28ca7b0b763b6bfff362)
> target head (main): [48cf0785e650f4b036e88e98f166ca06d2868edf](https://github.com/nrfconnect/sdk-nrf/commit/48cf0785e650f4b036e88e98f166ca06d2868edf)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/5e0c12fb6443f209fdcf28ca7b0b763b6bfff362..6411fdcfa2e80ceff3e31406dc2738b4c74d1291)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
samples
│  ├── wifi
│  │  ├── scan
│  │  │  │ sample.yaml
│  │  ├── sta
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-sdk-wifi

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-16 06:30 UTC, jangalda-nsc approved these changes

2024-09-16 11:55 UTC, thst-nordic commented on samples/wifi/scan/sample.yaml
> +  sample.scan.nrf7002eb.nrf54l15dk.shell:
need `.wifi.` in there also?

2024-09-16 11:59 UTC, thst-nordic requested changes
if you are going to be updating test names, you might as well add `.wifi.` to all of them to align with others.

2024-09-17 04:42 UTC, muraliThokala approved these changes

2024-09-17 07:34 UTC, nordic-piks commented
@krish2718 Can you proceed with merging? main is red now.
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/main/3991/testReport/junit/nrf54h20dk_nrf54h20_cpuapp_sample.nrf54h20dk_nrf7002ek/shell/Build___Test_with_Twister___Twister_NRF_5_10___sample_nrf54h20dk_nrf7002ek_shell/
Will this be fixed by this PR?

2024-09-17 09:16 UTC, thst-nordic approved these changes

2024-09-17 09:22 UTC, merged