CODEOWNERS: Overhaul in order to enable required reviews
nrfconnect/sdk-nrf pull request #17327
Opened 2024-09-16 10:36 UTC by carlescufi

Replaces https://github.com/nrfconnect/sdk-nrf/pull/15698

In preparation for the enabling of the GitHub "Require reviews from Code Owners" branch protection setting, reorganize the Codeowners file so that Vestavind is aware of changes in the files it needs to oversee.

See also: https://nordicsemi.atlassian.net/wiki/spaces/SPG/pages/635604878/CODEOWNERS+file

2024-09-16 10:39 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [d9de2aad56925e9365a034dcf0c7dbd6c6caadb9](https://github.com/nrfconnect/sdk-nrf/pull/17327/commits/d9de2aad56925e9365a034dcf0c7dbd6c6caadb9)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [d9de2aad56925e9365a034dcf0c7dbd6c6caadb9](https://github.com/nrfconnect/sdk-nrf/pull/17327/commits/d9de2aad56925e9365a034dcf0c7dbd6c6caadb9)
> merge base: [0063d04074e9b8927262eee0fecf518b5d2dd7c6](https://github.com/nrfconnect/sdk-nrf/commit/0063d04074e9b8927262eee0fecf518b5d2dd7c6)
> target head (main): [f7134aace07ded41351de2347c4898213e2d3884](https://github.com/nrfconnect/sdk-nrf/commit/f7134aace07ded41351de2347c4898213e2d3884)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/0063d04074e9b8927262eee0fecf518b5d2dd7c6..d9de2aad56925e9365a034dcf0c7dbd6c6caadb9)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
CODEOWNERS
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-16 11:08 UTC, gmarull approved these changes

2024-09-16 11:24 UTC, nordicjm commented on CODEOWNERS
> +Kconfig*                                  @nrfconnect/ncs-co-build-system
Should be a CMakeLists.txt one too

2024-09-16 11:25 UTC, nordicjm commented on CODEOWNERS
>  /modules/cjson/                           @nrfconnect/ncs-cia @plskeggs @sigvartmh
`sigvartmh` below can be removed, should remove from all entries in this file

2024-09-16 11:46 UTC, nordicjm commented on CODEOWNERS
> +Kconfig*                                  @nrfconnect/ncs-co-build-system
Also a *.cmake too

2024-09-16 12:14 UTC, nordicjm commented on CODEOWNERS
> +Kconfig*                                  @nrfconnect/ncs-co-build-system
need a *.cmake one too please

2024-09-16 12:26 UTC, bjarki-andreasen approved these changes

2024-09-16 12:38 UTC, nordicjm approved these changes

2024-09-16 18:21 UTC, carlescufi commented on CODEOWNERS
>  /lib/edge_impulse/                        @pdunaj
@pdunaj can you please let me know which teams to create?

2024-09-16 18:21 UTC, carlescufi commented on CODEOWNERS
>  /lib/fprotect/                            @hakonfam
@hakonfam? @nvlsianpu?

2024-09-16 18:21 UTC, carlescufi commented on CODEOWNERS
> +/samples/openthread/                      @nrfconnect/ncs-co-networking @edmont @canisLupus1313 @maciejbaczmanski
@edmont @canisLupus1313 @maciejbaczmanski team name?

2024-09-16 18:22 UTC, carlescufi commented on CODEOWNERS
> +/subsys/dfu/                              @hakonfam
@hakonfam?

2024-09-16 18:22 UTC, carlescufi commented on CODEOWNERS
> +/subsys/bootloader/                       @hakonfam
@hakonfam @nvlsianpu?

2024-09-16 18:22 UTC, carlescufi commented on CODEOWNERS
> +/subsys/mgmt/                             @hakonfam
@hakonfam @nvlsianpu?

2024-09-16 18:40 UTC, plskeggs approved these changes
LGTM for nrfcloud

2024-09-17 07:02 UTC, ankuns commented on CODEOWNERS
> +/subsys/ieee802154/                       @nrfconnect/ncs-co-networking @ankuns @piotrkoziar
`ncs-rs` would be okay, but I think such group/team name does not exist yet

2024-09-17 07:19 UTC, lemrey approved these changes

2024-09-17 07:35 UTC, hakonfam commented on CODEOWNERS
>  /lib/fprotect/                            @hakonfam
fprotect is pluto now

2024-09-17 07:35 UTC, hakonfam commented on CODEOWNERS
> +/subsys/dfu/                              @hakonfam
No, it should be pluto

2024-09-17 07:35 UTC, hakonfam commented on CODEOWNERS
> +/subsys/bootloader/                       @hakonfam
pluto

2024-09-17 07:47 UTC, carlescufi commented on CODEOWNERS
>  /include/sdfw/                            @anhmolt @hakonfam @jonathannilsen
ncs-aurora created

2024-09-17 07:47 UTC, hakonfam requested changes

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /include/sdfw/                            @anhmolt @hakonfam @jonathannilsen
ncs-aurora

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
> +/scripts/bootloader/                      @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
> +/subsys/mgmt/                             @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /subsys/sdfw_services/                    @anhmolt @hakonfam @jonathannilsen
ncs-aurora

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /tests/drivers/fprotect/                  @oyvindronningstad
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
> +/tests/subsys/dfu/                        @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
> +/tests/modules/mcuboot/external_flash/    @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
> +/tests/subsys/partition_manager/region/   @hakonfam
Same as 

`/tests/subsys/partition_manager/static_pm_file/ @nordicjm @tejlmand`

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /tests/subsys/sdfw_services/              @anhmolt @hakonfam @jonathannilsen
ncs-aurora

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /subsys/partition_manager/                @hakonfam
Not sure about this, but not me at least. 

Perhaps same as here? 

`/tests/subsys/partition_manager/static_pm_file/ @nordicjm @tejlmand`

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /subsys/pcd/                              @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /samples/sdfw/                            @hakonfam @jonathannilsen
ncs-aurora

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /samples/nrf5340/netboot/                 @hakonfam
pluto

2024-09-17 07:47 UTC, hakonfam commented on CODEOWNERS
>  /lib/flash_patch/                         @hakonfam
not sure, but not me. Perhaps the author @oyvindronningstad  ?

2024-09-17 07:47 UTC, carlescufi commented on CODEOWNERS
> +/subsys/ieee802154/                       @nrfconnect/ncs-co-networking @ankuns @piotrkoziar
ncs-radio-sw created

2024-09-17 07:52 UTC, hakonfam requested changes

2024-09-17 07:52 UTC, hakonfam commented on CODEOWNERS
>  /tests/drivers/flash_patch/               @oyvindronningstad
@nrfconnect/ncs-code-owners

2024-09-17 07:52 UTC, hakonfam commented on CODEOWNERS
>  /tests/drivers/fprotect/                  @oyvindronningstad
@nrfconnect/ncs-code-owners

2024-09-17 07:54 UTC, carlescufi commented on CODEOWNERS
> +/samples/openthread/                      @nrfconnect/ncs-co-networking @edmont @canisLupus1313 @maciejbaczmanski
ncs-thread created

2024-09-17 07:54 UTC, nordic-piks approved these changes

2024-09-17 09:14 UTC, thst-nordic approved these changes
The reason for this overhaul is to allow PR authors to merge small PR's faster.  

We should aim to replace as many individual accounts with teams to avoid delays due to absences.   It looks like good progress towards this already.

2024-09-17 09:38 UTC, hakonfam requested changes

2024-09-17 09:38 UTC, hakonfam commented on CODEOWNERS
> +/subsys/dfu/                              @hakonfam
This needs to be fixed

2024-09-17 09:38 UTC, hakonfam commented on CODEOWNERS
> +/subsys/pcd/                              @nfconnect/ncs-pluto
```suggestion
/subsys/pcd/                              @nrfconnect/ncs-pluto
```

2024-09-17 09:46 UTC, hakonfam approved these changes

2024-09-17 10:35 UTC, oyvindronningstad requested changes
`subsys/fw_info` and `tests/subsys/fw_info` should go to Pluto

2024-09-17 11:04 UTC, SeppoTakalo approved these changes

2024-09-17 11:20 UTC, ankuns approved these changes

2024-09-17 11:40 UTC, de-nordic approved these changes

2024-09-17 11:50 UTC, carlescufi commented
> `subsys/fw_info` and `tests/subsys/fw_info` should go to Pluto

Fixed

2024-09-17 11:59 UTC, oyvindronningstad approved these changes

2024-09-17 12:08 UTC, SeppoTakalo approved these changes

2024-09-17 12:55 UTC, jhn-nordic approved these changes

2024-09-17 12:59 UTC, shanthanordic approved these changes

2024-09-17 13:19 UTC, hubertmis approved these changes
Still, I would replace multiple @pdunaj with relevant teams. But I guess we can do that later.

2024-09-17 13:27 UTC, PerMac approved these changes

2024-09-17 13:30 UTC, nordic-segl approved these changes

2024-09-17 13:30 UTC, koffes approved these changes

2024-09-18 07:31 UTC, nordic-hani approved these changes

2024-09-18 09:54 UTC, nordicjm commented on CODEOWNERS
> +/snippets/                                @nrfconnect/ncs-co-boards
build system should be added here

2024-09-18 10:56 UTC, carlescufi commented on CODEOWNERS
> +/snippets/                                @nrfconnect/ncs-co-boards
done

2024-09-18 11:06 UTC, carlescufi commented
> Still, I would replace multiple @pdunaj with relevant teams. But I guess we can do that later.

Currently discussing it with him

2024-09-18 12:44 UTC, pdunaj commented
> > Still, I would replace multiple @pdunaj with relevant teams. But I guess we can do that later.
> 
> Currently discussing it with him

Pushed the change as a commit to this PR. Please squash if ok.

2024-09-18 15:28 UTC, hubertmis approved these changes

2024-09-19 05:24 UTC, maciejpietras commented on CODEOWNERS
>  /config/suit/                             @tomchy @ahasztag
```suggestion
/config/suit/                             @nrfconnect/ncs-charon
```

2024-09-19 09:37 UTC, SeppoTakalo commented
@carlescufi 

Final changes (hopefully) for my team.
I think these can be assigned to ncs-iot-oulu instead of individuals

* /samples/cellular/slm_shell/
* /subsys/net/lib/ftp_client/
* /lib/modem_jwt/  (maybe ncs-modem as well)
* /tests/lib/modem_jwt/

2024-09-19 10:15 UTC, carlescufi commented
> @carlescufi
> 
> Final changes (hopefully) for my team. I think these can be assigned to ncs-iot-oulu instead of individuals
> 
> * /samples/cellular/slm_shell/
> * /subsys/net/lib/ftp_client/
> * /lib/modem_jwt/  (maybe ncs-modem as well)
> * /tests/lib/modem_jwt/

Done

2024-09-19 11:26 UTC, maciejpietras approved these changes

2024-09-19 14:29 UTC, merged