sysbuild: Add compression options for MCUboot
nrfconnect/sdk-nrf pull request #17330
Opened 2024-09-16 12:36 UTC by nordicjm

manifest: Update sdk-mcuboot
    
    Pulls in changes for image decompression support

    sysbuild: Add compression options for MCUboot
    
    Adds an option which will enable compressed image support in
    MCUboot

    tests: nrf_compress: decompression: Add mcuboot_update test
    
    Adds a test which ensures compressed update image support works
    in MCUbot

2024-09-16 12:36 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| mcuboot | https://github.com/nrfconnect/sdk-mcuboot/commit/e66169aa8daf93eee0ff3729ecc2c343c7fade51 (main) | https://github.com/nrfconnect/sdk-mcuboot/pull/328 | [nrfconnect/sdk-mcuboot#328/files](https://github.com/nrfconnect/sdk-mcuboot/pull/328/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-16 12:50 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [a40bfb13e2090925872162ff0f023902f3d7e1c0](https://github.com/nrfconnect/sdk-nrf/pull/17330/commits/a40bfb13e2090925872162ff0f023902f3d7e1c0)
mcuboot: PR head: [7e8bab53c61404ade89ab99c82b81860911164b4](https://github.com/nrfconnect/sdk-mcuboot/pull/328/commits/7e8bab53c61404ade89ab99c82b81860911164b4)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [a40bfb13e2090925872162ff0f023902f3d7e1c0](https://github.com/nrfconnect/sdk-nrf/pull/17330/commits/a40bfb13e2090925872162ff0f023902f3d7e1c0)
> merge base: [0063d04074e9b8927262eee0fecf518b5d2dd7c6](https://github.com/nrfconnect/sdk-nrf/commit/0063d04074e9b8927262eee0fecf518b5d2dd7c6)
> target head (main): [3af6fccc09576d82ad05225195d817e340ced202](https://github.com/nrfconnect/sdk-nrf/commit/3af6fccc09576d82ad05225195d817e340ced202)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/0063d04074e9b8927262eee0fecf518b5d2dd7c6..a40bfb13e2090925872162ff0f023902f3d7e1c0)

mcuboot:
> PR head: [7e8bab53c61404ade89ab99c82b81860911164b4](https://github.com/nrfconnect/sdk-mcuboot/pull/328/commits/7e8bab53c61404ade89ab99c82b81860911164b4)
> merge base: [daf2946a0f07a14b57bd69d29ac4cdde6f810fb7](https://github.com/nrfconnect/sdk-mcuboot/commit/daf2946a0f07a14b57bd69d29ac4cdde6f810fb7)
> target head (main): [e66169aa8daf93eee0ff3729ecc2c343c7fade51](https://github.com/nrfconnect/sdk-mcuboot/commit/e66169aa8daf93eee0ff3729ecc2c343c7fade51)
> [Diff](https://github.com/nrfconnect/sdk-mcuboot/compare/daf2946a0f07a14b57bd69d29ac4cdde6f810fb7..7e8bab53c61404ade89ab99c82b81860911164b4)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (31)</summary>

```
bootloader
│  ├── mcuboot
│  │  ├── boot
│  │  │  ├── bootutil
│  │  │  │  ├── include
│  │  │  │  │  ├── bootutil
│  │  │  │  │  │  │ image.h
│  │  │  │  ├── src
│  │  │  │  │  ├── image_validate.c
│  │  │  │  │  ├── loader.c
│  │  │  │  │  │ swap_scratch.c
│  │  │  ├── zephyr
│  │  │  │  ├── CMakeLists.txt
│  │  │  │  ├── Kconfig
│  │  │  │  ├── decompression.c
│  │  │  │  ├── include
│  │  │  │  │  ├── compression
│  │  │  │  │  │  │ decompression.h
│  │  │  │  │  ├── mcuboot_config
│  │  │  │  │  │  │ mcuboot_config.h
│  │  ├── docs
│  │  │  ├── release-notes.d
│  │  │  │  ├── bootutil-image-verification.md
│  │  │  │  │ zephyr-compression.md
cmake
│  ├── sysbuild
│  │  │ image_signing.cmake
subsys
│  ├── bootloader
│  │  │ Kconfig
sysbuild
│  ├── CMakeLists.txt
│  │ Kconfig.mcuboot
tests
│  ├── subsys
│  │  ├── nrf_compress
│  │  │  ├── decompression
│  │  │  │  ├── mcuboot_update
│  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  ├── Kconfig
│  │  │  │  │  ├── compressed_app
│  │  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  │  ├── prj.conf
│  │  │  │  │  │  ├── src
│  │  │  │  │  │  │  │ main.c
│  │  │  │  │  ├── pm_static.yml
│  │  │  │  │  ├── prj.conf
│  │  │  │  │  ├── sample.yaml
│  │  │  │  │  ├── src
│  │  │  │  │  │  │ main.c
│  │  │  │  │  ├── sysbuild.cmake
│  │  │  │  │  ├── sysbuild.conf
│  │  │  │  │  ├── sysbuild
│  │  │  │  │  │  ├── mcuboot
│  │  │  │  │  │  │  ├── app.overlay
│  │  │  │  │  │  │  ├── boards
│  │  │  │  │  │  │  │  ├── nrf52840dk_nrf52840.conf
│  │  │  │  │  │  │  │  │ nrf54l15pdk_nrf54l15_cpuapp.conf
│  │  │  │  │  │  │  │ prj.conf
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-mcuboot
   - :orange_circle: test-sdk-dfu
   - :warning: test-fw-nrfconnect-fw-update

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-thread
   - test-low-level
   - test-sdk-audio
   - test-sdk-pmic-samples
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-16 12:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17330
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-25 06:42 UTC, nvlsianpu requested changes
just a few nits. Now I see why you need intel-hex output from imgtool.py

2024-09-25 06:42 UTC, nvlsianpu commented on samples/nrf_compress/mcuboot_update/src/main.c
not a main content of this sample in this file - expect main(). rename?

2024-09-25 06:42 UTC, nvlsianpu commented on samples/nrf_compress/mcuboot_update/src/main.c
> +
comment in the code for explaining what is it doing would be helpful once someone will look at this in few months.

2024-09-25 06:42 UTC, nvlsianpu commented on samples/nrf_compress/mcuboot_update/src/main.c
> +SYS_INIT(setup_something, APPLICATION, 0);
what does this SYS_INIT?

2024-09-25 06:42 UTC, nvlsianpu commented on tests/subsys/nrf_compress/decompression/mcuboot_update/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
> +CONFIG_NORDIC_QSPI_NOR=n
```suggestion
CONFIG_NORDIC_SPI_NOR=n
```
nRF54l15 hasn't QSPI.

2024-10-03 07:24 UTC, nvlsianpu approved these changes

2024-10-07 08:47 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***sample.matter.template.debug[nrf7002dk/nrf5340/cpuapp]***: ***High RAM usage: 394774[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-17330/20)*

2024-10-07 13:32 UTC, nordicjm commented
@carlescufi @tejlmand can you review please?

2024-10-08 08:55 UTC, tejlmand approved these changes

2024-10-08 10:08 UTC, de-nordic approved these changes

2024-10-08 10:44 UTC, carlescufi approved these changes

2024-10-09 07:03 UTC, merged