nrf54l15dk: patches needed for run MUBoot based dfu
nrfconnect/sdk-nrf pull request #17334
Opened 2024-09-16 13:30 UTC by nvlsianpu

This introduce changes missung in nRF54l15DK support,
mainly follow what have been done for the PDK.

These patches are needed for run MUBoot based dfu.

2024-09-16 13:31 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/78f654738d488e96e4d2107cec538347c3f0fce0 | https://github.com/nrfconnect/sdk-zephyr/pull/2026 | [nrfconnect/sdk-zephyr#2026/files](https://github.com/nrfconnect/sdk-zephyr/pull/2026/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-16 13:33 UTC, nordicjm approved these changes

2024-09-16 13:42 UTC, LuDuda reviewed
Thank you 🚀

2024-09-16 13:42 UTC, LuDuda commented on modules/trusted-firmware-m/Kconfig.tfm.pm
> +	default 0x6800 if TFM_PROFILE_TYPE_MINIMAL && BOOTLOADER_MCUBOOT && (SOC_NRF54L15_ENGA_CPUAPP || SOC_NRF54L15_ENGA_CPUAPP)
Did you mean:

```suggestion
	default 0x6800 if TFM_PROFILE_TYPE_MINIMAL && BOOTLOADER_MCUBOOT && (SOC_NRF54L15_ENGA_CPUAPP || SOC_NRF54L15_CPUAPP)
```

Same below?

2024-09-16 13:44 UTC, ArekBalysNordic commented on subsys/partition_manager/pm.yml.settings
> +#ifdef (CONFIG_SOC_NRF54L15_ENGA_CPUAPP || CONFIG_SOC_NRF54L15_CPUAPP)
```suggestion
#if defined(CONFIG_SOC_NRF54L15_ENGA_CPUAPP) || defined(CONFIG_SOC_NRF54L15_CPUAPP)
```

2024-09-16 13:44 UTC, ArekBalysNordic commented on subsys/partition_manager/pm.yml.settings
> +#ifdef (CONFIG_SOC_NRF54L15_ENGA_CPUAPP || CONFIG_SOC_NRF54L15_CPUAPP)
And the same below.

2024-09-16 15:26 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17334
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-17 14:46 UTC, gchwier approved these changes

2024-09-17 15:09 UTC, gchwier requested changes

2024-09-17 15:09 UTC, gchwier commented on subsys/partition_manager/pm.yml.settings
> +#if defined (CONFIG_SOC_NRF54L15_ENGA_CPUAPP || CONFIG_SOC_NRF54L15_CPUAPP)
failed in CI:
```
/jenkins_workspace/workspace/latest_sdk-nrf_PR-17334/nrf/subsys/partition_manager/pm.yml.settings:6:46: error: missing ')' after "defined"
    6 | #if defined (CONFIG_SOC_NRF54L15_ENGA_CPUAPP || CONFIG_SOC_NRF54L15_CPUAPP)
```

2024-09-17 16:47 UTC, gchwier approved these changes

2024-09-18 08:22 UTC, kapi-no commented
I think that the MCUboot configuration misses one entry to disable FPROTECT

```
CONFIG_FPROTECT=n
```

When building the Bluetooth Peripheral LBS sample with the following command:

```
west build -b nrf54l15dk/nrf54l15/cpuapp -- -DS
B_CONFIG_BOOTLOADER_MCUBOOT=y -DCONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y
```

I get the following output:

```
*** Booting MCUboot v2.1.0-dev-a41abbcbba5f ***
*** Using nRF Connect SDK v2.7.99-9b20dc0ee39b ***
*** Using Zephyr OS v3.6.99-9824af7b5a01 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0xc000
I: Jumping to the first image slot
E: Protect mcuboot flash failed, cancel startup.

```

2024-09-18 11:46 UTC, kapi-no commented
The last update fixed the issue with FPROTECT. The happy path for the swap mode works as expected:

```
*** Booting MCUboot v2.1.0-dev-5eba7ab4cbfc ***
*** Using nRF Connect SDK v2.7.99-8d9cb62c36df ***
*** Using Zephyr OS v3.6.99-25e278581141 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Secondary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Image index: 0, Swap type: none
I: Bootloader chainload address offset: 0xc000
I: Jumping to the first image slot
*** Booting My Application v2.7.99-8d9cb62c36df ***
*** Using nRF Connect SDK v2.7.99-8d9cb62c36df ***
*** Using Zephyr OS v3.6.99-25e278581141 ***
Starting Bluetooth Peripheral LBS example
I: 2 Sectors of 4096 bytes
I: alloc wra: 0, fa0
I: data wra: 0, 30
I: SoftDevice Controller build revision: 
I: 6c 48 af c9 da 87 c6 b7 |lH......
I: 89 37 8d 4c 36 5f bd 63 |.7.L6_.c
I: b9 bf 7e c2             |..~.    
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF54Lx (0x0005)
I: Firmware: Standard Bluetooth controller (0x00) Version 108.44872 Build 3330792137
I: No ID address. App must call settings_load()
Bluetooth initialized
I: Identity: C0:22:B6:54:D0:2D (random)
I: HCI: version 5.4 (0x0d) revision 0x3245, manufacturer 0x0059
I: LMP: version 5.4 (0x0d) subver 0x3245
Advertising successfully started
Connected
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: none
I: Image index: 0, Swap type: test
*** Booting MCUboot v2.1.0-dev-5eba7ab4cbfc ***
*** Using nRF Connect SDK v2.7.99-8d9cb62c36df ***
*** Using Zephyr OS v3.6.99-25e278581141 ***
I: Starting bootloader
I: Primary image: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
I: Secondary image: magic=good, swap_type=0x2, copy_done=0x3, image_ok=0x3
I: Boot source: none
I: Image index: 0, Swap type: test
I: Starting swap using move algorithm.
I: Bootloader chainload address offset: 0xc000
I: Jumping to the first image slot
*** Booting My Application v4.7.99-8d9cb62c36df ***
*** Using nRF Connect SDK v2.7.99-8d9cb62c36df ***
*** Using Zephyr OS v3.6.99-25e278581141 ***
Starting Bluetooth Peripheral LBS example
I: 2 Sectors of 4096 bytes
I: alloc wra: 0, fd0
I: data wra: 0, 0
I: SoftDevice Controller build revision: 
I: 6c 48 af c9 da 87 c6 b7 |lH......
I: 89 37 8d 4c 36 5f bd 63 |.7.L6_.c
I: b9 bf 7e c2             |..~.    
I: HW Platform: Nordic Semiconductor (0x0002)
I: HW Variant: nRF54Lx (0x0005)
I: Firmware: Standard Bluetooth controller (0x00) Version 108.44872 Build 3330792137
I: No ID address. App must call settings_load()
Bluetooth initialized
I: Identity: C0:22:B6:54:D0:2D (random)
I: HCI: version 5.4 (0x0d) revision 0x3245, manufacturer 0x0059
I: LMP: version 5.4 (0x0d) subver 0x3245
Advertising successfully started
```

2024-09-18 11:46 UTC, kapi-no approved these changes

2024-09-18 12:23 UTC, nvlsianpu commented
test-fw-nrfconnect-proprietary_esb - passed after re-run

2024-09-18 12:28 UTC, tomi-font approved these changes

2024-09-18 12:30 UTC, nordicjm commented
> test-fw-nrfconnect-proprietary_esb - passed after re-run test-fw-nrfconnect-nrf-iot_nrf_provisioning - failure irrelevant test-fw-nrfconnect-ble_mesh - failure irrelevant (unstable) test-low-leve - failure irrelevant
> 
> The rest CIs are green

When re-running CI, go to the PR ci job itself (not individual jobs) then click build, the `skip passed` checkbox should be ticked, click run, it will only rerun failed CI but will update the status here and allow merging

2024-09-18 13:27 UTC, ArekBalysNordic approved these changes

2024-09-19 09:28 UTC, kapi-no commented
@nvlsianpu, did you forget to bump the revision of sdk-zephyr in west manifest? It points still to the merged Zephyr PR?

2024-09-19 09:33 UTC, nvlsianpu commented
@kapi-no will fix in a moment - did locally, forgot to push...

2024-09-19 10:50 UTC, kapi-no approved these changes

2024-09-19 15:32 UTC, merged