manifest: Updated Matter repository to pull commissioning fix
nrfconnect/sdk-nrf pull request #17345
Opened 2024-09-17 07:09 UTC by kkasperczyk-no

The Matter version was updated to pull a fix for commissioning window.

2024-09-17 07:09 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/f6c947fef644f56cddb942c41e9a2b007753fe03 | https://github.com/nrfconnect/sdk-connectedhomeip/commit/7c2da28fd9c21ff4b5dd0aa027aff249d87dc526 (master) | [nrfconnect/sdk-connectedhomeip@f6c947fe..7c2da28f](https://github.com/nrfconnect/sdk-connectedhomeip/compare/f6c947fef644f56cddb942c41e9a2b007753fe03..7c2da28fd9c21ff4b5dd0aa027aff249d87dc526) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-17 07:12 UTC, doublemis1 commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19443: The device commissioning window can be opened for longer than 900 seconds, what violates the Matter specification.
Can we add information that the issue impacts following Matter Certification Test Cases:
[TC-CADMIN-1.21] Open commissioning window - durations max and max+1 [BCM] [DUT - Commissionee]
[TC-CADMIN-1.22] Open commissioning window - durations max and max+1 [ECM] [DUT - Commissionee]

2024-09-17 07:13 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [41d60810a0c2cd57b417c40ed00394a0f7f1c439](https://github.com/nrfconnect/sdk-nrf/pull/17345/commits/41d60810a0c2cd57b417c40ed00394a0f7f1c439)
matter: PR head: [7c2da28fd9c21ff4b5dd0aa027aff249d87dc526](https://github.com/nrfconnect/sdk-connectedhomeip/commit/7c2da28fd9c21ff4b5dd0aa027aff249d87dc526)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [41d60810a0c2cd57b417c40ed00394a0f7f1c439](https://github.com/nrfconnect/sdk-nrf/pull/17345/commits/41d60810a0c2cd57b417c40ed00394a0f7f1c439)
> merge base: [97dc80dd57cf4df3446cd4984b36d0e761999942](https://github.com/nrfconnect/sdk-nrf/commit/97dc80dd57cf4df3446cd4984b36d0e761999942)
> target head (main): [97dc80dd57cf4df3446cd4984b36d0e761999942](https://github.com/nrfconnect/sdk-nrf/commit/97dc80dd57cf4df3446cd4984b36d0e761999942)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/97dc80dd57cf4df3446cd4984b36d0e761999942..41d60810a0c2cd57b417c40ed00394a0f7f1c439)

matter:
> PR head: [7c2da28fd9c21ff4b5dd0aa027aff249d87dc526](https://github.com/nrfconnect/sdk-connectedhomeip/commit/7c2da28fd9c21ff4b5dd0aa027aff249d87dc526)
> merge base: [f6c947fef644f56cddb942c41e9a2b007753fe03](https://github.com/nrfconnect/sdk-connectedhomeip/commit/f6c947fef644f56cddb942c41e9a2b007753fe03)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/f6c947fef644f56cddb942c41e9a2b007753fe03..7c2da28fd9c21ff4b5dd0aa027aff249d87dc526)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (15)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  │ known_issues.rst
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── src
│  │  │  │  ├── app
│  │  │  │  │  ├── server
│  │  │  │  │  │  ├── CommissioningWindowManager.cpp
│  │  │  │  │  │  │ CommissioningWindowManager.h
│  │  │  │  ├── include
│  │  │  │  │  ├── platform
│  │  │  │  │  │  │ CHIPDeviceConfig.h
│  │  │  │  ├── platform
│  │  │  │  │  ├── ESP32
│  │  │  │  │  │  ├── CHIPDevicePlatformConfig.h
│  │  │  │  │  │  ├── nimble
│  │  │  │  │  │  │  │ BLEManagerImpl.cpp
│  │  │  │  │  ├── Linux
│  │  │  │  │  │  ├── BLEManagerImpl.cpp
│  │  │  │  │  │  ├── bluez
│  │  │  │  │  │  │  │ BluezAdvertisement.cpp
│  │  │  │  │  ├── NuttX
│  │  │  │  │  │  │ BLEManagerImpl.cpp
│  │  │  │  │  ├── Zephyr
│  │  │  │  │  │  ├── BLEManagerImpl.cpp
│  │  │  │  │  │  │ CHIPDevicePlatformConfig.h
│  │  │  │  │  ├── nrfconnect
│  │  │  │  │  │  │ CHIPDevicePlatformConfig.h
│  │  │  │  │  ├── silabs
│  │  │  │  │  │  ├── CHIPDevicePlatformConfig.h
│  │  │  │  │  │  ├── efr32
│  │  │  │  │  │  │  │ BLEManagerImpl.cpp
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-17 07:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17345
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-17 08:06 UTC, doublemis1 approved these changes

2024-09-17 09:58 UTC, wiba-nordic requested changes

2024-09-17 09:58 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19443: The device commissioning window can be opened for longer than 900 seconds, what violates the Matter specification.
```suggestion
KRKNWK-19443: The device commissioning window can be opened for longer than 900 seconds, which violates the Matter specification
```

2024-09-17 09:58 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  The device using Extended Announcement feature is allowed to open commissioning window for longer than 900 s only if it's uncommissioned.
```suggestion
  A device using the Extended Announcement feature is allowed to open the commissioning window for longer than 900 s only if it is uncommissioned.
```

2024-09-17 09:58 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  However, the implementation with Extended Announcement enabled allows to open commissioning window for longer than 900 s if the device is commissioned as well.
```suggestion
  However, the implementation with Extended Announcement enabled allows the device to open the commissioning window for longer than 900 s even when the device is commissioned.
```

2024-09-17 09:58 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  It leads to the TC-CADMIN-1.21 and TC-CADMIN-1.22 certification test cases failure.
```suggestion
  This leads to the TC-CADMIN-1.21 and TC-CADMIN-1.22 certification test cases failure.
```

2024-09-18 06:06 UTC, wiba-nordic approved these changes

2024-09-18 06:56 UTC, ArekBalysNordic approved these changes

2024-09-18 07:48 UTC, merged