doc: Added known issue related to clearing of the lock user
nrfconnect/sdk-nrf pull request #17341
Opened 2024-09-16 21:05 UTC by markaj-nordic

Added known issue about the lock sample not allowing for clearing of the user if the schedules feature is used and lock credentials are stored in the application.

2024-09-16 21:07 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [b525fceaff1906dcdfc0ddebf13949414ae93402](https://github.com/nrfconnect/sdk-nrf/pull/17341/commits/b525fceaff1906dcdfc0ddebf13949414ae93402)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [b525fceaff1906dcdfc0ddebf13949414ae93402](https://github.com/nrfconnect/sdk-nrf/pull/17341/commits/b525fceaff1906dcdfc0ddebf13949414ae93402)
> merge base: [8f3a64f3653688bc5e49dba14c7133f2b3490465](https://github.com/nrfconnect/sdk-nrf/commit/8f3a64f3653688bc5e49dba14c7133f2b3490465)
> target head (main): [8f3a64f3653688bc5e49dba14c7133f2b3490465](https://github.com/nrfconnect/sdk-nrf/commit/8f3a64f3653688bc5e49dba14c7133f2b3490465)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/8f3a64f3653688bc5e49dba14c7133f2b3490465..b525fceaff1906dcdfc0ddebf13949414ae93402)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  │ known_issues.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-16 21:28 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17341
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-17 09:53 UTC, wiba-nordic requested changes

2024-09-17 09:53 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19480: Lock sample does not allow for clearing the door lock user when using the schedules feature.
```suggestion
KRKNWK-19480: Lock sample does not allow for clearing the door lock user when using the schedules feature
```

2024-09-17 09:53 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  If the lock application is built with :kconfig:option:`CONFIG_LOCK_SCHEDULES` and lock credentials are programmed by the controller, clearing of the user always fails.
```suggestion
  If the lock application is built with the :kconfig:option:`CONFIG_LOCK_SCHEDULES` Kconfig option and lock credentials are programmed by the controller, clearing of the user always fails.
```

2024-09-25 09:40 UTC, wiba-nordic approved these changes

2024-09-25 09:44 UTC, wiba-nordic approved these changes

2024-09-25 11:08 UTC, ArekBalysNordic approved these changes

2024-09-25 14:52 UTC, merged