doc: Matter Bridge documentation enhancement
nrfconnect/sdk-nrf pull request #17342
Opened 2024-09-17 05:39 UTC by kg-nordicsemi

- Support for Thread protocol and nRF54H20 is experimental
- There is to many unnecesary buildings commands in smart-plug section

2024-09-17 05:42 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [a3a21b7b9e32bfd2596bd706515069739f418b50](https://github.com/nrfconnect/sdk-nrf/pull/17342/commits/a3a21b7b9e32bfd2596bd706515069739f418b50)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [a3a21b7b9e32bfd2596bd706515069739f418b50](https://github.com/nrfconnect/sdk-nrf/pull/17342/commits/a3a21b7b9e32bfd2596bd706515069739f418b50)
> merge base: [48cf0785e650f4b036e88e98f166ca06d2868edf](https://github.com/nrfconnect/sdk-nrf/commit/48cf0785e650f4b036e88e98f166ca06d2868edf)
> target head (main): [8f3a64f3653688bc5e49dba14c7133f2b3490465](https://github.com/nrfconnect/sdk-nrf/commit/8f3a64f3653688bc5e49dba14c7133f2b3490465)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/48cf0785e650f4b036e88e98f166ca06d2868edf..a3a21b7b9e32bfd2596bd706515069739f418b50)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
applications
│  ├── matter_bridge
│  │  ├── doc
│  │  │  │ matter_bridge_description.rst
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-17 06:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17342
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-17 06:29 UTC, maciejbaczmanski approved these changes

2024-09-17 06:45 UTC, kkasperczyk-no commented on applications/matter_bridge/doc/matter_bridge_description.rst
> +To enable the Matter smart plugin functionality, for example with :ref:`zephyr:nrf54h20dk_nrf54h20`, run the following command:
How about using some simpler example? It's only about presenting the part required for smart plug, so -Dmatter_bridge_SNIPPET=onoff_plug, the rest is not needed. I would suggest the following: 
```suggestion
To enable the Matter smart plugin functionality, run the following command with *board_target* replaced with the board target name:
```

2024-09-17 06:45 UTC, kkasperczyk-no commented on applications/matter_bridge/doc/matter_bridge_description.rst
> +   west build -b nrf54h20dk/nrf54h20/cpuapp -p -- -DSB_CONFIG_WIFI_NRF700X=y -DCONFIG_CHIP_WIFI=y -Dmatter_bridge_SHIELD=nrf700x_nrf54h20dk -DCONFIG_BRIDGED_DEVICE_BT=y -Dmatter_bridge_SNIPPET=onoff_
And with regards to the above comment:
```suggestion
   west build -b *board_target* -p -- -Dmatter_bridge_SNIPPET=onoff_plug
```

2024-09-17 07:15 UTC, kkasperczyk-no approved these changes

2024-09-17 09:45 UTC, wiba-nordic requested changes

2024-09-17 09:45 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Experimental Support for the :ref:`zephyr:nrf54h20dk_nrf54h20`.
```suggestion
  * Experimental support for the :ref:`zephyr:nrf54h20dk_nrf54h20`.
```

2024-09-17 09:45 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Experimental Support for the Thread protocol.
```suggestion
  * Experimental support for the Thread protocol.
```

2024-09-17 09:54 UTC, wiba-nordic approved these changes

2024-09-17 11:20 UTC, merged

2024-10-24 09:57 UTC, kkasperczyk-no commented on applications/matter_bridge/doc/matter_bridge_description.rst
> +   west build -b nrf54h20dk/nrf54h20/cpuapp -p -- -DSB_CONFIG_WIFI_NRF700X=y -DCONFIG_CHIP_WIFI=y -Dmatter_bridge_SHIELD=nrf700x_nrf54h20dk -DCONFIG_BRIDGED_DEVICE_BT=y -Dmatter_bridge_SNIPPET=onoff_
@kg-nordicsemi why haven't you applied this comment and resolved conversation? I've just noticed that the documentation was not fixed while reviewing the guide before the release. I suggest to resolve conversation AFTER applying the fix to not forget to do that.

2024-10-24 10:04 UTC, kkasperczyk-no commented on applications/matter_bridge/doc/matter_bridge_description.rst
> +   west build -b nrf54h20dk/nrf54h20/cpuapp -p -- -DSB_CONFIG_WIFI_NRF700X=y -DCONFIG_CHIP_WIFI=y -Dmatter_bridge_SHIELD=nrf700x_nrf54h20dk -DCONFIG_BRIDGED_DEVICE_BT=y -Dmatter_bridge_SNIPPET=onoff_
Sorry, it wasn't your fault :) Someone probably didn't rebase after your commit was merged and then force pushed PR, so your change was removed: https://github.com/nrfconnect/sdk-nrf/commit/b364fd802a36bd39cde9202d65735da8677bae97#diff-f250f5581599929b90c895f576af0b1ccf1b6dc333c1d6a859ac992cae861eb9R740

I will fix this.