samples: cellular: nrf_cloud: Control online alert
nrfconnect/sdk-nrf pull request #17422
Opened 2024-09-20 23:08 UTC by plskeggs

By default, no longer send an alert on startup.

Add logging of the reset reason, and if the online alert is enabled, include that in the value.

IRIS-9688

2024-09-20 23:11 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [d35e681f69224ff1edfed575e5888b06ad2f11bb](https://github.com/nrfconnect/sdk-nrf/pull/17422/commits/d35e681f69224ff1edfed575e5888b06ad2f11bb)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [d35e681f69224ff1edfed575e5888b06ad2f11bb](https://github.com/nrfconnect/sdk-nrf/pull/17422/commits/d35e681f69224ff1edfed575e5888b06ad2f11bb)
> merge base: [6e0e90ef17462312cc79278c5d5e88ab177b50f4](https://github.com/nrfconnect/sdk-nrf/commit/6e0e90ef17462312cc79278c5d5e88ab177b50f4)
> target head (main): [6e0e90ef17462312cc79278c5d5e88ab177b50f4](https://github.com/nrfconnect/sdk-nrf/commit/6e0e90ef17462312cc79278c5d5e88ab177b50f4)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/6e0e90ef17462312cc79278c5d5e88ab177b50f4..d35e681f69224ff1edfed575e5888b06ad2f11bb)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
doc
│  ├── nrf
│  │  │ links.txt
samples
│  ├── cellular
│  │  ├── nrf_cloud_multi_service
│  │  │  ├── Kconfig
│  │  │  ├── README.rst
│  │  │  ├── src
│  │  │  │  │ application.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :white_medium_square: Integration tests
   - :orange_circle: test-fw-nrfconnect-nrf-iot_cloud

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-09-20 23:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17422
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-23 05:30 UTC, peknis requested changes

2024-09-23 05:30 UTC, peknis commented on samples/cellular/nrf_cloud_multi_service/README.rst
> +If :kconfig:option:`CONFIG_SEND_ONLINE_ALERT` is enabled, it sends an alert to nRF Cloud containing the reset reason as the value field.
```suggestion
If the :kconfig:option:`CONFIG_SEND_ONLINE_ALERT` Kconfig option is enabled, it sends an alert to nRF Cloud containing the reset reason as the value field.
```

2024-09-23 18:19 UTC, glarsennordic approved these changes

2024-09-23 18:20 UTC, glarsennordic commented
That's interesting, did me reviewing this clear the review request for you @tony-le-24 @jayteemo ?

2024-09-23 18:23 UTC, jayteemo approved these changes

2024-09-23 18:23 UTC, jayteemo commented on samples/cellular/nrf_cloud_multi_service/src/application.c
> +static void report_reset(void)
nit
```suggestion
static void print_reset_reason(void)
```

2024-09-23 18:35 UTC, tony-le-24 commented
@glarsennordic it does clear my review request.

2024-09-23 21:39 UTC, tony-le-24 approved these changes
LGTM, green after manually CI testing.

2024-09-24 22:55 UTC, tony-le-24 commented
There are compliance issues about some trailing white spaces.

2024-09-25 05:49 UTC, peknis approved these changes

2024-09-26 14:50 UTC, merged