manifest: update Zephyr revision
nrfconnect/sdk-nrf pull request #17556
Opened 2024-09-30 12:19 UTC by maciejbaczmanski

Pull missing Zephyr KConfigs and enable
`OPENTHREAD_DYNAMIC_STORE_FRAME_AHEAD_COUNTER` by default

2024-09-30 12:19 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/4322f5169f4c0f24e3712de061a2fec5a29098a7 (main) | https://github.com/nrfconnect/sdk-zephyr/pull/2054 | [nrfconnect/sdk-zephyr#2054/files](https://github.com/nrfconnect/sdk-zephyr/pull/2054/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-30 12:21 UTC, LuDuda approved these changes

2024-09-30 12:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17556
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-09-30 12:48 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [7eae1e2faec3fd9b562645c3fe5758f5d05e6516](https://github.com/nrfconnect/sdk-nrf/pull/17556/commits/7eae1e2faec3fd9b562645c3fe5758f5d05e6516)
openthread: PR head: [2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56](https://github.com/zephyrproject-rtos/openthread/commit/2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56)
zephyr: PR head: [14dd7e8915aae3d47b9647959ab12c604c597112](https://github.com/nrfconnect/sdk-zephyr/pull/2054/commits/14dd7e8915aae3d47b9647959ab12c604c597112)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [7eae1e2faec3fd9b562645c3fe5758f5d05e6516](https://github.com/nrfconnect/sdk-nrf/pull/17556/commits/7eae1e2faec3fd9b562645c3fe5758f5d05e6516)
> merge base: [2bae3437305bc8f5eb29260ca545fb8033b2b80b](https://github.com/nrfconnect/sdk-nrf/commit/2bae3437305bc8f5eb29260ca545fb8033b2b80b)
> target head (main): [2bae3437305bc8f5eb29260ca545fb8033b2b80b](https://github.com/nrfconnect/sdk-nrf/commit/2bae3437305bc8f5eb29260ca545fb8033b2b80b)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/2bae3437305bc8f5eb29260ca545fb8033b2b80b..7eae1e2faec3fd9b562645c3fe5758f5d05e6516)

openthread:
> PR head: [2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56](https://github.com/zephyrproject-rtos/openthread/commit/2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56)
> merge base: [e10a92570f94ff1e0bc5e0da9ecf0ee135d955a6](https://github.com/zephyrproject-rtos/openthread/commit/e10a92570f94ff1e0bc5e0da9ecf0ee135d955a6)
> [Diff](https://github.com/zephyrproject-rtos/openthread/compare/e10a92570f94ff1e0bc5e0da9ecf0ee135d955a6..2aeb8b833ba760ec29d5f340dd1ce7bcb61c5d56)

zephyr:
> PR head: [14dd7e8915aae3d47b9647959ab12c604c597112](https://github.com/nrfconnect/sdk-zephyr/pull/2054/commits/14dd7e8915aae3d47b9647959ab12c604c597112)
> merge base: [4322f5169f4c0f24e3712de061a2fec5a29098a7](https://github.com/nrfconnect/sdk-zephyr/commit/4322f5169f4c0f24e3712de061a2fec5a29098a7)
> target head (main): [4322f5169f4c0f24e3712de061a2fec5a29098a7](https://github.com/nrfconnect/sdk-zephyr/commit/4322f5169f4c0f24e3712de061a2fec5a29098a7)
> [Diff](https://github.com/nrfconnect/sdk-zephyr/compare/4322f5169f4c0f24e3712de061a2fec5a29098a7..14dd7e8915aae3d47b9647959ab12c604c597112)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (404)</summary>

```
modules
│  ├── lib
│  │  ├── openthread
│  │  │  ├── .code-spell-ignore
│  │  │  ├── .github
│  │  │  │  ├── workflows
│  │  │  │  │  ├── build.yml
│  │  │  │  │  ├── codeql.yml
│  │  │  │  │  ├── docker.yml
│  │  │  │  │  ├── fuzz.yml
│  │  │  │  │  ├── makefile-check.yml
│  │  │  │  │  ├── otbr.yml
│  │  │  │  │  ├── otci.yml
│  │  │  │  │  ├── otns.yml
│  │  │  │  │  ├── posix.yml
│  │  │  │  │  ├── scorecards.yml
│  │  │  │  │  ├── simulation-1.1.yml
│  │  │  │  │  ├── simulation-1.4.yml
│  │  │  │  │  ├── size.yml
│  │  │  │  │  ├── toranj.yml
│  │  │  │  │  ├── unit.yml
│  │  │  │  │  │ version.yml
│  │  │  ├── .gitignore
│  │  │  ├── CMakeLists.txt
│  │  │  ├── etc
│  │  │  │  ├── cmake
│  │  │  │  │  │ options.cmake
│  │  │  ├── examples
│  │  │  │  ├── config
│  │  │  │  │  ├── ot-core-config-check-size-br.h
│  │  │  │  │  ├── ot-core-config-check-size-ftd.h
│  │  │  │  │  │ ot-core-config-check-size-mtd.h
│  │  │  │  ├── platforms
│  │  │  │  │  ├── simulation
│  │  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  │  ├── alarm.c
│  │  │  │  │  │  ├── infra_if.c
│  │  │  │  │  │  ├── openthread-core-simulation-config.h
│  │  │  │  │  │  ├── platform-config.h
│  │  │  │  │  │  ├── platform-simulation.h
│  │  │  │  │  │  ├── radio.c
│  │  │  │  │  │  ├── system.c
│  │  │  │  │  │  ├── virtual_time
│  │  │  │  │  │  │  │ alarm-sim.c
│  │  │  │  │  ├── utils
│  │  │  │  │  │  ├── mac_frame.cpp
│  │  │  │  │  │  │ mac_frame.h
│  │  │  ├── include
│  │  │  │  ├── openthread
│  │  │  │  │  ├── ble_secure.h
│  │  │  │  │  ├── border_agent.h
│  │  │  │  │  ├── border_routing.h
│  │  │  │  │  ├── coap.h
│  │  │  │  │  ├── coap_secure.h
│  │  │  │  │  ├── icmp6.h
│  │  │  │  │  ├── instance.h
│  │  │  │  │  ├── link.h
│  │  │  │  │  ├── platform
│  │  │  │  │  │  ├── dnssd.h
│  │  │  │  │  │  ├── multipan.h
│  │  │  │  │  │  ├── radio.h
│  │  │  │  │  │  │ time.h
│  │  │  │  │  ├── tcat.h
│  │  │  │  │  ├── thread.h
│  │  │  │  │  │ thread_ftd.h
│  │  │  ├── script
│  │  │  │  ├── check-arm-build
│  │  │  │  ├── check-gn-build
│  │  │  │  ├── check-scan-build
│  │  │  │  ├── check-simulation-build-cmake
│  │  │  │  ├── check-simulation-local-host
│  │  │  │  ├── cmake-build
│  │  │  │  ├── git-tool
│  │  │  │  ├── make-pretty
│  │  │  │  │ test
│  │  │  ├── src
│  │  │  │  ├── cli
│  │  │  │  │  ├── README.md
│  │  │  │  │  ├── README_BR.md
│  │  │  │  │  ├── README_TCAT.md
│  │  │  │  │  ├── cli.cpp
│  │  │  │  │  ├── cli.hpp
│  │  │  │  │  ├── cli_br.cpp
│  │  │  │  │  ├── cli_coap.cpp
│  │  │  │  │  ├── cli_coap_secure.cpp
│  │  │  │  │  ├── cli_coap_secure.hpp
│  │  │  │  │  ├── cli_dataset.cpp
│  │  │  │  │  ├── cli_dataset.hpp
│  │  │  │  │  ├── cli_dns.cpp
│  │  │  │  │  ├── cli_link_metrics.cpp
│  │  │  │  │  ├── cli_link_metrics.hpp
│  │  │  │  │  │ cli_tcat.cpp
│  │  │  │  ├── core
│  │  │  │  │  ├── BUILD.gn
│  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  ├── api
│  │  │  │  │  │  ├── border_agent_api.cpp
│  │  │  │  │  │  ├── border_routing_api.cpp
│  │  │  │  │  │  ├── channel_manager_api.cpp
│  │  │  │  │  │  ├── coap_api.cpp
│  │  │  │  │  │  ├── coap_secure_api.cpp
│  │  │  │  │  │  ├── link_api.cpp
│  │  │  │  │  │  ├── thread_api.cpp
│  │  │  │  │  │  │ thread_ftd_api.cpp
│  │  │  │  │  ├── backbone_router
│  │  │  │  │  │  ├── bbr_leader.cpp
│  │  │  │  │  │  ├── bbr_local.cpp
│  │  │  │  │  │  │ bbr_manager.cpp
│  │  │  │  │  ├── border_router
│  │  │  │  │  │  ├── infra_if.cpp
│  │  │  │  │  │  ├── routing_manager.cpp
│  │  │  │  │  │  │ routing_manager.hpp
│  │  │  │  │  ├── coap
│  │  │  │  │  │  ├── coap.cpp
│  │  │  │  │  │  ├── coap.hpp
│  │  │  │  │  │  ├── coap_message.cpp
│  │  │  │  │  │  ├── coap_message.hpp
│  │  │  │  │  │  ├── coap_secure.cpp
│  │  │  │  │  │  │ coap_secure.hpp
│  │  │  │  │  ├── common
│  │  │  │  │  │  ├── heap_string.cpp
│  │  │  │  │  │  ├── heap_string.hpp
│  │  │  │  │  │  ├── message.cpp
│  │  │  │  │  │  ├── message.hpp
│  │  │  │  │  │  ├── offset_range.cpp
│  │  │  │  │  │  ├── offset_range.hpp
│  │  │  │  │  │  ├── string.cpp
│  │  │  │  │  │  ├── string.hpp
│  │  │  │  │  │  ├── tlvs.cpp
│  │  │  │  │  │  │ tlvs.hpp
│  │  │  │  │  ├── config
│  │  │  │  │  │  ├── border_routing.h
│  │  │  │  │  │  ├── mle.h
│  │  │  │  │  │  ├── network_diagnostic.h
│  │  │  │  │  │  ├── openthread-core-config-check.h
│  │  │  │  │  │  │ srp_client.h
│  │  │  │  │  ├── diags
│  │  │  │  │  │  ├── README.md
│  │  │  │  │  │  ├── factory_diags.cpp
│  │  │  │  │  │  │ factory_diags.hpp
│  │  │  │  │  ├── instance
│  │  │  │  │  │  ├── instance.cpp
│  │  │  │  │  │  │ instance.hpp
│  │  │  │  │  ├── mac
│  │  │  │  │  │  ├── data_poll_sender.cpp
│  │  │  │  │  │  ├── mac.cpp
│  │  │  │  │  │  ├── mac_frame.cpp
│  │  │  │  │  │  ├── mac_frame.hpp
│  │  │  │  │  │  ├── mac_header_ie.cpp
│  │  │  │  │  │  ├── mac_header_ie.hpp
│  │  │  │  │  │  ├── mac_links.hpp
│  │  │  │  │  │  ├── sub_mac.cpp
│  │  │  │  │  │  ├── sub_mac.hpp
│  │  │  │  │  │  │ sub_mac_csl_receiver.cpp
│  │  │  │  │  ├── meshcop
│  │  │  │  │  │  ├── border_agent.cpp
│  │  │  │  │  │  ├── border_agent.hpp
│  │  │  │  │  │  ├── commissioner.cpp
│  │  │  │  │  │  ├── commissioner.hpp
│  │  │  │  │  [...]

2024-10-01 13:32 UTC, nordicjm requested changes
Commit message and description does not match contents at all

2024-10-02 06:26 UTC, nordicjm approved these changes

2024-10-02 06:27 UTC, merged