applications: nrf_desktop: Drop nRF54L PDK support
nrfconnect/sdk-nrf pull request #17588
Opened 2024-10-02 06:07 UTC by MarekPieta

Change drops nRF54L PDK support.

Jira: NCSDK-29420

2024-10-02 06:08 UTC, MarekPieta commented
https://github.com/nrfconnect/sdk-nrf/pull/17561 needs to go in first

2024-10-02 06:14 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [dec88b0009f961bc2f351cbc26335a804acb40f2](https://github.com/nrfconnect/sdk-nrf/pull/17588/commits/dec88b0009f961bc2f351cbc26335a804acb40f2)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [dec88b0009f961bc2f351cbc26335a804acb40f2](https://github.com/nrfconnect/sdk-nrf/pull/17588/commits/dec88b0009f961bc2f351cbc26335a804acb40f2)
> merge base: [7b1f88d8009719d50fd389487257675246ff4a70](https://github.com/nrfconnect/sdk-nrf/commit/7b1f88d8009719d50fd389487257675246ff4a70)
> target head (main): [7b1f88d8009719d50fd389487257675246ff4a70](https://github.com/nrfconnect/sdk-nrf/commit/7b1f88d8009719d50fd389487257675246ff4a70)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/7b1f88d8009719d50fd389487257675246ff4a70..dec88b0009f961bc2f351cbc26335a804acb40f2)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (36)</summary>

```
applications
│  ├── nrf_desktop
│  │  ├── board_configuration.rst
│  │  ├── configuration
│  │  │  ├── nrf54l15dk_nrf54l15_cpuapp
│  │  │  │  ├── app.overlay
│  │  │  │  ├── buttons_def.h
│  │  │  │  ├── buttons_sim_def.h
│  │  │  │  ├── click_detector_def.h
│  │  │  │  ├── hid_keyboard_leds_def.h
│  │  │  │  ├── hid_keyboard_leds_def_keyboard.h
│  │  │  │  ├── hid_keymap_def.h
│  │  │  │  ├── hid_keymap_def_keyboard.h
│  │  │  │  ├── images
│  │  │  │  │  ├── mcuboot
│  │  │  │  │  │  ├── app.overlay
│  │  │  │  │  │  ├── mcuboot_private.pem
│  │  │  │  │  │  ├── mcuboot_private_fast_pair.pem
│  │  │  │  │  │  ├── prj.conf
│  │  │  │  │  │  ├── prj_fast_pair.conf
│  │  │  │  │  │  ├── prj_keyboard.conf
│  │  │  │  │  │  │ prj_release.conf
│  │  │  │  ├── led_state_def.h
│  │  │  │  ├── pm_static.yml
│  │  │  │  ├── pm_static_fast_pair.yml
│  │  │  │  ├── pm_static_keyboard.yml
│  │  │  │  ├── pm_static_release.yml
│  │  │  │  ├── port_state_def.h
│  │  │  │  ├── prj.conf
│  │  │  │  ├── prj_fast_pair.conf
│  │  │  │  ├── prj_keyboard.conf
│  │  │  │  ├── prj_release.conf
│  │  │  │  ├── sysbuild.conf
│  │  │  │  ├── sysbuild_fast_pair.conf
│  │  │  │  ├── sysbuild_keyboard.conf
│  │  │  │  │ sysbuild_release.conf
│  │  │  ├── nrf54l15pdk_nrf54l15_cpuapp
│  │  │  │  ├── images
│  │  │  │  │  ├── mcuboot
│  │  │  │  │  │  ├── mcuboot_private.pem
│  │  │  │  │  │  │ mcuboot_private_fast_pair.pem
│  │  ├── description.rst
│  │  ├── doc
│  │  │  │ wheel.rst
│  │  │ sample.yaml
scripts
│  ├── hid_configurator
│  │  │ NrfHidManager.py
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-02 06:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17588
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-03 06:50 UTC, divipillai approved these changes

2024-10-07 08:30 UTC, kapi-no requested changes
Let's wait for this first https://github.com/nrfconnect/sdk-nrf/pull/17436 to minimize the usage of CI resources

2024-10-07 08:35 UTC, miha-nordic approved these changes

2024-10-08 12:54 UTC, kapi-no reviewed
Removing NAK, @MarekPieta  please rebase and fix conflict

2024-10-09 07:14 UTC, merged