manifest: sdk-connectedhomeip: Fix reliability issues with multicasts
nrfconnect/sdk-nrf pull request #17633
Opened 2024-10-03 20:29 UTC by LuDuda

This commit updates the Matter SDK revision to include fixes that improve the reliability of multicast message delivery by enabling MLDv2 reporting.

Btw. After this is merged i do plan to backport the fix to NCS 2.6 and 2.7 branches as well.

2024-10-03 20:30 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/486 | [nrfconnect/sdk-connectedhomeip#486/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/486/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-03 20:33 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [c89b9849df710127513e5ec6a3560d1b683617ef](https://github.com/nrfconnect/sdk-nrf/pull/17633/commits/c89b9849df710127513e5ec6a3560d1b683617ef)
matter: PR head: [aaf528b3877eb3be3f37b73ba8213743ca104367](https://github.com/nrfconnect/sdk-connectedhomeip/pull/486/commits/aaf528b3877eb3be3f37b73ba8213743ca104367)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [c89b9849df710127513e5ec6a3560d1b683617ef](https://github.com/nrfconnect/sdk-nrf/pull/17633/commits/c89b9849df710127513e5ec6a3560d1b683617ef)
> merge base: [547aaab19c52cc03660d57943a963480a042e14f](https://github.com/nrfconnect/sdk-nrf/commit/547aaab19c52cc03660d57943a963480a042e14f)
> target head (main): [547aaab19c52cc03660d57943a963480a042e14f](https://github.com/nrfconnect/sdk-nrf/commit/547aaab19c52cc03660d57943a963480a042e14f)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/547aaab19c52cc03660d57943a963480a042e14f..c89b9849df710127513e5ec6a3560d1b683617ef)

matter:
> PR head: [aaf528b3877eb3be3f37b73ba8213743ca104367](https://github.com/nrfconnect/sdk-connectedhomeip/pull/486/commits/aaf528b3877eb3be3f37b73ba8213743ca104367)
> merge base: [89eb37b47ca8e4b9d309c431bde30bdb19d07577](https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577)
> target head (master): [89eb37b47ca8e4b9d309c431bde30bdb19d07577](https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/89eb37b47ca8e4b9d309c431bde30bdb19d07577..aaf528b3877eb3be3f37b73ba8213743ca104367)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  │ known_issues.rst
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── src
│  │  │  │  ├── platform
│  │  │  │  │  ├── nrfconnect
│  │  │  │  │  │  │ ConnectivityManagerImpl.cpp
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-03 20:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17633
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-04 05:42 UTC, wiba-nordic requested changes

2024-10-04 05:42 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  Certain Access Points require Wi-Fi devices to send MLDv2 (Multicast Listener Discovery version 2) Report messages in order for multicast packets to be properly delivered to a given address.
```suggestion
  Certain Access Points require Wi-Fi devices to send Multicast Listener Discovery version 2 (MLDv2) Report messages for multicast packets to be properly delivered to a given address.
```

2024-10-04 05:42 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** To ensure reliable multicast communication, use the ``net_ipv6_mld_join`` and ``net_ipv6_mld_leave`` functions to explicitly subscribe or unsubscribe to multicast addresses.
```suggestion
  **Workaround:** To ensure reliable multicast communication, use the :c:func:`net_ipv6_mld_join` and :c:func:`net_ipv6_mld_leave` functions to explicitly subscribe or unsubscribe to multicast addresses.
```

2024-10-04 05:42 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  For reference, you can refer to the commit with the fix in the ``sdk-connectedhomeip`` repository (commit hash: ``TBD``).
```suggestion
  For reference, see the commit with the fix in the ``sdk-connectedhomeip`` repository (commit hash: ``TBD``).
```

2024-10-10 05:35 UTC, wiba-nordic approved these changes

2024-10-10 08:33 UTC, nordicjm approved these changes

2024-10-11 14:36 UTC, merged

2024-10-11 15:25 UTC, LuDuda commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  For reference, see the commit with the fix in the ``sdk-connectedhomeip`` repository (commit hash: ``TBD``).
Seems that the hash was not updated before merging to `08acaf44604acef6679bd7eb2d6b51245bcfa54c`. Will file a PR for it.