manifest: sdk-connectedhomeip: Update revision
nrfconnect/sdk-nrf pull request #17632
Opened 2024-10-03 19:53 UTC by LuDuda

This commit updates the revision of Matter SDK as well as clarify how to enable CC3xx support for samples with PSA.

2024-10-03 19:53 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/485 | [nrfconnect/sdk-connectedhomeip#485/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/485/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-03 19:54 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [d14f3eeae5447d7d7786041a689b047f855e6a47](https://github.com/nrfconnect/sdk-nrf/pull/17632/commits/d14f3eeae5447d7d7786041a689b047f855e6a47)
matter: PR head: [a7cb4d14661ae221fb413954499ba643902d3c9c](https://github.com/nrfconnect/sdk-connectedhomeip/pull/485/commits/a7cb4d14661ae221fb413954499ba643902d3c9c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [d14f3eeae5447d7d7786041a689b047f855e6a47](https://github.com/nrfconnect/sdk-nrf/pull/17632/commits/d14f3eeae5447d7d7786041a689b047f855e6a47)
> merge base: [ab3c57c3513ad309740eaaac0fc222413d35882e](https://github.com/nrfconnect/sdk-nrf/commit/ab3c57c3513ad309740eaaac0fc222413d35882e)
> target head (main): [547aaab19c52cc03660d57943a963480a042e14f](https://github.com/nrfconnect/sdk-nrf/commit/547aaab19c52cc03660d57943a963480a042e14f)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/ab3c57c3513ad309740eaaac0fc222413d35882e..d14f3eeae5447d7d7786041a689b047f855e6a47)

matter:
> PR head: [a7cb4d14661ae221fb413954499ba643902d3c9c](https://github.com/nrfconnect/sdk-connectedhomeip/pull/485/commits/a7cb4d14661ae221fb413954499ba643902d3c9c)
> merge base: [89eb37b47ca8e4b9d309c431bde30bdb19d07577](https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577)
> target head (master): [89eb37b47ca8e4b9d309c431bde30bdb19d07577](https://github.com/nrfconnect/sdk-connectedhomeip/commit/89eb37b47ca8e4b9d309c431bde30bdb19d07577)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/89eb37b47ca8e4b9d309c431bde30bdb19d07577..a7cb4d14661ae221fb413954499ba643902d3c9c)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (6)</summary>

```
doc
│  ├── nrf
│  │  ├── protocols
│  │  │  ├── matter
│  │  │  │  ├── end_product
│  │  │  │  │  │ security.rst
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── config
│  │  │  │  ├── nrfconnect
│  │  │  │  │  ├── chip-module
│  │  │  │  │  │  ├── Kconfig
│  │  │  │  │  │  │ Kconfig.defaults
samples
│  ├── matter
│  │  ├── template
│  │  │  │ sample.yaml
subsys
│  ├── net
│  │  ├── openthread
│  │  │  │ Kconfig
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-thread

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-04 05:32 UTC, wiba-nordic requested changes
The entries switch between "driver" and "backend" when referring to CRACEN and Oberon, and I'm not sure that's correct. Please unify wording if necessary.

2024-10-04 05:32 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/security.rst
> +.. [1] The CryptoCell backend is used in parallel with the Oberon backend. By default, the CryptoCell backend is used only for Random Number Generation (RNG) and the AEAD key derivation driver.
```suggestion
.. [1] The CryptoCell backend is used in parallel with the Oberon backend.
       By default, the CryptoCell backend is used only for Random Number Generation (RNG) and the AEAD key derivation driver.
```

2024-10-04 05:32 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/security.rst
> +       To enable the CryptoCell backend for additional operations, set the :kconfig:option:CONFIG_PSA_CRYPTO_DRIVER_CC3XX Kconfig option to true.
```suggestion
       To enable the CryptoCell backend for additional operations, set the :kconfig:option:`CONFIG_PSA_CRYPTO_DRIVER_CC3XX` Kconfig option to true.
```

2024-10-04 05:32 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/security.rst
> +.. [2] The CRACEN backend is used in parallel with the Oberon backend. The CRACEN driver is used by default for any supported cryptographic operations.
```suggestion
.. [2] The CRACEN backend is used in parallel with the Oberon backend.
       The CRACEN driver is used by default for any supported cryptographic operations.
```

2024-10-04 05:32 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/security.rst
> +       you will need to disable those operations in the CRACEN driver, as it takes priority when both are enabled.
```suggestion
       For all other operations not supported by CRACEN, the Oberon backend is used.
       To use the Oberon implementation for specific cryptographic operations supported by both drivers, disable those operations in the CRACEN driver, as it takes priority when both are enabled.
```

2024-10-04 07:27 UTC, ArekBalysNordic approved these changes

2024-10-04 07:27 UTC, ArekBalysNordic commented on subsys/net/openthread/Kconfig
> +	select MBEDTLS_ENABLE_HEAP if (!OPENTHREAD_COPROCESSOR_RCP && !BUILD_WITH_TFM)
```suggestion
	select MBEDTLS_ENABLE_HEAP if (!OPENTHREAD_COPROCESSOR_RCP && !BUILD_WITH_TFM && !PSA_SSF_CRYPTO_CLIENT)
```

To cover nRF54H20?

2024-10-09 19:32 UTC, doublemis1 approved these changes
LGTM!

2024-10-10 05:36 UTC, wiba-nordic approved these changes

2024-10-10 08:33 UTC, nordicjm approved these changes

2024-10-11 14:35 UTC, merged