wifi: Re-instate Wi-Fi driver docs
nrfconnect/sdk-nrf pull request #17653
Opened 2024-10-05 18:57 UTC by krish2718

The driver still resides in Zephyr upstream, but docs are only in NCS as Zephyr doesn't have vedor docs.

- [ ] Fix `options-from-kconfig` extensions to take a custom path @gmarull 
- [ ] Add `external_context` extensions to pull in RST + Doxygen docs from `modules/hal/nordic/drivers/nrf_wifi/doc` @gmarull

2024-10-05 18:58 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-10-05 19:17 UTC, krish2718 commented
Doc failure is due to #1

2024-10-07 08:51 UTC, sachinthegreen approved these changes

2024-10-07 08:51 UTC, gmarull commented
> The driver still resides in Zephyr upstream, but docs are only in NCS as Zephyr doesn't have vedor docs.
> 
> * [ ]  Fix `options-from-kconfig` extensions to take a custom path @gmarull
> * [ ]  Add `external_context` extensions to pull in RST + Doxygen docs from `modules/hal/nordic/drivers/nrf_wifi/doc` @gmarull

For external_content simply extend `doc/nrf/conf.py` paths, and for Doxygen the same in `doc/nrf/nrf.doxyfile.in`.

2024-10-07 10:17 UTC, krish2718 commented
> > The driver still resides in Zephyr upstream, but docs are only in NCS as Zephyr doesn't have vedor docs.
> > 
> > * [ ]   Fix `options-from-kconfig` extensions to take a custom path @gmarull
> > * [ ]   Add `external_context` extensions to pull in RST + Doxygen docs from `modules/hal/nordic/drivers/nrf_wifi/doc` @gmarull
> 
> For external_content simply extend `doc/nrf/conf.py` paths, and for Doxygen the same in `doc/nrf/nrf.doxyfile.in`.

The `nrfx` (`hal_nordic`) docset from the utils has been removed https://github.com/nrfconnect/sdk-nrf/blame/main/doc/_utils/utils.py#L22 should I bring it back or just hardcode the path `HAL_NORDIC_BASE`?

2024-10-17 10:11 UTC, bama-nordic commented on doc/nrf/drivers/wifi/native/nrf70.rst
> +If 15 dBm needs to be configured then value 60 (0x3c in hex) should be configured.
I am suggesting a little re-wording below. Let's review and update -

The following code block shows an example of the DTS overlay file. The entries shown are only to serve as examples and don’t represent values for any particular PCB design or package type.
Customers are expected to fill in the appropriate values based on measurements obtained from transmitter testing on their custom product. The values are represented in 0.25 dB steps. For example, if 15 dBm needs to be configured then value 60 or 0x3c (hex) should be used.

2024-10-17 10:14 UTC, bama-nordic commented on doc/nrf/drivers/wifi/native/nrf70.rst
> +To avoid this problem, you can specify the power ceiling at which the EVM and spectral mask are met for a given PCB design.
This ensures that the final maximum transmit power won't be above these specified values.

2024-10-17 10:23 UTC, richabp requested changes
I think it requires an additional Wi-Fi driver top page, with the following subpages-

- nRF Wi-Fi driver 
- nRF Wi-Fi portable driver

2024-10-17 10:23 UTC, richabp commented on doc/nrf/drivers/wifi/portable/nrf70.rst
> +The nRF Wi-Fi portable driver implements OS agnostic code for the nRF70 FullMAC Series of devices.
```suggestion
The nRF Wi-Fi portable driver implements OS-agnostic code for the nRF70 FullMAC Series of devices.
```

2024-10-17 10:23 UTC, richabp commented on doc/nrf/drivers/wifi/portable/nrf70.rst
> +This can be used to implement OS native drivers for the nRF70 Series devices.
```suggestion
This code can be used to implement OS-native drivers for the nRF70 Series devices.
```

2024-10-17 10:23 UTC, richabp commented on doc/nrf/drivers/wifi/portable/nrf70.rst
> +To use the Ethernet interface, the application can use `Zephyr Network APIs`_.
```suggestion
Once the nRF Wi-Fi driver is initialized, the application recognizes it as an Ethernet interface.
To use the Ethernet interface, the application can use the `Zephyr Network APIs`_.
```

2024-10-17 10:23 UTC, richabp commented on doc/nrf/drivers/wifi/portable/nrf70.rst
> +See the :ref:`nrfx:nrf_wifi_api` to learn more about various modes of low-level API.
```suggestion
See the :ref:`nrfx:nrf_wifi_api` to learn more about various modes of the low-level API.
```

2024-10-17 10:54 UTC, richabp commented
Please remove the third bullet about the driver documentation form the "Removed" section of "Documentation" from the Changelog https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/releases_and_maturity/releases/release-notes-changelog.html#documentation.

2024-10-24 18:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17653
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-24 21:16 UTC, krish2718 commented
> I think it requires an additional Wi-Fi driver top page, with the following subpages-
> 
> * nRF Wi-Fi driver
> * nRF Wi-Fi portable driver

we already have it https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17653/nrf/drivers/wifi.html

2024-10-24 21:17 UTC, krish2718 commented
Only pending items it to link to the generated doxygen content.

2024-10-25 08:01 UTC, bama-nordic approved these changes

2024-10-25 09:30 UTC, richabp commented on doc/nrf/drivers/wifi/nrf70_native.rst
> +The nRF Wi-Fi driver follows an OS agnostic design, and the driver implementation is split into OS-agnostic and OS (Zephyr)-specific code.
```suggestion
The nRF Wi-Fi driver follows an OS-agnostic design, and the driver implementation is split into OS-agnostic and OS (Zephyr)-specific code.
```

2024-10-25 09:30 UTC, richabp commented on doc/nrf/drivers/wifi/nrf70_native.rst
> +Note that the numbers filled in the following example do not represent any particular PCB design or package type.
Consider converting this into note if "note" has to remain in the sentence.
```suggestion
Note that the numbers used in this example do not represent any particular PCB design or package type.
```

2024-10-25 09:30 UTC, richabp commented on doc/nrf/drivers/wifi/native/nrf70.rst
> +Please see the DTS binding documentation for more information.
Can the link be added?

2024-10-25 09:33 UTC, richabp requested changes
Minor nits.

2024-10-28 10:52 UTC, krish2718 commented
> Only pending items it to link to the generated doxygen content.

As discussed with @gmarull , this needs more work and will be taken up later.

2024-10-28 15:05 UTC, krish2718 commented on doc/nrf/drivers/wifi/nrf70_native.rst
> +The values are represented in 0.25 dB increments.
This is not true, during upstreaming based on review comments, we have made this generic, so, removed the custom step size and used 1dBM, so, this and example values should be scaled down. Look at https://github.com/nrfconnect/sdk-zephyr/blob/main/drivers/wifi/nrfwifi/src/fmac_main.c#L497

2024-10-28 16:18 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/cc3c2ac3a76288c06a0a266527070fac89709e1a | https://github.com/nrfconnect/sdk-zephyr/pull/2183 | [nrfconnect/sdk-zephyr#2183/files](https://github.com/nrfconnect/sdk-zephyr/pull/2183/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-28 20:31 UTC, krish2718 commented
For some reason the doc build check has been disappeared, any ideas?

2024-10-28 21:52 UTC, krish2718 commented
> For some reason the doc build check has been disappeared, any ideas?

rebase seems to do the trick.

2024-10-29 11:00 UTC, srkanordic approved these changes

2024-10-29 12:41 UTC, richabp approved these changes

2024-10-29 13:52 UTC, PerMac submitted a review, later dismissed
does this resolve any issue from the quarantine https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine.yaml? If so, please also remove such entries from quarantine within this PR so we can let the CI verify the fixes. If not relevant, just ignore my comment and dismiss my request

2024-10-29 13:57 UTC, krish2718 commented
> does this resolve any issue from the quarantine https://github.com/nrfconnect/sdk-nrf/blob/main/scripts/quarantine.yaml? If so, please also remove such entries from quarantine within this PR so we can let the CI verify the fixes. If not relevant, just ignore my comment and dismiss my request

As commented https://github.com/nrfconnect/sdk-nrf/pull/18241#pullrequestreview-2401953783 Quarantine will be part of that PR.

2024-10-29 15:00 UTC, divipillai commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> -  * nRF70 Series support is upstreamed to Zephyr, hence the documentation is removed from the |NCS|.
Please remove this file and add a comment in PR - https://github.com/nrfconnect/sdk-nrf/pull/18192.

2024-10-30 07:39 UTC, umapraseeda commented on CODEOWNERS
> +/doc/nrf/drivers/wifi.rst                 @sachinthegreen @krish2718
```suggestion
/doc/nrf/drivers/wifi.rst                 @nrfconnect/ncs-wifi-doc
```

2024-10-30 09:07 UTC, rlubos reviewed
Please update SHAs

2024-10-30 09:07 UTC, rlubos commented on west.yml
>      # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
Typo in the commit message :`mainfet: sdk-zephyr: `

2024-10-30 11:23 UTC, rlubos approved these changes

2024-10-30 11:23 UTC, rlubos commented
@nrfconnect/ncs-co-drivers @nrfconnect/ncs-co-build-system Please review

2024-10-30 12:50 UTC, anangl approved these changes

2024-10-30 15:30 UTC, merged