samples: net: http_server: No fatal error for setup_server
nrfconnect/sdk-nrf pull request #17659
Opened 2024-10-07 06:57 UTC by stig-bjorlykke

Creating a server socket for one family type may fail while the other family type works. Do not terminate with FATAL_ERROR() in this case.

2024-10-07 06:59 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [fd6aa726153eff5f171dbebb2f38b34539a6db20](https://github.com/nrfconnect/sdk-nrf/pull/17659/commits/fd6aa726153eff5f171dbebb2f38b34539a6db20)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [fd6aa726153eff5f171dbebb2f38b34539a6db20](https://github.com/nrfconnect/sdk-nrf/pull/17659/commits/fd6aa726153eff5f171dbebb2f38b34539a6db20)
> merge base: [f0654346b9c7b64482740b1ee730641f2470410b](https://github.com/nrfconnect/sdk-nrf/commit/f0654346b9c7b64482740b1ee730641f2470410b)
> target head (main): [f0654346b9c7b64482740b1ee730641f2470410b](https://github.com/nrfconnect/sdk-nrf/commit/f0654346b9c7b64482740b1ee730641f2470410b)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/f0654346b9c7b64482740b1ee730641f2470410b..fd6aa726153eff5f171dbebb2f38b34539a6db20)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
samples
│  ├── net
│  │  ├── http_server
│  │  │  ├── src
│  │  │  │  │ main.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-07 07:33 UTC, jtguggedal approved these changes

2024-10-07 08:05 UTC, eivindj-nordic approved these changes
Should we have a changelog entry for this?

2024-10-07 10:42 UTC, stig-bjorlykke commented
> Should we have a changelog entry for this?

Fixed.

2024-10-07 10:49 UTC, peknis requested changes

2024-10-07 10:49 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    * Do not fail with a fatal error if IPv4 or IPv6 server setup fails.
```suggestion
  * Fixed not to fail with a fatal error if IPv4 or IPv6 server setup fails.
```

2024-10-07 10:55 UTC, peknis approved these changes

2024-10-07 11:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17659
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-08 08:05 UTC, divipillai approved these changes

2024-10-08 15:25 UTC, rlubos approved these changes

2024-10-08 15:25 UTC, merged