applications: nrf5340_audio: Fix HFClock calculation
nrfconnect/sdk-nrf pull request #17730
Opened 2024-10-08 10:00 UTC by alexsven

- Fixes bug where the calculation for HFClock was entered incorrectly
 - Old value: 39854
 - New correct value: 39845.888
- OCT-NONE

2024-10-08 10:06 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [fcfb4e15f007502999e6ed90fb0318f73881c57f](https://github.com/nrfconnect/sdk-nrf/pull/17730/commits/fcfb4e15f007502999e6ed90fb0318f73881c57f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [fcfb4e15f007502999e6ed90fb0318f73881c57f](https://github.com/nrfconnect/sdk-nrf/pull/17730/commits/fcfb4e15f007502999e6ed90fb0318f73881c57f)
> merge base: [4bad1c2b3a6cb176f56ada5575e7e48785e7b9da](https://github.com/nrfconnect/sdk-nrf/commit/4bad1c2b3a6cb176f56ada5575e7e48785e7b9da)
> target head (main): [18d7fd830f9293d5ce95ae70a70313b177257d03](https://github.com/nrfconnect/sdk-nrf/commit/18d7fd830f9293d5ce95ae70a70313b177257d03)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/4bad1c2b3a6cb176f56ada5575e7e48785e7b9da..fcfb4e15f007502999e6ed90fb0318f73881c57f)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
applications
│  ├── nrf5340_audio
│  │  ├── src
│  │  │  ├── modules
│  │  │  │  │ audio_i2s.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-sdk-audio

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-08 10:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17730
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-08 11:36 UTC, rick1082 approved these changes

2024-10-09 07:01 UTC, koffes commented
Approved. General note as that this only influences the initial condition of the PLL, and it will correct itself out automatically.

2024-10-09 07:05 UTC, koffes requested changes
Need to correct in audio_datapath as well.

2024-10-13 17:01 UTC, koffes approved these changes

2024-10-14 07:27 UTC, merged