Samples: Bluetooth: conn time sync fix
nrfconnect/sdk-nrf pull request #17745
Opened 2024-10-08 13:29 UTC by HaavardRei

This commit fixes the following:
  * Fix a bug in the initialization of `init_val` in the GPIOTE task used for the LED, where it would always be initialized to `NRF_GPIOTE_INITIAL_VALUE_HIGH` and not take the dt_flags into account. This made the LED toggle with inverted polarity on platforms where the LEDs are active high.
  * Update references to LED numbers in the README to match the actual sample behavior.

2024-10-08 13:43 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
sdk-nrf: PR head: [fed1324417ce4a7d7a88c9d58cc8658b7b9d3fd5](https://github.com/nrfconnect/sdk-nrf/pull/17745/commits/fed1324417ce4a7d7a88c9d58cc8658b7b9d3fd5)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [fed1324417ce4a7d7a88c9d58cc8658b7b9d3fd5](https://github.com/nrfconnect/sdk-nrf/pull/17745/commits/fed1324417ce4a7d7a88c9d58cc8658b7b9d3fd5)
> merge base: [4a34c9083a88920d3298f26a0e3058454c1b510d](https://github.com/nrfconnect/sdk-nrf/commit/4a34c9083a88920d3298f26a0e3058454c1b510d)
> target head (main): [4a34c9083a88920d3298f26a0e3058454c1b510d](https://github.com/nrfconnect/sdk-nrf/commit/4a34c9083a88920d3298f26a0e3058454c1b510d)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/4a34c9083a88920d3298f26a0e3058454c1b510d..fed1324417ce4a7d7a88c9d58cc8658b7b9d3fd5)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
samples
│  ├── bluetooth
│  │  ├── conn_time_sync
│  │  │  ├── README.rst
│  │  │  ├── src
│  │  │  │  │ timed_led_toggle.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-08 13:47 UTC, rugeGerritsen approved these changes

2024-10-08 13:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17745
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-08 14:16 UTC, Tschet1 approved these changes

2024-10-09 05:36 UTC, peknis approved these changes

2024-10-09 06:35 UTC, maje-emb approved these changes

2024-10-10 08:16 UTC, peknis requested changes

2024-10-10 08:16 UTC, peknis commented on samples/bluetooth/conn_time_sync/README.rst
> +       Blinks simultaneously on all devices after synchronization takes place.
```suggestion
      LED 2:
         Blinks simultaneously on all devices after synchronization takes place.
```
This should make this look like a term list, meaning bolding the first line.

2024-10-10 08:16 UTC, peknis commented on samples/bluetooth/conn_time_sync/README.rst
> +       Blinks simultaneously on all devices after synchronization takes place.
```suggestion
      LED 1:
         Blinks simultaneously on all devices after synchronization takes place.
```

2024-10-10 08:28 UTC, HaavardRei commented on samples/bluetooth/conn_time_sync/README.rst
> +       Blinks simultaneously on all devices after synchronization takes place.
Added both suggestions now!

2024-10-10 08:29 UTC, peknis approved these changes

2024-10-10 13:47 UTC, merged