doc: Update the ownership of RST files
nrfconnect/sdk-nrf pull request #17747
Opened 2024-10-08 13:56 UTC by umapraseeda

Add the ownership of all the RST files and txt files to the relevant techwriter groups assigned to the different software teams

2024-10-11 14:17 UTC, carlescufi requested changes

2024-10-11 14:17 UTC, carlescufi commented on CODEOWNERS
> +/doc/                                     @nrfconnect/ncs-co-doc
Please remove this one, we need to ensure that we catch missing entries and this will mask them

2024-10-11 14:17 UTC, carlescufi commented on CODEOWNERS
> +/doc/kconfig/*.rst                        @nrfconnect/ncs-doc-leads
Inside the `/doc/` folder you do not need the `*.rst` endings, just use:

`/doc/kconfig/`

and so on

2024-10-14 12:24 UTC, carlescufi commented
@umapraseeda  can you take this out of draft please?

2024-10-15 11:20 UTC, carlescufi requested changes

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/app_dev/**/                      @nrfconnect/ncs-doc-leads @nrfconnect/ncs-vestavind-doc
```suggestion
/doc/nrf/app_dev/                      @nrfconnect/ncs-doc-leads @nrfconnect/ncs-vestavind-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/                                 @nrfconnect/ncs-doc-leads
```suggestion
/doc/nrf/*.rst                                @nrfconnect/ncs-doc-leads
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/app_dev/bootloaders_dfu/**/      @nrfconnect/ncs-pluto-doc
```suggestion
/doc/nrf/app_dev/bootloaders_dfu/      @nrfconnect/ncs-pluto-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/dev_model_and_contributions/**/  @nrfconnect/ncs-doc-leads @nrfconnect/ncs-vestavind-doc
```suggestion
/doc/nrf/dev_model_and_contributions/  @nrfconnect/ncs-doc-leads @nrfconnect/ncs-vestavind-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/libraries/bluetooth_services/**/ @nrfconnect/ncs-si-muffin-doc @nrfconnect/ncs-dragoon-doc
```suggestion
/doc/nrf/libraries/bluetooth_services/ @nrfconnect/ncs-si-muffin-doc @nrfconnect/ncs-dragoon-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/libraries/bluetooth_services/mesh/**/ @nrfconnect/ncs-paladin-doc
```suggestion
/doc/nrf/libraries/bluetooth_services/mesh/ @nrfconnect/ncs-paladin-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/includes/*.txt                   @nrfconnect/ncs-doc-leads
```suggestion
/doc/nrf/includes/                   @nrfconnect/ncs-doc-leads
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/libraries/dfu/**/                @nrfconnect/ncs-pluto-doc
```suggestion
/doc/nrf/libraries/dfu/                @nrfconnect/ncs-pluto-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/libraries/nfc/**/                @nrfconnect/ncs-si-muffin-doc
```suggestion
/doc/nrf/libraries/nfc/                @nrfconnect/ncs-si-muffin-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/protocols/bt/bt_mesh/**/         @nrfconnect/ncs-paladin-doc
```suggestion
/doc/nrf/protocols/bt/bt_mesh/         @nrfconnect/ncs-paladin-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/protocols/matter/**/             @nrfconnect/ncs-matter-doc
```suggestion
/doc/nrf/protocols/matter/             @nrfconnect/ncs-matter-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/protocols/thread/**/             @nrfconnect/ncs-terahertz-doc
```suggestion
/doc/nrf/protocols/thread/             @nrfconnect/ncs-terahertz-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/protocols/wifi/**/               @nrfconnect/ncs-wifi-doc
```suggestion
/doc/nrf/protocols/wifi/               @nrfconnect/ncs-wifi-doc
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/releases_and_maturity/**/        @nrfconnect/ncs-doc-release
```suggestion
/doc/nrf/releases_and_maturity/        @nrfconnect/ncs-doc-release
```

2024-10-15 11:20 UTC, carlescufi commented on CODEOWNERS
> +/doc/nrf/test_and_optimize/**/            @nrfconnect/ncs-doc-leads
```suggestion
/doc/nrf/test_and_optimize/            @nrfconnect/ncs-doc-leads
```

2024-10-15 17:19 UTC, gmarull approved these changes

2024-10-16 07:48 UTC, b-gent approved these changes

2024-10-16 08:41 UTC, merged