Misc doc updates
nrfconnect/sdk-nrf pull request #17758
Opened 2024-10-08 22:25 UTC by jayteemo

Improve documentation in header comments.

2024-10-08 22:26 UTC, jayteemo commented
The changes were requested by Tuomas: https://github.com/theflintstone/sdk-nrf/pull/1

2024-10-08 22:29 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [2156926276dfe3ab0cec94639f3a62b3dbe2821a](https://github.com/nrfconnect/sdk-nrf/pull/17758/commits/2156926276dfe3ab0cec94639f3a62b3dbe2821a)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [2156926276dfe3ab0cec94639f3a62b3dbe2821a](https://github.com/nrfconnect/sdk-nrf/pull/17758/commits/2156926276dfe3ab0cec94639f3a62b3dbe2821a)
> merge base: [2c7add3b620b1256abf0508b22674c31c6d79366](https://github.com/nrfconnect/sdk-nrf/commit/2c7add3b620b1256abf0508b22674c31c6d79366)
> target head (main): [2c7add3b620b1256abf0508b22674c31c6d79366](https://github.com/nrfconnect/sdk-nrf/commit/2c7add3b620b1256abf0508b22674c31c6d79366)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/2c7add3b620b1256abf0508b22674c31c6d79366..2156926276dfe3ab0cec94639f3a62b3dbe2821a)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
include
│  ├── modem
│  │  │ modem_jwt.h
│  ├── net
│  │  ├── nrf_cloud.h
│  │  ├── nrf_cloud_coap.h
│  │  │ nrf_cloud_location.h
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-fw-nrfconnect-nrf-iot_cloud
   - :orange_circle: test-fw-nrfconnect-nrf-iot_mosh
   - :orange_circle: test-fw-nrfconnect-nrf-iot_positioning
   - :orange_circle: test-sdk-mcuboot
   - :warning: test-fw-nrfconnect-fw-update

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-08 22:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17758
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-09 00:13 UTC, plskeggs approved these changes

2024-10-09 05:40 UTC, peknis requested changes

2024-10-09 05:40 UTC, peknis commented on include/net/nrf_cloud_coap.h
> + * The full DTLS handshake will be performed, and on success, a connection ID (CID) will be
```suggestion
 * The full DTLS handshake is performed, and on success, a connection ID (CID) is
```

2024-10-09 05:40 UTC, peknis commented on include/net/nrf_cloud.h
> +	 *     1: only LOG_ERR (most urgent) will be sent to the cloud.
```suggestion
	/** If 0: None - the nrf_cloud library logging backend is disabled.
	 *     4: LOG_DBG (least urgent) and all levels below are sent to the cloud.
	 *     3: LOG_INF and all levels below are sent to the cloud.
	 *     2: LOG_WRN and all levels below are sent to the cloud.
	 *     1: only LOG_ERR (most urgent) is sent to the cloud.
```

2024-10-11 05:28 UTC, peknis approved these changes
Approved with a couple of minor nits.

2024-10-11 05:28 UTC, peknis commented on include/net/nrf_cloud_coap.h
> + * modem, SIM card and FOTA capabilities.
```suggestion
 * modem, SIM card, and FOTA capabilities.
```

2024-10-11 05:28 UTC, peknis commented on include/net/nrf_cloud.h
> + * The device data cards on nrfcloud.com automatically appear when the device
```suggestion
 * The device data cards on the nRF Cloud portal automatically appear when the device
```

2024-10-11 22:46 UTC, glarsennordic approved these changes

2024-10-14 07:11 UTC, nordicjm approved these changes

2024-10-14 07:19 UTC, eivindj-nordic approved these changes

2024-10-14 07:28 UTC, merged