samples: wifi: radio_test: Add 54H/L support to radio test sample
nrfconnect/sdk-nrf pull request #17773
Opened 2024-10-09 09:23 UTC by D-Triveni

Add build support for 54H/L targets for radio_test sample.

2024-10-09 09:28 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [2c574d037fe41cfc3e407672dd38dcf04810524a](https://github.com/nrfconnect/sdk-nrf/pull/17773/commits/2c574d037fe41cfc3e407672dd38dcf04810524a)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [2c574d037fe41cfc3e407672dd38dcf04810524a](https://github.com/nrfconnect/sdk-nrf/pull/17773/commits/2c574d037fe41cfc3e407672dd38dcf04810524a)
> merge base: [85dfab5a556022c1f84bc2e542ace42b66edbec4](https://github.com/nrfconnect/sdk-nrf/commit/85dfab5a556022c1f84bc2e542ace42b66edbec4)
> target head (main): [6c4ccc353909f1908d6f1317779233c1db7a6d59](https://github.com/nrfconnect/sdk-nrf/commit/6c4ccc353909f1908d6f1317779233c1db7a6d59)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/85dfab5a556022c1f84bc2e542ace42b66edbec4..2c574d037fe41cfc3e407672dd38dcf04810524a)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
samples
│  ├── wifi
│  │  ├── radio_test
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-sdk-wifi

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-09 09:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17773
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-14 12:36 UTC, sachinthegreen requested changes

2024-10-14 12:36 UTC, sachinthegreen commented on samples/wifi/radio_test/sample.yaml
> +      - nrf54l15pdk/nrf54l15/cpuapp
nrf54l15pdk is deprecated.

2024-10-14 15:13 UTC, krish2718 commented on samples/wifi/radio_test/sample.yaml
> +  sample.nrf7002eb_interposer_p1.nrf7002eb.radio_test:
```suggestion
  sample.nrf7002eb.radio_test:
```

2024-10-15 12:08 UTC, krish2718 approved these changes

2024-10-17 11:03 UTC, merged