matter: include EXTRAVERSION in Matter software version string
nrfconnect/sdk-nrf pull request #17787
Opened 2024-10-09 13:51 UTC by Damian-Nordic

Switch the Matter software version string from
APP_VERSION_TWEAK_STRING to APP_VERSION_EXTENDED_STRING.

2024-10-09 13:52 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/490 | [nrfconnect/sdk-connectedhomeip#490/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/490/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-09 13:54 UTC, nordicjm approved these changes

2024-10-09 13:55 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [8fa93088f5927dac57cf68daf08e5d8ff9b2b5f9](https://github.com/nrfconnect/sdk-nrf/pull/17787/commits/8fa93088f5927dac57cf68daf08e5d8ff9b2b5f9)
matter: PR head: [c33838a60097af9eb3e5b994f1b765cebea8df60](https://github.com/nrfconnect/sdk-connectedhomeip/pull/490/commits/c33838a60097af9eb3e5b994f1b765cebea8df60)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [8fa93088f5927dac57cf68daf08e5d8ff9b2b5f9](https://github.com/nrfconnect/sdk-nrf/pull/17787/commits/8fa93088f5927dac57cf68daf08e5d8ff9b2b5f9)
> merge base: [28220dccd486da3b28ab120f3bae089e2fb7f8da](https://github.com/nrfconnect/sdk-nrf/commit/28220dccd486da3b28ab120f3bae089e2fb7f8da)
> target head (main): [28220dccd486da3b28ab120f3bae089e2fb7f8da](https://github.com/nrfconnect/sdk-nrf/commit/28220dccd486da3b28ab120f3bae089e2fb7f8da)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/28220dccd486da3b28ab120f3bae089e2fb7f8da..8fa93088f5927dac57cf68daf08e5d8ff9b2b5f9)

matter:
> PR head: [c33838a60097af9eb3e5b994f1b765cebea8df60](https://github.com/nrfconnect/sdk-connectedhomeip/pull/490/commits/c33838a60097af9eb3e5b994f1b765cebea8df60)
> merge base: [5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2](https://github.com/nrfconnect/sdk-connectedhomeip/commit/5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2)
> target head (master): [5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2](https://github.com/nrfconnect/sdk-connectedhomeip/commit/5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/5a55d6099f6fdbdebdac9c0d7ea41fcfb751e7f2..c33838a60097af9eb3e5b994f1b765cebea8df60)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── config
│  │  │  │  ├── zephyr
│  │  │  │  │  ├── ota-image.cmake
│  │  │  │  │  │ ota-image_sysbuild.cmake
│  │  │  ├── src
│  │  │  │  ├── platform
│  │  │  │  │  ├── nrfconnect
│  │  │  │  │  │  │ CHIPDevicePlatformConfig.h
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-09 19:03 UTC, LuDuda reviewed
Thank you @Damian-Nordic!

I think we need slightly to modify the documentation here: https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/protocols/matter/end_product/versioning.html

We did ignore the extra string previously to have parity between BLE and Matter OTA images. Saying this, I think it's better to have an option to define this extra string even though it's not easily doable for BLE.

@doublemis1 could you check if some tests need adjustments?

2024-10-10 06:20 UTC, kkasperczyk-no approved these changes

2024-10-21 10:21 UTC, wiba-nordic requested changes

2024-10-21 10:21 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The firmware version format used for informational purposes when using the :file:``VERSION`` file to include the ``EXTRAVERSION`` component.
```suggestion
  * The firmware version format used for informational purposes when using the :file:``VERSION`` file.
    The format now includes the ``EXTRAVERSION`` component.
```
Could also be "the optional \`\`EXTRAVERSION`` component" if we want to highlight that it isn't necessary to use the component.

2024-10-21 10:28 UTC, wiba-nordic approved these changes

2024-10-21 10:40 UTC, divipillai approved these changes

2024-10-21 13:00 UTC, merged