doc: known issues: Add KRKNWK-19263 related to Zigbee FOTA bug on nRF53
nrfconnect/sdk-nrf pull request #17813
Opened 2024-10-10 11:56 UTC by AdamZelikNS

Added KRKNWK-19263 as a known issue.

2024-10-10 11:57 UTC, AdamZelikNS commented
Fix mentioned as the "workaround" provided here https://github.com/nrfconnect/sdk-nrf/pull/17796. Waiting for merge and then I will update the hash

2024-10-10 11:57 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-10-10 12:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17813
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-10 12:16 UTC, wiba-nordic requested changes

2024-10-10 12:16 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19263: FOTA DFU on nRF5340 fails due to invalid update image
```suggestion
KRKNWK-19263: FOTA DFU on the nRF5340 DK fails due to an invalid update image
```

2024-10-10 12:16 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  Performing fota dfu on nrf5340 throws an error during an attempt to install the new image.
```suggestion
  Performing FOTA DFU throws an error during an attempt to install the new image.
  
  **Affected platforms:** nRF5340
```

2024-10-10 12:16 UTC, wiba-nordic commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Manually cherry-pick and apply commit with fix from main (commit hash: ``to be updated: pull/17796 not yet merged``).
```suggestion
  **Workaround:** Manually cherry-pick and apply the commit with the fix from ``main`` (commit hash: ``to be updated: pull/17796 not yet merged``).
```

2024-10-11 08:24 UTC, AdamZelikNS commented on doc/nrf/releases_and_maturity/known_issues.rst
> +.. rst-class:: v2-7-0
👍 done

2024-10-11 08:24 UTC, AdamZelikNS commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19263: FOTA DFU on nRF5340 fails due to invalid update image
👍 fixed

2024-10-11 08:24 UTC, AdamZelikNS commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  Performing fota dfu on nrf5340 throws an error during an attempt to install the new image.
fixed

2024-10-11 08:24 UTC, AdamZelikNS commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Manually cherry-pick and apply commit with fix from main (commit hash: ``to be updated: pull/17796 not yet merged``).
fixed

2024-10-11 09:09 UTC, wiba-nordic approved these changes

2024-10-11 09:22 UTC, edmont approved these changes

2024-10-11 11:22 UTC, merged