samples: bluetooth: peripheral_mds: Set device ID at build time
nrfconnect/sdk-nrf pull request #17823
Opened 2024-10-10 13:40 UTC by jtguggedal

The device ID when using the MAC address was Unknown after the system booted because the device has not been given a MAC address yet at the time the device ID is set (system init). This change removes the option for using a MAC address as the device id for BLE devices, and sets a static device id for the BLE sample app.

2024-10-10 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=17823) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=17823) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=17823) it.</sub>

2024-10-10 13:41 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [666cd96fd282e95cef5cf20f755927125dff2a77](https://github.com/nrfconnect/sdk-nrf/pull/17823/commits/666cd96fd282e95cef5cf20f755927125dff2a77)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [666cd96fd282e95cef5cf20f755927125dff2a77](https://github.com/nrfconnect/sdk-nrf/pull/17823/commits/666cd96fd282e95cef5cf20f755927125dff2a77)
> merge base: [87476db9d2c5f448f89a79abffaf2f4a8e60da49](https://github.com/nrfconnect/sdk-nrf/commit/87476db9d2c5f448f89a79abffaf2f4a8e60da49)
> target head (main): [87476db9d2c5f448f89a79abffaf2f4a8e60da49](https://github.com/nrfconnect/sdk-nrf/commit/87476db9d2c5f448f89a79abffaf2f4a8e60da49)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/87476db9d2c5f448f89a79abffaf2f4a8e60da49..666cd96fd282e95cef5cf20f755927125dff2a77)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
samples
│  ├── bluetooth
│  │  ├── peripheral_mds
│  │  │  ├── README.rst
│  │  │  │ prj.conf
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-10 14:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17823
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-11 05:30 UTC, peknis requested changes

2024-10-11 05:30 UTC, peknis commented on samples/bluetooth/peripheral_mds/README.rst
> +Use :kconfig:option:`CONFIG_MEMFAULT_NCS_DEVICE_ID` to set a static device ID. For this sample, the device id is ``ncs-ble-testdevice`` by default.
```suggestion
Use the :kconfig:option:`CONFIG_MEMFAULT_NCS_DEVICE_ID` Kconfig option to set a static device ID.
For this sample, the device ID is ``ncs-ble-testdevice`` by default.
```

2024-10-11 06:53 UTC, peknis approved these changes

2024-10-11 12:38 UTC, jtguggedal commented on samples/bluetooth/peripheral_mds/prj.conf
> +CONFIG_MEMFAULT_LOGGING_ENABLE=y
No, this enables the Memfault logging backend so that log messages are part of the coredump sent to Memfault

2024-10-11 12:49 UTC, pdunaj approved these changes

2024-10-11 13:28 UTC, maje-emb approved these changes

2024-10-16 10:26 UTC, umapraseeda approved these changes
Approving the changelog addition.

2024-10-16 10:30 UTC, divipillai approved these changes

2024-10-16 10:47 UTC, wiba-nordic approved these changes

2024-10-16 18:35 UTC, rlubos commented
@nrfconnect/ncs-dragoon Ping

2024-10-17 06:54 UTC, hermabe commented
> @nrfconnect/ncs-dragoon Ping

Dragoon does not own this sample afaik

2024-10-17 07:09 UTC, rugeGerritsen commented
> > @nrfconnect/ncs-dragoon Ping
> 
> Dragoon does not own this sample afaik

FYI. @ppryga-nordic  will create a PR to update the codeowners file for the bluetooth samples

2024-10-17 07:39 UTC, merged