applications: nrf5340_audio: Change source of inline functions to Zephyr
nrfconnect/sdk-nrf pull request #17878
Opened 2024-10-14 12:08 UTC by gWacey

OCT-3115

The static inline functions in broadcast_config_tool.h has been moved to upstream Zephyr. We need to remove the functions from broadcast_config_tool.h and use these instead.

2024-10-14 12:13 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [57b4733a5d9cdff91b745964e91dddb58b6e0b47](https://github.com/nrfconnect/sdk-nrf/pull/17878/commits/57b4733a5d9cdff91b745964e91dddb58b6e0b47)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [57b4733a5d9cdff91b745964e91dddb58b6e0b47](https://github.com/nrfconnect/sdk-nrf/pull/17878/commits/57b4733a5d9cdff91b745964e91dddb58b6e0b47)
> merge base: [9418b891fc38d7b4bd7be2688e8cf73bee0ab4e5](https://github.com/nrfconnect/sdk-nrf/commit/9418b891fc38d7b4bd7be2688e8cf73bee0ab4e5)
> target head (main): [19fe584068cb106c2b184b309595f0824c400f77](https://github.com/nrfconnect/sdk-nrf/commit/19fe584068cb106c2b184b309595f0824c400f77)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/9418b891fc38d7b4bd7be2688e8cf73bee0ab4e5..57b4733a5d9cdff91b745964e91dddb58b6e0b47)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
samples
│  ├── bluetooth
│  │  ├── broadcast_config_tool
│  │  │  ├── README.rst
│  │  │  ├── include
│  │  │  │  │ broadcast_config_tool.h
│  │  │  ├── src
│  │  │  │  │ main.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-14 12:43 UTC, peknis requested changes

2024-10-14 12:43 UTC, peknis commented on samples/bluetooth/broadcast_config_tool/README.rst
> +an SD-card. The SD-card shall be formatted with either FAT or Ext2 file system.
```suggestion
The sample supports only pre-encoded LC3 data stored as :file:`<filename>.lc3` files on
an SD card.
The SD card must be formatted with either FAT or Ext2 file system.
```

2024-10-14 12:43 UTC, peknis commented on samples/bluetooth/broadcast_config_tool/README.rst
> +#. Insert the SD card loaded with the pre-encoded LC3 data.
```suggestion
1. Insert the SD card loaded with the pre-encoded LC3 data.
```

2024-10-14 12:53 UTC, peknis requested changes

2024-10-14 12:53 UTC, peknis commented on samples/bluetooth/broadcast_config_tool/README.rst
>  .. _broadcast_configuration_tool_ui:
Move this link tag above the **Shell commands list** title, not forgetting to leave one blank line before the title.
It is now failing the doc build. Link tags must always be just before the section titles.

2024-10-15 09:24 UTC, peknis approved these changes

2024-10-15 11:16 UTC, alexsven commented on samples/bluetooth/broadcast_config_tool/src/main.c
>  	}
I'm not getting the -1 and then +1 operation, could you explain why it doesn't go from 0? And if there is a match for `i`, why do we need to add 1 before returning? If name is "Back Left" (BIT(4)) for instance, then `i` would be 4 and the return value is 5, but it should really be BIT(4) which is 16. I guess that was made to work for Mono Audio as this is 0 and thus outside of the whole BIT() operation. I suggest to add a special case for that outside of the for loop:

```suggestion
	/* Check if name == Mono Audio */
	if (strcasecmp(bt_audio_location_bit_to_str(BT_AUDIO_LOCATION_MONO_AUDIO), name) == 0) {
	        return BT_AUDIO_LOCATION_MONO_AUDIO;
	}

	for (int i = 0; i < get_bits_set_num(BT_AUDIO_LOCATION_ANY); i++) {
		if (strcasecmp(bt_audio_location_bit_to_str(BIT(i)), name) == 0) {
			return BIT(i);
		}
	}
```

2024-10-15 11:26 UTC, alexsven commented on samples/bluetooth/broadcast_config_tool/src/main.c
>  	}
```suggestion
        shell_print(shell, "%d - %s", 0, bt_audio_location_bit_to_str(0));
        
	for (int i = 0; i < get_bits_set_num(BT_AUDIO_LOCATION_ANY); i++) {
		shell_print(shell, "%d - %s", BIT(i), bt_audio_location_bit_to_str(BIT(i)));
	}
```

2024-10-15 11:28 UTC, alexsven commented on samples/bluetooth/broadcast_config_tool/include/broadcast_config_tool.h
> -static struct audio_location locations[] = {
I had this short hand name so that people didn't have to spell out `F r o n t   L e f t` every time, we can discuss whether or not to have it there.

2024-10-16 06:23 UTC, alexsven approved these changes

2024-10-16 10:17 UTC, koffes requested changes

2024-10-16 10:17 UTC, koffes commented on samples/bluetooth/broadcast_config_tool/README.rst
> +Make sure you format the SD card with either FAT or Ext2 file system.
Only FAT is supported.

2024-10-16 10:17 UTC, koffes commented on samples/bluetooth/broadcast_config_tool/src/main.c
> +static int8_t context_set_max(uint16_t bits)
The word "set" implies that something is being set. Consider different name.

2024-10-17 08:58 UTC, koffes approved these changes

2024-10-17 13:49 UTC, merged