doc: SUIT DFU customize guide fixes for 2.8.0
nrfconnect/sdk-nrf pull request #17928
Opened 2024-10-16 12:57 UTC by ahasztag

This commit updates this part of the documentation taking into account changes for 2.8.0 release

2024-10-16 13:10 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [c8cbbba8fcac3181a4d1dd013fe7f624b7c8fd88](https://github.com/nrfconnect/sdk-nrf/pull/17928/commits/c8cbbba8fcac3181a4d1dd013fe7f624b7c8fd88)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [c8cbbba8fcac3181a4d1dd013fe7f624b7c8fd88](https://github.com/nrfconnect/sdk-nrf/pull/17928/commits/c8cbbba8fcac3181a4d1dd013fe7f624b7c8fd88)
> merge base: [9190d3a83974cc069b9569c060bcd84ffae3c200](https://github.com/nrfconnect/sdk-nrf/commit/9190d3a83974cc069b9569c060bcd84ffae3c200)
> target head (main): [205c209f4a8e20e23e6516517987191c0cfbdc22](https://github.com/nrfconnect/sdk-nrf/commit/205c209f4a8e20e23e6516517987191c0cfbdc22)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/9190d3a83974cc069b9569c060bcd84ffae3c200..c8cbbba8fcac3181a4d1dd013fe7f624b7c8fd88)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
doc
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── device_guides
│  │  │  │  ├── working_with_nrf
│  │  │  │  │  ├── nrf54h
│  │  │  │  │  │  ├── ug_nrf54h20_suit_customize_dfu.rst
│  │  │  │  │  │  │ ug_nrf54h20_suit_customize_qsg.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-17 09:50 UTC, maciejpietras commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
> +These templates can be found in :file:`nrf/config/suit/templates` and are suitable for standard development needs.
```suggestion
These templates can be found in :file:`nrf/config/suit/templates` and are suitable for typical development needs.
```

2024-10-17 09:51 UTC, maciejpietras commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
> +* Gey thr vendor name by using ``application['config']['CONFIG_SUIT_MPI_APP_LOCAL_1_VENDOR_NAME']``
```suggestion
* Get the vendor name by using ``application['config']['CONFIG_SUIT_MPI_APP_LOCAL_1_VENDOR_NAME']``
```

2024-10-17 09:53 UTC, maciejpietras requested changes
Small typos

2024-10-18 10:29 UTC, ahasztag commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
> +Nordic Semiconductor provides a :ref:`Software Update Internet of Things (SUIT) sample <nrf54h_suit_sample>` which uses predefined configurations in the build system.
Fixed

2024-10-18 10:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17928
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-18 14:24 UTC, tomchy approved these changes

2024-10-21 06:22 UTC, adsz-nordic approved these changes

2024-10-23 09:01 UTC, ahasztag commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
> +* Gey thr vendor name by using ``application['config']['CONFIG_SUIT_MPI_APP_LOCAL_1_VENDOR_NAME']``
Fixed

2024-10-23 09:47 UTC, maciejpietras approved these changes

2024-10-23 09:47 UTC, FrancescoSer approved these changes

2024-10-23 09:53 UTC, merged