doc: SUIT How to fetch payloads guide fixes for 2.8.0
nrfconnect/sdk-nrf pull request #17933
Opened 2024-10-16 13:22 UTC by ahasztag

This commit updates this part of the documentation taking into account changes for 2.8.0 release

2024-10-16 13:24 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [62cd3fa316dbf609e56e485dc3308d05e350a53e](https://github.com/nrfconnect/sdk-nrf/pull/17933/commits/62cd3fa316dbf609e56e485dc3308d05e350a53e)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [62cd3fa316dbf609e56e485dc3308d05e350a53e](https://github.com/nrfconnect/sdk-nrf/pull/17933/commits/62cd3fa316dbf609e56e485dc3308d05e350a53e)
> merge base: [6e57c1dda250287069d720eafc6d5923274314ce](https://github.com/nrfconnect/sdk-nrf/commit/6e57c1dda250287069d720eafc6d5923274314ce)
> target head (main): [d081c4006bb3b42c58f937800454cf47e7b6620b](https://github.com/nrfconnect/sdk-nrf/commit/d081c4006bb3b42c58f937800454cf47e7b6620b)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/6e57c1dda250287069d720eafc6d5923274314ce..62cd3fa316dbf609e56e485dc3308d05e350a53e)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
doc
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── device_guides
│  │  │  │  ├── working_with_nrf
│  │  │  │  │  ├── nrf54h
│  │  │  │  │  │  │ ug_nrf54h20_suit_fetch.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-16 14:28 UTC, jnsgsr approved these changes

2024-10-17 09:21 UTC, FrancescoSer requested changes

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
>  In the Software Updates for Internet of Things (SUIT), it is possible for a device to obtain a new firmware in two ways:
```suggestion
In the Software Updates for Internet of Things (SUIT), a device can obtain new firmware in two ways:
```

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
> +1. The push model - where all necessary candidate images are uploaded to the device along with the envelope before triggering the envelope processing.
```suggestion
1. Using the push model - where all necessary candidate images are uploaded to the device along with the envelope before triggering the envelope processing.
```

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
> +#. The fetch model - where not all of the required payloads are uploaded to the device before triggering the envelope processing.
```suggestion
#. Using the fetch model - where not all the required payloads are uploaded to the device before triggering the envelope processing.
```

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
> +In both models the SUIT envelope must be stored in a continuous memory region in the MCU's non-volatile storage.
```suggestion
In both models, the SUIT envelope must be stored in a continuous memory region in the MCU's non-volatile storage.
```

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
>  Some or all candidate images can be stored in separate memory regions from the envelope, or on a completely different storage device altogether.
```suggestion
Some or all candidate images can be stored either in separate memory regions from the envelope or on a completely different storage device.
```

2024-10-17 09:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
> +In the fetch model, the device can fetch the candidate images after the envelope processing has started.
```suggestion
In the push model, all candidate images must be uploaded to the device before the envelope processing starts.
In the fetch model, the device can fetch the candidate images after the envelope processing has started.
```

2024-10-17 14:01 UTC, maciejpietras approved these changes

2024-10-18 10:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-17933
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-18 14:25 UTC, tomchy approved these changes

2024-10-21 06:12 UTC, adsz-nordic approved these changes

2024-10-23 09:47 UTC, FrancescoSer approved these changes

2024-10-23 09:53 UTC, merged