Nrfx 6388 assembly mgmt west build
nrfconnect/sdk-nrf pull request #18018
Opened 2024-10-18 16:48 UTC by magp-nordic

Add two new CMake targets: `asm_check` and `asm_update`.

`asm_check` will check if content of the already existing ASM file and the new generated by `asm_gen` are the same. If they are the same, the newly generated is removed. If they are different, a warning is printed to update ASM file, if the new one should be included in build.

`asm_update` will replace the already existing ASM file with the new one generated by `asm_gen`. If the new ASM file does not exist, a warning is printed.

Based on #17638

It's still a work in progress.

2024-10-18 16:50 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-10-18 17:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18018
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-23 11:37 UTC, magp-nordic commented
@nrfconnect/ncs-co-build-system @nrfconnect/ncs-code-owners @nrfconnect/ncs-ll-ursus please, review, PR is already rebased on main

2024-10-23 14:01 UTC, masz-nordic commented on cmake/sdp.cmake
> +  set(asm_check_msg "Updating ASM files for Hard Real Time.")
`asm_update_msg`

2024-10-23 14:13 UTC, masz-nordic approved these changes

2024-10-23 14:27 UTC, jaz1-nordic approved these changes

2024-10-23 21:23 UTC, tejlmand commented
please rebase against main, `hrt.s` is missing in this PR (exists on main), which causes the following warning to be printed on each build:
```
[1/2] Running utility command for asm_gen
File hrt-temp.s has been cleaned of comments.
[2/2] Checking if ASM files for Hard Real Time have changed.
CMake Warning at /projects/github/review/nrf/cmake/sdp_asm_check.cmake:19 (message):
  hrt.s ASM file content has changed.  If you want to include the new ASM in
  build, please run `ninja asm_update` in FLPR build directory and build
  again
Call Stack (most recent call first):
  /projects/github/review/nrf/cmake/sdp_asm_check.cmake:29 (asm_check)
```

2024-10-23 22:26 UTC, tejlmand requested changes

2024-10-23 22:26 UTC, tejlmand commented on cmake/sdp.cmake
> +    COMMAND_EXPAND_LISTS
this does not work with lists.

First thing is that `;` will be replaced with `<space>`, thus resulting in: `-D hrt_srcs=foo.c bar.c`, and not `-D hrt_srcs="foo.c;bar.c"`.

To fix this, then first `COMMAND_EXPAND_LISTS` must be removed.
Secondly, `;` must be replaced by the `$<SEMICOLON>` generator expression.
and finally, the argument list must be quoted using `"`.

2024-10-23 22:26 UTC, tejlmand commented on applications/sdp/gpio/CMakeLists.txt
> +sdp_assembly_update("${CMAKE_SOURCE_DIR}/src/hrt/hrt.c")
First, this call is misleading / bad naming.

It gives the impression that the newly generated assembly file will actually be updated, which is not the case.
This call will only create a build target which can be called by the user to update the assembly files.

Another problem with the approach is that all files will be updated, and not only those which differs.
Or the user cannot choose to update only a single file.

This is not a big issue when only a single file is in use, but will become a problem in future.

For now, please improve the naming.
For future, please create a ticket to addre

2024-10-23 22:26 UTC, tejlmand commented on cmake/sdp.cmake
> +  if(TARGET asm_update)
A common naming convention for such targets is `install-<something>`, not update, so perhaps: `install-sdp-asm` / `install-hrt-asm` are better names.

2024-10-23 22:26 UTC, tejlmand commented on cmake/sdp.cmake
> +    COMMAND ${CMAKE_COMMAND} -D hrt_srcs=${hrt_srcs} -P ${ZEPHYR_NRF_MODULE_DIR}/cmake/sdp_asm_update.cmake
see other comment regarding this code not working with lists.

2024-10-24 09:28 UTC, magp-nordic commented on cmake/sdp_asm_check.cmake
Created ticket: https://nordicsemi.atlassian.net/browse/NRFX-6658

2024-10-24 11:08 UTC, magp-nordic commented on cmake/sdp.cmake
> +  )
@tejlmand is this something that can also be fixed later, after NCS release? I think this is just a minor issue, and I cannot find a solution for it. Unless you have some quick fix in mind.

2024-10-24 15:10 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zdebug[nrf52840dongle/nrf52840]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52840dongle/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_4llpmconn[nrf52840dongle/nrf52840]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_4llpmconn&var-testcase=none&var-arch=arm&var-platform=nrf52840dongle/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf5340dk/nrf5340/cpuapp]***: ***RAM*** size  ***increased by 1208[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf5340dk/nrf5340/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52820dongle/nrf52820]***: ***RAM*** size  ***increased by 1400[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52820dongle/nrf52820) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf52833dk/nrf52820]***: ***RAM*** size  ***increased by 1328[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf52833dk/nrf52820) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 948[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 4672[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug.usb_next[nrf52840dongle/nrf52840]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=usb_next&var-arch=arm&var-platform=nrf52840dongle/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_dongle.usb_next[nrf52840dk/nrf52840]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_dongle&var-testcase=usb_next&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_nrf21540ek_multicore[nrf5340dk/nrf5340/cpuapp]***: ***RAM*** size  ***increased by 1208[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_nrf21540ek_multicore&var-testcase=none&var-arch=arm&var-platform=nrf5340dk/nrf5340/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf5340dk/nrf5340/cpuapp]***: ***RAM*** size  ***increased by 1208[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf5340dk/nrf5340/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52833dk/nrf52820]***: ***RAM*** size  ***increased by 1400[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52833dk/nrf52820) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug.uart[nrf54h20dk/nrf54h20/cpuapp]***: ***RAM*** size  ***increased by 1008[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=uart&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug.uart[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 6440[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=uart&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52833dk/nrf52833]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52833dk/nrf52833) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug[nrf52833dongle/nrf52833]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug&var-testcase=none&var-arch=arm&var-platform=nrf52833dongle/nrf52833) (cc: @MarekPieta)
***applications.nrf_desktop.zdebug_dongle[nrf52840dk/nrf52840]***: ***RAM*** size  ***increased by 1272[B]*** in comparison to the ***main[cbf1d39c]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zdebug_dongle&var-testcase=none&var-arch=arm&var-platform=nrf52840dk/nrf52840) (cc: @MarekPieta)
***applications.nrf_desktop.zrelease[nrf52820dongle/nrf52820]** [...]

2024-10-25 13:37 UTC, tejlmand approved these changes
approved, as there are issues to track followup work

2024-10-25 13:40 UTC, merged

2024-10-25 14:01 UTC, magp-nordic commented on cmake/sdp.cmake
> +  )
Created ticket: https://nordicsemi.atlassian.net/browse/NRFX-6664