applications: nrf_desktop: Imply CONFIG_BT_CONN_TX_NOTIFY_WQ
nrfconnect/sdk-nrf pull request #18017
Opened 2024-10-18 14:15 UTC by MarekPieta

Change conditionally implies CONFIG_BT_CONN_TX_NOTIFY_WQ to workaround the MPSL flash synchronization known issue.

Jira: NCSDK-29354

2024-10-18 14:15 UTC, MarekPieta commented
Marking as DNM, https://github.com/nrfconnect/sdk-nrf/pull/17885 must be merged first.

2024-10-18 14:17 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [655f301b9ecd1ca775c9b2097762d8c70be7f65d](https://github.com/nrfconnect/sdk-nrf/pull/18017/commits/655f301b9ecd1ca775c9b2097762d8c70be7f65d)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [655f301b9ecd1ca775c9b2097762d8c70be7f65d](https://github.com/nrfconnect/sdk-nrf/pull/18017/commits/655f301b9ecd1ca775c9b2097762d8c70be7f65d)
> merge base: [378219e59b48d1561a2049ca0653d5785c8520c6](https://github.com/nrfconnect/sdk-nrf/commit/378219e59b48d1561a2049ca0653d5785c8520c6)
> target head (main): [378219e59b48d1561a2049ca0653d5785c8520c6](https://github.com/nrfconnect/sdk-nrf/commit/378219e59b48d1561a2049ca0653d5785c8520c6)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/378219e59b48d1561a2049ca0653d5785c8520c6..655f301b9ecd1ca775c9b2097762d8c70be7f65d)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
applications
│  ├── nrf_desktop
│  │  │ Kconfig.ble
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-18 14:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18017
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-21 07:35 UTC, nordicjm approved these changes

2024-10-21 08:13 UTC, pdunaj approved these changes

2024-10-21 14:42 UTC, mkapala-nordic approved these changes

2024-10-22 08:04 UTC, peknis requested changes

2024-10-22 08:04 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +    This is done to workaround timeout in MPSL flash synchronization (``NCSDK-29354`` known issue).
```suggestion
  * Bluetooth connectivity support (:ref:`CONFIG_DESKTOP_BT <config_desktop_app_options>`) implies using a separate workqueue for connection TX notify processing (:kconfig:option:`CONFIG_BT_CONN_TX_NOTIFY_WQ`) if MPSL is used for synchronization between the flash memory driver and radio (:kconfig:option:`CONFIG_SOC_FLASH_NRF_RADIO_SYNC_MPSL`).
    This is done to work around the timeout in MPSL flash synchronization (``NCSDK-29354`` known issue).
```

2024-10-22 09:30 UTC, peknis approved these changes

2024-10-22 10:13 UTC, merged