nRF Desktop: memory alignments for nRF54L15 DK configurations
nrfconnect/sdk-nrf pull request #18042
Opened 2024-10-21 12:15 UTC by kapi-no

2024-10-21 12:22 UTC, richabp requested changes

2024-10-21 12:22 UTC, richabp commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The partition memory configurations for the for the :ref:`zephyr:nrf54l15dk_nrf54l15` board to optimize size of the MCUboot bootloader partition.
```suggestion
  * The MCUboot image configurations for the :ref:`zephyr:nrf54l15dk_nrf54l15` board to enable Link Time Optimization (LTO) (see the :kconfig:option:`CONFIG_LTO` Kconfig option) and reduce the memory footprint of the bootloader.
  * The partition memory configurations for the :ref:`zephyr:nrf54l15dk_nrf54l15` board to optimize the size of the MCUboot bootloader partition.
```

2024-10-21 13:59 UTC, alstrzebonski requested changes

2024-10-21 13:59 UTC, alstrzebonski commented on applications/nrf_desktop/configuration/nrf54l15dk_nrf54l15_cpuapp/pm_static_keyboard.yml
> +  size: 0xb9000
`0xba000` The size should be increased by 0x2000.

2024-10-21 13:59 UTC, alstrzebonski commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * The partition memory configurations for the for the :ref:`zephyr:nrf54l15dk_nrf54l15` board to optimize size of the MCUboot bootloader partition.
`for the` is duplicated

2024-10-22 06:15 UTC, MarekPieta approved these changes

2024-10-22 07:01 UTC, richabp approved these changes

2024-10-22 07:46 UTC, alstrzebonski approved these changes

2024-10-22 07:51 UTC, merged