nrf_compress: Fix ARM thumb filter cross-chunk issue
nrfconnect/sdk-nrf pull request #18075
Opened 2024-10-22 07:35 UTC by nordicjm

Fixes an issue with the ARM thumb filter when an instruction
    crosses two chunks of data by storing bytes from the first for
    use in the second, this results in the output of the first run
    being less than the input data size and more than the input data
    size for the second run

2024-10-22 07:36 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| mcuboot | https://github.com/nrfconnect/sdk-mcuboot/commit/29646aceff168d3fce89042d7da76e27795e2f45 (main) | https://github.com/nrfconnect/sdk-mcuboot/pull/353 | [nrfconnect/sdk-mcuboot#353/files](https://github.com/nrfconnect/sdk-mcuboot/pull/353/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-10-22 07:39 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [ed1204925b9d1e5816b4459713fdfe0fbc1ce9cb](https://github.com/nrfconnect/sdk-nrf/pull/18075/commits/ed1204925b9d1e5816b4459713fdfe0fbc1ce9cb)
mcuboot: PR head: [690c58ee00fb9752163584f35ad8c853b7f05f32](https://github.com/nrfconnect/sdk-mcuboot/pull/353/commits/690c58ee00fb9752163584f35ad8c853b7f05f32)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [ed1204925b9d1e5816b4459713fdfe0fbc1ce9cb](https://github.com/nrfconnect/sdk-nrf/pull/18075/commits/ed1204925b9d1e5816b4459713fdfe0fbc1ce9cb)
> merge base: [958275302d1c6c391f46deb363e87b3c35f2e3d0](https://github.com/nrfconnect/sdk-nrf/commit/958275302d1c6c391f46deb363e87b3c35f2e3d0)
> target head (main): [958275302d1c6c391f46deb363e87b3c35f2e3d0](https://github.com/nrfconnect/sdk-nrf/commit/958275302d1c6c391f46deb363e87b3c35f2e3d0)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/958275302d1c6c391f46deb363e87b3c35f2e3d0..ed1204925b9d1e5816b4459713fdfe0fbc1ce9cb)

mcuboot:
> PR head: [690c58ee00fb9752163584f35ad8c853b7f05f32](https://github.com/nrfconnect/sdk-mcuboot/pull/353/commits/690c58ee00fb9752163584f35ad8c853b7f05f32)
> merge base: [29646aceff168d3fce89042d7da76e27795e2f45](https://github.com/nrfconnect/sdk-mcuboot/commit/29646aceff168d3fce89042d7da76e27795e2f45)
> target head (main): [29646aceff168d3fce89042d7da76e27795e2f45](https://github.com/nrfconnect/sdk-mcuboot/commit/29646aceff168d3fce89042d7da76e27795e2f45)
> [Diff](https://github.com/nrfconnect/sdk-mcuboot/compare/29646aceff168d3fce89042d7da76e27795e2f45..690c58ee00fb9752163584f35ad8c853b7f05f32)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (5)</summary>

```
bootloader
│  ├── mcuboot
│  │  ├── boot
│  │  │  ├── zephyr
│  │  │  │  │ decompression.c
subsys
│  ├── nrf_compress
│  │  ├── lzma
│  │  │  ├── armthumb.c
│  │  │  │ armthumb.h
│  │  ├── src
│  │  │  │ arm_thumb.c
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-sdk-mcuboot

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-22 07:51 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18075
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-22 15:03 UTC, de-nordic approved these changes

2024-10-23 05:12 UTC, nvlsianpu requested changes
One test is failing: `nrf/tests/subsys/nrf_compress/decompression/arm_thumb/src/main.c`

2024-10-23 07:46 UTC, nordicjm commented
> One test is failing: `nrf/tests/subsys/nrf_compress/decompression/arm_thumb/src/main.c`

Fixed

2024-10-24 06:31 UTC, nordicjm commented
Including as part of https://github.com/nrfconnect/sdk-nrf/pull/17567

2024-10-24 06:31 UTC, closed without merging