samples: matter: Created configuration with LEDs disabled
nrfconnect/sdk-nrf pull request #18080
Opened 2024-10-22 09:47 UTC by kkasperczyk-no

Added Kconfig that allows to disable LEDs initialization and created a configuration that uses it for nRF54L15. This is required for the power measurement purposes.

2024-10-22 09:49 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [26bfdf270c05599e7ae5e45a41459377a9455f13](https://github.com/nrfconnect/sdk-nrf/pull/18080/commits/26bfdf270c05599e7ae5e45a41459377a9455f13)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [26bfdf270c05599e7ae5e45a41459377a9455f13](https://github.com/nrfconnect/sdk-nrf/pull/18080/commits/26bfdf270c05599e7ae5e45a41459377a9455f13)
> merge base: [6d40ee41124cec57a9d9e6e02c51526d99ddbd28](https://github.com/nrfconnect/sdk-nrf/commit/6d40ee41124cec57a9d9e6e02c51526d99ddbd28)
> target head (main): [63130153b694e33577eb2b83f8fab2ede0f336bc](https://github.com/nrfconnect/sdk-nrf/commit/63130153b694e33577eb2b83f8fab2ede0f336bc)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/6d40ee41124cec57a9d9e6e02c51526d99ddbd28..26bfdf270c05599e7ae5e45a41459377a9455f13)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (6)</summary>

```
doc
│  ├── nrf
│  │  ├── protocols
│  │  │  ├── matter
│  │  │  │  ├── getting_started
│  │  │  │  │  │ low_power_configuration.rst
samples
│  ├── matter
│  │  ├── common
│  │  │  ├── src
│  │  │  │  ├── Kconfig
│  │  │  │  ├── board
│  │  │  │  │  │ board.cpp
│  │  ├── lock
│  │  │  │ sample.yaml
│  │  ├── smoke_co_alarm
│  │  │  │ sample.yaml
│  │  ├── window_covering
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-22 10:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18080
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-22 10:18 UTC, ArekBalysNordic approved these changes
Just documentation suggestions, so approving.

2024-10-22 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +When performing the power measurements on variouis development kits, the LEDs can be included in the measurement circuit or not:
```suggestion
When performing power measurements on various development kits, the LEDs can either be included in the measurement circuit or not:
```

2024-10-22 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +* For the nRF52840 DK and nRF5340 DK the LEDs are excluded from the measurement circuit, so they can be enabled for the low power configuration and it is not going to impact the measurement results.
```suggestion
* For the nRF52840 DK and nRF5340 DK, the LEDs are excluded from the measurement circuit, so they can be enabled for low power configuration without impacting the measurement results.
```

2024-10-22 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +* For the nRF54L15 DK, the MOSFET transistors controlling the LEDs are included in the measurement circuit, what results in increased measurement result by an additional, small leakage current, appea
```suggestion
* For the nRF54L15 DK, the MOSFET transistors controlling the LEDs are included in the measurement circuit, which results in increased measurement results due to a small leakage current if the LED is turned on.
```

2024-10-22 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +  To measure the current consumption of the nRF54L15 SoC and not include development kit components, such as LEDs, it is recommended to disable them.
```suggestion
  To measure the current consumption of the nRF54L15 SoC without including development kit components, such as LEDs, it is recommended to disable them.
```

2024-10-22 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +To disable LEDs from the Matter samples and applications, set the :kconfig:option:`CONFIG_NCS_SAMPLE_MATTER_LEDS` Kconfig option to ``n``.
```suggestion
To disable LEDs in the Matter samples and applications, set the :kconfig:option:`CONFIG_NCS_SAMPLE_MATTER_LEDS` Kconfig option to ``n``.
```

2024-10-22 10:47 UTC, maciejbaczmanski approved these changes

2024-10-22 10:54 UTC, wiba-nordic requested changes
Could also add a changelog entry noting that the Kconfig option was added to all Matter samples.

2024-10-22 10:54 UTC, wiba-nordic commented on doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
> +* For the nRF54L15 DK, the MOSFET transistors controlling the LEDs are included in the measurement circuit, what results in increased measurement result by an additional, small leakage current, appea
```suggestion
* For the nRF54L15 DK, the MOSFET transistors controlling the LEDs are included in the measurement circuit.
  This results in measurement results being increased by an additional, small leakage current that appears if an LED is turned on.
```

2024-10-22 12:02 UTC, kkasperczyk-no commented
> Could also add a changelog entry noting that the Kconfig option was added to all Matter samples.

Sure, applied.

2024-10-22 12:03 UTC, wiba-nordic approved these changes

2024-10-22 12:04 UTC, doublemis1 approved these changes

2024-10-22 12:30 UTC, umapraseeda approved these changes

2024-10-23 07:15 UTC, nordicjm approved these changes

2024-10-23 07:15 UTC, merged