samples: matter: Fixed few configs and docs
nrfconnect/sdk-nrf pull request #18160
Opened 2024-10-24 10:28 UTC by kkasperczyk-no

Going through the configs and docs lead to the introducing of few fixes:

* Removed enabling DAC migration, as it triggered warning for Wi-Fi that does not support PSA
* Fixed nrf70eb mentions in docs
* Added info about network commissioning cluster to the certification page
* Added experimental for few bridge configurations

2024-10-24 10:31 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [5f9b464b52f04b3348b1eb1e086f3e94c1e7e203](https://github.com/nrfconnect/sdk-nrf/pull/18160/commits/5f9b464b52f04b3348b1eb1e086f3e94c1e7e203)
matter: PR head: [ab6cd85b29527b856dc02e44c1380679ba8fa20b](https://github.com/nrfconnect/sdk-connectedhomeip/pull/500/commits/ab6cd85b29527b856dc02e44c1380679ba8fa20b)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [5f9b464b52f04b3348b1eb1e086f3e94c1e7e203](https://github.com/nrfconnect/sdk-nrf/pull/18160/commits/5f9b464b52f04b3348b1eb1e086f3e94c1e7e203)
> merge base: [cbcfa64e6d3b6db9618784712c5595008e977502](https://github.com/nrfconnect/sdk-nrf/commit/cbcfa64e6d3b6db9618784712c5595008e977502)
> target head (main): [81e9846e24a2aad9ca20d35df267cfbe4c1b3260](https://github.com/nrfconnect/sdk-nrf/commit/81e9846e24a2aad9ca20d35df267cfbe4c1b3260)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/cbcfa64e6d3b6db9618784712c5595008e977502..5f9b464b52f04b3348b1eb1e086f3e94c1e7e203)

matter:
> PR head: [ab6cd85b29527b856dc02e44c1380679ba8fa20b](https://github.com/nrfconnect/sdk-connectedhomeip/pull/500/commits/ab6cd85b29527b856dc02e44c1380679ba8fa20b)
> merge base: [5580536ab0013db53ef7e0607638e1943400e5ae](https://github.com/nrfconnect/sdk-connectedhomeip/commit/5580536ab0013db53ef7e0607638e1943400e5ae)
> target head (master): [5580536ab0013db53ef7e0607638e1943400e5ae](https://github.com/nrfconnect/sdk-connectedhomeip/commit/5580536ab0013db53ef7e0607638e1943400e5ae)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/5580536ab0013db53ef7e0607638e1943400e5ae..ab6cd85b29527b856dc02e44c1380679ba8fa20b)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (31)</summary>

```
applications
│  ├── matter_bridge
│  │  ├── Kconfig
│  │  ├── doc
│  │  │  ├── adding_ble_bridged_device_service.rst
│  │  │  │ matter_bridge_description.rst
│  │  ├── prj.conf
│  │  │ prj_release.conf
│  ├── matter_weather_station
│  │  ├── prj.conf
│  │  │ prj_release.conf
doc
│  ├── nrf
│  │  ├── protocols
│  │  │  ├── matter
│  │  │  │  ├── end_product
│  │  │  │  │  │ certification.rst
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── config
│  │  │  │  ├── nrfconnect
│  │  │  │  │  ├── chip-module
│  │  │  │  │  │  │ Kconfig.defaults
samples
│  ├── matter
│  │  ├── light_bulb
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  │ prj_release.conf
│  │  ├── light_switch
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  │ prj_release.conf
│  │  ├── lock
│  │  │  ├── README.rst
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  ├── prj_release.conf
│  │  │  │ prj_thread_wifi_switched.conf
│  │  ├── template
│  │  │  ├── README.rst
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  │ prj_release.conf
│  │  ├── thermostat
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  │ prj_release.conf
│  │  ├── window_covering
│  │  │  ├── boards
│  │  │  │  │ nrf54l15dk_nrf54l15_cpuapp_ns.conf
│  │  │  ├── prj.conf
│  │  │  │ prj_release.conf
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-24 10:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18160
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-24 11:02 UTC, wiba-nordic requested changes

2024-10-24 11:02 UTC, wiba-nordic commented on doc/nrf/protocols/matter/end_product/certification.rst
> +  The Network Commissioning cluster has also attributes for both Thread and Wi-Fi protocols enabled.
```suggestion
  For example, the default configurations for the samples use both Thread Network Diagnostics and Wi-Fi Network Diagnostics clusters, and the Network Commissioning cluster has attributes for both Thread and Wi-Fi protocols enabled.
```

2024-10-24 11:34 UTC, wiba-nordic approved these changes

2024-10-24 11:36 UTC, ArekBalysNordic approved these changes

2024-10-25 13:06 UTC, nordicjm requested changes

2024-10-25 13:06 UTC, nordicjm commented on applications/matter_bridge/Kconfig
> +	select EXPERIMENTAL if NET_L2_OPENTHREAD || BRIDGE_SMART_PLUG_SUPPORT
```suggestion
	select EXPERIMENTAL
```

2024-10-28 10:32 UTC, nordicjm approved these changes

2024-10-28 10:37 UTC, merged