amples: bluetooth: central_smp_client: Add support for nRF54L15DK
nrfconnect/sdk-nrf pull request #18217
Opened 2024-10-25 13:25 UTC by maje-emb

Added nRF54L15DK support in the central_smp_client sample.

2024-10-25 13:27 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [a4fd21dd48c7d4b5fd5f3c24f91d73b320ad7656](https://github.com/nrfconnect/sdk-nrf/pull/18217/commits/a4fd21dd48c7d4b5fd5f3c24f91d73b320ad7656)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [a4fd21dd48c7d4b5fd5f3c24f91d73b320ad7656](https://github.com/nrfconnect/sdk-nrf/pull/18217/commits/a4fd21dd48c7d4b5fd5f3c24f91d73b320ad7656)
> merge base: [c12de605204a9eb9371bd1b2316c1e03f18c1fd3](https://github.com/nrfconnect/sdk-nrf/commit/c12de605204a9eb9371bd1b2316c1e03f18c1fd3)
> target head (main): [f94bd7be086965ed813e98f0f8740518c86407df](https://github.com/nrfconnect/sdk-nrf/commit/f94bd7be086965ed813e98f0f8740518c86407df)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/c12de605204a9eb9371bd1b2316c1e03f18c1fd3..a4fd21dd48c7d4b5fd5f3c24f91d73b320ad7656)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
samples
│  ├── bluetooth
│  │  ├── central_smp_client
│  │  │  ├── README.rst
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-25 13:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18217
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-28 06:23 UTC, peknis requested changes

2024-10-28 06:23 UTC, peknis commented on samples/bluetooth/central_smp_client/README.rst
> +         When you have built the :zephyr:code-sample:`smp-svr`, call the following command to program it to the development kit::
```suggestion
         When you have built the sample, run the following command to program it to the development kit::
```

2024-10-28 06:23 UTC, peknis commented on samples/bluetooth/central_smp_client/README.rst
> +      #. Disconnect the devices by, for example, pressing the Reset button on the Central.
```suggestion
      #. Press the Reset button on the Central to disconnect the devices.
```

2024-10-28 06:23 UTC, peknis commented on samples/bluetooth/central_smp_client/README.rst
> +      #. Disconnect the devices by, for example, pressing the Reset button on the Central.
```suggestion
      #. Press the Reset button on the Central to disconnect the devices.
```

2024-10-28 07:13 UTC, wiba-nordic approved these changes

2024-10-28 08:36 UTC, peknis approved these changes

2024-10-28 08:43 UTC, dchat-nordic approved these changes

2024-10-28 08:45 UTC, divipillai approved these changes

2024-10-28 12:17 UTC, merged