Sw maturity level bt
nrfconnect/sdk-nrf pull request #18278
Opened 2024-10-28 12:54 UTC by yuxCai

2024-10-28 12:57 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [e6ed0b253296d28b08a23794fcf911e29288f821](https://github.com/nrfconnect/sdk-nrf/pull/18278/commits/e6ed0b253296d28b08a23794fcf911e29288f821)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [e6ed0b253296d28b08a23794fcf911e29288f821](https://github.com/nrfconnect/sdk-nrf/pull/18278/commits/e6ed0b253296d28b08a23794fcf911e29288f821)
> merge base: [11645184a54d02921bb0691a57e1e86c141393da](https://github.com/nrfconnect/sdk-nrf/commit/11645184a54d02921bb0691a57e1e86c141393da)
> target head (main): [ae9c56ca2bfce8f04819ec382e64b02a737e7155](https://github.com/nrfconnect/sdk-nrf/commit/ae9c56ca2bfce8f04819ec382e64b02a737e7155)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/11645184a54d02921bb0691a57e1e86c141393da..e6ed0b253296d28b08a23794fcf911e29288f821)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  │ software_maturity.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-10-28 13:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18278
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-10-28 14:20 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +        - --
52820 should support the scanner/central role

2024-10-28 14:22 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +        - --
all 52 devices should support advertising extensions

2024-10-29 15:57 UTC, divipillai approved these changes

2024-10-31 14:51 UTC, yuxCai commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +The following table indicates the software maturity levels of the support for each proprietary Bluetooth feature:
I will keep a separate table for the proprietary features before we know how to separate/group them in the same table

2024-11-01 12:36 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +      * - **Coded PHY (Long Range)**
for the 52 series, the following devices support Coded:
- 52811
- 52820
- 52833
- 52840

2024-11-01 12:37 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +      * - **Direction Finding**\ :sup:`3`
did you double-check that direction finding is not supported on 54?

2024-11-01 12:41 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +      * - **Direction Finding**\ :sup:`3`
for the 52 series, the following devices support DFE:
- 52811
- 52820
- 52833

2024-11-01 12:42 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +The following table indicates the software maturity levels of the support for each proprietary Bluetooth feature:
For the proprietary features, should we link them here to some description?
I think this is a good starting point, but we could probably mention additional proprietary features in a second step.

2024-11-01 12:43 UTC, Tschet1 requested changes
The table needs to be updated.

2024-11-01 13:22 UTC, Tschet1 commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +The following table indicates the software maturity levels of the support for each proprietary Bluetooth feature:
not sure. But we can do that later, I think.

2024-11-01 14:02 UTC, Tschet1 approved these changes

2024-11-01 14:41 UTC, merged