doc: misc updates
nrfconnect/sdk-nrf pull request #18356
Opened 2024-10-29 21:20 UTC by annwoj

small fixes

2024-10-29 21:21 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-10-30 13:50 UTC, greg-fer approved these changes

2024-10-31 07:14 UTC, nordicjm requested changes

2024-10-31 07:14 UTC, nordicjm commented on doc/nrf/app_dev/board_support/board_names.rst
> +For example, the board target ``nrf54l15dk@nrf54l15/cpuapp`` can be read as made of the following elements:
-@+/

2024-10-31 07:36 UTC, annwoj commented on doc/nrf/app_dev/board_support/board_names.rst
> +For example, the board target ``nrf54l15dk@nrf54l15/cpuapp`` can be read as made of the following elements:
fixed

2024-10-31 07:39 UTC, nordicjm approved these changes

2024-10-31 08:00 UTC, umapraseeda approved these changes

2024-10-31 08:29 UTC, rlubos commented
@annwoj Should this be backported or is there no label intentionally?

2024-10-31 08:34 UTC, annwoj commented
> @annwoj Should this be backported or is there no label intentionally?

Added label here as well

2024-10-31 08:50 UTC, merged