doc: fix maturity tables for crypto
nrfconnect/sdk-nrf pull request #18438
Opened 2024-10-31 12:47 UTC by mia-ko

Updates to Crypto API maturity table

2024-10-31 12:48 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-10-31 13:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18438
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-04 12:46 UTC, endre-nordic approved these changes

2024-11-04 13:17 UTC, melwee01 approved these changes

2024-11-04 13:24 UTC, divipillai requested changes

2024-11-04 13:24 UTC, divipillai commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +       - Experimental [1]_
```suggestion
       - Experimental\ :sup:`1`
```

2024-11-04 13:24 UTC, divipillai commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +       - Experimental [1]_
We add this a sup not as a footnote. https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/releases_and_maturity/software_maturity.html#wi-fi_feature_support

2024-11-04 13:24 UTC, divipillai commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +.. [1] The attestation service is not supported.
```suggestion
| [1]: The attestation service is not supported.
```

2024-11-05 09:04 UTC, divipillai approved these changes

2024-11-05 09:04 UTC, merged