snippets: add nrf9280 sw devbrd pin remap snippet
nrfconnect/sdk-nrf pull request #18450
Opened 2024-10-31 14:37 UTC by anhmolt

Add snippet for changing pin output of buttons and leds.

2024-10-31 14:38 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [92dd5ecc7f9a62f60ce91988900b29f097e73f5f](https://github.com/nrfconnect/sdk-nrf/pull/18450/commits/92dd5ecc7f9a62f60ce91988900b29f097e73f5f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [92dd5ecc7f9a62f60ce91988900b29f097e73f5f](https://github.com/nrfconnect/sdk-nrf/pull/18450/commits/92dd5ecc7f9a62f60ce91988900b29f097e73f5f)
> merge base: [6507f6301a431fd02aa1f94d6c505786b1112978](https://github.com/nrfconnect/sdk-nrf/commit/6507f6301a431fd02aa1f94d6c505786b1112978)
> target head (main): [6507f6301a431fd02aa1f94d6c505786b1112978](https://github.com/nrfconnect/sdk-nrf/commit/6507f6301a431fd02aa1f94d6c505786b1112978)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/6507f6301a431fd02aa1f94d6c505786b1112978..92dd5ecc7f9a62f60ce91988900b29f097e73f5f)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
snippets
│  ├── nrf9280sw-devbrd-pin-remap
│  │  ├── nrf9280sw-devbrd-pin-remap.overlay
│  │  │ snippet.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-01 08:16 UTC, nordicjm requested changes
codeowner update needed

2024-11-01 08:17 UTC, nordicjm requested changes
snippet has no documentation, don't have a clue what it's used for, and only applies to one board, why does this need to be a snippet?

2024-11-04 15:43 UTC, anhmolt commented
Closing this while exploring the option to extend a board instead.

2024-11-04 15:43 UTC, closed without merging