samples: crypto: update psa_tls sample
nrfconnect/sdk-nrf pull request #18522
Opened 2024-11-04 13:49 UTC by juhaylinen

Move registration of Pre-shared key (PSK) from main.c to secure/non-secure part of the code.

Add openssl commands for PSK connection to README.

2024-11-04 14:00 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [d54b06306cb0e7a2025f9ebf7a2cc1b148b65d8b](https://github.com/nrfconnect/sdk-nrf/pull/18522/commits/d54b06306cb0e7a2025f9ebf7a2cc1b148b65d8b)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [d54b06306cb0e7a2025f9ebf7a2cc1b148b65d8b](https://github.com/nrfconnect/sdk-nrf/pull/18522/commits/d54b06306cb0e7a2025f9ebf7a2cc1b148b65d8b)
> merge base: [ebf1059fe62bb6942718b01910f73008c010130f](https://github.com/nrfconnect/sdk-nrf/commit/ebf1059fe62bb6942718b01910f73008c010130f)
> target head (main): [8729fa975dd0e32f79ded7e9af85002d68c8ed32](https://github.com/nrfconnect/sdk-nrf/commit/8729fa975dd0e32f79ded7e9af85002d68c8ed32)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/ebf1059fe62bb6942718b01910f73008c010130f..d54b06306cb0e7a2025f9ebf7a2cc1b148b65d8b)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (7)</summary>

```
samples
│  ├── crypto
│  │  ├── psa_tls
│  │  │  ├── README.rst
│  │  │  ├── include
│  │  │  │  │ psa_tls_credentials.h
│  │  │  ├── src
│  │  │  │  ├── main.c
│  │  │  │  ├── non-secure
│  │  │  │  │  ├── psa_tls_credentials_client.c
│  │  │  │  │  │ psa_tls_credentials_server.c
│  │  │  │  ├── secure
│  │  │  │  │  ├── psa_tls_credentials_client.c
│  │  │  │  │  │ psa_tls_credentials_server.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-nrf_crypto

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-04 14:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18522
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-05 07:33 UTC, mia-ko approved these changes

2024-11-05 15:29 UTC, frkv requested changes
Will communicate offline on required changes

2024-12-17 00:36 UTC, closed without merging