samples: dect_phy: dect_shell: new startup_cmd and possibility to give AT commands from command prompt
nrfconnect/sdk-nrf pull request #18548
Opened 2024-11-05 08:39 UTC by jhirsi

Added:
- New `startup_cmd` command to store shell commands to be run sequentially after a bootup.
- Possibility to give AT-commands from desh command prompt.. Note: dect nr+ modem firmware has limited support for AT-commands.

2024-11-05 08:43 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [8a6fc809cab9ac0e16635860ff8c0250e1f64b0c](https://github.com/nrfconnect/sdk-nrf/pull/18548/commits/8a6fc809cab9ac0e16635860ff8c0250e1f64b0c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [8a6fc809cab9ac0e16635860ff8c0250e1f64b0c](https://github.com/nrfconnect/sdk-nrf/pull/18548/commits/8a6fc809cab9ac0e16635860ff8c0250e1f64b0c)
> merge base: [4c995152636a5baeed40449dbcca1691374794bb](https://github.com/nrfconnect/sdk-nrf/commit/4c995152636a5baeed40449dbcca1691374794bb)
> target head (main): [4ab6eb80c2fdd437b125b6cea8ecab8e7fd547b7](https://github.com/nrfconnect/sdk-nrf/commit/4ab6eb80c2fdd437b125b6cea8ecab8e7fd547b7)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/4c995152636a5baeed40449dbcca1691374794bb..8a6fc809cab9ac0e16635860ff8c0250e1f64b0c)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (12)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
samples
│  ├── dect
│  │  ├── dect_phy
│  │  │  ├── dect_shell
│  │  │  │  ├── CMakeLists.txt
│  │  │  │  ├── Kconfig
│  │  │  │  ├── README.rst
│  │  │  │  ├── prj.conf
│  │  │  │  ├── src
│  │  │  │  │  ├── main.c
│  │  │  │  │  ├── startup_cmd
│  │  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  │  ├── startup_cmd_ctrl.c
│  │  │  │  │  │  ├── startup_cmd_ctrl.h
│  │  │  │  │  │  ├── startup_cmd_settings.c
│  │  │  │  │  │  ├── startup_cmd_settings.h
│  │  │  │  │  │  │ startup_cmd_shell.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-05 08:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18548
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-05 12:11 UTC, trantanen approved these changes

2024-11-05 13:59 UTC, peknis requested changes

2024-11-05 13:59 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +      New command to store shell commands to be run sequentially after a bootup.
```suggestion
      This command is used to store shell commands to be run sequentially after bootup.
```

2024-11-05 13:59 UTC, peknis commented on samples/dect/dect_phy/dect_shell/README.rst
> +* FT/Beacon device - Set a command to start a cluster beacon at 5 seconds after a bootup:
```suggestion
* FT/Beacon device - Set a command to start a cluster beacon five seconds after bootup:
```

2024-11-05 13:59 UTC, peknis commented on samples/dect/dect_phy/dect_shell/prj.conf
> +#Note that NR+ modem FW has limited set of AT commands supported
```suggestion
# Note that NR+ modem FW supports a limited set of AT commands
```

2024-11-05 13:59 UTC, peknis commented on samples/dect/dect_phy/dect_shell/README.rst
> +You can use the ``startup_cmd`` command to store shell commands to be run sequentially after a bootup.
```suggestion
You can use the ``startup_cmd`` command to store shell commands to be run sequentially after bootup.
```

2024-11-05 13:59 UTC, peknis commented on samples/dect/dect_phy/dect_shell/README.rst
> +* PT/Client device - Set a command to start scanning for the beacon 60 seconds after a bootup, associate to it, and send RA data to it:
```suggestion
* PT/Client device - Set a command to start scanning for the beacon 60 seconds after bootup, associate to it, and send RA data to it:
```

2024-11-06 06:49 UTC, tokangas approved these changes

2024-11-06 09:25 UTC, merged