doc: Doc fixes for 2.8
nrfconnect/sdk-nrf pull request #18595
Opened 2024-11-05 14:53 UTC by umapraseeda

Doc fixes for 2.8 - release task

2024-11-05 14:53 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-11-05 15:00 UTC, umapraseeda commented on doc/nrf/links.txt
> -
Duplicate entry

2024-11-06 09:58 UTC, umapraseeda commented on doc/nrf/links.txt
> -.. _`nrf9160dk_nrf9160_partition_conf.dts`: https://github.com/nrfconnect/sdk-zephyr/blob/main/boards/arm/nrf9160dk_nrf9160/nrf9160dk_nrf9160_partition_conf.dts
unused entry

2024-11-06 10:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18595
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-06 11:29 UTC, peknis requested changes

2024-11-06 11:29 UTC, peknis commented on doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_qsg.rst
> +After rebuilding you will be able to find the following part in the :file:`./build/DFU/application.yaml` file.
```suggestion
After rebuilding you can find the following part in the :file:`./build/DFU/application.yaml` file.
```

2024-11-06 11:29 UTC, peknis commented on doc/nrf/libraries/dfu/suit_dfu.rst
> +The Software Updates for Internet of Things (SUIT) Device Firmware Upgrade (DFU) library provides functionality to a local domain for orchestrating the update based on the SUIT manifest.
```suggestion
The Software Updates for Internet of Things (SUIT) Device Firmware Upgrade (DFU) library provides functionality to a local domain for managing the update based on the SUIT manifest.
```

2024-11-06 12:05 UTC, b-gent approved these changes

2024-11-06 12:06 UTC, annwoj approved these changes

2024-11-06 12:14 UTC, divipillai approved these changes

2024-11-06 14:03 UTC, richabp approved these changes

2024-11-07 07:10 UTC, wiba-nordic approved these changes

2024-11-07 10:10 UTC, nordicjm approved these changes
Sysbuild/XIP/build parts OK

2024-11-07 12:14 UTC, melwee01 approved these changes

2024-11-07 12:25 UTC, frkv approved these changes
LGTM (TF-M, crypto drivers and and security)

2024-11-07 14:30 UTC, merged