samples: wifi: Optimize network buffer settings for improved throughput
nrfconnect/sdk-nrf pull request #18609
Opened 2024-11-05 18:29 UTC by D-Triveni

Override default 4KB sizes of Tx and Rx data pools to achieve better throughput.

2024-11-05 18:31 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [97d0716e56c077097529e483ac6bc26e3aa6a9cf](https://github.com/nrfconnect/sdk-nrf/pull/18609/commits/97d0716e56c077097529e483ac6bc26e3aa6a9cf)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [97d0716e56c077097529e483ac6bc26e3aa6a9cf](https://github.com/nrfconnect/sdk-nrf/pull/18609/commits/97d0716e56c077097529e483ac6bc26e3aa6a9cf)
> merge base: [771d5ce292c48893a30675179dfa1b0868d6c901](https://github.com/nrfconnect/sdk-nrf/commit/771d5ce292c48893a30675179dfa1b0868d6c901)
> target head (main): [5e74b5b4664336d9023b6f3c70cf8f7127d78ae3](https://github.com/nrfconnect/sdk-nrf/commit/5e74b5b4664336d9023b6f3c70cf8f7127d78ae3)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/771d5ce292c48893a30675179dfa1b0868d6c901..97d0716e56c077097529e483ac6bc26e3aa6a9cf)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (6)</summary>

```
samples
│  ├── wifi
│  │  ├── shell
│  │  │  │ Kconfig
│  │  ├── throughput
│  │  │  ├── overlay-high-performance.conf
│  │  │  ├── overlay-iot-devices.conf
│  │  │  ├── overlay-memory-optimized.conf
│  │  │  ├── overlay-rx-prio.conf
│  │  │  │ overlay-tx-prio.conf
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-sdk-wifi

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-05 18:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18609
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-05 19:56 UTC, krish2718 approved these changes

2024-11-06 02:11 UTC, bama-nordic approved these changes

2024-11-06 09:01 UTC, richabp requested changes
Does it require a Changelog entry?

2024-11-06 09:01 UTC, richabp commented on samples/wifi/shell/Kconfig
> +# nRF54 series targets have less memory
```suggestion
# nRF54 Series targets have less memory
```

2024-11-06 09:56 UTC, D-Triveni commented
> Does it require a Changelog entry?

No.

2024-11-06 11:24 UTC, richabp approved these changes

2024-11-06 13:12 UTC, merged