doc: nrf70: Fix 54 Series shields
nrfconnect/sdk-nrf pull request #18610
Opened 2024-11-05 20:03 UTC by krish2718

The shields usage is now updated.

2024-11-05 20:06 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [23bf9ab17199db3b3bd6594e77e4468d33ca0792](https://github.com/nrfconnect/sdk-nrf/pull/18610/commits/23bf9ab17199db3b3bd6594e77e4468d33ca0792)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [23bf9ab17199db3b3bd6594e77e4468d33ca0792](https://github.com/nrfconnect/sdk-nrf/pull/18610/commits/23bf9ab17199db3b3bd6594e77e4468d33ca0792)
> merge base: [5e74b5b4664336d9023b6f3c70cf8f7127d78ae3](https://github.com/nrfconnect/sdk-nrf/commit/5e74b5b4664336d9023b6f3c70cf8f7127d78ae3)
> target head (main): [5e74b5b4664336d9023b6f3c70cf8f7127d78ae3](https://github.com/nrfconnect/sdk-nrf/commit/5e74b5b4664336d9023b6f3c70cf8f7127d78ae3)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/5e74b5b4664336d9023b6f3c70cf8f7127d78ae3..23bf9ab17199db3b3bd6594e77e4468d33ca0792)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
doc
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── device_guides
│  │  │  │  ├── nrf70
│  │  │  │  │  ├── index.rst
│  │  │  │  │  │ nrf7002eb_dev_guide.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-05 20:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18610
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-06 02:12 UTC, bama-nordic approved these changes

2024-11-06 09:54 UTC, richabp requested changes

2024-11-06 09:54 UTC, richabp commented on doc/nrf/app_dev/device_guides/nrf70/nrf7002eb_dev_guide.rst
> +To build for the nRF7002 EB with the nRF54L15 PDK, use the ``nrf54l15pdk/nrf54l15/cpuapp`` board target with the CMake ``SHIELD`` variable set to ``nrf7002eb_interposer_p1 nrf7002eb``.
Should PDK be changed to  "DK" at all instances for nRFL15 PDK?
```suggestion
To build for the nRF7002 EB with the nRF54L15 DK, use the ``nrf54l15pdk/nrf54l15/cpuapp`` board target with the CMake ``SHIELD`` variable set to ``nrf7002eb_interposer_p1 nrf7002eb``.
```

2024-11-06 09:54 UTC, richabp commented on doc/nrf/app_dev/device_guides/nrf70/index.rst
I think line 80-84 needs an update as follows because we have  a document for DK (instead of PDK) and Quick Start now.

- :ref:`zephyr:nrf54l15dk_nrf54l15`
     - nRF7002 EB
     - PCA20053
     - ``nrf54l15dk/nrf54l15/cpuapp``
     - `Quick Start`_

2024-11-06 11:49 UTC, krish2718 commented on doc/nrf/app_dev/device_guides/nrf70/index.rst
both the comments are unrelated to this PR, I am doing a separate commit to rename PDK->DK.

2024-11-06 13:22 UTC, krga2022 approved these changes

2024-11-06 13:41 UTC, bama-nordic approved these changes

2024-11-06 14:09 UTC, richabp requested changes
Approving with a minor nit.

2024-11-06 14:09 UTC, richabp commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +   | [4]: Only with nrf7002EB and nRF7002EB-interposer
```suggestion
   | [4]: Only with nrf7002 EB and nRF7002 EB-interposer
```

2024-11-06 14:10 UTC, richabp approved these changes

2024-11-06 15:27 UTC, merged