samples: cellular: location: Enable Wi-Fi by default for Thingy91x
nrfconnect/sdk-nrf pull request #18719
Opened 2024-11-07 11:17 UTC by trantanen

Initially location sample had Wi-Fi disabled by default for Thingy91x (PR #14418).
Reverting that decision and aligning with some other apps/samples.

Jira: NCSDK-30108

2024-11-07 11:18 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [b78adb6c39240faf7d5784b8b4c22aa8e4bd0d03](https://github.com/nrfconnect/sdk-nrf/pull/18719/commits/b78adb6c39240faf7d5784b8b4c22aa8e4bd0d03)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [b78adb6c39240faf7d5784b8b4c22aa8e4bd0d03](https://github.com/nrfconnect/sdk-nrf/pull/18719/commits/b78adb6c39240faf7d5784b8b4c22aa8e4bd0d03)
> merge base: [bb63ee6f5e2f06882fdab3f1132213121349e907](https://github.com/nrfconnect/sdk-nrf/commit/bb63ee6f5e2f06882fdab3f1132213121349e907)
> target head (main): [bb63ee6f5e2f06882fdab3f1132213121349e907](https://github.com/nrfconnect/sdk-nrf/commit/bb63ee6f5e2f06882fdab3f1132213121349e907)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/bb63ee6f5e2f06882fdab3f1132213121349e907..b78adb6c39240faf7d5784b8b4c22aa8e4bd0d03)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (5)</summary>

```
samples
│  ├── cellular
│  │  ├── location
│  │  │  ├── Kconfig.sysbuild
│  │  │  ├── README.rst
│  │  │  ├── boards
│  │  │  │  ├── thingy91x_nrf9151_ns.conf
│  │  │  │  │ thingy91x_nrf9151_ns.overlay
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-nrf-iot_positioning

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-proprietary_esb
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-07 11:20 UTC, peknis requested changes

2024-11-07 11:20 UTC, peknis commented on samples/cellular/location/README.rst
> +   Thingy:91 X build has Wi-Fi support enabled by default. You do not need to add any overlays.
```suggestion
   The Thingy:91 X build supports Wi-Fi by default.
   You do not need to add any overlays.
```

2024-11-07 11:28 UTC, simensrostad approved these changes
LGTM

2024-11-07 11:29 UTC, jtguggedal approved these changes

2024-11-07 11:31 UTC, trantanen commented
Added changelog still.

2024-11-07 11:33 UTC, tokangas approved these changes
Approved with one minor nit, you could use the official device name also in the commit message, i.e. "Thingy:91 X".

2024-11-07 11:35 UTC, peknis approved these changes

2024-11-07 11:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18719
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2024-11-11 09:23 UTC, nordicjm approved these changes

2024-11-13 09:40 UTC, jhirsi approved these changes

2024-11-13 11:07 UTC, merged