tests: benchmarks: power_consumption: adc: multicore app for nrf54h20
nrfconnect/sdk-nrf pull request #18826
Opened 2024-11-12 21:06 UTC by nordic-piks

Add code for radio core so that it can be put into sleep and release resources.

2024-11-12 21:08 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [babe31f3a4115c9d7e174e7f66abd4f2cc565f3f](https://github.com/nrfconnect/sdk-nrf/pull/18826/commits/babe31f3a4115c9d7e174e7f66abd4f2cc565f3f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [babe31f3a4115c9d7e174e7f66abd4f2cc565f3f](https://github.com/nrfconnect/sdk-nrf/pull/18826/commits/babe31f3a4115c9d7e174e7f66abd4f2cc565f3f)
> merge base: [c94e86f50a38e200e449bdf2a3f0008037ca4933](https://github.com/nrfconnect/sdk-nrf/commit/c94e86f50a38e200e449bdf2a3f0008037ca4933)
> target head (main): [c94e86f50a38e200e449bdf2a3f0008037ca4933](https://github.com/nrfconnect/sdk-nrf/commit/c94e86f50a38e200e449bdf2a3f0008037ca4933)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/c94e86f50a38e200e449bdf2a3f0008037ca4933..babe31f3a4115c9d7e174e7f66abd4f2cc565f3f)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
tests
│  ├── benchmarks
│  │  ├── power_consumption
│  │  │  ├── adc
│  │  │  │  ├── Kconfig.sysbuild
│  │  │  │  ├── sysbuild.cmake
│  │  │  │  ├── sysbuild
│  │  │  │  │  │ nrf54h20dk_nrf54h20_cpurad.conf
│  │  │  │  │ testcase.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_cloud
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-13 06:51 UTC, nordic-bami approved these changes

2024-11-13 07:05 UTC, nordic-segl approved these changes

2024-11-13 07:08 UTC, nordic-babu approved these changes

2024-11-13 07:28 UTC, nordic-pikr approved these changes

2024-11-13 08:21 UTC, nordicjm requested changes
Apply changes to each commit

2024-11-13 08:21 UTC, nordicjm commented on tests/benchmarks/power_consumption/adc/sysbuild.cmake
> +  )
missing BOARD_REVISION

2024-11-13 08:21 UTC, nordicjm commented on tests/benchmarks/power_consumption/adc/sysbuild.cmake
> +
```suggestion
```

2024-11-13 08:30 UTC, nordic-piks commented on tests/benchmarks/power_consumption/adc/sysbuild.cmake
> +  )
Fixed.

2024-11-13 08:30 UTC, nordic-piks commented on tests/benchmarks/power_consumption/adc/sysbuild.cmake
> +
Fixed.

2024-11-13 08:31 UTC, nordicjm approved these changes

2024-11-13 08:58 UTC, merged