DNM: bluetooth: hci_driver: Fix deadlock in MPSL workq
nrfconnect/sdk-nrf pull request #18953
Opened 2024-11-19 11:35 UTC by PavelVPV

This is a draft PR used to test the fix in CI.

2024-11-19 11:35 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/PavelVPV/sdk-zephyr/commit/aa40507997a0052c04856db1ad6f290eb1f727cb | [PavelVPV/sdk-zephyr@hci_driver_async_buf_get](https://github.com/PavelVPV/sdk-zephyr/tree/hci_driver_async_buf_get) | [PavelVPV/sdk-zephyr@aa405079..hci_driver_async_buf_get](https://github.com/PavelVPV/sdk-zephyr/compare/aa40507997a0052c04856db1ad6f290eb1f727cb..hci_driver_async_buf_get) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-19 11:39 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-11-19 15:14 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***applications.nrf_desktop.zrelease[nrf54h20dk/nrf54h20/cpuapp]***: ***ROM*** size  ***increased by 1816[B]*** in comparison to the ***main[0d1aab5e]*** branch. - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=applications&var-submodule=nrf_desktop&var-scenario=zrelease&var-testcase=none&var-arch=arm&var-platform=nrf54h20dk/nrf54h20/cpuapp) (cc: @MarekPieta)
***sample.matter.template.release[nrf7002dk/nrf5340/cpuapp]***: ***High ROM usage: 811974[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-18953/3)*

2024-11-20 07:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-18953
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-20 09:45 UTC, PavelVPV commented
DNM until upstream PR is merged and downstreamed: https://github.com/zephyrproject-rtos/zephyr/pull/81646

2024-11-20 09:48 UTC, PavelVPV commented on west.yml
> +      remote: pavelvpv
Added for testing with the upstream fix. Will be reverted.

2024-11-20 09:49 UTC, PavelVPV commented
Moved from the draft state as no more work is needed for the change and would like to get feedback on the change.

2024-11-20 13:58 UTC, rugeGerritsen requested changes
Thanks for this nice change, and also for taking the time to describe how and what problem it solves. 

I believe we should add a changelog entry and update known issues. I suggest to do that in a separate PR.

2024-11-20 13:58 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
>  		LOG_ERR("No data buffer available");
This logging line should be changed to `DBG` or removed as we are no longer waiting forever to get a buffer. Similar change is needed in other similar places.

2024-11-20 13:58 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
> +	}
We should validate that we are getting sane return values: 
```suggestion
	} else {
		LOG_ERR("Unknown error when processing hci message, %d", err);
		k_panic();
	}
```
That will also allow us to remove some calls to `k_oops()` and `k_panic()` in other places.

2024-11-20 13:58 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
> +} rx_hci_msg;
Suggest to add some more documentation to make it more clear how this is used.
```suggestion
/** Storage for HCI packets from controller to host */
static struct {
	uint8_t buf[HCI_RX_BUF_SIZE];
	/** The type of HCI packet the buffer contains. */
	sdc_hci_msg_type_t type;
	/** Set to true if the buffer contains a packet*/
	bool fetched;
} rx_hci_msg;
```

Edit: When looking at it a bit more, we could benefit from defining `SDC_HCI_MSG_TYPE_NONE`, then we would not need the additional bool.

2024-11-20 13:58 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
Discussed offline. We should now be able to replace 
`err = sdc_enable(receive_signal_raise, sdc_mempool);` with `err = sdc_enable(hci_driver_receive_process, sdc_mempool);` because the blocking calls are removed.

2025-01-13 12:03 UTC, rugeGerritsen approved these changes

2025-01-13 12:30 UTC, alwa-nordic approved these changes

2025-01-13 12:32 UTC, merged

2025-01-13 12:44 UTC, alwa-nordic commented
Approved. I'm not sure whether or not the second commit https://github.com/nrfconnect/sdk-nrf/pull/18953/commits/e434180985eba1d76383ab3ddfaacce90ebfc0f8 is a good idea or not, but I'm fine with it. I assume it's done for performance.

It does raise the complexity slightly, as there are now multiple stack usage scenarios when invoking `hci_driver_receive_process`. This could make it harder to determine the needed stack sizes.

I assume the SDC callback is also on the MPSL work thread, so there is still only one thread that can call into `hci_driver_receive_process`.