dfu: Add custom device update
nrfconnect/sdk-nrf pull request #19005
Opened 2024-11-21 07:50 UTC by mathijsmeulendijks

This pull request introduces support for custom firmware upgrades to the DFU (Device Firmware Update) target library. The changes include updates to documentation, configuration options, and the addition of a new header file for custom DFU target implementation.

### Configuration Updates:
* Introduced a new Kconfig option `CONFIG_DFU_TARGET_CUSTOM` to enable support for custom updates.

### Support for Custom DFU Targets:
* Added a new header file `include/dfu/dfu_target_custom.h` with function declarations for custom DFU target implementation.
* Updated `include/dfu/dfu_target.h` to include a new image type `DFU_TARGET_IMAGE_TYPE_CUSTOM` for custom updates. [[1]](diffhunk://#diff-8857e847743854e08dd616843f7fa8327e20c35a1c1e3a40307c529da49c56c4R41-R42) [[2]](diffhunk://#diff-8857e847743854e08dd616843f7fa8327e20c35a1c1e3a40307c529da49c56c4L49-R51)
* Modified `subsys/dfu/dfu_target/src/dfu_target.c` to support the new custom DFU target by including the custom header and adding logic for identifying and initializing custom updates. [[1]](diffhunk://#diff-5ec84e4daa033f549562bdfebb2d50facf28417764dc9a747d73902f648cfde7R41-R44) [[2]](diffhunk://#diff-5ec84e4daa033f549562bdfebb2d50facf28417764dc9a747d73902f648cfde7R72-R76) [[3]](diffhunk://#diff-5ec84e4daa033f549562bdfebb2d50facf28417764dc9a747d73902f648cfde7R125-R129)Adds a custom device update option to the DFU subsystem
Signed-off-by: Mathijs Meulendijks <mathijs.meulendijks@unitial.tech>

2024-11-22 10:01 UTC, nvlsianpu approved these changes

2024-11-22 10:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19005
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-22 10:46 UTC, annwoj commented on doc/nrf/libraries/dfu/dfu_target.rst
> +The application must implement the custom upgrade logic by implementing function as defined in the :file:`include/dfu/dfu_target_custom.h` file.
```suggestion
This firmware upgrade supports custom updates for external peripherals or other custom firmware. 
To use this feature, the application must implement the custom upgrade logic by applying the functions defined in the :file:`include/dfu/dfu_target_custom.h` file.
```

2024-11-25 09:43 UTC, nordicjm requested changes

2024-11-25 09:43 UTC, nordicjm commented on subsys/dfu/dfu_target/Kconfig
> +	default n
```suggestion
```

2024-11-25 09:43 UTC, nordicjm commented on include/dfu/dfu_target.h
> +	DFU_TARGET_IMAGE_TYPE_CUSTOM = 32,
This is already assigned to `DFU_TARGET_IMAGE_TYPE_SMP`, so comment would need to be updated to indicate it is **not** for external MCUs, and ID should be moved to be at the end of the list, if it's an 8-bit value then 128 etc. to allow for additional entries to be added here

2024-11-25 09:47 UTC, annwoj approved these changes

2024-12-11 11:36 UTC, nordicjm reviewed
minor doc nit.

2024-12-11 11:36 UTC, nordicjm commented on include/dfu/dfu_target_custom.h
> + * @param[in] successful true if the DFU process was successful, false otherwise.
```suggestion
 * @param[in] true if the DFU process was successful, false otherwise.
```

2024-12-11 11:36 UTC, nordicjm commented on include/dfu/dfu_target_custom.h
> + * @brief  Release resources and erase the download area.
```suggestion
 * @brief Release resources and erase the download area.
```

2024-12-11 11:48 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [e4e76155a103add42fa610ef263bf9b28fc2f915](https://github.com/nrfconnect/sdk-nrf/pull/19005/commits/e4e76155a103add42fa610ef263bf9b28fc2f915)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [e4e76155a103add42fa610ef263bf9b28fc2f915](https://github.com/nrfconnect/sdk-nrf/pull/19005/commits/e4e76155a103add42fa610ef263bf9b28fc2f915)
> merge base: [c01d9380ddf82e8204098b3b08a7f423d5db292c](https://github.com/nrfconnect/sdk-nrf/commit/c01d9380ddf82e8204098b3b08a7f423d5db292c)
> target head (main): [e28af5e0cff6bde826d37613685c8c30ca1905d3](https://github.com/nrfconnect/sdk-nrf/commit/e28af5e0cff6bde826d37613685c8c30ca1905d3)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/c01d9380ddf82e8204098b3b08a7f423d5db292c..e4e76155a103add42fa610ef263bf9b28fc2f915)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (5)</summary>

```
doc
│  ├── nrf
│  │  ├── libraries
│  │  │  ├── dfu
│  │  │  │  │ dfu_target.rst
include
│  ├── dfu
│  │  ├── dfu_target.h
│  │  │ dfu_target_custom.h
subsys
│  ├── dfu
│  │  ├── dfu_target
│  │  │  ├── Kconfig
│  │  │  ├── src
│  │  │  │  │ dfu_target.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - :orange_circle: test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :warning: test-fw-nrfconnect-fw-update
   - :warning: test-fw-nrfconnect-nrf-iot_cloud

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-17 12:04 UTC, nordicjm approved these changes

2025-01-08 11:04 UTC, mathijsmeulendijks commented
@nordicjm Could you add the CI-requested label?

2025-01-08 13:26 UTC, peknis requested changes

2025-01-08 13:26 UTC, peknis commented on doc/nrf/libraries/dfu/dfu_target.rst
> +-------------------
```suggestion
Custom upgrades
---------------
```

2025-01-08 13:26 UTC, peknis commented on include/dfu/dfu_target_custom.h
> + * @brief Identifies if the provided buffer contains a custom firmware image.
```suggestion
 * @brief Check if the provided buffer contains a custom firmware image.
```

2025-02-15 00:32 UTC, closed without merging