Bluetooth hids mouse sample testing sample changes
nrfconnect/sdk-nrf pull request #19039
Opened 2024-11-22 15:10 UTC by kapi-no

2024-11-22 15:12 UTC, kapi-no commented
ncs-si-muffin-doc, ncs-si-dragoon-doc teams should be replaced by the ncs-si-bluebagel-doc team.

I will apply this change in a follow-up PR

2024-11-22 15:26 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [3de8e0ffeceff87cc7d3397dbf0c421166dc30b2](https://github.com/nrfconnect/sdk-nrf/pull/19039/commits/3de8e0ffeceff87cc7d3397dbf0c421166dc30b2)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [3de8e0ffeceff87cc7d3397dbf0c421166dc30b2](https://github.com/nrfconnect/sdk-nrf/pull/19039/commits/3de8e0ffeceff87cc7d3397dbf0c421166dc30b2)
> merge base: [a07b87c923420fdbfbdbff3698a3d30f5c1c33ee](https://github.com/nrfconnect/sdk-nrf/commit/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee)
> target head (main): [a07b87c923420fdbfbdbff3698a3d30f5c1c33ee](https://github.com/nrfconnect/sdk-nrf/commit/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee..3de8e0ffeceff87cc7d3397dbf0c421166dc30b2)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
samples
│  ├── bluetooth
│  │  ├── peripheral_hids_mouse
│  │  │  ├── Kconfig
│  │  │  ├── README.rst
│  │  │  ├── sysbuild
│  │  │  │  ├── ipc_radio
│  │  │  │  │  │ prj_bt_rpc.conf
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-22 15:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19039
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-25 07:24 UTC, peknis requested changes

2024-11-25 07:24 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   See the :ref:`peripheral_hids_mouse_ncd_build` section to learn how build the compatible sample configuration.
```suggestion
   See the :ref:`peripheral_hids_mouse_ncd_build` section to learn how to build a compatible sample configuration.
```

2024-11-25 10:21 UTC, alstrzebonski approved these changes

2024-11-25 10:21 UTC, alstrzebonski commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +      west build -b *board_target* -S nordic-bt-rpc -- -DFILE_SUFFIX=bt_rpc -DCONFIG_BT_DIRECTED_ADVERTISING=n -DCONFIG_BT_PRIVACY=n -Dipc_radio_CONFIG_BT_PRIVACY=n
I'd prefer to keep it as is. I don't like the idea of building from the testcase - it's less straight forward.

2024-11-25 10:39 UTC, kapi-no commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   |54H_engb_2_8|
this is maintained by the tech writers and if necessary they will probably align it for NCS 2.9

2024-11-25 10:42 UTC, kapi-no commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +* Privacy (:kconfig:option:`CONFIG_BT_PRIVACY`) - `nRF Connect for Desktop`_ does not support Bluetooth Privacy very well and does not allow distribution of the Identity Resolving Key (IRK) during th
you are right - this sounds a bit bad. I will change to "fully"

2024-11-25 10:46 UTC, kapi-no commented
addressed review comments

2024-11-25 10:51 UTC, kapi-no commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +      west build -b *board_target* -S nordic-bt-rpc -- -DFILE_SUFFIX=bt_rpc -DCONFIG_BT_DIRECTED_ADVERTISING=n -DCONFIG_BT_PRIVACY=n -Dipc_radio_CONFIG_BT_PRIVACY=n
yes, this also has educational value as it demonstrates what Kconfig option in the Bluetooth stack is responsible for enabling Privacy. We have never relied on the `-T` build variant in the documentation of our projects.

2024-11-25 10:54 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   |54H_engb_2_8|
@annwoj

2024-11-25 11:28 UTC, zycz approved these changes

2024-11-25 13:00 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +* Privacy (:kconfig:option:`CONFIG_BT_PRIVACY`) - `nRF Connect for Desktop`_ does not fully support the Bluetooth Privacy feature by disallowing distribution of the Identity Resolving Key (IRK) durin
```suggestion
* Privacy (:kconfig:option:`CONFIG_BT_PRIVACY`) - the `Bluetooth Low Energy app`_ does not fully support the Bluetooth Privacy feature by disallowing distribution of the Identity Resolving Key (IRK) during the pairing procedure.
```

2024-11-25 13:00 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +To build this sample in the configuration variant that is compatible with `nRF Connect for Desktop`_, disable the following Bluetooth features:
```suggestion
To build this sample in the configuration variant that is compatible with `Bluetooth Low Energy app`_, disable the following Bluetooth features:
```

2024-11-25 13:01 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +* High-duty directed advertising (:kconfig:option:`CONFIG_BT_DIRECTED_ADVERTISING`) - high-duty directed advertising with 3.75 ms advertising interval and 1.28 s duration prevents the subsequent undi
```suggestion
* High-duty directed advertising (:kconfig:option:`CONFIG_BT_DIRECTED_ADVERTISING`) - high-duty directed advertising with 3.75 ms advertising interval and 1.28 s duration prevents the subsequent undirected advertising from being reported in the scanning list of `Bluetooth Low Energy app`_ .
```

2024-11-25 13:01 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   To execute the testing steps below, you must build the sample in the configuration that is compatible with `nRF Connect for Desktop`_.
```suggestion
   To execute the testing steps below, you must build the sample in the configuration that is compatible with `Bluetooth Low Energy app`_.
```

2024-11-25 13:53 UTC, annwoj commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   |54H_engb_2_8|
@FrancescoSer is it okay to remove it in this PR or do you have a separate cleanup task planned?

2024-11-25 15:04 UTC, FrancescoSer commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +   |54H_engb_2_8|
This note should stay there, please check the note text contain in the file, it was updated do reflect 2.9 reality

2024-11-26 08:32 UTC, peknis approved these changes

2024-11-26 08:37 UTC, kapi-no commented
Rebased to reflect the new doc codeowners changes

2024-11-26 08:47 UTC, wiba-nordic approved these changes

2024-11-26 09:28 UTC, merged