tests: benchmarks: multicore: Test PM in SPI driver with locks
nrfconnect/sdk-nrf pull request #19037
Opened 2024-11-22 14:58 UTC by nordic-segl

Extend test that checks:
- current consumption in IDLE, S2RAM when SPIM was used;
- SPIM works correctly after leaving low power state.

Add tests suites where SPI is configured with
SPI_HOLD_ON_CS and/or SPI_LOCK_ON.

2024-11-22 15:05 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [3a8af0895c69734b8cc317769cc4d89ca0a9eb37](https://github.com/nrfconnect/sdk-nrf/pull/19037/commits/3a8af0895c69734b8cc317769cc4d89ca0a9eb37)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [3a8af0895c69734b8cc317769cc4d89ca0a9eb37](https://github.com/nrfconnect/sdk-nrf/pull/19037/commits/3a8af0895c69734b8cc317769cc4d89ca0a9eb37)
> merge base: [a07b87c923420fdbfbdbff3698a3d30f5c1c33ee](https://github.com/nrfconnect/sdk-nrf/commit/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee)
> target head (main): [a07b87c923420fdbfbdbff3698a3d30f5c1c33ee](https://github.com/nrfconnect/sdk-nrf/commit/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/a07b87c923420fdbfbdbff3698a3d30f5c1c33ee..3a8af0895c69734b8cc317769cc4d89ca0a9eb37)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (10)</summary>

```
tests
│  ├── benchmarks
│  │  ├── multicore
│  │  │  ├── idle_spim_loopback
│  │  │  │  ├── Kconfig
│  │  │  │  ├── Kconfig.sysbuild
│  │  │  │  ├── boards
│  │  │  │  │  ├── nrf54h20dk_nrf54h20_cpuapp.overlay
│  │  │  │  │  │ nrf54h20dk_nrf54h20_cpuapp_fast.overlay
│  │  │  │  ├── prj.conf
│  │  │  │  ├── prj_s2ram.conf
│  │  │  │  ├── src
│  │  │  │  │  │ main.c
│  │  │  │  ├── sysbuild.cmake
│  │  │  │  ├── sysbuild
│  │  │  │  │  │ nrf54h20dk_nrf54h20_cpurad.conf
│  │  │  │  │ testcase.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-25 08:49 UTC, nordicjm requested changes

2024-11-25 09:12 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_spim_loopback/Kconfig
> +	default n
Removed from both KConfig parameters.

2024-11-25 09:15 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_spim_loopback/src/main.c
> +		/* clear edge counters */
Fixed. However, I left three comments starting from small letter:
```
		while (!timer_expired) {
		(...)
		} /* while (!timer_expired) */

#if defined(CONFIG_TEST_SPI_RELEASE_BEFORE_SLEEP)
(...)
#else /* defined(CONFIG_TEST_SPI_RELEASE_BEFORE_SLEEP) */
(...)
#endif /* defined(CONFIG_TEST_SPI_RELEASE_BEFORE_SLEEP) */
```

2024-11-25 09:43 UTC, nordic-piks approved these changes

2024-11-26 10:39 UTC, nordicjm approved these changes

2024-11-26 10:39 UTC, merged