doc: Update testing steps in Peripheral UART sample
nrfconnect/sdk-nrf pull request #19041
Opened 2024-11-22 15:15 UTC by divipillai

NCSDK-29646
Updates to sample docs after comparing the testing the sample section of the getting started guide with
Testing sample steps of the Peripheral UART sample.

2024-11-22 15:25 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-11-22 15:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19041
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-25 07:59 UTC, peknis requested changes

2024-11-25 07:59 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +         This enables the notifications on the UART Tx characteristic on the peripheral (DK) to allow sending UART characters to the phone or tablet.
```suggestion
         This enables the notifications on the UART TX characteristic on the peripheral (DK) to allow sending UART characters to the phone or tablet.
```

2024-11-25 07:59 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +         This enables the notifications on the UART Tx characteristic on the peripheral (DK) to allow sending UART characters to the phone or tablet.
```suggestion
         This enables the notifications on the UART TX characteristic on the peripheral (DK) to allow sending UART characters to the phone or tablet.
```

2024-11-25 09:04 UTC, peknis approved these changes

2024-11-25 09:13 UTC, wiba-nordic approved these changes

2024-11-26 13:24 UTC, grochu approved these changes
Looks good

2024-11-26 14:28 UTC, greg-fer approved these changes

2024-11-27 08:55 UTC, merged