SRP client's RPC client
nrfconnect/sdk-nrf pull request #19049
Opened 2024-11-25 09:25 UTC by konradderda

2024-11-25 09:30 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [577ad7ef5947a8e7eddf574026bf61356728c48c](https://github.com/nrfconnect/sdk-nrf/pull/19049/commits/577ad7ef5947a8e7eddf574026bf61356728c48c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [577ad7ef5947a8e7eddf574026bf61356728c48c](https://github.com/nrfconnect/sdk-nrf/pull/19049/commits/577ad7ef5947a8e7eddf574026bf61356728c48c)
> merge base: [f4100a58a8fcfb9daf111c31cc1e10e53565fad5](https://github.com/nrfconnect/sdk-nrf/commit/f4100a58a8fcfb9daf111c31cc1e10e53565fad5)
> target head (main): [f4100a58a8fcfb9daf111c31cc1e10e53565fad5](https://github.com/nrfconnect/sdk-nrf/commit/f4100a58a8fcfb9daf111c31cc1e10e53565fad5)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/f4100a58a8fcfb9daf111c31cc1e10e53565fad5..577ad7ef5947a8e7eddf574026bf61356728c48c)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
samples
│  ├── nrf_rpc
│  │  ├── protocols_serialization
│  │  │  ├── client
│  │  │  │  ├── src
│  │  │  │  │  │ ot_shell.c
subsys
│  ├── net
│  │  ├── openthread
│  │  │  ├── rpc
│  │  │  │  ├── client
│  │  │  │  │  │ ot_rpc_srp_client.c
tests
│  ├── subsys
│  │  ├── net
│  │  │  ├── openthread
│  │  │  │  ├── rpc
│  │  │  │  │  ├── client
│  │  │  │  │  │  ├── src
│  │  │  │  │  │  │  │ srp_client_suite.c
│  │  │  │  │  ├── common
│  │  │  │  │  │  │ test_rpc_env.h
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-rpc
   - :orange_circle: test-fw-nrfconnect-thread
   - :orange_circle: test-fw-nrfconnect-ps

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-26 13:13 UTC, alxelax requested changes

2024-11-29 11:06 UTC, Damian-Nordic reviewed
Some extra comments from me

2024-11-29 11:06 UTC, Damian-Nordic commented on tests/subsys/net/openthread/rpc/client/src/srp_client_suite.c
> +	otError err_1st;
Why is `otError` used to store bool?

2024-11-29 11:06 UTC, Damian-Nordic commented on tests/subsys/net/openthread/rpc/client/src/srp_client_suite.c
> +	otError err1;
ditto

2024-11-29 11:06 UTC, Damian-Nordic commented on tests/subsys/net/openthread/rpc/common/test_rpc_env.h
> +#define CBOR_LIST(...) 0x9F, __VA_ARGS__, 0xFF
Could you move this to "/* Macros for constructing CBOR data items. */" section above?

2024-12-02 08:23 UTC, alxelax commented on samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
> +	for (int i = 0; i < SERVICE_NUM; ++i) {
I meant that if you use `IS_ARRAY_ELEMENT` then you do not need a cycle at all. Code will be much optimal both speed and size.

```
	if (IS_ARRAY_ELEMENT(services, service)) {
                struct srp_service *elem = CONTAINER_OF(service, struct srp_service, service);
                
                memset(elem, 0, sizeof(struct srp_service));   
	}
```

2024-12-02 08:33 UTC, alxelax reviewed
Some comments have not been resolved.

2024-12-02 12:31 UTC, canisLupus1313 approved these changes

2024-12-02 12:52 UTC, Damian-Nordic approved these changes

2024-12-02 12:52 UTC, Damian-Nordic commented on samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
> +	shell_print(sh, "Name set to: %s", argv[1]);
But argv must be null-terminated, no?

2024-12-02 13:08 UTC, alxelax approved these changes

2024-12-03 08:04 UTC, merged