doc: install_ncs: update path location for macOS
nrfconnect/sdk-nrf pull request #19097
Opened 2024-11-27 13:44 UTC by greg-fer

Fixed the path location for macOS.
Added information about the toolchain installation location. NCSIDB-1414.

2024-11-27 13:49 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-11-27 14:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19097
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-28 07:20 UTC, peknis approved these changes

2024-11-28 08:28 UTC, bencefr approved these changes

2024-11-28 08:40 UTC, carlescufi commented on doc/nrf/installation/install_ncs.rst
> +If you used the default location to install the toolchain (:file:`C:/ncs/toolchains` on Windows, :file:`~/ncs/toolchains/` on Linux, and :file:`/opt/nordic/ncs/toolchains/` on macOS), your directory
@kenr just explained that it is not possible to select the install location on macOS, but it is on Windows and Linux. So this should be reflected in the doc.

2024-11-28 08:44 UTC, greg-fer commented on doc/nrf/installation/install_ncs.rst
> +If you used the default location to install the toolchain (:file:`C:/ncs/toolchains` on Windows, :file:`~/ncs/toolchains/` on Linux, and :file:`/opt/nordic/ncs/toolchains/` on macOS), your directory
It's not for macOS, so indeed this is written incorrectly. I'll fix.

2024-11-28 10:29 UTC, greg-fer commented on doc/nrf/installation/install_ncs.rst
> +If you used the default location to install the toolchain (in the previous step) and the default location to install the SDK (:file:`C:/ncs` on Windows, :file:`~/ncs/` on Linux, and :file:`/opt/nordi
Docs already mention `--mr` in line 269 of this file, and the command works as intended.
However, as both me and @bencefr mentioned in the Teams chat, the issue is the location where the `west init` command is run. It should not be in (for Windows) `c:\ncs\`, but in `c:\ncs\*nRFConnectSDK_revision*` . Only then do we get the desired structure outlined at the end of the steps.

2024-11-28 11:16 UTC, FrancescoSer approved these changes

2024-11-28 12:04 UTC, skogseth approved these changes
Looks great!

2024-11-29 08:40 UTC, b-gent approved these changes

2024-11-29 08:49 UTC, carlescufi requested changes

2024-11-29 08:49 UTC, carlescufi commented on doc/nrf/installation/install_ncs.rst
> +      #. Create a directory for the *nRFConnectSDK_revision* you want to use and enter it:
Why? it is so much simple to instruct the user to run:

`west init -m https://github.com/nrfconnect/sdk-nrf --mr *nRFConnectSDK_revision* *nRFConnectSDK_revision*`

So for example:

`west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.8.0 v2.8.0`

2024-11-29 08:49 UTC, carlescufi commented on doc/nrf/installation/install_ncs.rst
> +      #. Create a directory for the *nRFConnectSDK_revision* you want to use and enter it:
Also, this change is required in the other 2 sub-sections below as well

2024-11-29 14:40 UTC, carlescufi approved these changes

2024-11-29 15:16 UTC, merged