doc: 54h documentation improvements
nrfconnect/sdk-nrf pull request #19099
Opened 2024-11-27 13:50 UTC by FrancescoSer

Improved various 54h doc pages.

2024-11-27 13:53 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-12-18 07:46 UTC, wiba-nordic requested changes

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +   If you connect multiple DKs to the machine and have not defined ``SEGGER-ID``, a pop-up window appears where you can manually select the ID of the DK to run J-Link on.
Duplicated sentence.

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
>  The Embedded Trace Router (ETR) is a hardware feature that provides a circular buffer in RAM for trace data.
Difference in capitalization for the feature between heading and body text.

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
> +Assisted multicore logging uses dictionary-based logging to send messages without redundant strings to STM, following the :ref:`zephyr:logging_guide_dictionary` feature of the Zephyr logging API.
```suggestion
Assisted multicore logging uses dictionary-based logging to send messages without redundant strings to STM, and is based on the :ref:`zephyr:logging_guide_dictionary` feature of the Zephyr logging API.
```
I don't think you follow features.

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
> +After building your application, the build directories for each core will contain a dictionary database file named :file:`log_database.json` (:file:`build/<app_name>/zephyr/`, where ``<app_name>`` is
```suggestion
After building your application, the build directories for each core (:file:`build/<app_name>/zephyr/`, where ``<app_name>`` is the application name for each core) will contain a dictionary database file named :file:`log_database.json`.
```

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_soc_binaries.rst
> +Both methods require using the :file:`nordic_top.suit` envelope, available inside the nRF54H20 SoC binaries ZIP file in the folder.
```suggestion
Both methods require using the :file:`nordic_top.suit` envelope, available inside the nRF54H20 SoC binaries ZIP file.
```
A folder has not been mentioned before on this page, so can not refer to "the folder". Alternatively, can make the reference more specific to clarify which folder is being referred to.

2024-12-18 07:46 UTC, wiba-nordic commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_soc_binaries.rst
> +* There is no need to update the version and sequence number of the manufacturer root manifest if you need to update only the SoC binaries.
```suggestion
* There is no need to update the version and sequence number of the manufacturer root manifest when you update only the SoC binaries.
```

2024-12-18 09:30 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_configuration.rst
> +You can find documentation for the output files created in your application build directory in :ref:`zephyr:devicetree-in-out-files`.
needs edit

2024-12-18 09:31 UTC, annwoj approved these changes
Approving but Wille's suggestions should be incorporated

2025-01-04 22:09 UTC, b-gent commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +   If you connect multiple DKs to the machine and have not defined ``SEGGER-ID``, a pop-up window appears where you can manually select the ID of the DK to run J-Link on.
I will assume that the second version is the one that was meant to be kept here.

2025-01-04 22:12 UTC, b-gent commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
>  The Embedded Trace Router (ETR) is a hardware feature that provides a circular buffer in RAM for trace data.
I've found cases of this being capitalized in Zephyr and Arm docs so I'll go for this here as well.

2025-01-04 22:22 UTC, b-gent commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_soc_binaries.rst
> +Both methods require using the :file:`nordic_top.suit` envelope, available inside the nRF54H20 SoC binaries ZIP file in the folder.
Changing to simply "inside the nRF54H20 SoC binaries ZIP package." without the 'folder' bit.
I checked the zip and all files in it are on the top level without any specific folders.

2025-01-04 22:29 UTC, b-gent commented
@wiba-nordic  please approve

2025-01-04 22:29 UTC, b-gent approved these changes

2025-01-07 06:38 UTC, wiba-nordic approved these changes

2025-01-07 16:46 UTC, merged