Selected Bluetooth/MPSL samples: Support nRF54L10 and nRF54L05
nrfconnect/sdk-nrf pull request #19106
Opened 2024-11-27 14:43 UTC by rugeGerritsen

These SoCs are similar to nRF54L15. No change to the sample is needed. This PR updates sample support for samples with codeowner set to @nrfconnect/ncs-dragoon.

Each of the samples has updated both integration_platform and platform_allow.

2024-11-27 14:50 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [1154cdfba57f29024654fd18f52568c5cd353123](https://github.com/nrfconnect/sdk-nrf/pull/19106/commits/1154cdfba57f29024654fd18f52568c5cd353123)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [1154cdfba57f29024654fd18f52568c5cd353123](https://github.com/nrfconnect/sdk-nrf/pull/19106/commits/1154cdfba57f29024654fd18f52568c5cd353123)
> merge base: [8fdc675d02285d4ae229268cdb92b8f464f7e227](https://github.com/nrfconnect/sdk-nrf/commit/8fdc675d02285d4ae229268cdb92b8f464f7e227)
> target head (main): [8ce5e57fe8c1569a882dfb60832c17601f2c9d01](https://github.com/nrfconnect/sdk-nrf/commit/8ce5e57fe8c1569a882dfb60832c17601f2c9d01)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/8fdc675d02285d4ae229268cdb92b8f464f7e227..1154cdfba57f29024654fd18f52568c5cd353123)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (16)</summary>

```
samples
│  ├── bluetooth
│  │  ├── channel_sounding_ras_initiator
│  │  │  │ sample.yaml
│  │  ├── channel_sounding_ras_reflector
│  │  │  │ sample.yaml
│  │  ├── conn_time_sync
│  │  │  ├── boards
│  │  │  │  ├── nrf54l15dk_nrf54l05_cpuapp.conf
│  │  │  │  │ nrf54l15dk_nrf54l10_cpuapp.conf
│  │  ├── event_trigger
│  │  │  ├── boards
│  │  │  │  ├── nrf54l15dk_nrf54l05_cpuapp.overlay
│  │  │  │  │ nrf54l15dk_nrf54l10_cpuapp.overlay
│  │  │  │ sample.yaml
│  │  ├── iso_time_sync
│  │  │  ├── boards
│  │  │  │  ├── nrf54l15dk_nrf54l05_cpuapp.conf
│  │  │  │  │ nrf54l15dk_nrf54l10_cpuapp.conf
│  │  ├── llpm
│  │  │  │ sample.yaml
│  │  ├── radio_coex_1wire
│  │  │  ├── boards
│  │  │  │  ├── nrf54l15dk_nrf54l05_cpuapp.overlay
│  │  │  │  │ nrf54l15dk_nrf54l10_cpuapp.overlay
│  │  │  │ sample.yaml
│  │  ├── radio_notification_cb
│  │  │  │ sample.yaml
│  │  ├── subrating
│  │  │  │ sample.yaml
│  ├── mpsl
│  │  ├── timeslot
│  │  │  │ sample.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-27 14:51 UTC, rugeGerritsen commented
@nrfconnect/ncs-dragoon-doc , does this need an entry in the changelog? I would assume that can be taken separately.

2024-11-27 14:53 UTC, Tschet1 commented
Should we also add support for l10 and l05 for the iso_combined_bis_and_cis sample? Or does that not fit?

2024-11-27 14:55 UTC, Tschet1 approved these changes

2024-11-27 14:56 UTC, rugeGerritsen commented
> Should we also add support for l10 and l05 for the iso_combined_bis_and_cis sample? Or does that not fit?

Thanks for pointing out. I missed those.

2024-11-27 15:00 UTC, rugeGerritsen commented
@nrfconnect/ncs-ci , requested a review from you to check if we want to go for the approach of adding all 54L to platform_allow and integration_platform

2024-11-28 07:42 UTC, rugeGerritsen commented
Thanks for pointing out @wiba-nordic , will add it

2024-11-28 08:43 UTC, wiba-nordic requested changes

2024-11-28 08:43 UTC, wiba-nordic commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l05)` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
```suggestion
| :ref:`nRF54L15 DK (emulating nrf54l05) <ug_nrf54l>` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
```

2024-11-28 08:43 UTC, wiba-nordic commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l10)` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l10/cpuapp`` |
```suggestion
| :ref:`nRF54L15 DK (emulating nrf54l10) <ug_nrf54l>` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l10/cpuapp`` |
```

2024-11-28 08:52 UTC, wiba-nordic requested changes

2024-11-28 08:52 UTC, wiba-nordic commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l05)` <ug_nrf54l>`  | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
```suggestion
| :ref:`nRF54L15 DK (emulating nrf54l05) <ug_nrf54l>`  | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
```

2024-11-28 08:52 UTC, wiba-nordic commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l10)` <ug_nrf54l>` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l10/cpuapp`` |
```suggestion
| :ref:`nRF54L15 DK (emulating nrf54l10) <ug_nrf54l>` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l10/cpuapp`` |
```

2024-11-28 08:57 UTC, peknis commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l05)` <ug_nrf54l>`  | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
emulating nRF54L05

2024-11-28 08:58 UTC, peknis commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nrf54l10)` <ug_nrf54l>` | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l10/cpuapp`` |
Rather: (emulating nRF54L10)

2024-11-28 09:01 UTC, wiba-nordic commented
I'll wait for the build to finish and check one or two of the samples, but looks good.

2024-11-28 09:02 UTC, rugeGerritsen commented
> I'll wait for the build to finish and check one or two of the samples, but looks good.

Note that we should update https://github.com/nrfconnect/sdk-zephyr/blob/main/boards/nordic/nrf54l15dk/doc/index.rst with a section about emulated targets like we do for 52. I believe that is better done separately

2024-11-28 09:20 UTC, peknis approved these changes

2024-11-28 09:30 UTC, wiba-nordic reviewed
Noticed we've got pages that actually mention the emulation, so changing the targets to those.

2024-11-28 10:57 UTC, wiba-nordic approved these changes

2024-11-28 10:58 UTC, wiba-nordic commented on doc/nrf/includes/sample_board_rows.txt
> +| :ref:`nRF54L15 DK (emulating nRF54L05) <ug_nrf54l>`  | PCA10156 | :ref:`nrf54l15dk <zephyr:nrf54l15dk_nrf54l15>` | ``nrf54l15dk/nrf54l05/cpuapp`` |
Ah, excellent. Then everything is good.

2024-11-28 12:23 UTC, annwoj approved these changes

2024-11-28 14:28 UTC, rugeGerritsen commented
Talked to @jangalda-nsc  about adding more integration targets, and he said this was fine.

2024-11-28 14:28 UTC, merged