suit: manifest-controlled variables
nrfconnect/sdk-nrf pull request #19104
Opened 2024-11-27 14:35 UTC by SylwesterKonczyk

Support for SUIT manifest-controlled variables

Ref: NCSDK-30530

2024-11-27 15:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19104
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-11-29 10:08 UTC, nordicjm approved these changes

2024-11-29 11:02 UTC, tomchy requested changes

2024-11-29 11:02 UTC, tomchy commented on tests/subsys/suit/manifest_variables/src/main.c
> +		zassert_equal(ret, SUIT_PLAT_SUCCESS,
Generally speaking - it might be worth to add an assertion on the returned `access_mask` value.

2024-11-29 13:02 UTC, ahasztag approved these changes
Except form the missing documentation as mentioned by @tomchy no further remarks from my side

2024-11-29 14:02 UTC, SylwesterKonczyk commented on subsys/suit/manifest_variables/include/suit_manifest_variables.h
> +suit_plat_err_t suit_mfst_var_set(uint32_t id, uint32_t val);
Right :-) I knew something is missing :-)

2024-11-29 14:05 UTC, SylwesterKonczyk commented on tests/subsys/suit/manifest_variables/Kconfig
> +#
Nope. For NVM based variables the module utilizes suit storage (so suit_storage_test.c in case of posix tests)

2024-12-02 09:31 UTC, tomchy approved these changes

2024-12-02 09:31 UTC, merged