doc: wifi: Update TX power calculation
nrfconnect/sdk-nrf pull request #19131
Opened 2024-11-28 12:58 UTC by prsi98

[SHEL-3277]: Update sample description with TX power equations

Dependency on https://github.com/nrfconnect/sdk-nrf/pull/19009

2024-11-28 13:04 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-11-28 13:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19131
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-03 11:14 UTC, srkanordic approved these changes

2024-12-03 15:23 UTC, richabp requested changes

2024-12-03 15:23 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         TX power calculation when ``tx_power`` command is issued is described by following equation:
```suggestion
         You can calculate the TX power when ``tx_power`` command is issued, by using the following formula:
```

2024-12-03 15:23 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         * ``AntGain`` is the compensation for the antenna gain in the TX direction, as described in `Antenna gain compensation`_. ``AntGain`` can be set to ``0`` using ``wifi_radio_test set_ant_gain
```suggestion
         * ``AntGain`` is the compensation for the antenna gain in the TX direction, as described in `Antenna gain compensation`_.
            ``AntGain`` can be set to ``0`` using ``wifi_radio_test set_ant_gain`` command.
```

2024-12-03 15:23 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         * ``EdgeBackoff`` is the backoff applied to band edge channels, as described in `Band edge compensation`_. ``EdgeBackoff`` can be set to ``0`` using ``wifi_radio_test set_edge_bo`` command.
```suggestion
         * ``EdgeBackoff`` is the backoff applied to band edge channels, as described in `Band edge compensation`_.
            ``EdgeBackoff`` can be set to ``0`` using ``wifi_radio_test set_edge_bo`` command.
```

2024-12-03 15:23 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         TX power calculation when ``bypass_reg_domain`` is ``1`` and the ``tx_power`` command is issued is described by following equation:
```suggestion
         You can calculate the TX power when ``bypass_reg_domain`` is ``1`` and the ``tx_power`` command is issued,  by using the following formula:
```

2024-12-03 15:23 UTC, richabp commented on samples/wifi/radio_test/sample_description.rst
> +         TX power calculation without issuing ``tx_power`` command is described in :ref:`nrf70_wifi_tx_power_calculation`.
Suggest to move this line after 590 at the end.
```suggestion
        To calculate the TX power without issuing ``tx_power`` command, see :ref:`nrf70_wifi_tx_power_calculation`.
```

2024-12-04 08:19 UTC, richabp approved these changes

2024-12-04 08:40 UTC, merged