samples: matter: Enable ZMS in nRF54H20
nrfconnect/sdk-nrf pull request #19170
Opened 2024-11-29 15:47 UTC by ArekBalysNordic

Enabled ZMS as Settings backend for nRF54H20 samples and other MRAM-based device that support it.

2024-11-29 15:48 UTC, NordicBuilder commented
The following west manifest projects have changed revision in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/297f762debcfe0d983fcef2dd60cc926e715b17c | https://github.com/nrfconnect/sdk-connectedhomeip/pull/516 | [nrfconnect/sdk-connectedhomeip#516/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/516/files) |

⛔ **DNM label due to: 1 project with PR revision**

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-11-29 15:50 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [7dc96835f0987aa78ccba9219241a4f62bf9788f](https://github.com/nrfconnect/sdk-nrf/pull/19170/commits/7dc96835f0987aa78ccba9219241a4f62bf9788f)
matter: PR head: [fd3e53839073a4bafe092b1013dbaea34ff412bd](https://github.com/nrfconnect/sdk-connectedhomeip/pull/516/commits/fd3e53839073a4bafe092b1013dbaea34ff412bd)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [7dc96835f0987aa78ccba9219241a4f62bf9788f](https://github.com/nrfconnect/sdk-nrf/pull/19170/commits/7dc96835f0987aa78ccba9219241a4f62bf9788f)
> merge base: [9faad159711fa0cea2ee875c9dc456cdda371a45](https://github.com/nrfconnect/sdk-nrf/commit/9faad159711fa0cea2ee875c9dc456cdda371a45)
> target head (main): [9faad159711fa0cea2ee875c9dc456cdda371a45](https://github.com/nrfconnect/sdk-nrf/commit/9faad159711fa0cea2ee875c9dc456cdda371a45)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/9faad159711fa0cea2ee875c9dc456cdda371a45..7dc96835f0987aa78ccba9219241a4f62bf9788f)

matter:
> PR head: [fd3e53839073a4bafe092b1013dbaea34ff412bd](https://github.com/nrfconnect/sdk-connectedhomeip/pull/516/commits/fd3e53839073a4bafe092b1013dbaea34ff412bd)
> merge base: [297f762debcfe0d983fcef2dd60cc926e715b17c](https://github.com/nrfconnect/sdk-connectedhomeip/commit/297f762debcfe0d983fcef2dd60cc926e715b17c)
> target head (master): [6c1a9c51256fa3bea98bcdbf31d8a6aeef006a19](https://github.com/nrfconnect/sdk-connectedhomeip/commit/6c1a9c51256fa3bea98bcdbf31d8a6aeef006a19)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/297f762debcfe0d983fcef2dd60cc926e715b17c..fd3e53839073a4bafe092b1013dbaea34ff412bd)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (6)</summary>

```
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── config
│  │  │  │  ├── nrfconnect
│  │  │  │  │  ├── chip-module
│  │  │  │  │  │  ├── CMakeLists.txt
│  │  │  │  │  │  │ Kconfig
│  │  │  │  ├── zephyr
│  │  │  │  │  │ Kconfig
samples
│  ├── matter
│  │  ├── lock
│  │  │  ├── boards
│  │  │  │  │ nrf54h20dk_nrf54h20_cpuapp.conf
│  │  ├── template
│  │  │  ├── boards
│  │  │  │  │ nrf54h20dk_nrf54h20_cpuapp.conf
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-11-29 16:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19170
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-02 07:20 UTC, maciejbaczmanski approved these changes

2024-12-02 13:08 UTC, kkasperczyk-no approved these changes
Could you add the same to the Matter bridge? Also maybe it would be worth to mention in change log that ZMS is now enabled also for MRAM based devices.

2024-12-02 14:37 UTC, nordicjm approved these changes

2024-12-02 15:08 UTC, LuDuda approved these changes

2024-12-03 06:42 UTC, peknis requested changes

2024-12-03 06:42 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Enabled the ZMS file subsystem in all devices that contain MRAM, such as the nRF54H Series devices.
```suggestion
* Updated:

  * Whatever there is now under Matter samples
  * All Matter samples to enable the ZMS file subsystem in all devices that contain MRAM, such as the nRF54H Series devices.
```
Now, this complies with our changelog wording conventions. Please move this under Matter samples (Updated).

2024-12-03 08:01 UTC, peknis approved these changes
Approved with a nit.

2024-12-03 08:01 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * All Matter samples that support low-power mode to enable the :ref:`lib_ram_pwrdn` feature.
```suggestion
* Updated:

  * All Matter samples that support low-power mode to enable the :ref:`lib_ram_pwrdn` feature.
```

2024-12-03 10:07 UTC, merged