samples: peripheral_power_profiling: Add support for nRF54H20 target
nrfconnect/sdk-nrf pull request #19186
Opened 2024-12-02 11:05 UTC by maje-emb

Added support for the nrf54h20 board target.
Currently, the System off mode is not supported by this sample for the nRF54H20 platform.

2024-12-02 11:08 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [f883b6df1928236efe9f0dc9bca2a048e1d8805a](https://github.com/nrfconnect/sdk-nrf/pull/19186/commits/f883b6df1928236efe9f0dc9bca2a048e1d8805a)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [f883b6df1928236efe9f0dc9bca2a048e1d8805a](https://github.com/nrfconnect/sdk-nrf/pull/19186/commits/f883b6df1928236efe9f0dc9bca2a048e1d8805a)
> merge base: [b1025349fd3bf3699df04c1a16340cdd4d45d854](https://github.com/nrfconnect/sdk-nrf/commit/b1025349fd3bf3699df04c1a16340cdd4d45d854)
> target head (main): [20158058f231395237a6cf40399af2a5c2e826cb](https://github.com/nrfconnect/sdk-nrf/commit/20158058f231395237a6cf40399af2a5c2e826cb)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/b1025349fd3bf3699df04c1a16340cdd4d45d854..f883b6df1928236efe9f0dc9bca2a048e1d8805a)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
samples
│  ├── bluetooth
│  │  ├── peripheral_power_profiling
│  │  │  ├── README.rst
│  │  │  ├── src
│  │  │  │  │ main.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-ble_samples

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-02 11:19 UTC, grochu approved these changes
Looks good to me

2024-12-02 11:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19186
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-02 11:54 UTC, peknis approved these changes

2024-12-02 14:17 UTC, peknis requested changes

2024-12-02 14:17 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  * Support for the :ref:`zephyr:nrf54h20dk_nrf54h20` board target in the :ref:`power_profiling` sample.
After all, this might be better be its own entry like:

* :ref:`power profiling` sample:

  * Added support for the ...

2024-12-03 06:47 UTC, peknis approved these changes

2024-12-03 08:18 UTC, merged