applications, samples, tests: use native YAML lists in twister config
nrfconnect/sdk-nrf pull request #19200
Opened 2024-12-02 14:52 UTC by gmarull

Support for space-separated lists has been deprecated for a while and it will be soon removed.

Automated using $ZEPHYR/scripts/utils/twister_to_list.py.

2024-12-02 14:55 UTC, rugeGerritsen commented
@gmarull , maybe you can split this PR into smaller PRs to avoid adding too many code owners at once?

2024-12-02 15:06 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [6eb2dfd2b9a42128c7476e41fed2df7cea082e7c](https://github.com/nrfconnect/sdk-nrf/pull/19200/commits/6eb2dfd2b9a42128c7476e41fed2df7cea082e7c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [6eb2dfd2b9a42128c7476e41fed2df7cea082e7c](https://github.com/nrfconnect/sdk-nrf/pull/19200/commits/6eb2dfd2b9a42128c7476e41fed2df7cea082e7c)
> merge base: [0da8ac9be16618ccc0cf6ca631eb9fac1dda6beb](https://github.com/nrfconnect/sdk-nrf/commit/0da8ac9be16618ccc0cf6ca631eb9fac1dda6beb)
> target head (main): [0da8ac9be16618ccc0cf6ca631eb9fac1dda6beb](https://github.com/nrfconnect/sdk-nrf/commit/0da8ac9be16618ccc0cf6ca631eb9fac1dda6beb)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/0da8ac9be16618ccc0cf6ca631eb9fac1dda6beb..6eb2dfd2b9a42128c7476e41fed2df7cea082e7c)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (452)</summary>

```
applications
│  ├── asset_tracker_v2
│  │  ├── sample.yaml
│  │  ├── tests
│  │  │  ├── debug_module
│  │  │  │  │ testcase.yaml
│  │  │  ├── json_common
│  │  │  │  │ testcase.yaml
│  │  │  ├── location_module
│  │  │  │  │ testcase.yaml
│  │  │  ├── lwm2m_codec_helpers
│  │  │  │  │ testcase.yaml
│  │  │  ├── lwm2m_integration
│  │  │  │  │ testcase.yaml
│  │  │  ├── nrf_cloud_codec
│  │  │  │  │ testcase.yaml
│  │  │  ├── nrf_cloud_codec_mocked_cjson
│  │  │  │  │ testcase.yaml
│  │  │  ├── ui_module
│  │  │  │  │ testcase.yaml
│  ├── connectivity_bridge
│  │  │ sample.yaml
│  ├── ipc_radio
│  │  │ sample.yaml
│  ├── machine_learning
│  │  │ sample.yaml
│  ├── matter_bridge
│  │  │ sample.yaml
│  ├── matter_weather_station
│  │  │ sample.yaml
│  ├── nrf5340_audio
│  │  │ sample.yaml
│  ├── nrf_desktop
│  │  │ sample.yaml
│  ├── sdp
│  │  ├── gpio
│  │  │  │ sample.yaml
│  ├── serial_lte_modem
│  │  │ sample.yaml
│  ├── zigbee_weather_station
│  │  │ sample.yaml
samples
│  ├── app_event_manager
│  │  │ sample.yaml
│  ├── app_event_manager_profiler_tracer
│  │  │ sample.yaml
│  ├── benchmarks
│  │  ├── coremark
│  │  │  │ sample.yaml
│  ├── bluetooth
│  │  ├── central_and_peripheral_hr
│  │  │  │ sample.yaml
│  │  ├── central_bas
│  │  │  │ sample.yaml
│  │  ├── central_hids
│  │  │  │ sample.yaml
│  │  ├── central_hr_coded
│  │  │  │ sample.yaml
│  │  ├── central_nfc_pairing
│  │  │  │ sample.yaml
│  │  ├── central_smp_client
│  │  │  │ sample.yaml
│  │  ├── central_uart
│  │  │  │ sample.yaml
│  │  ├── channel_sounding_ras_initiator
│  │  │  │ sample.yaml
│  │  ├── channel_sounding_ras_reflector
│  │  │  │ sample.yaml
│  │  ├── conn_time_sync
│  │  │  │ sample.yaml
│  │  ├── direct_test_mode
│  │  │  │ sample.yaml
│  │  ├── direction_finding_central
│  │  │  │ sample.yaml
│  │  ├── direction_finding_connectionless_rx
│  │  │  │ sample.yaml
│  │  ├── direction_finding_connectionless_tx
│  │  │  │ sample.yaml
│  │  ├── direction_finding_peripheral
│  │  │  │ sample.yaml
│  │  ├── enocean
│  │  │  │ sample.yaml
│  │  ├── event_trigger
│  │  │  │ sample.yaml
│  │  ├── fast_pair
│  │  │  ├── input_device
│  │  │  │  │ sample.yaml
│  │  │  ├── locator_tag
│  │  │  │  │ sample.yaml
│  │  ├── hci_lpuart
│  │  │  │ sample.yaml
│  │  ├── iso_combined_bis_and_cis
│  │  │  │ sample.yaml
│  │  ├── iso_time_sync
│  │  │  │ sample.yaml
│  │  ├── llpm
│  │  │  │ sample.yaml
│  │  ├── mesh
│  │  │  ├── ble_peripheral_lbs_coex
│  │  │  │  │ sample.yaml
│  │  │  ├── chat
│  │  │  │  │ sample.yaml
│  │  │  ├── dfu
│  │  │  │  ├── distributor
│  │  │  │  │  │ sample.yaml
│  │  │  │  ├── target
│  │  │  │  │  │ sample.yaml
│  │  │  ├── light
│  │  │  │  │ sample.yaml
│  │  │  ├── light_ctrl
│  │  │  │  │ sample.yaml
│  │  │  ├── light_dimmer
│  │  │  │  │ sample.yaml
│  │  │  ├── light_switch
│  │  │  │  │ sample.yaml
│  │  │  ├── sensor_client
│  │  │  │  │ sample.yaml
│  │  │  ├── sensor_server
│  │  │  │  │ sample.yaml
│  │  │  ├── silvair_enocean
│  │  │  │  │ sample.yaml
│  │  ├── multiple_adv_sets
│  │  │  │ sample.yaml
│  │  ├── nrf_auraconfig
│  │  │  │ sample.yaml
│  │  ├── nrf_dm
│  │  │  │ sample.yaml
│  │  ├── peripheral_ams_client
│  │  │  │ sample.yaml
│  │  ├── peripheral_ancs_client
│  │  │  │ sample.yaml
│  │  ├── peripheral_bms
│  │  │  │ sample.yaml
│  │  ├── peripheral_cgms
│  │  │  │ sample.yaml
│  │  ├── peripheral_cts_client
│  │  │  │ sample.yaml
│  │  ├── peripheral_gatt_dm
│  │  │  │ sample.yaml
│  │  ├── peripheral_hids_keyboard
│  │  │  │ sample.yaml
│  │  ├── peripheral_hids_mouse
│  │  │  │ sample.yaml
│  │  ├── peripheral_hr_coded
│  │  │  │ sample.yaml
│  │  ├── peripheral_lbs
│  │  │  │ sample.yaml
│  │  ├── peripheral_mds
│  │  │  │ sample.yaml
│  │  ├── peripheral_nfc_pairing
│  │  │  │ sample.yaml
│  │  ├── peripheral_power_profiling
│  │  │  │ sample.yaml
│  │  ├── peripheral_rscs
│  │  │  │ sample.yaml
│  │  ├── peripheral_status
│  │  │  │ sample.yaml
│  │  ├── peripheral_uart
│  │  │  │ sample.yaml
│  │  ├── radio_coex_1wire
│  │  │  │ sample.yaml
│  │  ├── radio_notification_cb
│  │  │  │ sample.yaml
│  │  ├── rpc_host
│  │  │  │ sample.yaml
│  │  ├── shell_bt_nus
│  │  │  │ sample.yaml
│  │  ├── subrating
│  │  │  │ sample.yaml
│  │  ├── throughput
│  │  │  │ sample.yaml
│  ├── bootloader
│  │  │ sample.yaml
│  ├── caf
│  │  │ sample.yaml
│  ├── caf_sensor_manager
│  │  │ sample.yaml
│  ├── cellular
│  │  ├── at_client
│  │  │  │ sample.yaml
│  │  ├── at_monitor
│  │  │  │ sample.yaml
│  │  ├── battery
│  │  │  │ sample.yaml
│  │  ├── ciphersuites
│  │  │  │ sample.yaml
│  │  ├── fmfu_smp_svr
│  │  │  │ sample.yaml
│  │  ├── gnss
│  │  │  │ sample.yaml
│  │  ├── http_update
│  │  │  ├── application_update
│  │  │  │  │ sample.yaml
│  │  │  ├── modem_delta_update
│  │  │  │  │ sample.yaml
│  │  │  ├── modem_full_update
│  │  │  │  │ sample.yaml
│  │  ├── location
│  │  │  │ sample.yaml
│  │  ├── lte_ble_gateway
│  │  │  │ sample.yaml
│  │  ├── lwm2m_carrier
│  │  │  │ sample.yaml
│  │  ├── lwm2m_client
│  │  │  │ sample.yaml
│  │  ├── modem_callbacks
│  │  │  │ sample.yaml
│  │  ├── modem_shell
│  │  │  │ sample.yaml
│  │  ├── modem_trace_backend
│  │  │  │ sample.yaml
│  │  ├── modem_trace_flash
│  │  │  │ sample.yaml
│  │  ├── nidd
│  │  │  │ sample.yaml
│  │  ├── nrf_cloud_multi_service
│  │  │  │ sample.yaml
│  │  ├── nrf_cloud_rest_cell_location
│  │  │  │ sample.yaml
│  │  ├── nrf_cloud_rest_device_message
│  │  │  │ sample.yaml
│  │  ├── nrf_cloud_rest_fota
│  │  │  │ sample.yaml
│  │  ├── nrf_provisioning
│  │  │  │ sample.yaml
│  │  ├── pdn
│  │  │  │ sample.yaml
│  │  ├── slm_shell
│  │  │  │ sample.yaml
│  │  ├── smp_svr
│  │  │  │ sample.yaml
│  │  ├── sms
│  │  │  │ sample.yaml
│  │  ├── udp
│  │  │  │ sample.yaml
│  │  ├── uicc_lwm2m
│  │  │  │ sample.yaml
│  ├── crypto
│  │  ├── aes_cbc
│  │  │  │ sample.yaml
│  │  ├── aes_ccm
│  │  │  │ sample.yaml
│  │  ├── aes_ctr
│  │  │  │ sample.yaml
│  │  ├── aes_gcm
│  │  │  │ sample.yaml
│  │  ├── chachapoly
│  │  │  │ sample.yaml
│  │  ├── ecdh
│  │  │  │ sample.yaml
│  │  ├── ecdsa
│  │  │  │ sample.yaml
│  │  ├── ecjpake
│  │  │  │ sample.yaml
│  │  ├── eddsa
│  │  │  │ sample.yaml
│  │  ├── hkdf
│  │  │  │ sample.yaml
│  │  ├── hmac
│  │  │  │ sample.yaml
│  │  ├── pbkdf2
│  │  │  │ sample.yaml
│  │  ├── persistent_key_usage
│  │  │  │ sample.yaml
│  │  ├── psa_tls
│  │  │  │ sample.yaml
│  │  ├── rng
│  │  │  │ sample.yaml
│  │  ├── rsa
│  │  │  │ sample.yaml
│  │  ├── sha256
│  │  │  │ sample.yaml
│  │  ├── spake2p
│  │  │  │ sample.yaml
│  ├── debug
│  │  ├── memfault
│  │  │  │ sample.yaml [...]

2024-12-02 15:10 UTC, rugeGerritsen approved these changes
Tip for others that want to look for the files they care about:
![image](https://github.com/user-attachments/assets/2be83717-235d-4441-b311-682e0533966a)

2024-12-02 15:26 UTC, 57300 approved these changes

2024-12-02 15:32 UTC, eivindj-nordic approved these changes

2024-12-02 15:32 UTC, eivindj-nordic commented on samples/cellular/gnss/sample.yaml
>    # Following configurations will be used by the positioning CI integration job to verify PRs
nit: This comment should be moved after the tag entries.

2024-12-02 16:08 UTC, masz-nordic approved these changes

2024-12-02 21:53 UTC, plskeggs approved these changes

2024-12-03 02:09 UTC, trantanen requested changes
It seems the script adds comments that were after the list label, right after the label and before the list

2024-12-03 08:40 UTC, tomchy requested changes

2024-12-03 08:40 UTC, tomchy commented on samples/suit/smp_transfer/sample.yaml
> +      - suit
I think lines 17, 24, 32, 41, 57, 65, 85, 102 should be removed

2024-12-03 08:45 UTC, hubertmis approved these changes

2024-12-03 09:18 UTC, muraliThokala approved these changes

2024-12-03 09:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19200
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-03 10:17 UTC, SeppoTakalo approved these changes

2024-12-03 10:39 UTC, trantanen approved these changes

2024-12-03 10:40 UTC, nordicjm approved these changes

2024-12-03 10:59 UTC, tokangas approved these changes

2024-12-03 15:58 UTC, tomchy approved these changes

2024-12-04 08:31 UTC, Balaklaka approved these changes

2024-12-04 08:56 UTC, kacperradoszewski commented on applications/serial_lte_modem/sample.yaml
>    applications.serial_lte_modem.lwm2m_carrier.lgu:
The `extra_args` list under `applications.serial_lte_modem.lwm2m_carrier.lgu` is still space-separated

2024-12-04 09:04 UTC, kacperradoszewski approved these changes

2024-12-04 15:41 UTC, nordic-segl commented on tests/drivers/pwm/gpio_loopback/testcase.yaml
Empty lines are in wrong place. Shall be before test configuration (or remove if it makes problems).
See
https://github.com/nrfconnect/sdk-nrf/blob/60c47c50d039d17f5ae2d0acf9a6fc9d7df3b5b3/tests/drivers/pwm/gpio_loopback/testcase.yaml#L27

2024-12-04 15:44 UTC, nordic-segl commented on tests/benchmarks/power_consumption/timer_waiting/testcase.yaml
Empty line in a wrong place. Shall be after list of tags.

2024-12-04 15:45 UTC, nordic-segl commented on tests/benchmarks/power_consumption/gpio/testcase.yaml
Empty line in a wrong place

2024-12-04 15:45 UTC, nordic-segl commented on tests/benchmarks/power_consumption/i2c/testcase.yaml
Empty line in a wrong place

2024-12-04 15:45 UTC, nordic-segl commented on tests/benchmarks/power_consumption/lpcomp/testcase.yaml
Empty line in a wrong place

2024-12-04 15:46 UTC, nordic-segl commented on tests/benchmarks/power_consumption/flash/testcase.yaml
Empty line in a wrong place

2024-12-04 15:46 UTC, nordic-segl commented on tests/benchmarks/power_consumption/adc_async/testcase.yaml
Empty line in a wrong place

2024-12-04 15:46 UTC, nordic-segl commented on tests/benchmarks/power_consumption/adc/testcase.yaml
Empty line in a wrong place

2024-12-04 15:47 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_twim/testcase.yaml
Empty line in a wrong place

2024-12-04 15:47 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_uarte/testcase.yaml
Empty line in a wrong place

2024-12-04 15:47 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_usb/testcase.yaml
Empty line in a wrong place

2024-12-04 15:48 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_spim/testcase.yaml
Empty line in a wrong place

2024-12-04 15:49 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_outside_of_main/testcase.yaml
Empty line in a wrong place

2024-12-04 15:49 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
Empty line in a wrong place

2024-12-04 15:50 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_comp/testcase.yaml
Empty line in a wrong place

2024-12-04 15:50 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_clock_control/testcase.yaml
Empty line in a wrong place

2024-12-04 15:50 UTC, nordic-segl commented on tests/benchmarks/multicore/idle_adc/testcase.yaml
Empty line in a wrong place

2024-12-04 15:50 UTC, nordic-segl commented on tests/benchmarks/multicore/idle/testcase.yaml
Empty line in a wrong place

2024-12-04 15:50 UTC, nordic-segl commented on tests/benchmarks/multicore/idle/testcase.yaml
Empty line in a wrong place

2024-12-04 15:51 UTC, nordic-segl commented on tests/benchmarks/multicore/idle/testcase.yaml
Empty line in a wrong place

2024-12-04 15:51 UTC, nordic-segl commented on tests/benchmarks/current_consumption/uart_idle/testcase.yaml
Empty line in a wrong place

2024-12-04 15:52 UTC, nordic-segl commented on tests/benchmarks/current_consumption/system_off/testcase.yaml
Empty line in a wrong place

2024-12-04 15:52 UTC, nordic-segl commented on tests/benchmarks/current_consumption/nfc_idle/testcase.yaml
Empty line in a wrong place

2024-12-04 15:52 UTC, nordic-segl commented on tests/benchmarks/current_consumption/multicore_system_off/testcase.yaml
Empty line in a wrong place

2024-12-04 15:52 UTC, nordic-segl commented on tests/benchmarks/current_consumption/grtc_idle/testcase.yaml
Empty line in a wrong place

2024-12-05 08:15 UTC, nordic-segl approved these changes

2024-12-05 09:54 UTC, nordic-auko approved these changes

2024-12-05 15:42 UTC, MirkoCovizzi approved these changes

2024-12-10 07:13 UTC, nordic-segl approved these changes

2024-12-10 07:50 UTC, maciejbaczmanski approved these changes

2024-12-10 09:42 UTC, leewkb4567 approved these changes

2024-12-10 09:48 UTC, ankuns approved these changes

2024-12-11 11:46 UTC, tejlmand approved these changes
nice cleanup, but I wonder why this is critical for NCS 2.9.0 ?

2024-12-11 14:50 UTC, PerMac approved these changes

2024-12-11 14:52 UTC, shanthanordic commented
should be the first PR to be merged after releases.

2024-12-13 14:47 UTC, koffes approved these changes

2025-01-07 07:18 UTC, nordic-segl approved these changes

2025-01-07 08:25 UTC, Vge0rge approved these changes

2025-01-07 11:24 UTC, magnev commented on samples/crypto/aes_cbc/sample.yaml
>        nrf54h20dk/nrf54h20/cpuapp
crypto samples does not use YAML lists for 54h20 target

2025-01-07 11:30 UTC, MarkusLassila approved these changes

2025-01-07 11:43 UTC, gmarull commented on samples/crypto/aes_cbc/sample.yaml
>        nrf54h20dk/nrf54h20/cpuapp
This format is still supported. It is allowed to have strings for single items.

2025-01-07 15:21 UTC, kapi-no approved these changes

2025-01-08 10:53 UTC, anangl approved these changes

2025-01-08 11:21 UTC, bama-nordic approved these changes

2025-01-08 14:34 UTC, merged