doc: Move Thingy:91 and Thingy:91 x under application development
nrfconnect/sdk-nrf pull request #19202
Opened 2024-12-02 16:41 UTC by divipillai

Moved Thingy:91 and Thingy:91 x under application development.

2024-12-02 16:45 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :white_medium_square: Toolchain
- :white_medium_square: Build twister
- :white_medium_square: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-12-03 16:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19202
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-04 09:17 UTC, umapraseeda requested changes

2024-12-04 09:17 UTC, umapraseeda commented on doc/_zoomin/ncs.tags.yml
> +  - nrf/app_dev/device_guides/thingy91x/*.html: ["thingy91x", "prototyping-platforms"]
nrf91 series tag could be added

2024-12-04 11:03 UTC, bjornspock commented on doc/nrf/app_dev/device_guides/thingy91x/thingy91x_features.rst
> +Nordic Thingy:91 X is an advanced version of the Thingy:91.
Thingy:91 and THingy:91 X are two destinct products, so I dont think we should state that the Thingy:91 X is an advanced version of the Thingy:91. Suggest replacing the sentence with the following:

"Nordic Thingy:91 X is a battery-operated prototyping platform for cellular IoT. "

2024-12-05 08:03 UTC, umapraseeda approved these changes

2024-12-05 08:19 UTC, martiles approved these changes

2024-12-05 12:10 UTC, greg-fer approved these changes
Checked the doc preview and it looks OK!

2024-12-06 09:20 UTC, divipillai commented
The compliance error is because of the image size of existing images. I think we could override this compliance check?

2024-12-06 10:06 UTC, merged

2024-12-09 08:16 UTC, FrancescoSer approved these changes