doc: nrf: bluetooth: RAS RREQ and RRSP docs
nrfconnect/sdk-nrf pull request #19230
Opened 2024-12-03 16:05 UTC by weeTike

This adds documentation for the Ranging Service Ranging Responder and Ranging Requestor.

2024-12-03 16:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19230
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-03 16:43 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [5c87cf6b4d5e8ed28b0240dbe49b0c42d7597644](https://github.com/nrfconnect/sdk-nrf/pull/19230/commits/5c87cf6b4d5e8ed28b0240dbe49b0c42d7597644)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [5c87cf6b4d5e8ed28b0240dbe49b0c42d7597644](https://github.com/nrfconnect/sdk-nrf/pull/19230/commits/5c87cf6b4d5e8ed28b0240dbe49b0c42d7597644)
> merge base: [09228a59365ab09daab2c6050044d6c9cf065ea1](https://github.com/nrfconnect/sdk-nrf/commit/09228a59365ab09daab2c6050044d6c9cf065ea1)
> target head (main): [e2cfdfd0f4c8b30e89463b7f421b4e27f2f1f35e](https://github.com/nrfconnect/sdk-nrf/commit/e2cfdfd0f4c8b30e89463b7f421b4e27f2f1f35e)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/09228a59365ab09daab2c6050044d6c9cf065ea1..5c87cf6b4d5e8ed28b0240dbe49b0c42d7597644)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── libraries
│  │  │  ├── bluetooth
│  │  │  │  ├── services
│  │  │  │  │  ├── rreq.rst
│  │  │  │  │  │ rrsp.rst
│  │  │ links.txt
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-04 06:40 UTC, peknis requested changes

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +- On Demand Ranging Data
```suggestion
The library supports On Demand Ranging Data.
```
The Supported features heading could be left out.

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Enable RREQ and RRSP kconfig options using the :kconfig:option:`CONFIG_BT_RAS` kconfig option.
```suggestion
To enable the RREQ and RRSP Kconfig options, use :kconfig:option:`CONFIG_BT_RAS`.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Set the maximum number of antenna paths supported by the device using the :kconfig:option:`CONFIG_BT_RAS_MAX_ANTENNA_PATHS` kconfig option.
```suggestion
Set the maximum number of antenna paths supported by the device using the :kconfig:option:`CONFIG_BT_RAS_MAX_ANTENNA_PATHS` Kconfig option.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +This sets the antenna paths per step that can be stored inside the Ranging Service.
```suggestion
This sets the antenna paths for each step that can be stored inside the Ranging Service.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Set support for storing Mode 3 Channel Sounding steps using the :kconfig:option:`CONFIG_BT_RAS_MODE_3_SUPPORTED` kconfig option.
```suggestion
To set support for storing Mode 3 Channel Sounding steps, use the :kconfig:option:`CONFIG_BT_RAS_MODE_3_SUPPORTED` Kconfig option.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Enable RREQ kconfig options using the :kconfig:option:`CONFIG_BT_RAS_RREQ` kconfig option.
```suggestion
To enable the RREQ Kconfig options, use :kconfig:option:`CONFIG_BT_RAS_RREQ`.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Set the number of simultaneously supported RREQ instances using the :kconfig:option:`CONFIG_BT_RAS_RREQ_MAX_ACTIVE_CONN` kconfig option.
```suggestion
To set the number of simultaneously supported RREQ instances, use the :kconfig:option:`CONFIG_BT_RAS_RREQ_MAX_ACTIVE_CONN` Kconfig option.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +Set the logging level of the RREQ library using the :kconfig:option:`CONFIG_BT_RAS_RREQ_LOG_LEVEL` Kconfig option.
```suggestion
To set the heap size for the GATT distance measurement module, use the :kconfig:option:`CONFIG_HEAP_MEM_POOL_ADD_SIZE_RAS_RREQ_GATT_DM` Kconfig option.

To set the logging level of the RREQ library, use the :kconfig:option:`CONFIG_BT_RAS_RREQ_LOG_LEVEL` Kconfig option.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +The RREQ can be setup as either a Channel Sounding Initiator or Reflector.
```suggestion
You can set up the RREQ either as a Channel Sounding Initiator or Reflector.
```

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rrsp.rst
> +- On Demand Ranging Data
```suggestion
The library supports On Demand Ranging Data.
```
You could leave out the Supported features heading also here.

2024-12-04 06:40 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rrsp.rst
> +Configuration
Do the same adjustments as in the other library doc. This PR also needs a changelog entry.

2024-12-04 08:17 UTC, umapraseeda commented on doc/nrf/libraries/bluetooth/services/rrsp.rst
> +Set the logging level of the RRSP library using the :kconfig:option:`CONFIG_BT_RAS_RRSP_LOG_LEVEL` Kconfig option.
May be a bulleted list might be beneficial here in this section (in both libraries) :
Example: 
:kconfig:option:`CONFIG_BT_RAS_RRSP_RD_BUFFERS_PER_CONN`  - Sets the number of ranging data buffers per connection.
and so on.

2024-12-04 11:32 UTC, nordicjm reviewed
commit should be lowercase for the areas and not have subsys and have the right area e.g. `doc: nrf: bluetooth: Add documentation for RREQ`

2024-12-04 14:15 UTC, peknis requested changes

2024-12-04 14:15 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +
```suggestion
* Added the :ref:`rreq_readme` and :ref:`rrsp_readme` libraries.
```
Like this, but remove the changelog entry from this PR and add it as a suggestion to my https://github.com/nrfconnect/sdk-nrf/pull/19240.

2024-12-04 14:15 UTC, peknis commented on doc/nrf/libraries/bluetooth/services/rrsp.rst
> +* :kconfig:option:`CONFIG_BT_RAS` - Enables RREQ and RRSP Kconfig options.
```suggestion
To enable this library, use the :kconfig:option:`CONFIG_BT_RAS` Kconfig option.

Check and adjust also the following Kconfig options:
```

2024-12-04 14:16 UTC, sean-madigan commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +  This affects the per-instance memory usage of the Ranging Service.
This doesn't really apply for rreq. Would maybe just keep the first line

2024-12-04 14:18 UTC, sean-madigan commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +| See the sample: :file:`samples/bluetooth/channel_sounding_ras_reflector`
```suggestion
```

Only top sample is valid

2024-12-04 15:17 UTC, peknis approved these changes

2024-12-04 15:21 UTC, sean-madigan commented on doc/nrf/libraries/bluetooth/services/rreq.rst
> +To enable this library, use the :kconfig:option:`CONFIG_BT_RAS` Kconfig option.
```suggestion
To enable this library, use the :kconfig:option:`CONFIG_BT_RAS` and :kconfig:option:`CONFIG_BT_RAS_RREQ` Kconfig options.
```
Maybe this makes more sense

2024-12-04 16:30 UTC, carlescufi approved these changes

2024-12-04 16:31 UTC, merged