samples: bluetooth: mesh: Add nrf54l05 and nrf54l10 targets
nrfconnect/sdk-nrf pull request #19327
Opened 2024-12-06 15:03 UTC by m-alperen-sener

Adding supported targets to mesh samples.

2024-12-06 15:06 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-12-06 15:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19327
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-09 10:18 UTC, PavelVPV approved these changes

2024-12-09 12:33 UTC, Balaklaka requested changes
There should be something in release notes about adding nrf54l10/05 under Bluetooth Mesh samples.

2024-12-09 13:40 UTC, m-alperen-sener commented on scripts/quarantine_integration.yaml
> +    - nrf54l15dk/nrf54l10/cpuapp
> nrf52840dk/nrf52840 is in this list.

the board is tested through the dfu variant.

> Why is not nrf54l15dk/nrf54l15/cpuapp not in the list? There is more of the same other places.

I think when the board first added it is not restricted on integration for any sample. We can consider it now.

2024-12-09 14:10 UTC, m-alperen-sener commented
> There should be something in release notes about adding nrf54l10/05 under Bluetooth Mesh samples.

Requested here:
https://github.com/nrfconnect/sdk-nrf/pull/19240#discussion_r1876041596

2024-12-10 09:15 UTC, Balaklaka approved these changes

2024-12-10 10:54 UTC, ardo-nordic approved these changes
Looks alright to me, except for somewhat inconsistent formatting of platforms lists in yaml files, which isn't a big deal I guess.

2024-12-10 11:17 UTC, jukkar approved these changes

2024-12-10 11:18 UTC, merged