Add support for multiple Doxygen projects, add wifi bridge
nrfconnect/sdk-nrf pull request #19341
Opened 2024-12-09 11:54 UTC by gmarull

See commits for more details.

2024-12-09 11:56 UTC, NordicBuilder commented
The following west manifest projects have changed revision in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/a7fe5f7c4aab18312bd7f61afef55647e38f3db6 | https://github.com/nrfconnect/sdk-zephyr/pull/2347 | [nrfconnect/sdk-zephyr#2347/files](https://github.com/nrfconnect/sdk-zephyr/pull/2347/files) |

⛔ **DNM label due to: 1 project with PR revision**

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-12-09 11:57 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-12-09 12:33 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19341
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2025-01-16 14:51 UTC, gmarull commented
> Index looks funny, can you please check?
> 
> ![image](https://private-user-images.githubusercontent.com/100136718/403857638-a39e6a65-270c-4356-8cb4-2d3bf3e549b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMzkzNDIsIm5iZiI6MTczNzAzOTA0MiwicGF0aCI6Ii8xMDAxMzY3MTgvNDAzODU3NjM4LWEzOWU2YTY1LTI3MGMtNDM1Ni04Y2I0LTJkM2JmM2U1NDliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNDUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWYyYmMyYmEyODNhM2Y0NGZkODE5OWI5MzRjNTljYmI1OWJhZjIzODAyYjFkYjRkOWViMzcwNjQ4MjQzOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2bVIoJxj94X9ZPAy381t09Ug54RDztu0zQ-HdrxjJeM)

yup, this was just a demo, I don;t know where rst files should be placed..

2025-01-16 15:22 UTC, krish2718 commented
> > Index looks funny, can you please check?
> > ![image](https://private-user-images.githubusercontent.com/100136718/403857638-a39e6a65-270c-4356-8cb4-2d3bf3e549b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMzkzNDIsIm5iZiI6MTczNzAzOTA0MiwicGF0aCI6Ii8xMDAxMzY3MTgvNDAzODU3NjM4LWEzOWU2YTY1LTI3MGMtNDM1Ni04Y2I0LTJkM2JmM2U1NDliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNDUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWYyYmMyYmEyODNhM2Y0NGZkODE5OWI5MzRjNTljYmI1OWJhZjIzODAyYjFkYjRkOWViMzcwNjQ4MjQzOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2bVIoJxj94X9ZPAy381t09Ug54RDztu0zQ-HdrxjJeM)
> 
> yup, this was just a demo, I don;t know where rst files should be placed..

Under the API documentation. Also, can we now open this PR and get it merged?

2025-01-16 15:25 UTC, gmarull commented
> > > Index looks funny, can you please check?
> > > ![image](https://private-user-images.githubusercontent.com/100136718/403857638-a39e6a65-270c-4356-8cb4-2d3bf3e549b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMzkzNDIsIm5iZiI6MTczNzAzOTA0MiwicGF0aCI6Ii8xMDAxMzY3MTgvNDAzODU3NjM4LWEzOWU2YTY1LTI3MGMtNDM1Ni04Y2I0LTJkM2JmM2U1NDliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNDUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWYyYmMyYmEyODNhM2Y0NGZkODE5OWI5MzRjNTljYmI1OWJhZjIzODAyYjFkYjRkOWViMzcwNjQ4MjQzOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2bVIoJxj94X9ZPAy381t09Ug54RDztu0zQ-HdrxjJeM)
> > 
> > 
> > yup, this was just a demo, I don;t know where rst files should be placed..
> 
> Under the API documentation. Also, can we now open this PR and get it merged?

After upmerge

2025-01-31 11:16 UTC, richabp requested changes

2025-01-31 11:16 UTC, richabp commented on doc/nrf/drivers/wifi/low_api_wifi.rst
> +The Wi-Fi mode is used for normal operation of the nRF70 Series device in, for example, STA mode or other modes that are supported in the future.
```suggestion
The Wi-Fi mode is used for the normal operation of the nRF70 Series device in the :abbr:`STA (Station)` mode or other modes that will be supported in the future.
```

2025-02-14 09:10 UTC, richabp commented on doc/nrf/drivers/wifi/low_api_wifi.rst
> +The Wi-Fi mode is used for normal operation of the nRF70 Series device in, for example, STA mode or other modes that are supported in the future.
This suggestion seems to be missed.

2025-02-14 10:52 UTC, gmarull commented on doc/_zoomin/wifi.apis.custom.properties
> +booktitle=wifi APIs - __VERSION__
done

2025-02-14 13:43 UTC, richabp approved these changes

2025-02-14 14:29 UTC, gmarull commented
ping @nrfconnect/ncs-ci @nrfconnect/ncs-co-build-system @nrfconnect/ncs-co-doc @nrfconnect/ncs-code-owners @nrfconnect/ncs-doc-leads

2025-02-17 07:53 UTC, nordicjm approved these changes

2025-02-17 08:23 UTC, gmarull commented
@nrfconnect/ncs-ci, @nrfconnect/ncs-co-doc, @nrfconnect/ncs-doc-leads ping

2025-02-17 08:33 UTC, umapraseeda approved these changes

2025-02-17 09:21 UTC, carlescufi approved these changes

2025-02-17 09:22 UTC, merged