bootloader: Add support for cleaning up RAM before application boot
nrfconnect/sdk-nrf pull request #19365
Opened 2024-12-10 08:46 UTC by nordicjm

Also enables by default on nRF54L15 SoC's

NCSDK-29767

2024-12-10 08:58 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
sdk-nrf: PR head: [19cb2cfb342673503442b4ba11c311857e7bca21](https://github.com/nrfconnect/sdk-nrf/pull/19365/commits/19cb2cfb342673503442b4ba11c311857e7bca21)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [19cb2cfb342673503442b4ba11c311857e7bca21](https://github.com/nrfconnect/sdk-nrf/pull/19365/commits/19cb2cfb342673503442b4ba11c311857e7bca21)
> merge base: [568a7d4cdebd5b1bfb1e52ddd6c9daf9ceb16cc4](https://github.com/nrfconnect/sdk-nrf/commit/568a7d4cdebd5b1bfb1e52ddd6c9daf9ceb16cc4)
> target head (main): [c5d87cebe4df74ec470e9f0a776630d24e43afda](https://github.com/nrfconnect/sdk-nrf/commit/c5d87cebe4df74ec470e9f0a776630d24e43afda)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/568a7d4cdebd5b1bfb1e52ddd6c9daf9ceb16cc4..19cb2cfb342673503442b4ba11c311857e7bca21)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
samples
│  ├── bootloader
│  │  ├── socs
│  │  │  │ nrf54l15_cpuapp.conf
subsys
│  ├── bootloader
│  │  ├── Kconfig
│  │  ├── bl_boot
│  │  │  │ bl_boot.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-mcuboot
   - :warning: test-fw-nrfconnect-fw-update
   - :warning: test-fw-nrfconnect-nrf-iot_cloud

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-thread
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-pmic-samples
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-10 09:01 UTC, michalek-no approved these changes

2024-12-10 09:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19365
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-10 10:28 UTC, de-nordic approved these changes

2024-12-10 11:06 UTC, gchwier requested changes
failed tests,
`west build -p -b nrf54l15dk/nrf54l15/cpuapp tests/subsys/bootloader/boot_chains -T boot_chains.secure_boot_and_bootloader_mcuboot -d build-54l-boot`

`west flash --skip-rebuild -d build-54l-boot --recover`
received
```
Attempting to boot slot 0.
Attempting to boot from address 0x8800.
I: Trying to get Firmware version
I: Verifying signature against key 0.
I: Hash: 0xa0...34
I: Firmware signature verified.
Firmware version 1
I: Setting monotonic counter (version: 1, slot: 0)
ERROR: Cannot fulfill EXT_API request.
```

2024-12-10 11:35 UTC, nordicjm commented
Fixed, though this option cannot be enabled/used until ed25519 support is added

2024-12-12 12:23 UTC, nordicjm commented
@tejlmand please review

2024-12-12 12:49 UTC, tejlmand approved these changes

2024-12-12 12:51 UTC, merged