doc: Doc fixes for 2.9
nrfconnect/sdk-nrf pull request #19442
Opened 2024-12-11 14:25 UTC by umapraseeda

Doc check and fixes for 2.9
NCSDK-30694

2024-12-11 14:39 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
sdk-nrf: PR head: [47409e75d4a9edac1b8e924609907e080e6ad971](https://github.com/nrfconnect/sdk-nrf/pull/19442/commits/47409e75d4a9edac1b8e924609907e080e6ad971)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [47409e75d4a9edac1b8e924609907e080e6ad971](https://github.com/nrfconnect/sdk-nrf/pull/19442/commits/47409e75d4a9edac1b8e924609907e080e6ad971)
> merge base: [e28af5e0cff6bde826d37613685c8c30ca1905d3](https://github.com/nrfconnect/sdk-nrf/commit/e28af5e0cff6bde826d37613685c8c30ca1905d3)
> target head (main): [c43a9ee4b4f20161b4d364c02e0540b04cd582d9](https://github.com/nrfconnect/sdk-nrf/commit/c43a9ee4b4f20161b4d364c02e0540b04cd582d9)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/e28af5e0cff6bde826d37613685c8c30ca1905d3..47409e75d4a9edac1b8e924609907e080e6ad971)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (114)</summary>

```
applications
│  ├── asset_tracker_v2
│  │  ├── doc
│  │  │  ├── asset_tracker_v2_description.rst
│  │  │  ├── cloud_wrapper.rst
│  │  │  ├── data_module.rst
│  │  │  │ location_module.rst
│  ├── matter_bridge
│  │  ├── README.rst
│  │  ├── doc
│  │  │  ├── adding_ble_bridged_device_service.rst
│  │  │  ├── adding_bridged_matter_device.rst
│  │  │  ├── adding_bridged_protocol.rst
│  │  │  │ matter_bridge_description.rst
│  ├── matter_weather_station
│  │  │ README.rst
│  ├── nrf_desktop
│  │  ├── application_kconfig.rst
│  │  ├── bluetooth.rst
│  │  ├── board_configuration.rst
│  │  ├── doc
│  │  │  ├── bas.rst
│  │  │  ├── ble_adv.rst
│  │  │  ├── ble_passkey.rst
│  │  │  │ ble_qos.rst
│  ├── serial_lte_modem
│  │  ├── doc
│  │  │  ├── GNSS_AT_commands.rst
│  │  │  │ NRFCLOUD_AT_commands.rst
doc
│  ├── _utils
│  │  │ redirects.py
│  ├── _zoomin
│  │  │ ncs.tags.yml
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── bootloaders_dfu
│  │  │  │  ├── mcuboot_nsib
│  │  │  │  │  ├── bootloader_adding_sysbuild.rst
│  │  │  │  │  │ bootloader_quick_start.rst
│  │  │  ├── config_and_build
│  │  │  │  ├── cmake
│  │  │  │  │  │ index.rst
│  │  │  │  ├── sysbuild
│  │  │  │  │  │ sysbuild_images.rst
│  │  │  ├── device_guides
│  │  │  │  ├── fem
│  │  │  │  │  │ 21540ek_dev_guide.rst
│  │  │  │  ├── nrf53
│  │  │  │  │  │ building_nrf53.rst
│  │  │  │  ├── nrf54h
│  │  │  │  │  │ ug_nrf54h20_suit_customize_dfu.rst
│  │  │  │  ├── nrf54l
│  │  │  │  │  │ fota_update.rst
│  │  │  │  ├── nrf70
│  │  │  │  │  ├── power_profiling.rst
│  │  │  │  │  │ stack_partitioning.rst
│  │  │  │  │ wifi_coex.rst
│  │  ├── drivers
│  │  │  ├── wifi
│  │  │  │  │ nrf70_portable.rst
│  │  ├── external_comp
│  │  │  ├── avsystem.rst
│  │  │  │ nrf_cloud.rst
│  │  ├── glossary.rst
│  │  ├── includes
│  │  │  │ zigbee_deprecation.txt
│  │  ├── libraries
│  │  │  ├── bin
│  │  │  │  ├── lwm2m_carrier
│  │  │  │  │  │ msc.rst
│  │  │  ├── bluetooth
│  │  │  │  │ adv_prov.rst
│  │  │  ├── caf
│  │  │  │  ├── ble_adv.rst
│  │  │  │  ├── ble_bond.rst
│  │  │  │  │ ble_state.rst
│  │  │  ├── dfu
│  │  │  │  │ dfu_multi_image.rst
│  │  │  ├── gazell
│  │  │  │  │ gzp.rst
│  │  │  ├── modem
│  │  │  │  │ location.rst
│  │  │  ├── networking
│  │  │  │  ├── lwm2m_location_assistance.rst
│  │  │  │  ├── nrf_cloud.rst
│  │  │  │  ├── nrf_cloud_location.rst
│  │  │  │  ├── nrf_cloud_log.rst
│  │  │  │  ├── ot_rpc.rst
│  │  │  │  ├── wifi_credentials.rst
│  │  │  │  │ wifi_mgmt_ext.rst
│  │  │  ├── others
│  │  │  │  │ dm.rst
│  │  │  ├── security
│  │  │  │  │ fatal_error.rst
│  │  │  ├── zigbee
│  │  │  │  ├── zigbee_fota.rst
│  │  │  │  │ zigbee_zcl_scenes.rst
│  │  ├── links.txt
│  │  ├── protocols
│  │  │  ├── coexistence
│  │  │  │  │ index.rst
│  │  │  ├── gazell
│  │  │  │  │ gzll.rst
│  │  │  ├── matter
│  │  │  │  ├── end_product
│  │  │  │  │  ├── certification.rst
│  │  │  │  │  ├── ecosystems_certification.rst
│  │  │  │  │  │ security.rst
│  │  │  │  ├── getting_started
│  │  │  │  │  ├── adding_clusters.rst
│  │  │  │  │  ├── advanced_kconfigs.rst
│  │  │  │  │  ├── ecosystem_compatibility_testing.rst
│  │  │  │  │  ├── hw_requirements.rst
│  │  │  │  │  ├── index.rst
│  │  │  │  │  ├── low_power_configuration.rst
│  │  │  │  │  ├── matter_api.rst
│  │  │  │  │  ├── memory_optimization.rst
│  │  │  │  │  ├── testing
│  │  │  │  │  │  ├── index.rst
│  │  │  │  │  │  ├── thread_separate_otbr_linux_macos.rst
│  │  │  │  │  │  │ wifi_pc.rst
│  │  │  │  ├── index.rst
│  │  │  │  ├── overview
│  │  │  │  │  ├── architecture.rst
│  │  │  │  │  ├── commissioning.rst
│  │  │  │  │  ├── dev_model.rst
│  │  │  │  │  ├── integration.rst
│  │  │  │  │  │ network_topologies.rst
│  │  │  ├── thread
│  │  │  │  ├── overview
│  │  │  │  │  │ commissioning.rst
│  │  │  │  │ tools.rst
│  │  │  ├── wifi
│  │  │  │  ├── advanced_modes
│  │  │  │  │  ├── offloaded_raw_tx.rst
│  │  │  │  │  ├── promiscuous_operation.rst
│  │  │  │  │  ├── raw_tx_operation.rst
│  │  │  │  │  │ sniffer_rx_operation.rst
│  │  │  │  ├── station_mode
│  │  │  │  │  │ powersave.rst
│  │  ├── releases_and_maturity
│  │  │  ├── migration
│  │  │  │  ├── 2.4.99-cs3_to_2.6.99-cs2
│  │  │  │  │  │ migration_guide_2.4.99-cs3_to_2.6.99-cs2_application.rst
│  │  │  │  ├── migration_guide_2.7.rst
│  │  │  │  ├── nRF54H20_migration_2.7
│  │  │  │  │  │ migration_guide_2.4.99-cs3_to_2.7_application.rst
│  │  │  │ software_maturity.rst
│  │  ├── samples
│  │  │  ├── bl.rst
│  │  │  ├── matter.rst
│  │  │  │ wifi.rst
│  │  ├── test_and_optimize
│  │  │  ├── optimizing
│  │  │  │  ├── memory.rst
│  │  │  │  │ power_general.rst
samples
│  ├── bluetooth
│  │  ├── nrf_auraconfig
│  │  │  │ README.rst
│  │  ├── peripheral_hids_mouse
│  │  │  │ README.rst
│  ├── cellular
│  │  ├── location
│  │  │  │ README.rst
│  │  ├── lwm2m_client
│  │  │  │ sample_description.rst
│  │  ├── modem_shell
│  │  │  │ README.rst
│  │  ├── modem_trace_flash
│  │  │  │ README.rst
│  │  ├── nrf_cloud_multi_service
│  │  │  │ README.rst
│  │  ├── nrf_cloud_rest_cell_location
│  │  │  │ README.rst
│  ├── matter
│  │  ├── light_bulb
│  │  │  │ README.rst
│  │  ├── light_switch
│  │  │  │ README.rst
│  │  ├── lock
│  │  │  │ README.rst
│  │  ├── template
│  │  │  │ README.rst
│  │  ├── thermostat
│  │  │  │ README.rst
│  ├── net
│  │  ├── mqtt
│  │  │  ├── doc
│  │  │  │  ├── architecture.rst
│  │  │  │  │ description.rst
│  ├── nfc
│  │  ├── system_off
│  │  │  │ README.rst
│  ├── suit
│  │  ├── recovery
│  │  │  │ README.rst
│  ├── wifi
│  │  ├── softap
│  │  │  │ README.rst
│  │  ├── wfa_qt_app
│  │  │  │ README.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification
   - :orange_circle: test-fw-nrfconnect-ble_samples
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nfc
   - :orange_circle: test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - :orange_circle: test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - :orange_circle: test-fw-nrfconnect-nrf-iot_samples
   - :orange_circle: test-fw-nrfconnect-nrf-iot_thingy91
   - :orange_circle: test-fw-nrfconnect-nrf-iot_mosh
   - :orange_circle: test-fw-nrfconnect-nrf-iot_positioning
   - :orange_circle: test-sdk-wifi
   - :orange_circle: test-sdk-dfu
   - :warning: test-fw-nrfconnect-nrf-iot_cloud
   - :wa [...]

2024-12-11 14:41 UTC, peknis requested changes

2024-12-11 14:41 UTC, peknis commented on samples/cellular/location/README.rst
> +  	You need not add any overlays.
Keep the text as it, but align with the line above.

2024-12-11 14:41 UTC, peknis commented on samples/suit/recovery/README.rst
> +For an example, see the files in the :file:`samples/suit/smp_transfer` sample.
```suggestion
For an example, see the files in the :file:`samples/suit/smp_transfer` folder.
```

2024-12-11 14:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19442
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-12 06:26 UTC, peknis approved these changes

2024-12-12 12:02 UTC, b-gent approved these changes

2024-12-12 12:52 UTC, gmarull approved these changes

2024-12-12 13:39 UTC, richabp requested changes

2024-12-12 13:39 UTC, richabp commented on doc/nrf/releases_and_maturity/software_maturity.rst
> +   * - **Wi-Fi®**
I think it should be added to Bluetooth® in line 193.

2024-12-12 13:39 UTC, richabp commented on doc/nrf/test_and_optimize/optimizing/power_general.rst
Bluetooth® Mesh at line 179?

2024-12-12 13:39 UTC, richabp commented on samples/matter/template/README.rst
Can remove ® from Line 52, 142.

2024-12-13 07:53 UTC, umapraseeda commented on applications/matter_bridge/README.rst
Fixed

2024-12-13 08:59 UTC, umapraseeda commented
@nrfconnect/ncs-protocols-serialization please check and approve.

2024-12-13 09:00 UTC, richabp approved these changes

2024-12-13 09:18 UTC, greg-fer approved these changes
One nit.

2024-12-13 09:18 UTC, greg-fer commented on doc/_utils/redirects.py
> +    ("app_dev/device_guides/nrf54l/snippets", "app_dev/device_guides/nrf54l/index"), # Removed after 2.8.0
If possible, mention the page title in the comment, to match other comment entries.

2024-12-13 10:27 UTC, shanthanordic commented
is this must go in for 2.9 ? @umapraseeda

2024-12-13 10:42 UTC, Damian-Nordic approved these changes

2024-12-16 08:22 UTC, merged