doc: nrf_security: Adding HKDF-extract and HKDF-Expand to supported
nrfconnect/sdk-nrf pull request #19476
Opened 2024-12-12 12:41 UTC by degjorva

HKDF-Extract and HKDF-Expand support have been added to cracen. Updating docs to match.

2024-12-12 12:48 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [abf4268e7ee9d7867c2b0215364cf2a4f4dba214](https://github.com/nrfconnect/sdk-nrf/pull/19476/commits/abf4268e7ee9d7867c2b0215364cf2a4f4dba214)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [abf4268e7ee9d7867c2b0215364cf2a4f4dba214](https://github.com/nrfconnect/sdk-nrf/pull/19476/commits/abf4268e7ee9d7867c2b0215364cf2a4f4dba214)
> merge base: [ffa08e9d4e592eaf079eb6f9dccfe14ec9d50bf5](https://github.com/nrfconnect/sdk-nrf/commit/ffa08e9d4e592eaf079eb6f9dccfe14ec9d50bf5)
> target head (main): [4885bf77165e8ca833cd937f6c88daaa87e3c40b](https://github.com/nrfconnect/sdk-nrf/commit/4885bf77165e8ca833cd937f6c88daaa87e3c40b)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/ffa08e9d4e592eaf079eb6f9dccfe14ec9d50bf5..abf4268e7ee9d7867c2b0215364cf2a4f4dba214)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
doc
│  ├── nrf
│  │  ├── libraries
│  │  │  ├── security
│  │  │  │  ├── nrf_security
│  │  │  │  │  ├── doc
│  │  │  │  │  │  │ driver_config.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-13 09:20 UTC, greg-fer approved these changes

2024-12-13 09:21 UTC, greg-fer commented
Consider changelog entry for this change (your call).

2025-01-07 12:44 UTC, melwee01 commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated:
I think there needs to be an empty line between the header and text.

2025-01-07 13:06 UTC, peknis requested changes

2025-01-07 13:06 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Updated:
Leave out the Updated line.

2025-01-07 13:15 UTC, melwee01 approved these changes

2025-01-07 13:43 UTC, merged