Support for Model Publication in Light CTL Temperature Server
nrfconnect/sdk-nrf pull request #19496
Opened 2024-12-13 09:24 UTC by IlijaVorontsov

## Specification Requirements
| From the Mesh Model Specification v1.0.1, Section 6.4.4.1:

This model shall support model publication, as defined in Section 4.2.2 of the Mesh Profile specification.

The Mesh Profile Specification v1.0.1, Section 4.2.2 defines model publication as a composite state that controls message publishing parameters, including:

Publish Address
Publish Period
Retransmission Settings

# Implementation Approach
The implementation adds publication support following the same pattern established in the light_ctl_srv, ensuring consistency with existing model implementations while fulfilling the specification's requirements. This approach maintains architectural coherence within the Bluetooth mesh stack.

2024-12-13 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=19496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=19496) before we can accept your contribution.<br/><hr/>**Ilija Vorontsov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=19496) it.</sub>

2024-12-13 09:24 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2024-12-17 10:36 UTC, omkar3141 requested changes
Looks good. However, commit message needs to follow the format as used by other commits in these files, should be bit more descriptive, and should be signed-off.

2025-01-02 11:35 UTC, alxelax requested changes
@omkar3141's concerns have not been fixed either.

I triggered CI, please take a look at the compliance bugs. They have to be fixed.

Please rebase at the latest main to avoid another issues.

2025-01-02 11:35 UTC, alxelax commented on subsys/bluetooth/mesh/light_temp_srv.c
> +	temp_get(srv, NULL, &status);
```suggestion
	srv->handlers->get(srv, NULL, &status);
```
Seems `temp_get` does nothing, just copies data to some local variable to move it again to another local variable.

2025-01-02 21:02 UTC, IlijaVorontsov commented on subsys/bluetooth/mesh/light_temp_srv.c
> +	temp_get(srv, NULL, &status);
I have tried to have it similar to `subsys/bluetooth/mesh/light_ctl_srv.c` where `ctl_get` is called which gets a superset of the values of `temp_get`. I have tested the code in production and it allowed to sent publication period and published correct values in set interval. If it really does nothing maybe the ligth_ctl code has to be adapted?

Can not check on my production system right now will be at the office back on tuesday.

```C
static void ctl_get(struct bt_mesh_light_ctl_srv *srv,
		    struct bt_mesh_msg_ctx *ctx,
		    struct bt_mesh_light_ctl_status *status)
{
	struct bt_mesh_light_temp_status temp;
	struct bt_mesh_lightness_status light;

	srv->lightness_srv.handlers->light_get(&srv->lightness_srv, ctx,
					       &light);
	srv->temp_srv.handlers->get(&srv->temp_srv, ctx, &temp);

	status->current_temp = temp.current.temp;
	status->current_light = light.current;
	status->target_temp = temp.target.temp;
	status->target_light = light.target;
	status->remaining_time = MAX(temp.remaining_time, light.remaining_time);
}

static int update_handler(const struct bt_mesh_model *model)
{
	struct bt_mesh_light_ctl_srv *srv = model->rt->user_data;
	struct bt_mesh_light_ctl_status status = { 0 };

	ctl_get(srv, NULL, &status);
	ctl_encode_status(srv->pub.msg, &status);

	return 0;
}
```

2025-01-03 08:57 UTC, alxelax commented on subsys/bluetooth/mesh/light_temp_srv.c
> +	temp_get(srv, NULL, &status);
I do not think that the referencing to CTL model implementation is correct here. 
Mesh model spec 1.1
```
6.4.3 Light CTL Server
6.4.3.1 Description
...
The Light CTL Server is a main model that extends the Light Lightness Server model (see Section
6.4.1) and corresponds with the Light CTL Temperature Server model (see Section 6.4.4).
...
```
BLE Mesh spec 1.1
```
2.3.6 Models
...
Correspond. When models share state/procedure instances and work together to achieve some
functionality, they have a correspond relationship. Models that have a correspond relationship may
share either state instances or state bindings; however, they may have different messages and
uninherited procedures interacting with the states.
...
```
CTL and CTL Temperature servers share states\procedures. To generate its own status, CTL server has to use CTL Temperature server to pick up temperature values.

To create its own status, CTL Temperature server doesn't require any other servers. It can call its own `get` handler directly.

That means the presence of `ctl_get` function is reasonable, but `temp_get` really does nothing here. Just call `get` handler in `update_handler`.
I'm quite sure it will work the same but without unnecessary wrapper function. :)

2025-01-14 11:27 UTC, omkar3141 commented
Hello, any updates on this PR? It is relevant and it will be nice to fix review comments and then we can get this in. Thanks.

2025-01-14 11:28 UTC, IlijaVorontsov commented
> Hello, any updates on this PR? It is relevant and it will be nice to fix review comments and then we can get this in. Thanks.

Hi, just set down to propperly write the commit messages with attribution

2025-01-14 12:30 UTC, IlijaVorontsov commented
Sorry about the delay, struggled a bit with amending the commit messages correctly whilst conforming to the contribution guidelines. I messed up with the built in attribution of Alex, but added him as co-author to the commit. Hope that is fine.

2025-01-17 15:44 UTC, alxelax approved these changes

2025-01-20 08:08 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [83fe35d8e1e223a1d05818b160df68158993652c](https://github.com/nrfconnect/sdk-nrf/pull/19496/commits/83fe35d8e1e223a1d05818b160df68158993652c)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [83fe35d8e1e223a1d05818b160df68158993652c](https://github.com/nrfconnect/sdk-nrf/pull/19496/commits/83fe35d8e1e223a1d05818b160df68158993652c)
> merge base: [e1b6e2afc766aa23cf1bebabdec52d75fd4ae648](https://github.com/nrfconnect/sdk-nrf/commit/e1b6e2afc766aa23cf1bebabdec52d75fd4ae648)
> target head (main): [5e125259f131cb4b5b7c1c72588df0fd0ae7f0c1](https://github.com/nrfconnect/sdk-nrf/commit/5e125259f131cb4b5b7c1c72588df0fd0ae7f0c1)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/e1b6e2afc766aa23cf1bebabdec52d75fd4ae648..83fe35d8e1e223a1d05818b160df68158993652c)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
include
│  ├── bluetooth
│  │  ├── mesh
│  │  │  │ light_temp_srv.h
subsys
│  ├── bluetooth
│  │  ├── mesh
│  │  │  │ light_temp_srv.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification
   - :orange_circle: test-fw-nrfconnect-ble_mesh

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2025-01-20 10:01 UTC, omkar3141 approved these changes

2025-01-20 10:07 UTC, merged