manifest: Update tags for NCS v2.9.0-rc2
nrfconnect/sdk-nrf pull request #19509
Opened 2024-12-13 10:43 UTC by jukkar

2024-12-13 10:45 UTC, NordicBuilder commented
The following west manifest projects have changed revision in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| find-my | https://github.com/nrfconnect/sdk-find-my/commit/0170d0374ffe379522a0d2eaf5b44d7d1aa1e7b7 (`v2.9-branch`) | [nrfconnect/sdk-find-my@v2.9.0-rc2](https://github.com/nrfconnect/sdk-find-my/releases/tag/v2.9.0-rc2)| [nrfconnect/sdk-find-my@0170d037..v2.9.0-rc2](https://github.com/nrfconnect/sdk-find-my/compare/0170d0374ffe379522a0d2eaf5b44d7d1aa1e7b7..v2.9.0-rc2) |
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/684c8128ad203c86d1f058913dcd73fde63e9eaf (`v2.9-branch`) | [nrfconnect/sdk-connectedhomeip@v2.9.0-rc2](https://github.com/nrfconnect/sdk-connectedhomeip/releases/tag/v2.9.0-rc2)| [nrfconnect/sdk-connectedhomeip@684c8128..v2.9.0-rc2](https://github.com/nrfconnect/sdk-connectedhomeip/compare/684c8128ad203c86d1f058913dcd73fde63e9eaf..v2.9.0-rc2) |
| mbedtls | [nrfconnect/sdk-mbedtls@v3.6.2-ncs2-rc1](https://github.com/nrfconnect/sdk-mbedtls/releases/tag/v3.6.2-ncs2-rc1) | [nrfconnect/sdk-mbedtls@v3.6.2-ncs2-rc2](https://github.com/nrfconnect/sdk-mbedtls/releases/tag/v3.6.2-ncs2-rc2)| [nrfconnect/sdk-mbedtls@v3.6.2-ncs2-rc1..v3.6.2-ncs2-rc2](https://github.com/nrfconnect/sdk-mbedtls/compare/v3.6.2-ncs2-rc1..v3.6.2-ncs2-rc2) |
| mcuboot | [nrfconnect/sdk-mcuboot@v2.1.0-ncs3-rc1](https://github.com/nrfconnect/sdk-mcuboot/releases/tag/v2.1.0-ncs3-rc1) | [nrfconnect/sdk-mcuboot@v2.1.0-ncs3-rc2](https://github.com/nrfconnect/sdk-mcuboot/releases/tag/v2.1.0-ncs3-rc2)| [nrfconnect/sdk-mcuboot@v2.1.0-ncs3-rc1..v2.1.0-ncs3-rc2](https://github.com/nrfconnect/sdk-mcuboot/compare/v2.1.0-ncs3-rc1..v2.1.0-ncs3-rc2) |
| nrf-802154 | https://github.com/nrfconnect/sdk-nrf-802154/commit/e8be396184667824f201ec1c364f8fb0ee829aaf (`main`,`v2.9-branch`) | [nrfconnect/sdk-nrf-802154@v2.9.0-rc2](https://github.com/nrfconnect/sdk-nrf-802154/releases/tag/v2.9.0-rc2)| [nrfconnect/sdk-nrf-802154@e8be3961..v2.9.0-rc2](https://github.com/nrfconnect/sdk-nrf-802154/compare/e8be396184667824f201ec1c364f8fb0ee829aaf..v2.9.0-rc2) |
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/65831e25aaf0a65082e82aed56fa87c314177a9d (`v2.9-branch`) | [nrfconnect/sdk-nrfxlib@v2.9.0-rc2](https://github.com/nrfconnect/sdk-nrfxlib/releases/tag/v2.9.0-rc2)| [nrfconnect/sdk-nrfxlib@65831e25..v2.9.0-rc2](https://github.com/nrfconnect/sdk-nrfxlib/compare/65831e25aaf0a65082e82aed56fa87c314177a9d..v2.9.0-rc2) |
| sidewalk | [nrfconnect/sdk-sidewalk@v2.9.0-rc1](https://github.com/nrfconnect/sdk-sidewalk/releases/tag/v2.9.0-rc1) | [nrfconnect/sdk-sidewalk@v2.9.0-rc2](https://github.com/nrfconnect/sdk-sidewalk/releases/tag/v2.9.0-rc2)| [nrfconnect/sdk-sidewalk@v2.9.0-rc1..v2.9.0-rc2](https://github.com/nrfconnect/sdk-sidewalk/compare/v2.9.0-rc1..v2.9.0-rc2) |
| suit-generator | [nrfconnect/suit-generator@v2.9.0-rc1](https://github.com/nrfconnect/suit-generator/releases/tag/v2.9.0-rc1) | [nrfconnect/suit-generator@v2.9.0-rc2](https://github.com/nrfconnect/suit-generator/releases/tag/v2.9.0-rc2)| [nrfconnect/suit-generator@v2.9.0-rc1..v2.9.0-rc2](https://github.com/nrfconnect/suit-generator/compare/v2.9.0-rc1..v2.9.0-rc2) |
| suit-processor | [nrfconnect/suit-processor@v2.9.0-rc1](https://github.com/nrfconnect/suit-processor/releases/tag/v2.9.0-rc1) | [nrfconnect/suit-processor@v2.9.0-rc2](https://github.com/nrfconnect/suit-processor/releases/tag/v2.9.0-rc2)| [nrfconnect/suit-processor@v2.9.0-rc1..v2.9.0-rc2](https://github.com/nrfconnect/suit-processor/compare/v2.9.0-rc1..v2.9.0-rc2) |
| trusted-firmware-m | [nrfconnect/sdk-trusted-firmware-m@v2.1.1-ncs2-rc1](https://github.com/nrfconnect/sdk-trusted-firmware-m/releases/tag/v2.1.1-ncs2-rc1) | [nrfconnect/sdk-trusted-firmware-m@v2.1.1-ncs2-rc2](https://github.com/nrfconnect/sdk-trusted-firmware-m/releases/tag/v2.1.1-ncs2-rc2)| [nrfconnect/sdk-trusted-firmware-m@v2.1.1-ncs2-rc1..v2.1.1-ncs2-rc2](https://github.com/nrfconnect/sdk-trusted-firmware-m/compare/v2.1.1-ncs2-rc1..v2.1.1-ncs2-rc2) |
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/22eec458376ee5ed7bcb4799aa89b996abfee141 (`v3.7.99-ncs2-branch`) | [nrfconnect/sdk-zephyr@v3.7.99-ncs2-rc2](https://github.com/nrfconnect/sdk-zephyr/releases/tag/v3.7.99-ncs2-rc2)| [nrfconnect/sdk-zephyr@22eec458..v3.7.99-ncs2-rc2](https://github.com/nrfconnect/sdk-zephyr/compare/22eec458376ee5ed7bcb4799aa89b996abfee141..v3.7.99-ncs2-rc2) |


Additional metadata changed:

| Name | URL | Submodules | West cmds | `module.yml` | 
| ---- | --- | ---------- | --------- | ------------ | 
| mcuboot |  |  |  | ✏ |

⛔ **DNM label due to: 1 project with metadata changes**

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-12-13 10:45 UTC, shanthanordic approved these changes

2024-12-13 10:47 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sidewalk: PR head: [a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e](https://github.com/nrfconnect/sdk-sidewalk/commit/a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e)
trusted-firmware-m: PR head: [f2bf78452629355e4180dc36756f6c1becc819fa](https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/f2bf78452629355e4180dc36756f6c1becc819fa)
sdk-nrf: PR head: [7cb23198d0bde8a5554ca5065f3f353254e6fcb9](https://github.com/nrfconnect/sdk-nrf/pull/19509/commits/7cb23198d0bde8a5554ca5065f3f353254e6fcb9)
mcuboot: PR head: [ed0fc24030f3765cfb04a8fdd8771bd5078107a7](https://github.com/nrfconnect/sdk-mcuboot/commit/ed0fc24030f3765cfb04a8fdd8771bd5078107a7)
nrfxlib: PR head: [65831e25aaf0a65082e82aed56fa87c314177a9d](https://github.com/nrfconnect/sdk-nrfxlib/commit/65831e25aaf0a65082e82aed56fa87c314177a9d)
find-my: PR head: [616004ea718636d90a4feb3b470b48f2616532f3](https://github.com/nrfconnect/sdk-find-my/commit/616004ea718636d90a4feb3b470b48f2616532f3)
mbedtls: PR head: [98603a8c91660beac00e0ee1d76198fb7c4ed29b](https://github.com/nrfconnect/sdk-mbedtls/commit/98603a8c91660beac00e0ee1d76198fb7c4ed29b)
suit-generator: PR head: [8f9ce9039e6fb8584dc915944b2bc275856757c0](https://github.com/nrfconnect/suit-generator/commit/8f9ce9039e6fb8584dc915944b2bc275856757c0)
suit-processor: PR head: [6802f3008cba16a74a8c65814af00808327a7ee7](https://github.com/nrfconnect/suit-processor/commit/6802f3008cba16a74a8c65814af00808327a7ee7)
matter: PR head: [684c8128ad203c86d1f058913dcd73fde63e9eaf](https://github.com/nrfconnect/sdk-connectedhomeip/commit/684c8128ad203c86d1f058913dcd73fde63e9eaf)
zephyr: PR head: [22eec458376ee5ed7bcb4799aa89b996abfee141](https://github.com/nrfconnect/sdk-zephyr/commit/22eec458376ee5ed7bcb4799aa89b996abfee141)
<details><summary> more details</summary>

sidewalk:
> PR head: [a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e](https://github.com/nrfconnect/sdk-sidewalk/commit/a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e)
> merge base: [a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e](https://github.com/nrfconnect/sdk-sidewalk/commit/a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e)
> [Diff](https://github.com/nrfconnect/sdk-sidewalk/compare/a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e..a2433e06b653e0f9a47f17af0fef6bd4c5e90a4e)

trusted-firmware-m:
> PR head: [f2bf78452629355e4180dc36756f6c1becc819fa](https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/f2bf78452629355e4180dc36756f6c1becc819fa)
> merge base: [f2bf78452629355e4180dc36756f6c1becc819fa](https://github.com/nrfconnect/sdk-trusted-firmware-m/commit/f2bf78452629355e4180dc36756f6c1becc819fa)
> [Diff](https://github.com/nrfconnect/sdk-trusted-firmware-m/compare/f2bf78452629355e4180dc36756f6c1becc819fa..f2bf78452629355e4180dc36756f6c1becc819fa)

sdk-nrf:
> PR head: [7cb23198d0bde8a5554ca5065f3f353254e6fcb9](https://github.com/nrfconnect/sdk-nrf/pull/19509/commits/7cb23198d0bde8a5554ca5065f3f353254e6fcb9)
> merge base: [a71d0c712723f31dc24bfdd2be7e0525627fd6f8](https://github.com/nrfconnect/sdk-nrf/commit/a71d0c712723f31dc24bfdd2be7e0525627fd6f8)
> target head (v2.9-branch): [a71d0c712723f31dc24bfdd2be7e0525627fd6f8](https://github.com/nrfconnect/sdk-nrf/commit/a71d0c712723f31dc24bfdd2be7e0525627fd6f8)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/a71d0c712723f31dc24bfdd2be7e0525627fd6f8..7cb23198d0bde8a5554ca5065f3f353254e6fcb9)

mcuboot:
> PR head: [ed0fc24030f3765cfb04a8fdd8771bd5078107a7](https://github.com/nrfconnect/sdk-mcuboot/commit/ed0fc24030f3765cfb04a8fdd8771bd5078107a7)
> merge base: [e890df7ab975da181a9f3fb3abc470bf935625ab](https://github.com/nrfconnect/sdk-mcuboot/commit/e890df7ab975da181a9f3fb3abc470bf935625ab)
> [Diff](https://github.com/nrfconnect/sdk-mcuboot/compare/e890df7ab975da181a9f3fb3abc470bf935625ab..ed0fc24030f3765cfb04a8fdd8771bd5078107a7)

nrfxlib:
> PR head: [65831e25aaf0a65082e82aed56fa87c314177a9d](https://github.com/nrfconnect/sdk-nrfxlib/commit/65831e25aaf0a65082e82aed56fa87c314177a9d)
> merge base: [65831e25aaf0a65082e82aed56fa87c314177a9d](https://github.com/nrfconnect/sdk-nrfxlib/commit/65831e25aaf0a65082e82aed56fa87c314177a9d)
> [Diff](https://github.com/nrfconnect/sdk-nrfxlib/compare/65831e25aaf0a65082e82aed56fa87c314177a9d..65831e25aaf0a65082e82aed56fa87c314177a9d)

find-my:
> PR head: [616004ea718636d90a4feb3b470b48f2616532f3](https://github.com/nrfconnect/sdk-find-my/commit/616004ea718636d90a4feb3b470b48f2616532f3)
> merge base: [616004ea718636d90a4feb3b470b48f2616532f3](https://github.com/nrfconnect/sdk-find-my/commit/616004ea718636d90a4feb3b470b48f2616532f3)
> [Diff](https://github.com/nrfconnect/sdk-find-my/compare/616004ea718636d90a4feb3b470b48f2616532f3..616004ea718636d90a4feb3b470b48f2616532f3)

mbedtls:
> PR head: [98603a8c91660beac00e0ee1d76198fb7c4ed29b](https://github.com/nrfconnect/sdk-mbedtls/commit/98603a8c91660beac00e0ee1d76198fb7c4ed29b)
> merge base: [98603a8c91660beac00e0ee1d76198fb7c4ed29b](https://github.com/nrfconnect/sdk-mbedtls/commit/98603a8c91660beac00e0ee1d76198fb7c4ed29b)
> [Diff](https://github.com/nrfconnect/sdk-mbedtls/compare/98603a8c91660beac00e0ee1d76198fb7c4ed29b..98603a8c91660beac00e0ee1d76198fb7c4ed29b)

suit-generator:
> PR head: [8f9ce9039e6fb8584dc915944b2bc275856757c0](https://github.com/nrfconnect/suit-generator/commit/8f9ce9039e6fb8584dc915944b2bc275856757c0)
> merge base: [8f9ce9039e6fb8584dc915944b2bc275856757c0](https://github.com/nrfconnect/suit-generator/commit/8f9ce9039e6fb8584dc915944b2bc275856757c0)
> [Diff](https://github.com/nrfconnect/suit-generator/compare/8f9ce9039e6fb8584dc915944b2bc275856757c0..8f9ce9039e6fb8584dc915944b2bc275856757c0)

suit-processor:
> PR head: [6802f3008cba16a74a8c65814af00808327a7ee7](https://github.com/nrfconnect/suit-processor/commit/6802f3008cba16a74a8c65814af00808327a7ee7)
> merge base: [6802f3008cba16a74a8c65814af00808327a7ee7](https://github.com/nrfconnect/suit-processor/commit/6802f3008cba16a74a8c65814af00808327a7ee7)
> [Diff](https://github.com/nrfconnect/suit-processor/compare/6802f3008cba16a74a8c65814af00808327a7ee7..6802f3008cba16a74a8c65814af00808327a7ee7)

matter:
> PR head: [684c8128ad203c86d1f058913dcd73fde63e9eaf](https://github.com/nrfconnect/sdk-connectedhomeip/commit/684c8128ad203c86d1f058913dcd73fde63e9eaf)
> merge base: [684c8128ad203c86d1f058913dcd73fde63e9eaf](https://github.com/nrfconnect/sdk-connectedhomeip/commit/684c8128ad203c86d1f058913dcd73fde63e9eaf)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/684c8128ad203c86d1f058913dcd73fde63e9eaf..684c8128ad203c86d1f058913dcd73fde63e9eaf)

zephyr:
> PR head: [22eec458376ee5ed7bcb4799aa89b996abfee141](https://github.com/nrfconnect/sdk-zephyr/commit/22eec458376ee5ed7bcb4799aa89b996abfee141)
> merge base: [22eec458376ee5ed7bcb4799aa89b996abfee141](https://github.com/nrfconnect/sdk-zephyr/commit/22eec458376ee5ed7bcb4799aa89b996abfee141)
> [Diff](https://github.com/nrfconnect/sdk-zephyr/compare/22eec458376ee5ed7bcb4799aa89b996abfee141..22eec458376ee5ed7bcb4799aa89b996abfee141)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (61)</summary>

```
VERSION
bootloader
│  ├── mcuboot
│  │  ├── .github
│  │  │  ├── workflows
│  │  │  │  ├── backport.yml
│  │  │  │  │ commit-tags.yml
│  │  ├── boot
│  │  │  ├── boot_serial
│  │  │  │  ├── src
│  │  │  │  │  ├── boot_serial.c
│  │  │  │  │  │ boot_serial_encryption.c
│  │  │  ├── bootutil
│  │  │  │  ├── include
│  │  │  │  │  ├── bootutil
│  │  │  │  │  │  ├── crypto
│  │  │  │  │  │  │  ├── aes_ctr.h
│  │  │  │  │  │  │  ├── ecdsa.h
│  │  │  │  │  │  │  │ sh [...]

2024-12-13 11:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19509
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-13 11:57 UTC, tejlmand approved these changes

2024-12-13 11:58 UTC, anangl approved these changes

2024-12-13 11:59 UTC, bjarki-andreasen approved these changes

2024-12-13 11:59 UTC, tejlmand requested changes
should this be updated ?
https://github.com/nrfconnect/sdk-nrf/blob/a71d0c712723f31dc24bfdd2be7e0525627fd6f8/scripts/ncs-toolchain-version-minimum.txt#L3

2024-12-13 12:00 UTC, jukkar commented
> should this be updated ?
> 
> https://github.com/nrfconnect/sdk-nrf/blob/a71d0c712723f31dc24bfdd2be7e0525627fd6f8/scripts/ncs-toolchain-version-minimum.txt#L3

No idea, tell me what to put there and I can send new version.

2024-12-13 12:19 UTC, jangalda-nsc commented
> > should this be updated ?
> > https://github.com/nrfconnect/sdk-nrf/blob/a71d0c712723f31dc24bfdd2be7e0525627fd6f8/scripts/ncs-toolchain-version-minimum.txt#L3
> 
> No idea, tell me what to put there and I can send new version.

Please change to
2.8.20241119

2024-12-13 12:34 UTC, tejlmand approved these changes

2024-12-13 12:58 UTC, gmarull approved these changes

2024-12-13 13:00 UTC, jfischer-no approved these changes

2024-12-13 14:11 UTC, merged

2024-12-20 14:37 UTC, kapi-no commented on west.yml
> +      revision: v2.9.0-rc2
Incorrect tag. The v2.9-branch should have been used for tagging in the sdk-find-my repository

2024-12-20 15:18 UTC, kapi-no commented on west.yml
> +      revision: v2.9.0-rc2
I fixed this by force-pushing the tag aliases in the `sdk-find-my` repository.