samples: benchmarks: coremark: Add nRF54L05 and nRF54L10 support
nrfconnect/sdk-nrf pull request #19514
Opened 2024-12-13 11:10 UTC by MarekPieta

Change adds support for nRF54L05 and nRF54L10 SoCs (emulated on nRF54L15 DK).

Jira: NCSDK-30313

2024-12-13 11:14 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [873d471cb4cf52512bcbb4449338d20cb489ed6a](https://github.com/nrfconnect/sdk-nrf/pull/19514/commits/873d471cb4cf52512bcbb4449338d20cb489ed6a)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [873d471cb4cf52512bcbb4449338d20cb489ed6a](https://github.com/nrfconnect/sdk-nrf/pull/19514/commits/873d471cb4cf52512bcbb4449338d20cb489ed6a)
> merge base: [e1b6e2afc766aa23cf1bebabdec52d75fd4ae648](https://github.com/nrfconnect/sdk-nrf/commit/e1b6e2afc766aa23cf1bebabdec52d75fd4ae648)
> target head (main): [5cf5bae9d6db77b2fc91cf9dff462bc644b54456](https://github.com/nrfconnect/sdk-nrf/commit/5cf5bae9d6db77b2fc91cf9dff462bc644b54456)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/e1b6e2afc766aa23cf1bebabdec52d75fd4ae648..873d471cb4cf52512bcbb4449338d20cb489ed6a)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (6)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  ├── releases
│  │  │  │  │ release-notes-changelog.rst
samples
│  ├── benchmarks
│  │  ├── coremark
│  │  │  ├── README.rst
│  │  │  ├── boards
│  │  │  │  ├── nrf54l15dk_nrf54l05_cpuapp.conf
│  │  │  │  │ nrf54l15dk_nrf54l10_cpuapp.conf
│  │  │  │ sample.yaml
scripts
│  │ quarantine_integration.yaml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-13 11:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19514
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-13 12:44 UTC, zycz commented
Overall good. Question should we test both classic and flash and run configurations in CI? IMO one is enough

2024-12-13 14:44 UTC, MarekPieta commented
> Overall good. Question should we test both classic and flash and run configurations in CI? IMO one is enough

Ok, let's leave only the `flash_and_run` for the new boards then (it tests runtime too)

2024-12-13 14:56 UTC, zycz approved these changes

2024-12-13 15:17 UTC, kapi-no approved these changes

2024-12-16 06:48 UTC, peknis requested changes

2024-12-16 06:48 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +* Added :ref:`nRF54L05 (emulated on nRF54L15 DK) <ug_nrf54l>` and :ref:`nRF54L10 (emulated on nRF54L15 DK) <ug_nrf54l>` support to the :ref:`coremark_sample` sample.
```suggestion
* :ref:`coremark_sample` sample:

  * Added support for the :ref:`nRF54L05 and nRF54L10 (emulated on nRF54L15 DK) <ug_nrf54l>` SoCs.
```

2024-12-16 10:30 UTC, peknis approved these changes

2024-12-16 12:35 UTC, PerMac approved these changes

2024-12-16 12:35 UTC, merged