subsys, nrf_security: add nrf92 devices to security and cracen config
nrfconnect/sdk-nrf pull request #19558
Opened 2024-12-16 13:19 UTC by ayla-nordicsemi

These changes aim to allow using cracen cryptographic features on nrf92 devices.
These changes are required to allow accessing built-in keys using psa over cracen driver.

2024-12-16 13:24 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 2
### Inputs:
#### Sources:
<details><summary> more details</summary>
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (0)</summary>

```
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :x: Toolchain
- :x: Build twister
- :x: Integration tests



*Note: This message is automatically posted and updated by the CI*

2024-12-16 13:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19558
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2025-01-14 09:28 UTC, jonathannilsen commented on subsys/sdfw_services/services/psa_crypto/Kconfig
> +service_default_enabled = y
Is this change required?

2025-01-14 09:28 UTC, jonathannilsen commented on subsys/nrf_security/src/drivers/cracen/Kconfig
> +	def_bool (SOC_SERIES_NRF54LX || SOC_SERIES_NRF92X)
This addition should not be needed I think - it should already be selected by the board

2025-01-14 09:28 UTC, jonathannilsen commented on subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig
> +				SOC_NRF9230_CPUSEC
this should be sufficient:
```suggestion
	depends on SOC_NRF54H20_CPUSEC || SOC_NRF9280_CPUSEC
```

2025-01-14 09:28 UTC, jonathannilsen commented on subsys/nrf_security/src/drivers/cracen/Kconfig
> +				(SOC_SERIES_NRF92X && (SOC_NRF9280_CPUSEC || SOC_NRF9230_CPUSEC))
I would think that this is sufficient:
```suggestion
	depends on (SOC_SERIES_NRF54LX && !SOC_NRF54L20) || SOC_SERIES_NRF54HX || \
				SOC_SERIES_NRF92X
```

2025-01-14 09:28 UTC, jonathannilsen commented on subsys/nrf_security/Kconfig
> +	default y if SOC_SERIES_NRF92X && (SOC_NRF9280_CPUSEC || SOC_NRF9230_CPUSEC)
```suggestion
	default y if SOC_SERIES_NRF92X && SOC_NRF9280_CPUSEC
```

2025-01-29 08:21 UTC, ayla-nordicsemi commented on subsys/sdfw_services/services/psa_crypto/Kconfig
> +service_default_enabled = y
It might be removed as it is not part of this PR changes, I will add it to this one #19561 as it relies on PSA_CRYPTO services to perform the signing of Json Web Tokens.

2025-02-03 10:46 UTC, nordicjm requested changes

2025-02-03 10:46 UTC, nordicjm commented on subsys/nrf_security/Kconfig
>  	default y if BUILD_WITH_TFM
git commit title should have : not ,

2025-02-03 10:46 UTC, nordicjm commented on subsys/nrf_security/Kconfig
> +	default y if SOC_SERIES_NRF92X && (SOC_NRF9280_CPUSEC || SOC_NRF9230_CPUSEC)
CPUSEC should not be referenced in this repo at all

2025-02-03 10:46 UTC, nordicjm commented on subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig
> +				SOC_NRF9230_CPUSEC
as above, no mention to CPUSEC

2025-02-07 13:09 UTC, ayla-nordicsemi commented on subsys/sdfw_services/services/psa_crypto/Kconfig
> +service_default_enabled = y
@jonathannilsen is it possible to activate this flag for an sdk-nrf sample using the prj.conf file ?
you are right about activating this by default actually doesn't make sense.

2025-02-10 06:50 UTC, closed without merging

2025-02-10 06:50 UTC, ayla-nordicsemi commented
This pull request is obsolete, the features it aimed to add has been already covered by other pull requests ( 
 [20107 ](https://github.com/nrfconnect/sdk-nrf/pull/20107) and [secdom/1089](https://github.com/nrfconnect/sdk-secdom/pull/1089).
Closing it.