doc: nrf: app_dev: nrf54h20: Global reset
nrfconnect/sdk-nrf pull request #19608
Opened 2024-12-18 10:04 UTC by karstenkoenig

Updated reset handling to reflect the new global domain reset handling for local domain resets, plus impact on debugging experience. Also highlighted need for local domains for good power consumption numbers.

2024-12-18 10:08 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [f85cafe262a42ccb74de101e7b7d03c58875bc3a](https://github.com/nrfconnect/sdk-nrf/pull/19608/commits/f85cafe262a42ccb74de101e7b7d03c58875bc3a)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [f85cafe262a42ccb74de101e7b7d03c58875bc3a](https://github.com/nrfconnect/sdk-nrf/pull/19608/commits/f85cafe262a42ccb74de101e7b7d03c58875bc3a)
> merge base: [212213225ec4869f3924504ffb998e95d1d1d0fd](https://github.com/nrfconnect/sdk-nrf/commit/212213225ec4869f3924504ffb998e95d1d1d0fd)
> target head (main): [f0fbddcfcf9198bf7ed6f3942372c32e535c14f5](https://github.com/nrfconnect/sdk-nrf/commit/f0fbddcfcf9198bf7ed6f3942372c32e535c14f5)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/212213225ec4869f3924504ffb998e95d1d1d0fd..f85cafe262a42ccb74de101e7b7d03c58875bc3a)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── device_guides
│  │  │  │  ├── nrf54h
│  │  │  │  │  ├── ug_nrf54h20_architecture_pm.rst
│  │  │  │  │  ├── ug_nrf54h20_architecture_reset.rst
│  │  │  │  │  │ ug_nrf54h20_debugging.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-18 10:33 UTC, bjarki-andreasen approved these changes
the reset strategy is definately nicer with just always resetting everything, and nrfutil is only needed for "special cases", so I think upstream is going to be just fine since west debug and attach work, similarly to what I believe the nrf5340 does

2024-12-18 10:41 UTC, jonathannilsen approved these changes

2024-12-18 10:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19608
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-18 10:59 UTC, jonathannilsen commented
> the reset strategy is definately nicer with just always resetting everything, and nrfutil is only needed for "special cases", so I think upstream is going to be just fine since west debug and attach work, similarly to what I believe the nrf5340 does

We will also work to improve the debugging experience moving forward to make it more usable. The solution described here was the best we were able to do without larger changes to the tooling etc., but in time I think we can make it as usable as it was before (hopefully better).

2024-12-18 11:41 UTC, FrancescoSer requested changes

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst
> +       They can be started individually with ``nrfutil device go --core Network`` and ``nrfutil device go --core Application``.
```suggestion
       This command resets the entire system while keeping both the application core and the radio core in a halted state.

       You can start each core individually using the following commands:

       * To start the Application core: ``nrfutil device go --core Application``
       * To start the Network core: ``nrfutil device go --core Network``
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst
> +       This is particularly useful for debugging individual domains from their reset handlers onward.
```suggestion
       This approach is particularly useful for debugging individual domains starting from their reset handlers.
       
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +Debugging early-boot or reset issues
```suggestion
Debugging early-boot and reset issues
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +************************************
```suggestion
*************************************
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +The following sample demonstrates debugging the early boot phase on the application core:
```suggestion
A local domain reset triggers a global reset, which resets the debugging state. As a result, a new debugging connection is required.
To debug early boot issues, you can trigger a reset while keeping the cores in a halted state. This allows time to attach the debugger. The cores can then be started individually.

The following example demonstrates debugging the early boot phase on the application core:
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +You can also attach to a running core with ``west attach``.
```suggestion
You can also attach to a running core using the ``west attach`` command.
```

2024-12-18 11:41 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_pm.rst
> +Refer to :ref:`multicore_idle_test` samples for reference implementations leveraging an always idle radio core combined with an actual application on the application core.
```suggestion
To achieve optimal low power consumption, it is important to ensure that both the radio and application domains are populated with firmware, as each domain is responsible for sending its own power and clock requirements to the System Controller. 

For reference implementations, refer to the :ref:`multicore_idle_test` samples.
These samples demonstrate configurations that leverage an always idle radio core combined with an active application on the application core.
```

2024-12-23 13:21 UTC, FrancescoSer requested changes

2024-12-23 13:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_pm.rst
> +These samples demonstrate configurations that leverage an always idle radio core combined with an active application on the application core.
```suggestion
To achieve optimal low power consumption, ensure that both the radio and application domains are programmed with firmware, as each domain independently sends its power and clock requirements to the System Controller.

For reference implementations, see the :ref:`multicore_idle_test` samples.  
These samples demonstrate configurations where the radio core remains idle while the application core remains active.
```

2024-12-23 13:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +You can also attach to a running core using the ``west attach`` command.
```suggestion
You can also attach the debug session to a running core using the ``west attach`` command.
```

2024-12-23 13:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst
> +       This approach is particularly useful for debugging individual domains starting from their reset handlers.
```suggestion
       This approach is particularly useful for debugging individual domains, starting from their reset handlers.

```

2024-12-23 13:21 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +The following example demonstrates debugging the early boot phase on the application core:
```suggestion
A local domain reset triggers a global reset, which resets the debugging state. As a result, a new debugging connection is required.
To debug early boot issues, you can trigger a reset while keeping the cores in a halted state. This approach allows time to attach the debugger.
The cores can then be started individually.

The following example demonstrates how to debug the early boot phase on the application core:
```

2025-01-07 16:07 UTC, b-gent commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_pm.rst
> +These samples demonstrate configurations that leverage an always idle radio core combined with an active application on the application core.
comitted

2025-01-07 16:48 UTC, b-gent commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
> +The following example demonstrates debugging the early boot phase on the application core:
committed

2025-01-08 11:28 UTC, b-gent approved these changes

2025-01-08 12:04 UTC, merged