cmake: Prevent regenerating dfu multi image on every build
nrfconnect/sdk-nrf pull request #19636
Opened 2024-12-19 08:04 UTC by adigie

* Move running dfu_multi_image_tool.py out of custom target to stop regenerating the image on every build.
* Fix DEPENDS for dfu_multi_image_package.

2024-12-19 09:41 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***sample.matter.template.debug[nrf7002dk/nrf5340/cpuapp]***: ***High ROM usage: 911846[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.release[nrf7002dk/nrf5340/cpuapp]***: ***High ROM usage: 820674[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-19636/1)*

2024-12-23 08:06 UTC, nordicjm requested changes

2024-12-23 08:06 UTC, nordicjm commented on modules/mcuboot/CMakeLists.txt
> +    DEPENDS ${dfu_multi_image_targets}
change to be dropped, this is child/parent code which is being removed

2025-01-16 08:26 UTC, adigie commented
@nordicjm Could you take a look?

2025-01-17 07:46 UTC, nordicjm approved these changes

2025-01-17 07:51 UTC, ArekBalysNordic approved these changes

2025-01-17 07:59 UTC, merged