mcuboot: Add Kconfig to force in-tree version of imgtool
nrfconnect/sdk-nrf pull request #19647
Opened 2024-12-19 10:46 UTC by nordicjm

Adds a new Kconfig which is selected by default, and will enforce that the in-tree version of imgtool is used instead of the system version

2024-12-19 10:50 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [7919670a7a817cec580fe186d2b4734ce532c58f](https://github.com/nrfconnect/sdk-nrf/pull/19647/commits/7919670a7a817cec580fe186d2b4734ce532c58f)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [7919670a7a817cec580fe186d2b4734ce532c58f](https://github.com/nrfconnect/sdk-nrf/pull/19647/commits/7919670a7a817cec580fe186d2b4734ce532c58f)
> merge base: [75107cc4392534af0f2a9cb2bc77b0262e9ce485](https://github.com/nrfconnect/sdk-nrf/commit/75107cc4392534af0f2a9cb2bc77b0262e9ce485)
> target head (main): [4989dd10e20f684616dda81e4b9bb41bea81154c](https://github.com/nrfconnect/sdk-nrf/commit/4989dd10e20f684616dda81e4b9bb41bea81154c)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/75107cc4392534af0f2a9cb2bc77b0262e9ce485..7919670a7a817cec580fe186d2b4734ce532c58f)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (5)</summary>

```
cmake
│  ├── sysbuild
│  │  ├── image_signing.cmake
│  │  ├── image_signing_firmware_loader.cmake
│  │  ├── image_signing_nrf700x.cmake
│  │  │ image_signing_split.cmake
subsys
│  ├── bootloader
│  │  │ Kconfig
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-sdk-audio
   - :orange_circle: desktop52_verification
   - :orange_circle: test-fw-nrfconnect-boot
   - :orange_circle: test-fw-nrfconnect-apps
   - :orange_circle: test_ble_nrf_config
   - :orange_circle: test-fw-nrfconnect-ble_mesh
   - :orange_circle: test-fw-nrfconnect-ble_samples
   - :orange_circle: test-fw-nrfconnect-chip
   - :orange_circle: test-fw-nrfconnect-nfc
   - :orange_circle: test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - :orange_circle: test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - :orange_circle: test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - :orange_circle: test-fw-nrfconnect-nrf-iot_samples
   - :orange_circle: test-fw-nrfconnect-nrf-iot_lwm2m
   - :orange_circle: doc-internal
   - :orange_circle: test-fw-nrfconnect-nrf-iot_thingy91
   - :orange_circle: test-fw-nrfconnect-nrf_crypto
   - :orange_circle: test-fw-nrfconnect-rpc
   - :orange_circle: test-fw-nrfconnect-rs
   - :orange_circle: test-fw-nrfconnect-fem
   - :orange_circle: test-fw-nrfconnect-tfm
   - :orange_circle: test-fw-nrfconnect-thread
   - :orange_circle: test-fw-nrfconnect-zigbee
   - :orange_circle: test-sdk-find-my
   - :orange_circle: test-fw-nrfconnect-nrf-iot_mosh
   - :orange_circle: test-fw-nrfconnect-nrf-iot_positioning
   - :orange_circle: test-sdk-sidewalk
   - :orange_circle: test-sdk-wifi
   - :orange_circle: test-low-level
   - :orange_circle: test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - :orange_circle: test-sdk-pmic-samples
   - :orange_circle: test-sdk-mcuboot
   - :orange_circle: test-sdk-dfu
   - :orange_circle: test-fw-nrfconnect-ps
   - :orange_circle: test-secdom-samples-public
   - :warning: test-fw-nrfconnect-fw-update
   - :warning: test-fw-nrfconnect-nrf-iot_cloud



*Note: This message is automatically posted and updated by the CI*

2024-12-19 11:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19647
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-19 12:05 UTC, NordicBuilder commented
### Memory footprint analysis revealed the following potential issues

***sample.matter.template.debug[nrf7002dk/nrf5340/cpuapp]***: ***High ROM usage: 911846[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=debug&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)
***sample.matter.template.release[nrf7002dk/nrf5340/cpuapp]***: ***High ROM usage: 820674[B]*** - [link](https://ci-health.nordicsemi.no/grafana/d/footprint-tracking-sample/footprint-tracking-for-samples-and-applications-sdk-nrf?orgId=1&var-module=sample&var-submodule=matter&var-scenario=template&var-testcase=release&var-arch=arm&var-platform=nrf7002dk/nrf5340/cpuapp) (cc: @kkasperczyk-no @ArekBalysNordic @markaj-nordic)


*Note: This message is automatically posted and updated by the CI (latest/sdk-nrf/PR-19647/1)*

2024-12-19 16:17 UTC, nvlsianpu approved these changes

2024-12-19 16:46 UTC, de-nordic approved these changes

2025-01-08 08:56 UTC, tejlmand requested changes

2025-01-08 08:56 UTC, tejlmand commented on cmake/sysbuild/image_signing_firmware_loader.cmake
> +  if(CONFIG_MCUBOOT_FORCE_IN_TREE_IMGTOOL_USAGE)
as minimum the comment is now wrong, because default is no longer the explicitly installed `IMGTOOL`.

But I really would like to question the use of a kconfig for this.
IMGTOOL is looked up using `find_program()`, just like several other tools.

CMake's `find_program()` has built-in support for the user to enforce a different tool, so when `find_program(IMGTOOL imgtool)` is called, then a user can point to a specific version using: `-DIMGTOOL=/use/this/version/imgtool`.

So instead of introducing specific KConfigs for this behavior for imgtool (and any other tool) I really think we should rely on CMake's built-in behavior, as that will give a uniform way for all tools without need for extra Kconfig settings.

So if we want to default imgtool to in-tree version, then I think we should just adjust the default search path order and not introduce new Kconfigs.

2025-01-08 09:03 UTC, tejlmand commented on cmake/sysbuild/image_signing_firmware_loader.cmake
> +  if(CONFIG_MCUBOOT_FORCE_IN_TREE_IMGTOOL_USAGE)
perhaps it's good to add some general description in Zephyr's CMake docs regarding how one can point to a specific tool.
Although it's a CMake feature, I think a lot of users are not aware, so i'm fine on a small description of CMake itself in this case (perhaps with link to CMake docs).
Note, such added doc is outside scope of this PR.

2025-01-13 16:39 UTC, nvlsianpu commented on cmake/sysbuild/image_signing_firmware_loader.cmake
> +  if(CONFIG_MCUBOOT_FORCE_IN_TREE_IMGTOOL_USAGE)
@tejlmand I'm not sure about are you asking for here. We want to make sure that user is by default working with proper version of the imgtool - which is in-repo version.
Should we inject relevant -DIMGTOOL=<a path>?

2025-01-14 07:06 UTC, closed without merging

2025-01-14 07:06 UTC, nordicjm commented
This PR has been implemented upstream