samples: matter: Disabled RAM power down for nRF5340 DK
nrfconnect/sdk-nrf pull request #19675
Opened 2024-12-20 10:24 UTC by kkasperczyk-no

Disabled RAM power down for nRF5340 DK release configuration due to DFU failures.

2024-12-20 10:27 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [77754a0af29041111bbebf848702669c1b3ea3bc](https://github.com/nrfconnect/sdk-nrf/pull/19675/commits/77754a0af29041111bbebf848702669c1b3ea3bc)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [77754a0af29041111bbebf848702669c1b3ea3bc](https://github.com/nrfconnect/sdk-nrf/pull/19675/commits/77754a0af29041111bbebf848702669c1b3ea3bc)
> merge base: [84ec4da2bfb18ecc3a6adffb4ae67cb520634e04](https://github.com/nrfconnect/sdk-nrf/commit/84ec4da2bfb18ecc3a6adffb4ae67cb520634e04)
> target head (main): [dee077dd8a7deedcd9bcc9e2af3dff0483903b03](https://github.com/nrfconnect/sdk-nrf/commit/dee077dd8a7deedcd9bcc9e2af3dff0483903b03)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/84ec4da2bfb18ecc3a6adffb4ae67cb520634e04..77754a0af29041111bbebf848702669c1b3ea3bc)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (5)</summary>

```
doc
│  ├── nrf
│  │  ├── releases_and_maturity
│  │  │  │ known_issues.rst
samples
│  ├── matter
│  │  ├── light_switch
│  │  │  ├── boards
│  │  │  │  │ nrf5340dk_nrf5340_cpuapp_release.conf
│  │  ├── lock
│  │  │  ├── boards
│  │  │  │  │ nrf5340dk_nrf5340_cpuapp_release.conf
│  │  ├── smoke_co_alarm
│  │  │  ├── boards
│  │  │  │  │ nrf5340dk_nrf5340_cpuapp_release.conf
│  │  ├── window_covering
│  │  │  ├── boards
│  │  │  │  │ nrf5340dk_nrf5340_cpuapp_release.conf
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-20 10:31 UTC, adigie commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19826 The Device Firmware Upgrade (DFU) fails for nRF5340 DK with RAM power down enabled.
```suggestion
KRKNWK-19826: The Device Firmware Upgrade (DFU) fails for nRF5340 DK with RAM power down enabled.
```

2024-12-20 10:32 UTC, adigie approved these changes

2024-12-20 10:33 UTC, peknis requested changes

2024-12-20 10:33 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +KRKNWK-19826 The Device Firmware Upgrade (DFU) fails for nRF5340 DK with RAM power down enabled.
```suggestion
KRKNWK-19826 The Device Firmware Upgrade (DFU) fails for nRF5340 DK with RAM power down enabled
```
The first heading line in a known issue always without a full stop

2024-12-20 10:33 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  This option is by default enabled for the release configuration of:
```suggestion
  This option is enabled by default for the ``release`` configuration of the following samples:
```

2024-12-20 10:33 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Set the :kconfig:option:`CONFIG_RAM_POWER_DOWN_LIBRARY` Kconfig option to ``n`` in the application :file:`prj_release.conf` file.
```suggestion
  **Workaround:** Set the :kconfig:option:`CONFIG_RAM_POWER_DOWN_LIBRARY` Kconfig option to ``n`` in the :file:`prj_release.conf` file of the application.
```
```suggestion
  **Workaround:** Set the :kconfig:option:`CONFIG_RAM_POWER_DOWN_LIBRARY` Kconfig option to ``n`` in the :file:`prj_release.conf` file of the application.
```

2024-12-20 11:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19675
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-20 11:49 UTC, ArekBalysNordic approved these changes

2025-01-02 12:41 UTC, peknis requested changes

2025-01-02 12:41 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +    * :ref:`Matter window covering sample <matter_window_covering_sample>`
```suggestion
    * :ref:`matter_lock_sample`
    * :ref:`matter_light_switch_sample`
    * :ref:`matter_smoke_co_alarm_sample`
    * :ref:`matter_window_covering_sample`
```

2025-01-02 12:41 UTC, peknis commented on doc/nrf/releases_and_maturity/known_issues.rst
> +  **Workaround:** Set the :kconfig:option:`CONFIG_RAM_POWER_DOWN_LIBRARY` Kconfig option to ``n`` in the application :file:`prj_release.conf` file of the application.
```suggestion
  **Workaround:** Set the :kconfig:option:`CONFIG_RAM_POWER_DOWN_LIBRARY` Kconfig option to ``n`` in the :file:`prj_release.conf` file of the application.
```

2025-01-03 07:09 UTC, peknis approved these changes

2025-01-03 08:01 UTC, merged