doc: SUIT recovery and customize DFU update
nrfconnect/sdk-nrf pull request #19686
Opened 2024-12-20 13:19 UTC by nordic-mik7

This commit introduces changes to docs regarding SUIT recovery sample and recovery guide.
Support for recovery app configuration with external flash was added recently.
Also, minor change to Customization DFU guide was added.

2024-12-20 13:22 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [117a7a6df047cba5bd34f549f59ade18883e24cb](https://github.com/nrfconnect/sdk-nrf/pull/19686/commits/117a7a6df047cba5bd34f549f59ade18883e24cb)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [117a7a6df047cba5bd34f549f59ade18883e24cb](https://github.com/nrfconnect/sdk-nrf/pull/19686/commits/117a7a6df047cba5bd34f549f59ade18883e24cb)
> merge base: [dee077dd8a7deedcd9bcc9e2af3dff0483903b03](https://github.com/nrfconnect/sdk-nrf/commit/dee077dd8a7deedcd9bcc9e2af3dff0483903b03)
> target head (main): [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/dee077dd8a7deedcd9bcc9e2af3dff0483903b03..117a7a6df047cba5bd34f549f59ade18883e24cb)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (3)</summary>

```
doc
│  ├── nrf
│  │  ├── app_dev
│  │  │  ├── device_guides
│  │  │  │  ├── nrf54h
│  │  │  │  │  ├── ug_nrf54h20_suit_customize_dfu.rst
│  │  │  │  │  │ ug_nrf54h20_suit_recovery.rst
samples
│  ├── suit
│  │  ├── recovery
│  │  │  │ README.rst
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-sdk-dfu
   - :warning: test-sdk-dfu

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-20 13:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19686
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-23 13:06 UTC, FrancescoSer requested changes

2024-12-23 13:06 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
> +After the MPI has been flashed, it is read by the Secure Domain Firmware, which can then use it to verify if the UUIDs in a manifest are correct.
```suggestion
Once the MPI has been flashed, it is read by the SDFW, which uses it to verify the correctness of the UUIDs in the manifest.
```

2024-12-23 13:06 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_recovery.rst
> +If it isn't, booting proceeds normally by running the root manifest.
```suggestion
If it is not, the boot process continues normally by executing the root manifest.
```

2024-12-23 13:06 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_recovery.rst
> +If no MPI configuration is found the Secure Domain performs an attempt to process the normal manufacturer root manifest.
```suggestion
If no MPI configuration is found, the Secure Domain attempts to process the normal manufacturer root manifest.
```

2024-12-23 13:06 UTC, FrancescoSer commented on doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_recovery.rst
> +   This will automatically program both the main application and the recovery firmware to the device.
```suggestion
   This automatically programs both the main application and the recovery firmware onto the device.
```

2024-12-23 13:06 UTC, FrancescoSer commented on samples/suit/recovery/README.rst
> +The following limitation apply to this application:
```suggestion
The following limitation applies to this application:
```

2025-01-02 09:14 UTC, tomchy approved these changes

2025-01-03 07:44 UTC, ahasztag approved these changes

2025-01-03 10:39 UTC, richabp approved these changes

2025-01-07 17:23 UTC, nordic-mik7 commented
All requested changes were apply, review pending.

2025-01-08 11:48 UTC, b-gent approved these changes

2025-01-08 12:29 UTC, merged