subsys: bluetooth: pass information on report id in callbacks
nrfconnect/sdk-nrf pull request #19693
Opened 2024-12-20 13:56 UTC by pdunaj

Add information about report id as argument to the callbacks. The old callback format is kept for backwards compatibility.

2024-12-20 13:59 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [3239054df46ba0e4092e5fb8dd3ff9e426c6db01](https://github.com/nrfconnect/sdk-nrf/pull/19693/commits/3239054df46ba0e4092e5fb8dd3ff9e426c6db01)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [3239054df46ba0e4092e5fb8dd3ff9e426c6db01](https://github.com/nrfconnect/sdk-nrf/pull/19693/commits/3239054df46ba0e4092e5fb8dd3ff9e426c6db01)
> merge base: [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> target head (main): [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/3665a25025dcfb35f78b1d383fc37444d8618037..3239054df46ba0e4092e5fb8dd3ff9e426c6db01)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (2)</summary>

```
include
│  ├── bluetooth
│  │  ├── services
│  │  │  │ hids.h
subsys
│  ├── bluetooth
│  │  ├── services
│  │  │  │ hids.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification
   - :orange_circle: test_ble_nrf_config
   - :orange_circle: test-fw-nrfconnect-ble_samples
   - :orange_circle: test-sdk-find-my

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-20 14:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19693
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2025-01-02 10:06 UTC, MarekPieta commented on include/bluetooth/services/hids.h
> +typedef void (*bt_hids_notify_ext_handler_t) (uint8_t report_id, enum bt_hids_notify_evt evt);
I would consider deprecating the old approach to keep API simple. Similarly as here: https://github.com/nrfconnect/sdk-nrf/pull/19692#discussion_r1900656782

2025-01-02 10:12 UTC, MarekPieta commented on subsys/bluetooth/services/hids.c
> +	struct bt_hids_rep report = {
Consider extending `struct bt_hids_rep` with `uint8_t report_id` to keep the ID together with report data and to avoid changing the API. HID report ID is actually part of the HID report.

2025-01-08 12:02 UTC, pdunaj commented on include/bluetooth/services/hids.h
> +typedef void (*bt_hids_notify_ext_handler_t) (uint8_t report_id, enum bt_hids_notify_evt evt);
no deprecation - explained in the other PR

2025-01-08 12:12 UTC, pdunaj commented on subsys/bluetooth/services/hids.c
> +	struct bt_hids_rep report = {
that is a good idea, let's switch to it

2025-01-08 12:34 UTC, pdunaj commented
rebased

2025-01-13 13:07 UTC, MarekPieta requested changes

2025-01-13 13:07 UTC, MarekPieta commented on subsys/bluetooth/services/hids.c
> +		inp_rep->handler_ext(report_id, evt);
Similar update seems needed for `hids_boot_mouse_inp_rep_ccc_changed` and `hids_boot_kb_inp_rep_ccc_changed`. Alternatively we could assert or return error to prevent user from registering the extended callback there (report ID parameter is not used for boot reports).

2025-01-13 13:23 UTC, MarekPieta commented on subsys/bluetooth/services/hids.c
> +		inp_rep->handler_ext(report_id, evt);
Discussed offline. Overlooked that HID boot reports use another structure type. We can leave it as is.

2025-01-13 13:23 UTC, MarekPieta approved these changes

2025-01-13 13:26 UTC, pdunaj commented
@zycz , please tick.

2025-01-13 13:27 UTC, pdunaj commented
unstable tests failed - will retrigger

2025-01-13 13:29 UTC, pdunaj commented
rebased

2025-01-16 08:21 UTC, zycz approved these changes

2025-01-16 08:22 UTC, zycz commented
Do want to add it to changelog?

2025-01-16 10:08 UTC, merged