applications: nrf_desktop: Support passthrough reports in hid state
nrfconnect/sdk-nrf pull request #19690
Opened 2024-12-20 13:41 UTC by pdunaj

Allow the hid state module to handle reports created by external modules. These reports will still be sent according to the his state rules.

2024-12-20 13:43 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [64dd11a595c4e36904b11f7d760c303bb9b4ebdc](https://github.com/nrfconnect/sdk-nrf/pull/19690/commits/64dd11a595c4e36904b11f7d760c303bb9b4ebdc)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [64dd11a595c4e36904b11f7d760c303bb9b4ebdc](https://github.com/nrfconnect/sdk-nrf/pull/19690/commits/64dd11a595c4e36904b11f7d760c303bb9b4ebdc)
> merge base: [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> target head (main): [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/3665a25025dcfb35f78b1d383fc37444d8618037..64dd11a595c4e36904b11f7d760c303bb9b4ebdc)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (4)</summary>

```
applications
│  ├── nrf_desktop
│  │  ├── configuration
│  │  │  ├── common
│  │  │  │  │ hid_report_desc.h
│  │  ├── src
│  │  │  ├── modules
│  │  │  │  ├── Kconfig.hid_state
│  │  │  │  ├── hid_state.c
│  │  │  │  │ usb_state.c
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-20 13:49 UTC, pdunaj commented
why @nrfconnect/ncs-co-build-system is needed for review of app specific kconfig?
@carlescufi , can it be fixed for our apps or is this some global setting on all kconfigs?

2024-12-20 13:51 UTC, nordicjm commented
> why @nrfconnect/ncs-co-build-system is needed for review of app specific kconfig? @carlescufi , can it be fixed for our apps or is this some global setting on all kconfigs?

Because of the amount of abuse and wrong things in Kconfigs all over the tree that have improved substantially now things are actually reviewed and issues pointed out

2024-12-20 13:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19690
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2024-12-20 15:44 UTC, pdunaj commented
Appease pedantic checkpatch

2024-12-23 07:52 UTC, nordicjm commented on applications/nrf_desktop/src/modules/Kconfig.hid_state
> +	bool
missing a prompt?

2025-01-03 09:51 UTC, MarekPieta requested changes

2025-01-03 09:51 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/hid_state.c
> +				   IS_ENABLED(CONFIG_DESKTOP_HID_REPORT_BOOT_INTERFACE_KEYBOARD))
Also in other places

2025-01-08 10:55 UTC, pdunaj commented on applications/nrf_desktop/src/modules/Kconfig.hid_state
> +	bool
I have not added prompt as I want this to be selected only when specific type of report is actually enabled.

2025-01-08 10:57 UTC, nordicjm commented on applications/nrf_desktop/src/modules/Kconfig.hid_state
> +	bool
Then none of this makes sense, the help text clearly states it can be enabled and there is no way to enable it, and none of this code is tested

2025-01-08 11:00 UTC, pdunaj commented
> > why @nrfconnect/ncs-co-build-system is needed for review of app specific kconfig? @carlescufi , can it be fixed for our apps or is this some global setting on all kconfigs?
> 
> Because of the amount of abuse and wrong things in Kconfigs all over the tree that have improved substantially now things are actually reviewed and issues pointed out

Each should focus on making they part work and be done on time, instead of worrying about "abuse and wrong things" in source they are not responsible for.

2025-01-08 11:11 UTC, pdunaj commented on applications/nrf_desktop/src/modules/hid_state.c
> +	struct hid_report_event *event = new_hid_report_event(report_size);
I was thinking about this. Also about moving the report composition outside of this file and so splitting the responsibilities. At this point I don't want to make such a big rework as there is no value in it.

2025-01-08 11:13 UTC, pdunaj commented on applications/nrf_desktop/src/modules/hid_state.c
> +	if (try_send_always && !report_sent) {
There was no use case for this. I would stick only to what is required to achieve the required functionality.

2025-01-08 11:17 UTC, pdunaj commented on applications/nrf_desktop/src/modules/hid_state.c
> +			handle_raw_input_report(NULL, report_id, data, size);
this will make the things complicated as you need to know what you are subscribing to. I aim at having this information outside of this module. I can imagine how this could be restructured but it would need more changes for no reason - it works as it is done atm.

2025-01-08 11:20 UTC, pdunaj commented on applications/nrf_desktop/src/modules/usb_state.c
> +	for (size_t i = 0; i < ARRAY_SIZE(input_reports); i++) {
Kept it here as it is a change following the input_reports.
I don't see a reason why we would spend more then few more minutes in this PR, why opening new PR then?

2025-01-08 11:23 UTC, pdunaj commented on applications/nrf_desktop/src/modules/hid_state.c
> +		rd->raw_data.data = k_malloc(size + sizeof(report_id));
Don't see what you refer to.
This will work similarly to consumer/system ctrl report - no pipeline. It serves the purpose it was created for.
Error is handled, unless I missed something...

2025-01-08 11:26 UTC, pdunaj commented on applications/nrf_desktop/src/modules/hid_state.c
> +	LOG_WRN("Sending raw data report %d of size %zu", rs->report_id, rd->raw_data.size);
Removed the log - there is no reason as this occurrence will be logged in the event manager.

2025-01-08 11:29 UTC, pdunaj commented
rebased

2025-01-08 11:36 UTC, tejlmand commented on applications/nrf_desktop/src/modules/Kconfig.hid_state
> +	bool
> I have not added prompt as I want this to be selected only when specific type of report is actually enabled.

but no Kconfigs are selecting this symbol.
And which specific type of reports are you referring to ?
The setting has no `depends on`.

I think help text should be improved so that NCS users at least are able to understand when / how this setting is supposed to be used / why it is a hidden (prompt-less) setting.

2025-01-08 14:34 UTC, pdunaj commented on applications/nrf_desktop/src/modules/Kconfig.hid_state
> +	bool
> Then none of this makes sense

It can be that I have simply failed at writing simple enough help. Have not focus on this really. I have checked help text in various promptless options in Zephyr repo. I see that the word "Enable/d" is often used so I expect it's not impossible to get that enable means select in such cases.

> I think help text should be improved so that NCS users...

@tejlmand , this change is part of more work needed, which is not public. I don't expect this will impact a generic NCS user since this app is very specific. Anyway this time waste is a good example of what I meant in my original comment. You clearly don't understand what is being done (which is fine as you have your own problems) and we have entered a bikeshedding discussion which is simply a time waste.

I will need to run one more edit as test failed and will add additional explanation to make you happy. Let's focus on something more productive on both ends.

2025-01-13 13:18 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/hid_state.c
> +	struct hid_report_event *event = new_hid_report_event(report_size);
Then maybe we could at least queue the report as `hid_report_event`? That would simplify implementation and speed up code execution

2025-01-13 13:29 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/hid_state.c
> +		rd->raw_data.data = k_malloc(size + sizeof(report_id));
Another raw HID report may be submitted while HID state enqueues the previous one. I would assert or log error to avoid silently leaking memory.

2025-01-13 13:29 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/usb_state.c
> +	for (size_t i = 0; i < ARRAY_SIZE(input_reports); i++) {
Smaller PRs tend to go in quicker. I would not insist here.

2025-01-13 13:44 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/hid_state.c
> +			handle_raw_input_report(NULL, report_id, data, size);
Should we pass the `sub` pointer to `handle_raw_input_report` then? The raw hid report source cannot select the subscriber anyway (we could even assert that `event->subscriber == NULL`)

2025-01-13 15:06 UTC, pdunaj commented
ping @MarekPieta

2025-01-13 15:45 UTC, MarekPieta commented
Added short review comments under existing threads

2025-02-25 00:34 UTC, closed without merging