applications: nrf_desktop: generic max report size handling
nrfconnect/sdk-nrf pull request #19691
Opened 2024-12-20 13:43 UTC by pdunaj

Handle max input and output report size in scalable way.

2024-12-20 13:45 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [059a2ed263744294de81f9420dd963901983ddc2](https://github.com/nrfconnect/sdk-nrf/pull/19691/commits/059a2ed263744294de81f9420dd963901983ddc2)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [059a2ed263744294de81f9420dd963901983ddc2](https://github.com/nrfconnect/sdk-nrf/pull/19691/commits/059a2ed263744294de81f9420dd963901983ddc2)
> merge base: [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> target head (main): [3665a25025dcfb35f78b1d383fc37444d8618037](https://github.com/nrfconnect/sdk-nrf/commit/3665a25025dcfb35f78b1d383fc37444d8618037)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/3665a25025dcfb35f78b1d383fc37444d8618037..059a2ed263744294de81f9420dd963901983ddc2)</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (1)</summary>

```
applications
│  ├── nrf_desktop
│  │  ├── configuration
│  │  │  ├── common
│  │  │  │  │ hid_report_desc.h
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: desktop52_verification

<details><summary>Disabled integration tests</summary>

- 
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-chip
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-20 13:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='https://ncsdoc.z6.web.core.windows.net/PR-19691
/'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publish GitHub Action.*

2025-01-02 10:04 UTC, MarekPieta requested changes

2025-01-08 11:38 UTC, pdunaj commented on applications/nrf_desktop/configuration/common/hid_report_desc.h
> +#if CONFIG_DESKTOP_HID_REPORT_MOUSE_SUPPORT || CONFIG_DESKTOP_HID_REPORT_BOOT_INTERFACE_MOUSE
the hid_state is using the same report data for both boot and normal variants. This is why I used this setup - it makes sure that code always works.

2025-01-08 11:41 UTC, pdunaj commented
rebased

2025-01-13 10:15 UTC, MarekPieta commented on applications/nrf_desktop/configuration/common/hid_report_desc.h
> +#if CONFIG_DESKTOP_HID_REPORT_MOUSE_SUPPORT || CONFIG_DESKTOP_HID_REPORT_BOOT_INTERFACE_MOUSE
This implementation limitation is already handled by Kconfig dependency here: https://github.com/nrfconnect/sdk-nrf/blob/main/applications/nrf_desktop/Kconfig.hid#L169-L175. I think we could simplify here then.

2025-01-13 11:10 UTC, pdunaj commented
@zycz , please tick

2025-01-13 12:23 UTC, zycz approved these changes

2025-01-13 12:45 UTC, MarekPieta approved these changes

2025-01-13 15:05 UTC, merged