samples: matter: disable mpsl before preforming factory reset
nrfconnect/sdk-nrf pull request #19696
Opened 2024-12-20 14:37 UTC by ArekBalysNordic

We can speed up flash operations while performing a factory reset by disabling mpsl before that.

Thanks to that flash operations do not wait for mpsl synchronization and all write operations take less time.

2024-12-20 14:38 UTC, NordicBuilder commented
The following west manifest projects have changed revision in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/20babbe7904f55511c39f19cae2162f7b770f974 | https://github.com/nrfconnect/sdk-connectedhomeip/pull/527 | [nrfconnect/sdk-connectedhomeip#527/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/527/files) |

⛔ **DNM label due to: 1 project with PR revision**

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-12-20 14:40 UTC, NordicBuilder commented
## CI Information

<sup>_To view the history of this post, clich the 'edited' button above_</sup>
Build number: 1
### Inputs:
#### Sources:
sdk-nrf: PR head: [bca218c40a0fc3334b6326c584dc59b012f81aff](https://github.com/nrfconnect/sdk-nrf/pull/19696/commits/bca218c40a0fc3334b6326c584dc59b012f81aff)
matter: PR head: [885aa07c65e987ebbea1806144060f0ee12677f9](https://github.com/nrfconnect/sdk-connectedhomeip/pull/527/commits/885aa07c65e987ebbea1806144060f0ee12677f9)
<details><summary> more details</summary>

sdk-nrf:
> PR head: [bca218c40a0fc3334b6326c584dc59b012f81aff](https://github.com/nrfconnect/sdk-nrf/pull/19696/commits/bca218c40a0fc3334b6326c584dc59b012f81aff)
> merge base: [31d1fa50d22bae9559f3ee06303ca56823a79a3e](https://github.com/nrfconnect/sdk-nrf/commit/31d1fa50d22bae9559f3ee06303ca56823a79a3e)
> target head (main): [37fba0b31a04db7499cc9cc7c77f4e60a7b77117](https://github.com/nrfconnect/sdk-nrf/commit/37fba0b31a04db7499cc9cc7c77f4e60a7b77117)
> [Diff](https://github.com/nrfconnect/sdk-nrf/compare/31d1fa50d22bae9559f3ee06303ca56823a79a3e..bca218c40a0fc3334b6326c584dc59b012f81aff)

matter:
> PR head: [885aa07c65e987ebbea1806144060f0ee12677f9](https://github.com/nrfconnect/sdk-connectedhomeip/pull/527/commits/885aa07c65e987ebbea1806144060f0ee12677f9)
> merge base: [20babbe7904f55511c39f19cae2162f7b770f974](https://github.com/nrfconnect/sdk-connectedhomeip/commit/20babbe7904f55511c39f19cae2162f7b770f974)
> target head (master): [2340e0aad89bd415a3a1faa0af0da69169c8aa4a](https://github.com/nrfconnect/sdk-connectedhomeip/commit/2340e0aad89bd415a3a1faa0af0da69169c8aa4a)
> [Diff](https://github.com/nrfconnect/sdk-connectedhomeip/compare/20babbe7904f55511c39f19cae2162f7b770f974..885aa07c65e987ebbea1806144060f0ee12677f9)
</details>

#### Github labels
| Enabled | Name | Description |
| -- | -- | -- |
|| ci-disabled | _Disable the ci execution_ | 
|| ci-all-test | _Run all of ci, no test spec filtering will be done_ | 
|| ci-force-downstream | _Force execution of downstream even if twister fails_ | 
|| ci-run-twister | _Force run twister_ | 
|| ci-run-zephyr-twister | _Force run zephyr twister_ | 

<details><summary> List of changed files detected by CI (7)</summary>

```
modules
│  ├── lib
│  │  ├── matter
│  │  │  ├── .github
│  │  │  │  ├── workflows
│  │  │  │  │  │ release_tools.yaml
│  │  │  ├── config
│  │  │  │  ├── nrfconnect
│  │  │  │  │  ├── chip-module
│  │  │  │  │  │  ├── Kconfig
│  │  │  │  │  │  │ Kconfig.defaults
│  │  │  ├── src
│  │  │  │  ├── platform
│  │  │  │  │  ├── Zephyr
│  │  │  │  │  │  │ ConfigurationManagerImpl.cpp
│  │  │  │  │  ├── nrfconnect
│  │  │  │  │  │  │ SystemPlatformConfig.h
samples
│  ├── matter
│  │  ├── common
│  │  │  ├── src
│  │  │  │  ├── app
│  │  │  │  │  │ fabric_table_delegate.h
west.yml
```
</details>

### Outputs:

#### Toolchain
Version: 
Build docker image: 

#### Test Spec & Results: :white_check_mark: Success; :x: Failure; :orange_circle: Queued; :yellow_circle: Progress; :white_medium_square: Skipped; :warning: Quarantine
- :orange_circle: Toolchain
- :orange_circle: Build twister
- :orange_circle: Integration tests
   - :orange_circle: test-fw-nrfconnect-chip

<details><summary>Disabled integration tests</summary>

- 
   - desktop52_verification
   - doc-internal
   - test_ble_nrf_config
   - test-fw-nrfconnect-apps
   - test-fw-nrfconnect-ble_mesh
   - test-fw-nrfconnect-ble_samples
   - test-fw-nrfconnect-boot
   - test-fw-nrfconnect-fem
   - test-fw-nrfconnect-nfc
   - test-fw-nrfconnect-nrf-iot_libmodem-nrf
   - test-fw-nrfconnect-nrf-iot_lwm2m
   - test-fw-nrfconnect-nrf-iot_mosh
   - test-fw-nrfconnect-nrf-iot_nrf_provisioning
   - test-fw-nrfconnect-nrf-iot_positioning
   - test-fw-nrfconnect-nrf-iot_samples
   - test-fw-nrfconnect-nrf-iot_serial_lte_modem
   - test-fw-nrfconnect-nrf-iot_thingy91
   - test-fw-nrfconnect-nrf-iot_zephyr_lwm2m
   - test-fw-nrfconnect-nrf_crypto
   - test-fw-nrfconnect-ps
   - test-fw-nrfconnect-rpc
   - test-fw-nrfconnect-rs
   - test-fw-nrfconnect-tfm
   - test-fw-nrfconnect-thread
   - test-fw-nrfconnect-zigbee
   - test-low-level
   - test-sdk-audio
   - test-sdk-dfu
   - test-sdk-find-my
   - test-sdk-mcuboot
   - test-sdk-pmic-samples
   - test-sdk-sidewalk
   - test-sdk-wifi
   - test-secdom-samples-public
</details>



*Note: This message is automatically posted and updated by the CI*

2024-12-23 07:51 UTC, nordicjm approved these changes

2025-01-02 12:56 UTC, peknis requested changes

2025-01-02 12:56 UTC, peknis commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +The factory reset functionality allows you to reset the device to its factory settings and remove all Matter and network non-volatile data.
```suggestion
The factory reset functionality allows you to reset the device to its factory settings and remove all non-volatile data related to Matter and network.
```

2025-01-02 12:56 UTC, peknis commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +The default implementation of the factory reset callback is located in the :file:`ncs/nrf/samples/matter/common/src/app/matter_init.cpp` file and it disables :ref:`mpsl` to speed up flash operations
```suggestion
The default implementation of the factory reset callback is located in the :file:`ncs/nrf/samples/matter/common/src/app/matter_init.cpp` file and it disables the :ref:`mpsl` to speed up flash operations during the factory reset.
```

2025-01-02 12:56 UTC, peknis commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +You can define your own factory reset callback by implementing it and setting it in the Configuration Manager module using the ``ConfigurationManagerImpl().SetFactoryResetDeviceCallback()`` method af
```suggestion
To define your own factory reset callback, implement and set it in the Configuration Manager module using the ``ConfigurationManagerImpl().SetFactoryResetDeviceCallback()`` method after initializing the Matter stack.
```
Where is the Configuration Manager module? Can we link to it?

2025-01-02 12:56 UTC, peknis commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  :ref:`mpsl` is also disabled during the last fabric removal process and is re-enabled after the flash operations are completed.
```suggestion
* Added the factory reset callback and described its usage in the :ref:`ug_matter_persistent_storage_factory_reset` section of the Matter documentation.
  The default implementation of the factory reset callback disables the :ref:`mpsl` before performing flash operations to speed up the process.
  The :ref:`mpsl` is also disabled during the last fabric removal process and is re-enabled after the flash operations are completed.
```

2025-01-03 09:00 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +You can define your own factory reset callback by implementing it and setting it in the Configuration Manager module using the ``ConfigurationManagerImpl().SetFactoryResetDeviceCallback()`` method af
It is a module inside the Matter core, and it is not described anywhere in the docs. I can add a sentence where it is, though.

2025-01-03 09:12 UTC, peknis approved these changes

2025-01-03 09:54 UTC, kkasperczyk-no commented on samples/matter/common/src/app/fabric_table_delegate.h
> +#if !defined(CONFIG_SOC_SERIES_NRF53X) && !defined(CONFIG_SOC_SERIES_NRF54HX)
Let's try to use maybe `CONFIG_MPSL` instead of listing the specific socs.

2025-01-03 09:54 UTC, kkasperczyk-no commented on samples/matter/common/src/app/fabric_table_delegate.h
> +#include <mpsl/mpsl_lib.h>
Put include under ifdef please.

2025-01-03 09:56 UTC, kkasperczyk-no commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +The default implementation of the factory reset callback is located in the :file:`ncs/nrf/samples/matter/common/src/app/matter_init.cpp` file and it disables the :ref:`mpsl` to speed up flash operati
Maybe it's worth to mention it is done only for the single core solution, as for multi-cores it is not needed.

2025-01-03 10:17 UTC, ArekBalysNordic commented on samples/matter/common/src/app/fabric_table_delegate.h
> +#if !defined(CONFIG_SOC_SERIES_NRF53X) && !defined(CONFIG_SOC_SERIES_NRF54HX)
Added `CONFIG_SOC_FLASH_NRF_RADIO_SYNC_MPSL` which is more accurate for this purpose.

2025-01-03 10:18 UTC, ArekBalysNordic commented on doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
> +The default implementation of the factory reset callback is located in the :file:`ncs/nrf/samples/matter/common/src/app/matter_init.cpp` file and it disables the :ref:`mpsl` to speed up flash operati
@peknis I've added such a line there.

2025-01-03 10:50 UTC, LuDuda commented on samples/matter/common/src/app/fabric_table_delegate.h
> +				mpsl_lib_uninit();
Just thinking loud - is there any possible issue (ala race condition) that `mpsl_lib_uninit` might be called while there is some ongoing Radio Driver operation? Maybe we should put the Thread interface down before?

FYI: @ankuns

2025-01-03 11:15 UTC, ArekBalysNordic commented on samples/matter/common/src/app/fabric_table_delegate.h
> +				mpsl_lib_uninit();
Or maybe we can just lock the Thread stack? What do you think? Do you mean calling there `ot_` function to disable Thread? Using Matter ThreadStackManager API we can only lock the stack.

2025-01-08 09:42 UTC, adigie commented on samples/matter/common/src/app/fabric_table_delegate.h
>  				chip::DeviceLayer::ConnectivityMgr().ErasePersistentInfo();
Does it work here with mpsl disabled? You moved it in another PR:
https://github.com/nrfconnect/sdk-connectedhomeip/pull/527/files#diff-af293fbf4365f90c5d31f4d568f6b390c4f932deb14377367b0dab1335af4e45R228

2025-01-08 09:58 UTC, ArekBalysNordic commented on samples/matter/common/src/app/fabric_table_delegate.h
>  				chip::DeviceLayer::ConnectivityMgr().ErasePersistentInfo();
right, it should be done before disabling mspl, thanks!

2025-01-08 13:07 UTC, adigie approved these changes

2025-01-09 13:50 UTC, LuDuda requested changes

2025-01-09 13:50 UTC, LuDuda commented on samples/matter/common/src/app/fabric_table_delegate.h
> +				mpsl_lib_uninit();
As disucssed F2F, let's remove it from here and just modify Matter Platform's code.

2025-01-09 15:05 UTC, ArekBalysNordic commented on samples/matter/common/src/app/fabric_table_delegate.h
> +				mpsl_lib_uninit();
Provided requested changes.

2025-01-09 15:37 UTC, LuDuda requested changes

2025-01-09 15:37 UTC, LuDuda commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  The :ref:`mpsl` is also disabled during the last fabric removal process and is re-enabled after the flash operations are completed.
This is not true now, right?

2025-01-10 07:47 UTC, ArekBalysNordic commented on doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> +  The :ref:`mpsl` is also disabled during the last fabric removal process and is re-enabled after the flash operations are completed.
Fixed.

2025-01-10 09:19 UTC, LuDuda approved these changes

2025-01-10 10:20 UTC, merged