cmake: multi image: pass on the DTC_OVERLAY_FILE to sub images
nrfconnect/sdk-nrf pull request #2630
Opened 2020-07-23 20:21 UTC by plskeggs

Device tree overlay files can be used to modify a board's device tree,
including things such as the UART TX/RX/CTS/RTS lines. This must be
passed on to sub images, especially mcuboot, so that, for example,
the logging UART uses the correct hardware pins for mcuboot.

Jira: NCSDK-5972

Signed-off-by: Pete Skeggs <peter.skeggs@nordicsemi.no>

2020-07-24 02:54 UTC, mbolivar-nordic commented
Hmm, sorry if I misled you when we were discussing on slack, but I don't think this is correct:

> This must be passed on to sub images, especially mcuboot, so that, for example,
> the logging UART uses the correct hardware pins for mcuboot.

I think doing this would in fact lead to errors. Devicetree overlays may or may not be application specific and passing them all along to sub-images will cause no end of "fun".

For example, if we did that, any peripheral drivers (SPI, say) which were turned on by the application due to the corresponding devicetree nodes being enabled would also be turned on for mcuboot. MCUboot doesn't need a SPI driver and this would just bloat the binary in the best case, or even break it in the worst case.

This is why I mentioned that I believe there is a mechanism to pass along a specific overlay along to sub-images. Using that mechanism is what I think needs to happen, but that's on an application specific basis.

Please close if you agree.

2020-07-24 04:31 UTC, plskeggs commented
OK, I can see your point.  I have so far found no documentation about "there is a mechanism to pass along a specific overlay along to sub-images."  Once I find such documentation, or someone here or on Teams points me in the right direction, I will close it.

2020-07-24 17:50 UTC, mbolivar-nordic commented
I found add_overlay_config() in nrf/cmake/extensions.cmake, but that's limited to Kconfig .conf files, not DTS overlays.

Looks like this mechanism is indeed missing. I think this issue could perhaps be converted to adding a similar extension to add_overlay_config() for DTS.

2020-08-26 11:45 UTC, tejlmand commented
> OK, I can see your point. I have so far found no documentation about "there is a mechanism to pass along a specific overlay along to sub-images." Once I find such documentation, or someone here or on Teams points me in the right direction, I will close it.

You can pass anything to the subimage, just prefix with subimage.
As example, for SPM, do:
```
cmake ... -Dspm_DTC_OVERLAY_FILE=<spm_specific_overlay_file> ...`
```

2020-08-26 11:47 UTC, tejlmand commented
@plskeggs see more here: http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_multi_image.html#image-specific-variables

2020-08-26 11:48 UTC, tejlmand requested changes
I believe this is already possible.
http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_multi_image.html#image-specific-variables

2020-08-26 17:33 UTC, plskeggs commented
OK, I'll withdraw this.  I tried a test with asset_tracker:

`C:\source\ncs\nrf>west build -p always -b thingy91_nrf9160ns -d build applications/asset_tracker -- -Dmcuboot_DTC_OVERLAY_FILE=c:/source/ncs/nrf/applications/asset_tracker/thingy91_nrf9160ns.overlay`

where thingy91_nrf9160ns.overlay contains:
`&uart0 {
	current-speed = <1000000>;
};
`
and the resulting build/mcuboot/zephyr/zephyr.dts now contains:
`
			uart0: uart@8000 {
...
				current-speed = < 0xf4240 >;
`
so, it is possible.  I think this should be better documented somewhere specifically about customizing hardware that affects logging.  But that would be a different PR.

2020-08-26 17:35 UTC, closed without merging