docs: update Thread CoAP client MED/SED info
nrfconnect/sdk-nrf pull request #2786
Opened 2020-08-27 12:21 UTC by greg-fer

Changed SED to MED in Thread CoAP client sample docs.
KRKNWK-7186

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2020-08-27 12:34 UTC, pszkotak requested changes
Some clarifications needed.
Please note that in the MED mode there is a serial console avaialble.

2020-08-27 12:34 UTC, pszkotak commented on samples/openthread/coap_client/README.rst
> +This means that the radio is enabled, but the serial console is disabled to save power.
```suggestion
This means that the radio is enabled when idle and the serial console is operating.
```

2020-08-27 12:34 UTC, pszkotak commented on samples/openthread/coap_client/README.rst
> +At this point, the radio is disabled and power consumption decreases.
```suggestion
At this point, the radio is disabled when idle and the serial console is not working to decrease the power consumption.
```

2020-08-27 12:34 UTC, pszkotak commented on samples/openthread/coap_client/README.rst
> +Switching between SED and MED modes does not affect the standard testing procedure.
Not sure if we should expand this part, leaving it to your judgement.
```suggestion
Switching between SED and MED modes does not affect the standard testing procedure, except for the fact that LEDs and terminal logs are not available in the SED mode.
```

2020-08-27 12:52 UTC, pszkotak commented on samples/openthread/coap_client/README.rst
> +Switching between SED and MED modes does not affect the standard testing procedure.
My bad, LEDs work just fine in the SED mode. Only the LED3 is turned off.

2020-08-27 13:37 UTC, pszkotak approved these changes
LGTM!

2020-08-28 08:29 UTC, rlubos approved these changes

2020-08-28 08:29 UTC, merged