applications: nrf_desktop: Update event propagation arrays
nrfconnect/sdk-nrf pull request #2837
Opened 2020-09-04 09:49 UTC by MarekPieta

Change updates event propagation arrays.

2020-09-04 10:13 UTC, pdunaj approved these changes

2020-09-07 07:23 UTC, greg-fer requested changes
Please apply fixes to the following issues:
- CPU measurement module table is not visible in the output.
- New module pages are missing Implementation details and Configuration information.
- The new module pages are missing from the Internal application modules list.

2020-09-07 11:25 UTC, pdunaj approved these changes

2020-09-07 11:26 UTC, greg-fer approved these changes

2020-09-11 09:26 UTC, merged