Added support for nrf5340pdk_nrf5340_cpuappns
nrfconnect/sdk-nrf pull request #2864
Opened 2020-09-08 12:18 UTC by DatGizmo

The primary change is the first commit, witch adds the "nrf5340pdk_nrf5340_cpuappns" to the Jenkins build.

I also noticed that not in all places where the "nrf5340pdk_nrf5340_cpuapp" was liste, the "nrf5340pdk_nrf5340_cpuappns" was listed as well. So I added them where there where missing.

2020-09-08 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=2864) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=2864) before we can accept your contribution.<br/><hr/>**Sebastian Wezel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=2864) it.</sub>

2020-09-11 09:52 UTC, trond-snekvik approved these changes

2020-09-18 08:12 UTC, joerchan approved these changes

2020-09-18 15:25 UTC, carlescufi commented
@DatGizmo you need to fix your commit formatting

2020-09-23 06:40 UTC, grochu approved these changes
Looks good.

2020-09-23 07:50 UTC, doki-nordic requested changes

2020-09-23 07:50 UTC, doki-nordic commented on samples/nrf5340/empty_app_core/CMakeLists.txt
> +  nrf5340pdk_nrf5340_cpuappns
NS is not supported by this sample (intentionally). Please remove this line.

2020-09-23 07:50 UTC, doki-nordic commented on samples/nrf5340/empty_app_core/sample.yaml
> +    platform_whitelist: nrf5340pdk_nrf5340_cpuapp nrf5340pdk_nrf5340_cpuappns
NS is not supported by this sample (intentionally). Please remove this change.

2020-10-01 08:02 UTC, kapi-no approved these changes
Thanks for adding nRF53 NS target to the CI on my request.

I initially thought that it is enough to add the nRF53 NS target to just one sample from each category (e.g one BLE sample, one NFC sample) so that we avoid overloading the CI. However, if this load is okay for CI, then having all samples covered with NS targets is even better.

2020-10-01 08:29 UTC, doki-nordic approved these changes

2020-10-01 09:14 UTC, DatGizmo commented
This adds 19 test which take ~4 min.

2020-10-12 09:11 UTC, DatGizmo commented
Rebased my changes to the latest master.

2020-10-12 12:30 UTC, thst-nordic approved these changes
sdk-nrf pipeline is now updated to run nrf5340pdk, just needs 1 more run on CI to verify

2020-10-13 08:15 UTC, merged