openthread: samples: Added using UART HWFC by default.
nrfconnect/sdk-nrf pull request #2879
Opened 2020-09-09 10:24 UTC by kkasperczyk-no

Overlays setting UART hardware flow control by default
were added/extended.

KRKNWK-7370

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2020-09-09 10:29 UTC, MarekPorwisz requested changes
what about coap client?

2020-09-09 10:45 UTC, kkasperczyk-no commented
> what about coap client?

Right, I forgot that coap client is not always working as SED and may use UART too.

2020-09-14 07:46 UTC, MarekPorwisz approved these changes

2020-09-14 07:47 UTC, MarekPorwisz commented
Don't we need to update some doc to inform user that HWFC needs to be enabled for Thread samples?

2020-09-14 08:22 UTC, kkasperczyk-no commented
> Don't we need to update some doc to inform user that HWFC needs to be enabled for Thread samples?

@MarekPorwisz it wasn't considered when the task was planned, but actually I think it could be useful. On the other hand it requires also adding some kind of guide for user, how to configure HWFC support on PC and boards' JLink. Do you think we could merge this as it is and create new task on documentation after consulting with tech writer or redefine it and merge it including complete documentation?

2020-09-14 09:53 UTC, kkasperczyk-no commented
I placed mention in each Thread sample informing that by default HWFC mechanism is enabled.

2020-09-14 10:05 UTC, MarekPorwisz requested changes

2020-09-14 10:05 UTC, MarekPorwisz commented on samples/openthread/coap_server/README.rst
> +Sample by default uses hardware flow control mechanism in serial communication.
Move this somewhere around where putty is mentioned.

2020-09-14 10:05 UTC, MarekPorwisz commented on samples/openthread/coap_client/README.rst
> +Sample by default uses hardware flow control mechanism in serial communication.
Move this somewhere around where putty is mentioned i.e.  ~line 139

2020-09-14 10:05 UTC, MarekPorwisz commented on samples/openthread/cli/README.rst
> +Sample by default uses hardware flow control mechanism in serial communication.
Move this somewhere around where putty is mentioned. (Probably multiple places in this sample)

2020-09-16 10:34 UTC, greg-fer approved these changes
Approving, but note there is a follow-up task for after 1.4 release: https://projecttools.nordicsemi.no/jira/browse/KRKNWK-7447

2020-09-16 10:55 UTC, MarekPorwisz approved these changes

2020-09-17 06:44 UTC, kkasperczyk-no commented
@carlescufi it's approved and all green, could you merge it, as I'm waiting for this change?

2020-09-18 09:19 UTC, rlubos approved these changes

2020-09-18 09:19 UTC, merged