doc: lib: lwm2m_carrier: documentation update
nrfconnect/sdk-nrf pull request #2941
Opened 2020-09-18 08:10 UTC by nordic-hani

- Updated version dependency table and moved it up.
- Added "important" to help communicate mandatory nature of the lib.
- Added link to the infocenter Mobile network operator certifications.

Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>

2020-09-18 10:05 UTC, umapraseeda approved these changes

2020-09-22 07:07 UTC, umapraseeda requested changes

2020-09-22 07:34 UTC, bjorn-tore-taraldsen approved these changes

2020-09-22 10:45 UTC, umapraseeda approved these changes

2020-09-25 08:16 UTC, lemrey approved these changes

2020-09-25 12:39 UTC, lemrey commented
Thanks; we should backport this to `v1.3-branch` too.

2020-09-29 12:12 UTC, rlubos approved these changes

2020-09-29 12:12 UTC, merged