Bluetooth: Mesh: Time models documentation
nrfconnect/sdk-nrf pull request #2972
Opened 2020-09-23 12:43 UTC by trond-snekvik

Adds documentation for the time models, and ensures that the time server
relay doesn't end up in a feedback loop.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

2020-09-29 12:15 UTC, joerchan requested changes
The documentation and the fix should be separate commits.

2020-09-30 07:37 UTC, joerchan approved these changes

2020-09-30 12:15 UTC, joerchan commented
@trond-snekvik CI documentation build failed with valid errors.

2020-10-01 07:49 UTC, Andrewpini commented on include/bluetooth/mesh/time_srv.rst
> +As described in the section on :ref:`bt_mesh_time_tai_readme`, the Time Server measures time as TAI seconds, and adds the UTC leap second offset and local time zone as additional information.
:ref:`bt_mesh_time_tai` ?

2020-10-01 07:55 UTC, Andrewpini approved these changes
This looks good to me. I have added one comment regarding a hyperlink reference that I suspect might be wrong, but other than that it looks good to go.

2020-10-01 13:13 UTC, Andrewpini approved these changes

2020-10-06 08:29 UTC, mia-ko requested changes

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time.rst
> +To convert to UTC, TAI based applications keep track of the UTC leap seconds separately, as well as time zone and time zone adjustments.
```suggestion
To convert to UTC, TAI based applications keep track of the UTC leap seconds separately, as well as the time zone and time zone adjustments.
```

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time_srv.rst
> +The Time Server model builds an ad-hoc time synchronization hierarchy through the mesh network, that propagates the current wall clock time as TAI timestamps.
```suggestion
The Time Server model builds an ad-hoc time synchronization hierarchy through the mesh network, that propagates the current wall-clock time as TAI timestamps.
```
Either wall-clock time or wall time :)

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time_srv.rst
> +   Time Server nodes that have no neighboring Time Servers need to get this information some other way.
```suggestion
   Time Server nodes that have no neighboring Time Servers need to get this information in some other way.
```

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time_srv.rst
> +
```suggestion
The Time Server inherits the uncertainty of the node it got its Time Status from, and the clock uncertainty of each mesh node increases for every hop the Time Status had to make from the Time Authority.

```

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time_srv.rst
> +   The TAI time is a composite state, with members ``sec`` and an 8 bit ``subsec``.
```suggestion
   The TAI time is a composite state, with members ``sec`` and an 8-bit ``subsec``.
```

2020-10-06 08:29 UTC, mia-ko commented on include/bluetooth/mesh/time_srv.rst
> +   Local time zone offset in 15 minute increments.
```suggestion
   Local time zone offset in 15-minute increments.
```

2020-10-06 12:10 UTC, mia-ko approved these changes

2020-10-08 11:58 UTC, merged

2020-10-21 15:46 UTC, michal-narajowski commented on subsys/bluetooth/mesh/time_srv.c
> +	if (status.is_authority <= srv->data.sync.status.is_authority &&
`status` is uninitialized here.