openthread: Enable nrf_security support for precompiled OT libs
nrfconnect/sdk-nrf pull request #2974
Opened 2020-09-23 14:31 UTC by lmaciejonczyk

From this commit nrf_security can be used together with precompiled OpenThread libraries.

2020-09-23 14:34 UTC, edmont approved these changes

2020-09-23 14:47 UTC, pszkotak commented on doc/nrf/ug_thread_configuring.rst
> +    Notice that while building OpenThread from sources an additional user configuration can overwrite selected sets of features.
Can we be more strict here?
I propose something like that:
```suggestion
    While building OpenThread from sources the user configuration overwrites selected predefined Master, FTD or MTD feature set.
```

2020-09-23 14:48 UTC, pszkotak commented on doc/nrf/ug_thread_configuring.rst
> +    The libraries destination directory differ based on chosen option :option:`CONFIG_OPENTHREAD_NORDIC_LIBRARY` and cryptography backends: :option:`CONFIG_CC310_BACKEND` or :option:`CONFIG_OBERON_BA
Awesome!

2020-09-23 14:57 UTC, pszkotak approved these changes
LGTM, thanks

2020-09-24 15:08 UTC, lmaciejonczyk commented on doc/nrf/ug_thread_configuring.rst
> +    The default configuration for all :ref:`openthread_samples` is defined in :file:`nrf/samples/common/overlay-ot-defaults.conf`.
```suggestion
    The default configuration for all :ref:`openthread_samples` is defined in :file:`nrf/samples/openthread/common/overlay-ot-defaults.conf`.
```

2020-09-24 15:20 UTC, lmaciejonczyk commented on doc/nrf/ug_thread_configuring.rst
> +After the sample is built, run the following command in the sample directory to overwrite the existing nrfxlib libraries with the new ones:
Actually you don't need to run the command always in the sample directory. For instance you can just run:
`west build -b nrf52840dk_nrf52840 -p always nrf/samples/openthread/cli/` from root directory and there you can just run `west build -t install_openthread_libraries` without moving to sample directory.

2020-09-24 15:27 UTC, lmaciejonczyk commented on doc/nrf/ug_thread_configuring.rst
> +These predefined sets are based on :ref:`nrfxlib:ot_libs` available in nrfxlib.
I would rather say that :ref:`nrfxlib:ot_libs` provide functionalities listed in these predefined sets.

2020-09-24 15:31 UTC, lmaciejonczyk commented on doc/nrf/ug_thread_configuring.rst
> +You can use these sets for configuration purposes or for building libraries with complete Thread specification support when you :ref:`configure OpenThread to use pre-built libraries <ug_thread_config
```suggestion
You can use these sets for configuration purposes when you build your application using OpenThread sources or for building application with complete Thread specification support when you :ref:`configure OpenThread to use pre-built libraries <ug_thread_configuring_basic_building>` with the :option:`CONFIG_OPENTHREAD_LIBRARY_1_1` Kconfig option.
```

2020-09-25 11:48 UTC, greg-fer commented
I discussed documentation with @lmaciejonczyk  and we agreed we're going to come back to the topic after he makes some changes to the menuconfig structure.

2020-09-25 11:49 UTC, MarekPorwisz commented on doc/nrf/ug_thread_configuring.rst
> +    When you selected :option:`CONFIG_OPENTHREAD_USER_CUSTOM_LIBRARY`, the location depends the chosen nRF Security backend, either :option:`CONFIG_CC310_BACKEND` or :option:`CONFIG_OBERON_BACKEND`.
Something to consider: Maybe we should not mention backends here and mention it "depends on device hardware crypto capabilities" as it is more complex than just CC and OBERON i.e. on nRF53 we'll have CC312, and on 52833 currently we use mixed config oberon + vanilla due to lack of SHA224 support in oberon(to be added soon).

2020-09-25 11:51 UTC, MarekPorwisz approved these changes

2020-09-28 13:33 UTC, greg-fer approved these changes

2020-10-08 07:21 UTC, greg-fer approved these changes

2020-10-08 08:04 UTC, edmont commented on samples/openthread/cli/prj.conf
> -CONFIG_OPENTHREAD_NORDIC_LIBRARY=y
Same thing applies to the NCP sample.

2020-10-08 10:54 UTC, tejlmand approved these changes

2020-10-08 12:22 UTC, greg-fer requested changes

2020-10-08 12:22 UTC, greg-fer commented on doc/nrf/ug_thread_configuring.rst
> +
```suggestion

This command builds two versions of the libraries, with and without debug symbols, and installs only the version without debug symbols.
```

2020-10-09 08:16 UTC, tejlmand commented
please rebase

2020-10-09 09:22 UTC, greg-fer approved these changes

2020-10-09 11:51 UTC, rlubos commented
Doc build failed with quite a few complaints:
https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf_doc/job/master/6029/artifact/_build/nrfxlib/doc.log

2020-10-09 14:08 UTC, lmaciejonczyk commented
How can we disable CI check for `nrf_security_mbedtls_configuration.h` files which exist only for checking OT libs dependencies?

2020-10-09 14:10 UTC, rlubos commented
@utzig @ru-fu Can particular header files be excluded from documentation build? Some mbedTLS config files are generating warnings, thus causing CI failure:
https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf_doc/job/master/6050/artifact/_build/nrfxlib/doc.log

2020-10-09 14:20 UTC, lmaciejonczyk commented
I can change the file extension if it helps.

2020-10-09 14:58 UTC, ru-fu commented
> 
> 
> @utzig @ru-fu Can particular header files be excluded from documentation build? Some mbedTLS config files are generating warnings, thus causing CI failure:
> https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf_doc/job/master/6050/artifact/_build/nrfxlib/doc.log

Yes, you can exclude files or folders in the nrf/doc/nrfxlib/nrfxlib.doxyfile.in file (line 805).

2020-10-09 15:02 UTC, utzig commented
> > @utzig @ru-fu Can particular header files be excluded from documentation build? Some mbedTLS config files are generating warnings, thus causing CI failure:
> > https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf_doc/job/master/6050/artifact/_build/nrfxlib/doc.log
> 
> Yes, you can exclude files or folders in the nrf/doc/nrfxlib/nrfxlib.doxyfile.in file (line 805).

If this include file has a proper include guard you can also try pre-defining it for Doxygen here: https://github.com/nrfconnect/sdk-nrf/blob/master/doc/nrfxlib/nrfxlib.doxyfile.in#L1947

2020-10-12 19:00 UTC, MarekPorwisz approved these changes
Tested and seems to work

2020-10-12 20:22 UTC, frkv approved these changes

2020-10-12 20:22 UTC, frkv commented on doc/nrf/ug_thread_configuring.rst
> +    When you selected :option:`CONFIG_OPENTHREAD_USER_CUSTOM_LIBRARY`, the location depends the chosen :ref:`nrf_security backend <nrfxlib:nrf_security_readme>`, either :option:`CONFIG_CC310_BACKEND`
CONFIG_CC3XX_BACKEND

2020-10-12 21:06 UTC, merged