Bluetooth: Mesh: DK Prov: Clarify UUID usage
nrfconnect/sdk-nrf pull request #2992
Opened 2020-09-28 14:06 UTC by trond-snekvik

Expands the UUID text in the DK Prov module to specify exactly how the
UUID is used.

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

2020-09-28 14:43 UTC, joerchan approved these changes

2020-09-30 10:49 UTC, mia-ko requested changes
It looked ok already, I just simplified a bit (split into two sentences to ease the readability) :)

2020-09-30 10:49 UTC, mia-ko commented on include/bluetooth/mesh/dk_prov.rst
> +The UUID is used in the unprovisioned beacon as well as the broadcasted Mesh Provisioning Service data, and allows Provisioners to uniquely identify the device before starting provisioning.
```suggestion
The UUID is used in the unprovisioned beacon and the broadcasted Mesh Provisioning Service data.
It allows the Provisioners to uniquely identify the device before starting provisioning.
```

2020-10-06 08:37 UTC, mia-ko approved these changes

2020-10-06 08:44 UTC, merged