Bluetooth: Mesh: Light Control regulator improvements
nrfconnect/sdk-nrf pull request #3013
Opened 2020-10-01 12:52 UTC by trond-snekvik

Makes all illuminance regulator coefficients, as well as internal values
in the regulator processing floating point values.

Separates the Light Control Client's coefficient configuration from the
other properties to allow floating point coefficients in the client as
well.

Adds steady state detection to the illuminance regulator to reduce the
amount of value changes propagated to the application.

2020-10-06 08:35 UTC, mia-ko requested changes

2020-10-06 08:35 UTC, mia-ko commented on include/bluetooth/mesh/light_ctrl_srv.rst
> +The error, regulator coefficients and internal sum are represented as 32 bit floating point values.
```suggestion
The error, the regulator coefficients, and the internal sum, are represented as 32-bit floating point values.
```

2020-10-06 10:09 UTC, mia-ko approved these changes

2020-10-08 14:38 UTC, joerchan approved these changes

2020-10-08 14:39 UTC, merged