net: lib: aws_fota: Report failure if fota_download does not start
nrfconnect/sdk-nrf pull request #3060
Opened 2020-10-07 11:40 UTC by sigvartmh

This adds the functionality if `fota_download_start` fails it will
update the job with failure instead of returning a failure to the
MQTT handler.

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

2020-10-07 11:41 UTC, sigvartmh commented
@coderbyheart Could you confirm that this fixes https://github.com/bifravst/firmware/issues/78

2020-10-07 12:03 UTC, coderbyheart commented
From the changes I don't see how this addresses the bug where [the download client is configure to use the TLS credentials of the MQTT connection](https://github.com/bifravst/firmware/issues/78#issuecomment-698936516), but I'll give it a shot.

2020-10-07 12:16 UTC, sigvartmh commented
Oh, maybe I addressed another issue than what was asked for. Let me iterate on the TLS config.

2020-10-07 12:27 UTC, sigvartmh commented
> From the changes I don't see how this addresses the bug where [the download client is configure to use the TLS credentials of the MQTT connection](https://github.com/bifravst/firmware/issues/78#issuecomment-698936516), but I'll give it a shot.

To fix that you just have to set `CONFIG_AWS_FOTA_DOWNLOAD_SECURITY_TAG=-1` in the `prj.conf` of the application.

2020-10-07 13:59 UTC, coderbyheart requested changes
This change actually makes the situation worse, the device now crashes:

```
[00:16:02.575,714] <dbg> cat_tracker.modem_rsrp_handler: Incoming RSRP status message, RSRP value is 39
[00:16:02.585,968] <dbg> cat_tracker.lte_evt_handler: RRC mode: Connected
[00:16:02.788,116] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/notify-next
[00:16:02.798,767] <inf> aws_fota: Checking for an available job
[00:16:02.805,603] <dbg> aws_fota.get_job_execution: Job doc: {"timestamp":1602079079,"execution":{"jobId":"524b93f7-d582-446a-b968-07994842b528","status":"QUEUED","queuedAt":1602079079,"lastUpdatedAt":1602079079,"versionNumber":1,"executionNumber":1,"jobDocument":{"operation":"app_fw_update","size":259784,"filename":"app_update.bin","location":{"protocol":"https","host":"bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com","path":"524b93f7-d582-446a-b968-07994842b528"},"fwversion":"0.0.0-development-thingy91_nrf9160ns-ltem-debug","targetBoard":"thingy91_nrf9160"}}}
[00:16:02.858,489] <dbg> aws_fota.get_job_execution: Job ID: 524b93f7-d582-446a-b968-07994842b528
[00:16:02.867,950] <dbg> aws_fota.get_job_execution: hostname: bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com
[00:16:02.879,791] <dbg> aws_fota.get_job_execution: file_path 524b93f7-d582-446a-b968-07994842b528
[00:16:02.889,434] <dbg> aws_fota.get_job_execution: execution_version_number: 1 
[00:16:02.897,583] <inf> aws_jobs: Subscribe: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/#
[00:16:02.910,583] <inf> aws_fota: Subscribed to FOTA update topic $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/#
[00:16:03.125,946] <dbg> aws_fota.update_job_execution: update_job_execution, state: 1, version_number: 1
[00:16:03.136,322] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update
[00:16:03.148,345] <inf> aws_jobs: Publish payload {"status":"IN_PROGRESS","statusDetails": null,"expectedVersion": "1","clientToken": ""}
[00:16:03.477,081] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/accepted
[00:16:03.491,455] <inf> aws_fota: Start downloading firmware from bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com/524b93f7-d582-446a-b968-07994842b528
[00:16:03.680,664] <inf> download_client: Setting up TLS credentials, tag 42
[00:16:03.688,293] <inf> download_client: Connecting to bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com
[00:16:04.450,714] <err> download_client: Unable to connect, errno 95
[00:16:04.459,899] <err> aws_fota: Error (-95) when trying to start firmware download
[00:16:04.468,597] <dbg> aws_fota.update_job_execution: update_job_execution, state: 3, version_number: 2
[00:16:04.478,942] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update
[00:16:04.490,936] <inf> aws_jobs: Publish payload {"status":"FAILED","statusDetails": null,"expectedVersion": "2","clientToken": ""}
[00:16:04.503,875] <err> os: ***** HARD FAULT *****
[00:16:04.509,552] <err> os:   Fault escalation (see below)
[00:16:04.515,960] <err> os: ***** USAGE FAULT *****
[00:16:04.521,697] <err> os:   Stack overflow (context area not valid)
[00:16:04.529,052] <err> os: r0/a1:  0x40028011  r1/a2:  0x3f7e417b  r2/a3:  0xe0cb8244
[00:16:04.537,963] <err> os: r3/a4:  0xafcb2736 r12/ip:  0xffffffff r14/lr:  0x00000000
[00:16:04.546,844] <err> os:  xpsr:  0x00039c00
[00:16:04.552,185] <err> os: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
[00:16:04.562,774] <err> os: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
[00:16:04.573,394] <err> os: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
[00:16:04.584,045] <err> os: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
[00:16:04.594,665] <err> os: fpscr:  0x2002ec48
[00:16:04.600,006] <err> os: Faulting instruction address (r15/pc): 0x2002ec38
[00:16:04.608,062] <err> os: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
[00:16:04.616,119] <err> os: Current thread: 0x20024360 (unknown)
[00:16:04.623,046] <err> cat_tracker: k_sys_fatal_error_handler, error: 2
[00:16:04.630,676] <err> cat_tracker: err_handler, error code: 2
*** Booting Zephyr OS build v2.3.0-rc1-ncs1-3614-ga4ead9805140  ***
```

2020-10-07 14:07 UTC, coderbyheart requested changes
To not have **future** applications run into the same issue, the default value of `AWS_FOTA_DOWNLOAD_SECURITY_TAG` should be made `-1`.

https://github.com/nrfconnect/sdk-nrf/blob/6482d3b75d136ed0193b609d19b311c78dbbdd7b/subsys/net/lib/aws_fota/Kconfig#L28

2020-10-07 14:15 UTC, coderbyheart commented
With `AWS_FOTA_DOWNLOAD_SECURITY_TAG=-1` the download starts, but still a hard fault happens (repeated until I delete the FOTA job):

```

[00:00:14.047,424] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/92151aaf-6fd1-4619-b5ac-3d390b404b6e/update/accepted
[00:00:14.061,767] <inf> aws_fota: Start downloading firmware from bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com/92151aaf-6fd1-4619-b5ac-3d390b404b6e
[00:00:15.153,503] <inf> download_client: Connecting to bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com
[00:00:15.267,639] <inf> download_client: Configuring socket timeout (4 s)
[00:00:15.275,634] <inf> download_client: Downloading: 92151aaf-6fd1-4619-b5ac-3d390b404b6e [0]
[00:00:15.284,942] <inf> cat_tracker: CLOUD_EVT_FOTA_START
[00:00:16.046,356] <inf> download_client: Downloaded 2048/259784 bytes (0%)
[00:00:16.054,504] <inf> STREAM_FLASH: Erasing page at offset 0x00085000
[00:00:16.173,706] <inf> download_client: Downloaded 4096/259784 bytes (1%)
[00:00:16.205,230] <inf> download_client: Downloaded 6144/259784 bytes (2%)
[00:00:16.212,860] <inf> STREAM_FLASH: Erasing page at offset 0x00086000
[00:00:16.332,000] <inf> download_client: Downloaded 8192/259784 bytes (3%)

[...]

[00:00:31.977,478] <inf> download_client: Downloaded 256000/259784 bytes (98%)
[00:00:31.985,382] <inf> STREAM_FLASH: Erasing page at offset 0x000c3000
[00:00:32.104,492] <inf> download_client: Downloaded 258048/259784 bytes (99%)
[00:00:32.189,758] <inf> download_client: Downloaded 259784/259784 bytes (100%)
[00:00:32.197,723] <inf> STREAM_FLASH: Erasing page at offset 0x000c4000
[00:00:32.309,661] <inf> download_client: Download complete
[00:00:32.318,023] <inf> STREAM_FLASH: Erasing page at offset 0x000fd000
[00:00:32.412,933] <inf> dfu_target_mcuboot: MCUBoot image upgrade scheduled. Reset the device to apply
[00:00:32.423,431] <inf> aws_fota: FOTA download completed evt received
[00:00:32.430,603] <err> cat_tracker: Unknown cloud event type: 13
[00:00:32.437,591] <dbg> aws_fota.update_job_execution: update_job_execution, state: 1, version_number: 4
[00:00:32.447,906] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/92151aaf-6fd1-4619-b5ac-3d390b404b6e/update
[00:00:32.459,930] <inf> aws_jobs: Publish payload {"status":"IN_PROGRESS","statusDetails": null,"expectedVersion": "4","clientToken": ""}
[00:00:32.668,090] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/92151aaf-6fd1-4619-b5ac-3d390b404b6e/update/accepted
[00:00:32.682,434] <inf> aws_fota: Firmware download completed
[00:00:32.688,812] <dbg> aws_fota.update_job_execution: update_job_execution, state: 2, version_number: 5
[00:00:32.699,218] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/92151aaf-6fd1-4619-b5ac-3d390b404b6e/update
[00:00:32.711,212] <inf> aws_jobs: Publish payload {"status":"SUCCEEDED","statusDetails": null,"expectedVersion": "5","clientToken": ""}
[00:00:32.724,365] <err> os: ***** HARD FAULT *****
[00:00:32.730,072] <err> os:   Fault escalation (see below)
[00:00:32.736,419] <err> os: ***** USAGE FAULT *****
[00:00:32.742,156] <err> os:   Stack overflow (context area not valid)
[00:00:32.749,511] <err> os: r0/a1:  0x40028011  r1/a2:  0x3f7e417b  r2/a3:  0xe0cb8244
[00:00:32.758,392] <err> os: r3/a4:  0xafcb2736 r12/ip:  0xffffffff r14/lr:  0x00000000
[00:00:32.767,242] <err> os:  xpsr:  0x00039c00
[00:00:32.772,583] <err> os: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
[00:00:32.783,142] <err> os: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
[00:00:32.793,731] <err> os: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
[00:00:32.804,351] <err> os: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
[00:00:32.814,971] <err> os: fpscr:  0x2002ec48
[00:00:32.820,281] <err> os: Faulting instruction address (r15/pc): 0x2002ec38
[00:00:32.828,308] <err> os: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
[00:00:32.836,364] <err> os: Current thread: 0x20024360 (unknown)
[00:00:32.843,292] <err> cat_tracker: k_sys_fatal_error_handler, error: 2
[00:00:32.850,891] <err> cat_tracker: err_handler, error code: 2
```

2020-10-07 14:15 UTC, sigvartmh commented
> This change actually makes the situation worse, the device now crashes:
> 
> ```
> [00:16:02.575,714] <dbg> cat_tracker.modem_rsrp_handler: Incoming RSRP status message, RSRP value is 39
> [00:16:02.585,968] <dbg> cat_tracker.lte_evt_handler: RRC mode: Connected
> [00:16:02.788,116] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/notify-next
> [00:16:02.798,767] <inf> aws_fota: Checking for an available job
> [00:16:02.805,603] <dbg> aws_fota.get_job_execution: Job doc: {"timestamp":1602079079,"execution":{"jobId":"524b93f7-d582-446a-b968-07994842b528","status":"QUEUED","queuedAt":1602079079,"lastUpdatedAt":1602079079,"versionNumber":1,"executionNumber":1,"jobDocument":{"operation":"app_fw_update","size":259784,"filename":"app_update.bin","location":{"protocol":"https","host":"bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com","path":"524b93f7-d582-446a-b968-07994842b528"},"fwversion":"0.0.0-development-thingy91_nrf9160ns-ltem-debug","targetBoard":"thingy91_nrf9160"}}}
> [00:16:02.858,489] <dbg> aws_fota.get_job_execution: Job ID: 524b93f7-d582-446a-b968-07994842b528
> [00:16:02.867,950] <dbg> aws_fota.get_job_execution: hostname: bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com
> [00:16:02.879,791] <dbg> aws_fota.get_job_execution: file_path 524b93f7-d582-446a-b968-07994842b528
> [00:16:02.889,434] <dbg> aws_fota.get_job_execution: execution_version_number: 1 
> [00:16:02.897,583] <inf> aws_jobs: Subscribe: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/#
> [00:16:02.910,583] <inf> aws_fota: Subscribed to FOTA update topic $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/#
> [00:16:03.125,946] <dbg> aws_fota.update_job_execution: update_job_execution, state: 1, version_number: 1
> [00:16:03.136,322] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update
> [00:16:03.148,345] <inf> aws_jobs: Publish payload {"status":"IN_PROGRESS","statusDetails": null,"expectedVersion": "1","clientToken": ""}
> [00:16:03.477,081] <dbg> aws_fota.on_publish_evt: Received topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update/accepted
> [00:16:03.491,455] <inf> aws_fota: Start downloading firmware from bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com/524b93f7-d582-446a-b968-07994842b528
> [00:16:03.680,664] <inf> download_client: Setting up TLS credentials, tag 42
> [00:16:03.688,293] <inf> download_client: Connecting to bifravst-storagebucket1817f433-1jcq77cgkzd5h.s3.amazonaws.com
> [00:16:04.450,714] <err> download_client: Unable to connect, errno 95
> [00:16:04.459,899] <err> aws_fota: Error (-95) when trying to start firmware download
> [00:16:04.468,597] <dbg> aws_fota.update_job_execution: update_job_execution, state: 3, version_number: 2
> [00:16:04.478,942] <inf> aws_jobs: Publish topic: $aws/things/352656100248049/jobs/524b93f7-d582-446a-b968-07994842b528/update
> [00:16:04.490,936] <inf> aws_jobs: Publish payload {"status":"FAILED","statusDetails": null,"expectedVersion": "2","clientToken": ""}
> [00:16:04.503,875] <err> os: ***** HARD FAULT *****
> [00:16:04.509,552] <err> os:   Fault escalation (see below)
> [00:16:04.515,960] <err> os: ***** USAGE FAULT *****
> [00:16:04.521,697] <err> os:   Stack overflow (context area not valid)
> [00:16:04.529,052] <err> os: r0/a1:  0x40028011  r1/a2:  0x3f7e417b  r2/a3:  0xe0cb8244
> [00:16:04.537,963] <err> os: r3/a4:  0xafcb2736 r12/ip:  0xffffffff r14/lr:  0x00000000
> [00:16:04.546,844] <err> os:  xpsr:  0x00039c00
> [00:16:04.552,185] <err> os: s[ 0]:  0x00000000  s[ 1]:  0x00000000  s[ 2]:  0x00000000  s[ 3]:  0x00000000
> [00:16:04.562,774] <err> os: s[ 4]:  0x00000000  s[ 5]:  0x00000000  s[ 6]:  0x00000000  s[ 7]:  0x00000000
> [00:16:04.573,394] <err> os: s[ 8]:  0x00000000  s[ 9]:  0x00000000  s[10]:  0x00000000  s[11]:  0x00000000
> [00:16:04.584,045] <err> os: s[12]:  0x00000000  s[13]:  0x00000000  s[14]:  0x00000000  s[15]:  0x00000000
> [00:16:04.594,665] <err> os: fpscr:  0x2002ec48
> [00:16:04.600,006] <err> os: Faulting instruction address (r15/pc): 0x2002ec38
> [00:16:04.608,062] <err> os: >>> ZEPHYR FATAL ERROR 2: Stack overflow on CPU 0
> [00:16:04.616,119] <err> os: Current thread: 0x20024360 (unknown)
> [00:16:04.623,046] <err> cat_tracker: k_sys_fatal_error_handler, error: 2
> [00:16:04.630,676] <err> cat_tracker: err_handler, error code: 2
> *** Booting Zephyr OS build v2.3.0-rc1-ncs1-3614-ga4ead9805140  ***
> ```

Well that didn't look nice, I'll see if I can reproduce it to understand why the stack exploded.

2020-10-15 22:12 UTC, sigvartmh commented
Did you try with increased stack size such as in the PR in question?

2020-10-19 08:24 UTC, sigvartmh commented
@simensrostad If you could confirm that this works together with the changes in bifvrast/firmware#78 I would like to get this merged.

2020-10-19 08:51 UTC, simensrostad commented
> @simensrostad If you could confirm that this works together with the changes in bifvrast/firmware#78 I would like to get this merged.

2020-10-19 08:53 UTC, simensrostad commented
> > @simensrostad If you could confirm that this works together with the changes in bifvrast/firmware#78 I would like to get this merged.

On it.

2020-10-19 09:21 UTC, simensrostad commented
> > @simensrostad If you could confirm that this works together with the changes in bifvrast/firmware#78 I would like to get this merged.

I have done some testing. It looks to be working fine. I also provoked a FOTA failure by setting ```CONFIG_AWS_FOTA_DOWNLOAD_SECURITY_TAG``` to 42 again and now a AWS FOTA failure status message is successfully sent to cloud.

2020-10-19 09:21 UTC, simensrostad approved these changes

2020-10-20 08:01 UTC, shantha-14 approved these changes

2020-10-20 08:06 UTC, coderbyheart approved these changes
Approved if merged alongside #3142

2020-10-20 08:08 UTC, merged