boards: arm: thingy91_nrf9160: Clean up RAM definitions
nrfconnect/sdk-nrf pull request #3103
Opened 2020-10-12 19:11 UTC by jtguggedal

This patch aligns the RAM definitions for secure, non-secure and
BSD library's RAM for Thingy:91 with nRF9160 DK.
This change fixes failing assertion check in SPM
after c9c1ac4a introduced RAM partitioning for nRF9160.

Signed-off-by: Jan Tore Guggedal <jantore.guggedal@nordicsemi.no>

2020-10-12 19:14 UTC, jtguggedal commented
`git bisect` led me to https://github.com/nrfconnect/sdk-nrf/commit/c9c1ac4a04298e1839e10bad4ca62e0528fbcede after builds for Thingy:91 started to produce this failed assert at the end of SPM:
```
SPM: prepare to jump to Non-Secure image.
ASSERTION FAIL [0] @ WEST_TOPDIR/zephyr/arch/arm/core/aarch32/cortex_m/mpu/arm_mpu.c:275
        Marking 1 areas for dynamic regions failed
```

I don't fully understand the changes in https://github.com/nrfconnect/sdk-nrf/commit/c9c1ac4a04298e1839e10bad4ca62e0528fbcede and exactly why these partition definition changes are required, so the commit message might very well be a bit off.

By the way, should the SPM still make the jump to non-secure when an assertion check fails?

2020-10-12 19:17 UTC, hakonfam commented
The changes are needed so that application configuration can affect the RAM partitioning. For instance if you set a configuration to use a variant of BSDlib which requires less RAM you can give the application more RAM without having to manually modify/include dts/overlay files.

From the top of my head I don't understand why changes to RAM configuration in devicetree can affect the issue, since the RAM partitioning is supposed to be done by PM now, but I have to look into it.

I agree that SPM shouldn't jump when it is not able to configure the SPU as specified.

2020-10-12 19:23 UTC, jtguggedal commented
> The changes are needed so that application configuration can affect the RAM partitioning. For instance if you set a configuration to use a variant of BSDlib which requires less RAM you can give the application more RAM without having to manually modify/include dts/overlay files.

Thanks for the explanation, that's a nice feature.

> From the top of my head I don't understand why changes to RAM configuration in devicetree can affect the issue, since the RAM partitioning is supposed to be done by PM now, but I have to look into it.

I don't understand why it's needed either, but was wondering that the missing `sram_s` node in dts could be to blame for this.

2020-10-12 19:37 UTC, hakonfam commented
Are you certain its from SPM? I don't think SPM has assertions enabled by default, and I assume this code is also included by the application.

2020-10-12 20:05 UTC, hakonfam requested changes
The problem is how partition manager gets the information about the SoCs RAM start and size.
Since this is only encoded in DTS (as opposed to a SoC Kconfig file) we need to use devicetree scripts inside kconfig to get the values.

```
# Helper configs needed since 'SRAM_SIZE/BASE' use the chosen node.
config PM_SRAM_BASE
	hex
	default $(dt_node_reg_addr_hex,/soc/memory@21000000) if SOC_NRF5340_CPUNET
	default $(dt_node_reg_addr_hex,/soc/memory@20000000)

config PM_SRAM_SIZE
	hex
	default $(dt_node_reg_size_hex,/soc/memory@21000000) if SOC_NRF5340_CPUNET
	default $(dt_node_reg_size_hex,/soc/memory@20000000)

```

As you can see we look up the node at address 0x2000000 (or 0x21000000 for nrf53 network core) as this in upstream zephyr is always the "whole" RAM.

Prior to your patch this node only defines 64kB for the board in question.

```
#define DT_N_S_soc_S_memory_20000000_REG_IDX_0_VAL_SIZE 65536 /* 0x10000 */
```

When I try to build hello world with the thingy board I get an error from the partition manager script, its strange that you don't see this.

So the commit message could be cleared up a bit, and I would check how the RAM is set up in devicetree in upstream to follow that convention.

"Align RAM definition with upstream to ensure node at 0x20000000 declares all of RAM. This fixes a bug where the partition manager would only use parts of the available RAM", or something like that.

2020-10-13 07:30 UTC, jtguggedal commented
> Are you certain its from SPM? I don't think SPM has assertions enabled by default, and I assume this code is also included by the application.

It looks like it comes from `arm_core_mpu_mark_areas_for_dynamic_regions()`, which is called from within `switch_to_main_thread()`, so that's probably after SPM has made the jump to non-secure and in the non-secure startup code? I still don't quite get why the execution continues after the assert, though.

> So the commit message could be cleared up a bit, and I would check how the RAM is set up in devicetree in upstream to follow that convention.
>
>"Align RAM definition with upstream to ensure node at 0x20000000 declares all of RAM. This fixes a bug where the partition manager would only use parts of the available RAM", or something like that.

Commit message has been updated per your suggestion.

> When I try to build hello world with the thingy board I get an error from the partition manager script, its strange that you don't see this.

I did some testing on the status before this patch:

- Of the samples I've tested, it's only with the asset tracker on Thingy:91 I've seen the assert. The application has a `pm_static.yml`, but I don't know if that's what makes the difference.
- Samples with BSD library and no `pm_static.yml` file in NCS compile and run seemingly without issues.
- Partition Manager error is seen when compiling samples for `thingy91_nrf9160ns` that don't use BSD library.

2020-10-13 07:34 UTC, hakonfam approved these changes

2020-10-13 09:01 UTC, merged