Port zigbee cli zcl ping command [KRKNWK-7706]
nrfconnect/sdk-nrf pull request #3113
Opened 2020-10-14 07:46 UTC by sebastiandraus

2020-11-06 16:23 UTC, tomchy commented on subsys/zigbee/cli/zigbee_cli_cmd_ping.c
> +	zb_osif_disable_all_inter();
Unfortunately the thread- (not interrupt-) safe buffer API is enabled by the `ZB_INTERRUPT_SAFE_BUFS` configuration macro and it is not defined nor configurable in our `zb_vendor.h` file. I think we should add with the next ZBOSS update.

BTW: this name is a bit misleading in NCS case. The `zb_osif_disable_all_inter` API is not disabling all interrupts, but trying to get the ZBOSS mutex, so effectively in this case this implementation is identical to the effect of the `ZB_INTERRUPT_SAFE_BUFS` config.

2020-11-16 13:27 UTC, jakub-uC approved these changes
LGTM from shell perspective

2020-11-16 19:04 UTC, wbober commented
Docs missing.

2020-11-17 15:37 UTC, rlubos commented on subsys/zigbee/CMakeLists.txt
>  	cli/zigbee_cli.c
`...` in commit 787fefda87d1446cf1774a80224cad588e14e217 is not a valid description. I suggest squashing the first two commits before merge anyway, there's no need to introduce non-building SDK code into the tree.

2020-11-17 15:37 UTC, rlubos commented on subsys/zigbee/cli/zigbee_cli_utils.c
> +extern zb_uint8_t cli_agent_ep_handler_ping(zb_bufid_t bufid);
It's a function declaration, `extern` is implicit here.

2020-11-17 15:37 UTC, rlubos commented on subsys/zigbee/cli/zigbee_cli_ping_types.h
> +// #define PING_TABLE_SIZE               10
Just remove it if it's not needed.

2020-11-17 15:37 UTC, rlubos commented on subsys/zigbee/cli/zigbee_cli_ping_types.h
> +typedef void (*ping_time_cb)(enum ping_time_evt evt, zb_uint32_t delay_ms,
`ping_time_cb_t`

2020-11-19 08:03 UTC, greg-fer requested changes
Please update documentation, I guess lib_zigbee_shell.rst.

2020-12-15 08:46 UTC, rlubos commented
Please also add a changelog entry for this change (it's now required to update https://github.com/nrfconnect/sdk-nrf/blob/master/doc/nrf/releases/release-notes-latest.rst within a PR).

2020-12-16 10:29 UTC, greg-fer approved these changes

2020-12-16 11:03 UTC, wbober approved these changes

2020-12-16 15:48 UTC, rlubos approved these changes

2020-12-16 15:55 UTC, merged