manifest: OpenThread NCP library and plat log fixes
nrfconnect/sdk-nrf pull request #3118
Opened 2020-10-14 11:46 UTC by pszkotak

This PR adds two fixes:
- provides two libraries needed by NCP to the  nrfxlib
- ensures that otPlatLog is provided with CONFIG_OPENTHREAD_DEBUG

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

2020-10-14 13:05 UTC, tejlmand commented
@pszkotak please provide a link to dependent nrfxlib PR.

2020-10-14 13:54 UTC, pszkotak commented
> @pszkotak please provide a link to dependent nrfxlib PR.

https://github.com/nrfconnect/sdk-nrfxlib/pull/299
Also updated the first post.

2020-10-17 17:24 UTC, MarekPorwisz requested changes
I think the zephyr part is no longer valid.Please restore it to the original value

As I understand the nrfxlib part is still valid since pr 306 does not build for me when I tested it. Please update PR 306 wit the libs added in PR 299

2020-10-19 08:16 UTC, pszkotak commented
This should not be merged as all changes presented here get in with the: https://github.com/nrfconnect/sdk-nrf/pull/3139

2020-10-21 08:39 UTC, pszkotak commented
#3139 is merged, closing this one.

2020-10-21 08:39 UTC, closed without merging