applications: nrf_desktop: Document settings incompatibility
nrfconnect/sdk-nrf pull request #3131
Opened 2020-10-15 09:34 UTC by MarekPieta

Change describes possible issue related to settings incompatibility after the firmware upgrade.

Jira:DESK-1103

2020-10-15 09:43 UTC, pdunaj approved these changes

2020-10-16 09:57 UTC, greg-fer requested changes

2020-10-16 09:57 UTC, greg-fer commented on applications/nrf_desktop/README.rst
> +   In case of incompatibilities, the settings area must be erased before using the new firmware.
```suggestion
.. important::
   Before updating the firmware, make sure that the data stored in the settings partition is compatible with the new firmware.
   If it is incompatible, erase the settings area before using the new firmware.
```

2020-10-16 10:58 UTC, greg-fer approved these changes

2020-10-20 08:04 UTC, shantha-14 approved these changes

2020-10-20 08:07 UTC, merged