doc: bootloader: Change it from DTS to partition manager
nrfconnect/sdk-nrf pull request #3146
Opened 2020-10-15 21:58 UTC by sigvartmh

The doc stated that you should look at the DTS. This is wrong when using
NCS the partition manager is the one who will setup the partitions.

NCSDK-6752

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

2020-10-16 07:01 UTC, hakonfam approved these changes

2020-10-16 07:34 UTC, greg-fer requested changes

2020-10-16 07:34 UTC, greg-fer commented on doc/nrf/ug_bootloader.rst
> +For detailed information about the memory layout, see the partition configuration in the ``<build folder>/partitions.yml`` file or run ``ninja partition_manager_report``.
```suggestion
For detailed information about the memory layout, see the partition configuration in the :file:`<build folder>/partitions.yml` file or run ``ninja partition_manager_report``.
```

2020-10-16 08:59 UTC, greg-fer approved these changes
Approving, as @mia-ko is out-of-office.

2020-10-19 08:18 UTC, mia-ko approved these changes

2020-10-20 09:10 UTC, shantha-14 approved these changes

2020-10-20 09:19 UTC, merged