Bluetooth: peripheral_lbs: Add minimal configuration
nrfconnect/sdk-nrf pull request #3157
Opened 2020-10-16 14:21 UTC by joerchan

Add a minimal configuration to the peripheral_lbs sample to demonstrate
how to tune stack sizes and reducing bluetooth features and buffers.

Example difference:
```
west build -b nrf52dk_nrf52810 samples/bluetooth/peripheral_lbs --\
   -DCONFIG_BT_LBS_SECURITY_ENABLED=n
Memory region         Used Size  Region Size  %age Used
           FLASH:      134584 B       192 KB     68.45%
            SRAM:       21009 B        24 KB     85.49%
        IDT_LIST:         136 B         2 KB      6.64%
```

```
west build -b nrf52dk_nrf52810 samples/bluetooth/peripheral_lbs -- \
   -DOVERLAY_CONFIG='minimal.conf' \
   -DCONFIG_BT_LBS_SECURITY_ENABLED=n
Memory region         Used Size  Region Size  %age Used
           FLASH:       97004 B       192 KB     49.34%
            SRAM:       14448 B        24 KB     58.79%
        IDT_LIST:         136 B         2 KB      6.64%
````

2020-10-16 14:54 UTC, carlescufi approved these changes

2020-10-16 15:00 UTC, b-gent requested changes

2020-10-16 15:00 UTC, b-gent commented on samples/bluetooth/peripheral_lbs/README.rst
> +The sample can be built with a minimum configuration as a demonstration in ways
Please put the sentence in one line (and maybe slightly reword)

```suggestion
The sample can be built with a minimum configuration as a demonstration of how to reduce code size and RAM usage.
```

2020-10-16 15:00 UTC, b-gent commented on samples/bluetooth/peripheral_lbs/README.rst
> +of reducing the code size and RAM usage of the application
```suggestion

```

2020-10-19 07:53 UTC, rugeGerritsen approved these changes

2020-10-19 08:30 UTC, grochu commented
I will do some testing now on this and will post the review afterwards.

2020-10-19 11:18 UTC, shantha-14 approved these changes

2020-10-20 08:45 UTC, b-gent approved these changes

2020-10-20 09:22 UTC, merged