doc: Add NCP from library case to the known issues
nrfconnect/sdk-nrf pull request #3164
Opened 2020-10-19 07:27 UTC by pszkotak

Adding info of the failed linking due to missing otPlatLog
when libs have not been built using the NCP sample.

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

2020-10-19 08:09 UTC, greg-fer requested changes

2020-10-19 08:09 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +KRKNWK-7803: automatically generated libraries are missing otPlatLog for NCP
```suggestion
KRKNWK-7803: Automatically generated libraries are missing otPlatLog for NCP
```

2020-10-19 08:09 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  When building OpenThread libraries using different sample than the NCP, the ncp_base.cpp is not compiled with the otPlatLog funciton.
```suggestion
  When building OpenThread libraries using a different sample than the :ref:`Thread NCP sample <ot_ncp_sample>`, the :file:`ncp_base.cpp` is not compiled with the :c:func:`otPlatLog` function.
```

2020-10-19 08:09 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  It results in linking failure when building the NCP with use of these libraries.
```suggestion
  This results in a linking failure when building the NCP with these libraries.
```

2020-10-19 08:09 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  **Workaround:** Use NCP sample to create OpenThread libraries.
```suggestion
  **Workaround:** Use the :ref:`Thread NCP sample <ot_ncp_sample>` to create OpenThread libraries.
```

2020-10-19 08:37 UTC, pszkotak commented
Thanks @greg-fer .
All fixed.

2020-10-19 11:30 UTC, greg-fer approved these changes

2020-10-20 09:45 UTC, carlescufi approved these changes

2020-10-20 09:45 UTC, merged