sample: aws_fota: Fix AWS FOTA response buffer too small
nrfconnect/sdk-nrf pull request #3168
Opened 2020-10-19 09:38 UTC by sigvartmh

When trying to connect to nRF Cloud with AWS FOTA sample the AT command
trying to get the IMEI number fails due to the readout buffer being too
small. This increases the size of the readout buffer.

NCSDK-6750

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

2020-10-20 20:14 UTC, jtguggedal requested changes
I think this change will make white spaces `\r\n` part of the client ID, which won't fly.
At some point this commit that fixed the issue with trailing whitespaces in the buffer has been effectively reverted: https://github.com/nrfconnect/sdk-nrf/commit/a6f72a0b78d6b7acc3f5b21417986a352b4ef75a

2020-10-20 21:34 UTC, sigvartmh commented
It got reverted by
https://github.com/nrfconnect/sdk-nrf/commit/bb259bfad1fa3572563444edb512fc8a6f12a3f4

tir. 20. okt. 2020 kl. 22:15 skrev Jan Tore Guggedal <
notifications@github.com>:

> *@jtguggedal* requested changes on this pull request.
>
> I think this change will make white spaces \r\n part of the client ID,
> which won't fly.
> At some point this commit that fixed the issue with trailing whitespaces
> in the buffer has been effectively reverted: a6f72a0
> <https://github.com/nrfconnect/sdk-nrf/commit/a6f72a0b78d6b7acc3f5b21417986a352b4ef75a>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nrfconnect/sdk-nrf/pull/3168#pullrequestreview-513096163>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA32LAT4QNI3WVSDAVX2IX3SLXVUJANCNFSM4SV4S22A>
> .
>

2020-10-21 08:12 UTC, hakonfam commented
@andvib please verify the fix.

2020-10-21 08:15 UTC, jtguggedal approved these changes
Looks good, thanks

2020-10-21 08:18 UTC, rlubos approved these changes

2020-10-21 08:28 UTC, sigvartmh reviewed
LGTM

2020-10-21 08:30 UTC, andvib approved these changes
Tested, application able to connect to nRF Cloud, bug fixed

2020-10-21 10:07 UTC, lemrey approved these changes

2020-10-21 18:55 UTC, shantha-14 approved these changes

2020-10-21 19:08 UTC, merged