fprotect: Use MDK function nrf53_errata_19()
nrfconnect/sdk-nrf pull request #3173
Opened 2020-10-19 13:14 UTC by oyvindronningstad

Instead of Zephyr variant which causes problems on nRF53 PDK 0.8.0

Ref: NCSDK-6769

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

2020-10-19 14:35 UTC, sigvartmh approved these changes
Looks fine to me haven't tested it on a board but from the code it will work.

2020-10-21 12:02 UTC, simon-iversen commented
This workaround did not solve the problem. Shouldn't [this](https://github.com/nrfconnect/sdk-nrf/blob/v1.4.0-rc1/subsys/spm/spm_internal.h#L33-L59) (used [here](https://github.com/nrfconnect/sdk-nrf/blob/v1.4.0-rc1/subsys/spm/spm.c#L39) and [here](https://github.com/nrfconnect/sdk-nrf/blob/v1.4.0-rc1/subsys/spm/spm.c#L179)) get modified instead? When I forced spu_flash_region_size() and num_spu_flash_regions() to return respectively 32*1024 and 32, the non-secure hello world sample ran fine on the nRF53 PDK v0.8.0.

2020-10-21 12:12 UTC, simon-iversen requested changes
See my earlier comment

2020-10-21 13:14 UTC, simon-iversen approved these changes
This commit seems to fix the problem. I was able to build a nonsecure hello world sample with the nRF53 PDK v0.8.0 after applying these changes

2020-10-21 14:00 UTC, oyvindronningstad commented
> 
> 
> This commit seems to fix the problem. I was able to build a nonsecure hello world sample with the nRF53 PDK v0.8.0 after applying these changes

Thanks for all the help!

2020-10-26 10:42 UTC, hakonfam approved these changes

2020-11-06 19:00 UTC, oyvindronningstad commented
@ioannisg merge?

2020-11-11 09:59 UTC, oyvindronningstad commented
@tejlmand merge?

2020-11-13 10:57 UTC, ioannisg approved these changes

2020-11-13 10:57 UTC, merged