kconfig: Default MAIN_STACK_SIZE=1024 for ZTEST in nrf
nrfconnect/sdk-nrf pull request #3183
Opened 2020-10-20 11:31 UTC by tejlmand

This adjust the upstream MAIN_STACK_SIZE default of 512 when using ZTEST
to 1024.
This allows to run entropy and crypto tests without stack overflows.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

2020-10-21 08:11 UTC, frkv approved these changes
LGTM. Change is appreciated!

2020-10-21 10:43 UTC, PerMac commented
It seems there are other configs that require "upgrading" than the main stack size as well. E.g `zephyr/tests/net/ipv6` requires increasing CONFIG_ZTEST_STACKSIZE (2048 seems enough). I will check other failing tests for stack limitations

2020-10-21 10:59 UTC, PerMac commented
The on-target plan checked out on this (1024 version) has ~300 fewer failures than without the PR. Some (probably most) are still caused by other stack size limitations. I will run the plan with the current version (force pushed to 2048 main stack size) to see if it solves something new and doesn't break anything. @tejlmand If the 2048 version is decided to go in, please fix the commit msg and title to the appropriate value.

2020-10-21 11:00 UTC, PerMac requested changes
as in the comment

2020-10-21 15:48 UTC, carlescufi approved these changes

2020-10-21 18:59 UTC, shantha-14 approved these changes

2020-10-22 07:10 UTC, PerMac commented
With the latest version (both ZTEST and MAIN stack sizes to 2048) only 2 test suites case overflow issue: net.socket.select (1 test case) and net.socet.tcp (10 test cases). @anangl found that adding `CONFIG_PRIVILEGED_STACK_SIZE=2048` solves these issues.
The question is: should we add this on the global level for ZTEST as the other stacks?

2020-10-22 09:33 UTC, tejlmand commented
> The question is: should we add this on the global level for ZTEST as the other stacks?

Discussed directly.

2020-10-22 09:54 UTC, PerMac commented
CI just finished. With the 3 above stacks increased all the stack overflow errors are fixed and no new ones appeared.

2020-10-22 09:54 UTC, PerMac approved these changes

2020-10-22 09:55 UTC, merged