event_manager: Make printing of event types optional
nrfconnect/sdk-nrf pull request #3206
Opened 2020-10-22 10:28 UTC by simensrostad

This patch adds a configurable option that enables/disables
the printing of event type names in the log output for the
event manager.

2020-10-22 10:47 UTC, pdunaj requested changes
If you don't print the event name how do you intend to identify the event? Using name or id in logging function of the event for this purpose seems wrong to me... You will have double name/id in case logging is re-enabled.

Btw - logging of each event can be disabled individually. Maybe you should simply disable all events you don't want to show instead?

If this is about name printing overhead maybe we should add option to use id instead of name if preferred?

2020-10-22 10:47 UTC, pdunaj commented on subsys/event_manager/event_manager.c
> +		if (IS_ENABLED(CONFIG_DESKTOP_EVENT_MANAGER_LOG_EVENT_TYPE)) {
this can become elseif at line 78

2020-10-22 11:24 UTC, simensrostad commented
> If you don't print the event name how do you intend to identify the event? Using name or id in logging function of the event for this purpose seems wrong to me... You will have double name/id in case logging is re-enabled.
> 
> Btw - logging of each event can be disabled individually. Maybe you should simply disable all events you don't want to show instead?
> 
> If this is about name printing overhead maybe we should add option to use id instead of name if preferred?

This is to accommodate applications that uses a single event for its managers with multiple types included in the event. These event types can be prefixed with some identifier signifying its origin and or purpose. So in order to not pollute the output log and to ensure proper alignment between an event print to the next its better to not include the event name. This is what it looks like with the name:

[00:00:00.337,707] <inf> event_manager: e: modem_mgr_event : MODEM_MGR_EVT_LTE_CONNECTING
[00:00:01.691,497] <inf> event_manager: e: modem_mgr_event : MODEM_MGR_EVT_LTE_DISCONNECTED
[00:00:02.897,216] <inf> event_manager: e: modem_mgr_event : MODEM_MGR_EVT_LTE_CONNECTED
[00:00:02.906,341] <inf> event_manager: e: cloud_mgr_event : CLOUD_MGR_EVT_CONNECTING
[00:00:14.469,696] <inf> event_manager: e: cloud_mgr_event : CLOUD_MGR_EVT_CONNECTED
[00:00:14.478,393] <inf> event_manager: e: app_mgr_event : APP_MGR_EVT_CONFIG_GET
[00:00:14.669,525] <inf> event_manager: e: modem_mgr_event : MODEM_MGR_EVT_DATE_TIME_OBTAINED

and this is without.

[00:00:00.334,289] <inf> event_manager: MODEM_MGR_EVT_LTE_CONNECTING
[00:00:01.642,364] <inf> event_manager: MODEM_MGR_EVT_LTE_DISCONNECTED
[00:00:02.848,083] <inf> event_manager: MODEM_MGR_EVT_LTE_CONNECTED
[00:00:02.855,407] <inf> event_manager: CLOUD_MGR_EVT_CONNECTING
[00:00:14.689,941] <inf> event_manager: CLOUD_MGR_EVT_CONNECTED

2020-10-22 12:22 UTC, simensrostad commented on subsys/event_manager/event_manager.c
> +		if (IS_ENABLED(CONFIG_DESKTOP_EVENT_MANAGER_LOG_EVENT_TYPE)) {
:+1:

2020-10-22 13:13 UTC, pdunaj approved these changes

2020-10-22 13:13 UTC, pdunaj commented
If it's useful then why not. I don't think it harms anybody.

2020-10-23 07:34 UTC, pdunaj commented
Let's wait until the 1.4.0 is out. I guess we would have to anyway but I am setting DNM just in case.

2020-11-24 10:24 UTC, simensrostad commented
@pdunaj Can we merge this?

2020-11-24 10:30 UTC, pdunaj commented
Hi @simensrostad , sure but since the policy is changed we need two reviewers (funny thing btw as its not the quantity but quality of the review that counts). Anyway @MarekPieta will help here.

2020-11-24 10:48 UTC, MarekPieta approved these changes

2020-11-24 10:53 UTC, pdunaj commented
@simensrostad , it seems that merging is still blocked because of tag creation. @carlescufi do you know when it will be re-enabled?

2020-12-07 08:33 UTC, merged