doc: relnotes: Zephyr release notes for NCS 1.4.0
nrfconnect/sdk-nrf pull request #3233
Opened 2020-10-26 12:57 UTC by carlescufi

Since we've gone through a full Zephyr release cycle between 1.3.0 and
1.4.0, point to the official Zephyr 2.4.0 release notes.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2020-10-26 13:34 UTC, ru-fu requested changes
If I understand it correctly, this is the PR for the current state on master, not related to the release.

In the release, the release-notes-latest page will not be included, but the content will be part of the release notes. See PR https://github.com/nrfconnect/sdk-nrf/pull/3127/ for the release notes - they should be updated in a similar way.

So this PR is for updating the release-notes-latest page that will be re-added after the release.

2020-10-26 13:34 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +Changes inherited from upstream Zephyr:
```suggestion

```
Delete this line - not needed.

2020-10-26 13:34 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +Since |NCS| v1.3.0 is based on Zephyr v2.3.0-rc1, and |NCS| v1.4.0 is based on Zephyr 2.4.0, we recommend referring to  Zephyr's 2.4.0 release notes directly: :ref:`zephyr:zephyr_2.4`.
```suggestion
The current |NCS| release is based on Zephyr 2.4.0.
See the :ref:`Zephyr 2.4.0 release notes <zephyr:zephyr_2.4>` for a list of changes.
```

2020-10-26 14:27 UTC, carlescufi commented
> In the release, the release-notes-latest page will not be included, but the content will be part of the release notes. See PR #3127 for the release notes - they should be updated in a similar way.

OK, so @greg-fer should cherry-pick this commit into #3127?

2020-10-26 14:31 UTC, ru-fu commented
> > In the release, the release-notes-latest page will not be included, but the content will be part of the release notes. See PR #3127 for the release notes - they should be updated in a similar way.
> 
> OK, so @greg-fer should cherry-pick this commit into #3127?

#3127 mainly needs the same changes in a different file (release-notes-1.4.0.rst).
This PR here should probably go in separately, since it's independent of the release.

2020-10-26 14:38 UTC, carlescufi commented
> > > In the release, the release-notes-latest page will not be included, but the content will be part of the release notes. See PR #3127 for the release notes - they should be updated in a similar way.
> > 
> > 
> > OK, so @greg-fer should cherry-pick this commit into #3127?
> 
> #3127 mainly needs the same changes in a different file (release-notes-1.4.0.rst).

OK, I will wait for @greg-fer to weigh in here before I push anywhere.

2020-10-26 14:45 UTC, greg-fer commented
I've applied changes from this PR into 1.4.0 release notes, in PR #3127 , commit 36b2cbcbc0633baccfbc4d9801acf22078cf0c8c.
This PR should indeed go in separately into master to update the release-notes-latest file.

2020-10-26 14:52 UTC, greg-fer approved these changes

2020-10-26 15:22 UTC, mbolivar-nordic approved these changes

2020-10-27 07:46 UTC, ru-fu approved these changes
Wanted to check the output to be sure it's okay, but the CI stopped.
So approving under the assumption that it would have been green ...

2020-10-30 10:04 UTC, ru-fu commented
This is now included in https://github.com/nrfconnect/sdk-nrf/pull/3240

2020-11-05 15:23 UTC, tejlmand commented
@carlescufi could this be closed, as 1.4 is already out ?

2020-11-13 14:42 UTC, carlescufi commented
> This is now included in #3240

Closing this.

2020-11-13 14:42 UTC, closed without merging