Updated licenses
nrfconnect/sdk-nrf pull request #3237
Opened 2020-10-26 15:59 UTC by Wild8ill

2020-10-26 18:03 UTC, hakonfam approved these changes
Files which I am codeowner for looks OK.

2020-10-27 09:23 UTC, KAGA164 requested changes

2020-10-27 09:23 UTC, KAGA164 commented on doc/mcuboot/conf.py
>  #!/usr/bin/env python3
I wonder if these scripts will work if the Shebang line `#!/usr/bin/env python3` isn't the first line of the file and python script has a C style comments ?

2020-10-27 09:59 UTC, MarekPorwisz commented on samples/openthread/cli/harness/nrf52840-ncs.py
> +/*
I see three issues here:
1. I think #!/usr/bin/env python must be the first line in the file, the copyright may come after
2. The file already has the copyrights done the proper way. This is not a nordic file in fact, so I am not sure this should be changed
3. The copyrights should be in python style comments not C

2020-10-27 10:04 UTC, MarekPorwisz requested changes
I've logged an issue to the files I am an owner.

In general I think that python files shall use Python style comments, not the C style.

2020-10-28 09:22 UTC, sigvartmh approved these changes
Changes to files I've authored seems good

2020-10-28 09:32 UTC, MarekPorwisz approved these changes

2020-10-28 10:18 UTC, carlescufi commented
@Wild8ill can we close this one and send Pull Requests for the different components? A couple of them have been merged already.

2020-10-28 11:10 UTC, shantha-14 commented
PR closed without merging. Domain owners are expected to raise individual PRS

2020-10-28 11:10 UTC, closed without merging