doc: add known-issues to nrf build
nrfconnect/sdk-nrf pull request #3271
Opened 2020-10-29 20:08 UTC by utzig

Run known-issues script from Zephyr on nrf build to generate a clean doc.warnings file. The current issues are due to a limitation in Sphinx which does not allow multiple symbols with the same name, eg, struct and function using the same name. The Sphinx fix is already work-in-progress, so this change should be dropped eventually.

2020-10-30 10:03 UTC, ru-fu requested changes
Doesn't seem to filter on Windows. :(

2020-10-30 11:06 UTC, utzig commented
> Doesn't seem to filter on Windows. :(

The easy solution is you all migrate to Linux! Just kidding, I updated the regex in the known-issues so it should work with both Unix and Windows line endings. I'll see into fixing the script upstream, but fixing the regex seems like an OK solution for now (here).

2020-11-03 14:44 UTC, ru-fu approved these changes
Filtering works now :)

2020-11-03 19:27 UTC, carlescufi approved these changes

2020-11-03 19:27 UTC, merged