Fix mcuboot_CONF_FILE list handling
nrfconnect/sdk-nrf pull request #3284
Opened 2020-11-01 01:06 UTC by otopetrik

Per zephyr documentation, project's 'CONF_FILE' can be a list of files.

Instead of 'get_filename_component unknown component' CMake error,
process 'mcuboot_CONF_FILE' as a list. First existing key file is used.

2020-11-01 01:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=3284) it.</sub>

2020-11-05 15:32 UTC, tejlmand requested changes
This code seems to be flawed, so would prefer if a proper fix is made.

2020-11-05 15:32 UTC, tejlmand commented on cmake/mcuboot.cmake
> +        set(mcuboot_key_file ${mcuboot_CONF_DIR}/${CONFIG_BOOT_SIGNATURE_KEY_FILE})
I would like to question if this code (both original and modified) actually works as expected.

What if `mcuboot_CONF_FILE` is defined and then user launches: `ninja mcuboot_menuconfig` and then reconfigures `BOOT_SIGNATURE_KEY_FILE` to a different file for testing ?

That doesn't seem to change the value of `mcuboot_key_file` and thing will most likely break.

2021-01-05 17:10 UTC, otopetrik commented
Not really sure, what is the proper way to fix this.
It seems there is another way to configure mcuboot keyfile.
https://github.com/nrfconnect/sdk-nrf/blob/1d0be6371e635d2ed94a4c5fbe3240a739488a93/applications/connectivity_bridge/CMakeLists.txt#L9-L11

2021-01-05 17:10 UTC, closed without merging

2021-01-06 11:30 UTC, tejlmand commented
> Not really sure, what is the proper way to fix this.
> It seems there is another way to configure mcuboot keyfile.
> 

which is another flawed way to do it, which is being cleaned up here:
https://github.com/nrfconnect/sdk-nrf/pull/3247