Include all regions in PM report
nrfconnect/sdk-nrf pull request #3300
Opened 2020-11-04 11:25 UTC by osaether

2020-11-04 12:16 UTC, hakonfam commented on scripts/partition_manager_report.py
> +    # print(bcolors["OKBLUE"] + "%s %s (0x%x - %dkB):" % (region, size, size / 1024) + bcolors["ENDC"])
Should this be removed?

2020-11-04 12:16 UTC, hakonfam commented on scripts/partition_manager_report.py
> +        print(f"{bcolors['OKBLUE']} {domain} {region} (0x{size:x} - {int(size/1024):d}kB): {bcolors['ENDC']}")
Could you pull out the difference between these two prints and assign the value to a variable which you pass to a single print expression?

```
val = f'{int(size/1024):d}kB' if size >= 1024 else f'{size:d}B'
print(... val ...)
```

2020-11-05 14:09 UTC, hakonfam approved these changes

2020-12-16 06:37 UTC, oyvindronningstad reviewed
Some suggestions to make it more concise.

2020-12-16 06:37 UTC, oyvindronningstad commented on scripts/partition_manager_report.py
> +            regions.append(r)
```suggestion
        regions = set(val['region'] for val in items.values())
        for r in regions:
```

2020-12-16 06:37 UTC, oyvindronningstad commented on scripts/partition_manager_report.py
> +                continue
Curious: When would this happen?

2020-12-16 06:37 UTC, oyvindronningstad commented on scripts/partition_manager_report.py
> +    print(f"{bcolors['OKBLUE']} {domain} {region} ({hex(size)} - {val}): {bcolors['ENDC']}")
```suggestion
    size_str = f'{int(size/1024):d}kB' if size >= 1024 else f'{size:d}B'
    print(f"{bcolors['OKBLUE']} {domain} {region} ({hex(size)} - {size_str}): {bcolors['ENDC']}")
```

2020-12-16 06:37 UTC, oyvindronningstad commented on scripts/partition_manager_report.py
> +    print(f"{bcolors['OKBLUE']} {domain} {region} ({hex(size)} - {val}): {bcolors['ENDC']}")
Maybe extract this logic into a function and use it below as well?

2020-12-16 09:07 UTC, tejlmand requested changes

2020-12-16 09:07 UTC, tejlmand commented on scripts/partition_manager_report.py
> +                pm_config[name]['size'] if pm_config[name]['size'] < 1024 else int(pm_config[name]['size']/1024),
If you use a lambda here, then you will signifficantly shorten the line:
```suggestion
               (lambda x: x if x < 1024 else int(x/1024))(pm_config[name]['size']),
```

2020-12-16 13:48 UTC, oyvindronningstad approved these changes
LGTM!

2021-01-04 13:01 UTC, osaether reviewed
@tejlmand  Simplified by using a function.

2021-01-11 13:42 UTC, tejlmand commented on scripts/partition_manager_report.py
> +            print_region(domain_name, r, max_address - min_address, pm_config_primary)
well, you do add four additional spaces to each line, making too long lines even longer.
That corresponds to changing those lines in this PR :wink:

2021-01-14 10:48 UTC, tejlmand approved these changes

2021-01-15 11:36 UTC, merged