net: openthread: Use atomic lock variant for CC310
nrfconnect/sdk-nrf pull request #3339
Opened 2020-11-13 13:08 UTC by lmaciejonczyk

For small AES encryption like MAC OpenThread frameas freguent mutuall
exclusive access to CC310 based on Zephyr's mutex is flexible
but havy approach. This is especially noticeable while calculating
throughput.
Atomic lock variant fasten these operations at the expense of comfort
of usage for applications which need to access CC310 from many threads
concurrently.

2020-11-27 09:47 UTC, pszkotak approved these changes

2021-01-12 08:58 UTC, edmont approved these changes

2021-01-21 12:40 UTC, edmont commented
@lmaciejonczyk can you please rebase?

2021-01-21 14:34 UTC, tejlmand requested changes

2021-01-21 14:34 UTC, tejlmand commented on west.yml
> +      revision: revision: pull/328/head
Too many revisions here:
```suggestion
      revision: pull/328/head 
```

2021-01-21 14:43 UTC, tejlmand commented on subsys/net/openthread/Kconfig
> +endif
In this case, this looks nicer and makes it easier to see the dependencies in menuconfig.
```suggestion
choice CC3XX_LOCK_VARIANT
	default CC3XX_ATOMIC_LOCK if CC310_BACKEND
endchoice
```

2021-01-22 07:58 UTC, NordicBuilder commented
The documentation should be made available shortly, follow this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3339
'>link</a> to see the preview!

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-01-22 13:39 UTC, tejlmand commented
Please update SHA to: 784df6f0093f915c0f1406393bcb6c242b02178d

2021-01-22 13:47 UTC, tejlmand approved these changes
SHA verified.

2021-01-22 14:46 UTC, merged