Known issues for nrf53
nrfconnect/sdk-nrf pull request #3500
Opened 2020-12-04 15:05 UTC by jostn

2020-12-04 15:09 UTC, jostn commented
This issue is related to https://github.com/zephyrproject-rtos/zephyr/issues/30441

2020-12-10 15:31 UTC, ru-fu requested changes

2020-12-10 15:31 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  Change BT_L2CAP_MTU from 65 to 247.
```suggestion
Limited HCI data packet payload in HCI UART sample
  The :ref:`zephyr:bluetooth-hci-uart-sample` sample supports a maximum of 69 bytes of HCI data packet payload.
  
  **Workaround:** In the :file:`ncs/zephyr/include/bluetooth/hci_raw.h` file, change the value for ``BT_L2CAP_MTU`` from 65 to 247.
```

2020-12-10 15:31 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +The hci_uart-example supports maximum 69 bytes of HCI Data packet payload.
Is there a JIRA issue for this?

2020-12-10 15:31 UTC, ru-fu commented on doc/nrf/known_issues.rst
This entry should be moved to the Zephyr section.

2021-02-23 01:09 UTC, closed without merging