doc: known_issues: add Thread known issue with UART in NCP sample
nrfconnect/sdk-nrf pull request #3501
Opened 2020-12-04 15:05 UTC by edmont

Update Thread known issues for v1-4-99-dev1 about NCP sample faulty UART responsiveness.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

KRKNWK-8286

2020-12-04 15:05 UTC, edmont commented
DNM until https://github.com/zephyrproject-rtos/zephyr/pull/30436 is merged.

2020-12-07 13:02 UTC, ru-fu requested changes

2020-12-07 13:02 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +KRKNWK-8286: NCP sample faulty UART responsiveness
```suggestion
KRKNWK-8286: Faulty UART responsiveness in Thread NCP sample
```

2020-12-07 13:02 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  A race condition in the UARTE driver makes the retrieval of Spinel responses to fail sometimes for the :ref:`NCP sample <ot_ncp_sample>`.
```suggestion
  A race condition in the UARTE driver causes the retrieval of Spinel responses to fail sometimes for the :ref:`ot_ncp_sample` sample.
```

2020-12-08 18:36 UTC, edmont commented
Updated link and applied review suggestions.

2020-12-09 07:45 UTC, ru-fu approved these changes

2020-12-09 14:54 UTC, MarekPorwisz approved these changes

2020-12-09 15:34 UTC, merged