west.yaml: Upmerge 14.12.2020 west update
nrfconnect/sdk-nrf pull request #3569
Opened 2020-12-16 15:26 UTC by de-nordic

Updated revision of zephyr-sdk.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2020-12-17 08:26 UTC, jhn-nordic commented
applications/connectivity_bridge has issues. CONFIG_SYS_PM_POLICY_APP has to be renamed to CONFIG_PM_POLICY_APP in prj.conf and uart_handler.c, but then it overflows RAM a lot. Will need to investigate

2020-12-17 08:27 UTC, jhn-nordic requested changes
applications/connectivity_bridge is broken (thingy91_nrf52840)

2020-12-18 10:17 UTC, rlubos approved these changes
Networking side looks good.

2020-12-18 15:53 UTC, nordic-auko approved these changes
connectivity_bridge application and alexa_gadget sample looks good

2020-12-18 22:31 UTC, de-nordic commented
Can someone look at the nrf/tests/subsys/dfu/dfu_target_mcuboot example?

2020-12-21 17:00 UTC, MarekPieta commented
I would like to make some manual checks for nrf_desktop before this goes in. I cannot add myself as a reviewer (that exceeds limit of 15 people).

2020-12-22 08:05 UTC, hakonfam commented
> Can someone look at the nrf/tests/subsys/dfu/dfu_target_mcuboot example?

I will do that

2020-12-23 07:29 UTC, MarekPieta commented on applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebug.conf
> +CONFIG_PM_DEEP_SLEEP_STATES=y
No need to select this explicitly. Power manager Kconfig option selects this one.

2020-12-23 07:29 UTC, MarekPieta commented on applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebug.conf
> +CONFIG_PM_DEEP_SLEEP_STATES=y
Also for other configurations.

2020-12-23 07:30 UTC, MarekPieta commented on applications/nrf_desktop/src/modules/Kconfig.power_manager
> +	select PW_DEEP_SLEEP_STATES
`PM_DEEP_SLEEP_STATES`

2020-12-23 07:37 UTC, MarekPieta requested changes
I noticed USB related problem for nrf_desktop devices. I am investigating it:
`<err> usb_nrfx: Buffer alloc failed for EP 0x01`

Edit:
PR with fix: https://github.com/zephyrproject-rtos/zephyr/pull/30980

2021-01-05 08:26 UTC, trond-snekvik approved these changes

2021-01-05 10:37 UTC, tejlmand approved these changes

2021-01-05 13:23 UTC, MarekPieta approved these changes
Everything works fine for nrf_desktop application

2021-01-05 13:47 UTC, pdunaj approved these changes

2021-01-05 14:23 UTC, de-nordic commented
> 
> 
> applications/connectivity_bridge is broken (thingy91_nrf52840)

@jhn-nordic Has anything changed with the app?

2021-01-06 07:07 UTC, hakonfam requested changes
TF-M sample is broken, looking at it

2021-01-06 07:09 UTC, jhn-nordic commented
> > applications/connectivity_bridge is broken (thingy91_nrf52840)
> 
> @jhn-nordic Has anything changed with the app?

I believe @nordic-auko  fixed this before the holidays

2021-01-06 08:40 UTC, hakonfam commented
> TF-M sample is broken, looking at it

@de-nordic here is a patch: https://github.com/de-nordic/sdk-zephyr/pull/2

2021-01-12 12:22 UTC, joerchan approved these changes

2021-01-13 13:05 UTC, grochu approved these changes
Looks good from the Protocols point of view. Good job!

2021-01-13 14:54 UTC, merged