doc: added AES crypto sample
nrfconnect/sdk-nrf pull request #3573
Opened 2020-12-17 07:57 UTC by peknis

Converted the sample in the Infocenter to rst.

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2020-12-18 09:00 UTC, b-gent commented on CODEOWNERS
> +/samples/crypto/aes/					  @peknis
FYI, this is done only for CI issues, obviously a different code owner should be put here

2020-12-18 13:28 UTC, b-gent requested changes

2020-12-18 13:28 UTC, b-gent commented on doc/nrf/samples.rst
> +.. _crypto_aes_samples:
```suggestion
.. _crypto_samples:
```

2020-12-18 13:28 UTC, b-gent commented on samples/crypto/aes/README.rst
> +1. Skip this step if you are using an RTT Viewer. By default, the crypto examples are configured to use RTT for logging. Start a terminal emulator like PuTTY and connect to the used COM port with the
New sentence from new line :) (everywhere)

2020-12-18 13:39 UTC, b-gent requested changes

2020-12-18 13:39 UTC, b-gent commented on samples/crypto/aes/README.rst
> +The source code and the project file of the sample are in ``<InstallFolder>\examples\crypto\nrf_crypto\aes``.
This is duplicated information from line 43

2020-12-18 13:40 UTC, b-gent commented
A Dependencies section would be nice at the end as per the sample template:
https://github.com/nrfconnect/sdk-nrf/blob/master/doc/nrf/templates/sample_README.rst#dependencies

It is not mandatory but most samples have it, if you can list dependencies, please do it.

2020-12-18 13:59 UTC, peknis commented
> A Dependencies section would be nice at the end as per the sample template:
> https://github.com/nrfconnect/sdk-nrf/blob/master/doc/nrf/templates/sample_README.rst#dependencies
> 
> It is not mandatory but most samples have it, if you can list dependencies, please do it.

I could not tell what sort of dependencies this sample has. How would I know which libraries this uses?

2021-01-13 11:11 UTC, frkv commented on samples/crypto/aes/README.rst
> +Testing different modes
Needs replacement pointing to logging in nRF Connect SDK

2021-01-13 11:12 UTC, frkv commented on samples/crypto/aes/README.rst
> +   * Serial: for UART or USB CDC ACM transport.
This needs to be converted into a sanity check mechanism of sorts

2021-12-01 13:23 UTC, closed without merging

2021-12-01 13:24 UTC, peknis commented
This was created just to be used as a template when porting crypto docs from Infocenter to NCS. Not needed anymore.