samples: openthread: disable autostart for CLI sample
nrfconnect/sdk-nrf pull request #3581
Opened 2020-12-18 12:03 UTC by edmont

The fact that for the CLI sample the Thread network is enabled automatically without user control has been reported to be counter-intuitive. This commit enables the manual Thread start for the CLI sample by making `CONFIG_OPENTHREAD_MANUAL_START=y` the default for all Thread samples.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

2020-12-18 12:40 UTC, MarekPorwisz approved these changes

2020-12-18 18:53 UTC, LuDuda approved these changes
Thanks :+1:

2021-01-04 14:08 UTC, ru-fu requested changes
I added a commit with some doc changes - reuse in RST is a pain. ☹️ 
Please check and squash if okay.

And just to double-check - when using the diagnostic module, there's no need to enable the network?

2021-01-04 14:23 UTC, edmont commented
> I added a commit with some doc changes - reuse in RST is a pain. frowning_face
> Please check and squash if okay.

Thanks, done.

> And just to double-check - when using the diagnostic module, there's no need to enable the network?

Exactly.

2021-01-04 14:43 UTC, ru-fu approved these changes

2021-01-07 08:08 UTC, rlubos approved these changes

2021-01-07 08:08 UTC, merged