applications: serial_lte_modem Unsolicited result code (URC) format
nrfconnect/sdk-nrf pull request #3584
Opened 2020-12-21 02:04 UTC by junqingzou

To help AT client to parse URC event message:
.Use comma ',' to separate each component in URC
.Use double quotes '"' to wrap string type component

DevZone ticket: 261674

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2020-12-21 02:13 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:14 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:14 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:14 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:15 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:15 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:15 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:15 UTC, lats1980 commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
Missed double quote for string.

2020-12-21 02:22 UTC, lats1980 commented on applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
>  				ctx.connected, ctx.cid, ctx.uname,
A missed space before \"%s\"

				" \"%s\", %d, %d\r\n",

2020-12-21 02:23 UTC, lats1980 commented on applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
>  				ctx.connected, ctx.cid, ctx.uname, ctx.pword,
A missed space before "%s"

			" \"%s\", %d, %d\r\n",

2020-12-21 02:27 UTC, lats1980 reviewed
Some missing space or double quotes as comment in line.

2020-12-21 11:23 UTC, rlubos approved these changes

2020-12-21 12:09 UTC, lats1980 approved these changes
Looks good!

2021-01-05 13:30 UTC, ru-fu requested changes
The current doc changes look good, but there are also a lot of AT commands and responses in slm_description.rst - these must probably be updated as well.

2021-01-06 03:07 UTC, junqingzou commented
> slm_description.rst

Added, please review

2021-01-06 08:52 UTC, ru-fu approved these changes
I don't know if these are all changes that are required or if some are missing (for example, there is an XACCEPT response in line 1069 that might need an update as well?).
But the changes that are made look good. :)

2021-01-07 08:25 UTC, merged