Add CHIP
nrfconnect/sdk-nrf pull request #3592
Opened 2020-12-28 08:44 UTC by greg-fer

Added user guide about CHIP.
Added info about CHIP to nRF52 UG.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2020-12-28 09:24 UTC, greg-fer commented
@LuDuda , @Damian-Nordic , @kkasperczyk-no , drafting this for your initial comments and feedback. If you want, you can also push to this PR and merge it into https://github.com/kkasperczyk-no/sdk-nrf/tree/chip_repository_integration , but only if Kamil's branch is rebased to include recent changes on master (including structural changes in links.txt).

2021-01-11 11:23 UTC, Damian-Nordic reviewed
Looking good, just a few comments/suggestions from me.

2021-01-11 11:23 UTC, Damian-Nordic commented on doc/nrf/ug_chip.rst
> +However, |NCS| is also one of the platforms available in CHIP.
How about adding: "That is, the code responsible for |NCS| and CHIP integration lies in the CHIP repository" or something similar?

2021-01-11 13:11 UTC, LuDuda requested changes
Thank you :+1: As discussed F2F please merge it with PR with initial CHIP support.

2021-01-11 13:11 UTC, LuDuda commented on doc/nrf/ug_chip.rst
> +* CHIP Reliable Message Protocol (CRMP) - reliable UDP-based transport protocol.
```suggestion
Connected Home over IP is in the early development stage. For this reason, the list of the protocol core supported features is not yet finalized nor implemented.
```

2021-01-12 15:32 UTC, greg-fer commented on doc/nrf/ug_chip.rst
> +  Operational certificates are used for establishing secure point-to-point communication.
Skipped as per conversation with Lukasz Duda.

2021-01-12 15:32 UTC, greg-fer commented on doc/nrf/ug_chip.rst
> +* CHIP commissioning procedure over Bluetooth LE, SoftAP, or Ethernet.
Skipped as per conversation with Lukasz Duda.

2021-01-12 15:32 UTC, greg-fer commented on doc/nrf/ug_chip.rst
> +* CHIP commissioning procedure over Bluetooth LE, SoftAP, or Ethernet.
Skipped as per conversation with Lukasz Duda.

2021-01-13 10:49 UTC, greg-fer commented
Going to be merged as part of: https://github.com/kkasperczyk-no/sdk-nrf/pull/3

2021-01-18 10:46 UTC, greg-fer commented
Closing, as this PR content's are now included in #3670

2021-01-18 10:46 UTC, closed without merging