doc: cleaning up the language in Power optimization doc
nrfconnect/sdk-nrf pull request #3597
Opened 2021-01-05 06:50 UTC by peknis

Making the tone more active and some other fixes.

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2021-01-05 14:56 UTC, umapraseeda requested changes

2021-01-05 14:56 UTC, umapraseeda commented on doc/nrf/app_power_opt.rst
> +   Hence, you can change the payload size to a value of 120 bytes in the :file:`prj.conf` to observe how it affects the charge in a single transmission.
```suggestion
    It is recommended to send a batch of six measurements for every 60 minutes to have some margin.
   Hence, you can change the payload size to a value of 120 bytes in the :file:`prj.conf` to observe how it affects the charge in a single transmission.
```

2021-01-05 14:56 UTC, umapraseeda commented on doc/nrf/app_power_opt.rst
> +	The result of the power profile simulation using Online Power Profiler:
```suggestion
The following image shows the result of the power profile simulation using Online Power Profiler:
```

2021-01-05 14:56 UTC, umapraseeda commented on doc/nrf/app_power_opt.rst
> +#. Before tuning, calculate the sending frequency of the payload, with the targeted battery life of two years:
```suggestion
#. Before tuning, calculate the payload transmission frequency, with the targeted battery life of two years:
```

2021-01-07 06:32 UTC, peknis commented on doc/nrf/app_power_opt.rst
> +* The `Power Profiler Kit II (PPK2)`_
Done

2021-01-07 06:33 UTC, peknis commented on doc/nrf/app_power_opt.rst
> +The result of the power profile simulation using Online Power Profiler:
Done

2021-01-07 06:33 UTC, peknis commented on doc/nrf/app_power_opt.rst
> +   Hence, you can change the payload size to a value of 120 bytes in the :file:`prj.conf` to observe how it affects the charge in a single transmission.
Done

2021-01-07 06:33 UTC, peknis commented on doc/nrf/app_power_opt.rst
> +	The result of the power profile simulation using Online Power Profiler:
Done

2021-01-07 06:33 UTC, peknis commented on doc/nrf/app_power_opt.rst
> +#. Before tuning, calculate the sending frequency of the payload, with the targeted battery life of two years:
Done

2021-01-07 07:56 UTC, umapraseeda approved these changes

2021-01-13 10:24 UTC, carlescufi approved these changes

2021-01-13 10:24 UTC, merged