tests: unity: Enable compilation on other without setjmp
nrfconnect/sdk-nrf pull request #3613
Opened 2021-01-07 14:47 UTC by nordic-krch

Updated cmock/unity to version which supports turning off setjmp
in cmock.

Added unity_config.h which excludes setjmp for platforms other
than native_posix.

Example test compiles now for qemu_cortex_m3

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2021-01-07 14:50 UTC, nordic-krch commented
Note that PR is currently based on PR in CMock. I commented there to see if it is alive today and got response reviewer.

2021-01-12 10:31 UTC, tejlmand requested changes
Did you miss a word in commit title ?

The title states:
```
tests: unity: Enable compilation on other without setjmp 
```

Should it have been:
```
tests: unity: Enable compilation on other platforms without setjmp 
```

2021-01-12 10:43 UTC, nordic-krch commented
@tejlmand fixed.

2021-01-12 11:03 UTC, tejlmand approved these changes

2021-01-13 08:22 UTC, trond-snekvik approved these changes

2021-01-29 18:07 UTC, carlescufi approved these changes

2021-02-03 07:41 UTC, nordic-krch commented
PR is merged to cmock. Updated west.yml, removed `DNM`.

2021-02-03 07:50 UTC, tejlmand commented
Please fix:
```
Complete results in compliance.xml
-:40: WARNING:BLOCK_COMMENT_STYLE: Block comments should align the * on each line
#40: FILE: tests/unity/unity_config.h:2:
+/* Copyright (c) 2021 Nordic Semiconductor ASA
+*
```

2021-02-03 08:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3613
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-03 09:17 UTC, merged