Bluetooth: Mesh: Remove light temp extension in CTL
nrfconnect/sdk-nrf pull request #3623
Opened 2021-01-08 14:08 UTC by trond-snekvik

According to the Bluetooth Mesh Model specification v1.0.1 section
6.4.3.1, the CTL server does not extend the Light temperature model, it
is just a "corresponding model".

Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

2021-01-15 12:17 UTC, joerchan approved these changes

2021-01-18 10:03 UTC, omkar3141 requested changes

2021-01-18 10:03 UTC, omkar3141 commented on subsys/bluetooth/mesh/light_ctrl_srv.c
> -	if (IS_ENABLED(CONFIG_BT_MESH_MODEL_EXTENSIONS)) {
This does not seem correct. The description of the PR does not match with the change and the file name where this is changed.

2021-01-19 10:10 UTC, Balaklaka approved these changes

2021-01-20 08:22 UTC, omkar3141 approved these changes

2021-01-20 08:23 UTC, merged