applications: serial_lte_modem: add CONFIG for external XTAL usage
nrfconnect/sdk-nrf pull request #3684
Opened 2021-01-19 08:47 UTC by junqingzou

The use of external XTAL was added in PR#3311 following spec of UARTE in PS.
Based on test, it increases power consumption when SLM is put to Idle mode.
Add CONFIG_SLM_EXTERNAL_XTAL (default 'y') to control the use of external XTAL.
Temporarily disable the usage in prj.conf so as to save power consumption.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2021-01-19 09:44 UTC, rlubos approved these changes

2021-01-19 13:30 UTC, ru-fu requested changes

2021-01-19 13:30 UTC, ru-fu commented on applications/serial_lte_modem/Kconfig
> +	bool "use external XTAL for UART"
```suggestion
	bool "Use external XTAL for UART"
```

2021-01-19 13:30 UTC, ru-fu commented on applications/serial_lte_modem/doc/slm_description.rst
> +.. option:: CONFIG_SLM_EXTERNAL_XTAL
```suggestion
.. option:: CONFIG_SLM_EXTERNAL_XTAL - Use external XTAL for UART
```

2021-01-19 13:30 UTC, ru-fu commented on applications/serial_lte_modem/doc/slm_description.rst
> +   Refer to nRF9160 PS v2.0 section 6.19 UARTE.
```suggestion
   This option configures the application to use an external XTAL for UART.
   See the `nRF9160 Product Specification`_ (section 6.19 UARTE) for more information.
```

2021-01-20 08:02 UTC, ru-fu approved these changes
Docs look good.

2021-01-22 07:32 UTC, merged