scripts: ncs_commands: add SOF to _BLOCKED_PROJECTS, remove TFM
nrfconnect/sdk-nrf pull request #3687
Opened 2021-01-19 12:36 UTC by jfischer-no

Add SOF (Sound Open Firmware) to _BLOCKED_PROJECTS and
rename Espressif HAL.

Remove TFM (Trusted Firmware M) from _BLOCKED_PROJECTS since
it is used by NCS.

2021-01-19 18:36 UTC, mbolivar-nordic requested changes
This should not be merged as a standalone patch. Please include it in the pull request with the corresponding changes to zephyr/west.yml instead.

2021-01-20 10:46 UTC, carlescufi commented
> This should not be merged as a standalone patch. Please include it in the pull request with the corresponding changes to zephyr/west.yml instead.

Split this PR into one that removes tfm from the blocked projects, which can be merged immediately, since tfm should *not* be in the blocked project already, and the rest which can come as part of the upmerge.

2021-01-20 11:03 UTC, jfischer-no commented
updated, @mbolivar-nordic please revise

2021-01-20 16:29 UTC, carlescufi approved these changes

2021-01-21 01:26 UTC, mbolivar-nordic approved these changes

2021-01-21 01:26 UTC, merged