samples: zigbee: add FEM support
nrfconnect/sdk-nrf pull request #3688
Opened 2021-01-19 12:39 UTC by wbober

This adds support for FEM in Zigbee examples. This is mainly docs
updates plus a few overlay files for nRF21540.

Signed-off-by: Wojciech Bober <wojciech.bober@nordicsemi.no>

2021-01-20 12:02 UTC, tomchy approved these changes

2021-01-20 15:57 UTC, wbober commented
Thanks @greg-fer . Looks good.

2021-01-21 08:32 UTC, greg-fer approved these changes

2021-01-21 12:24 UTC, edmont approved these changes
LGTM.

Just a nit, some of the copyright headers for the newly created files should say 2021 instead of 2020.

2021-01-21 12:29 UTC, ru-fu approved these changes

2021-01-21 15:33 UTC, wbober commented
@greg-fer I've added a note that FEM can't be combined with multiprotocol yet. Please take a look.

2021-01-21 19:01 UTC, jangalda-nsc approved these changes

2021-01-22 09:04 UTC, edmont commented on samples/zigbee/light_bulb/boards/nrf21540dk_nrf52840.overlay
> + * Copyright (c) 2020 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2021 Nordic Semiconductor ASA
```

2021-01-22 09:04 UTC, edmont commented on samples/zigbee/light_switch/boards/nrf21540dk_nrf52840.overlay
> + * Copyright (c) 2020 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2021 Nordic Semiconductor ASA
```

2021-01-22 09:04 UTC, edmont commented on samples/zigbee/network_coordinator/boards/nrf21540dk_nrf52840.overlay
> + * Copyright (c) 2020 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2021 Nordic Semiconductor ASA
```

2021-01-22 20:08 UTC, utzig commented
Regarding the CI failures, the gist of it is that you're adding an implicit link, "FEM support", into every file (through `rst_epilog`) and for every file that does not have a section named "FEM support" in it, there will be a warning.

But why doesn't it happen with Sphinx releases <3.3.0? This changed with the merge of https://github.com/sphinx-doc/sphinx/pull/8183, just after 3.2.1 release, which removed the `SubstitutionDefinitionsRemover` post transform, that was removing broken links from substitutions. This post-transform extension was initially added to solve issues with the Latex builder, and had the side-effect of allowing those links that don't resolve to work.

How to fix it? Easier way with implicit links would be to just copy/paste and not use substitutions, which is what I would suggest for this PR. Another option would be to add back the `SubstitutionDefinitionsRemover`, renamed to avoid conflict for people with Sphinx<3.3.0. And even another option would be to properly fix the dangling reference checks only for substitutions that are really being used in a given document, but I have no idea how hard that would be.

2021-01-25 08:09 UTC, ru-fu commented
> How to fix it? Easier way with implicit links would be to just copy/paste and not use substitutions, which is what I would suggest for this PR. 

Based on your explanation, it should also work to put the sentence into a file in doc/includes/ and include the content from there - since it then won't be included in other files that don't have the respective section.

2021-01-25 09:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3688
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-01-25 13:05 UTC, greg-fer requested changes

2021-01-25 13:05 UTC, greg-fer commented on doc/nrf/includes/sample_fem_support.txt
> +
Is this valid for Thread samples as well?
Can the two notes be combined into one?

2021-01-25 13:07 UTC, greg-fer requested changes

2021-01-25 13:07 UTC, greg-fer commented on samples/zigbee/light_bulb/README.rst
> +|zigbee_sample_fem_support|
I removed this line from Zigbee samples and shortcuts.txt earlier today. Please fix.

2021-01-25 14:38 UTC, greg-fer approved these changes

2021-01-26 10:22 UTC, greg-fer approved these changes

2021-01-26 16:03 UTC, merged