doc: known issues: Add issue link loss when LTK request is masked
nrfconnect/sdk-nrf pull request #3695
Opened 2021-01-20 08:13 UTC by rugeGerritsen

This issue is already fixed in the master branch.
See DRGN-15226.

Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

2021-01-20 11:32 UTC, joerchan approved these changes

2021-01-20 16:07 UTC, ru-fu requested changes

2021-01-20 16:07 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  This event is disabled when :option:`CONFIG_BT_SMP` and/or :option:`CONFIG_BT_CTLR_LE_ENC` is disabled.
```suggestion
  If the slave receives an encryption request while the "HCI LE Long Term Key Request" event is disabled, the link disconnects with the reason "LMP Response Timeout (0x22)".
  The event is disabled when :option:`CONFIG_BT_SMP` and/or :option:`CONFIG_BT_CTLR_LE_ENC` is disabled.
```

2021-01-21 08:08 UTC, ru-fu approved these changes

2021-01-21 08:48 UTC, merged