doc: zigbee: Remove redundant configuration step
nrfconnect/sdk-nrf pull request #3735
Opened 2021-01-25 09:45 UTC by sebastiandraus

This commit removes configuration step setting the TICKLESS_KERNEL as this option is enabled by default.

2021-01-25 10:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3735
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-01-25 10:03 UTC, greg-fer approved these changes

2021-01-25 10:22 UTC, greg-fer requested changes
Actually, a minor fix to the line below based on doc output.

2021-01-25 10:22 UTC, greg-fer commented on doc/nrf/ug_zigbee_configuring.rst
>  #. For current measurements for |nRF52840DK| or |nRF52833DK|, set **SW6** to ``nRF ONLY`` position to get the desired results.
```suggestion
#. For current measurements for nRF52840 DK board (PCA10056) or nRF52833 DK board (PCA10100), set **SW6** to ``nRF ONLY`` position to get the desired results.
See :ref:`ug_nrf52` for more information about these kits.
```

2021-01-25 13:37 UTC, greg-fer approved these changes

2021-01-27 11:23 UTC, rlubos approved these changes

2021-01-27 11:23 UTC, merged