release-note: record on MCUboot shell
nrfconnect/sdk-nrf pull request #3744
Opened 2021-01-25 16:28 UTC by nvlsianpu

Added record on introduction of the shell module
for MCUboot enabled application.

was inherited in the upmerge:
https://github.com/nrfconnect/sdk-zephyr/pull/413/

2021-01-25 16:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3744
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-01-26 07:33 UTC, de-nordic approved these changes

2021-01-26 08:22 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +
```suggestion
  * DFU:

    * Added shell module for MCUboot enabled application.
      See :option:`CONFIG_MCUBOOT_SHELL`.

```

2021-01-28 14:41 UTC, jfischer-no commented on doc/nrf/releases/release-notes-latest.rst
> +
@nvlsianpu please update

2021-01-28 18:25 UTC, nvlsianpu commented on doc/nrf/releases/release-notes-latest.rst
> +
done

2021-01-28 18:32 UTC, jfischer-no approved these changes

2021-01-29 08:20 UTC, ru-fu requested changes

2021-01-29 08:20 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +  * DFU
```suggestion
  * DFU:
```

2021-02-02 11:44 UTC, nvlsianpu commented on doc/nrf/releases/release-notes-latest.rst
> +  * DFU
fixed

2021-02-02 13:38 UTC, ru-fu approved these changes

2021-02-02 14:17 UTC, carlescufi approved these changes

2021-02-03 10:10 UTC, merged