crypto: Add AES CTR example using PSA APIS
nrfconnect/sdk-nrf pull request #3765
Opened 2021-01-27 14:26 UTC by Vge0rge

-Show encryption/decryption using AES CTR

Ref: NCSDK-7320

Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

2021-02-07 23:43 UTC, b-gent commented
The samples.rst file must be updated with a 'Crypto samples' section so that the new doc can appear in the structure. This has been shown here: https://github.com/nrfconnect/sdk-nrf/pull/3573/files

2021-02-07 23:56 UTC, b-gent requested changes

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +The AES sample shows how to perform AES encryption and decryption operations using the CTR mode without padding using an 128 bit AES key.
```suggestion
The AES sample shows how to perform AES encryption and decryption operations using the CTR mode without padding using a 128-bit AES key.
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +###########
```suggestion
###############
```
(must be at least as long as the text above, otherwise will return an error)

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +It does the following things:
I feel this sentence is redundant.

```suggestion
First, the sample encrypts a sample plaintext:
```
and then provide the steps in lines 18-22 as an ordered list. Remove text in line 17.

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   * Initalizes the PSA apis
```suggestion
   * The Platform Security Architecture (PSA) API is initialized.
```
Spell out acronyms when used for the first time, we cannot assume customers are familiar with all of them.

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   * Imports the AES key for encryption to the PSA keystore
```suggestion
   * The AES key used for encryption is imported to the PSA keystore.
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   * Generates a random IV
```suggestion
   * A random initialization vector (IV) is generated.
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   * Performs the encryption
```suggestion
   * Encryption is performed.
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   * Removes the key from the PSA keystore
```suggestion
   * The key is removed from the PSA keystore.
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +* Decrypts the sample plaintext:
```suggestion
* Then, the sample decrypts the sample plaintext:
```
and again , ordered list below

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +   :rows:  nrf5340dk_nrf5340_cpuappns nrf9160dk_nrf9160ns
```suggestion
   :rows:  nrf5340dk_nrf5340_cpuappns, nrf9160dk_nrf9160ns
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +The following process is applicable for testing the AES CTR example
```suggestion
Follow these steps to test the AES CTR example:
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +
```suggestion
.. note::
   By default, the sample is configured to use both RTT and UART for logging.
   If you are using RTT, skip the first step of the testing procedure.
   
```

2021-02-07 23:56 UTC, b-gent commented on samples/crypto/aes_ctr/README.rst
> +1. Skip this step if you are using an RTT Viewer. By default, the sample is configured to use both RTT and UART for logging.
this is now moved to note

2021-06-21 12:44 UTC, Vge0rge commented
All of the changes are incorporated in the final version of the PSA crypto examples: 
[samples/crypto](https://github.com/nrfconnect/sdk-nrf/tree/master/samples/crypto)

2021-06-21 12:44 UTC, closed without merging