Bluetooth: Mesh: Changing initial lightness range min to allowed value
nrfconnect/sdk-nrf pull request #3779
Opened 2021-01-29 11:55 UTC by dilner

Signed-off-by: David Dilner <david.dilner@nordicsemi.no>

2021-01-29 11:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3779) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3779) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=3779) it.</sub>

2021-01-29 12:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3779
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-01-29 15:40 UTC, Balaklaka approved these changes

2021-01-29 15:41 UTC, Balaklaka commented
Add labels

2021-02-01 06:41 UTC, trond-snekvik requested changes
Please put the signed-off-by line on the last line of the commit message. 
You'll also need to sign the CLA

2021-02-02 12:31 UTC, joerchan approved these changes

2021-02-02 12:46 UTC, trond-snekvik approved these changes

2021-02-02 12:46 UTC, merged