samples: ei_data_forwarder: Add EI data forwarder sample
nrfconnect/sdk-nrf pull request #3812
Opened 2021-02-03 14:28 UTC by MarekPieta

Change adds sample demonstrating usage of Edge Impulse data forwarder.

Jira: NCSDK-8038

2021-02-03 16:51 UTC, MarekPieta commented
We can disable sensor_sim trigger in Kconfig after this fix goes in:
https://github.com/nrfconnect/sdk-nrf/pull/3816

2021-02-04 09:34 UTC, pdunaj requested changes

2021-02-04 09:34 UTC, pdunaj commented on samples/ei_data_forwarder/src/main.c
> +void uart_cb(const struct device *dev, struct uart_event *evt, void *user_data)
static

2021-02-04 10:45 UTC, MarekPieta commented on samples/ei_data_forwarder/src/main.c
> +void uart_cb(const struct device *dev, struct uart_event *evt, void *user_data)
done

2021-02-04 11:16 UTC, pdunaj approved these changes

2021-02-08 11:50 UTC, MarekPieta commented
The commit will be added as part of: https://github.com/nrfconnect/sdk-nrf/pull/3768.
I close this PR.

2021-02-08 11:50 UTC, closed without merging