doc: release-notes-latest: Add changes in drivers from upmerge 20201214
nrfconnect/sdk-nrf pull request #3823
Opened 2021-02-04 11:49 UTC by anangl

Note changes related to Zephyr drivers that are relevant to NCS.

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

2021-02-04 12:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3823
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-05 10:16 UTC, ru-fu requested changes
Just some very small language updates. :-)

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Changed definition (parameters and return values) of API function :c:func:`clock_control_async_on`.
```suggestion
    * Changed the definition (parameters and return values) of the API function :c:func:`clock_control_async_on`.
```

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Excluded selection of nRF TIMER0 and RTC0 when Bluetooth controller is enabled.
```suggestion
    * Excluded selection of nRF TIMER0 and RTC0 when the Bluetooth Controller is enabled.
```

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Added the possibility of defining commands with variable number of arguments.
```suggestion
    * Added the possibility of defining commands with a variable number of arguments.
```

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Introduced :c:func:`gsm_ppp_start` and :c:func:`gsm_ppp_stop` functions, to allow restarting the networking stack without rebooting the device.
```suggestion
    * Introduced :c:func:`gsm_ppp_start` and :c:func:`gsm_ppp_stop` functions to allow restarting the networking stack without rebooting the device.
```

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Refactored :c:func:`uart_poll_out` implementation in the nRF UARTE driver to fix incorrect handling of HW flow control and power management.
```suggestion
    * Refactored the :c:func:`uart_poll_out` implementation in the nRF UARTE driver to fix incorrect handling of HW flow control and power management.
```

2021-02-05 10:16 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Extended the nRF RTC Timer driver with vendor-specific API that allows use of remaining compare channels of the RTC that provides the system clock.
```suggestion
    * Extended the nRF RTC Timer driver with vendor-specific API that allows using the remaining compare channels of the RTC that provides the system clock.
```

2021-02-05 13:37 UTC, ru-fu approved these changes
Looks good, thanks!

2021-02-08 15:55 UTC, carlescufi approved these changes

2021-02-08 15:55 UTC, carlescufi commented
Merging since this is doc-only and the doc build succeeded.

2021-02-08 15:56 UTC, merged