Zigbee: Build ncp sample with bootloader by default [KRKNWK-7933]
nrfconnect/sdk-nrf pull request #3831
Opened 2021-02-05 09:49 UTC by sebastiandraus

2021-02-05 10:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3831
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-08 09:41 UTC, wbober requested changes
Please update SPDX tag ```LicenseRef-Nordic-5-Clause```

2021-02-08 15:38 UTC, sebastiandraus commented
`DNM` until the https://github.com/nrfconnect/sdk-nrf/pull/3822 is merged

2021-02-09 10:32 UTC, wbober reviewed
LGTM. As discussed F2F lets enable dfu over usb when usb ncp transport is selected.

2021-02-09 19:39 UTC, tomchy commented
#3822 merged!
Please rebase & fix conflicts.

2021-02-10 08:59 UTC, wbober approved these changes
LGTM

2021-02-10 11:01 UTC, maciekfabia approved these changes

2021-02-10 12:52 UTC, rlubos approved these changes

2021-02-10 14:10 UTC, tejlmand requested changes

2021-02-10 14:10 UTC, tejlmand commented on samples/zigbee/ncp/CMakeLists.txt
> +  endif()
Shall the mcuboot.conf and app_with_mcuboot.conf only be used for `usb.overlay` or the `nrf52840dongle_nrf52840` board ?

Or is this code on the wrong side of the `if ... endif` statement. 

Also, please adopt to this pattern for the child image:
http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_multi_image.html#image-specific-variables

and probably use a `prj_mcuboot.conf` for the main app, which allows for additional `<board>_mcuboot` Kconfig fragments to be automatically sourced:
https://docs.zephyrproject.org/latest/guides/kconfig/setting.html#the-initial-configuration

Feel free to ping me directly to discuss how to best meet your needs and keep a pattern similar to what is used elsewhere.

2021-02-10 14:10 UTC, tejlmand commented on samples/zigbee/ncp/CMakeLists.txt
> +if ("usb.overlay" IN_LIST OVERLAY_CONFIG OR ${BOARD} STREQUAL "nrf52840dongle_nrf52840")
`.overlay` is for device tree files, use `overlay-usb.conf`.

2021-02-10 18:45 UTC, greg-fer approved these changes

2021-02-11 08:48 UTC, tejlmand approved these changes
Agreed that additional conf file cleanup will be addressed in followup PR.

2021-02-11 08:48 UTC, merged