manifest: Add UARTE power consumption fix
nrfconnect/sdk-nrf pull request #3853
Opened 2021-02-08 14:21 UTC by pszkotak

Update manifest with the fix lowering
idle current when used with disabling
console functionality.

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

https://github.com/nrfconnect/sdk-zephyr/pull/453
KRKNWK-8730

2021-02-08 14:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3853
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-09 11:53 UTC, lmaciejonczyk approved these changes

2021-02-09 12:50 UTC, pszkotak commented
Changed the sdk-zephyr PR as suggested by @anangl: https://github.com/nrfconnect/sdk-zephyr/pull/453#issuecomment-775896782.

2021-02-11 12:15 UTC, tejlmand requested changes
Included in: #3895

2021-02-11 15:11 UTC, closed without merging