west.yml: Update sdk-zephyr revision
nrfconnect/sdk-nrf pull request #3859
Opened 2021-02-09 07:20 UTC by jciupis

This commit updates sdk-zephyr revision.

Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

2021-02-09 07:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3859
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-09 10:46 UTC, hubertmis requested changes
It looks accompanying change to nrfxlib is required that would add capabilities to SL library

2021-02-09 14:02 UTC, hubertmis approved these changes

2021-02-10 15:02 UTC, tejlmand approved these changes

2021-02-10 21:41 UTC, merged