release-notes: notes for MCUboot, flash, MCUmgr, DFU
nrfconnect/sdk-nrf pull request #3867
Opened 2021-02-09 14:23 UTC by nvlsianpu

Describe changes introduced by the last sdk-zephyr upmerge to
components listed above.
sdk-mcuboot was additionally synchronized once more for bringing
the bugfix - patch updates its SHA as well.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2021-02-09 14:30 UTC, de-nordic approved these changes
Looks OK

2021-02-09 14:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3867
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-10 09:54 UTC, ru-fu requested changes
I'll add a commit.

2021-02-10 10:51 UTC, ru-fu reviewed
I added a commit - please check and squash, if okay.

We need a bit more information than just the commit titles (especially for the MCUboot part). Users need to be able to understand what has changed and where without going through the commits manually.

2021-02-10 15:57 UTC, nvlsianpu commented on doc/nrf/releases/release-notes-latest.rst
> +  * Updated the bootloader to clean up the NXP MPU configuration before boot.
will remove that line as not relevant for us

2021-02-10 16:12 UTC, ru-fu approved these changes

2021-02-10 21:39 UTC, merged