Added information about HomeKit ADK.
nrfconnect/sdk-nrf pull request #3870
Opened 2021-02-10 08:28 UTC by mariuszpos

Added information about HomeKit ADK.

Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>

2021-02-10 08:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3870
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-11 13:10 UTC, b-gent requested changes

2021-02-11 13:10 UTC, b-gent commented on doc/nrf/releases/release-notes-latest.rst
> +* Added HomeKit ADK repository available for verified company in MFi Program.
```suggestion
* Added HomeKit ADK repository available for verified companies participating in the MFi Program.
```
Not sure if this should be part of the Highlights section, can be decided by @carlescufi or during the doc review meeting.

2021-02-11 14:26 UTC, b-gent submitted a review, later dismissed

2021-02-11 16:24 UTC, mariuszpos commented
postponed

2021-02-18 10:34 UTC, b-gent approved these changes

2021-02-18 10:39 UTC, umapraseeda approved these changes

2021-02-18 11:34 UTC, merged