applications: serial_lte_modem: BUG-FIX unsupported FTP command
nrfconnect/sdk-nrf pull request #3922
Opened 2021-02-15 03:47 UTC by junqingzou

Old code was left when CLEAR command support was removed.
Remove it from enum.

JIRA reference: NCSIDB-379

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2021-02-15 04:07 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3922
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-15 07:19 UTC, martiles requested changes
Needs to update the [doc](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/serial_lte_modem/doc/FTP_AT_commands.html) to reflect the changes too

2021-02-15 07:23 UTC, junqingzou commented
> Needs to update the [doc](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/serial_lte_modem/doc/FTP_AT_commands.html) to reflect the changes too

But “clear” was not in this doc.

2021-02-15 09:00 UTC, rlubos approved these changes

2021-02-16 08:06 UTC, martiles approved these changes

2021-02-16 08:12 UTC, ru-fu approved these changes

2021-02-16 08:35 UTC, merged