Development
nrfconnect/sdk-nrf pull request #3931
Opened 2021-02-15 16:06 UTC by cntlccteam

1. added manual override time handling
2. changed regulator interval to 0

2021-02-15 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3931) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=3931) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=3931) it.</sub>

2021-02-15 16:07 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization.
At this time we are not accepting external contributions, but this may change soon.
Please visit https://devzone.nordicsemi.com/ to raise any issues you found or ask for help.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2021-02-15 16:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3931
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-16 11:10 UTC, trond-snekvik requested changes
Thanks for contributing! 

I have some trouble understanding this manual override mechanism and its purpose. From what I can tell, if a scene that disengages control is recalled, we will turn off the lights and a few seconds later, enable control anyway. If the scene engages control, we're unconditionally turning on the lights and starting the regulator. If we receive an occupancy mode, we'll extend the override timeout. 

This seems like a violation of spec, and I don't think it should be the generic behavior. I'd be interested in knowing what scenario this is addressing, so we can work out a solution that can be part of the framework code.

Our compliance checks are having some issues with the commit message formatting, as it does not follow the [commit guidelines](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#commit-guidelines):
- The commit must have a message body describing the change and why it's needed
- The commit title must start with a module prefix for where the change is made. In this case, `Bluetooth: Mesh:`.
- The commit must have a sign-off line at the end, in the format of `Signed-off-by: Firstname Lastname <myemail@mycompany.com>`. The name and email must match the commit author's name and email. Command line git can generate this line automatically by passing `-s` to `git commit`: `git commit -s`. This is a [Developer Certification of Origin](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#developer-certification-of-origin-dco) policy, and is mandatory.

The merge commit should not be excluded from the pull request. We generally never have merge commits in the git tree in the nRF Connect SDK projects. Commits can be removed through the interactive rebase mechanism described in [step 15 of the contribution workflow documentation](http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#contribution-workflow). This step in the workflow documentation should also be followed when updating pull requests.

I have also left a few style related comments that need to be resolved, please take a look.

2021-02-16 11:10 UTC, trond-snekvik commented on subsys/bluetooth/mesh/light_ctrl_srv.c
> +	k_delayed_work_submit(&srv->manual_override_timer,
This line has a space at the end. This needs to be removed.

2021-03-04 17:11 UTC, cntlccteam commented on include/bluetooth/mesh/light_ctrl_srv.h
> + * SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Nordic
ok

2021-03-04 17:17 UTC, cntlccteam commented on subsys/bluetooth/mesh/light_ctrl_srv.c
> +
added bt_mesh_light_ctrl_srv_

2021-03-04 17:19 UTC, cntlccteam commented on subsys/bluetooth/mesh/light_ctrl_srv.c
> +	}
ok

2021-03-22 10:00 UTC, joerchan reviewed
Hi @cntlccteam. Thank you for contributing.

I think something has gone a bit wrong in your changes here now. In the final diff there is only a change to the header file.
There is also merge commits in the pull request now, these needs to be removed, please use rebase instead.

The commit messages also needs to be updated to follow our commit message guidelines.
For more information about the contribution workflow you can see here:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/contribute/index.html#contribution-workflow

2021-03-22 10:00 UTC, joerchan commented on include/bluetooth/mesh/light_ctrl_srv.h
> +	// Manual Override Time (TimeMillisecond with resolution 0.001)
Please use `/* */` style commenting.

2021-03-22 10:00 UTC, joerchan commented on include/bluetooth/mesh/light_ctrl_srv.h
> +	// Indication if Manual Override Timer is enabled (Boolean)
Please use `/* */` style commenting.

2021-05-26 06:49 UTC, trond-snekvik commented
Closing this. The intended changes are carried out in #4634 and #4629.

2021-05-26 06:49 UTC, closed without merging