manifest: update for PR 410 nrfxlib
nrfconnect/sdk-nrf pull request #3946
Opened 2021-02-16 11:49 UTC by FrancescoSer

Updated manifest for PR 410 nrfxlib.

Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>

2021-02-16 12:57 UTC, b-gent approved these changes

2021-02-17 08:49 UTC, tejlmand commented
Please update SHA: f0b7d0dd50d6373910f565742b706f9c13529e8b

2021-02-17 09:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3946
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-17 09:48 UTC, tejlmand requested changes
Only one commit.

2021-02-17 10:48 UTC, tejlmand approved these changes

2021-02-17 11:45 UTC, merged