doc: Doc fixes for asset tracker v2
nrfconnect/sdk-nrf pull request #3963
Opened 2021-02-17 13:47 UTC by umapraseeda

Doc fixes for asset tracker v2

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

2021-02-17 13:54 UTC, coderbyheart requested changes

2021-02-17 13:54 UTC, coderbyheart commented on applications/asset_tracker_v2/README.rst
> +* :option:`CONFIG_HEAP_MEM_POOL_SIZE` - Configures the size of the heap, that is used by the application when encoding and sending data to the cloud. More information can be found in :ref:`memory_all
```suggestion
* :option:`CONFIG_HEAP_MEM_POOL_SIZE` - Configures the size of the heap that is used by the application when encoding and sending data to the cloud. More information can be found in :ref:`memory_allocation`.
```

2021-02-17 13:54 UTC, coderbyheart commented on applications/asset_tracker_v2/README.rst
> +* :option:`CONFIG_LTE_PDP_CONTEXT` - Used for manual configuration of APN. Set the option to ``0,\"IP\",\"apn.example.com\"``.
```suggestion
* :option:`CONFIG_LTE_PDP_CMD` - Used for manual configuration of the APN. Set the option to ``y`` to enable PDP define using AT+CGDCONT.
* :option:`CONFIG_LTE_PDP_CONTEXT` - Used for manual configuration of the APN. Example: ``0,\"IP\",\"apn.example.com\"``.
```

2021-02-17 14:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3963
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-18 07:08 UTC, jtguggedal approved these changes
Thanks

2021-02-18 08:14 UTC, simensrostad approved these changes

2021-02-18 09:27 UTC, coderbyheart approved these changes

2021-02-18 09:29 UTC, merged