doc: known_issues: Add HID configurator issue on Linux
nrfconnect/sdk-nrf pull request #3989
Opened 2021-02-19 11:14 UTC by MarekPieta

Change adds description of HID configurator issue under Linux.

Jira: NCSDK-8304

2021-02-19 11:20 UTC, MarekPieta commented
Waiting for review from @pdunaj

2021-02-19 11:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-3989
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-19 11:47 UTC, greg-fer requested changes
Couple of edits.

2021-02-19 11:47 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +NCSDK-8304: HID configurator issues of peripherals connected over Bluetooth LE to Linux host
```suggestion
NCSDK-8304: HID configurator issues for peripherals connected over Bluetooth LE to Linux host
```

2021-02-19 11:47 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  In that case, the device provides HID input reports, but it cannot be configured via HID configurator.
```suggestion
  In such case, the device will provide HID input reports, but it cannot be configured with the HID configurator.
```

2021-02-19 11:47 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  **Workaround:** Connect the nRF Desktop peripheral through USB or via nRF Desktop dongle.
```suggestion
  **Workaround:** Connect the nRF Desktop peripheral through USB or using the nRF Desktop dongle.
```

2021-02-19 12:28 UTC, MarekPieta commented
I squashed the changes

2021-02-19 13:39 UTC, umapraseeda approved these changes

2021-02-19 14:01 UTC, greg-fer approved these changes

2021-02-22 11:31 UTC, pdunaj approved these changes

2021-02-23 09:38 UTC, merged