zigbee: Add a known issue regarding Scenes commands
nrfconnect/sdk-nrf pull request #4024
Opened 2021-02-23 13:14 UTC by maciekfabia

Add a note in known issues section about corrupted payload
in Scenes cluster commands when using the production version
of ZBOSS lib.

2021-02-23 13:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4024
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-23 14:20 UTC, greg-fer requested changes
One suggestion.

2021-02-23 14:20 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  The payload of received Scenes cluster commands is corrupted when using the :ref:`nrfxlib:zboss` production libraries.
```suggestion
  When receiving Scenes cluster commands, the payload is corrupted when using the :ref:`nrfxlib:zboss` production libraries.
```

2021-02-23 14:56 UTC, maciekfabia commented on doc/nrf/known_issues.rst
> +  The payload of received Scenes cluster commands is corrupted when using the :ref:`nrfxlib:zboss` production libraries.
done

2021-02-24 08:46 UTC, tomchy approved these changes

2021-02-24 10:03 UTC, greg-fer approved these changes

2021-02-24 10:18 UTC, merged