ci: compliance: use py-versions from requirements-fixed.txt
nrfconnect/sdk-nrf pull request #4025
Opened 2021-02-23 14:22 UTC by thst-nordic

ci: compliance: use py-versions from requirements-fixed.txt
    
pylint==2.7.0 cause false failures for duplicate code
With this change, compliance workflow uses pylint==2.6.0

2021-02-23 14:40 UTC, tejlmand approved these changes
> ci: compliance: use py-versions from requirements-fixed.txt
> 
> pylint==2.7.0 cause false failures for duplicate code
> With this change, compliance workflow uses pylint==2.6.0

to me it seems that pylint 2.7.0 does what it is expected to do, and we request it to discover duplicate code:
https://github.com/nrfconnect/sdk-zephyr/blob/4ce908a2342494c19df09f347ce79ab81b415185/scripts/ci/pylintrc#L178
```
    duplicate-code,
```

so not sure locking pylint to version 2.6.x is the best approach in general, but of course reasonable for NCS 1.5.

2021-02-23 14:43 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4025
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-23 14:43 UTC, tejlmand commented
would be better to adjust line similarities upstream in Zephyr.

2021-02-23 14:51 UTC, thst-nordic commented
> reasonable for NCS 1.5.
> would be better to adjust line similarities upstream in Zephyr.

I agree. 

Something in the detection algorithm changed.  same lintrc, same source, with new pylint version causes errors.

2021-02-23 16:23 UTC, carlescufi requested changes

2021-02-23 16:23 UTC, carlescufi commented on .github/workflows/compliance.yml
> +      working-directory: ncs/nrf/scripts
Please remove this change, I'd rather run on the main repo

2021-02-23 16:23 UTC, carlescufi commented on .github/workflows/compliance.yml
> +        grep  pylint       requirements-fixed.txt | xargs pip3 install -U
Please replace all lines with:

```
grep -E "python-magic|junitparser|gitlint|pyilint|pykwalify" scripts/requirements-fixed.txt | xargs pip3 install -U
grep -E "west" scripts/requirements-fixed.txt | xargs pip3 install -U
```

2021-02-23 17:10 UTC, thst-nordic commented on .github/workflows/compliance.yml
> +        grep  pylint       requirements-fixed.txt | xargs pip3 install -U
ok

2021-02-23 17:16 UTC, carlescufi commented on .github/workflows/compliance.yml
> +        grep -E "python-magic|junitparser|gitlint|pylint|pykwalify" ncs/nrf/scripts/requirements-fixed.txt | xargs pip3 install -U
Ah, sorry!
I meant:
```
      with:
        path: ncs/nrf
``
and then remove the `ncs/nrf/` part in this line and the one below

2021-02-23 19:12 UTC, carlescufi approved these changes

2021-02-24 08:10 UTC, peknis approved these changes

2021-02-24 08:50 UTC, carlescufi commented
The workflow is not valid. .github/workflows/compliance.yml (Line: 26, Col: 7): Unexpected value 'run' .github/workflows/compliance.yml (Line: 23, Col: 7): Required property is missing: uses

2021-02-24 09:34 UTC, merged