doc: known_issues: Add new NCS 1.5 Thread known issues
nrfconnect/sdk-nrf pull request #4035
Opened 2021-02-24 17:18 UTC by MarekPorwisz

Added known issue (shell deadlock) found during NCS 1.5 testing that
affects also NCS 1.4

Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

2021-02-24 17:22 UTC, edmont approved these changes

2021-02-24 17:22 UTC, edmont commented on doc/nrf/known_issues.rst
> +  **Workaround:** If possible avoid invoking next command before execution of the previous one has complete.
```suggestion
  **Workaround:** If possible avoid invoking next command before execution of the previous one has completed.
```

2021-02-25 06:50 UTC, lmaciejonczyk approved these changes

2021-02-25 08:19 UTC, pszkotak approved these changes

2021-02-25 08:55 UTC, ru-fu requested changes

2021-02-25 08:55 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  **Workaround:** If possible avoid invoking next command before execution of the previous one has complete.
```suggestion
KRKNWK-9094: Possible deadlock in shell subsystem
  Issuing OpenThread commands too fast might cause a deadlock in the shell subsystem.

  **Workaround:** If possible, avoid invoking a new command before execution of the previous one has completed.
```

2021-02-25 12:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4035
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-25 12:23 UTC, ru-fu approved these changes

2021-03-01 12:03 UTC, merged