openthread: remove libs selection from Harness overlay
nrfconnect/sdk-nrf pull request #4050
Opened 2021-02-26 11:01 UTC by edmont

Deselect the Thread 1.1. precompiled libraries from the Harness overlay file.

This allows for easier adaptation for Thread 1.2 testing in the future.

This will also detach Thread CI from using libraries.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

KRKNWK-9139

2021-02-26 11:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4050
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-26 13:22 UTC, ru-fu requested changes

2021-02-26 13:22 UTC, ru-fu commented on doc/nrf/ug_thread_certification.rst
> +      The overlay file enables :ref:`multiprotocol support <ug_multiprotocol_support>` with Bluetooth LE advertising.
```suggestion
      The configuration option selects the precompiled OpenThread libraries.
      The overlay file enables :ref:`multiprotocol support <ug_multiprotocol_support>` with Bluetooth LE advertising.
```

2021-02-26 13:51 UTC, ru-fu approved these changes

2021-02-26 13:53 UTC, MarekPorwisz approved these changes

2021-02-26 14:35 UTC, mbolivar-nordic requested changes

2021-02-26 14:35 UTC, mbolivar-nordic commented on doc/nrf/ug_thread_certification.rst
> +         west build -b nrf52840dk_nrf52840 -- -DOVERLAY_CONFIG="harness/overlay-cert.conf -DCONFIG_OPENTHREAD_LIBRARY_1_1=y"
This doesn't look right. Shouldn't it be:

```suggestion
         west build -b nrf52840dk_nrf52840 -- -DOVERLAY_CONFIG=harness/overlay-cert.conf -DCONFIG_OPENTHREAD_LIBRARY_1_1=y
```

2021-02-26 15:09 UTC, edmont commented
@mbolivar-nordic yes it does. I misplaced the quotes in the previous commits, but anyway there are not needed when providing a single path.

2021-02-26 15:09 UTC, mbolivar-nordic commented
Thanks!

2021-02-26 15:18 UTC, mbolivar-nordic approved these changes

2021-02-26 18:31 UTC, mbolivar-nordic commented
@edmont any idea why CI might be saying this?

```
hudson.plugins.git.GitException: Command "git checkout -f cedb6891d8cb5eca38b6edd977aa233b4c0d53dd" returned status code 143:
```

2021-03-01 08:13 UTC, edmont commented
@mbolivar-nordic no idea. Triggering CI again since it doesn't seem related to the PR changes.

2021-03-01 10:41 UTC, rlubos approved these changes

2021-03-01 10:41 UTC, merged