DNM: west.yml using zephyr with twister fix
nrfconnect/sdk-nrf pull request #4051
Opened 2021-02-26 11:20 UTC by DatGizmo

Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>

2021-02-26 11:44 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4051
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-02-26 16:58 UTC, mbolivar-nordic requested changes
@DatGizmo we need to update the manifest in sdk-nrf when your sdk-zephyr PR is merged, and we should be testing against the PR reference, not a SHA in your fork.

Once the sdk-zephyr PR is merged, you will need to update this PR with the final SHA that gets merged into sdk-zephyr master. Then we will merge this sdk-nrf PR and users will have access to the updated sdk-zephyr using `west update`.

2021-02-26 16:58 UTC, mbolivar-nordic commented on west.yml
> +      url-base: https://github.com/datgizmo
```suggestion
```

2021-02-26 16:58 UTC, mbolivar-nordic commented on west.yml
> +      remote: gizmo
```suggestion
```

2021-02-26 16:58 UTC, mbolivar-nordic commented on west.yml
> +      revision: 852a2990a8dd70f37b4f0b7dcc80b6b6ff00ab25
```suggestion
      revision: pull/472/head
```

2021-02-26 18:08 UTC, PerMac commented
I suggested to put [DNM] on it, point in manifest to PR in sdk-zephyr, and when that PR is merged, point to the proper SHA and remove DNM from here. With the rest I agree with you @mbolivar-nordic

2021-03-01 18:17 UTC, mbolivar-nordic commented
@DatGizmo thanks for the update! Can you please force push an update to this PR changing the revision to c14c3658222fa940633f4560c9f9e96f92e3824a for sdk-zephyr? I've merged the PR as that commit.

2021-03-02 15:23 UTC, DatGizmo commented
The west.yaml was updated to commit "5acae16d9ea808785279b1de1cd177108c1b1354"
Which already includes the "c14c3658222fa940633f4560c9f9e96f92e3824a" commit.
So merging this PR is no longer needed.

2021-03-03 12:59 UTC, closed without merging