applications: machine_learning: Add sensor_sim_ctrl
nrfconnect/sdk-nrf pull request #4065
Opened 2021-03-01 14:48 UTC by MarekPieta

Change adds module to control generated sensor signal.

Jira: NCSDK-8457

2021-03-01 15:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4065
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-03 10:16 UTC, pdunaj requested changes

2021-03-03 10:16 UTC, pdunaj commented on applications/machine_learning/src/modules/Kconfig.sensor_sim_ctrl
> +menu "Sensor sim controller"
Simulated sensor controller

2021-03-03 10:28 UTC, MarekPieta commented on applications/machine_learning/src/modules/sensor_sim_ctrl.c
> +	const struct wave_gen_param *w;
done

2021-03-03 10:29 UTC, MarekPieta commented on applications/machine_learning/src/modules/Kconfig.sensor_sim_ctrl
> +menu "Sensor sim controller"
done

2021-03-03 15:02 UTC, pdunaj approved these changes

2021-03-05 11:25 UTC, emob-nordic approved these changes
Remember to add documentation for that later on. The comments are optional from my pov. If you want to make caf-like Kconfigs follow the comments, if no skip it.

2021-03-08 08:42 UTC, MarekPieta commented on applications/machine_learning/src/modules/Kconfig.sensor_sim_ctrl
> +# Copyright (c) 2021 Nordic Semiconductor
done

2021-03-08 08:52 UTC, MarekPieta commented on applications/machine_learning/src/modules/Kconfig.sensor_sim_ctrl
> +	bool "Enable simulated sensor controller"
done

2021-03-08 11:27 UTC, merged