Softdevice_controller: remove RNG from the SoftDevice Controller
nrfconnect/sdk-nrf pull request #4071
Opened 2021-03-02 08:57 UTC by bewi-nordic

The application is responsible for providing the SoftDevice Controller
with random number generating functions.

Signed-off-by: Bernhard Wimmer <bernhard.wimmer@nordicsemi.no>

2021-03-02 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4071) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4071) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=4071) it.</sub>

2021-03-02 09:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4071
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-02 10:42 UTC, rugeGerritsen commented
@joerchan , should we add the label "CI-all" to this PR?

2021-03-02 11:17 UTC, rugeGerritsen approved these changes

2021-03-02 15:06 UTC, joerchan requested changes
Great to finally see this change :)

2021-03-02 15:06 UTC, joerchan commented on subsys/bluetooth/controller/hci_driver.c
> +		return -EINVAL;
```suggestion
		return -ENODEV;
```

2021-03-02 15:06 UTC, joerchan commented on subsys/bluetooth/controller/hci_driver.c
> +		BT_ERR("Failed to register randomness source with the SoftDevice Controller");
Maybe add the err code returned to the log
```suggestion
		BT_ERR("Failed to register rand source (%d)", err);
```

2021-03-03 13:07 UTC, joerchan approved these changes

2021-03-03 13:18 UTC, joerchan commented
> @joerchan , should we add the label "CI-all" to this PR?

Let's be on the safe side.

2021-03-08 09:43 UTC, merged