samples: bluetooth: Fix peripheral_lbs device name
nrfconnect/sdk-nrf pull request #4133
Opened 2021-03-10 11:34 UTC by rugeGerritsen

The device name should have a proper name

2021-03-10 11:52 UTC, joerchan approved these changes

2021-03-10 11:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4133
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-11 10:09 UTC, KAGA164 requested changes
Please align the device name in a sample doc. I'm not sure also about a `nRF Blinky` application if it will work with this sample with the new name.

2021-03-11 10:28 UTC, KAGA164 commented
> Please align the device name in a sample doc. I'm not sure also about a `nRF Blinky` application if it will work with this sample with the new name.

I checked the `nRF Blinky` application. It works fine with devices under a different name.

2021-03-11 10:29 UTC, rugeGerritsen commented
> > Please align the device name in a sample doc. I'm not sure also about a `nRF Blinky` application if it will work with this sample with the new name.
> 
> I checked the `nRF Blinky` application. It works fine with devices under a different name.
Thanks for checking. Updated the README now.

2021-03-11 10:31 UTC, KAGA164 approved these changes

2021-03-11 11:06 UTC, merged