doc: Update known_issues for SoftDevice controller
nrfconnect/sdk-nrf pull request #4148
Opened 2021-03-11 15:13 UTC by kromancer

The SoftDevice Controller is not qualifiable for the nRF52832 SoC

Signed-off-by: Konstantinos Sotiropoulos <koso@nordicsemi.no>

2021-03-11 16:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4148
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-15 13:01 UTC, ru-fu requested changes
Sorry - I had commented last week, but seems the review didn't go through ...

2021-03-17 09:12 UTC, ru-fu requested changes

2021-03-17 09:12 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  Due to improper execution of product anomomally work arounds, certain conformance test cases are failing.
```suggestion
  Due to improper execution of product anomaly workarounds, certain conformance test cases are failing for nRF52832.
```

2021-03-17 09:12 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  **Workaround:** Upgrade to v1.5.1 or use master.
```suggestion
  **Workaround:** Upgrade to v1.5.1 (once available) or use the master branch.
```

2021-03-17 09:24 UTC, ru-fu approved these changes

2021-03-17 13:31 UTC, joerchan approved these changes

2021-03-17 13:40 UTC, thomasstenersen approved these changes

2021-03-17 13:43 UTC, ru-fu approved these changes

2021-03-17 15:17 UTC, merged