netboot: Fix stand alone build and add sample.yaml
nrfconnect/sdk-nrf pull request #4162
Opened 2021-03-15 11:30 UTC by osaether

Fix stand alone build and add sample.yaml.

Ref: NCSDK-7173

Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

2021-03-15 11:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4162
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-15 14:28 UTC, hakonfam requested changes

2021-03-15 14:28 UTC, hakonfam commented on doc/nrf/known_issues.rst
> -.. rst-class:: v1-5-0
I think we should keep this for now, and then not add v1-6-0 when that arrives. This way customers can see what is fixed between versions etc.

2021-03-17 10:31 UTC, hakonfam approved these changes

2021-03-24 11:56 UTC, ioannisg approved these changes

2021-03-24 11:57 UTC, merged