ext: cJSON: Update cJSON library to version v1.7.14
nrfconnect/sdk-nrf pull request #4222
Opened 2021-03-25 16:28 UTC by simensrostad

This commit updates the cJSON library to version v1.7.14.

**Note**
@sigvartmh and @plskeggs had commits on top of the previous version update. For the time being I squashed those into the version update commit in this PR. The question is really if they should be added on top to more clearly state what alterations has been done for NCS.

The reason for this update is that there has been added new APIs in cJSON that would be nice to take advantage of in NCS.

2021-03-25 16:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4222
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-25 17:47 UTC, plskeggs commented
Seems to me any Nordic-specific customizations should be kept as separate commits, perhaps in a similar way to how we handle Zephyr and [nrf noup] changes.

2021-03-25 21:29 UTC, sigvartmh commented
So the commit I added is basically safety additions that were removed from cJSON due to not being supported in C89.

2021-03-25 21:31 UTC, sigvartmh commented
I don't mind bumping the cJSON version btw.

2021-03-25 21:32 UTC, simensrostad commented
> So the commit I added is basically safety additions that were removed from cJSON due to not being supported in C89. Would recommend keeping those if they are still applicable. Could you change this PR to include them separately so that it's possible to review it properly if the changes are still needed?

Yes. Ill add the commits on top.

2021-03-25 21:39 UTC, plskeggs commented
Should we continue to manage cJSON this way, or make an effort to get changes made upstream?

2021-03-25 21:40 UTC, sigvartmh commented
The changes I added will never be accepted upstream as long as they target C89 which seems to be a major design goal.

2021-03-25 21:42 UTC, plskeggs commented
Yes, I agree with you on the C89 changes.  There are some other changes I've made related to memory management and a PR for adding more CS functions (constant strings for keys).  Bernt Johan also added a FreeString function.

2021-03-25 21:45 UTC, sigvartmh commented
Those I would at least try to submit upstream to see if they would want it. As it could be beneficial and properly better maintained.

2021-03-26 19:53 UTC, mbolivar-nordic requested changes
> @sigvartmh and @plskeggs had commits on top of the previous version update. For the time being I squashed those into the version update commit in this PR. The question is really if they should be added on top to more clearly state what alterations has been done for NCS.

I was unaware that we were carrying out of tree patches to an upstream library in an `ext/` directory in sdk-nrf.

IMO this really should have been managed using the process described in our development model here from the beginning:

https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_code_base.html#oss-repositories-downstream-project-history

I.e. this should be a fork of the cjson library repository inside the nrfconnect GH organization, with our downstream-only patches applied on top, with `[nrf ...]` sauce tags as described in the development model, and a pointer to it in nrf/west.yml.

I'm requesting changes as I think it should be done this way instead before we update to a new version.

cc @carlescufi

2021-03-26 23:41 UTC, mbolivar-nordic commented
> IMO this really should have been managed using the process described in our development model here from the beginning:

@plskeggs let me know that cjson has been in nrf for 2.5 years, so it's a little bit older than when west came on the scene. Fair enough -- still no reason to keep making an exception of it after all this time.

2021-03-30 07:31 UTC, simensrostad commented
> > @sigvartmh and @plskeggs had commits on top of the previous version update. For the time being I squashed those into the version update commit in this PR. The question is really if they should be added on top to more clearly state what alterations has been done for NCS.
> 
> I was unaware that we were carrying out of tree patches to an upstream library in an `ext/` directory in sdk-nrf.
> 
> IMO this really should have been managed using the process described in our development model here from the beginning:
> 
> https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_code_base.html#oss-repositories-downstream-project-history
> 
> I.e. this should be a fork of the cjson library repository inside the nrfconnect GH organization, with our downstream-only patches applied on top, with `[nrf ...]` sauce tags as described in the development model, and a pointer to it in nrf/west.yml.
> 
> I'm requesting changes as I think it should be done this way instead before we update to a new version.
> 
> cc @carlescufi

This sounds like the better approach. How would we proceed in doing this? I guess there would have to be some effort from one of the ```ncs-code-owners``` to get the repository forked.

2021-03-30 22:21 UTC, mbolivar-nordic commented
> This sounds like the better approach. How would we proceed in doing this? I guess there would have to be some effort from one of the `ncs-code-owners` to get this properly setup.

Yep, I think we need to decide on a name and have @carlescufi agree and create the repo.

2021-04-21 18:57 UTC, carlescufi commented
> > This sounds like the better approach. How would we proceed in doing this? I guess there would have to be some effort from one of the `ncs-code-owners` to get this properly setup.
> 
> Yep, I think we need to decide on a name and have @carlescufi agree and create the repo.

I completelt agree with @mbolivar-nordic. If this is patched then it should be treated like any other west project / zephyr module.

2021-04-21 20:10 UTC, mbolivar-nordic commented
Thanks @carlescufi for that and for letting me make repositories in the nrfconnect org.

@simensrostad I've made the repository here: https://github.com/nrfconnect/sdk-cjson

Can I ask you and the others who have touched this code since it was forked (e.g. @plskeggs ) to decide on how you'd like to populate it?

I think this should be submitted as pull requests with the following things:

in sdk-cjson:

1. an upstream cJSON commit, with full git history, to start with (I'm guessing whatever commit is tagged v1.7.14 will be fine)
2. a series of patches on top of it with `[nrf ...]` tags for our downstream patches, if any are still needed, on top. Note that we generally discourage such things, and any bug fixes should be sent upstream directly and put on top of our fork with `[nrf fromlist]` until we can do a proper upmerge after they are reviewed and merged upstream. Ideally we would only have the minimum commit necessary to make it a standalone zephyr module.

in sdk-nrfconnect:

1. addition of sdk-cjson to west.yml, pointing at our fork
2. removal of the existing code in `ext` and any other cleanups needed to get the library code from the new sdk-cjson module

Please let me know if anything's unclear etc. Thanks!

2021-04-28 08:23 UTC, simensrostad commented
PRs are up, Lets continue the conversion there.
[ https://github.com/nrfconnect/sdk-cjson/pull/1 ] 
[ https://github.com/nrfconnect/sdk-nrf/pull/4409 ]

2021-04-28 08:29 UTC, closed without merging