Update MPSL and SoftDevice Controller
nrfconnect/sdk-nrf pull request #4232
Opened 2021-03-29 09:18 UTC by rugeGerritsen

* Fixes a couple of bugs
* Introduces an API for configuring the number of supported advertising sets. Currently we only support 1 one advertising set.

I will create a separate PR for updating the known issues page

2021-03-29 10:51 UTC, joerchan requested changes
Shouldn't there be something remove in this PR since limitations is moved?
https://github.com/nrfconnect/sdk-nrfxlib/pull/449/files#diff-794dbd2613fe781e716b96b313b0fe1528ab53a619a9bce0472999878c513fcbR25

2021-03-29 10:51 UTC, joerchan commented on subsys/bluetooth/controller/hci_driver.c
> +#elif defined(CONFIG_BT_PERIPHERAL)
```suggestion
#elif defined(CONFIG_BT_BROADCASTER)
```

2021-03-29 11:22 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
> +#elif defined(CONFIG_BT_PERIPHERAL)
Thanks!

2021-03-29 11:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4232
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-29 12:48 UTC, joerchan approved these changes

2021-03-30 07:42 UTC, ru-fu approved these changes

2021-03-31 15:23 UTC, merged