known_issues: Add some more known issues
nrfconnect/sdk-nrf pull request #4235
Opened 2021-03-29 11:56 UTC by rugeGerritsen

* DRGN-15251: Very rare assertion fault when peripheral on Coded PHY 
* DRGN-15310: HCI Read RSSI fails

2021-03-29 12:19 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4235
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-03-29 12:56 UTC, thomasstenersen commented
@ru-fu is there a way to indicate that a known issue has been fixed in current master? As it is today, you'd have to manually cross-check the release notes of your component from the last tag?

2021-03-29 12:58 UTC, thomasstenersen requested changes
Minor nitpick

2021-03-29 12:58 UTC, thomasstenersen commented on doc/nrf/known_issues.rst
> +  * A packet is received with a CRC error
If the other bullet points ends with a period, this one should too :)

2021-03-30 07:56 UTC, ru-fu requested changes

2021-03-30 07:56 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +DRGN-15251: Very rare assertion fault when peripheral on Coded PHY
```suggestion
DRGN-15251: Very rare assertion fault when connected as peripheral on Coded PHY
```

2021-03-30 07:56 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  * A packet is received with a CRC error
```suggestion
  The controller might assert when the following conditions are met:

  * The device is connected as a peripheral.
  * The connection PHY is set to LE Coded PHY.
  * The devices have performed a data length update, and the supported values are above the minimum specification defined values.
  * A packet is received with a CRC error.
```

2021-03-30 07:56 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  The command "HCI Read RSSI" returns "Command Disallowed (0x0C)"
```suggestion
  The command "HCI Read RSSI" always returns "Command Disallowed (0x0C)".
```

2021-03-30 07:57 UTC, ru-fu commented
> 
> 
> @ru-fu is there a way to indicate that a known issue has been fixed in current master? As it is today, you'd have to manually cross-check the release notes of your component from the last tag?

No, we do not mark issues that have been fixed on master. There was a discussion about adding a "master" tag as well, but it was rejected.

2021-03-30 12:46 UTC, thomasstenersen approved these changes

2021-03-30 15:20 UTC, ru-fu commented on doc/nrf/known_issues.rst
> +  The command "HCI Read RSSI" always returns "Command Disallowed (0x0C)"
```suggestion
  The command "HCI Read RSSI" always returns "Command Disallowed (0x0C)".
```

2021-03-30 15:25 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +  The command "HCI Read RSSI" always returns "Command Disallowed (0x0C)"
Fixed

2021-04-22 18:08 UTC, carlescufi approved these changes

2021-05-14 06:08 UTC, rugeGerritsen commented
Rebased on master to retrigger CI

2021-05-14 08:26 UTC, merged