doc: release-notes-latest: Summarize networking changes from Zephyr
nrfconnect/sdk-nrf pull request #4243
Opened 2021-03-30 13:50 UTC by rlubos

Update the changelog based on the Zephyr PR list from the recent
upmerge.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2021-03-30 14:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4243
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-06 08:43 UTC, ru-fu requested changes
Just a bit of language nitpicking.

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Updated the OpenThread version to commit ``8f7024c3e9beb47a48cfc1e3185f5fce82fffba9``.
Need an empty line before the sublist.

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Added missing ``getaddrinfo()`` error codes translation.
```suggestion
    * Added verification of the network interface status before sending a packet.
    * Added missing translations for ``getaddrinfo()`` error codes.
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Added multiple bugfixes for IEEE802154 L2.
```suggestion
    * Added multiple bug fixes for IEEE 802.15.4 L2.
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Fixed a bug where large LwM2M endpoint names were not encoded properly in the Register message.
```suggestion
    * Fixed a bug where large LwM2M endpoint names were not encoded properly in the registration message.
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Added new OpenThread options:
```suggestion
    * Added the following OpenThread options:
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Fixed UTF-8 strings logging.
```suggestion
    * Fixed logging of UTF-8 strings.
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Fixed TLS sockets access from userspace.
```suggestion
    * Fixed TLS sockets access from user space.
```

2021-04-06 08:43 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * Updated a few API functions, to accept a const pointer when appropriate.
```suggestion
    * Updated a few API functions to accept a const pointer when appropriate.
```

2021-04-06 08:44 UTC, ru-fu commented
Need to update the Zephyr commit as well - not sure who's doing this?

2021-04-07 08:55 UTC, rlubos commented
Thanks @ru-fu, I've applied the changes.

> Need to update the Zephyr commit hash as well - not sure who's doing this?

From what I see the Zephyr SHA was already updated in the release notes in one of the upmerge commits so it's up to date.

2021-04-08 15:16 UTC, ru-fu approved these changes

2021-04-22 18:10 UTC, carlescufi approved these changes

2021-04-22 18:10 UTC, merged