applications: machine_learning: Add NUS to EI data forwarder
nrfconnect/sdk-nrf pull request #4271
Opened 2021-04-06 14:35 UTC by MarekPieta

Change introduces forwarding sensor samples over NUS and adds basic Bluetooth configuration for Thingy52.

Jira: NCSDK-8507

2021-04-06 14:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4271
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-07 07:47 UTC, pdunaj requested changes
Since NUS is so much different then UART I have a feeling it should be separated to different file. Let's talk offline.

2021-04-07 07:47 UTC, pdunaj commented on applications/machine_learning/src/modules/ei_data_forwarder.c
> +void bt_nus_sent_cb(struct bt_conn *conn)
static

2021-04-07 08:46 UTC, MarekPieta commented on applications/machine_learning/src/modules/ei_data_forwarder.c
> +void bt_nus_sent_cb(struct bt_conn *conn)
fixed

2021-04-08 11:12 UTC, MarekPieta commented on applications/machine_learning/src/modules/ei_data_forwarder_bt_nus.c
> +		return pos;
Will change it to return false, we should not consume the event in that case

2021-04-08 17:07 UTC, MarekPieta commented on applications/machine_learning/src/modules/ei_data_forwarder_bt_nus.c
> +		return pos;
Added fix

2021-04-09 11:40 UTC, emob-nordic approved these changes

2021-04-12 07:59 UTC, pdunaj approved these changes

2021-04-12 07:59 UTC, pdunaj commented on applications/machine_learning/src/util/ei_data_forwarder.c
> +	int tmp;
tmp could be moved to lower scope

2021-04-12 08:39 UTC, MarekPieta commented on applications/machine_learning/src/util/ei_data_forwarder.c
> +	int tmp;
done

2021-04-15 10:57 UTC, merged