samples: bluetooth: Add information to documentation.
nrfconnect/sdk-nrf pull request #4280
Opened 2021-04-07 12:28 UTC by maje-emb

In central_hr_coded and peripheral_hr_coded documention
added information that these samples doesn't support ZephyrLL

Ref: NCSDK-8743

Signed-off-by: Marcin Jeliński <marcin.jelinski@nordicsemi.no>

2021-04-07 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=4280) it.</sub>

2021-04-07 12:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4280
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-07 12:54 UTC, grochu requested changes

2021-04-07 12:54 UTC, grochu commented on samples/bluetooth/central_hr_coded/README.rst
> +The sample demonstrates a Bluetooth LE Central role functionality by scanning for other Bluetooth LE devices that run a Heart Rate Server with LE Coded PHY support which not available in ZephyrLL
I think the official term for the Zephyr LL is this: `Zephyr Bluetooth LE Controller` - as it is written in _doc/nrf/ug_ble_controller.rst_ - you can link to that label.

2021-04-07 12:54 UTC, grochu commented on samples/bluetooth/peripheral_hr_coded/README.rst
> +The sample demonstrates a basic Bluetooth LE Peripheral role functionality that exposes the Heart Rate GATT Service with LE Coded PHY support which not available in ZephyrLL.
See a similar comment in the central_hr_coded sample.

2021-04-09 12:24 UTC, grochu approved these changes
Looks good.

2021-04-09 12:27 UTC, peknis approved these changes

2021-04-09 12:30 UTC, peknis commented on samples/bluetooth/central_hr_coded/README.rst
> +The sample demonstrates a Bluetooth LE Central role functionality by scanning for other Bluetooth LE devices that run a Heart Rate Server with LE Coded PHY support which not available in Zephyr Bluet
To get rid of the compliance error, simply take out the trailing space after the full stop.

2021-04-09 13:02 UTC, KAGA164 approved these changes

2021-04-09 14:33 UTC, merged