manifest: Update sdk-zephyr revision with PPP changes from upstream
nrfconnect/sdk-nrf pull request #4329
Opened 2021-04-14 12:26 UTC by rlubos

Update sdk-zephyr revision with PPP changes from upstream.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2021-04-14 12:29 UTC, jhirsi approved these changes

2021-04-14 12:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4329
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-22 10:24 UTC, tejlmand requested changes
This PR is superseded by: https://github.com/nrfconnect/sdk-nrf/pull/4325

2021-04-22 10:24 UTC, tejlmand commented on west.yml
> +      revision: b0fc4807dafa31017efa14e6dfbaac032b45871a
This sha no longer points to latest in sdk-zephyr.

2021-04-23 11:49 UTC, rlubos commented
Manifest updated in other PR.

2021-04-23 11:49 UTC, closed without merging