applications: nrf_desktop: Increase BT ECC stack size
nrfconnect/sdk-nrf pull request #4330
Opened 2021-04-14 13:46 UTC by MarekPieta

Change increases BT ECC stack size to prevent stack overflows while pairing.

Jira: NCSDK-9106

2021-04-14 13:48 UTC, MarekPieta commented
@wiminordic, please verify if this fixes reported problem.

2021-04-14 13:55 UTC, MarekPieta commented
After the fix is confirmed to work well, I will update other affected configurations

2021-04-14 14:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4330
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-14 14:15 UTC, pdunaj approved these changes

2021-04-15 11:25 UTC, wiminordic commented
I confirm that this PR fixed the issue.

2021-04-15 11:29 UTC, MarekPieta commented
I increased stack size for all of the configurations (to ensure the issue will not occur). It seems like we fit (also on on nrf52810dmouse.

2021-04-15 12:27 UTC, pdunaj approved these changes

2021-04-15 12:56 UTC, emob-nordic approved these changes

2021-04-15 13:09 UTC, joerchan requested changes
ECC stack size shouldn't be affected by individual users, so if the value has changed it should be updated in Kconfig.

But why did it change?

2021-04-16 17:58 UTC, joerchan commented
Superseeded by https://github.com/nrfconnect/sdk-nrf/pull/4347

2021-04-16 17:58 UTC, closed without merging