doc: release-notes-latest: changes in FS, Flash from upmerge 20210305
nrfconnect/sdk-nrf pull request #4364
Opened 2021-04-20 13:45 UTC by nvlsianpu

Added notes on changes in flash driver, FS, stream_flash.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2021-04-20 14:06 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4364
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-04-20 14:21 UTC, de-nordic approved these changes
Left note, but generally I think this is OK.

2021-04-20 14:21 UTC, de-nordic commented on doc/nrf/releases/release-notes-latest.rst
> +      c:type:`fs_file_t` objects. Any :c:type:`fs_file_t` objects must now be
maybe "must be now (...)" -> "require initialization, by calling the function, prior to their first use."

2021-04-21 07:34 UTC, ru-fu requested changes
I'll add a commit.

2021-04-21 07:37 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
> +    * SoC embedded flash driver enabling imposes selection of
I'll remove this one - it is covered by https://github.com/nrfconnect/sdk-nrf/pull/4353/

2021-04-21 15:07 UTC, nvlsianpu commented
@ru-fu applied

2021-04-22 07:43 UTC, ru-fu approved these changes

2021-04-22 10:34 UTC, nvlsianpu commented
@mbolivar-nordic Can you tell why OSS history check fails on such a trivial patch?
https://github.com/nrfconnect/sdk-nrf/pull/4364/checks?check_run_id=2401682824

2021-04-22 11:06 UTC, nvlsianpu commented
^^ I think I forgot to rebase the patch.

2021-04-23 12:03 UTC, merged