doc/release-note: flash API & MCUboot notes
nrfconnect/sdk-nrf pull request #4505
Opened 2021-05-11 08:58 UTC by nvlsianpu

Added record on MCUboot changes and flash API
changes which was inherited within the last upmerge
#4370.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2021-05-11 09:01 UTC, nvlsianpu commented on doc/nrf/releases/release-notes-latest.rst
> +    * :c:func:`flash_write_protection_set()` has been deprecated and will be removed in
@ru-fu This is original zephyr record. It can be compressed.

2021-05-12 07:23 UTC, ru-fu requested changes
I'll add a commit.

2021-05-12 07:38 UTC, ru-fu commented on doc/nrf/releases/release-notes-latest.rst
Does the commit need to be updated?

2021-05-12 07:50 UTC, ru-fu commented
I added a commit - please check and squash, if okay.

2021-05-17 07:31 UTC, nvlsianpu commented
@ru-fu done.

2021-05-17 07:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4505
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-05-18 07:47 UTC, ru-fu approved these changes

2021-06-01 13:11 UTC, rlubos approved these changes

2021-06-01 13:12 UTC, merged