applications: machine_learning: Add release configurations
nrfconnect/sdk-nrf pull request #4563
Opened 2021-05-17 14:43 UTC by MarekPieta

Change introduces ZRelease configurations.

Jira: NCSDK-9608

2021-05-17 14:56 UTC, pdunaj approved these changes

2021-05-17 15:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4563
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-05-18 06:42 UTC, emob-nordic requested changes

2021-05-18 06:42 UTC, emob-nordic commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/hci_rpmsg_ZRelease.conf
> +CONFIG_EXCEPTION_STACK_TRACE=y
I think this could be dropped, or not?

2021-05-18 09:14 UTC, MarekPieta commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/hci_rpmsg_ZRelease.conf
> +CONFIG_EXCEPTION_STACK_TRACE=y
Ok, removed

2021-05-18 09:25 UTC, emob-nordic approved these changes

2021-05-18 12:00 UTC, MarekPieta commented
Fixed merge conflicts

2021-05-18 15:08 UTC, merged