applications: pelion_client: handle suspend removed
nrfconnect/sdk-nrf pull request #4603
Opened 2021-05-21 09:30 UTC by emob-nordic

Jira: NCSDK-9157

2021-05-21 09:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4603
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-01 09:59 UTC, emob-nordic commented
Rebased after upmerge.

2021-06-01 13:00 UTC, pdunaj requested changes
One small thing - please also add explicit state at https://github.com/nrfconnect/sdk-nrf/blob/master/applications/pelion_client/src/modules/pelion.cpp#L176

2021-06-01 14:04 UTC, pdunaj approved these changes

2021-06-01 14:24 UTC, pdunaj commented
maybe rebase will help...

2021-06-02 07:58 UTC, rakons approved these changes

2021-06-02 09:41 UTC, merged