samples: connectedhomeip: fix hangs on sys_rand32_get()
nrfconnect/sdk-nrf pull request #4616
Opened 2021-05-24 15:06 UTC by Damian-Nordic

There is a known issue in the cryptocell library causing
that an application may hang on a call to sys_rand32_get()
or underlying functions. The issue is supposed to be fixed
in the next cryptocell library version, but for now provide
a workaround using the non-cryptographically secure
Xoroshiro algorithm for random number generation.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

2021-05-24 15:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4616
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-05-25 06:09 UTC, kkasperczyk-no approved these changes
LGTM, do we need also changes in the upstream Matter repo?

2021-05-25 07:24 UTC, doublemis1 approved these changes

2021-05-25 07:26 UTC, Damian-Nordic commented
> LGTM, do we need also changes in the upstream Matter repo?

I think for some reason it didn't occur in the upstream repo, but maybe we will need to apply the changes once we bump the NCS revision in the upstream.

2021-05-27 15:15 UTC, rlubos requested changes
Need to put the files into `samples/matter/*` now

2021-05-27 21:30 UTC, LuDuda approved these changes

2021-05-28 06:58 UTC, rlubos approved these changes

2021-05-31 09:08 UTC, merged