net: lib: Introduce socket timeouts in AWS IoT and Azure IoT backends
nrfconnect/sdk-nrf pull request #4683
Opened 2021-05-31 13:31 UTC by simensrostad

Prevent send from blocking indefinitely by introducing Kconfig options
to set socket timeouts in AWS IoT and Azure IoT Hub cloud backends.

Closes CIA-323

2021-05-31 13:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4683
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-05-31 13:58 UTC, coderbyheart approved these changes

2021-06-01 08:19 UTC, jtguggedal requested changes
The timeout changes look good.
I think this should be three commits:

1. AWS IoT: Changes to connection establishment
2. AWS IoT: Add socket timeout
3. Azure IoT Hub: Add socket timeout

2021-06-01 08:19 UTC, jtguggedal commented on subsys/net/lib/aws_iot/Kconfig
> +	  use AWS_IOT_TIMEOUT_SEC.
`AWS_IOT_TIMEOUT_SEC` --> `AWS_IOT_SEND_TIMEOUT_SEC`

2021-06-01 08:19 UTC, jtguggedal commented on subsys/net/lib/aws_iot/src/aws_iot.c
> +		LOG_ERR("mqtt_connect, error: %d", err);
Hm, this is in reality the return code from `connect_error_translate`, which is different from the one returned by `mqtt_connect`. I think we should print the return code from `mqtt_connect` too for debugging. And wrap the translation in an `if (err) { ... }` and do it only if `mqtt_connect` fails

2021-06-01 08:19 UTC, jtguggedal commented on subsys/net/lib/aws_iot/src/aws_iot.c
> +	err = connect_client(NULL);
I think the changes to how the connection is established should be in a separate commit

2021-06-01 08:19 UTC, jtguggedal commented on subsys/net/lib/aws_iot/src/aws_iot.c
> +	LOG_DBG("AWS IoT broker connection request sent.");
Punctuation is usually not ues in log messages

2021-06-01 08:19 UTC, jtguggedal commented on subsys/net/lib/azure_iot_hub/Kconfig
> +	  use AZURE_IOT_HUB_TIMEOUT_SEC.
`AZURE_IOT_HUB_TIMEOUT_SEC` --> `AZURE_IOT_HUB_SEND_TIMEOUT_SEC`

2021-06-01 11:15 UTC, simensrostad commented
@jtguggedal Addressed comments and split PR into three commits.

2021-06-01 11:23 UTC, rlubos approved these changes

2021-06-01 11:49 UTC, jtguggedal approved these changes
Looks good, thanks

2021-06-02 08:20 UTC, merged