manifest: update sdk-zephyr revision
nrfconnect/sdk-nrf pull request #4684
Opened 2021-05-31 14:09 UTC by andvib

Update sdk-zephyr revision to include PSA Protected Storage sample

sdk-zephyr PR: https://github.com/nrfconnect/sdk-zephyr/pull/531

2021-05-31 14:17 UTC, ioannisg requested changes
Can you , instead use pull/`PR-number`/head?

2021-05-31 14:17 UTC, ioannisg commented on west.yml
> +      revision: 9532d853e64d13f50d51a5fbe4a5464376ac24d3
pull/531/head, should be :)

2021-05-31 14:21 UTC, andvib commented on west.yml
> +      revision: 9532d853e64d13f50d51a5fbe4a5464376ac24d3
Ah, my bad - updated!

2021-05-31 14:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4684
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-01 13:27 UTC, ioannisg approved these changes

2021-06-01 13:41 UTC, oyvindronningstad approved these changes

2021-06-01 13:44 UTC, magnev approved these changes

2021-06-01 21:08 UTC, merged