doc: zigbee: update ncp sample docs
nrfconnect/sdk-nrf pull request #4721
Opened 2021-06-02 13:53 UTC by greg-fer

Replaced mentions of network coordinator.
Now the docs mention the simple gateway.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2021-06-02 14:13 UTC, jangalda approved these changes

2021-06-02 14:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4721
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-02 14:24 UTC, sebastiandraus approved these changes

2021-06-07 09:09 UTC, totyz requested changes

2021-06-07 09:09 UTC, totyz commented on samples/zigbee/ncp/README.rst
> +The simple gateway device joins the Zigbee network and searches for a light bulb to control.
The simple gateway forms Zigbee network, not joins.

Better sentences would be:
"simple gateway device forms Zigbee network and opens the network for 180s for new devices. When light bulb joins, the LED 3 on the light bulb device turns on to indicate that it is connected to the simple gateway. The gateway then starts discovering On/Off cluster. If it is found, Simple gateway configures bindings and reporting for the device and
then it starts sending On/Off toggle commands with a 15-sec period that toggle the LED 4 on the light bulb on and off"

or something like that

2021-06-07 14:36 UTC, tomchy submitted a review, later dismissed
As written by Tomasz, the simple gateway does not join, but form a Zigbee network.

2021-06-08 10:29 UTC, totyz approved these changes

2021-06-08 14:31 UTC, nvlsianpu approved these changes

2021-06-08 14:36 UTC, merged