tfm_hello_world: Remove TFM_MINIMAL so the services are available
nrfconnect/sdk-nrf pull request #4795
Opened 2021-06-10 14:15 UTC by oyvindronningstad

Both platform_read and psa_crypto failed.

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

2021-06-10 14:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4795
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-10 16:23 UTC, hakonfam commented
It works fine on the current master to me:

![image](https://user-images.githubusercontent.com/1547348/121561248-9bfce480-ca18-11eb-94ef-6837eca73895.png)

2021-06-11 06:16 UTC, hakonfam requested changes
NACK since the issue being fixed only occurs on non-supported toolchain.

2021-06-11 08:20 UTC, oyvindronningstad commented
Does not happen for default setup.

2021-06-11 08:20 UTC, closed without merging