labeler.yml: Don't apply CI-all-test for west.yml
nrfconnect/sdk-nrf pull request #4797
Opened 2021-06-10 14:26 UTC by oyvindronningstad

The author should instead apply the right labels, since most updates
don't concern the whole tree.

Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

2021-06-10 14:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4797
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-11 08:05 UTC, thst-nordic approved these changes

2021-06-11 08:40 UTC, ioannisg commented
I think that's probably OK, but it should come with some documentation in the contribution guidelines, stressing what the author needs to do.

2021-06-11 08:49 UTC, tejlmand requested changes
> The author should instead apply the right labels, since most updates
don't concern the whole tree.

I strongly disagree.
Today we have this principle in sdk-nrf, and people forget to add  the right testing labels there.
For example they make changes to Bluetooth code, and forget to apply `ci-ble-test`.

If they cannot do this in sdk-nrf, I disapprove having the same for `west.yml`.

People can still remove the `ci-all-test` label and then add specific labels for the tests they actually need.need.

2021-06-11 08:53 UTC, tejlmand commented
As code owners we already spend a lot of time on investigating CI issues during release work, and i'm afraid this will become even worse if manifest PRs are not tested per default as more PRs may be merged that actually breaks CI, but that will not be detected until someone having a PR with that test label, and thus we'll need to spend even more time chasing down from where that error originated.

And the PR that failed will be blocked, even though that PR had nothing to do with the failure.

2021-06-11 09:11 UTC, lemrey commented
It's just taxing for authors to remove and reapply the appropriate labels every time they push a commit (after waiting for the bot to trigger). This can happen easily several times for each PR, and it would be much less work to let the author apply the proper labels, once and for all, and let the code-owner make sure of that before the PR is merged.

In the end, the code-owners are the one who merge PRs and they should accept the responsibility to make sure the correct labels are applied.

2021-06-11 09:26 UTC, tejlmand commented
> In the end, the code-owners are the one who merge PRs and they should accept the responsibility to make sure the correct labels are applied.

No, that's the responsibility of the author, unless code owners should start to only merge PRs where they have domain knowledge.
But in that case, you might need to wait longer time before getting things merged.

As I said, as long as people don't apply labels at `sdk-nrf` then I don't like to extend that scheme to manifest updates.
For example, why was this not testing anything:
https://github.com/nrfconnect/sdk-nrf/pull/4787

2021-06-11 09:27 UTC, tejlmand commented
> It's just taxing for authors to remove and reapply the appropriate labels every time they push a commit (after waiting for the bot to trigger)

Now, that would be a matter of asking the action to only apply the labels when the PR is opened.
Which is very different from what this PR suggests.

2021-06-11 09:42 UTC, lemrey commented
Having the bot trigger once instead of every push would be good enough for me.

2021-06-11 09:56 UTC, oyvindronningstad commented
Question, since the labeler and CI are triggered at the same time, I assume you only have a short window of time to change the labels before CI reads them, how long is that window. @thst-nordic do you know?

2021-06-11 10:00 UTC, thst-nordic commented
~20min   
this is how long it takes to run all the twister targets and build all the samples/apps.

2021-06-11 10:01 UTC, oyvindronningstad commented
Idea: Can we make https://github.com/zephyrproject-rtos/action-manifest apply the right CI labels? It already parses the manifest for the changed modules, and already applies labels (DNM++). @carlescufi @thst-nordic?

2021-06-11 10:35 UTC, oyvindronningstad commented
> 
> 
> Idea: Can we make https://github.com/zephyrproject-rtos/action-manifest apply the right CI labels? It already parses the manifest for the changed modules, and already applies labels (DNM++). @carlescufi @thst-nordic?

AFAICT, we would need to

1. Add a label-suffix, analogous to label-prefix
2. Change the relevant CI labes to match the module names from the manifests. If we also change the labels to remove "-test", we don't need 1.

cc @mbolivar-nordic

2021-06-11 16:15 UTC, mbolivar-nordic commented
@oyvindronningstad 

> Idea: Can we make https://github.com/zephyrproject-rtos/action-manifest apply the right CI labels?

Probably

> AFAICT, we would need to

I'm sorry, I'm having trouble understanding your shorthands. I looked at all the existing labels and I'm not sure how to apply your suggestion to them though.

Could you give an example, e.g. of what you want to happen when someone changes the find my repository in west.yml?

I assume we also want to run tests on everything if zephyr changes.

2021-06-13 12:36 UTC, oyvindronningstad commented
@mbolivar-nordic

>Could you give an example, e.g. of what you want to happen when someone changes the find my repository in west.yml?

It applies the CI-find-my-test label.

>I assume we also want to run tests on everything if zephyr changes.

I agree

I created a quick PR that does something like this:
https://github.com/zephyrproject-rtos/action-manifest/pull/2
nrf: https://github.com/nrfconnect/sdk-nrf/pull/4817

2021-06-14 14:33 UTC, mbolivar-nordic commented
> I created a quick PR that does something like this:

The approach seems sound to me.

2021-06-23 08:41 UTC, oyvindronningstad commented
Superseded by #4817

2021-06-23 08:41 UTC, closed without merging