applications: serial_lte_modem: xsleep doc note
nrfconnect/sdk-nrf pull request #4822
Opened 2021-06-14 10:57 UTC by martiles

Adding a note to disable UART2 when doing power
measurements on the nRF9160.

Signed-off-by: Martin Lesund <martin.lesund@nordicsemi.no>

2021-06-14 11:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4822
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-14 12:02 UTC, peknis requested changes

2021-06-14 12:02 UTC, peknis commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +If you are going to do power measurements on the nRF9160 DK while running the SLM application it is recommended to disable peripherals that are not in use.
```suggestion
If you are going to do power measurements on the nRF9160 DK while running the SLM application, it is recommended to disable unused peripherals.
```

2021-06-14 12:02 UTC, peknis commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +By default UART2 is enabled in the ``nrf9160dk_nrf9160ns.overlay`` so disable the UART2 by switching the status.
```suggestion
By default, UART2 is enabled in the :file:`nrf9160dk_nrf9160ns.overlay` file so disable the UART2 by switching the status.
```

2021-06-14 12:02 UTC, peknis commented on applications/serial_lte_modem/doc/Generic_AT_commands.rst
> +Change the line ``status = "okey"`` to ``status = "disabled"`` then save the ``nrf9160dk_nrf9160ns.overlay`` file to make sure you will get the expected power consumption numbers when doing the measu
```suggestion
Change the line ``status = "okay"`` to ``status = "disabled"`` and save the :file:`nrf9160dk_nrf9160ns.overlay` file to make sure you get the expected power consumption numbers when doing the measurements.
```

2021-06-15 09:19 UTC, peknis approved these changes

2021-06-15 22:21 UTC, lats1980 approved these changes
Looks good!

2021-06-25 00:20 UTC, junqingzou approved these changes

2021-06-25 08:30 UTC, rlubos approved these changes

2021-06-25 08:30 UTC, merged