applications: asset_tracker_v2: add help to PVT/NMEA choice
nrfconnect/sdk-nrf pull request #4836
Opened 2021-06-14 16:12 UTC by coderbyheart

This adds a help text to clarify what the options mean.

Signed-off-by: Markus Tacker <markus.tacker@nordicsemi.no>

2021-06-14 16:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4836
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-15 06:39 UTC, simensrostad requested changes

2021-06-15 06:39 UTC, simensrostad commented on applications/asset_tracker_v2/src/modules/Kconfig.gps_module
> +	  The GPS data will be send as a struct in the update.
```suggestion
	  The GPS data will be included as a struct in the GPS_EVT_DATA_READY event propagated by this module upon a fix.
```

2021-06-15 06:39 UTC, simensrostad commented on applications/asset_tracker_v2/src/modules/Kconfig.gps_module
> +	  The GPS data will be send as a string in the update.
```suggestion
	  The GPS data will be included as a string in the GPS_EVT_DATA_READY event.
```

2021-06-15 12:03 UTC, simensrostad approved these changes

2021-06-16 14:02 UTC, tejlmand approved these changes

2021-10-21 09:40 UTC, coderbyheart commented
Rebased.

2021-11-30 09:11 UTC, coderbyheart commented
Could someone merge this?

2021-11-30 13:19 UTC, merged