doc: nrf: update documentation build instructions
nrfconnect/sdk-nrf pull request #4878
Opened 2021-06-16 08:58 UTC by gmarull

Update the documentation build instructions with all the latest
features. Some steps have been simplified and some tips removed since
they are not relevant anymore.

2021-06-16 09:22 UTC, carlescufi requested changes
Thanks! Some comments

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +Currently, there are following docsets:
```suggestion
Currently, there are the following docsets:
```

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +Building the documentation output requires building output for all docsets.
```suggestion
Building the documentation output requires building the output for all docsets.
```

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +Since there are links from the NCS documentation set into other documentation sets,
"documentation set" or "docset" but let's keep it consistent.

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +   ninja ${DOCSET}-html-all
We usually use the following format:

```
ninja <docset name>-html-all
```

otherwise it looks like it's a real env var

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +where ``${DOCSET}`` is the docset name, e.g. ``nrf``.
see above

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +   ninja ${DOCSET}
see above

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +This target will only invoke the build for the ``${DOCSET}``, assuming all of its dependencies are available.
see above

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +This mechanism can sometimes cause problems such as navigation not being updated correctly.
```suggestion
This mechanism can sometimes cause issues such as navigation not being updated correctly.
```

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +If you experience any of such problems, clean the build folders before you run the documentation build.
```suggestion
If you experience any of such issues, clean the build folders before you run the documentation build.
```

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +   ninja ${DOCSET}-clean
see above

2021-06-16 09:22 UTC, carlescufi commented on doc/nrf/doc_build.rst
> +where ``${DOCSET}`` is the docset name, e.g. ``nrf``.
see above

2021-06-16 09:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4878
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-18 10:31 UTC, umapraseeda approved these changes

2021-06-18 10:34 UTC, carlescufi approved these changes

2021-06-18 10:34 UTC, merged