doc: iot release notes additions
nrfconnect/sdk-nrf pull request #4893
Opened 2021-06-17 09:38 UTC by nordic-hani

Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>

2021-06-18 13:28 UTC, rlubos approved these changes

2021-06-18 13:29 UTC, peknis requested changes

2021-06-18 13:29 UTC, peknis commented on doc/nrf/releases/release-notes-latest.rst
> +  * :ref:`_sms_readme` updated to enable sending of sms and decoding of received SMS payload.
```suggestion
  * :ref:`sms_readme` updated to enable sending of sms and decoding of received SMS payload.
```

2021-06-21 05:10 UTC, tokangas approved these changes

2021-06-21 09:29 UTC, bjorn-tore-taraldsen approved these changes

2021-06-21 09:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4893
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-21 09:59 UTC, peknis approved these changes

2021-06-21 15:06 UTC, merged