Bluetooth: Mesh: Environmental sensors test
nrfconnect/sdk-nrf pull request #4898
Opened 2021-06-17 11:41 UTC by alxelax

Unit tests of supported environmental sensors.

Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

2021-06-17 12:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4898
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-17 12:41 UTC, ludvigsj requested changes

2021-06-17 12:42 UTC, ludvigsj commented on tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
> +			"Encoded value is not equal expected");
Perhaps print channel number here?

2021-06-17 13:49 UTC, ludvigsj approved these changes

2021-06-22 13:46 UTC, PavelVPV approved these changes

2021-06-25 14:40 UTC, trond-snekvik approved these changes

2021-06-26 09:49 UTC, merged