doc: known_issues: Add section about FMFU and newest J-Link
nrfconnect/sdk-nrf pull request #4906
Opened 2021-06-17 14:47 UTC by sigvartmh

There is an issue with the newer J-Link versions which causes the UART
communication to break when sending the modem firmware data using the
SMP protocol.

This affects every version of the FMFU SMP Server sample. Using J-Link
firmware on the debugger chip from 6.88a fixes this issue.

Ref. NCSDK-9441

Signed-off-by: Sigvart Hovland <sigvart.hovland@nordicsemi.no>

2021-06-17 15:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4906
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-18 04:49 UTC, sigvartmh commented on doc/nrf/known_issues.rst
> +  **Workaround:** Downgrade the debugger chip to the firmware released with J-Link 6.88a or use another way of transferring serial data to chip.
```suggestion
  **Workaround:** Downgrade the debugger chip to the firmware released with J-Link 6.88a or use another way of transferring serial data to the chip.

2021-06-18 05:30 UTC, peknis requested changes

2021-06-18 05:30 UTC, peknis commented on doc/nrf/known_issues.rst
> +  Full modem serial update does not work on development kit with debugger chip version chipped with J-Link software > 6.88a
```suggestion
  Full modem serial update does not work on development kit with debugger chip version delivered with J-Link software > 6.88a
```

2021-06-18 10:08 UTC, peknis approved these changes

2021-06-18 15:12 UTC, ioannisg approved these changes

2021-06-18 19:04 UTC, merged