doc: Update versions for NCS 1.6 release
nrfconnect/sdk-nrf pull request #4938
Opened 2021-06-18 14:53 UTC by umapraseeda

Update versions for NCS 1.6 release
ref: NCSDK-8843
manifest update for PR 505

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

2021-06-18 15:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4938
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-21 09:53 UTC, tejlmand approved these changes

2021-06-21 22:37 UTC, b-gent approved these changes

2021-06-22 07:08 UTC, greg-fer approved these changes

2021-06-23 08:12 UTC, shantha-14 approved these changes

2021-06-23 09:46 UTC, ioannisg approved these changes

2021-06-23 10:08 UTC, shantha-14 reviewed
revoking my approval. Need some discussion

2021-06-23 10:10 UTC, shantha-14 requested changes
Need some discussion for mcuboot.

2021-06-23 12:43 UTC, shantha-14 approved these changes
discussed and agreed versions are correct.

2021-06-24 12:09 UTC, merged