samples: peripheral: lpuart: Reduce power consumption for nrf9160dk
nrfconnect/sdk-nrf pull request #4947
Opened 2021-06-21 07:40 UTC by nordic-krch

On nrf9160dk >=0.15.0 it is required to initilize the modem to get
lowest possible power consumption. Converting low power uart sample
to use nrf9160dk_nrf9160ns target with modem library enabled.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2021-06-21 07:42 UTC, lemrey commented on samples/peripheral/lpuart/boards/nrf9160dk_nrf9160ns.conf
> +CONFIG_HEAP_MEM_POOL_SIZE=32768
This is leftover?

2021-06-21 08:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4947
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-21 08:51 UTC, nordic-krch commented on samples/peripheral/lpuart/boards/nrf9160dk_nrf9160ns.conf
> +CONFIG_HEAP_MEM_POOL_SIZE=32768
this, only this is needed

2021-06-21 09:24 UTC, lemrey approved these changes
Thanks

2021-06-22 07:08 UTC, anangl commented on samples/peripheral/lpuart/boards/nrf9160dk_nrf9160ns.overlay
> +	status = "ok";
```suggestion
	status = "okay";
```
The "ok" form is deprecated.

2021-07-06 05:16 UTC, nordic-krch commented on samples/peripheral/lpuart/boards/nrf9160dk_nrf9160ns.overlay
> +	status = "ok";
fixed

2021-07-06 06:47 UTC, anangl requested changes

2021-07-06 06:47 UTC, anangl commented on samples/peripheral/lpuart/sample.yaml
> +    platform_allow: nrf52dk_nrf52832 nrf52833dk_nrf52833 nrf52840dk_nrf52840 nrf9160dk_nrf9160ns
Please update also documentation, it still says that the target for nRF9160 DK is `nrf9160dk_nrf9160`: https://github.com/nrfconnect/sdk-nrf/blob/e3716141c15d37f743bee03a025a2b5505288c32/samples/peripheral/lpuart/README.rst#L25

2021-09-30 01:34 UTC, closed without merging