doc: Release notes for SDC
nrfconnect/sdk-nrf pull request #4961
Opened 2021-06-21 16:42 UTC by seko-nordic

Top level release notes for SoftDevice Controller part in NCS v1.6.0.

Signed-off-by: Korotkov, Sergey <sergey.korotkov@nordicsemi.no>

2021-06-21 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4961) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=4961) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=4961) it.</sub>

2021-06-21 17:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-4961
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-21 18:07 UTC, rugeGerritsen commented on doc/nrf/releases/release-notes-latest.rst
> +* Added radio front-end module (FEM) support.
```suggestion
* Added radio front-end module (FEM) support (nRF52 Series only).
```

2021-06-21 18:09 UTC, rugeGerritsen requested changes
FEM is only supported on nRF52 Series devices

2021-06-21 22:29 UTC, b-gent commented on doc/nrf/releases/release-notes-latest.rst
> +* Added radio front-end module (FEM) support.
done

2021-06-21 22:31 UTC, b-gent approved these changes

2021-06-22 05:46 UTC, wiba-nordic approved these changes

2021-06-22 08:54 UTC, rugeGerritsen approved these changes

2021-06-22 10:04 UTC, merged