Doc updates after 1.6.0
nrfconnect/sdk-nrf pull request #5001
Opened 2021-06-25 13:11 UTC by b-gent

2021-06-25 13:26 UTC, shantha-14 requested changes
scripts/tools have to be updated.

2021-06-25 13:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5001
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-07-01 05:56 UTC, greg-fer approved these changes

2021-07-05 09:30 UTC, shantha-14 approved these changes

2021-07-05 10:58 UTC, rlubos approved these changes

2021-07-05 14:17 UTC, merged