DTM and radio test build empty_app_core sample by default as child image.
nrfconnect/sdk-nrf pull request #5015
Opened 2021-06-28 11:27 UTC by KAGA164

This PR adds possibility to build empty_app_core by default for the Direct Test Mode sample and the Radio Test sample

2021-06-28 11:50 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5015
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-28 12:30 UTC, peknis requested changes

2021-06-28 12:30 UTC, peknis commented on samples/bluetooth/direct_test_mode/README.rst
> +   If you want to program another sample for the application core, you must unset :option:'CONFIG_NCS_SAMPLE_EMPTY_APP_CORE_CHILD_IMAGE'.
```suggestion
   The :ref:`nrf5340_empty_app_core` is built and programmed automatically by default.
   If you want to program another sample for the application core, unset the :option:'CONFIG_NCS_SAMPLE_EMPTY_APP_CORE_CHILD_IMAGE' option.
```

2021-06-28 12:30 UTC, peknis commented on samples/peripheral/radio_test/README.rst
> +   If you want to program another sample for the application core, you must unset :option:'CONFIG_NCS_SAMPLE_EMPTY_APP_CORE_CHILD_IMAGE'.
Needs same fixes as above.

2021-06-29 10:43 UTC, qung approved these changes

2021-06-29 14:20 UTC, kapi-no approved these changes

2021-06-30 07:32 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/README.rst
> +   If you want to program another sample for the application core, you must unset :option:'CONFIG_NCS_SAMPLE_EMPTY_APP_CORE_CHILD_IMAGE'.
Done

2021-06-30 07:32 UTC, KAGA164 commented on samples/peripheral/radio_test/README.rst
> +   If you want to program another sample for the application core, you must unset :option:'CONFIG_NCS_SAMPLE_EMPTY_APP_CORE_CHILD_IMAGE'.
Fixed

2021-06-30 07:35 UTC, peknis approved these changes

2021-06-30 11:59 UTC, grochu approved these changes

2021-07-01 08:45 UTC, merged