doc: zigbee: clarify zigbee def handler docs
nrfconnect/sdk-nrf pull request #5041
Opened 2021-06-30 10:49 UTC by greg-fer

Improved documentation of application utilities.
Moved sections around, added additional info.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2021-06-30 10:49 UTC, greg-fer commented
TODO: Add links to signals in ZBOSS.

2021-06-30 11:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5041
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-30 11:14 UTC, sebastiandraus commented on include/zigbee/zigbee_app_utils.rst
> +For example, for a device that initiates the F&B procedure, extend ``zboss_signal_handler`` with a switch case statement for ``ZB_BDB_SIGNAL_FINDING_AND_BINDING_INITIATOR_FINISHED``:
Do we want to change \`\`zboss_signal_handler\`\` to \`zboss_signal_handler()\`_ here and in other occurencies?

2021-06-30 11:14 UTC, sebastiandraus commented on include/zigbee/zigbee_app_utils.rst
> +The following sections describe the logic implemented inside s:c:func:`zigbee_default_signal_handler`.
Typo?
```suggestion
The following sections describe the logic implemented inside :c:func:`zigbee_default_signal_handler`.
```

2021-06-30 14:32 UTC, sebastiandraus requested changes

2021-06-30 14:32 UTC, sebastiandraus commented on doc/nrf/links.txt
> +.. _`ZB_BDB_SIGNAL_STEERING`: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/zboss/3.6.0.0/group__zb__comm__signals.html#ga25a801841c95d6daddb9c60b39542b13v
Incorrect link
```suggestion
.. _`ZB_BDB_SIGNAL_STEERING`: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/zboss/3.6.0.0/group__zb__comm__signals.html#ga25a801841c95d6daddb9c60b39542b13
```

2021-07-01 08:49 UTC, rlubos approved these changes

2021-07-01 08:58 UTC, sebastiandraus approved these changes
LGTM

2021-07-01 09:02 UTC, tomchy approved these changes

2021-07-01 09:30 UTC, merged