samples: openthread: enable USB transport for CLI sample
nrfconnect/sdk-nrf pull request #5043
Opened 2021-06-30 11:32 UTC by lmaciejonczyk

Add new overlay configuration file which enables USB transport for the CLI
sample. Extend Thread CLI sample support for nrf52840 dongle.

Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>

2021-06-30 11:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5043
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-06-30 13:03 UTC, rlubos approved these changes

2021-06-30 13:40 UTC, edmont reviewed
Should we also update our docs on how to flash the dongle? Since `west flash` won't handle it. Maybe just a link to here: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/boards/arm/nrf52840dongle_nrf52840/doc/index.html

2021-06-30 13:40 UTC, edmont commented on samples/openthread/cli/README.rst
> +   :rows: nrf5340dk_nrf5340_cpuapp, nrf52840dk_nrf52840, nrf52840dongle_nrf52840, nrf52833dk_nrf52833, nrf21540dk_nrf52840
Should we add it here as well? https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/app_boards.html?highlight=nrf52840dongle_nrf52840#boards-included-in-sdk-nrf

2021-06-30 13:40 UTC, edmont commented on samples/openthread/cli/overlay-usb.conf
> +CONFIG_USB_DEVICE_PRODUCT="Thread Cli"
```suggestion
CONFIG_USB_DEVICE_PRODUCT="Thread CLI"
```

2021-07-01 07:36 UTC, lmaciejonczyk commented
> Should we also update our docs on how to flash the dongle? Since `west flash` won't handle it. Maybe just a link to here: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/boards/arm/nrf52840dongle_nrf52840/doc/index.html

I agree. What more It looks this is a missing part also for other samples which support nRF52840 dongle as well. I think It should be done as general fix, maybe in `gs_programming.rst`?

2021-07-01 14:10 UTC, ru-fu requested changes
I'll add a commit.

2021-07-01 14:29 UTC, ru-fu commented
I added two commits now - one for the language review and one to add a note to the programming instructions.

2021-07-01 14:31 UTC, edmont approved these changes
LGTM now.

@ru-fu do you mind squashing the language review commit?

2021-07-01 14:40 UTC, ru-fu approved these changes
Squashed and rebased.

2021-07-01 16:59 UTC, merged