doc: updating style guide
nrfconnect/sdk-nrf pull request #5074
Opened 2021-07-06 11:20 UTC by wiba-nordic

NCSDK-9708

Improve readability, remove extraneous examples

Some matters were moved over to the cheat sheet.

Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>

2021-07-06 11:33 UTC, wiba-nordic commented on doc/nrf/doc_styleguide.rst
>     Describe the condition for each of the return values (for example, "If the function completes successfully", "If the connection cannot be established").
I think these two, and the bullet point following these (lines 481-501/251-271), could be combined to one bullet point how to format the return, with the current ``@return`` and ``@retval`` as sub-bullets for it.

2021-07-06 11:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5074
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-07-06 12:53 UTC, peknis requested changes

2021-07-06 12:53 UTC, peknis commented on doc/nrf/doc_styleguide.rst
> +Each link should be defined only once in :file:`links.txt`, so if you are adding a new link, make sure it hasn't already been added.
```suggestion
Each link should be defined only once in :file:`links.txt`, so if you are adding a new link, make sure it has not already been added.
```

2021-07-06 12:53 UTC, peknis commented on doc/nrf/doc_styleguide.rst
> +The `Breathe documentation`_ contains information about what you can link to.
You might want to say something about the example below.

2021-07-13 12:06 UTC, greg-fer approved these changes

2021-07-13 12:19 UTC, peknis approved these changes

2021-07-14 10:05 UTC, peknis requested changes

2021-07-14 10:05 UTC, peknis commented on doc/nrf/doc_styleguide.rst
> +#. Do not user ``@returns``, use ``return`` or ``retval`` instead.
This needs a blank line before the bullet.

2021-07-14 10:36 UTC, peknis approved these changes

2021-07-20 13:01 UTC, merged