doc: Update sphinx nrfxlib config for Mathjax
nrfconnect/sdk-nrf pull request #5096
Opened 2021-07-09 07:59 UTC by weeTike

Adds the ability to use the Mathjax library for latex expressions in the :math: tag in rst files in nrfxlib documentation.

Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>

2021-07-09 08:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5096
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-07-09 14:32 UTC, gmarull requested changes
The default settings already load MathJax from jsdelivr: https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax_path, so why override that?
I also think that the extension needs to be enabled if needed, I don't see any formulae in this PR.

2021-07-09 14:55 UTC, weeTike commented
Ah, you are right, i did not realise there was a default. I have removed it.
Mathjax will be needed for some upcoming documentation which will be added with an SDC update soon.

2021-07-09 15:20 UTC, gmarull commented
> Ah, you are right, i did not realise there was a default. I have removed it.
> Mathjax will be needed for some upcoming documentation which will be added with an SDC update soon.

Let's wait until needed, then.

2021-08-17 14:26 UTC, carlescufi commented
Closing this for now

2021-08-17 14:26 UTC, closed without merging