doc: improve details around tagging CMakeLists.txt
nrfconnect/sdk-nrf pull request #5192
Opened 2021-07-27 11:29 UTC by Avalei

ref: NCSDK-9941

Explain tagging is already done for sdk-nrf sample applications, but not
for Zephyr or other repo applications

Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>

2021-07-27 11:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5192
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-07-27 11:55 UTC, FrancescoSer approved these changes

2021-07-27 11:57 UTC, peknis requested changes

2021-07-27 11:57 UTC, peknis commented on doc/nrf/gs_modifying.rst
> +The :file:`CMakeLists.txt` files for the sample applications in :file:`sdk-nrf` already have the required tags.
```suggestion
The :file:`CMakeLists.txt` files for the sample applications in the :file:`sdk-nrf` repository already have the required tags.
```

2021-07-27 11:57 UTC, peknis commented on doc/nrf/gs_modifying.rst
> +Projects in :file:`sdk-nrf` already have these tags, but projects from Zephyr and other repos do not.
```suggestion
Projects in the :file:`sdk-nrf` repository already have these tags, but projects from Zephyr and other repositories do not.
```

2021-07-27 11:57 UTC, peknis commented on doc/nrf/gs_modifying.rst
> +Follow the steps in :ref:`ses_tags_in_CMakeLists` to manually add tags when using :file:`CMakeLists.txt` files that are not located in the :file:`sdk-nrf` repo.
```suggestion
Follow the steps in :ref:`ses_tags_in_CMakeLists` to manually add tags when using :file:`CMakeLists.txt` files that are not located in the :file:`sdk-nrf` repository.
```

2021-07-27 11:57 UTC, peknis commented on doc/nrf/gs_modifying.rst
> +:file:`CMakeLists.txt` files must be tagged properly before they can be added to a project in SES.
```suggestion
You must tag the :file:`CMakeLists.txt` files properly before adding them to a project in SES.
```

2021-07-28 04:57 UTC, peknis approved these changes

2021-07-28 07:15 UTC, crfosse approved these changes

2021-07-28 08:43 UTC, carlescufi approved these changes

2021-07-28 08:43 UTC, carlescufi commented
@Avalei please rebase

2021-07-28 10:44 UTC, Avalei commented
@carlescufi Rebased and pushed again.

2021-07-28 12:24 UTC, merged