application: serial_lte_modem: Extend RX buffer size for datamode
nrfconnect/sdk-nrf pull request #5204
Opened 2021-07-29 05:12 UTC by junqingzou

Use full size of at_buf for datamode UART RX. This is to reduce the
possibility of buffer overflow, for which HWFC is initiated by SLM
and could lead to byte loss.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2021-07-29 05:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5204
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-07-29 12:09 UTC, FrancescoSer approved these changes

2021-07-29 12:21 UTC, rlubos requested changes
Looks good, just please squash the doc review commit.

2021-07-30 07:16 UTC, rlubos approved these changes

2021-07-30 07:17 UTC, merged