Bluetooth: Mesh: Refactor Light XYL and HSL Server models
nrfconnect/sdk-nrf pull request #5213
Opened 2021-07-30 11:05 UTC by michal-narajowski

When a node implements Light HSL Server and Light xyL Server located on
the same element, the Light xyL state and the Light HSL state are bound
indirectly via the Light Lightness Actual state.

The user has to add Lightness Server model to the composition data
separately and pass a pointer to HSL and XYL Server init macros.

Signed-off-by: Michał Narajowski <michal.narajowski@codecoup.pl>

2021-07-30 11:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5213
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-05 08:29 UTC, mia-ko requested changes
Just a tiny typo fix and a comma suggestion :) Otherwise ok.

2021-08-05 11:12 UTC, omkar3141 requested changes

2021-08-05 11:13 UTC, omkar3141 commented
Other than this, overall this looks ok to me.

2021-08-09 09:08 UTC, trond-snekvik reviewed
The init macros get a bit asymmetrical with this change. If we're turning the lightness server into a pointer, perhaps it makes sense to just turn the hue and saturation models into pointers as well? If we do, does it make sense to force the app developers to add these to the composition data too? 

This might not be better, but I wanted to have a bit of discussion anyway to make sure.

2021-08-10 08:53 UTC, michal-narajowski commented
@trond-snekvik To me, the asymmetry is justified because it reflects how the Lightness model is shared and Hue and Sat are not. But I'm not against changing the macros and passing a pointer to Hue/Sat. App developers have to add composition data entries for them anyway so I wouldn't worry about that.

2021-08-16 09:01 UTC, trond-snekvik approved these changes

2021-08-16 09:10 UTC, mia-ko approved these changes

2021-08-16 09:27 UTC, omkar3141 approved these changes

2021-08-16 13:54 UTC, PavelVPV approved these changes

2021-08-16 13:59 UTC, merged