samples: bluetooth: Add configuration for Thingy53 in mesh light switch sample
nrfconnect/sdk-nrf pull request #5222
Opened 2021-08-02 10:46 UTC by emob-nordic

Jira: NCSDK-10308.

Kconfig warnings during compilation discussed and accepted by @trond-snekvik .

2021-08-02 11:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5222
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-02 13:16 UTC, wiba-nordic requested changes
Just a little improvement to one sentence, otherwise looks good.

2021-08-03 07:31 UTC, emob-nordic commented on samples/bluetooth/mesh/light_switch/README.rst
> +Each instance of the Generic OnOff Client model are instantiated in the light switch sample, one for each button on the development kit that is available.
Done, please have a look once again if possible.

2021-08-03 09:52 UTC, wiba-nordic approved these changes
That looks good.

2021-08-03 10:02 UTC, pdunaj approved these changes

2021-08-03 10:30 UTC, emob-nordic commented on samples/bluetooth/mesh/light_switch/boards/thingy53_nrf5340_cpuapp.conf
> +CONFIG_MCUBOOT_IMAGE_VERSION="1.1.1+1"
Leftover after testing updates, will remove. Thanks!

2021-08-04 07:01 UTC, merged