docs: applications: add missing packages to documentation
nrfconnect/sdk-nrf pull request #5226
Opened 2021-08-03 13:43 UTC by zycz

add to documentation information what packeges have to be installed to
use led steam
Jira: NCSDK-10547

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2021-08-03 14:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5226
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-03 15:05 UTC, pdunaj approved these changes

2021-08-04 09:17 UTC, pdunaj approved these changes

2021-08-04 09:40 UTC, wiba-nordic approved these changes
Looks good!

2021-08-04 13:33 UTC, FrancescoSer approved these changes

2021-08-04 13:45 UTC, FrancescoSer approved these changes

2021-08-05 06:03 UTC, wiba-nordic requested changes

2021-08-05 06:03 UTC, wiba-nordic commented on scripts/hid_configurator/README.rst
> +From the user perspective, the nRF Desktop device is handled in the same way, regardless if it is connected to the host directly or through the nRF Desktop dongle.
```suggestion
From the user perspective, the nRF Desktop device is handled in the same way, regardless of it being connected to the host directly or through the nRF Desktop dongle.
```

2021-08-05 10:16 UTC, wiba-nordic approved these changes

2021-08-05 10:50 UTC, merged