subsys: esb: improve interrupt handling
nrfconnect/sdk-nrf pull request #5261
Opened 2021-08-10 11:27 UTC by maje-emb

Use ISR_DIRECT_DECLARE for esb ISRs, and ZERO_LATENCY_IRQS Kconfig
option for assuring fast IRQ handling.

NCSDK-10165

Signed-off-by: Marcin Jeliński <marcin.jelinski@nordicsemi.no>

2021-08-10 11:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5261
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-12 09:03 UTC, KAGA164 requested changes

2021-08-12 09:03 UTC, KAGA164 commented on subsys/esb/esb.c
> +	return 1;
Please add `ISR_DIRECT_PM();` before return

2021-08-12 10:28 UTC, maje-emb commented on subsys/esb/esb.c
>  	uint32_t interrupts;
Done for both `RADIO_IRQHandler` and `ESB_EVT_IRQHandler` functions.

2021-08-12 10:54 UTC, KAGA164 approved these changes
Looks good

2021-08-30 12:31 UTC, anangl approved these changes

2021-09-02 08:07 UTC, merged