doc: zigbee: expand default signal handler docs
nrfconnect/sdk-nrf pull request #5271
Opened 2021-08-11 11:40 UTC by greg-fer

Added new images to Zigbee default signal handler docs.
Applied minor style edits.
KRKNWK-10712.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2021-08-11 13:26 UTC, tomchy commented on include/zigbee/zigbee_app_utils.rst
> +  * Additionally for the end device, if :c:func:`stop_network_rejoin` is called with ``was_scheduled`` set to ``ZB_TRUE``, :c:func:`user_input_indicate` can restart the rejoin procedure.
This sentence is in the `Router rejoining network` section. If it is applicable for the router devices - I think the condition (`for the end device`) should be removed. If it is not - why it was not moved completely to the `End device rejoining network` section?

2021-08-11 13:26 UTC, tomchy commented on include/zigbee/zigbee_app_utils.rst
> +.. figure:: /images/zigbee_signal_handler_10_rejoin_end_device.svg
I think this figure needs to be improved: the `User action` is not part of a regular flow, meaning you do not check for user action after the whole rejoin procedure stops. This should be rather presented as an asynchronous event.

2021-08-11 13:26 UTC, tomchy commented on include/zigbee/zigbee_app_utils.rst
> +.. figure:: /images/zigbee_signal_handler_overview.svg
I do not understand this figure: so there are four options after the BDB initialization (new device scenario, commissioned device scenario, network joining, network formation) ?
Is not it that way, that the scenarios are enclosed inside the same block as the BDB initialization?

2021-08-11 13:26 UTC, tomchy commented on include/zigbee/zigbee_app_utils.rst
> +.. figure:: /images/zigbee_signal_handler_overview.svg
I'm not sure if I am a fan of arrows partially hidden behind boxes

2021-08-13 07:57 UTC, Avalei requested changes
doc/nrf/images/zigbee_signal_handler_10_rejoin.svg
- The "false" text has a white fill color.

doc/nrf/images/zigbee_signal_handler_10_rejoin_user_input.svg
- Since there is plenty of room, it would look more readable to have (eg. button press) all on one line). Keep all text in the box center aligned.

doc/nrf/images/zigbee_signal_handler_overview.svg
- Thinking about this some more, I wonder if we should have the Network start and Network leaving states in the lightest gray color with dark text so that it is not misinterpreted as being part of the Zigbee stack sleep routines.

2021-08-13 07:57 UTC, Avalei commented on include/zigbee/zigbee_app_utils.rst
> +The following sections describe the logic implemented inside :c:func:`zigbee_default_signal_handler` and correspond to the shapes on the figure.
```suggestion
The following sections describe the logic implemented inside :c:func:`zigbee_default_signal_handler` and correspond to the shapes in the figure.
```

2021-08-13 10:14 UTC, tomchy approved these changes

2021-08-13 12:12 UTC, sebastiandraus approved these changes

2021-08-16 09:15 UTC, Avalei approved these changes

2021-08-16 09:49 UTC, rlubos approved these changes

2021-08-16 09:49 UTC, merged