samples: matter: Fixed BLE advertising when not in pairing mode.
nrfconnect/sdk-nrf pull request #5286
Opened 2021-08-12 11:07 UTC by kkasperczyk-no

Currently for the Device Firmware Upgrade purposes nrfconnect
devices may advertise over BLE even with Thread enabled and not
in the pairing mode. However they should not advertise CHIPoBLE
service, but the one used for DFU (SMP).

* Added dfu_over_smp module handling performing DFU over BLE using
SMP protocol.
* Changed light_bulb config to start pairing mode autostart on boot,
as it is no longer forbidden by the spec.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2021-08-12 11:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5286
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-12 12:55 UTC, greg-fer requested changes
Two minor comments.

2021-08-12 12:55 UTC, greg-fer commented on samples/matter/light_bulb/README.rst
> +Before starting the commissioning procedure, the device must be discoverable over Bluetooth LE that starts automatically upon the device startup, but only for a predefined period of time (15 minutes
```suggestion
Before starting the commissioning procedure, the device must be made discoverable over Bluetooth LE, which starts automatically upon the device startup, but only for a predefined period of time (15 minutes by default).
```

2021-08-12 12:55 UTC, greg-fer commented on samples/matter/light_bulb/README.rst
> +If the Bluetooth LE advertising times out, you can re-enable pressing the **Button 4**.
```suggestion
If the Bluetooth LE advertising times out, you can re-enable it by pressing **Button 4**.
```

2021-08-12 12:59 UTC, greg-fer approved these changes

2021-08-13 10:50 UTC, Damian-Nordic approved these changes

2021-08-13 10:50 UTC, Damian-Nordic commented on doc/nrf/releases/release-notes-latest.rst
> +    Now if Matter pairing mode is not opened and the Bluetooth LE advertising is needed due to DFU requirements, the SMP service is advertised.
```suggestion
    Now if Matter pairing mode is not opened and the Bluetooth LE advertising is needed due to DFU requirements, only the SMP service is advertised.
```

2021-08-13 10:50 UTC, Damian-Nordic commented on samples/matter/weather_station/src/app_task.cpp
> +	sAppTask.PostEvent(&event);
We have a helper for that:

```suggestion
	sAppTask.PostEvent(AppEvent::Type::kStartSMPAdvertising, [](AppEvent *) { GetDFUOverSMP().StartBLEAdvertising(); });
```

2021-08-17 07:37 UTC, rlubos approved these changes

2021-08-17 07:37 UTC, merged