samples: matter: add support for nRF21540
nrfconnect/sdk-nrf pull request #5294
Opened 2021-08-13 14:13 UTC by LuDuda

This commit adds support for nRF21540 Front-End Module for Matter samples - nRF52 family.

Blocked by Zephyr's upmerge.

The change in the `sample_fem_support.txt` tries to reduce confusion due to the fact that this documentation is included in all Matter samples while nRF52833 is not supported by Matter. This is just an example anyway.

Signed-off-by: Lukasz Duda <lukasz.duda@nordicsemi.no>

2021-08-13 14:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5294
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-13 14:51 UTC, Damian-Nordic approved these changes

2021-08-16 10:24 UTC, greg-fer requested changes

2021-08-16 10:24 UTC, greg-fer commented on samples/matter/template/README.rst
> +FEM support
Are you sure you want to have such a long piece of documentation added to the template sample docs? I think that adding it here also requires changes to the Create a Matter accessory device guide, as we tell the user there to copy the template sample, so it is natural to ask how creating the accessory device impacts the FEM support.

2021-08-17 12:22 UTC, hubertmis commented on samples/matter/common/dts-nrf21540-fem.overlay
> +    nrf_radio_fem: nrf21540_fem {
Should other pins be configured as well? I mean MODE and SPI pins

2021-08-17 12:25 UTC, hubertmis commented
Please have a look at https://github.com/nrfconnect/sdk-nrf/pull/5263 . I think we should introduce nRF21540-EK to all samples in unified way, instead of creating devicetree overlays all over the repositories.

2021-08-17 13:42 UTC, greg-fer commented on samples/matter/template/README.rst
> +FEM support
After discussing this topic on Teams, I'm fine with adding this FEM support section to the template sample.

2021-08-17 13:49 UTC, greg-fer approved these changes
I approve the doc changes, because they match what we already did for other samples with FEM support in NCS.

However, I agree with @hubertmis that we need a solution that is more universal.
For example, a solution that replaces the fem_support.txt with a link to a guide to avoid bloating the documentation with the same section across all the samples. This change in my opinion should not happen in this PR, but in a separate PR, best candidate being #5263, which currently just adds new documentation without taking into account fem_support.txt or ug_radio_fem.rst.

2021-08-17 13:56 UTC, LuDuda commented
@hubertmis I also agree and already proposed to remove this overlay internally a few days ago, but encounter some different opinions. As support to the EK is not yet merged I didn't want to partially fix it for Matter. Let's make your proposed change as a follow-up PR. Thoughts?

2021-08-17 14:03 UTC, hubertmis commented
> As support to the EK is not yet merged I didn't want to partially fix it for Matter. Let's make your proposed change as a follow-up PR. Thoughts?

I would prefer to avoid introducing shield descriptions in samples. I'm checking if we can speed up merging #5263 to allow removing overlay and align documentation in #5294.

2021-08-17 14:19 UTC, greg-fer commented
> I would prefer to avoid introducing shield descriptions in samples. I'm checking if we can speed up merging #5263 to allow removing overlay and align documentation in #5294. 

Correct me if I'm wrong, but wouldn't merging #5263 as it is now introduce two different ways of supporting FEM across NCS samples? Also, aligning documentation for all samples in this PR that is limited to matter samples only will only cause confusion.

2021-08-17 14:22 UTC, hubertmis commented
> wouldn't merging #5263 as it is now introduce two different ways of supporting FEM across NCS samples?

I hope not. Have any samples already created overlays for nRF21540-EK?

2021-08-17 14:35 UTC, LuDuda commented
@hubertmis yet it is the case for Thread and Zigbee.

F2F discussed that we're going to remove overlays and simplify the description in the `samples_fem_support.txt` as a part of this or #5263 PR, depending on what can be merged faster.

2021-08-20 11:11 UTC, peknis requested changes

2021-08-20 11:11 UTC, peknis commented on samples/matter/light_bulb/README.rst
> +.. |fem_file_path| replace:: :file:`samples/matter/common`
This needs to be removed because of https://github.com/nrfconnect/sdk-nrf/pull/5263. Do not merge before that PR is in.

2021-08-20 11:11 UTC, peknis commented on samples/matter/light_switch/README.rst
> +.. |fem_file_path| replace:: :file:`samples/matter/common`
This needs to be removed because of #5263. Do not merge before that PR is in.

2021-08-20 11:11 UTC, peknis commented on samples/matter/lock/README.rst
> +.. |fem_file_path| replace:: :file:`samples/matter/common`
This needs to be removed because of #5263. Do not merge before that PR is in.

2021-08-20 11:11 UTC, peknis commented on samples/matter/template/README.rst
> +.. |fem_file_path| replace:: :file:`samples/matter/common`
This needs to be removed because of #5263. Do not merge before that PR is in.

2021-08-23 07:59 UTC, LuDuda commented
Blocked by #5263

2021-08-23 08:00 UTC, peknis approved these changes

2021-08-24 06:07 UTC, greg-fer approved these changes

2021-08-24 08:28 UTC, hubertmis approved these changes

2021-08-24 09:15 UTC, merged