application: serial_lte_modem: Add secondary PDN support to #XPING
nrfconnect/sdk-nrf pull request #5296
Opened 2021-08-16 02:38 UTC by junqingzou

Allow to specify which PDN to use in Ping test.
Prepared for NIDD test in the future.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2021-08-16 03:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5296
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-16 09:22 UTC, rlubos approved these changes

2021-08-20 08:27 UTC, peknis requested changes

2021-08-20 08:27 UTC, peknis commented on applications/serial_lte_modem/doc/ICMP_AT_commands.rst
> +  It represents ``cid`` in ``+CGDCONT`` command.
```suggestion
  It represents ``cid`` in  the ``+CGDCONT`` command.
```

2021-08-20 08:27 UTC, peknis commented on applications/serial_lte_modem/src/slm_util.h
> + * @param[in] cid PDP Context id as defined in "+CGDCONT" command (0~10)
```suggestion
 * @param[in] cid PDP Context ID as defined in "+CGDCONT" command (0~10)
```

2021-08-20 08:50 UTC, junqingzou commented on applications/serial_lte_modem/doc/ICMP_AT_commands.rst
> +  It represents ``cid`` in ``+CGDCONT`` command.
Applied, thanks

2021-08-20 08:50 UTC, junqingzou commented on applications/serial_lte_modem/src/slm_util.h
> + * @param[in] cid PDP Context id as defined in "+CGDCONT" command (0~10)
Applied, thanks

2021-08-20 09:04 UTC, peknis approved these changes

2021-08-20 10:31 UTC, melwee01 approved these changes

2021-08-20 11:00 UTC, merged