manifest: Updated sdk-connectedhomeip version
nrfconnect/sdk-nrf pull request #5312
Opened 2021-08-17 09:50 UTC by kkasperczyk-no

sdk-connectedhomeip upmerge containing documentation changes only

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2021-08-17 10:18 UTC, greg-fer approved these changes

2021-08-17 10:19 UTC, greg-fer requested changes

2021-08-17 10:19 UTC, greg-fer commented on doc/nrf/links.txt
> +.. _`Working with Python Controller`: https://github.com/nrfconnect/sdk-connectedhomeip/blob/8a4f2f1/src/controller/python/README.md
```suggestion
.. _`Working with Python Controller`: https://github.com/nrfconnect/sdk-connectedhomeip/blob/8a4f2f1/docs/guides/python_chip_controller_building.md
```

2021-08-17 10:28 UTC, greg-fer approved these changes

2021-08-17 10:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5312
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-18 08:52 UTC, LuDuda approved these changes

2021-08-18 08:54 UTC, LuDuda requested changes
Actually, links seem to be incorrect.

2021-08-18 09:09 UTC, LuDuda approved these changes

2021-08-18 12:17 UTC, merged