zigbee: add ncp custom command for changing led states
nrfconnect/sdk-nrf pull request #5317
Opened 2021-08-17 12:15 UTC by FilipZajdel

Exemplary usage of ncp custom commands to control the state
of a led and sending indications containing the led index.

Signed-off-by: Filip Zajdel <filip.zajdel@nordicsemi.no>

2021-08-18 08:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5317
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-01 12:14 UTC, sebastiandraus requested changes

2021-09-01 12:14 UTC, sebastiandraus commented on samples/zigbee/ncp/src/main.c
> +	zb_uint8_t resp_buf = zb_buf_get(ZB_FALSE, VENDOR_SPECIFIC_RESPONSE_LEN);
Check return value of `zb_buf_get`

2021-09-03 10:41 UTC, sebastiandraus requested changes

2021-09-03 10:41 UTC, sebastiandraus commented on samples/zigbee/ncp/src/main.c
> +}
Please fix this:

```suggestion
static void perform_custom_indication(zb_uint8_t led_idx)
{
	zb_buf_get_out_delayed_ext(custom_indication, led_idx, 0);
}
```

2021-09-03 11:22 UTC, FilipZajdel commented on samples/zigbee/ncp/src/main.c
> +}
fixed

2021-09-03 11:32 UTC, sebastiandraus approved these changes

2021-09-03 11:49 UTC, maciejpietras approved these changes

2021-09-03 12:04 UTC, greg-fer approved these changes

2021-09-03 12:16 UTC, SebastianBoe commented
Awaiting CI

2021-09-03 12:17 UTC, carlescufi approved these changes

2021-09-03 12:18 UTC, carlescufi commented
No need to wait @SebastianBoe, this passed CI in an earlier run.

2021-09-03 12:19 UTC, merged