doc: release_notes: update for v1.7.0 - protocols.
nrfconnect/sdk-nrf pull request #5429
Opened 2021-08-27 13:44 UTC by grochu

Release notes draft for NCS v. 1.7.0 - SPG Protocols scope.

Please have in mind, that this PR assumes the following PRs (with the 1.7.0 milestone) are merged for 1.7.0:
- https://github.com/nrfconnect/sdk-nrf/pull/5261

2021-08-30 07:25 UTC, kapi-no requested changes
I would add the following line to the release highlights regarding the Find My part:

- Added support for NFC and _pair before use_  accessories  to the Apple Find My add-on.

There is no point in adding here the changelog for Find My since the repo has its own release notes.

2021-08-30 09:25 UTC, grochu commented
> I would add the following line to the release highlights regarding the Find My part:
> 
> * Added support for NFC and _pair before use_  accessories  to the Apple Find My add-on.
> 
> There is no point in adding here the changelog for Find My since the repo has its own release notes.

Added as a placeholder in a "Highlights" section, although this section is not part of the standard changelog page. @greg-fer, any idea where to add this statement? Or should it wait till the proper 1.7.0 Release Notes page is created?

2021-08-30 11:57 UTC, peknis requested changes

2021-08-30 11:57 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * :ref:`ble_rpc` library: added support for GATT Server APIs.
```suggestion
  * :ref:`lbs_readme` library - added write request data validation in the LED characteristic.
  * :ref:`ble_rpc` library - added support for GATT Server APIs.
```

2021-08-30 13:06 UTC, grochu commented on doc/nrf/releases/release-notes-changelog.rst
> +  * :ref:`ble_rpc` library: added support for GATT Server APIs.
fixed

2021-08-30 13:07 UTC, peknis approved these changes

2021-08-30 14:23 UTC, peknis requested changes

2021-08-30 14:23 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added support for NFC and *pair before use* accessories to the Apple Find My add-on.
```suggestion
* Added support for NFC and *pair before use* type of accessories to the Apple Find My add-on.
```

2021-08-31 08:08 UTC, grochu commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added support for NFC and *pair before use* accessories to the Apple Find My add-on.
fixed

2021-08-31 08:27 UTC, peknis approved these changes

2021-09-02 17:06 UTC, SebastianBoe commented
@grochu : Needs rebase

2021-09-02 20:05 UTC, greg-fer requested changes
@grochu , the #4984 PR you mentioned as required for this update to go in is now descoped from 1.7.0. Can you review the release notes in this PR to make sure they do not mention the changes from #4984? Thanks!

2021-09-03 06:29 UTC, peknis requested changes

2021-09-03 06:29 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added a Device Tree shield definition for the nRF21540 Evaluation Kit.
```suggestion
* Added a device tree shield definition for the nRF21540 Evaluation Kit.
```

2021-09-03 09:28 UTC, grochu commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added a Device Tree shield definition for the nRF21540 Evaluation Kit.
fixed

2021-09-03 09:30 UTC, grochu commented
> @grochu , the #4984 PR you mentioned as required for this update to go in is now descoped from 1.7.0. Can you review the release notes in this PR to make sure they do not mention the changes from #4984? Thanks!

Yes, the descoped PR I removed from this PR's description and the relevant entry in changelog is removed too.

2021-09-03 12:52 UTC, greg-fer approved these changes
My comment was answered, I'm approving.

2021-09-03 12:54 UTC, kapi-no approved these changes

2021-09-03 12:59 UTC, peknis approved these changes

2021-09-03 13:03 UTC, merged