doc: adding more west info to introduction.rst
nrfconnect/sdk-nrf pull request #5464
Opened 2021-08-31 11:42 UTC by mia-ko

Added more info about the west tool.
Moved a couple of lines from gs_installing.rst.
NCSDK-10915

Signed-off-by: Mia Koen <mia.koen@nordicsemi.no>

2021-08-31 12:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5464
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-31 12:55 UTC, peknis requested changes

2021-08-31 12:55 UTC, peknis commented on doc/nrf/introduction.rst
> +You can learn more about the reasons behind the introduction of west in :ref:`this section <zephyr:west-history>` of the Zephyr documentation.
```suggestion
For more details about the reasons behind the introduction of west, see the :ref:`zephyr:west-history` section of the Zephyr documentation.
```

2021-08-31 12:55 UTC, peknis commented on doc/nrf/introduction.rst
> +It will clone the manifest repository into the workspace.
```suggestion
It clones the manifest repository into the workspace.
```

2021-08-31 12:55 UTC, peknis commented on doc/nrf/introduction.rst
> +However, the content of the manifest repository is managed using Git commands, since west will not modify or update it.
```suggestion
However, the content of the manifest repository is managed using Git commands, since west does not modify or update it.
```

2021-08-31 12:55 UTC, peknis commented on doc/nrf/introduction.rst
> +To clone the project repositories, the ``west update`` command is used.
```suggestion
To clone the project repositories, use the ``west update`` command.
```

2021-08-31 12:55 UTC, peknis commented on doc/nrf/introduction.rst
> +The ``west init`` command creates a west workspace, and you will typically run it only once to initialize west with the revision of the |NCS| that you want to check out.
```suggestion
The ``west init`` command creates a west workspace, and you typically need to run it only once to initialize west with the revision of the |NCS| that you want to check out.
```

2021-09-01 09:03 UTC, OeySa approved these changes
LGTM

2021-09-01 10:13 UTC, peknis approved these changes

2021-09-10 11:53 UTC, peknis commented on doc/nrf/introduction.rst
> +The ``west init`` command creates a west workspace, and you typically need to run it only once to initialize west with the revision of the |NCS| that you want to check out.
This is a very long paragraph. I think you could split it a bit. Maybe a paragraph for init and another for update. Maybe also have the references in a separate paragraph.

2021-09-29 08:58 UTC, merged