doc: matter: add known issue related to Android CHIPTool
nrfconnect/sdk-nrf pull request #5468
Opened 2021-08-31 13:35 UTC by Damian-Nordic

Add a known issue for NCS 1.7.0 about Android CHIPTool not
being able to communicate with a Matter device after the
device reboots.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

2021-08-31 13:56 UTC, greg-fer requested changes
Isn't this an issue related to the external Android CHIPtool and not to how NCS is working? Should we really document it in NCS known issues? Also, is there a workaround, like "Use Python CHIP Controller instead."?

2021-08-31 14:02 UTC, Damian-Nordic commented
> Isn't this an issue related to the external Android CHIPtool and not to how NCS is working? Should we really document it in NCS known issues? Also, is there a workaround, like "Use Python CHIP Controller instead."?

It is, but we use Android CHIPTool in our docs and we used to add known issues related to Android CHIPtool here as well. So you're saying we should not and there's no alternative way to communicate known issues related to testing tools?

We refer to both Android CHIPTool and Python CHIP Controller in our docs (for different scenarios and testing environments), so if a customer wants to use Android CHIPTool I'm not sure recommending the Python CHIP Controller will make them happy. Also, one doesn't need to reboot the device to test Matter so the issue is related with a very specific use case.

2021-08-31 14:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5468
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-08-31 14:57 UTC, greg-fer approved these changes

2021-08-31 14:57 UTC, greg-fer requested changes
Sorry, please DNM until we have a PR for known issues review.

2021-08-31 15:22 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +.. rst-class:: v1-7-0
```suggestion
.. rst-class:: v1-6-1
```
Please do not add tag for next release before it took place. The current version is still 1.6.1, so please use `v1-6-1` or wait till after RC1 and the PR that adds 1.7.0.

2021-09-01 08:38 UTC, greg-fer commented
Please merge this to #5475 or add it as comment there and close this PR.

2021-09-01 08:38 UTC, greg-fer approved these changes

2021-09-01 09:04 UTC, Damian-Nordic commented
@greg-fer Created a PR to your branch: https://github.com/greg-fer/fw-nrfconnect-nrf-1/pull/3. Closing this one.

2021-09-01 09:04 UTC, closed without merging