doc: Add link to Pelion development tools
nrfconnect/sdk-nrf pull request #5522
Opened 2021-09-03 10:52 UTC by pdunaj

Jira:NCSDK-10733

Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

2021-09-03 11:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5522
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-03 12:16 UTC, greg-fer requested changes

2021-09-03 12:16 UTC, greg-fer commented on doc/nrf/ug_pelion.rst
> +It is also possible to run update campaigns directly from a command line.
```suggestion
The `Pelion manifest tool`_ simplifies the creation of update resources and manifests.
You can also use them to run update campaigns directly from command line.

To download and install the tool, see `Installing the manifest tool`_ in the Pelion repository.
```

2021-09-03 12:16 UTC, greg-fer commented on doc/nrf/ug_pelion.rst
> +The `Pelion Development Tools` can be used to simplify update process during development stage.
```suggestion
You can also use the `Pelion manifest tool`_ to run the update process during development stage.
See `Using the manifest tool`_ in the Pelion repository for details.
```

2021-09-03 12:16 UTC, greg-fer commented on doc/nrf/links.txt
> +.. _`Pelion Development Tools`: https://github.com/PelionIoT/manifest-tool
```suggestion
.. _`Pelion manifest tool`: https://github.com/PelionIoT/manifest-tool#device-management-manifest-cli-tool
.. _`Installing the manifest tool`: https://github.com/PelionIoT/manifest-tool#installing-the-manifest-tool
.. _`Using the manifest tool`: https://github.com/PelionIoT/manifest-tool#using-the-manifest-tool
```

2021-09-03 12:16 UTC, greg-fer commented
@pdunaj , please add entry in the changelog.

2021-09-06 08:44 UTC, pdunaj commented
The last force push is just a rebase.

2021-09-06 10:24 UTC, pdunaj commented
It seems we are already referencing older version of pelion manifest tool from pelion_client app. I have added an explicit information that this manifest tool is for version 4.7 of update client. Newer manifest tool should still work (if used according to documentation). We could drop the information about the older version altogether but I think it would be safest to keep it as is for now. @greg-fer what do you think?

2021-09-09 18:31 UTC, greg-fer commented
@pdunaj , I'd go for the safest option, given how close the release is, and I think you've chosen the safest one.

2021-09-09 18:32 UTC, greg-fer approved these changes

2021-09-10 06:43 UTC, MarekPieta approved these changes

2021-09-10 07:15 UTC, merged