doc: openthread: Thread tools
nrfconnect/sdk-nrf pull request #5529
Opened 2021-09-06 07:08 UTC by lmaciejonczyk

Fix wrong build command, typo, language improvement.

Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>

2021-09-06 07:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5529
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-06 12:32 UTC, wiba-nordic requested changes
A small change request due to clarification from the writing team.

2021-09-06 12:32 UTC, wiba-nordic commented on doc/nrf/ug_thread_tools.rst
> +After cloning the repository, please make sure to check out the compatible commit id:
```suggestion
After cloning the repository, make sure to check out the compatible commit id:
```
The other writers noted that we do not use "please" in instructions.
This is a good time to fix it here as well.

2021-09-07 05:56 UTC, wiba-nordic approved these changes
Looks good!

2021-09-07 08:09 UTC, canisLupus1313 approved these changes

2021-09-07 08:50 UTC, carlescufi approved these changes

2021-09-07 08:50 UTC, merged