partition_manager: Fix flash map offset
nrfconnect/sdk-nrf pull request #5541
Opened 2021-09-06 13:36 UTC by KAGA164

This PR fixes flash map offset for
partition manager.

2021-09-06 14:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5541
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-06 14:21 UTC, grochu approved these changes

2021-09-06 17:50 UTC, hakonfam requested changes
All commits in `sdk-nrf` require a `Ref:` tag with a JIRA ticket. Also please provide a description in the commit message stating why this change is needed.

2021-09-07 07:44 UTC, KAGA164 commented
> All commits in `sdk-nrf` require a `Ref:` tag with a JIRA ticket. Also please provide a description in the commit message stating why this change is needed.

Sure @hakonfam. Done

2021-09-07 08:19 UTC, hakonfam approved these changes

2021-09-07 09:42 UTC, shantha-14 approved these changes

2021-09-07 09:48 UTC, osaether approved these changes

2021-09-07 13:44 UTC, MarekPieta approved these changes

2021-09-13 11:05 UTC, merged