doc: Update Zigbee memory requirements page
nrfconnect/sdk-nrf pull request #5545
Opened 2021-09-07 08:58 UTC by sebastiandraus

This commit updates memory usage values and adds memory requirements table for nRF21540 DK.

2021-09-07 09:13 UTC, sebastiandraus commented
PR not yet complete, need one additional update

2021-09-07 09:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5545
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-07 10:22 UTC, sebastiandraus commented
Updates to final version

2021-09-07 11:59 UTC, greg-fer approved these changes

2021-09-07 12:34 UTC, greg-fer commented
Removing the changelog label. I'll update the release notes in #5534

2021-09-09 06:35 UTC, greg-fer requested changes

2021-09-09 06:35 UTC, greg-fer commented on doc/nrf/ug_zigbee_memory.rst
> +
```suggestion

The following table lists memory requirements for the :ref:`nRF53 Series <ug_nrf5340>` devices.
```

2021-09-09 06:35 UTC, greg-fer commented on doc/nrf/ug_zigbee_memory.rst
> +   .. tab:: nRF53 family
```suggestion
   .. tab:: nRF53 Series
```

2021-09-09 06:35 UTC, greg-fer commented on doc/nrf/ug_zigbee_memory.rst
> +   .. tab:: nRF52 family
```suggestion
   .. tab:: nRF52 Series
```

2021-09-09 06:35 UTC, greg-fer commented on doc/nrf/ug_zigbee_memory.rst
> +
```suggestion

The following table lists memory requirements for the :ref:`nRF52 Series <ug_nrf52>` devices.
```

2021-09-09 07:45 UTC, totyz approved these changes

2021-09-09 10:39 UTC, greg-fer approved these changes

2021-09-09 10:48 UTC, merged