doc: Bluetooth state power manager documentation
nrfconnect/sdk-nrf pull request #5550
Opened 2021-09-07 19:51 UTC by rakons

Add documentation for the Bluetooth state power manager module.

JIRA: NCSDK-10556

Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>

2021-09-07 20:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5550
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-08 07:09 UTC, pdunaj requested changes

2021-09-08 07:09 UTC, pdunaj commented on doc/nrf/libraries/caf/ble_state_pm.rst
> +Configruation
Configuration

2021-09-08 07:09 UTC, pdunaj commented on doc/nrf/libraries/caf/ble_state_pm.rst
> +There is no logger implemented so it cannot be configured.
I would remove these two lines

2021-09-13 08:36 UTC, rakons commented on doc/nrf/libraries/caf/ble_state_pm.rst
> +Configruation
ok

2021-09-13 08:36 UTC, rakons commented on doc/nrf/libraries/caf/ble_state_pm.rst
> +There is no logger implemented so it cannot be configured.
ok

2021-09-13 09:06 UTC, pdunaj approved these changes

2021-09-17 11:44 UTC, greg-fer approved these changes
Please do not merge before 1.7.0 release, given the cleaned up changelog file to which this PR adds an entry.

2021-09-20 11:34 UTC, rakons commented
Waiting for release to finish - the release-notes-changelog.rst would be changed then anyway - so it makes no sense to rebase it right now.

2021-09-23 08:01 UTC, greg-fer commented
Rebased to the latest, emptied changelog.

2021-09-24 07:23 UTC, greg-fer commented
Removing the DNM label I put before the release.

2021-10-08 10:34 UTC, MarekPieta commented
@rakons, can we merge this one already?

2021-10-08 10:35 UTC, rakons commented
Yep!

2021-10-08 10:40 UTC, merged