net: lib: nrf_cloud: do FOTA init first to complete pending updates
nrfconnect/sdk-nrf pull request #5551
Opened 2021-09-07 21:36 UTC by jayteemo

FOTA should be initialized first so that pending updates can be completed.
NCSDK-11236

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2021-09-07 22:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5551
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-08 06:03 UTC, jtguggedal approved these changes

2021-09-08 07:00 UTC, peknis requested changes

2021-09-08 07:00 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Updated :c:func:`nct_init` to perform FOTA initialization before setting the client ID. This fixes an issue which prevented an expected reboot from occurring during a modem FOTA update.
```suggestion
    * Updated :c:func:`nct_init` to perform FOTA initialization before setting the client ID. This fixes an issue that prevented an expected reboot during a modem FOTA update.
```

2021-09-09 05:31 UTC, peknis approved these changes

2021-09-09 08:30 UTC, jorgenmk approved these changes

2021-09-09 09:14 UTC, carlescufi approved these changes

2021-09-09 09:15 UTC, merged