manifest: update Find My revision
nrfconnect/sdk-nrf pull request #5564
Opened 2021-09-08 13:47 UTC by kapi-no

Updated Find My revision to include the upgrade of the minimum
required CMake version.

Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

2021-09-08 14:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5564
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-09 10:54 UTC, KAGA164 approved these changes

2021-09-10 08:07 UTC, SebastianBoe commented
This is a code cleanup.

Like bumping the copyright in code, it does nothing.

It is not a doc improvement or a bug fix.

It has no functional effect, so it should not be merged at this stage of the release.

2021-09-10 08:07 UTC, SebastianBoe requested changes
merge after release.

2021-09-10 08:17 UTC, SebastianBoe commented
My mistake. Code cleanups are allowed after feature-freeze.

2021-09-10 08:17 UTC, SebastianBoe approved these changes

2021-09-10 08:18 UTC, merged