net: lib: nrf_cloud: remove GNSS socket support
nrfconnect/sdk-nrf pull request #5646
Opened 2021-09-17 12:39 UTC by tokangas

Removed GNSS socket support from nRF Cloud A-GPS and P-GPS. Also there's no need anymore to write A-GPS data using the GPS driver, the data can always be written directly using the GNSS API.

Signed-off-by: Tommi Kangas <tommi.kangas@nordicsemi.no>

2021-09-17 12:40 UTC, tokangas commented
I'll add an entry in the changelog after v1.7.0 has been released.

2021-09-17 13:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5646
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-17 13:39 UTC, rlubos approved these changes

2021-09-17 16:39 UTC, plskeggs approved these changes
LGTM

2021-09-20 22:35 UTC, junqingzou approved these changes
Nice move

2021-09-21 06:09 UTC, jtguggedal approved these changes

2021-09-21 08:26 UTC, simensrostad approved these changes

2021-09-21 11:16 UTC, eivindj-nordic approved these changes

2021-09-24 05:49 UTC, tokangas commented
Added the changelog entry.

2021-09-27 06:20 UTC, peknis requested changes

2021-09-27 06:20 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Removed GNSS socket API support from A-GPS/P-GPS.
```suggestion
    * Removed GNSS socket API support from A-GPS and P-GPS.
```

2021-09-27 06:54 UTC, tokangas commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Removed GNSS socket API support from A-GPS/P-GPS.
Changed.

2021-09-27 11:38 UTC, rlubos commented
@peknis Can you revisit? Your comment seems to be addressed.

2021-09-27 11:46 UTC, peknis approved these changes

2021-09-27 11:47 UTC, merged