applications: nrf_desktop: Fix turning off HID keyboard LEDs
nrfconnect/sdk-nrf pull request #5735
Opened 2021-09-29 12:02 UTC by MarekPieta

Change fixes turning off HID keyboard LEDs when host disconnects and there is no other host connected.

Jira: NCSDK-11626

2021-09-29 12:03 UTC, MarekPieta commented
@pdunaj, should this be mentioned as a known issue? I think yes, but if you think it's not needed I will remove it.

2021-09-29 12:07 UTC, pdunaj approved these changes

2021-09-29 12:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5735
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-29 12:45 UTC, pdunaj commented
> @pdunaj, should this be mentioned as a known issue? I think yes, but if you think it's not needed I will remove it.

I think so. This is clearly visible problem.

2021-09-29 13:14 UTC, alstrzebonski approved these changes

2021-09-30 07:59 UTC, mia-ko requested changes

2021-09-30 07:59 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +  **Workaround**: Do not use HID keyboard LEDs.
```suggestion
NCSDK-11626: HID keyboard LEDs are not turned off when host disconnects
  The HID keyboard LEDs, indicating among others state of Caps Lock and Num Lock, may not be updated after host disconnection.
  The problem replicates only if there is no other connected host.

  **Workaround**: Do not use HID keyboard LEDs.
```

2021-09-30 07:59 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed an issue causing HID keyboard LEDs to remain turned on after host disconnected if there is no other host connected.
```suggestion
  * Fixed an issue that was causing the HID keyboard LEDs to remain turned on after host disconnection and no other hosts were connected.
```

2021-09-30 09:07 UTC, MarekPieta commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed an issue causing HID keyboard LEDs to remain turned on after host disconnected if there is no other host connected.
`while no other hosts were connected`?

2021-09-30 10:26 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed an issue causing HID keyboard LEDs to remain turned on after host disconnected if there is no other host connected.
Sounds good

2021-09-30 11:01 UTC, MarekPieta commented
@mia-ko, I applied the requested changes. Please rereview

2021-09-30 11:06 UTC, mia-ko approved these changes

2021-09-30 13:46 UTC, merged