Known issues update
nrfconnect/sdk-nrf pull request #5743
Opened 2021-09-29 14:53 UTC by adrianstoica6

ncs 1.7.0 nrf5340 issue into known_issues.rst

2021-09-29 14:54 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2021-09-29 16:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5743
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-09-30 06:17 UTC, wiba-nordic requested changes
If the active scanner always asserts when performing extended scanning with a full whitelist, then "might assert" should instead be "asserts".

2021-09-30 06:17 UTC, wiba-nordic commented on doc/nrf/known_issues.rst
> +  Active scanner could assert when performing extended scanning on Coded PHY with a full whitelist.
```suggestion
DRGN-16113: Active scanner assert when performing extended scanning
  The active scanner might assert when performing extended scanning on Coded PHY with a full whitelist.
```
Is the workaround for this to ensure that the whitelist is not full?

2021-09-30 10:28 UTC, wiba-nordic approved these changes
Looks good.

2021-09-30 12:19 UTC, carlescufi approved these changes

2021-10-04 11:11 UTC, jori-nordic commented
we'll sort this out with @adrianstoica6 , please ignore the noise reviewers

2021-10-05 07:04 UTC, merged