doc: Update known issues for Softdevice Controller
nrfconnect/sdk-nrf pull request #5784
Opened 2021-10-05 12:07 UTC by hermabe

Update known issues with DRGN-16341.

2021-10-05 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=5784) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=5784) before we can accept your contribution.<br/><hr/>**Berget, Herman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=5784) it.</sub>

2021-10-05 12:18 UTC, rugeGerritsen approved these changes

2021-10-05 12:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5784
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-10-13 08:07 UTC, wiba-nordic requested changes
Is there a workaround for this issue?

2021-10-13 08:07 UTC, wiba-nordic commented on doc/nrf/known_issues.rst
> +  Extended Advertising Reports with data length 228 are discarded.
```suggestion
  Extended Advertising Reports with data length of 228 are discarded.
```

2021-10-13 09:28 UTC, hermabe commented
> Is there a workaround for this issue?

Not that I know of. From what I can see, all reports with data length of 228 are lost. One could potentially send 229 bytes with some dummy value as the last byte, but that is probably not that useful.

2021-10-14 07:00 UTC, merged