samples: nrf9160: aws_iot: Update `README` to reference root `Kconfig`
nrfconnect/sdk-nrf pull request #5794
Opened 2021-10-06 13:28 UTC by simensrostad

- Update the `README` to reference the correct placement of the sample root `Kconfig` file.
- Add missing documentation for `CONFIG_CONNECTION_RETRY_TIMEOUT_SECONDS` in `README`.

2021-10-06 13:43 UTC, peknis requested changes

2021-10-06 13:43 UTC, peknis commented on samples/nrf9160/aws_iot/README.rst
> +Configures the number of seconds between each AWS IoT connection retry."
```suggestion
Configures the number of seconds between each AWS IoT connection retry.
```

2021-10-06 13:54 UTC, simensrostad commented on samples/nrf9160/aws_iot/README.rst
> +Configures the number of seconds between each AWS IoT connection retry."
woops. Thanks!

2021-10-06 13:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-5794
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-10-07 10:38 UTC, peknis approved these changes

2021-10-07 10:40 UTC, merged