doc: separate HEX files for building with nrfjprog in nRF53 user guide
nrfconnect/sdk-nrf pull request #5870
Opened 2021-10-19 11:09 UTC by peknis

Introduced separate HEX files for network core and application core building with nrfjprog.
Ref: NCSDK-12004

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2021-10-20 19:33 UTC, sebastiandraus approved these changes

2021-10-21 06:37 UTC, OeySa requested changes
I can't find any *merged_domains.hex when after building. I must be missing something?

2021-10-21 07:19 UTC, sebastiandraus commented
@OeySa You're right, these .hex files are created when `west flash` is called to flash nRF53. They are missing after only `west build`.

2021-11-02 11:16 UTC, OeySa approved these changes

2021-11-02 12:00 UTC, greg-fer approved these changes
Some additional suggestions, but I approve.

2021-11-02 12:08 UTC, peknis commented on doc/nrf/ug_nrf5340.rst
> +         If you cannot locate the build folder of the network sample, look for a folder with one of these names inside the build folder of the application sample:
Sebastian says: "It does not, with west flash for nRF53 it's a single call and both cores will be flashed with correct images."

2021-11-02 14:26 UTC, merged