applications: asset_tracker_v2: Send neighbor cell data to nRF Cloud
nrfconnect/sdk-nrf pull request #5948
Opened 2021-10-28 11:05 UTC by simensrostad

Start sending neighbor cell data in the nRF Cloud integration. The data
is formattet according to the schema for `APP_ID` : `CELL_POS`
documented in this PR:

https://github.com/nRFCloud/application-protocols/pull/27

Closes CIA-445

2021-10-29 18:45 UTC, jayteemo requested changes

2021-10-29 18:45 UTC, jayteemo commented on applications/asset_tracker_v2/src/cloud/cloud_codec/nrf_cloud/nrf_cloud_codec.c
> +	struct lte_lc_cells_info info = neighbor_cells->cell_data;
rsrp and rsrq values are already converted here.
the nrf_cloud functions expect them to still be an index.

2021-11-01 17:21 UTC, coleHafner commented
> Ok, so adding an additional value "doReply": 0 to the root obj should prevent the location from being sent back?

@simensrostad @jayteemo  the `doReply` flag was only implemented on `SCELL` appId, not `CELL_POS`. It will always send a response. Sounds like this is something that we also be useful for `CELL_POS`. Please make a ticket and assign it to me and I will get it done.

2021-11-01 17:34 UTC, jayteemo approved these changes

2021-11-02 16:03 UTC, merged

2021-11-09 17:55 UTC, coleHafner commented
Linking ticket to turn off response for CELL_POS: https://projecttools.nordicsemi.no/jira/browse/IRIS-3701