zigbee: osif: Add variant for incomplete platforms
nrfconnect/sdk-nrf pull request #6009
Opened 2021-11-08 09:34 UTC by tomchy

Introduce a simplified variant of OSIF layer parts, to reduce the dependencies between ZBOSS and peripheral drivers.
This variant is not meant do be used in production. It can be useful during:
 - Porting Zigbee support to a new, incomplete platform.
 - Writing component tests (i.e. NVRAM migration or loading)

Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

2021-11-08 09:37 UTC, tomchy commented
The following symbols will be added before leaving draft stage:
```
	imply COUNTER
	imply COUNTER_TIMER2
```
They are temporary removed to test the ktimer implementation.

2021-11-08 10:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6009
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-28 17:24 UTC, thst-nordic commented
This PR needs to be rebased, and then the test-spec will be generated.
The CI-* Github Labels are now redundant so I will remove them.

2022-04-07 07:41 UTC, greg-fer requested changes

2022-04-07 07:41 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    This timer implementation is enabled by default in NCP sample and while using ZBOSS development libraries.
```suggestion
    This timer implementation is enabled by default in the :ref:`Zigbee NCP sample <zigbee_ncp_sample>` and when using ZBOSS development libraries.
```

2022-04-07 07:41 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    This implementation must not be used in production. It is meant to be used only for debugging purposes.
```suggestion
    This implementation must not be used in production.
    It is meant to be used only for debugging purposes.
```

2022-04-07 07:41 UTC, greg-fer commented on subsys/zigbee/Kconfig
> +	int "The number of ZBOSS (NV)RAM pages"
```suggestion
	int "The number of ZBOSS RAM or NVRAM pages"
```
Global edit

2022-04-07 07:41 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Kconfig option to set the number of ZBOSS NVRAM virtual pages.
```suggestion
  * :kconfig:option:`CONFIG_ZIGBEE_NVRAM_PAGE_COUNT` Kconfig option to set the number of ZBOSS NVRAM virtual pages.
```

2022-04-08 15:56 UTC, tomchy commented on doc/nrf/libraries/zigbee/osif.rst
> +* :kconfig:option:`CONFIG_ZIGBEE_NVRAM_PAGE_COUNT` - Configures the number of ZBOSS (NV)RAM logical pages.
If it is unacceptable to use the brackets, I prefer to stay with the `NVRAM` name.

2022-04-12 09:06 UTC, tomchy commented on subsys/zigbee/osif/zb_nrf_nvram_none.c
> +/* ZBOSS collaout that should be called once flash erase page operation is finished. */
fixed

2022-04-12 10:43 UTC, tomchy commented on subsys/zigbee/osif/zb_nrf_nvram_none.c
> +		memset(buf, 0xFF, len);
I've added error codes instead.

2022-04-12 12:04 UTC, greg-fer commented on doc/nrf/libraries/zigbee/osif.rst
> +* :kconfig:option:`CONFIG_ZIGBEE_NVRAM_PAGE_COUNT` - Configures the number of ZBOSS (NV)RAM logical pages.
Yes, ok, just don't use brackets.

2022-04-12 12:30 UTC, greg-fer approved these changes

2022-04-12 12:52 UTC, sebastiandraus approved these changes

2022-04-13 13:07 UTC, rlubos approved these changes

2022-04-15 17:18 UTC, mbolivar-nordic commented
I  believe the compliance failures can be addressed by modifying scripts/checkpatch/typedefsfile.

2022-04-19 09:57 UTC, carlescufi approved these changes

2022-04-19 09:57 UTC, merged