lib: edge_impulse: Expand ei_wrapper API
nrfconnect/sdk-nrf pull request #6013
Opened 2021-11-08 11:34 UTC by MarekPieta

Expand API to provide input data sampling frequency, all labels and result data associated with every label. Change also updates related application, sample and test. Documentation is updated too.

Jira: NCSDK-12108

2021-11-08 12:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6013
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-09 16:00 UTC, pdunaj requested changes

2021-11-10 07:46 UTC, greg-fer requested changes

2021-11-10 07:46 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Expand API to provide: input data sampling frequency, every label used by the machine learning model and result data associated with every label.
```suggestion
  * Expanded API to provide information about input data sampling frequency, every label used by the machine learning model, and results associated with every label.
```

2021-11-10 07:46 UTC, greg-fer commented on doc/nrf/ug_edge_impulse.rst
> +     The relative path starts from application source directory (``APPLICATION_SOURCE_DIR``).
```suggestion
     The relative path is tracked from the application source directory (``APPLICATION_SOURCE_DIR``).
```

2021-11-10 11:04 UTC, MarekPieta commented on lib/edge_impulse/ei_wrapper.cpp
> +		for (size_t idx = cur_idx + 1; idx < RESULT_LABEL_COUNT; idx++) {
Thanks for the suggestions. This seems simpler now :)

2021-11-10 13:42 UTC, pdunaj requested changes

2021-11-10 13:42 UTC, pdunaj commented on lib/edge_impulse/ei_wrapper.cpp
> +		if ((max_val == -INFINITY) && (val == -INFINITY) && (!found)) {
discussed offline - let's combine two cases

2021-11-10 13:47 UTC, MarekPieta commented on lib/edge_impulse/ei_wrapper.cpp
> +		if ((max_val == -INFINITY) && (val == -INFINITY) && (!found)) {
Fixed

2021-11-10 13:56 UTC, pdunaj approved these changes

2021-11-15 15:41 UTC, greg-fer approved these changes

2021-11-16 09:12 UTC, merged