samples: bluetooth: dtm: replace busy wait with sleep
nrfconnect/sdk-nrf pull request #6015
Opened 2021-11-08 11:50 UTC by kapi-no

[Work in Progress]

In the Direct Test Mode sample, busy waiting was replaced with the
sleep mode. This change attempts to introduce pauses in CPU activity
to reduce noise in the spectrum during DTM testing.

The sleep duration may slightly differ from the reference UART polling
cycle since the sleep resolution depends on the duration of a tick
(please see the CONFIG_SYS_CLOCK_TICKS_PER_SEC configuration).

2021-11-08 12:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6015
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-15 11:25 UTC, KAGA164 requested changes

2021-11-15 11:25 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/src/dtm.c
> +	     "Core DTM timer needs additional KConfig configuration");
Probably:
```suggestion
	     "Wait DTM timer needs additional KConfig configuration");
```

2021-11-15 11:29 UTC, kapi-no commented on samples/bluetooth/direct_test_mode/src/dtm.c
> +	     "Core DTM timer needs additional KConfig configuration");
fixed

2021-11-15 11:30 UTC, KAGA164 approved these changes
Looks good

2021-11-16 07:56 UTC, Rallare approved these changes

2021-11-16 08:16 UTC, merged