boards: thingy91_nrf9160: remove AT socket
nrfconnect/sdk-nrf pull request #6032
Opened 2021-11-09 15:25 UTC by MirkoCovizzi

This commit removes AT socket dependency from
board init in favor of the new AT API.

Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>

2021-11-09 15:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6032
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-10 12:35 UTC, lemrey requested changes
We need to escape the `%` character in the AT command when using `_printf`

2021-11-11 14:48 UTC, lemrey reviewed
Don't need to pass more arguments to `_printf` beyond the AT command, what is the `0` for?

2021-11-15 11:32 UTC, lemrey approved these changes

2021-11-15 14:02 UTC, jtguggedal approved these changes

2021-11-16 15:49 UTC, simensrostad approved these changes

2021-11-22 08:20 UTC, merged