Bluetooth: Mesh: Fix Sensor Client tests
nrfconnect/sdk-nrf pull request #6038
Opened 2021-11-10 10:17 UTC by michal-narajowski

2021-11-10 10:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6038
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-10 13:01 UTC, trond-snekvik requested changes

2021-11-10 13:01 UTC, trond-snekvik commented on subsys/bluetooth/mesh/sensor_types.c
> +
Please put this under `Warranty and service` on line 1207

2021-11-10 21:02 UTC, trond-snekvik approved these changes

2021-11-11 15:31 UTC, ludvigsj approved these changes

2021-11-17 09:05 UTC, trond-snekvik commented
@michal-narajowski could you please rebase this PR? It appears to fail in kconfig due to an undefined symbol.

2021-11-18 06:55 UTC, merged