samples: nrf9160: agps: remove sample
nrfconnect/sdk-nrf pull request #6048
Opened 2021-11-11 10:46 UTC by tokangas

Removed the A-GPS sample. nRF Cloud A-GPS and P-GPS are demonstrated in the GNSS sample (PR #6010), so there's no need for a separate A-GPS sample.

Added DNM label until PR #6010 has been merged.

2021-11-11 11:35 UTC, peknis requested changes

2021-11-11 11:35 UTC, peknis commented on doc/nrf/ug_nrf91_features.rst
>  * :ref:`gps_with_supl_support_sample` sample - Does not use A-GPS by default but can be configured to use SUPL. The sample displays tracking, fix information, and NMEA strings in the serial console.
Are we not adding the gnss_sample here?

2021-11-11 11:52 UTC, tokangas commented on doc/nrf/ug_nrf91_features.rst
>  * :ref:`gps_with_supl_support_sample` sample - Does not use A-GPS by default but can be configured to use SUPL. The sample displays tracking, fix information, and NMEA strings in the serial console.
That's in PR #6010.

2021-11-11 11:53 UTC, peknis commented on doc/nrf/ug_nrf91_features.rst
>  * :ref:`gps_with_supl_support_sample` sample - Does not use A-GPS by default but can be configured to use SUPL. The sample displays tracking, fix information, and NMEA strings in the serial console.
Of course. My bad.

2021-11-11 18:08 UTC, plskeggs commented
"nRF Cloud A-GPS and P-GPS are demonstrated in the GNSS sample (PR #6010), so there's no need for a separate A-GPS sample."  This is not quite correct, in that the older sample uses MQTT but the newer uses REST.  The distinction is important.

Isn't it unusual to simply remove a sample without any deprecation warning?  I thought the policy was to deprecate for 1 release and remove at the following release.

2021-11-12 06:39 UTC, tokangas commented
> Isn't it unusual to simply remove a sample without any deprecation warning? I thought the policy was to deprecate for 1 release and remove at the following release.

My understanding is that there's no such policy for samples. @rlubos, is it ok to remove a sample without deprecating it first?

2021-11-15 07:40 UTC, tokangas commented
@peknis There are references to `agps_sample` in old release notes. As we already discussed, when the sample is removed, those links still need to point somewhere.

2021-11-15 07:44 UTC, peknis commented
> @peknis There are references to `agps_sample` in old release notes. As we already discussed, when the sample is removed, those links still need to point somewhere.

Yep, I'm discussing this with my colleague to come up with a proposal. Hold on.

2021-11-15 13:17 UTC, rlubos commented
> > Isn't it unusual to simply remove a sample without any deprecation warning? I thought the policy was to deprecate for 1 release and remove at the following release.
> 
> My understanding is that there's no such policy for samples. @rlubos, is it ok to remove a sample without deprecating it first?

I think so, with library deprecation makes sense as it might be used by some customer project, so the deprecation gives the3rd party application time to adapt. But for sample, I don't see a need for a deprecation period. Especially that the functionality is exposed in a `gnss` sample now, I don't see a reason to carry the old sample around.

2021-11-15 13:18 UTC, rlubos approved these changes

2021-11-15 15:28 UTC, jtguggedal approved these changes

2021-11-16 12:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6048
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-16 14:11 UTC, peknis approved these changes

2021-11-17 08:04 UTC, merged