doc: zigbee: update zboss links
nrfconnect/sdk-nrf pull request #6074
Opened 2021-11-15 12:04 UTC by greg-fer

Updated links and shortcut to 3.9.0.0 ZBOSS.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2021-11-15 12:13 UTC, sebastiandraus requested changes

2021-11-15 12:13 UTC, sebastiandraus commented on doc/nrf/shortcuts.txt
> +.. |zboss_version| replace:: 3.9.0.0
It's ZBOSS version 3.9.0.1, please update links

2021-11-15 12:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6074
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-17 08:05 UTC, sebastiandraus approved these changes

2021-11-17 08:07 UTC, rlubos approved these changes

2021-11-17 08:08 UTC, merged