samples: openthread: enable PSA crypto API in non-secure builds
nrfconnect/sdk-nrf pull request #6091
Opened 2021-11-17 08:04 UTC by Damian-Nordic

We've recently added support for OpenThread crypto backend based on PSA crypto API to Zephyr. Let's make use of it in
our OpenThread samples.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

2021-11-17 10:12 UTC, LuDuda approved these changes

2021-11-17 10:14 UTC, LuDuda reviewed
Just spotted that we don't have information about this feature in change-log. Could we add such, that OT can be now built with TF-M...?

2021-11-17 14:43 UTC, rlubos approved these changes
The PR likely needs a rebase according to NCS CI channel.

2021-11-17 15:44 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6091
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-17 15:46 UTC, lmaciejonczyk approved these changes

2021-11-18 12:01 UTC, MarekPorwisz approved these changes

2021-11-18 14:22 UTC, greg-fer requested changes
I don't like how "build with ... the usage" sounds. Hence the edit.

2021-11-18 14:22 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    This allows to build the OpenThread samples with Trusted Firmware-M and the usage of PSA crypto API.
```suggestion
    This allows to build the OpenThread samples with Trusted Firmware-M and the PSA crypto API support.
```

2021-11-18 14:26 UTC, Damian-Nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +    This allows to build the OpenThread samples with Trusted Firmware-M and the usage of PSA crypto API.
Done.

2021-11-19 08:13 UTC, greg-fer approved these changes

2021-11-19 10:08 UTC, merged