samples: nrf9160: modem_shell: ppp updates and link ipv6 MTU printing
nrfconnect/sdk-nrf pull request #6130
Opened 2021-11-19 13:11 UTC by jhirsi

This PR adds bunch of improvements to PPP:
- ipv6 support enabled
- LTE link MTU to be informed to PC (via LCP MRU option)
- using semaphores for sockets instead of sleeping
- auto-restarting ppp net_if when dial up disconnected.
This enables reconnection possibility from PC side without
commanding manually ppp up/down from mosh.
- PPP net_if autostart disabled (needed by custom MTU)
- less UL buffering and not delaying ppp startup in bootup
- workarounding a modem failure for raw sckt sending (Jira: NCSDK-11858)

Additionally this add support for printing MTU for IPv6 within `link status` command.

Note: for full functionality this needs Zephyr changes from: https://github.com/nrfconnect/sdk-nrf/pull/6097

2021-11-19 13:41 UTC, peknis commented
Would this change be worth an entry in the changelog?

2021-11-19 13:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6130
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-19 14:42 UTC, trantanen approved these changes

2021-11-22 06:39 UTC, peknis approved these changes

2021-11-22 07:05 UTC, tokangas approved these changes

2021-11-22 07:18 UTC, jhirsi commented on samples/nrf9160/modem_shell/README.rst
> +   west build -p -b nrf9160dk_nrf9160ns -- -DDTC_OVERLAY_FILE=ppp.overlay -DOVERLAY_CONFIG=overlay-ppp.conf
changed

2021-11-22 07:19 UTC, jhirsi commented on samples/nrf9160/modem_shell/src/ppp/ppp_ctrl.c
> +	bool done = false;
Yes, no need. Changed.

2021-11-22 07:19 UTC, jhirsi commented on samples/nrf9160/modem_shell/overlay-ppp.conf
> +CONFIG_NET_BUF_LOG=n
Yes, no need. Removed.

2021-11-22 07:47 UTC, jhirsi commented
> Would this change be worth an entry in the changelog?

@peknis. I think it does, added one. Please, check.

2021-11-22 08:06 UTC, peknis requested changes

2021-11-22 08:06 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * PPP updates: IPv6 support, LTE link MTU to be informed to PC, autostarting of PPP improved and changes for enabling better performance.
```suggestion
  * PPP updates: 
    * IPv6 support
    * LTE link MTU to be informed to PC
    * Improved autostart of PPP
    * Changes for better performance
```

2021-11-22 08:35 UTC, rlubos approved these changes

2021-11-22 08:44 UTC, peknis approved these changes

2021-11-22 15:17 UTC, merged