partition manager: let sram_nonsecure span rpmsg_nrf53_sram partition
nrfconnect/sdk-nrf pull request #6137
Opened 2021-11-22 07:31 UTC by Damian-Nordic

In the case of nRF5340, Bluetooth subystem creates
rpmsg_nrf53_sram partition in SRAM for the HCI transport
between the two cores. If the partition is present,
sram_primary and sram_nonsecure partitions are reduced and
the rpmsg_nrf53_sram is not accessible from the non-secure
firmware - an application built with CONFIG_BT=y causes
the secure fault.

Make sram_nonsecure partition, which defines the non-secure
SRAM, span rpmsg_nrf53_sram as well.

Signed-off-by: Damian Krolik <damian.krolik@nordicsemi.no>

2021-11-22 08:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6137
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-22 08:08 UTC, hakonfam requested changes
We can do the inverse, and IMO that is a better solution.

Please check if the following patch also solves your problem 


```
diff --git a/subsys/partition_manager/pm.yml.bt_rpmsg_nrf53 b/subsys/partition_manager/pm.yml.bt_rpmsg_nrf53
index 6db564da5..6537681b4 100644
--- a/subsys/partition_manager/pm.yml.bt_rpmsg_nrf53
+++ b/subsys/partition_manager/pm.yml.bt_rpmsg_nrf53
@@ -5,3 +5,6 @@ rpmsg_nrf53_sram:
   placement: {before: end}
   size: CONFIG_RPMSG_NRF53_SRAM_SIZE
   region: sram_primary
+#if CONFIG_TRUSTED_EXECUTION_NONSECURE
+  inside: sram_nonsecure
+#endif
```

2021-11-22 08:19 UTC, Damian-Nordic commented
@hakonfam Out of curiosity, why is that better? Isn't it cleaner to have all partitions that form the non-secure SRAM region listed in a single place?

2021-11-22 08:24 UTC, hakonfam commented
> @hakonfam Out of curiosity, why is that better? Isn't it cleaner to have all partitions that form the non-secure SRAM region listed in a single place?

IMO it is better to state all the properties of a partition where it is declared, instead of having a definition scattered across multiple files. If you have strong opinions on this I won't block the PR. That being said, I got a build error with your initial proposal on the peripheral_uart sample.

2021-11-22 08:26 UTC, Damian-Nordic commented
@hakonfam No, I was just curious. I can do it as you suggest. I'll check the error.

2021-11-22 09:36 UTC, SebastianBoe approved these changes

2021-11-22 09:41 UTC, hakonfam approved these changes
Also please add a NCSDK jira ticket ref to the commit message.

2021-11-22 09:47 UTC, Damian-Nordic commented
@hakonfam Does it have to be NCSDK or KRKNWK is enough?

2021-11-22 10:49 UTC, hakonfam commented
> @hakonfam Does it have to be NCSDK or KRKNWK is enough?

My bad, any tag should be sufficient.

2021-11-22 12:35 UTC, LuDuda approved these changes

2021-11-24 21:08 UTC, merged

2022-02-11 06:24 UTC, sigvartmh commented
This broke building any application with non-secure board and netboot enabled.