applications: asset_tracker: env_sensor: add missing timestamps
nrfconnect/sdk-nrf pull request #6150
Opened 2021-11-22 18:11 UTC by jhn-nordic

Adding missing timestamps in bsec.c

jira: CIA-421

Signed-off-by: Jon Helge Nistad <jon.helge.nistad@nordicsemi.no>

2021-11-22 18:13 UTC, plskeggs approved these changes
LGTM

2021-11-22 18:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6150
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-22 20:27 UTC, jtguggedal approved these changes

2021-11-23 07:08 UTC, peknis requested changes

2021-11-23 07:08 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added missing timestamps to environment sensor data when compiled with :kconfig:`CONFIG_USE_BME680_BSEC`
```suggestion
* Added timestamps to environment sensor data when compiled with :kconfig:`CONFIG_USE_BME680_BSEC`
```

2021-11-23 07:12 UTC, jhn-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added missing timestamps to environment sensor data when compiled with :kconfig:`CONFIG_USE_BME680_BSEC`
done

2021-11-23 07:42 UTC, peknis approved these changes

2021-11-23 07:45 UTC, simensrostad approved these changes

2021-11-23 08:34 UTC, merged