net: lib: azure_iot_hub: Add API to reset DPS information
nrfconnect/sdk-nrf pull request #6162
Opened 2021-11-23 13:01 UTC by jtguggedal

Add API to reset the stored information received during the
initial device provisioning using DPS.
This can be used to trigger re-provisioning upon the next connection
establishment to Azure IoT Hub.

2021-11-23 13:03 UTC, jtguggedal commented on include/net/azure_iot_hub.h
> +
Will remove this change

2021-11-23 13:16 UTC, coderbyheart approved these changes

2021-11-23 13:23 UTC, peknis requested changes

2021-11-23 13:23 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added function :c:func:`azure_iot_hub_dps_reset` to reset DPS information.
```suggestion
  * Added the :c:func:`azure_iot_hub_dps_reset` function for resetting the DPS information.
```

2021-11-23 13:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6162
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-23 14:29 UTC, rlubos approved these changes

2021-11-23 14:29 UTC, rlubos commented on subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c
> +
nit: Redundant empty line.

2021-11-23 14:33 UTC, jtguggedal commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added function :c:func:`azure_iot_hub_dps_reset` to reset DPS information.
Fixed

2021-11-24 04:54 UTC, simensrostad approved these changes

2021-11-24 04:54 UTC, simensrostad commented on subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c
> +
Intentional newline?

2021-11-24 04:54 UTC, simensrostad commented on subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c
> +
Here too

2021-11-24 06:45 UTC, peknis approved these changes

2021-11-24 13:05 UTC, jtguggedal commented on subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c
> +
Yes, these newlines are intentional

2021-11-24 14:53 UTC, merged