net: lib: nrf_cloud: add missing state checks to MQTT based APIs
nrfconnect/sdk-nrf pull request #6176
Opened 2021-11-24 00:02 UTC by jayteemo

Ensure device is connected to the d2c topic before sending
data.
CIA-464

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2021-11-24 00:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6176
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-24 09:08 UTC, trantanen approved these changes

2021-11-24 10:08 UTC, rlubos approved these changes

2021-11-24 10:20 UTC, peknis requested changes

2021-11-24 10:20 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added state checks to :c:func:`nrf_cloud_agps_request`, :c:func:`nrf_cloud_cell_pos_request`, :c:func:`nrf_cloud_pgps_request`, and :c:func:`json_send_to_cloud`. These functions should be called
```suggestion
  * Added state checks to functions :c:func:`nrf_cloud_agps_request`, :c:func:`nrf_cloud_cell_pos_request`, :c:func:`nrf_cloud_pgps_request`, and :c:func:`json_send_to_cloud`. These functions should be called only after the device has connected to the nRF Cloud `` d2c`` topic.
```

2021-11-24 13:50 UTC, jtguggedal approved these changes

2021-11-25 06:35 UTC, peknis approved these changes

2021-11-25 07:44 UTC, merged