doc: openthread: align with upstream changes
nrfconnect/sdk-nrf pull request #6254
Opened 2021-11-30 10:54 UTC by lmaciejonczyk

"networkkey" replaces "masterkey" command

2021-11-30 13:34 UTC, wiba-nordic approved these changes

2021-11-30 14:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6254
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-11-30 15:25 UTC, MarekPorwisz commented on doc/nrf/includes/thread_configure_network.txt
> +   uart:~$ ot networkkey 00112233445566778899aabbccddeeff
there is also masterkey in line 1: ...``ot channel``, ``ot panid``, and ``ot **masterkey**`` commands.

2021-11-30 15:26 UTC, MarekPorwisz requested changes
Good work. but one masterkey is still there

2021-12-01 10:02 UTC, pomarek approved these changes

2021-12-01 11:46 UTC, MarekPorwisz approved these changes

2021-12-02 10:19 UTC, merged