fprotect: add sys init to protect image
nrfconnect/sdk-nrf pull request #6269
Opened 2021-12-01 11:04 UTC by osaether

There is no reason not to protect the image partition.
All areas that should be written to are stored in separate
partitions (storage, settings etc.)

Reopening of https://github.com/nrfconnect/sdk-nrf/pull/3264

Ref: NCSDK-6933
Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

2021-12-01 11:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6269
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-01 15:19 UTC, oyvindronningstad requested changes
fprotect already has tests, but they are in /tests/drivers/fprotect :P. See if they already test what you wanted to test here.

You'd be more than welcome to move them to tests/lib/ instead, it definitely makes more sense :)

2021-12-06 09:08 UTC, osaether commented
> fprotect already has tests, but they are in /tests/drivers/fprotect :P. See if they already test what you wanted to test here.
> 
> You'd be more than welcome to move them to tests/lib/ instead, it definitely makes more sense :)

I think we need this test as well. I moved this test to tests/drivers/fprotect/app so we preserve the history of the other tests.
I also removed the calls to the depricated flash_write_protection_set.

2021-12-06 10:48 UTC, hakonfam commented on lib/fprotect/Kconfig
> +
Remove this and the endif

2021-12-06 10:48 UTC, hakonfam commented on lib/fprotect/Kconfig
> +	depends on PARTITION_MANAGER_ENABLED
```suggestion
	depends on PARTITION_MANAGER_ENABLED && FPROTECT
```

2021-12-06 11:45 UTC, oyvindronningstad commented on tests/drivers/fprotect/app/testcase.yaml
> +        - "E:   Precise data bus error"
```suggestion
```
See if it works without the harness config.

If not we should add more precise regex lines.

2021-12-06 11:47 UTC, oyvindronningstad commented
@andvib how can we add this new test to CI?

2021-12-06 12:26 UTC, oyvindronningstad approved these changes

2021-12-06 12:33 UTC, hakonfam approved these changes

2021-12-06 13:10 UTC, andvib commented
@oyvindronningstad I see the other tests in tests/drivers/fprotect/ have the 'b0' tag - can that tag be added to these tests as well? With the 'b0' tag these tests will be picked up and run in the bootloader CI plan

2021-12-06 13:44 UTC, oyvindronningstad approved these changes

2021-12-07 14:14 UTC, FrancescoSer approved these changes

2021-12-22 16:03 UTC, carlescufi commented
@osaether please rebase

2022-01-03 09:37 UTC, coderbyheart approved these changes

2022-01-03 09:37 UTC, coderbyheart commented on tests/drivers/fprotect/app/CMakeLists.txt
> +# Copyright (c) 2021 Nordic Semiconductor
```suggestion
# Copyright (c) 2022 Nordic Semiconductor
```

2022-01-03 09:37 UTC, coderbyheart commented on tests/drivers/fprotect/app/src/main.c
> + * Copyright (c) 2021 Nordic Semiconductor ASA
```suggestion
 * Copyright (c) 2022 Nordic Semiconductor ASA
```

2022-01-03 09:37 UTC, coderbyheart commented on tests/drivers/fprotect/app/src/main.c
> +			"The wrong number of fatal error has occurred (e:%d != a:%d).\n",
```suggestion
			"The wrong number of fatal errors has occurred (e:%d != a:%d).\n",
```

2022-01-03 11:03 UTC, merged