[DNM] zigbee: Workaround for KRKNWK-12301
nrfconnect/sdk-nrf pull request #6291
Opened 2021-12-02 10:28 UTC by sebastiandraus

Add workaround for packets being retransmitted after incorrect delay when previously transmitted packet was not ACKed.

2021-12-02 10:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6291
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-02 11:29 UTC, tomchy requested changes

2021-12-02 11:29 UTC, tomchy commented on doc/nrf/known_issues.rst
> +KRKNWK-12301: Packets are retransmitted too early when ACK not received.
This is not the issue. The issue is that if the transmission fails, the joiner logic fails and the device requires cold reboot.

2021-12-02 12:56 UTC, sebastiandraus commented on subsys/zigbee/osif/zb_nrf_transceiver.c
> +/* Required by workaround for KRKNWK-12301. */
@greg-fer Are we supposed to mention issues (in known issues/release notes) that we have created workarounds for?

2021-12-02 15:23 UTC, sebastiandraus commented
Force pushed to retrigger CI

2021-12-03 10:26 UTC, tomchy approved these changes

2021-12-03 10:29 UTC, nvlsianpu approved these changes

2021-12-03 10:29 UTC, merged