doc: ug_edge_impulse: Add downloading public project instruction
nrfconnect/sdk-nrf pull request #6368
Opened 2021-12-09 12:58 UTC by alstrzebonski

Adds instruction on how to download public Edge Impulse project.
Fixes some inconsistencies in instruction on how to download private
Edge Impulse project.

Jira: NCSDK-12104

Signed-off-by: Aleksander Strzebonski <aleksander.strzebonski@nordicsemi.no>

2021-12-09 13:25 UTC, MarekPieta approved these changes
2 small fixes

2021-12-09 13:25 UTC, MarekPieta commented on doc/nrf/ug_edge_impulse.rst
> +      CONFIG_EDGE_IMPULSE_URI="https:\ //studio.edgeimpulse.com/v1/api/*XXXXX*/deployment/download?type=zip&modelType=int8"
I would add a note explaining why modelType=int8 is added here (that we can only download a quantized EON compiled model).

2021-12-09 13:38 UTC, greg-fer commented
I'm busy with the 1.9.0 release tasks and the deadline is upon us, so I'll have a look at this PR early next week for after the 1.8.0 release.

2021-12-10 17:19 UTC, rakons approved these changes

2021-12-13 11:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6368
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-13 13:59 UTC, greg-fer requested changes

2021-12-13 13:59 UTC, greg-fer commented on doc/nrf/ug_edge_impulse.rst
> +      Project ID in Edge Impulse studio dashboard
Duplicated the figure from line 112, but we need an updated one, so that the publicProjectId is visible.

2021-12-13 13:59 UTC, greg-fer commented
Please also include a changelog entry.

2021-12-13 14:34 UTC, greg-fer requested changes
Please check and squash my review. Pay attention to the project ID -- can we include this value in public docs?

2021-12-13 16:01 UTC, alstrzebonski commented
> Please check and squash my review. Pay attention to the project ID -- can we include this value in public docs?

I don't see a problem with the ID being shown. It's just the ID to my public EI project cloned from NCS EI project.
I squashed the review and changed just one comment at the end:
> This URI includes the ``modelType=int8`` parameter because from public Edge Impulse projects you can only download quantized models created with Edge Impulse's EON Compiler.
I think it is worth mentioning that this information applies only to public EI projects. Models from private projects don't have to neccessary be quantized or use EON Compiler.

2021-12-14 10:33 UTC, greg-fer approved these changes

2021-12-16 12:30 UTC, merged