Bluetooth: Mesh: Make BT_MESH_MODEL_USER_DATA macro public
nrfconnect/sdk-nrf pull request #6399
Opened 2021-12-15 10:26 UTC by PavelVPV

This fixes a reference to this macro in Chat sample walk-through guide.

Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>

2021-12-15 10:31 UTC, Balaklaka commented on include/bluetooth/mesh/model_types.h
>   * @brief Internal utility macro for type checking model user data.
"Internal" should be removed.

2021-12-15 10:31 UTC, Andrewpini approved these changes

2021-12-15 11:58 UTC, trond-snekvik approved these changes

2021-12-15 11:59 UTC, mia-ko requested changes
Looks good, just a small change suggestion from me :)

2021-12-15 11:59 UTC, mia-ko commented on include/bluetooth/mesh/model_types.h
> + * @brief Utility macro for type checking model user data.
```suggestion
 * @brief Utility macro for type checking of model user data.
```

2021-12-15 12:36 UTC, Balaklaka approved these changes

2021-12-15 12:47 UTC, mia-ko approved these changes

2021-12-15 12:51 UTC, mia-ko reviewed
It seems like the doc build is failing... It does not like @ref bt_mesh_model::user_data in line 101.

2021-12-16 11:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6399
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-16 19:51 UTC, merged