ESB samples nRF52833 DK support
nrfconnect/sdk-nrf pull request #6408
Opened 2021-12-16 07:29 UTC by leewkb4567

Add nRF52833 DK support to ESB samples.

2021-12-16 08:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6408
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-25 09:10 UTC, umapraseeda approved these changes

2022-02-21 09:49 UTC, grochu commented
Will the code section in https://github.com/nrfconnect/sdk-nrf/blob/main/subsys/esb/esb.c#L375 be executed for nRF52833?

2022-02-21 09:53 UTC, grochu reviewed
Please check the _nrf/subsys/esb/esb.c_ file for any additional code that applies for nRF52833 and may be compiled out.

2022-02-22 02:30 UTC, leewkb4567 commented
> Please check the _nrf/subsys/esb/esb.c_ file for any additional code that applies for nRF52833 and may be compiled out.

The ESB code looks OK. The ESB_BITRATE_2MBPS_BLE part is not very clean but it works too.

2022-02-22 09:52 UTC, grochu commented
> > Will the code section in https://github.com/nrfconnect/sdk-nrf/blob/main/subsys/esb/esb.c#L375 be executed for nRF52833?
> 
> I suppose so. Setting to bitrate ESB_BITRATE_1MBPS_BLE, the ptx and prx samples work fine.

I was thinking about the `ESB_BITRATE_250KBPS` specifically. The esb.c line 369 code checks `CONFIG_SOC_SERIES_NRF51X` symbol, which will not be defined for nRF52833 so the switch option will not be compiled - although I am not 100% sure it should. Should this bitrate supported on the nRF52 devices? Maybe this has been wrong already for nRF52832/840?

2022-02-22 11:07 UTC, grochu commented
@leewkb4567 it should be OK to merge from the development point of view. My concern is the test coverage. Shall we expand the test setup with a nRf52833 DK? @shantha-14 could you please comment?

2022-03-04 09:44 UTC, tejlmand commented
@leewkb4567 seems this should have an entry in the changelog here: https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases/release-notes-changelog.rst

2022-03-04 10:27 UTC, umapraseeda requested changes

2022-03-04 10:27 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
> +
```suggestion
Other libraries
---------------

* Updated:

  * :ref:`esb_readme`:

    * Fixed a compilation error for nRF52833.

```

```

2022-03-04 10:40 UTC, leewkb4567 commented
Rebased to current main for changelog changes.

@umapraseeda Your comment is addressed.

2022-03-04 11:32 UTC, umapraseeda approved these changes
LGTM. Thanks!

2022-03-18 10:12 UTC, tejlmand approved these changes

2022-03-18 10:12 UTC, merged