doc: RSC service total distance correction and units
nrfconnect/sdk-nrf pull request #6434
Opened 2021-12-20 12:07 UTC by dchat-nordic

Corrected:
number of bytes for set Total Distance service 3->4 (uint32)

Specified units (rscs.h) for:
-Instantenous speed,
-Instantenous Cadence,
-Instantenous Stride Length,
-Total Distance

Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>

2021-12-20 12:57 UTC, dchat-nordic commented
Removed tests, because only comments and docs are changed.

2021-12-20 13:11 UTC, peknis requested changes

2021-12-20 13:11 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Updated :ref:`peripheral_rscs` - corrected amount of bytes for setting the Total Distance Value and specified the data units.
```suggestion
* Updated:

  * :ref:`peripheral_rscs` - Corrected the number of bytes for setting the Total Distance Value and specified the data units.
```

2021-12-20 13:15 UTC, dchat-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +* Updated :ref:`peripheral_rscs` - corrected amount of bytes for setting the Total Distance Value and specified the data units.
Added the change

2021-12-20 13:16 UTC, peknis approved these changes

2021-12-21 08:12 UTC, rafpelc approved these changes

2021-12-21 11:56 UTC, grochu approved these changes
Looks good.

2021-12-21 15:16 UTC, KAGA164 approved these changes

2021-12-22 13:49 UTC, peknis commented
Rebase will do the trick and make the doc build pass.

2021-12-23 09:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6434
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-23 10:31 UTC, merged