doc: peripheral_hids_keyboard,mouse encryption notice
nrfconnect/sdk-nrf pull request #6454
Opened 2021-12-23 12:01 UTC by dchat-nordic

Added info about encryption config in:
-peripheral_hids_mouse
-peripheral_hids_keyboard
samples.

Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>

2021-12-23 12:27 UTC, qung approved these changes

2021-12-23 12:28 UTC, peknis requested changes

2021-12-23 12:28 UTC, peknis commented on doc/nrf/libraries/bluetooth_services/services/hids.rst
> +   Thus :kconfig:`BT_HIDS_DEFAULT_PERM_RW_ENCRYPT` should be enabled to satisfy this requirement.
```suggestion
   In some systems, you need to enable encryption to be able to connect to a device.
   To satisfy this requirement, enable the :kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT` option.
```
Should we specify what kind of systems require the encryption?

2021-12-23 12:28 UTC, peknis commented on samples/bluetooth/peripheral_hids_keyboard/README.rst
> +:kconfig:`BT_HIDS_DEFAULT_PERM_RW_ENCRYPT` is not required by HID GATT specification, but certain systems do not allow connections to unencrypted HID devices.
```suggestion
The HID GATT specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems do not allow connections to unencrypted HID devices.
```

2021-12-23 12:28 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +:kconfig:`BT_HIDS_DEFAULT_PERM_RW_ENCRYPT` is not required by HID GATT specification, but certain systems do not allow connections to unencrypted HID devices.
```suggestion
The HID GATT specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems do not allow connections to unencrypted HID devices.
```

2021-12-23 12:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6454
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2021-12-23 13:56 UTC, KAGA164 approved these changes

2021-12-23 14:02 UTC, grochu requested changes
Please also add Jira reference to the commit message to enable linking the Github commit with the Jira database.

2021-12-23 14:02 UTC, grochu commented on samples/bluetooth/peripheral_hids_keyboard/README.rst
> +The HID GATT specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems do not allow connections to unencrypted HID devices.
Again I would slightly change it:
```suggestion
The HID service specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems disconnect from the HID devices which do not support security.
```

2021-12-23 14:02 UTC, grochu commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +The HID GATT specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems do not allow connections to unencrypted HID devices.
Same comment as for the HID keyboard.

2021-12-23 14:16 UTC, grochu approved these changes

2021-12-27 08:23 UTC, peknis requested changes

2021-12-27 08:23 UTC, peknis commented on samples/bluetooth/peripheral_hids_keyboard/README.rst
> +The HID service specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems disconnect from the HID devices which do not support security.
```suggestion
The HID service specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems disconnect from the HID devices that do not support security.
```

2021-12-27 08:23 UTC, peknis commented on samples/bluetooth/peripheral_hids_mouse/README.rst
> +The HID service specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems disconnect from the HID devices which do not support security.
```suggestion
The HID service specification does not require encryption (:kconfig:`CONFIG_BT_HIDS_DEFAULT_PERM_RW_ENCRYPT`), but some systems disconnect from the HID devices that do not support security.
```

2021-12-27 08:38 UTC, peknis approved these changes

2022-01-03 09:00 UTC, merged