applications: nrf_desktop: dfu: Config chan backward compatibility
nrfconnect/sdk-nrf pull request #6472
Opened 2022-01-03 15:04 UTC by zycz

After changes introduced in
https://projecttools.nordicsemi.no/jira/browse/NCSDK-12781

change hid_configurator script to work with old version of firmware.

Jira: NCSDK-13087

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2022-01-03 15:10 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    The new implementation is backward compatible, since new version of script checks for module name and acts according to it.
```suggestion
    The new implementation is backward compatible: the new version of the script checks for module name and acts accordingly.
```

2022-01-03 15:25 UTC, greg-fer approved these changes

2022-01-03 15:33 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6472
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-04 08:22 UTC, pdunaj requested changes
looks ok, prefer `None` over `"not_supported"`

2022-01-04 08:22 UTC, pdunaj commented on scripts/hid_configurator/configurator_cli.py
> +        complete_dfu_module_name = 'not_supported'
I prefer to simply set it to None. Easier to understand and lower chance of bugs

2022-01-04 08:23 UTC, pdunaj commented
Hi @zycz , does it work for two FW versions? Was it tested?

2022-01-04 08:42 UTC, zycz commented
> Hi @zycz , does it work for two FW versions? Was it tested?

Yes it does. Checked it on both FW versions.

2022-01-04 10:11 UTC, pdunaj approved these changes

2022-01-04 11:09 UTC, MarekPieta requested changes

2022-01-04 11:09 UTC, MarekPieta commented on scripts/hid_configurator/configurator_cli.py
> +    img_file = DfuImage(args.dfu_image, info, dev.get_board_name(), complete_dfu_module_name)
Can we call the variable `bootloader_variant`, please ? It's no longer complete_dfu_module_name here so that could be misleading.

2022-01-04 11:09 UTC, MarekPieta commented on scripts/hid_configurator/configurator_cli.py
> +        complete_dfu_module_name = dev.get_complete_module_name('dfu')
Handle case where None is returned, please

2022-01-04 11:09 UTC, MarekPieta commented on scripts/hid_configurator/configurator_cli.py
> +        complete_dfu_module_name = dev.get_complete_module_name('dfu')
Or at least assert (we will probably never get None here if fwinfo is not None)

2022-01-04 11:44 UTC, MarekPieta approved these changes

2022-01-04 13:54 UTC, merged