scripts: unity: Fix whitespace not handled correctly
nrfconnect/sdk-nrf pull request #6478
Opened 2022-01-04 13:56 UTC by gregersrygg

The header parsing scripts used for test mocks does not handle whitespace between function identifier and the parameter list. This results in some functions not being wrapped correctly.

The fix updates the regexes to allow whitespace.

This is a breaking change if you use a strict interpretation of what is considered a breaking change. Tests that doesn't use the `__wrap_` prefix in the tests because of this bug will break after this change. So the tests would need to be updated with the prefix.

Signed-off-by: Gregers Gram Rygg <gregers.gram.rygg@nordicsemi.no>

2022-01-04 14:08 UTC, gregersrygg commented
The reason it's needed is because Segger define functions this way it in their RTT library: [zephyrproject-rtos/segger/blob/master/SEGGER/SEGGER_RTT.h#L284](https://github.com/zephyrproject-rtos/segger/blob/master/SEGGER/SEGGER_RTT.h#L284)

2022-01-04 15:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6478
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-04 21:20 UTC, balaji-nordic commented
Tested the changes in my branch. Works as expected. Thanks 👍

2022-01-04 21:21 UTC, balaji-nordic requested changes

2022-01-04 21:21 UTC, balaji-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +* Fixed bug not wrapping function declarations with whitespace between identifier and parameter list.
```suggestion
* Fixed bug that resulted in the mocks for some functions not having the __wrap prefix. This happened for functions declared with whitespaces between identifier and parameter list. 
```

2022-01-05 08:49 UTC, balaji-nordic approved these changes

2022-01-05 09:43 UTC, nordic-krch approved these changes

2022-01-05 19:38 UTC, tejlmand approved these changes
lgtm

2022-01-07 09:06 UTC, merged