Bluetooth: Mesh: Check Property ID is not 0
nrfconnect/sdk-nrf pull request #6493
Opened 2022-01-07 18:03 UTC by m-alperen-sener

srv_init fails if any of the property ID within server is 0
prevent listing of 0 property IDs

Signed-off-by: sener, alperen <alperen.sener@nordicsemi.no>

2022-01-07 18:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=6493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=6493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=6493) it.</sub>

2022-01-07 18:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6493
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-08 11:24 UTC, trond-snekvik requested changes
A good first PR! :tada: 

There's a compliance failure in the signed-off-by line, as it expects your configured `user.name` to be on the format "Alperen Şener", not "Şener, Alperen" (pedantic, I know).

Easiest fix is to do `git config --global user.name "Alperen Şener"`, then `git commit --amend --reset-author -s`, and remove the old signed-off-by line. Then a force push to the remote.

2022-01-10 08:35 UTC, alxelax commented
LGTM. Just fix Trond's comments

2022-01-10 09:24 UTC, alxelax approved these changes

2022-01-11 12:16 UTC, trond-snekvik approved these changes

2022-01-12 15:40 UTC, merged