samples: Added grant deny status log in 1wire coex sample
nrfconnect/sdk-nrf pull request #6529
Opened 2022-01-13 07:22 UTC by krishnabadam-nordic

sample: radio_coex_1wire -To work with sample more effectively, added logging grant deny status.

2022-01-13 07:22 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2022-01-13 10:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6529
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-13 11:58 UTC, Tschet1 approved these changes

2022-01-13 12:55 UTC, jori-nordic requested changes

2022-01-13 12:55 UTC, jori-nordic commented on samples/bluetooth/radio_coex_1wire/src/main.c
> +static bool state_granted;
could you rename to `grant_state` or `grant_all_requests` ?

2022-01-13 12:55 UTC, jori-nordic commented on samples/bluetooth/radio_coex_1wire/src/main.c
> +		printk("Current state is: Grant every request\n");
wrap in curly braces, even if it's a single statement

2022-01-13 12:55 UTC, jori-nordic commented on samples/bluetooth/radio_coex_1wire/src/main.c
> +		state_granted = true;
I see you're using this only for printing the current state, is there any reason to not just print the status here in this `if/else if` ?

2022-01-17 08:43 UTC, jori-nordic approved these changes

2022-01-17 10:01 UTC, KAGA164 approved these changes

2022-01-17 11:03 UTC, merged