zigbee: Fix zb_osif_abort() implementation [KRKNWK-12354]
nrfconnect/sdk-nrf pull request #6534
Opened 2022-01-13 12:16 UTC by sebastiandraus

2022-01-13 12:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6534
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-14 07:26 UTC, greg-fer requested changes

2022-01-14 07:26 UTC, greg-fer commented on doc/nrf/libraries/zigbee/osif.rst
> +  Use this option only for testing and debugging your application.
```suggestion
* :kconfig:`CONFIG_ZBOSS_RESET_ON_ASSERT` - Configures the ZBOSS OSIF layer to reset the device when a ZBOSS assert occurs.
  This option is enabled by default.
  Use it for production-ready applications.
* :kconfig:`CONFIG_ZBOSS_HALT_ON_ASSERT` - Configures the ZBOSS OSIF layer to halt the device when a ZBOSS assert occurs.
  Use this option only for testing and debugging your application.
```

2022-01-14 07:26 UTC, greg-fer commented on subsys/zigbee/Kconfig
> +	prompt "Default behavior on ZBOSS stack internal assert handler"
"on ... handler" sounds weird... "for the ZBOSS stack interna assert handler"?

2022-01-14 07:26 UTC, greg-fer commented on subsys/zigbee/Kconfig
> +		bool "Reset device when ZBOSS assert occurs"
when [a] ZBOSS assert

2022-01-14 07:26 UTC, greg-fer commented on subsys/zigbee/Kconfig
> +		bool "Halt device when ZBOSS assert occurs, use only for testing and debugging."
Halt device when a ZBOSS assert occurs. Use only for testing and debugging.

2022-01-17 12:19 UTC, greg-fer approved these changes

2022-01-18 10:42 UTC, tomchy approved these changes
LGTM

2022-01-18 11:01 UTC, merged