event_manager: Add subscribe first to event
nrfconnect/sdk-nrf pull request #6536
Opened 2022-01-13 13:09 UTC by zycz

Add first subscriber to event functionality to event manager.

Jira: NCSDK-9067

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2022-01-13 13:36 UTC, greg-fer requested changes

2022-01-13 13:36 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added EVENT_SUBSCRIBE_FIRST subscriber priority to event manager.
Add "Added" section before Updated.
```suggestion
* Added:

  * ``EVENT_SUBSCRIBE_FIRST`` subscriber priority.
```

2022-01-13 13:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6536
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-14 07:12 UTC, greg-fer approved these changes

2022-01-14 11:55 UTC, MarekPieta approved these changes

2022-01-21 15:37 UTC, merged