manifest: Updating nrfxlib - 2022 jan 18
nrfconnect/sdk-nrf pull request #6559
Opened 2022-01-18 10:18 UTC by AyturkDuzen

Updating nrfxlib and mpsl to latest version to fix bugs in periodic advertising and adding periodic advertising list feature

2022-01-18 10:28 UTC, rugeGerritsen requested changes
Mostly looks good. One minor comment. 
You also need to look into the failing compliance check

2022-01-18 10:28 UTC, rugeGerritsen commented on subsys/bluetooth/controller/Kconfig
> +# here for a second time, to set different range for Nordic BLE controller.
```suggestion
# here for a second time, to set different range for the SoftDevice Controller.
```
Applies to some other places as well

2022-01-18 11:52 UTC, rugeGerritsen approved these changes

2022-01-18 12:20 UTC, olivier-le-sage approved these changes

2022-01-18 12:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6559
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-19 10:08 UTC, rlubos commented on west.yml
> +      revision: pull/622/head
Please update SHA: `ab4cf70a277e44a4b8bc43bcfe9ac8c51f71a03f`

2022-01-19 12:15 UTC, AyturkDuzen commented on subsys/bluetooth/controller/Kconfig
> +# here for a second time, to set different range for Nordic BLE controller.
updated

2022-01-19 12:15 UTC, AyturkDuzen commented on west.yml
> +      revision: pull/622/head
updated

2022-01-19 12:17 UTC, rlubos approved these changes

2022-01-19 14:39 UTC, merged