manifest: update openthread feature sets and docs
nrfconnect/sdk-nrf pull request #6589
Opened 2022-01-20 11:18 UTC by edmont

Update OpenThread feature sets and their documentation.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

2022-01-20 11:25 UTC, lmaciejonczyk approved these changes

2022-01-20 11:38 UTC, canisLupus1313 commented on doc/nrf/releases/release-notes-changelog.rst
> +* Modified feature sets with support for SRP client and removal or rarely used features.
```suggestion
* Modified feature sets with support for SRP client and removal of rarely used features.
```

2022-01-20 11:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6589
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-20 12:35 UTC, wiba-nordic requested changes

2022-01-20 12:35 UTC, wiba-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +* Modified feature sets with support for SRP client and removal of rarely used features.
```suggestion
* Modified feature sets by adding support for SRP client and removing rarely used features.
```

2022-01-20 14:16 UTC, canisLupus1313 approved these changes

2022-01-24 17:30 UTC, LuDuda approved these changes

2022-01-28 10:02 UTC, rlubos commented on west.yml
> +      revision: pull/624/head
`dfeb3041c0b896c3c0f3ffd5688263d68622e8df`

2022-02-01 07:34 UTC, edmont commented
Rebased as the nrfxlib manifest has been updated by other PR.

2022-02-01 08:21 UTC, edmont commented
Closing as it's included in https://github.com/nrfconnect/sdk-nrf/pull/6692

2022-02-01 08:21 UTC, closed without merging