doc: Added links to RST files in header files
nrfconnect/sdk-nrf pull request #6616
Opened 2022-01-24 10:29 UTC by richabp

Provided comments in the header files about the location of corresponding RST files
 and rendered documentation for the particular library.

Ref: NCSDK-11624

Signed-off-by: Richa Pandey <richa.pandey@nordicsemi.no>

2022-01-24 11:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6616
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-06 15:11 UTC, b-gent commented
Leaving a few comments. Also the comments are missing from the following headers:
app_event_manager.h
event_manager_proxy.h
qos.h

2022-05-06 15:12 UTC, b-gent requested changes

2022-05-06 15:12 UTC, b-gent commented on include/app_event_manager_profiler_tracer.h
> + * https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/others/event_manager_profiler_tracer.html.
```suggestion
 * https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/others/app_event_manager_profiler_tracer.html.
```

2022-05-06 15:12 UTC, b-gent commented on include/app_event_manager_profiler_tracer.h
> + * doc/nrf/libraries/others/event_manager_profiler_tracer.rst.
```suggestion
 * doc/nrf/libraries/others/app_event_manager_profiler_tracer.rst.
```

2022-05-09 09:21 UTC, jenseneducation-richa-bajpai commented on include/app_event_manager_profiler_tracer.h
> + * doc/nrf/libraries/others/event_manager_profiler_tracer.rst.
It has 80 characters limit per line so had to break it where it was exceeding.

2022-05-09 09:21 UTC, jenseneducation-richa-bajpai commented on include/gzp_config.h
> + * The RST file for this library can be found in doc/nrf/libraries/gazell/gzp.rst.
Done.

2022-05-09 09:21 UTC, jenseneducation-richa-bajpai commented on include/app_event_manager_profiler_tracer.h
> + * https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/others/event_manager_profiler_tracer.html.
Done.

2022-05-09 09:22 UTC, jenseneducation-richa-bajpai commented on include/app_event_manager_profiler_tracer.h
> + * doc/nrf/libraries/others/event_manager_profiler_tracer.rst.
Done.

2022-05-09 09:44 UTC, richabp commented on include/app_event_manager_profiler_tracer.h
> + * doc/nrf/libraries/others/event_manager_profiler_tracer.rst.
It has 80 characters limit per line so had to break it.

2022-05-09 09:45 UTC, richabp commented on include/gzp_config.h
> + * The RST file for this library can be found in doc/nrf/libraries/gazell/gzp.rst.
Done.

2022-05-09 09:45 UTC, richabp commented on include/app_event_manager_profiler_tracer.h
> + * https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/others/event_manager_profiler_tracer.html.
Done

2022-05-09 09:45 UTC, richabp commented on include/app_event_manager_profiler_tracer.h
> + * doc/nrf/libraries/others/event_manager_profiler_tracer.rst.
Done

2022-12-05 11:13 UTC, gmarull commented
> I personally disagree with this.

Agreed, this is going to be a maintenance hell

2023-01-04 12:52 UTC, closed without merging