doc: Added links to RST files in bluetooth_mesh_2 header files
nrfconnect/sdk-nrf pull request #6667
Opened 2022-01-27 15:34 UTC by richabp

Provided comments in the include/bluetooth/mesh/ header files
part-2 about the location of corresponding RST files and
rendered documentation for the particular library.

Ref: NCSDK-11624

Signed-off-by: Richa Pandey <richa.pandey@nordicsemi.no>

2022-06-26 01:42 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |

**All integration tests**: added because there was no .github/test-spec.yml in 'sdk-nrf'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24599/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-27 09:47 UTC, mia-ko requested changes
Missing updates for light_ctrl_reg.h and light_ctrl_reg_spec.h :)

2022-10-27 12:35 UTC, mia-ko approved these changes
LGTM :)

2022-10-27 12:38 UTC, ludvigsj approved these changes

2022-10-28 09:18 UTC, b-gent approved these changes
Looking great.

2022-10-28 12:04 UTC, merged