lib: nrf_modem: Revert modem trace change from #6471
nrfconnect/sdk-nrf pull request #6691
Opened 2022-01-28 14:19 UTC by gregersrygg

It was assumed that the modem trace was always enabled at boot, but the
modem trace configuration is persisted in the modem periodically and when
using AT+CFUN=0. This caused a regression when the modem did not already
have the modem trace enabled in the persisted configuration. This commit
reverts the changes in lib/lte_link_control/lte_lc.c from #6471 and
corrects the documentation accordingly. Then modem traces should always
be enabled when CONFIG_NRF_MODEM_LIB_TRACE_ENABLED is turned on.

Fixes NCSDK-13500

Signed-off-by: Gregers Gram Rygg <gregers.gram.rygg@nordicsemi.no>

2022-01-28 14:24 UTC, balaji-nordic requested changes

2022-01-28 14:24 UTC, balaji-nordic commented on doc/nrf/libraries/modem/nrf_modem_lib.rst
> +When :kconfig:`CONFIG_NRF_MODEM_LIB_TRACE_ENABLED` Kconfig option is enabled, the modem traces are enabled in the modem and forwards it to the `Modem trace module`_.
```suggestion
When :kconfig:`CONFIG_NRF_MODEM_LIB_TRACE_ENABLED` Kconfig option is enabled, the modem traces are enabled in the modem and are forwarded to the `Modem trace module`_.
```

2022-01-28 14:26 UTC, tokangas approved these changes

2022-01-28 14:36 UTC, balaji-nordic approved these changes

2022-01-28 14:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6691
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-01-28 15:08 UTC, lemrey commented
Please wait for @eivindj-nordic review before merging.

2022-01-28 16:04 UTC, eivindj-nordic approved these changes

2022-02-01 09:28 UTC, umapraseeda approved these changes

2022-02-01 10:47 UTC, merged