doc improvement: Minor fixes of documents
nrfconnect/sdk-nrf pull request #6708
Opened 2022-01-31 12:39 UTC by divipillai

Minor fixes on the following files:
nrf_desktop_arch.svg
event_manager.rst
release-notes-changelog.rst

Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>

2022-01-31 13:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6708
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-01 05:54 UTC, Avalei requested changes

2022-02-01 05:54 UTC, Avalei commented on doc/nrf/libraries/others/event_manager.rst
> +	There is a deprecated way of logging Event Manager events by writing string to the provided buffer which is supported until few future releases of |NCS|.
Is "few" the right word here? Or is that maybe supposed to be "new"

2022-02-01 08:28 UTC, divipillai commented
The change log entry has been removed because it will be addressed in a future PR.

2022-02-01 09:40 UTC, Avalei approved these changes

2022-02-01 13:00 UTC, umapraseeda approved these changes

2022-02-01 13:11 UTC, merged