doc improvement: style fixes in NFC samples
nrfconnect/sdk-nrf pull request #6712
Opened 2022-02-01 07:13 UTC by peknis

Fixed inconsistencies in spelling and structure

Ref: NCSDK-13404

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2022-02-01 07:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6712
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-01 08:59 UTC, dchat-nordic requested changes

2022-02-01 08:59 UTC, dchat-nordic commented on samples/nfc/system_off/README.rst
> +When using the registers to wake up the device, replase :c:func:`start_nfc()` with the following function:
```suggestion
When using the registers to wake up the device, replace :c:func:`start_nfc()` with the following function:
```

2022-02-01 09:04 UTC, dchat-nordic approved these changes

2022-02-02 20:54 UTC, mbolivar-nordic approved these changes

2022-02-03 08:18 UTC, merged