doc: nrf: add section comparing MQTT and REST
nrfconnect/sdk-nrf pull request #6745
Opened 2022-02-02 19:26 UTC by jayteemo

Add section to the nRF Cloud documentation that describes and
compares MQTT and REST so that a user can choose the correct
protocol for their project.
CIA-518

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2022-02-02 19:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6745
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-02 22:51 UTC, plskeggs approved these changes

2022-02-03 07:04 UTC, peknis requested changes

2022-02-03 07:04 UTC, peknis commented on doc/nrf/ug_nrf_cloud.rst
> +* Each REST transaction contains HTTP headers, including the JWT, and any API specific payload.
```suggestion
REST overview
=============

* The device initiates a TLS connection to nRF Cloud.
* nRF Cloud supports a connection keep-alive/idle time of 60 seconds for REST API sockets.
* For authentication, the device must send a JSON Web Token (JWT) with each REST transaction. 
  The JWT is approximately 450 bytes, but can be larger depending on the claims.
* Each REST transaction contains HTTP headers, including the JWT, and any API specific payload.
```

2022-02-03 07:04 UTC, peknis commented on doc/nrf/ug_nrf_cloud.rst
> +* Each MQTT publish event contains the MQTT topic and the payload.
```suggestion
MQTT overview
=============

* The device initiates a mutual-TLS (mTLS) connection to the nRF Cloud MQTT broker.
* The MQTT keep-alive time can be set by the device and can be longer than 60s.
* Device authentication through mTLS lasts throughout the MQTT connection.
* Once connected, the device subscribes to the desired MQTT topics.
* Each MQTT publish event contains the MQTT topic and the payload.
```

2022-02-03 07:04 UTC, peknis commented on doc/nrf/ug_nrf_cloud.rst
> +REST may be preferred if a device sends data infrequently or does not need to receive unsolicited data from the cloud.
How about having this information right after the considerations below?

2022-02-03 07:32 UTC, peknis requested changes

2022-02-03 07:32 UTC, peknis commented on doc/nrf/ug_nrf_cloud.rst
> +MQTT has a higher (data/power) cost to setup a connection.  However, the data size per MQTT publish event is smaller than a comparable REST transaction.
```suggestion
MQTT has a higher (data/power) cost to set up a connection.  However, the data size of a MQTT publish event is smaller than a comparable REST transaction.
```

2022-02-03 07:48 UTC, jtguggedal approved these changes
This is very useful, thanks!

2022-02-04 06:16 UTC, peknis approved these changes

2022-02-04 08:02 UTC, merged