sample: nrf9160: lwm2m_client: Add shell cmd to turn off modem
nrfconnect/sdk-nrf pull request #6749
Opened 2022-02-03 09:21 UTC by eibe85

Carriers are not happy with us for not shutting down modem properly
during testing. This code will allow us to detach from network cleanly
during testing. Strictly speaking something like this would be nice to
add as a library function that could be added to samples with a Kconfig.

Signed-off-by: Eivind Berntsen <eivind.berntse@nordicsemi.no>

2022-02-03 09:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6749
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-03 11:18 UTC, VeijoPesonen requested changes

2022-02-03 11:18 UTC, VeijoPesonen commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +SHELL_CMD_REGISTER(shutdown_modem, NULL, "Turn off modem to do a clean detaach from carreir network", cmd_shutdown_modem);
I don't know if this plays perfectly with the client but I assume solving a real issue is the thing here.

2022-02-03 11:23 UTC, rlubos reviewed
I agree it'd be best to have some generic shell module to deal with the modem, but as a temporary solution for the sample this seems ok (unless we start duplicating the solution across the samples).

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> + * Copyright (c) 2021 Nordic Semiconductor ASA
2022

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +    int err = 0;
You should use tab for indentation.

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +
One empty line is enough.

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +      printk("The modem powered off\n");
You should rather use `shell_print()` as this is the response for the command.

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +        printk("\n***** WARNING! Modem did not shutdown correctly. error: %d *****\n", err);
ditto

2022-02-03 11:23 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/shell_cmds/shell_cmds.c
> +SHELL_CMD_REGISTER(shutdown_modem, NULL, "Turn off modem to do a clean detaach from carreir network", cmd_shutdown_modem);
nit, but perhaps `modem_shutdown` would be a better command - easier to find alphabetically.

2022-03-03 14:46 UTC, SeppoTakalo commented
This should not be LwM2M specific.
I proposed similar in https://github.com/nrfconnect/sdk-nrf/pull/7054 so that any application that uses shell is benefiting those.

2022-04-19 05:36 UTC, VeijoPesonen commented
Replaced with PR #7054

2022-04-19 05:36 UTC, closed without merging