doc: Add known issue with radio notifications
nrfconnect/sdk-nrf pull request #6786
Opened 2022-02-07 09:32 UTC by Tschet1

Report a known issue about the use of radio notifications on the ACTIVE
signal when the high frequency clock is running.

Signed-off-by: Jan Müller <jan.mueller@nordicsemi.no>

2022-02-07 09:34 UTC, Tschet1 commented
Note here, this will also be present for 1.9. I did not add the 1.9 Tag, since I think that will be updated automatically once that is released.

2022-02-07 09:49 UTC, rugeGerritsen requested changes

2022-02-07 09:49 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +
Usually we put newer asserts on the top of the list.

2022-02-07 09:49 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +.. rst-class:: v1-8-0 v1-7-1 v1-7-0 v1-6-1 v1-6-0 v1-5-2 v1-5-1 v1-5-0 v1-4-2 v1-4-1 v1-4-0
It would be nice if you could add NCS 1.9 now

2022-02-07 09:49 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +**Workaround**: use radio notifications on nACTIVE.
Please indent and format the line containing "**Workaround**" as done for other known issues. That ensures proper formatting when the documentation is generated.

2022-02-07 09:49 UTC, rugeGerritsen commented on doc/nrf/known_issues.rst
> +  **Workaround**: use radio notifications on nACTIVE.
```suggestion
  **Workaround**: Use radio notifications on nACTIVE.
```

2022-02-07 10:00 UTC, rugeGerritsen approved these changes

2022-02-07 10:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6786
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-07 12:45 UTC, rugeGerritsen approved these changes

2022-02-08 08:22 UTC, wiba-nordic approved these changes
Looks good.

2022-02-08 08:34 UTC, merged