doc improvement: style fixes in Other samples
nrfconnect/sdk-nrf pull request #6797
Opened 2022-02-07 13:52 UTC by richabp

Fixed inconsistencies in style and structure in
UART, Radio Test, BH1749, and Hello World samples.

Ref: NCSDK-13404

Signed-off-by: Richa Pandey <richa.pandey@nordicsemi.no>

2022-02-07 14:11 UTC, kapi-no approved these changes

2022-02-07 14:28 UTC, peknis requested changes

2022-02-07 14:28 UTC, peknis commented on samples/peripheral/radio_test/README.rst
> +After programming the sample to your development kit, test it by performing the folowing steps in one of two ways:
```suggestion
After programming the sample to your development kit, complete the following steps to test it in one of the following two ways:
```

2022-02-07 14:28 UTC, peknis commented on samples/peripheral/radio_test/README.rst
>  #. Run the following commands on one of the kits:
You also need an empty line before starting another list within a list.

2022-02-07 14:28 UTC, peknis commented on samples/sensor/bh1749/README.rst
>  Sample Output
```suggestion
Sample output
```

2022-02-07 14:28 UTC, peknis commented on samples/peripheral/radio_test/README.rst
> +You can run the tests by connecting to the development kit through the serial port and sending shell commands.
```suggestion
To run the tests, connect to the development kit through the serial port and send shell commands.
```

2022-02-07 14:28 UTC, peknis commented on samples/peripheral/radio_test/README.rst
> +The sample starts with enabling the high frequency crystal oscillator and configuring the shell.
```suggestion
The sample first enables the high frequency crystal oscillator and configures the shell.
```

2022-02-07 14:28 UTC, peknis commented on samples/peripheral/lpuart/README.rst
> +It has console and logging disabled by default, to demonstrate low power consumption while having UART active.
```suggestion
By default, the console and logging are disabled to demonstrate low power consumption when UART is active.
```

2022-02-07 14:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6797
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-08 06:33 UTC, peknis approved these changes

2022-02-08 08:08 UTC, merged