event_manager:  Change logging in Event Manager
nrfconnect/sdk-nrf pull request #6811
Opened 2022-02-08 16:21 UTC by zycz

Change how log function is recognised by event manager to
better support new events loggging.

Jira: NCSDK-13770

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2022-02-09 08:46 UTC, simensrostad reviewed
Since `native_posix.conf` in `applications/asset_tracker_v2/tests/debug_module/boards/` no longer contains any code, the `.../debug_module/boards/` folder can be removed.

native_posix.conf`

2022-02-24 08:39 UTC, pdunaj commented on subsys/event_manager/event_manager_priv.h
> +		.log_event_func_dep = ((IS_ENABLED(CONFIG_LOG) && Z_C_GENERIC) ?		\
the disadvantage is that it will use additional memory - it will impact smaller devices

2022-03-01 15:43 UTC, MarekPieta commented on applications/asset_tracker_v2/src/modules/modules_common.c
> +		if (event->log_event_func_dep) {
We should also use ifdef here. I would also change order, because in general we should rely on the new implementation

2022-03-01 15:43 UTC, MarekPieta commented on include/event_manager.h
> + * @retval    0 If the operation was successful. Error values can be added by user.
`true if event was consumed and should not be propagated to other listeners, false otherwise.`

2022-03-01 15:43 UTC, MarekPieta commented on subsys/event_manager/Kconfig
> +	bool "Enables tracing information"
I think we should select it when we enable profiling event manager events (that would simplify configuration)

2022-03-01 15:43 UTC, MarekPieta commented on subsys/event_manager/Kconfig
>  	default 128
depends on EVENT_MANAGER_USE_DEPRECATED_LOG_FUN

2022-03-01 15:43 UTC, MarekPieta commented on applications/asset_tracker_v2/src/modules/modules_common.c
> +		if (event->log_event_func_dep) {
The same related to changes in line 50

2022-03-01 15:43 UTC, MarekPieta commented on subsys/event_manager/event_manager.c
>  	BUILD_ASSERT(CONFIG_EVENT_MANAGER_EVENT_LOG_BUF_LEN != 1);
The same as if a few lines above

2022-03-11 09:21 UTC, divipillai commented on doc/nrf/libraries/others/event_manager.rst
> +	To use it you need to set :kconfig:`CONFIG_EVENT_MANAGER_USE_DEPRECATED_LOG_FUN` Kconfig option.
```suggestion
	To use the deprecated way, you need to set the :kconfig:`CONFIG_EVENT_MANAGER_USE_DEPRECATED_LOG_FUN` option.
```

2022-03-11 09:21 UTC, divipillai commented on doc/nrf/libraries/others/event_manager.rst
> +	You can then use both ways of logging and event manager will figure out which way is used based on the type of the logging function passed.
```suggestion
	You can then use both ways of logging events.
	Event manager figures out which way to be used based on the type of the logging function passed.
```

2022-03-11 16:10 UTC, divipillai approved these changes

2022-03-11 17:00 UTC, pdunaj approved these changes

2022-03-14 14:20 UTC, MarekPieta requested changes

2022-03-14 14:20 UTC, MarekPieta commented on subsys/event_manager/event_manager.c
> +#else
Shouldn't we support both cases here? It seems like only deprecated way of logging is supported here.

2022-03-14 14:20 UTC, MarekPieta commented on applications/asset_tracker_v2/src/modules/modules_common.c
> +		if (event->log_event_func_dep) {
We should support both ways of logging events here too.

2022-03-14 14:20 UTC, MarekPieta commented on applications/asset_tracker_v2/src/modules/modules_common.c
> +		if (event->log_event_func_dep) {
Support both way of logging here too, please

2022-03-14 14:20 UTC, MarekPieta commented on subsys/event_manager/event_manager_priv.h
> +		.log_event_func = log_fun,
Fix alignment, please.

2022-03-14 14:20 UTC, MarekPieta commented on subsys/event_manager/event_manager_priv.h
> +#define _EVENT_TYPE_DEFINE_LOG_FUN(log_fun)						\
Consider emitting build warning if user tries to use deprecated logging function, but the CONFIG_EVENT_MANAGER_USE_DEPRECATED_LOG_FUN=n. With current implementation the log would be silently dropped which could be quite confusing.

2022-03-15 07:20 UTC, MarekPieta requested changes

2022-03-15 07:20 UTC, MarekPieta commented on applications/asset_tracker_v2/prj.conf
> -CONFIG_EVENT_MANAGER_EVENT_LOG_BUF_LEN=0
Please also fix `applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_b0_wwcb.conf`

2022-03-15 07:20 UTC, MarekPieta commented on applications/asset_tracker_v2/src/modules/modules_common.c
> +		if (event->log_event_func_dep) {
Also regarding buf

2022-03-15 08:17 UTC, MarekPieta approved these changes

2022-03-21 10:01 UTC, merged

2022-03-22 09:59 UTC, kapi-no commented
@zycz, it seems that Find My CI was reconfigured for this PR to silently ignore warnings and do not treat them as errors. Are you aware of any such reconfiguration?

This change has caused build failures in Find My CI for other PRs (upmerge PR included) because they normally treat warnings as errors. The Find My repository samples are currently broken on the main NCS branch and cannot build because of this change.

2022-03-22 10:15 UTC, zycz commented
> @zycz, it seems that Find My CI was reconfigured for this PR to silently ignore warnings and do not treat them as errors. Are you aware of any such reconfiguration?
> 
> This change has caused build failures in Find My CI for other PRs (upmerge PR included) because they normally treat warnings as errors. The Find My repository samples are currently broken on the main NCS branch and cannot be built because of this change.

Hi, I have not been aware of such reconfiguration. To solve your problems you have to do one of two options:

1. set config flag which allows using old, deprecated way of logging in all of your applications:  CONFIG_EVENT_MANAGER_USE_DEPRECATED_LOG_FUN=y
2. Change to new logging by delating:  CONFIG_EVENT_MANAGER_EVENT_LOG_BUF_LEN=0 from config and changing logging in event.c files

static int your_event(const struct event_header *eh, char *buf, size_t buf_len) -> static void your_event(const struct event_header *eh)

additionally you have to delated "return 0" from this function. Let me know if any help is needed.