Bluetooth: Mesh: Shell support for light models
nrfconnect/sdk-nrf pull request #6837
Opened 2022-02-09 20:10 UTC by Andrewpini

Adds support for shell interaction with client model instances in a mesh
application.

This includes:
- Light Lightness
- Light CTL
- Light HSL
- Light xyL
- Light LC

Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

2022-02-09 20:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6837
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-10 09:25 UTC, Andrewpini commented
The common functionality is duplicated in several PRs ATM. Please refer to https://github.com/nrfconnect/sdk-nrf/pull/6738 if you have comments regarding the shell_utils module.

2022-02-10 14:09 UTC, Balaklaka commented on subsys/bluetooth/mesh/shell/shell_lc_cli.c
> +	uint32_t time = (argc == 3) ? (uint32_t)strtol(argv[2], NULL, 0) : 0;
Should this be >=, and for the line under.

2022-02-10 14:34 UTC, Balaklaka commented on subsys/bluetooth/mesh/shell/shell_hsl_cli.c
> +	uint32_t time = (argc == 5) ? (uint32_t)strtol(argv[4], NULL, 0) : 0;
```suggestion
	uint32_t time = (argc >= 5) ? (uint32_t)strtol(argv[4], NULL, 0) : 0;
```

2022-02-14 09:42 UTC, Andrewpini commented on subsys/bluetooth/mesh/shell/shell_ctl_cli.c
> +	uint32_t delay = (argc == 6) ? (uint32_t)strtol(argv[5], NULL, 0) : 0;
I guess we could alter this, but the shell module won't accept more than the Maximum arguments anyways. If you think it is important I will change it.

2022-02-14 09:42 UTC, Andrewpini commented on subsys/bluetooth/mesh/shell/shell_ctl_cli.c
> +	int16_t delta = (int16_t)strtol(argv[3], NULL, 0);
Check is done by the shell module.

2022-02-14 09:43 UTC, Andrewpini commented on subsys/bluetooth/mesh/shell/shell_ctl_cli.c
> +{
Check is done by the shell module.

2022-02-14 12:27 UTC, Balaklaka approved these changes

2022-02-15 14:17 UTC, PavelVPV commented on subsys/bluetooth/mesh/shell/shell_lc_cli.c
> +/*
Minor: could the file be renamed to `shell_ctrl_cli.c` so that it follows the same naming as other light controller files?

2022-02-15 17:02 UTC, omkar3141 requested changes

2022-02-15 17:02 UTC, omkar3141 commented on subsys/bluetooth/mesh/shell/shell_utils.c
> +/*
You can remove this (and corresponding header) file from PR after generic PR gets merged and only retain changes.

2022-02-16 13:58 UTC, PavelVPV approved these changes

2022-02-17 13:11 UTC, omkar3141 approved these changes

2022-02-18 07:37 UTC, trond-snekvik approved these changes

2022-02-18 11:33 UTC, merged