doc: nrf_desktop: minor fwupd doc fixes
nrfconnect/sdk-nrf pull request #6857
Opened 2022-02-10 14:20 UTC by greg-fer

Updated fwupd section with minor changes.
Added link source group for LVFS.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2022-02-10 14:54 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6857
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-10 15:32 UTC, divipillai approved these changes

2022-02-11 15:52 UTC, pdunaj requested changes

2022-02-11 15:52 UTC, pdunaj commented on applications/nrf_desktop/README.rst
> +* ``[HIDRAW\VEN_1915&DEV_52DE]`` - This line describes the method of communication (``HIDRAW`` selects communication using ``HID`` reports), vendor, and device identifiers.
I think we need to rephrase it. If we have open window for documentation update let's do it now.

` - This line describes OS provided device instance id that identifies the device`

2022-02-11 15:52 UTC, pdunaj commented
@shantha-14 @greg-fer , can we get this in 1.9 doc?

2022-02-14 12:31 UTC, pdunaj approved these changes

2022-02-14 12:53 UTC, shantha-14 approved these changes

2022-02-14 12:54 UTC, pdunaj commented
I the end it will get into NCS1.9?

2022-02-14 12:58 UTC, merged