samples: edge_impulse: wrapper: Run Edge Impulse sample in CI
nrfconnect/sdk-nrf pull request #6875
Opened 2022-02-11 11:58 UTC by alstrzebonski

Modifies Edge Impulse CI test.
Earlier, the test was build-only.
Now, the sample runs in CI and the test checks whether classification is
conducted correctly.
To be specific, the test checks whether:
  - sine classification value is greater than or equal to 0.9 and less
    than 1.1,
  - triangle and idle classification values are greater than or equal to
    0 and less than 0.1,
  - Anomaly value is negative.

Jira: NCSDK-12471

Signed-off-by: Aleksander Strzebonski <aleksander.strzebonski@nordicsemi.no>

2022-02-11 12:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6875
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-15 11:48 UTC, MarekPieta requested changes

2022-02-15 11:48 UTC, MarekPieta commented on samples/edge_impulse/wrapper/sample.yaml
> +     - ".*Anomaly: -.*"
Please remove comment that anomaly must be negative from commit message too.

2022-02-23 15:33 UTC, MarekPieta approved these changes

2022-02-24 08:33 UTC, pdunaj approved these changes

2022-02-24 09:55 UTC, merged