samples: bluetooth: direct_test_mode: Fix CTE disable handling
nrfconnect/sdk-nrf pull request #6876
Opened 2022-02-11 12:08 UTC by KAGA164

This fixes handling CTE disable command parameter.
Now it can handled even by the devices that don't support
CTE, it also improves handling CTE disable parameter on
the devices supporting the CTE.

2022-02-11 12:43 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6876
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-11 13:50 UTC, grochu approved these changes
Looks good to me.

2022-02-22 11:17 UTC, peknis requested changes

2022-02-22 11:17 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Fixed handling disable Constant Tone Extension command.
```suggestion
    * Fixed handling of the disable Constant Tone Extension command.
```

2022-02-22 12:36 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Fixed handling disable Constant Tone Extension command.
Done

2022-02-22 13:05 UTC, peknis approved these changes

2022-02-22 15:34 UTC, kapi-no approved these changes

2022-02-23 08:15 UTC, merged