tfm: Enable testing of cipher mode CFB
nrfconnect/sdk-nrf pull request #6878
Opened 2022-02-11 12:41 UTC by andvib

Enable the CFB mode for TF-M Regression tests

Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>

2022-02-11 12:49 UTC, joerchan reviewed
Nitpicking

2022-02-11 12:49 UTC, joerchan commented on modules/tfm/tfm/boards/nrf5340_cpuapp/config.cmake
> +set(TFM_CRYPTO_TEST_ALG_CFB             ON          CACHE BOOL      "Test CFB cryptography mode")
```suggestion
set(TFM_CRYPTO_TEST_ALG_CFB             ON           CACHE BOOL      "Test CFB cryptography mode")
```

2022-02-11 12:49 UTC, joerchan commented on modules/tfm/tfm/boards/nrf9160/config.cmake
> +set(TFM_CRYPTO_TEST_ALG_CFB             ON         CACHE BOOL      "Test CFB cryptography mode")
```suggestion
set(TFM_CRYPTO_TEST_ALG_CFB             ON          CACHE BOOL      "Test CFB cryptography mode")
```

2022-02-11 12:52 UTC, SebastianBoe commented
It will still be disabled for normal non-test builds, right?

2022-02-11 13:46 UTC, SebastianBoe requested changes
clarification requested

2022-02-11 14:29 UTC, andvib commented
> It will still be disabled for normal non-test builds, right?

Yes, the define is only referenced in the test code

2022-02-11 14:36 UTC, SebastianBoe approved these changes

2022-02-14 10:55 UTC, joerchan requested changes
Since the tests is not supported by all backends (cryptocell for example) and the cipher is not recommended let us keep the test disabled.

2022-02-14 11:48 UTC, closed without merging