samples: bluetooth: direct_test_mode: Do not reset fem parameters
nrfconnect/sdk-nrf pull request #6880
Opened 2022-02-11 13:43 UTC by KAGA164

Do not reset front-end module parameters like antenna,
gain, delay on the DTM Reset command. Testers like
Anritsu issues the DTM Reset command at every test
begging. So testing with different than default parameters
was not possible for aytomatic script testing.

2022-02-11 13:57 UTC, grochu reviewed
I added doc-only comments.

2022-02-11 14:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6880
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-11 14:20 UTC, peknis requested changes

2022-02-11 14:20 UTC, peknis commented on samples/bluetooth/direct_test_mode/README.rst
> +  If you change default front-end module parameters, you can restore it by sending ``FEM_DEFAULT_PARAMS_SET`` command or by power cycling your front-end module.
```suggestion
  Front-end module configuration parameters, such as antenna output, gain, and active delay, are not set to their default values after the DTM reset command.
  Testers, for example Anritsu MT885, issue a reset command in the beginning of every test.
  Therefore, you cannot run automated test scripts for front-end modules with other than the default parameters.
  
  If you have changed the default parameters of the front-end module, you must restore them.
  You can either send the ``FEM_DEFAULT_PARAMS_SET`` command or power cycle the front-end module.
```

2022-02-22 10:16 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/README.rst
> +  If you change default front-end module parameters, you can restore it by sending ``FEM_DEFAULT_PARAMS_SET`` command or by power cycling your front-end module.
Fixed

2022-02-22 10:16 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/README.rst
> +* If the Length field is set to ``6`` (symbol ``FEM_DEFAULT_PARAMS_SET``) and the Frequency filed is set to any value, the front-end module parameters like antenna output, gain, delay will be set to
Fixed

2022-02-22 10:16 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/README.rst
> +  If you change default front-end module parameters, you can restore it by sending ``FEM_DEFAULT_PARAMS_SET`` command or by power cycling your front-end module.
Done

2022-02-22 10:16 UTC, KAGA164 commented on samples/bluetooth/direct_test_mode/README.rst
> +* If the Length field is set to ``6`` (symbol ``FEM_DEFAULT_PARAMS_SET``) and the Frequency filed is set to any value, the front-end module parameters like antenna output, gain, delay will be set to
Done

2022-02-22 10:47 UTC, grochu approved these changes

2022-02-22 11:26 UTC, peknis requested changes

2022-02-22 11:26 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Added the ``FEM_DEFAULT_PARAMS_SET`` Vendor specific command for restoring default Front-end module parameters.
```suggestion
    * Added the vendor-specific ``FEM_DEFAULT_PARAMS_SET`` command for restoring the default Front-end module parameters.
```

2022-02-22 11:27 UTC, peknis requested changes

2022-02-22 11:27 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * The Front-end module test parameters are not set to their default value after the DTM reset command.
```suggestion
    * The front-end module test parameters are not set to their default value after the DTM reset command.
```

2022-02-22 12:51 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Added the ``FEM_DEFAULT_PARAMS_SET`` Vendor specific command for restoring default Front-end module parameters.
Done

2022-02-22 12:51 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +    * The Front-end module test parameters are not set to their default value after the DTM reset command.
Done

2022-02-22 13:06 UTC, peknis approved these changes

2022-02-22 15:35 UTC, kapi-no approved these changes

2022-02-23 11:20 UTC, merged