applications: asset_tracker_v2: send config if missing from shadow
nrfconnect/sdk-nrf pull request #6900
Opened 2022-02-14 19:17 UTC by jayteemo

If the shadow does not contain a config section, send reported
config once the cloud is connected.
CIA-547

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2022-02-14 19:20 UTC, jayteemo commented
for nrf cloud, when a new device is added there is no config section in the shadow.
this was noticed when testing the new config card on nrf cloud.

not sure if this change would affect other cloud backends, so i added the ifdef around the actual config send.
let me know if you have a better way to solve this.

2022-02-16 08:02 UTC, simensrostad commented
> for nrf cloud, when a new device is added there is no config section in the shadow. this was noticed when testing the new config card on (dev) nrf cloud.
> 
> not sure if this change would affect other cloud backends, hence the ifdef around the actual config send. let me know if you have a better way to solve this.

This can be aligned with the other cloud integrations by updating the nRF library to always forward the content of the device shadow to the application. Then the application can determine if any of the content in the shadow is of interest and decide to act on that. This would also accommodate for applications that uses different naming/structures in the device shadow. (Right now the shadow state is only forwarded if `config` if I'm not mistaken?

In the ATv2, If the device shadow/twin does not contain any configuration values (parsed in the app codec), we explicitly act on that by sending all the current configuration values.

2022-02-16 08:15 UTC, jayteemo commented
Correct only config gets sent.
I initially did update the nrf_cloud lib to send the full shadow but since the cloud is not in a fully connected state, atv2 fails to send the config.

2022-02-16 20:42 UTC, jayteemo commented
@simensrostad I updated nrf_cloud lib to always send shadow data and to allow shadow updates earlier in the connection process.

2022-02-16 21:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6900
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-17 15:02 UTC, simensrostad approved these changes
LGTM

2022-02-18 07:28 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * For nRF Cloud builds, the configuration section in the shadow will now be initialized during the cloud connection process.
```suggestion
  * For nRF Cloud builds, the configuration section in the shadow is now initialized during the cloud connection process.
```

2022-02-21 07:34 UTC, peknis requested changes

2022-02-21 07:34 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +      * The application can now send shadow updates earlier in the connection process.
```suggestion
* :ref:`lib_nrf_cloud` library:

  * Updated:

     * During the connection process, shadow data is sent to the application even if no "config" section is present.
     * The application can now send shadow updates earlier in the connection process.
```
Just minor alignments

2022-02-21 08:00 UTC, peknis approved these changes

2022-02-23 01:26 UTC, carlescufi commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6900
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-23 09:03 UTC, jtguggedal approved these changes

2022-02-24 07:59 UTC, merged