doc: Remove Getting Started Assistant documentation
nrfconnect/sdk-nrf pull request #6909
Opened 2022-02-15 11:08 UTC by divipillai

Remove Getting Started Assistant from nRF Connect SDK
documentation as Getting Started Assistant tool is deprecated.
NCSDK-13800

Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>

2022-02-15 11:19 UTC, divipillai commented on doc/nrf/gs_assistant.rst
> +On Linux, use the `Installing using Visual Studio Code`_ or follow the steps found on the :ref:`gs_installing` page.
Do we need to mention about Visual Studio Code here as the user will be redirected to same gs_installing page from the Visual Studio Code. Thoughts?

2022-02-17 08:56 UTC, Avalei requested changes

2022-02-17 08:56 UTC, Avalei commented on doc/nrf/gs_assistant.rst
> +On Linux, use the `Installing using Visual Studio Code <Installing on Linux_>`_ or follow the steps found on the :ref:`gs_installing` page.
Having "the" before the link currently sounds a little strange. I would suggest the following:

```suggestion
On Linux, use the `Installing using Visual Studio Code <Installing on Linux_>`_ instructions or follow the steps found on the :ref:`gs_installing` page.
```

2022-02-17 08:56 UTC, Avalei commented on doc/nrf/releases/release-notes-changelog.rst
> +    Linux users can use the `Installing using Visual Studio Code <Installing on Linux_>`_ or follow the steps on the :ref:`gs_installing` page for |NCS| installation.
Same as the previous note.

```suggestion
    Linux users can use the `Installing using Visual Studio Code <Installing on Linux_>`_ instructions or follow the steps on the :ref:`gs_installing` page for |NCS| installation.
```

2022-02-22 09:03 UTC, greg-fer reviewed
Just one comment.

2022-02-22 09:03 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    Linux users can use the `Installing using Visual Studio Code <Installing on Linux_>`_ instructions or follow the steps on the :ref:`gs_installing` page for |NCS| installation.
```suggestion
    Linux users can install the |NCS| by using the `Installing using Visual Studio Code <Installing on Linux_>`_ instructions or by following the steps on the :ref:`gs_installing` page.
```

2022-02-22 12:26 UTC, greg-fer approved these changes

2022-02-22 13:01 UTC, merged