manifest: update HomeKit revision
nrfconnect/sdk-nrf pull request #6984
Opened 2022-02-23 13:47 UTC by RobertGalatNordic

- [ ] https://github.com/nrfconnect/sdk-homekit/pull/329

Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>

2022-02-23 14:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6984
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-24 08:00 UTC, mariuszpos approved these changes

2022-02-24 08:01 UTC, pjasinski990 approved these changes

2022-02-24 08:58 UTC, tejlmand approved these changes

2022-02-24 13:13 UTC, b-gent requested changes

2022-02-24 13:13 UTC, b-gent commented on doc/nrf/known_issues.rst
> +KRKNWK-13095: Change in KVS key naming scheme caused error for updated devices
```suggestion
KRKNWK-13095: Change in KVS key naming scheme causes an error for updated devices.
```

2022-02-24 13:13 UTC, b-gent commented on doc/nrf/known_issues.rst
> +  Previous implementation allowed for empty key in domain, during refactoring this has been restricted.
```suggestion
  A previous implementation allowed for empty key in domain.
  This has been restricted during refactoring.
```

2022-02-25 09:55 UTC, b-gent approved these changes

2022-02-25 11:22 UTC, merged