doc: update some sample docs to use VT100/ANSI supported serial terminal.
nrfconnect/sdk-nrf pull request #6995
Opened 2022-02-24 14:54 UTC by divipillai

As per NCSDK-14045 task, we have added instruction to use
serial terminal that supports VT100/ANSI characters in the following
samples as the shell used in these samples uses these special characters:

../../samples/bluetooth/mesh/chat/sample_description.rst
../../samples/bluetooth/throughput/README.rst
../../samples/matter/light_bulb/README.rst
../../samples/matter/light_switch/README.rst
../../samples/matter/lock/README.rst
../../samples/matter/template/README.rst
../../samples/nrf9160/download/README.rst
../../samples/nrf9160/memfault/README.rst
../../samples/nrf9160/modem_shell/README.rst
../../samples/openthread/cli/README.rst
../../samples/openthread/coap_client/README.rst
../../samples/openthread/coap_server/README.rst
../../samples/peripheral/radio_test/README.rst

Please refer to the Jira ticket NCSDK-14045 for more information.

Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>

2022-02-24 15:15 UTC, divipillai commented
@kapi-no , @lmaciejonczyk, @rlubos , @edmont , @canisLupus1313 , @lemrey , @Damian-Nordic , @kkasperczyk-no , @trond-snekvik , @alwa-nordic , @KAGA164 - Please confirm do we need this instruction in the samples you own. The change is made as per the Jira ticket NCSDK-14045.

2022-02-24 15:26 UTC, edmont approved these changes
:thumbsup: for the Thread part.

2022-02-24 15:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-6995
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-02-25 06:19 UTC, wiba-nordic requested changes
One extra comma. Plus a question from me.

2022-02-25 06:19 UTC, wiba-nordic commented on samples/openthread/coap_client/README.rst
> +You can observe the sample logging output through a serial port, |ANSI|.
```suggestion
You can observe the sample logging output through a serial port |ANSI|.
```
"a serial port that supports VT100/ANSI escape characters" sounds odd. Should this part and CoAP server also mention terminal emulator?

2022-02-25 08:10 UTC, canisLupus1313 approved these changes

2022-02-25 08:22 UTC, wiba-nordic approved these changes

2022-02-25 09:47 UTC, Damian-Nordic approved these changes

2022-02-25 09:52 UTC, KAGA164 approved these changes

2022-03-02 12:57 UTC, gregersrygg approved these changes
LGTM 👍  Thank you :)

2022-03-04 09:36 UTC, merged