Rework credential management on LwM2M client library
nrfconnect/sdk-nrf pull request #7025
Opened 2022-03-01 12:17 UTC by SeppoTakalo

Store credentials and settings

LwM2M client utilities library will now independently handle
storage of credentials to modem and other security settings
to permanent storage. This includes various resources from
LwM2M objects server (ID 1) and security (ID 0).

Client utilities installs load_credentials hook into
client contexts and handles modem keys on this hook.
There is a side effect, that we might need to turn the modem
offline, if keys need to be updated.

For permanent storage, we use Zephyr's settings API.
We install create&destroy hooks into LwM2M engine for
security and server objects. When such object is created,
we install post-write hook on each of the resources we care about.

From Server object, we monitor resources:
* ID 0, Short Server ID
* ID 1, Lifetime

From Security object, we monitor:
* ID 0, LWM2M Server URI
* ID 2, Security mode
* ID 3, PSK Identity
* ID 4, Server Public key
* ID 10, Short Server ID

When we receive this data from Bootstrap server, our hooks
ensure that creted objects end up written in the permanent storage.
When client connection is started, the PSK from security object is
written to the modem. PSK is never written into settings storage
and after a reboot, it is not readable anymore.

On a reboot, we load these stored objects from settings storage,
and create them into LwM2M engine. Separate API has published
to allow application to check, whether we have client certificates
already, or if we need to bootstrap.

This PR contains changes from:
https://github.com/nrfconnect/sdk-nrf/pull/7023

2022-03-01 12:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7025
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-02 07:52 UTC, jheiskan81 approved these changes

2022-03-02 11:32 UTC, VeijoPesonen commented
I propose that we would introduce our own overlay files for Leshan and Coiote configurations. Both could have bootstrap and queue mode configs but as commented out. Just add instructions there that by uncommenting those sections both features can be turned on.

2022-03-02 13:18 UTC, VeijoPesonen requested changes

2022-03-02 13:18 UTC, VeijoPesonen commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
> +if (type == MODEM_KEY_MGMT_CRED_TYPE_PSK) {
Indentation.

2022-03-02 13:18 UTC, VeijoPesonen commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
> +		LOG_ERR("Failed to read modem functinal mode");
Typo

2022-03-02 14:24 UTC, rlubos reviewed
I think this change merits an entry in the changelog.

2022-03-02 14:24 UTC, rlubos commented
@umapraseeda Please reassign if lwm2m docs should be handled by someone else.

2022-03-03 13:39 UTC, SeppoTakalo commented on samples/nrf9160/lwm2m_client/src/main.c
> +		if (IS_ENABLED(CONFIG_LWM2M_RD_CLIENT_SUPPORT_BOOTSTRAP) &&
Actually, this is already checked there, so I can drop the `IS_ENABLED()` test.

2022-03-04 11:22 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
> +		LOG_ERR("Failed to read modem functinal mode");
fixed.

2022-03-04 11:22 UTC, SeppoTakalo commented on samples/nrf9160/lwm2m_client/overlay-ci.conf
> +CONFIG_LWM2M_CLIENT_UTILS_SERVER="passci"
Removed the overlay-ci.conf

2022-03-04 11:23 UTC, SeppoTakalo commented on samples/nrf9160/lwm2m_client/src/main.c
> +		/* it is the bootstrap PSK. In normal mode, it is the server key */
fixed.

2022-03-04 11:23 UTC, SeppoTakalo commented on subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
> +	ret = write_credential_type(ctx, SECURITY_SECRET_KEY_ID, MODEM_KEY_MGMT_CRED_TYPE_PSK);
`ret` was supposed to be returned. but I just realized that I have added functionality after this one, so it did not match the intention any more.
Fixed now

2022-03-04 12:31 UTC, VeijoPesonen approved these changes
Looks good to me

2022-03-07 11:53 UTC, umapraseeda approved these changes

2022-03-11 10:35 UTC, rlubos approved these changes

2022-03-11 10:36 UTC, rlubos commented
@SeppoTakalo sorry for the delay, I've lost the PR from my radar, could you please rebase to resolve the conflict?

2022-03-11 12:56 UTC, merged