samples: nrf9160: lwm2m_client: Fix boostrap documentation
nrfconnect/sdk-nrf pull request #7027
Opened 2022-03-01 12:37 UTC by SeppoTakalo

Documented steps for Leshan bootstrap server fixed.

2022-03-01 13:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7027
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-02 09:53 UTC, VeijoPesonen approved these changes
Looks good to me

2022-03-02 10:06 UTC, umapraseeda requested changes

2022-03-02 10:06 UTC, umapraseeda commented on samples/nrf9160/lwm2m_client/README.rst
> +            If you choose :guilabel:`Pre-shared Key`, add the values for :guilabel:`Identity` and :guilabel:`Key` fields (the configured Key need not match the Bootstrap Server configuration).
```suggestion
            If you choose :guilabel:`Pre-shared Key`, you must add the values for :guilabel:`Identity` and :guilabel:`Key` fields (the configured Key need not match the Bootstrap Server configuration).
```

2022-03-02 10:06 UTC, umapraseeda commented on samples/nrf9160/lwm2m_client/README.rst
> +         #. Click :guilabel:`NEXT` and don't add another Bootstrap server.
```suggestion
         #. Click :guilabel:`NEXT` and do not select :guilabel:`Add a Bootstrap Server`.
```

2022-03-02 10:06 UTC, umapraseeda commented on samples/nrf9160/lwm2m_client/README.rst
> +         #. Click :guilabel:`ADD`
```suggestion
         #. Click :guilabel:`ADD`.
```

2022-03-02 10:06 UTC, umapraseeda commented on samples/nrf9160/lwm2m_client/README.rst
> +            Please note that Coiote bootstrap server automatically creates account for LwM2M server using the same device endpoint name and random PSK key.
```suggestion
            The Coiote bootstrap server automatically creates an account for the LwM2M server using the same device endpoint name and random PSK key.
```

2022-03-02 12:01 UTC, umapraseeda approved these changes

2022-03-02 14:47 UTC, rlubos approved these changes

2022-03-02 14:47 UTC, merged