openthread: remove support for NCP and wpantund
nrfconnect/sdk-nrf pull request #7029
Opened 2022-03-01 13:58 UTC by edmont

Remove support for NCP architecture, making RCP the default.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

2022-03-01 14:00 UTC, rlubos commented
Is this only us dropping the support, or is OT planning to drop NCP as well?

2022-03-01 14:10 UTC, wiba-nordic requested changes
A couple of small improvements.

2022-03-01 14:10 UTC, wiba-nordic commented on doc/nrf/ug_logging.rst
> +To communicate using the Spinel protocol and gather logs, you need one of the `Pyspinel`_ tool:
```suggestion
To communicate using the Spinel protocol and gather logs, you need the `Pyspinel`_ tool:
```

2022-03-01 14:10 UTC, wiba-nordic commented on doc/nrf/ug_thread_commissioning.rst
> +To configure on-mesh Thread commissioning, you need at least two development kits that are compatible with either the CLI or the Coprocessor samples.
```suggestion
To configure on-mesh Thread commissioning, you need at least two development kits that are compatible with either the CLI or the Co-processor samples.
```

2022-03-01 14:10 UTC, wiba-nordic commented on doc/nrf/ug_thread_commissioning.rst
> +The |NCS|'s Thread CLI and Coprocessor samples come with the autostart feature, which means that the devices will form the network automatically without user intervention.
```suggestion
The |NCS|'s Thread CLI and Co-processor samples come with the autostart feature, which means that the devices will form the network automatically without user intervention.
```

2022-03-01 14:10 UTC, wiba-nordic commented on samples/openthread/coprocessor/README.rst
> +Depending on the configuration, the sample uses the :ref:`thread_architectures_designs_cp_rcp` architecture.
```suggestion
The sample uses the :ref:`thread_architectures_designs_cp_rcp` architecture.
```
Alternatively, if it is not mandatory, it's "The sample can be configured to use the :ref:`thread_architectures_designs_cp_rcp` architecture."

2022-03-01 14:18 UTC, lmaciejonczyk reviewed
We should remove Pyspinel parts as it's tool for NCP only.

2022-03-02 07:35 UTC, wiba-nordic requested changes
Noticed one more.

2022-03-02 07:35 UTC, wiba-nordic commented on samples/openthread/coprocessor/README.rst
> +Communication with the development kit it is also supported using `Pyspinel`_ commands.
```suggestion
Communication with the development kit using `Pyspinel`_ commands is also supported.
```

2022-03-02 14:30 UTC, lmaciejonczyk approved these changes

2022-03-03 07:00 UTC, canisLupus1313 commented
@edmont removing the `overlay-rcp.conf` causes the rcp samples to fail build stage there is also a need to change this in testing repo.

2022-03-03 07:02 UTC, canisLupus1313 requested changes

2022-03-03 07:07 UTC, edmont commented
> @edmont removing the `overlay-rcp.conf` causes the rcp samples to fail build stage there is also a need to change this in testing repo.

Yes, the matching CI PR is linked in the description.

2022-03-03 07:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7029
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-03 14:04 UTC, edmont commented
Test are passing for the updated test branch: https://jenkins-ncs.nordicsemi.no/job/latest/job/test-fw-nrfconnect-thread/job/debugging%252Fremove-ncp/4/

2022-03-04 08:36 UTC, canisLupus1313 approved these changes

2022-03-04 10:23 UTC, rlubos approved these changes

2022-03-04 10:23 UTC, merged