IPC service support
nrfconnect/sdk-nrf pull request #7043
Opened 2022-03-03 09:35 UTC by kapi-no

Migrated from the RPMsg service to the IPC service module which is used as inter-core transport mechanism for Bluetooth and 802.15.4 protocols on nRF53 devices.

2022-03-03 09:44 UTC, hubertmis approved these changes

2022-03-04 10:25 UTC, kapi-no commented
This PR change is now part of the Upmerge PR: https://github.com/nrfconnect/sdk-nrf/pull/7050

This PR is now only for validation/verification purposes and will eventually be closed.

2022-03-09 07:56 UTC, KAGA164 requested changes

2022-03-09 07:56 UTC, KAGA164 commented on samples/nrf5340/multiprotocol_rpmsg/src/main.c
> +		LOG_ERR("IPC service instance initialization failed: %d\n", err);
```suggestion
		LOG_ERR("IPC service instance initialization failed: %d", err);
```

2022-03-09 07:56 UTC, KAGA164 commented on subsys/nrf_rpc/nrf_rpc_rpmsg.c
> +struct ipc_ept nrf_rpc_ept;
static ?

2022-03-09 07:56 UTC, KAGA164 commented on subsys/nrf_rpc/nrf_rpc_rpmsg.c
> +struct ipc_ept nrf_rpc_ept;
static ?

2022-03-09 07:56 UTC, KAGA164 commented on subsys/nrf_rpc/nrf_rpc_rpmsg.c
> +		NRF_RPC_ERR("IPC service instance initialization failed: %d\n", err);
```suggestion
		NRF_RPC_ERR("IPC service instance initialization failed: %d", err);
```

2022-03-16 11:21 UTC, DatGizmo commented
With the new Integration Test Specification process we don't need the github labels.
I will remove themI.

Right now this PR runs all Integration tests because it changes sdk-zephyr in west.yml and there is no test-spec.yml in that repo yet.
You can add changes to this PR [nrfconnect/sdk-zephyr#767](https://github.com/nrfconnect/sdk-zephyr/pull/767) to make the test spec here more targeted.

To get the test spec feature working correctly on this PR, you need to rebase it to the latest main to get the [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml) file

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

2022-03-23 15:35 UTC, closed without merging