doc: matter: Added information about Amazon FFS support
nrfconnect/sdk-nrf pull request #7048
Opened 2022-03-03 11:06 UTC by kkasperczyk-no

There is no clear statement in the documentation that Nordic
supports Amazon FFS in Matter and how to enable it.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2022-03-03 11:35 UTC, LuDuda commented on doc/nrf/links.txt
> +.. _`Amazon Frustration-Free Setup`: https://developer.amazon.com/docs/frustration-free-setup/matter-simple-setup-overview.html
```suggestion
.. _`Amazon Frustration-Free Setup (FFS)`: https://developer.amazon.com/docs/frustration-free-setup/matter-simple-setup-overview.html
```

2022-03-03 11:35 UTC, LuDuda commented on doc/nrf/ug_matter_configuring_protocol.rst
> +The nRF Connect platform supports `Amazon Frustration-Free Setup`_ that allows to automatically setup Matter devices and join to Amazon Echo's network.
```suggestion
The nRF Connect platform supports `Amazon Frustration-Free Setup`_ that allows Matter devices to be automatically commissioned to the Matter network, by help of the Matter-enabled Amazon Echo device.
```

2022-03-03 11:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7048
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-03 12:14 UTC, greg-fer requested changes

2022-03-03 12:14 UTC, greg-fer commented on doc/nrf/ug_matter_configuring_protocol.rst
> +
```suggestion

Amazon FFS support
==================

Matter in the |NCS| supports `Amazon Frustration-Free Setup (FFS)`_ that allows Matter devices to be automatically commissioned to the Matter network using the Matter-enabled Amazon Echo device.
To enable the FFS support, set the following configuration options to meet the Amazon FFS setup prerequisites:

* :kconfig:`CONFIG_CHIP_COMMISSIONABLE_DEVICE_TYPE` to ``y``.
* :kconfig:`CONFIG_CHIP_ROTATING_DEVICE_ID` to ``y``.
* :kconfig:`CONFIG_CHIP_DEVICE_TYPE` to the appropriate value, depending on the device used.
  The value must be compliant with the Matter Device Type Identifier.

```

2022-03-03 12:14 UTC, greg-fer commented
Not sure about you, but I would add an entry to changelog for this (Documentation section).

2022-03-03 13:13 UTC, kkasperczyk-no commented
> Not sure about you, but I would add an entry to changelog for this (Documentation section).

@greg-fer ok, I did it.

2022-03-03 13:34 UTC, LuDuda approved these changes

2022-03-04 08:07 UTC, Damian-Nordic approved these changes

2022-03-04 10:43 UTC, greg-fer approved these changes

2022-03-04 11:31 UTC, merged