subsys: dfu_target: Add an API for clearing dfu_target_stream progress
nrfconnect/sdk-nrf pull request #7077
Opened 2022-03-08 13:19 UTC by 57300

Added dfu_target_stream_clear_progress() for resetting the offset to 0
and deleting it from settings (when DFU_TARGET_STREAM_SAVE_PROGRESS=y).
This allows the user to avoid resuming an aborted download.

Signed-off-by: Grzegorz Swiderski <grzegorz.swiderski@nordicsemi.no>

2022-03-08 13:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7077
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-16 14:09 UTC, DatGizmo commented
With the new Integration Test Specification process we don't need the CI-* github labels.
I will remove them.

To get the test spec feature working correctly on this PR, you need to rebase it to the latest main to get the [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml) file

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

2022-03-29 19:43 UTC, hakonfam approved these changes
Would it be possible to add a test case for this? Assuming that the existing test cases are being executed and are passing.

2022-03-29 19:43 UTC, hakonfam commented on subsys/dfu/dfu_target/src/dfu_target_stream.c
> +#endif
nit: can you use `IS_ENABLED` instead? To make the code look better.

```
if (IS_ENABLED(CONFIG_DFU_TARGET_STREAM_SAVE_PROGRESS)) { 
    err = clear_progress();
}
```

2022-04-12 11:37 UTC, FrancescoSer requested changes

2022-04-12 11:37 UTC, FrancescoSer commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Added the :c:func:`dfu_target_stream_clear_progress` function, which resets the offset of the flash stream DFU Target.
Shouldn't this change be mentioned also in dfu_target.rst? (likely inside the note at line 51)

2022-06-26 02:40 UTC, closed without merging

2022-06-26 02:44 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |

**All integration tests**: added because there was no .github/test-spec.yml in 'sdk-nrf'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24630/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*