caf: modules: buttons: use DEVICE_DT_GET_OR_NULL
nrfconnect/sdk-nrf pull request #7089
Opened 2022-03-10 09:15 UTC by gmarull

GPIO ports can be obtained at compile time, so simplify the
implementation by using DEVICE_DT_GET_OR_NULL (since port is optional).

2022-03-10 09:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7089
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-10 10:47 UTC, pdunaj requested changes
this change is very welcomed but will also require change in `applications/nrf_desktop/src/modules/profiler_sync.c`

2022-03-10 12:34 UTC, pdunaj approved these changes

2022-03-10 16:04 UTC, carlescufi approved these changes

2022-03-11 10:26 UTC, merged

2022-03-11 10:54 UTC, MarekPieta commented on applications/nrf_desktop/src/hw_interface/selector_hw.c
> +		if (!device_is_ready(gpio_dev[i])) {
I think we could allow to use selector on devices that e.g. do not use GPIO1 (e.g. if we only connect to pins of GPIO0). Currently we use the module only for nrf52840 based gaming mouse reference design, but customers are free to port it to e.g. smaller SoC if needed.