caf: modules: sensor_manager: use device references
nrfconnect/sdk-nrf pull request #7096
Opened 2022-03-10 12:58 UTC by gmarull

Use `const struct device *` in `struct sm_sensor_config` instead of
device name, since device references can be obtained at compile time
using DEVICE_DT_GET().

Depends on https://github.com/nrfconnect/sdk-nrf/pull/7095 (ignore first 2 commits)

2022-03-11 17:25 UTC, pdunaj approved these changes

2022-03-16 14:06 UTC, DatGizmo commented
With the new Integration Test Specification process we don't need the CI-* github labels.
I will remove them.

To get the test spec feature working correctly on this PR, you need to rebase it to the latest main to get the [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml) file

Then run CI here to update the test spec.

[Information about the test spec feature](https://projecttools.nordicsemi.no/confluence/display/NCS/Test+Spec)
[CI-Help for issues](https://ci-help.nordicsemi.no/)

2022-03-22 08:21 UTC, MarekPieta requested changes

2022-03-22 09:31 UTC, gmarull commented on subsys/caf/modules/sensor_manager.c
> +		if (!device_is_ready(sd->dev)) {
removed the device reference from `sensor_data`, thanks for catching this one.

2022-03-22 09:43 UTC, MarekPieta approved these changes

2022-03-22 20:48 UTC, mbolivar-nordic commented
@gmarull looks like you need another rebase on top of your DK_LIBRARY_INVERT_LEDS fix.

```
[2022-03-22T11:36:08.008Z] /jenkins_workspace/workspace/latest_sdk-nrf_PR-7096/homekit/applications/weather_station/configuration/thingy53_nrf5340_cpuapp/prj.conf:247: warning: attempt to assign the value 'n' to the undefined symbol DK_LIBRARY_INVERT_LEDS
```

2022-03-23 10:24 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/21939/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-03-23 11:49 UTC, merged