samples: Updating notes for central_smp_client readme
nrfconnect/sdk-nrf pull request #7106
Opened 2022-03-11 10:14 UTC by dchat-nordic

Added notes explicitly specifying that this sample
is not intended as device programmer.

Jira: NCSDK-14095

Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>

2022-03-11 10:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7106
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-11 11:36 UTC, peknis requested changes

2022-03-11 11:36 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Notes for :ref:`bluetooth_central_dfu_smp` specifying the intended use for the sample.
```suggestion
  * Notes to the :ref:`bluetooth_central_dfu_smp` sample document specifying the intended use of the sample.
```

2022-03-11 11:36 UTC, peknis commented on samples/bluetooth/central_smp_client/README.rst
> +   The sample is intended to show communication between SMP Client and SMP Server.
```suggestion
   This sample does not provide the means to program a device using DFU.
   It demonstrates the communication between SMP Client and SMP Server.
```

2022-03-11 11:36 UTC, peknis commented on samples/bluetooth/central_smp_client/README.rst
> +   This sample will *not* program the device using DFU.
```suggestion
   This sample does not program the device using DFU.
```

2022-03-11 11:42 UTC, peknis approved these changes

2022-03-17 14:33 UTC, grochu approved these changes
Looks good, it should be clear now, what the sample does.

2022-03-18 10:09 UTC, merged