mcuboot: Add path to mcuboot_CONF_FILE
nrfconnect/sdk-nrf pull request #7157
Opened 2022-03-18 13:23 UTC by osaether

Add path to mcuboot_CONF_FILE

Ref: NCSDK-13548

Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

2022-03-18 13:57 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7157
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-23 14:09 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/21956/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-03-30 07:39 UTC, hakonfam approved these changes
Looks good to me, but I remember there being a lot of discussions around how this works, so we should not merge this until @tejlmand has had his saying.

2022-06-22 08:39 UTC, tejlmand requested changes
Thanks for the proposal, unfortunately this is just a single patch and not a complete solution.

The build system will treat a relative path relative to `APPLICATION_CONFIG_DIR` as seen here:
https://github.com/nrfconnect/sdk-zephyr/blob/d6cd4fc1ceec4bb41c217709c373e5b9ffd05e51/cmake/modules/kconfig.cmake#L217

Per default, `APPLICATION_CONFIG_DIR` is the root of application, but can be adjusted by the CMakeLists.txt of the app or the user.
So if we are not taking that into consideration we might face a similar issue later.

When looking at this, I believe I have also noticed a flaw in how we extract `CONFIG_BOOT_SIGNATURE_KEY_FILE`, cause we extract it from the conf file, so as far as I can tell, we will not detect command line arguments or changes through menuconfig wrt. key file, @hakonfam is that observation correct ?

Would it be possible to fetch the setting from `.config` created in the mcuboot build folder instead ?
From what I can tell, this code is executed after CMake configuration of mcuboot, meaning `mcuboot/.config` ought to be available.

2022-10-25 08:12 UTC, closed without merging