doc: update LwM2M bin lib structure and content
nrfconnect/sdk-nrf pull request #7172
Opened 2022-03-22 14:38 UTC by divipillai

To update the structure of LwM2M bin library
as per the library template. Also, minor updates
on the content.
Jira task: NCSDK-14428

Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>

2022-03-23 08:46 UTC, peknis requested changes

2022-03-23 08:46 UTC, peknis commented on doc/nrf/libraries/bin/lwm2m_carrier/API_documentation.rst
> +LWM2M carrier library API
```suggestion
LwM2M carrier library API
```

2022-03-23 08:46 UTC, peknis commented on doc/nrf/libraries/bin/lwm2m_carrier/API_documentation.rst
> +LWM2M OS layer
```suggestion
LwM2M OS layer
```

2022-03-23 09:13 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7172
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-23 14:01 UTC, peknis requested changes

2022-03-23 14:01 UTC, peknis commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
> +You can enable the library by setting the :kconfig:option:`CONFIG_LWM2M_CARRIER` Kconfig option to ``y``.
```suggestion
Enable the library by setting the :kconfig:option:`CONFIG_LWM2M_CARRIER` Kconfig option to ``y``.
```

2022-03-23 14:10 UTC, peknis approved these changes

2022-03-23 14:39 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/21959/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-03-24 08:25 UTC, nordic-hani approved these changes

2022-03-24 09:42 UTC, umapraseeda approved these changes

2022-03-24 10:15 UTC, merged