samples: zigbee: ncp: use gpio_dt_spec for rst0
nrfconnect/sdk-nrf pull request #7237
Opened 2022-03-30 09:37 UTC by gmarull

Use gpio_dt_spec facilities for the rst0 GPIO pin. Note that set raw
call has been replaced with regular set. Since rst0 is defined as active
low (in nrf52840dongle_nrf52840 board), level is set to '1' (active).

2022-03-31 05:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7237
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-03-31 06:00 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-zigbee | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22137/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-03-31 13:08 UTC, tomchy commented on samples/zigbee/ncp/src/main.c
> +	err = gpio_pin_configure_dt(&rst0, GPIO_OUTPUT_ACTIVE);
This does not seem to be correct. The idea was to set the reset pin to low, so the nRF5 BL will boot, detect the GPIO pin-based reset and start the DFU over USB.

2022-03-31 13:09 UTC, tomchy requested changes
(answered in PR description)

2022-03-31 13:10 UTC, tomchy approved these changes

2022-04-04 07:35 UTC, sebastiandraus approved these changes

2022-04-04 08:37 UTC, merged