samples: nrf9160: modem_shell: add support for MFW v1.3.2 GNSS features
nrfconnect/sdk-nrf pull request #7327
Opened 2022-04-08 11:56 UTC by tokangas

Implemented support for new GNSS features in MFW v1.3.2. This includes several new fields in the PVT notification and a new command "gnss agps expiry" which can be used to query A-GPS data expiry times.

2022-04-08 12:13 UTC, peknis requested changes

2022-04-08 12:13 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +      * Support for MFW v1.3.2 GNSS features.
```suggestion
      * Support for the GNSS features introduced in modem firmware v1.3.2.
```

2022-04-08 12:13 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +        This includes several new fields in the PVT notification and a command to query assistance data expiry times.
```suggestion
        This includes several new fields in the PVT notification and a command to query the expiry times of assistance data.
```

2022-04-08 12:21 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7327
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-08 12:50 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22410/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-08 12:52 UTC, hiltunent approved these changes

2022-04-11 05:27 UTC, jhirsi approved these changes

2022-04-11 10:34 UTC, tokangas commented on doc/nrf/releases/release-notes-changelog.rst
> +      * Support for MFW v1.3.2 GNSS features.
Updated.

2022-04-11 10:34 UTC, tokangas commented on doc/nrf/releases/release-notes-changelog.rst
> +        This includes several new fields in the PVT notification and a command to query assistance data expiry times.
Updated.

2022-04-13 07:44 UTC, peknis approved these changes

2022-04-13 10:35 UTC, merged