application: serial_lte_modem: Support multiple sockets
nrfconnect/sdk-nrf pull request #7354
Opened 2022-04-12 03:00 UTC by junqingzou

Allow to open up to 8 sockets in Socket service.
Add #XSOCKETSELCT to select active socket among opened ones.
Add socket ranking to activate highest-ranked socket when
current active one is closed.
No change to existing Socket AT commands.

Re-implementation of PR#7334

Signed-off-by: Zou <jun.qing.zou@nordicsemi.no>

2022-04-12 03:06 UTC, junqingzou commented
@mgolu PR #7334

2022-04-12 03:25 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7354
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-12 04:02 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22474/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-12 19:37 UTC, mgolu commented
> @mgolu PR #7334

Looks good, thank you!

2022-04-12 20:53 UTC, FrancescoSer requested changes

2022-04-12 20:53 UTC, FrancescoSer commented on applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
> +The read command allows you to check all the opened sockets and the current active one.
This sentence is not that clear. What does the read command do, exactly?

2022-04-13 10:07 UTC, FrancescoSer approved these changes

2022-04-14 01:44 UTC, junqingzou commented
@pirun Thanks for the input. We're going to add an #XPOLL command to poll multiple sockets for incoming data after this PR.

2022-04-14 14:02 UTC, rlubos approved these changes

2022-04-15 16:52 UTC, merged