samples: matter: Disabled BLE+NFC advertising after the device's boot
nrfconnect/sdk-nrf pull request #7359
Opened 2022-04-12 10:33 UTC by ArekBalysNordic

The Lightswitch sample in NRF-SDK should not start BLE+NFC advertising after boot to be compatible with Matter upstream examples.

2022-04-12 10:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7359
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-12 11:31 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22500/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-13 10:45 UTC, kkasperczyk-no approved these changes

2022-04-13 10:50 UTC, greg-fer requested changes

2022-04-13 10:50 UTC, greg-fer commented on samples/matter/light_switch/README.rst
> +The device is not discoverable automatically upon the device startup user must press **Button 4** to enable the Bluetooth LE advertising.
```suggestion
By default, the device is not discoverable automatically upon startup and **Button 4** must be used to enable the Bluetooth LE advertising.
```

2022-04-14 08:27 UTC, Damian-Nordic approved these changes

2022-04-14 11:15 UTC, greg-fer approved these changes

2022-04-14 12:30 UTC, merged