samples: openthread: adjust logging options to logger v2
nrfconnect/sdk-nrf pull request #7370
Opened 2022-04-13 11:50 UTC by lmaciejonczyk

With the last zephyr upmerge the default logger is LOG2 which does not use strdup function. Any related Kconfig options stops to be applicable.
Adjust Thread samples configuration to the changes.

2022-04-13 11:55 UTC, edmont commented on doc/nrf/ug_thread_configuring.rst
> +* :kconfig:option:`CONFIG_LOG_BUFFER_SIZE` - This option specifies the number of logging buffers.
It seems it's not exactly the number of buffers: _Number of bytes dedicated for the logger internal buffer_

2022-04-13 11:57 UTC, edmont commented on samples/openthread/cli/overlay-logging.conf
> +CONFIG_LOG_BUFFER_SIZE=4048
Maybe move this configuration to `nrf/subsys/net/openthread/Kconfig.defconfig` instead?

```
config LOG_BUFFER_SIZE
	default 4048 if LOG
```

2022-04-13 12:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7370
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-13 12:47 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22537/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-13 13:25 UTC, edmont approved these changes

2022-04-13 13:50 UTC, rlubos approved these changes

2022-04-14 05:14 UTC, wiba-nordic requested changes
Very small nitpick from me, otherwise very good.

2022-04-14 05:14 UTC, wiba-nordic commented on doc/nrf/ug_thread_configuring.rst
> +* :kconfig:option:`CONFIG_LOG_BUFFER_SIZE` - This option specifies the number of bytes dedicated for the logger internal buffer.
```suggestion
* :kconfig:option:`CONFIG_LOG_BUFFER_SIZE` - This option specifies the number of bytes dedicated to the logger internal buffer.
```

2022-04-14 06:12 UTC, wiba-nordic approved these changes

2022-04-14 07:56 UTC, merged