applications: nrf5340_audio: Fix underrun condition
nrfconnect/sdk-nrf pull request #7416
Opened 2022-04-21 11:44 UTC by erik-nordic

When running an unidirectional stream with I2S as audio source, the I2S TX on the gateway is constantly in underrun condition. To remedy this, the tx buffer is set to NULL when initializing I2S

2022-04-21 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7416) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=7416) it.</sub>

2022-04-21 12:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7416
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-27 11:05 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22896/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-27 11:11 UTC, alexsven requested changes

2022-04-27 11:11 UTC, alexsven commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +#if CONFIG_STREAM_BIDIRECTIONAL || (CONDFIG_AUDIO_DEV == HEADSET)
Should have parenthesis around here:
`` #if (CONFIG_STREAM_BIDIRECTIONAL || (CONDFIG_AUDIO_DEV == HEADSET))``

This applies to all #if statements in this PR

2022-04-27 11:11 UTC, alexsven commented on applications/nrf5340_audio/src/audio/audio_datapath.c
> +#endif
#endif should have the if-statement as a comment:
``#endif /* #if (CONFIG_STREAM_BIDIRECTIONAL || (CONDFIG_AUDIO_DEV == HEADSET)) */ `` 

This applies to all #endif statements in this PR

2022-04-27 11:43 UTC, alexsven approved these changes

2022-04-29 06:02 UTC, erikrobstad approved these changes
LGTM

2022-04-29 09:48 UTC, merged