samples: nrf5340: netboot: Add missing steps to testing section
nrfconnect/sdk-nrf pull request #7428
Opened 2022-04-22 11:51 UTC by balaji-nordic

The steps for programming the network core update image was missing.
This is now fixed and additional expected console outputs added.

Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>

2022-04-22 12:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7428
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-25 11:02 UTC, peknis requested changes

2022-04-25 11:02 UTC, peknis commented on samples/nrf5340/netboot/README.rst
> +#. Observe that the output includes the following lines indicating that the MCUBoot in application core read the update image and performed a firmware update of the network core.
```suggestion
#. Observe that the output includes the following lines indicating that the MCUBoot in the application core has read the update image and performed a firmware update of the network core:
```

2022-04-25 11:02 UTC, peknis commented on samples/nrf5340/netboot/README.rst
> +#. Program the network core update image using ``nrfjprog`` as follows.
```suggestion
#. Program the network core update image using ``nrfjprog``:
```

2022-04-25 11:02 UTC, peknis commented on samples/nrf5340/netboot/README.rst
> +#. Observe the following lines in the console output.
```suggestion
#. Observe the following lines in the console output:
```

2022-04-25 11:34 UTC, peknis approved these changes

2022-04-25 11:55 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22810/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-26 19:20 UTC, hakonfam approved these changes
Nice!

2022-05-04 07:21 UTC, merged