esb: fix CRC setup configuration
nrfconnect/sdk-nrf pull request #7431
Opened 2022-04-25 06:40 UTC by valeriosetti

Set the CRC's register properly (16 bits, 8 bits, none)

2022-04-25 06:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7431) before we can accept your contribution.<br/><hr/>**Valerio Setti** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=7431) it.</sub>

2022-04-25 06:40 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2022-04-25 11:36 UTC, grochu reviewed
Thanks for this PR, the changes look good. Just please add an entry in https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases/release-notes-changelog.rst covering the fix.

2022-04-25 12:34 UTC, grochu approved these changes

2022-04-28 13:06 UTC, lemrey approved these changes

2022-05-11 13:13 UTC, FrancescoSer requested changes
Hi! Just a small suggestion

2022-05-11 13:13 UTC, FrancescoSer commented on doc/nrf/releases/release-notes-changelog.rst
> +* Fix: modified the "update_radio_crc()" function in order to correctly configure the CRC's registers (8 bits, 16 bits or none).
```suggestion
* Fixed the ``update_radio_crc()`` function in order to correctly configure the CRC's registers (8 bits, 16 bits, or none).
```

2022-05-18 13:39 UTC, FrancescoSer approved these changes

2022-06-10 08:51 UTC, valeriosetti commented
Hi @carlescufi, is there something missing on my side which prevents this pull request from being accepted?
Thanks :)

2022-06-16 14:29 UTC, lemrey commented
Hi @valeriosetti , can you please sign the CLA and do a rebase? We can get this merged if CI becomes green.

2022-06-22 13:55 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24503/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-22 15:54 UTC, merged

2022-06-22 15:54 UTC, lemrey commented
@valeriosetti thanks for you patience