samples: nrf9160: modem_shell: increase shell RX buffer size
nrfconnect/sdk-nrf pull request #7432
Opened 2022-04-25 09:15 UTC by tokangas

Increased shell RX buffer size to fix problems with test automation.

2022-04-25 09:27 UTC, tokangas commented
Added the DNM label. @moksanen had seen one buffer overflow during the weekend, so it seems that it's probably best to increase the buffers even more. We will run some more tests to see whether 512 or 1024 bytes would be enough.

2022-04-25 09:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7432
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-25 09:56 UTC, jhirsi approved these changes

2022-04-25 10:01 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22802/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-25 12:49 UTC, moksanen requested changes
modem_shell CI is much better with 256 bytes, but I was able to find one RX ring buffer error when running ~100 test cycles. For comparison, with 64 bytes there were would be hundreds, or thousands of RX ring buffer errors during 100 test rounds.
Today, I ran ~30 test rounds with 512 bytes buffer, and zero errors found. Could we jump directly to 512 bytes here?

2022-04-26 06:19 UTC, tokangas commented
> modem_shell CI is much better with 256 bytes, but I was able to find one RX ring buffer error when running ~100 test cycles. For comparison, with 64 bytes there were would be hundreds, or thousands of RX ring buffer errors during 100 test rounds. Today, I ran ~30 test rounds with 512 bytes buffer, and zero errors found. Could we jump directly to 512 bytes here?

Yes, it seems that with 256 bytes there are still some occasional errors. With 512 bytes no errors have been seen at all, so let's go with 512 bytes.

I force-pushed the change and removed the DNM label.

2022-04-26 06:20 UTC, moksanen approved these changes
512 bytes seems to work smoothly in MoSh CI.

2022-04-26 09:46 UTC, rlubos approved these changes

2022-04-26 09:46 UTC, merged