net: lib: nrf_cloud: update nrf cloud host name
nrfconnect/sdk-nrf pull request #7440
Opened 2022-04-25 22:21 UTC by jayteemo

The value of Kconfig option  NRF_CLOUD_HOST_NAME is now
simply "mqtt.nrfcloud.com"

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2022-04-25 22:23 UTC, glarsennordic approved these changes
LGTM

2022-04-25 22:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7440
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-26 01:01 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/22837/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-04-26 05:19 UTC, peknis requested changes

2022-04-26 05:19 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +      * The value of :kconfig:option:`NRF_CLOUD_HOST_NAME` option is now simply "mqtt.nrfcloud.com".
```suggestion
      * The value of the :kconfig:option:`NRF_CLOUD_HOST_NAME` option is now "mqtt.nrfcloud.com".
```

2022-04-26 05:48 UTC, peknis approved these changes

2022-04-26 09:24 UTC, martiles commented
The old NRF_CLOUD_HOST_NAME will still be valid to use for the foreseeable future right?

2022-04-26 16:39 UTC, jayteemo commented
> The old NRF_CLOUD_HOST_NAME will still be valid to use for the foreseeable future right?

yes, it will remain valid.

2022-04-27 23:11 UTC, plskeggs approved these changes

2022-04-28 07:03 UTC, merged