zigbee: Switch Zigbee crypto to use NRF_OBERON for nRF53 platform [KRKNWK-13928]
nrfconnect/sdk-nrf pull request #7453
Opened 2022-04-27 14:47 UTC by sebastiandraus

Changed the crypto library used to perform software AES encryption by the Zigbee samples targeted for nRF53 platform.
Previously used Tinycrypt is replaced by the nRF Oberon library.

2022-04-28 07:29 UTC, adsz-nordic approved these changes

2022-04-28 07:45 UTC, sebastiandraus commented
Rebased at newest main

2022-04-28 08:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7453
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-04-29 07:21 UTC, tomchy approved these changes
LGTM

2022-04-29 08:26 UTC, peknis requested changes

2022-04-29 08:26 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +        Now the nRF Oberon library is used instead of Tinycrypt library.
```suggestion
        Now, the :ref:`nrfxlib:nrf_oberon_readme` is used instead of the Tinycrypt library.
```
Okay with the link?

2022-04-29 08:29 UTC, sebastiandraus commented on doc/nrf/releases/release-notes-changelog.rst
> +        Now the nRF Oberon library is used instead of Tinycrypt library.
Done

2022-04-29 09:10 UTC, peknis approved these changes

2022-04-29 12:20 UTC, merged