samples: bluetooth: nrf_dm: update figure in the documentation.
nrfconnect/sdk-nrf pull request #7518
Opened 2022-05-06 08:56 UTC by maje-emb

Update the Synchronization process figure to match the guidelines.

Ref: NCSDK-15038

Signed-off-by: Marcin Jeliński <marcin.jelinski@nordicsemi.no>

2022-05-06 09:20 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7518
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-06 10:04 UTC, peknis approved these changes

2022-05-06 10:21 UTC, peknis commented
The compliance failure is a mystery to me. Maybe it has something to do with this:

Doxygen is getting updated to 1.9.4 because of issues in doc build in main. (
[Kuroś, Andrzej: Cannot build documentation https://github.com/nrfconnect/sdk-nrf/pul…](https://teams.microsoft.com/l/message/19:a44c20c9d6f349fd9adf98a517fe32cb@thread.skype/1651821807766?tenantId=28e5afa2-bf6f-419a-8cf6-b31c6e9e5e8d&groupId=bbf3a6ae-b458-4b7b-9c01-2d2881d8b2fb&parentMessageId=1651821807766&teamName=NCS&channelName=NCS%20CI&createdTime=1651821807766)

posted in NCS / NCS CI at Friday, May 6, 2022 9:23:27 AM ). PR open here: https://github.com/nrfconnect/sdk-nrf/pull/7515.

2022-05-06 12:23 UTC, greg-fer reviewed
Can be also rendered with the following formatting:

```suggestion
.. msc::
   hscale = "1.3";
   DevA [label="Device A"],DevB [label="Device B"];
   |||;
   DevA rbox DevB [label="Synchronization starts"];
   |||;
   DevA=>DevB [label="ADV_IND"];
   DevA<=DevB [label="SCAN_REQ"];
   DevA=>DevB [label="SCAN_RSP, Manufacturer-specific data"];
   |||;
   DevA rbox DevB [label="Synchronization ends"];
   |||;
   DevA box DevA [label="Reflector"],DevB box DevB [label="Initiator"];
   |||;
   DevA<=>DevB [label="Ranging"];
```

We save having to upload two additional files this way.

2022-05-06 12:30 UTC, greg-fer requested changes
The images need to be moved to ncs/nrf/doc/nrf/images directory. This is because we do not add images for samples in places other than this directory. Linking from the tag does not require providing the path, only file name should work.

2022-05-06 15:40 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23090/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-09 08:35 UTC, maje-emb commented
I have used the rendered diagram.

2022-05-16 11:56 UTC, peknis requested changes

2022-05-16 11:56 UTC, peknis commented on samples/bluetooth/nrf_dm/README.rst
> +The chart shows the sequence of synchronisation process.
```suggestion
The chart shows the sequence of the synchronization process.
```

2022-05-18 07:22 UTC, greg-fer approved these changes

2022-05-18 12:13 UTC, peknis approved these changes

2022-05-18 12:33 UTC, merged