manifest: update Zephyr revision
nrfconnect/sdk-nrf pull request #7540
Opened 2022-05-10 06:59 UTC by kapi-no

Cleaned up the IPC configuration for nRF5340 SoC in Device Tree. This
change fixes the (simple_bus_reg) warning about the missing or empty
reg/ranges property.

Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

2022-05-10 06:59 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/a73fdfbe4d9293589ed26c356644d2e94c1fc54e (main) | https://github.com/nrfconnect/sdk-zephyr/pull/791 | [nrfconnect/sdk-zephyr#791/files](https://github.com/nrfconnect/sdk-zephyr/pull/791/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-05-10 07:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7540
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-10 10:40 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |

**test-sdk-homekit:** added because there was no .github/test-spec.yml in 'homekit'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23137/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-10 12:42 UTC, kapi-no commented
CI failures in integration tests for Thread/RS are not related to this change. They fail during Python package installation

2022-05-10 13:55 UTC, anangl approved these changes
The commit title could also mention the homekit revision update.

2022-05-10 14:41 UTC, mariusz-nordicsemi commented
LGTM (homekit)

2022-05-10 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7540) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=7540) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kapi-no<br/>:x: mergify[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=7540) it.</sub>

2022-05-11 08:39 UTC, carlescufi requested changes
Nack on merge commit

2022-05-11 10:50 UTC, de-nordic commented
@kapi-no Can you remove the merge commit and refresh the PR?

2022-05-11 11:41 UTC, carlescufi approved these changes

2022-05-11 11:41 UTC, merged