openthread: samples: Adding overlays for CI and multiprotocol.
nrfconnect/sdk-nrf pull request #7554
Opened 2022-05-11 06:46 UTC by canisLupus1313

This commit adds overlay for multiprotocol enablemnt and CI in
threead CLI sample.

Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>

2022-05-11 06:54 UTC, edmont requested changes
The new files should be documented in the sample's Readme, and maybe in the changelog as well.

2022-05-11 06:54 UTC, edmont commented on samples/openthread/cli/overlay-ci.conf
> +# Disable logging
I believe we want logging for our CI.

2022-05-11 06:54 UTC, edmont commented on samples/openthread/cli/overlay-ci.conf
> +CONFIG_SHELL_DEFAULT_TERMINAL_WIDTH=416
Notice the missing new line at the end.

2022-05-11 06:54 UTC, edmont commented on samples/openthread/cli/sample.yaml
> +    platform_allow: nrf5340dk_nrf5340_cpuapp nrf5340dk_nrf5340_cpuapp_ns nrf52840dk_nrf52840 nrf21540dk_nrf52840
Is there a memory issue with the 1.1 build? I believe the default 1.2 build should be modified instead.

2022-05-11 07:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7554
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-11 07:43 UTC, lmaciejonczyk commented on samples/openthread/cli/overlay-multiprotocol.conf
> +# Copyright (c) 2020 Nordic Semiconductor
should be 2022

2022-05-11 07:43 UTC, lmaciejonczyk commented on samples/openthread/cli/overlay-multiprotocol.conf
> +CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2144
I'm wondering if it this is really needed for CLI sample. If it is needed and it is multiprotocol dependent it should be applied in general subsys/openthread when CONFIG_BT is being enabled.

2022-05-11 08:30 UTC, edmont requested changes
The new files should be documented in the sample's Readme, and maybe in the changelog as well.

2022-05-12 07:04 UTC, edmont approved these changes

2022-05-12 07:04 UTC, edmont commented on samples/openthread/cli/README.rst
> +* :file:`overlay-ci.conf` - Disables boot banned and shell prompt.
```suggestion
* :file:`overlay-ci.conf` - Disables boot banner and shell prompt.
```

2022-05-12 07:24 UTC, wiba-nordic approved these changes
Approving since I trust you'll make the small change.

2022-05-12 07:24 UTC, wiba-nordic commented on samples/openthread/cli/README.rst
> +* :file:`overlay-multiprotocol.conf` - Enables BLE support in this sample.
```suggestion
* :file:`overlay-multiprotocol.conf` - Enables Bluetooth LE support in this sample.
```

2022-05-12 08:46 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23214/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-17 10:16 UTC, edmont commented
Please rebase.

2022-05-17 22:02 UTC, tomaszkob89 commented on samples/openthread/cli/sample.yaml
> +    extra_args: OVERLAY_CONFIG="overlay-usb.conf overlay-ci.conf overlay-multiprotocol.conf"
This works for me:
```
extra_args: DOVERLAY_CONFIG=overlay-usb.conf DOVERLAY_CONFIG=overlay-ci.conf DOVERLAY_CONFIG=overlay-multiprotocol.conf
                DDTC_OVERLAY_FILE="usb.overlay"
```

2022-05-19 07:05 UTC, merged