samples: openthread: remove data lenght check for ble data
nrfconnect/sdk-nrf pull request #7603
Opened 2022-05-13 13:08 UTC by lmaciejonczyk

Accept ble data with len > 1 to support bluetooth/central_uart sample
as ble tester. central_uart appends new line char to the input data
therefore puting "p" we've got "p\n".

2022-05-13 13:12 UTC, canisLupus1313 approved these changes

2022-05-13 13:17 UTC, wiba-nordic requested changes

2022-05-13 13:17 UTC, wiba-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * CoAP Client sample with Multiprotocol Bluetooth LE extension is compatible now with Bluetooth Central UART sample.
```suggestion
  * CoAP Client sample with Multiprotocol Bluetooth LE extension is now compatible with Bluetooth Central UART sample.
```

2022-05-13 13:17 UTC, wiba-nordic commented on samples/openthread/coap_client/README.rst
> +If you enable the :ref:`coap_client_sample_multi_ext`, make sure you have a phone with the `nRF Toolbox`_ application installed or additional development kit programmed with :ref:`central_uart` sampl
```suggestion
If you enable the :ref:`coap_client_sample_multi_ext`, make sure you have a phone with the `nRF Toolbox`_ application installed or an additional development kit programmed with :ref:`central_uart` sample.
```

2022-05-13 13:17 UTC, wiba-nordic commented on samples/openthread/coap_client/README.rst
> +To test the multiprotocol Bluetooth LE extension, you can use nRF Toolbox or :ref:`central_uart` sample.
```suggestion
To test the multiprotocol Bluetooth LE extension, you can use nRF Toolbox or the :ref:`central_uart` sample.
```

2022-05-13 13:17 UTC, wiba-nordic commented on samples/openthread/coap_client/README.rst
> +Firstly you need to set up nRF Toolbox as follows:
```suggestion
The steps below assume nRF Toolbox as the Bluetooth tester.

First, you need to set up nRF Toolbox as follows:
```

2022-05-13 13:18 UTC, edmont approved these changes

2022-05-13 13:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7603
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-13 14:00 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23304/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-13 14:35 UTC, rlubos approved these changes

2022-05-16 05:20 UTC, wiba-nordic approved these changes

2022-05-16 07:45 UTC, merged