openthread: samples: Reorganise openthread cert overlay
nrfconnect/sdk-nrf pull request #7679
Opened 2022-05-19 07:43 UTC by canisLupus1313

This commit removes BLE functionality from overlay-cert.conf
and delagates this to separate overaly.

Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>

2022-05-19 07:47 UTC, edmont approved these changes

2022-05-19 07:56 UTC, wiba-nordic requested changes
A couple of small changes needed.

2022-05-19 07:56 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +   The :ref:`ot_cli_sample` sample is used as a base, modified with the :file:`harness/overlay-cert.conf` plus :file:`overlay-multiprotocol.conf` overlay files.
```suggestion
   The :ref:`ot_cli_sample` sample is used as a base, modified with the :file:`harness/overlay-cert.conf` and :file:`overlay-multiprotocol.conf` overlay files.
```

2022-05-19 07:56 UTC, wiba-nordic commented on doc/nrf/ug_thread_ot_memory.rst
> +* The sample was compiled using the default :file:`prj.conf` plus :file:`harness\overlay-cert.conf` plus the corresponding plus :file:`overlay-multiprotocol.conf` :kconfig:option:`OPENTHREAD_NORDIC_L
```suggestion
* The sample was compiled using the default :file:`prj.conf` plus :file:`harness\overlay-cert.conf` and :file:`overlay-multiprotocol.conf` overlay files, and the corresponding :kconfig:option:`OPENTHREAD_NORDIC_LIBRARY` and :kconfig:option:`OPENTHREAD_THREAD_VERSION` choices.
```

2022-05-19 07:56 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +      The overlay :file:`overlay-multiprotocol.conf` is not supported with nrf52833dk_nrf52833.
```suggestion
      The overlay :file:`overlay-multiprotocol.conf` is not supported with ``nrf52833dk_nrf52833``.
```

2022-05-19 08:11 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7679
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-19 08:39 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23580/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-20 06:23 UTC, wiba-nordic requested changes
I missed a couple places last time.

2022-05-20 06:23 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +     If the :file:`harness/overlay-cert.conf` is not visible in the drop-down menu, navigate to :file:`ncs/nrf/samples/openthread/cli/harness/` and copy the :file:`overlay-cert.conf` file to :file:`n
```suggestion
     If the :file:`harness/overlay-cert.conf` overlay file is not visible in the drop-down menu, navigate to :file:`ncs/nrf/samples/openthread/cli/harness/` and copy the :file:`overlay-cert.conf` file to :file:`ncs/nrf/samples/openthread/cli/` and try again.
```

2022-05-20 06:23 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +      The overlay :file:`overlay-multiprotocol.conf` is not supported with ``nrf52833dk_nrf52833``.
```suggestion
      The :file:`overlay-multiprotocol.conf` overlay file is not supported with ``nrf52833dk_nrf52833``.
```

2022-05-20 06:23 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
>        The overlay file enables :ref:`multiprotocol support <ug_multiprotocol_support>` with Bluetooth® LE advertising.
Which overlay file? Or both?

2022-05-20 07:24 UTC, wiba-nordic approved these changes

2022-05-20 08:17 UTC, lmaciejonczyk approved these changes

2022-05-20 14:47 UTC, lmaciejonczyk commented
Changelog-entry is still missing.

2022-05-23 07:29 UTC, rlubos approved these changes

2022-05-23 09:09 UTC, wiba-nordic commented
Changelog entry looks good.

2022-06-03 10:24 UTC, edmont commented
Please rebase.

2022-06-07 09:13 UTC, merged