doc: xip: add section to nRF5340DK UG
nrfconnect/sdk-nrf pull request #7692
Opened 2022-05-19 12:19 UTC by greg-fer

Added XIP configuration section to the Working with nRF5340 DK guide.
NRFX-1830.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2022-05-19 12:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7692
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-19 14:27 UTC, b-gent commented on doc/nrf/ug_nrf5340.rst
> +We used the :ref:`nrf_machine_learning_app` application running on the nRF5340 DK for the experiment.
Change the sentence to passive mode instead of 'we'
experiment -> testing?

2022-05-19 14:28 UTC, b-gent commented on doc/nrf/ug_nrf5340.rst
> +This is because the application design allows to move the Edge Impulse library to external memory.
```suggestion
This particular application was used because its design allows to move the Edge Impulse library to external memory.
```

2022-05-20 11:35 UTC, greg-fer commented on doc/nrf/ug_nrf5340.rst
> +   The numbers in the table refer to current consumed only by the nRF5340 DK.
SoC

2022-05-20 13:06 UTC, awojasinski-nordicsemi commented on doc/nrf/ug_nrf5340.rst
> +
```suggestion
For placing individual source code files into defined memory regions, check the :ref:`zephyr:code_relocation_nocopy` sample in Zephyr.

```

2022-05-20 13:07 UTC, awojasinski-nordicsemi requested changes

2022-05-20 13:17 UTC, greg-fer commented
@awojasinski-nordicsemi , @b-gent , please check again.

2022-05-20 13:38 UTC, awojasinski-nordicsemi commented on doc/nrf/ug_nrf5340.rst
> +Measuring XIP with nRF Machine Learning
This change is missing

2022-05-20 13:40 UTC, awojasinski-nordicsemi commented
@greg-fer this https://github.com/nrfconnect/sdk-nrf/pull/7692#discussion_r878122034 is still not applied

2022-05-23 06:22 UTC, greg-fer commented
@awojasinski-nordicsemi , check again please.

2022-05-23 06:41 UTC, awojasinski-nordicsemi approved these changes

2022-05-23 08:35 UTC, b-gent approved these changes

2022-05-23 08:36 UTC, greg-fer commented
@shantha-14 , @anangl , ready for merge.

2022-05-23 13:54 UTC, merged