doc: add software maturity table
nrfconnect/sdk-nrf pull request #7695
Opened 2022-05-19 13:09 UTC by wiba-nordic

Adds a table detailing the difference between supported
and experimental features.

Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>

2022-05-19 13:24 UTC, peknis requested changes

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - Unsupported
Should this be "Not supported" as you have that just above the table?

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - Not available .
```suggestion
     - Not available.
```

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - A feature or component is "supported" as an implementation, but is not compatible with, or tested on a specific device or series of products.
Dunno whether the quotation marks are needed.

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - API definition is stable
```suggestion
     - API definition is stable.
```

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - Incomplete verification
```suggestion
     - Incomplete verification.
```

2022-05-19 13:24 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - Suitable for prototyping an evaluation.
```suggestion
     - Suitable for prototyping or evaluation.
```

2022-05-19 13:27 UTC, peknis requested changes

2022-05-19 13:27 UTC, peknis commented on doc/nrf/software_maturity.rst
> +     - Not available.
```suggestion
     - Not applicable.
```

2022-05-19 13:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7695
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-19 14:19 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23623/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-20 05:13 UTC, wiba-nordic commented
Added a little bit of formatting to the table.

2022-05-20 06:23 UTC, peknis approved these changes

2022-05-21 02:38 UTC, mbolivar-nordic approved these changes

2022-05-21 02:38 UTC, merged