applications: nrf5340_audio: Improve how audio sync timers are initialized
nrfconnect/sdk-nrf pull request #7716
Opened 2022-05-20 12:07 UTC by alexsven

Initialize audio sync timer on the APP core post kernel,
before releasing the NET core. By doing this the NET core
can now send the IPC sync signal, in stead of sending it
from APP core.

Signed-off-by: Erik Robstad <erik.robstad@nordicsemi.no>
Signed-off-by: Alexander Svensen <alexander.svensen@nordicsemi.no>

2022-05-20 12:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7716
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-20 12:59 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/23671/artifact/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-05-20 14:21 UTC, erikrobstad approved these changes

2022-05-23 06:01 UTC, rick1082 approved these changes

2022-05-23 13:09 UTC, Frodevan requested changes
Needs the manifest.yaml file from the controller build

2022-06-03 06:17 UTC, merged