doc improvement: zigbee: update VSC screenshots in ZQSG
nrfconnect/sdk-nrf pull request #7717
Opened 2022-05-20 12:17 UTC by greg-fer

Added new screenshots to Zigbee QSG.
Removed unneeded screenshots.
NCSDK-15243.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2022-05-20 13:14 UTC, kittydepa approved these changes
LGTM

2022-05-20 13:25 UTC, Avalei requested changes

2022-05-20 13:25 UTC, Avalei commented on doc/nrf/ug_zigbee_qsg.rst
>     a. In the Welcome panel or on the Welcome page, click :guilabel:`Create a new application from sample`.
This is fine for now, but as a head's up we will be changing this to just say "Create a new application" either in the June or July VSC release.

2022-05-20 13:25 UTC, Avalei commented on doc/nrf/ug_zigbee_qsg.rst
>        The generation process takes some time and you can observe its progress in the :guilabel:`nRF Connect` terminal.
```suggestion
      The generation process takes some time and you can observe its progress in the :guilabel:`nRF Terminal`.
```

2022-05-23 06:35 UTC, greg-fer commented
@Avalei , please check again.

2022-05-23 07:02 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7717
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-05-23 11:32 UTC, Avalei approved these changes

2022-05-23 12:21 UTC, greg-fer commented
@shantha-14 , @anangl , ready for merge, despite Twister.

2022-05-23 13:54 UTC, merged