sample: Zigbee light switch: Free buffer in case of failed request [KRKNWK-14229]
nrfconnect/sdk-nrf pull request #7891
Opened 2022-06-03 11:37 UTC by sebastiandraus

Fixed an issue where a buffer is not freed when sending Match Descriptor Request fails.

2022-06-03 12:42 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-zigbee | X | | |
| test-fw-nrfconnect-zigbee_ut | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24098/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-08 07:49 UTC, tomchy approved these changes

2022-06-08 12:49 UTC, greg-fer requested changes

2022-06-08 12:49 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed an issue where a buffer is not freed when sending Match Descriptor request fails.
```suggestion
  * Fixed an issue where a buffer would not be freed after a fail occurs when sending Match Descriptor request.
```

2022-06-09 08:12 UTC, merged