doc: update modem firmware before application firmware for nRF9160 DK
nrfconnect/sdk-nrf pull request #7893
Opened 2022-06-03 13:02 UTC by wiba-nordic

Updating modem firmware erases application firmware, so it is
better to have the instructions for updating modem firmware
before the instructions for updating application firmware.

Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>

2022-06-03 14:13 UTC, balaji-nordic approved these changes
Left a comment. The snapshot images may need an update in a separate PR. The look and feel are somewhat different in Programmer version 3.0.0.

2022-06-06 05:16 UTC, wiba-nordic commented on doc/nrf/ug_nrf9160_gs.rst
> +If you continue to updating the application firmware, you can go directly to Step 5.
At this point, the user has Programmer open and the DK connected, so if they continue to updating the application firmware, they don't need to do the first four steps there (Open Programmer, Make sure **SW10** is correct, Connect USB cable, and select the DK from the dropdown).

2022-06-06 05:25 UTC, wiba-nordic commented on doc/nrf/ug_nrf9160_gs.rst
> +If you continue to updating the application firmware, you can go directly to Step 5.
Do you think it would be clearer if "updating the application firmware" was a link?

2022-06-07 10:37 UTC, balaji-nordic commented on doc/nrf/ug_nrf9160_gs.rst
> +If you continue to updating the application firmware, you can go directly to Step 5.
ahah. I see what you mean. Yes.  A link would be better then. I was also confused about this -> "step 5 of what?" So may be it is better to say, "If you now choose to update the application firmware, you can go to Step 5 of <<updating the application firmware>>".

2022-06-07 10:39 UTC, balaji-nordic requested changes
Requesting the change I propose in the comments

2022-06-07 11:54 UTC, wiba-nordic commented on doc/nrf/ug_nrf9160_gs.rst
> +If you continue to updating the application firmware, you can go directly to Step 5.
Left out the word "choose", don't want to accidentally imply that the application firmware doesn't need to be updated after a modem firmware update.

2022-06-07 11:59 UTC, balaji-nordic commented on doc/nrf/ug_nrf9160_gs.rst
> +If you continue to updating the application firmware, you can go directly to Step 5.
Nice. Thanks :)

2022-06-07 12:00 UTC, balaji-nordic approved these changes

2022-06-07 12:17 UTC, wiba-nordic commented
Rebased to correct merge conflict.

2022-06-07 13:03 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24142/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-08 07:25 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
> +* :ref:`ug_nrf9160_gs` by moving :ref:`nrf9160_gs_updating_fw_modem` before :ref:`nrf9160_gs_updating_fw_application` because updating modem firmware erases application firmware.
@wiba-nordic could you fix the general alignment in this documentation section?.. I see some issues with 'Added', 'Updated' labels in the preview.

2022-06-08 07:25 UTC, umapraseeda commented on doc/nrf/ug_nrf9160_gs.rst
> +   Updating the modem firmware erases the contents of the flash memory, so the application must be programmed again to the DK.
```suggestion
   Updating the modem firmware erases the contents of the flash memory, so the application must be programmed again to the nRF9160 DK.
```

2022-06-08 07:25 UTC, umapraseeda commented on doc/nrf/ug_nrf9160_gs.rst
> +      :alt: Programmer - Write
The color and the thickness of the highlight box are a bit different from the other screenshots. Could you check?

2022-06-08 07:25 UTC, umapraseeda commented on doc/nrf/ug_nrf9160_gs.rst
> +      Programmer - Erase & write
Same comment as line 121. Might be nice to check this for all the added screenshots.

2022-06-10 11:28 UTC, wiba-nordic commented
Refreshed all the Programmer screenshots to bring them to latest version, and so they look uniform.

2022-06-13 17:57 UTC, umapraseeda approved these changes

2022-06-15 05:47 UTC, merged