High precision calc
nrfconnect/sdk-nrf pull request #7895
Opened 2022-06-03 13:45 UTC by Tschet1

2022-06-03 14:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7895
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-06-06 10:14 UTC, maje-emb requested changes
Thanks for adding support for high precision calc.

2022-06-06 10:14 UTC, maje-emb commented on subsys/dm/dm.c
> +					high_precision_estimate = nrf_dm_high_precision_calc(&report);
On nrf53832 when calling this funcjion, MPU Fault occurs.
Additionally, for nrf53833 and nrf528322, the stack for dm_thread needs to be increased.

2022-06-07 08:55 UTC, Tschet1 commented
I also need to come up with a strategy to handle the dynamic memory allocations.

2024-02-07 09:57 UTC, closed without merging