samples: nrf9160: modem_shell: command for setting reference altitude
nrfconnect/sdk-nrf pull request #7906
Opened 2022-06-07 11:59 UTC by hiltunent

New command "gnss agps ref_altitude" for setting the reference
altitude required for 3-satellite fixes.

Signed-off-by: Tuomas Hiltunen <tuomas.hiltunen@nordicsemi.no>

2022-06-07 12:35 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7906
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-06-08 05:56 UTC, tokangas approved these changes
Looks good to me.

2022-06-08 06:34 UTC, peknis requested changes

2022-06-08 06:34 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +      For a position fix using only three satellites, GNSS module must have a reference altitude which can now be injected using the ``gnss agps ref_altitude`` command.
```suggestion
      For a position fix using only three satellites, GNSS module must have a reference altitude that can now be injected using the ``gnss agps ref_altitude`` command.
```

2022-06-08 07:58 UTC, trantanen approved these changes

2022-06-08 08:12 UTC, jhirsi approved these changes

2022-06-08 09:35 UTC, peknis approved these changes

2022-06-08 11:10 UTC, rlubos commented
@hiltunent MoSh build in Twister is failing with those changes, can you investigate?

2022-06-08 11:47 UTC, hiltunent commented
> @hiltunent MoSh build in Twister is failing with those changes, can you investigate?

Sorry, I forgot to try and compile this PR :) I will fix it next.

2022-06-08 13:38 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24173/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-08 14:53 UTC, rlubos approved these changes

2022-06-08 14:53 UTC, merged