doc: fast_pair: Allow hiding UI indication
nrfconnect/sdk-nrf pull request #7929
Opened 2022-06-09 09:25 UTC by alstrzebonski

Updates release notes and Fast Pair documentation.

Jira: NCSDK-14839

2022-06-09 09:27 UTC, alstrzebonski commented
This PR is a documentation update. It is meant to be merged after this PR: https://github.com/nrfconnect/sdk-nrf/pull/7653.

2022-06-09 10:24 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24201/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-09 10:58 UTC, greg-fer requested changes

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   **LED 3** blinks slowly then.
```suggestion
   **LED 3** starts blinking slowly.
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   **LED 3** blinks rapidly.
```suggestion
   **LED 3** starts blinking rapidly.
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   * Fast Pair not discoverable advertising, show UI indication.
```suggestion
   * Fast Pair not discoverable advertising (with the show UI indication).
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   * Blinks with 0.5 secs interval if the selected mode is Fast Pair not discoverable advertising, show UI indication.
```suggestion
   * Blinks with 0.5 secs interval if the selected mode is the Fast Pair not discoverable advertising with the show UI indication.
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   * Blinks with 1.5 secs interval if the selected mode is Fast Pair not discoverable advertising, hide UI indication.
```suggestion
   * Blinks with 1.5 secs interval if the selected mode is the Fast Pair not discoverable advertising with the hide UI indication.
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   If the device is in the show UI indication mode, a notification similar to the following one appears:
```suggestion
   If the device is in the show UI indication advertising mode, a notification similar to the following one appears:
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +   If the device is in the hide UI indication mode, no notification appears.
```suggestion
   If the device is in the hide UI indication advertising mode, no notification appears.
```

2022-06-09 10:58 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added possibility of toggling between show/hide UI indication Fast Pair advertising modes.
Too many nouns :)
```suggestion
  * Added possibility of toggling the advertising modes.
    You can now toggle between discoverable and not discoverable modes (with show UI and hide UI indications).
```

2022-06-09 10:58 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added option to set hide UI indication flag in Fast Pair not discoverable advertising data.
```suggestion
  * Added option to set the flag for the hide UI indication in the Fast Pair not discoverable advertising data.
```

2022-06-09 10:58 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +#. If the notification appears, tap on it to trigger the Fast Pair procedure.
```suggestion
#. In the show UI indication mode, when the notification appears, tap on it to trigger the Fast Pair procedure.
```

2022-06-10 09:56 UTC, MarekPieta commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added possibility of toggling the advertising modes.
Maybe: `Added possibility of toggling between show and hide UI indication in Fast Pair not discoverable advertising.`

2022-06-10 09:56 UTC, MarekPieta commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added option to set the flag for the hide UI indication in the Fast Pair not discoverable advertising data.
`Extended API to allow setting the flag ...`

2022-06-10 09:56 UTC, MarekPieta commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added option to set the flag for the hide UI indication in the Fast Pair not discoverable advertising data.
`option` may seem like reference to Kconfig option which could be a bit confusing

2022-06-10 09:56 UTC, MarekPieta commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added possibility of toggling the advertising modes.
Toggling between discoverable and not discoverable advertising was introduced before.

2022-06-14 09:22 UTC, greg-fer approved these changes

2022-06-15 12:51 UTC, MarekPieta approved these changes

2022-06-22 06:47 UTC, KAGA164 approved these changes

2022-06-29 07:49 UTC, merged