doc: known_issues: Add new issues in bluetooth samples.
nrfconnect/sdk-nrf pull request #7930
Opened 2022-06-09 13:01 UTC by grochu

For doc completeness, we should describe the following issues:
- low throughput value measured by the throughput sample,
- HR coded phy samples cannot start scanning/advertising
when using the SW Split LL.

2022-06-09 13:03 UTC, grochu commented on doc/nrf/known_issues.rst
> +  **Workaround:** Manually cherry-pick and apply commit with fix from main (commit hash: ``2ea62e3ac5c8164046643cf13e45b808d3ebab43``).
DNM till https://github.com/nrfconnect/sdk-nrf/pull/7886 is merged so correct SHA can be put here.

2022-06-09 13:09 UTC, peknis requested changes

2022-06-09 13:09 UTC, peknis commented on doc/nrf/known_issues.rst
> +NCSDK-15527: Advertising in :ref:`peripheral_hr_coded` and scanning in :ref:`bluetooth_central_hr_coded` cannot be started when using the SW Split Link Layer.
```suggestion
NCSDK-15527: Advertising in the :ref:`peripheral_hr_coded` sample and scanning in the :ref:`bluetooth_central_hr_coded` sample cannot be started when using the SW Split Link Layer.
```

2022-06-09 13:09 UTC, peknis commented on doc/nrf/known_issues.rst
> +  The peer's measured throughput is understated because it includes a delay, where no data transfer is done.
```suggestion
  The peer's measured throughput is understated because it includes a delay, during which there is no data transfer.
```

2022-06-09 13:32 UTC, grochu commented on doc/nrf/known_issues.rst
> +  The peer's measured throughput is understated because it includes a delay, where no data transfer is done.
fixed

2022-06-09 14:24 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24209/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-10 06:21 UTC, peknis approved these changes

2022-06-14 12:30 UTC, KAGA164 approved these changes

2022-06-23 22:21 UTC, doki-nordic approved these changes

2022-07-21 12:37 UTC, merged