application: serial_lte_modem: Add GNSS sleep/wakeup URC
nrfconnect/sdk-nrf pull request #7980
Opened 2022-06-15 08:11 UTC by junqingzou

Add to notify MCU side of modem GNSS sleep/wakeup events
Sleep could be due to fix retry tiemout or fix achieved
Wakeup is for the periodical mode.
Purpose is for MCU side to control GNSS for power saving.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2022-06-15 08:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-7980
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-06-15 09:06 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24325/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-16 05:52 UTC, tokangas requested changes

2022-06-16 05:52 UTC, tokangas commented on applications/serial_lte_modem/src/gnss/slm_at_gnss.c
> +		sprintf(rsp_buf, "\r\n#AXGPS: 1,%d\r\n", run_status);
```suggestion
		sprintf(rsp_buf, "\r\n#XAGPS: 1,%d\r\n", run_status);
```

2022-06-16 05:52 UTC, tokangas commented on applications/serial_lte_modem/src/gnss/slm_at_gnss.c
> +		sprintf(rsp_buf, "\r\n#PXGPS: 1,%d\r\n", run_status);
```suggestion
		sprintf(rsp_buf, "\r\n#XPGPS: 1,%d\r\n", run_status);
```

2022-06-17 13:01 UTC, FrancescoSer approved these changes

2022-06-20 11:38 UTC, tokangas approved these changes

2022-06-20 12:19 UTC, rlubos approved these changes

2022-06-21 07:25 UTC, merged