doc: ug_edge_impulse: Add explanation regarding API key
nrfconnect/sdk-nrf pull request #8004
Opened 2022-06-17 13:43 UTC by MarekPieta

Change introduces more detailed explanation regarding API key handling to prevent misunderstandings.

Jira: NCSDK-15725

2022-06-17 13:53 UTC, greg-fer approved these changes

2022-06-17 14:14 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8004
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-06-20 08:43 UTC, MarekPieta commented
Discussed with @OeySa and introduced a few additional improvements. Please rerevew.

2022-06-20 08:47 UTC, OeySa reviewed
LGTM!

2022-06-20 09:31 UTC, pdunaj approved these changes

2022-06-20 12:24 UTC, greg-fer requested changes

2022-06-20 12:24 UTC, greg-fer commented on doc/nrf/ug_edge_impulse.rst
> +     If the URI requires providing an additional API key in the HTTP header, you can provide it using the :c:macro:`EI_API_KEY_HEADER` CMake definition.
```suggestion
     If the URI requires providing an additional API key in the HTTP header.
     You can provide it using the :c:macro:`EI_API_KEY_HEADER` CMake definition.
```
Edit to remove the comma splice.

2022-06-20 12:36 UTC, merged