Issue14795 aggregator test
nrfconnect/sdk-nrf pull request #8039
Opened 2022-06-22 12:38 UTC by zycz

2022-06-22 13:12 UTC, greg-fer requested changes

2022-06-22 13:12 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
>  |no_changes_yet_note|
Remove this line -- there are already changes, so it is not needed.

2022-06-22 13:12 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +* :ref:`caf_sensor_data_aggregator` unit tests added.
```suggestion
* :ref:`caf_sensor_data_aggregator`:

  * Added unit tests for the library.
```

2022-06-22 13:47 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24501/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-06-23 07:19 UTC, gopiotr commented
Please add also register into CODEOWNERS file with path to test `/tests/subsys/caf/sensor_data_aggregator/` and person/people responsible for this test:
https://github.com/nrfconnect/sdk-nrf/blob/main/CODEOWNERS

2022-06-23 12:22 UTC, emob-nordic commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +		k_yield();
This is something i wouldn't expect in the tests. If you are lacking of the HEAP just increase it. This looks like something is not good within the test.
Furthermore if the test is named `test_order` i would expect we are firstly flood the system with events and then we check if they came in correct order. With this yield you would probably create and receive event one by one. It kinda "tests" what event manager ensures - event order.

2022-06-23 13:19 UTC, rakons approved these changes
Only style notes of zasserts usage.

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +	zassert_false(app_event_manager_init(), "Error when initializing");
zassert_ok

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +	zassert_equal(err, 0, "Test execution hanged");
zassert_ok

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +	zassert_equal(err, 0, "Test execution hanged");
zassert_ok

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +	zassert_equal(err, 0, "Test execution hanged");
zassert_ok

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/main.c
> +	zassert_true(false, "Wrong event type received");
zassert_unreachable

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/modules/test_basic.c
> +	zassert_true(false, "Event unhandled");
zassert_unreachable

2022-06-23 13:19 UTC, rakons commented on tests/subsys/caf/sensor_data_aggregator/src/modules/test_data_receiver.c
> +	zassert_true(false, "Event unhandled");
zassert_unreachable

2022-06-24 07:10 UTC, gopiotr approved these changes

2022-06-27 10:55 UTC, emob-nordic approved these changes

2022-06-27 13:08 UTC, merged