mcuboot: Added support for NET core serial recovery when CONFIG_NRF_MULTI_IMAGE_UPDATE=n
nrfconnect/sdk-nrf pull request #8050
Opened 2022-06-23 13:52 UTC by nvlsianpu

2022-06-23 14:29 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8050
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-01 07:36 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| mcuboot | [nrfconnect/sdk-mcuboot@v1.9.99-ncs1](https://github.com/nrfconnect/sdk-mcuboot/releases/tag/v1.9.99-ncs1) | https://github.com/nrfconnect/sdk-mcuboot/pull/206 | [nrfconnect/sdk-mcuboot#206/files](https://github.com/nrfconnect/sdk-mcuboot/pull/206/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-07-06 20:48 UTC, sigvartmh approved these changes

2022-07-07 12:43 UTC, KAGA164 requested changes

2022-07-08 10:17 UTC, nvlsianpu commented on samples/bluetooth/peripheral_uart/boards/nrf5340dk_nrf5340_cpuapp.conf
> +CONFIG_MCUBOOT_IMAGE_VERSION="1.0.0+0"
@KAGA164 I opened separate PR for document serial recovery of the networking core image: #8141

2022-07-29 15:33 UTC, nvlsianpu commented on samples/bluetooth/peripheral_uart/boards/nrf5340dk_nrf5340_cpuapp.conf
> +CONFIG_MCUBOOT_IMAGE_VERSION="1.0.0+0"
@KAGA164 I discussed this witch @grochu when you was OoO. It seam that best we can do is to add this as  optional configuration which can be included using Kconfig's OVERLAY_CONFIG mechanism and mentions this in the sample manual. General overview of the feature is under #8141

2022-08-31 18:02 UTC, nvlsianpu commented
@KAGA164 Can you look here again?

2022-09-01 08:36 UTC, KAGA164 reviewed
Looks good. Just please add license in configuration files

2022-09-01 08:36 UTC, KAGA164 commented on samples/bluetooth/peripheral_uart/nrf5340dk_app_sr_net.conf
> +CONFIG_MCUBOOT_IMAGE_VERSION="1.0.0+0"
Please add the license:
```
#
# Copyright (c) 2022 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
```

2022-09-01 08:36 UTC, KAGA164 commented on samples/bluetooth/peripheral_uart/nrf5340dk_mcuboot_sr_net.conf
> +CONFIG_MAIN_STACK_SIZE=10240
Please add the license:
```
#
# Copyright (c) 2022 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
```

2022-09-01 09:26 UTC, peknis requested changes

2022-09-01 09:26 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +     core image.
```suggestion
   * When used with :ref:`zephyr:nrf5340dk_nrf5340`, the sample might support the MCUboot bootloader with serial recovery of the networking core image.
```

2022-09-01 09:26 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +For the ``nrf5340dk_nrf5340_cpuapp`` it is possible to enable serial recovery of the network core while multi-image update is not enabled in the MCUboot.
```suggestion
For the ``nrf5340dk_nrf5340_cpuapp``, it is possible to enable serial recovery of the network core while multi-image update is not enabled in the MCUboot.
```

2022-09-01 09:26 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +and the :file:`nrf5340dk_mcuboot_sr_net.conf`.
```suggestion
See :ref:`peripheral_uart_sample_activating_variants` for details on how to build the sample with this feature using the :file:`nrf5340dk_app_sr_net.conf` and :file:`nrf5340dk_mcuboot_sr_net.conf` files.
```

2022-09-01 09:26 UTC, peknis commented on samples/bluetooth/peripheral_uart/README.rst
> +  Additinally, you need to set :makevar:`mcuboot_OVERLAY_CONFIG` to :file:`nrf5340dk_mcuboot_sr_net.conf`.
```suggestion
* For the MCUboot with serial recovery of the networking core image feature, set the :file:`nrf5340dk_app_sr_net.conf` file.
  You also need to set the :makevar:`mcuboot_OVERLAY_CONFIG` variant to :file:`nrf5340dk_mcuboot_sr_net.conf`.
```

2022-09-01 14:16 UTC, KAGA164 approved these changes

2022-09-01 14:30 UTC, nvlsianpu commented
@peknis I applied your suggestions.

2022-09-02 05:04 UTC, peknis approved these changes
Would this addition be worth a changelog entry?

2022-09-05 13:36 UTC, nvlsianpu commented
@peknis 

> Would this addition be worth a changelog entry?

Yes, Of course.

2022-09-06 14:03 UTC, rlubos commented on west.yml
> +      revision: pull/206/head
Please update SHA: `8b3d00abb132de5f5c46310f88c2208ddf6270d4`

2022-09-06 14:24 UTC, rlubos approved these changes

2022-09-06 16:37 UTC, rlubos commented
CI passed on reruns.

2022-09-06 16:37 UTC, merged