sample: Zigbee shell: Add support for nRF52 Dongle and USB transport [KRKNWK-12756]
nrfconnect/sdk-nrf pull request #8084
Opened 2022-06-30 11:30 UTC by sebastiandraus

This commit adds support for nRF52 Dongle in the Zigbee shell sample
and allows to built the sample with Shell configured to use USB transport.

2022-06-30 11:49 UTC, greg-fer commented
Also please update the memory requirements table with the new row for the USB ACM extension https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_zigbee_memory.html

2022-06-30 11:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8084
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-06-30 14:20 UTC, sebastiandraus commented on samples/zigbee/shell/README.rst
> +To change the Shell backend from the default UART to nRF USB CDC ACM, use the :file:`prj_usb.conf` configuration file and add the ``-DCONF_FILE='prj_usb.conf'`` flag to the build command.
Using just `prj_usb.conf` should be enough

2022-06-30 15:30 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-zigbee | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24756/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-04 08:01 UTC, greg-fer requested changes
Some more minor comments, sorry.

2022-07-04 08:01 UTC, greg-fer commented on samples/zigbee/shell/README.rst
> +You can enable UART backend for the logger, so that Zephyr logs are printed to both the shell backend and UART.
```suggestion
You can enable the UART backend for the logger, so that Zephyr logs are printed to both the shell backend and the UART.
```

2022-07-04 08:01 UTC, greg-fer commented on samples/zigbee/shell/README.rst
> +If sample is built for :ref:`zephyr:nrf52840dongle_nrf52840`, the nRF USB CDC ACM is the default backend for shell.
```suggestion
If the sample is built for :ref:`zephyr:nrf52840dongle_nrf52840`, the nRF USB CDC ACM is the default backend for shell.
```

2022-07-04 09:17 UTC, greg-fer approved these changes

2022-07-11 12:04 UTC, merged