samples: openthread: Logs errors by default in CLI sample.
nrfconnect/sdk-nrf pull request #8095
Opened 2022-07-04 09:56 UTC by lmaciejonczyk

This commit enables logging by default in CLI sample to print messages
in case of errors and hard faults.

Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>

2022-07-04 10:08 UTC, canisLupus1313 approved these changes

2022-07-04 10:16 UTC, edmont approved these changes
Would a similar approach be beneficial for other samples?

2022-07-04 10:21 UTC, lmaciejonczyk commented
> Would a similar approach be beneficial for other samples?

Other Thread samples have already enabled logging by default.

2022-07-04 10:26 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8095
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-05 07:37 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24814/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-05 09:06 UTC, lmaciejonczyk commented
Ci green -> Integration tests works after rerun https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8095/3/

2022-07-05 09:06 UTC, wiba-nordic requested changes
Small clarification

2022-07-05 09:09 UTC, wiba-nordic approved these changes
Looks good!

2022-07-05 12:08 UTC, rlubos approved these changes
Looks good, but could you force-push again to retrigger the CI? Something got stuck...

2022-07-05 14:48 UTC, merged