moules/mcuboot/zephyr: remove copy of BOOT_ERASE_PROGRESSIVELY Kconfig
nrfconnect/sdk-nrf pull request #8098
Opened 2022-07-04 12:10 UTC by nvlsianpu

The property was exact redefinition of its original definition in
the mcuboot. There is no sense of having this copy.

Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

2022-07-04 12:47 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8098
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-04 13:05 UTC, hakonfam approved these changes

2022-07-05 11:34 UTC, sigvartmh approved these changes

2022-08-15 08:01 UTC, tejlmand requested changes
@nvlsianpu Did you look at the history why this was introduced ?

https://github.com/nrfconnect/sdk-nrf/commit/15161781ba1ee671292fde86b2eac198253a2559

> Kconfig options defined by a sample Kconfig source file is not
available for other images.

> Fix this problem by only sourcing Kconfig.mcuboot from the
MCUboot sample Kconfig file.
>
> Also extract options from Kconfig.mcuboot that should be available
for all images.

So it's no surprise that this file contains identical redefinitions, cause that seems to be the purpose of the file to avoid sourcing `Kconfig.mcuboot` in all images.

So could you update the commit messages, stating why `BOOT_ERASE_PROGRESSIVELY` itself is no longer needed, while the rests are still needed.

2022-10-30 00:36 UTC, closed without merging