doc: Update figures for CAF libraries
nrfconnect/sdk-nrf pull request #8109
Opened 2022-07-05 12:37 UTC by divipillai

The following figures for CAF libraries are
updated to match with the guidelines:
caf_ble_state_transitions
caf_buttons_states
caf_power_manager_states
caf_sensor_states

Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>

2022-07-05 13:15 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8109
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-05 14:23 UTC, greg-fer requested changes
The changes look good, thank you for taking care of them!
My only concern is the [caf_power_manager_states.svg](https://github.com/nrfconnect/sdk-nrf/pull/8109/commits/93d9ff44cd38db33a6a38fcb58821ce2bd286494#diff-49170bff333eaa6198806f12f90054fc4176ff56c4b660c90dd210520118794e) file with the STATE_ERROR_SUSPENDED broken over two lines. Can this be fixed, for example by making that bubble bigger?

2022-07-06 06:25 UTC, greg-fer approved these changes

2022-07-06 18:21 UTC, emob-nordic approved these changes
Everything seems to be okay.

Opinion:
Tbh i don't see curved lines nicer and prettier than rectangular ones, but i bet its not my decision. I found rectangular lines much cleaner, professional and easier to read. More complex state diagrams would be messy in the future.

2022-07-08 11:34 UTC, merged