bug: applications: machine_learning: change pwm_period to improve led…
nrfconnect/sdk-nrf pull request #8114
Opened 2022-07-05 14:31 UTC by zycz

… color blinking

Decrease pwm_period for leds on thingy53 so while blinking
led does not shine in different colour.

Jira: NCSDK-15707

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2022-07-05 15:27 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24846/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-06 09:41 UTC, pdunaj requested changes
```
bug: applications: machine_learning
```
remove `bug:` from commit message.

BTW - there seems to be nothing in the code that would do what message suggests

2022-07-06 11:37 UTC, zycz commented
> ```
> bug: applications: machine_learning
> ```
> 
> remove `bug:` from commit message.
> 
> BTW - there seems to be nothing in the code that would do what message suggests

Removed bug label.
The change adds pwm nodes to dts overlay so it overwrites pwm_period which was previously defined 20ms in zephyr thingy53_common.dts

2022-07-06 11:49 UTC, MarekPieta commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/app.overlay
> +	pwmleds {
Update `_ns` configuration too

2022-07-06 12:04 UTC, MarekPieta commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/app.overlay
> +			label = "Green PWM LED";
Do we need to update labels ?

2022-07-06 14:39 UTC, MarekPieta requested changes

2022-07-06 14:39 UTC, MarekPieta commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/app.overlay
> +		compatible = "pwm-leds";
Is assigning `compatible` needed?

2022-07-06 14:39 UTC, MarekPieta commented on applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/app.overlay
> +		compatible = "pwm-leds";
Isn't it already assigned by the board's DTS?

2022-07-06 14:39 UTC, MarekPieta commented on doc/nrf/known_issues.rst
> +  It causes visual glitches while LED color is updated for LEDs with more than one color channel.
Maybe we could provide some context?
```
Update of the first LED channel occurs one PWM period earlier than update of remaining channels. Shorter LED PWM period mitigates the observed issue.
```

2022-07-06 14:39 UTC, MarekPieta commented on doc/nrf/known_issues.rst
> +  It causes visual glitches while LED color is updated for LEDs with more than one color channel.
Can we also add a short note about the problem in CAF LEDs documentation (I think we need it)

2022-07-07 08:35 UTC, greg-fer requested changes

2022-07-07 09:59 UTC, MarekPieta approved these changes

2022-07-07 10:41 UTC, gmarull commented
shouldn't this be set by default in the upstream board?

2022-07-08 12:34 UTC, MarekPieta commented
Hi @gmarull
`PWM_MSEC(20)` seems a default period for PWM LEDs of Zephyr boards.

If we use nrfx PWM driver to drive a RGB LED, update of the first LED color occurs one PWM period earlier than update of remaining channels (that causes glitches during e.g. RGB LED blinking). Shorter LED PWM period mitigates the observed issue.  The visual glitch would not affect monochromatic LEDs and cases when color is changed slowly (or cases where only one color channel is used). 

Shorter PWM period leads to increase of power consumption and it may not be needed in some use-cases. I think that if we decide to change the default value, we should do it for all of the boards to use consistent default configuration.

2022-07-08 12:39 UTC, pdunaj approved these changes

2022-07-08 14:09 UTC, merged