samples: Bluetooth: df: Forward GPIO pins from app to network core
nrfconnect/sdk-nrf pull request #8123
Opened 2022-07-06 11:29 UTC by ppryga

To give control over GPIO pins for Direction Finding Extension in
Radio peripheral when build for nRF53 network core, the application
core has to assign those pins to network core.

The commit adds overlays with appropriate configuration assigning
GPIO pins in all DF related samples.

Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>

2022-07-06 12:28 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | | | X |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24870/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-07 13:36 UTC, KAGA164 reviewed
Looks good. Please update add a changelog entry

2022-07-12 06:44 UTC, ppryga commented
@KAGA164 change log updated.

2022-07-14 13:23 UTC, ppryga commented
@greg-fer could you take a look on the PR?

2022-07-14 13:52 UTC, greg-fer requested changes
Please also describe (mention) the new files being available and their usage in each sample's readme file.

2022-07-14 13:52 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added nRF5340 application core DTS to configure GPIOs forwarding to allow Radio peripheral Direction Finding Extension for antenna switching.
```suggestion
  * Added devicetree overlay file for the nRF5340 application core that configures GPIO pin forwarding.
    This enables the radio peripheral's Direction Finding Extension for antenna switching.
```
Global edit.

2022-07-18 08:31 UTC, ppryga commented
@greg-fer requested change is done. Please re-review the PR.

2022-07-19 07:09 UTC, greg-fer reviewed
Couple of suggestions.

2022-07-19 07:09 UTC, greg-fer commented on samples/bluetooth/direction_finding_central/child_image/hci_rpmsg/boards/nrf5340dk_nrf5340_cpunet.overlay
> +	 * overlay gpio_fwd node.
```suggestion
	 * NOTE: Make sure to select the same GPIOs in the application core DTS
	 * overlay's gpio_fwd node.
```

2022-07-19 07:09 UTC, greg-fer commented on samples/bluetooth/direction_finding_central/README.rst
> +This gives control over GPIOs to the Radio peripheral to execute antenna switching.
```suggestion

nRF5340 configuration files
===================

The following additional configuration files are available for the :ref:`nRF5340 DK <ug_nrf5340>`:

* The Bluetooth LE controller is part of a child image meant to run on the network core.
  The configuration for the child image is stored in the :file:`child_image/` subdirectory.
* :file:`boards/nrf5340dk_nrf5340_cpuapp.overlay` DTS overlay file is available for the application core.
  This file forwards the control over GPIOs to network core, which gives control over GPIOs to the radio peripheral in order to execute antenna switching.
```
Propagate to other samples.

2022-07-19 12:42 UTC, ppryga commented on samples/bluetooth/direction_finding_central/child_image/hci_rpmsg/boards/nrf5340dk_nrf5340_cpunet.overlay
> +	 * overlay gpio_fwd node.
Corrected in all changed samples

2022-07-19 12:42 UTC, ppryga commented on samples/bluetooth/direction_finding_central/boards/nrf5340dk_nrf5340_cpuapp.overlay
> +  */
Corrected in all changed samples

2022-07-19 12:43 UTC, ppryga commented
@greg-fer thank you for suggested changes. All were added.

2022-07-19 13:59 UTC, ppryga commented
Fixed `doc-build`.

2022-07-21 07:01 UTC, greg-fer approved these changes

2022-07-22 13:04 UTC, alwa-nordic approved these changes

2022-07-25 10:34 UTC, merged