samples: peripheral_fast_pair: Limit discoverable adv session
nrfconnect/sdk-nrf pull request #8139
Opened 2022-07-07 15:18 UTC by MarekPieta

Change limits time of discoverable advertising session to fulfill Fast Pair requirements.

Jira: NCSDK-14830

2022-07-07 15:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8139
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-08 08:32 UTC, divipillai commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +       The discoverable advertising is automatically switched to not discoverable advertising with show UI indication after a 10-minute timeout.
```suggestion
       The discoverable advertising is automatically switched to not discoverable advertising with the show UI indication mode after a 10-minute timeout.
```

2022-07-11 16:32 UTC, alstrzebonski requested changes

2022-07-11 16:32 UTC, alstrzebonski commented on samples/bluetooth/peripheral_fast_pair/src/main.c
> +		k_work_cancel_delayable(&fp_adv_mode_status_led_handle);
This line can be removed. We later reschedule this work anyway and we are in cooperative thread.

2022-07-12 07:19 UTC, greg-fer requested changes

2022-07-12 07:19 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Automatic switching to not discoverable advertising with the show UI indication mode after 10 minutes of discoverable advertising.
```suggestion
    * Automatic switching to the not discoverable advertising with the show UI indication mode after 10 minutes of discoverable advertising.
```

2022-07-12 07:19 UTC, greg-fer commented on samples/bluetooth/peripheral_fast_pair/README.rst
> +       The discoverable advertising is automatically switched to not discoverable advertising with the show UI indication mode after a 10-minute timeout.
```suggestion
       The discoverable advertising is automatically switched to the not discoverable advertising with the show UI indication mode after a 10-minute timeout.
```

2022-07-12 11:47 UTC, greg-fer approved these changes

2022-07-13 06:06 UTC, greg-fer approved these changes

2022-07-13 09:51 UTC, merged