caf: Add polichrom led glitches to know issue for NCS 2.0
nrfconnect/sdk-nrf pull request #8149
Opened 2022-07-09 09:26 UTC by zycz

Add polychromatic LED  glitches caused by change in pwm_period
 to know issue for NCS 2.0

Jira: NCSDK-15707

Signed-off-by: Jan Zyczkowski <jan.zyczkowski@nordicsemi.no>

2022-07-09 09:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8149
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-09 10:23 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/24949/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-10 20:41 UTC, MarekPieta requested changes

2022-07-10 20:41 UTC, MarekPieta commented on doc/nrf/libraries/caf/leds.rst
> +  It is important to set pwm period for a tri-channel color LED node to value not greater then 1 millisecond.
Also maybe we could add this information as a note, to highlight it

2022-07-10 20:41 UTC, MarekPieta commented on doc/nrf/known_issues.rst
> +  Due to changes in board's default DTS, the default ``pwm_period`` has been increased.
`.. boards' default DTS configurations ...` (it should be plural I think)

2022-07-12 06:59 UTC, greg-fer approved these changes
Fully agree with @divipillai 's comments 👍

2022-07-12 10:12 UTC, MarekPieta commented
@zycz is on vacation. I took over the PR and applied requested changes. I also added my comments. Please rereview

2022-07-12 10:53 UTC, divipillai approved these changes

2022-07-12 11:49 UTC, greg-fer requested changes

2022-07-12 11:49 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  The first LED channel is updated one PWM period before the remaining channels are updated.
```suggestion
  The first LED channel is updated one PWM period before the remaining channels are updated.
```
What does it mean "is updated one PWM period"? You mean "by one"?

2022-07-12 12:45 UTC, greg-fer approved these changes

2022-07-13 08:44 UTC, pdunaj approved these changes

2022-07-13 09:50 UTC, merged