manifest: update nrfxlib revision
nrfconnect/sdk-nrf pull request #8155
Opened 2022-07-11 11:02 UTC by lmaciejonczyk

Update pre-built OpenThread libraries for NCS v2.0.1 release.

Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>

2022-07-11 11:02 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | [nrfconnect/sdk-nrfxlib@v2.0.0](https://github.com/nrfconnect/sdk-nrfxlib/releases/tag/v2.0.0) | https://github.com/nrfconnect/sdk-nrfxlib/pull/775 | [nrfconnect/sdk-nrfxlib#775/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/775/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-07-11 11:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8155
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-11 11:47 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/v2.0-branch/14/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-12 06:32 UTC, greg-fer approved these changes

2022-07-12 07:24 UTC, canisLupus1313 approved these changes

2022-07-12 07:36 UTC, edmont approved these changes

2022-07-12 09:18 UTC, greg-fer requested changes
@lmaciejonczyk , can we also add an entry to the Thread protocol section in the changelog?
I propose:
```
Updated the values in the memory requirement tables in :ref:`ug_thread_ot_memory` after the updated to the :ref:`nrfxlib:ot_libs` in nrfxlib.
```

2022-07-12 11:48 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +* Updated the values in the memory requirement tables in :ref:`ug_thread_ot_memory` after the updated to the :ref:`nrfxlib:ot_libs` in nrfxlib.
```suggestion
* Updated the values in the memory requirement tables in :ref:`ug_thread_ot_memory` after the updated to the :ref:`nrfxlib:ot_libs` in nrfxlib.
```
```suggestion
* Updated the values in the memory requirement tables in :ref:`ug_thread_ot_memory` after the update to the :ref:`nrfxlib:ot_libs` in nrfxlib.
```

2022-07-12 11:48 UTC, greg-fer requested changes
One typo :(

2022-07-12 13:36 UTC, greg-fer approved these changes

2022-07-13 09:58 UTC, merged