manifest: update SDC and MPSL
nrfconnect/sdk-nrf pull request #8167
Opened 2022-07-12 16:25 UTC by ibaz-nordic

MPSL - rev 08a6473ccb1b866b4d74ad8e8967ad99a81dd7d3
SDC  - rev 4f3841816def9901834fb2a159c8ba1554da52a7

Signed-off-by: Azizah Ibrahim <azizah.ibrahim@nordicsemi.no>

2022-07-12 16:25 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/766cc270caca3975fa6d924ada43177089040fcc (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/776 | [nrfconnect/sdk-nrfxlib#776/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/776/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-07-12 17:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8167
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-12 18:03 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25005/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-13 07:01 UTC, Tschet1 requested changes
Please add a note in the release notes.

2022-07-15 04:45 UTC, jori-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> -  * Added:
why the removed lines ? I think you need to rebase.

2022-07-15 04:47 UTC, jori-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +For details, see `softdevice_controller_changelog`.
Please fix the link:
```rst
For details, see :ref:`nrfxlib:softdevice_controller_changelog`.
```
I got this syntax from the previous release notes (nrf/doc/nrf/releases/release-notes-1.0.0.rst).

2022-07-15 04:48 UTC, jori-nordic requested changes

2022-07-15 04:48 UTC, jori-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +For details, see `softdevice_controller_changelog`.
Please fix the link:
```rst
For details, see :ref:`nrfxlib:softdevice_controller_changelog`.
```
I got this syntax from the previous release notes (nrf/doc/nrf/releases/release-notes-1.0.0.rst).

2022-07-15 04:48 UTC, jori-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> -  * Added:
why the removed lines ? I think you need to rebase.

2022-07-15 11:50 UTC, ibaz-nordic commented
Retest results look good:
https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Ftest-fw-nrfconnect-ble/detail/master/17223/pipeline
https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Fdesktop52_verification/detail/master/12890/pipeline
https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Ftest-sdk-find-my/detail/master/3915/pipeline

2022-07-15 12:22 UTC, jori-nordic approved these changes

2022-07-15 12:38 UTC, Tschet1 approved these changes

2022-07-15 13:32 UTC, rlubos commented on west.yml
> +      revision: pull/776/head
Please update SHA: `0fb04fb543c564430325b1df92c973a013632059`

2022-07-18 07:55 UTC, rlubos commented
@greg-fer Any chance for a changelog review (the dedicated tech writer is OoO).

2022-07-18 08:09 UTC, peknis requested changes

2022-07-18 08:09 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added support for changing peripheral latency mode using :c:func:`sdc_hci_cmd_vs_peripheral_latency_mode_set`.
```suggestion
* Added support for changing the radio transmitter's default power level using the :c:func:`sdc_default_tx_power_set` function.
* Added support for changing the peripheral latency mode using the :c:func:`sdc_hci_cmd_vs_peripheral_latency_mode_set` function.
```

2022-07-18 08:20 UTC, peknis approved these changes

2022-07-18 10:08 UTC, merged