application: serial_lte_modem: BUG-FIX DFU file size
nrfconnect/sdk-nrf pull request #8169
Opened 2022-07-13 08:31 UTC by junqingzou

Add new #XDFUSIZE to return total and downloaded image size
To replace the old way of notifying the size by URC
Cancel infinite wait semaphore when download fails
Also correct a few errors in documentation.

JIRA case: NCSIDB-795

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2022-07-13 09:05 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8169
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-14 01:18 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25026/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-14 09:22 UTC, rlubos approved these changes

2022-07-14 10:57 UTC, FrancescoSer requested changes

2022-07-14 10:57 UTC, FrancescoSer commented on applications/serial_lte_modem/doc/DFU_AT_commands.rst
> +The ``#XDFUSIZE`` command returns the size of downloaded (:file:`.bin`) image file.
```suggestion
The ``#XDFUSIZE`` command returns the size of the downloaded (:file:`.bin`) image file.
```

2022-07-14 10:57 UTC, FrancescoSer commented on doc/nrf/releases/release-notes-changelog.rst
> +    * New #XDFUSIZE command to get the size of DFU file image.
```suggestion
    * New #XDFUSIZE command to get the size of the DFU file image.
```

2022-07-15 06:51 UTC, FrancescoSer approved these changes

2022-07-15 09:42 UTC, pirun approved these changes

2022-07-15 09:44 UTC, merged