ATv2: add more docs to cloud_codec.h
nrfconnect/sdk-nrf pull request #8200
Opened 2022-07-18 11:22 UTC by maxd-nordic

This patch adds missing doxygen comments to cloud_codec.h.
Additionally, the unused cloud_codec_release_data() function is removed.

Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

2022-07-18 11:43 UTC, coderbyheart approved these changes

2022-07-18 11:43 UTC, coderbyheart commented
Nice! 👍🏻

2022-07-18 12:06 UTC, maxd-nordic commented
(just noticed some small errors because I took this from the refactor branch)

2022-07-18 13:25 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25087/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-22 09:41 UTC, simensrostad requested changes
Few comments here and there. `lte_lc.h` is a good reference to based these doc updates on I think.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +	/** Contains current cell and number of neighbor cells */
```suggestion
	/** Contains current cell and number of neighbor cells. */
```

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +	/** Contains neighborhood cells */
```suggestion
	/** Contains neighborhood cells. */
```

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +	/** Cell neighborhood data timestamp. UNIX milliseconds. */
```suggestion
	/** Neighbor cells data timestamp. UNIX milliseconds. */
```

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +	/** New config data if type is CLOUD_CODEC_EVT_CONFIG_UPDATE */
I would rather update the documentation for the `CLOUD_CODEC_EVT_CONFIG_UPDATE` event to include the payload type parameters. Also include that `CLOUD_CODEC_EVT_CONFIG_UPDATE` is only used for the LwM2M build. This aligns well with how its done in other header files, for instance in `lte_lc.h` or `modem_module_event.h`.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +/** @brief Event handler prototype.
```suggestion
/**
  * @brief Event handler prototype.
```

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> +/** @brief Event handler prototype.
To align with the other docs added in this PR.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @details Is called once in the data module to initialize the cloud codec used.
I don't think its necessary to mention the caller here.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @note currently only used for config updates in lwm2m
I'd prefer to have the note after the brief section. To inform the user quickly if there are some special care needed for the API.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @details Is called as part of the data_encode() function to encode LTE neighbor cells info.
Gives specific information about the caller. I don't think this is necessary. The docs should be kept as generic as possible.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @details Is called as part of the data_encode() function to encode LTE neighbor cells info.
Some air in between sections would be nice. A little bit easier to read. This goes for the other documentation updates to this file as well.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @param[in] cfg current configuration
Could specify that the input parameter is a pointer, that goes for the other docs added in this patch as well.

2022-07-22 09:41 UTC, simensrostad commented on applications/asset_tracker_v2/src/cloud/cloud_codec/cloud_codec.h
> + * @return 0 on success or error code according to errno.h.
I would be nice if each individual return code could be documented, if possible with multiple backends. The return codes should be more or less aligned. That goes for the other APIs as well.

2022-08-08 11:48 UTC, simensrostad approved these changes

2022-08-08 12:02 UTC, merged