doc: document transition to default Thread 1.3
nrfconnect/sdk-nrf pull request #8244
Opened 2022-07-25 13:14 UTC by edmont

Make Thread 1.3.0 support clear.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

2022-07-25 13:29 UTC, Damian-Nordic approved these changes

2022-07-25 13:45 UTC, canisLupus1313 approved these changes

2022-07-25 14:04 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'
**test-sdk-find-my:** added because there was no .github/test-spec.yml in 'find-my'
**test-sdk-homekit:** added because there was no .github/test-spec.yml in 'homekit'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/v2.0-branch/43/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-25 14:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8244
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-26 08:18 UTC, greg-fer requested changes
Couple of comments.

2022-07-26 08:18 UTC, greg-fer commented on doc/nrf/ug_thread_configuring.rst
> +The OpenThread stack can be configured to operate in compliance with either the Thread 1.1 Specification, the :ref:`Thread 1.2 Specification <thread_ug_supported_features_v12>` or the :ref:`Thread 1.
```suggestion
The OpenThread stack can be configured to operate in compliance with either the Thread 1.1 Specification, the :ref:`Thread 1.2 Specification <thread_ug_supported_features_v12>`, or the :ref:`Thread 1.3 Specification <thread_ug_supported_features_v13>`.
```

2022-07-26 08:18 UTC, greg-fer commented on doc/nrf/ug_thread_supported_features.rst
> +The OpenThread implementation of the Thread protocol supports all features defined in the Thread 1.3.0 Specification which are required for the Thread 1.3 Certification program:
```suggestion
The OpenThread implementation of the Thread protocol supports all features defined in the Thread 1.3.0 Specification that are required for the Thread 1.3 Certification program:
```

2022-07-26 08:18 UTC, greg-fer commented on doc/nrf/ug_thread_supported_features.rst
> +By default, |NCS| supports Thread 1.3, which includes Thread 1.2 support.
```suggestion
By default, |NCS| supports Thread 1.3, which includes support for Thread 1.2.
```

2022-07-26 08:18 UTC, greg-fer commented on doc/nrf/ug_thread_supported_features.rst
> +|NCS| provides the required SRP client functionality
```suggestion
|NCS| provides the required SRP client functionality.
```

2022-07-26 08:18 UTC, greg-fer commented on doc/nrf/ug_thread_supported_features.rst
> +Thread 1.3 Specification introduces DNS-SD Service Registration Protocol as a way for devices to advertise the fact that they provide services, while avoiding the use of multicast in the discovery.
```suggestion
Thread 1.3 Specification introduces DNS-SD Service Registration Protocol, which lets devices advertise the fact that they provide services while avoiding the use of multicast in the discovery.
```

2022-07-26 08:36 UTC, LuDuda approved these changes

2022-07-26 08:39 UTC, greg-fer approved these changes

2022-07-26 11:36 UTC, merged