lib: at_host: use ncs,at-host-uart
nrfconnect/sdk-nrf pull request #8260
Opened 2022-07-26 09:54 UTC by gmarull

Move AT Host UART choice to Devicetree by using ncs,at-host-uart. This
allows to obtain the UART device reference at compile time.

Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>

2022-07-26 10:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8260
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-26 11:08 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25257/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-26 13:24 UTC, anangl approved these changes

2022-07-26 13:24 UTC, anangl commented on lib/at_host/at_host.c
> +static const struct device *uart_dev = DEVICE_DT_GET(DT_CHOSEN(ncs_at_host_uart));
```suggestion
static const struct device *const uart_dev = DEVICE_DT_GET(DT_CHOSEN(ncs_at_host_uart));
```

2022-07-27 17:35 UTC, glarsennordic requested changes
I suggest defaulting to `DT_CHOSEN(zephyr_shell_uart)` if `ncs,at-host-uart` is not set.

That way samples aren't forced to include a device tree overlay file for every board they intend to support, and this module will work on any board that supports the zephyr UART shell without need of device tree configuration changes

You can use `DT_HAS_CHOSEN` to check whether `ncs,at-host-uart` is set

2022-07-28 21:36 UTC, gmarull commented
> I suggest defaulting to `DT_CHOSEN(zephyr_shell_uart)` if `ncs,at-host-uart` is not set.
> 
> That way samples aren't forced to include a device tree overlay file for every board they intend to support, and this module will work on any board that supports the zephyr UART shell without need of device tree configuration changes
> 
> You can use `DT_HAS_CHOSEN` to check whether `ncs,at-host-uart` is set

I don't think it is a good idea to re-use other choices. `zephyr,shell-uart` is specifically meant for the shell subsystem, so using it for something else is wrong IMO. Why should my shell be polluted with other stuff? One option would to default to, e.g., `uart0`, but I don't think this is a good practice anyway.

@mbolivar-nordic can you comment, please?

2022-07-28 21:53 UTC, glarsennordic commented
> Why should my shell be polluted with other stuff? 

I look at `zephyr,shell-uart` as a "sane choice" for a default in situations where `ncs,at-host-uart` was not specified

Both are sharing `uart0` on nordic boards anyways, so that pollution is happening either way. And the user still has the option to set `ncs,at-host-uart` if they want both to be on separate UART devices

I personally think requiring an overlay file for every combination of sample and target board should be avoided.

I suppose you could add `ncs,at-host-uart` to the `nrf9160dk_nrf9160_common.dts` and `thingy91_nrf9160_common.dts` files, (which is where the choices for `zephyr,shell-uart`, `zephyr,console` and `zephyr,uart-mcumgr` all live). But that seems a bit too broad in scope since this library is optional for those boards

I wonder if there is a way to create default device tree overlays at the library level. You could put the choice definition there, in that case

2022-08-02 11:26 UTC, tokangas commented
I agree with @glarsennordic that having to set `ncs,at-host-uart` in all samples it not very convenient.

I guess setting it in the board configuration for nRF9160 DK might not be possible, because the board DTS file comes from Zephyr and this is an NCS specific configuration?

2022-08-02 17:50 UTC, glarsennordic commented
> I guess setting it in the board configuration for nRF9160 DK might not be possible, because the board DTS file comes from Zephyr and this is an NCS specific configuration?

Oh man... You're totally right. I completely forgot about that. I guess that approach is out the window.

2022-08-03 08:56 UTC, divipillai commented on doc/nrf/libraries/modem/at_host.rst
> +The UART is chosen in Devicetree by using ``ncs,at-host-uart`` like this:
```suggestion
The UART is chosen by using ``ncs,at-host-uart`` in devicetree in the following way:
```
Just a minor suggestion.

2022-08-03 10:43 UTC, gmarull commented
> I agree with @glarsennordic that having to set `ncs,at-host-uart` in all samples it not very convenient.
> 
> I guess setting it in the board configuration for nRF9160 DK might not be possible, because the board DTS file comes from Zephyr and this is an NCS specific configuration?

Note that this approach has been taken by other subsystems in NCS. Some action will be required for the next upmerge, as labels have been removed upstream.

2022-08-03 19:36 UTC, mbolivar-nordic commented
> I don't think it is a good idea to re-use other choices. [...] @mbolivar-nordic can you comment, please?

I agree.

2022-08-03 20:01 UTC, glarsennordic commented
Is it just best practice, then, to require a device tree overlay file for every combination of sample and supported board, or is there a third option we're not seeing to this problem, @mbolivar-nordic ?

2022-08-04 07:14 UTC, divipillai approved these changes

2022-08-04 09:37 UTC, trantanen commented
> > One option would to default to, e.g., uart0, but I don't think this is a good practice anyway.
> 
> To be honest, I'm not sure this would actually be a terrible idea

Is this option something we should still consider? I agree with @tokangas and @glarsennordic that having some default that is used, e.g., 95% of the time would be convenient. I understand this may not be perfect ideologically but are there other drawbacks in this approach?

2022-08-15 23:41 UTC, plskeggs commented
> I don't think it is a good idea to re-use other choices. `zephyr,shell-uart` is specifically meant for the shell subsystem, so using it for something else is wrong IMO. Why should my shell be polluted with other stuff? One option would to default to, e.g., `uart0`, but I don't think this is a good practice anyway.

FYI, I've tried using at_host and the shell together before, and it doesn't work -- they each want to handle input from the user.

I instead added a shell command to switch in and out of AT mode with `at enable`.  Enabling is done using `shell_set_root_cmd("at")`.  When in AT mode, all shell input gets routed to the nrf_modem_at_cmd() function inside my AT shell command handler.  If the user input is actually the string "exit", then it exits AT mode.

2022-08-16 09:07 UTC, nordicjm commented
> > I guess setting it in the board configuration for nRF9160 DK might not be possible, because the board DTS file comes from Zephyr and this is an NCS specific configuration?
> 
> Oh man... You're totally right. I completely forgot about that. I guess that approach is out the window.

We have noup patches for boards in sdk-zephyr already, e.g. https://github.com/nrfconnect/sdk-zephyr/commit/c89343ac27c14bdacb61b1464c518543a0617ccd

2022-08-16 09:10 UTC, gmarull commented
The approach listed here has been adopted by a few other NCS subsystems, not sure why this case should be an exception. I'd like to see an alternative if this is not convincing (which I can understand).

2022-08-16 10:15 UTC, tokangas commented
I think we can say, that AT host almost always uses `uart0`. This PR has 20 board overlays, which all set the UART to `uart0`. Because of this it would be convenient that this would be the default. That's the only comment I have, otherwise this change is perfectly fine.

2022-08-16 10:51 UTC, de-nordic commented
> I think we can say, that AT host almost always uses `uart0`. This PR has 20 board overlays, which all set the UART to `uart0`. Because of this it would be convenient that this would be the default. That's the only comment I have, otherwise this change is perfectly fine.

@gmarull Is it possible to make the uart0 default option when not provided, and document this?

2022-08-16 10:53 UTC, gmarull commented
> > I think we can say, that AT host almost always uses `uart0`. This PR has 20 board overlays, which all set the UART to `uart0`. Because of this it would be convenient that this would be the default. That's the only comment I have, otherwise this change is perfectly fine.
> 
> @gmarull Is it possible to make the uart0 default option when not provided, and document this?

I guess it's a fair solution provided this is non-portable code. I will update PR later.

2022-08-16 12:23 UTC, carlescufi commented
@gmarull I think the `noup` patch proposal from @nordicjm makes sense, what is it you don't like there?

2022-08-16 12:52 UTC, gmarull commented
> @gmarull I think the `noup` patch proposal from @nordicjm makes sense, what is it you don't like there?

at_host library is using Kconfig to specify a hardware choice (hardcoding uart selection 0,1,2). This belongs to the Devicetree domain.

2022-08-16 12:57 UTC, carlescufi commented
> > @gmarull I think the `noup` patch proposal from @nordicjm makes sense, what is it you don't like there?
> 
> at_host library is using Kconfig to specify a hardware choice (hardcoding uart selection 0,1,2). This belongs to the Devicetree domain.

I mean a `noup` that adds the `chosen` node to the upstream boards' `.dts` files @gmarull

2022-08-16 13:03 UTC, de-nordic commented
@glarsennordic Can you take a look now? I think that your issue has been addressed.

2022-08-16 13:09 UTC, gmarull commented
> > > @gmarull I think the `noup` patch proposal from @nordicjm makes sense, what is it you don't like there?
> > 
> > 
> > at_host library is using Kconfig to specify a hardware choice (hardcoding uart selection 0,1,2). This belongs to the Devicetree domain.
> 
> I mean a `noup` that adds the `chosen` node to the upstream boards' `.dts` files @gmarull

Not a bad solution, just that I prefer to avoid `noups`. We probably need a standard mechanism to _extend_ boards downstream.

2022-08-16 13:36 UTC, carlescufi commented
> Not a bad solution, just that I prefer to avoid `noups`. We probably need a standard mechanism to _extend_ boards downstream.

We do. @tejlmand this is something for you mid-term.

2022-08-16 16:49 UTC, glarsennordic approved these changes
LGTM

Thanks for finding a way to remove all the overlays, I appreciate it

If you decide to go with a noup for the default instead, I'd be fine with that too.

2022-08-16 16:54 UTC, merged