boards: arm: thingy91_nrf9160: Change pwmleds frequency
nrfconnect/sdk-nrf pull request #8269
Opened 2022-07-26 23:18 UTC by glarsennordic

Changed the PWM frequency of pwmleds from 50hz to 125hz

50hz is directly perceptible by most humans

125hz is significantly less perceptible

IRIS4619

Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>

2022-07-26 23:32 UTC, plskeggs approved these changes
Seems OK.  It's important for a few others to review in addition to docs.

2022-07-26 23:48 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25282/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-07-26 23:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8269
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-07-27 06:09 UTC, peknis requested changes

2022-07-27 06:09 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +=========================
```suggestion
Devicetree configuration
========================
```

2022-07-27 06:09 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +* Changed the PWM frequency of the pwmleds device from 50hz to 125hz
```suggestion
* Changed the PWM frequency of the pwmleds device from 50 Hz to 125 Hz.
```
See https://projecttools.nordicsemi.no/confluence/display/TECHDOC/Units+of+measurement

2022-07-28 05:48 UTC, peknis approved these changes

2022-08-08 11:36 UTC, simensrostad approved these changes
Looks good to me

2022-08-15 22:58 UTC, plskeggs approved these changes

2022-08-18 08:22 UTC, merged