Bluetooth: Samples: Throughput speed optimalization
nrfconnect/sdk-nrf pull request #8374
Opened 2022-08-10 14:27 UTC by KAGA164

2022-08-10 14:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8374
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-10 14:59 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25698/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-11 06:51 UTC, peknis requested changes

2022-08-11 06:51 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Optimize throughput speed by increasing MTU to 498 and using the maximum connection event time.
```suggestion
  * Optimized throughput speed by increasing MTU to 498 and using the maximum connection event time.
```

2022-08-11 07:52 UTC, alwa-nordic approved these changes

2022-08-11 13:09 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Optimize throughput speed by increasing MTU to 498 and using the maximum connection event time.
Done

2022-08-12 12:45 UTC, kapi-no approved these changes

2022-08-12 12:49 UTC, maje-emb reviewed
Shouldn't we also update the `Default parameter values` table in the documentation?

2022-08-12 13:10 UTC, KAGA164 commented
> Shouldn't we also update the `Default parameter values` table in the documentation?

@maje-emb Right. I totally forgot about it. I updated the default parameters in a documentation

2022-08-12 13:17 UTC, maje-emb approved these changes

2022-08-16 07:07 UTC, merged