applications: asset_tracker_v2: Disable LwM2M bootstrap option
nrfconnect/sdk-nrf pull request #8385
Opened 2022-08-11 14:58 UTC by simensrostad

Bootstrapping is a paid service and not included in free tier accounts
in AVSystem Coiote Device management.

To enfore the out of box experience with AVSystem and not depend on
customers paying for the bootstrap service, bootstrapping
is disabled by default in the application.

CIA-719

2022-08-11 15:04 UTC, coderbyheart commented
/cc @SeppoTakalo @bkvaale

2022-08-11 15:06 UTC, coderbyheart approved these changes

2022-08-11 15:07 UTC, simensrostad commented
@peknis @umapraseeda Needs a doc review, thanks!

2022-08-11 15:29 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25737/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-11 15:33 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8385
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-12 05:45 UTC, peknis requested changes

2022-08-12 05:45 UTC, peknis commented on applications/asset_tracker_v2/doc/cloud_module.rst
> +This enables the device to work with `Coiote Device Management`_ without provisioning the PSK to the modem prior to running the application.
```suggestion
This enables the device to work with `Coiote Device Management`_ without provisioning the PSK to the modem before running the application.
```

2022-08-12 05:45 UTC, peknis commented on applications/asset_tracker_v2/doc/cloud_module.rst
> +See :ref:`server setup <server_setup_lwm2m>` for information on how the `Coiote Device Management server`_ can be configured to communicate with the application using the default PSK.
```suggestion
See :ref:`server setup <server_setup_lwm2m>` for information on how you can configure the `Coiote Device Management server`_  to communicate with the application using the default PSK.
```

2022-08-12 05:45 UTC, peknis commented on applications/asset_tracker_v2/doc/cloud_module.rst
> +   The PSK should also be provisioned to the modem prior to running the application.
```suggestion
   The PSK should also be provisioned to the modem before running the application.
```

2022-08-12 05:45 UTC, peknis commented on applications/asset_tracker_v2/doc/cloud_module.rst
> +   In production it is not recommended to use the default PSK that is automatically provisioned by the application.
```suggestion
   In production, it is not recommended to use the default PSK that is automatically provisioned by the application.
```

2022-08-12 05:45 UTC, peknis commented on applications/asset_tracker_v2/doc/cloud_module.rst
> +   This can be done by disabling the :kconfig:option:`CONFIG_LWM2M_INTEGRATION_PROVISION_CREDENTIALS` option and provisioning the PSK to a sec tag set by :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_SE
```suggestion
   Disable the :kconfig:option:`CONFIG_LWM2M_INTEGRATION_PROVISION_CREDENTIALS` option and provision the PSK to a sec tag set by :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_SERVER_TLS_TAG` or :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_BOOTSTRAP_TLS_TAG`.
```

2022-08-12 10:18 UTC, simensrostad commented
@peknis Suggestions applied. Added a changelog entry, that will need a lookover as well.

2022-08-12 10:21 UTC, peknis approved these changes

2022-08-12 15:32 UTC, merged