samples: matter: Added support for WiFi in lock sample
nrfconnect/sdk-nrf pull request #8389
Opened 2022-08-12 07:43 UTC by kkasperczyk-no

* Updated sdk-connectedhomeip SHA to pull Wi-Fi support in Matter
* Added code necessary to initialize WiFi driver
* Moved OpenThread config options from prj.confs to Kconfig file
* Added nrf7002dk and nrf7002_ek platforms to twister builds
* Extended documentation to include information about Wi-Fi
* Added handling user interface for nrf7002dk that has two
LEDs and two buttons.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

2022-08-12 07:43 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/632800fe7f2ef765abb47311a34611a186d9f4b2 (master) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/92 | [nrfconnect/sdk-connectedhomeip#92/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/92/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-08-12 08:28 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25757/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-12 09:07 UTC, markaj-nordic reviewed
Looks like we need to align ZAP and regenerate data model implementation to add WiFi related clusters, i.e. WiFi diagnostic cluster.

2022-08-12 10:53 UTC, LuDuda approved these changes

2022-08-12 10:56 UTC, Damian-Nordic approved these changes

2022-08-12 10:56 UTC, Damian-Nordic commented on samples/matter/light_bulb/README.rst
> +You have to make the device discoverable manually (for security reasons).
It is not true for light_bulb.

2022-08-12 11:13 UTC, LuDuda commented on west.yml
> +      revision: pull/92/head
```suggestion
      revision: 238a18db4eae15381c3c1838d8e863d841c59ead
```

2022-08-12 12:48 UTC, greg-fer requested changes
One comment + please squash my commit.

2022-08-12 12:48 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Introduced support for Matter over Wi-Fi on nrf7002dk_nrf5340_cpuapp and nrf5340dk_nrf5340_cpuapp with nrf7002_ek shield.
```suggestion
  * Introduced support for Matter over Wi-Fi on ``nrf7002dk_nrf5340_cpuapp`` and on ``nrf5340dk_nrf5340_cpuapp`` with the ``nrf7002_ek`` shield.
```

2022-08-12 12:50 UTC, Damian-Nordic approved these changes

2022-08-12 12:50 UTC, Damian-Nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Support for Matter over Wi-Fi.
Experimental?

2022-08-12 12:57 UTC, kkasperczyk-no commented
> Looks like we need to align ZAP and regenerate data model implementation to add WiFi related clusters, i.e. WiFi diagnostic cluster.

As discussed F2F it will be addressed in the followup PR adding support for Wi-Fi in light-switch sample.

2022-08-12 12:58 UTC, markaj-nordic approved these changes

2022-08-12 13:01 UTC, greg-fer approved these changes

2022-08-12 14:32 UTC, greg-fer commented
@kkasperczyk-no , made a push to solve the doc build issue.

2022-08-15 10:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8389
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-15 18:52 UTC, merged