samples: bluetooth: hr_coded: Redesign samples
nrfconnect/sdk-nrf pull request #8392
Opened 2022-08-12 09:00 UTC by KAGA164

Redesign the Peripheral HR coded and the Central
HR coded samples to make them consistent with
other Bluetooth samples.

2022-08-12 09:25 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25761/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-12 10:05 UTC, alwa-nordic approved these changes

2022-08-12 11:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8392
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-15 10:08 UTC, peknis commented
Remember the changelog.

2022-08-15 10:09 UTC, peknis requested changes

2022-08-15 10:09 UTC, peknis commented on samples/bluetooth/peripheral_hr_coded/README.rst
> +This sample uses the following |NCS| libraries:
```suggestion
This sample uses the following |NCS| library:
```

2022-08-16 08:44 UTC, KAGA164 commented on samples/bluetooth/peripheral_hr_coded/README.rst
> +This sample uses the following |NCS| libraries:
Done

2022-08-16 08:46 UTC, peknis approved these changes

2022-08-16 08:46 UTC, KAGA164 commented
> Remember the changelog.

@peknis Do we need to change changelog? The sample have the same functionality like previously, I just redesign a code and add leds. What do you think?

2022-08-16 08:48 UTC, peknis commented
> > Remember the changelog.
> 
> @peknis Do we need to change changelog? The sample has the same functionality like previously, I just redesign a code and add leds. What do you think?

I believe we are ok without. Please, remove the changelog-entry-required tag.

2022-08-16 08:56 UTC, dchat-nordic approved these changes

2022-08-17 14:02 UTC, merged