samples: Bluetooth: llpm: Fixing llpm sample on nrf53
nrfconnect/sdk-nrf pull request #8408
Opened 2022-08-15 21:01 UTC by martintv

Without this I'm not able to run this sample on nrf53 app core.
I think it is because IPC work doens't get to execute, since main thread is in this busylopp.
But I don't understand IPC so well, so I might be wrong. I thought main thread was preemptive and that IPC to hci_rpmsg on the netcore should work even if main thread is busylooping. Please let me know if I have misunderstood and something else is going on.

Anyway, I tested locally and it doesn't work without this commit, but works with it. This is how I built:
west build -b nrf5340dk_nrf5340_cpuapp nrf/samples/bluetooth/llpm --build-dir build_53

And then flash, and observe that you don't receive any adv reports when you select central (by typing c on the console).
But with this commit it works

2022-08-15 21:30 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25819/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-15 21:33 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8408
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-16 06:55 UTC, alwa-nordic commented
@ryanjh It looks like you are the author of this sample. What do you think?

2022-08-16 13:18 UTC, ryanjh commented
Could this issue be reproduced on Net core? Although, nrf5340_net hasn't been added into platform_allow. The LLPM latency is measured in the sample. When running it on App core, the extra delay of IPC is also included. It is better to support nrf5340dk_nrf5340_cpunet.

2022-08-16 20:51 UTC, martintv commented
> Could this issue be reproduced on Net core? Although, nrf5340_net hasn't been added into platform_allow. The LLPM latency is measured in the sample. When running it on App core, the extra delay of IPC is also included. It is better to support nrf5340dk_nrf5340_cpunet.

simply doing:
west build -b nrf5340dk_nrf5340_cpunet nrf/samples/bluetooth/llpm --build-dir build_53_net
west flash --build-dir build_53_net
doesn't work for me atleast. 
I get: 
*** Booting Zephyr OS build v3.0.99-ncs1-2483-g482dcc7865f7  ***
Starting Bluetooth LLPM example
E: Endpoint binding failed with -11
E: HCI driver open failed (-11)
Bluetooth init failed (err -11)

2022-08-16 21:00 UTC, martintv commented
We do still document that LLPM doesn't work on nrf53. So I guess it doesnt hurt that this sample doensnt work on nrf53. but I still want to merge this, because with this at least this sample runs on nrf53, but with worse performance than expected when switching to LLPM..

And it is a bit bad this this bug is the reason it breaks on nrf53.

I have been using this sample to test some stuff on nrf53, even without LLPM (it prints that before switching to LLPM)

2022-08-17 06:35 UTC, alwa-nordic commented
I'm skeptical to adding sleeps. Would it work to `k_yield()` instead? @martintv

2022-08-17 06:46 UTC, alwa-nordic commented
I suspect `test_ready` should be a semaphore. Using a semaphore would both properly block the thread running `main()` and also ensure correct synchronization between the main thread and BT RX. A simple `bool test_ready` is not guaranteed to work for synchronization between threads.

2022-08-17 09:52 UTC, KAGA164 requested changes
This does not work because the main thread and RPMSG backend thread have the same priority 0 that is the highest possible priority for preemptive thread. You can use `k_yield` in main thread loop or set the RPMsg thread to be cooperative thread by an overlay but I didn't test it

2022-08-17 09:52 UTC, KAGA164 commented on samples/bluetooth/llpm/src/main.c
> +		k_sleep(K_MSEC(100));
```suggestion
		k_yield();
```

2022-08-18 07:22 UTC, alwa-nordic approved these changes

2022-08-18 08:19 UTC, KAGA164 approved these changes

2022-08-18 08:21 UTC, KAGA164 approved these changes

2022-08-18 08:21 UTC, KAGA164 commented on samples/bluetooth/llpm/src/main.c
> +K_SEM_DEFINE(test_ready_sem, 0, 1);
```suggestion
static K_SEM_DEFINE(test_ready_sem, 0, 1);
```

2022-08-18 08:32 UTC, ryanjh approved these changes

2022-08-23 05:57 UTC, jori-nordic approved these changes
Could you also raise a PR (or ask someone else to do it) to raise the ipc workqueue priority to a coop level (with a dts overlay)?

2022-08-30 12:31 UTC, merged