net: lib: nrf_cloud: fix nrf_cloud_client_id_get for MQTT and REST
nrfconnect/sdk-nrf pull request #8429
Opened 2022-08-17 17:25 UTC by jayteemo

Fix nrf_cloud_client_id_get so that it returns a valid client ID
when MQTT and REST are both enabled and nrf_cloud_init has not
been called.
NCSDK-16475

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2022-08-17 17:51 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-sdk-coverity | | | X |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25891/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-17 18:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8429
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-17 20:26 UTC, plskeggs approved these changes

2022-08-17 20:28 UTC, glarsennordic approved these changes
LGTM

Nice catch, nice fix

2022-08-18 05:26 UTC, tokangas approved these changes

2022-08-18 05:26 UTC, jhirsi approved these changes

2022-08-22 09:34 UTC, peknis requested changes

2022-08-22 09:34 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +      * An issue that caused :c:func:`nrf_cloud_client_id_get` to fail if both :kconfig:option:`CONFIG_NRF_CLOUD_MQTT` and :kconfig:option:`CONFIG_NRF_CLOUD_REST` are enabled.
```suggestion
      * An issue that caused the :c:func:`nrf_cloud_client_id_get` function to fail if both :kconfig:option:`CONFIG_NRF_CLOUD_MQTT` and :kconfig:option:`CONFIG_NRF_CLOUD_REST` were enabled.
```

2022-08-23 05:33 UTC, peknis approved these changes

2022-08-23 07:14 UTC, merged