doc: release: Update Zephyr commit from upmerge
nrfconnect/sdk-nrf pull request #8463
Opened 2022-08-22 08:53 UTC by nordicjm

Updates the release note documentation to have the zephyr commit
details resulting from the latest upmerge

2022-08-22 09:41 UTC, nvlsianpu reviewed
MCUboot changes:

boot_serial: refactoring and optimalization (mainly afects progresive erase implementation)
- migrate includes to <zephyr/...>
- switched DFU detection GPIO-pin configuration to be done through DTS.
  That pin is assigned thanks to `mcuboot-button0` pin-alias.
- boot_serial: Fix echo command code no longer compiling
- Added MCUboot status callback support, see `CONFIG_MCUBOOT_ACTION_HOOKS` Kconfig option.
- reworked LED usage, prefer DTS mcuboot-led0 alias over bootloader-led0 alias
- Added initial support for leverage RAM-LOAD mode with the zephyr-rtos port
- boot_serial: Upgrade from cddl-gen 0.1.0 to zcbor 0.4.0
- zephyr: removed device_get_binding() usage in favor to DEVICE_DT_GET()

- imgtool: Added support for providing the signature by 3rd party

2022-08-22 10:01 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-coverity | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/25997/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-25 13:57 UTC, greg-fer requested changes

2022-08-25 13:57 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added :kconfig:option:`CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK` to override the external driver check, this is needed when using an external flash which is not using the QSPI NOR driver
```suggestion
* Added :kconfig:option:`CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK` to override the external driver check.
  This is needed when using an external flash which is not using the :ref:`QSPI NOR <zephyr:dtbinding_nordic_qspi_nor>` driver from Zephyr.
```

2022-08-25 13:57 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added initial support for leveraging RAM-LOAD mode with the zephyr-rtos port
```suggestion
* boot_serial: 

  * Refactored and optimized the code, mainly in what affects the progressive erase implementation.
  * Fixed a compilation issue with the echo command code.
  * Upgraded from cddl-gen v0.1.0 to zcbor v0.4.0.

* imgtool: Added support for providing signature through a third party.
* zephyr:
   
  * Added initial support for leveraging the RAM-LOAD mode with the zephyr-rtos port.
  * Added the MCUboot status callback support.
    See :kconfig:option:`CONFIG_MCUBOOT_ACTION_HOOKS`.
  * Edited includes to have the ``zephyr/`` prefix.
  * Edited the DFU detection's GPIO-pin configuration to be done through DTS using the ``mcuboot-button0`` pin alias.
  * Edited the LED usage to prefer DTS' ``mcuboot-led0`` alias over the ``bootloader-led0`` alias.
  * Removed :c:func:`device_get_binding()` usage in favor of :c:func:`DEVICE_DT_GET()`.
```

2022-08-25 13:57 UTC, greg-fer commented on scripts/partition_manager/partition_manager.rst
> +  If the external flash device is not using the QSPI NOR driver, :kconfig:option:`CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK` must be enabled to override the PM external flash driver check, and the req
```suggestion
   If the external flash device is not using the :ref:`QSPI NOR <zephyr:dtbinding_nordic_qspi_nor>` driver, :kconfig:option:`CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK` must be enabled to override the Partition Manager's external flash driver check, and the required driver must also be enabled for all applications that need it.
```

2022-08-30 06:58 UTC, greg-fer approved these changes

2022-08-31 06:46 UTC, nordicjm commented
@carlescufi @de-nordic can you review documentation updates please?

2022-09-01 13:47 UTC, de-nordic approved these changes

2022-09-05 08:21 UTC, carlescufi approved these changes

2022-09-05 08:21 UTC, merged