doc improvement: adding new terms to the glossary
nrfconnect/sdk-nrf pull request #8479
Opened 2022-08-23 07:51 UTC by peknis

In other PRs, bumped to a handful of new abbreviations
that deserve an entry in the glossary.

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2022-08-23 08:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8479
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-23 08:45 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26062/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-23 10:03 UTC, trantanen approved these changes

2022-08-24 10:43 UTC, b-gent requested changes

2022-08-24 10:43 UTC, b-gent commented on doc/nrf/glossary.rst
> +      Any device used directly by an end-user to communicate. It can be a hand-held telephone, a laptop computer equipped with a mobile broadband adapter, or any other device.
Please split into two lines.

2022-08-24 11:16 UTC, b-gent approved these changes

2022-08-24 11:31 UTC, merged