mpsl: Add possibility to use only front-end modules API
nrfconnect/sdk-nrf pull request #8487
Opened 2022-08-23 13:00 UTC by KAGA164

Add possibility to use front-end modules API from MPSL
without other MPSL features. It gives us possibility
to use FEM drivers from MPSL in the Direct Test Mode
sample, the Radio Test sample and in other Nordic's
radio protocols like the ESB.

2022-08-23 13:47 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26103/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-23 14:06 UTC, grochu reviewed
@KAGA164 maybe updating the following section in docs can be done in this PR? http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_radio_fem.html#ug-radio-fem-nrf21540-ek

2022-08-23 14:09 UTC, KAGA164 commented
> @KAGA164 maybe updating the following section in docs can be done in this PR? http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/ug_radio_fem.html#ug-radio-fem-nrf21540-ek

Yes. I going to update doc and add changelog entry about this but lets wait for other reviews

2022-08-23 14:11 UTC, czeslawmakarski approved these changes

2022-08-25 11:29 UTC, jciupis approved these changes

2022-08-25 12:49 UTC, grochu approved these changes
Looks good

2022-08-25 13:08 UTC, peknis requested changes

2022-08-25 13:36 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +  Using other MPSL features is not possible when this option is enabled.
Done

2022-08-25 13:37 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +  The :ref:`nrfxlib:mpsl_lib` (MPSL) is linked into build without the initialization.
Done

2022-08-25 13:37 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +* Added the :kconfig:option:`CONFIG_MPSL_FEM_ONLY` that allows the :ref:`nrfxlib:mpsl_fem` to be used without other MPSL features.
Done

2022-08-25 13:37 UTC, KAGA164 commented on doc/nrf/ug_radio_fem.rst
> +In this case you must enable following options:
Done

2022-08-26 05:49 UTC, peknis approved these changes

2022-08-26 14:42 UTC, merged