doc: app_dev: expand list of output files
nrfconnect/sdk-nrf pull request #8525
Opened 2022-08-25 12:59 UTC by greg-fer

Added TF-M output files to the output file table.
NCSIDB-718.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2022-08-25 13:25 UTC, joerchan commented on doc/nrf/app_build_system.rst
> +| :file:`tfm_s.hex`               |                                                                                                 | DFU over Zigbee for both single-core and multi-core applications
The "DFU over zigbee" line is a copy-paste error?

2022-08-25 13:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8525
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-30 08:05 UTC, umapraseeda commented
Do we need a changelog entry? @balaji-nordic could you confirm if we can delete the table from ug_thingy91.rst?

2022-08-30 10:13 UTC, balaji-nordic requested changes
I prefer to keep the table in thingy user guide because it is more specific to the thingy use case. For example, many thingy users will have to use an 'external programmer' and 'nrf Connect programmer app' for programming. Since we have the right wording for that use cases in that table, and is very difficult to put those in the generic app_build_system.rst file, its better to keep that table.

2022-08-30 13:29 UTC, greg-fer commented
> 

No problem, @balaji-nordic , as long as we link to the output build section from under the table. Restored the table.

2022-08-30 17:54 UTC, balaji-nordic approved these changes

2022-08-31 07:18 UTC, divipillai approved these changes
Just a minor comment.

2022-08-31 08:42 UTC, greg-fer commented
@trond-snekvik , @joerchan , can you have a look? :)

2022-08-31 10:19 UTC, umapraseeda approved these changes

2022-08-31 17:01 UTC, trond-snekvik approved these changes

2022-09-01 08:26 UTC, merged