Gazell support for nRF5340 network core
nrfconnect/sdk-nrf pull request #8530
Opened 2022-08-26 03:24 UTC by leewkb4567

Support Gazell on nRF5340 network core.

The GZLL in nrfconnect/nrfxlib#812 is included for CI testing.

The fix in #8347 is cherry-picked.

2022-08-26 03:24 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/f1bdea31a936fbaa1d52dce7a59788f51c021083 (main) | https://github.com/nrfconnect/sdk-nrfxlib/pull/812 | [nrfconnect/sdk-nrfxlib#812/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/812/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-08-26 03:53 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26251/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-26 03:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8530
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-31 07:30 UTC, peknis requested changes

2022-08-31 07:30 UTC, peknis commented on doc/nrf/libraries/gazell/gzp.rst
> +In addition, the Gazell Pairing library also employs three nRF52/3 Series peripherals:
```suggestion
In addition, the Gazell Pairing library also employs three nRF52 and nRF533 Series peripherals:
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +* Three PPI / DPPI channels
```suggestion
* Three PPI/DPPI channels
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +   The byte order in Gazell and the nRF52/3 Series radio peripheral are not the same.
```suggestion
   The byte order in Gazell and the nRF52 and nRF53 Series radio peripheral are not the same.
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +The Gazell Low Power Host role (Host role 1) is not supported in the nRF52/3 Series.
```suggestion
The Gazell Low Power Host role (Host role 1) is not supported in the nRF52 and nRF53 Series.
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +* Use the :c:func:`nrf_gzll_set_channel_table()` function in the nRF52/3 Series projects.
```suggestion
* Use the :c:func:`nrf_gzll_set_channel_table()` function in the nRF52 and nRF53 Series projects.
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +* 504 us timeslot period, nRF52/3 Series Gazell Device to nRF24L IC Gazell Host.
```suggestion
* 600 us timeslot period, nRF52 and nRF53 Series Gazell Device to nRF52 and nRF53 Series Gazell Host.
* 504 us timeslot period, nRF52 and nRF53 Series Gazell Device to nRF24L IC Gazell Host.
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +* Use the :c:func:`nrf_gzll_set_timeslot_period()` function in the nRF52/3 Series projects (nRF52/3 Series Gazell timeslot period = 0.5*GZLL_RX_PERIOD).
```suggestion
* Use the :c:func:`nrf_gzll_set_timeslot_period()` function in the nRF52 and nRF53 Series projects (nRF52 and nRF53 Series Gazell timeslot period = 0.5*GZLL_RX_PERIOD).
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +The Gazell Link Layer protocol for the nRF52/3 Series is compatible with the most useful roles of the Gazell Link Layer for the nRF24L IC.
```suggestion
The Gazell Link Layer protocol for the nRF52 and nRF53 Series is compatible with the most useful roles of the Gazell Link Layer for the nRF24L IC.
```

2022-08-31 07:30 UTC, peknis commented on doc/nrf/ug_gzll.rst
> +The 2.4 GHz proprietary radio uses an alternating sequence of 0s and 1s as the preamble of the packet.
```suggestion
The 2.4 GHz proprietary radio uses an alternating sequence of 0 s and 1 s as the preamble of the packet.
```

2022-09-02 05:04 UTC, leewkb4567 commented
@peknis Your comments are addressed.

2022-09-02 05:17 UTC, peknis approved these changes

2022-09-19 13:57 UTC, carlescufi commented
@leewkb4567 is this still DNM?

2022-09-20 04:25 UTC, leewkb4567 commented
@carlescufi CI adds DNM label when manifest points to the nrfxlib gzll PR for nRF5340.

Rebase to current main.

2022-09-20 14:45 UTC, carlescufi commented
> @carlescufi CI adds DNM label when manifest points to the nrfxlib gzll PR for nRF5340.
> 
> Rebase to current main.

Oh right, I merged the nrfxlib PR now.

2022-09-26 07:59 UTC, leewkb4567 commented
Rebase to current main, which manifest has the nRF5340 GZLL library.

2022-11-29 02:38 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8530/9/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8530/9/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-proprietary_esb | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8530/9/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-29 02:44 UTC, leewkb4567 commented
Rebase to current main.

2022-12-09 06:35 UTC, leewkb4567 commented
Rebase to current main.

2023-06-15 03:32 UTC, leewkb4567 commented
Rebase to current main.

2023-08-29 00:27 UTC, closed without merging