doc: Add an Gazell section in the memory optimization guide.
nrfconnect/sdk-nrf pull request #8543
Opened 2022-08-29 05:30 UTC by leewkb4567

Add an Gazell section in the memory optimization guide.

JIRA: NCSDK-14483

2022-08-29 06:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8543
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-29 06:07 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26293/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-31 07:06 UTC, peknis requested changes

2022-08-31 07:06 UTC, peknis commented on doc/nrf/app_memory.rst
> +If your application is a Pairing Device, you may study the system workqueue stack size.
```suggestion
Specifically, study the Interrupt Service Routine (ISR) stack size.
If your application is in a pairing device, pay attention to the system workqueue stack size.
```

2022-08-31 07:06 UTC, peknis commented on doc/nrf/app_memory.rst
> +Do not enable the features that your application does not use. The configuration options default to disable the optional features.
```suggestion
Do not enable features that your application does not use.
The configuration options default to disabling optional features, such as:
```

2022-08-31 07:06 UTC, peknis commented on doc/nrf/app_memory.rst
> +You may reduce the logging level by the setting configuration option :kconfig:option:`CONFIG_GAZELL_LOG_LEVEL_CHOICE`.
```suggestion
To reduce the logging level, set the :kconfig:option:`CONFIG_GAZELL_LOG_LEVEL_CHOICE` Kconfig option.
```

2022-08-31 07:06 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * A section about Gazell in the :ref:`app_memory` page.
This entry might fit better under the Application development.

2022-08-31 07:39 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * A section about Gazell in the :ref:`app_memory` page.
Fine to leave it as it is, if you think it would be too high-profile under Application development.

2022-08-31 09:32 UTC, peknis approved these changes

2022-08-31 09:40 UTC, leewkb4567 commented
@peknis Does it take one more reviewer? Can you help assigning? Otherwise, I will make a 'merge request'.

2022-08-31 10:02 UTC, peknis commented
> @peknis Does it take one more reviewer? Can you help assigning? Otherwise, I will make a 'merge request'.

All PRs need a minimum of two reviewers and their approval. Suggesting to have someone from the SPG Protocols team as another reviewer.

2022-09-01 07:35 UTC, greg-fer commented
Please add milestone and get this merged during doc improvement by Sept 8.

2022-09-02 07:09 UTC, greg-fer approved these changes

2022-09-02 07:10 UTC, merged