bluetooth: adv_prov: Align to naming convention
nrfconnect/sdk-nrf pull request #8581
Opened 2022-08-31 11:53 UTC by alstrzebonski

Aligns advertising providers naming.

Jira: NCSDK-16508

2022-08-31 12:02 UTC, MarekPieta requested changes

2022-08-31 12:27 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8581
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-31 12:36 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26433/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-08-31 13:02 UTC, kapi-no approved these changes
Changes in the subsys/bluetooth, include/bluetooth and doc/libraries/bluetooth_services look good to me (They are aligned with the consensus in our discussion regarding the naming conventions)

2022-08-31 15:06 UTC, KAGA164 approved these changes

2022-09-01 06:20 UTC, divipillai commented on applications/machine_learning/README.rst
> -This CAF module relies on :ref:`bt_le_adv_prov_readme` to manage advertising data and scan response data.
Agree with @MarekPieta.

2022-09-01 07:52 UTC, divipillai approved these changes

2022-09-01 07:53 UTC, MarekPieta approved these changes

2022-09-01 07:54 UTC, MarekPieta commented
Hi @carlescufi
Is the current naming convention fine for you?

2022-09-01 09:54 UTC, merged