bluetooth: fast_pair: Improve procedure timeout handling
nrfconnect/sdk-nrf pull request #8591
Opened 2022-08-31 14:39 UTC by MarekPieta

Rescheduling work does not unsubmit work item that has been submitted to queue. Such work item could trigger spurious timeout right after the work was rescheduled.

Jira: NCSDK-16143

2022-08-31 15:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8591
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-08-31 15:35 UTC, rakons requested changes

2022-08-31 15:35 UTC, rakons commented on subsys/bluetooth/services/fast_pair/fp_keys.c
> +			(void)k_work_schedule(&proc->timeout, FP_KEY_TIMEOUT);
Please assert the return value.

2022-08-31 15:35 UTC, rakons commented on subsys/bluetooth/services/fast_pair/fp_keys.c
> +		(void)k_work_schedule(&proc->timeout, FP_KEY_TIMEOUT);
We are relaying on the fact that we are in cooperative thread and the work cannot be in RUN state, it means that cancel should always work - it is implementation detail, and such "*should*" needs assert test.

2022-09-01 07:52 UTC, rakons approved these changes

2022-09-01 10:57 UTC, alstrzebonski approved these changes

2022-09-01 10:59 UTC, merged