Fix bssid in scan
nrfconnect/sdk-nrf pull request #8618
Opened 2022-09-01 17:01 UTC by krish2718

2022-09-01 17:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8618
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-01 17:46 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26553/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-02 07:40 UTC, richabp approved these changes

2022-09-02 08:39 UTC, sachinthegreen requested changes

2022-09-02 08:39 UTC, sachinthegreen commented on samples/wifi/shell/README.rst
> +      1    | xyz                              4     | 1    | -27  | WPA2-PSK        | xx:xx:xx:xx:xx:xx
len should be 3

2022-09-02 08:39 UTC, sachinthegreen commented on subsys/net/l2/wifi/wifi_shell.c
> +	SHELL_CMD(scan, NULL, "Scan for Wi-Fi AP's", cmd_wifi_scan),
AP's should be APs

2022-09-02 08:56 UTC, sachinthegreen approved these changes

2022-09-02 10:27 UTC, merged