asset_tracker_v2: bump linked release version of nRF Asset Tracker
nrfconnect/sdk-nrf pull request #8637
Opened 2022-09-05 10:21 UTC by coderbyheart

nRF Asset Tracker has released support for nRF Connect SDK v2.1.x

See https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/issues/533

2022-09-05 10:53 UTC, coderbyheart commented
Double checked that new links work.

2022-09-05 11:04 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8637
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-05 11:20 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26611/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-06 08:14 UTC, rlubos approved these changes

2022-09-06 11:00 UTC, peknis requested changes

2022-09-06 11:00 UTC, peknis commented on doc/nrf/links.txt
> +.. _`nRF Asset Tracker web application`: https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/app/Index.html
And the same with these three. Not linked to from any NCS docs. Ok to remove.

2022-09-06 11:38 UTC, coderbyheart commented on doc/nrf/links.txt
> +.. _`nRF Asset Tracker web application`: https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/app/Index.html
```suggestion
```

2022-09-06 11:39 UTC, coderbyheart commented on doc/nrf/links.txt
> +.. _`Timestamping`: https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/guides/FourKindsOfData.html#time-stamping
```suggestion
```

2022-09-06 13:17 UTC, rlubos commented
@coderbyheart  Please squash the fixes.

2022-09-06 14:09 UTC, merged