applications: asset_tracker_v2: Add GNSS use-case and dynamics kconfig
nrfconnect/sdk-nrf pull request #8712
Opened 2022-09-12 08:59 UTC by maxd-nordic

This patch adds KConfig options to configure GNSS use-case and dynamics settings. Both can be used to tune GNSS to a specific use-case.

Implements CIA-732.

Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

2022-09-12 09:30 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8712
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-13 08:35 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26824/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-14 08:42 UTC, tejlmand requested changes

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/src/modules/Kconfig.gnss_module
> +	prompt "Tune GNSS performance for a specific use case"
is this really the most optimal title possible ?
Combined with the config choices below, this doesn't play well in `menuconfig`.

Could you try to shorten the text, while still keep the title informative enough.

Remember users can open help text if the need more detsiled information, so no need to write on details in the title field.
![image](https://user-images.githubusercontent.com/9802583/190104013-ec509b24-a807-499d-aed1-0823ae7680f5.png)

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/src/modules/Kconfig.gnss_module
> +	default n
Why the `default n` here ?

https://docs.zephyrproject.org/latest/build/kconfig/tips.html#redundant-defaults

```suggestion
```

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/src/modules/Kconfig.gnss_module
> +	default n
Why the `default n` here ?

https://docs.zephyrproject.org/latest/build/kconfig/tips.html#redundant-defaults

```suggestion
```

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/src/modules/Kconfig.gnss_module
> +	bool "Allow for low accuracy fixes using as few as three satellites."
this seems to be help text, please shorten the title and use this in the help text.

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/src/modules/Kconfig.gnss_module
> +	bool "Disable scheduled downloads of ephemerides and almanacs."
So if I enable this setting, then i'm actually disabling it ?

I suggest to revert this to instead enable something, and then have `default y`.

Also shorten the title, and move part of this to the help text.

2022-09-14 08:42 UTC, tejlmand commented on applications/asset_tracker_v2/tests/gnss_module/CMakeLists.txt
> +cmock_handle(${ZEPHYR_BASE}/../nrf/include/modem/lte_lc.h )
Use:
```suggestion
cmock_handle(${ZEPHYR_NRF_MODULE_DIR}/include/modem/lte_lc.h )
```

and please update the lines above and below to similar pattern when anyway touching this file.

Note: `${ZEPHYR_BASE}/../nrfxlib` --> `${ZEPHYR_NRFXLIB_MODULE_DIR}`

2022-10-05 07:57 UTC, simensrostad reviewed
Discussed offline that these changes will remain pending until the integration with the location API has completed. https://github.com/nrfconnect/sdk-nrf/pull/8631

2022-10-12 11:20 UTC, closed without merging