doc: known_issues: Add entry for i2c_nrfx_twim not building w/o PINCTRL
nrfconnect/sdk-nrf pull request #8752
Opened 2022-09-15 15:22 UTC by anangl

Ref. NCSIDB-840

Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>

2022-09-15 15:54 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/26922/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-15 16:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8752
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-16 10:06 UTC, greg-fer requested changes

2022-09-16 10:06 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  with :kconfig:option:`CONFIG_PINCTRL` set to ``n``.
```suggestion
  The I2C driver for TWIM peripherals (:file:`i2c_nrfx_twim.c`) cannot be compiled with :kconfig:option:`CONFIG_PINCTRL` set to ``n``.
```

2022-09-16 10:09 UTC, anangl commented on doc/nrf/known_issues.rst
> +  with :kconfig:option:`CONFIG_PINCTRL` set to ``n``.
Applied.

2022-09-16 11:13 UTC, greg-fer approved these changes

2022-09-19 09:09 UTC, carlescufi approved these changes

2022-09-19 09:09 UTC, merged