doc: gs: align installation steps with VSC ext
nrfconnect/sdk-nrf pull request #8771
Opened 2022-09-16 14:24 UTC by greg-fer

Edited installing automatically page to align it with the VSC extension. VSC-1254.

Signed-off-by: Grzegorz Ferenc <Grzegorz.Ferenc@nordicsemi.no>

2022-09-16 15:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8771
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-19 07:14 UTC, Avalei requested changes

2022-09-19 08:19 UTC, kittydepa reviewed
LGTM, and I agree with Deidre's comments. Will approve once those are addressed.

2022-09-23 10:34 UTC, greg-fer commented on doc/nrf/gs_assistant.rst
> +Additionally, if you are using a M1-based Mac machine, install the Universal version of SEGGER J-Link.
Add "This is required for SEGGER J-Link to work correctly on Mac machines". TBC with Simen Tinderholt.

2022-09-27 07:55 UTC, greg-fer commented on doc/nrf/gs_assistant.rst
> +Installing |nRFVSC|
To me yes, hence I kept the gerund form.

2022-09-27 08:04 UTC, greg-fer commented on doc/nrf/gs_assistant.rst
> +Additionally, if you are using a M1-based Mac machine, install the Universal version of SEGGER J-Link.
Updated as discussed with Simen: no need to restrict this prerequisite to only Mac machines.

2022-09-27 08:04 UTC, greg-fer commented
@kittydepa , @Avalei , please check again.

2022-09-27 09:08 UTC, kittydepa approved these changes

2022-09-28 11:19 UTC, Avalei approved these changes

2022-09-29 13:02 UTC, peknis requested changes

2022-09-29 13:02 UTC, peknis commented on doc/nrf/gs_assistant.rst
> +   The |NCS| version of your choice is installed on your machine.
```suggestion
#. In :guilabel:`SDK ENVIRONMENTS`, click the :guilabel:`Install` button next to the |NCS| version that you want to install.

   The |NCS| version of your choice is installed on your machine.
```
Just to separate the consequence from the actual task and keep the steps crisp.

2022-09-29 13:02 UTC, peknis commented on doc/nrf/gs_assistant.rst
> +   A notification appears with a list of missing extensions that you need to install, including those from the `nRF Connect for Visual Studio Code`_ extension pack.
```suggestion
#. In Toolchain Manager, click the :guilabel:`Open VS Code` button.

   A notification appears with a list of missing extensions that you need to install, including those from the `nRF Connect for Visual Studio Code`_ extension pack.
```

2022-09-29 13:02 UTC, peknis commented on doc/nrf/gs_assistant.rst
> +To build on the command line, use the following steps:
```suggestion
To build on the command line, complete the following steps:
```

2022-09-29 13:28 UTC, umapraseeda commented on doc/nrf/gs_assistant.rst
> +#. Click :guilabel:`SETTINGS` in the navigation bar to specify where you want to install the |NCS|.
There is some issue with the numbering.

2022-09-29 13:28 UTC, umapraseeda commented on doc/nrf/gs_assistant.rst
> +1. Open Toolchain Manager in nRF Connect for Desktop.
Should we update the following image to Toolchain Manager v0.10.3 to match with the second screenshot?

2022-09-29 13:28 UTC, umapraseeda commented on doc/nrf/gs_programming.rst
>  1.    Open a terminal window.
Line 40: Shouldn't we update the link :ref:`automatic <gs_app_installing-ncs-tcm>` to point to https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8771/nrf/gs_assistant.html#installing-command-line-requirements?

2022-09-29 13:37 UTC, greg-fer commented on doc/nrf/gs_assistant.rst
> +#. Click :guilabel:`SETTINGS` in the navigation bar to specify where you want to install the |NCS|.
Done, alignment was missing.

2022-09-30 05:22 UTC, peknis approved these changes

2022-09-30 06:55 UTC, umapraseeda approved these changes

2022-09-30 06:55 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
>  * Updated :ref:`ug_matter_gs_adding_cluster` documentation with new code snippets to align it with the source code of refactored Matter template sample.
```suggestion
* Updated:

  * Steps in :ref:`gs_assistant` page to reflect the fact that the |nRFVSC| is the default recommended IDE.
  * ref:`ug_matter_gs_adding_cluster` documentation with new code snippets to align it with the source code of refactored Matter template sample.
```

2022-09-30 08:32 UTC, merged