applications: asset_tracker_v2: Assert if event pointer is NULL
nrfconnect/sdk-nrf pull request #8805
Opened 2022-09-22 13:35 UTC by simensrostad

Assert if event pointer is NULL

2022-09-22 19:45 UTC, balaji-nordic approved these changes

2022-09-23 09:10 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27095/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-23 14:21 UTC, dilner approved these changes

2022-09-23 14:23 UTC, carlescufi requested changes

2022-09-23 15:20 UTC, simensrostad commented on applications/asset_tracker_v2/src/main.c
> +	if (app_module_event == NULL) {
Yes, of course. Changed.

2022-09-26 06:03 UTC, jorgenmk approved these changes

2022-09-26 13:14 UTC, balaji-nordic approved these changes

2022-09-27 14:43 UTC, merged