bluetooth: mesh: Fix in Time srv API
nrfconnect/sdk-nrf pull request #8832
Opened 2022-09-26 11:40 UTC by akredalen

Allow only servers with Time Role State 0x01 (Time Authority) or 0x02 (Time Relay) to send unsolicited Time Status messages (Mesh Model Specification 5.3.1.2.2).

Signed-off-by: Stine Akredalen <stine.akredalen@nordicsemi.no>

2022-09-26 11:40 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2022-09-26 12:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=8832) it.</sub>

2022-09-29 07:34 UTC, alxelax requested changes

2022-09-29 07:34 UTC, alxelax commented on include/bluetooth/mesh/time_srv.h
> +	/** @brief Publish an unsolicited Time Status message.
```suggestion
/** @brief Publish an unsolicited Time Status message.
```

2022-09-29 07:34 UTC, alxelax commented on include/bluetooth/mesh/time_srv.h
> + * 						  sending of unsolicited Time Status messages.
wrong text alignment

2022-09-29 08:37 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8832
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-03 16:43 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27349/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-04 06:50 UTC, alxelax commented
Seems the minor alignment issues have been fixed. However, there is still a compliance issue. Please fix it as well as the license agreement signing. It is not possible to merge PR without passing all CI stages.

2022-10-04 10:10 UTC, alxelax approved these changes

2022-10-11 07:43 UTC, ludvigsj approved these changes

2022-10-11 07:47 UTC, merged