build: fix minor naming issue in cmake file
nrfconnect/sdk-nrf pull request #8838
Opened 2022-09-27 06:23 UTC by mguc

Fixes the following error when building the `nrf_profiler`:

```
CMake Error at /opt/ncs/zephyr/cmake/modules/extensions.cmake:418 (add_library):
  Cannot find source file:
    /opt/ncs/nrf/subsys/nrf_profiler/nrf_profiler_common_shell.c
Call Stack (most recent call first):
  /opt/ncs/zephyr/CMakeLists.txt:105 (zephyr_library_named)
```

2022-09-27 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8838) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8838) before we can accept your contribution.<br/><hr/>**Marko Gucanin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=8838) it.</sub>

2022-09-27 06:23 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2022-09-27 07:25 UTC, pdunaj requested changes

2022-09-27 07:25 UTC, pdunaj commented on subsys/nrf_profiler/CMakeLists.txt
> +zephyr_sources_ifdef(CONFIG_SHELL profiler_common_shell.c)
The source file should be renamed instead.

2022-09-27 07:27 UTC, pdunaj commented
Hi @mguc , thank you for your contribution. It seems one file was not committed correctly when profiler rename was done. Can you change the fix to adjust the file name instead?

2022-09-27 07:58 UTC, pdunaj requested changes
Change is ok but the commits cleanup is neeed.
Please squash two commits into one (`git rebase -i HEAD~2` and mark the second to be squashed). Also re-write first commit's message to match with previous ones. That can be something like:
```
    profiler: Fix source file name.

    Fix profiler source file name according to the recent
    rename.
    
    Signed-off-by: Your Name <your@address.xy>
```

When you commit you can add `-s` (`git commit -s`) for sign-off line to be added for you
according to name/email variables set in git.

2022-09-27 07:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8838
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-29 10:10 UTC, MarekPieta reviewed
Please use `nrf_profiler` instead of `profiler` as commit message prefix. The subsystem is currently called `nrf_profiler`

2022-11-24 08:37 UTC, pdunaj approved these changes

2022-11-24 19:43 UTC, MarekPieta approved these changes

2022-11-26 13:08 UTC, pdunaj commented
Hi @MarekPieta , it would be good to have it in the coming release, could you rebase? Unless @mguc will do it :)

2022-11-28 08:07 UTC, MarekPieta commented
Hi @pdunaj
The issue is fixed in https://github.com/nrfconnect/sdk-nrf/pull/9473. (it could go together with profiler shell fix)

2022-11-28 16:13 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8838/5/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8838/5/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-28 16:20 UTC, nordicjm commented
Closing as fixed in #9473

2022-11-28 16:20 UTC, closed without merging