[DNM] scripts: add simple Zephyr upmerge
nrfconnect/sdk-nrf pull request #8852
Opened 2022-09-28 08:39 UTC by karhama

Minimal script for upmerging Zephyr project.

Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>

2022-09-28 09:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8852
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-07 22:13 UTC, mbolivar-nordic requested changes
Putting a -1 on for now. I have some basic questions:

- what portions of our upmerge process does this intend to automate, and what portions are out of scope and will be left manual?
- I am assuming you have given some thought about how not to break the oss-history automatic rebase steps, right?
- who will maintain this?
- what are the proposed processes for making sure this does not drift from our internal documentation?

Feel free to point me at an internal bug tracker reference if you prefer to answer there.

2022-10-11 11:31 UTC, karhama commented
> Putting a -1 on for now. I have some basic questions:
> 
> * what portions of our upmerge process does this intend to automate, and what portions are out of scope and will be left manual?
> * I am assuming you have given some thought about how not to break the oss-history automatic rebase steps, right?
> * who will maintain this?
> * what are the proposed processes for making sure this does not drift from our internal documentation?
> 
> Feel free to point me at an internal bug tracker reference if you prefer to answer there.

Target is to have MVP for automatic upmerge process. This script is quite close to ncs-compare but instead of only printing the information this script will do reverting (fromlist / fromtree commits) and then merge upstream. This script will pass only if there are no conflicts (in reverting or in merging).

Idea is to trigger this tool using e.g. github actions and if it passes execute some CI tests and even automatically upmerge. This way we will at least receive frequent feedback of issues vs. current manual upmerge process.

This is WIP mainly because I'm not sure how to test other than Zephyr project (I have only run "west ncs-upmerger zephyr"). I'm not even sure if there are any other project which it can be tested at this point.

2022-10-11 13:31 UTC, mbolivar-nordic commented
> This is WIP mainly because I'm not sure how to test other than Zephyr project (I have only run "west ncs-upmerger zephyr"). I'm not even sure if there are any other project which it can be tested at this point.

Give it a shot with mcuboot first before moving on to other projects, I would guess would be easiest.

2022-10-24 10:33 UTC, carlescufi commented
@mbolivar-nordic can you please re-review?
@de-nordic can you take a look?

2022-10-24 18:31 UTC, mbolivar-nordic approved these changes
Seems harmless; let's try it

2022-11-09 12:26 UTC, de-nordic approved these changes
Looks OK to me.

2022-11-09 13:48 UTC, thst-nordic approved these changes

2022-11-09 14:02 UTC, karhama commented on scripts/west_commands/ncs_commands.py
> +class NcsUpmerger(NcsWestCommand):
done

2022-11-09 14:42 UTC, merged