cmake: child image: support passing of quoted settings to child images
nrfconnect/sdk-nrf pull request #8864
Opened 2022-09-29 08:57 UTC by tejlmand

JIRA: NCSIDB-806

CMake string variables which are defined with escaped quotes, such as
-D<image>_FOO=\"BAR\" loose their quotes when written to the pre-load
file. More precisely, <image>_FOO becomes `set(FOO ""BAR"" ...)`.

This commit correct this by properly escaping quotes in CMake string
variables before writing them to the pre-load file, so that
<image>_FOO becomes `set(FOO "\"BAR\"" ...)`.

The manifest is updated to get corresponding fix for quoted Kconfig
settings that are passed on command line to be treated properly.

2022-09-29 08:57 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/97c4a1a6d1bda83f0272d9bbf68b211efadc7b4a (main) | https://github.com/nrfconnect/sdk-zephyr/pull/917 | [nrfconnect/sdk-zephyr#917/files](https://github.com/nrfconnect/sdk-zephyr/pull/917/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-09-29 09:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8864
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-29 09:36 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27236/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-29 15:16 UTC, carlescufi approved these changes

2022-09-30 06:45 UTC, ChrisKurz approved these changes
I have tested the changes. I have replaced the files ../nrf/cmake/multi-image.cmake and ../zephyr/cmake/modules/extensions.cmake in NCS v2.1.0 with the updated files, because customer has to use NCS v2.1.0. With these updated files the build process does not show the privous error...

2022-10-05 10:49 UTC, Damian-Nordic commented
@tejlmand Does this also fix https://projecttools.nordicsemi.no/jira/browse/NCSDK-14549?

2022-10-20 20:37 UTC, nickrbogdanov commented
Unfortunately this did not work for me.  I'm still getting `malformed string literal` errors even after applying this patch to NCS v2.1.0.

This fix _did_ work: https://github.com/nrfconnect/sdk-nrf/pull/7997

My invocation looks like this:

```
west build --pristine --build-dir=build --board nrf52840dk_nrf52840 -- \
	-DOVERLAY_CONFIG=overlay.conf \
	-DPM_STATIC_YML_FILE=pm_ota.yml \
	-D"mcuboot_CONFIG_DISABLE_FLASH_PATCH=y" \
	-D"mcuboot_CONFIG_BOOT_SIGNATURE_KEY_FILE=\"/home/me/key.pem\"" \
	-D"CONFIG_MCUBOOT_IMAGE_VERSION=\"1.2.3\"" \
	-D"CONFIG_BUILD_EXT=\"-debug\""
```

Can we merge #7997 into the next NCS release?

2022-10-27 10:03 UTC, tejlmand commented
> Unfortunately this did not work for me. I'm still getting `malformed string literal` errors even after applying this patch to NCS v2.1.0.

thanks for reporting this, actually a combination of #7997 and #8864 is needed.

The issue experienced by you happens when making variant builds, so the extra line missing has been applied now.

2022-11-24 10:39 UTC, nordicjm approved these changes

2022-11-24 10:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8864/8/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8864/8/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-8864/8/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-24 11:00 UTC, FrancescoSer requested changes

2022-11-24 11:02 UTC, tejlmand commented on doc/nrf/releases/release-notes-changelog.rst
> +* Fixed issue with passing of quoted settings to child images.
applied

2022-11-24 11:08 UTC, FrancescoSer approved these changes

2022-11-25 12:57 UTC, merged