samples: wifi: Scan sample documentation
nrfconnect/sdk-nrf pull request #8878
Opened 2022-09-30 10:13 UTC by D-Triveni

Documentation for Wi-Fi scan sample

Signed-off-by: Triveni D <triveni.danda@nordicsemi.no>

2022-09-30 10:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8878
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-09-30 10:54 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27283/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-09-30 13:10 UTC, richabp requested changes
I am unable to add my comments after line 10, not sure why. 
Don't we have any Dependencies for this sample, if yes, then please add them.

2022-09-30 14:24 UTC, D-Triveni commented
> I am unable to add my comments after line 10, not sure why. Don't we have any Dependencies for this sample, if yes, then please add them.

@richabp Sample has no dependencies.

2022-10-03 08:27 UTC, richabp requested changes
Not able to provide my suggestions inline so I am giving it here:

Line 2: This sample can perform Wi-Fi "Scan" operation over both 2.4GHz and 5GHz
Change to : This sample can perform Wi-Fi scan operation in the 2.4GHz and 5GHz bands.

Line 24: Using this sample, the development kit can scan for available Access Points in :abbr:`STA (Station)` mode.
Change to: Using this sample, the development kit can scan for available access points in :abbr:`STA (Station)` mode.

Line 34 and 45: Use code block:: console to write the code.

Line 44: Leave a blank line after line 44.

Line 45: The output should be similar to the following
Change to: The sample shows the following output:

Line 45: Do we have any command which shows the following output, if yes, add it.

Line 47 and 52: Remove  "inf scan:"

2022-10-04 06:17 UTC, D-Triveni commented
@richabp Resolved.
> Line 34 and 45: Use code block:: console to write the code.
> 
With present change, we can see code block.

2022-10-04 07:44 UTC, richabp requested changes

2022-10-04 07:44 UTC, richabp commented on samples/wifi/scan/README.rst
> +The Scan sample demonstrates how to use the Nordic Semiconductor's Wi-Fi chipset to scan for the Access points without using the wpa_supplicant.
```suggestion
The Scan sample demonstrates how to use the Nordic Semiconductor's Wi-Fi chipset to scan for the access points without using the wpa_supplicant.
```

2022-10-04 07:44 UTC, richabp commented on samples/wifi/scan/README.rst
> +This sample can perform Wi-Fi scan operation in both 2.4GHz and 5GHz bands.
```suggestion
This sample can perform Wi-Fi scan operation in the 2.4GHz and 5GHz bands.
```

2022-10-04 07:44 UTC, richabp commented on samples/wifi/scan/README.rst
>  The following is an example of the CLI command::
```suggestion
The following is an example of the CLI command:

.. code-block:: console
```

2022-10-04 07:44 UTC, richabp commented on samples/wifi/scan/README.rst
> +    The sample shows the following output::
```suggestion
    The sample shows the following output:
    
    .. code-block:: console
```

2022-10-04 18:18 UTC, bama-nordic approved these changes
LGTM

2022-10-06 18:24 UTC, richabp approved these changes

2022-10-07 06:58 UTC, merged