samples: nrf9160: lwm2m_client: Level resource 5548 is double type in…
nrfconnect/sdk-nrf pull request #8895
Opened 2022-10-03 15:04 UTC by charlieshao5189

…stead of integer

Signed-off-by: Charlie Shao <charlie.shao@nordicsemi.no>

2022-10-03 15:36 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8895
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-03 15:54 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27347/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-04 07:52 UTC, rlubos approved these changes

2022-10-04 09:13 UTC, VeijoPesonen requested changes

2022-10-04 09:13 UTC, VeijoPesonen commented on samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_buzzer.c
> +	uint8_t intensity = *(double *)data;
Please fix the log message on the line 57 too.

2022-10-04 09:22 UTC, VeijoPesonen approved these changes

2022-10-04 10:16 UTC, merged