samples: bluetooth: peripheral_mds: Add new testing scenario
nrfconnect/sdk-nrf pull request #8935
Opened 2022-10-06 13:18 UTC by KAGA164

This commit adds documentation section about testing the Peripheral MDS sample with the nRF Memfault
mobile applications for iOS and Android.

2022-10-06 13:51 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8935
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-06 14:07 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27463/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-10 06:41 UTC, peknis requested changes

2022-10-10 06:41 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Add documentation section about testing with the `nRF Memfault for Android`_ and the `nRF Memfault for iOS`_ mobile applications.
```suggestion
    * Added a section about testing with the `nRF Memfault for Android`_ and the `nRF Memfault for iOS`_ mobile applications to the documentation.
```

2022-10-10 06:41 UTC, peknis commented on samples/bluetooth/peripheral_mds/README.rst
> +#. On your mobile phone with an access to the Internet, open the nRF Memfault application.
```suggestion
#. On your mobile phone with access to the Internet, open the nRF Memfault application.
```

2022-10-10 06:41 UTC, peknis commented on samples/bluetooth/peripheral_mds/README.rst
> +#. In your mobile application, click the :guilabel:`Start` button.
```suggestion
#. In the mobile application, tap :guilabel:`Start`.
```

2022-10-10 06:41 UTC, peknis commented on samples/bluetooth/peripheral_mds/README.rst
> +   See :ref:`peripheral_mds_user_interface` for details about button functions.
```suggestion
#. Use the buttons to trigger Memfault crashes, traces and metrics collection.

   See :ref:`peripheral_mds_user_interface` for details about button functions.
```

2022-10-10 06:41 UTC, peknis commented on samples/bluetooth/peripheral_mds/README.rst
> +#. As bond information is preserved, you can immediately reconnect to the device by clicking the :guilabel:`Connect` button again.
```suggestion
#. When you have finished collecting diagnostic data, tap :guilabel:`Disconnect` to the close connection with your development kit.

   As the bond information is preserved, you can tap :guilabel:`Connect` again to immediately reconnect to the device.
```

2022-10-24 06:46 UTC, kapi-no approved these changes

2022-10-24 10:24 UTC, peknis approved these changes

2022-10-27 12:31 UTC, merged