cmake: pass WEST_PYTHON to child image builds
nrfconnect/sdk-nrf pull request #8949
Opened 2022-10-07 16:41 UTC by taralx

Without this, child images keep picking up my system python and then complaining about `yaml` module not being present.

2022-10-07 16:41 UTC, NordicBuilder commented
Thank you for your contribution!
It seems you are not a member of the nrfconnect GitHub organization. External contributions are handled as follows:
Large contributions, affecting multiple subsystems for example, may be rejected if they are complex, may introduce regressions due to lack of test coverage, or if they are not consistent with the architecture of nRF Connect SDK.
PRs will be run in our continuous integration (CI) test system.
If CI passes, PRs will be tagged for review and merged on successful completion of review. You may be asked to make some modifications to your contribution during review.
If CI fails, PRs may be rejected or may be tagged for review and rework.
PRs that become outdated due to other changes in the repository may be rejected or rework requested.
External contributions will be prioritized for review based on the relevance to current development efforts in nRF Connect SDK.  Bug fix PRs will be prioritized.
You may raise issues or ask for help from our Technical Support team by visiting https://devzone.nordicsemi.com/.

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*

2022-10-07 16:42 UTC, taralx commented
Marking draft pending license approval.

2022-10-07 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8949) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=8949) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=8949) it.</sub>

2022-10-14 09:51 UTC, tejlmand commented
@taralx thanks a lot for your contribution.

I assume you're not using the [Toolchain Manager](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_assistant.html#install-toolchain-manager) but instead [Installing manually](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_installing.html).
Not using toolchain manager is a perfectly valid setup, but to support both manual setup and Toolchain Manager some small modifications must be made to your patch.

Also notice, `west` is not required, so building using only CMake and ninja is also supported (in which case `WEST_PYTHON` is undefined.)

2022-10-17 19:07 UTC, taralx commented
Hi - legal says they do not have the CLA on file. Do you have a signed CLA from Amazon?

2022-10-24 18:13 UTC, taralx commented
@tejlmand any suggestions?

2022-11-22 11:41 UTC, carlescufi commented
@taralx could you please sign the CLA? It's right here for you to sign:

![image](https://user-images.githubusercontent.com/12450381/203305478-54d0b4ae-9692-40a0-bab1-9bd409f2e604.png)

2022-11-22 17:04 UTC, taralx commented
@carlescufi I cannot, as it has to be signed by my employer, not me. FYI you have a corporate CLA?

2022-11-23 14:06 UTC, carlescufi commented
> @carlescufi I cannot, as it has to be signed by my employer, not me. Do you have a corporate CLA?

I don't think so, no. We only have this one. Can't you sign this yourself? I think it's designed to be done on behalf of the company you work for.

2022-11-23 18:34 UTC, taralx commented
Am working with sales/legal to get a corporate CLA in place. Will update here when that's done.

2022-11-24 08:52 UTC, carlescufi commented
> Am working with sales/legal to get a corporate CLA in place. Will update here when that's done.

OK, thanks @taralx.

2022-11-28 21:09 UTC, taralx commented
Ok, CLA signed.

2022-12-01 00:47 UTC, taralx commented
Putting this back to draft. I don't understand why it was failing for me before, but other child images seem to work. Will investigate more later.

2022-12-09 01:43 UTC, taralx commented
Okay, so I finally puzzled this out. If your PATH contains a binary called "python", west will pick it up in preference to a binary called "python3". This is a problem on many systems. I think this is the correct fix.

2023-01-15 00:06 UTC, taralx commented
@carlescufi @nordicjm Anything more needed?

2023-02-01 09:23 UTC, nordicjm commented
@taralx this needs to be signed off e.g. `git commit --amend -s`, please do that and force push and I will re-request @tejlmand to look at it

2023-02-02 00:31 UTC, taralx commented
Done, thanks!

2023-02-24 09:05 UTC, taralx commented
@nordicjm @tejlmand ping 🙂

2023-03-03 02:39 UTC, taralx commented
@carlescufi can help?

2023-03-21 13:19 UTC, nordicjm requested changes
@taralx this needs a commit message as well as a title, e.g.
```
cmake: pass WEST_PYTHON to child image builds

Fixes an issue whereby the west python variable was not passed
to child images and caused build failures.
```

2023-03-21 19:24 UTC, taralx commented
Done, thanks.

2023-03-22 08:02 UTC, nordicjm approved these changes

2023-03-22 09:07 UTC, tejlmand approved these changes

2023-03-22 09:09 UTC, merged

2023-04-05 20:44 UTC, sarah-read commented
@tejlmand I'm seeing a warning since this was merged due to the backslash separated path provided by WEST_PYTHON. Following is on Windows using Toolchain Manager:

```
Loading Zephyr default modules (Zephyr base).
-- Application: C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr
-- Found Python3: C:/ncs/toolchains/v2.3.0/opt/bin/python.exe (found suitable exact version "3.8.2") found components: Interpreter 
-- Cache files will be written to: C:/ncs/main/zephyr/.cache
-- Zephyr version: 3.2.99 (C:/ncs/main/zephyr)
-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")
-- Board: nrf5340dk_nrf5340_cpuapp
-- Found host-tools: zephyr 0.15.2 (C:/ncs/toolchains/v2.3.0/opt/zephyr-sdk)
-- Found toolchain: zephyr 0.15.2 (C:/ncs/toolchains/v2.3.0/opt/zephyr-sdk)
-- Found Dtc: C:/ncs/toolchains/v2.3.0/opt/bin/dtc.exe (found suitable version "1.4.7", minimum required is "1.4.6") 
-- Found BOARD.dts: C:/ncs/main/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp.dts
-- Generated zephyr.dts: C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/zephyr/dts.cmake
Parsing C:/ncs/main/zephyr/Kconfig
Loaded configuration 'C:/ncs/main/zephyr/boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_defconfig'
Merged configuration 'C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/prj.conf'
Configuration saved to 'C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/zephyr/.config'
Kconfig header saved to 'C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/zephyr/include/generated/autoconf.h'
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/ncs/toolchains/v2.3.0/opt/zephyr-sdk/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe

=== child image hci_rpmsg - CPUNET begin ===
loading initial cache file C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/hci_rpmsg/child_image_preload.cmake
CMake Warning (dev) at C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/hci_rpmsg/child_image_preload.cmake:9 (set):
  Syntax error in cmake code at

    C:/ncs/main/nrf/samples/bluetooth/central_and_peripheral_hr/build/hci_rpmsg/child_image_preload.cmake:9

  when parsing string

    c:\ncs\toolchains\v2.3.0\opt\bin\python.exe

  Invalid escape sequence \v

  Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
  "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Loading Zephyr default modules (Zephyr base).
```
Strangely, I found I could use PYTHON_EXECUTABLE instead of WEST_PYTHON in multi_image.cmake and that path was acceptable (forward slashes)..

2023-05-05 07:03 UTC, jori-nordic commented
@tejlmand any ideas why this is happening?

2023-05-05 07:24 UTC, nordicjm commented
@sarah-read @jori-nordic I don't have a windows setup to test but can you apply use this for sdk-zephyr and let me know if it fixes the problem? https://github.com/nrfconnect/sdk-zephyr/pull/1152