doc: doc updates for 2.1.99-dev2
nrfconnect/sdk-nrf pull request #8965
Opened 2022-10-11 06:58 UTC by peknis

Update versions, changelog and notes for the dev tag.

Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>

2022-10-11 09:00 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-8965
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-12 08:16 UTC, gmarull approved these changes

2022-10-12 08:18 UTC, bama-nordic approved these changes
LGTM

2022-10-12 08:57 UTC, ioannisg requested changes
I see some inconsistencies between the changelog and the highlights. 
To my understanding there is no standalone FICR sample, rather an extension of the radio sample that adds some functionality. And since the Radio Test sample was not part of v2.1.0, it needs to be mentioned.

2022-10-12 08:57 UTC, ioannisg commented on doc/nrf/index.rst
> +   * New :ref:`wifi_ficr_prog` sample, adding support for FICR/OTP programming.
I think here we need to list the radio test sample. This was not part of any previous release. the "FICR" Sample is only a part of this sample that support commands for FICR, OTP programming.

2022-10-12 08:57 UTC, ioannisg commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Subcommands for FICR/OTP programming.
This reflects better what was added in this tag

2022-10-12 10:13 UTC, b-gent requested changes

2022-10-12 10:13 UTC, b-gent commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Subcommands for FICR/OTP programming.
Incorrect indentation
![image](https://user-images.githubusercontent.com/29537761/195316271-50fc62c3-9b5f-467a-80bd-1d45ba593dc1.png)

2022-10-12 10:14 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
Line 116: Missing colon
Line 118: CONFIG_SLM_DATAMODE_URC -> :ref:\`CONFIG_SLM_DATAMODE_URC <CONFIG_SLM_DATAMODE_URC>\`

2022-10-12 10:30 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
Fixed.

2022-10-12 10:48 UTC, bama-nordic commented
> thanks! @bama-nordic please do a final check on the last version

Looks good to me.

2022-10-12 11:20 UTC, umapraseeda approved these changes

2022-10-12 13:51 UTC, ioannisg commented
@b-gent pls, revisit this one :)

2022-10-12 14:17 UTC, b-gent approved these changes

2022-10-13 07:58 UTC, merged