doc: FOTA over BLE doc update
nrfconnect/sdk-nrf pull request #8966
Opened 2022-10-11 09:38 UTC by annakielar

FOTA over BLE chapter (ug_nrf52.rst) reordered and rephrased. Small edits in shorcuts.txt and ug_nrf91_features. 1 substitution removed.

Signed-off-by: Anna Kielar <anna.kielar@nordicsemi.no>

2022-10-11 09:50 UTC, annwoj commented on doc/nrf/ug_nrf52.rst
> +   #. Download the new image to a device.
```suggestion
   #. Download the new image to your device.
```

2022-10-11 09:59 UTC, annwoj commented on doc/nrf/ug_nrf52.rst
>  FOTA over Bluetooth LE
Bluetooth LE or Bluetooth Low Energy - to be unified in this section

2022-10-11 11:07 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |

Test spec set is empty, this is probabley due to no matching entry in [.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27591/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-11 12:43 UTC, FrancescoSer requested changes
Just a few tips

2022-10-11 12:43 UTC, FrancescoSer commented on doc/nrf/ug_nrf52.rst
> +   * Use :doc:`mcuboot:index-ncs` as the upgradable bootloader (:kconfig:option:`CONFIG_BOOTLOADER_MCUBOOT` must be enabled).
Consider that :doc:`mcuboot:index-ncs`  is named "Introduction to MCUboot", so the sentence structure should accomodate the link accordingly

2022-10-11 12:43 UTC, FrancescoSer commented on doc/nrf/ug_nrf52.rst
>  ======================
```suggestion
FOTA over Bluetooth Low Energy
==============================
```

2022-10-11 12:43 UTC, FrancescoSer commented on doc/nrf/ug_nrf52.rst
> +   * Enable the mcumgr module that handles the transport protocol over Bluetooth Low Energy:
```suggestion
   * Enable the mcumgr module that handles the transport protocol over Bluetooth Low Energy as follows:
```
Just to clarify the sense of the following lines

2022-10-11 12:43 UTC, FrancescoSer commented on doc/nrf/ug_nrf52.rst
> +   After completing these steps, your application should advertise the SMP Service with UUID 8D53DC1D-1DB7-4CD3-868B-8A527460AA84.
```suggestion
   After completing these steps, your application should advertise the SMP Service with UUID ``8D53DC1D-1DB7-4CD3-868B-8A527460AA84``.
```

2022-10-11 12:43 UTC, FrancescoSer commented on doc/nrf/shortcuts.txt
>  .. |fota_upgrades_building| replace:: To create a binary file for an application upgrade, make sure that :kconfig:option:`CONFIG_BOOTLOADER_MCUBOOT` is enabled and build the application as usual.
```suggestion
.. |fota_upgrades_building| replace:: To create a binary file for an application upgrade, build the application with the :kconfig:option:`CONFIG_BOOTLOADER_MCUBOOT` option enabled.
```

2022-10-12 07:21 UTC, sigvartmh approved these changes

2022-10-12 07:23 UTC, sigvartmh approved these changes
The instructions are correct in how to enable things I guess there is still some things to touch up on but from a technical stand point this is okei.

2022-10-12 12:06 UTC, annwoj approved these changes

2022-10-13 12:22 UTC, FrancescoSer approved these changes

2022-10-13 13:21 UTC, merged