drivers: wifi: Read request IEs in assoc response event
nrfconnect/sdk-nrf pull request #9000
Opened 2022-10-14 09:30 UTC by rado17

Reading request IEs in the assoc response event to identify the link mode.

Signed-off-by: Ravi Dondaputi <ravi.dondaputi@nordicsemi.no>

2022-10-14 09:31 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/4ee2a9c76e28dfd590f289960b44e7b100cb4e04 | https://github.com/nrfconnect/sdk-hostap/pull/35 | [nrfconnect/sdk-hostap#35/files](https://github.com/nrfconnect/sdk-hostap/pull/35/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-10-14 10:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9000
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-14 10:55 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27712/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-27 12:46 UTC, krish2718 requested changes
We also need the same patch ported to RevB as well.

2022-11-10 12:35 UTC, sachinthegreen approved these changes

2022-11-22 12:05 UTC, sr1dh48r approved these changes

2022-11-29 16:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9000/4/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9000/4/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9000/4/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-06 11:33 UTC, krish2718 approved these changes

2022-12-08 12:13 UTC, merged