wifi: MBO Pre-certification bugfixes
nrfconnect/sdk-nrf pull request #9029
Opened 2022-10-18 10:49 UTC by sr1dh48r

Support for handling MLME frames.
Enable RRM support in capabilities.
Support for wnm_bss_query wpa_cli cmd.

Signed-off-by: Sridhar Nuvusetty <sridhar.nuvusetty@nordicsemi.no>

2022-10-18 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=9029) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=9029) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=9029) it.</sub>

2022-10-18 10:49 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/306b36c1f02579c1988c3dbab64baac4ec7b9224 (main) | pull/36/HEAD | [nrfconnect/sdk-hostap@306b36c1..pull/36/HEAD](https://github.com/nrfconnect/sdk-hostap/compare/306b36c1f02579c1988c3dbab64baac4ec7b9224..pull/36/HEAD) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-10-18 13:04 UTC, sachinthegreen requested changes

2022-10-18 13:04 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	mgmt_tx_info->freq_params.channel_type = NRF_WIFI_CHAN_WIDTH_20;
Is NRF_WIFI_CHAN_WIDTH_20 the correct macro to be used here (i.e. should there be a different macro for channel type)?

2022-10-18 13:04 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +
Good to have a defensive check here to see that if_priv and mlme_event are not NULL.

2022-10-19 10:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9029
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-19 10:52 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27799/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-21 06:09 UTC, sr1dh48r commented
@krish2718 @sachinthegreen reminder on this !! Ajay is waiting on this PR to make further changes ..

2022-10-21 06:13 UTC, krish2718 approved these changes
LGTM, but you need to rebase for CI to pass.

2022-10-21 06:35 UTC, sachinthegreen approved these changes

2022-10-31 11:28 UTC, merged