Manifest adv delay
nrfconnect/sdk-nrf pull request #9079
Opened 2022-10-24 10:29 UTC by ibaz-nordic

2022-10-24 10:30 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/90bad439cd19ad912877cc0d4d04e5294356e2b6 | https://github.com/nrfconnect/sdk-nrfxlib/pull/851 | [nrfconnect/sdk-nrfxlib#851/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/851/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-10-24 11:17 UTC, rugeGerritsen requested changes

2022-10-24 11:17 UTC, rugeGerritsen commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Support for changing advertising randomness using :c:func:`sdc_hci_cmd_vs_set_adv_randomness function.
Discussed offline. The update the release notes should be removed

2022-10-24 11:28 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/27918/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-10-24 12:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9079
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-27 09:39 UTC, PerMac commented
87/112 nrf5340dk_nrf5340_cpuapp  zigbee/light_switch/sample.zigbee.light_switch.fota_and_multiprotocol FAILED Build failure (build) is failing due to `/tools/ncs/toolchains/v2.1.0/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section 'noinit' will not fit in region 'SRAM'`
 @tomchy @sebastiandraus I guess you might want to take a look at this. Do you think the sample can be optimized to adopt to the changes introduced with updating of SDC and MPSL?

2022-10-27 13:26 UTC, ibaz-nordic commented
> 87/112 nrf5340dk_nrf5340_cpuapp zigbee/light_switch/sample.zigbee.light_switch.fota_and_multiprotocol FAILED Build failure (build) is failing due to `/tools/ncs/toolchains/v2.1.0/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/10.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section 'noinit' will not fit in region 'SRAM'` @tomchy @sebastiandraus I guess you might want to take a look at this. Do you think the sample can be optimized to adopt to the changes introduced with updating of SDC and MPSL?

With the slightly smaller SDC, the test survives.

You might want to consider reducing ([CONFIG_BT_MAX_CONN](https://github.com/nrfconnect/sdk-nrf/blob/main/samples/zigbee/light_switch/child_image/multiprotocol_rpmsg/boards/nrf5340dk_nrf5340_cpunet_fota.conf#L19)) to reduce memory. I don't think you need that many.

2022-10-28 06:42 UTC, rugeGerritsen approved these changes

2022-10-28 13:53 UTC, bugo-nordic approved these changes

2022-10-28 13:58 UTC, rugeGerritsen requested changes
I would be happy if you could change the commit message to:
```
Bluetooth: Controller: Don't set adv set count if not supported

Setting the number of advertisers for a build configuration that does not support the peripheral role will fail.
```

2022-10-28 13:58 UTC, rugeGerritsen commented on subsys/bluetooth/controller/hci_driver.c
> +	if (IS_ENABLED(CONFIG_BT_PERIPHERAL)) {
We need to be able to set the number of advertising sets when not supporting the peripheral
```suggestion
	if (IS_ENABLED(CONFIG_BT_BROADCASTER)) {
```

2022-11-02 12:21 UTC, joerchan requested changes
This PR was first pointing to nrfxlib#853, which was merged without this manifest PR ever being green, or merged.

This is currently blocking others from merging to nrfxlib because 853 has a regression and the Bluetooth test-cases are red.

I am therefore reverting the changes of 853, and blocking this PR until that has been done.
This PR needs to be rebased on top of https://github.com/nrfconnect/sdk-nrf/pull/9179/files once that is merged.

2022-11-04 17:34 UTC, ibaz-nordic commented
Finally passed CI.

Code owners - please let me know if you have any concerns.
Appreciate it if we could merge this ASAP as it has been blocked for a while (due to CI failure).

2022-11-07 07:25 UTC, jori-nordic approved these changes

2022-11-07 07:25 UTC, jori-nordic commented
> Finally passed CI.
> 
> Code owners - please let me know if you have any concerns. Appreciate it if we could merge this ASAP as it has been blocked for a while (due to CI failure).

tag them directly

2022-11-07 08:49 UTC, jciupis approved these changes

2022-11-07 08:55 UTC, rlubos commented on west.yml
> +      revision: pull/859/head
Please update SHA: `688cdced97ff20d507def2d17d42d20654968758`

2022-11-07 09:00 UTC, rlubos approved these changes

2022-11-07 09:17 UTC, rugeGerritsen approved these changes

2022-11-07 09:19 UTC, canisLupus1313 approved these changes

2022-11-07 14:52 UTC, tejlmand approved these changes
lgtm

2022-11-07 17:04 UTC, merged