doc: Add 2.1.2 to main
nrfconnect/sdk-nrf pull request #9115
Opened 2022-10-26 14:12 UTC by umapraseeda

Add 2.1.2 docs to main

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

- [ ] Add release notes (with highlights)

2022-10-27 05:26 UTC, peknis approved these changes

2022-10-27 16:57 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9115
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-31 08:02 UTC, greg-fer requested changes

2022-10-31 08:02 UTC, greg-fer commented on doc/nrf/releases/release-notes-2.1.2.rst
> +This minor release adds the following changes on top of the :ref:`nRF Connect SDK v2.1.0 <ncs_release_notes_210>`:
See edits to #9114

2022-10-31 08:02 UTC, greg-fer commented on doc/nrf/releases/release-notes-2.1.2.rst
> +This is the same commit ID as the one used for |NCS| :ref:`v2.1.0 <ncs_release_notes_210>`.
See edits to #9114

2022-10-31 08:54 UTC, umapraseeda commented on doc/nrf/releases/release-notes-2.1.2.rst
> +This minor release adds the following changes on top of the :ref:`nRF Connect SDK v2.1.0 <ncs_release_notes_210>`:
applied here too.

2022-11-02 13:01 UTC, umapraseeda commented on doc/nrf/releases/release-notes-2.1.2.rst
> +This is the same commit ID as the one used for |NCS| :ref:`v2.1.0 <ncs_release_notes_210>`.
Applied edits from 9114.

2022-11-04 08:58 UTC, greg-fer approved these changes

2022-11-04 09:32 UTC, rlubos approved these changes

2022-11-04 10:49 UTC, b-gent approved these changes

2022-11-04 10:57 UTC, rlubos commented
Aborted the full CI since it's doc only (apparently the CI did not detect the label on rerun)

2022-11-04 10:57 UTC, merged