samples: peripheral: radio_test: Add nRF7002 DK support
nrfconnect/sdk-nrf pull request #9136
Opened 2022-10-27 16:55 UTC by krish2718

Add nRF7002 DK support for radio test and empty application core samples, this is same as nRF5340 as there are no Wi-Fi changes but helps use test nRF7002 definitions (DTS).

Signed-off-by: Krishna T <krishna.t@nordicsemi.no>

2022-10-27 17:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9136
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-28 09:22 UTC, mjd90 commented on samples/peripheral/radio_test/README.rst
> +   On nRF5340 DK and nrf7002 DK, the sample is designed to run on the network core.
```suggestion
   On nRF5340 DK and nRF7002 DK, the sample is designed to run on the network core.
```

2022-10-28 12:54 UTC, krga2022 approved these changes
Ble_radio test between two boards is working as expected
Transmitted 10000 packets on TX and able to receive all 10000 packets on RX board.

2022-10-28 14:31 UTC, mjd90 approved these changes
Looks good.

2022-10-31 11:58 UTC, richabp requested changes

2022-10-31 11:58 UTC, richabp commented on samples/peripheral/radio_test/README.rst
> +    Above examples are applicable for |nRF7002DKnoref| as well, please use the board name nrf7002dk_nrf5340_cpunet in the commands.
```suggestion
    You can also build the sample with the remote IPC Service Shell for the |nRF7002DKnoref| using the ``nrf7002dk_nrf5340_cpunet`` build target in the commands.
```

2022-11-02 09:26 UTC, richabp approved these changes

2022-12-07 19:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9136/6/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9136/6/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9136/6/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-12 08:11 UTC, merged