OTBR support
nrfconnect/sdk-nrf pull request #9151
Opened 2022-10-28 17:01 UTC by krish2718

Add an overlay for Wi-Fi thread combo, useful for the OTBR [1].
    
    OpenThread interface is the first interface though its not default, so,
    we need to explicitly initialize the network stack to use Wi-Fi
    interface else DHCPv4 chooses OpenThread and it will drop the packets as
    it only supports IPv6.
    
    [1] - https://openthread.io/guides/border-router

2022-10-28 17:02 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/2e7d29c4868ada9cc4c7bc2c434b3b0c1af08527 | https://github.com/nrfconnect/sdk-hostap/pull/40 | [nrfconnect/sdk-hostap#40/files](https://github.com/nrfconnect/sdk-hostap/pull/40/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-10-28 17:48 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9151
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-10-31 03:53 UTC, sr1dh48r approved these changes

2022-10-31 12:12 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/28168/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-03 10:22 UTC, jciupis requested changes
I have a couple of comments that I'd like to see addressed before this PR is merged.

1. I pulled the code from the PR and built the `wifi/shell` sample for nRF7002 DK using the following command:
```
west built -p -b nrf7002dk_nrf5340_cpuapp -- -DOVERLAY_CONFIG=./overlay-otbr.conf
```
It crashes almost immediately after boot. I'm not ruling out some hardware issue on my side, but so far it hasn't worked out of the box for me - let's synchronize directly on this.

2. I'm missing documentation of this new overlay. The name `overlay-otbr` is rather cryptic and its purpose is not documented anywhere. Could you please add, for example, a section in the sample's `README.rst`?
3. It seems to me that the commits in this PR are not bisectable. First the overlay is added, then the manifest update that should allow it to work is added, and then some fix for the sample is added. Could you please look into the commit history and restructure it to make it clean?

2022-11-10 12:30 UTC, sachinthegreen requested changes

2022-11-10 12:30 UTC, sachinthegreen commented on samples/wifi/shell/src/wifi_main.c
> +#ifdef CONFIG_NET_L2_OPENTHREAD
I guess we can remove this conditional flag...i.e. make this applicable by default.

2022-11-10 12:30 UTC, sachinthegreen commented on samples/wifi/shell/src/wifi_main.c
> +#ifdef CONFIG_NET_L2_OPENTHREAD
I guess we can remove this conditional flag...i.e. make this applicable by default.

2022-11-14 15:43 UTC, krish2718 commented
> 1. I pulled the code from the PR and built the `wifi/shell` sample for nRF7002 DK using the following command:
> 
> ```
> west built -p -b nrf7002dk_nrf5340_cpuapp -- -DOVERLAY_CONFIG=./overlay-otbr.conf
> ```
> 
> It crashes almost immediately after boot. I'm not ruling out some hardware issue on my side, but so far it hasn't worked out of the box for me - let's synchronize directly on this.
As discussed offline this is not a crash rather an assert, it was because of mismatched build, compiling with `-DCONFIG_NRF700X_REV_A=y` works. But nonetheless it shouldn't crash, but the `net_if_up` mandatorily expectes MAC address even if the interface is failed to bring (for nrf7002 l2->enable is not defined). @rlubos is this expected?
> 
> 2. I'm missing documentation of this new overlay. The name `overlay-otbr` is rather cryptic and its purpose is not documented anywhere. Could you please add, for example, a section in the sample's `README.rst`?

Renamed the overlay to openthread (easier to fix this than write docs :) ).

> 3. It seems to me that the commits in this PR are not bisectable. First the overlay is added, then the manifest update that should allow it to work is added, and then some fix for the sample is added. Could you please look into the commit history and restructure it to make it clean?

LGTM now, please check.

2022-11-21 07:10 UTC, sachinthegreen commented
> I have a couple of comments that I'd like to see addressed before this PR is merged.
> 
> 1. I pulled the code from the PR and built the `wifi/shell` sample for nRF7002 DK using the following command:
> 
> ```
> west built -p -b nrf7002dk_nrf5340_cpuapp -- -DOVERLAY_CONFIG=./overlay-otbr.conf
> ```
> 
> It crashes almost immediately after boot. I'm not ruling out some hardware issue on my side, but so far it hasn't worked out of the box for me - let's synchronize directly on this.
> 
> 2. I'm missing documentation of this new overlay. The name `overlay-otbr` is rather cryptic and its purpose is not documented anywhere. Could you please add, for example, a section in the sample's `README.rst`?
> 3. It seems to me that the commits in this PR are not bisectable. First the overlay is added, then the manifest update that should allow it to work is added, and then some fix for the sample is added. Could you please look into the commit history and restructure it to make it clean?



> 



> 

@jciupis : If you are ok with these resolutions, could you please give your upvote so that this PR can be merged?

2022-11-21 07:38 UTC, jciupis approved these changes
LGTM, sorry that I kept you waiting @sachinthegreen @krish2718 :)

2022-11-22 11:35 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9151/7/)
- Skipped (Not yet implemented)

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9151/7/)
- Skipped (Not yet implemented)



*Note: This message is automatically posted and updated by the CI*

2023-01-10 11:05 UTC, merged