application: nrf_desktop: update the b0 bootloader config in readme
nrfconnect/sdk-nrf pull request #9184
Opened 2022-11-02 14:37 UTC by kapi-no

Updated the B0 bootloader configuration section in the nRF Desktop application readme file with information on how to correctly set the firmware version on both image slots  before the DFU package generation.

Ref: NCSDK-13838

Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

2022-11-02 15:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9184
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-02 16:39 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/28241/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-03 09:33 UTC, divipillai approved these changes

2022-11-03 10:02 UTC, pdunaj approved these changes

2022-11-03 10:07 UTC, annwoj commented on applications/nrf_desktop/README.rst
> +  For the DFU package generation, you need to update this configuration in the main application image and the ``s1_image`` child image.
For the DFU package generation -> To generate the DFU package

2022-11-03 10:11 UTC, annwoj commented on applications/nrf_desktop/README.rst
> +  You can do that by rebuilding the application from scratch or by changing the configuration independently in both images with the help of menuconfig.
with the help of menuconfig ->in menuconfig / through menuconfig

Sorry for leaving comments instead, suggesting mode doesn't work for me for some reason.

2022-11-03 10:38 UTC, MarekPieta requested changes

2022-11-03 10:38 UTC, MarekPieta commented on applications/nrf_desktop/README.rst
> +  For the DFU package generation, you need to update this configuration in the main application image and the ``s1_image`` child image.
Maybe we should explain here that we build images for both S0 and S1 if we use B0. The S0 image is built as the main application and S1 image is built as a child image called `s1_image`. Such introduction could be helpful for customers.

2022-11-03 10:38 UTC, MarekPieta commented on applications/nrf_desktop/README.rst
>  * :kconfig:option:`CONFIG_SB_SIGNING_KEY_FILE` - Required for providing the signature used for image signing and verification.
In commit message `applications: ...`

2022-11-03 10:38 UTC, MarekPieta commented on applications/nrf_desktop/README.rst
>  * :kconfig:option:`CONFIG_SB_SIGNING_KEY_FILE` - Required for providing the signature used for image signing and verification.
We also use `Jira: NCSDK-XXXX` instead of `Ref: NCSDK-XXXX`. Maybe we could align here?

2022-11-03 10:38 UTC, MarekPieta commented on applications/nrf_desktop/README.rst
> +  You can do that by rebuilding the application from scratch or by changing the configuration independently in both images with the help of menuconfig.
If I update image version in application's `prj.conf`, version for both images is updated.
If I update through menuconfig, `manifest.json` in the zip shows both images with updated versions, but the actual firmware version included in the S1 image is not updated. It seems like a bug. Maybe we need to resolve it before introducing documentation.

2023-01-17 00:28 UTC, closed without merging