samples: peripheral_uart: Allow build with security disabled
nrfconnect/sdk-nrf pull request #9188
Opened 2022-11-02 15:53 UTC by rakons

This commit fix the build with BT_NUS_SECURITY_ENABLED option disabled. Test for such configuration added.

JIRA: NCSDK-17883

Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>

2022-11-03 08:38 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9188
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-03 09:24 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sub/job/test-fw-nrfconnect-nrf/job/master/28268/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-03 14:26 UTC, emob-nordic approved these changes

2022-11-03 14:26 UTC, KAGA164 approved these changes
Look good to me

2022-11-03 15:09 UTC, KAGA164 commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Fixed code build with BT_NUS_SECURITY_ENABLED option disabled.
```suggestion
    * Fixed code build with the :kconfig:option:`CONFIG_BT_NUS_SECURITY_ENABLED` Kconfig option disabled.
```

2022-11-03 15:09 UTC, KAGA164 commented on doc/nrf/known_issues.rst
> +NCSDK-17883: Cannot build peripheral UART sample with security disabled
```suggestion
NCSDK-17883: Cannot build peripheral UART sample with security (:kconfig:option:`CONFIG_BT_NUS_SECURITY_ENABLED`) disabled
```

2022-11-04 07:38 UTC, KAGA164 approved these changes

2022-11-04 07:39 UTC, peknis requested changes

2022-11-04 07:39 UTC, peknis commented on doc/nrf/known_issues.rst
> +  The :ref:`peripheral_uart` sample fails to build when BT_NUS_SECURITY_ENABLED option is disabled.
```suggestion
  The :ref:`peripheral_uart` sample fails to build when the :konfig:option:`BT_NUS_SECURITY_ENABLED` Kconfig option is disabled.
```

2022-11-04 07:39 UTC, peknis commented on doc/nrf/known_issues.rst
> +  **Workaround:** In main.c file, search for the ``#else`` of ``#if defined(CONFIG_BT_NUS_SECURITY_ENABLED)`` add empty declaration of conn_auth_info_callbacks structure, just after the similar empty
```suggestion
  **Workaround:** In :file:`main.c` file, search for the ``#else`` entry of the ``#if defined(CONFIG_BT_NUS_SECURITY_ENABLED)`` item and add an empty declaration of the ``conn_auth_info_callbacks`` structure,  just after the similar empty definition of ``conn_auth_callbacks``.
```

2022-11-07 08:41 UTC, peknis requested changes

2022-11-07 08:41 UTC, peknis commented on doc/nrf/known_issues.rst
> +  The :ref:`peripheral_uart` sample fails to build when the :konfig:option:`BT_NUS_SECURITY_ENABLED` Kconfig option is disabled.
```suggestion
  The :ref:`peripheral_uart` sample fails to build when the :kconfig:option:`BT_NUS_SECURITY_ENABLED` Kconfig option is disabled.
```
Sorry, had a typo in my earlier suggestion.

2022-11-07 08:41 UTC, peknis commented on doc/nrf/known_issues.rst
> +  **Workaround:** In :file:`main.c` file, search for the ``#else`` entry of the ``#if defined(CONFIG_BT_NUS_SECURITY_ENABLED)`` item and add an empty declaration of the ``conn_auth_info_callbacks`` s
```suggestion
  **Workaround:** In :file:`main.c` file, search for the ``#else`` entry of the ``#if defined(CONFIG_BT_NUS_SECURITY_ENABLED)`` item and add an empty declaration of the ``conn_auth_info_callbacks`` structure, just after the similar empty definition of ``conn_auth_callbacks``.
```

2022-11-07 10:20 UTC, peknis approved these changes

2022-11-16 14:13 UTC, merged