samples: nrf5340: multiprotocol_rpmsg: decrease BT_MAX_CONN
nrfconnect/sdk-nrf pull request #9226
Opened 2022-11-08 13:27 UTC by jciupis

The multiprotocol_rpmsg is hovering around the limits of RAM available on nRF5340 network core. In order to free some of the memory and make it easier to extend the sample with additional features, this commit reduces the maximum number of concurrent BLE connections to 4. In real-life scenarios, it is unexpected for more concurrent connections to be needed*. The decrease should therefore impose no actual limitations on the users while saving a lot of RAM.

*in fact, is is uncommon for any multiprotocol application to use more concurrent connections than 2, so there's still a margin.

Signed-off-by: Jędrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

2022-11-08 13:29 UTC, rugeGerritsen approved these changes

2022-11-08 13:42 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9226/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-08 13:46 UTC, hubertmis approved these changes
Should this be accompanied with a point in release notes?

2022-11-08 14:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9226
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-09 10:50 UTC, jciupis commented
@hubertmis release notes updated.

2022-11-10 07:38 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Decreased the maximum supported number of concurrent BLE connections to 4.
```suggestion
  * Decreased the maximum supported number of concurrent Bluetooth LE connections to 4.
```
BLE acronym is forbidden in docs.

2022-11-10 07:38 UTC, greg-fer requested changes
One edit.

2022-11-10 11:20 UTC, greg-fer approved these changes

2022-11-10 12:02 UTC, merged