doc: Doc fixes
nrfconnect/sdk-nrf pull request #9298
Opened 2022-11-15 12:39 UTC by umapraseeda

Doc fixes 
Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

2022-11-15 13:32 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9298
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-15 13:49 UTC, peknis requested changes

2022-11-15 13:49 UTC, peknis commented on doc/nrf/ug_radio_coex.rst
> +3. If :kconfig:option:`CONFIG_WIFI` is disabled or none of the supported SR protocols are enabled the implementation must be enabled manually with :kconfig:option:`CONFIG_MPSL_CX` and :kconfig:option
```suggestion
3. If :kconfig:option:`CONFIG_WIFI` is disabled or none of the supported SR protocols are enabled, the implementation must be enabled manually with :kconfig:option:`CONFIG_MPSL_CX` and :kconfig:option:`CONFIG_MPSL_CX_NRF700X`.
```

2022-11-15 13:49 UTC, peknis commented on include/net/lwm2m_client_utils.h
> + * @note This API calls settings_subsys_init() and so should
```suggestion
 * @note This API calls settings_subsys_init() and should
```

2022-11-15 13:49 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Added the ability to use buttons to send get and set messages for a sensor setting, as well as a get message for a sensor descriptor.
```suggestion
  * Added the ability to use buttons to send ``get`` and ``set`` messages for a sensor setting, as well as a ``get`` message for a sensor descriptor.
```
Not 100% sure about this, but I would prefer some highlighting for the message types to make them stand out from the text.

2022-11-15 13:49 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Updated by decreasing the maximum supported number of concurrent Bluetooth LE connections to 4.
4 -> four ?

2022-11-15 13:49 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +     * Parameter type in :c:func:`lte_lc_neighbor_cell_measurement` changed to :c:struct:`lte_lc_ncellmeas_params`.
```suggestion
     * Parameter type in the :c:func:`lte_lc_neighbor_cell_measurement` function changed to :c:struct:`lte_lc_ncellmeas_params`.
```

2022-11-16 09:58 UTC, umapraseeda commented on doc/nrf/ug_radio_coex.rst
> +   When using the :ref:`ug_radio_cx_nrf700x_impl` manually selecting the :kconfig:option:`CONFIG_MPSL_CX` Kconfig option is not needed.
@FrancescoSer could you check/suggest? Would this be correct: When using the :ref:`ug_radio_cx_nrf700x_impl`, manually selecting the :kconfig:option:`CONFIG_MPSL_CX` Kconfig option is not needed.

2022-11-18 15:28 UTC, FrancescoSer requested changes

2022-11-18 15:28 UTC, FrancescoSer commented on samples/wifi/shell/README.rst
> +.. code-block::console
```suggestion
.. code-block:: console
```

2022-11-23 06:26 UTC, peknis requested changes

2022-11-23 06:26 UTC, peknis commented on doc/nrf/ug_radio_coex.rst
> +   When using the :ref:`ug_radio_cx_nrf700x_impl`, manually selecting the :kconfig:option:`CONFIG_MPSL_CX` Kconfig option is not needed.
```suggestion
   When using the :ref:`ug_radio_cx_nrf700x_impl`, you do not need to select the :kconfig:option:`CONFIG_MPSL_CX` Kconfig option manually.
```

2022-11-23 08:54 UTC, divipillai approved these changes

2022-11-23 09:37 UTC, FrancescoSer approved these changes

2022-11-23 09:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9298/8/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9298/8/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9298/8/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-23 16:24 UTC, pdunaj approved these changes

2022-11-24 06:46 UTC, sachinthegreen approved these changes

2022-11-24 08:45 UTC, umapraseeda commented
The fixes to the changelog will be applied later while creating the release notes from the changelog. Removing that from the PR.

2022-11-24 09:16 UTC, Damian-Nordic approved these changes

2022-11-24 12:54 UTC, joerchan requested changes

2022-11-24 13:42 UTC, umapraseeda commented on samples/bluetooth/throughput/README.rst
> +#. Press **Button 2** on the second development kit or type ``peripheral`` in the terminalconnected to the second kit to set it into the peripheral (peer) role.
fixed

2022-11-24 13:44 UTC, joerchan approved these changes

2022-11-24 15:51 UTC, merged