nRF Desktop Simplify Bluetooth configurat part 2
nrfconnect/sdk-nrf pull request #9320
Opened 2022-11-16 13:33 UTC by kapi-no

2022-11-16 13:36 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9320/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-16 14:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9320
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-18 12:41 UTC, MarekPieta requested changes

2022-11-18 12:41 UTC, MarekPieta commented on applications/nrf_desktop/Kconfig.ble
> +	default y
Maybe modules that use these options could select them?

2022-11-18 15:21 UTC, kapi-no commented on applications/nrf_desktop/Kconfig.ble
> +config DESKTOP_BT_CENTRAL
Are we sure that we want to have such a constraint? It is not uncommon to be both Peripheral and Central  (e.g. DESKTOP_ROLE_HID_RELAY). I think that some Audio roles require both Central and Peripheral capabilities (e.g. Scan Delegator, Broadcast Assistant)

2022-11-18 15:30 UTC, kapi-no commented on applications/nrf_desktop/Kconfig.ble
> +	default y
I thought that it should be the other way around:

1. nRF Desktop Role determines the high-level use case of the application configuration
2. Based on the high-level role, we may want to add Bluetooth connectivity for Bluetooth devices (DESKTOP_BT_CENTRAL / DESKTOP_BT_PERIPHERAL)
3. DESKTOP_BT_* selects modules and configuration to fulfill its role in the Bluetooth scope

2022-11-18 15:35 UTC, kapi-no commented on applications/nrf_desktop/Kconfig.ble
> +	default y
I could introduce here independent roles DESKTOP_BT_GATT_CLIENT and DESKTOP_BT_GATT_SERVER that would be selected by some higher-level role. For example:

```
config DESKTOP_ROLE_HID_BT_PERIPHERAL
  select DESKTOP_BT_PERIPHERAL
  select DESKTOP_BT_GATT_SERVER
```

2022-11-20 14:03 UTC, MarekPieta commented on applications/nrf_desktop/Kconfig.ble
> +	default y
Then maybe we should have a single Kconfig option for enabling Bluetooth connectivity for nRF Desktop device (this config could enable the needed Bluetooth modules depending on the fact if device is HID peripheral or HID dongle)? In general HID peripheral works only as a Bluetooth peripheral and HID dongle works only as a Bluetooth central.

2022-11-20 14:04 UTC, MarekPieta commented on applications/nrf_desktop/Kconfig.ble
> +	default y
In the future, we could introduce new nRF Desktop roles and expand enabled Bluetooth configuration to match new use-cases.

2022-11-20 14:10 UTC, MarekPieta commented on applications/nrf_desktop/Kconfig.ble
> +	default y
Regarding selecting Kconfigs, I meant that we could select given functionality in Kconfig that enables module that uses the functionality (e.g. select `CONFIG_BT_GATT_DM` in BLE discovery module Kconfig). Some of the options (like BT_PERIPHERAL or BT_CENTRAL) do not belong directly to any application module, so we should still configure them in global Kconfig (as it's done now).

2022-11-20 14:12 UTC, MarekPieta commented on applications/nrf_desktop/Kconfig.ble
> +config DESKTOP_BT_CENTRAL
Then we could consider using only one option with prompt that enables Bluetooth connectivity (see my comment above). The exact set of enabled modules would still depend on nRF Desktop role, so we could still introduce new modules/options related to role selected by the user.

2022-11-21 13:29 UTC, kapi-no commented on applications/nrf_desktop/src/modules/Kconfig.ble_passkey
> +	default n
Added

2022-11-21 13:30 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9320/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9320/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9320/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-21 13:30 UTC, kapi-no commented on applications/nrf_desktop/Kconfig.ble
> +	default y
Changed it according to your comments and the discussion from the meeting

2022-11-21 13:30 UTC, kapi-no commented on applications/nrf_desktop/Kconfig.ble
> +config DESKTOP_BT_CENTRAL
Addressed

2022-11-22 08:35 UTC, MarekPieta approved these changes

2022-11-22 08:55 UTC, pdunaj approved these changes

2022-11-22 10:59 UTC, merged