Wifi util shell
nrfconnect/sdk-nrf pull request #9329
Opened 2022-11-17 13:50 UTC by ajayparida

2022-11-17 13:51 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/f665cad9361eab62d3eea077b04e68613c7e93a6 | https://github.com/nrfconnect/sdk-hostap/commit/5ee5972d527ede375f982fcedaeea26f2fb03f10 | [nrfconnect/sdk-hostap@f665cad9..5ee5972d](https://github.com/nrfconnect/sdk-hostap/compare/f665cad9361eab62d3eea077b04e68613c7e93a6..5ee5972d527ede375f982fcedaeea26f2fb03f10) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-11-17 13:55 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9329/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-17 14:24 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9329
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-21 07:03 UTC, sachinthegreen requested changes

2022-11-21 07:03 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.h
> + * @brief nRF Wi-Fi radio-test mode shell module
`radio-test` ?

2022-11-21 07:03 UTC, sachinthegreen commented on samples/wifi/shell/prj.conf
> +CONFIG_NRF700X_WIFI_UTIL=y
We should not have this enabled by default.

2022-11-21 11:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9329/8/)
- Skipped (Not yet implemented)

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9329/8/)
- Skipped (Not yet implemented)



*Note: This message is automatically posted and updated by the CI*

2022-11-21 11:07 UTC, ajayparida commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +
No, it is alrady part of command (minimum arguments required)

2022-11-21 11:10 UTC, ajayparida commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +
No it is already part of the command (minimum arguments required)

2022-11-21 12:11 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.h
> + * @brief nRF Wi-Fi radio-test mode shell module
Still shows as Wi-Fi radio-test mode ?

2022-11-22 08:09 UTC, sachinthegreen approved these changes

2022-11-22 09:07 UTC, rlubos approved these changes

2022-11-22 15:23 UTC, merged