Oct 2299 BIS headset to sync to multiple BISes and output the audio for one of these
nrfconnect/sdk-nrf pull request #9331
Opened 2022-11-17 18:03 UTC by gWacey

As a user of the BLE broadcast audio I would like to synchronise to a number of BISes and stream one of these to the output within the earbud. At some point, on a button press, I would like to switch to a different BIS synchronised to and output the audio for this new stream.

2022-11-17 18:05 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9331/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-17 18:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9331
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-21 10:00 UTC, koffes requested changes

2022-11-21 10:00 UTC, koffes commented on applications/nrf5340_audio/tools/buildprog/nrf5340_audio_dk_devices.json
> +       {
All this needs to be removed. You can ignore it locally.

2022-11-21 11:58 UTC, koffes requested changes

2022-11-23 07:28 UTC, erikrobstad commented on applications/nrf5340_audio/src/audio/streamctrl.c
> +			LOG_DBG("Button functions not supported in walkie-talkie mode");
Hmm, for BUTTON_PLAY_PAUSE DBG is used

2022-11-23 08:11 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +			codec_info->octets_per_sdu * 8 * (1000000 / codec_info->frame_duration_us);
Please check my change here

2022-11-23 08:12 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +		LOG_WRN("Codec is not LC3, codec_id: 0x%2hhx", codec->id);
@gWacey

2022-11-23 11:06 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +			LOG_DBG("BIS %d   index = %hhu", j, index);
I have changed this section abit now, we can have a walkthrough

2022-11-23 11:07 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +					break;
Lets discuss this in the walkthrough

2022-11-23 11:10 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +			((active_stream_index == AUDIO_CH_L) ? CH_L_TAG : CH_R_TAG),
See my added comment in the code. It think we can keep it like this for now

2022-11-23 11:10 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +int le_audio_user_defined_button_press(void)
We can discuss in the walkthrough

2022-11-23 11:43 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +	if (active_audio_stream.stream->ep->status.state != BT_AUDIO_EP_STATE_STREAMING) {
I agree that it is abit strange. But I cannot come up with a better name. It is a "bt_audio_stream", not e.g. ID or a number

2022-11-23 11:50 UTC, erikrobstad commented on applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
> +	playing_state = false;
Looks like her is fine

2022-11-23 20:39 UTC, closed without merging

2022-11-23 20:40 UTC, erikrobstad commented
Replaced by https://github.com/nrfconnect/sdk-nrf/pull/9428