lib: location: wifi: nRF Cloud Wi-Fi over MQTT
nrfconnect/sdk-nrf pull request #9348
Opened 2022-11-21 07:09 UTC by jhirsi

In addition to existing REST support, MQTT is now supported with NRF Cloud Wi-Fi positioning. 
NRF_CLOUD_LOCATION taken into use for nRF Cloud Wi-Fi. Thus, removing all nRF Cloud JSON codecs from location lib. 
Jira: NCSDK-15604

2022-11-21 07:10 UTC, NordicBuilder commented
### Integration test specification

| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9348/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-21 07:40 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9348
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-21 08:47 UTC, peknis requested changes

2022-11-21 08:47 UTC, peknis commented on doc/nrf/libraries/modem/location.rst
> +None of the supported DKs have an integrated Wi-Fi chip. You can use external Wi-Fi chip, such as nRF7002 EK, and connect it to the nRF9160 DK.
```suggestion
None of the supported DKs have an integrated Wi-Fi chip.
You can use an external Wi-Fi chip, such as nRF7002 EK, and connect it to the nRF9160 DK.
```

2022-11-21 10:48 UTC, trantanen approved these changes
Good work!

2022-11-22 08:10 UTC, jhirsi commented on doc/nrf/libraries/modem/location.rst
> +None of the supported DKs have an integrated Wi-Fi chip. You can use external Wi-Fi chip, such as nRF7002 EK, and connect it to the nRF9160 DK.
Changed.

2022-11-22 08:11 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9348/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9348/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9348/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-22 09:00 UTC, peknis approved these changes

2022-11-22 09:24 UTC, hiltunent approved these changes

2022-11-22 09:36 UTC, merged

2022-11-22 17:33 UTC, glarsennordic commented
Thanks for this, @jhirsi !