manifest: update sdk-nrf-802154 revision
nrfconnect/sdk-nrf pull request #9357
Opened 2022-11-21 09:43 UTC by jciupis

This commit updates sdk-nrf-802154 and sdk-nrfxlib revision to bring in the latest changes in the nrf_802154 component.

Signed-off-by: Jędrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

2022-11-21 09:43 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrf-802154 | https://github.com/nrfconnect/sdk-nrf-802154/commit/362d2e7af15725f28225a4589ac67aa16c839f38 | https://github.com/nrfconnect/sdk-nrf-802154/commit/994817a30a0d7cd4b5114318480f92867a790d3c (main) | [nrfconnect/sdk-nrf-802154@362d2e7a..994817a3](https://github.com/nrfconnect/sdk-nrf-802154/compare/362d2e7af15725f28225a4589ac67aa16c839f38..994817a30a0d7cd4b5114318480f92867a790d3c) |
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/72a1dc2669632cf9dc98c2313ce6cdae02ffde3a | https://github.com/nrfconnect/sdk-nrfxlib/pull/870 | [nrfconnect/sdk-nrfxlib#870/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/870/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-11-21 09:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9357/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9357/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9357/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-21 10:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9357
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-22 11:47 UTC, rlubos commented on west.yml
> +      revision: pull/870/head
Please update SHA: `db4c249f668e49db8f7d41bf4e85e6f8163ec5d8`

2022-11-22 11:56 UTC, rlubos approved these changes

2022-11-22 13:02 UTC, FrancescoSer requested changes

2022-11-22 13:02 UTC, FrancescoSer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * RADIO trim values are reapplied after POWER register write to workaround hardware errata 158 for nRF5340.
```suggestion
  * RADIO trim values are reapplied after a ``POWER`` register write as a workaround for the hardware errata 158 of the nRF5340.
```

2022-11-23 08:14 UTC, FrancescoSer approved these changes

2022-11-23 08:14 UTC, merged