Bluetooth: Mesh: Use defereed log for Friendship
nrfconnect/sdk-nrf pull request #9365
Opened 2022-11-21 12:05 UTC by Andrewpini

Adds deferred log option to all samples that is configured for friendship. This improves performance while devices is communicating over low power communication channel by avoiding unnecessary delays due to logging events.

Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

2022-11-21 12:07 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9365/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9365/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9365/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-21 12:51 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9365
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-21 15:12 UTC, omkar3141 requested changes
I think adding a config option here misses the point that the reader of this prj.conf will not be able to figure out why LOG_MODE_DEFERRED is needed here or what are the consequences of removing this. I would say it is better to do this via Kconfig file.
```
config BT_MESH_FRIEND
	bool "Support for acting as a Friend Node"
        imply LOG_MODE_DEFERRED if LOG
	help
	  Enable this option to be able to act as a Friend Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to improve the power performance of LPN.
	  
config BT_MESH_LOW_POWER
	bool "Support for Low Power features"
        imply LOG_MODE_DEFERRED if LOG
	help
	  Enable this option to be able to act as a Low Power Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to improve the power performance of LPN.
```

2022-11-22 08:11 UTC, Andrewpini commented
> I think adding a config option here misses the point that the reader of this prj.conf will not be able to figure out why LOG_MODE_DEFERRED is needed here or what are the consequences of removing this. I would say it is better to do this via Kconfig file.
> 
> ```
> config BT_MESH_FRIEND
> 	bool "Support for acting as a Friend Node"
>         imply LOG_MODE_DEFERRED if LOG
> 	help
> 	  Enable this option to be able to act as a Friend Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to help reduce the average current consumption of LPN.
> 	  
> config BT_MESH_LOW_POWER
> 	bool "Support for Low Power features"
>         imply LOG_MODE_DEFERRED if LOG
> 	help
> 	  Enable this option to be able to act as a Low Power Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to the average current consumption of LPN.
> ```

I see your point. But it comes at a small cost to do it in this way. It does not necessarily create issues for this particular case, but if we start to follow this pattern it would require users to be more aware of the different Kconfig options since they now have side effects that does not only concern mesh related configuration. I'm not opposed to do it in this way, but then we must close this PR and do another one in zephyr.

2022-11-22 08:15 UTC, ludvigsj commented
> > I think adding a config option here misses the point that the reader of this prj.conf will not be able to figure out why LOG_MODE_DEFERRED is needed here or what are the consequences of removing this. I would say it is better to do this via Kconfig file.
> > ```
> > config BT_MESH_FRIEND
> > 	bool "Support for acting as a Friend Node"
> >         imply LOG_MODE_DEFERRED if LOG
> > 	help
> > 	  Enable this option to be able to act as a Friend Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to help reduce the average current consumption of LPN.
> > 	  
> > config BT_MESH_LOW_POWER
> > 	bool "Support for Low Power features"
> >         imply LOG_MODE_DEFERRED if LOG
> > 	help
> > 	  Enable this option to be able to act as a Low Power Node. When this feature is used in the application, it is recommended to use deferred logging, or to turn off logging, to the average current consumption of LPN.
> > ```
> 
> I see your point. But it comes at a small cost to do it in this way. It does not necessarily create issues for this particular case, but if we start to follow this pattern it would require users to be more aware of the different Kconfig options since they now have side effects that does not only concern mesh related configuration. I'm not opposed to do it in this way, but then we must close this PR and do another one in zephyr.

I _am_ a bit opposed to do it this way, it will move the Kconfig in the direction of spaghetti. In general I'm not a fan of "magic" where changing one thing has a number of cascading effects elsewhere. I'd rather suggest to do it the way Anders has done here, and also mention in the documentation and/or a comment in the cfg files _why_ this is done.

2022-11-22 08:25 UTC, Andrewpini commented
`imply LOG_MODE_DEFERRED if LOG` 
Conditional imply is not supported either

2022-11-22 10:01 UTC, omkar3141 commented
> `imply LOG_MODE_DEFERRED if LOG` Conditional imply is not supported either

It is being used already.

https://github.com/nrfconnect/sdk-nrf/blob/0cb35d7d07bcb3f37542709bfa148b4578a1154f/samples/Kconfig#L15
https://github.com/nrfconnect/sdk-nrf/blob/0cb35d7d07bcb3f37542709bfa148b4578a1154f/subsys/zigbee/lib/zigbee_fota/Kconfig#L14

2022-11-22 10:16 UTC, omkar3141 commented
> I _am_ a bit opposed to do it this way, it will move the Kconfig in the direction of spaghetti. In general I'm not a fan of "magic" where changing one thing has a number of cascading effects elsewhere. I'd rather suggest to do it the way Anders has done here, and also mention in the documentation and/or a comment in the cfg files _why_ this is done.

I don't think this is creating spaghetti. Imply is not a strong configuration and it can be overridden easily. Anyone who uses CONFIG options can easily refer to Kconfig options from vscode extension or documentation. Adding an option to "prj.conf" with no explanation creates a situation where application developers have to simply guess what is the logic behind specific magic options that make the sample work, if they change or remove some config option, suddenly the sample is performing poorly and it is not easy to figure out why. 

I'm also okay adding this each prj.conf as long as it is added as:
```
# Deffered logging helps improve LPN power consumption
# when friendship is established.
CONFIG_LOG_MODE_DEFERRED=y
```

Once could argue that this statement can be inserted into LPN sample documentation, but we also need to make this statement for the friend feature, somewhere that is intuitively easy to find out. Since Friend and LPN both need this option enabled for friendship to work optimally.

2022-11-22 13:01 UTC, Andrewpini commented
> > `imply LOG_MODE_DEFERRED if LOG` Conditional imply is not supported either
> 
> It is being used already.
> 
> https://github.com/nrfconnect/sdk-nrf/blob/0cb35d7d07bcb3f37542709bfa148b4578a1154f/samples/Kconfig#L15
> 
> 
> https://github.com/nrfconnect/sdk-nrf/blob/0cb35d7d07bcb3f37542709bfa148b4578a1154f/subsys/zigbee/lib/zigbee_fota/Kconfig#L14

Strange... I could not get your suggestion to compile at least

2022-11-22 13:01 UTC, Andrewpini commented
> > I _am_ a bit opposed to do it this way, it will move the Kconfig in the direction of spaghetti. In general I'm not a fan of "magic" where changing one thing has a number of cascading effects elsewhere. I'd rather suggest to do it the way Anders has done here, and also mention in the documentation and/or a comment in the cfg files _why_ this is done.
> 
> I don't think this is creating spaghetti. Imply is not a strong configuration and it can be overridden easily. Anyone who uses CONFIG options can easily refer to Kconfig options from vscode extension or documentation. Adding an option to "prj.conf" with no explanation creates a situation where application developers have to simply guess what is the logic behind specific magic options that make the sample work, if they change or remove some config option, suddenly the sample is performing poorly and it is not easy to figure out why.
> 
> I'm also okay adding this each prj.conf as long as it is added as:
> 
> ```
> # Deffered logging helps improve LPN power consumption
> # when friendship is established.
> CONFIG_LOG_MODE_DEFERRED=y
> ```
> 
> Once could argue that this statement can be inserted into LPN sample documentation, but we also need to make this statement for the friend feature, somewhere that is intuitively easy to find out. Since Friend and LPN both need this option enabled for friendship to work optimally.

Ok, then I'll do that 👍

2022-11-23 11:34 UTC, ludvigsj approved these changes
But please update the commit message to say "deferred" instead of "defereed", to make it easier when searching for this.

2022-11-23 12:29 UTC, omkar3141 approved these changes

2022-11-24 07:34 UTC, nordicjm requested changes
Previous comment asked for typo correction in commit message

2022-11-24 08:57 UTC, Andrewpini commented
> Previous comment asked for typo correction in commit message

Done @nordicjm

2022-11-24 08:58 UTC, nordicjm approved these changes

2022-11-24 16:04 UTC, merged