subsys: nfc: Fix write to constant and out of bound write
nrfconnect/sdk-nrf pull request #9389
Opened 2022-11-22 12:43 UTC by dchat-nordic

Fix write to a constant by memset in ndef.
Fix out of bound write by memcpy in isodep.

2022-11-22 12:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9389/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9389/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9389/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-22 13:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9389
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-22 13:23 UTC, peknis requested changes

2022-11-22 13:23 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed write to a constant field in the :c:func:`ac_rec_payload_parse` function.
```suggestion
  * Fixed a write to a constant field in the :c:func:`ac_rec_payload_parse` function.
```

2022-11-23 06:18 UTC, peknis approved these changes

2022-11-23 13:28 UTC, grochu reviewed
Looks good. Just a minor comment clarifying the code.

2022-11-23 13:28 UTC, grochu commented on subsys/nfc/t4t/isodep.c
> +		if (t4t_isodep.tag.historical_len > NFC_T4T_ISODEP_HIST_MAX_LEN) {
Please add a comment saying that parsing is limited to 15 bytes as specification mandates. Parsing of further historical bytes is not supported.

2022-11-23 14:46 UTC, grochu approved these changes

2022-11-24 09:22 UTC, merged