net: ftp_client: Fix doxygen markers for response codes
nrfconnect/sdk-nrf pull request #9396
Opened 2022-11-22 14:44 UTC by rlubos

The response code API documentation did not use a valid doxygen syntax, resuling in the documentation not being rendered correctly.

NCSDK-18150

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

2022-11-22 14:51 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9396/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9396/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9396/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-22 15:20 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9396
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-23 06:11 UTC, peknis requested changes

2022-11-23 06:11 UTC, peknis commented on include/net/ftp_client.h
> +	/** Can't open data connection */
```suggestion
	/** Cannot open data connection */
```

2022-11-23 06:11 UTC, peknis commented on include/net/ftp_client.h
> +	 *  File unavailable (e.g., file busy)
```suggestion
	 *  File unavailable (for example, file busy)
```

2022-11-23 06:11 UTC, peknis commented on include/net/ftp_client.h
> +	/** Requested action not taken. File unavailable (e.g., file not found,
```suggestion
	/** Requested action not taken. File unavailable (for example, file not found,
```

2022-11-23 08:21 UTC, peknis approved these changes

2022-11-24 10:27 UTC, junqingzou approved these changes

2022-11-24 10:29 UTC, merged