doc: Drop read only functionality for bl_storage library from app
nrfconnect/sdk-nrf pull request #9418
Opened 2022-11-23 11:14 UTC by mswarowsky

If the application rely on reading out the OTP based on the bl_storage format, the NISB and the application must always be compiled with the same version of the bl_storage library.
But as the format of OTP within the bl_storage might change in future, it is likely that the application is build with a newer version causing read failures if a DFU is performed.

Therefore we remove the feature to use the library within the application.

Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

2022-11-23 11:17 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9418/1/)
- Skipped (Not yet implemented)

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9418/1/)
- Skipped (Not yet implemented)



*Note: This message is automatically posted and updated by the CI*

2022-11-23 11:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9418
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-23 12:27 UTC, Vge0rge commented on doc/nrf/libraries/bootloader/bl_storage.rst
> +If the |NSIB| (NSIB) is used the library can only be used by the NSIB and must not included into the application image.
If the |NSIB| (NSIB) is enabled it should be only user of this library. The application image can only include this library when |NSIB| (NSIB) is disabled.

Seems a bit more clear to me

2022-11-23 14:57 UTC, Vge0rge approved these changes

2022-11-24 07:54 UTC, mia-ko requested changes

2022-11-24 07:54 UTC, mia-ko commented on doc/nrf/libraries/bootloader/bl_storage.rst
> +If the |NSIB| (NSIB) is enabled it should be the only user of this library. The application image can only include this library when |NSIB| (NSIB) is disabled.
```suggestion

If the |NSIB| (NSIB) is enabled, it should be the only user of this library.
The application image can only include this library when NSIB is disabled.
```

2022-11-24 07:54 UTC, mia-ko commented on doc/nrf/releases/release-notes-changelog.rst
> +  * :ref:`doc_bl_storage`: Removed option to use the library to read out OTP memory from the application, when the |NSIB| (NSIB) is used.
```suggestion
  * :ref:`doc_bl_storage`:
  
    * Removed the option of application using the library to read OTP memory when the |NSIB| (NSIB) is enabled.
```

2022-11-24 13:43 UTC, joerchan approved these changes

2022-11-24 14:12 UTC, merged