samples: nrf9160: default to newlibc nano
nrfconnect/sdk-nrf pull request #9420
Opened 2022-11-23 11:29 UTC by lemrey

The nano flavour of newlibc used to be the default before NCS v2.2.0.

This changed when the commit in
https://github.com/zephyrproject-rtos/zephyr/pull/51340 was merged downstream, increasing the FLASH size of all nrf9160 samples by about 40KB, due to their requirement on some variadic C functions whose implementation is much larger in vanilla newlibc.

This patch reverts the change from upstream and maintains the newlibc nano flavour as the default, avoiding a size increase across all nrf9160 samples.

2022-11-23 11:32 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9420/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9420/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9420/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-23 12:10 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9420
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-24 12:18 UTC, tejlmand requested changes
let's stick to newlib-nano as default in NCS when newlib is selected.

2022-11-24 12:18 UTC, tejlmand commented on samples/Kconfig
> +
no reason for a new kconfig, and certainly not with `imply`.

Let's just change the default to be nano in Kconfig.nrf here:
https://github.com/nrfconnect/sdk-nrf/blob/cce7127811522aae923f2ef062053601a5e0ed79/Kconfig.nrf#L10

Add something like:
```
# Zephyr default is newlib and not newlib-nano for consistency between architectures.
# For footprint reasons, newlib-nano is preferred default in NCS when newlib is selected.
config NEWLIB_LIBC_NANO
	default y
	depends on NEWLIB_LIBC && HAS_NEWLIB_LIBC_NANO
```

2022-11-24 12:49 UTC, lemrey commented
Thanks @tejlmand I made the changes you proposed, one thing to keep in mind now is:
- for nrf9160 samples, this maintains the nano flavour as default, as it had been before latest upmerge
- for all other samples that use newlibc, it will set the nano flavour as default (this might be a change)

2022-11-24 13:13 UTC, rlubos commented
> for all other samples that use newlibc, it will set the nano flavour as default (this might be a change)

I'm not sure if I follow, how is that different for non-nrf9160 samples? If they relied on the default newlib configuration before the upmerge, they must've worked with nano variant - otherwise, nano must've been disabled explicitly in the project file, and this still takes precedence over the default choice here.

2022-11-24 13:13 UTC, rlubos approved these changes

2022-11-25 08:37 UTC, lemrey commented
I tried a rebase this morning

2022-11-25 12:46 UTC, merged