doc: Remove outdated sample FEM documentation
nrfconnect/sdk-nrf pull request #9427
Opened 2022-11-23 13:28 UTC by KAGA164

Remove outdated front-end module documentation for the Radio Test and the Direct Test Mode sample.

2022-11-23 13:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9427/1/)
- Skipped (Not yet implemented)

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9427/1/)
- Skipped (Not yet implemented)



*Note: This message is automatically posted and updated by the CI*

2022-11-23 13:43 UTC, peknis requested changes

2022-11-23 13:43 UTC, peknis commented on doc/nrf/includes/sample_dtm_radio_test_fem.txt
>  ``west build -b nrf5340dk_nrf5340_cpunet -- -DSHIELD=nrf21540_ek``
```suggestion
For example, to build the sample from the command line for an nRF5340 DK with an attached nRF21540 EK, invoke the following command within the sample directory:

``west build -b nrf5340dk_nrf5340_cpunet -- -DSHIELD=nrf21540_ek``
```

2022-11-23 14:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9427
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-23 15:00 UTC, grochu approved these changes

2022-11-23 15:06 UTC, KAGA164 commented on doc/nrf/includes/sample_dtm_radio_test_fem.txt
>  ``west build -b nrf5340dk_nrf5340_cpunet -- -DSHIELD=nrf21540_ek``
I replaced it with the `code-block`

2022-11-24 06:35 UTC, peknis approved these changes

2022-11-24 09:20 UTC, merged