applications: asset_tracker_v2: Ignore error code when enabling mdev
nrfconnect/sdk-nrf pull request #9429
Opened 2022-11-23 13:34 UTC by simensrostad

Modem domain events are not supported for modem firmware versions older than 1.3.0. Therefore we ignore error codes returned by `lte_lc_modem_events_enable` to prevent the application from rebooting. In case an older modem firmware version is used.

2022-11-23 13:56 UTC, maxd-nordic approved these changes
lgtm

2022-11-23 14:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9429
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-23 20:49 UTC, balaji-nordic requested changes

2022-11-23 20:49 UTC, balaji-nordic commented on applications/asset_tracker_v2/src/modules/modem_module.c
> +		LOG_WRN("Modem firmware versions older than 1.3.0 does not support "
```suggestion
		LOG_DBG("Modem firmware versions older than 1.3.0 do not support "
```

2022-11-24 06:54 UTC, hiltunent approved these changes

2022-11-24 10:50 UTC, balaji-nordic approved these changes

2022-11-25 10:25 UTC, merged