applications: asset_tracker_v2: impact detection: depend on adxl372
nrfconnect/sdk-nrf pull request #9453
Opened 2022-11-24 13:41 UTC by maxd-nordic

This patch makes CONFIG_EXTERNAL_SENSORS_IMPACT_DETECTION pull in the sensor driver as a dependency so it doesn't need to be explicitly specified.

Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

2022-11-24 13:43 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9453/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9453/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9453/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-24 13:43 UTC, simensrostad commented on applications/asset_tracker_v2/doc/sensor_module.rst
> -.. _CONFIG_EXTERNAL_SENSORS_IMPACT_DETECTION:
We still want this?

2022-11-24 14:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9453
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-24 15:01 UTC, coderbyheart approved these changes

2022-11-24 15:36 UTC, maxd-nordic commented on applications/asset_tracker_v2/doc/sensor_module.rst
> -.. _CONFIG_EXTERNAL_SENSORS_IMPACT_DETECTION:
right, removed this

2022-11-25 07:38 UTC, jtguggedal requested changes
The commit title should be changed to reflect that we now `select` the driver instead of using `depend on`

2022-11-25 08:31 UTC, simensrostad approved these changes

2022-11-25 08:40 UTC, jtguggedal approved these changes

2022-11-25 12:17 UTC, divipillai approved these changes

2022-11-25 13:26 UTC, merged