Propagate CONFIG_NFCT_PINS_AS_GPIOS to TF-M build
nrfconnect/sdk-nrf pull request #9457
Opened 2022-11-24 14:24 UTC by vili-nordic

Propagates CONFIG_NFCT_PINS_AS_GPIOS configuration to TF-M's build system.

Signed-off-by: Vidar Lillebø <vidar.lillebo@nordicsemi.no>

2022-11-24 14:27 UTC, joerchan commented
@vili-nordic Can you add the Jira ref in the commit message?

2022-11-24 14:28 UTC, joerchan approved these changes

2022-11-24 14:28 UTC, Rallare approved these changes

2022-11-24 14:28 UTC, joerchan requested changes
commit message must have "tfm: " in the title.

2022-11-24 14:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9457/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9457/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9457/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-24 15:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9457
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-25 09:09 UTC, joerchan approved these changes

2022-11-25 12:45 UTC, merged