wifi : Adds support for handling WIPHY capabilities, RX MLME frames
nrfconnect/sdk-nrf pull request #9476
Opened 2022-11-25 12:21 UTC by sr1dh48r

Adds support for handling WIPHY capabilities, RX MLME frames to fix the following MBO issues

SHEL-859 : Not able to send BTM response for the BTM request frame from the AP.
SHEL-888: Supported Operating classes IE missing in the Assoc Request frame.
SHEL-877: DUT not responding to AP beacon request frame using case 3 values

2022-11-25 12:23 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9476/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9476/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9476/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-28 06:53 UTC, sachinthegreen requested changes

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + *
Description for if_idx missing.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + *
Description for if_idx and frame_info missing.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +
Add defensive check for dev_ctx and if_idx.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +
Add defensive check for input parameters.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	for (count = 0; count < 29; count++) {
Can 29 be replaced by a macro?

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +
Add defensive check for sband. Also initialize band to all 0's.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	for (count = 0; count < 13; count++) {
Can 13 be replaced by a macro?

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	for (count = 0; count < 3; count++) {
Can 3 be replaced by a macro?

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +struct wpa_supp_event_supported_band
Did you mean to return a struct or a pointer to a struct? Better to take pointer to band as one more input parameter and return success/fail as return value.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	if (!if_priv) {
Also add checks for wiphy_info and event_len.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	if (status == WIFI_NRF_STATUS_FAIL) {
Better to have (status != WIFI_NRF_STATUS_SUCCESS) as a check.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	if (!if_priv) {
Please add checks for other input params too.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	if (status == WIFI_NRF_STATUS_FAIL) {
Better to have (status != WIFI_NRF_STATUS_SUCCESS) as a check.

2022-11-28 06:53 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
> +	if (!if_priv) {
Please add checks for other input params too.

2022-11-28 06:54 UTC, sachinthegreen commented
> Adds support for handling WIPHY capabilities, RX MLME frames to fix the following MBO issues
> 
> [SHEL-859] : Not able to send BTM response for the BTM request frame from the AP. [SHEL-888]: Supported Operating classes IE missing in the Assoc Request frame. [SHEL-877]: DUT not responding to AP beacon request frame using case 3 values

I believe the right prefix to be used is drivers: wifi:

2022-11-28 07:06 UTC, sachinthegreen commented
Please add Milestone as 2.2.0 and "bugfix" label.

2022-11-28 11:31 UTC, sr1dh48r commented
@rlubos  CI is failing at the following. I don't see the issue in local build though (unless I go out of bounds). Any idea if packed structure array need to be specially handled or how I can locally reproduce this ? 

9476/nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c: In function 'wifi_nrf_parse_sband':
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c:1168:62: error: iteration 26 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
 1168 |                 chan->wpa_supp_flags = sband->channels[count].nrf_wifi_flags;
      |                                        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c:1165:31: note: within this loop
 1165 |         for (count = 0; count < 29; count++) {
      |                         ~~~~~~^~~~
cc1: all warnings being treated as errors

2022-11-28 11:54 UTC, rlubos commented
> @rlubos CI is failing at the following. I don't see the issue in local build though (unless I go out of bounds). Any idea if packed structure array need to be specially handled or how I can locally reproduce this ?
> 
> 9476/nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c ../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c: In function 'wifi_nrf_parse_sband': ../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c:1168:62: error: iteration 26 invokes undefined behavior [-Werror=aggressive-loop-optimizations] 1168 | chan->wpa_supp_flags = sband->channels[count].nrf_wifi_flags; | ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~ ../../../../../nrf/drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c:1165:31: note: within this loop 1165 | for (count = 0; count < 29; count++) { | ~~~~~~^~~~ cc1: all warnings being treated as errors

I'd start by running all of the sample configurations with `twister` to get the same coverage as the CI.

Anyway, it seems that current code using hardcoded magic numbers could cause out-of-bound access for rev A?
https://github.com/nrfconnect/sdk-nrf/blob/main/drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw_A/host_rpu_umac_if.h#L3186

2022-11-29 10:02 UTC, sachinthegreen approved these changes

2022-11-29 10:17 UTC, krga2022 approved these changes

2022-12-09 09:58 UTC, merged