samples: wifi: Update command output and help
nrfconnect/sdk-nrf pull request #9495
Opened 2022-11-28 12:13 UTC by rado17

Update help text to provide information for TWT and power save commands in wifi shell.

Signed-off-by: Ravi Dondaputi <ravi.dondaputi@nordicsemi.no>

2022-11-28 12:15 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9495/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9495/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-28 12:56 UTC, sachinthegreen approved these changes

2022-11-28 12:59 UTC, sachinthegreen commented
Please add reference to the Jira bug which this PR solves.

2022-11-28 12:59 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9495
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-28 14:21 UTC, richabp requested changes

2022-11-28 14:21 UTC, richabp commented on samples/wifi/shell/README.rst
> +       |
```suggestion
```

2022-11-28 14:21 UTC, richabp commented on samples/wifi/shell/README.rst
> +       |          <setup_cmd: 0: Request, 1: Suggest, 2: Demand>
```suggestion
       | setup - Start a TWT flow:
       |          <negotiation_type: 0 - Individual, 1 - Broadcast, 2 - Wake TBTT>
       |          <setup_cmd: 0 - Request, 1 - Suggest, 2 - Demand>
```

2022-11-28 14:21 UTC, richabp commented on samples/wifi/shell/README.rst
> +       |          <setup_cmd: 0: Request, 1: Suggest, 2: Demand>
```suggestion
       | teardown - Teardown a TWT flow:
       |            <negotiation_type: 0 - Individual, 1 - Broadcast, 2 - Wake TBTT>
       |            <setup_cmd: 0 - Request, 1 - Suggest, 2 - Demand>
```

2022-11-28 14:23 UTC, richabp requested changes

2022-11-29 07:25 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       | off - Turns off power save
Options mentioned here are in small-case and the suggested options are not accepted by the command.

2022-11-29 07:35 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       | off - Turns off power save
Included other suggested changes.

2022-11-29 07:35 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       |
Removed the suggested lines.

2022-11-29 07:36 UTC, rado17 commented on samples/wifi/shell/README.rst
> +     - | Manage TWT flows
Done

2022-11-29 07:36 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       |          <setup_cmd: 0: Request, 1: Suggest, 2: Demand>
Done,

2022-11-29 07:37 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       |          <setup_cmd: 0: Request, 1: Suggest, 2: Demand>
Done

2022-11-29 07:37 UTC, rado17 commented on samples/wifi/shell/README.rst
> +       | teardown_all  : Teardown all TWT flows
Done.

2022-11-29 10:18 UTC, richabp approved these changes

2022-11-29 10:39 UTC, nordicjm requested changes
Marking as -1 because of doc-required tag and no doc approval and no one from doc team in review list

2022-11-29 10:42 UTC, rado17 commented
> Marking as -1 because of doc-required tag and no doc approval and no one from doc team in review list

It has been approved by @richabp.  Do we need to tag anybody else?

2022-11-29 10:44 UTC, nordicjm commented
> It has been approved by @richabp. Do we need to tag anybody else?

Someone in https://github.com/orgs/nrfconnect/teams/ncs-doc-owners/members

2022-11-29 11:19 UTC, nordicjm approved these changes

2022-11-29 11:19 UTC, merged