Bluetooth: Mesh: Update light FOTA docs platforms
nrfconnect/sdk-nrf pull request #9499
Opened 2022-11-28 13:16 UTC by Andrewpini

It has been discovered that the nrf52832 and nrf52833 platforms can not fit the overlay configuration into flash, thus they have been removed from the supported platforms in the docs.

Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

2022-11-28 13:18 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9499/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9499/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-28 13:28 UTC, Balaklaka commented on samples/bluetooth/mesh/light/README.rst
> +While this overlay configuration is only applicable for the mentioned platforms in this sample, DFU over Bluetooth Low Energy may be utilized on other platforms as well.
```suggestion
While this overlay configuration is only applicable for the mentioned platforms in this sample, DFU over Bluetooth Low Energy may be utilized on other platforms as well. When doing that the flash size need to be taken into consideration, as both the nRF52832 and the nRF52833 has somewhat limited flash size.
```

2022-11-28 13:56 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9499
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-29 10:11 UTC, Balaklaka approved these changes

2022-11-30 07:35 UTC, peknis requested changes

2022-11-30 07:35 UTC, peknis commented on samples/bluetooth/mesh/light/README.rst
> +While this overlay configuration is only applicable for the mentioned platforms in this sample, DFU over Bluetooth Low Energy may be utilized on other platforms as well.
```suggestion
While this overlay configuration is only applicable for the mentioned platforms in this sample, DFU over Bluetooth Low Energy may be used on other platforms as well.
```

2022-11-30 07:35 UTC, peknis commented on samples/bluetooth/mesh/light/README.rst
> +Take the flash size into consideration when utilizing DFU over Bluetooth LE on other platforms.
```suggestion
Take the flash size into consideration when using DFU over Bluetooth LE on other platforms.
```

2022-11-30 07:47 UTC, mia-ko approved these changes

2022-11-30 07:48 UTC, peknis approved these changes

2022-11-30 13:07 UTC, merged