doc improvement: Minor updates to Lib carrier docs
nrfconnect/sdk-nrf pull request #9510
Opened 2022-11-29 10:42 UTC by divipillai

Minor updates to Lib carrier docs

Signed-off-by: divya <divya.pillai@nordicsemi.no>

2022-11-29 11:50 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9510/8/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9510/8/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-29 11:58 UTC, umapraseeda requested changes

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
>    * For example, If you are deploing a product in several networks but only need to enable the carrier library within Verizon, you must set :kconfig:option:`CONFIG_LWM2M_CARRIER_VERIZON` to ``y`` and
```suggestion
  * For example, If you are deploying a product in several networks but only need to enable the carrier library within Verizon, you must set :kconfig:option:`CONFIG_LWM2M_CARRIER_VERIZON` to ``y`` and all the others to ``n``.
```

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
> +    It can also be be triggered when the application calls :c:func:`lwm2m_carrier_request`.
```suggestion
    It can also be triggered when the application calls :c:func:`lwm2m_carrier_request`.
```

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
> +    It can also be be triggered when the application calls :c:func:`lwm2m_carrier_request`.
```suggestion
    It can also be triggered when the application calls :c:func:`lwm2m_carrier_request`.
```

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
>    * These configurations allows you to choose the networks in which the carrier library will apply.
```suggestion
  * These configurations allow you to choose the networks in which the carrier library will apply.
```

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
>    * This configurations lets you choose between using the nRF9160 SoC 2DID Serial Number, or the Device IMEI as a Serial Number when connecting to the LG U+ device management server.
```suggestion
  * This configuration lets you choose between using the nRF9160 SoC 2DID Serial Number, or the device IMEI as a serial number when connecting to the LG U+ device management server.
```

2022-11-29 11:58 UTC, umapraseeda commented on doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
> +  * It occur during the bootstrapping process, startup and FOTA.
```suggestion
  * It occurs during the bootstrapping process, startup, and FOTA.
```

2022-11-29 12:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9510
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-29 14:03 UTC, nordic-hani approved these changes
Looks good to me. ✔

2022-11-30 10:20 UTC, divipillai commented on doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
>  * Added the function :c:func:`lwm2m_carrier_request`
Lines 125-127 are definitions, as confirmed by @nordic-hani. I made the necessary changes to the documents. 

2022-11-30 11:55 UTC, umapraseeda approved these changes

2022-11-30 12:26 UTC, merged