applications: asset_tracker_v2: Add link to survey
nrfconnect/sdk-nrf pull request #9513
Opened 2022-11-29 12:20 UTC by simensrostad

Add link to survey that will be used to collect feedback from users of the application.

2022-11-29 13:08 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9513
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-30 08:46 UTC, jhn-nordic approved these changes
Great initiative! Will give very valuable information to the team

2022-11-30 08:51 UTC, coderbyheart approved these changes

2022-11-30 08:51 UTC, coderbyheart commented on applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst
> +   Please help improve the Asset Tracker v2 by answering a few questions from the developer team, `Asset Tracker v2 survey`_.
```suggestion
   Please help improve the Asset Tracker v2 by answering a few questions from the developer team: `Asset Tracker v2 survey`_.
```

2022-12-01 13:37 UTC, divipillai requested changes
As discussed in the meeting, blocking the PR.

2023-03-23 14:25 UTC, closed without merging