docs: wifi: Update release notes
nrfconnect/sdk-nrf pull request #9517
Opened 2022-11-29 16:11 UTC by rado17

Update release notes with shell sample additions.

Signed-off-by: Ravi Dondaputi <ravi.dondaputi@nordicsemi.no>

2022-11-29 16:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9517/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9517/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-29 16:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9517
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-30 07:13 UTC, sachinthegreen approved these changes

2022-11-30 08:03 UTC, bama-nordic approved these changes

2022-11-30 08:32 UTC, richabp requested changes

2022-11-30 08:32 UTC, richabp commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Configuration support for Wi-Fi power save.
```suggestion
    * Configuration support for the Wi-Fi power saving feature.
```

2022-11-30 08:47 UTC, umapraseeda commented
We could close this as I have updated this in the release notes PR: https://github.com/nrfconnect/sdk-nrf/pull/9519/files#diff-c6e55e7fc79eba9ae43df6e8d82b4368555c3445592d544aeb4d9e2d6dee9c6aR484

2022-11-30 09:22 UTC, closed without merging