doc: provide THCI file for Thread 1.3 Certification testing
nrfconnect/sdk-nrf pull request #9528
Opened 2022-11-30 12:41 UTC by edmont

Thread Test Harness issues require incompatible APIs to be used in THCI files for Thread 1.3 testing. Providing here the apropriate file for such DUT.

Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

2022-11-30 12:47 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9528/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9528/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-thread | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9528/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-11-30 12:54 UTC, canisLupus1313 approved these changes

2022-11-30 12:57 UTC, wiba-nordic requested changes

2022-11-30 12:57 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +   c. Copy an image of your choice to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK.jpg` and to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK_1_3.jpg`.
```suggestion
   c. Copy images of your choice to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK.jpg` and :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK_1_3.jpg`.
   You can use the same image for both.
```

2022-11-30 13:01 UTC, canisLupus1313 commented
@edmont seems that Linter complains about python 2 style `print`.
``` 
************* Module nRF_Connect_SDK_1_3
samples/openthread/cli/harness-tchi-1-3/nRF_Connect_SDK_1_3.py:3467:9: E0001: Missing parentheses in call to 'print'. Did you mean print(...)? (<unknown>, line 3467) (syntax-error)
Error: Process completed with exit code 1.
```

2022-11-30 13:06 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +   c. Copy images of your choice to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK.jpg` and to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK_1_3.jpg`.
```suggestion
   c. Copy images of your choice to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK.jpg` and :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK_1_3.jpg`.
   You can use the same image for both.
```
Missed the added new line.

2022-11-30 13:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9528
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-11-30 13:51 UTC, edmont commented on doc/nrf/ug_thread_certification.rst
> +   c. Copy images of your choice to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK.jpg` and to :file:`C:\\GRL\\Thread1.2\\Web\\images\\nRF_Connect_SDK_1_3.jpg`.
Fixed, thanks.

2022-11-30 13:52 UTC, wiba-nordic approved these changes

2022-12-01 05:33 UTC, wiba-nordic commented on doc/nrf/ug_thread_certification.rst
> +   You can use the same image for both.
```suggestion
     You can use the same image for both.
```
One more little thing. That was my bad, I gave you the wrong indentation.

2022-12-01 08:28 UTC, merged