Bluetooth: Mesh: Update DM server docs
nrfconnect/sdk-nrf pull request #9538
Opened 2022-11-30 16:05 UTC by Andrewpini

Adds description of the distance measurement procedure to the Distance Measurement Server documentation.

Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

2022-11-30 16:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9538/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9538/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-11-30 16:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9538
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-01 12:41 UTC, Balaklaka approved these changes

2022-12-01 12:50 UTC, alxelax commented on doc/nrf/libraries/bluetooth_services/mesh/vnd/dm_srv.rst
> +A Distance measurement procedure is started by issuing a ``bt_mesh_dm_cli_measurement_start`` message from a Distance Measurement Client. Within this message the caller must define the target address
test

2022-12-01 13:31 UTC, mia-ko requested changes

2022-12-01 13:31 UTC, mia-ko commented on doc/nrf/libraries/bluetooth_services/mesh/vnd/dm_srv.rst
> +   Due to size restrictions in the result message format, measurements exceeding 65535 centimeters (UINT16_MAX) will be floored to 65535 centimeters. E.g. any client receiving a result with a value s
```suggestion
If the ranging procedure fails, the result is still stored on both servers.
The DM SRV 1 sends the result entry as a response to the client, indicating that something went wrong during the procedure.

.. note::
   Due to size restrictions in the result message format, measurements exceeding 65535 centimeters (UINT16_MAX) will be floored to 65535 centimeters.
   Clients receiving results with values set to 65535 should interpret the result as 65535 centimeters **or higher**.
```

2022-12-01 13:34 UTC, Andrewpini commented on doc/nrf/libraries/bluetooth_services/mesh/vnd/dm_srv.rst
> +   :align: center
It is a draw.io export

2022-12-05 11:13 UTC, mia-ko requested changes

2022-12-06 14:24 UTC, mia-ko approved these changes

2022-12-06 14:54 UTC, merged