script: fix likely_merged heuristic
nrfconnect/sdk-nrf pull request #9546
Opened 2022-12-01 10:01 UTC by karhama

Attempt to fix heuristic #2 so that it could find a match.

Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>

2022-12-01 10:03 UTC, karhama commented
For reference currently heuristics fails with e.g. these commits: 
https://github.com/nrfconnect/sdk-zephyr/commit/f833a2e53ecae8f759fcedeeb4b895b09cbb042d
https://github.com/zephyrproject-rtos/zephyr/commit/c32ee7199fad670d6f7051a9eebf9d97d9eeb4b4

2022-12-01 11:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9546
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-01 15:39 UTC, mbolivar-nordic requested changes
Please justify why this is a correction in the commit message. An example would be helpful as well.

2022-12-02 07:57 UTC, karhama commented
> Please justify why this is a correction in the commit message. An example would be helpful as well.

when debugging the code there are these two strings (see links above):
commit_shortlog(uc) = "Bluetooth: Mesh: Filter out unknown conns and disconns in pb-gatt srv" - from upstream
sl = "[nrf fromtree] Bluetooth: Mesh: Filter out unknown conns and disconns..."   - from downstream

old code says:
commit_shortlog(uc).startswith(sl) --> based on my understanding this is never true because of [nrf ...] in sl string. 

[:-3] is just to allow some room for extra characters in case user uses e.g. "..."

2022-12-02 21:43 UTC, mbolivar-nordic commented
> > Please justify why this is a correction in the commit message. An example would be helpful as well.
> 
> when debugging the code there are these two strings (see links above): commit_shortlog(uc) = "Bluetooth: Mesh: Filter out unknown conns and disconns in pb-gatt srv" - from upstream sl = "[nrf fromtree] Bluetooth: Mesh: Filter out unknown conns and disconns..." - from downstream
> 
> old code says: commit_shortlog(uc).startswith(sl) --> based on my understanding this is never true because of [nrf ...] in sl string.
> 
> [:-3] is just to allow some room for extra characters in case user uses e.g. "..."

Please get into the habit of putting this sort of thing into the commit log, not github messages. The commit log is the permanent record of why changes were introduced, and this information should be there too.

2022-12-02 21:44 UTC, mbolivar-nordic commented
> [:-3] is just to allow some room for extra characters in case user uses e.g. "..."

Users shouldn't be doing this anymore, though. We should address this at the next rebase time. That should be covered by the edit distance heuristic at any rate.

We only needed '...' when the sauce tag itself was counted against the line length limit for the shortlog. That is no longer required so we don't need to use '...' anymore, and we should be fixing this in our downstream commit logs.

2022-12-08 11:44 UTC, thst-nordic commented
I took over this PR for Kari. 

I updated the commit message as said above, and added a target_branch change that was requested by @carlescufi 

Please merge if not changes needed, and notify @de-nordic so he can continue his work.

2022-12-09 11:00 UTC, thst-nordic commented
I've removed my target branch commit in anticipation of this being closed. 
New location: https://github.com/nrfconnect/sdk-nrf/pull/9644

2023-01-13 23:30 UTC, mbolivar-nordic commented
@de-nordic @thst-nordic I believe this "fix" is no longer necessary. Please see https://github.com/nrfconnect/action-oss-history/pull/6 and in particular the commit log for `action.py: forbid trailing '...' in shortlogs`.

With that merged, I think we shouldn't have any more `...` to deal with in this heuristic, so this patch is likely not needed.

Please LMK if I missed something.

2023-01-16 07:57 UTC, karhama commented
> @de-nordic @thst-nordic I believe this "fix" is no longer necessary. Please see [nrfconnect/action-oss-history#6](https://github.com/nrfconnect/action-oss-history/pull/6) and in particular the commit log for `action.py: forbid trailing '...' in shortlogs`.
> 
> With that merged, I think we shouldn't have any more `...` to deal with in this heuristic, so this patch is likely not needed.
> 
> Please LMK if I missed something.

AFAIK there are supposed to be two heuristics in use (based on code comments). However heuristic 2 will never activate without **shortlog_no_sauce** introduced in this PR. For me it looks just a small bug in heuristic 2. However it is possible that heuristic 2 is not needed in the first place but then it would be probably more clean to remove such heuristic and comments.

2023-04-04 01:44 UTC, closed without merging