doc: change the structure of doc files
nrfconnect/sdk-nrf pull request #9561
Opened 2022-12-02 00:44 UTC by b-gent

Reorganizing the doc/nrf folder to make it easier to locate specific RST files whenever they need modification.

The folder now has a clear structure of subfolders rather than having most of the files on the main level.

Signed-off-by: Bartosz Gentkowski <bartosz.gentkowski@nordicsemi.no>

2022-12-02 00:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9561/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9561/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-12-05 14:47 UTC, gmarull requested changes
I think this still needs another round of simplification. For example, all `ug_`, `app_` prefixes should be deleted. Some other names shortened (remember they end up being URLs), e.g. `protocols/ble/bt_mesh/ug_bt_mesh.rst` -> `protocols/ble/mesh/index.rst`, `protocols/ble/bt_mesh/ug_bt_mesh_concepts.rst` -> `protocols/ble/mesh/concepts.rst`

2022-12-22 13:54 UTC, umapraseeda commented
@b-gent, Added the commit for the wrapper page.

2023-01-19 08:30 UTC, tomchy approved these changes

2023-01-24 07:43 UTC, erikrobstad requested changes
The Audio DK images should not be there.
Maybe a rebase gone wrong?

2023-01-24 07:53 UTC, greg-fer requested changes
Two things:
- The reintroduced "nrf5340_audio_dk" images should be removed. These were removed in a recent PR to sdk-nrf, so most likely your rebase didn't catch them.
- I know @gmarull mentioned shortening the names of some files, but this led to file names like "dcl.rst" or "dfu.rst" for Matter. DCL (Distributed Compliance Ledger) is a CSA database that could be potentially used by other protocols, while DFU is a more broad concept. Thus, there might be more pages named like this in other parts of the doc. Are we ok with that?

2023-01-24 08:15 UTC, b-gent commented
> Two things:
> 
> * The reintroduced "nrf5340_audio_dk" images should be removed. These were removed in a recent PR to sdk-nrf, so most likely your rebase didn't catch them.
> * I know @gmarull mentioned shortening the names of some files, but this led to file names like "dcl.rst" or "dfu.rst" for Matter. DCL (Distributed Compliance Ledger) is a CSA database that could be potentially used by other protocols, while DFU is a more broad concept. Thus, there might be more pages named like this in other parts of the doc. Are we ok with that?

The idea is that file path is part of the file name. So yes, there are now a few files called dfu.rst but you can tell by their path what protocol/user guide they belong to. It's a situation similar to our sample files - they are all called README.rst and that's ok because they are identified by their location in the folder structure.

2023-02-01 09:09 UTC, b-gent commented on doc/nrf/protocols/bt_mesh/vendor_model/vendor_model_chat_sample_walk_through.rst
> -.. literalinclude:: ../../samples/bluetooth/mesh/chat/include/chat_cli.h
no, will fix

2023-02-01 09:09 UTC, b-gent commented on doc/nrf/protocols/bt_mesh/vendor_model/vendor_model_dev_overview.rst
> -.. figure:: /images/bt_mesh_model_callbacks.svg
no, will fix

2023-02-01 16:49 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9561
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-02-02 12:30 UTC, b-gent commented
> The Audio DK images should not be there. Maybe a rebase gone wrong?

These are now removed.

2023-02-07 07:14 UTC, peknis requested changes

2023-02-07 07:14 UTC, peknis commented on doc/nrf/ecosystem_integration.rst
> +* Apple FindMy
A
```suggestion
* Apple Find My
```

2023-02-07 07:14 UTC, peknis commented on doc/nrf/ecosystem_integration.rst
> +In the case of HomeKit and FindMy, MFi licensees can get access to the repository by issuing a Nordic `DevZone`_ private ticket.
```suggestion
In the case of HomeKit and FindMy, MFi licensees can get access to the repository by issuing a Nordic `DevZone`_ private ticket.
```
```suggestion
In the case of HomeKit and Find My, MFi licensees can get access to the repository by issuing a Nordic `DevZone`_ private ticket.
```

2023-02-07 13:09 UTC, umapraseeda commented
Now since https://github.com/nrfconnect/sdk-nrf/pull/10182 is merged, we might need another PR in nrfxlib to remove the Visio source files there.

2023-02-07 13:12 UTC, gautesl approved these changes

2023-02-07 14:46 UTC, umapraseeda commented
For [doc/nrf/app_power_opt.rst → doc/nrf/app_dev/optimizing/power_opt.rst](https://github.com/nrfconnect/sdk-nrf/pull/9561/files#diff-477f63e7ee0615ac9d66ca84b7213eb2753acaa1825aaf3c888e54bc6227defd) , do we need the _opt suffix for the new file name?

2023-02-07 14:51 UTC, gmarull approved these changes
overall lgtm, tested a few redirects and they work as expected

2023-02-07 15:12 UTC, umapraseeda commented
doc/nrf/images/ncs-west-repos.png → doc/nrf/developing/images/ncs-west-repos.png. I don't think this PNG image is being used. There is a svg equivalent that is used in the docs.

2023-02-07 15:18 UTC, umapraseeda commented on doc/nrf/ecosystem_integration.rst
> +The following user guides describe the integration of various eco systems and tools with |NCS|.
```suggestion
The following user guides describe the integration of various ecosystems and tools with |NCS|.
```

2023-02-07 15:20 UTC, umapraseeda commented on doc/_utils/redirects.py
> +	("ug_memfault", "external_comp/memfault"),
```suggestion
    ("ug_edge_impulse", "external_comp/edge_impulse"),
    ("ug_memfault", "external_comp/memfault"),
```

2023-02-07 18:42 UTC, umapraseeda commented
[ /images/matter_components_DM_doorlock.svg → .../images/matter_components_DM_doorlock.svg ](https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9561/nrf/protocols/matter/overview/data_model.html#data-model-example-door-lock) is missing the caption.

2023-02-07 19:06 UTC, umapraseeda commented
Under protocols\thread\overview\images\, ot-arch_2x.svg (the PNG version is used), thread_platform_design_nRF53.odg and thread_platform_design_nRF53_multi.odg are not used anywhere. May be we can remove these.

2023-02-07 19:15 UTC, umapraseeda commented on doc/_utils/redirects.py
> +    ("ug_zigbee_commissioning","protocols/zigbee/commisioning"),
```suggestion
    ("ug_zigbee_commissioning","protocols/zigbee/commissioning"),
```

2023-02-08 06:48 UTC, peknis requested changes

2023-02-08 06:48 UTC, peknis commented on doc/nrf/ecosystem_integration.rst
> +* Apple FindMy
Not fixed yet.

2023-02-08 06:48 UTC, peknis commented on doc/nrf/ecosystem_integration.rst
> +In the case of HomeKit and FindMy, MFi licensees can get access to the repository by issuing a Nordic `DevZone`_ private ticket.
Not fixed yet.

2023-02-08 07:23 UTC, mia-ko approved these changes

2023-02-08 09:21 UTC, erikrobstad approved these changes

2023-02-09 09:59 UTC, b-gent commented on doc/nrf/ecosystem_integration.rst
> +* Apple FindMy
fixed

2023-02-09 10:00 UTC, b-gent commented on doc/nrf/ecosystem_integration.rst
> +In the case of HomeKit and FindMy, MFi licensees can get access to the repository by issuing a Nordic `DevZone`_ private ticket.
fixed

2023-02-09 10:00 UTC, b-gent commented on doc/nrf/ecosystem_integration.rst
> +The following user guides describe the integration of various eco systems and tools with |NCS|.
fixed

2023-02-09 10:02 UTC, b-gent commented
> Under protocols\thread\overview\images, ot-arch_2x.svg (the PNG version is used), thread_platform_design_nRF53.odg and thread_platform_design_nRF53_multi.odg are not used anywhere. May be we can remove these.

removed

2023-02-09 10:06 UTC, b-gent commented
> doc/nrf/images/ncs-west-repos.png → doc/nrf/developing/images/ncs-west-repos.png. I don't think this PNG image is being used. There is a svg equivalent that is used in the docs.

removed

2023-02-09 10:08 UTC, b-gent commented
> For [doc/nrf/app_power_opt.rst → doc/nrf/app_dev/optimizing/power_opt.rst](https://github.com/nrfconnect/sdk-nrf/pull/9561/files#diff-477f63e7ee0615ac9d66ca84b7213eb2753acaa1825aaf3c888e54bc6227defd) , do we need the _opt suffix for the new file name?

suffix removed

2023-02-09 10:08 UTC, peknis approved these changes

2023-02-09 10:12 UTC, b-gent commented
> [ /images/matter_components_DM_doorlock.svg → .../images/matter_components_DM_doorlock.svg ](https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9561/nrf/protocols/matter/overview/data_model.html#data-model-example-door-lock) is missing the caption.

corrected in data_model.rst

2023-02-09 10:12 UTC, wiba-nordic approved these changes
Looked through the Thread section an didn't notice anything wrong. Nice job!

2023-02-09 10:33 UTC, b-gent commented on doc/_utils/redirects.py
> +    ("ug_zigbee_commissioning","protocols/zigbee/commisioning"),
corrected

2023-02-09 10:33 UTC, b-gent commented on doc/_utils/redirects.py
> +	("ug_memfault", "external_comp/memfault"),
corrected

2023-02-09 11:27 UTC, umapraseeda commented on doc/_utils/redirects.py
> +    ("app_power_opt", "app_dev/optimizing/power_opt"),
since we renamed the file 
```suggestion
    ("app_power_opt", "app_dev/optimizing/power"),
```

2023-02-09 11:29 UTC, b-gent commented on doc/_utils/redirects.py
> +    ("app_power_opt", "app_dev/optimizing/power_opt"),
right, thanks :)

2023-02-09 11:32 UTC, umapraseeda commented
Also, there is one file ncs-west-repos.xml in the images folder. Not sure if that is required.

2023-02-09 11:33 UTC, umapraseeda approved these changes
LGTM! Thanks!

2023-02-09 11:40 UTC, b-gent commented
> Also, there is one file ncs-west-repos.xml in the images folder. Not sure if that is required.

not sure either, removed

2023-02-10 06:57 UTC, richabp approved these changes

2023-02-10 08:11 UTC, annwoj approved these changes

2023-02-10 08:44 UTC, merged