doc: update Matter known issues for 2.2.0
nrfconnect/sdk-nrf pull request #9581
Opened 2022-12-02 14:42 UTC by markaj-nordic

Added a description of a bug in the Android CHIP Tool. This affects 2.1.1 and 2.1.2 releases as well.

Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>

2022-12-02 14:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9581/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9581/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-12-02 15:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9581
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-05 06:18 UTC, kkasperczyk-no approved these changes

2022-12-05 07:10 UTC, greg-fer requested changes
Aren't we talking about two clusters here? Couldn't find one called "Light On/Off & Level" in the dev lib spec.

2022-12-05 07:10 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +KRKNWK-15846: Android CHIP Tool crashes when subscribing in the Light On/Off & Level Cluster
```suggestion
KRKNWK-15846: Android CHIP Tool crashes when subscribing to the Light On/Off and Level Clusters
```

2022-12-05 07:10 UTC, greg-fer commented on doc/nrf/known_issues.rst
> +  Also, the Subscription window in the Light On/Off & Level Cluster contains faulty GUI layout (overlapping captions) used when passing minimum and maximum subscription interval values.
```suggestion
  The Android CHIP Tool crashes when attempting to start the subscription after typing minimum and maximum subscription interval values.
  Also, the Subscription window in the Light On/Off and Level Clusters contains faulty GUI layout (overlapping captions) used when passing minimum and maximum subscription interval values.
  This affects the Android CHIP Tool revision used for the |NCS| v2.2.0, v2.1.1, and v2.1.2 releases.
```

2022-12-05 07:51 UTC, markaj-nordic commented
> Aren't we talking about two clusters here? Couldn't find one called "Light On/Off & Level" in the dev lib spec.

This is the Android CHIP Tool denomination, the section of the GUI is called "LIGHT ON/OFF & LEVEL CLUSTER", so I sticked to this one. Anyway, I don't have a strong opinion on that. What do others think about it? @kkasperczyk-no, @Damian-Nordic, any suggestions?

2022-12-05 10:10 UTC, Damian-Nordic commented
> > Aren't we talking about two clusters here? Couldn't find one called "Light On/Off & Level" in the dev lib spec.
> 
> This is the Android CHIP Tool denomination, the section of the GUI is called "LIGHT ON/OFF & LEVEL CLUSTER", so I sticked to this one. Anyway, I don't have a strong opinion on that. What do others think about it? @kkasperczyk-no, @Damian-Nordic, any suggestions?

Well, it all depends on what we want to convey. If we're referring to the screen of the CHIPTool app (which is fine with me), we should use the name of the screen (using capital letters, perhaps).

2022-12-05 10:13 UTC, markaj-nordic commented
> > > Aren't we talking about two clusters here? Couldn't find one called "Light On/Off & Level" in the dev lib spec.
> > 
> > 
> > This is the Android CHIP Tool denomination, the section of the GUI is called "LIGHT ON/OFF & LEVEL CLUSTER", so I sticked to this one. Anyway, I don't have a strong opinion on that. What do others think about it? @kkasperczyk-no, @Damian-Nordic, any suggestions?
> 
> Well, it all depends on what we want to convey. If we're referring to the screen of the CHIPTool app (which is fine with me), we should use the name of the screen (using capital letters, perhaps). Otherwise, there's no such thing as "Light On/Off" cluster. There's only "On/Off" cluster.

Ok, so let me keep the Android CHIP Tool naming but apply remarks from @greg-fer in parallel.

2022-12-05 10:41 UTC, greg-fer commented
@markaj-nordic , edited my comments.

2022-12-05 10:53 UTC, greg-fer approved these changes

2022-12-05 11:27 UTC, merged