Bluetooth: Mesh: Remove model_send and model_ackd_send
nrfconnect/sdk-nrf pull request #9582
Opened 2022-12-02 16:45 UTC by PavelVPV

Remove `model_ackd_send` and `model_send` from model_utils.c as they are implemented in upstream in msg.c as `bt_mesh_msg_ackd_send` and `bt_mesh_msg_send` accordingly.

Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>

2022-12-02 16:46 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9582/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9582/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble_mesh | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9582/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-02 17:17 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9582
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-05 14:19 UTC, Andrewpini requested changes

2022-12-05 14:19 UTC, Andrewpini commented on subsys/bluetooth/mesh/gen_loc_cli.c
> +	return bt_mesh_msg_ackd_send(cli->model, ctx, &msg, rsp ? rsp_ctx : NULL);
```suggestion
	return bt_mesh_msg_ackd_send(cli->model, ctx, &msg, rsp ? &rsp_ctx : NULL);
```
?

2022-12-05 14:19 UTC, Andrewpini commented on subsys/bluetooth/mesh/light_ctl_cli.c
> +	return bt_mesh_msg_ackd_send(cli->model, ctx, &buf, rsp ? &rsp_ctx : NULL);
```suggestion
	return bt_mesh_msg_ackd_send(cli->model, ctx, &msg, rsp ? &rsp_ctx : NULL);
```
? Applies several places in this file

2022-12-05 14:19 UTC, Andrewpini commented on subsys/bluetooth/mesh/light_hsl_cli.c
> +		.op = BT_MESH_LIGHT_HSL_OP_HUE_STATUS,
```suggestion
		.op = BT_MESH_LIGHT_HUE_OP_STATUS,
```
?

2022-12-05 14:19 UTC, Andrewpini commented on subsys/bluetooth/mesh/light_hsl_cli.c
> +		.op = BT_MESH_LIGHT_HSL_OP_SAT_STATUS,
```suggestion
		.op = BT_MESH_LIGHT_SAT_OP_STATUS,
```
?

2022-12-05 14:19 UTC, Andrewpini commented on subsys/bluetooth/mesh/scene_cli.c
>  			       BT_MESH_SCENE_OP_REGISTER_STATUS, rsp);
Seems to miss full refactor here. Too many args.

2022-12-06 08:22 UTC, Andrewpini approved these changes

2022-12-06 09:48 UTC, Andrewpini requested changes
Adding `${ZEPHYR_BASE}/subsys/bluetooth` [here](https://github.com/nrfconnect/sdk-nrf/blob/65c56fb519122aa5117da2efcaf66d2d16fad6f0/tests/subsys/bluetooth/mesh/silvair_enocean_model/CMakeLists.txt#L21-L24) seems to make the enocean test build at least

2022-12-06 13:26 UTC, Andrewpini approved these changes

2022-12-12 15:15 UTC, akredalen approved these changes

2022-12-13 09:04 UTC, ludvigsj approved these changes

2023-01-09 15:37 UTC, merged