SPM: Remove SPM from NCS
nrfconnect/sdk-nrf pull request #9586
Opened 2022-12-04 10:43 UTC by joerchan

Remove SPM and secure services
Remove documentation of SPM and secure services
Remove SPM noup patches in sdk-zephyr
Remove SPM support in the entropy driver.

Document that SPM has been removed from NCS.

2022-12-04 10:44 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/c0689b16ff127d1b71a4cc20310d476e1807e26e (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1005 | [nrfconnect/sdk-zephyr#1005/files](https://github.com/nrfconnect/sdk-zephyr/pull/1005/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-12-04 10:45 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9586/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9586/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9586/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-04 20:44 UTC, hakonfam requested changes
We should remove from all partition manager configs as well 
![image](https://user-images.githubusercontent.com/1547348/205514503-2160b1db-ac76-4095-bc97-9461aa85d020.png)

There is also this:
![image](https://user-images.githubusercontent.com/1547348/205514521-6982d809-12e2-448c-9164-27a400ecf094.png)

and this 
![image](https://user-images.githubusercontent.com/1547348/205514552-85f49863-bd1e-4c02-8c4c-2762e15ba5d3.png)

2022-12-05 18:43 UTC, plskeggs approved these changes

2022-12-05 21:14 UTC, hakonfam approved these changes

2022-12-06 08:51 UTC, simensrostad approved these changes

2022-12-06 19:24 UTC, glarsennordic approved these changes
LGTM

2022-12-09 12:02 UTC, gregersrygg approved these changes

2022-12-09 12:26 UTC, sigvartmh approved these changes

2022-12-12 13:33 UTC, mia-ko requested changes
What about samples\bootloader\pm.yml?

2022-12-12 13:57 UTC, joerchan commented on doc/nrf/releases/release-notes-1.0.0.rst
> +    * Secure Partition Manager (SPM)
This was a search replace, `lib_spm` would have been replaced with this text.

2022-12-12 14:19 UTC, rlubos commented on west.yml
> +      revision: pull/1005/head
Please update SHA: `8fb465f43f6a90ac4c4ce89265047e04f7d5ee5b`

2022-12-12 21:27 UTC, mia-ko requested changes
Just one tiny thing I missed in the first round...

And one more thing. I found some SPM related stuff in sample_boardnames.txt (in doc\nrf\includes\boardname_tables), see line 268-281... I'm thinking we could remove this as well :)

2022-12-12 21:27 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +    The Secure Partition Manager (SPM) was deprecated in |NCS| 2.1.0 and removed in |NCS| v2.3.0, it is replaced by :ref:`Trusted Firmware-M (TF-M) <ug_tfm>`.
Sorry, I missed this one in the first round. It's better to split it in two sentences.
```suggestion
    The Secure Partition Manager (SPM) was deprecated in |NCS| 2.1.0 and removed in |NCS| v2.3.0. It is replaced by :ref:`Trusted Firmware-M (TF-M) <ug_tfm>`.
```

2022-12-13 09:58 UTC, mia-ko approved these changes

2022-12-13 11:31 UTC, merged