applications: machine_learning: Pass chosen pm-ext-flash to mcuboot
nrfconnect/sdk-nrf pull request #9593
Opened 2022-12-05 14:28 UTC by MarekPieta

Change explicitly passes the chosen pm-ext-flash to the mcuboot child image. This is needed to allow MCUboot access external FLASH during the DFU.

Jira: NCSDK-18532

2022-12-05 14:30 UTC, kapi-no approved these changes
Consider linking the commit in the commit message when this operation was done tree wide for other projects

2022-12-05 14:33 UTC, nordicjm approved these changes

2022-12-05 15:03 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9593
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-05 15:12 UTC, tejlmand requested changes
isn't this handled by this PR ?
https://github.com/nrfconnect/sdk-zephyr/pull/994/files

2022-12-05 15:14 UTC, tejlmand approved these changes
approved, as this is required for 2.2, whereas https://github.com/nrfconnect/sdk-zephyr/pull/994 is after release

2022-12-06 10:43 UTC, nordicjm commented
Removing 2.2.0 label as requested. This can probably be fixed by the alternative PR instead to fix it for all applications instead, at this point.

2022-12-06 11:05 UTC, MarekPieta commented
Hi @nordicjm,
I fixed this only in the machine learning's Thingy:53 configurations to limit scope of the change. Adding this for Thingy:53 board in general would affect more samples/apps so I think that the current approach is safer (we are able to recheck for the application to ensure that it works fine). Other applications/samples on Thingy:53 already apply this DTS change to MCUboot. in the same way

2022-12-07 08:01 UTC, MarekPieta commented
Should go in after https://github.com/nrfconnect/sdk-nrf/pull/9507

2022-12-13 14:55 UTC, pdunaj approved these changes

2022-12-13 16:27 UTC, merged