Revert "thingy53: samples and applications: Use common partition layout"
nrfconnect/sdk-nrf pull request #9595
Opened 2022-12-05 14:35 UTC by MarekPieta

This reverts commit 1f9765df5acbb36afff0ce40c94ba65d44d19d70.

2022-12-05 14:35 UTC, MarekPieta commented
PR opened on @kapi-no request.

2022-12-05 14:36 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/c0689b16ff127d1b71a4cc20310d476e1807e26e (main) | https://github.com/nrfconnect/sdk-zephyr/pull/1004 | [nrfconnect/sdk-zephyr#1004/files](https://github.com/nrfconnect/sdk-zephyr/pull/1004/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-12-05 14:37 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9595/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9595/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9595/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-05 15:23 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9595
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-05 15:28 UTC, kapi-no approved these changes

2022-12-06 08:17 UTC, tejlmand requested changes
this just creates noise and more work to ourselves as we would need to revert the revert again later.

2022-12-06 10:09 UTC, MarekPieta commented
This would not go into NCS 2.2.0. There is no point to introduce it later on. Closed.

2022-12-06 10:09 UTC, closed without merging