application: serial_lte_client: Add TFTP client
nrfconnect/sdk-nrf pull request #9624
Opened 2022-12-08 06:51 UTC by junqingzou

Add a TFTP client, using Zephyr tftp library.
'AT#XTFTP=<op>,<url>,<port>,<file_path>[,<mode>]'

Currently only support TFTP Read.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2022-12-08 06:52 UTC, junqingzou commented
DNM: not for NCSv2.2.0

2022-12-08 06:52 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9624/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9624/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9624/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-08 09:18 UTC, rlubos reviewed
Regarding the commit title, there is a small mistake, the application is still called `serial_lte_modem` not `serial_lte_client`.

2022-12-08 09:18 UTC, rlubos commented on applications/serial_lte_modem/doc/slm_description.rst
> +.. _CONFIG_SLM_FTPC:
It should be `_CONFIG_SLM_TFTPC`?

2022-12-09 00:38 UTC, junqingzou commented on applications/serial_lte_modem/doc/slm_description.rst
> +.. _CONFIG_SLM_FTPC:
Yes, and that fails the doc build 😅

2022-12-09 01:57 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9624
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-09 08:22 UTC, pirun approved these changes

2022-12-09 14:24 UTC, FrancescoSer requested changes

2022-12-09 14:24 UTC, FrancescoSer commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  Valid values are "netascii", "octet" and "mail".
```suggestion
  Valid values are ``netascii``, ``octet`` and ``mail``.
```

2022-12-09 14:24 UTC, FrancescoSer commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  Default port 69 is applied if this parameter is omitted or set to 0.
```suggestion
  Default port 69 is applied if this parameter is omitted or set to ``0``.
```

2022-12-09 14:24 UTC, FrancescoSer commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  Default value "octet" is applied if this parameter is omitted.
```suggestion
  The default value ``octet`` is applied if this parameter is omitted.
```

2022-12-13 11:33 UTC, wiba-nordic requested changes
Also, there's an old error on Line 50: there should be a space before \`\`uput\`\`, it's not currently rendering correctly.

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +      The maximum size of a file supported is 2100 bytes.
```suggestion
      The maximum supported file size is 2100 bytes.
```

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  * ``4`` - TFTP write request using IP protocol family version 6 (currently not supported).
```suggestion
  * ``1`` - TFTP read request using IP protocol family version 4.
  * ``3`` - TFTP read request using IP protocol family version 6.
  * *Currently not supported:* ``2`` - TFTP write request using IP protocol family version 4.
  * *Currently not supported:* ``4`` - TFTP write request using IP protocol family version 6.
```
I'm not sure if we even need to include the values that are currently not supported. But if they are included, it's better to start with the "not supported" text so it stands out more.

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  It indicates the filepath on TFTP server to read from or write to.
```suggestion
  It indicates the file path on the TFTP server to read from or write to.
```

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  It is negative integer.
```suggestion
  It is a negative integer indicating the error code.
```

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +* The ``<error_msg>`` value is an string.
```suggestion
* The ``<error_msg>`` value is a string.
```

2022-12-13 11:33 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  It is the description of the ``<error>`` code.
```suggestion
  It is the description of the error code.
```

2022-12-14 07:24 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  It is the description of the ``<error>`` code.
If we want to keep it, then it could be formed like this:
```suggestion
  It is the description that corresponds to the ``<error>`` value.
```

2022-12-14 08:42 UTC, wiba-nordic requested changes

2022-12-14 08:42 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/FTP_AT_commands.rst
> +  It is a negative integer.
```suggestion
  It is a negative integer based on the type of error.
```

2022-12-14 08:51 UTC, wiba-nordic approved these changes

2022-12-27 11:42 UTC, merged