manifest: pull Matter Wi-Fi network diagnostics implementation
nrfconnect/sdk-nrf pull request #9625
Opened 2022-12-08 07:11 UTC by markaj-nordic

This change adds support the the wifinetworkdiagnostics cluster. Following statistics can be read:
  * multicast RX/TX
  * unicast RX/TX
  * beacons lost/TX

2022-12-08 07:11 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | [nrfconnect/sdk-connectedhomeip@v2.2.0](https://github.com/nrfconnect/sdk-connectedhomeip/releases/tag/v2.2.0) | https://github.com/nrfconnect/sdk-connectedhomeip/pull/157 | [nrfconnect/sdk-connectedhomeip#157/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/157/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-12-08 07:14 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9625/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9625/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |

**test-fw-nrfconnect-chip:** added because there was no .github/test-spec.yml in 'matter'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9625/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-08 07:45 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9625
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-08 12:35 UTC, LuDuda reviewed
Please add the information in release notes about this addition. Otherwise, looks good!

2022-12-09 08:03 UTC, greg-fer requested changes
I guess we need to update sha in the links.txt for all the Matter docset links, right, @Damian-Nordic ?

2022-12-09 08:03 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Support for Wi-Fi Network Diagnostic Custer (the counts for the number of packets received and transmitted on the Wi-Fi interface)
```suggestion
  * Support for Wi-Fi Network Diagnostic Cluster (which counts the number of packets received and transmitted on the Wi-Fi interface).
```

2022-12-09 08:50 UTC, kkasperczyk-no commented
> I guess we need to update sha in the links.txt for all the Matter docset links, right, @Damian-Nordic ?

@greg-fer I think we don't need to do that. This change updates only code and nothing related to docs didn't change, so it should be fine.

2022-12-09 08:53 UTC, kkasperczyk-no approved these changes

2022-12-12 07:26 UTC, greg-fer approved these changes

2022-12-12 07:55 UTC, merged