lib: multicell_location: Deprecate this library
nrfconnect/sdk-nrf pull request #9664
Opened 2022-12-13 08:11 UTC by trantanen

Deprecating Multicell location library.

Relevant function is available through Location library.

2022-12-13 08:29 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9664/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9664/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9664/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-02 11:57 UTC, peknis requested changes

2023-01-02 11:57 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Multicell location sample removed because multicell location library is now deprecated.
```suggestion
  * Multicell location sample because of the deprecation of the Multicell location library.
```

2023-01-02 11:57 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * This library is now deprecated and relevant functionality is available through :ref:`lib_location` library.
```suggestion
  * This library is now deprecated and relevant functionality is available through the :ref:`lib_location` library.
```

2023-01-02 11:57 UTC, peknis commented on doc/nrf/libraries/networking/multicell_location.rst
> +   This library is deprecated and relevant functionality is available through :ref:`lib_location`.
```suggestion
   This library is deprecated and relevant functionality is available through the :ref:`lib_location` library.
```

2023-01-02 11:57 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    Relevant functionality is available through :ref:`lib_location` library.
```suggestion
    Relevant functionality is available through the :ref:`lib_location` library.
```

2023-01-02 12:29 UTC, tokangas commented
Should we mention also the release version number since when the library has been deprecated? Also, would be good to mention the deprecation in the beginning of `multicell_location.h` and maybe also make it visible in Kconfig as well.

Here's an example from the GPS driver deprecation: https://github.com/nrfconnect/sdk-nrf/commit/a8ddf4fb1ffa6f86a070c686414db499b814539f

2023-01-02 12:56 UTC, peknis approved these changes

2023-01-03 06:43 UTC, trantanen commented
> Should we mention also the release version number since when the library has been deprecated? Also, would be good to mention the deprecation in the beginning of `multicell_location.h` and maybe also make it visible in Kconfig as well.

Added release version, deprecation in Kconfig and header file.

2023-01-03 06:47 UTC, tokangas approved these changes

2023-01-03 07:12 UTC, jhirsi approved these changes

2023-01-03 09:41 UTC, simensrostad approved these changes

2023-01-03 14:45 UTC, rlubos approved these changes

2023-01-03 14:46 UTC, merged