cmake: Fix overlay additions of child images not persisting
nrfconnect/sdk-nrf pull request #9679
Opened 2022-12-13 14:20 UTC by nordicjm

Fixes an issue whereby child image overlays were added but were not processed until cmake was re-ran on the project causing an invalid build configuration.

2022-12-13 14:22 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9679/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9679/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-tfm | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9679/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-13 14:52 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9679
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-13 15:59 UTC, MarekPieta requested changes
Unfortunately, the fix does not seem to work. The https://github.com/nrfconnect/sdk-nrf/pull/9593 PR still replicates the same issue (MCUboot child image DTS overlay is somehow dropped on CMake rerun) after fix was cherry-picked.

Edit: Tested adding `/home/mapi/ncs/nrf/applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay` file. The file is no longer taken into account after CMake rerun.

2022-12-14 17:52 UTC, tejlmand requested changes
not convinced this is fixing the root cause of the observed behavior.

Could you provide a sample and board for which this specific problem occurs ?

2022-12-14 17:52 UTC, tejlmand commented on cmake/extensions.cmake
> +    set(${image}_${overlay_type} "${old_overlays};${overlay_file}" PARENT_SCOPE)
this is just setting the overlay in parent scope, that is the scope of the caller, and therefore not really fixing anything, cause there could be higher level scopes.

But besides that, if line:93 is hiding the cache variable then we have a different issue cause for child images then those variables should never be in local scope, they should only exists in the cache.

When does this occur  / which sample ?
And is it a problem related to when this function is called, for example:
- add_child_image(NAME my_image ...)
- add_overlay(my_image ...)  
cause in such a case the overlay file is set too late and things will not work.

2022-12-14 18:27 UTC, tejlmand commented
Interesting, when testing this here:
Initial run:
```
$ cmake -GNinja -DBOARD=nrf5340dk_nrf5340_cpuapp -Bbuild applications/machine_learning/
$ grep DTC_OVERLAY_FILE build/mcuboot/child_image_preload.cmake 
set(DTC_OVERLAY_FILE "/projects/github/ncs/nrf/modules/mcuboot/flash_sim.overlay;/projects/github/ncs/nrf/modules/mcuboot/usb.overlay;/projects/github/ncs/nrf/applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay" CACHE INTERNAL "NCS child image controlled")
```

Everything looks correct, so let's do a re-run:
```
$ cmake build/mcuboot/
Loading Zephyr default modules (Zephyr base (cached)).
...
$ grep DTC_OVERLAY_FILE build/mcuboot/child_image_preload.cmake
set(DTC_OVERLAY_FILE "/projects/github/ncs/nrf/modules/mcuboot/flash_sim.overlay;/projects/github/ncs/nrf/modules/mcuboot/usb.overlay;/projects/github/ncs/nrf/applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay" CACHE INTERNAL "NCS child image controlled")
```

Still correct.

Which CMake version are you using ?
I wonder if we are discovering another cache bug similar to this I have raised:
https://gitlab.kitware.com/cmake/cmake/-/issues/22734

Note, i'm testing with CMake 3.21.

2022-12-14 18:37 UTC, tejlmand commented
Tested with 3.23.3 and 3.25.1 and same correct behavior is observed.
The `child_image_preload.cmake` contains expected `DTC_OVERLAY_FILE` setting on first and subsequent runs.

```
=== child image mcuboot -  begin ===
loading initial cache file /projects/github/ncs/nrf/build/mcuboot/child_image_preload.cmake
...
-- Found devicetree overlay: /projects/github/ncs/nrf/modules/mcuboot/flash_sim.overlay
-- Found devicetree overlay: /projects/github/ncs/nrf/modules/mcuboot/usb.overlay
-- Found devicetree overlay: /projects/github/ncs/nrf/applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay
-- Found devicetree overlay: /projects/github/ncs/bootloader/mcuboot/boot/zephyr/dts.overlay
...
```

2022-12-14 18:40 UTC, tejlmand commented
Reproduced it, it's purely a re-run of the child image, it must be a re-run of the parent + the child image.
I see the faulty behavior now.

2022-12-14 18:49 UTC, tejlmand commented
Found the root cause.
On second and subsequent runs, the `CONF_FILE` variable is set, hence the `if` is not taken and therefore the board and image specific files are not being picked up.
https://github.com/nrfconnect/sdk-nrf/blob/301472d0a2a5f4659f8a3a030bc05188ad2c1088/cmake/multi_image.cmake#L307

2022-12-14 18:52 UTC, tejlmand commented
oh my, seems we need the conf file in the cache, ref:
https://github.com/nrfconnect/sdk-nrf/commit/14023e5e0ca0e27de52a3270a45e8c34ea0cf226

2022-12-14 20:04 UTC, tejlmand commented
Find proper fix here: #9699

2022-12-14 20:05 UTC, tejlmand commented on cmake/extensions.cmake
> +    set(${image}_${overlay_type} "${old_overlays};${overlay_file}" PARENT_SCOPE)
found the root cause.

2023-02-27 00:28 UTC, closed without merging