application: serial_lte_modem: Support TCP/UDP client config
nrfconnect/sdk-nrf pull request #9712
Opened 2022-12-16 05:21 UTC by junqingzou

Allow TCP/TLS or UDP/DTLS client to configure socket options. 
Add new ``<op>`` code to handle the request.

Signed-off-by: Jun Qing Zou <jun.qing.zou@nordicsemi.no>

2022-12-16 05:22 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9712/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9712/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9712/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-16 05:22 UTC, junqingzou commented
DNM: solution proposal to BDM/Customer as of now

2022-12-16 07:39 UTC, wiba-nordic requested changes

2022-12-16 07:39 UTC, wiba-nordic commented on applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
> +    ``<value>`` is the timeout in seconds and can be one of the following integers: ``1``, ``3``, ``7``, ``15``, ``31``, ``63``, ``123``.
```suggestion
* For the TLS client, the ``<name>`` parameter can accept one of the values below, which also determines the ``<value>`` parameter:

  * ``2`` - ``TLS_HOSTNAME``.
  
    * ``<value>`` is a string.
    
  * ``5`` - ``TLS_PEER_VERIFY``.
  
    * ``<value>`` is an integer and can be either ``0`` or ``1``.
    
  * ``12`` - ``TLS_SESSION_CACHE``.
  
    * ``<value>`` is an integer and can be either ``0`` or ``1``.
   
  * ``13`` - ``TLS_SESSION_CACHE_PURGE``.
  
    * ``<value>`` can accept any integer value.
    
  * ``14`` - ``TLS_DTLS_HANDSHAKE_TIMEO``.
  
    * ``<value>`` is the timeout in seconds and can be one of the following integers: ``1``, ``3``, ``7``, ``15``, ``31``, ``63``, ``123``.
    
  For a complete list of the supported SET ``<name>`` accepted parameters, see the `SETSOCKETOPT Service Spec Reference`.
```
The same changes should be applied to the other command as well.

2022-12-20 13:05 UTC, rlubos approved these changes
Code part looks ok.

2023-07-31 08:27 UTC, closed without merging