samples: bluetooth: peripheral_uart: Change from ms to us
nrfconnect/sdk-nrf pull request #9732
Opened 2022-12-20 09:55 UTC by edvinand

Wait time has been changed from ms to us in Zephyr, and is now updated in the peripheral_uart's Kconfig file in this commit.

Signed-off-by <edvin.holmseth@nordicsemi.no>

2022-12-20 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=9732) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrf?pullRequest=9732) before we can accept your contribution.<br/><hr/>**Edvin Holmseth** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrf?pullRequest=9732) it.</sub>

2022-12-20 10:06 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9732/2/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9732/2/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9732/2/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-20 10:53 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9732
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-09 12:21 UTC, alwa-nordic requested changes
This is an API breaking change. I will require an entry in the change log at the least.

But is it not better to keep milliseconds as unit for `BT_NUS_UART_RX_WAIT_TIME`? Changing it now may silently break user code that has `BT_NUS_UART_RX_WAIT_TIME` in `prj.conf` or `build/.config`.

Another alternative is to mark `BT_NUS_UART_RX_WAIT_TIME` as deprecated, and add a new config `BT_NUS_UART_RX_WAIT_TIME_US`.

2023-01-23 14:49 UTC, KAGA164 commented
> 

I agree with @alwa-nordic. I would keep BT_NUS_UART_RX_WAIT_TIME in milliseconds unit and calculate it into microseconds in a sample

2023-01-23 14:50 UTC, KAGA164 requested changes
I agree with @alwa-nordic. I would keep BT_NUS_UART_RX_WAIT_TIME in milliseconds unit and calculate it into microseconds in a sample.

2023-01-24 10:55 UTC, alwa-nordic approved these changes
I did not notice that the config belongs to the sample itself. In that case, I don't think this is an API that needs to be stable. I'm ok with this after all. Do you agree@KAGA164?

2023-01-24 12:52 UTC, KAGA164 commented
I agree. @edvinand Please update changelog, I think this is worth to mention there and then we can merge it

2023-01-24 14:06 UTC, edvinand commented
How do I do that? Sorry. I am not that experienced in Github. To be honest, I am not even sure how I would fish up the pull request for changes. Besides, if I figured out how to edit the change log, what change exactly do you want me to add?

2023-01-25 14:38 UTC, alwa-nordic commented
> How do I do that? Sorry. I am not that experienced in Github. To be honest, I am not even sure how I would fish up the pull request for changes. Besides, if I figured out how to edit the change log, what change exactly do you want me to add?

https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases/release-notes-changelog.rst#L15

2023-02-01 09:13 UTC, alwa-nordic commented
@edvinand You have to add a change to the file https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/releases/release-notes-changelog.rst in this PR. Add a subsection under "Bluetooth samples" explaining the change in this PR.

2023-04-17 11:46 UTC, grochu commented
Pushed the update in the changelog to unblock the PR. @peknis could you please check?

2023-04-17 11:55 UTC, peknis requested changes

2023-04-17 11:55 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Fixed unit of the :kconfig:option:`CONFIG_BT_NUS_UART_RX_WAIT_TIME` option to comply with the UART API.
```suggestion
  * Fixed the unit of the :kconfig:option:`CONFIG_BT_NUS_UART_RX_WAIT_TIME` Kconfig option to comply with the UART API.
```

2023-04-18 05:31 UTC, peknis approved these changes

2023-04-18 06:05 UTC, grochu approved these changes

2023-04-24 11:13 UTC, KAGA164 approved these changes

2023-04-24 11:21 UTC, merged