manifest: pull Matter fix for WPA3 Wi-Fi connection
nrfconnect/sdk-nrf pull request #9737
Opened 2022-12-20 15:19 UTC by markaj-nordic

This PR also removes the default support for nRF7002 revision A in Matter, 
since now we only maintain revision B.

Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>

2022-12-20 15:20 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| matter | https://github.com/nrfconnect/sdk-connectedhomeip/commit/9a828bbf44262e37bb560200f59e14af02b9f1a6 | https://github.com/nrfconnect/sdk-connectedhomeip/pull/170 | [nrfconnect/sdk-connectedhomeip#170/files](https://github.com/nrfconnect/sdk-connectedhomeip/pull/170/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2022-12-20 15:45 UTC, LuDuda reviewed
We should also update the documentation to not claim that REV_A is only used + some release highlight would be great (about WPA3 fix and Rev B).

2022-12-21 08:09 UTC, markaj-nordic commented
> We should also update the documentation to not claim that REV_A is only used + some release highlight would be great (about WPA3 fix and Rev B).

Good point, will do.

2022-12-21 11:02 UTC, markaj-nordic commented
@greg-fer should we also get rid of https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/shortcuts.txt#L119 ?

2022-12-21 15:24 UTC, greg-fer submitted a review, later dismissed
Sorry, two comments.

2022-12-21 15:24 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Default support for nRF7002 revision B
```suggestion
  * Default support for nRF7002 revision B.
```

2022-12-21 15:24 UTC, greg-fer commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Connection timeout when attaching to Wi-Fi Access Point which requires Wi-Fi Protected Access 3 (WPA3)
```suggestion
  * An issue with a connection timeout when attaching to a Wi-Fi Access Point that requires Wi-Fi Protected Access 3 (WPA3).
```

2022-12-21 15:31 UTC, greg-fer commented
@markaj-nordic , re:

> should we also get rid of https://github.com/nrfconnect/sdk-nrf/blob/main/doc/nrf/shortcuts.txt#L119 

Good question. I don't think we should, as this note refers specifically to NCS v2.2.0, which is already released.
You might rather want to edit it somewhat like:
```
.. |matter_wifi_revb_ncs220_test_note| replace:: All Matter samples in the |NCS| v2.2.0 that offer Wi-Fi support have been tested using the nRF7002 DK (PCA10143) rev. A and are built with rev. A support by default.
   When using the |NCS| v2.2.0, you can configure Matter samples to use rev. B by setting the :kconfig:option:`CONFIG_NRF700X_REV_A` Kconfig option to ``n``.
   Since then, all Matter samples have been updated to support both rev. A and rev. B.
   Make sure that you build the samples for the revision of the nRF7002 DK that you are using.
```

2022-12-21 15:58 UTC, LuDuda commented
@greg-fer agree that it refers to NCS 2.2.0 but this is no longer valid. NCS 2.2.0 users can still check documentation for NCS 2.2.0. Thus i would definately remove it now (i guess) or sometime before 2.3.0. We won't support Rev A long term anyway.

2022-12-21 16:13 UTC, markaj-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Default support for nRF7002 revision B
Done.

2022-12-21 16:13 UTC, markaj-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Connection timeout when attaching to Wi-Fi Access Point which requires Wi-Fi Protected Access 3 (WPA3)
Done.

2022-12-22 07:02 UTC, markaj-nordic commented
> @greg-fer agree that it refers to NCS 2.2.0 but this is no longer valid. NCS 2.2.0 users can still check documentation for NCS 2.2.0. Thus i would definately remove it now (i guess) or sometime before 2.3.0. We won't support Rev A long term anyway.

@greg-fer, @LuDuda  I have removed the note from README file of all samples.

2022-12-22 07:43 UTC, Damian-Nordic approved these changes

2022-12-22 10:58 UTC, LuDuda approved these changes

2022-12-22 11:01 UTC, wiba-nordic requested changes

2022-12-22 13:36 UTC, wiba-nordic approved these changes

2022-12-23 09:29 UTC, merged