doc: Documentation about Wi-Fi based LwM2M location assistance
nrfconnect/sdk-nrf pull request #9740
Opened 2022-12-21 06:40 UTC by jarlamsa

Add documentation about the Wi-Fi based location assistance through LwM2M server to the nrfCloud.

Signed-off-by: Jarno Lämsä <jarno.lamsa@nordicsemi.no>

2022-12-21 06:41 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9740/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9740/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-12-21 06:47 UTC, peknis requested changes

2022-12-21 06:47 UTC, peknis commented on doc/nrf/libraries/networking/lwm2m_location_assistance.rst
> +To populate the objects, first enable the Kconfig option for the access point scanner :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_WIFI_AP_SCANNER` and call the :c:func:`lwm2m_wifi_request_scan` to req
```suggestion
To populate the objects, first enable the Kconfig option for the access point scanner :kconfig:option:`CONFIG_LWM2M_CLIENT_UTILS_WIFI_AP_SCANNER` and call the :c:func:`lwm2m_wifi_request_scan` function to request the access point scan.
```

2022-12-21 06:47 UTC, peknis commented on doc/nrf/libraries/networking/lwm2m_location_assistance.rst
> +The Ground Fix Location object is used similar to the cell-based location when sending the location request.
```suggestion
The Ground Fix Location object is used in the same manner as the cell-based location when sending the location request.
```

2022-12-21 06:56 UTC, jarlamsa commented
Thank you @peknis for your review comments. I think I have addressed those now, please re-review.

2022-12-21 07:09 UTC, peknis approved these changes

2022-12-21 07:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9740
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-22 07:44 UTC, VeijoPesonen approved these changes

2022-12-22 07:58 UTC, merged