boards: nrf5340_audio_dk: Add version 1.2.0
nrfconnect/sdk-nrf pull request #9746
Opened 2022-12-21 10:53 UTC by erikrobstad

To board.h

Signed-off-by: Erik Robstad <erik.robstad@nordicsemi.no>

2022-12-21 10:56 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9746/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9746/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9746/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-22 08:02 UTC, koffes requested changes
This looks good. Though, please mention in the commit message something like:
"This only adds bootup support. Full peripheral support to come"

2022-12-26 03:09 UTC, rick1082 approved these changes

2022-12-30 13:25 UTC, erikrobstad commented
> This looks good. Though, please mention in the commit message something like: "This only adds bootup support. Full peripheral support to come"

Done

2023-01-02 10:44 UTC, alexsven approved these changes

2023-01-02 11:39 UTC, merged