caf: Sizes of enums inside events
nrfconnect/sdk-nrf pull request #9758
Opened 2022-12-23 08:07 UTC by michalek-no

Added macro intended to define last state of the
enums handled by event_manager_proxy.
Applied to all caf events enums.

Signed-off-by: Mateusz Michalek <mateusz.michalek@nordicsemi.no>

2022-12-23 08:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9758/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9758/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-sdk-find-my | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9758/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-23 09:01 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9758
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-04 11:25 UTC, pdunaj requested changes

2023-01-04 11:25 UTC, pdunaj commented on include/caf/events/ble_common_event.h
> +	/** Unused in code, required for inter-core compatibility  */
add dots at sentence end (check new doxygen lines) for the sake of consistency

2023-01-04 11:25 UTC, pdunaj commented on subsys/app_event_manager/app_event_manager_priv.h
> +#define CONDITIONAL_ENUM_SIZE_FORCE(ename) COND_CODE_1(IS_ENABLED(CONFIG_EVENT_MANAGER_PROXY),	\
s/CONDITIONAL_ENUM_SIZE_FORCE/APP_EM_ENFORCE_ENUM_SIZE

2023-01-04 11:25 UTC, pdunaj commented on subsys/app_event_manager/app_event_manager_priv.h
> +/* Size setting enum state generator, required for inter-core compatibility.
s/Size setting enum state generator,/Enum element enforcing integer size,

2023-01-04 11:25 UTC, pdunaj commented on subsys/app_event_manager/app_event_manager_priv.h
> + * Shall be called as last state of enum.
s/Shall be called as last state of enum./Shall be added as the last element of enum.

2023-01-09 09:51 UTC, emob-nordic commented on subsys/app_event_manager/app_event_manager_priv.h
> +	(ENUM_##ename##_SIZE = UINT32_MAX),							\
``` suggestion
	(ename##_FORCE_ENUM_SIZE = UINT32_MAX),							\
```
This way all enum names would be consistent in style.

2023-01-09 09:51 UTC, emob-nordic requested changes
Please address Pawel's comments. One comment from me.

2023-01-09 10:09 UTC, rakons approved these changes
No more comments that are already there. ACK when rest is addressed.

2023-01-09 10:58 UTC, pdunaj approved these changes

2023-01-09 15:58 UTC, emob-nordic approved these changes
You can fix that or not.

2023-01-09 15:58 UTC, emob-nordic commented on subsys/app_event_manager/app_event_manager_priv.h
> +/* Enum element enforcing integer size, required for inter-core compatibility.
``` suggestion
/* Enum element enforcing 32 bit unsigned integer size, required for inter-core compatibility.
```

2023-01-15 07:22 UTC, emob-nordic commented
@annwoj or @divipillai Could you please have a look at changelog?

2023-01-16 08:22 UTC, annwoj commented on doc/nrf/releases/release-notes-changelog.rst
> +* :ref:`caf_overview_events`
```suggestion
* :ref:`caf_overview_events`:
```

2023-01-16 08:22 UTC, annwoj commented on doc/nrf/releases/release-notes-changelog.rst
> +    Applied macro to all affected caf events.
```suggestion
  * Improved inter-core compatibility.
  * Added a macro intended to set the size of events member enums to 32 bits when the Event Manager Proxy is enabled.
  * Applied macro to all affected CAF events.
```

2023-01-16 08:22 UTC, annwoj commented on doc/nrf/releases/release-notes-changelog.rst
> +    Applied macro to all affected caf events.
please double-check the meaning after adjustments (2nd bullet point)

2023-01-16 10:30 UTC, annwoj approved these changes

2023-01-16 17:14 UTC, nvlsianpu approved these changes

2023-01-17 08:18 UTC, merged