doc: dev model: Add a reference to ncs-example-application
nrfconnect/sdk-nrf pull request #9770
Opened 2022-12-28 17:22 UTC by carlescufi

This new repo is intended to serve as a templated reference of Wokflow 4: application as a manifest repository.

Rework the Workflow 4 section to cover the use of the new ncs-example-application, as well as rewording it for clarity.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

2022-12-28 17:23 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9770/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9770/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2022-12-28 17:27 UTC, carlescufi commented
Note to reviewers: As part of reviewing this PR  please feel free to send PRs modifying the README file in the ncs-example-application repo:
https://github.com/nrfconnect/ncs-example-application#readme

2022-12-28 17:35 UTC, gmarull approved these changes

2022-12-28 18:31 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9770
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2022-12-29 07:53 UTC, peknis requested changes

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +In order to create your own repository you have a couple of options, described in the sections below.
```suggestion
You have a couple of different options to create your own repository.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +-----------------------------------------------
```suggestion
Recommended: Using the example application repository
-----------------------------------------------------
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +Nordic maintains a templated example repository for the purpose of serving as a reference for users that choose this workflow, `ncs-example-application`_.
```suggestion
Nordic Semiconductor maintains a templated example repository as a reference for users that choose this workflow, `ncs-example-application`_.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +This repository showcases many features of both the |NCS| and Zephyr:
```suggestion
This repository showcases the following features of both the |NCS| and Zephyr:
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +drivers, and libraries as required by your application.
```suggestion
It is highly recommended to use this templated repository as a starting point for your own application manifest repository.
Click the :guilabel:`Use this template` button on the GitHub web user interface.
Once you have your own copy of the repository, you can then modify it.
You can add your own projects to the manifest file, as well as your own boards, drivers, and libraries as required by your application.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +the version of the |NCS| that they intend to use.
```suggestion
The `ncs-example-application`_ repository is tagged every time a new release of the |NCS| is launched (starting with v2.3.0), using the same version number.
This allows you to select the tag that matches the version of the |NCS| you intend to use.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +--------------------------------------------
```suggestion
Creating your own manifest repository from scratch
--------------------------------------------------
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +as a starting point, then you can start from scratch to create your own manifest repo that imports the |NCS|.
```suggestion
If you decide not to use the example application repository as a starting point, you can start from scratch to create your own manifest repository that imports the |NCS|.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/dm_adding_code.rst
> +your repository (typically in :file:`root/west.yml`):
```suggestion
To start the process, ``import`` `sdk-nrf`_ in your own :file:`west.yml`, using the :ref:`manifest imports <zephyr:west-manifest-import>` feature of west.
This is demonstrated by the following code, that would be placed somewhere in your repository (typically in :file:`root/west.yml`):
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/introduction.rst
> +familiar with the basics.
```suggestion
To start developing your application you need to understand a few fundamental concepts.
Follow the :ref:`Zephyr guide to Application Development <zephyr:application>` and browse through the included :ref:`reference applications <applications>` in the |NCS| to get familiar with the basics.
```

2022-12-29 07:53 UTC, peknis commented on doc/nrf/introduction.rst
> +reference and/or starting point.
```suggestion
You also need to decide how to structure your application.
You can choose from a few alternative :ref:`user workflows <dm_user_workflows>`, but having the
:ref:`application as the manifest repository <dm_workflow_4>` is recommended.
An `ncs-example-application`_ repository is provided to serve as a reference or starting point.
```

2022-12-29 10:27 UTC, peknis approved these changes

2022-12-29 10:43 UTC, merged