Clean up LwM2M sample
nrfconnect/sdk-nrf pull request #9776
Opened 2022-12-30 13:10 UTC by SeppoTakalo

### Simplify logging configuration
      
There is now only one log level configuration for application.
      
Also, there is now only couple of logging modules registered
with LOG_MODULE_REGISTER()
* app_lwm2m_client
* app_lwm2m
* app_sensors
* gnss_module

Multiple C files now share the same module and use
LOG_MODULE_DECLARE instead of each defining their own.

### Remove sensor avents
      
Simplify the sensor code by removing the applications events
that deliver sensor data. Instead write directly to the LwM2M
engine from the sensor worker. This is much more cleaner example.

Also remove unnecessary filtering of sensor data. It is enough
to filter with observation parameters.

Update timestamps on post_write callback.

2022-12-30 13:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9776/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9776/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9776/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2022-12-30 13:53 UTC, juhaylinen approved these changes

2022-12-30 13:56 UTC, jarlamsa approved these changes
LGTM

2022-12-30 14:12 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9776
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-02 07:08 UTC, jheiskan81 approved these changes

2023-01-02 13:17 UTC, rlubos approved these changes
LGTM - please rebase the PR (conflict).

2023-01-02 13:17 UTC, rlubos commented on samples/nrf9160/lwm2m_client/src/events/CMakeLists.txt
>  zephyr_include_directories(include)
There's a typo in the commit title, `avents` -> `events`

2023-01-02 13:36 UTC, SeppoTakalo commented
Rebased and added a changelog and minor documentation update.
@peknis  please review.

2023-01-02 13:42 UTC, peknis requested changes

2023-01-02 13:42 UTC, peknis commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Sensor module has been simplified, it does not use application events, filtering or configurable periods anymore.
```suggestion
    * The sensor module has been simplified.
      It does not use application events, filtering, or configurable periods anymore.
```

2023-01-02 13:42 UTC, peknis commented on samples/nrf9160/lwm2m_client/sample_description.rst
> +The sample has a sensor module which, if enabled, reads the selected sensors, and updates the client's LwM2M resource values.
```suggestion
The sample has a sensor module which, if enabled, reads the selected sensors and updates the client's LwM2M resource values.
```

2023-01-02 13:42 UTC, peknis commented on samples/nrf9160/lwm2m_client/sample_description.rst
> +If notifications are enabled for a Sensor Value resource, and the corresponding sensor is enabled in the sensor module, a notification will be sent when that value changes.
```suggestion
If notifications are enabled for a Sensor Value resource and the corresponding sensor is enabled in the sensor module, a notification will be sent when the value changes.
```

2023-01-02 13:42 UTC, peknis commented on samples/nrf9160/lwm2m_client/sample_description.rst
> +Frequency of notification packets are configured by LwM2M attributes set by the server.
```suggestion
The frequency of notification packets is configured by LwM2M attributes set by the server.
```

2023-01-03 06:59 UTC, peknis approved these changes

2023-01-03 14:12 UTC, VeijoPesonen approved these changes

2023-01-03 14:33 UTC, merged