sr_coex: Add support for Wi-Fi and BLE co-existence
nrfconnect/sdk-nrf pull request #9778
Opened 2022-12-30 16:17 UTC by muraliThokala

This is for Wi-Fi and Short Range (SR) coexistence sample that demonstrates coexistence between WLAN and SR radios such as Bluetooth Low Energy (BLE) and Thread in 2.4GHz frequency. Though it is mentioned as Wi-Fi coexistence with SR, this initial version of coexistence sample supports Wi-Fi coexistence with BLE only.

This sample needed changes in the following samples/modules.
1. BLE throughput sample - By default BLE throughput is a file based one. To have BLE throughput like WLAN time-based throughput (so that both WLAN and BLE throughput runs simultaneously for the same duration) updates are done to BLE throughput sample to have support for both file and time-based approaches.
2. RPU - RPU updates are available as a firmware patch.
3. Wi-Fi Driver - Updates done to support multiple commands refactor the SR coexistence command in the
    Driver-RPU interface. 
4.  zperf - Updates done to have non-blocking zperf application.
5. Boards - DTS bindings required to control nRF5340 side switch. SR grant is made high using pull-up.
 
Tasks pending related to this coexistence sample are
1. Zperf code:  Push non-blocking zperf related updates to NCS.
2. Zperf app: Buffer optimizations to solve errors like "failed to allocate net_pkt" when zperf is run.
    Also observing LAST PACKET NOT RECEIVED!!! error and missing statistics. Currently the solution to this is using iperf 2.0.5 as given in https://docs.zephyrproject.org/3.2.0/connectivity/networking/api/zperf.html.
3. Boards: SR grant pull-up is to be avoided, instead net-mgmt APIs are to be used to enable/disable SR side coexistence.
4. sr_coex sample: BLE related files are copied to sr_coex sample to run the BLE throughput simultaneously with zperf. This file copy is to be avoided and BLE throughput library to be used instead.
BLE connection interval is hardcoded in the sample test bench. would be good to provide this as part of Kconfig.

2023-01-01 19:56 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| zephyr | https://github.com/nrfconnect/sdk-zephyr/commit/8fb465f43f6a90ac4c4ce89265047e04f7d5ee5b | https://github.com/nrfconnect/sdk-zephyr/pull/1018 | [nrfconnect/sdk-zephyr#1018/files](https://github.com/nrfconnect/sdk-zephyr/pull/1018/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-01-01 20:34 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9778
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-11 13:01 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9778/18/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9778/18/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-sdk-find-my | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9778/18/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-11 13:51 UTC, peknis requested changes

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +|               |              | Program coexistence sample application on nRF7002 DK.  |
```suggestion
| Wi-Fi only    | NA           | Run Wi-Fi **iperf** in server mode on test PC.         |
| throughput    |              | Program coexistence sample application on nRF7002 DK.  |
+---------------+--------------+--------------------------------------------------------+
| Bluetooth LE only      | NA          | Program BLE throughput application on nRF5340 DK and   |
| throughput    |              | select role as peripheral.                             |
|               |              | Program coexistence sample application on nRF7002 DK.  |
+---------------+--------------+--------------------------------------------------------+
| Wi-Fi and BLE | Disabled/    | Run Wi-Fi **iperf** in server mode on test PC.             |
| combined      | Enabled      | Program Bluetooth LE throughput application on nRF5340 DK and   |
| throughput    |              | select role as peripheral.                             |
|               |              | Program coexistence sample application on nRF7002 DK.  |
```
Again, messed up the table, I'm afraid. Just focused on the text. Bear with me.

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +Wi-Fi throughput result appears on test PC terminal on which iperf server is run. BLE throughput result appears on minicom terminal connected to nRF5340 DK.
```suggestion
The Wi-Fi throughput result appears on the test PC terminal on which **iperf** server is run.
The Bluetooth LE throughput result appears on the minicom terminal connected to the nRF5340 DK.
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +Summary of results obtained when coexistence tests are run for different Wi-Fi operating bands and antenna configurations with Wi-Fi mode set to 802.11n are given below. These tests are run keeping t
```suggestion
The following table collects a summary of results obtained when coexistence tests are run for different Wi-Fi operating bands and antenna configurations with Wi-Fi mode set to 802.11n.
The tests are run with the test setup inside an RF shield box.
Therefore, the results are representative and might change with adjustments in the test setup.
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +**Wi-Fi in 2.4GHz**
```suggestion
Wi-Fi in 2.4 GHz
================
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +*Separate antennas*
```suggestion
Separate antennas
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +
BLE is a banned abbreviation. Change it to Bluetooth LE in all tables.

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +*Shared antenna*
```suggestion
Shared antenna
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +**Wi-Fi in 5GHz**
```suggestion
Wi-Fi in 5 GHz
=============
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +*Separate antennas*
```suggestion
Separate antennas
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +*Shared antenna*
```suggestion
Shared antenna
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +Screenshots of coexistence test results obtained for separate antenna configuration with Wi-Fi mode set to 802.11n are given below. These tests are run when WLAN connected to an AP in 2.4GHz band. In
```suggestion
The following screenshots show coexistence test results obtained for separate antenna configuration with Wi-Fi mode set to 802.11n.
These tests were run with WLAN connected to an AP in 2.4 GHz band.
In the images, left-side result shows Wi-Fi throughput that appears on a test PC terminal in which Wi-Fi **iperf** server is run and right-side result shows Bluetooth LE throughput that appears on a minicom terminal in which the Bluetooth LE throughput sample is run.
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +     Wi-Fi only throughput 10.2Mbps
```suggestion
     Wi-Fi only throughput 10.2 Mbps
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +     BLE only throughput: 1107kbps
```suggestion
     Bluetooth LE only throughput: 1107 kbps
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +     Wi-Fi and BLE throughput, coexistence disabled: Wi-Fi 9.9Mbps and BLE 145kbps
```suggestion
     Wi-Fi and Bluetooth LE throughput, coexistence disabled: Wi-Fi 9.9 Mbps and BLE 145 kbps
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +     Wi-Fi and BLE throughput, coexistence enabled: Wi-Fi 8.3Mbps and BLE 478kbps
```suggestion
     Wi-Fi and Bluetooth LE throughput, coexistence enabled: Wi-Fi 8.3 Mbps and Bluetooth LE 478 kbps
```

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +
Remove extra empty lines. One is enough.

2023-01-11 13:51 UTC, peknis commented on samples/wifi/sr_coex/README.rst
> +.. _Network Traffic Generator: Network Traffic Generator — Zephyr Project Documentation
Instead of introducing the link targets here, insert them in doc/nrf/links.txt

2023-01-12 11:46 UTC, umapraseeda requested changes

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +| nRF7002 DK   | coex sample    | The sample runs Wi-Fi throughputs, Bluetooth LE throughputs                  |
Bluetooth LE coexistence sample

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +|                        | throughput in Mbps | throughputin kbps |
```suggestion
|                        | throughput in Mbps | throughput in kbps |
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +|                        | throughput in Mbps | throughputin kbps |
```suggestion
|                        | throughput in Mbps | throughput in kbps |
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +|                        | throughput in Mbps | throughputin kbps |
```suggestion
|                        | throughput in Mbps | throughput in kbps |
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +|                        | throughput in Mbps | throughputin kbps |
```suggestion
|                        | throughput in Mbps | throughput in kbps |
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +  For the concurrent Wi-Fi and Bluetooth LE test, make sure that both of these are set to the same duration to ensure maximum overlap.
```suggestion
  For the concurrent Wi-Fi and Bluetooth LE test, make sure that both are set to the same duration to ensure maximum overlap.
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +After the DKs are connected to the test PC through USB connectors and powered on, open a suitable terminal and run the following command:
```suggestion
After the DKs are connected to the test PC through USB connectors and powered on, open a suitable terminal, and run the following command:
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +=================================
Could be removed as the subheadings are there.

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +*****************
```suggestion
Connecting to DKs
=================
```

2023-01-12 11:46 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +***************
```suggestion
Programming DKs
===============
```

2023-01-13 15:13 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +  Based on the required test, set only one of these to ``y`.
```suggestion
  * :kconfig:option:`CONFIG_TEST_TYPE_WLAN_BLE` for concurrent Wi-Fi and Bluetooth LE test.

    Based on the required test, set only one of these to ``y`.
```

2023-01-13 15:13 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +The generated hex file to be used is :file:`build/zephyr/merged_domains.hex`.
```suggestion
The generated HEX file to be used is :file:`build/zephyr/merged_domains.hex`.
```

2023-01-13 16:40 UTC, krish2718 approved these changes

2023-01-14 18:01 UTC, bama-nordic requested changes

2023-01-14 18:11 UTC, bama-nordic requested changes

2023-01-14 18:11 UTC, bama-nordic commented on drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_coex.h
> + * @brief      Function used to configure SR side switch (nRF5340 side switch in nRF7002 DK).
Explain that this API configures the SR side antenna switch as per the selection of shared/separate antenna mentioning CONFIG_COEX_SEP_ANTENNAS symbol needs to be set appropriately.

2023-01-15 17:44 UTC, bama-nordic approved these changes
LGTM

2023-01-16 08:37 UTC, umapraseeda commented on samples/wifi/sr_coex/README.rst
> +
@richabp, FYI the images might need rework (as discussed offline) and might need to be moved into the common images folder.

2023-01-16 09:27 UTC, umapraseeda commented
Please add an entry in the changelog: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases/release-notes-changelog.html#wi-fi-samples

2023-01-16 13:31 UTC, sachinthegreen approved these changes

2023-01-16 15:12 UTC, umapraseeda approved these changes

2023-01-16 15:12 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
> +  * Sample demonstrating Wi-Fi Bluetooth LE coexistence
```suggestion
```

2023-01-16 15:12 UTC, umapraseeda commented on doc/nrf/releases/release-notes-changelog.rst
> +    * Wi-Fi Bluetooth LE coexistence sample
```suggestion
* Added:

  * :ref:`wifi_sr_coex_sample` sample demonstrating Wi-Fi Bluetooth LE coexistence.
 ```

2023-01-17 07:37 UTC, jciupis approved these changes

2023-01-17 07:37 UTC, jciupis commented on dts/bindings/radio_coex/nordic,nrf700x-coex.yaml
> +            coex case) of the nRF7002.
Please restore the empty line between properties.

2023-01-17 10:08 UTC, peknis approved these changes

2023-01-18 09:51 UTC, merged