Port QSPI power mangement fixes from flash driver
nrfconnect/sdk-nrf pull request #9779
Opened 2023-01-01 15:13 UTC by krish2718

* 95d867e8ed ("drivers/flash/nrf_qspi_nor: fix for missing device deactivation.")
  * da3ec7dbfa ("drivers: flash: Fix regression on nrf52840 anomaly 122 workaround")
  * 527315d451 ("drivers: flash: nrf_qspi_nor: Add support for device power management").
  * 65976137dc ("boards: nrf: Activate pull-up on QSPI CSN line in "sleep" state")

This is still WIP, but raising for early review esp. for @anangl, with this LMAC boot is failing as QSPI reads are wrong. Not sure if the model of init/deinit for every transaction over QSPI needs some support from RPU (nrf700x)?

2023-01-09 10:53 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9779/5/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9779/5/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9779/5/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-09 11:36 UTC, sachinthegreen approved these changes

2023-01-11 03:40 UTC, leewkb4567 requested changes

2023-01-11 03:40 UTC, leewkb4567 commented on drivers/wifi/nrf700x/zephyr/src/qspi/src/qspi_if.c
> +	return qspi_freq_to_sckfreq(INST_0_SCK_FREQUENCY);
The function qspi_freq_to_sckfreq() processes an input in MHz unit. Nevertheless, INST_0_SCK_FREQUENCY is specified in Hz. Therefore, a 24MHz in DTS will become 6MHz in this function...

2023-01-11 03:40 UTC, leewkb4567 commented on drivers/wifi/nrf700x/zephyr/src/qspi/src/qspi_if.c
> +		return NRF_QSPI_FREQ_DIV1;
This function input is given in MHz unit. Yet the macro NRF_QSPI_BASE_CLOCK_FREQ is specified in Hz.

2023-01-12 05:35 UTC, sr1dh48r approved these changes

2023-01-12 08:21 UTC, krish2718 commented
I have tested this using PPK connected to 5340 and seeing about 2mA current consumption and also seeing that nrf7002 is able to wakeup the host from suspend and then nrf5340 is able to process and send ICMP replies.

2023-01-12 09:11 UTC, leewkb4567 commented on drivers/wifi/nrf700x/zephyr/src/qspi/src/qspi_if.c
> +	/* DTS freqyency is in HZ */
```suggestion
	/* DTS frequency is in HZ */
```

2023-01-12 09:12 UTC, leewkb4567 commented on drivers/wifi/nrf700x/zephyr/src/qspi/src/qspi_if.c
> +int qspi_device_init(const struct device *dev)
```suggestion
static int qspi_device_init(const struct device *dev)
```

2023-01-12 09:12 UTC, leewkb4567 commented on drivers/wifi/nrf700x/zephyr/src/qspi/src/qspi_if.c
> +void qspi_device_uninit(const struct device *dev)
```suggestion
static void qspi_device_uninit(const struct device *dev)
```

2023-01-16 07:25 UTC, krish2718 commented
> Please address the 3 comments.
> 
> Unfortunately, committing in GitHub won't pass the CI checks. It takes modifying the last commit.

It does work, I commit in to github, then fetch + rebase, but as I am using two laptops, so, might have accidentally overwritten the changes.

2023-01-16 07:58 UTC, leewkb4567 approved these changes

2023-01-16 08:45 UTC, leewkb4567 commented
> It does work, I commit in to github, then fetch + rebase, but as I am using two laptops, so, might have accidentally overwritten the changes.

I saw a commit done in GitHub did not have a description for CI checks. Anyway, it is good now.

2023-01-16 11:48 UTC, merged