net: lib: nrf_cloud: remove P-GPS prediction period configuration
nrfconnect/sdk-nrf pull request #9806
Opened 2023-01-04 11:22 UTC by tokangas

This PR proposes to remove the P-GPS Kconfig option `CONFIG_NRF_CLOUD_PGPS_PREDICTION_PERIOD`. I haven't paid much attention to this before, but now that I started looking into it, I'm not sure what the purpose of this configuration is.

The range for this option is 60 - 480 minutes and the default is 240 minutes. 4 hours makes sense, because each ephemeris/prediction is valid for 4 hours.

I tried different values and 60 minutes and 480 minutes don't look too good. When the option is set to 60 minutes, the cloud still sends predictions with 240 min period and download is aborted by the P-GPS library because of this mismatch. When the option is set to 480 minutes, at least the first received ephes are exactly the same as with 240 minutes, so the ephes are not valid for a longer time. Because of this, the ephemerides just expire at the end of the 240 min period and no new ephes are injected by the library for another four hours. I'm also not sure whether our GNSS implementation would handle ephes with a longer fit interval properly anyway. The ephes received from GPS satellite broadcast have always 4 hour fit interval.

120 minutes could make some sense and it looks like it works properly. Using only the middle two hours of each ephemeris would in theory improve accuracy. However, the ephemerides are anyway predictions, so most likely any theoretical improvement in accuracy is lost in accumulated errors due to predicting the satellite location in the future.

@plskeggs, do you know a good reason why this configuration is needed? To me it looks like we should just always stick to the 4 hour period.

2023-01-04 11:55 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9806
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-04 11:58 UTC, peknis requested changes

2023-01-04 11:58 UTC, peknis commented on doc/nrf/libraries/networking/nrf_cloud_pgps.rst
> +   Each prediction requires 2 kB of flash. With 42 predictions per week, the flash requirement adds up to 84 kB.
```suggestion
   Each prediction requires 2 kB of flash.
   With 42 predictions in a week, the flash requirement adds up to 84 kB.
```

2023-01-04 11:58 UTC, peknis commented on subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_pgps
> +	  will cover. The default values allows for one week of predictions.
```suggestion
	  will cover. The default values allow for one week of predictions.
```

2023-01-04 12:46 UTC, peknis approved these changes

2023-01-04 17:57 UTC, plskeggs commented
@tokangas -- I don't recall now why I set the range as low as 60 or as high as 480, but the idea was to cover at a minimum 120 and 240 as choices, since HERE provides predictions to the nRF Cloud backend in 120 minute intervals.  The default 240 is actually skipping every other prediction they give us.

At the time I implemented this, it wasn't clear whether allowing 120 minute intervals (at the expense of 2X the flash requirements) would benefit some use cases or not.

I suggest before removing this feature, your team could consider testing accuracy of 120 vs. 240 a week or 2 weeks and see if 120 provides any benefit at all.

2023-01-05 06:35 UTC, tokangas commented
> @tokangas -- I don't recall now why I set the range as low as 60 or as high as 480, but the idea was to cover at a minimum 120 and 240 as choices, since HERE provides predictions to the nRF Cloud backend in 120 minute intervals. The default 240 is actually skipping every other prediction they give us.

Ok, that's how I though it works as well.

> I suggest before removing this feature, your team could consider testing accuracy of 120 vs. 240 a week or 2 weeks and see if 120 provides any benefit at all.
> 
> At a minimum, changing this to be fixed values of 120 vs. 240 would be ok with me.

Yes, at least the configuration should be changed so that only 120 and 240 min periods can be selected. I'll see if we could do a test run with two devices, one using 120 min and one using 240 min period.

2023-01-05 13:51 UTC, hiltunent approved these changes

2023-01-18 12:09 UTC, tokangas commented
A one week test with both 120 min and 240 min prediction period shows marginal improvement in accuracy and time to fix with 120 min period. Not all CEPs were better, but because 120 min period may improve the performance slightly, maybe we should keep the option.

I'll change the implementation so, that it's possible to choose between 120 min and 240 min prediction periods.

2023-01-19 10:41 UTC, tokangas commented
@plskeggs @peknis @hiltunent Reworked the PR so, that instead of removing the prediction period configuration it's now possible to choose between the two values which are usable, 240 minutes and 120 minutes. Please review.

2023-01-19 10:48 UTC, peknis approved these changes

2023-01-20 07:31 UTC, hiltunent approved these changes

2023-01-23 10:51 UTC, tokangas commented on doc/nrf/libraries/networking/nrf_cloud_pgps.rst
> +* :kconfig:option:`CONFIG_NRF_CLOUD_PGPS_PREDICTION_PERIOD_120_MIN`
Thanks, good point. It's updated now.

2023-01-23 11:02 UTC, trantanen approved these changes

2023-01-24 18:52 UTC, plskeggs approved these changes
LGTM.  Thanks for doing this.

2023-01-25 07:42 UTC, merged