doc: Minor updates to the introduction page
nrfconnect/sdk-nrf pull request #9809
Opened 2023-01-04 11:26 UTC by umapraseeda

Minor updates to the introduction page

Signed-off-by: UMA PRASEEDA <uma.praseeda@nordicsemi.no>

2023-01-04 11:58 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9809
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-05 12:39 UTC, peknis requested changes

2023-01-05 12:39 UTC, peknis commented on doc/nrf/introduction.rst
> +     The `sdk-zephyr`_ repository is a :term:`soft fork` that Nordic maintains and it is not the same as Zephyr SDK, which is a set of :ref:`installation tools <gs_installing_toolchain>` used while i
```suggestion
     The `sdk-zephyr`_ repository is a :term:`soft fork` that Nordic Semiconductor maintains.
     It is not the same as Zephyr SDK, which is a set of :ref:`installation tools <gs_installing_toolchain>` used while installing the |NCS|.
```

2023-01-05 12:39 UTC, peknis commented on doc/nrf/introduction.rst
> +All the repositories that are named ``sdk-<repository>`` contain the |NCS| firmware and code.
```suggestion
All repositories with the prefix ``sdk`` contain the |NCS| firmware and code.
```

2023-01-09 07:47 UTC, peknis approved these changes

2023-01-09 11:24 UTC, carlescufi approved these changes

2023-01-09 11:24 UTC, merged