manifest: update homekit revision
nrfconnect/sdk-nrf pull request #9822
Opened 2023-01-05 08:00 UTC by mariuszpos

nrfconnect/sdk-homekit#452

Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>

2023-01-05 08:01 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| homekit | [nrfconnect/sdk-homekit@v2.2.0](https://github.com/nrfconnect/sdk-homekit/releases/tag/v2.2.0) | https://github.com/nrfconnect/sdk-homekit/pull/452 | [nrfconnect/sdk-homekit#452/files](https://github.com/nrfconnect/sdk-homekit/pull/452/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-01-05 08:02 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9822/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9822/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-homekit | X | | |

**test-sdk-homekit:** added because there was no .github/test-spec.yml in 'homekit'

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9822/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-05 08:41 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9822
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-09 08:11 UTC, sachinthegreen approved these changes

2023-01-09 08:17 UTC, kkasperczyk-no commented
@mariuszpos thanks for contributing and aligning the other samples as well. Could you describe a little bit what are the changes introduced by this PR? Looking at the code I guess now some hooks are available in the MCUMGR library, so we should be able to better handle DFU process in our applications. From the Matter perspective please be aware that there are many other samples apart from weather station that may optionally use DFU over SMP, so we should align them as well. I think the best option would be to add `select` for this new mcumgr configs here: https://github.com/nrfconnect/sdk-connectedhomeip/blob/master/config/nrfconnect/chip-module/Kconfig.features#L76. Would you mind adding such change or someone from our team should assist you?

2023-01-09 08:55 UTC, krish2718 approved these changes
For `drivers/wifi/nrf700x/zephyr/src/qspi/src/spi_if.c`

2023-01-09 10:38 UTC, kkasperczyk-no commented
@mariuszpos sorry I didn't realize it is not your commit, but you just included upmerge commits :) Please ignore my previous comment.

2023-01-09 10:43 UTC, rakons approved these changes

2023-01-10 08:28 UTC, alxelax requested changes

2023-01-10 08:28 UTC, alxelax commented on samples/bluetooth/mesh/chat/prj.conf
> -CONFIG_BT_MESH_DEBUG_MODEL=y
What is the reason for disabling model debugging here but leaving mesh stack debugging?  App demonstrates vendor model implementation.

2023-01-10 08:54 UTC, alxelax reviewed
I see this came from upmere PR. I'll redirect my questions there.

2023-01-10 08:56 UTC, alxelax approved these changes

2023-01-11 06:39 UTC, mariuszpos commented
This PR is no longer required because the homekit revision update has been added to the PR: https://github.com/nrfconnect/sdk-nrf/pull/9669

2023-01-11 06:39 UTC, closed without merging