Cmd ps mode
nrfconnect/sdk-nrf pull request #9846
Opened 2023-01-06 14:06 UTC by ajayparida

2023-01-06 14:08 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9846/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9846/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9846/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-09 07:58 UTC, sachinthegreen requested changes
Please add a description for the PR.

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
>  	} else {
Indentation is off.

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +					       WIFI_PS_MODE_LEGACY_UAPSD_QUEUES);
Indentation is off.

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +	get_ps_cfg = wifi_nrf_osal_mem_zalloc(fmac_dev_ctx->fpriv->opriv,
Is this supposed to be get_ps_cfg**_cmd** ?  If yes how did this compile?

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +					      sizeof(*get_ps_cfg));
Is this supposed to be get_ps_cfg**_cmd** ?

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +	if (!get_ps_cfg) {
Is this supposed to be get_ps_cfg**_cmd** ?

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +				      "%s: Unable to allocate memory\n", __func__);
Generic comment: Please put each parameter on a separate line (i.e. in this case __func__ can be moved to the next line).

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +	if (!dev || !params) {
params ??

2023-01-09 07:58 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +	if (!dev || !params) {
params??

2023-01-11 08:00 UTC, krish2718 requested changes

2023-01-11 08:00 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/inc/zephyr_ps.h
> +	WIFI_PS_MODE_WMM_UAPSD_QUEUES = 0xF,
These should be defined in FMAC header file.

2023-01-11 08:00 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +		status = wifi_nrf_fmac_set_uapsd_queue(rpu_ctx_zep->rpu_ctx,
Though not in this commit, API looks tied to Linux style, can we use LEGACY/WMM and internally to UMAC use uapsd_queues? If its too much rework then ignore.

2023-01-11 08:00 UTC, krish2718 commented
You also need to squash the commits.

2023-01-12 05:32 UTC, sr1dh48r approved these changes

2023-01-12 08:27 UTC, krish2718 approved these changes

2023-01-12 11:26 UTC, ajayparida commented
> Please add a description for the PR.

Description aded

2023-01-13 12:18 UTC, sachinthegreen approved these changes

2023-01-13 12:33 UTC, merged