wifi : Bugfix for RRM request handling
nrfconnect/sdk-nrf pull request #9851
Opened 2023-01-09 10:06 UTC by sr1dh48r

SHEL-877: DUT did not respond to AP beacon request frame 
Enable misisng RRM capability in Assoc request.
Update clock to fix BSS expiration issue.

Signed-off-by: Sridhar Nuvusetty <sridhar.nuvusetty@nordicsemi.no>

2023-01-09 10:07 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/c1f1e0593d5bde73ba5d512b44fb765472829574 (main) | https://github.com/nrfconnect/sdk-hostap/pull/50 | [nrfconnect/sdk-hostap#50/files](https://github.com/nrfconnect/sdk-hostap/pull/50/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-01-09 10:12 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9851/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9851/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9851/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-09 10:15 UTC, krish2718 commented on samples/wifi/shell/src/wifi_main.c
> +	clock_settime(CLOCK_REALTIME, &tspec);
This looks like a hack, any specific reason? I am debugging a similar bug related to BSS flush from Matter, is it the same?

2023-01-09 10:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9851
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-09 19:52 UTC, krish2718 commented on samples/wifi/shell/src/wifi_main.c
> +	clock_settime(CLOCK_REALTIME, &tspec);
I have root cause and raised https://github.com/nrfconnect/sdk-hostap/pull/53 with proper fix (added your SOB too).

2023-01-10 13:05 UTC, tejlmand approved these changes
lgtm

2023-01-11 09:17 UTC, sachinthegreen approved these changes

2023-01-11 09:26 UTC, krish2718 requested changes
Based on above comments, we need to rebase this to include the BSS age fix.

2023-02-15 15:11 UTC, krish2718 approved these changes

2023-02-23 08:18 UTC, merged