Sta sample improvements
nrfconnect/sdk-nrf pull request #9852
Opened 2023-01-09 12:09 UTC by krish2718

* Keep trying connection in case of any failures
  * Add support for LED0 blinking when connected, this is tied to WPA
  supplicant events
  * Handle duplicate events and sanity checks
  * Update documentation

2023-01-09 12:09 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/c1f1e0593d5bde73ba5d512b44fb765472829574 (main) | https://github.com/nrfconnect/sdk-hostap/pull/51 | [nrfconnect/sdk-hostap#51/files](https://github.com/nrfconnect/sdk-hostap/pull/51/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-01-09 12:16 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9852/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9852/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9852/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-09 14:18 UTC, sachinthegreen approved these changes

2023-01-09 19:22 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9852
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-10 13:34 UTC, D-Triveni commented on samples/wifi/sta/src/main.c
Do we still need this semaphore?

2023-01-11 05:29 UTC, D-Triveni approved these changes

2023-01-11 08:58 UTC, richabp requested changes

2023-01-13 01:10 UTC, richabp requested changes

2023-01-13 01:10 UTC, richabp commented on samples/wifi/sta/README.rst
> +    * **LED1** stops blinking when the sample is disconnected from the access point
```suggestion
    * **LED1** starts blinking when the sample is connected to the access point.
    * **LED1** stops blinking when the sample is disconnected from the access point.
```

2023-01-13 11:20 UTC, bama-nordic requested changes

2023-01-13 11:20 UTC, bama-nordic commented on samples/wifi/sta/prj.conf
> +CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.0.99"
Please explain static v/s DHCP IP addressing behaviour for users

2023-01-13 13:57 UTC, bama-nordic approved these changes

2023-01-16 05:00 UTC, sr1dh48r approved these changes

2023-01-16 11:16 UTC, richabp requested changes

2023-01-16 11:16 UTC, richabp commented on samples/wifi/sta/README.rst
> +the default static IP configuration.
```suggestion
The sample uses DHCP to obtain an IP address for the Wi-Fi interface.
It starts with a default static IP address to handle networks without DHCP servers, or if the DHCP server is not available.
Successful DHCP handshake will override the default static IP configuration.
```

2023-01-16 11:16 UTC, richabp commented on samples/wifi/sta/README.rst
> +The default static configuration is below and can be changed in the ``prj.conf`` file:
```suggestion
The following static configuration is by default and can be changed in the :file:`prj.conf` file:
```

2023-01-16 12:51 UTC, richabp approved these changes

2023-01-16 13:41 UTC, nordicjm commented
@krish2718 needs rebase

2023-01-16 16:47 UTC, merged