Mac addr provisioning from host
nrfconnect/sdk-nrf pull request #9854
Opened 2023-01-09 13:04 UTC by sachinthegreen

[SHEL 1102]: Provision for MAC address configuration from host.

2023-01-09 13:04 UTC, NordicBuilder commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| sdk-hostap | https://github.com/nrfconnect/sdk-hostap/commit/c1f1e0593d5bde73ba5d512b44fb765472829574 (main) | https://github.com/nrfconnect/sdk-hostap/pull/52 | [nrfconnect/sdk-hostap#52/files](https://github.com/nrfconnect/sdk-hostap/pull/52/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-01-09 13:39 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9854
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-11 09:21 UTC, krish2718 requested changes
MAC address configuration through shell is still not working, debugging in progress.

2023-01-11 09:34 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +				LOG_WRN("%s:  Invalid OTP MAC0 addr: %02X%02X%02X%02X%02X%02X\n",
This check has now moved to fmac_api.c...so can't use zephyr APIs.

2023-01-12 05:30 UTC, sr1dh48r approved these changes

2023-01-12 12:35 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +	status = wifi_nrf_fmac_chg_vif_state(rpu_ctx_zep->rpu_ctx,
This is not needed as discovered during testing.

2023-01-13 16:33 UTC, krish2718 approved these changes

2023-01-16 09:09 UTC, bama-nordic approved these changes

2023-01-16 14:16 UTC, merged