doc: known_issues: add NCSDK-18746
nrfconnect/sdk-nrf pull request #9866
Opened 2023-01-10 12:37 UTC by nordic-hani

Added a known issue (and workaround) for the LwM2M carrier library. This corner case can cause the start-up sequence to fail under certain conditions.

Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>

2023-01-10 12:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9866/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9866/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-01-10 13:18 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9866
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-10 13:19 UTC, kacperradoszewski commented on doc/nrf/known_issues.rst
> +  The LwM2M carrier library will attempt to retreive a PSK from :kconfig:option:`LWM2M_CARRIER_SERVER_SEC_TAG` even though a PSK should not be needed for the non-secure bootstrap.
typo `retrieve`

2023-01-10 13:19 UTC, kacperradoszewski commented on doc/nrf/known_issues.rst
> +  The PSK in this sec_tag is (corectly) not used, but reading the sec_tag causes the bootstrap to fail if the :kconfig:option:`LWM2M_CARRIER_SERVER_SEC_TAG` is default (0).
typo `correctly`

2023-01-10 14:10 UTC, umapraseeda requested changes

2023-01-10 14:10 UTC, umapraseeda commented on doc/nrf/known_issues.rst
> +
```suggestion
NCSDK-18746: LwM2M carrier library fails to complete non-secure bootstrap when using a custom URI and the default security tag
  If the LwM2M carrier library is operating in generic mode (not connecting to any of the predefined supported carriers), and the :kconfig:option:`CONFIG_LWM2M_CARRIER_CUSTOM_URI` is set to connect to a non-secure server, the library attempts to retrieve a PSK from :kconfig:option:`CONFIG_LWM2M_CARRIER_SERVER_SEC_TAG` even though a PSK is not needed for the non-secure bootstrap.
  The PSK in this ``sec_tag`` is not used, but reading the ``sec_tag`` causes the bootstrap to fail if the :kconfig:option:`CONFIG_LWM2M_CARRIER_SERVER_SEC_TAG` is set to the default value (0).

  **Workaround:** Assign any non-zero value to :kconfig:option:`CONFIG_LWM2M_CARRIER_SERVER_SEC_TAG`.

```

2023-01-11 10:42 UTC, umapraseeda approved these changes

2023-01-11 11:54 UTC, kacperradoszewski approved these changes

2023-02-08 09:12 UTC, divipillai approved these changes

2023-02-08 15:15 UTC, merged