Mcast addr ops
nrfconnect/sdk-nrf pull request #9875
Opened 2023-01-11 07:40 UTC by ajayparida

2023-01-11 07:42 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9875/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9875/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9875/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-11 07:51 UTC, krish2718 requested changes

2023-01-11 07:51 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +	dev = net_if_get_device(iface);
Add a NULL check

2023-01-11 07:51 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +		LOG_ERR("%s: Unable to allocate memory for mcast_info\n", __func__);
print size

2023-01-11 07:51 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +	} else if ((mgmt_event == NET_EVENT_IPV6_MADDR_ADD) ||
There is lot of common code, we can refactor this

2023-01-11 07:51 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +	net_mgmt_add_event_callback(&ip_maddr6_del_cb);
You can add them in a single CB handler, by ORing the events 

```
net_mgmt_init_event_callback(&ip_madd_cbs,
                  ip_maddr_event_handler, 
                  NET_EVENT_IPV4_MADDR_ADD |  NET_EVENT_IPV4_MADDR_DEL | 
                   NET_EVENT_IPV6_MADDR_ADD | NET_EVENT_IPV6_MADDR_DEL);
```

2023-01-11 07:51 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +			LOG_ERR("%s: nrf_wifi_fmac_set_multicast failed\n", __func__);
log the MAC address as well

2023-01-11 09:30 UTC, sachinthegreen requested changes

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * wifi_nrf_fmac_set_multicast - set the multicast filter address.
Change multicast to mcast_addr.

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * @mcast_info: multicast information to be set
multicast should be Multicast

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * instruct the firmware to set the multicast filter address with an index of
`...with an index of` should be `....to an interface with index` ?

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> +enum wifi_nrf_status wifi_nrf_fmac_set_multicast(struct wifi_nrf_fmac_dev_ctx *fmac_dev_ctx,
Change multicast to mcast_addr

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +enum wifi_nrf_status wifi_nrf_fmac_set_multicast(struct wifi_nrf_fmac_dev_ctx *fmac_dev_ctx,
Change multicast to mcast_addr

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +				 unsigned char if_idx,
Indentation

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +	unsigned int len = sizeof(*set_mcast_cmd);
Why is extra variable len required...why not just use sizeof(*set_mcast_cmd) where needed?

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +				   uint32_t mgmt_event, struct net_if *iface)
Put each parameter on a separate line.

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +
Unintentional blank line?

2023-01-11 09:30 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +
Unintentional blank line?

2023-01-11 16:00 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
> +	net_mgmt_add_event_callback(&ip_maddr6_del_cb);
As discussed offline, the above won't work as we are trying to mix two layers of net_mgmt IPv4 andIPv6, the check in `mgmt_run_callbacks` fails, so, divide in to two handlers ipv4 and ipv6 and you can use multiple events.

2023-01-12 05:28 UTC, sr1dh48r approved these changes

2023-01-12 10:41 UTC, krish2718 requested changes
Please update RPU patch commit log with details, I did the same in my branch as below but couldn't find any reference to mcast in the log. This is the diff b/w 55 (MAIN) and 59.

```
    drivers: wifi: revB: Update RPU patch to #59
    
    Changelog:
    
     UMAC:
      - Add 802.11d regulatory beacon hints
      - API to configure power save inactivity timer
      - API to retrieve DTIM and beacon interval
      - Set random Nordic OUI MAC address for default VIF (host doesn't send
        this anymore in the init)
    
    Update the interface file as well, these new commands are not supported
    in RevA as that is deprecated.
    
    Fix the header file to use proper macro NRF_WIFI_ETH_ADDR_LEN.
```

2023-01-12 10:41 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> - *
unncessary change

2023-01-12 12:08 UTC, krish2718 commented
My PR https://github.com/nrfconnect/sdk-nrf/pull/9897 also bumps the RPU patch to 59 but with proper commit log, so, you can rebase once that is merged.

2023-01-13 16:34 UTC, krish2718 approved these changes

2023-01-13 16:50 UTC, sachinthegreen approved these changes

2023-01-16 08:09 UTC, merged