RF performance improvements
nrfconnect/sdk-nrf pull request #9883
Opened 2023-01-11 13:42 UTC by imapa

For both system and radio test, few RF improvements like TX power, reducing calibration times, adjust XO are being done.

2023-01-11 14:10 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9883/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9883/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9883/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-11 14:43 UTC, srkanordic approved these changes

2023-01-11 14:52 UTC, krish2718 approved these changes

2023-01-12 12:04 UTC, imapa commented
I enabled temperature based calibration which was missing in last push. Please review it.

2023-01-12 12:50 UTC, sachinthegreen requested changes

2023-01-12 12:50 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/hw_if/hal/inc/fw_B/phy_rf_params.h
> -
Why are these defines removed?

2023-01-13 10:19 UTC, closed without merging

2023-01-13 10:20 UTC, imapa commented
We can merge this later.