cmake: enable child-image builds without partition_manager
nrfconnect/sdk-nrf pull request #9901
Opened 2023-01-12 13:13 UTC by maxd-nordic

This patch allows building child images without having to use the partition manager.

Signed-off-by: Emil Obalski <emil.obalski@nordicsemi.no>
Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

NCSDK-18922

2023-01-12 13:16 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9901/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9901/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-ci-nrfconnect-boot-fw-update | X | | |
| test-fw-nrfconnect-apps | X | | |
| test-fw-nrfconnect-ble | X | | |
| test-fw-nrfconnect-ble_mesh | X | | |
| test-fw-nrfconnect-ble_samples | X | | |
| test-fw-nrfconnect-chip | X | | |
| test-fw-nrfconnect-fem | X | | |
| test-fw-nrfconnect-nfc | X | | |
| test-fw-nrfconnect-nrf-iot_cloud | X | | |
| test-fw-nrfconnect-nrf-iot_libmodem | X | | |
| test-fw-nrfconnect-nrf-iot_lwm2m | X | | |
| test-fw-nrfconnect-nrf-iot_mosh | X | | |
| test-fw-nrfconnect-nrf-iot_positioning | X | | |
| test-fw-nrfconnect-nrf-iot_samples | X | | |
| test-fw-nrfconnect-nrf-iot_thingy91 | X | | |
| test-fw-nrfconnect-nrf-iot_zephyr_lwm2m | X | | |
| test-fw-nrfconnect-nrf_crypto | X | | |
| test-fw-nrfconnect-proprietary_esb | X | | |
| test-fw-nrfconnect-rpc | X | | |
| test-fw-nrfconnect-rs | X | | |
| test-fw-nrfconnect-tfm | X | | |
| test-fw-nrfconnect-thread | X | | |
| test-fw-nrfconnect-zigbee | X | | |
| test-sdk-audio | X | | |
| test-sdk-find-my | X | | |
| test-sdk-homekit | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |

**All integration tests**: null

[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9901/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-12 13:50 UTC, emob-nordic approved these changes

2023-01-12 19:59 UTC, hakonfam approved these changes

2023-01-16 11:07 UTC, alwa-nordic approved these changes

2023-01-19 08:11 UTC, joan-nordic approved these changes

2023-01-19 08:47 UTC, tejlmand requested changes
One thing is to allow child images to disable partition manager, another thing is when this should be considered allowed.

At this point I require use-cases in NCS as when exactly it should be allowed to disable partition-manager.
Feel free to take this discussion offline.

2023-01-19 08:47 UTC, tejlmand commented on cmake/multi_image.cmake
> +  if (CONFIG_PARTITION_MANAGER_ENABLED)
how do this work with where there are multiple levels of "parents" ?

That is where a child-image is including extra child images, such as Bluetooth sample on nRF5340 which includes hci_rpmsg, which will then act as an extra parent for secure boot (b0n).

2023-01-25 09:49 UTC, closed without merging