doc: nrf: mention MMSS sample as alternative to ATv2
nrfconnect/sdk-nrf pull request #9904
Opened 2023-01-12 22:29 UTC by jayteemo

In the getting started guide for the DK and T91,
mention the nRF Cloud MQTT multi-service sample
as an alternative to ATv2.
NCSDK-18118

Signed-off-by: Justin Morton <justin.morton@nordicsemi.no>

2023-01-12 23:23 UTC, plskeggs approved these changes
LGTM

2023-01-13 20:59 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9904/2/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9904/2/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-01-16 09:37 UTC, peknis requested changes

2023-01-16 09:37 UTC, peknis commented on doc/nrf/ug_nrf9160_gs.rst
> +  See :ref:`gs_programming` for information about how to build a firmware sample application.
```suggestion
  See :ref:`gs_programming` for details on building a firmware sample application.
```

2023-01-16 09:37 UTC, peknis commented on doc/nrf/ug_thingy91_gsg.rst
> +See :ref:`gs_programming` for information about how to build a firmware sample application.
```suggestion
See :ref:`gs_programming` for details on building a firmware sample application.
```

2023-01-17 02:42 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9904
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-17 06:31 UTC, peknis approved these changes

2023-01-17 08:18 UTC, merged