doc: Add known issue about compilation error in SPM build
nrfconnect/sdk-nrf pull request #9909
Opened 2023-01-13 10:32 UTC by joerchan

Add known issue about compilation error when building SPM.

zephyr/drivers/timer/cortex_m_systick.c:265:6:
error: redefinition of 'sys_clock_disable'
  265 | void sys_clock_disable(void)
      |      ^~~~~~~~~~~~~~~~~
zephyr/drivers/timer/cortex_m_systick.c:7:
zephyr/drivers/timer/system_timer.h:123:20:
note: previous definition of 'sys_clock_disable' with type 'void(void)'
  123 | static inline void sys_clock_disable(void) {}
      |                    ^~~~~~~~~~~~~~~~~

NCSDK-19156

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

2023-01-13 10:34 UTC, SebastianBoe approved these changes

2023-01-13 10:39 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9909/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9909/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-01-13 12:57 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9909
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-13 14:01 UTC, mia-ko requested changes

2023-01-13 14:01 UTC, mia-ko commented on doc/nrf/known_issues.rst
> +    .. code-block::
Make sure to double-check the alignments.
It looks like the code block is not properly aligned, and you can see it in the doc build.

2023-01-16 07:15 UTC, mia-ko approved these changes

2023-01-16 10:20 UTC, merged