applications: nrf5340_audio: Set encryption bool for big_create
nrfconnect/sdk-nrf pull request #9915
Opened 2023-01-13 14:17 UTC by alexsven

- Set uninitialized member to default false

Signed-off-by: Alexander Svensen <alexander.svensen@nordicsemi.no>

2023-01-13 14:19 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9915/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9915/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-sdk-audio | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9915/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-13 14:40 UTC, rick1082 approved these changes

2023-01-16 08:34 UTC, koffes approved these changes

2023-01-16 09:16 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9915
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-16 11:24 UTC, greg-fer requested changes

2023-01-16 11:24 UTC, greg-fer commented on applications/nrf5340_audio/src/bluetooth/Kconfig
>  	  Encrypt the broadcast to limit the connectability
```suggestion
	  Encrypt the broadcast to limit the connection possibilities.
```
"Connectability" is not present in any dictionary. Use proposed or "connectivity".

2023-01-16 16:11 UTC, gWacey approved these changes

2023-01-17 09:49 UTC, greg-fer approved these changes

2023-01-17 10:59 UTC, merged