doc: release-notes: Document changes to manifest entries
nrfconnect/sdk-nrf pull request #9918
Opened 2023-01-13 15:29 UTC by joerchan

Document the changes to the manifest entries.
Removed zephyr fork of mbedtls and move NCS fork of mbedtls to the same location and using same name.
Removed tfm-mcuboot.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

2023-01-13 15:30 UTC, carlescufi approved these changes

2023-01-13 15:31 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9918/1/)
- Skipped

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9918/1/)
- Skipped



*Note: This message is automatically posted and updated by the CI*

2023-01-13 16:09 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9918
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-13 22:36 UTC, mbolivar-nordic requested changes

2023-01-13 22:36 UTC, mbolivar-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * manifest file entry ``mbedtls`` (ZEPHYR_MBEDTLS_MODULE_DIR) checked out at path file:`modules/crypto/mbedtls` now points to NCS' fork of MBedTLS instead of zephyr's fork.
1. same issues as comment a few lines up
2. NCS's

2023-01-13 22:36 UTC, mbolivar-nordic commented on doc/nrf/releases/release-notes-changelog.rst
> +  * manifest file entry ``tfm-mcuboot`` (ZEPHYR_TFM_MCUBOOT_MODULE_DIR) checked out at path file:`modules/tee/tfm-mcuboot`.
1. Use

```
:file:`foo`
```

not

```
file:`foo`
```

2. Use

```
:makevar:`ZEPHYR_FOO_MODULE_DIR`
```

not

```
ZEPHYR_FOO_MODULE_DIR
```

2023-01-17 14:00 UTC, umapraseeda approved these changes

2023-01-17 17:06 UTC, mbolivar-nordic approved these changes

2023-01-17 17:06 UTC, merged