caf: Clean up sensor manager files
nrfconnect/sdk-nrf pull request #9932
Opened 2023-01-16 13:45 UTC by emob-nordic

Reorganize configuration files and move common declarations to a common file.

This is required for NCSDK-17492.

2023-01-16 13:48 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9932/1/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9932/1/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| desktop52_verification | X | | |
| test-fw-nrfconnect-apps | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9932/1/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-01-16 13:48 UTC, annwoj approved these changes

2023-01-16 14:43 UTC, zycz approved these changes

2023-01-17 09:46 UTC, NordicBuilder commented
You can find the documentation preview for this PR at this <a href='http://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-9932
'>link</a>. It will be updated about 10 minutes after the documentation build succeeds.

*Note: This comment is automatically posted by the Documentation Publishing GitHub Action.*

2023-01-17 10:09 UTC, rakons requested changes
General note - keep some namespace. In c, we use prefixes as a replacement of non-existing namespaces. The variable name like sampled_channel with global scope seems a risky implementation. As it would serve for both "sensor manager" and "sensor sampler" we agreed offline to caf_ prefix.

2023-01-17 10:55 UTC, nvlsianpu requested changes
I'm agree wit @rakons comments regard prefixes.
Otherwise LGTM

2023-01-17 12:13 UTC, emob-nordic commented
@rakons  @nvlsianpu  suggestion applied. I've found more stuff that could be cleaned up and did that too. Please revisit, it has more changes now.
@b-gent I updated doxygen group as we discussed offline, please have a look.

2023-01-17 12:19 UTC, rakons approved these changes

2023-01-17 13:50 UTC, pdunaj approved these changes

2023-01-18 12:43 UTC, merged