drivers: wifi: support for enabling passive scan.
nrfconnect/sdk-nrf pull request #9982
Opened 2023-01-19 10:50 UTC by ajayparida

[SHEL-822] Utility command to do passive scan.

2023-01-31 12:40 UTC, sachinthegreen requested changes

2023-01-31 12:40 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
> +	if ((val < 0) || (val > 1)) {
val < 0 check is probably not needed since it is a unsigned variable

2023-02-01 08:16 UTC, krish2718 requested changes
Commit logs nits:

* Remove full stop at the end
* Capitalise `support`
* `enabling` is not imperative
* `Add support for passive scan` might be better?

2023-02-01 08:16 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
> +	bool passive_scan;
This should be in VIF context to support multiple VIFs.

2023-02-08 09:48 UTC, krish2718 approved these changes

2023-02-08 15:02 UTC, sachinthegreen approved these changes

2023-02-09 09:44 UTC, merged