sample: tfm_psa_template add immediate log out configuration
nrfconnect/sdk-nrf pull request #9985
Opened 2023-01-19 12:05 UTC by mswarowsky

Changed the logging mode for the twister test build to be synchronous This should result in a cleaner log output for testing.

Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

2023-01-19 13:20 UTC, torsteingrindvik approved these changes

2023-01-19 13:35 UTC, SebastianBoe commented on samples/tfm/tfm_psa_template/sample.yaml
> +      - CONFIG_LOG_MODE_IMMEDIATE=y
This option can affect race conditions, if we put this in the prj.conf then we are more likely to get the same result in CI and when building with west locally.

I can't see any reason to not put it in prj.conf. The performance of the non-secure app doesn't matter for this sample.

2023-01-19 13:36 UTC, SebastianBoe requested changes
changes requested

2023-01-20 09:12 UTC, SebastianBoe approved these changes

2023-01-20 15:19 UTC, merged