drivers: wifi: Get all current power save information
nrfconnect/sdk-nrf pull request #9992
Opened 2023-01-19 13:52 UTC by ajayparida

[SHEL-1156] Support to get all power save information.

Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>

2023-01-19 13:56 UTC, krish2718 requested changes

2023-01-19 13:56 UTC, krish2718 commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
> +	fmac_dev_ctx = dev_ctx;
check for STA mode.

2023-01-19 13:56 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +void wifi_nrf_event_proc_get_power_save_info(void *vif_ctx,
does this warrant a separate file?

2023-01-19 13:56 UTC, krish2718 commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +	vif_ctx_zep->ps_info = ps_config;
This is racy, please do this before sending the event.

2023-02-02 09:08 UTC, sachinthegreen requested changes

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
> + * wifi_nrf_fmac_get_power_save_info() - Get the cuttent power save info.
current*

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_cmd.h
> +#define WIFI_NRF_FMAC_PS_CONFIG_EVENT_RECV_TIMEOUT 50 /* ms */
Try to shorten maro names where possible...in this case you could use CONF instead of CONFIG and EVNT instead of EVENT.

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
> +	int iftype;
if_type

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/inc/zephyr_ps.h
> +			unsigned int event_len);
Alignment

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +			unsigned int event_len)
Alignment

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +	/*vif_ctx_zep->ps_info->twt_responder = ps_info->twt_responder;*/
Remove unused code.

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
> +		sizeof(struct wifi_twt_flow_info));
Alignment

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +		LOG_ERR("%s: Operation not supported\n", __func__);
Make it a more informative message e.g. Operation supported only in STA mode.

2023-02-02 09:08 UTC, sachinthegreen commented on drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
> +		LOG_ERR("%s: wifi_nrf_fmac_ failed\n", __func__);
Function name incomplete?

2023-02-07 11:27 UTC, NordicBuilder commented
## Test specification

### [CI/Jenkins/NRF](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9992/3/)
- Integration Platforms

### [CI/Jenkins/integration](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9992/3/)
| Test Module | File based changes | Manually selected | West overwrite |
| ----------- | :----------------: | :---------------: | :------------: |
| test-fw-nrfconnect-chip | X | | |
| test-sdk-wifi | X | | |
| test-sdk-wifi-radio | X | | |
| test-sdk-wifi-scan | X | | |
| test-sdk-wifi-sta | X | | |


[Detailed information of selected test modules](https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/PR-9992/3/artifact/test-spec/test-spec-summary.yml/*view*/)

*Note: This message is automatically posted and updated by the CI*

2023-02-08 09:49 UTC, krish2718 approved these changes

2023-02-08 15:02 UTC, sachinthegreen approved these changes

2023-02-09 08:15 UTC, rlubos approved these changes

2023-02-09 08:15 UTC, merged